### ISSUE TITLE
Fresh sync of network 1 mainnet stuck at Stage 11

### ISSUE THREAD

**Issue by srvint** [ledgerwatch/erigon#10035]
#### System information

Erigon version: 2.58.1 & 2.59.3 (same result)

OS & Version: Ubuntu

Erigon Command (with flags/config): ./erigon --datadir /mnt/raid0/data/erigon/ --networkid 1 --chain mainnet --torrent.download.rate 32mb --log.dir.path /mnt/raid0/logs/erigon-2.59.3/ --port=30303 --http.port=8545 --authrpc.port=9551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon

Chain/Network: Ethereum Mainnet 1

#### Expected behaviour
- Fresh sync to complete from step 1 to step 12

#### Actual behaviour
- After completing step 10, step 11 does not start

#### Steps to reproduce the behaviour
Install erigon 2.58.1 and start a new sync of network1 mainnet

#### Backtrace
INFO[04-23|09:36:10.384] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=c9c4d9ec
INFO[04-23|09:36:40.385] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=d1d2eb1b
INFO[04-23|09:37:10.387] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=d850942e
INFO[04-23|09:37:40.392] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=e41d2489
INFO[04-23|09:38:10.387] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=f3114dd5
INFO[04-23|09:38:40.388] [10/12 LogIndex] ETL [2/2] Loading       into=LogAddressIndex current_prefix=fa85069e
INFO[04-23|09:38:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:38:47.692] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=4.3GB sys=17.0GB
INFO[04-23|09:38:55.183] [10/12 LogIndex] DONE                    in=4h14m30.839689201s
INFO[04-23|09:38:55.187] [snapshots] Prune Blocks                 to=18909000 limit=100
INFO[04-23|09:41:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:41:47.682] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.2GB sys=17.0GB
INFO[04-23|09:44:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:44:47.672] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.5GB sys=17.0GB
INFO[04-23|09:47:47.669] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:47:47.673] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.2GB sys=17.0GB
INFO[04-23|09:50:47.669] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:50:47.692] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.5GB sys=17.0GB
INFO[04-23|09:53:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:53:47.672] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.2GB sys=17.0GB
INFO[04-23|09:56:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:56:47.673] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.5GB sys=17.0GB
INFO[04-23|09:59:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
INFO[04-23|09:59:47.672] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.2GB sys=17.0GB
INFO[04-23|10:02:47.668] [p2p] GoodPeers                          eth68=33 eth67=31 eth66=1
............
now endlessly cycling between [txpool] and [p2p], where is stage 11?

**Comment by srvint** [comment]
I added the flag --internalcl and it appears to be working on something else now. Hopefully this just resolves it and the notes are here for the next guy who runs into this issue. Will report back soon.

**Comment by srvint** [comment]
This in fact solved the problem with initial sync. Suggestion to keep this from being an issue in future releases is to default --internalcl to true

**Comment by yperbasis** [comment]
Internal CL (Caplin) will be the default in Erigon 3 (PR #10239)
