### ISSUE TITLE
Better support for `--sync.loop.block.limit`

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10088]
Now if set  `--sync.loop.block.limit=100`: 
- node will download all blocks to db (likely to tmpdb and then copy to db)
- don't mark blocks as canonical
- and then will start process them by 100 - only because StageSenders has support for this flag

Need better support for `--sync.loop.block.limit` because E3 sync speed depends on DB size. And to keep it small - better don't download all blocks. 

Read also: https://github.com/ledgerwatch/erigon/pull/10286#issuecomment-2106181621

- [ ] Do we need support by Caplin? Or it must be only EL feature? 
- [ ] To re-visit and simplify updateForkChoice function. In E2 we did revert support of this flag in updateForkChoice. But in E3 we still have (because hard to revert).

**Comment by Giulio2002** [comment]
https://github.com/ledgerwatch/erigon/pull/10341
