### ISSUE TITLE
Incorrect nonce for EOA 0xb5be73f96117ffe740b08c51becaea3d81e44dca

### ISSUE THREAD

**Issue by mrhornsby** [ledgerwatch/erigon#10096]
Retrieving the nonce (`eth_getTransactionCount`) for address `0xb5be73f96117ffe740b08c51becaea3d81e44dca` always seems to return the latest nonce value (`0x4b` as of block `19747163`) even when querying historic blocks where the nonce was lower. Some sample curl commands comparing my node and https://cloudflare-eth.com are included below.

#### System information

Erigon version: v2.59.3

OS & Version: Linux container (thorax/erigon:v2.59.3)

Erigon Command (with flags/config): `erigon --internalcl --http.vhosts=* --http.addr=0.0.0.0 --prune=hrtc --datadir /mnt/data1/mainnet --nat none --chain=mainnet --http.api eth,erigon,engine,trace`

Consensus Layer: Internal

Consensus Layer Command (with flags/config): N/A

Chain/Network: Ethereum mainnet

#### Expected behaviour

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x1232869"],"id":1}' https://cloudflare-eth.com`

`{"jsonrpc":"2.0","result":"0x1","id":1}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x123286a"],"id":1}' https://cloudflare-eth.com`

`{"jsonrpc":"2.0","result":"0x2","id":1}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x1233969"],"id":1}' https://cloudflare-eth.com`

`{"jsonrpc":"2.0","result":"0xc","id":1}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x12d515b"],"id":1}' https://cloudflare-eth.com`

`{"jsonrpc":"2.0","result":"0x4b","id":1}`

#### Actual behaviour

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x1232869"],"id":1}' <my-node>`

`{"jsonrpc":"2.0","id":1,"result":"0x4b"}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x123286a"],"id":1}' <my-node>`

`{"jsonrpc":"2.0","id":1,"result":"0x4b"}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x1233969"],"id":1}' <my-node>`

`{"jsonrpc":"2.0","id":1,"result":"0x4b"}`

`curl -sH "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xb5be73f96117ffe740b08c51becaea3d81e44dca", "0x12d515b"],"id":1}' <my-node>`

`{"jsonrpc":"2.0","id":1,"result":"0x4b"}`

#### Steps to reproduce the behaviour

Sync a node and execute the above curl commands.

#### Backtrace

N/A

**Comment by shohamc1** [comment]
@mrhornsby can you check on 2.60.1? I am unable to replicate this issue on my Sepolia node on a different address. Does this issue happen with all accounts or just this one?

```
curl --request POST \
  --url http://127.0.0.1:8545/ \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_getTransactionCount",
        "params": [
                "0x6Cc9397c3B38739daCbfaA68EaD5F5D77Ba5F455",
                "0x5C8F91"
        ],
        "id": 1,
        "jsonrpc": "2.0"
}'
{"jsonrpc":"2.0","id":1,"result":"0x169ad7"}
```

```
curl --request POST \
  --url http://127.0.0.1:8545/ \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_getTransactionCount",
        "params": [
                "0x6Cc9397c3B38739daCbfaA68EaD5F5D77Ba5F455",
                "0x5C8F92"
        ],
        "id": 1,
        "jsonrpc": "2.0"
}'
{"jsonrpc":"2.0","id":1,"result":"0x169ad8"}
```

**Comment by mrhornsby** [comment]
Hey @shohamc1,

I've just downloaded 2.60.1 (docker) and re-started my node and it still returns the incorrect result.

Just to confirm that I've only identified this one address, `0xb5be73f96117ffe740b08c51becaea3d81e44dca`, that has the error, all others seem to be fine.

Thanks

Mark

**Comment by shohamc1** [comment]
@mrhornsby I've noticed that you are using `prune=hrtc`. You are pruning history to the latest 90k blocks and then querying outside the available block range. I have checked that the issue does not exist when querying in the correct block range.

```
curl --request POST \
  --url http://127.0.0.1:8545/ \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_getTransactionCount",
        "params": [
                "0x56de1961fDA5454E6F8e6D0e3124fF648FD69400",
                "0x1326472"
        ],
        "id": 1,
        "jsonrpc": "2.0"
}'
{"jsonrpc":"2.0","id":1,"result":"0x1c141"}
```

```
curl --request POST \
  --url http://127.0.0.1:8545/ \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_getTransactionCount",
        "params": [
                "0x56de1961fDA5454E6F8e6D0e3124fF648FD69400",
                "0x1326473"
        ],
        "id": 1,
        "jsonrpc": "2.0"
}'
{"jsonrpc":"2.0","id":1,"result":"0x1c142"}
```

**Comment by mrhornsby** [comment]
Thanks @shohamc1, you make a good point. I believe when the issue originally occurred that I was within the 90k block window, but given the amount of time that has passed it's hard to confirm. I'll close the issue, thanks for your help.
