### ISSUE TITLE
Split Database Files Where Possible

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1021]
Adding this as an issue for tracking.

Has any thought been given to splitting the data.mdb file into separate database files/buckets?

It would make managing storage easier if we could split it up somehow. Right now it's a single 685GB file for me. I could see scenarios where it would be nice to split it across disks.

For instance my Intel NUCs have 2 SSDs, both 500GB. I couldn't store that single file on either disk.

For Nethermind and geth, because they put files in different folders, I can mount storage at those locations or use symlinks in order to spread the load across disks without resorting to RAID setups.

**Comment by metala** [comment]
I think an LVM would solve your issue.

**Comment by MysticRyuujin** [comment]
If I had a host dedicated to the singular purpose of running TG and set it up that way, sure. This isn't a constructive reply.

**Comment by AskAlexSharov** [comment]
We working on it by moving headers and blocks to to historical snapshot: https://github.com/ledgerwatch/turbo-geth/pull/1836

But only headers+blocks it’s 150gb, not much. I think other historical data also may go out, but not in plans yet.

**Comment by metala** [comment]
> If I had a host dedicated to the singular purpose of running TG and set it up that way, sure. This isn't a constructive reply. LVM volumes come with their own sets of problems wrt to expansion, write load balancing, etc.
> 
> It also doesn't solve many of the other uses cases and benefits of splitting your database into different "files" allowing you to mix and match differing performance disks.

I am sorry. I though your issue was just storage, which I am currently trying to solve with btrfs+zstd. Also, sorry for the necro.

**Comment by AskAlexSharov** [comment]
@metala if btrfs+zstd will not work well enough, you can try zfs+It’s default compression. When using compression speed is mostly depends on amount of RAM in TG case.

**Comment by AskAlexSharov** [comment]
--syncmode=snap released. now block are in datadir/snapshots
