### ISSUE TITLE
Downloader on bor-mainnet is stuck waiting for metadata of v1-054600-054700-borspans.seg

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#10233]
I'm trying to sync `bor-mainnet` from scratch with `release/2.60` (commit 40d1327a35e6c5ed08691a37bb9bcc8dec56e0bc), but my node is stuck at
```
[INFO] [05-07|21:13:16.310] [snapshots] no metadata yet              files=1 list=v1-054600-054700-borspans.seg
[INFO] [05-07|21:13:16.336] [1/15 Snapshots] download                progress="99.90% 940.4GB/940.4GB" time-left=999hrs:99m total-time=4m0s download=0B/s upload=0B/s peers=2 files=695 metadata=694/695 connections=2 alloc=670.5MB sys=968.4MB
```

I suspect that it's caused by https://github.com/ledgerwatch/erigon-snapshot/pull/142, which changed the hash of this file for no apparent reason.

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon/pull/10242
https://github.com/ledgerwatch/erigon-snapshot/pull/159
https://github.com/ledgerwatch/erigon/pull/10243
https://github.com/ledgerwatch/erigon-snapshot/pull/160

**Comment by yperbasis** [comment]
> #10242 [ledgerwatch/erigon-snapshot#159](https://github.com/ledgerwatch/erigon-snapshot/pull/159) #10243 [ledgerwatch/erigon-snapshot#160](https://github.com/ledgerwatch/erigon-snapshot/pull/160)

It's not helping unfortunatelly:
```
[INFO] [05-08|07:08:08.886] Build info                               git_branch=e2_bor_mainnet_borspan git_tag=v2.54.0-819-g665c9a180c git_commit=665c9a180c54744d6b1f490c0714aae8296d2201
...
[INFO] [05-08|07:11:11.090] [snapshots] no metadata yet              files=1 list=v1-054600-054700-borspans.seg
```

**Comment by bcxyz** [comment]
Still have the same issue 054600-054700-borspans.seg, even on the latest release.

**Comment by yperbasis** [comment]
> ledgerwatch/erigon-snapshot#160

With [v2.60.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.60.0)? Then please `rm <datadir>/snapshots/v1-054600-054700-borspans.seg*`  and restart.

**Comment by bcxyz** [comment]
Yes, with v2.60.0. Removed v1-054600-054700-borspans.seg*, restarted Erigon and the issue still persists. Also, snapshots/v1-054600-054700-bor* was removed successfully and is still gone. I cannot remove it again to give it another try.

<img width="1063" alt="Screenshot 2024-05-16 at 13 57 57" src="https://github.com/ledgerwatch/erigon/assets/135616961/701afb34-cd8c-4ab0-a5b7-37e87582428c">

**Comment by AskAlexSharov** [comment]
@bcxyz sorry, i don't believe you :-) show:
- git status
- `rm` command which you do
- `ls` output after rm is done
-

**Comment by bcxyz** [comment]
Not sure why you wouldn't believe me.

<img width="1140" alt="Screenshot 2024-05-17 at 13 07 05" src="https://github.com/ledgerwatch/erigon/assets/135616961/8e5e0108-482c-45f4-a190-7f7763e32dd4">

The diagnostics error is due to heimdalld using port 6060. Also tried changing that, with no results.

Am I missing something or making a mistake somewhere?
