### ISSUE TITLE
After a reboot Erigon incorrectly reports that it is in sync

### ISSUE THREAD

**Issue by mriccobene** [ledgerwatch/erigon#10248]
After a restart, Erigon downloads and processes the missing blocks to get to the tip of the chain. 

During that time it reports being in sync if queried via the JSON RPC API, but that's not true: it will get to be in sync after completing that process.

This behavior can be analyzed e.g. [here](https://github.com/ledgerwatch/erigon/actions/runs/8993430302/job/24705215883) where Erigon's log has been annotated with information from Etherscan

**Comment by yperbasis** [comment]
That's on branch `release/2.60`, right?

**Comment by AskAlexSharov** [comment]
probably related with https://github.com/ledgerwatch/erigon/issues/8752

**Comment by AskAlexSharov** [comment]
Improving eth_syncing may be even more important for e3 - there are progress of stages always equal.

**Comment by mriccobene** [comment]
Yes, it is on branch release/2.60

**Comment by yperbasis** [comment]
Probably too late to fix it in 2.60. Let's fix it in e3.
