### ISSUE TITLE
investigate why PR's from external repos have red CI

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10271]
CI of https://github.com/ledgerwatch/erigon/pull/10159

**Comment by yperbasis** [comment]
@AskAlexSharov are the changed you added in PR #10332 related to this issue?

**Comment by AskAlexSharov** [comment]
@yperbasis yes. unblocked PR's.

**Comment by yperbasis** [comment]
Fixed by PR #10332.
