### ISSUE TITLE
enable TestNonceFromAddress in `main` branch

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10307]
erigon-lib/types EncodeSenderLengthForStorage, EncodeSender, DecodeSender - seems don't support E3 encoding
need somehow support it and enable tests 

Tests:  TestNonceFromAddress, TestReplaceWithHigherFee,TestReverseNonces,TestTxPoke,TestBlobTxReplacement,TestDropRemoteAtNoGossip,TestBlobSlots,TestGasLimitChanged

**Comment by AskAlexSharov** [comment]
@Giulio2002 maybe it's related to empty txpool problem

**Comment by Giulio2002** [comment]
No, there is already support.
