### ISSUE TITLE
enable cache_test.go:TestAPI in `main`

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10308]
`/erigon-lib/kv/kvcache/cache_test.go:TestAPI`

**Comment by Giulio2002** [comment]
This test does not test anything that has to do with E3. It just tests the API of the KV Cache - which by itself is not either E2 or E3. I think `TestNonceFromAddress` is a better test for seeing if the correct value is being stored. I think this test checks if the API works and if the get(k) and set(k, v) are consistent. I re-enabled it in #10399. let me know
