### ISSUE TITLE
Serve receipts by P2P

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10320]
Code is here: in `getReceipts66` need uncomment things and inside `AnswerGetReceiptsQuery` implement re-execution of requested blocks - to produce Receipts.

Additional: need use only 1 gorotine for all such P2P requests. (probably by `*semaphore.Weighted`)

Additional: add LRU of results.

Example of block re-exec see in: `getLogsV3`. (there is use of `intraBlockExec`).
See also Receipts LRU in RPCDaemon (as an example. don't re-use it).

**Comment by Giulio2002** [comment]
My 2 cents: this should be priority low and probably be not a "requirement" for E3 alpha

**Comment by AskAlexSharov** [comment]
agree. created `beta` milestone. moved issue there.
