### ISSUE TITLE
Introduce option to use TLS and basic authentication for communication between TG and RPC daemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#1034]
This is to allow more flexible usage: for example:
1) running TG instance on the cloud computer, but running RPC daemon locally
2) running analytics (like state growth) locally against remote TG instance

**Comment by AlexeyAkhunov** [comment]
https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls

**Comment by AskAlexSharov** [comment]
done
