### ISSUE TITLE
Snapshot download stuck

### ISSUE THREAD

**Issue by bcxyz** [ledgerwatch/erigon#10364]
#### System information
Ubuntu 22.04

Erigon version: 
2.60.0-rc1-32f7775c

OS & Version: 
Linux

Erigon Command (with flags/config):
```
sudo ./build/bin/erigon \
  --chain=bor-mainnet \
  --bor.heimdall=http://localhost:1317 \
  --datadir=/root/node/erigon/erigon-chaindata \
  --prune=hrtc \
  --http.addr="0.0.0.0" \
  --http.api=eth,web3,net,debug,trace,txpool \
  --torrent.download.rate=512mb
```

Chain/Network: 
Polygon Mainnet

**The issue:**
INFO[05-16|00:17:30.429] [snapshots] no metadata yet              files=1 list=v1-054600-054700-borspans.seg
INFO[05-16|00:17:30.492] [1/15 Snapshots] download                progress="99.90% 940.4GB/940.4GB" time-left=999hrs:99m total-time=20s download=0B/s upload=0B/s peers=0 files=695 metadata=694/695 connections=0 alloc=447.8MB sys=796.0MB

I checked recent open/closed issues and tried running Erigon with less flags as this was recommended as a potential fix:
`./build/bin/erigon --prune=hrtc --datadir=/root/node/erigon/erigon-chaindata --port 35269 --p2p.allowed-ports 35269,36942,57640 --torrent.port 62469`

This did not work for me. There's another open issue related to v1-054600-054700-borspans.seg. I am running the latest version and that merge did not work either.

All necessary ports are open, I have sufficient storage space, and a good internet speed/connection.

Any ideas?

**Comment by AskAlexSharov** [comment]
rm snapshots/v1-054600-054700-bor*

**Comment by bcxyz** [comment]
Removed the file, restarted Erigon and the issue still persists. Also, snapshots/v1-054600-054700-bor* was removed successfully and is still gone. I cannot remove it again to give it another try.

**Comment by bcxyz** [comment]
<img width="1053" alt="Screenshot 2024-05-16 at 13 54 12" src="https://github.com/ledgerwatch/erigon/assets/135616961/0f0c74de-8a53-4b4b-b29e-14fe942047ca">

**Comment by bcxyz** [comment]
<img width="1063" alt="Screenshot 2024-05-16 at 13 57 57" src="https://github.com/ledgerwatch/erigon/assets/135616961/6619e6f0-b268-4114-a7ca-fb40b1f9252c">

**Comment by Giulio2002** [comment]
CC @mholt-dv

**Comment by yperbasis** [comment]
@bcxyz please update to the final v2.60.0: https://github.com/ledgerwatch/erigon/issues/10233#issuecomment-2117515722
