### ISSUE TITLE
debug_traceCall API returns not valid json format output when the tx execute is fail

### ISSUE THREAD

**Issue by marshalys** [ledgerwatch/erigon#10376]
#### System information

Erigon version: `./erigon --version`

erigon version 2.59.3

OS & Version: Windows/Linux/OSX

linux ubuntu

Chain/Network: mainnet

#### Expected behaviour

return valid format json

#### Actual behaviour

return not valid format json

I found the reason is the result is wrong, like:
```
"result":{"structLogs":[]}null,"error":{"code":-32000, ...
```
it should be `"result":null,"error":{"code":-32000, ...` in most case when the execute is fail, but now the result value is `{"structLogs":[]}null,`, not a valid json format.

**Comment by taratorio** [comment]
@marshalys thanks for reporting. 
Short term solution: https://github.com/ledgerwatch/erigon/pull/10383
Long term solution: https://github.com/ledgerwatch/erigon/issues/10389

please can you do me a favour and verify that the short term solution solves your problem?

**Comment by taratorio** [comment]
> @marshalys thanks for reporting. Short term solution: #10383 Long term solution: #10389
> 
> please can you do me a favour and verify that the short term solution solves your problem?

managed to test myself, looks fixed

**Comment by taratorio** [comment]
should be included in v2.60.1 and future v3 for erigon 3
