### ISSUE TITLE
Syncing Erigon Node to Specific Block Height

### ISSUE THREAD

**Issue by devateho** [ledgerwatch/erigon#10372]
I am trying to set up an Erigon node and sync it only to a specific block height (let's say block 1000). **I want to interact with historical data and contracts deployed early in Ethereum's history, but I have limited disk space on my SSD (1TB).** I have tried various combinations of settings, but the RPC always returns 0x for the block number.

Here is an example of my RPC query:

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8545`

And the response:

`{"jsonrpc":"2.0","id":1,"result":"0x0"}`

I have searched the documentation, issues, and discussions, but I could not find a clear solution to my problem. I am open to any suggestions or workarounds to achieve my goal of syncing only the first X blocks. Thank you in advance for your help!

**Comment by Giulio2002** [comment]
We do not have such a feature. you can try E3 on main branch with `--prune=minimal`, you will have access to contracts but not to other things
