### ISSUE TITLE
E3: Genesis Unwind bug 

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#10458]
Unwind does weird things: sets DB to wrong block, crashes, does not unwind even if requested to.

### Steps to reproduce

Run hive tests, 1 test will be failing, you can see the bug I am talking about in that test.

**Comment by yperbasis** [comment]
Not high-priority because it only occurs at genesis.

**Comment by awskii** [comment]
closed due to new unwind implementation
