### ISSUE TITLE
Diagnostics: make errors users-friendly 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10518]
```
go run ./cmd/diag dbs 
invalid character 'p' after top-level value
exit status 1
```
unclear what/where broken

**Comment by dvovk** [comment]
It means that you run diag command before Erigon node fully running. Diagnostics starts after all erigon components. Probably I need to show proper error message.

**Comment by dvovk** [comment]
fixed - https://github.com/ledgerwatch/erigon/pull/10527
