### ISSUE TITLE
user reports of eth_getBlockByNumber returning null between block 19700053 and 19700454

### ISSUE THREAD

**Issue by taratorio** [ledgerwatch/erigon#10572]
User `nicolaslaw.eth` reported this on Discord ([msg](https://discord.com/channels/687972960811745322/738982866670714901/1246035240091389962)). Needs investigation.

#### System information

Erigon version: `v2.60.0`

OS & Version: Linux

Erigon Command (with flags/config): ``` ${ERIGON_FLAGS-} --private.api.addr=0.0.0.0:9090
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex --authrpc.addr=0.0.0.0 --datadir=/home/erigon/.local/share/erigon
      --chain=mainnet --http --ws --http.api=eth,debug,net,trace,web3,erigon --db.size.limit=8TB```

Consensus Layer: Nimbus

Consensus Layer Command (with flags/config): ```
    command: >-
      --network=mainnet
      --data-dir=/home/user/nimbus-eth2/build/data/shared_mainnet_0
      --web3-url=ws://erigon-erigon-1:8551
      --el=ws://erigon-erigon-1:8551
      --jwt-secret=/jwt/jwt.hex
      --nat=extip:130.254.84.224
      --log-level=info
      --tcp-port=9000
      --udp-port=9000
      --rest
      --rest-address=0.0.0.0
      --rest-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=8008
```

Chain/Network: Ethereum mainnet

#### Expected behaviour
eth_getBlockByNumber to return block data matching what other clients are returning, e.g. can try quicknode api
```
curl https://docs-demo.quiknode.pro/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0x12C9955",false],"id":1,"jsonrpc":"2.0"}'
```

#### Actual behaviour
returns null

#### Steps to reproduce the behaviour
```
curl <URL> \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0x12C9955",false],"id":1,"jsonrpc":"2.0"}'
```

#### Backtrace
N/A

**Comment by Giulio2002** [comment]
Closed by #10850
