### ISSUE TITLE
Add static peer CLI flag

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#1066]
They removed the static-peers.json in favor of the TOML config file, but the TOML config file introduces other problems
If you want to use the TOML config file, you need a full and complete TOML config file. But the problem is, they often add/remove/modify TOML config properties...so it breaks a lot if you try to use a custom TOML config

**Comment by MysticRyuujin** [comment]
I would say this could either be:

_a_. CLI Flag that accepts an array of enodes
or
_b_. CLI Flag that points to a JSON file (containing an array of enodes)

_b_ is how Nethermind does it. Geth used to automatically use a file called `static-nodes.json` file in the datadir.

**Comment by mandrigin** [comment]
Personally, I like the option (b) a bit more..

**Comment by MysticRyuujin** [comment]
bump :smile:

**Comment by AskAlexSharov** [comment]
@MysticRyuujin I see in TG code to parse `static-nodes.json` file in datadir. Still need cli parameter?

**Comment by MysticRyuujin** [comment]
Oh! I did not know that was an option/worked! I'll try it. I don't need a cli flag if that's the case.

**Comment by MysticRyuujin** [comment]
Ok so, you closed this before I tested it. I tested it, and there's no indication that tg is either a) even reading the file, or b) it's working at all.

**Comment by MysticRyuujin** [comment]
I tossed wireshark up and looked to see if tg would reach out to one of the configured peers on startup, and I got nothing.

**Comment by MysticRyuujin** [comment]
I created a garbage file that isn't even JSON and tg starts just fine. If it was trying to read that file at all, I assume it would throw an error.

**Comment by AlexeyAkhunov** [comment]
It has been added
