### ISSUE TITLE
Sync problem: limited big jump on tip

### ISSUE THREAD

**Issue by DejanKr** [ledgerwatch/erigon#10679]
Hello. I have problem with synhonization of my erigon node. It stop on block 20048314. Erigon version is 3.00.0-dev-c228b705. 

Here is my erigon.service file:
Description=Erigon Ethereum Client
After=network.target

[Service]
User=root
ExecStart=/root/erigon/build/bin/erigon --datadir=/root/.erigon \
  --maxpeers=150 \
  --prune=htc --prune.r.before=6617916 \
  --private.api.addr=127.0.0.1:9090 \
  --http --http.addr=127.0.0.1 --http.port=8545 \
  --ws --ws.port=8546 \
  --http.api=eth,debug,net,trace,web3,erigon,txpool \
  --torrent.upload.rate=200mb \
  --torrent.download.rate=200mb \

Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target

Here is result of "journalctl -u erigon.service -f"

Jun 09 08:47:51 node.one erigon[96431]: [INFO] [06-09|08:47:51.901] Starting downloading History             app=caplin stage=DownloadHistoricalBlocks from=9260256
Jun 09 08:47:52 node.one erigon[96431]: [INFO] [06-09|08:47:52.791] Missing blocks download finished (note: this does not mean that the history is complete, only that the missing blocks need for sync have been downloaded) app=caplin stage=DownloadHistoricalBlocks
Jun 09 08:47:55 node.one erigon[96431]: [INFO] [06-09|08:47:55.701] [1/12 Snapshots] Requesting downloads
Jun 09 08:47:56 node.one erigon[96431]: [INFO] [06-09|08:47:56.652] [snapshots:download] Stat                blocks=20043k indices=20043k alloc=8.2GB sys=12.2GB
Jun 09 08:47:56 node.one erigon[96431]: [INFO] [06-09|08:47:56.652] [snapshots:history] Stat                 blocks=20044k txs=2437m txNum2blockNum="1024=14760K,1536=19814K,1552=19968K,1560=20044K" first_history_idx_in_db=20044869 last_comitment_block=20044869 last_comitment_tx_num=2437500000 alloc=8.2GB sys=12.2GB
Jun 09 08:47:56 node.one erigon[96431]: [INFO] [06-09|08:47:56.917] Ready to insert history, waiting for sync cycle to finish app=caplin stage=DownloadHistoricalBlocks
Jun 09 08:47:56 node.one erigon[96431]: [INFO] [06-09|08:47:56.925] [Caplin] Forward Sync                    app=caplin stage=ForwardSync from=9260256 to=9260337
Jun 09 08:48:28 node.one erigon[96431]: [INFO] [06-09|08:48:28.756] [Caplin] Forward Sync                    app=caplin stage=ForwardSync progress=9260340 distance-from-chain-tip=-36s estimated-time-remaining=732013h41m39.672793088s
Jun 09 08:48:31 node.one erigon[96431]: [INFO] [06-09|08:48:31.589] [sync] limited big jump                  from=20048314 amount=5000
Jun 09 08:48:36 node.one erigon[96431]: [INFO] [06-09|08:48:36.659] [sync] limited big jump                  from=20048314 amount=5000
Jun 09 08:48:48 node.one erigon[96431]: [INFO] [06-09|08:48:48.626] [sync] limited big jump                  from=20048314 amount=5000
Jun 09 08:48:50 node.one erigon[96431]: [INFO] [06-09|08:48:50.487] P2P                                      app=caplin peers=39
Jun 09 08:49:01 node.one erigon[96431]: [INFO] [06-09|08:49:01.412] [sync] limited big jump                  from=20048314 amount=5000
Jun 09 08:49:13 node.one erigon[96431]: [INFO] [06-09|08:49:13.445] [sync] limited big jump                  from=20048314 amount=5000
Jun 09 08:49:24 node.one erigon[96431]: [INFO] [06-09|08:49:24.456] [sync] limited big jump                  from=20048314 amount=5000

What is the problem and how I can solve it. Please for help. Thanks.

**Comment by AskAlexSharov** [comment]
fixed. feel free to re-open if need.
