### ISSUE TITLE
how to clear txpool's queued data?

### ISSUE THREAD

**Issue by nanahos** [ledgerwatch/erigon#10700]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://github.com/ledgerwatch/erigon#erigon-discord-server).

I am querying the txpool of the Erigon node. The queued data in the txpoolt are steadily increasing, c. Besides restarting Erigon, how can I clear the queued data

**Comment by AskAlexSharov** [comment]
There is cli flag for limit txpool size. 
Also can remove datadir/txpool folder
