### ISSUE TITLE
e3: mainnet to produce caplin files

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10727]
e3: on ethmainnet snapshotter
i removed flags ` --caplin.backfilling --caplin.archive --caplin.backfilling.blob` because with this flags - node trying to download unlimited amount of blocks. So, i decided to prioritize E3 files release for mainnet and then produce Caplin files (as separated step).

Logs after 24 hours of node run:
```
[INFO] [06-11|02:12:26.717] Node is still syncing... downloading past blocks app=caplin stage=DownloadHistoricalBlocks slot=7327416 blockNumber=18139326 frozenBlocks=18999999 blk/sec=2.1 snapshots=0
[INFO] [06-11|02:12:56.717] Node is still syncing... downloading past blocks app=caplin stage=DownloadHistoricalBlocks slot=7327288 blockNumber=18139199 frozenBlocks=18999999 blk/sec=4.3 snapshots=0
```  

Need produce missing Capin files for ethmainnet. 
But plz let's release blocks/state files first (almost done).

**Comment by Giulio2002** [comment]
Caplin files for that range should be already generated on rclone. please rsync the snapshots.  or remove from the .lock json files blobsidecars and beaconblocks entries

**Comment by AskAlexSharov** [comment]
I was needed to re-gen some transactions.seg files from `18999999` (and also some .ef files) because they was broken. 
So, i can't rclone. 
Also today I did have `19.8M` .seg files. And i did try to enable caplin flags - it also tried to download beyond .seg files. And i disabled flags. 

Also today: ethmainnet snapshotter got https://github.com/ledgerwatch/erigon/issues/10733 - so I was need to start from `19.8M` .seg files and `15M` state files. 

So, i will close this issue for now - because need wait for state files production anyway.

**Comment by AskAlexSharov** [comment]
@Giulio2002 it's bug anyway - that Caplin trying to download more blocks than erigon has in files. right?

**Comment by Giulio2002** [comment]
How have you ran the node? can you check content of the lock file and put it here, put flags as well please

**Comment by AskAlexSharov** [comment]
node name is `snapshotter-bm-e3fore2files-ethmainnet-n1.erigon.io`
