### ISSUE TITLE
Erigon 3, receiptHash mismatch: [7/15 Execution] Execution failed block=56958257

### ISSUE THREAD

**Issue by g45g4wwf** [ledgerwatch/erigon#10775]
During the first synchronization attempt of the Erigon node Version 3 with the Polygon  main network, an error (warn) occurred indicating a mismatch in the receipt hash during block execution. The log entry was: 
`[7/15 Execution] Execution failed block=56958257 txNum=4100004369 hash=0x198af3128fa8b5b6f092044bd8259b10ca3f243c7d1a8f0d451138a8d10fecb1 err="invalid block, txnIdx=195, receiptHash mismatch: eef556e8dffd811ec6b0b52cb7ff0cd6606ed6064e092f2a25d07be0775e24f7 != d63d6f852ff47c6e5d467f6e63c6763d0de0a9d84296d5ed4b804fda8448135b, headerNum=56958257, 198af3128fa8b5b6f092044bd8259b10ca3f243c7d1a8f0d451138a8d10fecb1"`
This log repeats every some minutes, the synchronization process is stopped.

This issue persists (stopping at same block) even after attempting the synchronization for the second time, possibly due to issues with the downloaded torrent data which was not deleted after the first attempt. How can i fix this issue or should i delete snapshots too and try it again?

Erigon 3.00.0-dev-037a5600
OS ubuntu:latest
Command: 
`erigon 
      --chain=bor-mainnet
      --datadir=/data
      --port=31303
      --bor.heimdall=http://heimdall:1317
      --authrpc.addr=0.0.0.0
      --authrpc.port=8651
      --authrpc.jwtsecret=/secrets/jwt.hex
      --authrpc.vhosts=any
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.corsdomain=*
      --http.api=admin,eth,net,web3,debug,engine,erigon,bor
      --ws
      --ws.port=8646
      --private.api.addr=0.0.0.0:9091
      --torrent.download.rate=64mb
      --torrent.port=42069`

Chain/Network: Polygon
Consensus: Heimdall 1.0.6
`heimdall start --home=/heimdall-home --chain=mainnet --rest-server --eth_rpc_url=http://erigon:8545`

**Comment by AskAlexSharov** [comment]
thank you. we are working on it.

**Comment by AskAlexSharov** [comment]
partially fixed by https://github.com/ledgerwatch/erigon/pull/10871
