### ISSUE TITLE
E3: Downloader stuck at progress=100%

### ISSUE THREAD

**Issue by dvovk** [ledgerwatch/erigon#10808]
#### System information

Erigon version: v2.59.1-4731-gdf0e57667 

Commit hash: df0e57667b417bd8e078ff3797e4393fd3921a19

Downloader stuck at progress=100%
`[INFO] [06-18|13:36:04.505] [1/12 Snapshots] downloading header-chain progress="100.00% 688.1GB/688.1GB" time-left=999hrs:99m total-time=10m40s download=0B/s upload=0B/s peers=3 files=260 metadata=260/260 connections=4 alloc=4.0GB sys=6.0GB`
Log: https://binki.metala.org/?3074642b131d4e33#BrUKQnNAjqxoM7axu9UPn1rzcSd4ELt7znoiUJ9HfEBs

As a future investigation showed one file wasn't downloaded: `INFO[06-19|19:09:59.420] [snapshots] progress                     file=v1-008900-009000-beaconblocks.seg progress=99.55% peers=1 webseeds=0`

Discord link: https://discord.com/channels/687972960811745322/1253003917986369677

**Comment by AskAlexSharov** [comment]
Mark fixed it in https://github.com/ledgerwatch/erigon/pull/10715 - but this PR will take long time to release/test. Maybe he will able to split it to 2 PR's for "correctness" and for "performance". will see.
