### ISSUE TITLE
eth_getBlockByNumber returns null

### ISSUE THREAD

**Issue by dvovk** [ledgerwatch/erigon#10809]
#### System information

Erigon version: 2.60.1
chain: gnosis

User request: Can't query the block after #32810000
`$ curl --location 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data '{
        "jsonrpc":"2.0",
        "method":"eth_getBlockByNumber",
        "params":[
                "0x1F4A410",
                true
        ],
        "id":1
}'
{"jsonrpc":"2.0","id":1,"result":null}`

Debug request response is:
`Jun 19 18:20:13 gnosis-arch42 erigon[766187]: [INFO] [06-19|18:20:13.230] [dbg] BlockReader(idxMax=32809999,segMax=32809999).blockWithSenders(hash=cf01053f86f0421069363db342082a85edfbe3bc39ef8fea68cf90817d97ef26,blk=32810000) -> found_in_db=false`

**Comment by AskAlexSharov** [comment]
`integration print_stages` can show what is last block in snapshots and first block in db. 
to re-download blocks in DB: `integration stage_headers --reset`

**Comment by awskii** [comment]
user had pruned range starting from that block, did not return with new updates after 4 days and got same advises as Alex supposed + clarifications in that thread: https://discord.com/channels/687972960811745322/1252745101743226941
