### ISSUE TITLE
Improper shutdown

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1107]
I did a shutdown, apparently in the middle of Stage 11, however, the node fails to exit.

It's hangs at this spot indefinitely (or until my 5 minute process kill timer expires at least)

```
INFO [09-12|09:25:07.712] Sync stage 1/12. Download headers... 
INFO [09-12|09:25:07.958] Sync stage 2/12. Write block hashes... 
INFO [09-12|09:25:07.958] Sync stage 3/12. Download block bodies... 
INFO [09-12|09:25:07.958] Sync stage 4/12. Recover senders from tx signatures... 
INFO [09-12|09:25:07.958] Sync stage 5/12. Execute blocks w/o hash checks... 
INFO [09-12|09:25:07.958] Sync stage 6/12. Hash the key in the state... 
INFO [09-12|09:25:07.958] Sync stage 7/12. Generate intermediate hashes and computing state root... 
INFO [09-12|09:25:07.958] Sync stage 8/12. Generate account history index... 
INFO [09-12|09:25:07.958] Sync stage 9/12. Generate storage history index... 
INFO [09-12|09:25:07.958] Sync stage 10/12. Generate tx lookup index... 
INFO [09-12|09:25:07.958] Sync stage 11/12. Update transaction pool... 
INFO [09-12|09:47:34.247] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-12|10:47:34.247] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-12|11:47:34.248] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-12|12:37:15.458] Got interrupt, shutting down... 
INFO [09-12|12:37:15.458] Blockchain stopped 
INFO [09-12|12:37:15.482] TxPoolUpdate: Reading canonical hashes complete hashes=0
INFO [09-12|12:37:15.483] Transaction stats                        pending=878  queued=1024
INFO [09-12|12:37:15.483] Sync stage 11/12. Update transaction pool... DONE! 
INFO [09-12|12:37:15.483] Sync stage 12/12. Final: update current block for the RPC API... 
INFO [09-12|12:37:15.483] Memory                                   alloc=698.74MiB sys=1.20GiB
INFO [09-12|12:37:15.483] Timings                                  Headers=245.765665ms    BlockHashes="45.108µs"  Senders="15µs"      Execution="8.339µs"    IntermediateHashes="9.14µs"     AccountHistoryIndex="8.07µs"     StorageHistoryIndex="8.149µs"    TxLookup="175.194µs"  Bodies="191.424µs" HashState="7.83µs"     TxPool=3h12m7.524753435s Finish="14.929µs"
INFO [09-12|12:37:15.484] Commit blocks                            in="501.883µs"
```

**Comment by AlexeyAkhunov** [comment]
Next time it happens, can you please send `kill -6` to the process, this should produce the stack trace that can be helpful to understand why it is hanging

**Comment by akme** [comment]
> I did a shutdown, apparently in the middle of Stage 11, however, the node fails to exit.
> 
> 
> 
> It's hangs at this spot indefinitely (or until my 5 minute process kill timer expires at least)
> 
> 
> 
> ```
> 
> INFO [09-12|09:25:07.712] Sync stage 1/12. Download headers... 
> 
> INFO [09-12|09:25:07.958] Sync stage 2/12. Write block hashes... 
> 
> INFO [09-12|09:25:07.958] Sync stage 3/12. Download block bodies... 
> 
> INFO [09-12|09:25:07.958] Sync stage 4/12. Recover senders from tx signatures... 
> 
> INFO [09-12|09:25:07.958] Sync stage 5/12. Execute blocks w/o hash checks... 
> 
> INFO [09-12|09:25:07.958] Sync stage 6/12. Hash the key in the state... 
> 
> INFO [09-12|09:25:07.958] Sync stage 7/12. Generate intermediate hashes and computing state root... 
> 
> INFO [09-12|09:25:07.958] Sync stage 8/12. Generate account history index... 
> 
> INFO [09-12|09:25:07.958] Sync stage 9/12. Generate storage history index... 
> 
> INFO [09-12|09:25:07.958] Sync stage 10/12. Generate tx lookup index... 
> 
> INFO [09-12|09:25:07.958] Sync stage 11/12. Update transaction pool... 
> 
> INFO [09-12|09:47:34.247] Regenerated local transaction journal    transactions=0 accounts=0
> 
> INFO [09-12|10:47:34.247] Regenerated local transaction journal    transactions=0 accounts=0
> 
> INFO [09-12|11:47:34.248] Regenerated local transaction journal    transactions=0 accounts=0
> 
> INFO [09-12|12:37:15.458] Got interrupt, shutting down... 
> 
> INFO [09-12|12:37:15.458] Blockchain stopped 
> 
> INFO [09-12|12:37:15.482] TxPoolUpdate: Reading canonical hashes complete hashes=0
> 
> INFO [09-12|12:37:15.483] Transaction stats                        pending=878  queued=1024
> 
> INFO [09-12|12:37:15.483] Sync stage 11/12. Update transaction pool... DONE! 
> 
> INFO [09-12|12:37:15.483] Sync stage 12/12. Final: update current block for the RPC API... 
> 
> INFO [09-12|12:37:15.483] Memory                                   alloc=698.74MiB sys=1.20GiB
> 
> INFO [09-12|12:37:15.483] Timings                                  Headers=245.765665ms    BlockHashes="45.108µs"  Senders="15µs"      Execution="8.339µs"    IntermediateHashes="9.14µs"     AccountHistoryIndex="8.07µs"     StorageHistoryIndex="8.149µs"    TxLookup="175.194µs"  Bodies="191.424µs" HashState="7.83µs"     TxPool=3h12m7.524753435s Finish="14.929µs"
> 
> INFO [09-12|12:37:15.484] Commit blocks                            in="501.883µs"
> 
> ```

What commit do you run? I had similar behaviour before memory leak was fixed

**Comment by MysticRyuujin** [comment]
It was the commit at (close the ticker #1104)
0f24a0167772efe55f5c5f751b90a7213e3dd154

If that's the memory leak you're referring to, I was running the patched commit.

**Comment by AskAlexSharov** [comment]
hi, I think it's fixed
