### ISSUE TITLE
My Erigon node is not progressing and is stuck on the 19600K block. 

### ISSUE THREAD

**Issue by SelimRokbani** [ledgerwatch/erigon#11094]
It has already executed and ran all the previous blocks, but now it won't download new headers to sync.

erigon --version
erigon version 2.60.0

OS & Version: Windows/Linux/OSX
Ubuntu 22.04

Configuration
Command used to run Erigon: ./build/bin/erigon --prune.h.older=1000000 --prune.r.older=1000000 --prune.t.older=1000000 --prune.c.older=1000000 --torrent.download.rate=512mb --http.api=erigon,debug,eth,net,web3 --http.corsdomain="*" --http.port=8545 --private.api.addr=localhost:9090

Additional context
The node was syncing fine until it reached the 19600K block. No recent changes were made to the configuration or the environment.

Logs:

INFO[07-07|04:38:52.784] logging to file system                   log dir=/home/smohamed/.local/share/erigon/logs file prefix=erigon log level=info json=false
INFO[07-07|04:38:52.784] Build info                               git_branch=HEAD git_tag=v2.60.0 git_commit=7883a4e3c99a22ccc826906f7ecdab61afee74f8
INFO[07-07|04:38:52.785] Starting Erigon on Ethereum mainnet...
INFO[07-07|04:38:52.789] Maximum peer count                       ETH=100 total=100
INFO[07-07|04:38:52.789] starting HTTP APIs                       port=8545 APIs=erigon,debug,eth,net,web3
INFO[07-07|04:38:52.791] torrent verbosity                        level=WRN
INFO[07-07|04:38:54.896] Set global gas cap                       cap=50000000
INFO[07-07|04:38:54.979] [Downloader] Running with                ipv6-enabled=true ipv4-enabled=true download.rate=512mb upload.rate=4mb
INFO[07-07|04:38:54.980] Opening Database                         label=chaindata path=/home/smohamed/.local/share/erigon/chaindata
INFO[07-07|04:38:54.982] [db] open                                label=chaindata sizeLimit=12TB pageSize=8192
WARN[07-07|04:38:54.989] Sanitizing invalid bor miner gas price   provided=1000000000 updated=30000000000
INFO[07-07|04:38:54.989] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: 1681338455, Cancun: 1710338135, Prague: <nil>, Osaka: <nil>, Engine: ethash, NoPruneContracts: map[0x00000000219ab540356cBB839Cbe05303d7705Fa:true]}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[07-07|04:39:26.875] Initialising Ethereum protocol           network=1
INFO[07-07|04:39:26.875] Disk storage enabled for ethash DAGs     dir=/home/smohamed/.local/share/erigon/ethash-dags count=2
INFO[07-07|04:39:26.891] Starting private RPC server              on=localhost:9090
INFO[07-07|04:39:26.891] new subscription to logs established
INFO[07-07|04:39:26.892] rpc filters: subscribing to Erigon events
INFO[07-07|04:39:26.892] new subscription to newHeaders established
INFO[07-07|04:39:26.892] New txs subscriber joined
INFO[07-07|04:39:26.893] RPC server shutting down
EROR[07-07|04:39:26.894] cli.StartRpcServer error                 err="could not start RPC api: listen tcp 127.0.0.1:8545: bind: address already in use"
INFO[07-07|04:39:26.894] Reading JWT secret                       path=/home/smohamed/.local/share/erigon/jwt.hex
INFO[07-07|04:39:26.895] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
INFO[07-07|04:39:26.926] [txpool] Started
INFO[07-07|04:39:26.930] [1/12 Snapshots] Requesting downloads
INFO[07-07|04:39:31.791] [snapshots:download] Stat                blocks=19600k indices=19600k alloc=3.4GB sys=5.0GB
INFO[07-07|04:39:34.716] New txs subscriber joined
INFO[07-07|04:39:34.716] new subscription to newHeaders established
INFO[07-07|04:41:51.388] [NewPayload] Handling new payload        height=20160927 hash=0x25ee8c32f441424da1ee4bff42938e0f94bd4affc0e78eb2356ab69e564ccc73
INFO[07-07|04:41:51.388] [EngineBlockDownloader] Downloading PoS headers... hash=0x96ef57edc0b9f7decd893157bc211e8126e5844e4c98e3eeb92a0ad3d75e3b88 requestId=0
INFO[07-07|04:42:26.869] [p2p] GoodPeers
INFO[07-07|04:42:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.0GB sys=5.0GB
INFO[07-07|04:42:26.920] [mem] memory stats                       Rss=3.9GB Size=0B Pss=3.9GB SharedClean=2.5MB SharedDirty=0B PrivateClean=342.4MB PrivateDirty=3.6GB Referenced=3.9GB Anonymous=3.6GB Swap=0B alloc=3.0GB sys=5.0GB
INFO[07-07|04:45:26.869] [p2p] GoodPeers
INFO[07-07|04:45:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=4.1GB sys=5.1GB
INFO[07-07|04:45:26.987] [mem] memory stats                       Rss=6.1GB Size=0B Pss=6.1GB SharedClean=2.5MB SharedDirty=0B PrivateClean=1.0GB PrivateDirty=5.1GB Referenced=6.1GB Anonymous=5.1GB Swap=0B alloc=4.1GB sys=5.1GB
INFO[07-07|04:48:26.869] [p2p] GoodPeers
INFO[07-07|04:48:26.895] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=4.0GB sys=5.4GB
INFO[07-07|04:48:27.022] [mem] memory stats                       Rss=6.1GB Size=0B Pss=6.1GB SharedClean=2.5MB SharedDirty=0B PrivateClean=715.2MB PrivateDirty=5.4GB Referenced=6.1GB Anonymous=5.4GB Swap=0B alloc=4.0GB sys=5.4GB
INFO[07-07|04:50:44.042] new subscription to newHeaders established
INFO[07-07|04:50:44.042] New txs subscriber joined
INFO[07-07|04:51:26.870] [p2p] GoodPeers
INFO[07-07|04:51:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|04:51:26.959] [mem] memory stats                       Rss=3.9GB Size=0B Pss=3.9GB SharedClean=2.5MB SharedDirty=0B PrivateClean=27.4MB PrivateDirty=3.8GB Referenced=3.9GB Anonymous=3.8GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|04:54:26.869] [p2p] GoodPeers
INFO[07-07|04:54:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|04:54:26.953] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=29.0MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|04:57:26.869] [p2p] GoodPeers
INFO[07-07|04:57:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|04:57:26.955] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=30.1MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|05:00:26.869] [p2p] GoodPeers
INFO[07-07|05:00:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:00:26.963] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=31.1MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|05:03:26.869] [p2p] GoodPeers
INFO[07-07|05:03:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.1GB sys=5.5GB
INFO[07-07|05:03:26.966] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=32.2MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=3.1GB sys=5.5GB
INFO[07-07|05:06:26.869] [p2p] GoodPeers
INFO[07-07|05:06:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:06:26.949] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=33.1MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|05:09:26.869] [p2p] GoodPeers
INFO[07-07|05:09:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.0GB sys=5.5GB
INFO[07-07|05:09:26.958] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=34.3MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=3.0GB sys=5.5GB
INFO[07-07|05:12:26.869] [p2p] GoodPeers
INFO[07-07|05:12:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|05:12:26.950] [mem] memory stats                       Rss=3.6GB Size=0B Pss=3.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=36.9MB PrivateDirty=3.5GB Referenced=3.6GB Anonymous=3.5GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|05:15:26.868] [p2p] GoodPeers
INFO[07-07|05:15:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.0GB sys=5.5GB
INFO[07-07|05:15:26.945] [mem] memory stats                       Rss=3.8GB Size=0B Pss=3.8GB SharedClean=2.5MB SharedDirty=0B PrivateClean=37.6MB PrivateDirty=3.7GB Referenced=3.8GB Anonymous=3.7GB Swap=0B alloc=3.0GB sys=5.5GB
INFO[07-07|05:18:26.869] [p2p] GoodPeers
INFO[07-07|05:18:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|05:18:26.949] [mem] memory stats                       Rss=4.0GB Size=0B Pss=4.0GB SharedClean=2.5MB SharedDirty=0B PrivateClean=38.5MB PrivateDirty=3.9GB Referenced=4.0GB Anonymous=3.9GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|05:21:26.869] [p2p] GoodPeers
INFO[07-07|05:21:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.0GB sys=5.5GB
INFO[07-07|05:21:26.942] [mem] memory stats                       Rss=4.2GB Size=0B Pss=4.2GB SharedClean=2.5MB SharedDirty=0B PrivateClean=39.4MB PrivateDirty=4.2GB Referenced=4.2GB Anonymous=4.2GB Swap=0B alloc=3.0GB sys=5.5GB
INFO[07-07|05:24:26.869] [p2p] GoodPeers
INFO[07-07|05:24:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|05:24:26.947] [mem] memory stats                       Rss=4.4GB Size=0B Pss=4.4GB SharedClean=2.5MB SharedDirty=0B PrivateClean=40.5MB PrivateDirty=4.3GB Referenced=4.4GB Anonymous=4.3GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|05:27:26.869] [p2p] GoodPeers
INFO[07-07|05:27:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:27:26.940] [mem] memory stats                       Rss=4.5GB Size=0B Pss=4.5GB SharedClean=2.5MB SharedDirty=0B PrivateClean=41.2MB PrivateDirty=4.5GB Referenced=4.5GB Anonymous=4.5GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|05:30:26.869] [p2p] GoodPeers
INFO[07-07|05:30:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.8GB sys=5.5GB
INFO[07-07|05:30:26.939] [mem] memory stats                       Rss=4.6GB Size=0B Pss=4.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=42.2MB PrivateDirty=4.5GB Referenced=4.6GB Anonymous=4.5GB Swap=0B alloc=2.8GB sys=5.5GB
INFO[07-07|05:33:26.869] [p2p] GoodPeers
INFO[07-07|05:33:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:33:26.939] [mem] memory stats                       Rss=4.6GB Size=0B Pss=4.6GB SharedClean=2.5MB SharedDirty=0B PrivateClean=43.1MB PrivateDirty=4.6GB Referenced=4.6GB Anonymous=4.6GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|05:36:26.869] [p2p] GoodPeers
INFO[07-07|05:36:26.893] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.1GB sys=5.5GB
INFO[07-07|05:36:26.936] [mem] memory stats                       Rss=4.7GB Size=0B Pss=4.7GB SharedClean=2.5MB SharedDirty=0B PrivateClean=44.1MB PrivateDirty=4.6GB Referenced=4.7GB Anonymous=4.6GB Swap=0B alloc=3.1GB sys=5.5GB
INFO[07-07|05:39:26.869] [p2p] GoodPeers
INFO[07-07|05:39:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:39:26.949] [mem] memory stats                       Rss=4.7GB Size=0B Pss=4.7GB SharedClean=2.5MB SharedDirty=0B PrivateClean=45.1MB PrivateDirty=4.7GB Referenced=4.7GB Anonymous=4.7GB Swap=0B alloc=2.9GB sys=5.5GB
INFO[07-07|05:42:26.869] [p2p] GoodPeers
INFO[07-07|05:42:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=3.1GB sys=5.5GB
INFO[07-07|05:42:26.936] [mem] memory stats                       Rss=4.8GB Size=0B Pss=4.8GB SharedClean=2.5MB SharedDirty=0B PrivateClean=46.0MB PrivateDirty=4.8GB Referenced=4.8GB Anonymous=4.8GB Swap=0B alloc=3.1GB sys=5.5GB
INFO[07-07|05:45:26.869] [p2p] GoodPeers
INFO[07-07|05:45:26.892] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=5.5GB
INFO[07-07|05:45:26.937] [mem] memory stats                       Rss=4.9GB Size=0B Pss=4.9GB SharedClean=2.5MB SharedDirty=0B PrivateClean=47.0MB PrivateDirty=4.8GB Referenced=4.9GB Anonymous=4.8GB Swap=0B alloc=2.9GB sys=5.5GB

**Comment by AskAlexSharov** [comment]
—internalcl
