### ISSUE TITLE
Required guidance for websocket

### ISSUE THREAD

**Issue by Parmanand0712** [ledgerwatch/erigon#11208]
The Ethereum Archive Node is currently syncing on my machine using the following command:

./build/bin/erigon --datadir=/nvme --chain=mainnet --http.addr="0.0.0.0" --http.api=eth,web3,net,debug,trace,txpool --torrent.download.rate=512mb

I am currently able to use RPC (http://localhost:8545/) on the server to retrieve information from the syncing data. However, I want to access this information using WebSocket instead. What changes do I need to make in the above command to enable WebSocket?

**Comment by somnathb1** [comment]
https://erigon.gitbook.io/erigon/advanced-usage/rpc-daemon#websocket
