### ISSUE TITLE
Windows: RPC Hijacked Connection

### ISSUE THREAD

**Issue by joesixpack** [ledgerwatch/erigon#1171]
Any explanation?  This always happens real soon after changing the RPC port and the corresponding firewall port.  I suspect something internal, possibly a go module.  Who/what would feel the need to be hijacking Ethereum nodes from Pakistan?

![image](https://user-images.githubusercontent.com/23145642/94890788-28d8b280-0435-11eb-8623-de5df0244a67.png)

**Comment by AlexeyAkhunov** [comment]
That. pretty much always happens when you open up anything that looks like JSON RPC to the wider internet. It looks for your unlocked wallets (`eth_accounts`) to steal your ETH. A good practice is not to expose this unprotected API to the internet

**Comment by mandrigin** [comment]
I see the same as soon as I published my eth supply bot.

And I saw stuff like that as soon as you publish any web service. You immediately get requests for phpmyadmin or wordpress even if you are not using php at all. 

It could be just a botnet victim, just an infected computer, that will explain any weird location.
