### ISSUE TITLE
Missing leading zero in 'r' value returned from getTransactionBy routines.

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#1221]
This curl command:

```
curl --location --request POST 'http://archive02.archivenode.io:8545' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"eth_getTransactionByBlockHashAndIndex","params":["0x785b221ec95c66579d5ae14eebe16284a769e948359615d580f02e646e93f1d5", "0x25"],"id":1 }'
```

returns different values in the `r` key from Nethermind, but same to Parity. I think Nethermind has it right.

Nethermind returns:

```
    ....
   "r": "0x0acdf839bdcb6653da60900f739076a00ecbe0059fa046933348e9b68a62a222",
    ....
```

_(64 characters and a leading zero)_

Both TurboGeth and Parity return

```
    ....
   "r": "0xacdf839bdcb6653da60900f739076a00ecbe0059fa046933348e9b68a62a222",
    ....
```
_(63 characters, no leading zero)_

As bytes, these two values are identical. As strings, when returned from RPC, they differ.

64 characters with a leading zero makes more sense to me.

There's probably differences in other values (for example 'v' and 's') returned with leading zero as well, although I have no examples.

**Comment by tjayrush** [comment]
I had a conversation with someone from Nethermind. Their documentation says that the 'r' value is DATA. Parity's and TurboGeth's says the value is a QUANTITY. I'm not sure what these values are. In the first case, 64 chars is correct. In the second case, 63 characters is correct. I'm not sure which it should be, but at least it's documented.

**Comment by tjayrush** [comment]
According to this document: https://github.com/ethereum/EIPs/blob/794830d53ac68fc510637268eb37e37749fdb0b1/EIPS/eip-1474.md#eth_gettransactionbyblockhashandindex, it's DATA.

**Comment by tjayrush** [comment]
@mandrigin Should I close this? It's nearly a year old.

**Comment by AskAlexSharov** [comment]
If it’s not causing any software incompatibility issues - then pet’s close it.
