### ISSUE TITLE
pending blocks support?

### ISSUE THREAD

**Issue by huglester** [ledgerwatch/erigon#1255]
Hello 

I am working with theGraph

and logs show this message:
 body: '{"jsonrpc":"2.0","id":48,"error":{"code":-32000,"message":"pending blocks are not supported"}}\n',

any idea if this can be somehow enabled? 
parity works here.

thanks

**Comment by AlexeyAkhunov** [comment]
pending blocks require access to the transaction pool, which RPC daemon current does not have. We will enable this functionality as a part of support for mining, which we plan to enable by the end of this year

**Comment by huglester** [comment]
thanks. probably can be closed for now?

**Comment by ericmuyser** [comment]
Would love to see this as well.

**Comment by AskAlexSharov** [comment]
FYI: 
I finished adding TxPool to RpcDaemon. 
Now working on adding pending transactions. 
Then will switch to pending blocks.

**Comment by AskAlexSharov** [comment]
@huglester , @ericmuyser , hi - It was released. (not totally in all handlers, but much where)

**Comment by mandrigin** [comment]
assume that is fixed, closing
