### ISSUE TITLE
Updates to RPC for next hard fork

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#1278]
Just documenting this here for future reference:

![image](https://user-images.githubusercontent.com/5417918/96876426-70f06100-1446-11eb-8be5-7f4e7e7ba7b9.png)

**Comment by AskAlexSharov** [comment]
@tjayrush , hi, I think you did it

**Comment by AskAlexSharov** [comment]
last part done by https://github.com/ledgerwatch/erigon/pull/2436
