### ISSUE TITLE
Support graphql

### ISSUE THREAD

**Issue by WyseNynja** [ledgerwatch/erigon#1336]
#### System information

tg version 2020.11.1-alpha

#### Feature Request

Geth has "/graphql" and "/graphql/ui" endpoints on its HTTP server that can be useful. I've recently been using it for estimating gas costs: https://gist.github.com/WyseNynja/0b8d7bedbc40baa23a83995eeb2ee284

It would be nice if turbo-geth also had this feature.

**Comment by BirdyUK** [comment]
+1

**Comment by orangeagain** [comment]
Maybe it can be implemented in rpcdeamon?

**Comment by tinoh99** [comment]
Has this been in the current erigon release?

**Comment by SLoeuillet** [comment]
Basic implementation is coming there :
https://github.com/ledgerwatch/erigon/pull/6821

**Comment by SLoeuillet** [comment]
It has been merged.
Currently only implementing 2 queries : block and chainid

Please test
