### ISSUE TITLE
turbo-geth terminated by sigkill

### ISSUE THREAD

**Issue by luisalrp** [ledgerwatch/erigon#1347]
Hi there,

#### System information

Geth version: `turbo-geth v2020.11.01`
OS & Version: DAppNode VM over unRAID passed through an unassigned 2TB SSD

#### Expected behaviour
Sync everything.

#### Actual behaviour
it just sync the number of blocks, but I think it does not validate and sync them and it continuously restarts prompting terminating by sigkill.
![image](https://user-images.githubusercontent.com/31384138/98820048-f22b8a00-242d-11eb-97b9-f919f1f03cb0.png)

**Comment by mandrigin** [comment]
Hmm, it looks like it was killed when it was extracting block hashes... Maybe some CPU quota?

**Comment by mandrigin** [comment]
@luisalrp is it always killed on the same log line? (`[2/14 BlockHashes] ....`)

**Comment by luisalrp** [comment]
Hello @mandrigin 

I am running it in a VM over unRAID with 6 CPUs of the 8 the whole i7 has.

It is not always killed in the same log line. Here is an example killed after `[1/14 Headers] Imported new block headers count=8040...`

I attached the log file:
[logs-dappnode-package-DAppNodePackage-turbo-geth.dnp.dappnode.eth.txt](https://github.com/ledgerwatch/turbo-geth/files/5542666/logs-dappnode-package-DAppNodePackage-turbo-geth.dnp.dappnode.eth.txt)

And a small piece of the log file:
`INFO [11-11|17:25:41.554] [1/14 Headers] Imported new block headers count=16536 elapsed=35.606s   number=311448 hash="142c5a…1b0106" age=5y2mo1w
INFO [11-11|17:25:59.847] [1/14 Headers] Imported new block headers count=8040  elapsed=18.279s   number=319488 hash="bc83e9…72d39f" age=5y2mo1w
INFO [11-11|17:26:37.366] [1/14 Headers] Imported new block headers count=16536 elapsed=37.464s   number=336024 hash="5faaf6…9519b5" age=5y2mo4d
INFO [11-11|17:26:54.778] New local node record                    seq=4 id=2f3a8c881863ef17 ip=90.164.252.107 udp=30303 tcp=30303
INFO [11-11|17:27:04.085] [1/14 Headers] Imported new block headers count=8040  elapsed=26.632s   number=344064 hash="c90867…549468" age=5y2mo2d
2020-11-11 17:27:22,855 INFO exited: tg (terminated by SIGKILL; not expected)
WARN [11-11|17:27:22.820] received unexpected error from server after CloseSend err="rpc error: code = Unavailable desc = transport is closing"
WARN [11-11|17:27:22.826] Served                                   conn=172.33.1.7:38656 method=eth_blockNumber reqid=2016 t=2.397986491s err="rpc error: code = Unavailable desc = transport is closing"`

Thanks!

**Comment by AlexeyAkhunov** [comment]
It could be that the software that runs in the DappNode package tries to monitor TG and if it does not respond for some time, tries to kill it?

**Comment by AskAlexSharov** [comment]
close this issue because too old, probably everything changed already. feel free to re-open if need
