### ISSUE TITLE
Add blockHash to RPC filters

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#1366]
Keeping track of this: https://eips.ethereum.org/EIPS/eip-234 which just went into last call status.

**Comment by perama-v** [comment]
I made the following call:

```
curl -s --location --request POST --header 'Content-Type:  application/json' --data-raw '{ "jsonrpc": "2.0", "id":"1", "method": "eth_getLogs", "params": [{"blockHash": "0xbdbed56b3a54cce6055fbb507d7270bc4ea9bfecb95048c35d8375624b752b77"}] }' http://localhost:8545
```

Following the example in the link to the EIP above. The call return the block appropriately. 

The call to a non-existent hash:

```
curl -s --location --request POST --header 'Content-Type:  application/json' --data-raw '{ "jsonrpc": "2.0", "id":"1", "method": "eth_getLogs", "params": [{"blockHash": "0xbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0c"}] }' http://localhost:8545
```

Returned:

```
{"jsonrpc":"2.0","id":"1","error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field input.blockHash of type common.Hash"}}
```

Rather than the expected message of the form:

'If no block exists with that hash then an error should be returned with a code of -32000, a message of "Block not found." and a data of "0xbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0cbl0c"'

**Comment by AskAlexSharov** [comment]
@perama-v , hi. it's not "non-existing" hash, it's invalid hash. Hash can have only characters from 0-9 and a-f (ff stands for 256 in hexary base, and 256 is the maximum digit which can be stored in 1 byte). Character `l` is not allowed.

**Comment by perama-v** [comment]
Oh, that was silly of me. Okay, this valid but non-existing hash:

```
curl -s --location --request POST --header 'Content-Type:  application/json' --data-raw '{ "jsonrpc": "2.0", "id":"1", "method": "eth_getLogs", "params": [{"blockHash": "0xbdbed56b3a54cce6055fbb507d7270bc4ea9bfecb95048c35d8375624b752b78"}] }' http://localhost:8545
```
Returns the correct response:
```
{"jsonrpc":"2.0","id":"1","error":{"code":-32000,"message":"block not found: bdbed56b3a54cce6055fbb507d7270bc4ea9bfecb95048c35d8375624b752b78"}}
```
So it looks good to me.

**Comment by AskAlexSharov** [comment]
You are welcome

**Comment by tjayrush** [comment]
I'm going to close this issue. It looks like it's working as it should.
