### ISSUE TITLE
Minor issue with shutting down

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#1379]
This is a minor issue, but I thought I'd document it. It feels a lot worse than it is I'm sure.

When shutting down, TG responds to the control+C, but then says "Ethereum peer registration failed" which sound ominous. It further says "Looking for peers" which is also seems ominous.

Perhaps it would be better if, once TG knows it's shutting down, it no longer reports that it's trying to connect to peers.

![image](https://user-images.githubusercontent.com/5417918/100681789-878db000-3342-11eb-9f39-e56acd2fd793.png)

**Comment by cyberbono3** [comment]
I will take a look at it

**Comment by AskAlexSharov** [comment]
i think it's fixed now.
