### ISSUE TITLE
rpcdaemon http error code when tg unavailable

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1397]
Not sure what you guys think about this, but, when the RPC daemon can't talk to tg it returns an error saying as much, however the HTTP status code is 200

I'm wondering if that's the desired behavior instead of say returning a 503 or something?

**Comment by MysticRyuujin** [comment]
Also, the error that returns gives the locally significant IP address of the configured tg endpoint. Which ideally isn't leaked in this manner.

**Comment by mandrigin** [comment]
So let's reformulate it this way.
use the grpc health-check between the rpc daemon and erigon core (`./bin/erigon`) and if the erigon is unhealthy, return 503 error status.
Also, the IP address should not be returned in this error response.
