### ISSUE TITLE
RPC trace_transaction - method handler crashes

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#1407]
**Only happens against the call-trace branch**

This curl command:

```[bash]
curl -s --location --request POST --header 'Content-Type:  application/json' --data-raw '{"jsonrpc":  "2.0","method":  "trace_transaction","params":  ["0x88162c6bcbb040fd8f6676fe336f83d7a27a5765b18bfce524beea2a0e107159"],"id":  "1"}' http://localhost:8545
```

returns:

```
{
  "error": {
    "code": -32000,
    "message": "method handler crashed"
  },
  "id": "1",
  "jsonrpc": "2.0"
}
```

The error occurs in this code block: https://github.com/ledgerwatch/turbo-geth/blob/trace-call/cmd/rpcdaemon/commands/trace_types.go#L181

**Comment by twilightrus** [comment]
eth_call also has been crashed

**Comment by AskAlexSharov** [comment]
@twilightrus do you have logs?

**Comment by perama-v** [comment]
I have tested the above `trace_transaction` with `erigon version 2021.07.2-alpha`  (https://github.com/ledgerwatch/erigon/commit/5eaf4c8cc371a14358f85e2b747c0ad8116a929a) and receive a good response, with no `method handler crashed` error.

**Comment by AskAlexSharov** [comment]
closing then
