### ISSUE TITLE
Tracing has incorrect gasUsed for value transfers

### ISSUE THREAD

**Issue by naddison36** [ledgerwatch/erigon#1436]
I'm seeing incorrect `gasUsed` amounts for ether value transfers from tracing

An examples is this Uniswap example that removes ether liquidity [0xed080a06ef45da6f2f09e8371b9f2f7f9c5784ac431f07f55d32cf2fee62a4cc](https://etherscan.io/tx/0xed080a06ef45da6f2f09e8371b9f2f7f9c5784ac431f07f55d32cf2fee62a4cc)

The JSON RPC call I used
```json
{
    "jsonrpc":"2.0",
    "method":"debug_traceTransaction",
    "params":["0xed080a06ef45da6f2f09e8371b9f2f7f9c5784ac431f07f55d32cf2fee62a4cc", {"tracer": "callTracer"}],
    "id":1
}
```

The last call in the trace is
```json
{
    "type": "CALL",
    "from": "0x7a250d5630b4cf539739df2c5dacb4c659f2488d",
    "to": "0xe4bef064c912bc95c404850019909efe8d357716",
    "value": "0xa781797b5b33caf",
    "gas": "0xdeadbeef",
    "gasUsed": "0xdead4a90",
    "input": "0x",
    "output": "0x"
}
```

The 0xdead4a90 (3,735,898,768)  `gasUsed` can't be right as the transaction only used 181,212 gas

The code the initiated the last value transfer is
```Solidity
function safeTransferETH(address to, uint value) internal {
    (bool success,) = to.call{value:value}(new bytes(0));
    require(success, 'TransferHelper: ETH_TRANSFER_FAILED');
}
```

**Comment by mandrigin** [comment]
@tjayrush is that still the issue?
