### ISSUE TITLE
debug_traceTransaction callTracer execution timeout

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1468]
The following results in an `execution timeout`

```
curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x6dc268706818d1e6503739950abc5ba2211fc6b451e54244da7b1e226b12e027",{"tracer":"callTracer"}],"id":1}'
```

It's a ridiculous transaction so I guess I'm not surprised lol

I went ahead and did a pprof profile of both TG and rpcdaemon during the execution, which is only about 5 seconds.

TG:
![tg](https://user-images.githubusercontent.com/8877131/107036175-d01c7c00-677e-11eb-94ef-ed94137fff53.png)

RPCDAEMON:
![rpcdaemon](https://user-images.githubusercontent.com/8877131/107036198-d7438a00-677e-11eb-8f40-7840f3f2aedb.png)

**Comment by AlexeyAkhunov** [comment]
Is `callTracer` supposed to mimic `trace_call` of OpenEthereum? These are now being re-done without using javascript engine

**Comment by MysticRyuujin** [comment]
I don't know. It was reported to me over in Archive Node and I reproduced it.

I though it was strange that it only takes ~5 seconds but it times out. I assume this *IS* JavaScript, and Nethermind doesn't support it at all.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2373

**Comment by AskAlexSharov** [comment]
and yes, debug_traceTransaction using JS tracer
