### ISSUE TITLE
rpcdaemon doesn't log chaindata success or fail in dual mode

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1605]
rpcdaemon does not log any success or failure of correctly configuring the chaindata folder...

If I run rpcdaemon with only `--private.api.addr="localhost:9090"` all is well.

If I run rpcdaemon with `--private.api.addr="localhost:9090"` AND `--chaindata="/incorrect/path"` all is well :-1: there is no log indicating that it failed to open the chandata path, it just does its thing.

If I run rpcdaemon with `--private.api.addr="localhost:9090"` AND `--chaindata="/correct/path/chaindata"` all is well :+1: but there's no log or indication that it was correctly configured or that it's operating in dual mode :-1: 

Hopefully this make sense.

I kinda feel like the `--datadir="/data/turbo-geth/datadir"` flag should be consistent with the rpcdaemon flag, but as far as I can tell I need to use `--chaindata="/data/turbo-geth/datadir/tg/chaindata"` which is a little more confusing.

**Comment by AskAlexSharov** [comment]
Added by: https://github.com/ledgerwatch/turbo-geth/pull/1747
