### ISSUE TITLE
Ephemeral local fork mode

### ISSUE THREAD

**Issue by banteg** [ledgerwatch/erigon#1613]
# Rationale

A very common pattern ([1](https://eth-brownie.readthedocs.io/en/latest/network-management.html), [2](https://hardhat.org/guides/mainnet-forking.html)) for testing contract integrations is to run them against a forked mainnet environment using [ganache-cli](https://github.com/trufflesuite/ganache-cli), [hardhat](https://hardhat.org/) or [hevm](https://dapp.tools/hevm/). It would be useful to have this functionality built in the client itself as it would work much faster and would follow consensus rules more precisely.

# Implementation

Similarly to rpcdaemon, a process could connect to the existing database, and maintain an ephemeral overlay database on top.

Additionally, it'll need to support ability to control chain state, advance time and unlock arbitrary accounts. [Hardhat](https://hardhat.org/hardhat-network/#hardhat-network-methods) and [ganache-cli](https://github.com/trufflesuite/ganache-cli#custom-methods) use custom RPC methods and [hevm](https://github.com/dapphub/dapptools/tree/master/src/hevm#cheat-codes) uses cheat codes.

**Comment by AlexeyAkhunov** [comment]
Maintaining ephemeral database while still staying in sync with the mainnet is going to require opening a long-lived read-transaction, and cause a rapid database bloat. However, such ephemeral database would be possible if turbo-geth stopped being in sync with the mainnet and just "froze" itself. Then, only ephemeral part will grow, until it is discarded, at which point turbo-geth proceeds with catching up again

**Comment by AskAlexSharov** [comment]
@AlexeyAkhunov 1. We don’t need transaction if can use GetAsOf 2. Does this require writable ephemeral overlay?

**Comment by AlexeyAkhunov** [comment]
@AskAlexSharov As far as I understand, the overlay is indeed writable. Yes, I think you are right, we could use `GetAsOf` to create an appearance of a fork without a long-running read transaction

**Comment by kushalbabel** [comment]
Hi @AlexeyAkhunov @banteg @AskAlexSharov , was there any further discussion about supporting mainnet forks in the client? Or is it shelved for now?

**Comment by riordant** [comment]
Would also like to know if this is a planned feature.  Existing fork modes are comparatively very slow.

**Comment by mandrigin** [comment]
@AlexeyAkhunov @banteg 
> such ephemeral database would be possible if turbo-geth stopped being in sync with the mainnet and just "froze" itself

isn't that how existing forks work? they freeze the DB, sync tx pool and mine on their own.

**Comment by mandrigin** [comment]
I agree it could be a very cool feature, if we can piggy-back on our dev network

**Comment by AskAlexSharov** [comment]
@mandrigin FYI: 
1. our mining now doesn't use dbRwTransaction, it using only "mutation" object. FunnyGiulio worked on this feature.
Maybe 1. can be used for this feature (if don't need store ephemeral fork in db

**Comment by mandrigin** [comment]
could be, but I need someone @banteg do you need this to be persistent across Erigon launches?

**Comment by beejiujitsu** [comment]
+1 this would be helpful.

At least from my limited point of view, stateless ephemeral forks would be a good first step.

**Comment by sambacha** [comment]
> +1 this would be helpful.
> 
> At least from my limited point of view, stateless ephemeral forks would be a good first step.

This is the only viable method in reality.

**Comment by naddison36** [comment]
This would be a fantastic feature. Tools like [tx2uml](https://github.com/naddison36/tx2uml) require transaction traces like `traceTransaction` and `debug_traceTransaction`.
For value transfer diagrams, tx2uml uses `debug_traceTransaction` with a custom EVM tracer. This is not currently supported by Foundry's Anvil, Hardhat or Ganache. Ideally, Erigon could be run in fork mode locally and transaction traces run against the local node.
