### ISSUE TITLE
Problems with trace_filter

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/erigon#1709]
#### System information

Geth version: v2021-04-01
OS & Version: Ubuntu 18.04 LTS
Commit hash : e47ed7c

#### Expected behaviour
Turbogeth excecutes trace_filter requests

#### Actual behaviour
Apr 10 05:23:01.812 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:31:21.007 INFO Syncing 31 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 31, blocks_behind: 31, latest_block_head: 12209716, current_block_head: 12209685, network_name: mainnet, component: BlockIngestor
Apr 10 05:31:38.260 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(RPC error: Error { code: ServerError(-32000), message: "transaction e130df1634f9d7bed033fdf07948c5c1a1dd2d7dd7824b25a3006d944cb332d2 failed: nonce too high: address 0x826d891dFeEf744a321E490456Bb23e044028A31, tx: 28 state: 0", data: None }
Caused by:
    Server error: transaction e130df1634f9d7bed033fdf07948c5c1a1dd2d7dd7824b25a3006d944cb332d2 failed: nonce too high: address 0x826d891dFeEf744a321E490456Bb23e044028A31, tx: 28 state: 0), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:33:38.282 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:40:21.819 INFO Syncing 50 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 50, blocks_behind: 53, latest_block_head: 12209769, current_block_head: 12209716, network_name: mainnet, component: BlockIngestor
Apr 10 05:44:26.466 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(RPC error: Error { code: ServerError(-32000), message: "transaction addb1056d7f88a4577dceff0b26c799093fe65bc9c6d4750f8d78d6e65190cf9 failed: nonce too high: address 0xBE9fE925e53fa70868d9Ce1A964e3D43976f6D47, tx: 11 state: 0", data: None }
Caused by:
    Server error: transaction addb1056d7f88a4577dceff0b26c799093fe65bc9c6d4750f8d78d6e65190cf9 failed: nonce too high: address 0xBE9fE925e53fa70868d9Ce1A964e3D43976f6D47, tx: 11 state: 0), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:46:26.484 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:52:55.453 INFO Syncing 50 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 50, blocks_behind: 56, latest_block_head: 12209825, current_block_head: 12209769, network_name: mainnet, component: BlockIngestor
Apr 10 05:56:22.365 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(Decoder error: Error("data did not match any variant of untagged enum Action", line: 0, column: 0)), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 05:58:22.384 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:04:53.270 INFO Syncing 44 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 44, blocks_behind: 44, latest_block_head: 12209869, current_block_head: 12209825, network_name: mainnet, component: BlockIngestor
Apr 10 06:08:52.463 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(Decoder error: Error("data did not match any variant of untagged enum Action", line: 0, column: 0)), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:10:52.481 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:16:42.512 INFO Syncing 50 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 50, blocks_behind: 66, latest_block_head: 12209935, current_block_head: 12209869, network_name: mainnet, component: BlockIngestor
Apr 10 06:20:54.632 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(Decoder error: Error("data did not match any variant of untagged enum Action", line: 0, column: 0)), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:22:54.654 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:26:31.230 INFO Syncing 49 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 49, blocks_behind: 49, latest_block_head: 12209984, current_block_head: 12209935, network_name: mainnet, component: BlockIngestor
Apr 10 06:32:29.226 WARN Trying again after trace_filter RPC call failed (attempt #10) with result Err(RPC error: Error { code: ServerError(-32000), message: "transaction fad82932e37e22c4f1e17caf02075b1cdc4a9bca0860cc5a452eeff435dfa990 failed: nonce too high: address 0x73952F60Df25C4389e6afCFA4EBbDFA093e54B73, tx: 61294 state: 0", data: None }
Caused by:
    Server error: transaction fad82932e37e22c4f1e17caf02075b1cdc4a9bca0860cc5a452eeff435dfa990 failed: nonce too high: address 0x73952F60Df25C4389e6afCFA4EBbDFA093e54B73, tx: 61294 state: 0), subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream
Apr 10 06:34:29.243 INFO Scanning blocks [9247083, 9247083], range_size: 1, subgraph_id: QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj, component: SubgraphInstanceManager > BlockStream

#### Steps to reproduce the behaviour
Setup graph-node (including postres)
Use ipfs https://api.thegraph.com/ipfs/
Use turbogeth as eth mainnet archive

Instruct graph-node to index UMA subgraph
http post 127.0.0.1:48020 jsonrpc="2.0" method="subgraph_create" id="1" params:='{"name": "synctime/fjfkT68Axj"}'
http post 127.0.0.1:48020 jsonrpc="2.0" id="1" method="subgraph_deploy" params:='{"name": "synctime/fjfkT68Axj", "ipfs_hash": "QmXRiGnQM9EVeB7enk2jYCs6R1N4c1QnoeNGfjfkT68Axj", "node_id":"testnet_index01"}'

EDITED : commands had wrong ipfs hashes

**Comment by koen84** [comment]
I took the wrong commands from my history and have updated "steps to reproduce".

**Comment by AlexeyAkhunov** [comment]
Should all be working now if you do fresh resync
