### ISSUE TITLE
How can I start a private network by turbo geth using clique consensus?

### ISSUE THREAD

**Issue by guagualvcha** [ledgerwatch/erigon#1724]
It looks like mining have to wait for syncing for peers, but for single node in private network, the miner just stuck

**Comment by AlexeyAkhunov** [comment]
Thanks @guagualvcha. Yes, I am aware of this, because I am trying to do the same thing. will return to it once I've finished my current PR about integrating EIP-1559.
After that, I will be working on setting up turbo-mine devnet where we can test different things about mining

**Comment by AlexeyAkhunov** [comment]
For Clique, the issue has the same route cause

**Comment by guagualvcha** [comment]
Hi, @AlexeyAkhunov, thanks for the quick response.  I believe the integration with EIP-1559 should be a huge work,  what would be the ETA?  Actually, my team is willing to contribute to speed this up, we are eager to use turbo geth. Thanks.

**Comment by guagualvcha** [comment]
hi, @AlexeyAkhunov  any progress on this issue?

**Comment by AskAlexSharov** [comment]
Looks a bit solved in https://github.com/ledgerwatch/erigon/issues/2588
