### ISSUE TITLE
headers.v2 download with external sentry hangs idle

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#1743]
#### System information

OS & Version: macOS 10.15.6
Commit hash : 368f37a02ffa71eb9432695aa18ad63886e8652a

#### Expected behaviour

The block headers start to be downloaded and progress is reported incrementally.

#### Actual behaviour

The data dir is created with about 3Mb, and then nothing happens.
Every 30 sec it prints:

    INFO [04-18|17:54:49.879] [1/3 Headers] Processing headers...      from=0

#### Steps to reproduce the behaviour

Checkout [rust sentry](https://github.com/rust-ethereum/sentry), and `cargo run` it.

Run "download.v2" with external sentry:

     make
    ./build/bin/tg --download.v2 --datadir ../tgdata/goerli --chain goerli --sentry.api.addr localhost:8000

(old) Run [headers download with external sentry](https://github.com/ledgerwatch/turbo-geth/tree/master/cmd/headers#running-with-an-external-p2p-sentry):

    make headers
    ./build/bin/headers download --datadir ../tgdata/goerli --chain goerli --sentry.api.addr localhost:8000

#### Debugging

[stage_headers_new.go HeadersForward has a loop](https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_headers_new.go#L91) where:
- [`req = hd.RequestMoreHeaders`](https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_headers_new.go#L93) always returns nil (due to `hd.anchorQueue.Len() == 0`)
- [`req = hd.RequestSkeleton`](https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_headers_new.go#L114) returns nil (due to `hd.topSeenHeight < hd.highestInDb+stride`, as topSeenHeight = 0 and highestInDb = 0)
- the loop will pause for [1 sec timer](https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_headers_new.go#L137) and repeat
thus `headerReqSend` is never called!

**Comment by battlmonstr** [comment]
The problem likely is that the rust sentry never finds any peers:
https://github.com/rust-ethereum/sentry/issues/6

**Comment by battlmonstr** [comment]
A new roadblock:

When connected to a geth node synced with the "fast" strategy, the geth node requests GetBlockHeaders, and doesn't get any response from the downloader within 15 sec. This is treated as "useless peer" by geth, and it disconnects.

(aka "checkpoint challenge")

**Comment by AskAlexSharov** [comment]
@AlexeyAkhunov , did we fix this?
