### ISSUE TITLE
Binance Smart Chain support

### ISSUE THREAD

**Issue by BennyTheDev** [ledgerwatch/erigon#1803]
# Rationale

BSC's geth fork cannot handle the amount of data properly.
Due to the use of leveldb vs. amount of tx per block, log queries are seriously harming performance.
Looking back a couple of 1000 blocks can already bring down powerful machines.

# Implementation

Compare BSC's geth fork with the vanilla ones, spot the difference and try to re-implement into turbo-geth.
Maybe getting in touch with the BSC dev team could speed things up.

# Benefit

Improved awareness about turbo-geth.

**Comment by fellu** [comment]
Is there a diff somewhere how bsc's geth is different from the eth one? Was thinking on trying to run bsc chain with erigon, but did not had time yet to check what has to be changed.

**Comment by AlexeyAkhunov** [comment]
It is done in `devel`
