### ISSUE TITLE
eth_getLogs not working on block number dispatched by newBlockHeader subscription

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/erigon#1822]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

After receiving a `newBlockHeader` event, all calls related to the provided block number should work

#### Actual behaviour

`eth_getLogs` not working in some cases

#### Steps to reproduce the behaviour

use `provider.on('blocks', callback)` with ethers.js and run an `eth_getLogs` call right afterwards with provided block number.

#### Backtrace

`rpcdaemon`
````
ERROR[04-26|16:54:00.302] Missing body but have receipt            hash="05cc1d…aeb12f" number=12317165
WARN [04-26|16:54:00.302] Served                                   conn=172.18.0.6:40278 method=eth_getLogs reqid=63 t=1.872633ms err="block 05cc1de71b1ca86a587c368755deb2258c0dbf914db0e30a0c6ffd2055aeb12f not found"
````

**Comment by AskAlexSharov** [comment]
Thank you. 
Of course it's a bit incorrect - to expect that logs will ready immediately after receiving new header. But I will try to fix, because looks like everybody using NewHeader event as "block downloaded and processed and all other indices created and any other work is done" event.

**Comment by AskAlexSharov** [comment]
"Missing body but have receipt" - oh, it's something really weird. Let's investigate.

**Comment by AskAlexSharov** [comment]
Do you have any logs before this line?

**Comment by 0xD34D81** [comment]
I don’t have the logs and I tried reproducing yesterday with a simpler script but were unable to get the same result, will run my stack again to see if I can get the error again !

**Comment by AskAlexSharov** [comment]
So, it means - probably it disappear after time. Thank you. Need to think.

**Comment by AlexeyAkhunov** [comment]
> So, it means - probably it disappear after time. Thank you. Need to think.

I suspect this problem happens during the initial stage (straight after restart), until we get into "runStagesInOneTransaction" mode. Perhaps we should not fire block notifications from Finish stage when we are not in that mode?

**Comment by AskAlexSharov** [comment]
But error is: “found receipt and not found block body”

**Comment by AlexeyAkhunov** [comment]
> But error is: “found receipt and not found block body”

Perhaps because the subscription is made to pending blocks? I am not sure what `provider.on('blocks', callback)` do, and how pending blocks subscription works

**Comment by 0xD34D81** [comment]
It’s a “newBlockHeader” subscription under the hood, should be triggered when new included block is received and available for queries.
Equivalent would be to poll eth_getBlockNumber to get the latest available one

**Comment by AlexeyAkhunov** [comment]
We've got to try to find way to reproduce it at least semi-reliably. @0xD34D81 Can you include your js script in the comment above?

**Comment by 0xD34D81** [comment]
Trying to reproduce atm, will keep you updated if anything works !

**Comment by 0xD34D81** [comment]
I came accross this error again while running my full stack but when trying to reproduce in a small script I cannot see the error again.

**Comment by AskAlexSharov** [comment]
Hi. In last release was fixes for this issue - help to check please.
