### ISSUE TITLE
Location of IPC endpoint

### ISSUE THREAD

**Issue by pcko1** [ledgerwatch/erigon#1977]
Coming from a `Geth` client, what is the path of the IPC endpoint after running `./build/bin/tg --datadir /my/data/dir` ?

Using `Geth`, I could specify the path via the optional argument `--ipcpath`.

**Comment by AlexeyAkhunov** [comment]
There is no IPC endpoint. What are you using it for?

**Comment by pcko1** [comment]
I was hoping it was available after reading [this](https://github.com/ledgerwatch/erigon/blob/master/node/config.go#L76-L80).

I used to connect to my `Geth` node via IPC as it's the "fastest and most secure" option (citing `web3.py` [docs](https://web3py.readthedocs.io/en/stable/providers.html#choosing-how-to-connect-to-your-node)).

However, the truth is that my `web3.py` client doesn't seem to connect the RPC endpoint (`localhost:8545`) after I start the RPCDaemon, that's why I was hoping for an IPC alternative.
