### ISSUE TITLE
Sometimes it gets stuck on stage 1 until restart

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#2001]
Using: 2021.05.03 tag, macos

The sync cycles work fine, but then suddenly it gets stuck in stage 1 and only unstuck after a restart.

I'm attaching 2 logs, one of them got stuck just after start, the other one got stuck over the night, but a restart seemed to unstuck it immediately.

**Comment by wmitsuda** [comment]
[otherlog.txt](https://github.com/ledgerwatch/erigon/files/6528892/otherlog.txt)
[lastlog.txt](https://github.com/ledgerwatch/erigon/files/6528894/lastlog.txt)

**Comment by wmitsuda** [comment]
Just adding that I've seem this happen today while using my laptop running erigon in a terminal in background, so it doesn't appear to be related to macos sleeping or something like that. Nothing extraordinary in the logs.

**Comment by wmitsuda** [comment]
[log.txt](https://github.com/ledgerwatch/erigon/files/6536409/log.txt)

**Comment by AskAlexSharov** [comment]
We fixed couple reasons in last releases. Feel free to re-open if it's still happening.
