### ISSUE TITLE
Display tx/second in addition to blk/second when logging progress

### ISSUE THREAD

**Issue by gebrits** [ledgerwatch/erigon#2020]
# Rationale

Requesting to show `tx/second` in addition to `blk/second` when at step [7/17]

This is useful because `tx/second` should be (relatively) constant over time. 

This ensures that users that monitor progress can see rather consistent progress even when there's a lot of tx/blocks to chew through. This will likely result in less people getting worried about progress. ("will this ever finish?"). 

# Implementation

stats should be readily available so trivial to implement

**Comment by LogvinovLeon** [comment]
Should we rather display MGas/s like geth does. Transactions are different and time is mostly spent on reading and writing storage which is better reflected by gas.

**Comment by AskAlexSharov** [comment]
@LogvinovLeon - is it useful for users?

**Comment by LogvinovLeon** [comment]
I don't think it's high pri at all. Just pointing it out as it's relevant in this issue.
That's how geth does it:
`Imported new chain segment               blocks=1  txs=188  mgas=14.904  elapsed=457.194ms mgasps=32.600   number=12586668 hash="3e5d87…d244bd" dirty=0.00B`

**Comment by AndreaLanfranchi** [comment]
As of release 2021.06.02 this has been implemented.
This is actually more relevant for `[7/18 Execution]` stage but don't expect a "roughly constant number of tx/second".
Both block and tx per second are meant to decay as the state grows and DB has to pull reads from pages more and more apart.
