### ISSUE TITLE
Feature request: pushing latest docker build to docker hub

### ISSUE THREAD

**Issue by renaynay** [ledgerwatch/erigon#2029]
The geth team is currently trying to integrate the erigon client into [hive](https://github.com/ethereum/hive) (our testing rig) so that we can run behaviour / spec conformance tests on erigon along with the rest of the eth1 clients as part of our CI. The easiest way for us to integrate erigon would be if there were an official up-to-date docker image on [dockerhub](https://hub.docker.com/) to pull from as a base so that we can build on top of it to make it runnable as part of the hive suite.

**Comment by KaiRo-at** [comment]
This would also be very helpful for anyone trying to run a node themselves without needing to build it themselves, esp. in production environments where you usually do not want to run any building on production machines.

**Comment by gg22mm** [comment]
docker is good!

**Comment by AskAlexSharov** [comment]
done https://hub.docker.com/r/thorax/erigon
