### ISSUE TITLE
Feature request: ability to initialise erigon with a genesis file and import a given chain

### ISSUE THREAD

**Issue by renaynay** [ledgerwatch/erigon#2030]
Related to the reasoning mentioned in #2029, it would also be useful to be able to initialise erigon with a genesis file and also import a chain file (similar to `geth init <genesis.json>` and `geth import <chain.rlp>`) . This is an important feature for testing the client generally and, without it, it will not be possible to plug it into the [hive](https://github.com/ethereum/hive) testing rig.

**Comment by Bhargavasomu** [comment]
@AskAlexSharov is this request still relevant, given that we have a specific dev chain? Thanks.

**Comment by AskAlexSharov** [comment]
Yes. Use would like to do next thing (without Erigon re-compile): "I wanna start my own network with my own genesis" ("custom chainConfig" we leave out of scope for now). 
So I create new node with `--chain dev` and `--networkid` flags and with my genesis.json; Invite some friends - start some simulation for research reasons. 

We wanna such articles to be valid for Erigon: https://medium.com/datawallet-blog/how-to-deploy-a-local-private-ethereum-blockchain-c2b497f068f4

**Comment by Bhargavasomu** [comment]
I have started working on this.

**Comment by Bhargavasomu** [comment]
`erigon import` has been implemented as part of [this](https://github.com/ledgerwatch/erigon/pull/3298) PR.

I'm currently working on adding erigon to Hive. Will keep you posted. Thanks.
