### ISSUE TITLE
Intersection mode for trace_filter

### ISSUE THREAD

**Issue by banteg** [ledgerwatch/erigon#2119]
Currently `fromAddress` and `toAddress` arguments of `trace_filter` work as union, yielding results relating to either set of addresses. It would be useful to have an option to intersect the indexes and narrow down the amount of traces to compute. An example of this would be finding all calls from one set of addresses to another.

Another useful thing could another index which allows filtering by call input. Storing four byte function signature would be enough for practical reasons.

**Comment by AlexeyAkhunov** [comment]
Thanks! If you suggest the format of input arguments for `trace_filter` for the intersection, it should be not hard to add it. For the extra index, it is also not hard, however it would require a bit more coding and another `storage-mode` option. And in that case, we would need a suggestion of how this would be used in a request

**Comment by mandrigin** [comment]
Let's do the `trace_filter` intersection mode as a bounty. We can add an optional parameter: "mode" that has 2 values "union"(default) and "intersection" (what @banteg described).

**Comment by awskii** [comment]
I'm not sure I used correct way to generate test data, so correct me please.

**Comment by mandrigin** [comment]
closed by #3167 

@banteg feel free to try it out when you have time :)

**Comment by awskii** [comment]
Due to task explanations by @AlexeyAkhunov  https://github.com/ledgerwatch/erigon/pull/3167#issuecomment-1014241624 I reimplemented filter as long as incorrect test.
