### ISSUE TITLE
Memory consumption is high? (first stages)

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2123]
<img width="1265" alt="Screen Shot 2021-06-08 at 18 06 43" src="https://user-images.githubusercontent.com/46885206/121174748-72ab4f80-c884-11eb-8445-b38344d13f83.png">

**Comment by AlexeyAkhunov** [comment]
Yes, I would like to confirm that most memory is actually taken by the block bodies pending to be inserted into the database. Default window is 64k bodies

**Comment by AskAlexSharov** [comment]
After stage_senders mem goes down to 1.5Gb 
<img width="1847" alt="Screen Shot 2021-06-09 at 11 24 29" src="https://user-images.githubusercontent.com/46885206/121293234-79ce6e00-c915-11eb-91dd-a61d47d78ea3.png">

**Comment by AskAlexSharov** [comment]
and probably this is reason of "execution stage is slower on dv2" from #testing discord channel
