### ISSUE TITLE
`evm` unsuitable for fuzzing

### ISSUE THREAD

**Issue by holiman** [ledgerwatch/erigon#2130]
Tested with commit 40eaf77eb87d961fee56873fecee74871c3da2bd

I've been trying to incorporate the erigon `evm` tool into the same fuzzing framework we use for the other vms, and there are two things which make it problematic: 

1. The `evm` does not exit after running a `statetest`. So performing `evm statetest <file.json>` does not exit the process until `ctrl-c` is invoked. 
2. The `evm` output contains the wrong stateroot in the `json` output -- it emits the expected root, not the actual root. While fuzzing, we set the stateroot to `0x000...` when generating the test, we ignore the 'fail'/'success', and instead compare the opcodes and the stateroot between the vms. 

Example of the latter problem: 

This is fine: the "normal" output tells me that it got the root `2a401d8f1c4c74b9a68ccff4c483cf28fd224450843717d44db8ef2aaf251760`:
```
./evm statetest ~/consensus_err/00000002-storagefuzz-0.json
[
  {
    "name": "00000002-storagefuzz-0",
    "pass": false,
    "fork": "Berlin",
    "error": "post state root mismatch: got 2a401d8f1c4c74b9a68ccff4c483cf28fd224450843717d44db8ef2aaf251760, want 0000000000000000000000000000000000000000000000000000000000000000"
  }
]
```  
Alas the `json`: 
```
./evm --json --nomemory statetest ~/consensus_err/00000002-storagefuzz-0.json 
....
{"pc":4351,"op":0,"gas":"0x12a8","gasCost":"0x0","memory":"0x","memSize":3616,"stack":[],"returnStack":null,"returnData":"0x","depth":1,"refund":222200,"opName":"STOP","error":""}
{"output":"","gasUsed":"0x79a940","time":898044494}
{"stateRoot": "0000000000000000000000000000000000000000000000000000000000000000"}
[
  {
    "name": "00000002-storagefuzz-0",
    "pass": false,
    "fork": "Berlin",
    "error": "post state root mismatch: got 2a401d8f1c4c74b9a68ccff4c483cf28fd224450843717d44db8ef2aaf251760, want 0000000000000000000000000000000000000000000000000000000000000000"
  }
]

```
What I expect: 
```
./evm --json --nomemory statetest ~/consensus_err/00000002-storagefuzz-0.json 
....
{"pc":4351,"op":0,"gas":"0x12a8","gasCost":"0x0","memory":"0x","memSize":3616,"stack":[],"returnStack":null,"returnData":"0x","depth":1,"refund":222200,"opName":"STOP","error":""}
{"output":"","gasUsed":"0x79a940","time":898044494}
{"stateRoot": "2a401d8f1c4c74b9a68ccff4c483cf28fd224450843717d44db8ef2aaf251760"}
[
  {
    "name": "00000002-storagefuzz-0",
    "pass": false,
    "fork": "Berlin",
    "error": "post state root mismatch: got 2a401d8f1c4c74b9a68ccff4c483cf28fd224450843717d44db8ef2aaf251760, want 0000000000000000000000000000000000000000000000000000000000000000"
  }
]

```

**Comment by JekaMas** [comment]
@holiman Thank you for the report!

I fixed the deadlock issue in https://github.com/ledgerwatch/erigon/issues/2135.

Could you help me with stateRoot issue and attach the `json` test here?

**Comment by holiman** [comment]
On mobile, but the issue with the root is that it's only calculated on success: https://github.com/ledgerwatch/erigon/blob/devel/cmd/evm/staterunner.go#L122

**Comment by JekaMas** [comment]
> On mobile, but the issue with the root is that it's only calculated on success: https://github.com/ledgerwatch/erigon/blob/devel/cmd/evm/staterunner.go#L122

Got it. Could you test on `fuzzing-evm` branch?

**Comment by holiman** [comment]
Works now, thanks!
