### ISSUE TITLE
More preparations for EIP-1559

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#2132]
1. Change gas price oracle to use effective tip (+ ignoreUnder parameter)
2. Add support for new consensus test for London (9.0.0)

**Comment by yperbasis** [comment]
By the way, consensus tests 9.0.0 have some issues, better use [9.0.1](https://github.com/ethereum/tests/releases/tag/9.0.1).

**Comment by BitBaseBit** [comment]
I'm working on effective tip + ignoreUnder

**Comment by BitBaseBit** [comment]
@AlexeyAkhunov I've finished changing gas price oracle to use effective tip + ignoreUnder. Do you want me to submit a PR for devel or a different branch?
