### ISSUE TITLE
add OE trace_replayTransaction RPC method

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#2140]
I'm using openethereum for a long time, and currently looking to migrate into erigon.
Erigon performance looks awesome, but the lack of `trace_replayTransaction` rpc method is preventing me to make the switch. I would appreciate if at some point it gets implemented

**Comment by ArtemKo7v** [comment]
I second that, thanks

**Comment by AskAlexSharov** [comment]
done by https://github.com/ledgerwatch/erigon/pull/2238
