### ISSUE TITLE
Implement a way to get transactions by address

### ISSUE THREAD

**Issue by paulmillr** [ledgerwatch/erigon#2156]
# Rationale

I was actually surprised to learn that Erigon does not allow to view list of account transactions.

Why should this feature exist? - This is one of the most common use cases of block explorers. Simply viewing a list of transactions that the address sent/received.

Implementing this feature would allow users to stop using 3rd-party block explorers and "be their own node".

# Implementation

Do you have ideas regarding the implementation of this feature? - Obviously should not be the default. Can be hidden via flag, if we stick to a specific implementation; or can be made more generic, if there would simply be a way to add custom per-account indexes
Are you willing to implement this feature? - Not quite, I don't know erigon codebase

**Comment by AskAlexSharov** [comment]
@paulmillr are you talking about `eth_listTransactions`?

**Comment by AskAlexSharov** [comment]
@paulmillr we have `trace_*` and `debug_trace*` api's - they do not cover your use case? https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon#rpc-implementation-status

**Comment by paulmillr** [comment]
@AskAlexSharov it's a bit complex for me to understand. How can `trace` help here? What do I need to do? Sorry for asking here, but this is a very common case for archive nodes.

**Comment by AskAlexSharov** [comment]
@paulmillr , i can't read your mind :-) If it's common case of archive nodes - tell me how you doing it now. How you doing it with Geth? (Or with OpenEthereum?). Which API method you call? (we can add same compatible method).

**Comment by AskAlexSharov** [comment]
FYI: here is documentation about trace API's:
https://openethereum.github.io/JSONRPC-trace-module
https://geth.ethereum.org/docs/dapp/tracing

**Comment by AskAlexSharov** [comment]
@paulmillr have you found solution for your use-case?

**Comment by AskAlexSharov** [comment]
I think `trace_filter` can find transactions by "fromAddress" and by "toAddress" https://openethereum.github.io/JSONRPC-trace-module#trace_filter
We don't support pagination here, but we do support streaming of json results.

**Comment by paulmillr** [comment]
yeah, all cool, trace worked

**Comment by paulmillr** [comment]
Also Otterscan is pretty neat
