### ISSUE TITLE
Proper way to build as downstream library consumer, consume state 

### ISSUE THREAD

**Issue by fxfactorial** [ledgerwatch/erigon#2183]
I want to use the db in my separate project

```golang
package main

import (
	"flag"
	"log"

	"github.com/ledgerwatch/erigon/ethdb"
)

var (
	chainDB = flag.String("chaindb", "", "where is the erigon chaindata")
)

func program() error {
	rwKv, err := ethdb.NewMDBX().Path(*chainDB).Readonly().Open()
	if err != nil {
		return err
	}

	return nil
}

func main() {
	if err := program(); err != nil {
		log.Fatal(err)
	}
}
```

and go get yields:
```
go get 
# github.com/ledgerwatch/erigon/ethdb/mdbx
gcc: error: ../../go/pkg/mod/github.com/ledgerwatch/erigon@v0.0.0-20210616162644-1702ef866d11/ethdb/mdbx/dist/mdbx-static.o: No such file or directory
```

but i did do `make` in the erigon project, which built successfully and in principle everything ought to be in my go/pkg - but clearly isn't

**Comment by AskAlexSharov** [comment]
I will take a look today.

**Comment by lithp** [comment]
I also ran into this issue (when building against v2021.06.04) but I think it can be closed, https://github.com/ledgerwatch/erigon/pull/2186/ fixes it for me

**Comment by AskAlexSharov** [comment]
@lithp i think it’s done by https://github.com/ledgerwatch/erigon/pull/2186
?

**Comment by fxfactorial** [comment]
Excellent thank you ! I’ll update my tools now with erigons db
