### ISSUE TITLE
RPCDaemon web3_clientVersion, net_version and eth_protocolVersion all return with "connection closed"

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [ledgerwatch/erigon#2193]
#### System information

Erigon version: 2021.06.1-alpha

OS & Version: Ubuntu 20.10 (GNU/Linux 5.8.0-50-generic x86_64) (fully synched node)

```sh
erigon \
  --datadir "/home/foo/erigon" \
  --metrics \
  --txpool.globalslots 16384 \
  --txpool.globalqueue 4096

rpcdaemon \
  --datadir "home/foo/erigon" \
  --private.api.addr=0.0.0.0:9090 \
  --http.api=eth,debug,net,web3,trace,erigon \
  --http.addr=0.0.0.0 \
  --metrics \
  --metrics.port=6070 \
  --ws
 ```

Commit hash : -

#### Expected behaviour

I expect the following RPC methods to work:
- web3_clientVersion
- net_version
- eth_protocolVersion

#### Actual behaviour

They return with an error "connection closed".

Examples of methods that do work as expeced: 
- net_listening
- net_peerCount
- eth_blockNumber
- eth_syncing
- erigon_forks

#### Steps to reproduce the behaviour

Use the Postman configuration as provided in the RPCDaemon documentation or use CURL directly

```sh
HTTP_IP=""

curl --location --request POST $HTTP_IP --header 'Content-Type: application/json' --data-raw '{
  "jsonrpc":"2.0",
  "method":"web3_clientVersion",
  "params":[],
  "id":1
}'
```

**Comment by AskAlexSharov** [comment]
@TimvanScherpenzeel , i can't reproduce it. Please make sure you pass `--http.api=eth,debug,net,web3,trace,erigon` option.

**Comment by TimvanScherpenzeel** [comment]
Hi, @AskAlexSharov , after updating to the latest version of Erigon the issue appears to have resolved itself (could have also been related to my local setup). Thanks 👍
