### ISSUE TITLE
Replace ChainConfig.WithEIPsFlags by go-ethereum's ChainConfig.Rules 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2212]
Because solution based on `context.Context` is hiding data-dependency, slow, producing much garbage, etc... 

And of course need support params.Rules in evm.

**Comment by AlexeyAkhunov** [comment]
Yes, please, I think the reliance on the context properties was a mistake

**Comment by AskAlexSharov** [comment]
done
