### ISSUE TITLE
Kovan Testnet Faucet

### ISSUE THREAD

**Issue by PatrickAlphaC** [ledgerwatch/erigon#2224]
Hi all! I'm looking to help rebirth the kovan faucet, as it often has a lot of downtime. https://faucet.kovan.network/

Is there someone I can connect with to either:
1. Help them host the faucet
2. Onboard me as a kovan validator so we can run our own facuet?

Also, the discord link in this question is invalid, can you please update. 

Any help or direction appreciated, thank you!

**Comment by mandrigin** [comment]
not sure how that is related to a node...
