### ISSUE TITLE
EIP-1898 correctness of JSON-RPC methods 

### ISSUE THREAD

**Issue by leoyvens** [ledgerwatch/erigon#2226]
[EIP-1898](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md) allows doing certain JSON-RPC calls by block hash instead of number, such as `eth_getStorageAt`, `eth_getCode`, `eth_getTransactionCount` and `eth_getBalance`. However these are handling the block hash through `GetBlockNumber` https://github.com/ledgerwatch/erigon/blob/6292056503173aca7e3d47f33365b32b7ac17479/turbo/rpchelper/helper.go#L25-L25
which can give an ambiguous result if `RequireCanonical` is not set, as shown in this check
https://github.com/ledgerwatch/erigon/blob/6292056503173aca7e3d47f33365b32b7ac17479/turbo/rpchelper/helper.go#L66-L66
if `RequireCanonical` is false, then the call may be executed against a hash different from the requested one, which is non-deterministic and not conformant with EIP-1898.

In https://github.com/ledgerwatch/erigon/pull/2137/commits/ae8ca0d00a624a903df4e007cdac157e02249980 this was worked around for `eth_call`, but I believe there should be a general solution for all callers of `GetBlockNumber`. It might as simple as changing `if blockNrOrHash.RequireCanonical && ch != hash` to just `if ch != hash`.

**Comment by 3mg** [comment]
Hi ! I'll take this issue, please do not assign it.

**Comment by 3mg** [comment]
https://github.com/ledgerwatch/erigon/pull/2736

**Comment by mandrigin** [comment]
fixed in 2021.09.05
