### ISSUE TITLE
`codeHash` format inconsistency in `debug_accountRange`

### ISSUE THREAD

**Issue by zzh1996** [ledgerwatch/erigon#2240]
#### System information

Erigon version: 2021.06.4-alpha

OS & Version: Linux

Commit hash: bc2f8bd48ffb3364c1a92e97f5ee99d8f0f72f72

#### Expected behaviour

`codeHash` for different Ethereum Addresses should be consistent, either with or without `0x` prefix.

#### Actual behaviour

`codeHash` has `0x` prefix for contracts with empty code (code size = 0), while doesn't have `0x` prefix for other addresses (EOAs, contracts with code size > 0 and self-destructed contracts).

#### Steps to reproduce the behaviour

For address 0x0000000000000000000000000000000000000000:

```
$ curl http://127.0.0.1:8545 -H 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"debug_accountRange","id":1,"params":["latest","",1,true,true,true]}'
{"jsonrpc":"2.0","id":1,"result":{"root":"0xfc609a37d205f6d2f6a9b188d728cbbdc0b57ab16bcd380fe4368f10e67e6c91","accounts":{"0x0000000000000000000000000000000000000000":{"balance":"8420348067864568008460","nonce":0,"root":"0000000000000000000000000000000000000000000000000000000000000000","codeHash":"c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}},"next":"AAAAAAAAAAAAAAAAAAAAAAAAAAE="}}
```

You could see `"codeHash":"c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"` without `0x`.

For address 0x00004003d3f5fb01940793cc4f65af10d353e4f0 (contract with empty code):

```
$ curl http://127.0.0.1:8545 -H 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"debug_accountRange","id":1,"params":["latest","AABAA9P1+wGUB5PMT2WvENNT5PA=",1,true,true,true]}'
{"jsonrpc":"2.0","id":1,"result":{"root":"0xfc609a37d205f6d2f6a9b188d728cbbdc0b57ab16bcd380fe4368f10e67e6c91","accounts":{"0x00004003d3f5fb01940793cc4f65af10d353e4f0":{"balance":"0","nonce":1,"root":"0000000000000000000000000000000000000000000000000000000000000000","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}},"next":"AABAH2pCaIFmAOSH3RW4OfPK95g="}}
```

You could see `"codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"` with `0x`.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2243

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2378
