### ISSUE TITLE
the method trace_block does not exist/is not available

### ISSUE THREAD

**Issue by hylsceptic** [ledgerwatch/erigon#2242]
It seems the "trace_block" has been implemented. But when I call it:
`curl -s --data '{"method":"trace_block","params":["0xb443"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545`

It returns:
`{"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"the method trace_block does not exist/is not available"}}`

What did I missed, Or is there is a bug?

**Comment by AskAlexSharov** [comment]
@hylsceptic rpc methods have pattern `[namespace]_[methodName]`
any namespace can be enabled by adding to `--http.api` list 
for example:
--http.api="eth,debug,txpool,net,trace"

**Comment by hylsceptic** [comment]
Forget to add "trace", it works now. Thanks.  May can write it more clear in the docs.

**Comment by AskAlexSharov** [comment]
Added more info to “rpcdaemon -h”

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon/pull/2244
