### ISSUE TITLE
MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE 

### ISSUE THREAD

**Issue by suntzu93** [ledgerwatch/erigon#2246]
#### System information

Erigon version: erigon version 2021.06.5-alpha

OS & Version: Linux

Commit hash : cc360ec65854d724873bb5907d239adff1b10559

#### Expected behaviour

Continue sync network

#### Actual behaviour

Crash and stop sync network.

#### Steps to reproduce the behaviour

I'm syncing at version 2021.06.4-alpha and stuck at block 12681633 with log :

> Jun 26 15:06:59 oenode erigon[1385281]: INFO [06-26|15:06:59.988] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=1.30GiB    sys=10.49GiB  numGC=57443
Jun 26 15:07:29 oenode erigon[1385281]: INFO [06-26|15:07:29.988] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=1.29GiB    sys=10.49GiB  numGC=57444
Jun 26 15:07:59 oenode erigon[1385281]: INFO [06-26|15:07:59.989] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=1.13GiB    sys=10.49GiB  numGC=57445
Jun 26 15:08:29 oenode erigon[1385281]: INFO [06-26|15:08:29.988] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=892.48MiB  sys=10.49GiB  numGC=57446
Jun 26 15:08:59 oenode erigon[1385281]: INFO [06-26|15:08:59.989] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=1.23GiB    sys=10.49GiB  numGC=57446
Jun 26 15:09:29 oenode erigon[1385281]: INFO [06-26|15:09:29.989] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=976.72MiB  sys=10.49GiB  numGC=57447
Jun 26 15:09:59 oenode erigon[1385281]: INFO [06-26|15:09:59.988] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=762.51MiB  sys=10.49GiB  numGC=57448
Jun 26 15:10:29 oenode erigon[1385281]: INFO [06-26|15:10:29.988] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=1.17GiB    sys=10.49GiB  numGC=57448
Jun 26 15:10:59 oenode erigon[1385281]: INFO [06-26|15:10:59.989] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=981.18MiB  sys=10.49GiB  numGC=57449
Jun 26 15:11:29 oenode erigon[1385281]: INFO [06-26|15:11:29.989] [1/18 Headers] Wrote block headers       number=12681633 blk/second=0.000     alloc=744.21MiB  sys=10.49GiB  numGC=57450

So I have stopped service erigon and upgrade to 2021.06.5-alpha. After upgrade and restart erigon service, it crashes and message: 

```
err="mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, path: /root/.local/share/erigon/erigon/chaindata" stack="goroutine 1 [running]: 
goroutine 1 [running]:
runtime/debug.Stack(0xc0005fb8d0, 0x148bc20, 0xc000e40240)
        runtime/debug/stack.go:24 +0x9f
github.com/ledgerwatch/erigon/common/debug.LogPanic()
        github.com/ledgerwatch/erigon/common/debug/log_panic.go:65 +0x6a
panic(0x148bc20, 0xc000e40240)
        runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/turbo/node.RegisterEthService(...)
        github.com/ledgerwatch/erigon/turbo/node/node.go:86
github.com/ledgerwatch/erigon/turbo/node.New(0xc000378b00, 0x0, 0xa)
        github.com/ledgerwatch/erigon/turbo/node/node.go:77 +0x30d
main.runErigon(0xc000378b00)
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:33 +0x1c5
github.com/urfave/cli.HandleAction(0x1412520, 0x1f07cf0, 0xc000378b00, 0xc000378b00, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:528 +0x59
github.com/urfave/cli.(*App).Run(0xc00050e8c0, 0xc00003c070, 0x7, 0x7, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:288 +0x675
main.main()
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:21 +0xa9
```

**Comment by perama-v** [comment]
I have experience an almost identical error with the same release version, and have included
the details below. Some additional context might illuminate the source of the error, which
appears to be as follows:

1. Power outage during sync stage "committing block bodies"
2. The sync finishes.
3. The node attempts to update the current block for the
RPC API.
4. The block header for that operation becomes stuck on the block
around the time of the power outage.

**System information**
Erigon version:
- Initial: erigon version 2021.06.5-alpha (commit cc360ec)
- Current: erigon version 2021.07.01-alpha (commit 3001a15)

OS & Version: Linux

Hardware: 4 cores, 16GB RAM

**Expected behaviour**
Continue sync network

**Actual behaviour**
Sync progress halts at "Update current block for the RPC API" after completing majority of sync.

```
[1/18 Headers] Wrote block headers       number=12715886 blk/second=0.000     alloc=673.77MiB  sys=10.88GiB  numGC=64925
```

Attempt to run `./build/bin/erigon` results in `MDBX_BUSY` error, and terminates:

```
Opening Database                         label=chaindata
Re-Opening DB in exclusive mode to apply migrations
database closed (MDBX)                   mdbx=chaindata
panic                                    err="mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE fl>
```

**Steps to reproduce the behaviour**

1. Begin sync.
2. Successfull committing of ~4 million block bodies.
3. Power loss after ~4.5 hours. (Time "A").
4. Restart and re-commence sync.
5. Progress through sync with normal-appearing behaviour for next 6 days.
6. Sync stuck at "Wrote block headers", with block `12715886` corresponding to time "A".
7. Stop service, update `git pull` and `make erigon` to latest release (3001a15).
8. Start service, `MDBX_BUSY` error,

**Logs**

Error when restarting service:

```
Build info                               git_branch=devel git_tag= git_commit=9683b26483f5003afa4da41850c1097271bf6cdb
Starting Erigon on Ethereum mainnet...
Maximum peer count                       ETH=100 total=100
Set global gas cap                       cap=25000000
Crashes From Previous Boots Detected. Find the stack trace in /home/usr/.local/share/erigon/crashreports
Opening Database                         label=chaindata
Re-Opening DB in exclusive mode to apply migrations
database closed (MDBX)                   mdbx=chaindata
panic                                    err="mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE fl>
```

Following normal-appearing progression through the sync stages, the final logs before the halted
progress were:

```
Update current block for the RPC API     from=12715770        to=12715770
[1/18 Headers] Waiting for headers...    from=12715770
[1/18 Headers] Processed                 highest inserted=12715886 age=1w11h20m
[4/18 Bodies] Processing bodies...       from=12715770        to=12715886
[4/18 Bodies] Processed                  highest=12715886
[6/18 Senders] Started                   from=12715770        to=12715886
[7/18 Execution] Blocks execution        from=12715770        to=12715886
[7/18 Execution] Completed on            block=12715886
[7/18 Execution] DONE                    in=32.912434009s
[10/18 HashState] Promoting plain state  from=12715770        to=12715886
[10/18 HashState] Incremental promotion started from=12715770        to=12715886 codes=true csbucket=AccountChangeSet
[10/18 HashState] Incremental promotion started from=12715770        to=12715886 codes=false csbucket=AccountChangeSet
[10/18 HashState] Incremental promotion started from=12715770        to=12715886 codes=false csbucket=StorageChangeSet
[11/18 IntermediateHashes] Generating intermediate hashes from=12715770        to=12715886
[11/18 IntermediateHashes] Trie root      hash=0x2c7e324822f79a264f0803ec144e327e9b0b1b99073611729a0bccee43bf0bb4 in=25.250638823s
[11/18 IntermediateHashes] DONE          in=30.119366901s
[17/18 TxPool] Transaction stats         pending=3964 queued=1024
Memory                                   alloc=691.83MiB  sys=10.88GiB
Timings                                  Headers=983.537746ms   BlockHashes=58.347104ms Bodies=27.59953125s       Senders=640.185065ms       Execution=32.912484224s        HashState=21.280665004s      IntermediateHashes=30.119470628s   CallTraces=12.895833679s      AccountHistoryIndex=9.395248348s     StorageHistoryIndex=12.571185786s      LogIndex=8.161273831s      TxLookup=11.669963125s      TxPool=2.355719473s Finish=2.402564ms
Update current block for the RPC API     from=12715771        to=12715886
[1/18 Headers] Waiting for headers...    from=12715886
[1/18 Headers] Wrote block headers       number=12715886 blk/second=0.000     alloc=580.35MiB  sys=10.88GiB  numGC=64923
[1/18 Headers] Wrote block headers       number=12715886 blk/second=0.000     alloc=596.77MiB  sys=10.88GiB  numGC=64924
[1/18 Headers] Wrote block headers       number=12715886 blk/second=0.000     alloc=673.77MiB  sys=10.88GiB  numGC=64925
```
The error when executing `./build/bin/erigon`:
```
MDBX_EXCLUSIVE flag, path: /home/usr/.local/share/erigon/erigon/chaindata"
stack="goroutine 1 [running]: runtime/debug.Stack(0xc0001438d0, 0x14bc100, 0xc0004d20a0)
    runtime/debug/stack.go:24 +0x9f
github.com/ledgerwatch/erigon/common/debug.LogPanic()
    github.com/ledgerwatch/erigon/common/debug/log_panic.go:65 +0x6a panic(0x14bc100, 0xc0004d20a0) runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/turbo/node.RegisterEthService(...)
    github.com/ledgerwatch/erigon/turbo/node/node.go:105 github.com/ledgerwatch/erigon/turbo/node.New(0xc0000b6900, 0x28d0880, 0x7)
github.com/ledgerwatch/erigon/turbo/node/node.go:97 +0xe5 main.runErigon(0xc0000e8f20)
    github.com/ledgerwatch/erigon/cmd/erigon/main.go:54 +0x21e
github.com/urfave/cli.HandleAction(0x14410c0, 0x1f492e0, 0xc0000e8f20, 0xc0000e8f20, 0x0)
    github.com/urfave/cli@v1.22.4/app.go:528 +0x59
github.com/urfave/cli.(*App).Run(0xc00047ea80, 0xc0001b4000, 0x2, 0x2, 0x0, 0x0)
    github.com/urfave/cli@v1.22.4/app.go:288 +0x675 main.main()
github.com/ledgerwatch/erigon/cmd/erigon/main.go:24 +0xa9 "
Jul 05 19:29:11 usr systemd[1]: eth1.service: Succeeded.
```

**Comment by perama-v** [comment]
Additionally, testing the RPC API:

RPC block number:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8545

{"jsonrpc":"2.0","id":1,"result":"0xc2076e"}

```

Block `0xc2076e` is `12715886`, which matches the stuck block in the logs above.

Node syncing status:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_syncing", "params": [], "id":1}' localhost:8545

{"jsonrpc":"2.0","id":1,"result":false}
```

Returns false, indicating that the node is synced.

**Comment by AskAlexSharov** [comment]
Here is 2 unrelated issues I think. 

1. About stuck: I have feeling that HeaderDownloading can't handle `kill -9` (power off in your case). 
This what I saw in the past after set `--verbosity=4`:
```
DEBUG[06-29|13:17:49.108] NewAnchor failed                         error="new anchor too far in the past: 10529192, latest header in db: 10534925"
```
Probably this is error which we don't see on default verbosity and it feels for us as "stuck".
Also save Stage 1 progress done somewhere deep inside `FeedHeader` instead of right before `tx.Commit()` it feels weird.

2. About `BUSY` error - I added more information to this error - in branch `mdbx_err_with_stack`

**Comment by perama-v** [comment]
Update on progress on my side: 

I made a pull to this 
[commit](https://github.com/ledgerwatch/erigon/commit/954304e43aefe6725a47d67144d19ea8527e43fc) 
from the `devel` branch. After restarting the service, the node continued past the block `12715886` without an error.

**Comment by BNB666666666** [comment]
> 我这边的最新进展：
> 
> 我从分支拉到这个[提交](https://github.com/ledgerwatch/erigon/commit/954304e43aefe6725a47d67144d19ea8527e43fc)。重新启动服务后，节点继续通过块而没有错误。`devel``12715886`

I just got same problem,what did you do to fix it up?

**Comment by BNB666666666** [comment]
WARN[11-19|14:38:32.500] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:32.506] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:33.497] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:33.503] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:33.508] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:33.517] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:34.509] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:34.515] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:34.522] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:34.531] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:35.521] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:35.527] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:35.533] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:35.539] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:36.534] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:36.557] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:36.563] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
