### ISSUE TITLE
Official Docker images

### ISSUE THREAD

**Issue by antonok-edm** [ledgerwatch/erigon#2247]
# Rationale

OpenEthereum is approaching the end of its support, and node operators are being encouraged to use Erigon instead.

One great thing about OpenEthereum was the presence of [official Docker images](https://hub.docker.com/r/openethereum/openethereum) for each release. This has made it very easy for users to ensure they are always running an up-to-date node.

Erigon, on the other hand, does not appear to have any official Docker images. This forces node operators to build images for each release they wish to use, or to evaluate unofficial third-party options which may be outdated, poorly supported, malicious, or otherwise problematic. This point of additional friction presents a barrier-to-entry for new Erigon users, who may settle for the current majority client Geth, or worse, not run a node at all.

# Implementation

The OpenEthereum team did a great job of pushing each release to Docker Hub with a new tag. The exact same setup would be excellent to have for Erigon as well.

**Comment by kobrien** [comment]
while your waiting for an official upstream image, this may help when building your own (which in general should be the recommended way, imo)
https://github.com/yorickdowne/eth-docker/blob/main/erigon/Dockerfile.source

**Comment by AskAlexSharov** [comment]
We have and Dockerfile and docker-compose.yml just lazy to dial with githubActions+dockerHub automation.

**Comment by AskAlexSharov** [comment]
Done: https://hub.docker.com/repository/docker/thorax/erigon
only `devel` available now
release tag will available after next release (every Thursday)

Please review changes in Dockerfile and docker-compose.yml

I didn't add non-root user - because in my experience it makes debug harder. Feel free to recommend something.

**Comment by antonok-edm** [comment]
Amazing, thanks @AskAlexSharov! I'll give it a try this week and let you know how that goes.

**Comment by antonok-edm** [comment]
Apologies for delay on my end, but the new images have been pretty solid for me. Thanks again!
