### ISSUE TITLE
Skipping upgrades

### ISSUE THREAD

**Issue by alcuadrado** [ledgerwatch/erigon#2251]
I normally forget to upgrade my instance of Erigon, and when I remember to do it, I realize that I'm a couple of versions behind. When this happens, I'm always confused about how to proceed, and end up running each version for at least a few minutes just to avoid ruining the db and resyncing.

Is it safe to skip versions that don't have any "Long Migrations"? For example, can I skip 2021.06.04-alpha?

Thanks!

**Comment by AskAlexSharov** [comment]
It’s safe. You will get all migrations anyway.

**Comment by alcuadrado** [comment]
Thanks for your answer, @AskAlexSharov!
