### ISSUE TITLE
RPC deamon docs are misleading - Update rpcdaemon README

### ISSUE THREAD

**Issue by kobrien** [ledgerwatch/erigon#2266]
I am trying to run the rpcdaemon in a separate docker container to the erigon node itself, both use a shared data volume on the host, therefore according to the docs I expected I would be able to run the rpc daemon in local mode (not dual)

https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md#running-locally

`If you have direct access to Erigon's database folder, you may run the rpcdaemon locally. This may provide faster results.
After building, run this command to start the daemon locally:
./build/bin/rpcdaemon --datadir ~/Library/Erigon/ --http.api=eth,debug,net,web3
`

When i run rpc daemon I get this error
```
ERROR[07-01|21:16:52.564] Could not connect to DB                  error="mdbx_env_open: resource temporarily unavailable, path: /data/erigon/chaindata"
```

Here the docs say that if you provide the --datadir flag, this runs in dual mode, which does not work with docker. 

 `Running rpcdaemon in "Dual-Mode" (including the --datadir flag) `
https://github.com/ledgerwatch/erigon#rpcdaemon-dual-mode-does-not-work-with-docker-container

**Comment by AskAlexSharov** [comment]
removed dual-mode from docs. also there is "known issues" section in Readme.md

We need somebody help - to find Docker volume driver or some other Docker configuration to fix this issue.
