### ISSUE TITLE
trace_replayTransaction crashes on some transactions

### ISSUE THREAD

**Issue by ArtemKo7v** [ledgerwatch/erigon#2272]
#### System information

erigon version 2021.07.2-alpha
Ubuntu 20.04.2 LTS

#### Actual behaviour

`curl -s http://127.0.0.1:8555 -X POST -H "Content-Type: application/json" -d '{"method":"trace_replayTransaction","params":["0xe252529404dd88b4c95d5740ffacd2741dc5135f9e47238c77dabe5696f042fb", ["stateDiff"]],"id":1,"jsonrpc":"2.0"}'`

`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}`

**Comment by AskAlexSharov** [comment]
I didn't investigate this issue. 
but maybe this fix is related: https://github.com/ledgerwatch/erigon/pull/2319

**Comment by AskAlexSharov** [comment]
@ArtemKo7v , hi, can you help me to test it on last devel branch?

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2372

**Comment by ArtemKo7v** [comment]
It works fine now, thanks!
