### ISSUE TITLE
Incorrect JSON-RPC type in transaction receipt objects

### ISSUE THREAD

**Issue by alcuadrado** [ledgerwatch/erigon#2288]
#### System information

Erigon version: 2021.06.5-alpha

OS & Version: Linux puc 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Commit hash : https://github.com/ledgerwatch/erigon/commit/cc360ec65854d724873bb5907d239adff1b10559

#### Expected behaviour

Getting a transaction receipt returns an object with a `status` field, which should be formatted as `QUANTITY`.

#### Actual behaviour

The `status` field is formatted as a plain number.

#### Steps to reproduce the behaviour

%  curl -s puc:8545 -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_getTransactionReceipt", "params": ["0xed0b0b132bd693ef34a72084f090df07c5c3a2ec019d76316da040d4222cdfb8"]}' | jq -r .result.status

This prints "0", but should print "0x0".

**Comment by AlexeyAkhunov** [comment]
Yes, receipts were messed up multiple times, sorry. Working on the solution that should fix it. The "0x0" thing has been fixed in the most release I believe. When did you do your sync, with which version?

**Comment by alcuadrado** [comment]
Thanks for the quick answer!

I re-synced a few weeks ago. I think it was `2021.06.03-alpha`, but can I check it somewhere?

**Comment by AlexeyAkhunov** [comment]
At the moment, it is not possible to check what was the version you synced with. I have just merged migration into `devel` branch that should fix receipts broken by previous issues. Takes about 1h40m on main net DB

**Comment by alcuadrado** [comment]
Awesome! Thanks!

> At the moment, it is not possible to check what was the version you synced with.

I'm pretty sure I synced with that one tough.

**Comment by AskAlexSharov** [comment]
closing because looks fixed. feel free to reopen
