### ISSUE TITLE
Unable to sync node: stuck on Failed to recover header downloader error = "mdbx_txn_begin: MDBX_PANIC

### ISSUE THREAD

**Issue by yashutanna** [ledgerwatch/erigon#2318]
Hey

There seems to be an infinite loop issue. I have multiple nodes currently syncing. the node that has this issue was given static peers. all other settings and arguments are the same. 

Not really sure where to go and where to start

ERROR[07-08|14:32:51.403] Failed to recover header downloader      error="mdbx_txn_begin: MDBX_PANIC: Environment had fatal error, trace: [github.com/ledgerwatch/erigon/ethdb.(*MdbxKV).BeginRo github.com/ledgerwatch/erigon/ethdb.(*MdbxKV).View github.com/ledgerwatch/erigon/turbo/stages/headerdownload.(*HeaderDownload).RecoverFromDb github.com/ledgerwatch/erigon/turbo/stages.StageLoop github.com/ledgerwatch/erigon/eth.Loop runtime.goexit] 

and this error goes on forever

**Comment by AskAlexSharov** [comment]
Try add flag `--database.verbosity=4` flag and post output here.

**Comment by AskAlexSharov** [comment]
and run `./build/bin/mdbx_chk <datadir>/erigon/chaindata`
(it may take few hours)

**Comment by AskAlexSharov** [comment]
closing for now, because not enough information. feel free open new issue if you still have this problem. 
probably issue fixed by: https://github.com/ledgerwatch/erigon/pull/2351 and https://github.com/ledgerwatch/erigon/pull/2352
