### ISSUE TITLE
Status of websocket filters/log subscription & sponsoring

### ISSUE THREAD

**Issue by brockelmore** [ledgerwatch/erigon#2321]
Hi there,

Love the great work done on Erigon. Curious if work is actively being done on websocket subscription filters and logs? I know it is in the `TODO`s but I can't find a branch that has made any progress on that front. If there are blockers to completion, it would be great to have transparency into that. We @nascentxyz are working to understand the code so we can potentially contribute in the future, but are new to the repo (but not to geth).

[@Nascentxyz](https://github.com/nascentxyz) would be willing to create a bounty for this work & potentially do a wider sponsoring of Erigon. On that front, what is the best way to go about that? We didn't find a gitcoin grant nor github sponsoring.

**Comment by mandrigin** [comment]
I think we have newHeads subscription for sure. Here is a good list of API implementation status: https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon#rpc-implementation-status

look at eth_subscribe there. 

re: bounties. Reach out to me on Telegram (mandrigin) or on our Discord, and I’ll be happy to discuss.

**Comment by AskAlexSharov** [comment]
closing because look answered. feel free to reopen
