### ISSUE TITLE
make rpcdaemon Error 

### ISSUE THREAD

**Issue by gg22mm** [ledgerwatch/erigon#2326]
[root@dc236f2dd1fb erigon-2021.07.02]# make rpcdaemon
fatal: not a git repository (or any parent up to mount point /usr/local/servers)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr/local/servers)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr/local/servers)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
env GO111MODULE=on go build -trimpath -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit= -X github.com/ledgerwatch/erigon/params.GitBranch= -X github.com/ledgerwatch/params.GitTag=" -o /usr/local/servers/web/erigon-2021.07.02/build/bin/rpcdaemon ./cmd/rpcdaemon
go: github.com/Azure/azure-storage-blob-go@v0.10.0: Get "https://proxy.golang.org/github.com/%21azure/azure-storage-blob-go/@v/v0.10.0.mod": dial tcp 172.217.27.145:443: i/o timeout
make: *** [Makefile:62: rpcdaemon] Error 1

**Comment by AndreaLanfranchi** [comment]
Seems like erigon repo is not cloned properly.
Can you post the tree of the directory where you're launching `make rpcdaemon` from ?

**Comment by AskAlexSharov** [comment]
Yep, you need “.git” folder

**Comment by gg22mm** [comment]
> 
> 
> 是的，你需要“.git”文件夹

down:  https://github.com/ledgerwatch/erigon/archive/refs/tags/v2021.07.02.tar.gz

tar -zxvf v2021.07.02.tar.gz
make rpcdaemon  


make: *** [Makefile:62: rpcdaemon] Error 1

**Comment by gg22mm** [comment]
> 
> 
> Yep, you need “.git” folder

[root@dc236f2dd1fb erigon]# make rpcdaemon
env GO111MODULE=on go build -trimpath -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=5d4c7237dcf38e4b3069b836e6ed42fc7d5a9688 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/params.GitTag=test_docker_hub" -o /usr/local/servers/web/erigon72/erigon/build/bin/rpcdaemon ./cmd/rpcdaemon
go: github.com/Azure/azure-storage-blob-go@v0.10.0: Get "https://proxy.golang.org/github.com/%21azure/azure-storage-blob-go/@v/v0.10.0.mod": dial tcp 216.58.200.241:443: i/o timeout
make: *** [Makefile:62: rpcdaemon] Error 1

**Comment by AskAlexSharov** [comment]
Use git clone instead of tar ball download

**Comment by gg22mm** [comment]
> 
> 
> 使用 git clone 而不是 tar ball 下载

 git config --global --unset http.proxy 
 git config --global --unset https.proxy
git clone https://github.com/ledgerwatch/erigon.git

[root@dc236f2dd1fb erigon]# make rpcdaemon
env GO111MODULE=on go build -trimpath -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=5d4c7237dcf38e4b3069b836e6ed42fc7d5a9688 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/params.GitTag=test_docker_hub" -o /usr/local/servers/web/erigon72/erigon/build/bin/rpcdaemon ./cmd/rpcdaemon
go: github.com/Azure/azure-storage-blob-go@v0.10.0: Get "https://proxy.golang.org/github.com/%21azure/azure-storage-blob-go/@v/v0.10.0.mod": dial tcp 216.58.200.241:443: i/o timeout
make: *** [Makefile:62: rpcdaemon] Error 1
[root@dc236f2dd1fb erigon]# make rpcdaemon
env GO111MODULE=on go build -trimpath -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=5d4c7237dcf38e4b3069b836e6ed42fc7d5a9688 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/params.GitTag=test_docker_hub" -o /usr/local/servers/web/erigon72/erigon/build/bin/rpcdaemon ./cmd/rpcdaemon
go: github.com/Azure/azure-storage-blob-go@v0.10.0: Get "https://proxy.golang.org/github.com/%21azure/azure-storage-blob-go/@v/v0.10.0.mod": dial tcp 172.217.27.145:443: i/o timeout
make: *** [Makefile:62: rpcdaemon] Error 1

**Comment by AskAlexSharov** [comment]
we can't do anything with your internet connection or proxy.golang.org stability.
just retry, check internet, if you are in china - find some local proxy of golang packages, ...

We recently published docker image - you can try it https://hub.docker.com/r/thorax/erigon
(see docker-compose.yml for examples)

**Comment by gg22mm** [comment]
> 
> 
> we can't do anything with your internet connection or proxy.golang.org stability.
> just retry, check internet, if you are in china - find some local proxy of golang packages, ...
> 
> We recently published docker image - you can try it https://hub.docker.com/r/thorax/erigon
> (see docker-compose.yml for examples)

docker run -ti --name erigon -v /home/bee/erigon_v2:/var/lib/erigon:rw -p 30303:30303 -p 30304:30304 -p 6060:6060  -p 9090:9090 -p 8080:8080 -p 8545:8545 -p 8546:8546 thorax/erigon:devel 
/usr/local/bin/erigon --datadir=/var/lib/erigon --private.api.addr=localhost:9090

curl localhost:9090     

Is that right ?

**Comment by gg22mm** [comment]
INFO [07-10|07:16:08.935] Build info                               git_branch=devel git_tag= git_commit=e340fa0debda5ee92b88bd7a89f54c0d5e012812
INFO [07-10|07:16:08.935] Starting Erigon on Ethereum mainnet... 
INFO [07-10|07:16:08.936] Maximum peer count                       ETH=100 total=100
INFO [07-10|07:16:08.936] Set global gas cap                       cap=25000000
INFO [07-10|07:16:09.079] Opening Database                         label=chaindata
INFO [07-10|07:16:09.083] database closed (MDBX)                   mdbx=chaindata label=chaindata exclusive=false
WARN [07-10|07:16:09.084] Crashes From Previous Boots Detected. Find the stack trace in /var/lib/erigon/crashreports 
INFO [07-10|07:16:09.084] Opening Database                         label=chaindata
INFO [07-10|07:16:09.088] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}"
INFO [07-10|07:16:09.088] Disk storage enabled for ethash DAGs     dir=/var/lib/erigon/erigon/ethash-dags count=2
INFO [07-10|07:16:09.088] Initialising Ethereum protocol           network=1
INFO [07-10|07:16:09.088] Effective                                storage mode="{Initialised:true History:true Receipts:true TxIndex:true CallTraces:true TEVM:false}"
INFO [07-10|07:16:09.089] Starting private RPC server              on=localhost:9090
INFO [07-10|07:16:09.188] [1/18 Headers] Waiting for headers...    from=0
INFO [07-10|07:16:09.204] Started P2P networking                   version=66 self=enode://93d968376a1064c25f882cfcc6617cd7453b70e05981cdbed111679b8a243359323dfde98a90227a7a5621c8a46a929cd5e7790a96f8931401acac26cffc5ca9@127.0.0.1:30303
INFO [07-10|07:16:09.204] Started P2P networking                   version=65 self=enode://93d968376a1064c25f882cfcc6617cd7453b70e05981cdbed111679b8a243359323dfde98a90227a7a5621c8a46a929cd5e7790a96f8931401acac26cffc5ca9@127.0.0.1:30304
INFO [07-10|07:16:39.189] [1/18 Headers] Wrote block headers       number=0 blk/second=0.000 alloc=17.31MiB sys=73.58MiB



How to access?

**Comment by gg22mm** [comment]
I in the docker start ,  How to visit outside?

//use
docker run -ti --name erigon -v /home/bee/erigon_v2:/var/lib/erigon:rw -p 30303:30303 -p 30304:30304 -p 6060:6060  -p 9090:9090 -p 8080:8080 -p 8545:8545 -p 8546:8546 thorax/erigon:devel 
/usr/local/bin/erigon --datadir=/var/lib/erigon --private.api.addr=localhost:9090

curl http://119.147.104.160:9090 
 
Connection is reset

**Comment by gg22mm** [comment]
ERROR[07-10|12:31:04.534] RecvUploadMessage: Handling incoming message error="send bodies response: sendMessageById to peer 8584be33dc7f79e1bbfc364eef034fd59c0fdb78396a279681cd1c8c67fdaa87: write tcp 172.17.0.2:30304->47.254.214.43:60762: write: broken pipe"

**Comment by gg22mm** [comment]
> 
> 
> we can't do anything with your internet connection or proxy.golang.org stability.
> just retry, check internet, if you are in china - find some local proxy of golang packages, ...
> 
> We recently published docker image - you can try it https://hub.docker.com/r/thorax/erigon
> (see docker-compose.yml for examples)

docker run -ti --name erigon -v /home/bee/erigon_v2:/var/lib/erigon:rw -p 30303:30303 -p 30304:30304 -p 6060:6060 -p 6061:6061  -p 9090:9090 -p 8080:8080 -p 8545:8545 -p 8546:8546 thorax/erigon:devel
docker exec -ti erigon sh
/usr/local/bin/erigon --datadir=/var/lib/erigon --metrics --metrics.addr="0.0.0.0" --metrics.port="6060" --private.api.addr="0.0.0.0:9090" --pprof --pprof.addr="0.0.0.0" --pprof.port="6061"


[root@localhost ~]#  curl http://192.168.1.200:9090    
curl: (56) Recv failure: Connection reset by peer

**Comment by AskAlexSharov** [comment]
"Private API" - it's low-level gRPC api. 
If you need HTTP JSON-RPC - please run RPCDaemon (yes, rpc living in separated daemon). 
https://github.com/ledgerwatch/erigon#json-rpc-daemon
https://github.com/ledgerwatch/erigon/blob/devel/docker-compose.yml#L39
https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md

**Comment by gg22mm** [comment]
Thank you for your help ~

my config:
docker run -ti --name erigon -v /home/bee/erigon_v2:/var/lib/erigon:rw -p 30303:30303 -p 30304:30304 -p 6060:6060 -p 6061:6061  -p 9090:9090 -p 8080:8080 -p 8545:8545 -p 8546:8546 thorax/erigon:devel
docker exec -ti erigon sh
erigon --datadir=/var/lib/erigon --metrics --metrics.addr="0.0.0.0" --metrics.port="6060" --private.api.addr="0.0.0.0:9090" --pprof --pprof.addr="0.0.0.0" --pprof.port="6061"
rpcdaemon  --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net

-----------------but have WARN , am I right?----------------------

/var/lib/erigon # rpcdaemon  --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net
INFO [07-11|08:57:11.867] if you run RPCDaemon on same machine with Erigon add --datadir option 
INFO [07-11|08:57:11.868] rpc filters: subscribing to Erigon events 
INFO [07-11|08:57:11.870] HTTP endpoint opened                     url=0.0.0.0:8545 ws=false ws.compression=false
INFO [07-11|08:57:11.872] interfaces compatible                    remote_db=0.0.0.0:9090 client=3.0.0 server=3.0.0
INFO [07-11|08:57:11.872] interfaces compatible                    remote_service=eth_backend client=2.1.0 server=2.1.0
INFO [07-11|08:57:11.873] interfaces compatible                    remote_service=mining      client=1.0.0 server=1.0.0
INFO [07-11|08:57:11.873] interfaces compatible                    remote_service=tx_pool     client=1.0.0 server=1.0.0
**WARN [07-11|08:57:16.040] Served                                   conn=185.14.29.23:47156 method=eth_accounts reqid=1 t="111.049µs" err="the method has been deprecated: eth_accounts"
WARN [07-11|08:57:48.711] Served                                   conn=185.14.29.23:54180 method=eth_accounts reqid=1 t="62.598µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|08:58:21.433] Served                                   conn=185.14.29.23:59964 method=eth_accounts reqid=1 t="58.48µs"   err="the method has been deprecated: eth_accounts"
WARN [07-11|08:58:54.234] Served                                   conn=185.14.29.23:38710 method=eth_accounts reqid=1 t="54.832µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|08:59:36.520] Served                                   conn=185.14.29.23:49044 method=eth_accounts reqid=1 t="62.971µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|09:00:03.942] Served                                   conn=185.14.29.23:59290 method=eth_accounts reqid=1 t="34.452µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|09:00:32.431] Served                                   conn=185.14.29.23:38352 method=eth_accounts reqid=1 t="57.6µs"    err="the method has been deprecated: eth_accounts"
WARN [07-11|09:01:05.050] Served                                   conn=185.14.29.23:47356 method=eth_accounts reqid=1 t="89.913µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|09:01:37.666] Served                                   conn=185.14.29.23:55326 method=eth_accounts reqid=1 t="58.347µs"  err="the method has been deprecated: eth_accounts"
WARN [07-11|09:02:10.378] Served                                   conn=185.14.29.23:35328 method=eth_accounts reqid=1 t="57.898µs"  err="the method has been deprecated: eth_accounts"**

--------test------------

[root@localhost ~]# curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x0"}

**Comment by AskAlexSharov** [comment]
Yes. 
It's ok if some api is deprecated. 
List of supported api's: https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md

We don't have API to track sync progress (eth_syncing works, but not very useful in our case), you can use next command to see progress of different stages:
```
./build/bin/integration print_stages --datadir=<your_data_dir>
```

see also --http.api flag docs to enable more namespaces

**Comment by gg22mm** [comment]
Thank you very much ~
-------------------------
I need a bigger hard disk .

[root@localhost bee]# df -h
Filesystem                   Size     Used    Avail   Use%   Mounted on

/dev/nvme0n1             881G   624G  212G    75%    /home/bee

**Comment by gg22mm** [comment]
Thank you very much ~
-------------------------
I need a bigger hard disk .

[root@localhost bee]# df -h
Filesystem                   Size     Used    Avail   Use%   Mounted on

/dev/nvme0n1             881G   624G  212G    75%    /home/bee

**Comment by AskAlexSharov** [comment]
have fun.

1.3TB is default. space can be saved more by turning-off some indices - but it then some RPC API methods will become unavailable - see `--storage-mode` flag docs.
`<datadir>/etl-tmp` also require ~200Gb of free space - but can be mounted/symlinked to slow disk.
