### ISSUE TITLE
Syncing Mainnet, Rpcdaemon shows 0x0 block number for a long

### ISSUE THREAD

**Issue by pnowosie** [ledgerwatch/erigon#2329]
#### System information

Erigon version: `./erigon --version`
erigon version 2021.06.3-alpha

OS & Version: Windows/Linux/OSX
Linux, Ubuntu 20.04.2 LTS
32 GB RAM, ~8+ cores

Commit hash : https://github.com/ledgerwatch/erigon/commit/81a22af4d923b89100a978fde9037c245c527627

#### Expected behaviour
Calling method `eth_syncing` of JSON RPC, rpcdaemon shows progress of syncing.

#### Actual behaviour
Current block states `0x0` for over a 2 days of syncing the Mainnet.

```bash
> http post 0.0.0.0:8545 id=1 method=eth_syncing
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 98
Content-Type: application/json
Date: Fri, 09 Jul 2021 12:11:19 GMT

{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "currentBlock": "0x0",
        "highestBlock": "0xc33484"
    }
}
```

- Erigon is syncing since July 7th, 
- consumed 447 GB of space of `datadir`.
- no errors appeared during startup

I had no such issues syncing testnets. ❤️  Thank you for the advice!

#### Steps to reproduce the behaviour

Here are parameters I started binaries

##### Erigon
```
erigon --datadir /media/papa/DATA/erigon --private.api.addr="0.0.0.0:9090"
```

##### RpcDaemon
```
HOME/bin/rpcdaemon --datadir /media/papa/DATA/erigon \
  --http.vhosts * --http.api "eth,net,web,tg" \
  --http.addr 0.0.0.0 --http.port 8555 \
  --private.api.addr="0.0.0.0:9090"
```

#### Backtrace

````
[backtrace]
````

**Comment by AndreaLanfranchi** [comment]
This is expected ... `current_block` gets updated at the end of every stage loop (i.e. all the stages must complete at least one round).
As you're sync'ing since July 7 (today is July 9) is very likely you're in the middle of heavy-weight execution stage (if you report the logs you currently see it could be of great help) ... but the very first cycle has not completed yet.

**Comment by AndreaLanfranchi** [comment]
The reason you did not experience this behavior on testnets is due to the fact mainnet has lot more blocks, transactions, contracts ... hence it takes a lot more to get in sync at very first stage loop.

**Comment by pnowosie** [comment]
Thank you @AndreaLanfranchi for explaination! I suspected Mainnet sync would be heavy-weight task.
Logs from `erigon` does not suggest anything wrong - just me getting nervous. 

I'll close the issue, now. I hope this thread will help other impatient users 😅

**Comment by AndreaLanfranchi** [comment]
You may also want to check with rpc method `eth_syncing`
As long as the reponse is `true` the node is catching up.
When it returns `false` you're in sync and `currentBlock` matches `highestBlock`

**Comment by AskAlexSharov** [comment]
`current` means here not only blocks are downloaded, but also executed, and all other indices are built. 
Erigon doesn't process blocks one-by-one. It will exec all blocks first, then built history index for all block, then build next index for all blocks, and next, ... It means this field will become > only when all blocks are processed (not when at least one block processed). https://github.com/ledgerwatch/erigon/blob/devel/eth/stagedsync/README.md
