### ISSUE TITLE
eth_call method handler crashed (rinkeby)

### ISSUE THREAD

**Issue by twilightrus** [ledgerwatch/erigon#2330]
#### System information

Erigon version: `erigon version 2021.07.2-alpha`

OS & Version: Ubuntu 18.04

#### Expected behaviour
eth_call return success result

#### Actual behaviour
eth_call return error on request:

`{"id":1,"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x727004cda14316125f3511c9aa50bf524e44fc5a","value":"0x0","data":"0xfe26a778000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bf8abdc1b46292f0bb5d0203d25d40429fcbf38b"},"latest"]}`

response:

`{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}`

I think it because in rinkeby applies london update

Errors in logs:
`
goroutine 93 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00381a6c0, 0x8, 0xc003843ca0)
	github.com/ledgerwatch/erigon/rpc/service.go:220 +0xc6
panic(0x10d6460, 0x1be3490)
	runtime/panic.go:965 +0x1b9
github.com/holiman/uint256.(*Int).Lt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:766
github.com/holiman/uint256.(*Int).Gt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:727
github.com/holiman/uint256.(*Int).Cmp(0xc003857330, 0x0, 0x0)
	github.com/holiman/uint256@v1.2.0/uint256.go:791 +0x5
github.com/ledgerwatch/erigon/core.(*StateTransition).preCheck(0xc0035a7780, 0x203000, 0xc003842cd0, 0x45815b)
	github.com/ledgerwatch/erigon/core/state_transition.go:246 +0x43e
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc0035a7780, 0x13b0001, 0xc0038570e0, 0xc00381a9a8, 0xc0035a7780)
	github.com/ledgerwatch/erigon/core/state_transition.go:280 +0x4f
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc00387e2c0, 0x13b2e78, 0xc0038570e0, 0xc00381a9a8, 0xc003870001, 0x0, 0x0, 0x1c8debe)
	github.com/ledgerwatch/erigon/core/state_transition.go:182 +0x6d
github.com/ledgerwatch/erigon/turbo/transactions.DoCall(0x13a6670, 0xc00365f380, 0x0, 0xc00364d608, 0xc000217678, 0x0, 0x0, 0x0, 0xc003649de0, 0xc0036f5158, ...)
	github.com/ledgerwatch/erigon/turbo/transactions/call.go:117 +0xd49
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Call(0xc000217630, 0x13a6670, 0xc00364f840, 0x0, 0xc00364d608, 0xc000217678, 0x0, 0x0, 0x0, 0xc003649de0, ...)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_call.go:41 +0x225
reflect.Value.call(0xc0012f1400, 0xc000206660, 0x13, 0x12329fc, 0x4, 0xc0035a7700, 0x5, 0x5, 0xc0035a7730, 0xc003880050, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0012f1400, 0xc000206660, 0x13, 0xc0035a7700, 0x5, 0x5, 0x5d, 0x0, 0x0)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc00001b380, 0x13a6670, 0xc00364f840, 0xc00381a6c0, 0x8, 0xc003880050, 0x3, 0x3, 0xc00365f1a0, 0x0, ...)
	github.com/ledgerwatch/erigon/rpc/service.go:227 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0038786c0, 0x13a6670, 0xc00364f840, 0xc0000cc8c0, 0xc00001b380, 0xc003880050, 0x3, 0x3, 0xc00365f1a0, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:488 +0x18be
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0038786c0, 0xc003685710, 0xc0000cc8c0, 0xc00365f1a0, 0x203000)
	github.com/ledgerwatch/erigon/rpc/handler.go:392 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0038786c0, 0xc003685710, 0xc0000cc8c0, 0xc00365f1a0, 0x1d0cde0)
	github.com/ledgerwatch/erigon/rpc/handler.go:346 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc003685710)
	github.com/ledgerwatch/erigon/rpc/handler.go:187 +0x4f
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0038786c0, 0xc003649d80)
	github.com/ledgerwatch/erigon/rpc/handler.go:274 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:270 +0x66
goroutine 77 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc000039f48, 0x8, 0xc00383dca0)
	github.com/ledgerwatch/erigon/rpc/service.go:220 +0xc6
panic(0x10d6460, 0x1be3490)
	runtime/panic.go:965 +0x1b9
github.com/holiman/uint256.(*Int).Lt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:766
github.com/holiman/uint256.(*Int).Gt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:727
github.com/holiman/uint256.(*Int).Cmp(0xc003287ab0, 0x0, 0x0)
	github.com/holiman/uint256@v1.2.0/uint256.go:791 +0x5
github.com/ledgerwatch/erigon/core.(*StateTransition).preCheck(0xc000033400, 0x203000, 0xc00383ccd0, 0x45815b)
	github.com/ledgerwatch/erigon/core/state_transition.go:246 +0x43e
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc000033400, 0x13b0001, 0xc003287860, 0xc003908040, 0xc000033400)
	github.com/ledgerwatch/erigon/core/state_transition.go:280 +0x4f
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc003902420, 0x13b2e78, 0xc003287860, 0xc003908040, 0xc003900001, 0x0, 0x0, 0x1c8debe)
	github.com/ledgerwatch/erigon/core/state_transition.go:182 +0x6d
github.com/ledgerwatch/erigon/turbo/transactions.DoCall(0x13a6670, 0xc003904180, 0x0, 0xc000212b70, 0xc000217678, 0x0, 0x0, 0x0, 0xc0033b9b80, 0xc00020bb30, ...)
	github.com/ledgerwatch/erigon/turbo/transactions/call.go:117 +0xd49
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Call(0xc000217630, 0x13a6670, 0xc0033e2440, 0x0, 0xc000212b70, 0xc000217678, 0x0, 0x0, 0x0, 0xc0033b9b80, ...)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_call.go:41 +0x225
reflect.Value.call(0xc0012f1400, 0xc000206660, 0x13, 0x12329fc, 0x4, 0xc000033380, 0x5, 0x5, 0xc0000333b0, 0xc000217bd0, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0012f1400, 0xc000206660, 0x13, 0xc000033380, 0x5, 0x5, 0x5d, 0x0, 0x0)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc00001b380, 0x13a6670, 0xc0033e2440, 0xc000039f48, 0x8, 0xc000217bd0, 0x3, 0x3, 0xc0033bdf80, 0x0, ...)
	github.com/ledgerwatch/erigon/rpc/service.go:227 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0001df3b0, 0x13a6670, 0xc0033e2440, 0xc0002547e0, 0xc00001b380, 0xc000217bd0, 0x3, 0x3, 0xc0033bdf80, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:488 +0x18be
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0001df3b0, 0xc0033c12f0, 0xc0002547e0, 0xc0033bdf80, 0x203000)
	github.com/ledgerwatch/erigon/rpc/handler.go:392 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0001df3b0, 0xc0033c12f0, 0xc0002547e0, 0xc0033bdf80, 0xc000056800)
	github.com/ledgerwatch/erigon/rpc/handler.go:346 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0033c12f0)
	github.com/ledgerwatch/erigon/rpc/handler.go:187 +0x4f
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0001df3b0, 0xc0033b9b40)
	github.com/ledgerwatch/erigon/rpc/handler.go:274 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:270 +0x66
goroutine 97 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00381aa98, 0x8, 0xc0038afca0)
	github.com/ledgerwatch/erigon/rpc/service.go:220 +0xc6
panic(0x10d6460, 0x1be3490)
	runtime/panic.go:965 +0x1b9
github.com/holiman/uint256.(*Int).Lt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:766
github.com/holiman/uint256.(*Int).Gt(...)
	github.com/holiman/uint256@v1.2.0/uint256.go:727
github.com/holiman/uint256.(*Int).Cmp(0xc003857ab0, 0x0, 0x0)
	github.com/holiman/uint256@v1.2.0/uint256.go:791 +0x5
github.com/ledgerwatch/erigon/core.(*StateTransition).preCheck(0xc0035a7980, 0x203000, 0xc0038aecd0, 0x45815b)
	github.com/ledgerwatch/erigon/core/state_transition.go:246 +0x43e
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc0035a7980, 0x13b0001, 0xc003857860, 0xc00381ab90, 0xc0035a7980)
	github.com/ledgerwatch/erigon/core/state_transition.go:280 +0x4f
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc00387eb00, 0x13b2e78, 0xc003857860, 0xc00381ab90, 0xc003870001, 0x0, 0x0, 0x1c8debe)
	github.com/ledgerwatch/erigon/core/state_transition.go:182 +0x6d
github.com/ledgerwatch/erigon/turbo/transactions.DoCall(0x13a6670, 0xc00365f740, 0x0, 0xc00364d740, 0xc000217678, 0x0, 0x0, 0x0, 0xc0038a8020, 0xc0036f5290, ...)
	github.com/ledgerwatch/erigon/turbo/transactions/call.go:117 +0xd49
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Call(0xc000217630, 0x13a6670, 0xc00364fa80, 0x0, 0xc00364d740, 0xc000217678, 0x0, 0x0, 0x0, 0xc0038a8020, ...)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_call.go:41 +0x225
reflect.Value.call(0xc0012f1400, 0xc000206660, 0x13, 0x12329fc, 0x4, 0xc0035a7900, 0x5, 0x5, 0xc0035a7930, 0xc003880320, ...)
... (135 lines left)
`

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2319

**Comment by twilightrus** [comment]
fix works
