### ISSUE TITLE
getReceipts error: gas limit reached

### ISSUE THREAD

**Issue by LogvinovLeon** [ledgerwatch/erigon#2350]
#### System information

Erigon version: `erigon version 2021.06.4-alpha`

OS & Version: Linux/AWS

Commit hash : 

#### Expected behaviour
I get the transaction receipt

#### Actual behaviour
I get an error:
```
{
    "error": {
        "code": -32000,
        "message": "getReceipts error: gas limit reached"
    },
    "id": "1",
    "jsonrpc": "2.0"
}
```

#### Steps to reproduce the behaviour
1. Sync an erigon node.
2. Request the transaction receipt for transaction: ``
```
http :8545 method=eth_getTransactionReceipt id=1 jsonrpc:=2.0 params:='["0x5e97fc59582118112046b6d8ed649b5f5452cc27b0601fdd13450f476858ef8b"]'
```

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/2327

**Comment by LogvinovLeon** [comment]
I'll try the new version and let you know if it fixes this, but I doubt that this was the issue as I was experiencing this on the mainnet where EIP 1559 isn't enabled yet.
