### ISSUE TITLE
Networking with Peer

### ISSUE THREAD

**Issue by hmajidy2001** [ledgerwatch/erigon#2356]
I have pored over the documentation and GSearch but can't find any info on how to hook up 2 turbo-geth peers on a LAN. Can this be done?

**Comment by AskAlexSharov** [comment]
@hmajidy2001 do you mean `--staticpeers` flag?

**Comment by AskAlexSharov** [comment]
closing because no reply

**Comment by hmajidy2001** [comment]
Yes, where is this documented? Does it work?

**Comment by AskAlexSharov** [comment]
erigon —help
When node starts it print node ID to logs. 
geth docs are also valid here https://geth.ethereum.org/docs/interface/peer-to-peer

**Comment by hmajidy2001** [comment]
Thank you kindly, Alex.
