### ISSUE TITLE
Low performance in Testnet

### ISSUE THREAD

**Issue by zzyalbert** [ledgerwatch/erigon#2398]
I have done a test for erigon and go-ethereum on testnet goerli on the same machine, but erigon was much slower than geth when processing the same block (tens of ms vs about 1.9ms). I used both of then as full node. Did I miss something?

[version]
erigin: latest release 2021.07.03-alpha
geth: master branch(commit 58b0420a8a5d7809981eab119ae64218ea53bc4c)

[machine]
aws c4.5xlarge (16 core/32GB mem/400GB ssd)

[config]
both use default config as full node on testnet goerli

**Comment by SanJue** [comment]
I really want to what improvement about storage have been made
and how can I verify it by testing

thanks!

**Comment by AskAlexSharov** [comment]
@zzyalbert , sorry but your information is totally not enough. 
How did you test?
What block is it? 
How did you measure speed? Is it includes work with network? if "no", how do you know that answer is "no"? :-) 

Erigon has enabled by default indices which Geth doesn't have: 
- indexing of receipts/logs for eth_getLogs method
- indexing of calltraces for OpenEthereum's-style trace_* RPC methods

Why this metric is important for you?
Please give some context

**Comment by AskAlexSharov** [comment]
@SanJue - you also need give more context about your question. Otherwise answer will be "go read code, docs and run sync, watch Grafana board with disk read/write stats". Erigon's archive node 1.3Tb now. 
https://github.com/ledgerwatch/erigon/blob/devel/README.md#system-requirements
https://github.com/ledgerwatch/erigon#how-much-ram-do-i-need

**Comment by AskAlexSharov** [comment]
Hi, guys. Because no active discussion here - i closing issue. Feel free to re-open.
