### ISSUE TITLE
Feature: `--prune.*.before`

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#2421]
# Rationale

`--prune.*.before` would keep all receipts, history, etc, from a given block on, but not before it.

This is useful for integrating with Ethereum PoS consensus clients, which need eth_getLogs about deposits since genesis, block "11052984" on the PoW chain.

`--prune.*.before` and `--prune.*.older` would be mutually exclusive. While `older` keeps the last N; `before` would keep everything since N, including N: The threshold would not move with the tip of the chain. This is useful for any dApp or contract that cares about "transactions since deployment".

**Comment by andrejpodzimek** [comment]
Based on the situation described in #2506, it would be awesome to (also) have an option like `--prune-so-that-eth2-works`, which may become increasingly important in the (near) future. Basically it would tell `erigon` to keep the minimum amount of data that makes deposit queries (and everything related to staking configuration / launchpad steps) work just fine. (Completeness or usefulness of data irrelevant for Eth2 would not be much of a concern; the less data the better.)

**Comment by Cript** [comment]
There are 2 pull requests:
- to erigon-lib: https://github.com/ledgerwatch/erigon-lib/pull/72 - should be merged first
- to main erigon repository: https://github.com/ledgerwatch/erigon/pull/2687
