### ISSUE TITLE
nomenclature: full node vs archive node

### ISSUE THREAD

**Issue by 1blockologist** [ledgerwatch/erigon#2429]
Hello, I had been following turbo geth from the sidelines as a potential alternative for achival nodes that take up 1 TB vs 8 TB

with the rebrand to erigon, it doesn't seem that the summary or readme addresses this use case specifically.

Is the "full" reference to all the states of an archival node? 

What are the specific instructions for doing this kind of "full" sync that is analogous to an archival node? Can the readme disambiguify this?

All the best

**Comment by mandrigin** [comment]
Basically it is a full archive node by default. If you don’t need archive, enable pruning. That was released today.

**Comment by 1blockologist** [comment]
Thanks for building and releasing that, I feel like I should wait for bugs or upcoming hardfork to shake out but maybe I'll give it a shot
