### ISSUE TITLE
Process hangs while downloading blocks, continues using RAM, Network, CPU and Disk but is not doing anything

### ISSUE THREAD

**Issue by 1blockologist** [ledgerwatch/erigon#2444]
#### System information

Erigon version: 2021.07.5-alpha

OS & Version: Windows

Commit hash : 

#### Expected behaviour

Syncing happens completely on autopilot

#### Actual behaviour

Hangs randomly while in the "senders recovery" phase of downloading blocks, as the console stops printing new information, going in to close the process using CTRL+C actually makes the process stop hanging and continue syncing.

#### Steps to reproduce the behaviour

Sync from scratch on Windows

#### Backtrace

````
[backtrace]
````

**Comment by 1blockologist** [comment]
I let it hang for 2 days, just in case it had actually progressed to the phase that was supposed to take 32 hours, but assuming my hardware was not as efficient I let it go longer. But after that was past I went to close the process with CTRL+C to restart it, but instead of the process dying it just resumed downloading blocks.

**Comment by AndreaLanfranchi** [comment]
We need more informations.
1) Full logs
2) Database size
3) Kind of hardware (CPU, RAM, Storage Type, Space available)
4) Which version are you on (Stable ? Devel ?)

**Comment by AskAlexSharov** [comment]
we fixed couple reasons in last release. feel free to re-open if it's still happening.
