### ISSUE TITLE
To port last updates of js tracer

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2447]
To port next changes:
- https://github.com/ethereum/go-ethereum/commit/0fda25e471aa0e061396050c3d5e59fbaaf1e7b0
- https://github.com/ethereum/go-ethereum/commit/0524cede37508068b3031912989493e10eb0544a
- https://github.com/ethereum/go-ethereum/commit/29905d86aef336bb6a12ba61403008e068226a10
- https://github.com/ethereum/go-ethereum/commit/9d10856e84e884936c2390360e60e9ebca6d7a34
Probably it's related to: 
https://github.com/ledgerwatch/erigon/issues/2446

**Comment by Denis-score** [comment]
This update don't look resolve #2446
