### ISSUE TITLE
After copying datadir to other server, restarting erigon on new server causes panic

### ISSUE THREAD

**Issue by gebrits** [ledgerwatch/erigon#2454]
#### System information

Erigon version: `./erigon --version`
New server: 2021.07.5-alpha
Old server: 2021.06.1-alpha

OS & Version: Windows/Linux/OSX
Linux Ubuntu 20.04

#### Expected behaviour
Steps: 

* clean shutdown of Erigon on server A
* Copy datadir from server A (2021.06.1-alpha) to server B (2021.07.5-alpha)
* Expect to be able to restart Erigon by pointing to datadir. 

Used command (same as on server A, which worked): 
`/root/erigon/build/bin/erigon --datadir /chains/ethereum/eth-mainnet --chain mainnet --private.api.addr=localhost:9090`

#### Actual behaviour

Erigon immediately crashes with panic: 

ERROR[07-27|17:17:25.486] catch panic                              err="prune is history=no,receipt=no,txindex=no,calltrace=no,experiments.tevm=disabled original prune is history=no,receipt=no,txindex=no,calltrace=90000,experiments.tevm=disabled" stack="goroutine 1 [running]: runtime/debug.Stack(0xc00018f8d0, 0x1485dc0, 0xc000f8a190) runtime/debug/stack.go:24 +0x9f github.com/ledgerwatch/erigon/common/debug.LogPanic() github.com/ledgerwatch/erigon/common/debug/log_panic.go:63 +0x6a panic(0x1485dc0, 0xc000f8a190) runtime/panic.go:965 +0x1b9 github.com/ledgerwatch/erigon/turbo/node.RegisterEthService(...) github.com/ledgerwatch/erigon/turbo/node/node.go:105 github.com/ledgerwatch/erigon/turbo/node.New(0xc00050a000, 0x28ccc60, 0xc000120000) github.com/ledgerwatch/erigon/turbo/node/node.go:97 +0xe5 main.runErigon(0xc0001abe40) github.com/ledgerwatch/erigon/cmd/erigon/main.go:54 +0x21e github.com/urfave/cli.HandleAction(0x143ac60, 0x1f4fda0, 0xc0001abe40, 0xc0001abe40, 0x0) github.com/urfave/cli@v1.22.5/app.go:526 +0x59 github.com/urfave/cli.(*App).Run(0xc0001f3880, 0xc000136120, 0x6, 0x6, 0x0, 0x0) github.com/urfave/cli@v1.22.5/app.go:286 +0x675 main.main() github.com/ledgerwatch/erigon/cmd/erigon/main.go:24 +0xa9 "

**Comment by gebrits** [comment]
Probably version related. I'll reopen if that doesn't appear to be the case.

**Comment by AskAlexSharov** [comment]
@gebrits 
ERROR[07-27|17:17:25.486] catch panic err="prune is history=no,receipt=no,txindex=no,calltrace=no,experiments.tevm=disabled original prune is history=no,receipt=no,txindex=no,calltrace=90000,experiments.tevm=disabled" 
this error means that you need use same flag “—prune” as you used on original machine. 
if you used “—storage-mode” flag, please see last release notes about “—prune” flag
