### ISSUE TITLE
Feature: tiered chaindata storage

### ISSUE THREAD

**Issue by tsutsu** [ledgerwatch/erigon#2471]
# Rationale

Despite Erigon's efficient chaindata storage format, archive-node chaindata disk usage will still grow over time.

Archive nodes hosted on IaaS VM instances, for maximum read IOPS under heavy query load (e.g. when used as shared backends for node hosting providers), will likely hold chaindata state on direct-attached instance-local ephemeral SSDs (AWS "instance store" volumes; GCP "scratch SSD" volumes.)

And VMs in such a configuration — at least on these major IaaS providers — do not allow for online growth of this ephemeral direct-attached storage. The VM is stuck with whatever direct-attached storage pool size it was created with. Data must be migrated laboriously from one VM to another to "enlarge" the node — as if repotting a plant in a larger pot.

And beyond that, these IaaSes impose direct-attached-storage-pool size limits. I am already running into such a storage limit on GCP (not with Erigon, but with upstream Geth) where our BSC archive node has nearly filled the full 9TiB direct-attached storage pool possible to allocate for a single GCP VM. There is nowhere further to migrate the node from there (except away from IaaS entirely.)

I'm working on porting BSC's Geth fork patches over to Erigon, to stand up a BSC Erigon node. But this will only delay the inevitable — the node, perhaps after another year or two, will still exceed the maximum direct-attached-storage-pool size.

This problem could be avoided if the ephemeral(!) direct-attached-storage-pool were actually being used for its intended purpose: as a discardable, re-warmable cache, rather than as a primary data store. This is would be very difficult to achieve with Geth's LevelDB-based storage (so I'm not going to suggest this change upstream); but I feel that it _may_ be possible to achieve on top of Erigon's libmdbx-based storage.

# Implementation

What I'm imagining:

* an optional CLI flag `--chaindata-cache-dir`, only applicable if the node is in archive mode, to specify a chaindata cache location.

* if the flag is passed, then the `ethdb` abstracted database struct would initialize and hold a second `cache_db` database handle, to a second mdbx database. `ethdb.Batch`es being committed into the database would then actually be committed _twice_ (hopefully in parallel) — once to the "hot" database (idiomatically, configured to live on a direct-attached-storage-pool), and once to the "cold" database (idiomatically, configured to live on a regular network storage volume.)

* make the pruning policy specified by `--prune` run against _both_ databases (possible perf optimization: scan the cold DB to find keys to delete, then send the delete batch to both the hot and cold DBs)

* add a CLI flag `--cache-prune`, which configures _additional_ pruning _only_ for the hot DB

This way, a node could be configured to operate as both a full node _and_ an archive node, at the same time. Block ingest reads, and RPC queries for recent blocks, would be run against the hot DB; while only historical RPC queries would hit the cold DB.

Optionally, `--cache-prune` could also allow for pruning of historical _blocks_ and _transactions_ from the hot DB, in a way that the regular `--prune` cannot; as these would still exist in the cold DB.

Note that this isn't really anything like upstream Geth's ancient-data freezer — as in this model, the cold DB isn't _just_ for old stuff, but is actually a strict superset of the data in the hot DB. The hot DB could at any time be reconstructed from the cold DB.

**Comment by AskAlexSharov** [comment]
Thank you.
We already working on snapshot sync. 
Snapshots - databases with historical data - will be separated databases and can be stored anywhere. 

I think this is enough?

**Comment by tsutsu** [comment]
Ah, I didn't realize snapshot sync was on its way. It's probably enough. Just to verify:

1. given an Erigon node configured as an archive node, will the snapshots contain all historical state versions?
2. is an Erigon archive node with snapshots enabled, able to efficiently prune its working-state chaindata DB of _all_ data held in the snapshots, such that what's left in the working-state DB becomes nearly fixed-size / only growing `O(log N)` over time — while still retaining all archive-node functionality?
2. presuming the Erigon `rpcdaemon` is running with access to both the shared memory of the `erigon` process, and the `chaindata` DB, and the snapshots — is the RPC daemon able to respond for both historical (reading from the snapshots) and "live" (`latest`-height) queries?

If all of those are true, then yes, nothing needs to be done other than to get snapshot sync fully working. :)

**Comment by AskAlexSharov** [comment]
@tsutsu 
1. Yes - for archive node, no - for pruned node.
2. Yes (pruned mode already does it - for all data except blocks itself - snapshot feature will get it done for blocks)
3. Snapshots - technically are also databases (no difference from chaindata) - and RPCDaemon can access it and shared memory will work same way (OS will manage to keep Hot part of data in RAM - doesn't matter in which DB stored this Hot data). 

"nothing needs to be done other than to get snapshot sync fully working" - yes, @b00ris working on it.
