### ISSUE TITLE
Transaction stuck in queue in dev mode

### ISSUE THREAD

**Issue by mmgen** [ledgerwatch/erigon#2476]
#### System information

Erigon version: 2021.07.5-alpha

OS & Version: Debian GNU/Linux 10 (buster)

Commit hash: 63a6c45ef1f998f8c74d38d19b6c57835ebdf977

I start the daemon like this:
```bash
$ build/bin/erigon --private.api.addr=127.0.0.1:9090 --verbosity=5 --chain=dev --miner.etherbase=00a329c0648769a73afac7f9381e08fb43dbea72
```
And the RPC daemon like this:
```bash
$ build/bin/rpcdaemon --private.api.addr=127.0.0.1:9090 --verbosity=5 --http.api=eth,web3,txpool
```
Funds are showing up OK in the dev address:
```bash
$ curl -s -X POST -H "Content-Type: application/json" \
	--data '{"jsonrpc": "2.0", "method": "eth_getBalance", "params": ["0x00a329c0648769a73afac7f9381e08fb43dbea72","latest"], "id":1}' \
	localhost:8545 | jq -M '.'
```
```json
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": "0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7"
}
```
But when I try to send a transaction, the call hangs:

```bash
$ curl -s -X POST -H "Content-Type: application/json" \
	--data '{"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0xf86f80850ba43b7400825208941f2f0641c80c1f6a13edf22e184292584ddcc9d98906b14bd1e6eea0000080820a96a09d16d88269ca9ccd2bfd7ec90c63424f4107c10b183d00f7335b85619f019751a05b71382c8d025526f11c87fb5de0a148f727ec0c3d9e6a604b59c83307ae58e4"], "id":1}' \
	localhost:8545
```
(Ctrl-C)

Checking the txpool, I see that the transaction is queued rather than pending, which shouldn’t be happening, since the nonce is zero:
```bash
$ curl -s -X POST -H "Content-Type: application/json" \
	--data '{"jsonrpc": "2.0", "method": "txpool_content", "params": [], "id":1}' \
	localhost:8545 | jq -M '.'
```
```json
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": {
		"pending": {},
		"queued": {
			"0x00a329c0648769A73afAc7F9381E08FB43dBEA72": {
				"0": {
					"blockHash": null,
					"blockNumber": null,
					"from": "0x00a329c0648769a73afac7f9381e08fb43dbea72",
					"gas": "0x5208",
					"gasPrice": "0xba43b7400",
					"hash": "0x797cd07b29aef1049236dc853875a0e7f586da19528450aed9601712f5c7b4f6",
					"input": "0x",
					"nonce": "0x0",
					"to": "0x1f2f0641c80c1f6a13edf22e184292584ddcc9d9",
					"transactionIndex": null,
					"value": "0x6b14bd1e6eea00000",
					"type": "0x0",
					"v": "0xa96",
					"r": "0x9d16d88269ca9ccd2bfd7ec90c63424f4107c10b183d00f7335b85619f019751",
					"s": "0x5b71382c8d025526f11c87fb5de0a148f727ec0c3d9e6a604b59c83307ae58e4"
				}
			}
		}
	}
}
```
Not surprisingly, the blockchain never advances, as the daemon output shows:
```log
INFO [07-30|19:37:04.794] Build info                               git_branch=devel git_tag=v2021.07.04-25-g63a6c45ef git_commit=63a6c45ef1f998f8c74d38d19b6c57835ebdf977
INFO [07-30|19:37:04.794] Starting Erigon in ephemeral dev mode...
INFO [07-30|19:37:04.795] Maximum peer count                       ETH=100 total=100
INFO [07-30|19:37:04.795] Set global gas cap                       cap=50000000
INFO [07-30|19:37:04.795] Using developer account                  address=0x00a329c0648769A73afAc7F9381E08FB43dBEA72
INFO [07-30|19:37:04.815] Writing custom genesis block             hash=0x8064b3b7fa03f3a660d6b72229483faa73e89bd222f50c9077c1c847a91831e8
INFO [07-30|19:37:04.819] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: <nil>, Engine: clique}"
INFO [07-30|19:37:04.823] Initialising Ethereum protocol           network=1337
INFO [07-30|19:37:04.823] Effective                                prune="history=no,receipt=no,txindex=no,calltrace=no,experiments.tevm=disabled"
INFO [07-30|19:37:04.827] Starting private RPC server              on=127.0.0.1:9090
...
INFO [07-30|19:37:04.860] Started P2P networking                   version=65 self="enode://d804a426f2ffcac6fa817b0c044243e085d4bfaaecd723b3e53413eef013f242973aa68bf36ab9912b5e32d75213a86a66ea3671ab28f7b9f8e381cc5209f3e2@127.0.0.1:30304?discport=0" name=erigon/v2021.07.5-alpha-63a6c45e/linux-amd64/go1.16.6
...
INFO [07-30|19:37:20.050] Setting new local account                address=0x00a329c0648769A73afAc7F9381E08FB43dBEA72
TRACE[07-30|19:37:20.051] Pooled new future transaction            hash="797cd0…c7b4f6" from=0x00a329c0648769A73afAc7F9381E08FB43dBEA72 to=0x1f2F0641c80c1f6A13Edf22E184292584Ddcc9D9
...
DEBUG[07-30|19:37:20.853] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:21.854] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:22.855] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:23.857] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:24.858] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:25.859] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:26.860] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
...
DEBUG[07-30|19:37:27.860] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
```
By applying the following patch, I see that clique.period == 0, as it should be, so that’s not the problem:
```diff
diff --git a/core/genesis.go b/core/genesis.go
index c30f1d39c..aef0f8e3c 100644
--- a/core/genesis.go
+++ b/core/genesis.go
@@ -621,6 +621,7 @@ func DeveloperGenesisBlock(period uint64, faucet common.Address) *Genesis {
	// Override the default period to the user requested one
	config := *params.AllCliqueProtocolChanges
	config.Clique.Period = period
+	log.Info("User debug","config.Clique.Period", config.Clique.Period)

	// Assemble and return the genesis with the precompiles and faucet pre-funded
	return &Genesis{
```
In developer mode blocks should be mined automatically with each new pending transaction if the period is set to 0. However, the transaction is never mined as it remains stuck in the queue. What am I missing here?

**Comment by Uttam-Singhh** [comment]
@mmgen Why did you closed the issue?
Did you find any solution?

**Comment by mmgen** [comment]
> @mmgen Why did you closed the issue?

Because I realized this functionality is completely missing in Erigon.

> Did you find any solution?

As stated previously, the only solution is to reimplement it from scratch.

**Comment by Uttam-Singhh** [comment]
Ahh ok!
Thank you!

**Comment by 0xKrishna** [comment]
Same issue, What changes to be done to make sure it processes transactions in dev mode locally?

**Comment by Uttam-Singhh** [comment]
@mmgen 
I also tried the same and eventually I was able submit my transaction!👇

<img width="1440" alt="Screenshot 2021-09-07 at 12 51 40 PM" src="https://user-images.githubusercontent.com/63050765/132302479-f11fbebc-d6c9-4831-b531-85f273700dac.png">


but still the blocks are not increasing...🤦‍♂️
I don't know why..🤐

@AskAlexSharov Can you help out here!

**Comment by mmgen** [comment]
> Same issue, What changes to be done to make sure it processes transactions in dev mode locally?

You might take a look at this discussion: https://github.com/ledgerwatch/erigon/issues/2588

This functionality exists in Geth but was removed from Erigon after it was forked from Geth.

I think devnet could be reintroduced without restoring all the `geth init` infrastructure. Adding a hard-coded faucet address to the Genesis block like Parity does would an easier solution, in my view.

**Comment by mmgen** [comment]
@Uttam-Singhh: as stated previously, until the necessary modifications are made to the code, the blocks are not going to increase. That's why I closed this issue.

The key component that needs reenabling here is the Clique engine, which mines a block every time it detects a new transaction in the mempool.

**Comment by Uttam-Singhh** [comment]
I actually did some changes like implemented(reintroduced) the genesis init functionality again!
so I thought it should work!

@AskAlexSharov Can you guide me more changes thats need to be done!

**Comment by AskAlexSharov** [comment]
> > Same issue, What changes to be done to make sure it processes transactions in dev mode locally?
> 
> You might take a look at this discussion: #2588
> 
> This functionality exists in Geth but was removed from Erigon after it was forked from Geth.
> 
> I think devnet could be reintroduced without restoring all the `geth init` infrastructure. Adding a hard-coded faucet address to the Genesis block like Parity does would an easier solution, in my view.

Added https://github.com/ledgerwatch/erigon/pull/2639
