### ISSUE TITLE
Different results found for rpctest benchTraceCallMany (Erigon vs OpenEthereum)

### ISSUE THREAD

**Issue by annadanchenko** [ledgerwatch/erigon#2490]
#### System information

Erigon version: `./erigon --version` shows "2021.08.2-alpha" but GitTag=v2021.08.01

OS & Version: Ubuntu

Commit hash : dfa2800a6ddf63ef9c7f6284fb6535b0f214736f

#### Expected behaviour

No differences found

#### Actual behaviour

`Different results for method trace_callMany, errCtx block 9000004: different string values at prefix result[75].stateDiff.0xb2930b35844a230f00e51431acae96fe543a0347.balance.*.to: "0x2124af5be9c1b1164fb" / "0x2124aeee2b19fa1e0fb"`

Full error file: https://github.com/ledgerwatch/rpctests/blob/main/errors/err_oe_benchTraceCallMany2.txt

#### Steps to reproduce the behaviour
`./build/bin/rpctest benchTraceCallMany --erigonUrl http://localhost:8547 --gethUrl http://localhost:9546 --needCompare --blockFrom 9000000 --blockTo 9000006 --recordFile req_oe_benchTraceCallMany2.txt --errorFile err_oe_benchTraceCallMany2.txt`

**Comment by annadanchenko** [comment]
on 'devel' branch, commit hash `65a9a265c2049b22f9fe78f0f93715ed00a33014`

#### Actual behaviour

`different results for method trace_callMany, errCtx: block 9000002: different string values at prefix result[5].vmTrace.code: "0x" / "0x608060405234801561001057600080fd5b506101c1806100206000396000f3fe60806040526004361061003b576000357c01000000000000000000000000000000000000000000000000000000009004806390b98a1114610040575b600080fd5b34801561004c57600080fd5b506100996004803603604081101561006357600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506100af565b6040518082815260200191505060405180910390f35b60008073822d9f6f6d1e0a9785a8dff3083858e2c888f078905060008490508073ffffffffffffffffffffffffffffffffffffffff1663a9059cbb83866040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050600060405180830381600087803b15801561017157600080fd5b505af1158015610185573d6000803e3d6000fd5b505050506001925050509291505056fea165627a7a723058208a08aac5bfdc83f8f2dca87426dd9f7cddfd43c0557ec62e9abe09aad7e871e90029"`

Full error file (zip): https://github.com/ledgerwatch/rpctests/blob/main/errors/err_oe_benchTraceCallMany3.txt.zip

#### Steps to reproduce the behaviour
Note: RPC daemon is run with `--trace.compat`: 
`./build/bin/rpcdaemon --private.api.addr=localhost:9090 --http.port=8547 --http.api=eth,debug,trace --verbosity=4 --datadir /mnt/nvme/data1 --trace.compat `

` ./build/bin/rpctest benchTraceCallMany --erigonUrl http://localhost:8547 --gethUrl http://localhost:9546 --needCompare --blockFrom 9000000 --blockTo 9000002 --recordFile req_oe_benchTraceCallMany3.txt --errorFile err_oe_benchTraceCallMany3.txt`

**Comment by annadanchenko** [comment]
1. no issues if run rpctest with `./build/bin/rpctest benchTraceCallMany --erigonUrl http://localhost:8547 --gethUrl http://localhost:9546 --needCompare --blockFrom 9000000 --blockTo 9000006 --recordFile req_oe_benchTraceCallMany2.txt --errorFile err_oe_benchTraceCallMany2.txt`

2. There is new issue `Different results for method trace_callMany, errCtx block 9000010: arrays have different length at prefix result[35].vmTrace.ops: 105 / 104` if run rpctest with wider range of blocks: `./build/bin/rpctest benchTraceCallMany --erigonUrl http://localhost:8547 --gethUrl http://localhost:9546 --needCompare --blockFrom 9000000 --blockTo 9000026 --recordFile req_oe_benchTraceCallMany99.txt --errorFile err_oe_benchTraceCallMany99.txt`
Full error file: https://github.com/ledgerwatch/rpctests/blob/main/errors/err_oe_benchTraceCallMany99.txt.zip

**Comment by revitteth** [comment]
Closing as OE no longer supported.
