### ISSUE TITLE
"unexpected RLP kind: Byte" when broadcasting EIP-1559 txs

### ISSUE THREAD

**Issue by banteg** [ledgerwatch/erigon#2499]
#### System information

Erigon version: 2021.08.1-alpha

OS & Version: Linux

Commit hash : 

#### Expected behaviour

Calling `eth_sendRawTransaction` with a valid payload of type 2 transaction should broadcast a transaction.

I successfully sent the same payload via Geth.

#### Actual behaviour

```python
Method: eth_sendRawTransaction Params: ('0x[redacted]',)
Method: eth_sendRawTransaction, Response: {'jsonrpc': '2.0', 'id': 10, 'error': {'code': -32000, 'message': 'unexpected RLP kind: Byte'}}
```

#### Steps to reproduce the behaviour

1. Create a raw EIP-1559 transaction, e.g. with eth-account.
2. Try sending it via Erigon
3. Observe the RLP error

If it helps, it seems the new tx type does not conform to the standard RLP encoding, e.g. this can be seen in Python:
```python
>>> from eth_account import Account
>>> import rlp
>>> from eth_account._utils.typed_transactions import DynamicFeeTransaction
>>> user = Account.create()
>>> tx = user.sign_transaction({'from': acc.address, 'gas': 21000, 'nonce': 0, 'maxFeePerGas': 1, 'maxPriorityFeePerGas':
 1, 'type': 2}).rawTransaction
>>> rlp.decode(tx)
DecodingError: RLP string ends with 80 superfluous bytes
>>>  DynamicFeeTransaction.from_bytes(tx).as_dict()
this works
```

**Comment by AskAlexSharov** [comment]
yes, it doesn't conform (it's well-known thing): 
- old: txRlp
- new: rlpString(txType) | txRlp
Here is the fix: https://github.com/ledgerwatch/erigon/pull/2500
