### ISSUE TITLE
Unable to shutdown

### ISSUE THREAD

**Issue by gelfand** [ledgerwatch/erigon#2516]
#### System information

Erigon version: `2021.08.2-alpha`

OS & Version: `Linux 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux`

Golang version: `go1.16.7 linux/amd64`

Commit hash: `f78484d141589daf4ebb032ea400ca566c169b07`

#### Expected behaviour

````
^CINFO[08-12|09:01:55] Got interrupt, shutting down...
INFO[08-12|09:01:55] Transaction pool stopped
INFO[08-12|09:01:56] Successfully update p2p node database    path=/root/.erigon/nodes/eth66 updated=0 deleted=4837
INFO[08-12|09:01:56] database closed (MDBX)
INFO[08-12|09:01:56] Successfully update p2p node database    path=/root/.erigon/nodes/eth65 updated=0 deleted=4837
INFO[08-12|09:01:56] database closed (MDBX)
````

#### Actual behaviour

````
^CINFO[08-12|08:43:45] Got interrupt, shutting down...
INFO[08-12|08:43:45] Transaction pool stopped
^CWARN[08-12|08:45:37] Already shutting down, interrupt more to panic. times=9
````

#### Steps to reproduce the behaviour

Try to stop running instance with `^C`

#### Explanation

Had the same issue on my `Mainnet` instance yesterday, it wasn't shutting down for like 20+ minutes and I had to interrupt it 10 times so it panics. Today the same on `Ropsten`. I am running them on different machines with the same `System Information` as described above.

#### CLI flags

Mainnet
`./build/bin/erigon --datadir /root/.erigon --prune=hrtc`

Ropsten
`./build/bin/erigon --datadir /root/.erigon/ropsten --chain ropsten`

**Comment by sambacha** [comment]
> #### System information
> Erigon version: `2021.08.2-alpha`
> 
> OS & Version: `Linux 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux`
> 
> Golang version: `go1.16.7 linux/amd64`
> 
> Commit hash: `f78484d141589daf4ebb032ea400ca566c169b07`
> 
> #### Expected behaviour
> ```
> ^CINFO[08-12|09:01:55] Got interrupt, shutting down...
> INFO[08-12|09:01:55] Transaction pool stopped
> INFO[08-12|09:01:56] Successfully update p2p node database    path=/root/.erigon/nodes/eth66 updated=0 deleted=4837
> INFO[08-12|09:01:56] database closed (MDBX)
> INFO[08-12|09:01:56] Successfully update p2p node database    path=/root/.erigon/nodes/eth65 updated=0 deleted=4837
> INFO[08-12|09:01:56] database closed (MDBX)
> ```
> 
> #### Actual behaviour
> ```
> ^CINFO[08-12|08:43:45] Got interrupt, shutting down...
> INFO[08-12|08:43:45] Transaction pool stopped
> ^CWARN[08-12|08:45:37] Already shutting down, interrupt more to panic. times=9
> ```
> 
> #### Steps to reproduce the behaviour
> Try to stop running instance with `^C`
> 
> #### Explanation
> Had the same issue on my `Mainnet` instance yesterday, it wasn't shutting down for like 20+ minutes and I had to interrupt it 10 times so it panics. Today the same on `Ropsten`. I am running them on different machines with the same `System Information` as described above.
> 
> #### CLI flags
> Mainnet
> `./build/bin/erigon --datadir /root/.erigon --prune=hrtc`
> 
> Ropsten
> `./build/bin/erigon --datadir /root/.erigon/ropsten --chain ropsten`

For reference on how Go handles Unix-like Signal calls:

SIGINT and Go, ref: pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs

The SIGINT signal is sent when the user at the controlling terminal presses the interrupt character, which by default is ^C (Control-C). The SIGQUIT signal is sent when the user at the controlling terminal presses the quit character, which by default is ^\ (Control-Backslash). In general you can cause a program to simply exit by pressing ^C, and you can cause it to exit with a stack dump by pressing ^\.

Are you running this through a container (docker) or on the VM/machine itself? 

Have you tried not using the `/root/` directory for the data dir?

**Comment by AskAlexSharov** [comment]
Very likely it's deadlock:
```
goroutine 47 [semacquire, 1226 minutes]:
p2p/enode.(*DB).commitCache
```

**Comment by AlexeyAkhunov** [comment]
Ok, I will take a look today

**Comment by AlexeyAkhunov** [comment]
Thanks for reporting, fix is coming

**Comment by gelfand** [comment]
Thanks.
Also after `git pull` I got this error after about two hours running on Ropsten
````
WARN[08-13|17:39:13] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
````
then decided to increase `MapSize` in `p2p/enode/nodedb.go` from `MapSize(64 * datasize.MB)` to `MapSize(128 * datasize.MB)` and now it seems working flawlessly.

**Comment by gelfand** [comment]
> Thanks.
> Also after `git pull` I got this warning after about two hours running on Ropsten
> 
> ```
> WARN[08-13|17:36:57] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:57] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:57] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:57] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> DBUG[08-13|17:36:58] Empty anchor queue
> DBUG[08-13|17:36:58] Request skeleton                         anchors=0 top seen height=10829524 highestInDb=10829524
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:58] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth66 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> WARN[08-13|17:36:59] p2p node database update failed          path=/root/.erigon/ropsten/nodes/eth65 err="mdbx_cursor_del: MDBX_MAP_FULL: Environment mapsize limit reached"
> ```
> 
> then decided to increase `MapSize` in `p2p/enode/nodedb.go` from `MapSize(64 * datasize.MB)` to `MapSize(128 * datasize.MB)` and now it seems working flawlessly.

Not seeing this on Mainnet, not sure but the reason could be that I was actively communicating with RPC using websockets in my specific case, so closing.

**Comment by AskAlexSharov** [comment]
@gelfand can you try git pull one more time. I think https://github.com/ledgerwatch/erigon/pull/2524 fixes the problem

**Comment by AskAlexSharov** [comment]
If not, then just delete `/root/.erigon/ropsten/nodes/eth6*` folders and we will investigate the problem
