### ISSUE TITLE
Missing 'baseFeePerGas' in Block Headers

### ISSUE THREAD

**Issue by mdben1247** [ledgerwatch/erigon#2549]
#### System information
Erigon version: 2021.08.2-alpha
OS & Version: Linux

#### Expected behaviour
When doing `eth_subscribe` with `newHeads`, block headers should include `baseFeePerGas`. At least OE seems to work that way, see: 
https://github.com/openethereum/openethereum/blob/5d9ff63043bb5986a8045935f1a25e2bfa6239fd/crates/rpc/src/v1/types/block.rs#L134

#### Actual behaviour
Field `baseFeePerGas` in missing in streamed block headers.

**Comment by AskAlexSharov** [comment]
fix is likely here https://github.com/ledgerwatch/erigon/pull/2550 
but didn't test much yet

**Comment by mdben1247** [comment]
yes, it works with the fix provided
