### ISSUE TITLE
Missing raw tx data in tx object returned by eth_getTransactionByHash

### ISSUE THREAD

**Issue by mdben1247** [ledgerwatch/erigon#2557]
#### System information
erigon version 2021.08.3-alpha
OS & Version: Linux
Commit hash : e7574a6d14a64c5af58574d909b8c6a014bd2daf

#### Expected behaviour
Transaction object returned by `eth_getTransactionByHash` should include raw transaction data (field `raw`). Not sure if this is really part of the specification, but OE includes the raw transaction data for both pending and mined txs. See here, section "Transaction Responses":
https://openethereum.github.io/JSONRPC

#### Actual behaviour
No raw transaction data is returned by `eth_getTransactionByHash`.

**Comment by AskAlexSharov** [comment]
@mdben1247 what flags you run Erigon with?

**Comment by mdben1247** [comment]
The only one that seems relevant to the issue is: `--prune=hc`. Other flags are `datadir`, `port`, `p2p.eth65.port` and `txpool.locals`.

**Comment by mdben1247** [comment]
It looks this was OE specific, I can't find `raw` field in any other specification (what counts as 'official' eth_ spec, anyway?). Also, `eth_getTransactionByHash` provides all the information to calculate raw data, it's just a bit less convenient.

**Comment by AskAlexSharov** [comment]
'offitial' is here: https://github.com/ethereum/execution-specs/blob/master/json-rpc/spec.json
But it's ok to support some OpenEthereum features if they are useful. 
There is also method: eth_getRawTransactionByHash, probably also not very convenient? @mdben1247

**Comment by mdben1247** [comment]
> There is also method: eth_getRawTransactionByHash, probably also not very convenient? 

:) I really didn't know about that one, I wouldn't have bothered you if I did. I usually refer to https://openethereum.github.io/JSONRPC-eth-module and the method isn't listed there.

I guess we can close this. No sense in implementing `raw` field, if there's a separate method to get that.
