### ISSUE TITLE
Execution failed 

### ISSUE THREAD

**Issue by jackliu10** [ledgerwatch/erigon#2561]
#### System information

Erigon version: `./erigon --version`   
erigon version 2021.08.3-alpha

OS & Version: Windows Microsoft Windows [版本 10.0.22000.160]
and Mac os

Three mistakes at different times

<img width="1037" alt="7f8a230399a714d32db0e91829807db" src="https://user-images.githubusercontent.com/40690755/130273716-bf104c85-ea84-439d-b667-58ea10fbc6ea.png">

<img width="1073" alt="a0ce40ea529b8c066e3629eba9bbfd8" src="https://user-images.githubusercontent.com/40690755/130273739-cb17e9ef-e891-4778-a4f7-67d1a6a303f2.png">

<img width="698" alt="75d0b4a36b5684852bfb68888805be5" src="https://user-images.githubusercontent.com/40690755/130273757-f496651e-2184-4e73-9d12-5e5d370a65a7.png">

**Comment by AskAlexSharov** [comment]
Hi. 
Will try to reproduce today... 
What is your FileSystem and Disk?

**Comment by AskAlexSharov** [comment]
can't reproduce - something wrong with your setup.
maybe you did something special? special erigon flags?
what is `trace trap`? why do you need it?
