### ISSUE TITLE
Memory exhaustion during CallTraces Prune

### ISSUE THREAD

**Issue by mikeshultz** [ledgerwatch/erigon#2591]
#### System information

Erigon version: `erigon version 2021.08.5-alpha`

OS & Version: `Linux eth 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux`

Commit hash : f3021dd2afdb41f95e9f6b243fad9420a79ab968

System memory: 

                   total        used        free      shared  buff/cache   available
    Mem:           15900         260       15042           0         597       15227
    Swap:          11043          43       11000

#### Expected behaviour

Complete sync

#### Actual behaviour

Process gets killed for being out of memory during the "CallTraces Prune" process

    Aug 28 12:06:51 eth erigon[541]: [INFO] [08-28|12:06:51.357] [p2p] GoodPeers                          eth66=33 eth65=32
    Aug 28 12:07:08 eth erigon[541]: [INFO] [08-28|12:07:08.509] [12/18 CallTraces Prune] Progress        number=9695430 alloc="16.16 GiB" sys="19.82 GiB"
    Aug 28 12:07:38 eth erigon[541]: [INFO] [08-28|12:07:38.508] [12/18 CallTraces Prune] Progress        number=9705590 alloc="16.83 GiB" sys="19.82 GiB"
    Aug 28 12:08:08 eth erigon[541]: [INFO] [08-28|12:08:08.506] [12/18 CallTraces Prune] Progress        number=9714193 alloc="17.45 GiB" sys="19.82 GiB"
    Aug 28 12:08:38 eth erigon[541]: [INFO] [08-28|12:08:38.509] [12/18 CallTraces Prune] Progress        number=9716355 alloc="17.96 GiB" sys="19.82 GiB"
    Aug 28 12:08:51 eth erigon[541]: [INFO] [08-28|12:08:51.356] [p2p] GoodPeers                          eth66=33 eth65=31
    Aug 28 12:09:08 eth erigon[541]: [INFO] [08-28|12:09:08.511] [12/18 CallTraces Prune] Progress        number=9716793 alloc="18.42 GiB" sys="19.82 GiB"
    Aug 28 12:09:22 eth systemd[1]: erigon.service: A process of this unit has been killed by the OOM killer.
    Aug 28 12:09:30 eth systemd[1]: erigon.service: Main process exited, code=killed, status=9/KILL
    Aug 28 12:09:30 eth systemd[1]: erigon.service: Failed with result 'oom-kill'.
    Aug 28 12:09:30 eth systemd[1]: erigon.service: Consumed 1h 59min 17.321s CPU time.

This is repeatable and I'm unable to sync.

#### Steps to reproduce the behaviour

    erigon --networkid 1 --nat upnp --prune=c --private.api.addr 127.0.0.1:9090

I've also tried setting `--blockDownloaderWindow` significantly lower than default with no change in outcome.

Possibly related: #2160

**Comment by AskAlexSharov** [comment]
It must not prune so much (it must just not to write most of data during initial sync). I will take a look

**Comment by mikeshultz** [comment]
If context helps, I haven't yet gotten the initial sync due to some other memory exhaustion issues (e.g. #2160).  Installed a bit more RAM and restarted the process, got a little farther, and now I'm in this state.

**Comment by AskAlexSharov** [comment]
plz sow: `./build/bin/integration print_stages --datadir=<datadir>`

**Comment by mikeshultz** [comment]
$ ./build/bin/integration print_stages --datadir=/data/ethereum/erigon/
    Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

                 stage_at    prune_at
    Headers          13115973    0
    BlockHashes          13115973    0
    Bodies           13115973    0
    Senders          13115973    0
    Execution        13115973    0
    Translation          0       0
    HashState        13115973    0
    IntermediateHashes   13115973    0
    AccountHistoryIndex      13115973    0
    StorageHistoryIndex      13115973    0
    LogIndex         13115973    0
    CallTraces       13115973    0
    TxLookup         13115973    0
    TxPool           13115973    0
    Finish           13115973    0
    --
    prune distance: --prune=c

    INFO[08-28|20:11:04.160] database closed                          label=chaindata

**Comment by AskAlexSharov** [comment]
here is the fix: https://github.com/ledgerwatch/erigon/pull/2592

**Comment by mikeshultz** [comment]
After compiling with the branch for PR #2492 I was able to complete syncing.  Here's another run of that integration tool:

    Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

                 stage_at    prune_at
    Headers          13121078    0
    BlockHashes          13121078    0
    Bodies           13121078    0
    Senders          13121078    0
    Execution        13121078    13121078
    Translation          0       0
    HashState        13121078    0
    IntermediateHashes   13121078    13121078
    AccountHistoryIndex      13121078    0
    StorageHistoryIndex      13121078    0
    LogIndex         13121078    0
    CallTraces       13121078    13121078
    TxLookup         13121078    0
    TxPool           13121078    0
    Finish           13121078    0
    --
    prune distance: --prune=c

    INFO[08-29|09:08:34.840] database closed                          label=chaindata

Let me know if there's anything else you need.

Thanks for the quick turnaround, Alex.  Good to have my node back.  :smile:
