### ISSUE TITLE
Support for Logs Subscription

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#2604]
# Rationale

Why should this feature exist?
All other clients support it 🙂 

What are the use-cases?
To subscribe to new logs and events

# Implementation

Do you have ideas regarding the implementation of this feature?
https://geth.ethereum.org/docs/rpc/pubsub - Logs

Are you willing to implement this feature?
🙁

**Comment by AskAlexSharov** [comment]
done
