### ISSUE TITLE
Wrong trie root of block 13140927

### ISSUE THREAD

**Issue by jackliu10** [ledgerwatch/erigon#2611]
<img width="736" alt="1630517370(1)" src="https://user-images.githubusercontent.com/40690755/131717092-09d2c4b0-08e5-4c5f-95f3-59ffa5520694.png">
<img width="736" alt="1630517417(1)" src="https://user-images.githubusercontent.com/40690755/131717109-f2be9a5c-0deb-4e30-b973-494847944452.png">

**Comment by fedecastelli** [comment]
Same here but at block `13140584`. After I got this error, it started to download blocks from the block before (`13140583`) but it's still stuck there.

The only thing I can see is it started to invalidate random blocks downloaded before.

**Comment by AlexeyAkhunov** [comment]
You need to try to update the the newest version of Erigon, which has a fix for the Geth/Erigon vulnerability. Also, preparing that fix that would enable to come back to the correct chain if you end up on the wrong chain. Trying to fit it into the tomorrow's release

**Comment by fedecastelli** [comment]
Okay, thank you. So can you confirm that the bug is still present in the release version `2021.09.1-alpha`?

**Comment by AlexeyAkhunov** [comment]
@jackliu10 can you please try to run from `devel` branch? I have just merged the fix for the similar issue on Ropsten

**Comment by AskAlexSharov** [comment]
closing as fixed
