### ISSUE TITLE
Allow getting data for pending transactions

### ISSUE THREAD

**Issue by KaiRo-at** [ledgerwatch/erigon#2629]
# Rationale

I'm running a (company-internal) monitoring service on our blockchain nodes, which in addition to watching node health, also keeps statistics about recent blocks and pending transactions so we get more insight into the current environment of chain congestion and gas prices. For quick info, the count of pending transactions as seen by the node is interesting, for detailed stats, the actual pending transactions can be dug into and analyzed.

To get the count of pending transactions, [eth_getBlockTransactionCountByNumber](https://eth.wiki/json-rpc/API#eth_getblocktransactioncountbynumber) (like some other commands) can - per the JSON-RPC documentation in the wiki - be called with, the block be specified as `"pending"` which is documented in [the default block parameter](https://eth.wiki/json-rpc/API#the-default-block-parameter). Unfortunately, that seems to not be supported by Erigon right now, as I found out when experimenting with some new Erigon nodes to replace our existing OpenEthereum nodes, which support that.

For actually analyzing pending transactions, I have been using [parity_pendingTransactions](https://openethereum.github.io/JSONRPC-parity-module#parity_pendingtransactions) on OpenEthereum, but I would be happy about any way that I can get a list of transactions in the mempool that this nodes is aware of, so I can e.g. see what priority fees those have set and make statistics about that.

# Implementation

For all of that, Erigon needs to keep a list of pending transactions in memory, but i guess for mining, that is required as well anyhow. If that exists, it sounds to me as an outside as the JSON-RPC end points may be relatively easy to implement - at least if the RPC daemon can get access to that list.

I'm personally not able to dig into development myself but as soon as a docker image with that functionality is available, I'm happy to test and give feedback.

**Comment by gelfand** [comment]
> For actually analyzing pending transactions, I have been using [parity_pendingTransactions](https://openethereum.github.io/JSONRPC-parity-module#parity_pendingtransactions) on OpenEthereum, but I would be happy about any way that I can get a list of transactions in the mempool that this nodes is aware of, so I can e.g. see what priority fees those have set and make statistics about that.

For that purpose you can use `txpool_content`, it returns both `pending` and `queued` transactions, so you would have to just get rid off `queued`(aka `non-executable`) transactions.
```
 ~ ❯❯❯ curl -X POST -H "Content-Type: application/json" --data '{"method": "txpool_content", "params": [], "id":1}' localhost:8545
 ```

**Comment by AskAlexSharov** [comment]
If need only counters - can use txpool_status

**Comment by KaiRo-at** [comment]
OK, now that I'm looking into implementing our monitoring with this, I see that for `eth_getBlockTransactionCountByNumber` for the `pending` block I can very well be use the `pending` count from `txpool_status` - actually, you probably could implement it on your side with this. :)

That said, when trying to analyze the list of transactions in `txpool_content`, I found that e.g. on Goerli, I get only about 10% of the expected transactions in the `pending` list compared to what the `txpool_status` says that I should expect (and also compared to what OpenEthereum gives me in `parity_pendingTransactions`. What could be the reason for that?
FWIW, I see the same difference in the numbers between `txpool_content` and `txpool_status` when I look at `queued`.
