### ISSUE TITLE
Geth drops Erigon peers

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#2653]
From Geth 1.10.8:

`Checkpoint challenge timed out, dropping id=24d6c2f357d5a06b conn=inbound addr=108.214.8.13:39154   type=erigon/v2021.09.1-al...`

I am assuming this isn't supposed to happen.

I've seen this behaviour since 2021.07 alpha

**Comment by AskAlexSharov** [comment]
@yorickdowne , thank you. we will take a look

**Comment by AskAlexSharov** [comment]
looks like I fixed it by https://github.com/ledgerwatch/erigon/pull/2666

**Comment by AlexeyAkhunov** [comment]
Bravo!

**Comment by yorickdowne** [comment]
This may not be fully fixed yet: `Checkpoint challenge timed out, dropping id=6ca720f4502f7113 conn=inbound addr=5.9.136.69:56446      type=erigon/v2021.09.5-al...`

**Comment by mandrigin** [comment]
@AskAlexSharov @yorickdowne if this one repeats, please reopen
