### ISSUE TITLE
[AuRa] Eliminate `HeadersSeal` function and associated environment variable

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#2658]
We are working on the support of AuRa consensus in Erigon, and some initial work has been done by @AskAlexSharov to support Sokol POA network. This work needs to continue.

In AuRa, block headers have an extra field, called "Seal", which does not appear in any non-AuRa network. This makes is tricker to parse block headers RLP and serialise headers into RLP. Currently as a "quick-fix", there is a function that uses environment variable that switches the parsing and serialisation behaviour:

https://github.com/ledgerwatch/erigon/blob/71ec0938b5691d34a2d5940c67db62c7d11aa086/common/debug/experiments.go#L112

Find the usages of this function throughout the code. Then replace this with "proper" configuration, starting from this structure: https://github.com/ledgerwatch/erigon/blob/71ec0938b5691d34a2d5940c67db62c7d11aa086/params/config.go#L165

In that structure, `ChainConfig`, we can introduce a enum field that tells us which type of consensus it is (EtHash, Clique, AuRa). And then, this needs to be passed around to the code where parsing of block header RLPs and serialisation of block headers happens, instead of relying of `HeadersSeal` function and the environment variable.

**Comment by AlexeyAkhunov** [comment]
In order to activate one of these `ChainConfig` choices, Erigon needs to be launched with the option `--chain <chain_name>`, for example, `--chain sokol`. Though with Sokol currently, it is very hard to find good peers

**Comment by e-danko** [comment]
Hello ! I'll take this issue, please do not assign it.
