### ISSUE TITLE
[AuRa] Add seal verification to the header processing for AuRa chains

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#2659]
We are working on the support of AuRa consensus in Erigon, and some initial work has been done by @AskAlexSharov to support Sokol POA network. This work needs to continue.

In AuRa, block headers have an extra field, called "Seal", which does not appear in any non-AuRa network. This `Seal` field contains the block number signed by the validator who "approved", or "sealed" that block. In the current version of code in `devel` branch, there is no verification of that signature. This verification needs to be added and Stage "Headers" needs to report error and abort if the signature is invalid.

**Comment by mandrigin** [comment]
(1) Generate the seal (if I understand, @AskAlexSharov, this isn't implemented yet, right?)

(2) Update `eth/stagedsync/stage_headers.go` to check that seal

**Comment by AskAlexSharov** [comment]
Yes. There is already exists VerifyHeader method in Consensus interface.
