### ISSUE TITLE
Huge memory consumption (>10GB RAM)

### ISSUE THREAD

**Issue by KaiRo-at** [ledgerwatch/erigon#2662]
#### System information

Erigon version: erigon version 2021.09.2-alpha (same with 2021.09.1-alpha)

OS & Version: Linux

Commit hash :  --- / docker container from docker hub, tag "v2021.09.02" (and tag "v2021.09.01")

#### Expected behaviour

Fully synced running node uses a single-digit amount of GB in RAM (or less)

#### Actual behaviour

This is from `top` on a machine I admin that has 128GB RAM and Erigon has been running fully synced on mainnet for a few days:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  80709 1000      20   0 2051.2g  53.6g  51.5g S  44.2  42.7   1241:30 erigon
```

On a different machine (with 16 GB RAM) on which I did set up a Ropsten node to replace OpenEthereum (which used under 1GB `RES` memory), after fully syncing, it goes up to just over 13GB `RES` and then the machine becomes unusably slow as almost no memory is available to any process any more. Note that `SHR` grows much slower, `VIRT` is always the very high number here, but virtual memory allocation shouldn't matter much as I understand it.

#### Steps to reproduce the behaviour

1. Install Erigon docker container
2. Run it with `erigon --chain ropsten --datadir /data/erigon/ropsten/ --maxpeers 100 --nat extip:x.x.x.x --private.api.addr=0.0.0.0:9090` (or run with mainnet, same results) via `docker-compose`, let it fully sync.
3. Wait and watch memory consumption over hours/days

**Comment by AskAlexSharov** [comment]
@KaiRo-at do you have some logs from time when problem occurred?

**Comment by KaiRo-at** [comment]
> @KaiRo-at do you have some logs from time when problem occurred?

Well, the memory is going up continuously, so it's not a problem occurring at a certain point in time. The ropsten node got stuck over night and so was somewhat behind on syncing after that when I restarted it 2.5h ago, but right now it's up to 9.8g `RES`, the log from this run so far is [erigon-docker-ropsten-20210910.log](https://github.com/ledgerwatch/erigon/files/7144122/erigon-docker-ropsten-20210910.log)

I'm happy to help in getting any other data as far as it can be done on a docker container.

**Comment by KaiRo-at** [comment]
And here's the last 15 minutes of the log of the mainnet machine that is at over 50 GB `RES` right now: [erigon-docker-mainnet-20210910.log](https://github.com/ledgerwatch/erigon/files/7144190/erigon-docker-mainnet-20210910.log)

**Comment by KaiRo-at** [comment]
And here's the last ~500 lines of the logs from the mainnet node that is at over 50GB `RES` right now: [erigon-docker-mainnet-20210910.log](https://github.com/ledgerwatch/erigon/files/7144202/erigon-docker-mainnet-20210910.log)

**Comment by KaiRo-at** [comment]
Also, when I first looked for issues on memory consumption last night, I found #2123 and as the Ropsten node was logging at that point (after clogging up the machine once more), I noticed that memory consumption did indeed drop slightly when some stages finished (could have been around execution or so, I don't remember exactly), but it was only a reduction of a few hundred MB at best when the process already took up 5-10 GB total.

**Comment by AskAlexSharov** [comment]
Ok, something is wrong with “Stage 1: headers download”. Likely regression after https://github.com/ledgerwatch/erigon/pull/2614

**Comment by AlexeyAkhunov** [comment]
We would need a heap dump to investigate this. Running with `--pprof` and then running `go tool pprof http://localhost:6060/debug/pprof/heap` and then making PNG would give us more info

**Comment by AskAlexSharov** [comment]
`go tool pprof -png  http://127.0.0.1:6060/debug/pprof/heap > mem.png`

**Comment by KaiRo-at** [comment]
I'm running the ropsten node with `--pprof` right now and will get back to you with the data once it has been running for a while.

**Comment by KaiRo-at** [comment]
OK, right now, the Ropsten node is up to 3.4g `RES` though internally it thinks it has allocated about half of that or so. In any case, I tried to give you some data, so I tried running it like this:

```
docker-compose -f /data/docker-compose.yml exec -u root erigon sh
apk add --no-cache go graphviz
go tool pprof -png http://127.0.0.1:6060/debug/pprof/heap > /path/to/volume/mem.png
```

But I found out that there was some font missing or something, as all characters came out as squares on that PNG, which isn't very helpful. So I ended up creating an SVG instead, though I had to go in with Inkscape to resize the document to the content so a normal image viewer would display it usefully. And then I found that GitHub doesn't support adding an SVG here :( - So, another trip to Inkscape and export as PNG to give you this here:
![erigon-ropsten-20210910-1](https://user-images.githubusercontent.com/824140/132879701-f3bb3728-a339-46ec-b3a8-465a7958b25a.png)

**Comment by AlexeyAkhunov** [comment]
Thanks a lot, we'll take a look at those

**Comment by KaiRo-at** [comment]
Here's another one taken after the process blew up to 13GB `RES` (I guess it pretty much says the same thing, but just to be complete): 
![erigon-ropsten-20210910-2](https://user-images.githubusercontent.com/824140/132885261-870b6695-ad7c-4114-970f-71b1242a1040.png)

**Comment by AlexeyAkhunov** [comment]
So it looks like the majority of heap space is occupied by blobs of about 640 bytes (there are approx 1.3 million of them) appearing during the parsing of headers. This is unexpected, I'd need to try to reproduce

**Comment by KaiRo-at** [comment]
FWIW, the Ropsten node is on a machine that is quite loaded from other processes as well, has rotating disk storage, and is seeing the same problem with 2021.08.5

**Comment by KaiRo-at** [comment]
Is it possible that stage 1 / parsing headers is started again and again while it is already running from a previous time it was started, and running that in parallel causes issues, like e.g. some kind of objects to be abandoned and never cleaned up? Just from the logs and the data, something like that would sound likely, without actually knowing anything about the code or its architecture.

**Comment by AskAlexSharov** [comment]
@KaiRo-at , staged sync is single-threaded, but communication with peers is multi-threaded. 
So, yes it syncing with peers in parallel and save headers by ParseSegment method, then stage 1 processing them when it can. 

But there are limits, which must protect RAM. Likely it's "objects to be abandoned and never cleaned up" problem.

**Comment by KaiRo-at** [comment]
Trying to run with 2021.08.5 for now, I saw that the points where a real lot of memory growth is happening, the logs are full withg messages like this:

```
erigon_1                     | [WARN] [09-15|18:23:55.005] Invalidating anchor for suspected unavailability height=11039324
erigon_1                     | [WARN] [09-15|18:23:57.002] Invalidating anchor for suspected unavailability height=11043358
erigon_1                     | [WARN] [09-15|18:23:58.213] Invalidating anchor for suspected unavailability height=11042974
erigon_1                     | [WARN] [09-15|18:23:59.002] Invalidating anchor for suspected unavailability height=11042014
erigon_1                     | [WARN] [09-15|18:23:59.002] Invalidating anchor for suspected unavailability height=11042398
erigon_1                     | [WARN] [09-15|18:23:59.037] Invalidating anchor for suspected unavailability height=11047591
erigon_1                     | [WARN] [09-15|18:24:00.000] Invalidating anchor for suspected unavailability height=11040286
erigon_1                     | [WARN] [09-15|18:24:03.765] Invalidating anchor for suspected unavailability height=11047015
erigon_1                     | [WARN] [09-15|18:24:04.256] Invalidating anchor for suspected unavailability height=11041822
```

**Comment by MysticRyuujin** [comment]
This could have something to do with the Ropaten fork... I saw a lot of those too before reverting the bad block...

**Comment by KaiRo-at** [comment]
Ropsten has just a slightly higher rate of reorgs / forked blocks than Mainnet, but it sometimes has forks that go on for a longer period / block height. All in all, it's a pretty good test network for Ethereum node / client software, I hope the Erigon team is running a few Ropsten nodes due to this. Also, with the Docker container available, it's easier than ever before to actually set up and run such nodes. :)

All that said, I also always have services always hooked up to our nodes (via RPC), at least for monitoring node health, and those do a lot of requests for the current block with eth_getBlockByNumber (probably with "latest" as the parameter) and also to web3_clientVersion (which I have in the status output but I guess web3.py is requesting that also as a heartbeat for the connection). I would guess that it may not play a role for this leak, but I wanted to mention that in case it does.

**Comment by jlokier** [comment]
I don't know if it's helpful, but the first time I ran Erigon on Mainnet, it was up to 43.19 GiB sys, 26.69 GiB alloc, within 15 minutes:
```
INFO[09-08|14:51:04.827] [1/18 Headers] Wrote block headers       number=5584968 blk/second=0.000 alloc="26.69 GiB" sys="43.19 GiB"
```

I stopped it with Control-C, and then subsequent restarts kept crashing out quickly with:
```
INFO[09-08|15:00:20.285] Opening Database                         label=chaindata path=/home/jamie/.erigon/mainnet/chaindata
EROR[09-08|15:00:20.286] Erigon startup                           err="missing block number for head header hash"
```

As it had only been 15 minutes I wiped the datadir and started again, then it worked fine, using no more than 9.03 GiB sys, 1.11 GiB alloc, during the block bodies download.

The current instance I have running which is fully synced to mainnet, has settled on 10.60 GiB sys, 2.18 GiB alloc:
```
INFO[09-20|17:13:25.611] [1/18 Headers] Wrote block headers       number=13263632 blk/second=0.000 alloc="2.18 GiB" sys="10.60 GiB
"
```

**Comment by KaiRo-at** [comment]
As another note, this has been happening a lot with versions before but has become rare with 2021.09.4 - though I still did see it, after some restarts, it was fine, at least for quite a while.

**Comment by AskAlexSharov** [comment]
@KaiRo-at thank you

**Comment by sthornington** [comment]
I am not sure if this is relevant, but I had a bad time trying to sync up a ropsten db.  Goerli seems to be working fine, and I'll try mainnet once a new disk arrives.

**Comment by soulmachine** [comment]
Memory consumption is horrible 

![erigon-memory](https://user-images.githubusercontent.com/620768/165872628-a7713d77-d5a2-4add-a30a-be38ff7551c2.jpg)

**Comment by AskAlexSharov** [comment]
@soulmachine https://github.com/ledgerwatch/erigon#htop-shows-incorrect-memory-usage

**Comment by soulmachine** [comment]
@AskAlexSharov and I saw my Ubuntu started to use swap on disk, was it also incorrect?

**Comment by AskAlexSharov** [comment]
If real memory owned by App grows to max, then OS will Swap it. If virtual memory attributed to App but owned by OS go to max, then must be no swap - must be PageCache eviction until OS get’s enough free RAM.

**Comment by AskAlexSharov** [comment]
You may see “alloc” in our logs - this is memory hardly holded by app, if it’s big it’s bad (but we know couple reasons why it may =10gb, will fix them some day).
