### ISSUE TITLE
To port bitcurve.add changes

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2680]
from https://github.com/ethereum/go-ethereum/pull/22621 to https://github.com/ledgerwatch/secp256k1

**Comment by iszubok** [comment]
I would like to take this one. @AskAlexSharov, there are 7 commits in original PR, only one of which has bitcurve.add changes, the rest are fuzzer implementation. Do we need to port fuzzer as well?

**Comment by AskAlexSharov** [comment]
Yes
