### ISSUE TITLE
[meta] Include preverified-hashes step in RELEASE_INSTRUCTIONS.md

### ISSUE THREAD

**Issue by tsutsu** [ledgerwatch/erigon#2690]
Unsure how exactly to invoke it, but I see that `hack extractHashes` exists and is used to (re)generate the `preverified_hashes_*.go` files.

Presumably, if the jumpdest `SkipAnalysis` function should get updated before each release (except emergency releases), then these files should be regenerated before each release as well?

**Comment by AskAlexSharov** [comment]
i think so
