### ISSUE TITLE
MDBX_UNABLE_EXTEND_MAPSIZE: Database engine was unable to extend mapping (On windows)

### ISSUE THREAD

**Issue by mtbitcoin** [ledgerwatch/erigon#2705]
Erigon version: v2021.09.03-alpha_5c377a4.
OS & Version: Windows Server 2019

RPCDaemon command line : 
rpcdaemon --datadir mainnet --http.api=eth,debug,net,web3,trace --http.port 8546 --http.addr 0.0.0.0 --http.corsdomain "*" --http.vhosts "*"

This issue appears to affect the windows builds when running rpcdaemon with shared memory access (--datadir mainnet ). Both erigon and rpcdaemon is on the same machine. After running it for a couple hours, will eventually run into the below errors. Restarting the rpcdaemon fixes the issue until it happens again after a couple of hours.

The erigon client appears unaffected. The issue affect the rpcdaemon 

-Error log snippet-

WARN[09-20|03:12:21.497] Served                                   conn=x.x.x.x:35224 method=debug_traceTransaction reqid=0 t=0s err="mdbx_txn_begin: MDBX_UNABLE_EXTEND_MAPSIZE: Database engine was unable to extend mapping, e.g. since address space is unavailable or busy, or Operation system not supported such operations, label: chaindata, trace: [github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).BeginRo github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*PrivateDebugAPIImpl).TraceTransaction reflect.Value.call reflect.Value.Call github.com/ledgerwatch/erigon/rpc.(*callback).call github.com/ledgerwatch/erigon/rpc.(*handler).runMethod github.com/ledgerwatch/erigon/rpc.(*handler).handleCall github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1 github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1]"
WARN[09-20|03:12:30.619] Served                                   conn=127.0.0.1:1299 method=eth_blockNumber reqid=83 t=0s err="mdbx_txn_begin: MDBX_UNABLE_EXTEND_MAPSIZE: Database engine was unable to extend mapping, e.g. since address space is unavailable or busy, or Operation system not supported such operations, label: chaindata, trace: [github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).BeginRo github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).BlockNumber reflect.Value.call reflect.Value.Call github.com/ledgerwatch/erigon/rpc.(*callback).call github.com/ledgerwatch/erigon/rpc.(*handler).runMethod github.com/ledgerwatch/erigon/rpc.(*handler).handleCall github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1 github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1]"
WARN[09-20|03:12:37.130] Served                                   conn=x.x.x.x:35224 method=debug_traceTransaction reqid=0 t=0s err="mdbx_txn_begin: MDBX_UNABLE_EXTEND_MAPSIZE: Database engine was unable to extend mapping, e.g. since address space is unavailable or busy, or Operation system not supported such operations, label: chaindata, trace: [github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).BeginRo github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*PrivateDebugAPIImpl).TraceTransaction reflect.Value.call reflect.Value.Call github.com/ledgerwatch/erigon/rpc.(*callback).call github.com/ledgerwatch/erigon/rpc.(*handler).runMethod github.com/ledgerwatch/erigon/rpc.(*handler).handleCall github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1 github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1]"

**Comment by AskAlexSharov** [comment]
Hi. Show “du -ha <datadir>“

**Comment by mtbitcoin** [comment]
This is a window machine. So du does not work. I've attached a screen cap of the disk utilization

![image](https://user-images.githubusercontent.com/8327464/134009775-9dacd1bf-8f62-4f05-b818-eaded0d27d40.png)

**Comment by AskAlexSharov** [comment]
@mtbitcoin no space left on disk?

**Comment by mtbitcoin** [comment]
Around 2tb of disk space left. Googling for similar issues on MDBX_UNABLE_EXTEND_MAPSIZE and windows

https://github.com/erthink/libmdbx/issues/98

**Comment by AskAlexSharov** [comment]
I don’t know. You have free space, your db is 1.5Tb (with 2Tb limit and 2Gb growth step). No reason to get MDBX_UNABLE_EXTEND_MAPSIZE. 

What is “nodes” folder size?

**Comment by mtbitcoin** [comment]
> I don’t know. You have free space, your db is 1.5Tb (with 2Tb limit and 2Gb growth step). No reason to get MDBX_UNABLE_EXTEND_MAPSIZE.
> 
> What is “nodes” folder size?

513 MB
![image](https://user-images.githubusercontent.com/8327464/134144708-1a62ba17-2162-495d-af9e-2d4abfe2229d.png)

**Comment by AndreaLanfranchi** [comment]
@AskAlexSharov I believe **on Windows** this should be expected. As we know from LMDB experience there's a 1:1 relation amongst map_size and file_size on windows. And actually MDBX makes no difference: it simply "hides" the problem using its geometry increase logic. On Windows the only way possible to extend the data file is to unmap it, resize it, and eventually remap it but as the db is opened by two distinct processes (erigon and rpcdaemon) there might be issues releasing the locks on file.

I suspect that actually is erigon asking for more space but don't understand why the logs about the error are printed by rpcdaemon.

Maybe we could start digging from [here](https://github.com/erthink/libmdbx/blob/99b75b5004047d8792973501d8eb7ef49df9a5da/src/osal.c#L1594-L1613)

@mtbitcoin can you please try run rpcdaemon for a long batch **without** `--datadir` command line option ?

**Comment by mtbitcoin** [comment]
> @AskAlexSharov I believe **on Windows** this should be expected. As we know from LMDB experience there's a 1:1 relation amongst map_size and file_size on windows. And actually MDBX makes no difference: it simply "hides" the problem using its geometry increase logic. On Windows the only way possible to extend the data file is to unmap it, resize it, and eventually remap it but as the db is opened by two distinct processes (erigon and rpcdaemon) there might be issues releasing the locks on file.
> 
> I suspect that actually is erigon asking for more space but don't understand why the logs about the error are printed by rpcdaemon.
> 
> Maybe we could start digging from [here](https://github.com/erthink/libmdbx/blob/99b75b5004047d8792973501d8eb7ef49df9a5da/src/osal.c#L1594-L1613)
> 
> @mtbitcoin can you please try run rpcdaemon for a long batch **without** `--datadir` command line option ?

**Without**  "--datadir" it works fine, albeit at a lower RPC performance (not as fast). Also, no issue on ubuntu. So this only appears when
1. using --datadir with rpcdaemon
2. running on windows

**Comment by AndreaLanfranchi** [comment]
> **Without** "--datadir" it works fine, albeit at a lower RPC performance (not as fast). Also, no issue on ubuntu. So this only appears when
> 
> 1. using --datadir with rpcdaemon
> 2. running on windows

Yes ... as I mentioned before this specific issue **only** affects windows due to differences about how the NT kernel memory maps files. Unfortunately this creates strong limitations on achieving best performances on Windows (besides we [have also other kind of issues on Windows in the related project Silkworm](https://github.com/torquem-ch/silkworm#windows) which is erigon's implementation in C++). Also you might enjoy [this comment](https://github.com/erthink/libmdbx/blob/a5e10b4ea1e3ae80b521c9100c0f58616cfd9034/src/lck-windows.c#L17-L21) from MDBX authors.

If max rpcdaemon performance is what is you're aiming to I definitely suggest to stick to Linux.
(we might find solutions in the future though)

**Comment by AskAlexSharov** [comment]
> 513 MB

this is too much, maybe problem coming from there. show what is inside and what sizes of folders there. 
then try to remove this (nodes) folder and see if it helped you.

**Comment by mtbitcoin** [comment]
> > 513 MB
> 
> this is too much, maybe problem coming from there. show what is inside and what sizes of folders there.
> then try to remove this (nodes) folder and see if it helped you.

Under (nodes) folder
--------------------
eth65 (2 files) ~256mb
eth66 (2 files) ~256mb

I don't think they are related to to how large these folders are, because just restarting the RPC daemon (without needing to restart erigon) works for a couple of hours again before running into the same errors again later.

**Comment by AskAlexSharov** [comment]
“ I don't think they are related ” - they have low maximum limit, and maybe you touched it. Try remove them and see if it helps.

**Comment by mtbitcoin** [comment]
1. Stopped both erigon and rpcdaemon
2. Removed the Nodes folder
3. Restarted both erigon and rpcdaemon
4. Nodes folder eventually build back up the same size previous and files
5. Does not resolve the issue

**Comment by AskAlexSharov** [comment]
Does "remove --datadir from rpcdaemon on windows" ok for you?

**Comment by mtbitcoin** [comment]
> Does "remove --datadir from rpcdaemon on windows" ok for you?

Yes, as shared above running it with out the “—datadir” works but that sacrifices  rpc performance

**Comment by AskAlexSharov** [comment]
Then probably we just must recommend this way on Win. (Performance of remote rpc-daemon will get better - we will have caching - we working on some pre-requirements for it).

**Comment by AskAlexSharov** [comment]
closing for now - as no better solution yet
