### ISSUE TITLE
Erigon method eth_chainID is not compatible with other client.

### ISSUE THREAD

**Issue by begetan** [ledgerwatch/erigon#2708]
#### Description

We use case-sensitive strict filters to apply white-lists for RPC requests.
According to the [documentation](https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md), Erigon is using the method `eth_chainID`
According to the Ethereum proposal [eip-695](https://eips.ethereum.org/EIPS/eip-695)  this method should be `eth_chainId` 

This makes Erigon incompatible with other clients when following documentation strictly.

I think that actually Erigon just accepts both forms.  Could you confirm it and update the documentation accordingly?

**Comment by AskAlexSharov** [comment]
@begetan we already have both
