### ISSUE TITLE
Incorrect transaction field "From" value?

### ISSUE THREAD

**Issue by 8travis** [ledgerwatch/erigon#2712]
I've just got my erigon node synced, soooo fast! But after playing with rpc calls got some questions:

When I request {"jsonrpc":"2.0","method":"eth_getBlockByHash","params": ["0x9a7c48f0e9779f731168e2ae319e404a2efd32dfa2d3ce0d3fb1466301f33be8",true],"id":1}
it returns 236 entries where one of them is -
...,
{
	"blockHash": "0x9a7c48f0e9779f731168e2ae319e404a2efd32dfa2d3ce0d3fb1466301f33be8",
	"blockNumber": "0xc977b4",
	"from": "0x0000000000000000000000000000000000000000",
	"gas": "0x5530a0",
	"gasPrice": "0xe2710488b",
	"maxPriorityFeePerGas": "0x59682f00",
	"maxFeePerGas": "0x159aea641f",
	"hash": "0xe8106c5e5df2313fc95e5bebfd1dfcadb8131f0e9c897f10be176f7e05ca2f96",
	"input": "<REMOVED TO MAKE IT SHORT>",
	"nonce": "0x1",
	"to": null,
	"transactionIndex": "0xd7",
	"value": "0x0",
	"type": "0x2",
	"chainId": "0x1",
	"v": "0x1",
	"r": "0x1c246ac65af899876ed70fcab16d9d96cfd6a7f02d1250217e4fac7038c1da26",
	"s": "0x25ad7d2adaf769e5e2bd99f3396ea7c7faa88cc143bcd6e1de7a7e5b9f826386"
},
...

please note the field "from", which is 0x0.

When I request this particular transaction via {"jsonrpc":"2.0","method":"eth_getTransactionByHash","params": ["0xe8106c5e5df2313fc95e5bebfd1dfcadb8131f0e9c897f10be176f7e05ca2f96"],"id":1}
I got the identical structure except it shows the correct "from" value which is "0x71d6c3823bbbce39af789d2b063ad33b2ecda7d3"

Is it expected behavior or my DB got corrupted? I downloaded with "2021.09.01-alpha" and after full sync upgraded to "2021.09.03-alpha". Thanks!

**Comment by AskAlexSharov** [comment]
My node returns `"from":"0x71d6c3823bbbce39af789d2b063ad33b2ecda7d3"`
What cli parameters you used to start erigon?

**Comment by 8travis** [comment]
I run it in docker as /erigon/bin/erigon --private.api.addr="localhost:9090" --etl.bufferSize=1024MB --txpool.globalslots 100000 --txpool.globalqueue 100000 --datadir="/erigon/data"

After checking logs I also found this message happened during the sync stage:

[INFO] [09-12|14:39:13.227] Update current block for the RPC API     from=13191488 to=13191487
[INFO] [09-12|14:39:13.227] [1/18 Headers] Waiting for headers...    from=13191487
[INFO] [09-12|14:39:43.228] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.71 GiB" sys="15.47 GiB"
[INFO] [09-12|14:40:13.227] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.44 GiB" sys="15.47 GiB"
[INFO] [09-12|14:40:43.227] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.05 GiB" sys="15.47 GiB"
[INFO] [09-12|14:41:10.727] [p2p] GoodPeers                          eth66=30 eth65=32
[INFO] [09-12|14:41:13.228] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.82 GiB" sys="15.47 GiB"
[INFO] [09-12|14:41:43.227] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.52 GiB" sys="15.47 GiB"
[INFO] [09-12|14:41:43.227] [1/18 Headers] Processed                 highest inserted=0 age=52y5mo1w
[INFO] [09-12|14:41:43.227] [1/18 Headers] DONE                      in=2m30.000804189s
[INFO] [09-12|14:41:43.228] Update current block for the RPC API     from=13191488 to=13191487
[INFO] [09-12|14:41:43.228] [1/18 Headers] Waiting for headers...    from=13191487
[INFO] [09-12|14:42:13.229] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.32 GiB" sys="15.47 GiB"
[INFO] [09-12|14:42:43.229] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.95 GiB" sys="15.47 GiB"
[INFO] [09-12|14:43:10.727] [p2p] GoodPeers                          eth66=30 eth65=32
[INFO] [09-12|14:43:13.229] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.67 GiB" sys="15.47 GiB"
[INFO] [09-12|14:43:43.229] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.20 GiB" sys="15.47 GiB"
[INFO] [09-12|14:44:13.229] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.81 GiB" sys="15.47 GiB"
[INFO] [09-12|14:44:13.229] [1/18 Headers] Processed                 highest inserted=0 age=52y5mo1w
[INFO] [09-12|14:44:13.229] [1/18 Headers] DONE                      in=2m30.000558413s
[INFO] [09-12|14:44:13.230] Update current block for the RPC API     from=13191488 to=13191487
[INFO] [09-12|14:44:13.230] [1/18 Headers] Waiting for headers...    from=13191487
[INFO] [09-12|14:44:43.231] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.63 GiB" sys="15.47 GiB"
[INFO] [09-12|14:45:10.727] [p2p] GoodPeers                          eth66=30 eth65=32
[INFO] [09-12|14:45:13.231] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.35 GiB" sys="15.47 GiB"
[INFO] [09-12|14:45:43.231] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.05 GiB" sys="15.47 GiB"
[INFO] [09-12|14:46:13.231] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.63 GiB" sys="15.47 GiB"
[INFO] [09-12|14:46:43.231] [1/18 Headers] Wrote block headers       number=13191487 blk/second=0.000 alloc="1.29 GiB" sys="15.47 GiB"
[INFO] [09-12|14:46:43.231] [1/18 Headers] Processed                 highest inserted=0 age=52y5mo1w
[INFO] [09-12|14:46:43.231] [1/18 Headers] DONE                      in=2m30.001158232s

It was infinite loop of the same messages  "Update current block for the RPC API     from=13191488 to=13191487"

It continued fine after upgrading to "2021.09.03".

**Comment by 8travis** [comment]
Also it was compiled with go 1.17

**Comment by 8travis** [comment]
I was also wondering if there is a way to re-check/re-build data integrity/indexes after the full sync?

**Comment by AskAlexSharov** [comment]
`It was infinite loop of the same messages "Update current block for the RPC API from=13191488 to=13191487"` - it's another non-related known issue. for now if restart doesn't help, remove folder `<datadir>/nodes`.

**Comment by AskAlexSharov** [comment]
> I can confirm that eth_getBlockByHash returns invalid "from" on a lot of TXs for every block I tried. Both local erigon and archivenode.io. While eth_getTransactionByHash returns the correct value.
> Running latest stable. No prunning.

Then I will create some tool to check senders in DB

**Comment by AskAlexSharov** [comment]
Branch: `sender_check`
Command: `go run -trimpath ./cmd/integration stage_senders --datadir=<datadir> --integrity.slow=true --block=13_000_000`

**Comment by alysak6075** [comment]
@AskAlexSharov  should the node be running while i run this?

**Comment by alysak6075** [comment]
saw a bunch of these lines and no issues:
INFO[09-21|21:41:50.067] checked                                  block=13272700
INFO[09-21|21:41:50.248] checked                                  block=13272710
INFO[09-21|21:41:50.357] checked                                  block=13272720
INFO[09-21|21:41:50.584] checked                                  block=13272730
INFO[09-21|21:41:50.712] checked                                  block=13272740
INFO[09-21|21:41:50.865] checked                                  block=13272750
INFO[09-21|21:41:51.008] checked                                  block=13272760
INFO[09-21|21:41:51.211] checked                                  block=13272770
INFO[09-21|21:41:51.379] checked                                  block=13272780
INFO[09-21|21:41:51.548] checked                                  block=13272790
INFO[09-21|21:41:51.733] checked                                  block=13272800
INFO[09-21|21:41:51.986] checked                                  block=13272810
INFO[09-21|21:41:52.209] checked                                  block=13272820
INFO[09-21|21:41:52.415] checked                                  block=13272830
INFO[09-21|21:41:52.603] checked                                  block=13272840
INFO[09-21|21:41:53.167] database closed                          label=chaindata

**Comment by AskAlexSharov** [comment]
then looks like db has correct values

**Comment by alysak6075** [comment]
also archivenode.io has same issue

**Comment by AskAlexSharov** [comment]
Ok. Then help me check next things plz: 
1. go to branch `sender_check_dbg` - rebuild rpcdaemon - run that request where you see `from: 0x0` - show me logs of rpcdaemon
2. go to branch `sender_check_read_from_db` - rebuild rpcdeamon - run that request where you see `from: 0x0` - see if it fixing issue or not.

**Comment by 8travis** [comment]
1) cmd from branch sender_check - all checked

2) rpcdaemon logs from branch:

log [INFO] [09-22|04:02:00.732] recovered                                tx=ad4083c5da454e1fd8cce31e4f86eafae1d4faaa832bbc1a9be9ac2cfd956a87 sender="ebf9532ca9c982b69e91ecbb4b8da3eac65453ca\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=d101a0f6a0c0bcf04ba22ba190a7952277ccf29c51495f1254e69fd2cfdc0b8b sender="b0452276df7406de56d78345480facdda3b9666a\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=8d39ddd02d8138eacd6f01b3c34447171cc5316ae1d5c196f7b1e52c10c8997c sender="15dce17509846b420b1f5c158fe3d7518204abb6\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=2816edae0aeb88f38e81b60f2391048238ecb17a5434beece2116c314e096356 sender="4910f2cecdab9da69685e7c16cdacf484bb5065a\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=2924de9db3dca9bcecad24e0422f3a4fe1786829d064cf6ea29872c34fa9ef8a sender="1938a448d105d26c40a52a1bfe99b8ca7a745ad0\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=c485ed1a7684cb036cba3b56c3d2061d0ea13d81a87d7d8020d72b3de4f3aa4a sender="000000a23c3512d4aab1129564b7e4e1ff571287\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=7d988e1305ab861a5157afc7e592933e67963418e408cd9d4434292a2aeeb18f sender="824a6e242bf2d17cb9850a24f918a0b22f3b864d\n"
[INFO] [09-22|04:02:00.733] recovered                                tx=7fa571cff28c4e5798b82af110bb0bcfff1d4d0b534eca0b167f1e99fa1bf6b3 sender="e93381fb4c4f14bda253907b18fad305d799241a\n"
<many more>

3) rpcdaemon from sender_check_read_from_db  returns correct from

**Comment by AskAlexSharov** [comment]
then fixed by https://github.com/ledgerwatch/erigon/pull/2717
