### ISSUE TITLE
When calling eth_getBlockByHash, some From fields are zeros 

### ISSUE THREAD

**Issue by yoavj1** [ledgerwatch/erigon#2720]
#### System information

Erigon version: 2021.09.4-alpha

OS & Version: Linux

When using eth_getBlockByHash, for some transactions, the "from" field has the value of 0x0000000000000000000000000000000000000000, instead of the actual sender. It happens also for some regular transfers (without smart contracts).

Note that it doesn't happen when using eth_getBlockByNumber, for the same block, for which I get the correct sender addresses

#### Expected behaviour
Receive the actual sender address

#### Actual behaviour
Receiving 0x0000000000000000000000000000000000000000 as sender address

#### Steps to reproduce the behaviour
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getBlockByHash", "params": [
"0x2a77f524606bdd4bfb4487ee96e9495e416ea21ea27a8819aec04e552a3f93c4", true], "id":1}' localhost:8545

An example problematic transaction in this block is 0xd815add2cb3da187c4fb3710341b2f95ed05f4b3d94467df872a05377fda58db, for which I get:
{"blockHash":"0x2a77f524606bdd4bfb4487ee96e9495e416ea21ea27a8819aec04e552a3f93c4","blockNumber":"0xa91e6c","from":"0x0000000000000000000000000000000000000000","gas":"0x5208","gasPrice":"0x9ad54e1e","maxPriorityFeePerGas":"0x9ad54e16","maxFeePerGas":"0x9ad54e23","hash":"0xd815add2cb3da187c4fb3710341b2f95ed05f4b3d94467df872a05377fda58db","input":"0x","nonce":"0x18","to":"0x4d8924151fe831d627786a499f02cf27325a196f","transactionIndex":"0x6","value":"0x16345785d8a0000","type":"0x2","chainId":"0x3","v":"0x0","r":"0xc0a66b9d5fd42e0972f2fb9deb03539ad025684849713f69d5a1d30581e472c3","s":"0x401ea8d27660e18055ea30701285be6d37e412b884bedc4ca741f5095af433cc"}

**Comment by AskAlexSharov** [comment]
I think fixed by https://github.com/ledgerwatch/erigon/pull/2717

**Comment by yoavj1** [comment]
Sorry I missed that, it does seem like the same issue - I'll close this one
