### ISSUE TITLE
Flags: --prune.*.older=0 must disable stages

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2725]
- Stages after StageIntermediateHash - can be disabled - if --prune.*.older=0
- ChangeSets work: StageHashState, StageIntermediatHashes, Unwind of StageExec). It means: StageExec still must write FullImmutabilityThreshold amount of ChangeSets - even if --prune.h.older < FullImmutabilityThreshold. See variables `writeChangeSets` and `nextStagesExpectData`. (Please create test for this corner case - because if pruned node will have not-enough changeSets for re-org - there will be no way to repair it, only re-sync).

FYI: this feature is part of "mining edition" roadmap. There we will disable all stages after IntermediateHashes.

**Comment by Cript** [comment]
@AskAlexSharov , as I understand the correct way should be 

1. execute `Forward` for all stages before `CallTraces`
2. call `Unwind` for `Execution` stage

Is it correct?

**Comment by AskAlexSharov** [comment]
@Cript depends on flag. “c” can disable CallTraces stage at all (and Execution will not write CallTraceSet). “r” and “t” - same as “c”. “h” can disable HistoryIndices stage, but Execution will need write ChangeSets of 90K blocks, because they required for Unwind (and for StageHashState).
