### ISSUE TITLE
p2p node database update failed [again]

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#2729]
I've just noticed it started to happen again:

```
WARN[09-25|14:07:17.728] p2p node database update failed          path=/Volumes/erigon-data/nodes/eth66 err="mdbx_cursor_put: operation not permitted"
```

du -h

```
7.0M	/Volumes/erigon-data/nodes/eth66
 56M	/Volumes/erigon-data/nodes/eth65
 63M	/Volumes/erigon-data/nodes
  0B	/Volumes/erigon-data/etl-temp
 20K	/Volumes/erigon-data/.fseventsd
du: /Volumes/erigon-data/.Spotlight-V100: Operation not permitted
1.5T	/Volumes/erigon-data/chaindata
  0B	/Volumes/erigon-data/crashreports
1.5T	/Volumes/erigon-data
```

Using the latest stable.

_Originally posted by @wmitsuda in https://github.com/ledgerwatch/erigon/issues/2570#issuecomment-927153852_

**Comment by AskAlexSharov** [comment]
@wmitsuda had you faced it since then?

**Comment by wmitsuda** [comment]
I haven't been running my node for long periods over the last days, so I didn't notice it.

I'll let it run non-stop now and see if it happens, I'll let you know.

**Comment by wmitsuda** [comment]
Got it, left it running overnight and it is happening again. The message is slightly different on this version.

```
WARN[10-06|10:49:41.825] p2p node database update failed          path=/Volumes/erigon-data/nodes/eth66 err="table: Inode, err: mdbx_cursor_put: operation not permitted"
```

Lots of these messages.
