### ISSUE TITLE
MDBX_PAGE_NOTFOUND error prevents sync finishing

### ISSUE THREAD

**Issue by Tronic** [ledgerwatch/erigon#2730]
Syncing hangs at stage 13 with a repeating error. After the error stage 13 restarts and this repeats after about 90 minutes once it again reaches number 12316795.

```
[INFO] [09-25|16:08:18.677] [13/18 AccountHistoryIndex] Progress     number=12304037 alloc="1.4 GiB" sys="10.7 GiB"
[INFO] [09-25|16:08:38.482] Flushed buffer file                      name=/srv/erigon/etl-temp/tg-sync-sortable-buf911676053 alloc="3.4 GiB" sys="10.7 GiB"
[INFO] [09-25|16:08:48.707] [13/18 AccountHistoryIndex] Progress     number=12316795 alloc="3.6 GiB" sys="10.7 GiB"
[INFO] [09-25|16:08:58.612] [13/18 AccountHistoryIndex] etl: temp files removed total size="19.5 GB"
[EROR] [09-25|16:08:58.612] Staged Sync                              error="[13/18 AccountHistoryIndex] failed MdbxKV cursor.Next(): mdbx_cursor_get: MDBX_PAGE_NOTFOUND: Requested page not
 found"
[INFO] [09-25|16:09:33.494] Flushed buffer file                      name=/srv/erigon/etl-temp/tg-sync-sortable-buf3614158811 alloc="4.8 GiB" sys="10.7 GiB"
[INFO] [09-25|16:09:36.082] [13/18 AccountHistoryIndex] Progress     number=2426971 alloc="5.8 GiB" sys="10.7 GiB"
[INFO] [09-25|16:09:50.830] Flushed buffer file                      name=/srv/erigon/etl-temp/tg-sync-sortable-buf2006043711 alloc="4.0 GiB" sys="10.7 GiB"
[INFO] [09-25|16:10:00.628] [13/18 AccountHistoryIndex] Progress     number=2458437 alloc="2.6 GiB" sys="10.7 GiB"
[INFO] [09-25|16:10:02.172] [p2p] GoodPeers                          eth66=31 eth65=33
[INFO] [09-25|16:10:12.141] Flushed buffer file                      name=/srv/erigon/etl-temp/tg-sync-sortable-buf2867541441 alloc="3.5 GiB" sys="10.7 GiB"
```

Running erigon version 2021.09.4-alpha with initial sync but the service has been restarted a few times while it was running. Possibly systemd has killed it if it took more than 30 seconds to exit. Perhaps this corrupted the database?

**Comment by Tronic** [comment]
Tried stopping the daemon and deleting etl-temp. After restarting it did the prior stages again or for new blocks, and then got stuck again:

```
[INFO] [09-25|22:52:22.736] [13/18 AccountHistoryIndex] Progress     number=12320705 alloc="2.5 GiB" sys="9.8 GiB"
[INFO] [09-25|22:52:30.601] [13/18 AccountHistoryIndex] etl: temp files removed total size="19.2 GB"
[EROR] [09-25|22:52:30.611] Staged Sync                              error="[13/18 AccountHistoryIndex] failed MdbxKV cursor.Next(): mdbx_cursor_get: MDBX_PAGE_NOTFOUND: Requested page not found"
```

**Comment by AskAlexSharov** [comment]
hi
- what is your FS 
- do you use any manual FS tuning

try run: 
```
make db-tools
./build/bin/mdbx_chk -v -d <datadir>/chaindata
```

**Comment by AskAlexSharov** [comment]
please also try Erigon's version `v2021.09.03` - to see if it's related to https://github.com/ledgerwatch/erigon/pull/2716 or not

**Comment by Tronic** [comment]
The filesystem setup is... complicated. RAID of HDDs with bcache SSD caching, and btrfs on top of that with compression and autodefrag enabled. Still, I never had data corruption and there were no reboots or re-mount of the filesystem at any point.

Didn't try with the earlier Erigon build yet, since corruption was found:
```
mdbx_chk v0.10.3-0-gbf603bd (2021-08-27T22:47:12+03:00, T-89059f5e31a893b0739257a1df03e3d9fcc6d74d)
Running for /srv/erigon/chaindata in 'read-only' mode...
 - monopolistic mode
 - current boot-id 86d770b47f3377cb-b7f9d02ab0ff4f1b
 - pagesize 4096 (4096 system), max keysize 1980..2022, max readers 118
 - mapsize 2199023255552 (2.00 Tb)
 - dynamic datafile: 12288 (12.00 Kb) .. 2199023255552 (2.00 Tb), +2147483648 (2.00 Gb), -4096 (4.00 Kb)
 - current datafile: 1346472247296 (1.22 Tb), 328728576 pages
 - meta-0: steady txn#223, head
 - meta-1: steady txn#221, tail
 - meta-2: steady txn#222, stay
 - transactions: recent 223, latter reader 223, lag 0
Skipping b-tree walk...
Processing '@MAIN'...
 - key-value kind: usual-key => single-value
 - summary: 44 records, 0 dups, 526 key's bytes, 2112 data's bytes, 0 problems
Processing '@GC'...
 - key-value kind: ordinal-key => single-value
 - last modification txn#223
 - fixed key-size 8
 - summary: 222 records, 0 dups, 1776 key's bytes, 11952284 data's bytes, 0 problems
 - space: 536870912 total pages, backed 328728576 (61.2%), allocated 328418513 (61.2%), available 210790666 (39.3%)
 - skip check used and gc pages (btree-traversal with monopolistic or read-write mode only)
Processing 'AccountChangeSet'...
 - key-value kind: usual-key => multi-value
 - last modification txn#220
 ! corrupted broken-page #0, mod-txnid 0
 ! mismatch actual pgno (0) != expected (261584464)
 ! mdbx_cursor_get() failed, error -30797 MDBX_PAGE_NOTFOUND: Requested page not found
 - problems: different number of entries (1)
 - summary: 1763358549 records, 1751028607 dups, 14106868392 key's bytes, 52483395769 data's bytes, 1 problems
 ! mdbx_cursor_get() failed, error -30782 MDBX_BAD_TXN: Transaction is not valid for requested operation, e.g. had errored and be must aborted, has a child, or is invalid
 - problems: different number of entries (1)
Total 6 errors are detected, elapsed 2086.278 seconds.
[WARN] - (starship::utils): Executing command "git" timed out.
[WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.
```

**Comment by AskAlexSharov** [comment]
Yes, your db corrupted because of some FS reason. Actually it’s first time I see db corruption  (after we switched to mdbx - 6 months ago). I think it’s because you have some “write buffer”.

1. I advise disable btrfs autodefrag - with erigon db it eating too much disk. 
2. Usually “read cache of FS” does not lead to corruption. 
3. But “write cache” does. I advise disable write buffers - Erigon doesn’t write much - and see if you still fine with performance. 

Also, check - maybe you have some disk degradation. 

For more information about our db consistency see: https://github.com/erthink/libmdbx/blob/master/mdbx.h#L1150 (we using MDBX_SYNC_DURABLE option by default - as you can see it rely on fact that 2 fsync syscalls happening in right order and “FS’s write buffer” can break this order).

**Comment by Tronic** [comment]
Is there any way to backtrack from here without restarting the whole sync? Took me about a week on this setup and I cannot spare that much SSD space.

**Comment by AskAlexSharov** [comment]
If some of this will show no error, then maybe have chance to recover (otherwise nope):
./build/bin/mdbx_chk -v -d -2 <datadir>/chaindata
./build/bin/mdbx_chk -v -d -1 <datadir>/chaindata
./build/bin/mdbx_chk -v -d -0 <datadir>/chaindata

**Comment by Tronic** [comment]
Checking with `-2` finished with the same six errors and I decided to start from scratch. Using a RAID-0 built of two NVME partitions totaling just enough to fit the uncompressed chaindata. After 18 hours I am in 7-Execution, num 7M progressing at about 500 Mgas/s: roughly five times faster than on the SSD-cached HDD array. Perhaps a bit more parallelism could be implemented to speed up the initial sync (not that I know how exactly it works or how possible it is to do things concurrently).

I will report back if the sync now goes correctly, still using the same version of Erigon, and trying to avoid any daemon restarts this time. Closing for now.

**Comment by Tronic** [comment]
Finished and running OK now, despite two nasty interruptions. First a hard crash of erigon due to running out of disk space (mmapped I/O caused SIGBUS and a 3800-line traceback followed). Then much later a General Protection Fault and the entire machine crashed (a faulty kernel module, unrelated to this). Even with both of these, the database now stayed intact. The whole process took four days, and Execution, which took about three days, was CPU-bottlenecked the whole time (running on i5-11600k).

Note: One should either disable btrfs CoW or enable compression. Otherwise a lot more disk space is consumed than the actual file size of 1.6 TB (as of today, once everything was finished). Some 700 GB space lost to btrfs was the cause why I ran out of space pretty early in Execution.
