### ISSUE TITLE
Log for Update current block for the RPC API is reporting incorrect "from" number

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#2743]
Latest stable release:

Erigon used to say:

`Update current block for the RPC API from=<old> to=<new>`

Now it says `Update current block for the RPC API from=<new> to=<new>`

Something messed with the log output - every single log entry for that step is "non incrementing" it's the same block number in the from field and the to field.

Example:
```
[INFO] [09-28|15:44:59.353] Update current block for the RPC API     from=13316458 to=13316458
[INFO] [09-28|15:44:59.354] [1/18 Headers] Waiting for headers...    from=13316458
[INFO] [09-28|15:45:18.721] [1/18 Headers] Processed                 highest inserted=13316459 age=21s
[INFO] [09-28|15:45:19.321] [7/18 Execution] Completed on            block=13316459
[INFO] [09-28|15:45:20.082] [17/18 TxPool] Transaction stats         pending=4016 queued=1022
[INFO] [09-28|15:45:20.282] Commit cycle                             in=199.781096ms
[INFO] [09-28|15:45:20.282] Update current block for the RPC API     from=13316459 to=13316459
[INFO] [09-28|15:45:20.282] [1/18 Headers] Waiting for headers...    from=13316459
```

**Comment by AndreaLanfranchi** [comment]
> Now it says `Update current block for the RPC API from=<new> to=<new>`

Actually it's not `from=<new> to=<new>` rather `from=<old+1> to=<new>`: which basically, on 1 block cycles, is perceived as new to new.

**Comment by MysticRyuujin** [comment]
It's still wrong 🤷‍♂️

**Comment by AndreaLanfranchi** [comment]
> It's still wrong 🤷‍♂️

I don't get it. We have a PR linked but is not merged yet.

**Comment by quickchase** [comment]
Sorry @AndreaLanfranchi - I didn't see the PR. Thanks!
