### ISSUE TITLE
"block device required" error when starting Erigon

### ISSUE THREAD

**Issue by GBBx** [ledgerwatch/erigon#2761]
#### System information

Erigon version: `erigon version 2021.10.1-alpha`

OS & Version: Linux

Commit hash :  ef80fd54b1c6c82aae92f5fa24cbd381e8577b50

#### Expected behaviour
Erigon starts synchronising

#### Actual behaviour
Erigon fails to start

#### Steps to reproduce the behaviour
- Build with Go as described here: https://github.com/ledgerwatch/erigon#usage
- create datadir
- try to start erigon specifying the datadir (also fails without `--datadir` even if `~/.local/share/erigon/chaindata` exists)

#### Backtrace

````
erigon --datadir /erigon
INFO[10-01|10:44:40.318] Build info                               git_branch=HEAD git_tag=v2021.10.01 git_commit=ef80fd54b1c6c82aae92f5fa24cbd381e8577b50
INFO[10-01|10:44:40.319] Starting Erigon on Ethereum mainnet...
INFO[10-01|10:44:40.322] Maximum peer count                       ETH=100 total=100
INFO[10-01|10:44:40.322] Set global gas cap                       cap=50000000
INFO[10-01|10:44:40.416] Opening Database                         label=chaindata path=/erigon/chaindata
EROR[10-01|10:44:40.418] Erigon startup                           err="mdbx_env_open: block device required, label: chaindata, trace: [github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.Open github.com/ledgerwatch/erigon/node.OpenDatabase.func1 github.com/ledgerwatch/erigon/node.OpenDatabase github.com/ledgerwatch/erigon/eth.New github.com/ledgerwatch/erigon/turbo/node.RegisterEthService github.com/ledgerwatch/erigon/turbo/node.New main.runErigon github.com/urfave/cli.HandleAction github.com/urfave/cli.(*App).Run main.main]"


````

**Comment by AskAlexSharov** [comment]
@GBBx what is your disk? what is your FS?

**Comment by GBBx** [comment]
I tried to run it in a container with podman, mounting the `--datadir` as a volume (but it doesn't work even with other paths which are not on the mounted volume). I use xfs filesystem.
Is the `--datadir` supposed to be a device? So something like `/dev/sdb1`?

**Comment by AskAlexSharov** [comment]
Must be fine.

**Comment by GBBx** [comment]
Hi @AskAlexSharov , so you mean it should work with just the path, not `/dev/...`?

**Comment by AskAlexSharov** [comment]
I think this is not error of MDBX, but error of Linux/FileSystem/Docker. 
Probably something wrong with mount options.
You can google "block device required linux" or "block device required docker"

**Comment by GBBx** [comment]
Interesting. It really does work outside podman. I'll need to investigate further.

Thanks for your help.

**Comment by GBBx** [comment]
Alright, I found the solution. I add it here for others as a reference.

Podman can use vfs or overlayfs for storage.
Overlayfs seems to cause the issue.
# Check current driver:
```
podman info | grep graph
  graphDriverName: overlay
```
# Uninstall fuse-overlayfs
# Edit /etc/containers/storage.conf:
```
# Default Storage Driver, Must be set for proper operation.
driver = "vfs"
```
# Delete temporary data:
```
rm -rf ~/.local/share/containers/*
```
# Now it should work. No need to use `--mount`.
You can double-check the graphql driver:
```
podman info | grep graph
  graphDriverName: vfs
```

There may be some similar differences in docker as well.
