### ISSUE TITLE
rpcdaemon always return block 0x0

### ISSUE THREAD

**Issue by baruchrb** [ledgerwatch/erigon#2791]
#### System information

Erigon version: erigon version 2021.10.1-alpha

OS & Version: Linux alpine3.14 / Linux Ubuntu 20.04

Commit hash : ef80fd54b1c6c82aae92f5fa24cbd381e8577b50

#### Expected behaviour
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8845

{
    "jsonrpc": "2.0",
    "id": 1,
    "result":" 0xa5b9ba"
}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8845/health

{"check_block":"HEALTHY","healthcheck_query":"HEALTHY","min_peer_count":"HEALTHY"}
#### Actual behaviour
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8845

{
    "jsonrpc": "2.0",
    "id": 1,
    "result":" 0x0"
}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8845/health

{"check_block":"DISABLED","healthcheck_query":"HEALTHY","min_peer_count":"DISABLED"}

#### Steps to reproduce the behaviour

```
erigon --chain ropsten --datadir=/home/ubuntu/.local/share/erigon --private.api.addr=localhost:9090
rpcdaemon --datadir=/home/ubuntu/.local/share/erigon --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --http.port=8845
```

#### Backtrace

No backtrace as there's no crash.

**Comment by AskAlexSharov** [comment]
closing for now, feel free to reopen if need
