### ISSUE TITLE
Provide a somewhat stable version

### ISSUE THREAD

**Issue by paulmillr** [ledgerwatch/erigon#2795]
- https://www.ethernodes.org says 7% of the network is using Erigon
- The [wiki page for transition](https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta) is unclear if the goals are achieved already. Perhaps you could create a GitHub Project, or use Milestones, or something, to signify what's left to be done for Beta?
- It's very tiring to have Erigon breaking and corrupting data release after release

It would be great if some focus was poured on getting a stable release out, a release that won't corrupt data & won't need "updates" (besides security) for at least 6 months.

**Comment by mandrigin** [comment]
here is the document about the Beta program: https://github.com/ledgerwatch/erigon/wiki/Erigon-Beta-1-announcement

closing this issue for now.
