### ISSUE TITLE
no peers for Kovan

### ISSUE THREAD

**Issue by gabronick** [ledgerwatch/erigon#2808]
#### System information

Erigon version:  erigon version 2021.10.2-alpha

OS & Version: Linux 4.14.248-189.473.amzn2.x86_64

Commit hash : 

#### Expected behaviour

download kovan headers and blocks

#### Actual behaviour

INFO[10-10|06:06:44.222] Initialising Ethereum protocol           network=42
INFO[10-10|06:06:44.222] Effective                                prune="--prune="
WARN[10-10|06:06:44.222] Preverified hashes not found for         chain=kovan
INFO[10-10|06:06:44.225] Starting private RPC server              on=localhost:9090
INFO[10-10|06:06:44.226] Loaded local transaction journal         transactions=0 dropped=0
INFO[10-10|06:06:44.226] Regenerated local transaction journal    transactions=0 accounts=0
INFO[10-10|06:06:44.226] transaction pool started
INFO[10-10|06:06:44.227] [1/18 Headers] Waiting for headers...    from=0
INFO[10-10|06:06:44.247] Started P2P networking                   version=66 self=enode://d24be40a683adafd6ba3b68f2ad252a851a9de77b1fd1ffeb5ef3ffe5b414a9f2186af5825bd56e659a42812fe8f6560277d17f9ede28b5033f5a4d0074b497e@127.0.0.1:30303 name=erigon/v2021.10.2-alpha-8b4d31f6/linux-amd64/go1.17.2
INFO[10-10|06:06:44.308] Started P2P networking                   version=65 self=enode://d24be40a683adafd6ba3b68f2ad252a851a9de77b1fd1ffeb5ef3ffe5b414a9f2186af5825bd56e659a42812fe8f6560277d17f9ede28b5033f5a4d0074b497e@127.0.0.1:30304 name=erigon/v2021.10.2-alpha-8b4d31f6/linux-amd64/go1.17.2
INFO[10-10|06:06:45.866] event subscription channel established with the RPC daemon
INFO[10-10|06:07:14.227] [1/18 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="10.33 MiB" sys="28.02 MiB"
 Waiting for headersINFO[10-10|06:07:44.227] [1/18 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="8.89 MiB" sys="28.02 MiB"
INFO[10-10|06:08:14.227] [1/18 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="9.79 MiB" sys="28.02 MiB"

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
@e-danko FYI: Sokol has hardcoded forkID https://github.com/ledgerwatch/erigon/blob/5069558752ab951ed79148beb207577d7cbb3c96/core/forkid/forkid.go#L206 (i don’t remember why). Maybe ForkID of Kovan is also not compatible now.

**Comment by tiagocmachado** [comment]
Any solution for this @AskAlexSharov ? should we use some older version to run a kovan node?

**Comment by AskAlexSharov** [comment]
@enriavil1 working on AuRa now

**Comment by netquery** [comment]
Hey @AskAlexSharov , how's it going:) we need to run a kovan node. Thanks!

**Comment by AskAlexSharov** [comment]
@netquery  Hi, sorry. But looks like there will be no AuRa support in Erigon - because of changes in roadmap and priorities. Thank you.
