### ISSUE TITLE
Data collection requests

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#285]
Vitalik Buterin, [11 Dec 2019 at 16:14:02]:
So to summarize what I would love to have personally:

* Average # of unique accounts accessed per block (so if block 1841245 and 1841246 both access 0xabcde that's 1 account access for both blocks, but if 1841245 accesses 0xabcde twice that's only 1 account access)
* Average # of unique storage slots accessed per block
* Average # of code bytes read
* Average # of code bytes read *within some range of blocks*, eg. for different powers of 10

The first three to calculate witness sizes, the last one to estimate how much savings we would get from some form of code caching

This is also highly relevant to eth2 btw

**Comment by mandrigin** [comment]
@AlexeyAkhunov if you want, you can reopen it, but it seems very old and outdated now
