### ISSUE TITLE
trace_block error "first run for txIndex 69 error: fee cap less than block base fee: address 0xEaBD126f17135A724a188E9A60F5927Acb1079F3, gasFeeCap: 1000000000 baseFee: 1038466509"

### ISSUE THREAD

**Issue by twilightrus** [ledgerwatch/erigon#2872]
#### System information

Erigon version: 2021.10.03-alpha
OS & Version: Ubuntu
Network: Rinkeby

When I send JSON-RPC:
`
{"id": null, "method": "trace_block", "params": ["0x9171ac"]}
`

I got a response:
`
{
    "jsonrpc": "2.0",
    "id": null,
    "error": {
        "code": -32000,
        "message": "first run for txIndex 69 error: fee cap less than block base fee: address 0xEaBD126f17135A724a188E9A60F5927Acb1079F3, gasFeeCap: 1000000000 baseFee: 1038466509"
    }
}
`

**Comment by twilightrus** [comment]
> —chain rinkeby

 ./integration state_stages --datadir=/mnt/erigon/erigon/rinkeby/ --unwind=2000 --integrity.fast=false —chain rinkeby
INFO [10-29|11:40:50.071] database closed (MDBX)                   mdbx=chaindata exclusive=false
panic: database contains incompatible genesis (have 6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177, new d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3)

goroutine 1 [running]:
github.com/ledgerwatch/erigon/cmd/integration/commands.newSync(0x1f55e90, 0xc00007f280, 0x1f5e1c8, 0xc000116300, 0xc0005e7be0, 0x0, 0x4a76a5, 0xc000000180, 0x200000003, 0xc000000180, ...)
        github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:792 +0x1994
github.com/ledgerwatch/erigon/cmd/integration/commands.syncBySmallSteps(0x1f5e1c8, 0xc000116300, 0x0, 0x0, 0x0, 0x0, 0x2b4dbe0, 0x0, 0x0, 0x2b4dbe0, ...)
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:142 +0x85
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func24(0x28bac60, 0xc000098af0, 0x2, 0x5, 0x0, 0x0)
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:62 +0x225
github.com/spf13/cobra.(*Command).execute(0x28bac60, 0xc000098aa0, 0x5, 0x5, 0x28bac60, 0xc000098aa0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x28bc2e0, 0xc00007f0c0, 0xc0003dd060, 0x18)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
main.main()
        github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x129

**Comment by AskAlexSharov** [comment]
I don’t know. You open database of another chain. Maybe wrong folder somewhere

**Comment by AskAlexSharov** [comment]
Probably related to 2 “erigon” words in the path

**Comment by twilightrus** [comment]
Fixed by upgrading to 2021.10.05-alpha
