### ISSUE TITLE
Please support parity_getBlockReceipts

### ISSUE THREAD

**Issue by YordanPavlov** [ledgerwatch/erigon#2886]
Please consider implementing the API supported by Parity:
[parity_getblockreceipts](https://openethereum.github.io/JSONRPC-parity-module#parity_getblockreceipts)

In our use case we are trying to monitor all gas being used for each and every transaction. Doing so using the existing `getTransactionReceipt` is impractical as it would require a separate call for each transaction.

Alternatively if you can recommend another way to efficiently monitor gas used, you are very welcome.

Thank you.

**Comment by YordanPavlov** [comment]
> You want to use `eth_getTransactionReceipt` which returns the `gasUsed` for the entire transaction. If you want the `gasUsed` for each individual trace you have to use one of the `trace_` routines. `eth_getLogs` only returns events which do not include `gasUsed`.

Thanks for your feedback @tjayrush! As mentioned in my first post I am looking for ways to fetch the receipts for an entire block at once. I know that the way to do it per-transaction is using `getTransactionReceipt`, however this would be impractical  for my use case. I want to monitor all gas being spent as the blockchain progress. Having a bulk request instead per-transaction is what the Parity API solves.

**Comment by tjayrush** [comment]
Oh. I see. Have you looked at `trace_block`? It's actually really fast and, while it doesn't deliver 'receipts' per se, it deliver Traces which contain two subfields call TraceAction and TraceResult. If you look at the fields of these two object the first correspond pretty well to a transaction and the later (TraceResult) corresponds to the Reciept.

There's probably better links to show you, but these are handy:

This describes the trace data: https://trueblocks.io/data-model/chaindata/#trace

This describes the TraceAction data: https://trueblocks.io/data-model/chaindata/#traceaction

And this describes the TraceResult data: https://trueblocks.io/data-model/chaindata/#traceresult

The routine `trace_block` returns an array of all the traces that happened in a given block.

You have to add up the `gasUsed` and there's a weird results where the adding doesn't equal the same `gasUsed` as is found in the transaction's receipt, but that detail is something you'll have to work through. (I forget how to calculate the result so all the gas adds up.)

**Comment by YordanPavlov** [comment]
Thank you for the information @tjayrush ! I would look into those leads and report back.

**Comment by YordanPavlov** [comment]
I finally had the time to play a bit more with the trace API @tjayrush, sorry for the long delay. It seems like one can indeed recover the gas used from the trace. However what the actual steps are I am not sure, so from my experiments with the block 1000000 it looks like:
1. Each `call` trace is 21000 gas + whatever the value of the field:
```
result": {
   "gasUsed": "0x5a4",
   "output": "0x"
}
```
2. If you have two traces for a transaction you need to consider only the 'upper' most one. That is the one having a non 0 `subtraces` count. That is because this upper most call would include the gasUsed of the inner ones.

However I suspect things are much more complicated and I am not sure how feasible it is for me to try and sum everything this way. For example I guess I should also consider if the output is not 0 and such things. With all this considered, my original proposal for an API extension stands. I think the node itself must have the logic implemented as it supports the getTransactionReceipt where all this calculations must be taking place.

**Comment by YordanPavlov** [comment]
Some update on this issue, actually it turned out that the API call I am after is supported! It is called:
`eth_getBlockReceipts`
strangely I did not find it when I went over the docs. I guess this request can be closed.

**Comment by noam-alchemy** [comment]
BTW - if anyone else needs this, it is now supported with `alchemy_getTransactionReceipts` :)
https://docs.alchemy.com/alchemy/enhanced-apis/transaction-receipts-api#alchemy_gettransactionreceipts

**Comment by AskAlexSharov** [comment]
great
