### ISSUE TITLE
MDBX_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by tholcman** [ledgerwatch/erigon#2888]
I have found similar issues here but those are resolved by previous releases.

#### System information

Erigon version: `./erigon --version`

> erigon version 2021.10.3-alpha

OS & Version: Windows/Linux/OSX

> docker, 20.04.1-Ubuntu

#### Expected behaviour

Erigon will run and sync smoothly.

#### Actual behaviour

It fills 2TB on disk and keeps trying to sync, it is writing:

On mainnet 1 node out of 4
```
[INFO] [10-29|07:15:10.785] [4/18 Bodies] Processing bodies...       from=13454019 to=13493233
[EROR] [10-29|07:15:43.848] Staged Sync                              error="[4/18 Bodies] writing block body: failed to WriteRawTransactions: bucket: BlockTransaction, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached"
[INFO] [10-29|07:15:44.380] [4/18 Bodies] Processing bodies...       from=13454019 to=13493233
[EROR] [10-29|07:16:17.599] Staged Sync                              error="[4/18 Bodies] writing block body: failed to WriteRawTransactions: bucket: BlockTransaction, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached"
```

We have also seen this behavior on 2 nodes out of 4 on rinkeby (on different blocks). The other nodes has ~275GB of data, but the problematic one growth to 2TB and stopped syncing.

#### Steps to reproduce the behaviour

Don't know, some nodes are running ok, some are not.

**Comment by AskAlexSharov** [comment]
1 minute - is fine.

You can try:
```
make db-tools
mv <datadir>/chaindata  <datadir>/chaindata_backup
./build/bin/mdbx_copy -c <datadir>/chaindata_backup <datadir>/chaindata
# then chaindata folder must get small
```

**Comment by tholcman** [comment]
we are using docker image based on `thorax/erigon:v2021.10.03` which probably doesn't contain `mdbx_copy` executable
```
$ ls -al /usr/local/bin/
...
-rwxr-xr-x    1 root     root      53369184 Oct 14 12:09 erigon
-rwxr-xr-x    1 root     root      51893688 Oct 14 12:09 integration
-rwxr-xr-x    1 root     root      33848832 Oct 14 12:09 rpcdaemon
-rwxr-xr-x    1 root     root      32667088 Oct 14 12:10 sentry
```

I guess it might be the `integration`

```
$ integration --help
long and heavy integration tests for Erigon

Usage:
  integration [command]

Available Commands:
  ...
  f_to_mdbx         copy data from '--chaindata' to '--chaindata.to'
  ...
  mdbx_to_mdbx      copy data from '--chaindata' to '--chaindata.to'
  ...
```

Unfortunately, we already had to destroy the environments (and start them from snapshot), but I guess this might be a workaround if it will happen next time.

**Comment by AndreaLanfranchi** [comment]
> which probably doesn't contain `mdbx_copy` executable

`mdbx_copy` executable is obtained by `make db-tools` (db tools are not built by default)

**Comment by anisoptera** [comment]
I hit this issue myself, with a 1.1T data dir. I'll try the mentioned mdbx_copy.

**Comment by AskAlexSharov** [comment]
> I hit this issue myself, with a 1.1T data dir. I'll try the mentioned mdbx_copy.

@anisoptera , you can get it only with 2Tb datadir. Likely you have another problem. For example with "nodes" folder in datadir. Show `du -h <datadir>/*`

**Comment by AskAlexSharov** [comment]
also show logs with error

**Comment by 0xKrishna** [comment]
I am working with a clique based consensus, I got this
```WARN[11-02|19:26:33.541] Verification failed for header           hash=0x7d820636bcf6e92d0572e12b6620cce25a482928155b30bc86636bfc6ce38d44 height=8317953 error="table: CliqueSeparate, err: mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached"```

**Comment by anisoptera** [comment]
> > I hit this issue myself, with a 1.1T data dir. I'll try the mentioned mdbx_copy.
> 
> @anisoptera , you can get it only with 2Tb datadir. Likely you have another problem. For example with "nodes" folder in datadir. Show `du -h <datadir>/*`

```
512     /eth1-data/erigon/LOCK
430G    /eth1-data/erigon/chaindata
1.1T    /eth1-data/erigon/chaindata-backup
8.5K    /eth1-data/erigon/etl-temp
512     /eth1-data/erigon/nodekey
6.5M    /eth1-data/erigon/nodes
512     /eth1-data/erigon/transactions.rlp
16M     /eth1-data/erigon/txpool
1.5T    total
```

Logs (this just loops forever):
```
Nov 01 19:34:19 eth1 erigon[25185]: [INFO] [11-01|19:34:19.323] [11/18 IntermediateHashes] Generating intermediate hashes from=13526617 to=13532435
Nov 01 19:35:08 eth1 erigon[25185]: [INFO] [11-01|19:35:08.558] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf3581758468 alloc="1.6 GiB" sys="3.0 GiB"
Nov 01 19:35:12 eth1 erigon[25185]: [INFO] [11-01|19:35:12.079] [p2p] GoodPeers                          eth66=33 eth65=33
Nov 01 19:35:14 eth1 erigon[25185]: [INFO] [11-01|19:35:14.016] [11/18 IntermediateHashes] Calculating Merkle root current key=ab14d688...
Nov 01 19:35:21 eth1 erigon[25185]: [INFO] [11-01|19:35:21.467] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf2010371405 alloc="1.2 GiB" sys="3.0 GiB"
Nov 01 19:35:31 eth1 erigon[25185]: [INFO] [11-01|19:35:31.325] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf1404404080 alloc="1.5 GiB" sys="3.0 GiB"
Nov 01 19:35:37 eth1 erigon[25185]: [INFO] [11-01|19:35:37.425] [11/18 IntermediateHashes] etl: temp files removed total size="303.8 MB"
Nov 01 19:35:37 eth1 erigon[25185]: [INFO] [11-01|19:35:37.822] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf3506344563 alloc="690.5 MiB" sys="3.0 GiB"
Nov 01 19:35:45 eth1 erigon[25185]: [INFO] [11-01|19:35:45.716] [11/18 IntermediateHashes] etl: temp files removed total size="384.3 MB"
Nov 01 19:35:46 eth1 erigon[25185]: [EROR] [11-01|19:35:46.082] Staged Sync                              error="[11/18 IntermediateHashes] mdbx_txn_commit_ex: MDBX_MAP_FULL: Environment mapsize limit reached"
Nov 01 19:35:46 eth1 erigon[25185]: [INFO] [11-01|19:35:46.808] [11/18 IntermediateHashes] Generating intermediate hashes from=13526617 to=13532435
Nov 01 19:36:36 eth1 erigon[25185]: [INFO] [11-01|19:36:36.194] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf2072651014 alloc="1.3 GiB" sys="3.0 GiB"
Nov 01 19:36:41 eth1 erigon[25185]: [INFO] [11-01|19:36:41.365] [11/18 IntermediateHashes] Calculating Merkle root current key=ab14d688...
Nov 01 19:36:48 eth1 erigon[25185]: [INFO] [11-01|19:36:48.705] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf1061237008 alloc="1.8 GiB" sys="3.0 GiB"
Nov 01 19:36:57 eth1 erigon[25185]: [INFO] [11-01|19:36:57.660] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf4122448757 alloc="2.1 GiB" sys="3.0 GiB"
Nov 01 19:37:03 eth1 erigon[25185]: [INFO] [11-01|19:37:03.995] [11/18 IntermediateHashes] etl: temp files removed total size="303.8 MB"
Nov 01 19:37:04 eth1 erigon[25185]: [INFO] [11-01|19:37:04.398] Flushed buffer file                      name=/eth1-data/erigon/etl-temp/tg-sync-sortable-buf411178154 alloc="861.0 MiB" sys="3.0 GiB"
Nov 01 19:37:12 eth1 erigon[25185]: [INFO] [11-01|19:37:12.080] [p2p] GoodPeers                          eth66=33 eth65=33
Nov 01 19:37:12 eth1 erigon[25185]: [INFO] [11-01|19:37:12.567] [11/18 IntermediateHashes] etl: temp files removed total size="384.3 MB"
Nov 01 19:37:12 eth1 erigon[25185]: [EROR] [11-01|19:37:12.934] Staged Sync                              error="[11/18 IntermediateHashes] mdbx_txn_commit_ex: MDBX_MAP_FULL: Environment mapsize limit reached"
Nov 01 19:37:13 eth1 erigon[25185]: [INFO] [11-01|19:37:13.493] [11/18 IntermediateHashes] Generating intermediate hashes from=13526617 to=13532435
Nov 01 19:37:19 eth1 systemd[1]: Stopping Erigon DB...
```

This is on latest master, on an HDD RAID10 with 5 mirrors on it. I was able to sync mainnet on this setup and it synced fully and was keeping up for days before it got stuck in this state.

**Comment by AskAlexSharov** [comment]
"I accidentally synced with pruning off originally, then added --prune htc" - Erigon must not allow this. If it does - it's bug.

**Comment by AskAlexSharov** [comment]
here is the fix to prohibit change prune mode: https://github.com/ledgerwatch/erigon/pull/2907

**Comment by anisoptera** [comment]
I see. I guess I will just sync from scratch then. Thanks for the quick fix to prevent anyone else getting stuck like this :)

**Comment by AskAlexSharov** [comment]
@0xKrishna `du -h <datadir>/*`

**Comment by AskAlexSharov** [comment]
We got some output of `mdbx_stat -a` which showed us that something is wrong with "EthTransactions" table: 
https://gist.github.com/LefterisJP/1c9ef4ecb451e1f4c9f93b6e6a3681aa#file-mdbx_stat-log-L45
likely we have bug as BodiesDownload stage, we will investigate.

**Comment by KaiRo-at** [comment]
FWIW, I also ran into this and as the docker container doesn't include that mdbx_copy tool, all I could do is to re-sync from scratch.

**Comment by AskAlexSharov** [comment]
In this case copy will not help. Only https://github.com/ledgerwatch/erigon/pull/2941 can help, but it’s not released yet.

**Comment by AskAlexSharov** [comment]
Hi. I created for you branch `mdbx_revert_augument_limit_stable`.
It's `stable` (beta) + 2 fixes about db size growth: https://github.com/ledgerwatch/erigon/pull/2949
https://github.com/ledgerwatch/erigon/pull/2956
But likely you nee re-sync.

**Comment by KaiRo-at** [comment]
> Hi. I created for you branch `mdbx_revert_augument_limit_stable`. It's `stable` (beta) + 2 fixes about db size growth: #2949 #2956 But likely you nee re-sync.

Is there a docker container with this? I just re-synced with the last release and ran into the same "mapsize limit" issue again after a few days of being synced...

**Comment by AskAlexSharov** [comment]
https://hub.docker.com/r/thorax/erigon/tags/stable

**Comment by AskAlexSharov** [comment]
FYI: there is also `v2021.11.03` tag available now

**Comment by KaiRo-at** [comment]
Oh, I thought you said some branch, if it's on the main release, that's great. Updated now and triggered a full re-sync again.

**Comment by 0xKrishna** [comment]
How to enable/disable the receipt calculation?
I can see my node going into `mismatched receipt headers for block` inside `ExecuteBlockEphemerally`
as the receipt doesn't have the logs and generates a different hash as compared to the block header.

**Comment by AskAlexSharov** [comment]
> How to enable/disable the receipt calculation?
> I can see my node going into `mismatched receipt headers for block` inside `ExecuteBlockEphemerally`
> as the receipt doesn't have the logs and generates a different hash as compared to the block header.

can’t - because it’s part of consensus (receipts hash is in header). Give us more info.

**Comment by 0xKrishna** [comment]
Here, It's configurable
https://github.com/ledgerwatch/erigon/blob/devel/core/blockchain.go#L154
That `vmConfig.NoReceipts`

**Comment by 0xKrishna** [comment]
Problem is that in my reciepts I am not getting `Logs` and hence the calculated hash is coming out to be different then `block.Header().ReceiptHash`

**Comment by AskAlexSharov** [comment]
> Here, It's configurable
> https://github.com/ledgerwatch/erigon/blob/devel/core/blockchain.go#L154
> That `vmConfig.NoReceipts`

In source code everything is configurable :-) I mean - I don't know what vector of attack can open by disabling receipts hash check - during sync.

**Comment by mtake** [comment]
> Oh, I thought you said some branch, if it's on the main release, that's great. Updated now and triggered a full re-sync again.

Hi @KaiRo-at , did you confirm the `v2021.11.03` tag solved the issue? I have the same `MDBX_MAP_FULL: Environment mapsize limit reached` issue with the `v2021.11.02` tag when the archive node was fully re-synced and looking for a solution. Thanks.

**Comment by KaiRo-at** [comment]
I can't say if it's fixed forever, but after a re-sync with `v2021.11.03` I did not run into the problem again so far.

**Comment by mtake** [comment]
@KaiRo-at Thank you. I just started re-sync with `v2021.11.03` and waiting for completion.

**Comment by bsamuels453** [comment]
I experienced this issue on a fresh v2021.11.03 sync

**Comment by cflb** [comment]
I'm suffering with the problem below:
`error="[3/15 Bodies] mdbx_txn_commit_ex: MDBX_MAP_FULL: Environment mapsize limit reached"`
I was a little confused about item 5 of the changelog of the last version released (v2022.01.01).

`5. MDBX version update - fixing the slow commit related to reclaimable space`

https://github.com/ledgerwatch/erigon/releases/tag/v2022.01.01
Does it solve this problem?

**Comment by AskAlexSharov** [comment]
@cflb it depends on reason why you get it. Need know your erigon version, “mdbx_stat -ef “ output, etc… 
Closing this issue as fixed, feel free to create new one if need.

**Comment by skolem-dan** [comment]
Apologies for resurrecting an old issue, but this is currently the top (and sometimes _only_) result that comes up on Google when searching for "MDBX_MAP_FULL: Environment mapsize limit reached".

Anyone running a Polygon node using Erigon is going to run into this error after updating due to #7478, and Polygon's own docs/release notes don't include the highlight from `v2.45.0` about the need to manually revert this new limitation. That's something they'll need to address in their own docs, but until then, for anyone landing on this page in the coming days/weeks, here's the new flag you need to add when starting erigon:
```
--db.size.limit 7697000000000
```
