### ISSUE TITLE
https://twitter.com/mnooa101/status/1421534153376423936?t=siw7EYWf6MquxGpwAcHB6A&s=19

### ISSUE THREAD

**Issue by mnooa101** [ledgerwatch/erigon#2894]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).

**Comment by AskAlexSharov** [comment]
Closing - looks as scam
