### ISSUE TITLE
RPC: add websocket method eth_subscribe logs

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#2919]
Implementation details: please re-use logic of eth_getLogs - there is implemented all filters support. 
Can test websocket API by `wscat -c ws://localhost:8545`

https://geth.ethereum.org/docs/rpc/pubsub

Returns logs that are included in new imported blocks and match the given filter criteria.

In case of a chain reorganization previous sent logs that are on the old chain will be resend with the removed property set to true. Logs from transactions that ended up in the new chain are emitted. Therefore a subscription can emit logs for the same transaction multiple times.

Parameters:

object with the following (optional) fields
address, either an address or an array of addresses. Only logs that are created from these addresses are returned (optional)
topics, only logs which match the specified topics (optional)

Example: 
```
>> {"id": 1, "method": "eth_subscribe", "params": ["logs", {"address": "0x8320fe7702b96808f7bbc0d4a888ed1468216cfd", "topics": ["0xd78a0cb8bb633d06981248b816e7bd33c2a35a6089241d099fa519e361cab902"]}]}
<< {"jsonrpc":"2.0","id":2,"result":"0x4a8a4c0517381924f9838102c5a4dcb7"}

<< {"jsonrpc":"2.0","method":"eth_subscription","params": {"subscription":"0x4a8a4c0517381924f9838102c5a4dcb7","result":{"address":"0x8320fe7702b96808f7bbc0d4a888ed1468216cfd","blockHash":"0x61cdb2a09ab99abf791d474f20c2ea89bf8de2923a2d42bb49944c8c993cbf04","blockNumber":"0x29e87","data":"0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000003","logIndex":"0x0","topics":["0xd78a0cb8bb633d06981248b816e7bd33c2a35a6089241d099fa519e361cab902"],"transactionHash":"0xe044554a0a55067caafd07f8020ab9f2af60bdfe337e395ecd84b4877a3d1ab4","transactionIndex":"0x0"}}}
```

**Comment by yorickdowne** [comment]
This will enable Erigon to be used with Blox Staking's SSV/DVT (Secret Shared Validator / Distributed Validator Technology) implementation. They currently use `eth_subscribe logs` to get live events from their registry contract.

**Comment by AskAlexSharov** [comment]
done
