### ISSUE TITLE
Erigon docker container is restarting when almost synced

### ISSUE THREAD

**Issue by halimaster** [ledgerwatch/erigon#2932]
I am having an issue where erigon is restarting everytime it gets up around block 12000000. I am using a docker compose file to deploy erigon and have only changed the data directory. here is what my docker-compose file looks like:

version: '2.1'

services:

  erigon:
    container_name: eri1
    image: pocketfoundation/erigon:2021.07.05-alpha
    user: 1000:1000
    restart: unless-stopped
    cpus: '14'
    mem_limit: '30G'
    command: erigon --metrics --metrics.addr="0.0.0.0" --metrics.port="6060" --private.api.addr="0.0.0.0:9090" --pprof --pprof.addr="0.0.0.0" --pprof.port="6061"
    volumes:
      - /home/erigon/.local/share/erigon:/home/erigon/.local/share/erigon
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
    networks:
      - default

  rpcdaemon:
    container_name: eri-rpc1
    image: pocketfoundation/erigon:2021.07.05-alpha
    restart: unless-stopped
    cpus: '2'
    mem_limit: '2G'
    command: rpcdaemon --private.api.addr="erigon:9090" --http.addr="0.0.0.0" --http.vhosts="*" --http.corsdomain="*" --http.api="eth,debug,net,trace"
    ports:
      - 8545:8545
    networks:
      - default

networks:
  default:
    external:
      name: nodes

This is what my docker logs look like when it restarts itself:

INFO [11-08|03:26:43.389] Peer 67e0712e786ef7734d63191699a1de9274cf7247ee9c9242ac786c546c5e0388 [Geth/v1.10.8-stable-26675454/linux-amd64/go1.16.4] stable proto=66
INFO [11-08|03:26:49.021] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics
INFO [11-08|03:26:49.021] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
INFO [11-08|03:26:49.021] Build info                               git_branch=HEAD git_tag=v2021.07.05 git_commit=3452413fe11b5325b4122652534bc51e7f64e108
INFO [11-08|03:26:49.021] Starting Erigon on Ethereum mainnet... 
INFO [11-08|03:26:49.024] Maximum peer count                       ETH=100 total=100
INFO [11-08|03:26:49.024] Set global gas cap                       cap=50000000
INFO [11-08|03:26:49.090] Opening Database                         label=chaindata
mdbx_setup_dxb:14929 filesize mismatch (expect 12884901888b/3145728p, have 309237645312b/75497472p)
INFO [11-08|03:26:49.224] Re-Opening DB in exclusive mode to apply migrations 
INFO [11-08|03:26:49.225] database closed (MDBX) 
INFO [11-08|03:26:49.231] Apply migration                          name=rebuild_call_trace_index
WARN [11-08|03:26:49.231] Nothing to rebuild, CallTraceSet table is empty 
INFO [11-08|03:26:49.231] Applied migration                        name=rebuild_call_trace_index
INFO [11-08|03:26:49.232] Updated DB schema to                     version=3.0.0
INFO [11-08|03:26:49.232] database closed (MDBX) 
INFO [11-08|03:26:49.461] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}"
INFO [11-08|03:26:49.462] Disk storage enabled for ethash DAGs     dir=/home/erigon/.local/share/erigon/erigon/ethash-dags count=2
INFO [11-08|03:26:49.462] Initialising Ethereum protocol           network=1
INFO [11-08|03:26:49.462] Effective                                prune="history=no,receipt=no,txindex=no,calltrace=no,experiments.tevm=disabled"
INFO [11-08|03:26:49.462] Starting private RPC server              on=0.0.0.0:9090
INFO [11-08|03:26:49.696] event subscription channel established with the RPC daemon 
INFO [11-08|03:26:51.001] [1/18 Headers] Waiting for headers...    from=13571983
INFO [11-08|03:26:51.033] Started P2P networking                   version=66    self=enode://6814b75dac486341a06b2581efa1e6929a94f7253f3fa07f584515ce7012f4e9a6d06f81156f73c1ef47ce0255b18adfcbac02b8d46635c83f253a57672cee9d@127.0.0.1:30303 name=erigon/v2021.08.1-alpha-3452413f/linux-amd64/go1.16.5
INFO [11-08|03:26:51.047] Started P2P networking                   version=65    self=enode://6814b75dac486341a06b2581efa1e6929a94f7253f3fa07f584515ce7012f4e9a6d06f81156f73c1ef47ce0255b18adfcbac02b8d46635c83f253a57672cee9d@127.0.0.1:30304 name=erigon/v2021.08.1-alpha-3452413f/linux-amd64/go1.16.5
INFO [11-08|03:27:21.001] [1/18 Headers] Wrote block headers       number=13571983 blk/second=0.000 alloc=85.14MiB sys=217.98MiB

What can I do to fix this?

**Comment by AskAlexSharov** [comment]
Hi. This logs are “after restart”, we need logs “before restart”. 
Or maybe Docker can provide last restart reason.

**Comment by halimaster** [comment]
Hi Alex, I searched those logs and cant find any sort of error. It seems to
be just stopping itself and restarting for no apparent reason. Did you see
my data directory in the docker-compose file? Does that look right to you?

Thanks

**Comment by AskAlexSharov** [comment]
1. You can take a look OOM killer log on your host machine
2. Your docker-compose file looks fine

**Comment by halimaster** [comment]
>     1. You can take a look OOM killer log on your host machine
> 
>     2. Your docker-compose file looks fine

I see that I am running out of memory. I have plenty of memory and nvmes so I dont understand why that would happen. Is there something you might recommend to prevent that from happening? I suspect it is not writing the information quickly enough even though I have nvmes

/var/log/kern.log:Nov  7 01:45:10 poktnodes-M12SWA-TF kernel: [16588.971228] Memory cgroup out of memory: Killed process 13466 (erigon) total-vm:2180818704kB, anon-rss:30189304kB, file-rss:0kB, shmem-rss:0kB, UID:100000 pgtables:83428kB oom_score_adj:0
/var/log/kern.log:Nov  7 04:53:07 poktnodes-M12SWA-TF kernel: [31465.333130] Memory cgroup out of memory: Killed process 17283 (erigon) total-vm:2181313092kB, anon-rss:30701544kB, file-rss:1008kB, shmem-rss:0kB, UID:100000 pgtables:86148kB oom_score_adj:0
/var/log/kern.log:Nov  7 09:11:30 poktnodes-M12SWA-TF kernel: [46968.308256] Memory cgroup out of memory: Killed process 19679 (erigon) total-vm:2181367320kB, anon-rss:30654820kB, file-rss:0kB, shmem-rss:0kB, UID:100000 pgtables:86024kB oom_score_adj:0
/var/log/kern.log:Nov  7 19:26:44 poktnodes-M12SWA-TF kernel: [83881.961055] Memory cgroup out of memory: Killed process 30605 (erigon) total-vm:2181436384kB, anon-rss:30641036kB, file-rss:44984kB, shmem-rss:0kB, UID:100000 pgtables:87440kB oom_score_adj:0

**Comment by AskAlexSharov** [comment]
- " I have plenty of memory (256gb) "  - you also has docker-compose limit: `mem_limit: '30G'`
- usually erigon using not much RAM - maybe we have some bug...
- We print memory usage to logs: `alloc=3.84GiB    sys=7.46GiB` - `sys` it's historical maximum. 8Gb it's quite a lot, but far from 30Gb. So, don't know. 
- but your OOM killer says we used 30Gb `anon-rss:30654820kB`

**Comment by nextfullstorm** [comment]
Piggybacking. I have similar issue, but without using docker. I'm running erigon native, no vm, no cloud storage, just 20 core xeon, 32gb ram, 2tb sata ssd, Ubuntu server 18.04. I've tried several last versions. I'm trying to sync ethereum mainnet for about a month already, several attempts and all of them ends with OOM killer. And after each OOM I need to start from wiping datadir, cause db always corrupts ("MDBX_PAGE_NOTFOUND: Requested page not found"). And each attempt takes from several days to week to complete.

erigon log:
`
INFO[11-15|18:29:13.609] [5/15 Execution] Executed blocks         number=8694287 blk/s=0.013 tx/s=0.318 Mgas/s=0.011 batch="394.66 MiB" alloc="10.97 GiB" sys="16.35 GiB"
INFO[11-15|18:29:21.714] [p2p] GoodPeers                          eth66=1
INFO[11-15|18:29:22.134] [txpool] stat                            block=8650029 pending=10000 baseFee=6583 queued=10000 alloc_mb=11228 sys_mb=16744
INFO[11-15|18:30:27.628] [txpool] stat                            block=8650029 pending=10000 baseFee=6583 queued=10000 alloc_mb=11229 sys_mb=16744
INFO[11-15|18:31:22.196] [p2p] GoodPeers                          eth66=1
INFO[11-15|18:31:23.120] [txpool] stat                            block=8650029 pending=10000 baseFee=6583 queued=10000 alloc_mb=11228 sys_mb=16744
INFO[11-15|18:32:21.794] [txpool] stat                            block=8650029 pending=10000 baseFee=6583 queued=10000 alloc_mb=11228 sys_mb=16744
INFO[11-15|18:32:24.473] [5/15 Execution] Executed blocks         number=8694288 blk/s=0.005 tx/s=0.079 Mgas/s=0.003 batch="394.66 MiB" alloc="10.97 GiB" sys="16.35 GiB"
`

/var/log/kern.log
`
Nov 15 18:50:41 mm-root kernel: [277829.797148] Out of memory: Kill process 17112 (erigon) score 951 or sacrifice child
Nov 15 18:50:41 mm-root kernel: [277829.797259] Killed process 17112 (erigon) total-vm:4335538220kB, anon-rss:29830352kB, file-rss:0kB, shmem-rss:0kB
Nov 15 18:50:41 mm-root kernel: [277831.589138] oom_reaper: reaped process 17112 (erigon), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
`

I'm running erigon without additional options: `build/bin/erigon --datadir /mnt/2tb/erigon`

**Comment by AskAlexSharov** [comment]
@nextfullstorm if you have error - create github issue. With information enough for us to debug. Erigon has 4 databases - when you just show us part of error `MDBX_PAGE_NOTFOUND` - we can't identify to which db it's related. 

Also OOM Kill or -9 kill or power outage - doesn't lead to db corruption of Erigon. If it does - then likely you have some specific settings (for example disabled fsync) or broken hardware (we several times saw people had broken RAM - you can try http://memtest86.com to diagnose). 

About OOM - yes it's bug of Erigon, but it can't corrupt db. Please issue with more info, logs, etc...
