### ISSUE TITLE
insufficient funds for gas * price in eth_estimateGas when maxPriorityFeePerGas and maxFeePerGas are specified

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#2944]
Hey there! I think there is a bug in eth_estimateGas when maxPriorityFeePerGas and maxFeePerGas are specified
The eth_estimateGas fails with "insufficient funds for gas * price + value: address 0x176c27973E0229501D049De626d50918ddA24656 have 1219373584177062759 want 3230307210903527424". The tx itself consumes around 185k gas, and the wanted 3 ETH for the tx is clearly wrong.
The estimate works well with a type 0 transaction
Here's a working call with legacy transaction type:
```
$ curl -sq http://10.2.0.7:8545 -H 'Content-Type: application/json' --data-raw '{"method":"eth_estimateGas","params":[{"gasPrice":"0x3222111000","from":"0x176c27973e0229501d049de626d50918dda24656","to":"0x055cc48f7968fd8640ef140610dd4038e1b03926","data":"0xd8b2114e0000000000000000000000004c2f62d6f34388a8d134907fea723e7ed902fe220000000000000000000000000000000000000000000000000000000000000001"}],"id":85,"jsonrpc":"2.0"}' | jq
{
  "jsonrpc": "2.0",
  "id": 85,
  "result": "0x2f343"
}
```
Here's the same tx with tx type 2:
```
$ curl -sq http://10.2.0.7:8545 -H 'Content-Type: application/json' --data-raw '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x3222111000","maxPriorityFeePerGas":"0x77359400","from":"0x176c27973e0229501d049de626d50918dda24656","to":"0x055cc48f7968fd8640ef140610dd4038e1b03926","data":"0xd8b2114e0000000000000000000000004c2f62d6f34388a8d134907fea723e7ed902fe220000000000000000000000000000000000000000000000000000000000000001"}],"id":85,"jsonrpc":"2.0"}' | jq
{
  "jsonrpc": "2.0",
  "id": 85,
  "error": {
    "code": -32000,
    "message": "insufficient funds for gas * price + value: address 0x176c27973E0229501D049De626d50918ddA24656 have 1219373584177062759 want 3230307210903527424"
  }
}
```
I'm using v2021.11.01 (freshly upgraded, was failing before upgrading, I think I had something from early november october before this)

**Comment by AlexeyAkhunov** [comment]
inside `eth_estimageGas` there is a binary search for gas, and it starts with the block's gas limit
this is where 3 ETH comes from (15m multipled by the gas price of the tx)
so the solution is to disable this check in the context of `eth_estimageGas`

**Comment by nebojsa94** [comment]
I don't think that is the problem here.

The reason why execution fails immediately is that provided gas is too high in this context. There is a part of the code that checks for this https://github.com/ledgerwatch/erigon/blob/da00e949c4d8affae2589e7ab79137b7016d6255/cmd/rpcdaemon/commands/eth_call.go#L146 this part will compute correct available gas when transaction type is 0, but it doesn't work with London gas fields.

I think that go-ethereum accounted for this case, see https://github.com/ethereum/go-ethereum/blob/e185a8c8181a2153150e0da8b7dfd3d7a95f8b22/internal/ethapi/api.go#L1012

**Comment by AlexeyAkhunov** [comment]
> I don't think that is the problem here.
> 
> The reason why execution fails immediately is that provided gas is too high in this context. There is a part of the code that checks for this
> 
> https://github.com/ledgerwatch/erigon/blob/da00e949c4d8affae2589e7ab79137b7016d6255/cmd/rpcdaemon/commands/eth_call.go#L146
> 
> this part will compute correct available gas when transaction type is 0, but it doesn't work with London gas fields.
> I think that go-ethereum accounted for this case, see https://github.com/ethereum/go-ethereum/blob/e185a8c8181a2153150e0da8b7dfd3d7a95f8b22/internal/ethapi/api.go#L1012

Thank you, you are right, I made PR: https://github.com/ledgerwatch/erigon/pull/3006
