### ISSUE TITLE
When will call frame tracing and golang call tracer be implemented? 

### ISSUE THREAD

**Issue by Troublor** [ledgerwatch/erigon#2952]
# Rationale

Why should this feature exist?
This is implemented in https://github.com/ethereum/go-ethereum/pull/23087 and https://github.com/ethereum/go-ethereum/pull/23708.
Erigon is the best to maintain an archive node, on which call tracing is heavily used to inspect transactions on Ethereum. 
It is necessary to keep in track with the new features on go-ethereum. 

What are the use-cases?
Analyze transaction executions. 

# Implementation

Do you have ideas regarding the implementation of this feature?
Merge the implementation on Ethereum. 

Are you willing to implement this feature?
Not sure.

**Comment by mandrigin** [comment]
I am not sure we have capacity to do it now ourselves, but if someone want to take a look -- we are open for PRs.
