### ISSUE TITLE
Bad Blocks - MDBX_MAP_FULL - ErrUnknownAncestor - MDBX_MAP_FULL

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#2954]
#### System information

Erigon version: `v2021.10.05`

OS & Version: Linux Mint 20.2

Probably related to #2888 

My erigon instance started throwing endless `MDBX_MAP_FULL` messages. I went back and looked at the logs and have attached them. I truncated the fluff and endlessly repeating messages.

Here's what I see from the logs:

Node processes some BAD BLOCKS and rewinds, this looks more or less normal, however, shortly after it hits `MDBX_MAP_FULL` errors at the `CallTraces` stage, then at the various other stages.

I then later get an error `consensus.ErrUnknownAncestor`

I restart the whole process and ergion is stuck with:
> bucket: TxSender, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached

In an endless loop.

[erigon.err.log](https://github.com/ledgerwatch/erigon/files/7532938/erigon.err.log)

**Comment by MysticRyuujin** [comment]
I just realized that I'm on a slightly older version with an outdated mdbx - guessing that might be the problem - and I'm also guessing I need to re-sync? (which is fine)

**Comment by AskAlexSharov** [comment]
Hi, everybody. 
There was 2 non-related problems which lead to same result. 
They fixed only in v2021.11.03 
But, yes, you need re-sync.

**Comment by marinajpereira** [comment]
I'm having a similar issue with an older erigon version. 
May I know why is a re-sync required after updating the version? I intend to update Erigon version on my end and was wondering if I need to scrap the synced data on disk and restart the sync again after the update?

**Comment by AskAlexSharov** [comment]
“ May I know why is a re-sync required after updating the version?” - not required, different problems need different way to fix. 

In your case please just remove erigon/datadir/nodes folder.

**Comment by marinajpereira** [comment]
> erigon/datadir/nodes

If I remove erigon/datadir/nodes and upgrade the Erigon version, will it continue to sync from where it stopped?

**Comment by AskAlexSharov** [comment]
Yes
