### ISSUE TITLE
Support for POSDAO AuRa consensus 

### ISSUE THREAD

**Issue by eabz** [ledgerwatch/erigon#2984]
Hello,

I have been following the erigon development.

Looking forward to support our blockchain (Polis Chain https://explorer.polis.tech) to the client.

I know that AuRa is not yet supported, my question is: how can I support the development of it?

Submitting a Gitcoin Grant should be good?

**Comment by enriavil1** [comment]
I am sorry, but as of yesterday the support for the Authority Rounds consensus was dropped.
