### ISSUE TITLE
MDBX_PROBLEM: Unexpected internal error

### ISSUE THREAD

**Issue by alysak6075** [ledgerwatch/erigon#2992]
#### System information

Bare Metal

Erigon version: erigon version 2021.11.3-beta

OS & Version: Linux CentOS 8

Commit hash : a37afc5b1546c1ee4c3056fec1315060d03442bd

#### Expected behaviour
After updating from 10.03 to 11.03 a normal start and behavior

#### Actual behaviour
First start:
mdbx_setup_dxb:15019 filesize mismatch (expect 1740877877248b/425019013p, have 1741609238528b/425197568p)
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_setup_dxb:15310 updating db-format signature for meta[1], txnid 568904, error -30779
EROR[11-18|19:38:20.786] Erigon startup                           err="mdbx_env_open: MDBX_PROBLEM: Unexpected internal error, transaction should be aborted, label: chaindata, trace: [kv_mdbx.go:217 node.go:531 node.go:534 backend.go:144 node.go:107 node.go:98 main.go:31 app.go:526 app.go:286 main.go:18 proc.go:225 asm_amd64.s:1371]"

Second start (after I removed nodes directory):
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_setup_dxb:15310 updating db-format signature for meta[1], txnid 568904, error -30779
EROR[11-18|19:39:41.698] Erigon startup                           err="mdbx_env_open: MDBX_PROBLEM: Unexpected internal error, transaction should be aborted, label: chaindata, trace: [kv_mdbx.go:217 node.go:531 node.go:534 backend.go:144 node.go:107 node.go:98 main.go:31 app.go:526 app.go:286 main.go:18 proc.go:225 asm_amd64.s:1371]"

#### Steps to reproduce the behaviour
update from 10.03 to 11.03 and try to start it

**Comment by alysak6075** [comment]
rolled back to a backup I had, and am back online now. Should i first update to 10.05, and then to 11.03?

**Comment by AskAlexSharov** [comment]
> rolled back to a backup I had, and am back online now. Should i first update to 10.05, and then to 11.03?

I think no real difference.

**Comment by alysak6075** [comment]
So how would i update the node without resync? Can I stay on my current version past the december difficulty bomb, since 10.03 doesnt have that adjusted to June.

**Comment by AskAlexSharov** [comment]
1. Can you test upgrade on another machine? 
2. I need investigate what “mdbx_setup_dxb:15310 updating db-format signature for meta[1], txnid 568904, error -30779” means…
3. i think you must not have problem with difficulty bomb.

**Comment by AskAlexSharov** [comment]
2. This is minor bug in mdbx. Likely next our release will include fix.

**Comment by alysak6075** [comment]
1. Unfortunately this is the only machine I have :(
2. ok sounds good, ill wait for the fix and try again
3. ok sounds good

**Comment by AskAlexSharov** [comment]
fix merged to `stable` branch (https://github.com/ledgerwatch/erigon/pull/3015)
releases happening from `stable` branch every Thursday

**Comment by alysak6075** [comment]
Confirmed this is fixed, also fixed a weird swap issue.
