### ISSUE TITLE
Introducing unwind process.

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#3047]
# Rationale

Conventionally, Go-ethereum updates the chain through forkchainupdate, but what we can do instead use ExecutePayloadV1?

# Implementation

So, we can go in the following way about it:
1) We obtain a block owned by a different fork, in order to start unwinding the block must have the following requirements:
* must be added at the beggining of HeadersDownward
* if the payload number is greater or equal to the head (`s.BlockNumber`) then we start the unwind process to `payload number - 1`

**Comment by Giulio2002** [comment]
This will start only after #2997 is merged.

**Comment by yperbasis** [comment]
Implemented in PR #3340.
