### ISSUE TITLE
FR: Support for debug_traceBlockBy(Number|Hash)

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#3080]
Please add support for `debug_traceBlockByNumber` and `debug_traceBlockByHash` methods

# Rationale

Why should this feature exist? `compatibility with geth`
What are the use-cases? `debugging stuff`

# Implementation

Do you have ideas regarding the implementation of this feature? `geth`
Are you willing to implement this feature? 😞

**Comment by McSim85** [comment]
Looks like has been added
https://github.com/ledgerwatch/erigon/commit/58d2118c1053bb06a0c360f6b3b9ea8cb73e542e

**Comment by mandrigin** [comment]
thanks, you are right, closing
