### ISSUE TITLE
About the problem of not syncing after bsc connection

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#3122]
Hello, is there an example of the command to connect to the bsc network? I have been in the state of `Wrote block headers` after I ran it
cmd: `erigon --networkid 56 --datadir /node/bsc --port 21050 --p2p.eth65.port 21051 --private.api.addr 127.0.0.1:21052`
![image](https://user-images.githubusercontent.com/24621599/145945392-b12fc3f3-215a-49bd-aeed-abe79d298186.png)

**Comment by AlexeyAkhunov** [comment]
Hello! BSC support is not complete yet, it is still work in progress. Instead of one large PR, it is now being done in many smaller PRs

**Comment by sundafa** [comment]
Okay, I will wait until the software supports community use.

**Comment by radian-rgc** [comment]
> Hello! BSC support is not complete yet, it is still work in progress. Instead of one large PR, it is now being done in many smaller PRs

Hi, Still is not support ?
