### ISSUE TITLE
Port last changes of discv4 from go-ethereum 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#3124]
Next changes need to port:
- https://github.com/ethereum/go-ethereum/pull/22842
- https://github.com/ethereum/go-ethereum/pull/21396

**Comment by battlmonstr** [comment]
21396 is already applied [here](https://github.com/ledgerwatch/erigon/commit/b9bcd407d5540f7adc06fd7340229f8e04e2b74c)

**Comment by battlmonstr** [comment]
done on devel @ https://github.com/ledgerwatch/erigon/commit/13d66198bc29d88e93e8f0e3fa3d5083f981345b
