### ISSUE TITLE
High number of concurrent network connections

### ISSUE THREAD

**Issue by iSOcH** [ledgerwatch/erigon#3126]
#### System information

Erigon version: `erigon version 2021.12.1-beta`

OS & Version: `Linux erigon-goerli 5.4.157-1-pve #1 SMP PVE 5.4.157-1 (Mon, 29 Nov 2021 12:01:44 +0100) x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 20.04.3 LTS running in LXC Container on Proxmox 6.4)

Commit hash : 2021.12.1-beta release

#### Expected behaviour
Erigon uses a reasonable amount of network connections to other clients.

#### Actual behaviour
It appears that erigon opens/uses a very high number of network connections. This issue was noticed because I am facing sporadic packet loss / delayed network transmissions since I started running an erigon node on the Goeli network. My mainnet node is still syncing, so I cannot say whether it happens there as well.

I checked logs on my OpenWRT firewall, and I can see a high amount of concurrent connections:

![image](https://user-images.githubusercontent.com/10696022/146025122-9de5b1b8-f13b-423a-88ce-69cec33b6299.png)

I find this surprising also because erigon was reporting quite low peer counts when it was up.

```
Dec 14 09:14:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:14:26.995] [p2p] GoodPeers                          eth66=7 eth65=7
Dec 14 09:16:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:16:26.995] [p2p] GoodPeers                          eth66=7 eth65=5
Dec 14 09:18:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:18:26.995] [p2p] GoodPeers                          eth66=3 eth65=2
Dec 14 09:20:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:20:26.995] [p2p] GoodPeers                          eth66=3 eth65=2
Dec 14 09:22:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:22:26.995] [p2p] GoodPeers                          eth66=3 eth65=2
Dec 14 09:24:26 erigon-goerli erigon[1235]: [INFO] [12-14|09:24:26.995] [p2p] GoodPeers                          eth66=5 eth65=2
```

I did not yet try, but from this output I assume lowering maxPeers would not help.

#### Steps to reproduce the behaviour
Unsure, simply run erigon (on goerli)? fwiw, here's my command line:

`/usr/local/bin/erigon --datadir /srv --chain goerli --private.api.addr=localhost:9089 --metrics --pprof --prune htc`

**Comment by iSOcH** [comment]
Checking if the following changes help (so far it appears to):

- Update to 2021.12.03 (removes eth66)
- Forward ports on router (set a custom port for goerli, let mainnet on standard port)
- Set `--maxPeers 20` on both instances (mainnet is still syncing)

So far it seems to help, at least in the conntrack graph of my firewall (the visible decline happened due to chaning `maxPeers`. The other changes were already in place before that.

![image](https://user-images.githubusercontent.com/10696022/146731080-4ac3765b-05dc-4209-8562-d4a353d61051.png)

But still the amount of connections is quite a bit higher than what I would have expected given the `maxPeers` setting:

```
root@erigon-goerli:~# netstat -tn | wc -l
57
```

I assume I could run geth with significantly higher peer count than that. I had geth running for both goerli and mainnet and did not encounter any of these issues with the standard networking settings.

**Comment by AskAlexSharov** [comment]
@weishirongzhen can you try set: — torrent.conns.perfile=2 
And check if it helps

**Comment by revitteth** [comment]
@iSOcH please re-open if the advice above is not working :)

**Comment by kiwec** [comment]
> @iSOcH please re-open if the advice above is not working :)

It doesn't help.
