### ISSUE TITLE
Wrong results for eth_call when using a future block number

### ISSUE THREAD

**Issue by jondoe1337** [ledgerwatch/erigon#3136]
When doing a contract call (eth_call) with using a block number that is in the future a valid result is returned instead of an error message. 

#### System information

Erigon version: 2021.12.02

OS & Version: Linux / docker

Commit hash : 1781181b7d970609c55b3243a7b7d620de3eaa2e

#### Expected behaviour
Result should be:
`{"jsonrpc":"2.0","id":123,"error":{"code":-32000,"message":"header not found"}}`

#### Actual behaviour
Result is:
`{"jsonrpc":"2.0","id":123,"result":"0x"}`

#### Steps to reproduce the behaviour
`curl --location --request POST 'erigon.node' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","method": "eth_call","params":[{"to": "0x111111111117dC0aa78b770fA6A738034120C302","data": "0x70a08231000000000000000000000000a09d1afae21bda81c06fd6de9bbd7c7ed7b6dfb1"},"0xD59F80"],"id":123}'`

**Comment by temaniarpit27** [comment]
@jondoe1337: I will be happy to take this task up.
Can you please assign this to me?

**Comment by mandrigin** [comment]
@temaniarpit27 feel free to fix and submit a PR

**Comment by Maharacha** [comment]
Any update on this beautiful issue? @jondoe1337 ?

**Comment by Maharacha** [comment]
> Any update on this beautiful issue? @jondoe1337 ?

Just found this issue where it should be solved.. But we are having the issue on latest version.
https://github.com/ledgerwatch/erigon/issues/6518

**Comment by akegaviar** [comment]
Hey guys, can you reopen the issue? It was fixed in Geth 5+ years ago. Can you please pull in that change? It'd be very helpful

https://github.com/ethereum/go-ethereum/issues/16925

Thanks!
