### ISSUE TITLE
debug_storageRangeAt transaction index being ignored

### ISSUE THREAD

**Issue by bcelect** [ledgerwatch/erigon#3147]
#### System information

Erigon version: `./erigon --version`

erigon version 2021.12.2-beta

OS & Version: Linux

Commit hash : 1781181b7d970609c55b3243a7b7d620de3eaa2e

#### Expected behaviour

`debug_storageRangeAt` shows changes to storage when transactions within a block mutate the storage

#### Actual behaviour

`debug_storageRangeAt` shows the same data regardless of transaction index

#### Steps to reproduce the behaviour

Using a recent transaction in index 0 that happens to modify storage at this address (`0x27C70Cd1946795B66be9d954418546998b546634`).

```
# erigon
$ curl --data '{"jssonrpc":"2.0","method":"debug_storageRangeAt", "id": 1, "params": ["0x99136e1fd072ff630537cf7231c355a6839d848f7673026a7b100a92b26c9f4b", 0, "0x27C70Cd1946795B66be9d954418546998b546634", "0x0000000000000000000000000000000000000000000000000000000000000000", 16384]}' -H "Content-Type: application/json" -X POST localhost:8545 > /tmp/0e.txt
$ curl --data '{"jssonrpc":"2.0","method":"debug_storageRangeAt", "id": 1, "params": ["0x99136e1fd072ff630537cf7231c355a6839d848f7673026a7b100a92b26c9f4b", 1, "0x27C70Cd1946795B66be9d954418546998b546634", "0x0000000000000000000000000000000000000000000000000000000000000000", 16384]}' -H "Content-Type: application/json" -X POST localhost:8545 > /tmp/1e.txt
$ diff /tmp/0e.txt /tmp/1e.txt  # empty but should not be
# geth
$ curl --data '{"jssonrpc":"2.0","method":"debug_storageRangeAt", "id": 1, "params": ["0x99136e1fd072ff630537cf7231c355a6839d848f7673026a7b100a92b26c9f4b", 0, "0x27C70Cd1946795B66be9d954418546998b546634", "0x0000000000000000000000000000000000000000000000000000000000000000", 16384]}' -H "Content-Type: application/json" -X POST localhost:18545 > /tmp/0g.txt
$ curl --data '{"jssonrpc":"2.0","method":"debug_storageRangeAt", "id": 1, "params": ["0x99136e1fd072ff630537cf7231c355a6839d848f7673026a7b100a92b26c9f4b", 1, "0x27C70Cd1946795B66be9d954418546998b546634", "0x0000000000000000000000000000000000000000000000000000000000000000", 16384]}' -H "Content-Type: application/json" -X POST localhost:18545 > /tmp/1g.txt
$ diff /tmp/0g.txt /tmp/1g.txt  # not empty, there is a difference
```

The erigon outputs are the same (0e.txt vs 1e.txt) and geth ones are different (0g.txt vs 1g.txt) for example entry `0x105d72960504084ff8d8cfd02cb1a814511b5336b74fcdb41b2ec256532d36e2` value is changed in 1g.txt

(At first I thought this was an off by one error in my use of the API but I tried all the txn indexes in the block and found the storage wasn't modified to be different from the 0 index for any of them)

#### Backtrace

None

**Comment by bgelb** [comment]
I think this PR fixes it: https://github.com/ledgerwatch/erigon/pull/3148
