### ISSUE TITLE
Ethereum Classic

### ISSUE THREAD

**Issue by IstoraMandiri** [ledgerwatch/erigon#3179]
Hello! I'm writing as a long time Ethereum and Ethereum Classic supporter and I would like to open a discussion about what paths might be taken so that one day we can get Ethereum Classic to be maintained either officially or as some kind of module of this project.

There are substantial benefits to ETC if we were able to collaborate; not only would ETC be able to take advantage of erigon's data structure optimizations to help with bloat, but it would also seems like there is potential to benefit from easier integration of upstream EVM changes, as opposed to maintaining separate forks of geth, which is the current situation for ETC.  

Ethereum Classic is still going strong and has a growing active community. We recently went through a bit of an interesting phase (the Treasury debate) that resulted in some development teams parting ways, and many ETC supporters are now seeking alternative opportunities with regards to client development.

I'm sure that the funding for an ETC integration with erigon - either as a bounty or by finding external developers - could be found, but I first wanted to open an issue to see where the current development team sits with this idea and how we might continue. 

I'm aware there might be some nervousness surrounding ETC due to our colourful history with Ethereum, but hopefully enough time has passed and we can focus on technicals; I feel there's an really big opportunity for us to synergize and grasp some low hanging fruit.

Thanks in advance

**Comment by brolal** [comment]
This is the one? https://github.com/ledgerwatch/erigon

**Comment by w1g0** [comment]
It would be great to see a reintegration of Etc with Eth once it migrates to the beacon chain. This would revolutionize the ecosystem imho.

**Comment by mandrigin** [comment]
I am not exactly sure we, the core team, can do that right now. But we are always open for someone who wants to add this support and submit PRs to both implement that and also support the feature.

So far I am closing this one, but feel free to comment further.
