### ISSUE TITLE
Parse transaction payload: invalid chainID

### ISSUE THREAD

**Issue by lachobn** [ledgerwatch/erigon#3180]
#### System information

erigon version 2021.11.3-alpha

OS & Version: GNU/Linux Debian Buster

Commit hash : 

#### Expected behaviour

explains the reason of the error

#### Actual behaviour

[INFO] [12-27|20:31:00.879] [1/15 Headers] Processed                 highest inserted=13889144 age=5s
[INFO] [12-27|20:31:00.920] [5/15 Execution] Completed on            block=13889144
[INFO] [12-27|20:31:01.877] Commit cycle                             in=873.505747ms
[INFO] [12-27|20:31:01.877] RPC Daemon notified of new headers       from=13889143 to=13889144
[INFO] [12-27|20:31:01.877] [1/15 Headers] Waiting for headers...    from=13889144
[WARN] [12-27|20:31:01.882] onNewBlock                               err="err: parse transaction payload: invalid chainID, 137 (expected 1), rlp: f86e80850d4dfacdb682520894e386e3372e3d316ae063af50c38704ec6fba514988015f021397cf465080820136a06d116ab1815c81aa7e046df51470d5d0894170d01e11a15efc8215a9a10d1a1ca0054ac7eb8377fd4b81aeb68e839c7ab9337767326f4e9bbff0d1b49d6aa6401f"

#### Steps to reproduce the behaviour

Erigon command line:  /opt/erigon/build/bin/erigon --datadir="/opt/archive" --maxpeers 20 --private.api.addr="0.0.0.0:9090"

#### Backtrace

none

**Comment by AskAlexSharov** [comment]
@lachobn did you add flag —chain dev?

**Comment by lachobn** [comment]
@AskAlexSharov no, i am using it for mainnet. The help option say: "default: mainnet"

--chain value                      Name of the testnet to join (default: "mainnet")

**Comment by AskAlexSharov** [comment]
@lachobn Is this still the issue or can close?
