### ISSUE TITLE
error "WatchTheBurn" block 13908764

### ISSUE THREAD

**Issue by KryptoBillah** [ledgerwatch/erigon#3189]
Seeing following error:
<img width="1837" alt="Screen Shot 2021-12-30 at 3 39 24 PM" src="https://user-images.githubusercontent.com/29290500/147786621-3ebf6498-3587-4362-b493-7bc50ad77c6b.png">

**Comment by Antti-Kaikkonen** [comment]
Seems to be the same error that I was getting, but with different block number. https://github.com/ledgerwatch/erigon/issues/3181
