### ISSUE TITLE
Create Erigon Backup/Restore point?

### ISSUE THREAD

**Issue by BirdyUK** [ledgerwatch/erigon#3206]
Hi,

is it possible to take a backup of the erigon data directory once fully synced to use as a restore point?

I tried to do the following but seems to not have worked so im unsure if this is possible or if i have done it wrong.

Steps:

**1)  tar or zip the entire erigon directory
2)  move tar or zip file to new host and unzip to excact same dir location
3)  install erigon and ensure .conf file is pointing to the same data dir using:  --datadir=/data/erigon/datadir
4)  start erigon and rpcdeamon
5)  check erigon log which shows the following**

```
tail -f /var/log/supervisor/erigon.err.log
[INFO] [01-05|09:27:34.733] [2/15 BlockHashes] DONE                  in=3m17.750795042s
[INFO] [01-05|09:27:34.806] [3/15 Bodies] Processing bodies...       from=13928597 to=13944621
[INFO] [01-05|09:28:04.808] [3/15 Bodies] Wrote block bodies         block_num=13928731 delivery/sec="39.38 MiB" wasted/sec="0.00 B" alloc="2.03 GiB" sys="2.30 GiB"
[INFO] [01-05|09:28:28.607] [p2p] GoodPeers                          eth66=12
[INFO] [01-05|09:28:34.808] [3/15 Bodies] Wrote block bodies         block_num=13929042 delivery/sec="2.79 MiB" wasted/sec="0.00 B" alloc="2.35 GiB" sys="2.56 GiB"
[INFO] [01-05|09:29:04.808] [3/15 Bodies] Wrote block bodies         block_num=13933604 delivery/sec="734.03 KiB" wasted/sec="0.00 B" alloc="2.52 GiB" sys="2.76 GiB"
[INFO] [01-05|09:30:28.607] [p2p] GoodPeers                          eth66=18
[INFO] [01-05|09:32:28.607] [p2p] GoodPeers                          eth66=21
[INFO] [01-05|09:34:28.607] [p2p] GoodPeers                          eth66=22
[INFO] [01-05|09:36:28.606] [p2p] GoodPeers                          eth66=25

```

**6)  Try geth client to see if we can read any blocks:**

```
> eth.getBlock(13929682)
null
> eth.getBlock(2)
null
```

**7)  check what geth for syncing stats:** 

```
> eth.syncing
{
  currentBlock: 0,
  highestBlock: 0,
  stages: [{
      block_number: "0x0",
      stage_name: "Headers"
  }, {
      block_number: "0x0",
      stage_name: "BlockHashes"
  }, {
      block_number: "0x0",
      stage_name: "Bodies"
  }, {
      block_number: "0x0",
      stage_name: "Senders"
  }, {
      block_number: "0x0",
      stage_name: "Execution"
  }, {
      block_number: "0x0",
      stage_name: "Translation"
  }, {
      block_number: "0x0",
      stage_name: "HashState"
  }, {
      block_number: "0x0",
      stage_name: "IntermediateHashes"
  }, {
      block_number: "0x0",
      stage_name: "AccountHistoryIndex"
  }, {
      block_number: "0x0",
      stage_name: "StorageHistoryIndex"
  }, {
      block_number: "0x0",
      stage_name: "LogIndex"
  }, {
      block_number: "0x0",
      stage_name: "CallTraces"
  }, {
      block_number: "0x0",
      stage_name: "TxLookup"
  }, {
      block_number: "0x0",
      stage_name: "TxPool"
  }, {
      block_number: "0x0",
      stage_name: "Finish"
  }],
  startingBlock: 0
}
```

Maybe i did something wrong or this just is not possible?

Thanks

**Comment by AskAlexSharov** [comment]
- If Erigon stopped - it’s ok do move/backup datadir. 
- logs show that Erigon works well (see db), but RpcDaemon not - likely it’s miss-configuration of rpcdaemon.
- show cli flags of rpcdaemon

**Comment by BirdyUK** [comment]
@AskAlexSharov 100% correct, was rpcdeamon!

I had changed the config but forgot to restart supervisord!

Using the following command works perfectly fine with the directory copied from another server:

```
/opt/erigon/build/bin/rpcdaemon --datadir=/erigon/datadir --private.api.addr=localhost:9090 --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,web3,net,debug,trace,txpool --ws
```

This now enables us to create weekly backups on a local SAN thus should anything go wrong we will only ever need to re-sync the last 7 days.

If anyone wants to download this backup from a new fully synced unused archive node we could potentially provide a download url, in which case one would just need to unzip and sync the last few days?

Unzipped the fully synced erigon directory is about 1.7TB and zipped its about 704G

Thanks 👍

**Comment by AskAlexSharov** [comment]
All looks right.
