### ISSUE TITLE
Most relevant fork for BSC support ?

### ISSUE THREAD

**Issue by g4bwy** [ledgerwatch/erigon#3219]
Hi/HNY Erigon devs,

There have been a number of people starting to try out the BSC/Parlia support branches initiated by Ankr, and we've already encountered a few [issues](https://github.com/binance-chain/bsc-erigon/issues) reported in [this repository](https://github.com/binance-chain/bsc-erigon).

However, there's at least another repository [here](https://github.com/Ankr-network/erigon) which belongs to Ankr and seemed a bit more active, but it has issues disabled, and we also noticed upstreaming work seems to have begun, but status is unclear.

Is BSC code considered upstreamed/supported enough so that users willing to test and report issues can do so directly here ?

BR,

**Comment by AskAlexSharov** [comment]
Need finish this https://github.com/ledgerwatch/erigon/pull/3144

**Comment by koen84** [comment]
I switched to erigon team repo for running bsc with it.
https://github.com/ledgerwatch/erigon

**Comment by g4bwy** [comment]
> I switched to erigon team repo for running bsc with it. https://github.com/ledgerwatch/erigon

same here, I've been running ok on upstream branch "devel" for a week, and most issues I had when running the bsc fork (low peers count, txpool not sending transactions, new blocks import sometimes getting stuck for more than 30s) somehow vanished.

**Comment by yperbasis** [comment]
BSC is no longer supported by Erigon. Please consider https://github.com/node-real/bsc-erigon instead
