### ISSUE TITLE
failed ReadTransaction hash=0x... block=13949080 err="rlp: element is larger than containing list"

### ISSUE THREAD

**Issue by clifton** [ledgerwatch/erigon#3226]
any idea whats going on here? this happened after i updated my OS from 20.10 to 21.10 but I'm using docker so its not clear what could be causing the issue

#### System information

Erigon version: `erigon version 2021.12.3-beta` from docker image

OS & Version: Pop_OS! (ubuntu) 21.10

#### Behaviour

```
erigon_1      | [INFO] [01-09|20:58:12.637] [1/15 Headers] Processed                 highest inserted=13973631 age=11s
erigon_1      | [INFO] [01-09|20:58:12.751] [3/15 Bodies] Processing bodies...       from=13973136 to=13973631
erigon_1      | [INFO] [01-09|20:58:42.752] [3/15 Bodies] Wrote block bodies         block_num=13973212 delivery/sec="852.04 KiB" wasted/sec="0.00 B" alloc="300.45 MiB" sys="350.05 MiB"
erigon_1      | [INFO] [01-09|20:59:09.929] [3/15 Bodies] Processed                  highest=13973631
erigon_1      | [INFO] [01-09|20:59:09.929] [4/15 Senders] Started                   from=13947136 to=13973631
erigon_1      | [EROR] [01-09|20:59:11.168] failed ReadTransaction                   hash=0x0b7d22c000536b8dc913e1554b06ec075eba2a1ed503cb58fa0aec189a858c3d block=13949080 err="rlp: element is larger than containing list"
erigon_1      | [EROR] [01-09|20:59:14.873] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[log_panic.go:24 panic.go:1038 panic.go:221 signal_unix.go:735 stage_senders.go:306 stage_senders.go:132 asm_amd64.s:1581]"
erigon_1      | [INFO] [01-09|20:59:14.873] Got interrupt, shutting down...
erigon_1      | [INFO] [01-09|20:59:14.884] Successfully update p2p node database    path=/home/erigon/.local/share/erigon/nodes/eth66 updated=0 deleted=181
erigon_1      | [INFO] [01-09|20:59:14.885] database closed                          label=sentry
erigon_1      | [INFO] [01-09|20:59:14.945] database closed                          label=chaindata
erigon_1      | [INFO] [01-09|20:59:14.946] database closed                          label=txpool
stack_erigon_1 exited with code 0
```

**Comment by clifton** [comment]
i think there's a reasonable chance https://github.com/ledgerwatch/erigon/issues/2545#issuecomment-979823765 will fix it. tho 2 days of downtime is :(

**Comment by AskAlexSharov** [comment]
> i think there's a reasonable chance [#2545 (comment)](https://github.com/ledgerwatch/erigon/issues/2545#issuecomment-979823765) will fix it. tho 2 days of downtime is :(

Sorry, I don’t see relation between your problem and this comment

**Comment by clifton** [comment]
that the db may be corrupted and need to be rebuilt

**Comment by AskAlexSharov** [comment]
Unlikely. Just some bad record by some reason. Also link you show is not related to “db corruption”. 

@clifton try https://github.com/ledgerwatch/erigon/issues/2872#issuecomment-953440728

**Comment by clifton** [comment]
> Unlikely. Just some bad record by some reason. Also link you show is not related to “db corruption”.
> 
> @clifton try [#2872 (comment)](https://github.com/ledgerwatch/erigon/issues/2872#issuecomment-953440728)

thank you! looks promising so far. I'll reopen if i run into any issues.

**Comment by clifton** [comment]
ah, damn it happened again.

```
erigon_1      | [INFO] [01-10|07:27:33.760] [3/15 Bodies] Processed                  highest=13976393
erigon_1      | [INFO] [01-10|07:27:33.760] [3/15 Bodies] DONE                       in=2m27.163159733s
erigon_1      | [INFO] [01-10|07:27:33.760] [4/15 Senders] Started                   from=13947136 to=13976393
erigon_1      | [EROR] [01-10|07:27:42.392] failed ReadTransaction                   hash=0x0b7d22c000536b8dc913e1554b06ec075eba2a1ed503cb58fa0aec189a858c3d block=13949080 err="rlp: element is larger than containing list"
erigon_1      | [EROR] [01-10|07:27:42.392] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[log_panic.go:24 panic.go:1038 panic.go:221 signal_unix.go:735 stage_senders.go:306 stage_senders.go:132 asm_amd64.s:1581]"
erigon_1      | [INFO] [01-10|07:27:42.392] Got interrupt, shutting down...
erigon_1      | [INFO] [01-10|07:27:42.393] event subscription channel closed with the RPC daemon
rpcdaemon_1   | [INFO] [01-10|07:27:42.393] rpcdaemon: the subscription channel was closed
rpcdaemon_1   | [INFO] [01-10|07:27:42.393] rpcdaemon: the subscription channel was closed
rpcdaemon_1   | [WARN] [01-10|07:27:42.393] rpc filters: error subscribing to pending transactions err="rpc error: code = Unknown desc = context canceled"
rpcdaemon_1   | [WARN] [01-10|07:27:43.393] rpc filters: error subscribing to pending logs err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR"
erigon_1      | [INFO] [01-10|07:27:54.868] Successfully update p2p node database    path=/home/erigon/.local/share/erigon/nodes/eth66 updated=0 deleted=350
```

@AskAlexSharov should i just delete my db and re-sync? i would have thought unwinding would work

**Comment by snakeflow** [comment]
> ah, damn it happened again.
> 
> ```
> erigon_1      | [INFO] [01-10|07:27:33.760] [3/15 Bodies] Processed                  highest=13976393
> erigon_1      | [INFO] [01-10|07:27:33.760] [3/15 Bodies] DONE                       in=2m27.163159733s
> erigon_1      | [INFO] [01-10|07:27:33.760] [4/15 Senders] Started                   from=13947136 to=13976393
> erigon_1      | [EROR] [01-10|07:27:42.392] failed ReadTransaction                   hash=0x0b7d22c000536b8dc913e1554b06ec075eba2a1ed503cb58fa0aec189a858c3d block=13949080 err="rlp: element is larger than containing list"
> erigon_1      | [EROR] [01-10|07:27:42.392] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[log_panic.go:24 panic.go:1038 panic.go:221 signal_unix.go:735 stage_senders.go:306 stage_senders.go:132 asm_amd64.s:1581]"
> erigon_1      | [INFO] [01-10|07:27:42.392] Got interrupt, shutting down...
> erigon_1      | [INFO] [01-10|07:27:42.393] event subscription channel closed with the RPC daemon
> rpcdaemon_1   | [INFO] [01-10|07:27:42.393] rpcdaemon: the subscription channel was closed
> rpcdaemon_1   | [INFO] [01-10|07:27:42.393] rpcdaemon: the subscription channel was closed
> rpcdaemon_1   | [WARN] [01-10|07:27:42.393] rpc filters: error subscribing to pending transactions err="rpc error: code = Unknown desc = context canceled"
> rpcdaemon_1   | [WARN] [01-10|07:27:43.393] rpc filters: error subscribing to pending logs err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR"
> erigon_1      | [INFO] [01-10|07:27:54.868] Successfully update p2p node database    path=/home/erigon/.local/share/erigon/nodes/eth66 updated=0 deleted=350
> ```
> 
> @AskAlexSharov should i just delete my db and re-sync? i would have thought unwinding would work

Did you solve the problem? I got stuck exactly as you did for days. Systems reinstalled and db deleted to re-sync for a couple times...
