### ISSUE TITLE
Kovan No peers no data

### ISSUE THREAD

**Issue by jennie-bv** [ledgerwatch/erigon#3234]
#### System information

Erigon version: `erigon version 2021.12.3-beta`

OS & Version:  `Linux 5.10.75-79.358.amzn2.x86_64`

Commit hash : 

#### Actual behaviour

> [INFO] [01-11|12:07:37.530] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
[INFO] [01-11|12:07:37.530] Build info                               git_branch=HEAD git_tag=v2021.12.03 git_commit=47c3b9df31ce6f53b4d6067bbc52d1518966f90e
[INFO] [01-11|12:07:37.530] Starting Erigon on                       devnet=kovan
[INFO] [01-11|12:07:37.532] Maximum peer count                       ETH=100 total=100
[INFO] [01-11|12:07:37.532] Set global gas cap                       cap=50000000
[INFO] [01-11|12:07:37.532] Opening Database                         label=chaindata path=/bv/kovan-data/chain-data/chaindata
[INFO] [01-11|12:07:37.598] Re-Opening DB in exclusive mode to apply migrations
[INFO] [01-11|12:07:37.599] database closed                          label=chaindata
[INFO] [01-11|12:07:37.600] Apply migration                          name=db_schema_version
[INFO] [01-11|12:07:37.602] Applied migration                        name=db_schema_version
[INFO] [01-11|12:07:37.604] Updated DB schema to                     version=3.0.0
[INFO] [01-11|12:07:37.605] database closed                          label=chaindata
[INFO] [01-11|12:07:37.616] Writing custom genesis block             hash=0xa3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9
[INFO] [01-11|12:07:37.620] Initialised chain configuration          config="{ChainID: 42 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 5067000 Constantinople: 9200000 Petersburg: 10255201 Istanbul: 14111141, Muir Glacier: <nil>, Berlin: 24770900, London: 26741100, Arrow Glacier: <nil>, Engine: unknown}"
[INFO] [01-11|12:07:37.624] Initialising Ethereum protocol           network=42
[INFO] [01-11|12:07:37.624] Effective                                prune="--prune="
[WARN] [01-11|12:07:37.626] Preverified hashes not found for         chain=kovan
[INFO] [01-11|12:07:37.635] Starting private RPC server              on=172.xx.xx.xx:9098
[INFO] [01-11|12:07:37.636] [1/15 Headers] Waiting for headers...    from=0
[INFO] [01-11|12:07:37.644] Started P2P networking                   version=66 self=enode://859eaffbc18ad1f3ca1dccbd0d94611ec1e035e29892f822bf11db4c5306b09aa66b39767644b83032ea06cccb2c67e1d0c348f421e748c6a83d9534a30edad7@127.0.0.1:30403 name=erigon/v2021.12.3-beta-47c3b9df/linux-amd64/go1.17.1
[INFO] [01-11|12:08:07.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="8.93 MiB" sys="23.58 MiB"
[INFO] [01-11|12:08:37.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="10.50 MiB" sys="27.58 MiB"
[INFO] [01-11|12:09:07.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="9.52 MiB" sys="27.58 MiB"

#### Backtrace

````
[backtrace]
````

**Comment by jennie-bv** [comment]
> #### System information
> Erigon version: `erigon version 2021.12.3-beta`
> 
> OS & Version: `Linux 5.10.75-79.358.amzn2.x86_64`
> 
> Commit hash :
> 
> #### Expected behaviour
> #### Actual behaviour
> > [INFO] [01-11|12:07:37.530] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
> > [INFO] [01-11|12:07:37.530] Build info                               git_branch=HEAD git_tag=v2021.12.03 git_commit=47c3b9df31ce6f53b4d6067bbc52d1518966f90e
> > [INFO] [01-11|12:07:37.530] Starting Erigon on                       devnet=kovan
> > [INFO] [01-11|12:07:37.532] Maximum peer count                       ETH=100 total=100
> > [INFO] [01-11|12:07:37.532] Set global gas cap                       cap=50000000
> > [INFO] [01-11|12:07:37.532] Opening Database                         label=chaindata path=/bv/kovan-data/chain-data/chaindata
> > [INFO] [01-11|12:07:37.598] Re-Opening DB in exclusive mode to apply migrations
> > [INFO] [01-11|12:07:37.599] database closed                          label=chaindata
> > [INFO] [01-11|12:07:37.600] Apply migration                          name=db_schema_version
> > [INFO] [01-11|12:07:37.602] Applied migration                        name=db_schema_version
> > [INFO] [01-11|12:07:37.604] Updated DB schema to                     version=3.0.0
> > [INFO] [01-11|12:07:37.605] database closed                          label=chaindata
> > [INFO] [01-11|12:07:37.616] Writing custom genesis block             hash=0xa3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9
> > [INFO] [01-11|12:07:37.620] Initialised chain configuration          config="{ChainID: 42 Homestead: 0 DAO:  DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 5067000 Constantinople: 9200000 Petersburg: 10255201 Istanbul: 14111141, Muir Glacier: , Berlin: 24770900, London: 26741100, Arrow Glacier: , Engine: unknown}"
> > [INFO] [01-11|12:07:37.624] Initialising Ethereum protocol           network=42
> > [INFO] [01-11|12:07:37.624] Effective                                prune="--prune="
> > [WARN] [01-11|12:07:37.626] Preverified hashes not found for         chain=kovan
> > [INFO] [01-11|12:07:37.635] Starting private RPC server              on=172.xx.xx.xx:9098
> > [INFO] [01-11|12:07:37.636] [1/15 Headers] Waiting for headers...    from=0
> > [INFO] [01-11|12:07:37.644] Started P2P networking                   version=66 self=enode://859eaffbc18ad1f3ca1dccbd0d94611ec1e035e29892f822bf11db4c5306b09aa66b39767644b83032ea06cccb2c67e1d0c348f421e748c6a83d9534a30edad7@127.0.0.1:30403 name=erigon/v2021.12.3-beta-47c3b9df/linux-amd64/go1.17.1
> > [INFO] [01-11|12:08:07.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="8.93 MiB" sys="23.58 MiB"
> > [INFO] [01-11|12:08:37.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="10.50 MiB" sys="27.58 MiB"
> > [INFO] [01-11|12:09:07.636] [1/15 Headers] Wrote block headers       number=0 blk/second=0.000 alloc="9.52 MiB" sys="27.58 MiB"
> 
> #### Steps to reproduce the behaviour
> #### Backtrace
> ```
> [backtrace]
> ```

https://github.com/ledgerwatch/erigon/issues/2808

**Comment by jennie-bv** [comment]
same issue [#2808 ](https://github.com/ledgerwatch/erigon/issues/2808)

**Comment by enriavil1** [comment]
Kovan uses the AuRa consensus which currently is not supported in Erigon.

**Comment by AskAlexSharov** [comment]
Sorry, due to changes in priorities and roadmap - AuRa support dropped

**Comment by easeev** [comment]
@AskAlexSharov should it be removed from https://github.com/ledgerwatch/erigon/blob/devel/params/networkname/network_name.go#L12 then to avoid confusion?

**Comment by AskAlexSharov** [comment]
Yes

**Comment by enriavil1** [comment]
I have created a PR deleting Kovan from erigon
