### ISSUE TITLE
Is thorax/erigon:latest using the unstable branch?

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#3239]
An Otterscan user apparently tried to run Erigon from the dockerhub image and got a devel build.

Please see the user comment here: https://github.com/wmitsuda/otterscan/issues/155#issuecomment-1010299349

From his logs it appears so because of the "incompatible db schema" message, but it also appears that his db was not migrated because he was able to force-run the stable image afterwards.

I don't have spare disk space to try it myself and confirm, but if this is happening it could be bad for users since they could be getting an unstable version by accident.

**Comment by AskAlexSharov** [comment]
“erigon:stable” for sure pointed to stable releases. 

Default “git clone” and “erigon:latest docker” are pointed to devel branch. 

Devel branch is not really “unstable” - we will do  “erigon 2 alpha” releases from that branch in future. Into “stable” branch we adding only bugfixes, all new features going to “devel”.

About db schema error - it’s not “incompatibility” - but it’s “too strict validity condition” which I need relax (will try today).
