### ISSUE TITLE
RPC Daemon Shuts Down and Closes Endpoint URL (localhost:8545) Immediately after Startup

### ISSUE THREAD

**Issue by codesport** [ledgerwatch/erigon#3247]
This error occurrs on both v2022.01.01 and  v2021.12.03 of Erigon.  Trying without success to deploy Erigon with Lighthouse  for proof-of-stake on the Ethereum MainNet.  

**The only logical explanation is that the RPC daemon is designed to shutdown automatically until Erigon is fully synched. However, we're unable confirm if this is the intended and expected behaviour with Erigon.** 

Since localhost:8545 remains open and available for Geth, Besu, and Nethermind during their synching processes, this error is may also be a configuration issue on our part... or maybe a bug in the Erigon RPC Daemon? 

Our startup config files for Erigon and its RPC Daemon are included below for reference.

### System information

**Erigon version:** v2022.01.01  **AND** v2021.12.03

**OS & Version**: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-94-generic x86_64)

**Commit hashes** :  db7fa3d0ed0758fdca29efd337c85200a290becf  **AND** 748abd39f68b44408555dc6eb6648999f6b5a7ad

### Expected behaviour
RPC daemon should keep the HTTP endpoint URL (localhost:8545) open 

### Actual behaviour
RPC server immediately exits and shuts down. HTTP endpoint URL closes permanetly. 

Also these are in the logs:

`Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [WARN] [01-12|09:20:47.092] rpc filters: error subscribing to pending transactions err="rpc error: code = Unimplemented desc = unknown service txpool.Txpool"`

`Jan 12 09:20:47 hope rpcdaemon[5103]: [EROR] [01-12|09:20:47.092] getting Version                          remote_service=mining error="rpc error: code = Unimplemented desc = unknown service txpool.Mining"`

Please refer to the 16 lines of RPC Daemon logs (back trace) below for more details.

### Steps to reproduce the behaviour
Below are our systemd configuration scripts used to startup Erigon. **NB:** The port for the `--private.api.addr` was changed to 9089 since we have Prometheus using port 9090.

**Contents of /etc/systemd/system/eth1-erigon.service:**
```
[Unit]
Description    = Erigon ETH1 Execution Client service
Wants            = network-online.target
After              = network-online.target 
Requires        = erigon-rpcdaemon.service

[Service]
Type            = simple
User            = $USER
ExecStart       = $HOME/erigon/build/bin/erigon --datadir /var/lib/erigon --chain mainnet --private.api.addr=localhost:9089 --metrics --pprof --prune htc --prune.r.before=11184524
Restart         = on-failure
RestartSec      = 3
KillSignal      = SIGINT
TimeoutStopSec  = 5

[Install]
WantedBy    = multi-user.target
```

**Contents of /etc/systemd/system/erigon-rpcdaemon.service:**

```
[Unit]
Description     = Erigon RPC Daemon Service
BindsTo	       = eth1-erigon.service
After               = eth1-erigon.service

[Service]
Type            = simple
User            = $USER
ExecStartPre	  = /bin/sleep 3
ExecStart       = $HOME/erigon/build/bin/rpcdaemon --private.api.addr=localhost:9089 --datadir /var/lib/erigon --http.api=eth,erigon,web3,net,debug,trace,txpool,shh
Restart         = on-failure
RestartSec      = 3
KillSignal      = SIGINT
TimeoutStopSec  = 5

[Install]
WantedBy    = eth1-erigon.service
```

### Backtrace

````
Jan 12 09:20:43 codesport-server systemd[1]: Starting erigon rpcdaemon service...
Jan 12 09:20:46 codesport-server systemd[1]: Started erigon rpcdaemon service.
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.075] DB schemas compatible                    reader=5.0.0 database=5.0.0
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.076] rpc filters: subscribing to Erigon events
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [EROR] [01-12|09:20:47.076] Unavailable modules in HTTP API list     unavailable=[shh] available="[eth erigon web3 net debug trace txpool]"
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.077] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=false grpc=false
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.080] interfaces compatible                    remote_db= client=5.0.0 server=5.0.0
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.080] interfaces compatible                    remote_service=eth_backend client=3.0.0 server=3.0.0
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [WARN] [01-12|09:20:47.092] rpc filters: error subscribing to pending transactions err="rpc error: code = Unimplemented desc = unknown service txpool.Txpool"
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [EROR] [01-12|09:20:47.092] getting Version                          remote_service=mining error="rpc error: code = Unimplemented desc = unknown service txpool.Mining"
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.092] Exiting...
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.092] RPC server shutting down
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [EROR] [01-12|09:20:47.093] ensure version                           remote_service=tx_pool error="rpc error: code = Unimplemented desc = unknown service txpool.Txpool"
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.094] HTTP endpoint closed                     url=localhost:8545
Jan 12 09:20:47 codesport-server rpcdaemon[5103]: [INFO] [01-12|09:20:47.094] database closed                          label=chaindata
Jan 12 09:20:47 codesport-server systemd[1]: erigon-rpcdaemon.service: Succeeded.
````

**Comment by AskAlexSharov** [comment]
@codesport add to RPCDaemon: --txpool.api.addr=localhost:9089 
(it has default value 127.0.0.1:9090)
now txpool can optionally be launched outside of Erigon, so we have one more cli option to configure

**Comment by codesport** [comment]
> @codesport add to RPCDaemon: --txpool.api.addr=localhost:9089 (it has default value 127.0.0.1:9090) now txpool can optionally be launched outside of Erigon, so we have one more cli option to configure

Thanks for the feedback. 

 As suspected, this is a config problem on our part. Will close this issue now.
