### ISSUE TITLE
BSC node becomes very slow 5 minutes after launch

### ISSUE THREAD

**Issue by SuchJitter** [ledgerwatch/erigon#3249]
#### System information

Erigon version: `erigon version 2021.11.3-alpha`

OS & Version:  CentOS 8.5.2111

Commit hash : 

#### Expected behaviour
Syncing BSC at a steady pace

#### Actual behaviour
Dropping to almost 0 blocks/second after 5 minutes

#### Steps to reproduce the behaviour
./erigon --chain bsc --datadir data

**Example**
NFO[01-12|20:38:37.368] [4/15 Senders] Started                   from=14315843 to=14316534
INFO[01-12|20:38:38.116] [5/15 Execution] Blocks execution        from=7085461 to=14316534
INFO[01-12|20:39:08.283] [5/15 Execution] Executed blocks         number=7085686 blk/s=7.458 tx/s=2849.837 Mgas/s=249.037 batch="7.26 MiB" alloc="165.55 MiB" sys="298.66 MiB"
INFO[01-12|20:39:38.156] [5/15 Execution] Executed blocks         number=7085935 blk/s=8.335 tx/s=2597.752 Mgas/s=252.762 batch="12.76 MiB" alloc="227.86 MiB" sys="307.41 MiB"
INFO[01-12|20:39:56.961] [p2p] GoodPeers                          eth66=21
INFO[01-12|20:40:08.122] [5/15 Execution] Executed blocks         number=7086181 blk/s=8.209 tx/s=2586.970 Mgas/s=250.690 batch="17.77 MiB" alloc="223.84 MiB" sys="331.66 MiB"
INFO[01-12|20:40:38.187] [5/15 Execution] Executed blocks         number=7086471 blk/s=9.646 tx/s=2271.996 Mgas/s=267.319 batch="23.39 MiB" alloc="287.96 MiB" sys="357.79 MiB"
INFO[01-12|20:41:08.198] [5/15 Execution] Executed blocks         number=7086734 blk/s=8.764 tx/s=2496.080 Mgas/s=260.007 batch="28.20 MiB" alloc="248.73 MiB" sys="390.22 MiB"
INFO[01-12|20:41:38.174] [5/15 Execution] Executed blocks         number=7086990 blk/s=8.540 tx/s=2386.840 Mgas/s=245.165 batch="32.68 MiB" alloc="334.60 MiB" sys="402.66 MiB"
INFO[01-12|20:41:56.961] [p2p] GoodPeers                          eth66=28
INFO[01-12|20:42:08.189] [5/15 Execution] Executed blocks         number=7087244 blk/s=8.462 tx/s=2180.897 Mgas/s=233.583 batch="37.11 MiB" alloc="323.92 MiB" sys="425.57 MiB"
INFO[01-12|20:42:38.198] [5/15 Execution] Executed blocks         number=7087488 blk/s=8.131 tx/s=2107.678 Mgas/s=229.029 batch="41.30 MiB" alloc="331.04 MiB" sys="454.01 MiB"
INFO[01-12|20:43:08.180] [5/15 Execution] Executed blocks         number=7087702 blk/s=7.137 tx/s=2675.033 Mgas/s=224.746 batch="44.69 MiB" alloc="289.93 MiB" sys="466.38 MiB"
INFO[01-12|20:43:38.161] [5/15 Execution] Executed blocks         number=7087904 blk/s=6.738 tx/s=2536.524 Mgas/s=217.923 batch="48.20 MiB" alloc="418.42 MiB" sys="486.76 MiB"
INFO[01-12|20:43:56.961] [p2p] GoodPeers                          eth66=31
INFO[01-12|20:44:08.131] [5/15 Execution] Executed blocks         number=7088076 blk/s=5.739 tx/s=2499.599 Mgas/s=211.041 batch="51.31 MiB" alloc="377.61 MiB" sys="501.20 MiB"
INFO[01-12|20:44:38.157] [5/15 Execution] Executed blocks         number=7088313 blk/s=7.893 tx/s=2183.422 Mgas/s=228.983 batch="55.28 MiB" alloc="348.17 MiB" sys="521.64 MiB"
INFO[01-12|20:45:08.260] [5/15 Execution] Executed blocks         number=7088542 blk/s=7.607 tx/s=2375.845 Mgas/s=230.467 batch="59.18 MiB" alloc="248.39 MiB" sys="541.95 MiB"
INFO[01-12|20:45:38.275] [5/15 Execution] Executed blocks         number=7088734 blk/s=6.397 tx/s=2743.462 Mgas/s=222.949 batch="62.52 MiB" alloc="294.91 MiB" sys="564.20 MiB"
INFO[01-12|20:45:56.960] [p2p] GoodPeers                          eth66=29
INFO[01-12|20:46:08.339] [5/15 Execution] Executed blocks         number=7088962 blk/s=7.584 tx/s=2331.455 Mgas/s=228.180 batch="66.25 MiB" alloc="442.25 MiB" sys="572.33 MiB"
INFO[01-12|20:46:38.231] [5/15 Execution] Executed blocks         number=7089185 blk/s=7.460 tx/s=2434.874 Mgas/s=228.651 batch="69.80 MiB" alloc="502.02 MiB" sys="597.00 MiB"
INFO[01-12|20:47:08.150] [5/15 Execution] Executed blocks         number=7089413 blk/s=7.621 tx/s=2438.321 Mgas/s=227.056 batch="73.27 MiB" alloc="488.79 MiB" sys="613.56 MiB"
INFO[01-12|20:47:38.117] [5/15 Execution] Executed blocks         number=7089635 blk/s=7.408 tx/s=2607.313 Mgas/s=232.789 batch="76.83 MiB" alloc="452.92 MiB" sys="636.01 MiB"
INFO[01-12|20:47:56.961] [p2p] GoodPeers                          eth66=29
INFO[01-12|20:48:08.494] [5/15 Execution] Executed blocks         number=7089831 blk/s=6.452 tx/s=2079.313 Mgas/s=194.477 batch="79.85 MiB" alloc="496.40 MiB" sys="652.38 MiB"
INFO[01-12|20:48:38.729] [5/15 Execution] Executed blocks         number=7089865 blk/s=1.125 tx/s=280.105 Mgas/s=30.382 batch="80.40 MiB" alloc="332.82 MiB" sys="652.44 MiB"
INFO[01-12|20:49:08.456] [5/15 Execution] Executed blocks         number=7089900 blk/s=1.177 tx/s=232.517 Mgas/s=28.760 batch="80.95 MiB" alloc="406.94 MiB" sys="652.44 MiB"
INFO[01-12|20:49:38.868] [5/15 Execution] Executed blocks         number=7089938 blk/s=1.250 tx/s=298.539 Mgas/s=33.375 batch="81.58 MiB" alloc="539.36 MiB" sys="652.44 MiB"
INFO[01-12|20:49:56.962] [p2p] GoodPeers                          eth66=30
INFO[01-12|20:50:08.198] [5/15 Execution] Executed blocks         number=7089973 blk/s=1.193 tx/s=284.143 Mgas/s=31.208 batch="82.15 MiB" alloc="366.27 MiB" sys="652.44 MiB"
INFO[01-12|20:50:38.579] [5/15 Execution] Executed blocks         number=7090006 blk/s=1.086 tx/s=342.321 Mgas/s=32.837 batch="82.73 MiB" alloc="515.01 MiB" sys="652.44 MiB"
INFO[01-12|20:51:08.842] [5/15 Execution] Executed blocks         number=7090033 blk/s=0.892 tx/s=445.486 Mgas/s=35.440 batch="83.21 MiB" alloc="430.14 MiB" sys="668.69 MiB"
INFO[01-12|20:51:38.715] [5/15 Execution] Executed blocks         number=7090069 blk/s=1.205 tx/s=325.860 Mgas/s=32.720 batch="83.78 MiB" alloc="555.25 MiB" sys="668.69 MiB"

**Comment by AskAlexSharov** [comment]
I think now better ask BSC questions here https://github.com/ledgerwatch/erigon/issues/3249
In any case - this issue has not enough info: 
- is it happening every time - and at any block number? Or you just saw it once?
- What is your hardware? Disk, RAM. 
- is it server or desktop? any other Disk/RAM-hungry processes on same machine?
