### ISSUE TITLE
roadmap of eth_subscribe and filter method

### ISSUE THREAD

**Issue by netquery** [ledgerwatch/erigon#3250]
1. Currently Erigon's eth_subscribe method only supports newHeads & newPendingTransaction, when will logs and syncing be supported?

![image](https://user-images.githubusercontent.com/51869602/149254831-f8b4b325-7723-44ad-ac3f-99ef6a654bf5.png)

2. And when will the following filter methods be supported?
![image](https://user-images.githubusercontent.com/51869602/149254861-f763761e-20d9-4e34-b86b-d1272a51cb2f.png)

Thanks!

**Comment by AskAlexSharov** [comment]
- newPendingTransaction - I think we have it. plz try.

- About "newFilter" methods - No ETA - because no much people need them. But we have eth_getLogs - and it's fast with any filters and at any history depth.

**Comment by netquery** [comment]
> * newPendingTransaction - I think we have it. plz try.
> * About "newFilter" methods - No ETA - because no much people need them. But we have eth_getLogs - and it's fast with any filters and at any history depth.

yep, when will logs and syncing be supported?(eth_subscribe)

**Comment by AskAlexSharov** [comment]
hi. I think it's done (in devel, will be in next alpha release)
