### ISSUE TITLE
getTransactionReceipt and trace functions return null for tranactions DEVEL 

### ISSUE THREAD

**Issue by TheAlexCH** [ledgerwatch/erigon#3257]
On GOERLI, for some old blocks I get NULL values for getTransactionReceipt

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": ["0xe07322123d0747c649b9942c6aeba023e1c129502247fab00ecdcc26a920f85b"], "id":1}' localhost:8545

below some params. It happens for just a few transactions around that transaction.
![image](https://user-images.githubusercontent.com/39984889/149371462-6d5acf90-eb9b-4f11-8c1e-8db3a60ea191.png)

**Comment by TheAlexCH** [comment]
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "trace_replayTransaction", "params": ["0x82f9ab143665c0c9534d3a0a342bdd1817f9f0e211ce3eb3a376054af7d5ff58",["trace"]], "id":1}' localhost:8545

 curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": ["0x82f9ab143665c0c9534d3a0a342bdd1817f9f0e211ce3eb3a376054af7d5ff58"], "id":1}' localhost:8545
 
 This is now on Mainnet.

**Comment by TheAlexCH** [comment]
Here is a list of transactions within the first 120,000 blocks that I have gotten no result.

0x01f440b4539821dda29c2ff87c08c18c85b7873b0e88389a8c72fdd98d1521a6
0x7412279e437a22c6c8a3b2caf5b148cd1c471e2b3790d20908ac50b0129ab334
0xac8f4d5c23511bbf854410dc84d4e4602f1f63eeceac9e0ff76e13d30842242e
0xf29992ef639edf6405297afc98705cafb9437fa85a35d0d667b78eed929c1266
0x67b2a6728d68345067bb8662e85caac85635bfe9c3c636ecf7772dfe424ea19d
0x46828262c499630d70a0c833752c871c72b6aec84ffec910d9e5d8cc95ac51e2
0xd78a47b6fedb0295b9ce4f3e3a5444672ad91da03facd8f82bd4bd41e79b5429
0x73425699a47c8aa890c0ae301593e9cfc1a8818949bffe4e8849907991893486
0xdbc8727bc7123dbd582949839ae56d2d9f1b89e37e2d956ddb034a672ad79d5a
0xb616080e75b094918872316dec26581ff67de63cac80854735f7f2831b74d280
0x4bcc007135db49e7b10a3b08d37d95acd3e040439867234288b20ce57335716e
0x25134b57cf395292eb00815cea6330b764f5ec9b63f87d7ccae5d0e3ba6a4c69
0x8d040708ef3c10bd97ed88b93712991d42cf0519464274ff2a4602e4c0172410
0xd59de4e1aff0d784f0db5f75fca69dbb68aba957c336ea70167f4d2c7ed5b772
0x356f24398678144f076270151dc2191db74d2dd3bbbdcb210339be65f1d9b5fd
0x7dee38d0e08df1a660756b7a668cb7d70bfec1c8edc4e52c72e5026cc9629505
0x328815187f8c0c80165a50f18a1d797b040dd937a538daa452466ae12bc2b0bd
0x1f7d9de2457a454840c1bcbb34c0fc6fd553df695113782a64005bafd6e25ff0
0x1441331dc959daddd0fda1c4d9f8c00e073e5c424db4401a615e723c67dbf3fe
0xd376e21e9d768897fa2363840bbbe0f71c6c7a26f0b1207f050150a4251354b6
0xfc66d4d5e82df1a827529acb29ff7025e60bd952a108f06c066e100caaab0cb0
0x86bf41db0106f92e7ed0fbabad8513a798d1870fce49936c2a80a926e456b765
0x47f81dfc0118cd9bc5e1d0e064c47bacd97e52fc13b4152d2bd08e7be9bde1a8
0xaf15da6148c8316c27684c95a27e3fa90a853261d3d898c577b2469359b7ecee
0x5acaab0e8708119f2b7ca0c9f337fdb5a8a30462dc9e40a47c0473c06646099c
0xaa8342b2377b90e0d66d3c89c33fc156c7207eccdcc44a096a68532ba7f2f0ee
0x4b4dfcdc2db248d22ce9cfd027913e54528bd18a94c0a2a739444cb00fc5afdc
0x4eb7d2cdfa281ec80c9a19d2a44c3651736fd3604c8495e985dc4a05005e36e7
0xbfe047e256fcd98790e54dd6345e5e53bcba6def932d4b6054c46c259092c4eb
0x1ee088d3d5e4b1ba4043254dd84fc506ee89d4887555df4207937247210846f3
0xd3e397ce9459fcebde452fd2a130208581538a6dcc9c01815564c3d704bdbc7f
0x02b85779182fed52be69fd2e9d112273c958962a5c137065dd371cf4fb64eb04
0x3eaa5469bdbf90afb8de2c07151a49ae17711be1da7dceb31aa1f24aeb99079b
0x82ca0420079fde4cb3cd028fcc280097ab18a063fe1a9c2e7990c89b7eaaff52
0x0ce69a6adcd9b5a1fa61061d6f41616c08bebc5dc9dca2d04d5d174d6880a44c
0x69c194c2ae45334af60da1a1c165cad8ce075d8ea939b576300f70881da8be36
0x9a8bf5dbccccd77d9ef41b5718bd8b7430c4ea1f4f55e62e36c17281124ee38e
0x06d6d103c31cf791f23e7a8804aeb1edd92e708cdd049accd7d9e825bbca3911
0x4391a9804f083bbb0c2ee8578d5f8c886a40b85b958621c3a33091a2692b346d
0xa30aedcd4977ac6956fb947a45280a38cc361ea0e41f3ef46553b3d04cc2e276
0x91fb6dfac75231b2dd953eb093dee5b4652c80f3f3d4c25eacf1361328d16af1
0x7f515a54f0a069f92f2a3fceb5672732a66f59253423e83eab0100b80b152a77
0x1acf2d2319f2b71a3f523b948fbfb38c8870bcfb10f3bda327b279ee84a6db4f
0x15288ae75e6cd84353d093bbadc333836b323a7f3bd59608e5927aedcb622671
0xdd0bdc468865b9ebe1b9c8f596056dac929738cf552b5d917d0ddb5200dfe2c1
0x59384f5d50f47f17612b4cf37b1c072644e43d3703cb77f8f2d48a896c4c2bbb
0xa67c83562bcd037f64ad53db8842e551a91999f4698c0a3653a5e32bbc8c9e99
0x1d3b94bf3eead4952d7a36527c253b5ae7198becdb68d157921ccb571178cb03
0xa10ec7fb10f30936b508c6784c66d21520b2013f8e61cf56388d5939d01df0c5
0x3be5cf15b72939e71834a5575ccbf8ba5c357b322b6f536d4b9b5fef3025ce20
0x5f1a18bc771223be7569158ce4e3e9e389dd8fd1d4b1781ade62cbe14302a317
0xd039a1ca04b8fed89b9303e4f621f24feebd2330a041a928b8e7913fd1492a8f
0x08d0a3daadcc43df5c762b77a22dc1adfc02cda039f575a3f38c48e0f591a43b
0x08d1dfe9c8eb5401f352230e4292fbff946ed024479640387e182d283382cdca
0x97f13e1db4b128efd9502c30c17cf4c052c3485c078953b0dcb6afdf901a3caf
0x7480f97521f3179217168272a30d579e19f169f1b50e939bc4a71ba70b844805
0x894072f23ccad9249b929e1feb60bce61ea6867dac1e36c271662ac192fc69c3
0x5eddc8f948dc81167bb66f8de8872fc9ebc71bfc04d28c405e07ac67736a6891
0xe5c10ec29a46d54e7a781537dc4b2366f5729ed27ac95e51750709f292c359ed
0x8eafed4b1963f6ed60488f2c54f55f8d0a9df3f0bbb7c022de2e8d7aaac045b9
0x69b5c644b44477c6dcf3416fa068c2fd022a29efbfa8a9779804a1e9e4180983
0x740849f2f835bf289080583eeba964d911a7d00a09f016046b2d5120e179c215
0xea351ef340c199ce08f8eb53c6023e7b45b522ee98380316a43ee7e62509d736
0x5be42ebd58332a82391f5bb7cb706a11ca31280a7f1f3385f59afe8949e95edc
0xcf885583fa45cc8457fab48684c04c3a5e4aa969b0fa8cbb9246c85d06d9ecf5
0xed0a320594c31dc37464373857aa3b9f144d51190ba3094879047f1838545e04
0x62217588c020f640d81e10197b8d4da1491f483f2c3a1388cfe4be31ff30ffd6
0xdd540c594eba206e8262d2390113650b597252a9dfd474bd6b2dc29676531fee
0xb68c9ccb3888a9cc273cd07f00db28170066e74beca44c6b820602e65a05e97a
0xd18f08fc934bfe9e77cfd9b0b3dcedfa7f41cc7a8ef0a94582ad3f22ab095b48
0xc646a919de98138848a472fcb7ff9fb5454d8b7e71b526e0516eb79ac1f1ea7f
0xd8f76db150cc2bebf1a10d1a7dfdcfb456278e60418036141fbf03fa8e97e669
0xebce9ab6e0ff6d074fea4c066c8d3922985dbaf6a0bb69016aa70e1bb4f47ec8
0x346734ddcfb47521c456dd4fbfd5228f1c3c61bc85811373bcf119d7481218b3
0xe3decfa883adf2eed62ec8892bbeb3c071815a68746387b73027ffaf7260500c
0x36bbd550a9db6b7e2a6214571ab2bded6b4b297d7b240e12ceaa23aec9c137bc
0xcc0f4db8e956562c08907378b3d220325bfad62ac1a6100b935d7390609a0e7a
0x82f9ab143665c0c9534d3a0a342bdd1817f9f0e211ce3eb3a376054af7d5ff58
0x901e058fa3cb24f6764380a35ef0279ca787db67372324d07360816cf8369549
0xd96cf434ba53c4cd095786b8ebcac273c1339eb40012859f67e49fbbce462be4
0xde6aff654d3b8ddf22efcc69e7d7d231d594599689f575a6b94f804666bd325e

**Comment by tjayrush** [comment]
I just ran all those txs against this version of Erigon (erigon/2021.11.3/linux-amd64/go1.16.3) and got non-null traces and receipts for all.

For example, against mainnet, for `0xe3decfa883adf2eed62ec8892bbeb3c071815a68746387b73027ffaf7260500c` using `trace_transaction` I get:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "action": {
        "from": "0x4e9f76cbc24805bf1db0fb2113b3fab42f9879df",
        "callType": "call",
        "gas": "0x8fc",
        "input": "0x",
        "to": "0x9f78552704fe7e52cc7c3853534aa2c3cf580d54",
        "value": "0xd18df9ff2c660000"
      },
      "blockHash": "0x59fbe3d09e65a8ffb3a45f9b54042c17699e95e56efb5943c0207ecabb0192b8",
      "blockNumber": 84362,
      "result": {
        "gasUsed": "0x0",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [],
      "transactionHash": "0xe3decfa883adf2eed62ec8892bbeb3c071815a68746387b73027ffaf7260500c",
      "transactionPosition": 1,
      "type": "call"
    }
  ]
}
```

**Comment by TheAlexCH** [comment]
thanks @tjayrush  your response. Very nice to see somebody is looking into it. The entire utility of erigon is here at stake for us as we rely on those functions.

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "**trace_replayTransaction**", "params": ["0x3abbce21989f706547c03bb30c04e9677edaf64c7c58f67f775acc8201618bc7",["trace"]], "id":1}' localhost:8545

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "**eth_getTransactionReceipt**", "params": ["0x3abbce21989f706547c03bb30c04e9677edaf64c7c58f67f775acc8201618bc7"], "id":1}' localhost:8545

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "**trace_transaction**", "params": ["0x3abbce21989f706547c03bb30c04e9677edaf64c7c58f67f775acc8201618bc7"], "id":1}' localhost:8545
```

all 3 return NULL. This is another TX Hash that doesn't work as well. 

What could it possibly be? I mean is there even something I could do wrong? its also not the case that its random. I parsed 1 million blocks now 10 times and its the exact same TX hashes that do not work every single time. 

What I found is that this data is available on block level requests. So it is somewhere just somehow the RPC does not return anything.

./build/bin/erigon --version
erigon version 2021.11.3-alpha

**Comment by tjayrush** [comment]
If I copy your exact text above (modified to run against my RPC endpoint):

```
jrush@iMac:~/D/trueblocks-explorer|develop✓➤ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "**trace_replayTransaction**", "params": ["0x3abbce21989f706547c03bb30c04e9677edaf64c7c58f67f775acc8201618bc7",["trace"]], "id":1}' localhost:23456
```

I get:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method **trace_replayTransaction** does not exist/is not available"}}
```

If I remove the stars from the command:

```
jrush@iMac:~/D/trueblocks-explorer|develop✓➤ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "trace_replayTransaction", "params": ["0x3abbce21989f706547c03bb30c04e9677edaf64c7c58f67f775acc8201618bc7",["trace"]], "id":1}' localhost:23456
```

I get:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "output": "0x",
    "stateDiff": null,
    "trace": [
      {
        "action": {
          "from": "0xb735bf53abc79525a4f585a004a620d08cc66b27",
          "callType": "call",
          "gas": "0x5c628",
          "input": "0xce5566c500000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000",
          "to": "0xdf415bb7ae2363ecbb6a595f07cbc2fc0fd417d3",
          "value": "0x0"
        },
        "result": {
          "gasUsed": "0x7442",
          "output": "0x"
        },
        "subtraces": 1,
        "traceAddress": [],
        "type": "call"
      },
      {
        "action": {
          "from": "0xdf415bb7ae2363ecbb6a595f07cbc2fc0fd417d3",
          "callType": "call",
          "gas": "0x8fc",
          "input": "0x",
          "to": "0xb735bf53abc79525a4f585a004a620d08cc66b27",
          "value": "0x1d24b2dfac520000"
        },
        "result": {
          "gasUsed": "0x0",
          "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [
          0
        ],
        "type": "call"
      }
    ],
    "vmTrace": null
  }
}
```

Which makes sense since the commands have no stars (**) in them.

By the way -- I'm not affiliated with Erigon, just trying to help out.

**Comment by TheAlexCH** [comment]
the stars are because of "bold" text. thats a github website thing.
like if I make **THIS** bold, it gets two stars.

**Comment by tjayrush** [comment]
All good. In that case, we get straight-up good data. Again, not affiliated with Erigon, so maybe I'm not helping. I'll bow out now. Cheers. Good luck.

**Comment by TheAlexCH** [comment]
it might be as I am on Devel means there might be a bug now that isn't in stable version

**Comment by AskAlexSharov** [comment]
@TheAlexCH , please try next debug branch (based on devel): debug_null_receipt
send here what rpcdaemon prints on this branch when you send request
