### ISSUE TITLE
BSC node error

### ISSUE THREAD

**Issue by susuper** [ledgerwatch/erigon#3258]
#### System information

Erigon version: git_branch=bsc git_tag=v2022.01.01 git_commit=51203138b404bee74814d0e73b0c7e2a1
7ee9bf2

OS & Version: FreeBSD 13.0-RELEASE-p5

Commit hash : 51203138b404bee74814d0e73b0c7e2a17ee9bf2

The error occurred only once:
[EROR] [01-12|20:03:53.483] Staged Sync error="runtime error: index out of range [66] with length 66, trace: [stageloop.go:120 panic.go:1052 panic.go:90 header_data_struct.go:117 heap.go:93 heap.go:86 header_algos.go:593 stage_headers.go:423 stage_headers.go:121 default_stages.go:20 sync.go:318 sync.go:235 stageloop.go:154 stageloop.go:58 asm_amd64.s:1581]"

**Comment by AlexeyAkhunov** [comment]
Please try latest version from the branch, I have committed a fix
