### ISSUE TITLE
BSC sync finished but cant connect

### ISSUE THREAD

**Issue by radian-rgc** [ledgerwatch/erigon#3279]
After 15 days i finished synce BSC but can not connect to the node via web3 by `ws://127.0.0.1:8545` and `http://127.0.0.1:8545`

I use below command for run bsc erigon:

`./build/bin/erigon --chain bsc --prune=hrtc --prune.h.older=3000000 --prune.r.older=3000000 --prune.t.older=3000000 --prune.c.older=3000000 --datadir dexpool  --maxpeers 300`

what is the problem ?

![dex2](https://user-images.githubusercontent.com/23151404/149762308-67993fcb-a8b3-4dfa-8327-555def4f6958.png)

**Comment by AskAlexSharov** [comment]
JSON-RPC living in another process: https://github.com/ledgerwatch/erigon#json-rpc-daemon

**Comment by radian-rgc** [comment]
Thanks,
I run it, but now just i can connect via http protocol, and can't access via websocket.

**Comment by radian-rgc** [comment]
Sorry, i found it

must add --ws

Thanks,
