### ISSUE TITLE
Use IPC endpoint

### ISSUE THREAD

**Issue by radian-rgc** [ledgerwatch/erigon#3281]
Im using web3 to connect bsc node but its very slowly to get data.

for example i want to get balance for last 100 blocks and i get this results:  (101 blocks in 10.574 seconds; 9 blocks/sec).

i think it's too slow and can be faster.

`http://127.0.0.1:8545` => `(101 in 10.765 seconds; 9 blocks/sec).`
`ws://127.0.0.1:8545` => `(101 in 11.281 seconds; 8 blocks/sec)`

I think if i use `IPCProvider ` can be more faster to fetch data.

how can i use it ?

I see this in:

https://github.com/ledgerwatch/erigon/blob/devel/node/config.go#L78

but no any documentation about this.

**Comment by AskAlexSharov** [comment]
No. You just need pass —datadir option to rpcdaemon.

**Comment by radian-rgc** [comment]
> No. You just need pass —datadir option to rpcdaemon.

Sorry, I do not think you understand what I mean or I have misinterpreted.

is it possible to web3 connect to the node via IPC endpoint.


// Using the IPC provider in node.js
```
var net = require('net');
var web3 = new Web3('/Users/myuser/Library/Ethereum/geth.ipc', net);
```

erigon support IPC ?

**Comment by AskAlexSharov** [comment]
no IPC. 
to improve performance of RPCDaemon add --datadir flag - it will use shared memory access with Erigon then

**Comment by SuchJitter** [comment]
> 

Will there be any support for IPC in the future, I assume that it is faster than WebSocket?
