### ISSUE TITLE
Running full node and using fast sync

### ISSUE THREAD

**Issue by arater** [ledgerwatch/erigon#3291]
How can I run a node as a full node and how can I sync my node via fast sync?
- Because by default running is an archive node
- And I could not see anything how to specify synchronization because I want fast sync not full sync.
I created this command after some investigation in order to handle full node, in there I tried to reach state data after block number 5000000. Is this correct for what I want?
./build/bin/erigon --datadir rinkeby --chain rinkeby --prune=hrtc --prune.h.before=5000000 --prune.r.before=5000000 --prune.t.before=5000000 --prune.c.before=5000000
But how can I specify fast sync to this command?

**Comment by AskAlexSharov** [comment]
All correct. Erigon doesn't have fast sync.
