### ISSUE TITLE
How to reach node data?

### ISSUE THREAD

**Issue by arater** [ledgerwatch/erigon#3292]
I run my full node with Erigon and ethereum rinkeby network data is written to my local storage. How can I reach and get some of data according to my filter? And for example I want to see transactions which are bigger than 10k how can I get this information from my running node?

**Comment by AskAlexSharov** [comment]
@arater do you looking for json rpc? https://github.com/ledgerwatch/erigon#json-rpc-daemon

**Comment by arater** [comment]
I guess I am looking for that when I sure about it I will close issue thanks.
Btw can I query and fetch data from node by using the graph (https://thegraph.com/en/)

**Comment by AskAlexSharov** [comment]
Yes
