### ISSUE TITLE
txpool Command Copy refereces p2p sentry

### ISSUE THREAD

**Issue by mikeshultz** [ledgerwatch/erigon#3334]
#### System information

Commit hash : 1e32281

#### Expected behaviour

Text description of the purpose of the `txpool` command.  

Didn't notice this executable until now and I was trying to learn more about its purpose.  Help output appears to be from a copy and paste.  [The docs on this command](https://github.com/ledgerwatch/erigon/tree/devel/cmd/txpool) don't especially have a general description, either.  I can infer it has to do with transaction pool handling, but it's not really clear if it's the entire network's mempool known to the node or local transactions or what.

It's not immediately clear to me if the commad options are for this one or sentry.

#### Actual behaviour

Descriptions of p2p sentry command.

#### Steps to reproduce the behaviour

    $ txpool --help
    Run p2p sentry

    Usage:
      sentry [flags]
    [...]

**Comment by AskAlexSharov** [comment]
Ok, i will add better description.
 
it’s exactly what you run inside Erigon now, but you also can disable pool inside erigon by —txpool.disable and run it outside ( so can run multiple of them, or use your own implementation, or customize logic). 

Same thing you can do with sentry. Also, after the-megre you will run external consensus service. 

95% of pool-related code (from p2p message parsing, to sorting logic) is inside this folder: https://github.com/ledgerwatch/erigon-lib/tree/main/txpool

Our pool is different from Geth’s - here is design doc: https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design
