### ISSUE TITLE
eth_getTransactionByHash on unknown transaction causes error

### ISSUE THREAD

**Issue by mikeshultz** [ledgerwatch/erigon#3335]
#### System information

Erigon version: `2021.11.3-alpha`

OS & Version: Linux

Commit hash : 9c1b5f8f0cd3a89a9f763c7b66737ea1c9256e20

#### Expected behaviour

    $ curl -v -X POST -H 'Content-Type: application/json' --data '{ "id": 123, "method": "eth_getTransactionByHash", "params": ["0x16c55d9e9ca5b673cafaa112195a5ad78ceb104e612ff2afbf34c233d6e7482b"] }' http://localhost:8545/
    {
        "jsonrpc": "2.0",
        "id": 123,
        "result": null
    }

#### Actual behaviour

    $ curl -v -X POST -H 'Content-Type: application/json' --data '{ "id": 123, "method": "eth_getTransactionByHash", "params": ["0x16c55d9e9ca5b673cafaa112195a5ad78ceb104e612ff2afbf34c233d6e7482b"] }' http://localhost:8545/
    {
        "jsonrpc": "2.0",
        "id": 123,
        "error":
        {
            "code": -32000,
            "message": "rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil"
        }
    }

#### Steps to reproduce the behaviour

    $ curl -v -X POST -H 'Content-Type: application/json' --data '{ "id": 123, "method": "eth_getTransactionByHash", "params": ["0x16c55d9e9ca5b673cafaa112195a5ad78ceb104e612ff2afbf34c233d6e7482b"] }' http://localhost:8545/

#### Backtrace

No crash so trace, but here's logs:

    Jan 23 16:32:21 node erigon[141748]: 2022/01/23 16:32:21 ERROR: [core] grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
    Jan 23 16:32:21 node rpcdaemon[142028]: [WARN] [01-23|16:32:21.602] Served                                   conn=127.0.0.1:44192 method=eth_getTransactionByHash reqid=123 t=771.081µs err="rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil"

**Comment by mikeshultz** [comment]
This may also occur with local transactions in the txpool (but I'm not sure of a way to confirm this using another method than this RPC endpoint).

**Comment by enriavil1** [comment]
What erigon branch are you using? I put in a fix in devel, which will return nil if the tx pool doesn't find the tx hash.

**Comment by enriavil1** [comment]
This is the commit where it avoid that error ef180848f0c01c58351233eb535f975f2fd14a54

**Comment by mikeshultz** [comment]
Sorry for the delay.

> What erigon branch are you using? I put in a fix in devel, which will return nil if the tx pool doesn't find the tx hash.

@enriavil1  I've been running off devel and my current build includes the commit you referenced.

**Comment by mikeshultz** [comment]
Updated to `erigon version 2022.99.99-dev` (2cc49f454ffecd9e17d5b04c1cd68b393cd0bbe7) and same behavior.

**Comment by enriavil1** [comment]
> Updated to `erigon version 2022.99.99-dev` (2cc49f454ffecd9e17d5b04c1cd68b393cd0bbe7) and same behavior.

Which chain are you using, so I could try recreating the issue. Only suggestion I have is to try it on stable.

**Comment by mikeshultz** [comment]
Ethereum mainnet, nothing fancy.  Have you tried my curl repro above?  It's a hash that doesn't exist, and I'd imagine would cause the same error.  If you can't reproduce it, I'll try a completely clean clone and build from devel. 

Not sure about moving to stable.  Wouldn't that potentially cause issues due to migrations run or other DB incompatibilities?  I'd prefer not to have to resync if I can avoid it.

**Comment by enriavil1** [comment]
I'll check it out, but syncing would take a while for me.

**Comment by enriavil1** [comment]
I believe id should be 1 so the call should look something like this 
`curl -s --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0xb2fea9c4b24775af6990237aa90228e5e092c56bdaee74496992a53c208da1ee"],"id":"1"}' -H "Content-Type: application/json" -X POST http://localhost:8545`

**Comment by mikeshultz** [comment]
`id` in JSON-RPC is arbitrary and generally only used to match a response to a request.  It should not have any affect on what response is given.  

I tried it anyway and included the version (`"jsonrpc": "2.0"`) to no effect.

**Comment by AlexeyAkhunov** [comment]
@enriavil1 I have been just reviewing this. I think the `nil` transaction is actually happening here: https://github.com/ledgerwatch/erigon-lib/blob/2fc62cd2f54e77751e64d1e88c55dbd94c0f7017/txpool/grpc_server.go#L268

I saw the clue in the error message, taking about `proto`, to suggest it was not JSON marshalling, but GRPC (protobuf) marshalling that causes the issues. Another clue is that it appears in the Erigon log, not RPC daemon log

**Comment by gfxlabs** [comment]
i'm still getting this issue on v2022.05.04

more specifically, 
```method=eth_getTransactionByHash reqid=12 t=3.829001ms err="rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil"``` 
on the rpcdaemon logs  and 
```2022/05/21 21:39:38 ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil``` 
on the erigon logs. this is my ropsten node.

so it's something with the grpc marshaling, but im not 100% sure if the patch fixed it?

**Comment by KaiRo-at** [comment]
@AlexeyAkhunov it looks like this regressed recently, I guess with the changes that also moved from beta to alpha. From what I remember, the beta versions gave a correct response there but now we are seeing this issue.
We have even seen it when Web3.py is waiting for a receipt for a transaction it just posted (I guess it just polls for the transaction by hash there), which is actually breaking code as it errors out instead of waiting longer when a transaction has not been included yet.

**Comment by AskAlexSharov** [comment]
@KaiRo-at what is your erigon version?

**Comment by KaiRo-at** [comment]
> @KaiRo-at what is your erigon version?

This was on v2022.05.06, I haven't tested on .05.08 yet as that one keeps crashing every hour or so on our Goerli test machine (but that is probably unrelated).

**Comment by KaiRo-at** [comment]
And it looks like it's probably fine again in v2022.05.08, actually :)

**Comment by mandrigin** [comment]
closing this one, if that behaviour repeats please reopen
