### ISSUE TITLE
use erigon prune to help devide archive node into several nodes

### ISSUE THREAD

**Issue by flywukong** [ledgerwatch/erigon#3349]
the data of erigon on  archive node on bsc mainnet  has reach more than 6T ,  I want to split archive  node into 3-4 segment .  for example,  segment-1 
is responsible for 1-500w height data( 
stop sync manually after reach this height), segment-2 is responsible for 501-1000w height data ( with 1-500w height state data pruned).   Of course, such an approach requires a  strategy which can forward the rpc request to the correct segment .

My question is in the data processing part ，can such a requirement be achieved through erigon prune? My tests has failed  because prune parameters cannot be dynamically modified.

**Comment by AskAlexSharov** [comment]
Probably yes. 
- To make it work - you need somehow stop stage_bodies (I advise you create PR with cli flag for this) at given block. stage_bodies.go has next code: `headerProgress, err = stages.GetStageProgress(tx, stages.Headers)` - you need set variable `headerProgress` to any value - stage_bodies will stop there.
- Then if you start such node with parameter --nodiscover - it will not download more blocks, but will process all blocks (produce indices, etc).
- Also you can use Env variable: `STOP_BEFORE_STAGE=Execution`, to stop Erigon before some stage (to later start node with --nodiscover flag).
- Also you will need set correct --prune parameters (i think it must just work).

You can easily test it: build node for early 1M-1.1M blocks range.

**Comment by allada** [comment]
> the data of erigon on archive node on bsc mainnet has reach more than 6T
I have a full sync of BSC on erigon in archive mode, but the data is 4.5TB.

The data is also very compressible, in my case between 2x and 2.5x, so size on disk is around 2.2TB (I use zfs + lz4). This does have some overhead, but not enough to cause issues in my case.

If you would like more info on how I set this up, see: https://github.com/allada/bsc-archive-snapshot
