### ISSUE TITLE
BSC: Ultra-slow stage 5/15 (Block execution)

### ISSUE THREAD

**Issue by kawahwookiee** [ledgerwatch/erigon#3371]
I am running Erigon with the following settings:
`--chain=bsc --datadir=/data/erigon-bsc/node --prune=hrtc`
The current stage has already been running for 3 days straight, and it barely got halfway:
`INFO[01-29|10:07:19.170] [5/15 Execution] Executed blocks         number=7664467 blk/s=5.205 tx/s=1836.131 Mgas/s=303.532 batch="308.55 MiB" alloc="1.46 GiB" sys="17.30 GiB"`

The machine is a 32-core AMD, 128Gb RAM and 4TB NVMe SSD, which is more than able to sync and run BSC + Geth in under 2 days.

Could the sync process be accelerated?

**Comment by AskAlexSharov** [comment]
Is it real disk or cloud one? Raid? FileSystem?

**Comment by kawahwookiee** [comment]
it's a real disk on a Hetzner server.
ext4, no RAID

**Comment by AskAlexSharov** [comment]
Here are some our timings
![BEA9FE44-9CC4-4EB0-A855-B07BB49D9006](https://user-images.githubusercontent.com/46885206/151692694-9ad251ec-ae82-4162-8cec-2b733a3228e6.jpeg)

“ sync and run BSC + Geth in under 2 days.” - you are likely not about archive node. erigon by default is archive

**Comment by kawahwookiee** [comment]
@AskAlexSharov yes, i only use full, not archive nodes. is it possible to turn off the archive mode?

**Comment by AskAlexSharov** [comment]
See —prune flag, but it will only reduce db size, not increase sync speed (because it’s not a snapshot sync).

**Comment by g4bwy** [comment]
> The machine is a 32-core AMD, 128Gb RAM and 4TB NVMe SSD, which is more than able to sync and run BSC + Geth in under 2 days.

for a fair comparison, you should use ```--syncmode full``` with geth. my guess is even a non-archive sync in this mode would take much longer than erigon.
