### ISSUE TITLE
Add BOR consensus engine to Erigon for Polygon chain support (Call for Community)

### ISSUE THREAD

**Issue by Uttam-Singhh** [ledgerwatch/erigon#3384]
We at Polygon have tried creating a **TurboBor** client similar to Erigon by implementing Bor consensus in the Erigon fork - https://github.com/maticnetwork/turbo-bor
As of now it only supports Syncing and RPC Calls, Mining is not supported yet and it is only available on Testnet (Mumbai) right now (Mainnet testing is in the process).

Now we are proposing to **Add Bor Consensus Engine to the official Erigon codebase which can support the Polygon chain.** 

**We would appreciate if developers from Erigon, Polygon, or any other community would take a look at what we've done so far and would help us to implement Bor Consensus Engine to Erigon’s official codebase and create a PR for the same.**

We believe that together with community collaboration we can achieve our goal quickly and constructively.

**References:**
TurboBor - [https://github.com/maticnetwork/turbo-bor](https://github.com/maticnetwork/turbo-bor)
PR which implements Bor Consensus to Erigon Folk - [https://github.com/maticnetwork/turbo-bor/pull/1](https://github.com/maticnetwork/turbo-bor/pull/1)
About TurboBor - [https://github.com/maticnetwork/turbo-bor/blob/master/README.md](https://github.com/maticnetwork/turbo-bor/blob/master/README.md)

**Comment by AskAlexSharov** [comment]
PR merged: https://github.com/ledgerwatch/erigon/pull/3449

**Comment by 0xKrishna** [comment]
Awesome work guys, Really appreciate this. I will check out the implementation today.
