### ISSUE TITLE
Number of active Erigon Nodes

### ISSUE THREAD

**Issue by 70nyIT** [ledgerwatch/erigon#3401]
This can be flagged as a question, not an issue!

I've been following this project since a while, seeing it growing (and changing its name!)

I'm now curious: do we know how many Mainnet Ethereum nodes are running Erigon as of now? And how many of them are Archive nodes? Or is there a stat of how many git clone or release downloads are performed on a weekly or monthly base?

Thanks for satisfying my curiosity! 🙂

**Comment by darkhorse-spb** [comment]
https://www.ethernodes.org/

**Comment by 70nyIT** [comment]
Thanks for the link @darkhorse-spb ! Didn't expect that number. Does that stat includes all the running nodes or does it includes only public nodes? I was expecting more than 5k Ethereum nodes all around the globe, something like 40k or close.
Like I have one archive node. It's private, as I personally use it. Is that included in that stat?

**Comment by AskAlexSharov** [comment]
We are not developers of ethernodes.org and it’s closed source - we don’t know how it works.

**Comment by 70nyIT** [comment]
Yes, makes sense, and thanks again for your answer. Can we maybe guess it from the number of git clone that happens on a daily basis? If you have this number, I cannot find in github stats.

**Comment by 70nyIT** [comment]
**Update:**
Not all the nodes are tracked. If I see https://ethernodes.org/nodes  and I search for my Archive Node, I don't see it. Just as an extra info

**Comment by AndreaLanfranchi** [comment]
@70nyIT there are a few points about that 

- as @AskAlexSharov mentioned we don't have the exact info about how ethernodes works nevertheless ...
- it takes time for a node to be "discovered" (a good rule of thumb is to be active for at least 36 hours straight) and ...
- if you want to be tracked your node must be "public" ie you have to expose it on the internet which means you could be used also as a source to download blocks

**Comment by AskAlexSharov** [comment]
400 clones /day, 100 unique clones/day
<img width="917" alt="Screen Shot 2022-02-03 at 18 58 12" src="https://user-images.githubusercontent.com/46885206/152338642-aee4f272-a36f-4776-972c-5f14d7788caa.png">

**Comment by 70nyIT** [comment]
Thank you so much! This gives a better view to the whole community about how this project is being adopted.
