### ISSUE TITLE
rpcdaemon - no logs subscription in eth namespace

### ISSUE THREAD

**Issue by radian-rgc** [ledgerwatch/erigon#3420]
#### System information

Erigon version: `2021.11.3-alpha`

OS & Version: Linux

**erigon command:**

`./build/bin/erigon --chain bsc --prune=hrtc --prune.h.older=3000000 --prune.r.older=3000000 --prune.t.older=3000000 --prune.c.older=3000000 --datadir dexpool`

**rpcdaemon command:**

`./build/bin/rpcdaemon --datadir=dexpool --private.api.addr=127.0.0.1:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --ws `

erigon  is working fine, but i giving **no logs subscription in eth namespace** in rpcdaemon for every request from web3

![dexpool](https://user-images.githubusercontent.com/23151404/152448424-b4112f5f-f222-461a-807a-7fada6c0091e.png)

**Comment by AskAlexSharov** [comment]
Maybe will add support soon: https://github.com/ledgerwatch/erigon/pull/3344
