### ISSUE TITLE
eth_getTransaction not retrieving txpool transactions

### ISSUE THREAD

**Issue by mine-27** [ledgerwatch/erigon#3429]
#### System information

Erigon version: `erigon version 2022.99.99-dev

OS & Version: Linux

Commit hash : 

#### Expected behaviour
When trying to retrieve a transaction by its transaction hash, and that transaction is a pending transaction provided by the rpcdaemon, the transaction details should be returned.

#### Actual behaviour
Pending transaction subscription works properly and provides a continuous flow of pending transactions, but all calls to eth_getTransaction are returning null.

#### Steps to reproduce the behaviour
`web3.eth.subscribe('pendingTransactions')
.on('connected', function(subscriptionId){
    console.log("ReConnect at:", Utils.getTime(), subscriptionId);
})
.on('data', (txHash) => {
    setTimeout(async ()=>{
        try{
            let tx = await web3.eth.getTransaction(txHash);
            console.log(txHash,tx);
        }
        catch(err){
            console.log(err);
        }
    });
})
.on('error', function(error, receipt) { 
    console.log(error, receipt);
});`

You should see a lot of transaction hashes, but only null values for the `web3.eth.getTransaction(txHash)` call.

**Comment by sragss** [comment]
I have this issue as well at the same version. I believe `eth_getTransactionByHash` is using block_reader.go for `TxnLookup()` rather than eth_backend.go. IIRC block_reader should only be used during sync and not during up-to-date execution. Lookups are failing because its looking through the blocks db which pending txs do not exist in.

**Comment by AskAlexSharov** [comment]
@sragss @mine-27 , hi. Here is the fix: https://github.com/ledgerwatch/erigon/pull/3463
Help me to test it plz

**Comment by mine-27** [comment]
Ok, i need to sync to the highest block before giving you feedback

**Comment by sragss** [comment]
@AskAlexSharov Yup works on local and mainnet. Thanks!
