### ISSUE TITLE
RPC daemon fails to start when erigon runs with --txpool.disable

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#3444]
#### System information

Erigon version: devel v2022.02.01
OS & Version: Linux debian
Commit hash : 2cc49f454ffecd9e17d5b04c1cd68b393cd0bbe7

#### Expected behaviour
RPC daemon runs normally when erigon runs with --txpool.disable argument. This was the case before the extrnal txpool update. I don't need the txpool and would like to keep it disabled.
`erigon --txpool.disable --datadir /erigon --maxpeers 25 --ethash.dagdir /erigon/erigon-ethash --port 30305 --private.api.addr=localhost:9090`
`rpcdaemon --datadir /erigon --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace --txpool.api.addr=localhost:9090 --http.addr 192.168.1.2 --http.port 8650 --ws`
Same thing happens without the `--txpool.api.addr=localhost:9090` argument on rpcdaemon

#### Actual behaviour
RPC daemon crashes
```
DB schemas compatible                    reader=5.0.0 database=5.0.0
rpc filters: subscribing to Erigon events
HTTP endpoint opened                     url=192.168.1.2:8650 ws=true ws.compression=false grpc=false
rpc filters: error subscribing to pending transactions err="rpc error: code = Unimplemented desc = unknown service txpool.Txpool"
interfaces compatible                    remote_db= client=5.1.0 server=5.1.0
interfaces compatible                    remote_service=eth_backend client=3.0.0 server=3.0.0
interfaces compatible                    remote_service=mining client=1.0.0 server=1.0.0
ensure version                           remote_service=tx_pool error="rpc error: code = Unimplemented desc = unknown service txpool.Txpool"
Exiting...
RPC server shutting down
```

**Comment by AskAlexSharov** [comment]
@geomad - it's happening because: 
-  `localhost:9090` - has real GRPC server (Erigon's private API)
- `--txpool.disable` - this flag means "don't start any TxPool-related functionality inside Erigon, I will run TxPool as individual process". So, Erigon doesn't serve txpool api's on `localhost:9090` in this case. 
-  But in RPCDaemon you set `--txpool.api.addr=localhost:9090` - RPCDaemon connecting to Erigon, asking "do you have TxPool API?" and Erigon says "Nope" (`unknown service txpool.Txpool`)
- What you need to do: change `--txpool.api.addr=localhost:9090` to another port (by agreement it's 9094). RPCDaemon then will try to connect there (in background, non-blocking) until success. 
- You can start or not start (up to you) external TxPool on `9094` port https://github.com/ledgerwatch/erigon/tree/devel/cmd/txpool#external-mode


I'm happy to make it more user-friendly - but don't know how yet - feel free to advise

**Comment by AskAlexSharov** [comment]
“ let the rpc daemon trying to connect to localhost:9090 TxPool Api if it can't find it at the time, without throwing any errors - Just print a warning to let the user know about it” - this is exactly what happened to you here.


“ removing it would mean I don't want to connect there right?” - no, default value is localhost:9090

**Comment by geomad** [comment]
@AskAlexSharov
“ - this is exactly what happened to you here.” 
It's not - the Rpc Daemon exited after the error, so it could not serve any other requests, and my systemd service went into a restarting loop.
The daemon should display that message, but otherwise operate normally for the rest of the services that got detected.

**Comment by AskAlexSharov** [comment]
@geomad 
What if:
- There will be no warning in the beginning 
- But all txpool calls will return "TxPool Disabled" error
?

It will: 1. allow rpcdaemon to start without problems, 2. allow enable txpool inside Erigon without rpcdaemon restart 3. methods like eth_getTransactionByHash will work well, if pass there pending hash it will return error "TxPool Disabled"

**Comment by geomad** [comment]
@AskAlexSharov this sounds perfect!

**Comment by AskAlexSharov** [comment]
ok, done https://github.com/ledgerwatch/erigon/pull/3485

**Comment by geomad** [comment]
@AskAlexSharov looks like the issue persists (commit dffcc57ecc7fa64ea207cc9075a29e8874669327). Rpc daemon exits when tx pools is disabled and txpool.api.addr argument is not provided
```
DB schemas compatible                    reader=5.0.0 database=5.0.0
database closed                          label=consensus
rpc filters: subscribing to Erigon events
HTTP endpoint opened                     url=192.168.1.2:8650 ws=true ws.compression=false grpc=false
rpc filters: error subscribing to pending transactions err="rpc error: code = Unknown desc = TxPool Disabled"
interfaces compatible                    remote_db= client=5.1.0 server=5.1.0
interfaces compatible                    remote_service=eth_backend client=3.0.0 server=3.0.0
interfaces compatible                    remote_service=mining client=1.0.0 server=1.0.0
ensure version                           remote_service=tx_pool error="rpc error: code = Unknown desc = TxPool Disabled"
Exiting...
RPC server shutting down
HTTP endpoint closed                     url=192.168.1.2:8650
database closed                          label=consensus
database closed                          label=chaindata
```

**Comment by geomad** [comment]
@AskAlexSharov not sure if the above was attempted to be fixed in the commit e74b9ef9ffea340798c9c6ca439e707efa444cbf (since I saw some revelant commits and release notes) but the issue still persists. Rpc log same as above.

**Comment by AskAlexSharov** [comment]
Ok, i will re-check release

**Comment by AskAlexSharov** [comment]
Yes, I missed one corner-case. Fixed by https://github.com/ledgerwatch/erigon/pull/3540
