### ISSUE TITLE
Execution Stage - BSC - Execution failed block=14773589

### ISSUE THREAD

**Issue by perfectcircle2020** [ledgerwatch/erigon#3474]
#### System information

Erigon version: `erigon version 2022.99.99-dev `

OS & Version: Windows/Linux/OSX

Commit hash : 

#### Actual behaviour

Execution failed        block=14773589 hash=0xa3eb0e6df5911def7f55d529ff19be6b355e89225a0e0c47ecd311c40d3ed038 

#### Backtrace

````
INFO[02-10|23:00:23.166] Flushed buffer file                      name=/home/geth/erigon/bsc-mainnet/etl-temp/erigon-sortable-buf-2316338324 alloc="358.4 MiB" sys="4.0 GiB"INFO[02-10|23:00:38.547] [p2p] GoodPeers                          eth66=51
INFO[02-10|23:00:53.177] [5/16 Senders] ETL [2/2] Loading         into=TxSender block=14995021 alloc="196.2 MiB" sys="4.0 GiB"
INFO[02-10|23:01:23.176] [5/16 Senders] ETL [2/2] Loading         into=TxSender block=15109201 alloc="160.3 MiB" sys="4.0 GiB"
INFO[02-10|23:01:34.383] [5/16 Senders] etl: temp files removed   total size="1.3 GB"
INFO[02-10|23:01:36.307] [5/16 Senders] DONE                      in=10m44.751131232s
INFO[02-10|23:01:36.308] [6/16 Execution] Blocks execution        from=14773588 to=15144978
EROR[02-10|23:01:36.858] [6/16 Execution] Execution failed        block=14773589 hash=0xa3eb0e6df5911def7f55d529ff19be6b355e89225a0e0c47ecd311c40d3ed038 error="expected system tx (hash 0x0fb2ea58ae7605beead1560046cad4c9643c70d5871d0fd02330e3e0eb06b513, nonce 724977, to 0x0000000000000000000000000000000000001000, value 0x2dd7f260ccbe84c, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000685b1ded8013785d6623cc18d214320b6bb64759), actual tx (hash 0x5b00edd23604759f6b6d26e26da8c54bb5135b52f8fb39e5a1d3bf4a4d31bb84, nonce 724977, to 0x0000000000000000000000000000000000001000, value 0x2dd7f40d354a64c, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000685b1ded8013785d6623cc18d214320b6bb64759)"
INFO[02-10|23:01:36.858] UnwindTo                                 block=14773588 bad_block_hash=0xa3eb0e6df5911def7f55d529ff19be6b355e89225a0e0c47ecd311c40d3ed038
INFO[02-10|23:01:36.858] [6/16 Execution] Completed on            block=14773588
<^CINFO[02-10|23:02:01.435] Got interrupt, shutting down...
````

**Comment by perfectcircle2020** [comment]
This is the correct transaction actually for block [14773589](https://bscscan.com/block/14773589)

https://bscscan.com/tx/0x15e31623244ad215532d8931b01d1f4128cc2beaac517e108740c640f03b4aa4

**Comment by perfectcircle2020** [comment]
@AlexeyAkhunov  @AskAlexSharov  Can somebody tell me where is the problem? 

Which portion of the source code is in charge of that?

I know it already happend to one of the first blocks while erigon was still in development for bsc, but cannot find the issue here on github.

**Comment by perfectcircle2020** [comment]
0x2dd7f260ccbe84c  = 206460959329085516
0x2dd7f40d354a64c  = 206461074329085516

Correct value from bscscan is -> 206461074329085516

**Comment by perfectcircle2020** [comment]
I hacked my way in parlia.go and added the following lines: 

`
if header.Number == big.NewInt(14773589) {
value = uint256.NewInt(0x2dd7f40d354a64c)
}
`

but there is a problem sowhere else evidently

**Comment by nikolinsko** [comment]
Hey,

not sure if this will work or help your use case. I experienced unwinds after which i was stuck on a block. 

I reset to this commit:

https://github.com/ledgerwatch/erigon/commit/bb8a17e422b24390fbbdc1cddd9be8da3ac59201

and it seems to be working again, but i only need mempool and current block data for my use case.

seems like you need to resync after this commit for bsc: https://github.com/ledgerwatch/erigon/commit/2cc49f454ffecd9e17d5b04c1cd68b393cd0bbe7

**Comment by perfectcircle2020** [comment]
@nikolinsko Hey man thanks for reaching out! 

I knew something was going on I was not aware of, thank you for pointing out.

I also wanted to know whats the size of your database at the moment?

**Comment by nikolinsko** [comment]
somewhere around 1.4T but im only keeping the latest 10k blocks

**Comment by perfectcircle2020** [comment]
Unfortunatelly it happened again: 

EROR[02-17|06:41:17.030] [6/16 Execution] Execution failed        block=7192418 hash=0x6be58555b813340c2f5e449fff71f4be2654434f3d395eb7a70eeba96fb21916 error="expected system 
tx (hash 0x1f1adba6cf72635eb9c8c82575236fd84a570781618e7c5b8b94879372b83c23, 
nonce 60874, to 0x0000000000000000000000000000000000001002, 
value 0x28973dfb63acac,
gas 9223372036854775807, 
gasPrice 0x0, data ), 
actual tx (
hash 0x603a5ed9ca59eb10bd1d24a76cfb6d897bca7ee7ffe4b473e95db3b079534b2e, 
nonce 60874,
 to 0x0000000000000000000000000000000000001002, 
value 0x288f97313cf74c, 
gas 9223372036854775807, gasPrice 0x0, data )"                                                                                           INFO[02-17|06:41:17.030] UnwindTo                                 
block=7192417 bad_block_hash=0x6be58555b813340c2f5e449fff71f4be2654434f3d395eb7a70eeba96fb21916    

INFO[02-17|08:32:42.855] Build info                               git_branch=devel git_tag=v2022.02.02 git_commit=b3905fb659570b56c389a56e33be59cab034d7bb

**Comment by perfectcircle2020** [comment]
@nikolinsko Hey man would you create a torrent of your database, and share it somehow?

**Comment by nikolinsko** [comment]
Hello,

my database seems to be corrupted too and i wouldnt be able to fit the torrent on the hard drive.

**Comment by perfectcircle2020** [comment]
@nikolinsko yeah, it doesnt work its blocked at block 7192418

**Comment by AlexeyAkhunov** [comment]
> @nikolinsko yeah, it doesnt work its blocked at block 7192418

I am almost there, currently on the block 7m

**Comment by perfectcircle2020** [comment]
@AlexeyAkhunov great
