### ISSUE TITLE
Fatal: ChainDB name is not recognized: bsc

### ISSUE THREAD

**Issue by mine-27** [ledgerwatch/erigon#3475]
#### System information

erigon version 2022.02.2-beta

OS & Version: Linux

`./build/bin/erigon --datadir /home/erigon-data --chain bsc --prune=hrtc  --maxpeers 300`

INFO[02-11|10:37:02.729] Build info                               git_branch= git_tag= git_commit=
INFO[02-11|10:37:02.729] Starting Erigon on                       devnet=bsc
INFO[02-11|10:37:02.730] Maximum peer count                       ETH=300 total=300
INFO[02-11|10:37:02.730] Set global gas cap                       cap=50000000
Fatal: ChainDB name is not recognized: bsc

**Comment by AskAlexSharov** [comment]
BSC support is only in “devel” branch for now
