### ISSUE TITLE
The first parameter of `eth_callBundle` is wrong

### ISSUE THREAD

**Issue by zzh1996** [ledgerwatch/erigon#3487]
#### System information

Erigon version: [2022.02.02-beta](https://github.com/ledgerwatch/erigon/releases/tag/v2022.02.02)

OS & Version: Linux

Commit hash : 

#### Expected behaviour

The first parameter of `eth_callBundle` should be a list of raw txs, according to https://docs.flashbots.net/flashbots-auction/miners/mev-geth-spec/v04-rpc

#### Actual behaviour

The first parameter of `eth_callBundle` is a list of tx hashes

#### Backtrace

````
[backtrace]
````

**Comment by monperrus** [comment]
I confirm that erigon's implementation of `eth_callBundle` is not compatible with the flashbots specification.

**Comment by monperrus** [comment]
FTR, a draft fix is 

```go
func (api *APIImpl) CallBundle(ctx context.Context, rawTxs []hexutil.Bytes, stateBlockNumberOrHash rpc.BlockNumberOrHash, timeoutMilliSecondsPtr *int64) (map[string]interface{}, error) {
...
	var txs types.Transactions

	for _, encodedTx := range rawTxs {		
		txn, err := types.DecodeTransaction(rlp.NewStream(bytes.NewReader(encodedTx), uint64(len(encodedTx))))
		if err != nil {
			return nil, err
		}
		txs2 = append(txs2, txn)
	}
```

However, the request cannot be unmarshalled to `[]hexutil.Bytes`, there is more work to be done on a unmarshable input datatype.

**Comment by kushalbabel** [comment]
Hey @monperrus 
It is indeed on purpose back then, as I was using this call to simulate transactions (by their hashes) at a historical state (different state than what they were actually executed on).
The call was never intended to be compatible with the flashbots specification.
Now that flashbots has grown in popularity, I agree that indeed this can cause confusion.
I propose to rename the current `eth_callBundle` to `eth_simulate` and have another implementation for `eth_callBundle`

**Comment by praveenbm5** [comment]
Any updates on this?

Is current eth_callBundle compatible with Flashbots RPC?

**Comment by darkhorse-solution** [comment]
Can you tell me the correct type of eth_callBundle?
Now I am always meet unmarshal object.
