### ISSUE TITLE
`debug_traceCall` not working if gas price is not enough or not set (behavior different from Geth)

### ISSUE THREAD

**Issue by zzh1996** [ledgerwatch/erigon#3494]
Erigon version: 2022.02.02-beta
OS & Version: Linux

Request:

```
curl http://127.0.0.1:8545/ -H "Content-Type: application/json" --data '{
        "method": "debug_traceCall",
        "params" :[
                {
                    "from": "0x0123456789012345678901234567890123456789",
                    "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "data": "0x",
                    "value": "0x0"
                },
                "latest", {"tracer": "callTracer"}
        ],
        "id": 0,
        "jsonrpc": "2.0"
}'
```

Erigon response:

```
{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"tracing failed: fee cap less than block base fee: address 0x0123456789012345678901234567890123456789, gasFeeCap: 0 baseFee: 54337541210"}}
```

Geth response:

```
{"jsonrpc":"2.0","id":0,"result":{"type":"CALL","from":"0x0123456789012345678901234567890123456789","to":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","value":"0x0","gas":"0x2fa9e78","gasUsed":"0xef7","input":"0x","output":"0x"}}
```

**Comment by geomad** [comment]
I think that's done to be consistent with OpenEthereum that handled traces this way. Imo its not ideal though, geths behavior here is better. Would love to see a flag on rpc deamon to mimic geths tracecall.

**Comment by zzh1996** [comment]
> I think that's done to be consistent with OpenEthereum that handled traces this way. Imo its not ideal though, geths behavior here is better. Would love to see a flag on rpc deamon to mimic geths tracecall.

Thanks for your reply. As far as I know, OE does not have this RPC. All OE tracing API starts with `trace_`. `debug_traceCall` is a geth API.

**Comment by quickchase** [comment]
Is anyone having issues using debug_traceCall with archive blocks? I'm getting:
```
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32000,"message":"block 18992271(9c7cb3118bc32a473de8ed2cc98d8a3ba7e616a518db75b2beaa483dc2823809) not found"}}
```
But the block is available via `eth_getBlockByNumber` on `2022.07.3`

This is with BSC Mainnet

**Comment by dwampa** [comment]
Hello Team!
Any updates on this? Would love to see a fix for this.

**Comment by aertoria** [comment]
Hello team, any update on this?
