### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by qkum** [ledgerwatch/erigon#3500]
**Hello, lovely devs.**

**I just want to take advantage of my right to praise you guys for writing Quality Code & Documentation that deserves a medal.**

I like intelligent programmers.

Most are not.

Most do a half-assed job and everybody who has to use the code in the future will get grey hair and waste their life fighting with the horrible code.

Even when they seem to try hard, 9 out of 10 times I'm nearly knocking my head into the table because they fail horribly at something Basic like the Documentation or --help explanations. 

That takes no brain to write. (where their true intelligence shows, in not giving a flying F about the basics! - Idiots)

I would rather not have them share their code than share it without proper, Updated, Documentation & Code comments.

Or at least write something like this on the first line **"We hate everybody who is new to programming and wish you to go to hell. That is why we assume you are a pro with 10+ years of experience in our code & documentation"** 

You guys & gals deserve a medal for the code, documentation, and improving the Ethereum Codebase in a serious way 🏆

**Comment by AskAlexSharov** [comment]
thanks you. 
we don't really like finger-pointing and saying bad words about others. 
anyway thank you for feedback
