### ISSUE TITLE
Readonly nodes

### ISSUE THREAD

**Issue by BirdyUK** [ledgerwatch/erigon#3505]
Hi,

Is it possible and reliable to create a ready only node from the datadir? My theory behind this would be to create a Kubernetes Persistent Volume that one or many pods can read from but not write to for redundancy.

I believe trying to create multiple erigon instances would attempt to write new blocks to the dataset thus throws an error stating the datadir is already in use.

What would be a the best solution to create read only nodes from the main dataset?

Thanks

**Comment by AskAlexSharov** [comment]
1. Erigon's flags: --nodiscover --txpool.disable
2. On 1 datadir can start 1 Erigon and multiple RPCDaemon's if need (it opens db in ReadOnly mode).

**Comment by BirdyUK** [comment]
So to have multiple read-only instances, all one needs is multiple RPCDaemon's?

My theory behind this is something like this... (Just a basic diagram.. in reality it will be a k8 cluster)

1) Erigon ingests data to the Datadir
2) Multiple RPCDaemon's read from the datadir and traffic is distributed over a Load balancer / proxy to the available RPC pods

<img src="https://i.ibb.co/cw6WF6C/erigon-flow.png" />

Does that sound reasonable to you?

PS: Thanks for doing an amazing job with erigon, i am currently using it for both eth and bsc full archive nodes, you should consider allowing funding to support the project :-)

**Comment by AskAlexSharov** [comment]
Yes. It must cover 99% of cases. 

And if RPCDaemons will have access to same datadir - they will share same OS’s PageCache.

But they mush have different PID: https://github.com/ledgerwatch/erigon/blob/3655f9e629c4e7c4613425582cadb2812298c292/docker-compose.yml#L50
