### ISSUE TITLE
Fatal: ChainDB name is not recognized: bsc

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#3523]
command:`/root/bsc-arch/erigon --chain bsc --datadir /root/bsc-arch/node --private.api.addr 0.0.0.0:10086`

err log:
[INFO] [02-16|16:46:51.719] Build info                               git_branch= git_tag= git_commit=
[INFO] [02-16|16:46:51.719] Starting Erigon on                       devnet=bsc
[INFO] [02-16|16:46:51.720] Maximum peer count                       ETH=100 total=100
[INFO] [02-16|16:46:51.721] Set global gas cap                       cap=50000000
Fatal: ChainDB name is not recognized: bsc

**Comment by AskAlexSharov** [comment]
bsc support is in "devel" branch only for now

**Comment by kugimiya530** [comment]
> bsc support is in "devel" branch only for now

what is devel branch....

**Comment by AskAlexSharov** [comment]
```
git checkout devel
git pull
make all
```

**Comment by kugimiya530** [comment]
sorry but it's confuse me ,   you mean git this repo then  
excute

git checkout devel
git pull
make all

but it's show 

# git checkout devel
fatal: not a git repository (or any of the parent directories): .git

**Comment by AskAlexSharov** [comment]
I know nothing about your setup. Give me more info.

**Comment by kugimiya530** [comment]
hi.. i am on ubuntu 20

i know how to using geth and their command flag

but  erigon i stuck at first step

i don't even know how to switch the devel branch

try to download this repo  and  excute your command but fail

can u kindly give me detail command to start erigon (devel branch bsc)

**Comment by AndreaLanfranchi** [comment]
Following the Getting Started in our Readme you only need one additional step.
Assuming you're in directory `/home/user`

```
# This will clone the repository in /home/user/erigon
git clone --recurse-submodules -j8 https://github.com/ledgerwatch/erigon.git
#enter the cloned directory
cd erigon
#set the branch devel as current
git checkout devel
#build all erigon's components
make all
```

eventually run
```
/home/user/erigon/build/bin/erigon --chain bsc --datadir /root/bsc-arch/node --private.api.addr 0.0.0.0:10086
```

Warning ! Don't rely too much on your knowledge of geth command line arguments as Erigon has diverged a lot from geth.

**Comment by kugimiya530** [comment]
wow it's work, i am very appreciate your help
due to u say there is alot different between erigon and geth

is  erigon work with config.toml  or  just command

and  where is command list
