### ISSUE TITLE
roadmap of filter_xxx interface

### ISSUE THREAD

**Issue by netquery** [ledgerwatch/erigon#3544]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/51869602/154688337-7a89acc7-8df1-47c1-beb0-f8ebf09e9fef.png">

When will Erigon start adapting the filter-related rpc interface? It seems that this piece has not been updated for a long time. thanks!

**Comment by AlexeyAkhunov** [comment]
When we have some free hands to implement them. Likely after we have added log events support to `eth_subscribe`, which is currently in progress. We would need similar infrastructure for `eth_newFilter`
