### ISSUE TITLE
erigon_getBlockByTimeStamp should accept similar inputs to eth_getBlockByNumber

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#3551]
This is a small issue, so not a high priority, but I wanted to document it.

The new `erigon_getBlockByTimeStamp` is great and very useful, but because it returns the exact same data as `eth_getBlockByNumber` (i.e., the block data) its inputs should behave similarly. The latter accepts a broader range of inputs, as explained by this table:

| Command                            | Input                    | Result        |
| -------------------------- | ---------------- | ------------- |
| eth_getBlockByNumber     | "0xc"                   | valid block data for block 12 |
|                                               | 0xc (no quotes) | parse error |
|                                               | "12"                    | valid block data for block 12 |
|                                               | 12 (no quotes)   | valid block data for block 12 |
|                                               |                             |               |
| erigon_getBlockByTimeStamp | "0xc"             | invalid argument         |
|                                               | 0xc (no quotes)  | error         |
|                                               | "12"                     | invalid argument         |
|                                               | 12 (no quotes)    | valid block data for block 12 |

This happens because of this line (https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/commands/erigon_block.go#L65) which only accepts a `uint64`.

You could accept an `rpc.blockNumber` or perhaps, better yet, `rpc.timeStamp` (which may not exist, but could be created and should behave identically).

Here's the test cases:

```
curl --data '{"method":"eth_getBlockByNumber","params":["0xc", false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"eth_getBlockByNumber","params":[0xc,   false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"eth_getBlockByNumber","params":["12",  false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"eth_getBlockByNumber","params":[12,    false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"erigon_getBlockByTimeStamp","params":["0xc", false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"erigon_getBlockByTimeStamp","params":[0xc,   false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"erigon_getBlockByTimeStamp","params":["12",  false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
curl --data '{"method":"erigon_getBlockByTimeStamp","params":[12,    false],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```

Tagging: @enriavil1

**Comment by enriavil1** [comment]
I have added so now we have a rpc.Timestamp
