### ISSUE TITLE
Panic: send on closed channel - TxPool error

### ISSUE THREAD

**Issue by AliakseiMalyshau** [ledgerwatch/erigon#3559]
#### System information

Erigon version: `v2022.02.03` (running in Docker via Docker Compose)

OS & Version: Linux Ubuntu 20.04 LTS (4 vCPU / 16GB RAM / 2 TB SSD)

Commit hash :  [227bb73](https://github.com/ledgerwatch/erigon/commit/227bb7368937ba408da82fddcacc02d27153d4fe)

#### Expected behaviour

Erigon service is running without any errors.

#### Actual behaviour

Sometime Erigon service restart with next error:

```
[INFO] [02-20|23:03:07.068] [txpool] stat                            block=14245821 pending=988 baseFee=30000 queued=30000 alloc_mb=1329 sys_mb=1761
panic: send on closed channel

goroutine 3306407 [running]:
github.com/ledgerwatch/erigon/cmd/sentry/download.(*PeerInfo).Async(0xc0234429a0, 0xc020baca50)
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:135 +0xff
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).writePeer(0xc0001e0b40, {0x1184852, 0x10}, 0xc0234429a0, 0x8, {0xc03cae9f50, 0x22, 0x22}, 0x0)
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:662 +0x112
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).SendMessageToAll.func1({0xc03e554d00, 0x40}, 0xc03c1309c0)
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:830 +0x66
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).rangePeers.func1({0xfdc320, 0xc05010be70}, {0x10e84e0, 0xc0234429a0})
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:637 +0x62
sync.(*Map).Range(0x436947, 0xc035e82bb8)
	sync/map.go:346 +0x2aa
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).rangePeers(0x1023360, 0xc000308690)
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:631 +0x3d
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).SendMessageToAll(0xc0001e0b40, {0x10, 0xfe18c0}, 0xc04fadf2c0)
	github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:829 +0x17e
github.com/ledgerwatch/erigon-lib/direct.(*SentryClientDirect).SendMessageToAll(0xc03cd3af40, {0x1c897d8, 0xc000501800}, 0x0, {0xc000501800, 0x0, 0x0})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220212095410-fa2dc4720eb0/direct/sentry_client.go:186 +0x2c
github.com/ledgerwatch/erigon-lib/txpool.(*Send).AnnouncePooledTxs(0xc000501ac0, {0xc03cd3af40, 0x20, 0x20})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220212095410-fa2dc4720eb0/txpool/send.go:141 +0x352
github.com/ledgerwatch/erigon-lib/txpool.MainLoop.func1()
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220212095410-fa2dc4720eb0/txpool/pool.go:1389 +0x97a
created by github.com/ledgerwatch/erigon-lib/txpool.MainLoop
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220212095410-fa2dc4720eb0/txpool/pool.go:1327 +0x8a5
```

Running commands:

- Erigon: `erigon --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 --datadir=/home/erigon/data --private.api.addr=0.0.0.0:9090`
- Rpcdaemon: `rpcdaemon --datadir=/home/erigon/data --private.api.addr=0.0.0.0:9090 --txpool.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,web3,net,debug,trace,txpool --ws`

#### Steps to reproduce the behaviour

1. Run Erigon service via Docker Compose
2. Waiting at least 1 -2 days (note: **node already synced**)
3. Have an error

#### Backtrace

* 21.02.2021 - Erigon service was restarted and works correctly

**Comment by AskAlexSharov** [comment]
thank you. here is the fix: https://github.com/ledgerwatch/erigon/pull/3568

**Comment by AliakseiMalyshau** [comment]
@AskAlexSharov hello! Thank you! So if my understanding is correct this changes will implement in `stable` and `devel` images, right?

Thanks!

**Comment by AskAlexSharov** [comment]
Yes

**Comment by AliakseiMalyshau** [comment]
Okay so what about `v2022.02.03`? This fix will be in next versions? @AskAlexSharov

**Comment by AskAlexSharov** [comment]
`Okay so what about v2022.02.03?` - tags must be immutable. you can use latest `stable` branch, or wait for next release (every Thursday).

**Comment by AliakseiMalyshau** [comment]
@AskAlexSharov understood! Thank you!
