### ISSUE TITLE
what's the difference between GlobalBaseFeeQueue and GlobalQueue?

### ISSUE THREAD

**Issue by netquery** [ledgerwatch/erigon#3565]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/51869602/155004698-3ab0c7f9-a7a0-45b4-a5f2-af803593a385.png">

**Comment by AskAlexSharov** [comment]
Can read here: https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design#changes-for-eip-1559
