### ISSUE TITLE
Documentation discrepancy: `debug_traceBlockByNumber` support

### ISSUE THREAD

**Issue by pjoshi751** [ledgerwatch/erigon#3605]
The documentation here says `debug_traceBlockByNumber` is supported:

https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md

However, when I tried, I got this error: `"the method debug_traceBlockByNumber does not exist/is not available"`.

I also see an open issue suggesting it is not yet implemented:

https://github.com/ledgerwatch/erigon/issues/3080

**Comment by AlexeyAkhunov** [comment]
Which version of the code you are using? This has been added recently to `devel` branch, and only got into beta release today

**Comment by pjoshi751** [comment]
Thanks @AlexeyAkhunov.  When are we likely to release this?

**Comment by pjoshi751** [comment]
This is working in latest beta version.
