### ISSUE TITLE
[QUESTION] Subscription to events coming from private api GRPC

### ISSUE THREAD

**Issue by perfectcircle2020** [ledgerwatch/erigon#3629]
Hello,

I have question regarding the publish/subscription model in erigon using GRPC.

I see in this file `eth/filters/filter_system.go` there is a list of possible events a client can subscribe to.

Are these events accesible from the private GRPC api? 

If so how to access them?

Thank you

**Comment by AskAlexSharov** [comment]
All grpc interfaces are here https://github.com/ledgerwatch/interfaces
 
 In Erigon “private api” - it’s grpc server. It supports reflection - means you can explore it.

Also Erigon has txpool grpc server (see —txpool.api.addr). 

If run Sentry as independent process - it also will have own grpc server.

**Comment by perfectcircle2020** [comment]
@AskAlexSharov  Thank you for pointing this out, I've been looking for these for a long time
