### ISSUE TITLE
Difference between RPC response from Erigon and Nethermind

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#3630]
#### System information

Erigon version: `./erigon --version`

```
erigon version 2022.99.99-dev
commit 0cac29d1d2021562722dd6dec5d36f170d5a0a84 (HEAD -> devel, origin/devel, origin/HEAD)
Author: Alex Sharov <AskAlexSharov@gmail.com>
Date:   Sat Feb 26 19:55:17 2022 +0700
```

OS & Version: Windows/Linux/OSX

Linux

Commit hash : 

commit 0cac29d1d2021562722dd6dec5d36f170d5a0a84 (HEAD -> devel, origin/devel, origin/HEAD)
Author: Alex Sharov <AskAlexSharov@gmail.com>
Date:   Sat Feb 26 19:55:17 2022 +0700

#### Expected behaviour

Agreement with previous version of Erigon and current version of Nethermind when querying RPC

#### Actual behaviour

Difference -- `eth_getBalance` appears to be off by one block

#### Steps to reproduce the behaviour

Balance at block 0 against Nethermind:

```
curl -s --data '{"method":"eth_getBalance","params":["0x5abfec25f74cd88437631a7731906932776356f9","0x0"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <nethermind RPC>
```

Returns non-zero balance (correct):

```
{
  "jsonrpc": "2.0",
  "result": "0x9d83cc0dfa11177ff8000",
  "id": "1"
}
```

Balance at block 1 against Nethermind:

```
curl -s --data '{"method":"eth_getBalance","params":["0x5abfec25f74cd88437631a7731906932776356f9","0x1"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <nethermind RPC>
```

Returns non-zero balance (correct):

```
{
  "jsonrpc": "2.0",
  "result": "0x9d83cc0dfa11177ff8000",
  "id": "1"
}
```

Balance at block 0 against Erigon:

```
curl -s --data '{"method":"eth_getBalance","params":["0x5abfec25f74cd88437631a7731906932776356f9","0x0"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <erigon RPC>
```

Returns zero balance (**incorrect**):

```
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": "0x0"
}
```

Balance at block 0 against Erigon:

```
curl -s --data '{"method":"eth_getBalance","params":["0x5abfec25f74cd88437631a7731906932776356f9","0x1"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <erigon RPC>
```

Returns non-zero balance (correct):

```
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": "0x9d83cc0dfa11177ff8000"
}
```

#### Backtrace

````
[backtrace]
````

**Comment by tjayrush** [comment]
This show what I think is the same problem, but it points to the possibility that you have an off-by-one error somewhere:

![image](https://user-images.githubusercontent.com/5417918/155897047-37c71ad3-80e7-4598-bc9d-2cf83c1a68bf.png)

**Comment by AlexeyAkhunov** [comment]
Here is the fix: https://github.com/ledgerwatch/erigon/pull/3737

**Comment by tjayrush** [comment]
I can confirm this is now fixed and working as before.
