### ISSUE TITLE
Cannot start downloading new blocks when `--bad.block` is used and goes beyond `persistedLinkLimit`

### ISSUE THREAD

**Issue by allada** [ledgerwatch/erigon#3636]
I maintain an erigon BSC archive node and we were hit by a bug outlined here:
https://github.com/allada/bsc-archive-snapshot/issues/14

In looking for answers that did not require a full resync we found that `--bad.block` should solve our problem by allowing erigon to unwind the changes back to before the bug was found on the chain and then replay from that point onward saving a month+ of resync time.

In doing this, I found that if `Unwind` is called on a block too far back (beyond the `persistedLinkLimit`) erigon gets stuck. I made a hack to get around this issue by adding something like:
```go
if header.Number.Uint64() > 14509999 {
  continue
}
```

to this line https://github.com/ledgerwatch/erigon/blob/f58e80bd56ee449cc31b8dc2eead431890d5b500/turbo/stages/headerdownload/header_algos.go#L546

However, the real problem appears to be that the associated `kv.Headers`'s are not being purged from the database during an unwind.

I will look at making a patch for this, but before I do, I wanted to make sure that deleting the associated `kv.Headers` is the appropriate and safe thing to do.

**Comment by coelho** [comment]
> However, the real problem appears to be that the associated kv.Headers's are not being purged from the database during an unwind.

This is also the case for kv.Bodies & kv.Receipts from Body Downloader. DB corruption will cause Erigon to endlessly retrieve bad blocks, and unwinding does nothing to recover.

This is the issue causing https://github.com/ledgerwatch/erigon/issues/3708 to be unrecoverable.

Problematic line of code: https://github.com/ledgerwatch/erigon/blob/devel/turbo/stages/bodydownload/body_algos.go#L151
If you apply this, Erigon recovers:

```
                                        block = rawdb.ReadBlock(tx, hash, blockNum)
+                                       if block != nil {
+                                               rawdb.DeleteReceipts(tx, blockNum)
+                                               rawdb.DeleteBody(tx, hash, blockNum)
+                                               block = nil
+                                       }
```

If the node _ever_ stops uncleanly this corruption can occur. Sounds high priority?

**Comment by AskAlexSharov** [comment]
"retrieve bad blocks" - what is "bad" block - in your case?

**Comment by AskAlexSharov** [comment]
"appears to be that the associated kv.Headers's are not being purged from the database during an unwind." - why do you need delete them? Are data written to db is incorrect? if yes - do you know why?

**Comment by coelho** [comment]
@AskAlexSharov Correct block number + hash, but incorrect body/receipts. I have not debugged to see what the actual corruption looks like.

There's really two issues here:

1. There is an edge case where if Erigon is stopped uncleanly, it can somehow corrupt body/receipts.

2. When you unwind bodies/headers, you expect to redownload & reprocess them. This isn't the case (you do not redownload) and if there's any DB corruption it doesn't get fixed currently. Currently, it is absolutely impossible (no command exists) to recover from this edge case.

**Comment by AskAlexSharov** [comment]
ah, now I see what you mean.

2. no, because "unwind" it's our mechanism for `reorg` and reorgs must be fast - it's part of consensus stability. No reason to re-download block - because nothing can change inside block, if something changed - it will change hash of block.
1. I have some idea how it can happen... not related to shutdown... let me think...

**Comment by coelho** [comment]
@AskAlexSharov Possibly interim, could I suggest a new command in `integration` that allows people to clear headers/bodies/receipts that are not yet canonical (or are unwound)?

This would allow people at least a path to recover while the main issue is debugged.

**Comment by AskAlexSharov** [comment]
Unwind already does remove receipts: eth/stagedsync/stage_execute.go -> unwindExecutionStage -> DeleteNewerReceipts

Block: 14794507 error `tx count = 276, receipts count = 275`
Block: 14794507 has 276 txs https://bscscan.com/block/14794507 - which is correct - means no reason to delete blocks

**Comment by AskAlexSharov** [comment]
FYI: Receipts are not coming from p2p network - they are generated when block executed.

**Comment by AskAlexSharov** [comment]
So, probably need find why block execution does write 275 receipts(instead of 276): `eth/stagedsync/stage_execute.go -> SpawnExecuteBlocksStage -> executeBlock -> AppendReceipts`

Can re-exec blocks next way:
```
#first unwind to block < 14794507
go run --trimpath  ./cmd/integration state_stages --datadir=<your_datadir> --chain=bsc --integrity.fast=false --unwind=123

#then run forward to block 14794507
go run --trimpath  ./cmd/integration state_stages --datadir=<your_datadir> --chain=bsc --integrity.fast=false --block= 14794507 
```

**Comment by AskAlexSharov** [comment]
"could I suggest a new command in integration that allows users to clear headers/bodies/receipts that are not yet canonical (or are unwound)?" - Added into `stage_header --unwind` https://github.com/ledgerwatch/erigon/pull/3813/ - but if you can help check https://github.com/ledgerwatch/erigon/issues/3636#issuecomment-1086579685 before delete - would be helpful

**Comment by AskAlexSharov** [comment]
done `stage_header --unwind` and `stage_header --reset` (but reset working only in latest devel - found bug there recently).
