### ISSUE TITLE
Support Gnosis Chain (formerly xDai)

### ISSUE THREAD

**Issue by KaiRo-at** [ledgerwatch/erigon#3643]
# Rationale

Currently, the Gnosis Chain (formerly xDai) is supported by two clients: OpenEthereum and Nethermind. OpenEthereum will stop working when The Merge happens, so people should get off it ASAP. On the other side, Nethermind seems to be somewhat of a memory hog and additionally, there should be client diversity, a network should not be in the hands of a single client.
In addition, in https://medium.com/openethereum/gnosis-joins-erigon-formerly-turbo-geth-to-release-next-gen-ethereum-client-c6708dd06dd was touted as the client that all OpenEthereum users should switch to, but for those running a Gnosis Chain node (no matter if a validating or non-validating one), it's not a valid alternative right now.

# Implementation

I know the largest issue there is probably the AuRa consensus algorithm used on that chain right now - even more as it will be replaced by the Beacon Chain consensus (hopefully) in the near future. Still it would be great if we could run Erigon at least in a non-validating form before The Merge so client diversity on that chain could be upheld to some degree.

**Comment by 0xAyanami** [comment]
https://github.com/ledgerwatch/erigon/tree/devel/consensus/aura

PoA mainnet is already supported by erigon

https://github.com/ledgerwatch/erigon/blob/devel/params/config.go#L274

So, adding support for Gnosis Chain wouldn't be a hassle

**Comment by beegmon** [comment]
Bumping this issue as well. We just began node operations on gnosis and having to run openethereum as a backup to nethermind isn't something I want to support longer than I have to. Really looking forward to getting erigon in the mix instead!

**Comment by diwu1989** [comment]
Is anyone able to successfully run & sync to head Erigon for Gnosis XDai?

**Comment by yperbasis** [comment]
Implemented in PRs #4671, #5479, #5487, #5488, #5600, #5617, #5645, #5685, #5700, #5717, #5737, #5783, #5798, #5820, #5873, #5929, #5989, and #5997.
