### ISSUE TITLE
[QUESTION] Execution stage

### ISSUE THREAD

**Issue by perfectcircle2020** [ledgerwatch/erigon#3646]
It's clear to me that this stage cannot be parallelized in anyway to speed it up since each step in the execution phase depends on the previous step, what I am wonderthing tho, maybe there are other possible ways in which a node can sync the state without having to execute all the blocks from scratch.

Can this in any way be done with snapshots ? 

Has this repository something to do with my question? 

https://github.com/ledgerwatch/erigon-snapshot/

@AskAlexSharov

**Comment by AskAlexSharov** [comment]
Hi. Yes, we working on Snapshot sync support. 
Also our snapshots will allow - re-execute blocks with some parallelism. 
But snapshots format is not fully stabilized yet, we changing it periodically. We will announce it "soon".
worh happening in `devel`, here: 
https://github.com/ledgerwatch/erigon/tree/devel/turbo/snapshotsync 
https://github.com/ledgerwatch/erigon/blob/devel/cmd/state/commands/erigon2.go
https://github.com/ledgerwatch/erigon-lib/tree/main/recsplit
https://github.com/ledgerwatch/erigon-lib/tree/main/compress
https://github.com/ledgerwatch/erigon-lib/tree/main/commitment
