### ISSUE TITLE
Allowing ajax requests to prometheus endpoint

### ISSUE THREAD

**Issue by pnowosie** [ledgerwatch/erigon#3660]
# Rationale

We'd like to access prometheus metrics of the node from the browser.

# Implementation

Our naive implementation could be like this: https://github.com/golemfactory/erigon/commit/06a2d7110ebc04aa199e8f04934e01187fafe69f
```
---
 metrics/exp/exp.go | 1 +
 1 file changed, 1 insertion(+)

diff --git a/metrics/exp/exp.go b/metrics/exp/exp.go
index c894dd6ae..977bf1812 100644
--- a/metrics/exp/exp.go
+++ b/metrics/exp/exp.go
@@ -46,6 +46,7 @@ func ExpHandler(r metrics.Registry) http.Handler {
 // This function enables metrics reporting separate from pprof.
 func Setup(address string) {
        http.HandleFunc("/debug/metrics/prometheus", func(w http.ResponseWriter, r *http.Request) {
+               w.Header().Set("Access-Control-Allow-Origin", "*")
                metrics2.WritePrometheus(w, true)
        })
        //m.Handle("/debug/metrics", ExpHandler(metrics.DefaultRegistry))
--
2.35.1
```

> Are you willing to implement this feature?

I'd love to help. However I'm not a golang dev, so if it'd require more changes I'd need some help as well ;)

**Comment by AskAlexSharov** [comment]
ok. adding by: 
devel - https://github.com/ledgerwatch/erigon/pull/3662
stable - https://github.com/ledgerwatch/erigon/pull/3663
