### ISSUE TITLE
REDA RZINI

### ISSUE THREAD

**Issue by Redarzini** [ledgerwatch/erigon#3681]
Hello, I have a problem transferring money. I sent my money from a metamask wallet to a wrong address, and this address belongs to the gnosis chain network. I spoke with metamask support. They told me your money is at the gnosis network.

**Comment by Redarzini** [comment]
And I really want your help. I have no way. I called all metamask support and Smart Chain support and they told me that you should contact the gnosis network

**Comment by AskAlexSharov** [comment]
Hello. 
Sorry, but we are not owning Gnosis network (and as I know - not affiliated). 
Gnosis has their website - you better contact them: https://gnosis.io
