### ISSUE TITLE
Pruning still disabled without --prune flag, even if other prune flags are set

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#3690]
Next set of flags interpreted as "disabled pruning":
`--prune.h.older 10 --prune.r.older 10 --prune.t.older  10 --prune.c.older 10` 
because of no `--prune=hrtc` flag

**Comment by vanphandinh** [comment]
Hello,
I added flags: `--prune.h.before=12525700 --prune.r.before=12525700 --prune.t.before=12525700 --prune.c.before=12525700` but it seems doesn't work. 
Should I need to add `--prune=hrtc`?

**Comment by AskAlexSharov** [comment]
@vanphandinh this is what current issue about

**Comment by vanphandinh** [comment]
> 

Are there any ways to change from `--prune.h.before=12525700 --prune.r.before=12525700 --prune.t.before=12525700 --prune.c.before=12525700` to `--prune=hrtc`?

**Comment by AskAlexSharov** [comment]
We prefer don't give users way to change --prune flags after node creation: because it will lead to unexpected side-effects,  human-mistakes, etc...

**Comment by AskAlexSharov** [comment]
fixed by: https://github.com/ledgerwatch/erigon/pull/4165
