### ISSUE TITLE
mdbx_env_open error when starting Erigon (devel branch)

### ISSUE THREAD

**Issue by GBBx** [ledgerwatch/erigon#3697]
#### System information

Erigon version: `erigon version 2022.99.99-dev`
OS & Version: Linux (kernel: 4.18.0)

Tried to build it twice:
1. Commit hash : `4ee0ae161067a6cc68d85e4032d80fcf91f77fdb` with go 1.17.1.
2. Commit hash: `a0765a8bc4df72931edbeda92a89ee01f4900005` with go 1.17.8.
Both have the same error.

#### Expected behaviour
Erigon can be started.

#### Actual behaviour
Erigon fails to start.

#### Steps to reproduce the behaviour
```
git clone --recurse-submodules -j8 --branch devel https://github.com/ledgerwatch/erigon.git
cd erigon
make erigon
erigon --datadir /data/erigon --chain ropsten --private.api.addr=localhost:9090
```

Changing the chain to e.g. mainnet does not make any difference.

#### Backtrace

````
INFO[03-15|09:53:09.159] Build info                               git_branch=devel git_tag=v2022.02.04 git_commit=4ee0ae161067a6cc68d85e4032d80fcf91f77fdb
INFO[03-15|09:53:09.160] Starting Erigon on Ethereum mainnet...
INFO[03-15|09:53:09.163] Maximum peer count                       ETH=100 total=100
INFO[03-15|09:53:09.163] Set global gas cap                       cap=50000000
INFO[03-15|09:53:09.307] Opening Database                         label=chaindata path=/data/erigon/chaindata
mdbx_env_open:16183 Linux prior to 5.4 requires MDBX_WRITEMAP because of a flaw of unified page/buffer cache. See https://github.com/erthink/libmdbx/issues/269
EROR[03-15|09:53:09.307] Erigon startup                           err="mdbx_env_open: protocol not available, label: chaindata, trace: [kv_mdbx.go:234 node.go:532 node.go:535 backend.go:162 node.go:121 node.go:109 main.go:32 app.go:526 app.go:286 main.go:19 proc.go:255 asm_amd64.s:1581]"
````

**Comment by erthink** [comment]
This is response of a "fuse" to protect against potentially more serious problems.
Please read my [comment](https://github.com/erthink/libmdbx/issues/269#issuecomment-1068214834) for corresponding issue.

**Comment by AskAlexSharov** [comment]
@GBBx likely you have linux 4.9, and there are some technical problems in compatibility with this version yet. my advise: use linux >5.4

**Comment by AskAlexSharov** [comment]
Btw, maybe we can add automatic enabling MDBX_WRITEMAP if see error above.

**Comment by GBBx** [comment]
Thank you. Yes, it works with the new kernel.

**Comment by AskAlexSharov** [comment]
And we are also released fallback to WriteMap on old kernels.

**Comment by p1nox** [comment]
I'm receiving this error when using an nfs4 EFS partition in an AWS instance (https://aws.amazon.com/efs/), on Linux version 5.15.0-1020-aws (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1). Is this also an issue related to the filesystem?
