### ISSUE TITLE
eth_createAccessList returns address '1' that does not lower gas usage

### ISSUE THREAD

**Issue by sunce86** [ledgerwatch/erigon#3698]
`eth_createAccessList` returns access list containing address `1` as storage key. When this access list is used with `eth_call`, gas usage is higher then without using access list. Also, when storage key `1` is removed, gas usage is lower.

#### System information
Erigon version: 2022.02.04-beta

OS & Version: Windows 10

#### Expected behaviour

```
[
            {
                "address": "0x9008d19f58aabd9ed0d60971565aa8510560ab41",
                "storageKeys": [],
            },
            {
                "address": "0x2c4c28ddbdac9c5e7055b4c863b72ea0149d8afe",
                "storageKeys": [
                    "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
                    "0x3e0a6b9ca93e33d18d2a2214f9ba022e0362fbadbdf27cd46f31629229baa68b",
                ],
            },
            {
                "address": "0x9e7ae8bdba9aa346739792d219a808884996db67",
                "storageKeys": [],
            },
        ]
```

#### Actual behaviour

```
[
            {
                "address": "0x9008d19f58aabd9ed0d60971565aa8510560ab41",
                "storageKeys": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                ],
            },
            {
                "address": "0x2c4c28ddbdac9c5e7055b4c863b72ea0149d8afe",
                "storageKeys": [
                    "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
                    "0x3e0a6b9ca93e33d18d2a2214f9ba022e0362fbadbdf27cd46f31629229baa68b",
                ],
            },
            {
                "address": "0x9e7ae8bdba9aa346739792d219a808884996db67",
                "storageKeys": [],
            },
        ]

```
#### Steps to reproduce the behaviour

Call eth_createAccessList() with

`{"jsonrpc":"2.0","method":"eth_createAccessList","params":[{"from":"0xde786877a10dbb7eba25a4da65aecf47654f08ab","to":"0x9008d19f58aabd9ed0d60971565aa8510560ab41","data":"0x13d79a0b000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000003600000000000000000000000000000000000000000000000000000000000000002000000000000000000000000990f341946a3fdb507ae7e52d17851b87168017c000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000041dd01130000000000000000000000000000000000000000000000005f8bd2107584f0580000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e0c0a0b77b83284d048aa29d0fce632e7fd1e90f0000000000000000000000000000000000000000000000005f8bd2107584f058000000000000000000000000000000000000000000000000000000004188d8b70000000000000000000000000000000000000000000000000000000062238035e4d1ab10f2c9ffe7bdd23c315b03f18cff90888d6b2bb5022bacd46ab9cddf2400000000000000000000000000000000000000000000000000b4955c4661a1f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005f8bd2107584f058000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000418aa020b91bdb1a2303dbf07701f206185db8f715b95613e15adf6f5bb0ed02b330437c5bb8932719b6101e118fdefa16823764e72e80e98854ab46eb1046fc7a1b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000def1c0ded9bec7f1a1670819833240f027b25eff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001486af479b200000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000005f8bd2107584f0580000000000000000000000000000000000000000000000000000000041aa6bd200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042990f341946a3fdb507ae7e52d17851b87168017c000bb8c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20001f4a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000000000000869584cd0000000000000000000000009008d19f58aabd9ed0d60971565aa8510560ab410000000000000000000000000000000000000000000000f619d2de2c622379550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}],"id":"1"}`

#### Backtrace

````
[backtrace]
````

**Comment by sunce86** [comment]
Not sure, but might be related to and fix by: https://github.com/ledgerwatch/erigon/pull/3453

**Comment by mandrigin** [comment]
@sunce86 please reopen if still happens
