### ISSUE TITLE
Panic on Ethereum Mainnet

### ISSUE THREAD

**Issue by Brando753** [ledgerwatch/erigon#3702]
#### System information

12th Gen I7 CPU
64 GB DDR4 Ram
16 TB NVMe SSD on ZFS RaidZ1 pool with LZ4 compression

Erigon version: `./erigon --version`: erigon version 2022.99.99-dev

OS & Version:  Debian 11.2 x86-64

Commit hash : identified on 47df98a4992690ca5e9af874f14e3f7088551a91 upgraded to b6f707d8119667f13a069082b432c800def6da3f and after database migration the issue resumed.

#### Expected behaviour

Ethereum mainnet to sync and then stay synced

#### Actual behaviour

Ethereum mainnet syncs, then after a few days starts to panic everytime Erigon runs

#### Steps to reproduce the behaviour

Starting on the hash identified perform a full sync and let the node run for days uninterrupted, CLI to start the sync is:
```
erigon --datadir /zfs_pool/ethereum --private.api.addr=localhost:9091 -port 30303 --chain mainnet --watch-the-burn
```

#### Backtrace

Attached as file, too large to post in body of bug report.
[Erigon-Ethereum-Backtrace.txt](https://github.com/ledgerwatch/erigon/files/8253600/Erigon-Ethereum-Backtrace.txt)

I can make available the datadir of this node to any developers on the Erigon team, reach out to me on Discord and I will provide you a download link (be aware compressed it will still be 500~800 GB).

**Comment by AskAlexSharov** [comment]
1. To exclude hardware problem: use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk
2. If you can - please create coredump by setting GOTRACEBACK=crash (see also https://stackoverflow.com/questions/44430117/go-gotraceback-crash-with-no-core-file ) - and share coredump to us somehow.

**Comment by Brando753** [comment]
Hey Alex, I ran memtest86 about three or four times when I built the computer, it was custom built just for being a blockchain archive node, but I can run it through one more cycle to verify ram issues have not developed. I would be amazed if the issue were with the SSDs since ZFS has been configured in RAIDz1, which has data redundancy; if any drive were failing, it would still be able to fetch the correct data, and it even verifies data after writing. That being said, I will check the state of the drives and report back. Once I finish the me mtest, I will have it run with the core-dump setting.

**Comment by Brando753** [comment]
So much for that, something very well may be wrong with the drives, looks like after running a ZFS scrub some checksums could not be recovered so there is data corruption. Will investigate whats going on if it was bad RAM or bad drives.

```
➜  ~ sudo zpool status -v
  pool: zfs_pool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 00:20:04 with 1 errors on Sun Mar 13 00:44:05 2022
config:

	NAME            STATE     READ WRITE CKSUM
	zfs_pool        ONLINE       0     0     0
	  raidz1-0      ONLINE       0     0     0
	    zfs_pool_1  ONLINE       0     0 16.8K
	    zfs_pool_2  ONLINE       0     0 16.8K
	    zfs_pool_3  ONLINE       0     0 16.8K
	    zfs_pool_4  ONLINE       0     0 16.8K
	    zfs_pool_5  ONLINE       0     0 16.8K
	    zfs_pool_6  ONLINE       0     0 16.8K
	    zfs_pool_7  ONLINE       0     0 16.8K
	    zfs_pool_8  ONLINE       0     0 16.8K

errors: Permanent errors have been detected in the following files:

        /zfs_pool/ethereum/chaindata/mdbx.dat
```
For now I am going to close this bug as its clear the cause may be hardware related.

**Comment by erthink** [comment]
@AskAlexSharov, is this the fourth (or the fifth?) production case of a database damage due to hardware problems?

**Comment by AskAlexSharov** [comment]
@erthink do you mean over all time? or over last week/month?

**Comment by erthink** [comment]
> @erthink do you mean over all time? or over last week/month?

Overall.

**Comment by AskAlexSharov** [comment]
@erthink 
Overall: 6-7. Couple was in Discord, not on github.
