### ISSUE TITLE
Memory Leak on bor mainnet

### ISSUE THREAD

**Issue by Brando753** [ledgerwatch/erigon#3703]
#### System information

12th Gen I7 CPU
64 GB DDR4 Ram
16 TB NVMe SSD on ZFS RaidZ1 pool with LZ4 compression

Erigon version: ./erigon --version: erigon version 2022.99.99-dev

OS & Version: Debian 11.2 x86-64

Commit hash : Initial sync on 47df98a4992690ca5e9af874f14e3f7088551a91 still persists on b6f707d8119667f13a069082b432c800def6da3f

#### Expected behaviour

Bor mainnet (Polygon) would fully sync and stay synced.

#### Actual behaviour

Halfway through the sync erigon starts to blow up in memory usage which results in erigon getting killed by the OOM killer and the process to repeat.

#### Steps to reproduce the behaviour

Attempt to sync a full node running the following command:

erigon --datadir /zfs_pool/polygon --private.api.addr=localhost:9092 --port 30304 --chain bor-mainnet --watch-the-burn

#### Backtrace
Attached as file, too large to post in the body of a bug report.
[Erigon-Bor-Backtrace.txt](https://github.com/ledgerwatch/erigon/files/8253712/Erigon-Bor-Backtrace.txt)

I can make available the datadir of this node to any developers on the Erigon team, reach out to me on Discord and I will provide you a download link (be aware compressed it will still be 500~800 GB).

**Comment by AskAlexSharov** [comment]
likely it's fixed. try on latest "devel"
