### ISSUE TITLE
Insufficient funds check before adding it to the pool

### ISSUE THREAD

**Issue by stickx** [ledgerwatch/erigon#3706]
With EIP-1559 transactions:
if maxFeePerGas * gas > balance it will sit in the txpool forever.

There should be a balance check prior to adding this transaction to the pool.

Maybe turn this on/off with a flag, but default should be on, IMO.

Love your work.

**Comment by AskAlexSharov** [comment]
@stickx Now we have next check: `(gas*tip+value) > balance` do you feel it invalid?

**Comment by stickx** [comment]
Yes, it doesn't seem to check correctly. Tip should be taken into account too of course.

I can provide examples if you wish.

**Comment by AskAlexSharov** [comment]
yes, please. 
FYI: checks are here: https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L686

**Comment by stickx** [comment]
should we be adding a line at 688:
`total.Mul(total, uint256.NewInt(txn.feeCap))`

**Comment by AskAlexSharov** [comment]
maybe, need to think

**Comment by AskAlexSharov** [comment]
hi. i think it's done. feel free to reopen if it's not
