### ISSUE TITLE
need getTransactionReceiptByBlockNumberAndIndex

### ISSUE THREAD

**Issue by microcai** [ledgerwatch/erigon#3740]
# Rationale

getTransactionByBlockNumberAndIndex exist but not for Reciept

getTransactionReceiptByBlockNumberAndIndex can be way faster than getTransactionReceipt if txhash is not hot.
on my setup,  getTransactionByBlockNumberAndIndex returns within 200ms even for old data  but getTransactionByHash will block for over 2 seconds. so for the same reason, getTransactionReceiptByBlockNumberAndIndex should be faster thant getTransactionReceipt.

# solution

provide getTransactionReceiptByBlockNumberAndIndex

**Comment by AskAlexSharov** [comment]
"getTransaction will block for over 2 seconds" - we don't have "getTransaction" method. Which API method is slow for you?

**Comment by microcai** [comment]
> "getTransaction will block for over 2 seconds" - we don't have "getTransaction" method. Which API method is slow for you?

updated
