### ISSUE TITLE
docker image git_tag string is one release behind

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#3779]
#### System information

```
erigon_1              | [INFO] [03-27|13:48:21.193] Build info                               git_branch=stable git_tag=v2022.03.01 git_commit=997846fc4fb3fc99856679aa7407cad644cbc34b
```

The commit matches v2022.03.02, but the tag reported is v2022.03.01. This is likely a CI/CD artefact when creating the docker images.

Version output is correct:
```
ubuntu@btc-a:~/prater-lh$ docker run --rm erigon:local --version
Unable to determine eth deposit contract, running without prune.r.before
erigon version 2022.03.2-beta
```

**Comment by AskAlexSharov** [comment]
we using now `git describe --tags `git rev-list --tags="v*" --max-count=1`
@yorickdowne do you know better way to get tag?

**Comment by AskAlexSharov** [comment]
maybe this will help https://github.com/ledgerwatch/erigon/pull/3780

**Comment by erthink** [comment]
The `git rev-list --tags` does not guarantee any order of tags. So there is no guarantee the nearest tag will be used.

For modern (i.e. non outdated) git I prefer the `git describe --tags --long --dirty=-dirty "--match=v[0-9]*"`.

**Comment by AskAlexSharov** [comment]
Thank you. 
We changed that thing many times and never happy. 
I will give it a try.

**Comment by battlmonstr** [comment]
@AskAlexSharov this could have been fixed by #4212, but how can I verify? I see that somebody/something uploads the images here: https://hub.docker.com/r/thorax/erigon/tags with tags "alpha", "stable", "devel", "latest" and various version tags. Yet the "docker" task in ci.yml is just building an image, but not pushing it. I wonder what is pushing the images and how is it set up? Can I get access there?

**Comment by battlmonstr** [comment]
@AskAlexSharov thanks for explanation.

Verified locally:
```
$ git tag v2022.05.23
$ git describe --tags --dirty
v2022.05.23
$ make erigon
...
$ ./build/bin/erigon 
INFO[05-23|16:10:35.090] Build info git_branch=httphealth git_tag=v2022.05.23 git_commit=a99dfade5c150b2659cc4291bf5ea176415fd77a
```

Backported the fix to stable:
https://github.com/ledgerwatch/erigon/pull/4239

**Comment by mandrigin** [comment]
looks fixed to me, feel free to reopen if not
