### ISSUE TITLE
trace_filter API call fails with ReadCanonicalHash error

### ISSUE THREAD

**Issue by YordanPavlov** [ledgerwatch/erigon#3789]
#### System information

Erigon version:  2021.12.2-beta
OS & Version: A Docker image: thorax/erigon:v2021.12.02

#### Expected behaviour
To return the requested traces or a more explanatory error.

#### Actual behaviour
Returns the error:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed ReadCanonicalHash: EOF, number=2283427"}}`

#### Steps to reproduce the behaviour
`curl --data '{"method":"trace_filter","params":[{"fromBlock":"0x22D789","toBlock":"0x22D7A9"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://ERIGON_URL`

When invoking the above command the above error is received. The query fetches traces for the block interval 2283401 to 2283433. In the error response there is an error for invalid hash for a intermediate block 2283427. If I reduce the block interval in roughly half, let's say 2283420 to block 2283433 I am getting the result as expected. As additional information the above failing query passes using Parity node.

**Comment by AskAlexSharov** [comment]
Hi. I think it's fixed in later erigon versions. Feel free to create new issue if need.
