### ISSUE TITLE
Remote sentry fails to find peers

### ISSUE THREAD

**Issue by limhyesook** [ledgerwatch/erigon#3795]
#### System information

Erigon version: 2022.99.99-dev-11087864

OS & Version: Linux

Commit hash : devel / [816ad30]

#### Expected behaviour
Sentry is launched on separate server and works as a separate p2p endpoint.

#### Actual behaviour
Sentry connects to main server but fails to find any peers. Multiple problems are reported in logs like these:

[TRACE] [03-21|10:32:47.968] >> PING/v4                               id=666463730f556d41d6cf2bbf4c28f5d0d0d8ae26a205e8bd6f42d88c945bc23e addr=65.108.7.37:30311 err=nil
[TRACE] [03-21|10:32:47.968] Removed dead node                        b=16 id=666463730f556d41d6cf2bbf4c28f5d0d0d8ae26a205e8bd6f42d88c945bc23e ip=65.108.7.37 checks=0
[TRACE] [03-21|10:32:48.128] << PONG/v4                               id=666463730f556d41d6cf2bbf4c28f5d0d0d8ae26a205e8bd6f42d88c945bc23e addr=65.108.7.37:30311 err="unsolicited reply"
[TRACE] [03-21|10:32:54.939] >> PING/v4                               id=b909c30dc9bde6b61c2004fc0c18b7caef01f71df878d341a8d2f4f987d04129 addr=162.55.240.202:30311 err=nil
[TRACE] [03-21|10:32:54.939] Removed dead node                        b=15 id=b909c30dc9bde6b61c2004fc0c18b7caef01f71df878d341a8d2f4f987d04129 ip=162.55.240.202 checks=0
[TRACE] [03-21|10:32:55.090] << PONG/v4                               id=b909c30dc9bde6b61c2004fc0c18b7caef01f71df878d341a8d2f4f987d04129 addr=162.55.240.202:30311 err="unsolicited reply"

Some debugging has shown that the problem is connected to the fact that SetStatus function gets nil context. Then Done() channel is added which is closed already. So, ping commands (and others probably) are shut down immediately after launch and are not waiting for the reply.

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
plz check if this helps: https://github.com/ledgerwatch/erigon/pull/3796

**Comment by limhyesook** [comment]
Yes, it works now. I have replaced my workaround with the latest devel and multiple sentries now work!
