### ISSUE TITLE
The given value 'latest' is not a numbers for special named block

### ISSUE THREAD

**Issue by devin-aegis-studio** [ledgerwatch/erigon#3800]
#### System information

Erigon version: `./erigon --stable`

OS & Version: Linux Ubuntu 20.04 LTS

Commit hash : 

#### Expected behaviour
should print all blocks

When I run localhost:8080/when?list=true

I'm expecting to 

{
    "data": [
        {
            "blockNumber": 0,
            "timestamp": 1438269960,
            "date": "2015-07-30 15:26:00",
            "name": "first"
        },
        {
            "blockNumber": 46147,
            "timestamp": 1438918233,
            "date": "2015-08-07 03:30:33",
            "name": "firstTrans"
        },
        {
            "blockNumber": 50111,
            "timestamp": 1438984075,
            "date": "2015-08-07 21:47:55",
            "name": "firstContract"
        },
        {
            "blockNumber": 200000,
            "timestamp": 1441661589,
            "date": "2015-09-07 21:33:09",
            "name": "iceage"
        },
        {
            "blockNumber": 543626,
            "timestamp": 1447577992,
            "date": "2015-11-15 08:59:52",
            "name": "devcon1"
        },
        {
            "blockNumber": 1150000,
            "timestamp": 1457981393,
            "date": "2016-03-14 18:49:53",
            "name": "homestead"
        },
        {
            "blockNumber": 1428756,
            "timestamp": 1461980573,
            "date": "2016-04-30 01:42:53",
            "name": "daofund"
        },
        {
            "blockNumber": 1718497,
            "timestamp": 1466134488,
            "date": "2016-06-17 03:34:48",
            "name": "daohack"
        },
        {
            "blockNumber": 1920000,
            "timestamp": 1469020840,
            "date": "2016-07-20 13:20:40",
            "name": "daofork"
        },
        {
            "blockNumber": 2286910,
            "timestamp": 1474275599,
            "date": "2016-09-19 08:59:59",
            "name": "devcon2"
        },
        {
            "blockNumber": 2463000,
            "timestamp": 1476796771,
            "date": "2016-10-18 13:19:31",
            "name": "tangerine"
        },
        {
            "blockNumber": 2675000,
            "timestamp": 1479831344,
            "date": "2016-11-22 16:15:44",
            "name": "spurious"
        },
        {
            "blockNumber": 2717576,
            "timestamp": 1480448309,
            "date": "2016-11-29 19:38:29",
            "name": "stateclear"
        },
        {
            "blockNumber": 3265360,
            "timestamp": 1488272400,
            "date": "2017-02-28 09:00:00",
            "name": "eea"
        },
        {
            "blockNumber": 3327417,
            "timestamp": 1489165544,
            "date": "2017-03-10 17:05:44",
            "name": "ens2"
        },
        {
            "blockNumber": 4041179,
            "timestamp": 1500417203,
            "date": "2017-07-18 22:33:23",
            "name": "parityhack1"
        },
        {
            "blockNumber": 4370000,
            "timestamp": 1508131331,
            "date": "2017-10-16 05:22:11",
            "name": "byzantium"
        },
        {
            "blockNumber": 4469339,
            "timestamp": 1509526798,
            "date": "2017-11-01 08:59:58",
            "name": "devcon3"
        },
        {
            "blockNumber": 4501969,
            "timestamp": 1509981921,
            "date": "2017-11-06 15:25:21",
            "name": "parityhack2"
        },
        {
            "blockNumber": 4605167,
            "timestamp": 1511415679,
            "date": "2017-11-23 05:41:19",
            "name": "kitties"
        },
        {
            "blockNumber": 4620855,
            "timestamp": 1511634257,
            "date": "2017-11-25 18:24:17",
            "name": "makerdao"
        },
        {
            "blockNumber": 6610517,
            "timestamp": 1540890000,
            "date": "2018-10-30 09:00:00",
            "name": "devcon4"
        },
        {
            "blockNumber": 6627917,
            "timestamp": 1541137042,
            "date": "2018-11-02 05:37:22",
            "name": "uniswap"
        },
        {
            "blockNumber": 7280000,
            "timestamp": 1551383524,
            "date": "2019-02-28 19:52:04",
            "name": "constantinople"
        },
        {
            "blockNumber": 8700401,
            "timestamp": 1570525179,
            "date": "2019-10-08 08:59:39",
            "name": "devcon5"
        },
        {
            "blockNumber": 8928158,
            "timestamp": 1573672677,
            "date": "2019-11-13 19:17:57",
            "name": "mcdai"
        },
        {
            "blockNumber": 9069000,
            "timestamp": 1575764709,
            "date": "2019-12-08 00:25:09",
            "name": "istanbul"
        },
        {
            "blockNumber": 9200000,
            "timestamp": 1577953849,
            "date": "2020-01-02 08:30:49",
            "name": "muirglacier"
        },
        {
            "blockNumber": 12244000,
            "timestamp": 1618481223,
            "date": "2021-04-15 10:07:03",
            "name": "berlin"
        },
        {
            "blockNumber": 12965000,
            "timestamp": 1628166822,
            "date": "2021-08-05 12:33:42",
            "name": "london"
        },
        {
            "blockNumber": 13773000,
            "timestamp": 1639079723,
            "date": "2021-12-09 19:55:23",
            "name": "arrowglacier"
        }
    ],
    "meta": {
        "client": 14491897,
        "finalized": 14479946,
        "staging": 14481020,
        "ripe": 14481020,
        "unripe": 14481039,
        "chainId": 1,
        "networkId": 1,
        "chain": "mainnet"
    }
}

#### Actual behaviour
The given value 'latest' is not a numbers for special named block

#### Steps to reproduce the behaviour
chifra blocks -v 0-latest

#### Backtrace

````
[backtrace]
````

**Comment by tjayrush** [comment]
This is not an Erigon issue. It's an issue with TrueBlocks (https://github.com/TrueBlocks/trueblocks-core/issues).

@devin-aegis-studio You should close this issue and write the issue against TrueBlocks.
