### ISSUE TITLE
after upgrade erigon to v2022.03.02, erigon start fail with error: "cannot downgrade major DB version from 5 to 3"

### ISSUE THREAD

**Issue by marshalys** [ledgerwatch/erigon#3803]
#### System information

Erigon version: `./erigon --version`
v2022.03.02

OS & Version: Windows/Linux/OSX
linux

Commit hash : 

#### Expected behaviour
start success

#### Actual behaviour
 start fail with error: "cannot downgrade major DB version from 5 to 3"

i found the reason is the erigon-lib@v0.0.0-20220327062501-84f0d06450aa is config with wrong version of db 

![image](https://user-images.githubusercontent.com/344530/161002130-d0eb5a11-cb02-48a6-b5eb-4264e9ab46a9.png)

with this commit: https://github.com/ledgerwatch/erigon/commit/c12f8987fe95a91d4907acaf628b36bea7dd2466#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R38

please tell me how to fix it, thank you!

**Comment by AskAlexSharov** [comment]
You created your db by `devel` branch - it has db version 5. 
Just continue use `devel` in this case.
