### ISSUE TITLE
Private API rplTxs data structure

### ISSUE THREAD

**Issue by perfectcircle2020** [ledgerwatch/erigon#3810]
Hello,

I'm using the private API to subscribe to the `OnAdd ` event of the txpool.
I successfully subscribed to the event and everything seems to work as expected, the only thing that's not clear is the underline datastructure of the transferred bytes.

For example a sampled response would be this:

`[b'\xf9\x01S\x08\x85\x01*\x05\xf2\x00\x83\x07\xa1 \x94\x10\xedC\xc7\x18qN\xb6=Z\xa5{x\xb5G\x04\xe2V\x02N\x88\r\xfb[\xe9{4\xc0\x00\xb8\xe4\xb6\xf9\xde\x95\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0I\x06k\xff\xdf\xfd\xd8\x05\xfa\xe9\xed:\xbd\xb2\xf2\x99\xa2K\xa7\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bHS\xcd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbbL\xdb\x9c\xbd6\xb0\x1b\xd1\xcb\xae\xbf-\xe0\x8d\x91s\xbc\t\\\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x008i\x1ea_\xf3&g\x02\xfaV\t=\x7f\x9d\x02X\xced\xd7\x81\x93\xa0\xe3\x80}$\xda\xbbt\xbb\xbc\xdbG-\x9c\xc9\xa0\xca\xa3\xbe\xa9,s[\x1b\xef\xe5\xd1\xe5,O\x10(\xd7\xa0\x7f\xc0\xb8pw\x0e\xc6;S\xc0\x86N\xf66\xf6\x15\tc@(\xb8/g8\xba\xf3X\xb3\x84,\xbe\xcb'] `

Where can I find the exact offsets of the properties of the Transaction in the response?

`
message OnAddReply {
  repeated bytes rplTxs = 1;
}
`

How can I deserialize `rplTxs`?

Thank you!

**Comment by AskAlexSharov** [comment]
It's standard Ethereum encoding of transactions: RLP https://eth.wiki/en/fundamentals/rlp
Very likely you can find some lib in internet (for any language) to parse RLP-serialized transactions
It's a bit non-trivial story: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md -> https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2718.md


In go: https://github.com/ledgerwatch/erigon-lib/blob/75b64f01a32926bafa0e6d86fd8264316e303374/txpool/types.go#L119
another example in go: https://github.com/ethereum/go-ethereum/blob/1e973a96b4b52d2a3af07a935ad41a4358924422/core/types/transaction.go#L153

**Comment by perfectcircle2020** [comment]
@AskAlexSharov Thank you
