### ISSUE TITLE
Sync speed is very slow on Mainnet archive node

### ISSUE THREAD

**Issue by air3ijai** [ledgerwatch/erigon#3835]
As Discord invite is invalid, let's continue here

1. [Issue](#issue)
2. [Hardware on AWS](#hardware-on-aws)
3. [Docker compose](#docker-compose)
4. [Questions](#questions)
5. [Node metrics from AWS](#node-metrics-from-aws)

### Issue
We started two new Erigon nodes ~ 11 days ago and they are still sync and sync slowed down in time:
```
# 1/16
[INFO] [03-25|10:52:17.519] [1/16 Headers] Wrote block headers       number=1536 blk/second=51.200 alloc="271.71 MiB" sys="326.47 MiB"

# 2/16
[INFO] [03-25|11:12:07.438] [2/16 BlockHashes] ETL [1/2] Extracting  from=Header current key=0000000000ae88b1912c0676286d159a9938fc232f557e810a7b6c3e5652644309fc66cc5023e55e alloc="1.7 GiB" sys="6.0 GiB"

# 3/16
[INFO] [03-25|11:14:47.514] [3/16 Bodies] Processing bodies...       from=0 to=14455041
[INFO] [03-25|11:15:19.600] [3/16 Bodies] Wrote block bodies         block_num=2907 delivery/sec="53.28 KiB" wasted/sec="0.00 B" alloc="943.50 MiB" sys="6.00 GiB"

# 4/16
[INFO] [03-25|19:49:43.442] [4/16 Senders] Started                   from=0 to=14455041
[INFO] [03-25|19:49:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-25|19:50:13.446] [4/16 Senders] Preload headers           block_number=2397516
...
[INFO] [03-26|22:45:43.378] [4/16 Senders] DONE                      in=26h55m59.936783585s

# 5/16
[INFO] [03-26|22:45:43.380] [5/16 Execution] Blocks execution        from=0 to=14455041
[INFO] [03-26|22:45:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-26|22:46:13.385] [5/16 Execution] Executed blocks         number=176189 blk/s=5872.645 tx/s=3111.296 Mgas/s=91.955 batch="1.43 MiB" alloc="1.94 GiB" sys="9.79 GiB"
...
# 27.03
[INFO] [03-26|23:59:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-27|00:00:13.483] [5/16 Execution] Executed blocks         number=2429889 blk/s=33.348 tx/s=156.522 Mgas/s=7.996 batch="492.86 MiB" alloc="4.80 GiB" sys="9.79 GiB"
...
# 28.03
[INFO] [03-27|23:59:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-28|00:00:13.427] [5/16 Execution] Executed blocks         number=6524532 blk/s=32.773 tx/s=3328.258 Mgas/s=184.268 batch="170.48 MiB" alloc="2.50 GiB" sys="9.80 GiB"
...
# 29.03
[INFO] [03-28|23:59:47.433] [p2p] GoodPeers                          eth66=100
[INFO] [03-29|00:00:13.425] [5/16 Execution] Executed blocks         number=8149028 blk/s=20.227 tx/s=2247.513 Mgas/s=139.898 batch="166.64 MiB" alloc="2.19 GiB" sys="9.81 GiB"
...
# 30.03
[INFO] [03-29|23:59:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-30|00:00:13.473] [5/16 Execution] Executed blocks         number=9520642 blk/s=9.254 tx/s=1099.040 Mgas/s=76.640 batch="6.87 MiB" alloc="1.23 GiB" sys="9.81 GiB"
...
# 31.03
[INFO] [03-31|00:01:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-31|00:02:12.461] Write to db                              progress=7.6M/7.8M current table=PlainState
[INFO] [03-31|00:02:42.461] Write to db                              progress=7.7M/7.8M current table=PlainState
[INFO] [03-31|00:03:04.099] [5/16 Execution] Executed blocks         number=10433865 blk/s=0.212 tx/s=25.495 Mgas/s=2.320 batch="0.00 B" alloc="2.32 GiB" sys="9.82 GiB"
[INFO] [03-31|00:03:13.650] [5/16 Execution] Executed blocks         number=10433883 blk/s=1.885 tx/s=257.064 Mgas/s=21.732 batch="541.70 KiB" alloc="2.42 GiB" sys="9.82 GiB"
[INFO] [03-31|00:03:43.410] [5/16 Execution] Executed blocks         number=10433995 blk/s=3.763 tx/s=434.037 Mgas/s=41.501 batch="3.09 MiB" alloc="2.90 GiB" sys="9.82 GiB"
[INFO] [03-31|00:03:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [03-31|00:04:13.404] [5/16 Execution] Executed blocks         number=10434159 blk/s=5.468 tx/s=679.506 Mgas/s=59.701 batch="6.28 MiB" alloc="3.53 GiB" sys="9.82 GiB"
[INFO] [03-31|00:04:43.536] [5/16 Execution] Executed blocks         number=10434331 blk/s=5.708 tx/s=643.520 Mgas/s=64.718 batch="9.68 MiB" alloc="1.05 GiB" sys="9.82 GiB"
[INFO] [03-31|00:05:13.505] [5/16 Execution] Executed blocks         number=10434504 blk/s=5.773 tx/s=678.050 Mgas/s=65.948 batch="12.98 MiB" alloc="1.69 GiB" sys="9.82 GiB"
[INFO] [03-31|00:05:43.496] [5/16 Execution] Executed blocks         number=10434673 blk/s=5.635 tx/s=607.501 Mgas/s=64.543 batch="16.67 MiB" alloc="1.37 GiB" sys="9.82 GiB"...
...
# 01.04
[INFO] [03-31|23:59:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [04-01|00:00:13.508] [5/16 Execution] Executed blocks         number=11106107 blk/s=6.349 tx/s=1295.338 Mgas/s=78.294 batch="12.70 MiB" alloc="1.98 GiB" sys="9.82 GiB"
...
# 02.04
[INFO] [04-01|23:59:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [04-02|00:00:13.401] [5/16 Execution] Executed blocks         number=11710981 blk/s=8.289 tx/s=1656.788 Mgas/s=102.216 batch="223.47 MiB" alloc="2.18 GiB" sys="9.83 GiB"
...
# 03.04
[INFO] [04-02|23:59:47.433] [p2p] GoodPeers                          eth66=100
[INFO] [04-03|00:00:13.489] [5/16 Execution] Executed blocks         number=12274997 blk/s=8.114 tx/s=1844.124 Mgas/s=100.615 batch="196.96 MiB" alloc="2.75 GiB" sys="9.83 GiB"
...
# 04.04
[INFO] [04-03|23:59:47.432] [p2p] GoodPeers                          eth66=99
[INFO] [04-04|00:00:13.458] [5/16 Execution] Executed blocks         number=12684482 blk/s=5.185 tx/s=1031.404 Mgas/s=76.507 batch="36.25 MiB" alloc="2.02 GiB" sys="9.84 GiB"
...
# 05.04
[INFO] [04-05|00:13:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [04-05|00:14:14.482] Write to db                              progress=7.6M/7.6M current table=PlainState
[INFO] [04-05|00:14:25.599] [5/16 Execution] Executed blocks         number=13111884 blk/s=0.004 tx/s=0.802 Mgas/s=0.095 batch="0.00 B" alloc="1.05 GiB" sys="9.84 GiB"
[INFO] [04-05|00:14:43.588] [5/16 Execution] Executed blocks         number=13111913 blk/s=1.612 tx/s=296.346 Mgas/s=26.941 batch="1.12 MiB" alloc="1.33 GiB" sys="9.84 GiB"
[INFO] [04-05|00:15:13.676] [5/16 Execution] Executed blocks         number=13111999 blk/s=2.858 tx/s=467.026 Mgas/s=43.344 batch="3.75 MiB" alloc="1.08 GiB" sys="9.84 GiB"
[INFO] [04-05|00:15:43.536] [5/16 Execution] Executed blocks         number=13112105 blk/s=3.550 tx/s=597.050 Mgas/s=54.389 batch="6.65 MiB" alloc="1.89 GiB" sys="9.84 GiB"
...
# 06.04
[INFO] [04-06|00:01:47.432] [p2p] GoodPeers                          eth66=100
[INFO] [04-06|00:01:49.591] Write to db                              progress=7.8M/7.8M current table=PlainState
[INFO] [04-06|00:01:55.854] [5/16 Execution] Executed blocks         number=13509173 blk/s=0.017 tx/s=4.190 Mgas/s=0.277 batch="0.00 B" alloc="2.87 GiB" sys="9.84 GiB"
[INFO] [04-06|00:02:13.558] [5/16 Execution] Executed blocks         number=13509200 blk/s=1.525 tx/s=304.290 Mgas/s=21.230 batch="1008.08 KiB" alloc="1.27 GiB" sys="9.84 GiB"
[INFO] [04-06|00:02:43.551] [5/16 Execution] Executed blocks         number=13509279 blk/s=2.634 tx/s=601.742 Mgas/s=40.480 batch="3.06 MiB" alloc="1.85 GiB" sys="9.84 GiB"
[INFO] [04-06|00:03:13.389] [5/16 Execution] Executed blocks         number=13509375 blk/s=3.217 tx/s=726.244 Mgas/s=50.032 batch="5.36 MiB" alloc="1.54 GiB" sys="9.84 GiB"
[INFO] [04-06|00:03:43.648] [5/16 Execution] Executed blocks         number=13509486 blk/s=3.668 tx/s=814.901 Mgas/s=56.013 batch="7.90 MiB" alloc="1.29 GiB" sys="9.84 GiB"
```
```
1.4T	/data/erigon
```

### Hardware on AWS
m5a.xlarge: 4vCPU / 16 GB
gp3/3000 GB: 16000IOPS / 1000Mbit/s

### Docker compose
We used [docker-compose.yml](https://github.com/ledgerwatch/erigon/blob/devel/docker-compose.yml) from repository as a source
```
version: '3.9'

services:
  erigon:
    container_name: erigon
    image: thorax/erigon:v2022.03.02
    command: erigon --chain mainnet --datadir=/home/erigon/.local/share/erigon --private.api.addr=0.0.0.0:9090 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    user: 2000:2000
    volumes:
      - /data/erigon:/home/erigon/.local/share/erigon
    ports:
      - "30303:30303/tcp" # P2P TCP
      - "30303:30303/udp" # P2P UDP
      - "30304:30304/tcp" # P2P TCP
      - "30304:30304/udp" # P2P UDP
      - "6060:6060"       # Metrics
      - "6061:6061"       # pprof
    restart: unless-stopped

  rpcdaemon:
    container_name: rpcdaemon
    image: thorax/erigon:v2022.03.02
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,web3,net,debug,trace,txpool --ws
    user: 2000:2000
    pid: service:erigon
    volumes_from:
      - erigon
    ports:
      - "8545:8545" # RPC/WS
      - "9090:9090" # gRPC
    restart: unless-stopped
```

Today we tried again to run a downloader to speed up sync but is still fail
```
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "downloader": executable file not found in $PATH: unknown
```

### Questions
1. Is downloader executable present in the current docker image and can be used to speedup the sync?
2. Can we use snap-sync if initially we started Erigon without this option?
3. Why sync is so slow? It slowed down some days ago and we still see `blk/s=5.517` instead of initial bigger ones.

### Node metrics from AWS
<img width="1210" alt="Screenshot 2022-04-06 at 11 55 53" src="https://user-images.githubusercontent.com/88528265/161937233-84409db7-612f-4bec-90e2-d4ab631e6e56.png">
<img width="1215" alt="Screenshot 2022-04-06 at 11 54 20" src="https://user-images.githubusercontent.com/88528265/161937217-d7d73519-5061-4b06-ae35-faeba750ba91.png">
<img width="1213" alt="Screenshot 2022-04-06 at 11 54 41" src="https://user-images.githubusercontent.com/88528265/161937223-2c2a4dcf-b342-4019-a5dd-589fe1b11539.png">
<img width="1211" alt="Screenshot 2022-04-06 at 11 55 21" src="https://user-images.githubusercontent.com/88528265/161937230-71cb12eb-b357-4820-a4ca-d2ca7709e0c0.png">
<img width="1216" alt="Screenshot 2022-04-06 at 11 53 47" src="https://user-images.githubusercontent.com/88528265/161937193-e440fddc-2765-4891-a515-af5c447b76d3.png">

**Comment by mandrigin** [comment]
I think it is expected on EBS, especially `gp` type. We had better experience either with `io`-type EBS or with internal SSDs.
Erigon is sensitive to the i/o latency, not throughput.

**Comment by mandrigin** [comment]
answers to your questions

> Is downloader executable present in the current docker image and can be used to speedup the sync?

I don't think the downloader will do anything for stable erigon release. @AlexeyAkhunov @AskAlexSharov please reopen/comment if that is not true :)

> Can we use snap-sync if initially we started Erigon without this option?
Erigon doesn't support snap-sync.

> Why sync is so slow? It slowed down some days ago and we still see blk/s=5.517 instead of initial bigger ones.

blk/s is a bad metric to judge the perfomance, early blocks have less transactions. use `mgas/s` instead. The speed is expecged on AWS `gp` EBS, I wouldn't recommend using that setup.

**Comment by air3ijai** [comment]
@mandrigin,

> I don't think the downloader will do anything for stable erigon release. @AlexeyAkhunov @AskAlexSharov please reopen/comment if that is not true :)

`image: thorax/erigon:v2022.03.02` - [2022.03.02-beta](https://github.com/ledgerwatch/erigon/releases/tag/v2022.03.02). So it is beta - can it work with this release?


> Erigon doesn't support snap-sync.

[What then this line mean](https://github.com/ledgerwatch/erigon/blob/devel/docker-compose.yml#L59)?
`downloader: # Service to download/seed historical data (need only if you use --syncmode=snap)`

> `blk/s` is a bad metric to judge the perfomance, early blocks have less transactions. use `mgas/s` instead. The speed is expected on AWS gp EBS, I wouldn't recommend using that setup.

We already have a node on AWS with similar hardware and doesn't have any issue with it, but we didn't note how long it take for initial sync.

Anyway, thank you for the info about disk requirements. We just changed from gp3/16000 to io-2/1000. Let's see if something will be changed.

**Comment by AskAlexSharov** [comment]
we will releasee snapsync soon. but v1 of our snapsync will not speedup blocks execution. v2 will.

**Comment by air3ijai** [comment]
We did update of the EBS from gp3 to the io2-1000/2000/3000, but looks like nothing changed drastically

| Type | Size | IOPS  | Throughput | Cost       |
| ---- | ---- | ----- | ---------- | ---------- |
| gp3  | 3000 | 16000 | 1000       | 340.00 USD |
| io2  | 3000 | 1000  | -          | 440.00 USD |
| io2  | 3000 | 2000  | -          | 505.00 USD |
| io2  | 3000 | 3000  | -          | 570.00 USD |

<img width="1210" alt="Screenshot 2022-04-08 at 08 54 56" src="https://user-images.githubusercontent.com/88528265/162382543-292b1efe-9f15-4c40-bcde-317e4bc9d1d1.png">
<img width="1216" alt="Screenshot 2022-04-08 at 08 55 57" src="https://user-images.githubusercontent.com/88528265/162382566-33c3285a-7372-4a91-af1c-76d6412380bc.png">
<img width="1215" alt="Screenshot 2022-04-08 at 08 56 53" src="https://user-images.githubusercontent.com/88528265/162382613-cf0d9be6-7b33-464f-963d-5c0a552673a6.png">
<img width="1212" alt="Screenshot 2022-04-08 at 10 02 18" src="https://user-images.githubusercontent.com/88528265/162382635-306e76a7-7122-477d-8193-5874204ba8c0.png">

**Comment by nisaacson** [comment]
I suggest you switch to an instance store volume type. For example use the `i3en.3xlarge` instance type and put the erigon database on the nvme drive.

```
sudo useradd -m -s /bin/bash erigon
df -h
lsblk # note the nvme drive in the list
sudo mkdir /data
sudo mkfs -t ext4 /dev/nvme1n1
sudo mount /dev/nvme1n1 /data
mkdir -p /data/erigon/datadir
chown -R erigon:erigon /data/erigon
```

 In the example below make sure to set the erigon process to run as `erigon` user

**Comment by AskAlexSharov** [comment]
In cloud: 
1. During initial sync - give for erigon nvme and much RAM. 
2. When initial sync is done - move db to any other disk type and reduce RAM.
3. You can mount <datadir>/snapshots and <datadir>/etl-temp to cheaper disk type

**Comment by air3ijai** [comment]
An article about `i3` vs `m5` - [Optimizing Performance and Cost: Infura Benchmark Analysis](https://blog.infura.io/post/optimizing-performance-and-cost-infura-benchmark-analysis-f083ccf8f6ac)
