### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by SuchJitter** [ledgerwatch/erigon#3848]
#### System information

OS & Version: Windows/Linux/OSX
CentOS 8.5

#### Expected behaviour
Rpc working fine on BSC chain

#### Actual behaviour
giving an error using getTransactionReceipt.
`goroutine 51972 [runnable]:
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_get1(0x76b6c40537c0, 0xc0f73eea60, 0x20, 0xc0f7396320, 0xc0f7396330, 0xf)
	_cgo_gotypes.go:966 +0x4c
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal1.func1(0x203026, {0xc0f73eea60, 0x20, 0x12f49edadef68163}, 0xf)
	github.com/torquem-ch/mdbx-go@v0.22.14/mdbx/cursor.go:196 +0xdd
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal1(0xc0f9e99078, {0xc0f73eea60, 0x8, 0x120}, 0x0)
	github.com/torquem-ch/mdbx-go@v0.22.14/mdbx/cursor.go:196 +0x25
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Get(0xc0f7396340, {0xc0f73eea60, 0x20, 0x20}, {0x0, 0x14d9820, 0x1}, 0xf)
	github.com/torquem-ch/mdbx-go@v0.22.14/mdbx/cursor.go:142 +0x54
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).set(...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220224151801-2fc62cd2f54e/kv/mdbx/kv_mdbx.go:1021
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).SeekExact(0xc0f738cc90, {0xc0f73eea60, 0x16, 0x1})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220224151801-2fc62cd2f54e/kv/mdbx/kv_mdbx.go:1385 +0x265
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).GetOne(0xc0f9e99190, {0x15dbb9a, 0x152a8e0}, {0xc0f73eea60, 0x20, 0x20})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220224151801-2fc62cd2f54e/kv/mdbx/kv_mdbx.go:877 +0x62
github.com/ledgerwatch/erigon/core/rawdb.ReadTxLookupEntry({0x7fbb596ab1f8, 0xc0f738cc90}, {0x92, 0x8b, 0xee, 0x6f, 0x94, 0x91, 0x94, 0xe9, ...})
	github.com/ledgerwatch/erigon/core/rawdb/accessors_indexes.go:39 +0x7b
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReader).TxnLookup(0x44d3aa, {0x1475620, 0x15929e0}, {0x7fbb596ab1f8, 0xc0f738cc90}, {0x92, 0x8b, 0xee, 0x6f, 0x94, ...})
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:83 +0x45
github.com/ledgerwatch/erigon/cmd/rpcdaemon/services.(*RemoteBackend).TxnLookup(0x0, {0x1a15f98, 0xc0f217ca80}, {0x7fbb596ab1f8, 0xc0f738cc90}, {0x92, 0x8b, 0xee, 0x6f, 0x94, ...})
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/services/eth_backend.go:161 +0x55
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*BaseAPI).txnLookup(...)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:136
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).GetTransactionReceipt(0xc00010f0e0, {0x1a15f98, 0xc0f217ca80}, {0x92, 0x8b, 0xee, 0x6f, 0x94, 0x91, 0x94, ...})
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_receipts.go:274 +0x2ec
reflect.Value.call({0xc00020b980, 0xc000110878, 0x7fbb82e3f9e8}, {0x15c0952, 0x4}, {0xc0e7b32c80, 0x3, 0xc0f3d16a00})
	reflect/value.go:556 +0x845
reflect.Value.Call({0xc00020b980, 0xc000110878, 0xc0f73eea20}, {0xc0e7b32c80, 0x3, 0x3})
	reflect/value.go:339 +0xc5
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc000a81b60, {0x1a15f98, 0xc0f217ca80}, {0xc0f5bed3c0, 0x19}, {0xc0f210de90, 0x1, 0xc0f3d16a00}, 0xc0e65f32c0)
	github.com/ledgerwatch/erigon/rpc/service.go:222 +0x58a
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc00ee9bc70, {0x1a15f98, 0xc0f217ca80}, 0xc0f11543f0, 0x459dad, {0xc0f210de90, 0x4, 0x0}, 0x8)
	github.com/ledgerwatch/erigon/rpc/handler.go:484 +0x25b
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc000ed7ae0, 0xc0f738cc30, 0xc0f11543f0, 0x8)
	github.com/ledgerwatch/erigon/rpc/handler.go:389 +0x2c9
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc000ed7ae0, 0x76b7e42138a8, 0xc0f11543f0, 0x28)
	github.com/ledgerwatch/erigon/rpc/handler.go:343 +0xd6
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0f738cc30)
	github.com/ledgerwatch/erigon/rpc/handler.go:181 +0x111
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1()
	github.com/ledgerwatch/erigon/rpc/handler.go:271 +0xc5
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:267 +0x92
`

#### Steps to reproduce the behaviour
Starting a for loop using getTransactionReceipt

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
error is about "nil pointer"?

**Comment by SuchJitter** [comment]
If using a snapshot, I updated to the current version of erigon and now get this error:

`Could not connect to DB                  err="create bucket: LastForkchoice, mdbx_dbi_open: MDBX_NOTFOUND: No matching key/data pair found"`

**Comment by AskAlexSharov** [comment]
1. What kind of snapshot? Did you stop erigon when created snapshot?
2. Are you sure that you using correct directory? Show folders structure and erigon’s cli flags
