### ISSUE TITLE
i have trouble when i try to start bsc mainnet

### ISSUE THREAD

**Issue by kugimiya530** [ledgerwatch/erigon#3850]
EROR[04-08|02:36:40.190] Erigon startup                           err="cannot upgrade major DB version for more than 1 version from 3 to 5, use integration tool if you know what you are doing"

start with ./erigon --chain bsc

and is there any snapshot for erigon bsc?

i only use geth before

**Comment by AskAlexSharov** [comment]
it means you created Erigon node by version from our `devel` branch. You can't switch this node to `stable` branch(current releases). 
Just keep using `devel` (bsc supported only in `devel` now)
