### ISSUE TITLE
help  to stop sync process and restart it 

### ISSUE THREAD

**Issue by xiaogea01** [ledgerwatch/erigon#3856]
I start a new erigon node and meet some problem.

 The first time I start with cli  "./erigon --datadir /backup/erigon/"  after 2 days, I read the doc  and  found this is a full node mode but My nvme space only 2T, maybe not enough for saving the data. so I delete the node  and  just want  keep block data,txhash transaction data and tx receipt data .
 I restart with new cmd ./erigon --datadir /backup/erigon/ --prune=hc --prune.h.older=0 --prune.c.older=0 --batchSize=2048

the current console log show:
INFO[04-09|09:39:50.023] [6/16 Execution] Executed blocks        **number=5153872 blk/s=16.381** tx/s=1944.402 Mgas/s=106.164 gasState=1.229 estimated duration=236h6m4.025s batch="0.00 B" alloc="1.45 GiB" sys="6.22 GiB"
INFO[04-09|09:39:50.024] Committed State                          gas reached=7730150 gasTarget=6291456
INFO[04-09|09:39:50.066] Committed State                          gas reached=8463786 gasTarget=6291456
INFO[04-09|09:39:50.219] Committed State                          gas reached=9751852 gasTarget=6291456
INFO[04-09|09:39:50.334] Committed State                          gas reached=7968751 gasTarget=6291456
INFO[04-09|09:39:50.418] Committed State                          gas reached=7989208 gasTarget=6291456

everything is happy except the blk/s speed.I simple estimate that it  nearly need 38 days to catch up with the latest block, It's so sad ...
I humbly ask for advice, can I stop current sync process and restart it. I fear to lose prestage downloading header and body data.
My computer is Apple M1 16G Mem, 2T NVME.   how to speed up  Executed blocks stage. 
Sincere thanks for all suggestions ：）

**Comment by AskAlexSharov** [comment]
5M block - is the time of some DDOS attack on network - can't estimate by this number. `estimated duration=236h`, but I think you will finish in 1 week. 
See also: https://github.com/ledgerwatch/erigon/issues/3791

**Comment by xiaogea01** [comment]
> 5M block - is the time of some DDOS attack on network - can't estimate by this number. `estimated duration=236h`, but I think you will finish in 1 week.
> See also: #3791

thans for you repley ,
If I have to shutdown my pc today and tomorrow I restart the process, will it  continue the current process?
I fair to loss curent stage : [6/16 Execution] Executed blocks

**Comment by AskAlexSharov** [comment]
You can kill any time - everything will be good enough.
