### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by JohnGump** [ledgerwatch/erigon#3859]
#### System information

Erigon version: `./erigon --version`

OS & Version: Linux Ubuntu 20.04
CPU:AMD5900X

Commit hash : 

This error occurred when I synced to 500GB for about 18 hours.
CPU utilization reached 100 percent before the system crashed

INFO[04-09|16:40:22.661] [p2p] GoodPeers                          eth66=5
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x795484e41010 pc=0x43c637]

runtime stack:
runtime.throw({0x17edd24?, 0x6b6bf4a0d56a500?})
        runtime/panic.go:992 +0x71
runtime.sigpanic()
        runtime/signal_unix.go:802 +0x3a9

I have tried to find some solutions, including changing DNS, but none of them have been solved. Have you ever encountered this situation?
This is the code I used when I synchronized:
screen ./build/bin/erigon --datadir /media/john/data/eth --private.api.addr=localhost:9090

./build/bin/rpcdaemon --datadir=/media/john/data/eth --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
1. do you have longer trace?
2. do you have erigon logs before crash?
3. what is erigon version?

**Comment by khkwan0** [comment]
hello, i am seeing this as well...
Is there a certain branch I should be using?  

This is the complete log of the run...
https://gist.github.com/khkwan0/f8eda7c1704f818b95139969966956a8

```
% ./erigon --version
erigon version 2022.99.99-dev-c1eef706
```

Here is my script that is used to start it...
```
#!/bin/bash

erigon/build/bin/erigon --chain=bsc --datadir=/mnt/highpoint --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 2>&1 | tee erigon_logs.txt
```
