### ISSUE TITLE
Bsc Sync super slow....

### ISSUE THREAD

**Issue by kugimiya530** [ledgerwatch/erigon#3873]
![image](https://user-images.githubusercontent.com/30725599/162758199-d9da300c-f512-4023-9607-466bff0b5a4c.png)

i can't imaging how long should i wait until sync finish...

any improvement way?

**Comment by kugimiya530** [comment]
after i put --syncmode=fast and remove datadir

it's stuck here sameblock for a 1 hour

blk/s =0  

./erigon --chain=bsc --private.api.addr=0.0.0.0:10086 --syncmode=fast  
![image](https://user-images.githubusercontent.com/30725599/162819448-f67ddfcc-d8c8-4115-9623-b8924407982c.png)

**Comment by kugimiya530** [comment]
alright after  i  terminate it and run again 

it's normal for now

hi alex if i want to a node for rpc (metamask  mempool  etc.)  it's  command below correct? 

./erigon --chain=bsc --private.api.addr=0.0.0.0:10086 --syncmode=fast --http.api=eth,debug,net,trace,web3,erigon --http.port 8546

the json rpc it's   IP:8546     but   this is  http  , how about  ws rpc  how to enable it

**Comment by kugimiya530** [comment]
> --ws (same port with http)

./erigon --chain=bsc --private.api.addr=localhost:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon --http.addr "localhost" --http.port "6666"  --maxpeers 300 --syncmode=fast --prune=hrtc

hi alex
this is my command and always  ws work  but http is  nonactive

is erigon only support  one of them active in same time?

**Comment by AskAlexSharov** [comment]
you need add `--http` flag
`improve the sync speed` - no, defaults are fine. For sync speed - you can give disk with lower latency (not throughput), you can give more RAM.

**Comment by kugimiya530** [comment]
> you need add `--http` flag `improve the sync speed` - no, defaults are fine. For sync speed - you can give disk with lower latency (not throughput), you can give more RAM.

hi Alex 
i think i already add --http   

./erigon --chain=bsc --private.api.addr=localhost:9090 **--http** --ws --http.api=eth,debug,net,trace,web3,erigon --http.addr "localhost" --http.port "6666" --maxpeers 300 --syncmode=fast --prune=hrtc

i already using psyical nvmessd and  which command can i give more RAM to erigon

appreciate

**Comment by kugimiya530** [comment]
any updated...?

**Comment by AskAlexSharov** [comment]
on what question?

**Comment by kugimiya530** [comment]
i already add --http and --ws  but only  ws work

Alex Sharov ***@***.***> 於 2022年4月18日 週一 下午1:08寫道：

**Comment by AskAlexSharov** [comment]
what error you see?

**Comment by AskAlexSharov** [comment]
do you test from inside server? no firewall between erigon and your http client?

**Comment by AskAlexSharov** [comment]
- do you see in logs line `HTTP endpoint opened`? What it shows?
- if you call erigon from another server probably you need set `0.0.0.0` instead of localhost
- did you try to replace localhost to 127.0.0.1?

**Comment by kugimiya530** [comment]
first of all this is my command   "./erigon --chain=bsc
--private.api.addr=localhost:9090 --http --ws
--http.api=eth,debug,net,trace,web3,erigon,txpool --http.addr "0.0.0.0"
--http.port "6666"  --maxpeers 300 --syncmode=fast --prune=hrtc
--state.cache 4000000 --db.pagesize "64kb""

i am using web3 module test ws, and it's working fine

i am using metamask to add http rpc and it's didn't work, and also sniper
don't work

for ws i test from inside 127.0.0.1  or  outside  IP:6666  it's fine

but http both fail   and  yes  i  close the firewall now

maybe can u provide the step that how you check this problem  i  can try
thx

Alex Sharov ***@***.***> 於 2022年4月18日 週一 下午1:31寫道：

**Comment by kugimiya530** [comment]
[image: image.png]
maybe http  didn't open... but how
i already add --http

Kugyu TsuKaima ***@***.***> 於 2022年4月18日 週一 下午1:54寫道：

**Comment by kugimiya530** [comment]
![image](https://user-images.githubusercontent.com/30725599/163762463-9a6b0832-2388-4960-82cc-13cb0572238d.png)

maybe http  didn't open... but how
i already add --http

**Comment by AskAlexSharov** [comment]
- `both fail` - with which error message?
- test from inside server first: `curl -v http://127.0.0.1:8545/`

**Comment by kugimiya530** [comment]
Hi Alex
![image](https://user-images.githubusercontent.com/30725599/163765397-394c220e-6e47-487b-9380-0b849c02e4a9.png)
![image](https://user-images.githubusercontent.com/30725599/163765425-cbd7520a-f447-4741-b310-84ed84621124.png)
![image](https://user-images.githubusercontent.com/30725599/163765440-182f48cb-e5cd-4a7f-a2e4-dd2e87e5082b.png)

P1. directly test local ip it's work   but  using domain..i think there is some problem?

P2.Sniper , ws it's work  http it's fail(using direct IP:6666)

P3.Metamask fail

**Comment by AskAlexSharov** [comment]
curl shows error code `403 Forbidden` 
- or you firewall or you load balancer or some http proxy in-front of erigon - rejecting request (see their logs)
- or your server doesn't allow `http` protocol and expecting `https`.

**Comment by kugimiya530** [comment]
Damn thats weird, i am closed firewall, and curl -v http://127.0.0.1:6666.
Its work  and didnt show 403 but with domain its show 403

And even i start or stop nginx its same.  Rly confuse me.  But my command
doesnt has problem right?

Alex Sharov ***@***.***> 於 2022年4月18日 週一 17:26 寫道：

**Comment by AskAlexSharov** [comment]
Command is ok. 

Probably you don’t open 6666 port on firewall. 
Also if you have nginx - then probably it listen not on 6666. 

I don’t have any knowledge about your infrastructure - so, i can’t help.

**Comment by kugimiya530** [comment]
@AskAlexSharov hm..

i was use lastest version erigon

and brand new system

and follow the guide

git clone --recurse-submodules -j8 https://github.com/ledgerwatch/erigon.git
#enter the cloned directory
cd erigon
#set the branch devel as current
git checkout devel
#build all erigon's components
make all
eventually run

/home/user/erigon/build/bin/erigon --chain bsc --datadir /root/bsc-arch/node --private.api.addr 0.0.0.0:10086 --http --ws --syncmode=fast --http.addr 0.0.0.0 --torrent.download.rate 1000mb --torrent.upload.rate 200mb 

after half day syncing... it's  not bsc node...  why  i think i already add"--chain bsc"

**Comment by AskAlexSharov** [comment]
"it's not bsc node" - it's too abstract definition of problem. 
Please open new issue with:
- clear description of problem
- Erigon version
- description of your infrastructure (Docker? Cloud? OS?)
- some recent logs
- error message


Also - re-check all next ports are open on your firewall: https://github.com/ledgerwatch/erigon#default-ports-and-protocols--firewalls
