### ISSUE TITLE
Random Panic on stage_execution

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#3874]
erigon: mdbx:8403: mdbx_iov_done: Assertion `ctx->iov_items == 0' failed.
SIGABRT: abort
PC=0x7f24a780b03b m=13 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 102 [syscall, locked to thread]:
runtime.cgocall(0x16069f0, 0xc08055c3f8, 0x0)
	runtime/cgocall.go:154 +0x5b fp=0xc08055c3c8 sp=0xc08055c390 pc=0x449e3b
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2(0x7623d0dfef70, 0xc0b5280d80, 0x1c, 0xc0cf34b4c0, 0x2a, 0xc000000040, 0x0)
	_cgo_gotypes.go:1033 +0x48 fp=0xc08055c3f8 sp=0xc08055c3c8 pc=0x9960e8
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put.func1(0xc0b7542060, 0xc0b5280d80, 0x1c, 0x3c, 0xc0cf34b4c0, 0x2a, 0x40, 0x40, 0xc143e9e128)
	github.com/torquem-ch/mdbx-go@v0.23.1/mdbx/cursor.go:235 +0xad fp=0xc08055c448 sp=0xc08055c3f8 pc=0x99e9cd
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put(0xc0b7542060, 0xc0b5280d80, 0x1c, 0x3c, 0xc0cf34b4c0, 0x2a, 0x40, 0x40, 0xc0b5280d80, 0x1c)
	github.com/torquem-ch/mdbx-go@v0.23.1/mdbx/cursor.go:235 +0x9f fp=0xc08055c4b0 sp=0xc08055c448 pc=0x99799f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).putCurrent(...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220401025652-224f0c9dc058/kv/mdbx/kv_mdbx.go:1081
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).putDupSort(0xc0b5593da0, 0xc0b5280d80, 0x3c, 0x3c, 0xc11445b290, 0xa, 0x30, 0x3c, 0x0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220401025652-224f0c9dc058/kv/mdbx/kv_mdbx.go:1404 +0x36a fp=0xc08055c650 sp=0xc08055c4b0 pc=0x9aaf0a
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Put(0xc0b5593da0, 0xc0b5280d80, 0x3c, 0x3c, 0xc11445b290, 0xa, 0x30, 0x0, 0x0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220401025652-224f0c9dc058/kv/mdbx/kv_mdbx.go:1363 +0xc6 fp=0xc08055c718 sp=0xc08055c650 pc=0x9aa926
github.com/ledgerwatch/erigon-lib/etl.loadFilesIntoBucket.func1(0xc0b5280d80, 0x3c, 0x3c, 0xc0b5280d80, 0x3c, 0x3c, 0xc11445b290, 0xa, 0x30, 0xc0002e4101, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220401025652-224f0c9dc058/etl/collector.go:252 +0x682 fp=0xc08055c938 sp=0xc08055c718 pc=0xeaa5e2
github.com/ledgerwatch/erigon-lib/etl.glob..func1(0xc0b5280d80, 0x3c, 0x3c, 0xc11445b290, 0xa, 0x30, 0x2ae4800, 0xc0

**Comment by erthink** [comment]
This is my bug. Will fix soon.

**Comment by AskAlexSharov** [comment]
merged fix to devel https://github.com/ledgerwatch/erigon/pull/3876

**Comment by erthink** [comment]
@Giulio2002, I need a little help from you.

In February, I discovered a [specific issue](https://github.com/erthink/libmdbx/issues/269) in the Linux kernel, which until your case could only be reproduced on highloaded Positive Technologies' software with closed source code.
Unfortunately, we could not find any simpler and/or isolated method of reproduction.
But now you have reproduced this issue.

So, please describe the configuration of your machine, including the kernel version, the disks and controllers used, the type of file system, etc.
I hope this information will help with the analysis and search for a simple playback scenario.

**Comment by Giulio2002** [comment]
Could this issue be part of the fact that my machine run out of space, the db was 1.5 TB long and the machine had 2TB of disk, is there the possibility it finished disk space?

**Comment by erthink** [comment]
> Could this issue be part of the fact that my machine run out of space, the db was 1.5 TB long and the machine had 2TB of disk, is there the possibility it finished disk space?

Hmm, No, but perhaps the lack of space provokes the manifestation of the noted issue and/or increases the probability.
