### ISSUE TITLE
Docker container platform add arm64

### ISSUE THREAD

**Issue by zzir** [ledgerwatch/erigon#3878]
when debugging something on Macbook, I found that the container was only x86_64.

**Comment by AskAlexSharov** [comment]
I don't understand the problem

**Comment by zzir** [comment]
> I don't understand the problem

In this,

```bash
docker pull thorax/erigon
```

only `linux/amd64` platform. When used on MacOS, hint: 

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

It is hoped that image can support multiple platforms.

**Comment by AskAlexSharov** [comment]
what is `linux/arm64/v8`? v8?

**Comment by AskAlexSharov** [comment]
probably M1

**Comment by AskAlexSharov** [comment]
you can try docker's flag `--platform linux/amd64`
I don't know yet how to configure hub.docker.com to build for `linux/amd64/v8`

**Comment by AskAlexSharov** [comment]
Also you can build Erigon Docker image locally from sources. See: https://github.com/docker/for-mac/issues/5310#issuecomment-779791882

**Comment by mandrigin** [comment]
@AskAlexSharov I think it is possible to have a "multiplatform" Docker image using `docker buildx` command, but the question is do we want to do so? :) If so, I can try to fix it, otherwise we can close this issue.

**Comment by mandrigin** [comment]
okay, it is a duplicate of https://github.com/ledgerwatch/erigon/issues/3676 anyway
