### ISSUE TITLE
Meet a big problem，i'm going out of my mind

### ISSUE THREAD

**Issue by xiaogea01** [ledgerwatch/erigon#3883]
#### System information

Erigon version: erigon version 2022.99.99-dev-d223580d

OS & Version: OSX

I was syncing from the 0 block and current stage is about 
[04-13|00:01:21.948] [6/16 Execution] Executed blocks         number=9815818

But accident happened suddenly, someone touched my ssd , and system shows  my ssd was ejected.
I remount my ssd, and restart with the cmd:
erigon --datadir /Volumes/U/backup/erigon/ --prune=hc --prune.h.older=0 --prune.c.older=0 --batchSize=2048
I hope it will recover the process and stage,but error happended, here is the key log:

INFO[04-13|23:22:49.435] Flushed buffer file                      name=/Volumes/U/backup/erigon/etl-temp/erigon-sortable-buf-3933384531 alloc="2.1 GiB" sys="7.7 GiB"
INFO[04-13|23:22:54.108] [8/16 HashState] etl: temp files removed total size="21.7 GiB"
INFO[04-13|23:22:54.149] [8/16 HashState] etl: temp files removed total size="3.3 GiB"
EROR[04-13|23:22:54.149] Staged Sync                              err="[8/16 HashState] failed MdbxKV cursor.Next(): mdbx_cursor_get: MDBX_PAGE_NOTFOUND: Requested page not found"
INFO[04-13|23:22:55.047] [8/16 HashState] Promoting plain state   from=0 to=9813575
INFO[04-13|23:23:09.095] Flushed buffer file                      name=/Volumes/U/backup/erigon/etl-temp/erigon-sortable-buf-1871677176 alloc="1.7 GiB" sys="7.7 GiB"
INFO[04-13|23:23:23.739] Flushed buffer file                      name=/Volumes/U/backup/erigon/etl-temp/erigon-sortable-buf-2086194098 alloc="1.4 GiB" sys="7.7 GiB"
INFO[04-13|23:23:25.048] [8/16 HashState] ETL [1/2] Extracting    current key=02fd92d1bff7... alloc="1.4 GiB" sys="7.7 GiB"

I monitor log for a while , it keep looping
 
INFO[04-13|23:52:07.509] [8/16 HashState] etl: temp files removed total size="3.3 GiB"
EROR[04-13|23:52:07.509] Staged Sync                              err="[8/16 HashState] failed MdbxKV cursor.Next(): mdbx_cursor_get: MDBX_PAGE_NOTFOUND: Requested page not found"
INFO[04-13|23:52:08.458] [8/16 HashState] Promoting plain state   from=0 to=9813575
INFO[04-13|23:52:23.066] Flushed buffer file                      name=/Volumes/U/backup/erigon/etl-temp/erigon-sortable-buf-722922546 alloc="1.4 GiB" sys="7.7 GiB"
INFO[04-13|23:52:37.620] Flushed buffer file                      name=/Volumes/U/backup/erigon/etl-temp/erigon-sortable-buf-214514274 alloc="1.4 GiB" sys="7.7 GiB"
the dir file size always loop from 0 to 25GB 
0B	    /Volumes/U/backup/erigon/etl-temp/
 25G	/Volumes/U/backup/erigon/etl-temp/

maybe the db file have some problem , I'm a little bit broken ,are there any rescue measures? 
please help..

**Comment by erthink** [comment]
> mdbx_cursor_get: MDBX_PAGE_NOTFOUND: Requested page not found"

Please use [memtest86](https://www.memtest86.com/) to check you RAM and then check SSD/HDD.

**Comment by xiaogea01** [comment]
➜  erigon git:(devel) ./build/bin/mdbx_chk -v -d /Volumes/U/backup/erigon/chaindata
mdbx_chk v0.11.6-4-ga6b506be (2022-03-25T13:54:34+03:00, T-48c2c9f4cfff32e32d043427a7c46b342ddf988f)
Running for /Volumes/U/backup/erigon/chaindata in 'read-only' mode...
 - monopolistic mode
 - current boot-id a9c98898021550d2-5a40e969df104452
 - pagesize 4096 (16384 system), max keysize 1980..2022, max readers 500
 - mapsize 6597069766656 (6.00 Tb)
 - dynamic datafile: 12288 (12.00 Kb) .. 6597069766656 (6.00 Tb), +2147483648 (2.00 Gb), -4294967296 (4.00 Gb)
 - current datafile: 1013612281856 (944.00 Gb), 247463936 pages
 - meta-0: steady txn#4639681, stay
 - meta-1: steady txn#4639682, head
 - meta-2: steady txn#4639680, tail
 - transactions: recent 4639682, latter reader 4639682, lag 0
Skipping b-tree walk...
Processing '@MAIN'...
 - key-value kind: usual-key => single-value
 - last modification txn#4639682
 - summary: 57 records, 0 dups, 739 key's bytes, 2736 data's bytes, 0 problems
Processing '@GC'...
 - key-value kind: ordinal-key => single-value
 - last modification txn#4639682
 - fixed key-size 8
 - summary: 260 records, 0 dups, 2080 key's bytes, 312959272 data's bytes, 0 problems
 - space: 1610612736 total pages, backed 247463936 (15.4%), allocated 247220692 (15.3%), available 1441631596 (89.5%)
 - skip check used and gc pages (btree-traversal with monopolistic or read-write mode only)
Processing 'AccountChangeSet'...
 - key-value kind: usual-key => multi-value
 - last modification txn#9
 - summary: 8893 records, 8892 dups, 71144 key's bytes, 177860 data's bytes, 0 problems
Processing 'AccountHistory'...
 - key-value kind: usual-key => single-value
 - last modification txn#9
 - summary: 8893 records, 0 dups, 249004 key's bytes, 266790 data's bytes, 0 problems
Processing 'BittorrentInfo'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'BlockBody'...
 - key-value kind: usual-key => single-value
 - last modification txn#4639679

 - summary: 14576963 records, 0 dups, 583078520 key's bytes, 792863996 data's bytes, 0 problems
Processing 'BlockBorTransactionLookup'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'BlockTransaction'...
 - key-value kind: usual-key => single-value
 - last modification txn#4639679
 - summary: 674577085 records, 0 dups, 5396616680 key's bytes, 125239469694 data's bytes, 0 problems
Processing 'BlockTransactionLookup'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'BorReceipt'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'BorSeparate'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CallFromIndex'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CallToIndex'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CallTraceSet'...
 - key-value kind: usual-key => multi-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CanonicalHeader'...
 - key-value kind: usual-key => single-value
 - last modification txn#4639681
 - summary: 9813576 records, 0 dups, 78508608 key's bytes, 314034432 data's bytes, 0 problems
Processing 'CliqueLastSnapshot'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CliqueSeparate'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'CliqueSnapshot'...
 - key-value kind: usual-key => single-value
 - last modification txn#4
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
Processing 'Code'...
 - key-value kind: usual-key => single-value
 - last modification txn#4639667
 ! corrupted broken-page #0, mod-txnid 0
 ! mismatch actual pgno (0) != expected (167984517)
 ! mdbx_cursor_get() failed, error -30797 MDBX_PAGE_NOTFOUND: Requested page not found
 - problems: different number of entries (1)
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 1 problems
 ! mdbx_cursor_get() failed, error -30782 MDBX_BAD_TXN: Transaction is not valid for requested operation, e.g. had errored and be must aborted, has a child, or is invalid
 - problems: different number of entries (1)
Total 6 errors are detected, elapsed 578.639 seconds.

**Comment by erthink** [comment]
> * ! corrupted broken-page #0, mod-txnid 0
>   ! mismatch actual pgno (0) != expected (167984517)

Your DB is corrupted.
The DB page `#167984517` seems is zeroed.
This cannot be fixed since (at least) this corruptions has occurred `4639682 - 4639667 = 15` transactions ago.

With a fairly high degree of confidence, I can assume that this is the result of a hardware failure, and not any software bug.
So you should check your hardware, especially RAM and disks.

**Comment by xiaogea01** [comment]
> 
Thank you [erthink](https://github.com/erthink)
It  means I have to sync from the beginning.Am i right?

**Comment by AskAlexSharov** [comment]
1. Check hardware 2. If it’s broken - change hardware 3. Then sync from beginning

**Comment by xiaogea01** [comment]
> 1. Check hardware 2. If it’s broken - change hardware 3. Then sync from beginning

I see , I have to resync , thank you [AskAlexSharov](https://github.com/AskAlexSharov) ,my  heart broken,thank you again [erthink](https://github.com/erthink)
