### ISSUE TITLE
why txpool result huge less than geth

### ISSUE THREAD

**Issue by kugimiya530** [ledgerwatch/erigon#3892]
Hi i have my own node 

geth and erigon

and i am using      web3 module  to result the PendingTransaction

and the result , erigon was less than geth (a lot)

any idea?

here is a little part of result  from  57s~60s

geth
`0x98d7cd2ac9e3817cf6d3e33fb3047dd00cd970a62186070635762656ba640fae 1649998357.086
0x2ef3ef7abccc055a8c28e0ade58d978c627f451e1da085cb6acf3d0a9915d4d9 1649998357.168
0x0830e254d9802ed1f2d1ab1473d1ddc0ba4f117409a371a7dd56049750ec6376 1649998357.209
0xd2c811086147b2c6fd9e46f1883acad4d088f96725353e6c0861a2baa54c09cf 1649998357.233
0xefdb33215055db3a005a67d1dc14686569e81bd0f2672b85dec28a7ad82096ad 1649998357.24
0xd56dadb1f35968c4630daaea69309251d65bd31bf5206d9fe0c7fc85fc07be7d 1649998357.257
0x3d9fe049020dc5f72880d41be0f094afa183c088921d9d4eb8fc5e3a1d58b00d 1649998357.291
0x150fb4041bb095298a3ac9bfcc759ddcf52402b73e848320613ba39ca9148a4a 1649998357.301
0xe0a2bcfe3a4d82c94eb0b0fa04b3bcf2a7fedabe558fd73a30750ff90722bfbc 1649998357.352
0x9da7a7e33d0e35b64e9cb887af9f506cb3854cf599a8672d3129b8e3c88c3585 1649998357.476
0x07e5f0128f9bef2a83904cf1f2b09f014bd0487d52b59b2ea3715a7c007cb19e 1649998357.527
0x1a7e0ef04a5953161c3125be4e9a7c5d299662c9d0ffb9b0de3e2bac30144374 1649998357.592
0x73b3e996b9fe47c3f37ff51bf231a26ec755324a002ae6aef17aff5832d5b3ab 1649998357.619
0x7af2175e8fe11b8b49dc6a5f19447b55e132db9b0fd957be21c04648813effa1 1649998357.688
0xacd1d5de5225d10f26f8f1707f704851b75fc1557db865a68f42fd3ef3ce009d 1649998357.701
0xf93d5159701271fd9ac874d21671ddd9b086cd9ca23ae48a2bff7d78cdc59a7c 1649998357.717
0x539613b847c02de797f7ad33c409f76433a3933c054762eb1fcf62a52a5d3b3c 1649998357.733
0x3f928d56eb1c58940cc6b59dfff7be20f0b05dc9cd1b18e0a5270768ab4d9cea 1649998357.74
0x4a4fd3986a3bd57c143696e2eb80270f5e818b85717185b1ce037e291726bf52 1649998357.798
0x0c54de6394d4b5de2721b61986b14fc409c9c5b395ec47f7636457e25e974643 1649998357.88
0xb0a71a1645ae2736a83a1c4b7a5804d47f10307430f606f4ef4534507da5da8b 1649998357.886
0x401039175cb712e883b25881723500cd6c7442009171705dc16c898c86bbdb33 1649998357.91
0x498f7120efd58f61bda1baf68d90de15edb7d616bac34a617659be4771bc20fc 1649998357.97
0x0901f90ccf29cc0098edc84e5f2422b6c089838c4f42d92c338eddd7f20a6830 1649998358
0x463c48297e5e2e1ea7615790b9eddc6504c2329cf35da5ddf3dbe82e62d7873f 1649998358.022
0xdff24d0874dd10fca400f8850039ef0cd0c19f6b721028d2aa47940614435f13 1649998358.024
0x9f022944d00240756e2611a4b96323400c2e32fe1db1a4f90d3d23b072c5babd 1649998358.075
0xcebe2bd672a375d9734005bc7c055bf8293f0394a273c202eda96f939ed37987 1649998358.104
0x5b5f7ea5c1e5fe3a8d60deb33f9dbbdd601de9fcd5a942124bde8533db027d37 1649998358.105
0x498cd4a6084c6b3cbe9cff11a0d05df50976fec73f56cf8aa78fa86cec7286fb 1649998358.11
0xe5a822c1e880f664b02310d8fd42e3f5e223cc1037056dd8bd407061b14cb274 1649998358.129
0x95d65c7de7c4a8d814a9e006999b991309dee3e842f14b4f1f7a4a0ac18467de 1649998358.168
0x62691b62a8c98cbb638ff691fc838047c749aa0da8103fd1d3e64f1956847b5b 1649998358.189
0x85d73158b54fac858edc967f522c9236f5196107b00c46d0df3983728e561bfe 1649998358.226
0x3ae0ae8cc995f044bae8b4f3b572eb36ef50c36e7deba80af77c88b890cf8543 1649998358.228
0x7731a874a41920d7285df12cc04a7bdb2a245eb92e99646067871049a6a10024 1649998358.27
0x2d83f0eb99d02269fd5146a51101861219905aec31106149cc860f458b4c7530 1649998358.273
0xc007044aef7a731c42dc54601f1609521ba938ab27229b234e28f47411194cad 1649998358.281
0x538a72c3cd9bfaeb23db344a9fb21d41ba0f547c6842912d1f0072b24f8c6e25 1649998358.361
0x8897864a766956a0db092f87e1ad45c4554137ab3cf1051ffedf60e87f50d2bc 1649998358.385
0x004f4ebb6f18163ecd6c21feace1ce4c14060cb4b48ccec4425b81994ffbf251 1649998358.422
0xbc07249378bb89ecbd69568fe6dc38c320eb6cb5d8a1d14fcfe4c98f8a29dab3 1649998358.426
0xbaf5e8d484c4bda5f8c3397622303dbbf3049e4b0e8ec88cccc05d81324d5441 1649998358.437
0xfb1783f7e9968ec53bd65c5d9e6ff696e0e60b31b210a727e2fee7c8bb760216 1649998358.438
0x9b22bd093b856700a4e2a2d20dc30c224096cd04019a748371d941fa79180858 1649998358.472
0x25e05f7c5ca2179e3411c27c10bc304391432f2f4c023eab2e0a19519996c4b6 1649998358.484
0x64e752d56c048fa69821e03ba29d8c4bc99eb7eefee53444c9a3a4afa8521460 1649998358.502
0x842b03916e5a8ac8211f48124a70cc281b59f7ca1f6289797a672844539e1cc3 1649998358.515
0xfde57df15d7f98df19c40c9f443422e18614bd2acf72d3c8ac5ddc3c9c845473 1649998358.526
0x1253b9b3b0e852336b7a02d55d61cff85122f33d02ce39e73bde1512b171533b 1649998358.564
0xd1c3a0d5b40b957e37f5b2f3b35f0bac1256aca7f61834291ebb4ff236915059 1649998358.649
0xa1c4010d539eb59fa18386363513c916c7af4c56e4700de7bd28bf9ba61450e1 1649998358.652
0x6a44ee04e2f196840515782ee10b0934ce925ea689258bab16190998d2f1e4d8 1649998358.676
0xe3081cfd52a07359658447ba7b3d696780846b77f449bb0821002a08d8cf971e 1649998358.699
0xecc86572590b25f491ab920eb40a417f41338418440d2d3d08828bae125f7d9e 1649998358.819
0x2b530913eaef57a794d29bcfa70408ef9d4d95dd54fca788eececb987ad84a3c 1649998358.823
0x52673ccf512bc65a04e964b12913a56eb998703d6fc5c3e8077477e7b19013fc 1649998358.832
0xb0ed43af82229caa06858b5e663e176ef6c0e52b0ec37d45d9bdf2851d79020c 1649998358.839
0x5247621e3fbb357f749701f59ada6f5f2501f353d4ffc8198a65ce23556bfe48 1649998358.979
0x4052b8c0b6c049a9642144cfb6dd335d6af38ef55ab458b6295a2dbb41649bd5 1649998358.996
0x2b73f235c4b3fe29f206e6b3f5fcde34089077059e622a325a44a5e1cba3e84b 1649998359.015
0xd0105f3caad66b2f145704e038d74055d1542eba3b9556b5825999edd1634210 1649998359.112
0x5a7079d576fcb6970a3379944c6c5c9913fa9421f14370f4968c36aa84b4e798 1649998359.123
0xbfd48c4dd09f845925ffaad5bd59b7dbfe53cc94b812a25d7702572e9c340b5c 1649998359.15
0xa2cbe0388e42e10447e40a282e43eedbb76775244a3c43089471f91938e4cfba 1649998359.152
0x288a7b326f2660b609b3b93c18da0638a7c72d647cf90f85567ed3a4c412e90a 1649998359.153
0xd7784f5c0cfb4e002c3c53eab6ede290e8d6a9fb7ff33a3099112d4f7c8db788 1649998359.164
0x00daef424f365a5becce1c6ffa62b325485156082197f7335d88c3da3b8d8733 1649998359.192
0x3fdb97694687c805993203f7f1cd283f872a65da79eac25e9a6c19374ba2f21e 1649998359.208
0x2fa589d6096ec9073cbd1de0960dac638c53c507686b914a97e744dbde6ac01c 1649998359.238
0xa6d9edbb85441c43bd0ab764200b7437111de5c26ae01ef1bf13d7967a3009e3 1649998359.289
0xfb04039d6e6796cf247e12daf60632b3c97c823a09721801b5f657df97654c2d 1649998359.318
0x6b580f1bd939ffe949ae4e98dbd59fb78bded72be48b265473e8936a326df800 1649998359.33
0xf21e7151956040899fdd8fc73124acb2a3392082d4c69551af6acc189bf990d9 1649998359.343
0x6eb4322294d9570e6b50508b416d903536e4ffc83e75d974d24c68e8f26bbc9a 1649998359.346
0x05133d7df5f82388213ca7a7cbbba7f66220fdc64f5f833a71bd62eba859b39c 1649998359.44
0x8b28571ec39091a081c48c9642a125c015cc27a6910119cf32d21b056df878e1 1649998359.447
0x10ab98594451ebc5af090bb72b2eb089496be3ab9e3a3f1740ce8e61a2e2ad22 1649998359.511
0x6a1885da3ab346fbeb15a25c1897209a4bfddb4cc3e1c425e1fc4d7e7f032ccf 1649998359.555
0x0255327804b856ec6d4a65855b67044f547f390b208b3217a67994f16d508e6d 1649998359.57
0xe2cce5558f1dbdee75b21b1cb15de2d3bc3c416515c174ad8455157d25a42577 1649998359.675
0x3664a5b4b58f3bf5dc9b6a2f75b544ea86c896d6bcea5fba71524900dac99b40 1649998359.701
0xdc1603432b41c7746075512eab0ec0c8455b3f5991f6c70320807414cec780d6 1649998359.727
0x96cc0a893e3fbf233102eb103f0837b562985a8343a18099a3b471057fcbd43d 1649998359.736
0xf966eff79c13a3995897707d409e660a7bd0764199206ca9d9d4e335eae13541 1649998359.738
0x4c55d759e5c14828cc189f6fd3b0efd3b82686932f2856a953864e48d96e8258 1649998359.74
0x995f60e927fbda7291c93abc1ebfedc7d3c6414f797cead899d4432bdac939d4 1649998359.809
0x5e1afd9dffea150dbe5168daf0344236f630b1d2e412758b18c1bc84319fdfa2 1649998359.852
0xfde3c48c01ba0235acb26cb6eecaa117140be981600a01db91cd5f3282c469a9 1649998359.869
0x9a508793d153683793d1625a34044f365b354a2238dfb319b13d481ed8af3aac 1649998359.909
0x1b94c02bb24d179c0b666e6f29cbd7960527ba9ca46774e0b03de789bc40b373 1649998359.91
0x1f9f3955f526af240d2fd6bb17e0928357c8a63806905836536df97541a0e114 1649998359.924
0xbdbd39cad781ddbef21f000a82a7e0ede912064a03cd1bfe304db4a95313b92b 1649998359.992
0x496eca383be1fbe9b4fc365b4da2669ebeb9d7da1836668866c5dd504db31e6a 1649998360.041
0x4d81370a4fee9214013e1c8952f106035de91053e787fecc7d41e0a24077dc2d 1649998360.074
0x59db506088abbf4371e62b681417e9e3a705a179c043a5cb9d1c1f60c4ab5022 1649998360.144
0x28ce2410af1786ee4e24d59569ee32e4edb94d568cfa6c775c0d1f5b883b9a41 1649998360.18
0x6ada50a0e7618c6f142c8d23c8c2a49068bac65377be72197c8909ebd392dc9d 1649998360.317
0xead593ec9799f43a9c873510c8ab72dea6e8ac377af3a438ed4f495a15f25934 1649998360.454
0x77103ede1459b22a2f80edb6e6ecb1d8e863c36853f0e100fb52ada0b717c43e 1649998360.51
0xcd92ee94d4846aba087ca332acedc87a3936e0f2a5497fc143acaa414a0dd98c 1649998360.587
0xdd6d47623fde249d7a6f937eb08fb151502f8bc74bc3fa467c40fabe4787bafd 1649998360.587
0xb2120f7cb05502612d4deae0397f688637fb4615e038ab1314f562d25d8dce1e 1649998360.667
0x74431d0ea7b4233aeb7278181c74c1b42b9070b1292d63f30bc4d0a317c03278 1649998360.668
0x036c83e95707fed60f481a2f5ff0e6842cee78fffe4693b3ad6f9dad636338e2 1649998360.681
0xaae725b1c0ae23f7b93c09e5f2476f10696465848bca3e56061be31c9f1b9053 1649998360.693
0xdd51ebd12f8b174c0ebfde2199c599f128d77b99390ee49cd8948afcf9b616b1 1649998360.71
0x48f5f9236aea8efccc53181234517b5c3f31c8281225e968822665a65b179a0e 1649998360.748
0xc1cc341beeb15cc96424030a844202c1bbcc348f949e5a2888c4cd8f89d07f79 1649998360.752
0x4cac2e194e1984e36ee62257fd4cb4693a2182994386cb60f4e44926c7a8047c 1649998360.765
0x79de5955b7c3902ce2ec3de33329cf7f882d3b114063ceae2e48ac5542ecbf60 1649998360.781
0x4e15084d47d72f10e821aec498778592af5daddeaf150438ce2a358480d1e575 1649998360.791
0x07b0982efa6cd5955d0c3566c23d32164e59156a9923a025b5b1cd930538baf0 1649998360.801
0x607fa584da470dfa55d6c2b69cb3b44d1bf1b8530c9b70283e2fed05504077e6 1649998360.804
0xc66427e2837c3d61183c92f1e011abb03a3728e0be881c76fd061c13777c1643 1649998360.82
0x55f1c011f00e8cd0495019e894e548d1acf40d07d7b9ecfb6df6d69749126767 1649998360.852
0x3b0da5ec48c8d3ea686ab5ec535e8b55dbee70db0fe8d1d3f92382bef4ad2efe 1649998360.915
0x73d5c6ce24ccf6a54cf5c89738225831271c26c07d35724fb1d9261dfdd9c335 1649998360.915
0x2767d00b42910c6c0470b87143c545f8ccef4a1b6bc99e2b9ed7fedfc98106d9 1649998360.967
0x923d390d2feb4e5cee0f1aa58600ae4263ccdad162edddbc06116a2c210bcf46 1649998360.967
0x1718727d5bf9cb6ed83839a441fd25ddfe23fac1017c8fed7290903f18b9b023 1649998360.996
0xe45b060806c5ea03c33392b9b49f5e519a735e03cb123ce533776015490ceeba 1649998360.997`

Erigon

`0x98d7cd2ac9e3817cf6d3e33fb3047dd00cd970a62186070635762656ba640fae 1649998357.144
0x0830e254d9802ed1f2d1ab1473d1ddc0ba4f117409a371a7dd56049750ec6376 1649998357.244
0x150fb4041bb095298a3ac9bfcc759ddcf52402b73e848320613ba39ca9148a4a 1649998357.344
0xe0a2bcfe3a4d82c94eb0b0fa04b3bcf2a7fedabe558fd73a30750ff90722bfbc 1649998357.444
0x07e5f0128f9bef2a83904cf1f2b09f014bd0487d52b59b2ea3715a7c007cb19e 1649998357.544
0x1a7e0ef04a5953161c3125be4e9a7c5d299662c9d0ffb9b0de3e2bac30144374 1649998357.644
0x539613b847c02de797f7ad33c409f76433a3933c054762eb1fcf62a52a5d3b3c 1649998357.743
0x3f928d56eb1c58940cc6b59dfff7be20f0b05dc9cd1b18e0a5270768ab4d9cea 1649998357.844
0x0c54de6394d4b5de2721b61986b14fc409c9c5b395ec47f7636457e25e974643 1649998357.944
0x0901f90ccf29cc0098edc84e5f2422b6c089838c4f42d92c338eddd7f20a6830 1649998358.043
0x498cd4a6084c6b3cbe9cff11a0d05df50976fec73f56cf8aa78fa86cec7286fb 1649998358.143
0x3ae0ae8cc995f044bae8b4f3b572eb36ef50c36e7deba80af77c88b890cf8543 1649998358.244
0x2d83f0eb99d02269fd5146a51101861219905aec31106149cc860f458b4c7530 1649998358.344
0x004f4ebb6f18163ecd6c21feace1ce4c14060cb4b48ccec4425b81994ffbf251 1649998358.443
0x25e05f7c5ca2179e3411c27c10bc304391432f2f4c023eab2e0a19519996c4b6 1649998358.544
0x1253b9b3b0e852336b7a02d55d61cff85122f33d02ce39e73bde1512b171533b 1649998358.644
0x6a44ee04e2f196840515782ee10b0934ce925ea689258bab16190998d2f1e4d8 1649998358.744
0x2b530913eaef57a794d29bcfa70408ef9d4d95dd54fca788eececb987ad84a3c 1649998358.843
0x52673ccf512bc65a04e964b12913a56eb998703d6fc5c3e8077477e7b19013fc 1649998358.944
0x2b73f235c4b3fe29f206e6b3f5fcde34089077059e622a325a44a5e1cba3e84b 1649998359.043
0x5a7079d576fcb6970a3379944c6c5c9913fa9421f14370f4968c36aa84b4e798 1649998359.144
0x00daef424f365a5becce1c6ffa62b325485156082197f7335d88c3da3b8d8733 1649998359.244
0x2fa589d6096ec9073cbd1de0960dac638c53c507686b914a97e744dbde6ac01c 1649998359.344
0x05133d7df5f82388213ca7a7cbbba7f66220fdc64f5f833a71bd62eba859b39c 1649998359.443
0x10ab98594451ebc5af090bb72b2eb089496be3ab9e3a3f1740ce8e61a2e2ad22 1649998359.544
0x0255327804b856ec6d4a65855b67044f547f390b208b3217a67994f16d508e6d 1649998359.643
0x3664a5b4b58f3bf5dc9b6a2f75b544ea86c896d6bcea5fba71524900dac99b40 1649998359.743
0x4c55d759e5c14828cc189f6fd3b0efd3b82686932f2856a953864e48d96e8258 1649998359.843
0x1b94c02bb24d179c0b666e6f29cbd7960527ba9ca46774e0b03de789bc40b373 1649998359.944
0xbdbd39cad781ddbef21f000a82a7e0ede912064a03cd1bfe304db4a95313b92b 1649998360.043
0x496eca383be1fbe9b4fc365b4da2669ebeb9d7da1836668866c5dd504db31e6a 1649998360.144
0x28ce2410af1786ee4e24d59569ee32e4edb94d568cfa6c775c0d1f5b883b9a41 1649998360.243
0x6ada50a0e7618c6f142c8d23c8c2a49068bac65377be72197c8909ebd392dc9d 1649998360.343
0x77103ede1459b22a2f80edb6e6ecb1d8e863c36853f0e100fb52ada0b717c43e 1649998360.543
0xcd92ee94d4846aba087ca332acedc87a3936e0f2a5497fc143acaa414a0dd98c 1649998360.644
0x036c83e95707fed60f481a2f5ff0e6842cee78fffe4693b3ad6f9dad636338e2 1649998360.743
0x07b0982efa6cd5955d0c3566c23d32164e59156a9923a025b5b1cd930538baf0 1649998360.844
0x3b0da5ec48c8d3ea686ab5ec535e8b55dbee70db0fe8d1d3f92382bef4ad2efe 1649998360.944`

**Comment by kugimiya530** [comment]
any updated..?

**Comment by AskAlexSharov** [comment]
@kugimiya530 hi. is this issue still exist? how to read your output?

**Comment by AskAlexSharov** [comment]
@kugimiya530 hi. is this issue still exist? how to read your output?

**Comment by AskAlexSharov** [comment]
Same complains: 
https://github.com/ledgerwatch/erigon/issues/3373#issuecomment-1051085411 
https://github.com/ledgerwatch/erigon/issues/3373#issuecomment-1149245943

**Comment by AskAlexSharov** [comment]
Just nobody started working on this yet, we focus on https://erigon.substack.com/p/erigon-2-three-upgrades?s=r

**Comment by Sleapy31** [comment]
Ok nvm

**Comment by u39kun** [comment]
Posted my fix here: https://github.com/ledgerwatch/erigon-lib/pull/555

Essentially, newPendingTransactions push was throttled to at most 1 new pending transaction per 100ms as you can see in the log above.  The fix removes this.

**Comment by Sleapy31** [comment]
> Posted my fix here: [ledgerwatch/erigon-lib#555](https://github.com/ledgerwatch/erigon-lib/pull/555)
> 
> Essentially, newPendingTransactions push was throttled to at most 1 new pending transaction per 100ms as you can see in the log above. The fix removes this.

Thank you ! it seems to be working now.
Geth is still around 10ms faster for me but at least erigon can compete

**Comment by revitteth** [comment]
Closing this one as it seems to be fixed :)
