### ISSUE TITLE
Sync stuck on Kiln

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#3899]
Reported by OhraeMez on [Discord](https://discord.com/channels/687972960811745322/906989870419959818/964561261536878643):

i am testing erigon on the kiln testnet and have an issue when doing checkpoint sync in lighthouse and a fresh erigon instance. erigon syncs up to about 20 blocks from head and then gets stuck there. (see log file)
but when i restart erigon it catches up to head.

[erigon_sync.txt](https://github.com/ledgerwatch/erigon/files/8499560/erigon_sync.txt)

**Comment by yperbasis** [comment]
Might be already fixed by PR #3888.

**Comment by mandrigin** [comment]
@yperbasis please reopen if still valid
