### ISSUE TITLE
Ethstats crash - invalid memory address

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#3948]
#### System information

Erigon version: `git_branch=devel git_tag=v2022.04.03 git_commit=3ad25c929c992575412264b4fa0d6f0a213c4cca`

OS & Version: Linux

Commit hash : `3ad25c929c992575412264b4fa0d6f0a213c4cca`

#### Expected behaviour
Don't crash

#### Actual behaviour
```
[INFO] [04-23|15:46:36.016] [Snapshots] Fetching torrent files metadata 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe25bb8]

goroutine 6603 [running]:
github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0x13a52ce?)
	github.com/ledgerwatch/erigon/core/types/block.go:1312 +0x38
github.com/ledgerwatch/erigon/ethstats.(*Service).reportBlock(0xc0074fc900, 0x1?, 0x0)
	github.com/ledgerwatch/erigon/ethstats/ethstats.go:508 +0x111
github.com/ledgerwatch/erigon/ethstats.(*Service).report(0xc0094c7e20?, 0xc0094c7c80?)
	github.com/ledgerwatch/erigon/ethstats/ethstats.go:412 +0x3b
github.com/ledgerwatch/erigon/ethstats.(*Service).loop(0xc0074fc900)
	github.com/ledgerwatch/erigon/ethstats/ethstats.go:222 +0x63f
created by github.com/ledgerwatch/erigon/ethstats.(*Service).Start
	github.com/ledgerwatch/erigon/ethstats/ethstats.go:148 +0x5a
```

#### Steps to reproduce the behaviour
I'm not sure exactly how to reproduce because it was working fine yesterday, but that was during the download stage, while I was getting torrent data. Now I'm in the execution stage... it happens every time I restart Erigon with this flags now:
`--ethstats="archivenode.io - node04:<redacted>@wss://ethstats.net/api"`

**Comment by MysticRyuujin** [comment]
I guess I'll ping @Giulio2002 for this one :slightly_smiling_face:

**Comment by Giulio2002** [comment]
Fixed in https://github.com/ledgerwatch/erigon/pull/3951
