### ISSUE TITLE
"method handler crashed" calling eth_getTransactionReceipt

### ISSUE THREAD

**Issue by richardklafter** [ledgerwatch/erigon#3954]
#### System information

Erigon version: `erigon version 2022.99.99-dev-25ab6455`

OS & Version: Linux using default docker-compose.yml

#### Expected behaviour
Returns TransactionReceipt JSON

#### Actual behaviour
Call to eth_getTransactionReceipt errors with:
```
curl -X POST -s --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xcc2588e34ed1111cf1553c0b0884c4069c0173b2073af76bc29196707dee7bbc"],"id":1}' http://localhost:8545/ -H "Content-Type: application/json" | jq . 
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "method handler crashed"
  }
}
```
rpc logs say:
```
rpcdaemon_1   | [EROR] [04-24|23:31:18.121] RPC method eth_getTransactionReceipt crashed: runtime error: index out of range [0] with length 0
rpcdaemon_1   | [service.go:217 panic.go:1038 panic.go:90 block_reader.go:569 block_reader.go:602 block_snapshots.go:312 block_reader.go:601 eth_backend.go:186 eth_api.go:136 eth_receipts.go:271 value.go:556 value.go:339 service.go:222 handler.go:484 handler.go:389 handler.go:343 handler.go:181 handler.go:271 asm_amd64.s:1581] 
rpcdaemon_1   | [WARN] [04-24|23:31:18.121] Served                                   conn=172.27.0.1:56976 method=eth_getTransactionReceipt reqid=1 t=292.978µs err="method handler crashed"
```
Most calls to `eth_getTransactionReceipt` work fine but about 1% error with this error.

#### Steps to reproduce the behavior
`curl -X POST -v -s --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xcc2588e34ed1111cf1553c0b0884c4069c0173b2073af76bc29196707dee7bbc"],"id":1}' http://localhost:8545/ -H "Content-Type: application/json"`

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/erigon/pull/3957

**Comment by richardklafter** [comment]
Thanks! I will give it a test.
