### ISSUE TITLE
Can't build because repo of libmdbx submodule has been deleted

### ISSUE THREAD

**Issue by tsutsu** [ledgerwatch/erigon#3965]
```
fatal: repository 'https://github.com/erthink/libmdbx/' not found
fatal: clone of 'https://github.com/erthink/libmdbx' into submodule path '/home/tsutsu/erigon/libmdbx' failed
```

**Comment by tsutsu** [comment]
This may have been due to my rebase on a branch not pulling in submodule updates, sorry

**Comment by AskAlexSharov** [comment]
Github censured (removed) https://github.com/erthink/libmdbx repo. Available solutions:
- update erigon version
- change submodule to point to https://github.com/torquem-ch/libmdbx
