### ISSUE TITLE
Block missing from archive node

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#3967]
#### System information

Erigon version: devel v2022.04.02
OS & Version: Linux debian
Commit hash : 89c30492447a20c4ab21b914e75b057e7ffb9576

#### Issue

I'm running an archive node and looks like block #14178113 is missing from the database.
Found out while running `trace_filter`. The erros message I get is
`Returned error: block 6eeed65f3f2424f3aa7925beeab24fda778a006bc7bcb8d2b2eb7149401c7e0b not found`

Additionally when trying `eth_getBlock("14178113") ` erigon returns `null`

`trace_filter` and `eth_getBlock` for blocks before and after the one in question return expected results.

Edit: looks like thats not the only block that is missing. I'm getting the same error with other blocks aswell when trying to trace a different range.
`Returned error: block 47ae2b468a0f008b6bb6cf7cd24393f33e01081d35c2e8b7defcb5a19bc9ca9f not found`

**Comment by geomad** [comment]
**UPDATE:** 
I fully resynced the node, using the erigon 2 alpha version from devel (hash: 47f492663ee48fd15aa5bc52ff82211b658e44be)
Now `trace_filter` is getting a different error. The error appears in a block a bit after the start of the tracing range.
`Returned error: parent header 13603717(b855ab229a1ea2fe3aa94cbbd6c7eaa7227c3f22381d24cdd46736a402d96664) not found`
This happens in every block range (1000+ blocks) I tried
The difference now is that eth_getBlock can now sucessfully retrive the block in question and the blocks around it.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/4042

**Comment by UliGall** [comment]
Do I need to resync my node to fix the issue after updating erigon?

**Comment by AskAlexSharov** [comment]
no
