### ISSUE TITLE
"method handler crashed" calling eth_getTransactionReceipt 

### ISSUE THREAD

**Issue by glemmatim** [ledgerwatch/erigon#3979]
#### System information
Erigon version:  2022.04.3-alpha-61515ed2

OS & Version: Ubuntu 20.04.4 LTS

#### Expected behaviour
Returns TransactionReceipt JSON

#### Actual behaviour
Call to eth_getTransactionReceipt errors with:

`curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_getTransactionReceipt","params":["0xa83c3d0d0523450bf2e4f016ac5b3c4239fe450a5f8742091a36b090619ac201"],"id":1,"jsonrpc":"2.0"}'`

`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}`

RPC daemon error: 
`rpcdaemon[25645]: [service.go:217 panic.go:838 panic.go:117 block_reader.go:588 block_reader.go:614 block_snapshots.go:312 block_reader.go:613 eth_backend.go:187 eth_api.go:136 eth_receipts.go:271 value.go:556 value.go:339 service.go:222 handler.go:484 handler.go:389 handler.go:343 handler.go:181 handler.go:271 asm_amd64.s:1571]`

#### Steps to reproduce the behaviour
get transaction receipt. Error appears for about 5% of transactions in a block. Some other examples; 
0x75005f58e2ecbbebeeee72094c04f32d8d74a2eb5c725799bb5e929ba6587502
0x4e199140e0db12681414201f05d008e30baa220508b99e540d699af86547fe02
0xa83c3d0d0523450bf2e4f016ac5b3c4239fe450a5f8742091a36b090619ac201
0x7e0a63e790cfb08202c1f446913f002cfe9b681f90f56bfa3e0f60775f4d6e42

curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_getTransactionReceipt","params":["0x75005f58e2ecbbebeeee72094c04f32d8d74a2eb5c725799bb5e929ba6587502"],"id":1,"jsonrpc":"2.0"}'

Might be related to the issue that got closed 2 days ago: 
https://github.com/ledgerwatch/erigon/issues/3954

**Comment by AskAlexSharov** [comment]
I will take a look

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/4012

**Comment by glemmatim** [comment]
Works great now 👍. Thanks!
