### ISSUE TITLE
Question - Torrent port and speed 

### ISSUE THREAD

**Issue by breezytm** [ledgerwatch/erigon#4001]
Does using the torrent port flag ``--torrent.port `` and opening the set port speed up the snapshot downloading process? 

```
[INFO] [04-27|17:51:47.388] [Snapshots] download                     progress=34.41% download="256.5 KiB/s"
[INFO] [04-27|17:52:18.288] [Snapshots] download                     progress=34.41% download="258.1 KiB/s"
[INFO] [04-27|17:52:47.535] [Snapshots] download                     progress=34.41% download="270.4 KiB/s"
[INFO] [04-27|17:53:17.658] [Snapshots] download                     progress=34.42% download="275.7 KiB/s"
[INFO] [04-27|17:53:24.780] [p2p] GoodPeers                          eth66=33
[INFO] [04-27|17:53:47.691] [Snapshots] download                     progress=34.42% download="289.6 KiB/s"
[INFO] [04-27|17:54:18.032] [Snapshots] download                     progress=34.42% download="272.0 KiB/s"

````

**Comment by suspended** [comment]
Yes, just add  `--torrent.download.rate 100mb` flag when starting erigon

**Comment by AskAlexSharov** [comment]
1. If --torrent.port default value is 42069, yes need open it on firewall of tcp and udp
2. --torrent.download.rate 100mb
3. Update to latest devel, I just merged to devel new flag: `--torrent.download.slots`- `amount of files to download in parallel. If network has enough seeders 1-3 slot enough, if network has lack of seeders increase to 5-7 (too big value will slow down everything)` - so switch to latest devel will speedup things for you.
