### ISSUE TITLE
Observer - Panic

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#4002]
#### System information

erigon version 2022.04.4-alpha-f3065a11

Linux ethereum-erigon2 5.4.0-109-generic # 123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

#### Steps to reproduce the behaviour

./observer --chain mainnet --datadir /mnt/data 

#### Trace

````bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1201262]

goroutine 125 [running]:
github.com/ledgerwatch/erigon/cmd/observer/observer.(*Crawler).Run.func1()
        github.com/ledgerwatch/erigon/cmd/observer/observer/crawler.go:310 +0x102
created by github.com/ledgerwatch/erigon/cmd/observer/observer.(*Crawler).Run
        github.com/ledgerwatch/erigon/cmd/observer/observer/crawler.go:304 +0x1185

````

**Comment by battlmonstr** [comment]
@Texnomic thanks for the report.
It is fixed now on the `devel` branch. Please rebuild from there.

@AskAlexSharov I somehow decided that `(nil, nil)` is a valid output there, but forgot to check for it. I didn't notice, because all of my recent tests were not starting from scratch 😓
