### ISSUE TITLE
torrent.download.rate

### ISSUE THREAD

**Issue by kugimiya530** [ledgerwatch/erigon#4006]
where can i modify this value

download speed it's so slow... limit at 8Mbit

**Comment by suspended** [comment]
Just add  `--torrent.download.rate 100mb` flag when starting erigon

**Comment by AskAlexSharov** [comment]
1. If --torrent.port default value is 42069, yes need open it on firewall of tcp and udp
2. --torrent.download.rate 100mb
3. Update to latest devel, I just merged to devel new flag: --torrent.download.slots - amount of files to download in parallel. If network has enough seeders 1-3 slot enough, if network has lack of seeders increase to 5-7 (too big value will slow down everything) - so switch to latest devel will speedup things for you.

**Comment by breezytm** [comment]
Great. Is that available in the devel docker image in the docker hub? Currently i am using alpha image, would i have an issue with DB if i switch over to devel?

**Comment by AskAlexSharov** [comment]
docker hub `latest` points to devel

**Comment by AskAlexSharov** [comment]
switch from alpha to devel is ok

**Comment by breezytm** [comment]
I will give it a try now. Thanks

**Comment by kugimiya530** [comment]
hi what is snapshot 's  size  ... cuz  download so slow

**Comment by breezytm** [comment]
@AskAlexSharov It seems to be downloading much faster than before. 

```
[INFO] [04-28|07:21:58.847] [p2p] GoodPeers                          eth66=33
[INFO] [04-28|07:22:00.762] [Snapshots] download                     progress="23.65% 49.1Gb/207.5Gb" download=1.4Mb/s upload=214.4Kb/s peers=102 connections=383 files=87
[INFO] [04-28|07:22:06.977] [Snapshots] download                     progress="23.66% 49.1Gb/207.5Gb" download=1.3Mb/s upload=163.2Kb/s peers=103 connections=383 files=87
[INFO] [04-28|07:22:13.644] [Snapshots] download                     progress="23.66% 49.1Gb/207.5Gb" download=2.1Mb/s upload=118.4Kb/s peers=104 connections=381 files=87
[INFO] [04-28|07:22:20.704] [Snapshots] download                     progress="23.67% 49.1Gb/207.5Gb" download=1.9Mb/s upload=227.2Kb/s peers=107 connections=388 files=87
[INFO] [04-28|07:22:26.977] [Snapshots] download                     progress="23.67% 49.1Gb/207.5Gb" download=1.8Mb/s upload=147.2Kb/s peers=107 connections=387 files=87
[INFO] [04-28|07:22:33.644] [Snapshots] download                     progress="23.68% 49.1Gb/207.5Gb" download=2.4Mb/s upload=153.6Kb/s peers=109 connections=387 files=87
[INFO] [04-28|07:22:40.642] [Snapshots] download                     progress="23.69% 49.2Gb/207.5Gb" download=2.2Mb/s upload=326.4Kb/s peers=111 connections=394 files=87
[INFO] [04-28|07:22:46.977] [Snapshots] download                     progress="23.69% 49.2Gb/207.5Gb" download=2.7Mb/s upload=262.4Kb/s peers=109 connections=391 files=87
[INFO] [04-28|07:22:53.644] [Snapshots] download                     progress="23.71% 49.2Gb/207.5Gb" download=5.8Mb/s upload=291.2Kb/s peers=111 connections=394 files=87
[INFO] [04-28|07:23:00.833] [Snapshots] download                     progress="23.72% 49.2Gb/207.5Gb" download=1.5Mb/s upload=291.2Kb/s peers=108 connections=381 files=87
[INFO] [04-28|07:23:06.977] [Snapshots] download                     progress="23.73% 49.2Gb/207.5Gb" download=3.1Mb/s upload=281.6Kb/s peers=107 connections=385 files=87
```

**Comment by AskAlexSharov** [comment]
1. Please avoid abstract phrases like “ so slow” - it’s more likely that we can help if you show logs, say your erigon version, formulate problem more concreet. What speed you had in the past? 
2. I gave steps: https://github.com/ledgerwatch/erigon/issues/4006#issuecomment-1111797298   did you? 
3. @breezytm  try increase to 6?
4. It will get faster with time: more peers, better geo locality of peers, we will create more our seed machines, we will get more experience with bittorrent protocol. 
5. snapshots are 2 times more compact than previous version of sync (need download 2 times less things): https://erigon.substack.com/p/disk-footprint-changes-in-new-erigon?s=r
6. if you facing some unacceptable downtime: use —syncmode=full (it switch back to previous version of sync).

**Comment by AskAlexSharov** [comment]
FYI: we found that user had slow download speed because his port was closed. Please check that port 42069 is open for TCP and UDP (by firewal, in your Docker ports mapping, etc…) https://github.com/ledgerwatch/erigon#default-ports-and-protocols--firewalls

**Comment by breezytm** [comment]
i just realized i added tcp to the container but not udp and that was slowing me down. for others who might come across this 
``-p 42069:42069/tcp -p 42069:42069/udp``
my download speed is about 3-5x now
