### ISSUE TITLE
POA signer missing ERROR

### ISSUE THREAD

**Issue by LenChoi** [ledgerwatch/erigon#4026]
./erigon --datadir lastnode/ --syncmode 'full' --port 30311  --http.api 'personal,db,eth,net,web3,txpool,miner'

./erigon --datadir=test3 --chain dev --private.api.addr=localhost:9091 --staticpeers "enode://7c36cfbde3a2d61218e4c68fe03549d2b23cf2c5e94cee68554cfde1ea93a61651d8f40c47076077a5416522e0d719348a8adbb52da162332b6af964f68f108b@127.0.0.1:30311" --nodiscover --mine --miner.etherbase="c40100104341ab6e315060811532f0c3712dcb54"

INFO[04-29|16:42:42.214] Initialising Ethereum protocol           network=1337
INFO[04-29|16:42:42.214] Effective                                prune_flags="--prune=" snapshot_flags=
INFO[04-29|16:42:42.246] Starting private RPC server              on=localhost:9091
INFO[04-29|16:42:42.246] new subscription to logs established 
EROR[04-29|16:42:42.248] Etherbase account unavailable locally    err=nil
EROR[04-29|16:42:42.248] Erigon startup                           err="signer missing: %!w(<nil>)"

I built a private network with ./erigon init genesis.json.(POA)
I have added a signer to genesis.json and I am trying to mine with the signer account, but an error appears.

err="signer missing: %!w(<nil>)"

How can we solve this problem?
And can't I access the console like geth?

**Comment by AskAlexSharov** [comment]
you can try to add --miner.sigfile
