### ISSUE TITLE
Node killed when building indices

### ISSUE THREAD

**Issue by SamuelArlig** [ledgerwatch/erigon#4035]
#### System information

Erigon version: 2022.04.4-alpha

OS & Version: Ubuntu 20.04.4 LTS

Commit hash : f3065a11

#### Expected behaviour

While syncing a fresh node with flags:
prune_flags="--prune=c --prune.h.older=5000000 --prune.r.older=5000000 --prune.t.older=5000000"
snapshot_flags="--syncmode=snap"

after the snapshots are downloaded the node should build indices

#### Actual behaviour

On "[snapshots] HeadersIdx                   blockNum=6500000" the computer freezes and  the erigon node process gets killed after some time

#### Steps to reproduce the behaviour

Sync a fresh node and wait until all snapshots are downloaded

#### Backtrace

INFO[04-30|11:13:43.000] [Snapshots] download                     progress="207.5 GiB" download="0 B/s" torrent_peers=35 connections=140
INFO[04-30|11:14:03.009] [Snapshots] download                     progress="207.5 GiB" download="0 B/s" torrent_peers=35 connections=145
INFO[04-30|11:14:23.000] [Snapshots] download                     progress="207.5 GiB" download="0 B/s" torrent_peers=33 connections=147
INFO[04-30|11:14:50.240] [p2p] GoodPeers                          eth66=100
INFO[04-30|11:16:50.240] [p2p] GoodPeers                          eth66=100
INFO[04-30|11:18:50.337] [p2p] GoodPeers                          eth66=100
INFO[04-30|11:20:53.953] [p2p] GoodPeers                          eth66=100
INFO[04-30|11:22:28.295] [snapshots] Build indices                from=0
why? 0, 0, 500000, 14499999, 0
sn: 14499999, 0
    == Snapshots, Header
0,  true
500000,  true
1000000,  true
1500000,  true
2000000,  true
2500000,  true
3000000,  true
3500000,  true
4000000,  true
4500000,  true
5000000,  true
5500000,  true
6000000,  true
6500000,  true
7000000,  true
7500000,  true
8000000,  true
8500000,  true
9000000,  true
9500000,  true
10000000,  true
10500000,  true
11000000,  true
11500000,  true
12000000,  true
12500000,  true
13000000,  true
13500000,  true
14000000,  true
    == Snapshots, Body
0,  true
500000,  true
1000000,  true
1500000,  true
2000000,  true
2500000,  true
3000000,  true
3500000,  true
4000000,  true
4500000,  true
5000000,  true
5500000,  true
6000000,  true
6500000,  true
7000000,  true
7500000,  true
8000000,  true
8500000,  true
9000000,  true
9500000,  true
10000000,  true
10500000,  true
11000000,  true
11500000,  true
12000000,  true
12500000,  true
13000000,  true
13500000,  true
14000000,  true
    == Snapshots, Txs
0,  true, true
500000,  true, true
1000000,  true, true
1500000,  true, true
2000000,  true, true
2500000,  true, true
3000000,  true, true
3500000,  true, true
4000000,  true, true
4500000,  true, true
5000000,  true, true
5500000,  true, true
6000000,  true, true
6500000,  true, true
7000000,  true, true
7500000,  true, true
8000000,  true, true
8500000,  true, true
9000000,  true, true
9500000,  true, true
10000000,  true, true
10500000,  true, true
11000000,  true, true
11500000,  true, true
12000000,  true, true
12500000,  true, true
13000000,  true, true
13500000,  true, true
14000000,  true, true
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
seg with nil idx: 0,500000
==== end debug print ====
WARN[04-30|11:22:30.977] [RecvUploadMessage]                      err="runtime error: invalid memory address or nil pointer dereference, trace: [downloader.go:181 panic.go:838 panic.go:220 signal_unix.go:818 index.go:146 block_reader.go:478 block_reader.go:202 block_snapshots.go:245 block_snapshots.go:643 block_reader.go:191 handlers.go:102 downloader.go:612 kv_mdbx.go:639 downloader.go:611 downloader.go:735 downloader.go:206 downloader.go:160 backend.go:807 asm_amd64.s:1571]"
INFO[04-30|11:22:50.791] [p2p] GoodPeers                          eth66=99
INFO[04-30|11:22:50.787] [snapshots] HeadersIdx                   blockNum=2500000 alloc="9.6 GiB" sys="10.3 GiB"
INFO[04-30|11:24:51.152] [p2p] GoodPeers                          eth66=98
INFO[04-30|11:26:51.918] [p2p] GoodPeers                          eth66=99
INFO[04-30|11:26:55.992] [snapshots] HeadersIdx                   blockNum=3000000 alloc="7.9 GiB" sys="10.8 GiB"
INFO[04-30|11:27:18.150] [snapshots] HeadersIdx                   blockNum=6500000 alloc="10.1 GiB" sys="10.9 GiB"
Killed

**Comment by eval-exec** [comment]
Whati's your memory infomation please.
```bash
free -h
```

**Comment by SamuelArlig** [comment]
total        used        free      shared  buff/cache   available
    Mem:           15Gi       2,9Gi       7,2Gi        60Mi       5,3Gi        12Gi
    Swap:            0B          0B          0B

**Comment by eval-exec** [comment]
Your erigon node was killed by kernel OOM killer, maybe your 16GB memory is
insufficient.

**Comment by SamuelArlig** [comment]
I tried adding an 8gb swap file, seems to have helped the situation somewhat but still got killed at `[Snapshots Indexing] TransactionsIdx`

**Comment by AskAlexSharov** [comment]
Thank. I know how to reduce RAM usage here.

**Comment by AskAlexSharov** [comment]
fixed in devel

F

**Comment by SamuelArlig** [comment]
Haven't had the chance to try the fix yet, but thanks very much!
