### ISSUE TITLE
tracing returns 'parent header not found' before block #14500003

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#4040]
#### System information

Erigon version: v2022.04.04 (devel)
Commit hash : 47f492663ee48fd15aa5bc52ff82211b658e44be
Machine specs: 64 GB ram, AMD 3900x, 4TB Nvme gen4 ssd
OS & Version: Linux Debian

#### Expected behavior
 `trace_filter` and `trace_replayTransaction` return expected results in old blocks (before #14500003)

#### Actual behavior
rpc returns `Returned error: parent header 13603717(b855ab229a1ea2fe3aa94cbbd6c7eaa7227c3f22381d24cdd46736a402d96664) not found`

The node is an archive node without any pruning flags set up.
` Effective                                prune_flags="--prune=" snapshot_flags="--syncmode=snap"`
 `eth_getBlock` returns expected results.
 
Not sure if this is related: When the node finished the initial fresh sync, and started syncing the rest of the remaining blocks to find the tip of the chain, it was stuck on receiving headers for the same block (not sure which one since I restarted the server and lost the logs), and I had to restart it. After that it finished syncing normally.

**Comment by AskAlexSharov** [comment]
here is the fix https://github.com/ledgerwatch/erigon/pull/4042
