### ISSUE TITLE
Erigon sync failure

### ISSUE THREAD

**Issue by dcposch** [ledgerwatch/erigon#4080]
#### System information

erigon version 2022.04.3-alpha-62c3775

Ubuntu 20.04

#### Expected behaviour

Finish syncing.

#### Actual behaviour

Got to step 9/16 after a few days, then print some enigmatic errors, then stuck at 1/16 indefinitely.

Errors include `consensus.ErrUnknownAncestor`.

#### Steps to reproduce the behaviour

I ran the following command to start Erigon. Fresh start, empty datadir.
```
erigon --private.api.addr=localhost:9090 --port=30333 --prune htc --prune.r.before=11184524
```
 
#### Backtrace

Here's the part where the node seems to fail. The execution step has already completed successfully by this point.

<img width="1922" alt="image" src="https://user-images.githubusercontent.com/169280/166865655-11559840-f5a4-4699-b433-bad0817725f2.png">

Full log: [erigon-frozen.log.gz](https://github.com/ledgerwatch/erigon/files/8628908/erigon-frozen.log.gz)

**Comment by AskAlexSharov** [comment]
hi. here is the solution: https://github.com/ledgerwatch/erigon/issues/3964#issuecomment-1114130777

**Comment by dcposch** [comment]
I'll try that. FWIW this is on mainnet, not goerli

**Comment by AskAlexSharov** [comment]
same for mainnet
