### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by infusixllc** [ledgerwatch/erigon#4086]
Hi, I ran erigon previously and didn't run it for a while.  When I upgraded I am now getting this error:

INFO[05-05|23:14:14.038] Build info                               git_branch=devel git_tag=v2022.05.02 git_commit=0fc99b7c55b47aea3f75ce8cc7ad56c8a33f7813
INFO[05-05|23:14:14.038] Starting Erigon on Ethereum mainnet... 
INFO[05-05|23:14:14.039] Maximum peer count                       ETH=100 total=100
INFO[05-05|23:14:16.146] Set global gas cap                       cap=50000000
INFO[05-05|23:14:16.214] Opening Database                         label=chaindata path=/mnt/data1/erigon-data/chaindata
EROR[05-05|23:14:16.223] Erigon startup                           err="migrator.VerifyVersion: cannot upgrade major DB version for more than 1 version from 3 to 6, use integration tool if you know what you are doing"

But I can't find instructions anywhere of what to do in this situation.  Can you guys provide any help?  Thanks!

**Comment by AskAlexSharov** [comment]
Hi. From beta releases to alpha releases (or devel) - only re-sync.

**Comment by infusixllc** [comment]
Ah bummer, thanks
