### ISSUE TITLE
BSC: to port Euler hard-fork feature

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4097]
link: https://github.com/bnb-chain/bsc/pull/885/files
announce: https://www.bnbchain.world/en/blog/bnb-smart-chain-testnet-euler-upgrade/

**Comment by IvanLazarevsky** [comment]
How is it going?

**Comment by AlexeyAkhunov** [comment]
https://github.com/ledgerwatch/erigon/pull/4461
