### ISSUE TITLE
Also stuck at "Wrote block headers..."

### ISSUE THREAD

**Issue by garyrob** [ledgerwatch/erigon#4099]
#### System information

Erigon version: 2022.99.99-dev-54076c9b

OS & Version:  Ubuntu 22.04 LTS 

Commit hash : devel branch

#### Expected behaviour
Syncing finished.

#### Actual behaviour
Stuck at Wrote block headers number=14499999 blk/second=0.000 alloc=6.9Gb sys=20.3Gb

#### Steps to reproduce the behaviour
~/erigon/build/bin/erigon

#### Backtrace

````
INFO[05-07|12:02:41.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=15.0Gb sys=23.3Gb
INFO[05-07|12:03:01.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=9.3Gb sys=23.3Gb
INFO[05-07|12:03:12.688] [p2p] GoodPeers                          eth66=64
INFO[05-07|12:03:21.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=12.2Gb sys=23.3Gb
INFO[05-07|12:03:41.962] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=15.0Gb sys=23.3Gb
INFO[05-07|12:04:01.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=13.2Gb sys=23.3Gb
INFO[05-07|12:04:21.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=11.9Gb sys=23.3Gb
INFO[05-07|12:04:41.962] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=14.7Gb sys=23.3Gb
INFO[05-07|12:05:01.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=17.6Gb sys=23.3Gb
INFO[05-07|12:05:12.689] [p2p] GoodPeers                          eth66=61
INFO[05-07|12:05:21.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=11.9Gb sys=23.3Gb
INFO[05-07|12:05:41.963] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=14.8Gb sys=23.3Gb
INFO[05-07|12:06:01.962] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=17.7Gb sys=23.3Gb
INFO[05-07|12:06:21.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=11.6Gb sys=23.3Gb
INFO[05-07|12:06:41.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=14.5Gb sys=23.3Gb
INFO[05-07|12:07:01.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=17.3Gb sys=23.3Gb
INFO[05-07|12:07:12.688] [p2p] GoodPeers                          eth66=60
INFO[05-07|12:07:21.962] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=11.3Gb sys=23.3Gb
INFO[05-07|12:07:41.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=14.1Gb sys=23.3Gb
INFO[05-07|12:08:01.961] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=17.0Gb sys=23.3Gb

````
#########################################################

Note that this appears to be the same issue as 4081 except that a) it's stuck at block 14499999, and b) I am using a version of erigon that I understand should include the fix that supposedly solved 4081. Although, it's suspicious that the error is occuring on 1 block before a very round block height. 

I ran the erigon executable with no args—I didn't know any reason I shouldn't go with all the defaults.

I don't know whether this is relevant, but before installing the latest release, I had a rapid infinite loop on a particular block saying something like "bad execution". This was while running an untagged devel release from a few days ago. I figured it might get fixed if I just upgrade to the latest devel release. So I did so, and now I'm in the loop described above.

If necessary I can delete all my data and re-sync from scratch, but I'd rather not!

**Comment by AskAlexSharov** [comment]
show a bit more logs pls, before that repeating lines.

**Comment by AskAlexSharov** [comment]
You also can try next fix: https://github.com/ledgerwatch/erigon/issues/4037#issuecomment-1114131161

**Comment by garyrob** [comment]
Restarted it. Here's the log from the new run:

./erigon/build/bin/erigon
INFO[05-07|17:54:48.329] Build info                               git_branch=devel git_tag=v2022.05.02 git_commit=54076c9bcfb5670e8189e2698c7115b39ae9fd56
INFO[05-07|17:54:48.329] Starting Erigon on Ethereum mainnet...
INFO[05-07|17:54:48.330] Maximum peer count                       ETH=100 total=100
INFO[05-07|17:54:50.433] Set global gas cap                       cap=50000000
INFO[05-07|17:54:50.486] Opening Database                         label=chaindata path=/home/garyrob/.local/share/erigon/chaindata
INFO[05-07|17:54:50.503] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[05-07|17:54:51.115] Disk storage enabled for ethash DAGs     dir=/home/garyrob/.local/share/erigon/ethash-dags count=2
INFO[05-07|17:54:51.115] Initialising Ethereum protocol           network=1
INFO[05-07|17:54:51.115] Effective                                prune_flags="--prune=" snapshot_flags="--syncmode=snap"
INFO[05-07|17:54:51.739] Starting private RPC server              on=127.0.0.1:9090
INFO[05-07|17:54:51.740] new subscription to logs established
INFO[05-07|17:54:51.751] [Snapshots] Fetching torrent files metadata
INFO[05-07|17:54:51.760] Started P2P networking                   version=66 self=enode://3fce5337d345af134b1481c6ede455d90e5702fdb032fe5f96200c822949e6821bbebd26a7497c06d1d3bf6f35bfd10655e3b7d419c9fe6daa4c53c3fcb3b98b@127.0.0.1:30303 name=erigon/v2022.99.99-dev-54076c9b/linux-amd64/go1.18.1
INFO[05-07|17:55:19.732] [1/16 Headers] Waiting for headers...    from=14499999
INFO[05-07|17:55:39.733] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=6.8Gb sys=11.0Gb
INFO[05-07|17:55:59.733] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=6.8Gb sys=11.0Gb
INFO[05-07|17:56:19.733] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=6.8Gb sys=11.0Gb
INFO[05-07|17:56:39.733] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=6.8Gb sys=11.0Gb
INFO[05-07|17:56:50.504] [p2p] GoodPeers                          eth66=2
INFO[05-07|17:56:59.733] [1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=6.9Gb sys=11.0Gb

**Comment by garyrob** [comment]
I think the fix at https://github.com/ledgerwatch/erigon/issues/4037#issuecomment-1114131161 may have fixed it. It's doing something different, with a number of rows of inserting headers. I have to go now and won't be able to report further for a while, so I just wanted to give that feedback while I could.

**Comment by AskAlexSharov** [comment]
good

**Comment by garyrob** [comment]
Yes, it appears to be fixed! Thanks!
