### ISSUE TITLE
How to start a bsc archive node?

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#4120]
I want to run a bsc archive node.Which sync mode should I use？ snap or full ?   I am using **snap** syncmode now.
command:`erigon --chain bsc --datadir /root/svc/node --syncmode snap --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain * --http.vhosts * --http.api "eth,net,web3" --ws --torrent.port 42096  --torrent.download.rate 32mb`

**Comment by AskAlexSharov** [comment]
1. syncmode - it's sync algorithm - not related to "archive or full node I will get in result".  So, can use both. My advise: snap
2. Erigon by default is archive mode, to remove historical data - use flags `--prune*`

**Comment by AskAlexSharov** [comment]
maybe for BSC you need also pass --db.pagesize=8kb (or 16kb), because default value 4kb does limit max DB size to 8TB (and snap-synced archive BSC now ~6Tb).
