### ISSUE TITLE
RPC always returns current state even though block number was provided

### ISSUE THREAD

**Issue by JC1DA** [ledgerwatch/erigon#4149]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev-0e457ba9

OS & Version: Windows/Linux/OSX
Linux, Ubuntu 20.04  LTS

Commit hash : 0e457ba9d7ef6e1e27d8229f335c55362a864dde

#### Expected behaviour
Return correct historical state data of a contract

#### Actual behaviour
I'm using Web3 python client to query for contract state with block identifier but it always returns the current state
e.g, pool_contract.history.call(block_identifier=block_number) returns similar result compared to pool_contract.history.call()

#### Steps to reproduce the behaviour
./build/bin/erigon --syncmode snap --prune.h.before 12369621 --prune.t.before 12369621 --prune.c.before 12369621 --prune.r.before=11184524 --torrent.download.rate=1000mb --datadir /NVME2/erigon --http --http.addr 0.0.0.0

I want to note that during the sync, the client did hang at block around 14700000 and I restarted erigon, which could cause the issue.

Any ideas how to reindex or fix this issue?
#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
@JC1DA hi. do you have example request?

**Comment by JC1DA** [comment]
I reset the "state_stages" and it's working fine now. I'll close the issue.
