### ISSUE TITLE
erigon http.api trace_block can't work

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#4173]
#### System information

Erigon version: `erigon --datadir=/data/erigon --http --ws --http.addr 0.0.0.0 --http.compression --http.corsdomain * --http.vhosts * --http.api "eth,erigon,web3,net,debug,trace,txpool"`

OS & Version: Ubuntu 20.04

Commit hash :  erigon version 2022.05.4-alpha-a9f3c67f

#### Expected behaviour

Request return
```
normal
```

#### Actual behaviour

Request return
````
trace api (trace_block) is failing with error 'the method trace_block does not exist/is not available
````

#### Steps to reproduce the behaviour

Copy run command

Request data using JSON RPC interface

Using trace_ Block module get error

**Comment by AskAlexSharov** [comment]
--http.api=eth
