### ISSUE TITLE
how long to complete stage [8/16 HashState] so that it can move on the next stage 

### ISSUE THREAD

**Issue by maxlyh93** [ledgerwatch/erigon#4174]
<img width="956" alt="hashstate" src="https://user-images.githubusercontent.com/58538392/168743002-782d6434-675f-44e8-a36f-ca64486fe9ef.PNG">

i dont think there is anything wrong going on here, but im just curious why its been almost a month that im stuck here... is there any way to speed it up ?

**Comment by AskAlexSharov** [comment]
Maybe something wrong with your node, but can't say without more context.
- Erigon version?
- Mainnet? Or other Netwrork? 
- No errors in logs? 
- Disk with high latency?
- show `./build/bin/integration print_stages --datadir=<your_datadir>`
- Does OOM killer kills Erigon sometime?

**Comment by maxlyh93** [comment]
1. erigon version = erigon/2022.04.3/linux-amd64/go1.18.1
2. BSC, Binance Smart Chain
3.  I'm not sure if there is any errors, can you give me suggestions to check it ?
4. SSD 10TB storage 10000 IOPS, 300 throughput, 16GB ram, m5zn.3xlarge(aws) 
5. print stages is taking a really long time too 
6. so far i dont think its killing Erigon, i didnt face any downtime for erigon

**Comment by maxlyh93** [comment]
My bad i was running erigon so integration didnt work. this is the output of 
./build/bin/integration print_stages --datadir=<your_datadir>

![image](https://user-images.githubusercontent.com/58538392/168762913-2b40a6b3-89d3-4548-910a-92d2dfe8ce9d.png)

**Comment by AskAlexSharov** [comment]
if you are at AWS with gp3/gp2 then i/o latency(not throughput) of EBS is what limits you
to get more you can either switch to io1/io2 (which is expensive as hell) or Instance Store NVME

we don't have any specific recommendations about AWS, just general knowledge: disk latency is the current bottleneck (more RAM may help a bit) - especially for big chains like BSC.
