### ISSUE TITLE
`eth_getTransactionReceipt` failing on some transaction hashes for Ethereum mainnet

### ISSUE THREAD

**Issue by mturnshek** [ledgerwatch/erigon#4199]
#### System information

```
$ ./erigon/build/bin/erigon --version
erigon version 2022.04.4-alpha-f3065a11

$ uname -a
Linux archive 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Commit hash : f3065a1149b5a15b6bc450adea842ce9762ef85e

#### Expected behaviour

Calling eth_getTransactionReceipt with a valid Ethereum mainnet transaction hash, for an Ethereum mainnet erigon node, does not cause the RPC client to throw an internal run-time error, and accurately returns a transaction receipt.

#### Actual behaviour

Calling eth_getTransactionReceipt with a significant percentage of valid transaction hashes results in an error. Here are several valid transaction hashes that cause the internal error:

```
['0x2d4763faa40fc2d6cdf7f8afeab5448c755ce327908546ce019ded583fab068f',
'0x22ddba6cc2ec54322db54132340e7b73bf30807e1692fbdbd8c09cab380e792b',
'0x2373639eff317b767f33930724ab010ee5af82d4b11d7d74d1f652e65286a86d',
'0x2dbd0bf10fde0cdb2d656e5b2437788fd145187a667e3fd572b0cdce78423a59',
'0x6664a993c3dc500f6343d155adbd713c8e9ed67b9ebb1cceea8ddb78863a3362',
'0xff1994d1359043433603adb22f671816bbc2133ec6aee725689ef32003557a9a',
'0x40c7ffb053eb6d39a82c51a9171c6b1b25d878e5cd9111533252dc0b2caa3aa8',
'0x73c837fdc0550335567b508d9d764b5cf66bcc8880578ac952c2842a32ecd3cc',
'0xc6b93eb5105ca3ff01d67cee09c399ac39a4f3765fe5e4312524f8316d084d93',
'0xb669d06e9d950718937754ad68a9f3ab5806f6df17bca061d9b87fe4fb0b2996',
'0x2050527de95cb082c6eed56f4e31dd37d1241124a331178586b3e31edead16f5']
```

The same transaction hashes deterministically cause the internal error to occur. I can easily collect more hashes if necessary. From what I can tell it's about 5% of the transactions I'm attempting to analyze which throw the error.

The internal error message is always one of the following two:

```
WARN[05-18|22:46:03.190] Served                                   
conn=127.0.0.1:44342 method=eth_getTransactionReceipt reqid=376 t=2.044028ms 
err="rpc error: code = Internal desc = runtime error: slice bounds out of range 
[:21] with capacity 0"
```

```
WARN[05-18|22:46:05.000] Served                                   
conn=127.0.0.1:44342 method=eth_getTransactionReceipt reqid=443 t=3.814767ms 
err="rpc error: code = Internal desc = runtime error: slice bounds out of range 
[21:0]"
```

#### Steps to reproduce the behaviour

1. Run an erigon node with no CLI flags
```
./build/bin/erigon
```
2. Run an RPC daemon. Exact command:
```
./erigon/build/bin/rpcdaemon --http.port=8545 --private.api.addr=127.0.0.1:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool
```
3. Call eth_getTransactionReceipt with one of the previously listed hashes.

#### Comments

If there's some additional information I can help provide from my system, please let me know.

**Comment by AskAlexSharov** [comment]
fixed in later versions
