### ISSUE TITLE
Optimize eth_getLogs

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4205]
In eth_getLogs: we do read whole block by `api.blockByNumberWithSenders`, but we can read only given transaction by it's id within block 
see how can read individual transaction: `rawdb.ReadCanonicalBodyWithTransactions`

**Comment by leonardchinonso** [comment]
@mandrigin @AskAlexSharov this issue is fixed by: https://github.com/ledgerwatch/erigon/pull/4662
Can close it now, yes?

**Comment by AskAlexSharov** [comment]
Yes
