### ISSUE TITLE
trie: TestIHCursor fails on CI

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#4236]
The test has started to fail on Linux and macOS on CI on devel.

Example failures:
https://github.com/ledgerwatch/erigon/runs/6539366721
https://github.com/ledgerwatch/erigon/runs/6534454606
https://github.com/ledgerwatch/erigon/runs/6521992636

**Comment by battlmonstr** [comment]
@AlexeyAkhunov , @AskAlexSharov , please assign somebody to investigate this, and determine if this is a major breakage, or something non-essential. I have disabled the test for now to keep the CI in a good shape.

The first commit where it started to fail is: https://github.com/ledgerwatch/erigon/commit/64508a7d4e5bdb47edc352bbe62d3682ca2e2d94

It failed in 30% of the builds after that.
( see https://github.com/ledgerwatch/erigon/commits )

**Comment by AskAlexSharov** [comment]
I will take a look tomorrow.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/4247
