### ISSUE TITLE
This parameter does not support '--rpc.allow-unprotected-txs'

### ISSUE THREAD

**Issue by wetezos** [ledgerwatch/erigon#4244]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.05.6-alpha-327e7d96
OS & Version: Windows/Linux/OSX
Linux
Commit hash : 
 (HEAD detached at v2022.05.07)
#### Actual behaviour
Can config `--rpc.allow-unprotected-txs`

#### Steps to reproduce the behaviour
When I send a tx through my eth rpc, I have this error:
`only replay-protected (EIP-155) transactions allowed over RPC `
so I want to add parameter `allow-unprotected-txs`, but I find this parameter is no longer supported.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/40154568/169944522-10702c38-532b-45ae-aa7d-75717eb1afe1.png">

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
What is your use-case?

**Comment by wetezos** [comment]
> What is your use-case?

Sent a transaction to interact with the eth contract. When I use infura's eth node, everything is fine. But when I replaced it with my own node, which is running by erigon, I encounterd this error: only replay-protected (EIP-155) transactions allowed over RPC. I believe we need add --rpc.allow-unprotected-txs, right?

**Comment by AskAlexSharov** [comment]
I mean “EIP-155” is very old, why do you need send pre-eip-155 transactions to node? Is it for some history-analisys? Or for what?

**Comment by wetezos** [comment]
> I mean “EIP-155” is very old, why do you need send pre-eip-155 transactions to node? Is it for some history-analisys? Or for what?

Yes, it is indeed very old, and our service was developed a long time ago, so it is still the old way of sending transactions, and there has been no problem using infura node until using our own node. Does erigon client not support this feature? If not, we will consider upgrading our code to send the transaction using the new way.

**Comment by AskAlexSharov** [comment]
Do you send it to TransactionPool?

“Sending unprotected transactions to TransactionsPool” - sounds for me as an Security Issue. Better address it on your side. 

Please discuss it with your team. If it’s totally not doable, come back here, we will take a look again. Thank you.

**Comment by wetezos** [comment]
> Do you send it to TransactionPool?
> 
> “Sending unprotected transactions to TransactionsPool” - sounds for me as an Security Issue. Better address it on your side.
> 
> Please discuss it with your team. If it’s totally not doable, come back here, we will take a look again. Thank you.
> 
> It’s edge case - you are the first who asked about it.

Sure, we will discuss it first, thanks.
