### ISSUE TITLE
Failed to run erigon after updating to latest commit

### ISSUE THREAD

**Issue by JC1DA** [ledgerwatch/erigon#4248]
#### System information

Erigon version: erigon version 2022.99.99-dev-31e94803

OS & Version: Linux

Commit hash : 31e94803dc1318784ff3bd2653c0bde254458c9e

#### Expected behaviour
Sync works

#### Actual behaviour
erigon --syncmode snap --prune.h.before 12369621 --prune.t.before 12369621 --prune.c.before 12369621 --prune.r.before=11184524 --torrent.download.rate=1000mb --datadir /NVME2/erigon --http --http.addr 0.0.0.0
EROR[05-23|22:17:33.693] Erigon startup                           err="not allowed change of --prune flag, last time you used: "

#### Steps to reproduce the behaviour
Compile with previous commit: 24244a09c76214595c98fdcd430cb0168be5386b
Run "erigon --syncmode snap --prune.h.before 12369621 --prune.t.before 12369621 --prune.c.before 12369621 --prune.r.before=11184524 --torrent.download.rate=1000mb --datadir /NVME2/erigon --http --http.addr 0.0.0.0"

Update to latest commit: 31e94803dc1318784ff3bd2653c0bde254458c9e
Run "erigon --syncmode snap --prune.h.before 12369621 --prune.t.before 12369621 --prune.c.before 12369621 --prune.r.before=11184524 --torrent.download.rate=1000mb --datadir /NVME2/erigon --http --http.addr 0.0.0.0"

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
It's because in the past without --prune flag any other --prune.* flags were ignored. it means your node didn't prune anything. 
Solution: remove `--prune.h.before 12369621 --prune.t.before 12369621 --prune.c.before 12369621 --prune.r.before=11184524`. If you need this flags - start new sync with this flags.
