### ISSUE TITLE
DeleteAncientBlocks: block body not found height

### ISSUE THREAD

**Issue by vanphandinh** [ledgerwatch/erigon#4250]
#### System information

Erigon version: `erigon version 2022.99.99-dev-216a5c46`

OS & Version: `Ubuntu 20.04.3 LTS`

Commit hash :  git_branch=devel git_tag=v2021.10.03-1144-g216a5c468 git_commit=216a5c468fe3d0620d6b4d2a4558163ff2843878

#### Expected behavior
My Erigon node is synced and no warning messages

#### Actual behaviour
This message is displayed in my synced node.
`[WARN] [05-24|13:59:12.690] DeleteAncientBlocks: block body not found height=14504196`

#### Steps to reproduce the behavior
`/root/erigon/build/bin/erigon --datadir=/root/erigon-data/ --torrent.download.rate=512mb --prune.r.before=11184524 --prune=htc --private.api.addr=localhost:9090`

#### Backtrace
![Screen Shot 2022-05-24 at 1 53 36 PM](https://user-images.githubusercontent.com/13887599/169968704-f0af2ddf-8fda-49af-9608-662d0ef54784.png)

**Comment by geomad** [comment]
This happend for me too on v2021.10.03-1135-g8ea2bb55d-dirty before the logs pasted on #4240. Possibly related. My node is an archive node.

**Comment by AskAlexSharov** [comment]
It’s not dangerous. I will add more info to this error tomorrow

**Comment by AwyResearch** [comment]
same error, any idea what's causing this?

**Comment by AskAlexSharov** [comment]
seems update and next command fixing the problem: `./build/bin/integration stage_headers --reset --datdir=<your_datadir>`

**Comment by vanphandinh** [comment]
> seems update and next command fixing the problem: `./build/bin/integration stage_headers --reset --datdir=<your_datadir>`

New Warn Message:
```[txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err=RLPTooLong```

**Comment by emilianobonassi** [comment]
> > seems update and next command fixing the problem: `./build/bin/integration stage_headers --reset --datdir=<your_datadir>`
> 
> New Warn Message: `[txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err=RLPTooLong`

I've started to receive it from yesterday and erigon is stuck at block 14961000

**Comment by emilianobonassi** [comment]
> > > seems update and next command fixing the problem: `./build/bin/integration stage_headers --reset --datdir=<your_datadir>`
> > 
> > 
> > New Warn Message: `[txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err=RLPTooLong`
> 
> I've started to receive this from yesterday and erigon is stuck at block 14961000

A restart seems to have solved

**Comment by AskAlexSharov** [comment]
There were released db migration which fixed this issue
