### ISSUE TITLE
"method handler crashed" on RPC calls greater than height of 90k blocks

### ISSUE THREAD

**Issue by steelep** [ledgerwatch/erigon#4255]
#### System information

erigon version 2022.99.99-dev-56fcb195
5.10.109-104.500.amzn2.x86_64 x86_64 GNU/Linux (AWS Linux)

#### Expected behaviour
My goal is to run a full mainnet archive node and run w3.eth.get_logs for any arbitrary block and return matching transactions  - I do not want or expect any pruning. 

#### Actual behaviour
My problem is when via the RPC, I try and pull a transaction from approximately 90,000+ blocks back, it returns "`ValueError: {'code': -32000, 'message': 'method handler crashed'}`" While anything more recent than 90,000 blocks works just fine.

I have subsequently tried setting prune flags to 0, but I receive a warning saying they are being ignored.

`sudo ~/erigon/build/bin/erigon --datadir /mnt/opt1/mainnet --ws --http --prune.h.before 10000000 --prune.r.before 10000000 --prune.c.before 10000000 --prune.t.before 10000000

`EROR[05-24|17:35:24.919] Erigon startup                           err="not allowed change of --prune flag, last time you used: "`

#### Steps to reproduce the behaviour
I have synced mainnet to what I understand is a full archive node with `"~/erigon/build/bin/erigon --datadir /myDataDir"`, with no additional parameters as your docs specifically state "**Pruning: Disabled by default."**

I then run a simple w3 call from Web3.py along the lines of:

w3.eth.get_logs(
            {
                "fromBlock": 13755911,
                "toBlock": 13755911 + 1000,
                "address": '0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc',
                "topics": '0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822',
            }
        )

which results in the below back trace, setting "fromBlock" to something near the top of the block height results in a normal RPC response with the expected data.

#### Backtrace
````
Traceback (most recent call last):
  File "mvp.py", line 64, in findTargetTX
    txn = w3.eth.get_transaction(txnHash)
  File "/mnt/opt1/anaconda3/envs/xyz/lib/python3.7/site-packages/web3/eth.py", line 737, in get_transaction
    return self._get_transaction(transaction_hash)
  File "/mnt/opt1/anaconda3/envs/xyz/lib/python3.7/site-packages/web3/module.py", line 60, in caller
    null_result_formatters)
  File "/mnt/opt1/anaconda3/envs/xyz/lib/python3.7/site-packages/web3/manager.py", line 201, in request_blocking
    null_result_formatters)
  File "/mnt/opt1/anaconda3/envs/xyz/lib/python3.7/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'method handler crashed'}
````

Have I synced the node correctly? It took ~5days with IOPs SSD's on AWS and the datadir is currently >1.6tb's

Any assistance debugging this (without a full new sync) would be appreciated.

Thanks!

**Comment by AskAlexSharov** [comment]
Show erigon and rpcdaemon logs

**Comment by AskAlexSharov** [comment]
“been ignored” fixed by https://github.com/ledgerwatch/erigon/pull/4165

**Comment by AskAlexSharov** [comment]
try upgrade to latest "devel" - I have feeling that I solved this issue recently

**Comment by steelep** [comment]
> try upgrade to latest "devel" - I have feeling that I solved this issue recently

Running the latest devel branch works here perfectly... Thanks Alex.
