### ISSUE TITLE
Big number of ETH disappear without trace

### ISSUE THREAD

**Issue by lianqiao** [ledgerwatch/erigon#4256]
Is `trace_replayBlockTransactions` complete? I found a big number of eth disappear without trace.

`0x84ef4b2357079cd7a7c69fd7a37cd0609a679106` get nearly 60k eth disappeared in block 1920000, but `stateDiff` from `trace_replayBlockTransactions` doesn't traced this. There are only 4 transactions in the block, state diffs don't trace any big balance change https://etherscan.io/txs?block=1920000

```
addr = '0x84ef4b2357079cd7a7c69fd7a37cd0609a679106'
print(eval(rpc_call('eth_getBalance', [addr,'0x%x' % 1919999])['result'])/1e18)
print(eval(rpc_call('eth_getBalance', [addr,'0x%x' % 1920000])['result'])/1e18)
```
```
598974.3265607931
0.0
```

**Comment by tjayrush** [comment]
The ETH didn't disappear. It was moved in a non-standard account balance change due to the DAO fork. You can read about it here: https://ethereum.stackexchange.com/questions/7832/give-a-summary-of-the-fork-state-changes-in-block-1920000.

This issue can probably be closed.

**Comment by lianqiao** [comment]
Thanks
