### ISSUE TITLE
Clarity around what `--snap.keepblocks=true` does...

### ISSUE THREAD

**Issue by allada** [ledgerwatch/erigon#4264]
Hi, I maintain [a public BSC archive snapshot](https://github.com/allada/bsc-archive-snapshot) and looking at some new flags since I last updated the code. I see `--snap.keepblocks`, but I am trying to figure out if this flag will cause issues with archive nodes and if I was to restore an archive node using the torrent, would this flag (or any other snap-related flags) cause issues with supporting a full archive node?

Thanks!

**Comment by AskAlexSharov** [comment]
No. Your node will be an Archive in any case. Only —prune* flags can change it.

**Comment by AskAlexSharov** [comment]
This flag is about keeping block And in snapshots And in DB. Mostly for debugging.
