### ISSUE TITLE
Slow block execution while sync

### ISSUE THREAD

**Issue by unlimittt** [ledgerwatch/erigon#4310]
Erigon version:  2022.05.8-alpha-1d2551e0
OS: docker thorax/erigon:v2022.05.08, ubuntu
Chain: bsc, snap sync

I noticed that only single CPU is in use, is it normal?

![Screenshot from 2022-05-30 22-29-30](https://user-images.githubusercontent.com/3004628/171024433-05a4c018-4ba2-4942-a8a0-18931e535108.png)

**Comment by AskAlexSharov** [comment]
Yes, it’s normal. It will change after upgrade3: https://erigon.substack.com/p/erigon-2-three-upgrades?utm_source=substack&utm_campaign=post_embed&utm_medium=web&s=r
