### ISSUE TITLE
trace_get errors

### ISSUE THREAD

**Issue by steelep** [ledgerwatch/erigon#4316]
#### System information

erigon version 2022.99.99-dev-13a1b3c1

AWS Linux - 5.10.109-104.500.amzn2.x86_64

#### Expected behaviour

RPC call trace_get returns a transaction trace

I am trying to get mainnet traces through my Erigon Archive Node, AFAIK everything is set to let this work, but I get an error every time I make the call (other calls work fine).

#### Actual behaviour

`curl --data '{"method":"trace_get","params":["0x17104ac9d3312d8c136b7f44d4b8b47852618065ebfa534bd2d3b5ef218ca1f3",["0x0"]],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
`
Returns: `{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method trace_get does not exist/is not available"}}`

RPCDaemon Log:` WARN[05-31|10:41:34.252] Served                                   conn=127.0.0.1:55000 method=trace_get reqid=1 t=11.394µs err="the method trace_get does not exist/is not available"
`
#### Steps to reproduce the behaviour

Running the RPCDaemon:
`./build/bin/rpcdaemon --datadir /mnt/opt1/mainnet --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --ws --ws.compression --http.compression http.api=eth,debug,net,trace,web3,erigon
`
Running Erigon: 
`sudo ./build/bin/erigon --datadir /mnt/opt1/mainnet --private.api.addr=localhost:9090 --private.api.ratelimit=31872 http.api=eth,debug,net,trace,web3,erigon --rpc.batch.concurrency=10
`

**Comment by AskAlexSharov** [comment]
`--http.api`, not `http.api`
