### ISSUE TITLE
Disk Usage 50% greater than geth

### ISSUE THREAD

**Issue by anonqoder** [ledgerwatch/erigon#4356]
Erigon version ```2022.05.8-alpha-1d2551e0```

Execute as ```./erigon  --datadir=/home/data/erigon  --syncmode=full --prune.r.before=11184524 --prune=htc```

I also have geth running side-by-side, started with ```./geth --datadir /home/data/geth --cache 1024 --syncmode full```

Disk usage:
```
  918.5 GiB [#######################] /erigon
  608.7 GiB [###############        ] /geth
```

the [README](https://github.com/ledgerwatch/erigon#system-requirements) mentions 400 GB for erigon mainnet with full sync, what am I missing? Is there some pruning background operation that will be executed eventually?

**Comment by AskAlexSharov** [comment]
@anonqoder 1. Use —syncmode=snap in erigon will reduce disk usage 2. Show erigon logs at startup 3. Show space usage inside erigon datadir 4. You storing much receipts --prune.r.before=11184524 , does geth storing them? Receipts are big.

**Comment by anonqoder** [comment]
1. Too late, I've already synced using full. Does snap brings the disk usage close to geth? The difference is large

2. Init logs

```
Jun 04 06:57:47 systemd[1]: Started Erigon execution client Mainnet.
Jun 04 06:57:47 erigon[3360246]: [INFO] [06-04|06:57:47.879] Build info                               git_branch=HEAD git_tag=v2022.05.08 git_commit=1d2551e0216587c213e4ca69896bbc85c3330cbb
Jun 04 06:57:47 erigon[3360246]: [INFO] [06-04|06:57:47.879] Starting Erigon on Ethereum mainnet...
Jun 04 06:57:47 erigon[3360246]: [INFO] [06-04|06:57:47.881] Maximum peer count                       ETH=100 total=100
Jun 04 06:57:49 erigon[3360246]: [INFO] [06-04|06:57:49.982] Set global gas cap                       cap=50000000
Jun 04 06:57:50 erigon[3360246]: [INFO] [06-04|06:57:50.035] Opening Database                         label=chaindata path=/home/data/ethereum/mainnet/execution/erigon/chaindata
Jun 04 06:57:50 erigon[3360246]: [INFO] [06-04|06:57:50.039] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAO Support: true Tangerine Whistle: 2463000 Spurious Dragon: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
Jun 04 06:57:50 erigon[3360246]: [INFO] [06-04|06:57:50.039] Disk storage enabled for ethash DAGs     dir=/home/data/ethereum/mainnet/execution/erigon/ethash-dags count=2
Jun 04 06:57:50 erigon[3360246]: [INFO] [06-04|06:57:50.039] Initialising Ethereum protocol           network=1
Jun 04 06:57:50 erigon[3360246]: [INFO] [06-04|06:57:50.039] Effective                                prune_flags="--prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 --prune.r.before=11184524" snapshot_flags=
Jun 04 06:57:52 erigon[3360246]: [INFO] [06-04|06:57:52.393] Starting private RPC server              on=127.0.0.1:8181
Jun 04 06:57:52 erigon[3360246]: [INFO] [06-04|06:57:52.393] new subscription to logs established
Jun 04 06:57:52 erigon[3360246]: [INFO] [06-04|06:57:52.413] Started P2P networking                   version=66 self=enode://619537c0bf527e9bcd60e4d8e61e20e8635617f708a1230ca3c32a57d026ccc4f4ceceea6728869f103c06c09e6f0c813e85747063cdcdecc4fc2da98171594f@127.0.0.1:31303 name=erigon/v2022.05.8-alpha-1d2551e0/linux-amd64/go1.18.2
```

3. Inside erigon:

```
--- /home/data/ethereum/mainnet/execution/erigon ----------------------------------------------------------------------------------------------------------------------------------------
                                         /..                                                                                                                                             
  947.6 GiB [##########################] /chaindata
   88.5 MiB [                          ] /txpool
    3.7 MiB [                          ] /nodes
    4.0 KiB [                          ]  nodekey
    0.0   B [                          ]  LOCK
```

```chaindata``` contains a massive file

```
947.6 GiB [##########################]  mdbx.dat
    1.0 MiB [                          ]  mdbx.lck
```


4. Do the receipts after block ```11184524``` account for extra 500 GB of space? This seem unlikely. I've only used them because the [README](https://github.com/ledgerwatch/erigon#beacon-chain) specified that it is necessary to use it as a beacon chain execution client. Currently my beacon node uses ```geth``` as a web3 backend, and it is working fine.

**Comment by anonqoder** [comment]
Forgot to mention: my ```geth``` node went through an offline prune ```geth snapshot prune-state``` 
The reason why I am trying to move to erigon is to use less disk and less resident anonymous memory, maybe the docs are misleading or incomplete?

**Comment by AskAlexSharov** [comment]
1. https://erigon.substack.com/p/disk-footprint-changes-in-new-erigon?s=r and https://erigon.substack.com/p/more-on-the-disk-footprint-of-erigon?s=r
4. you can calc it by: `make db-tools` and `./build/bin/mdbx_stat -s TransactionLog <your_datadir>/chaindata` 

---
it's well known that Erigon is smaller than Geth as Archive node. as non-archive Geth is smaller (because we didn't release snapshots of state yet). But docs are correct, my node with `--syncmode=snap --prune=hrtc`:
```
du -h .
139M	./txpool
254G	./chaindata
9.7M	./nodes/eth66
9.7M	./nodes
8.4M	./snapshots/db
226G	./snapshots
8.9G	./etl-temp
488G	.
```

**Comment by anonqoder** [comment]
That is pretty decent! 👏

So to fix my issue I need to resync from scratch, or is there a prune tool like geth?

Regarding receipts, geth AFAICT doesn't include them in non-archive nodes, and the latests docs on the merge seem to imply it will work just fine: https://mirror.xyz/jmcook.eth/1GcUHyHst4VxXsbr4Ee3DJbrFQjAmQLkqt-fIBEeX_M

Do I really need to add ```--prune.r.before=11184524```?

**Comment by anonqoder** [comment]
> Do I really need to add --prune.r.before=11184524 to use it with a beacon node

☝️

**Comment by AskAlexSharov** [comment]
I don’t know, you can try to ask in discord

**Comment by anonqoder** [comment]
It is written in the README of the project, and I have the nimbus beaconchain + erigon (simply with ```--prune=hrtc```) running fine, that is why I wonder if that is some sort of leftover

**Comment by AskAlexSharov** [comment]
@Giulio2002 do you know?
