### ISSUE TITLE
MB != Mb

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#4383]
I was looking at the logs and wondering why the download speed was so slow. It actually is not, the message is showing the wrong unit, and I do confirm it from OS network monitor.

It is showing 4.0 megabits/s when it is actually 40 megabits, or 4.0 megaBYTEs, so it should be 40mbps or 4.0MB/s (note the capital B, same applies to other units Kilo/Giga/etc.)

See: https://www.makeuseof.com/tag/megabit-vs-megabyte/

`
INFO[06-06|18:19:20.883] [Snapshots] download                     progress="75.55% 39.4Gb/52.1Gb" download=4.0Mb/s upload=0b/s peers=1 connections=5 files=72 alloc=155.5Mb sys=248.0Mb
INFO[06-06|18:19:40.455] [p2p] GoodPeers                          eth66=30
INFO[06-06|18:19:40.882] [Snapshots] download                     progress="75.70% 39.4Gb/52.1Gb" download=3.9Mb/s upload=0b/s peers=1 connections=5 files=72 alloc=89.7Mb sys=248.0Mb
`

**Comment by AskAlexSharov** [comment]
Can it be “mb”?

**Comment by wmitsuda** [comment]
I think the right abbreviation is MB (all capitalized), if you use mb (all lowercase) I would assume megabits because of lowercase b

**Comment by AskAlexSharov** [comment]
Ok. Again logs will scream on me :-)
