### ISSUE TITLE
DEV chain stuck: "Wrong trie root" leading to "possible uncles"

### ISSUE THREAD

**Issue by mohoff** [ledgerwatch/erigon#4385]
#### System information

Erigon version: `2022.06.1-alpha-1d3259aa`

Commit hash : 

#### Expected behaviour

DEV chain should mine txs successfully as it did under `2022.04.01`

#### Actual behaviour

Log snippets:

```
[EROR] [06-06|22:43:15.017] [9/16 IntermediateHashes] Wrong trie root of block 80: c5c2710419c57b053123b1c4fca8b38ae2b04fcbe7930819e1c8139471ab8cea, expected (from header): e54f9793979b80e1a2136c4c20c95489d0672c74fac4bb51cf4839934d765fa2. Block hash: eaee3952c30924808f5c76560fcd45f4c3dd593c451302bae09b5c6c57ff5343
[WARN] [06-06|22:43:15.017] Unwinding due to incorrect root hash     to=79
[INFO] [06-06|22:43:15.017] UnwindTo                                 block=79 bad_block_hash=0xeaee3952c30924808f5c76560fcd45f4c3dd593c451302bae09b5c6c57ff5343
```

it seems to unwind successfully to block 79. Then:

```
[INFO] [06-06|22:43:15.034] [1/16 Headers] Waiting for headers...    from=79
[TRACE] [06-06|22:43:15.034] Empty anchor queue
[DBUG] [06-06|22:43:15.034] Request skeleton                         anchors=0 top seen height=0 highestInDb=79
[INFO] [06-06|22:43:15.034] local tx propagated                      tx_hash=6f1dac49a994e711b049586aa36830ca4fa17e251a88562c748a18c951718573 announced to peers=0 broadcast to peers=0 baseFee=38466
[DBUG] [06-06|22:43:15.039] [1/5 MiningCreateBlock] Candidate txs    amount=1
[INFO] [06-06|22:43:15.039] [1/5 MiningCreateBlock] Start mine       block=80 baseFee=38466 gasLimit=12433868
[TRACE] [06-06|22:43:15.039] Possible uncle rejected                  hash=0xeaee3952c30924808f5c76560fcd45f4c3dd593c451302bae09b5c6c57ff5343 reason="uncle is sibling"
```

and the cycle repeats, dev chain stuck at block 79.

Switched from concurrent to sequential tx broadcasting (4 txs) but the issue persists. However, first I ran into `tx failed. nonce too high` which wasn't an issue with the same code under version `2022.04.01`. Not sure if a separate issue or the same.

Worth mentioning that before the first error, 4 txs were successfully mined.

This is a follow-up issue for https://github.com/ledgerwatch/erigon/issues/4301 which seems fixed in the latest release. cc @enriavil1

**Comment by AskAlexSharov** [comment]
Switch to latest devel: 
  ./build/bin/integration stage_headers —reset —datadir=<your_datadir>
   ./build/bin/integration stage_exec —unwind=100 —datadir=<your_datadir>

**Comment by Giulio2002** [comment]
Can you send me what transactions are executing to get this setup? do you have a script i can reproduce this on?

**Comment by Giulio2002** [comment]
I reproduced it, i know what it is, fix is incoming

**Comment by mohoff** [comment]
Thanks, the fix worked!
