### ISSUE TITLE
Ropsten: context canceled during `engine_exchangeTransitionConfigurationV1`

### ISSUE THREAD

**Issue by rkapka** [ledgerwatch/erigon#4398]
#### System information

Erigon version: `./erigon --version`

2022.99.99-dev-bcbb8bec

OS & Version: Windows/Linux/OSX

Linux

Commit hash : 

#### Expected behaviour

Erigon running alongside Prysm

#### Actual behaviour

After a few hours Erigon just stops. Last message is

```
[WARN] [06-07|01:13:58.064] Served conn=127.0.0.1:44736 method=engine_exchangeTransitionConfigurationV1 reqid=3 t=1.618421875s err="context canceled"
```

#### Steps to reproduce the behaviour

1. Run Erigon as EL and Prysm as CL.
2. Wait 

#### Backtrace

````
[backtrace]
````

**Comment by enriavil1** [comment]
Are there any logs before? It seems like erigon might have stopped before hand.

**Comment by enriavil1** [comment]
What branch of prysm are you using and what commands?

**Comment by rkapka** [comment]
I am running Prysm `v2.1.3-rc.2`

Erigon commands: `--datadir ropsten --http --http.api=eth,erigon,web3,net,debug,trace,txpool,engine --authrpc.jwtsecret=/tmp/jwtsecret  --chain ropsten`
Prysm commands: `--http-web3provider=http://localhost:8551 --jwt-secret=/tmp/jwtsecret --genesis-state=./genesis.ssz --ropsten`

**Comment by SeaMonkey82** [comment]
> --genesis-state=./genesis.ssz

You don't need this flag anymore.  Genesis state is covered by `--ropsten`.

**Comment by rkapka** [comment]
Hi, I just updated to commit `644d25d25df7b1ae08b13c6baa32b2779bc8ae33` and everything works OK. I think we can close the issue.
