### ISSUE TITLE
data migration leads to panic (mdbx_env_open: MDBX_BUSY)

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#4400]
Erigon version: v2021.10.03-1257-gd7d698f56-dirty (devel)
Commit hash : d7d698f565bd3c57981799a1a78f84ce3b0bdb3b
Machine specs: 64 GB ram, AMD 3900x, 4TB Nvme gen4 ssd
OS & Version: Linux Debian

Updating and restarting erigon leads to panic. After shutting down rpcdaemon erigon could start normally and started the data migration process.

```
[INFO] [06-08|01:04:38.931] Build info                               git_branch=devel git_tag=v2021.10.03-1257-gd7d698f56-dirty git_commit=d7d698f565bd3c57981799a1a78f84ce3b0bdb3b
[INFO] [06-08|01:04:38.932] Starting Erigon on Ethereum mainnet...
[INFO] [06-08|01:04:38.932] Maximum peer count                       ETH=30 total=30
[INFO] [06-08|01:04:41.035] Set global gas cap                       cap=50000000
[INFO] [06-08|01:04:41.096] Opening Database                         label=chaindata path=/chain/erigon/chaindata
[INFO] [06-08|01:04:41.097] Re-Opening DB in exclusive mode to apply migrations
[EROR] [06-08|01:04:41.097] Erigon startup                           err="mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: chaindata, trace: [kv_mdbx.go:241 node.go:515 node.go:534 backend.go:158 node.go:117 node.go:108 main.go:41 app.go:526 app.go:286 main.go:28 proc.go:250 asm_amd64.s:1571]"
```
Same error appears to rpcdaemon when trying to start it while the migration is happening
```
[EROR] [06-07|23:06:38.045] Could not connect to DB                  err="mdbx_env_open: resource temporarily unavailable, label: chaindata, trace: [kv_mdbx.go:241 config.go:251 main.go:19 command.go:856 command.go:974 command.go:902 command.go:895 main.go:38 proc.go:250 asm_amd64.s:1571]"
```

**Comment by AskAlexSharov** [comment]
- `resource temporarily unavailable` - DBMigration happening in Exclusive mode - means other processes can't open db. It's expected. 
- "MDBX_BUSY: Another write transaction is running` - Other Erigon running in background?

**Comment by geomad** [comment]
Fix was easy, just posted it since it disrupted the flow of the update. There was no other erigon running for sure so I assumed it was cause by the rpcdaemon. Is this fix a one time thing? Maybe then its ok to leave it as is?
Except if the issue was the db still writing after erigon was terminated but the process was already ended and not waiting? I run erigon as a service, so I just `systemctl restart`

**Comment by AskAlexSharov** [comment]
one-time: we may release new db migrations - rare thing.

**Comment by mohoff** [comment]
Seeing the same issue running a dockerized version and restarting with `docker stop; rm; run`

 This happens with `2022.06.01-alpha` but also `2022.06.02-alpha`. Trying to sync mainnet. Running erigon and rpcdaemon as separate processes but in the same container.

**Comment by nate-staked** [comment]
The fix for me was to make sure rpcdaemon wasn't running

**Comment by MrLouzao** [comment]
Hi. I am running Erigon in a kubernetes service and having the same problem.

```
command: ["/bin/bash","-c"]
args: ["erigon --chain ropsten \
        --override.terminaltotaldifficulty=50000000000000000 \
        --datadir=/home/.local/share/erigon \
        --metrics --metrics.addr=0.0.0.0 --private.api.addr=localhost:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 & \
        sleep 10 && rpcdaemon --datadir=/home/.local/share/erigon \
        --private.api.addr=localhost:9090 \
        --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* \
        --http.api=eth,erigon,web3,net,debug,trace,txpool,engine --http.port=8845 \
        --ws \
        --engine.addr=0.0.0.0 --engine.port=8551 \
        --authrpc.jwtsecret=/tmp/.jwt/jwt.hex"]
```

Reading the comments I assume that this is caused by the fact that I am running the erigon and rpcdaemon at the same time, while erigon is trying to locking  exclusively the db.

I turned off the liveness and readiness probes and removed the rpc daemon from the args,  but  I am still receiving the same error. In addition, the pod is always restarted because is not able to acquire the lock to access to the DB, entering into a crash loop.

What is the suggested action in this case? Thanks.

**Comment by Aracki** [comment]
I temporarily fixed this by going back to `v2022.04.02`

**Comment by tropicar** [comment]
I have this issue too, I am using docker-compose, rpdaemon and erigon in two separate containers. If I stop the rpcdaemon container the error does not appear.

**Comment by AskAlexSharov** [comment]
This is how exclusive mode in mdbx works. We don’t plan to change it.
