### ISSUE TITLE
trace_block and trace_transaction is inconceivable slow

### ISSUE THREAD

**Issue by jondoe1337** [ledgerwatch/erigon#4413]
#### System information

Erigon version: `erigon version 2022.05.9-alpha-97e8c42d` (running ETH Mainnet)

OS & Version: Linux / Docker (running on a Dell PowerEdge™ R6515 DX181 with NVMe Raid)

#### Expected behaviour
Tested a few calls using `trace_block` and `trace_transaction` with blocks and transactions that are not more than 500 blocks ago. Both of them take more than 15-30seconds (!). This is not feasible.

#### Actual behaviour
OpenEthereum as a reference for those calls take milliseconds (around 100-400ms depending on load).

Why is that? Is there anything we can prepare the node to speed this up?

**Comment by artjoma** [comment]
Version: 2022.06.2-alpha-5632b634 BSC mainnet

Block trace spent 3-5sec it's supper slow

**Comment by iFA88** [comment]
AFAIK OpenEthereum stores the traces during executing and when you query them it is just a read. On other hand Erigon excecutes them and gives the tracer result back.

**Comment by tjayrush** [comment]
I am not a current member of the core team, but I used to be a couple of summers ago. I can confirm what @iFA88 says. That's one of the reasons (there are others) that OpenEthereum requires a 12 TB hard drive and Erigon requires a 2TB hard drive. You can't have everything.

I switched officially from OpenEthereum to Erigon about a year and half ago. The main reason why I didn't do so earlier was because of the exact issue you describe. One of the things that we found to be very beneficial was to use `trace_block`. In fact, in our testing, Erigon's `trace_block` was faster than OpenEthereum's `trace_block`. I can't explain why this was the case, but it may have been another engineering choice -- perhaps Erigon optimizes `trace_block` whereas OpenEthereum chose to optimize `trace_transaction`.

For our application, the speed of `trace_block` is excellent, and I would argue that very small disc space usage is very much worth any performance differences.

Having said all of this. I am no longer a core dev on Erigon, so not exactly what you asked for.

**Comment by jondoe1337** [comment]
@tjayrush thank you very much for that answer. I came to the same conclusion to try `trace_block` but to be honest, the performance was not excellent for us. For a block that was around 500 behind the tip the call took almost 30s. 
Not sure how to proceed here...a flag to include the tracing in the db would be somewhat helpful. For indexing the chain those performance numbers are not feasible. 😢

**Comment by tjayrush** [comment]
My guess is that it will be a very long time before such a flag appears. (Not speaking for the team, of course).

I actually don't think you're correct when you say that "for indexing the chain, those performance numbers are not feasible." 30-second return time is, but we're not seeing that at all.

We have a locally running version of Erigon and our software (TrueBlocks) indexes the entire chain on **a laptop computer** (admittedly a pretty massive one - 64GB of Ram, 8TB hard drive) in under two days. And this is an astronomically deep index. We visit every block, every transaction, every log, every receipt, and every trace and find more than `29,003,365,214` addresses.

I'm very sure there's something wrong with your setup. My guess is an under-provisioned machine.

Hope this is helpful. I'd be very interest to learn what you find. And, please remember, I'm not speaking for the team.

**Comment by AlexeyAkhunov** [comment]
Thanks for report, I will be working with tracing quite soon and will check out this issue as well to see why there might be such a slowdown

**Comment by AlexeyAkhunov** [comment]
> Why is that? Is there anything we can prepare the node to speed this up?

What is your setup? Do you run separate RPC daemon or embedded?

If you are running separate, are you giving `--datadir` command line option to the RPC daemon?

**Comment by artjoma** [comment]
I solved my issue using multiple rpcnodes instances. Right now works fast.

**Comment by jondoe1337** [comment]
> > Why is that? Is there anything we can prepare the node to speed this up?
> 
> What is your setup? Do you run separate RPC daemon or embedded?
> 
> If you are running separate, are you giving `--datadir` command line option to the RPC daemon?

We run two separate RPC Daemons and just checked, no we don't have that option added to the run command.

@tjayrush Well, I see those numbers by just doing plain curl commands from the same machine. We synced that machine 2 weeks ago with the newest version, from scratch with the described hardware specs. 
And to be honest, I doubt that you index the entire Mainnet within 2 days ;-) TrueBlocks does caching and IPFS sharing, maybe that boots that a lot.

**Comment by tjayrush** [comment]
@jondoe1337 Are you on the Erigon discord? I'd love to continue the conversation there. Otherwise, glad it's running faster. Do you think the solution has to do with using `--datadir`? I guess you can close this issue?

**Comment by jondoe1337** [comment]
@tjayrush I never wrote that it's running faster, I was just giving a recap on "how old is that node". Yes I'm on discord there.

**Comment by jondoe1337** [comment]
@artjoma the help output says: `(enabled if no --datadir set)` for the `state.cache`. I guess it won't work then?

**Comment by artjoma** [comment]
> @artjoma the help output says: `(enabled if no --datadir set)` for the `state.cache`. I guess it won't work then?

I never used this argument. Help description of -cache looks strange. My point of view, you should create your custom block-tracer and tx-tracer + API methods for them, to reduce trace result size. Your tracer will works only with EVM opcodes what you really need.
