### ISSUE TITLE
Mainnet Snapshot download stuck at >90%

### ISSUE THREAD

**Issue by mohoff** [ledgerwatch/erigon#4423]
#### System information

Erigon version: `v2022.06.02-alpha`

Commit hash : `fd0837d962987636649b5a2a5090601f3410d632`

#### Expected behaviour

Sync mainnet

#### Actual behaviour

Snapshot download stuck at high percentage.

```
[INFO] [06-09|18:12:28.320] [Snapshots] download                     progress="93.29% 193.6Gb/207.5Gb" download=17.3Mb/s upload=0b/s peers=11 connections=15 files=87 alloc=1.2Gb sys=1.5Gb
[INFO] [06-09|18:12:48.320] [Snapshots] download                     progress="93.41% 193.8Gb/207.5Gb" download=13.5Mb/s upload=4.0Kb/s peers=2 connections=6 files=87 alloc=736.9Mb sys=1.5Gb
[INFO] [06-09|18:13:08.320] [Snapshots] download                     progress="93.41% 193.8Gb/207.5Gb" download=0b/s upload=819b/s peers=2 connections=5 files=87 alloc=788.0Mb sys=1.5Gb
[INFO] [06-09|18:13:28.320] [Snapshots] download                     progress="93.41% 193.8Gb/207.5Gb" download=0b/s upload=0b/s peers=2 connections=5 files=87 alloc=823.2Mb sys=1.5Gb
[INFO] [06-09|18:13:48.319] [Snapshots] download                     progress="93.41% 193.8Gb/207.5Gb" download=0b/s upload=0b/s peers=2 connections=7 files=87 alloc=864.0Mb sys=1.5Gb
[INFO] [06-09|18:14:08.319] [Snapshots] download                     progress="93.41% 193.8Gb/207.5Gb" download=0b/s upload=819b/s peers=1 connections=4 files=87 alloc=920.8Mb sys=1.5Gb
```

Deleted all state and tried again but same issue.

**Comment by mohoff** [comment]
In my situation, restarting erigon without starting rpcdaemon continues downloading snapshots. If rpcdaemon starts too, erigon runs into a db lock issue (see https://github.com/ledgerwatch/erigon/issues/4400)

**Comment by mohoff** [comment]
@AskAlexSharov 6h+ the first time

**Comment by iamchrissmith** [comment]
this has been happening to me as well. I've tried downloading state several times.  After I reach this point, when I kill the process and try to restart I get 

```bash
EROR[09-01|16:43:38.049] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[main.go:29 panic.go:884 panic.go:260 signal_unix.go:835 index.go:149 block_snapshots.go:179 config.go:245 block_snapshots.go:286 config.go:243 backend.go:572 node.go:115 main.go:58 app.go:526 app.go:286 main.go:34 proc.go:250 asm_amd64.s:1594]"
```

erigon version: `erigon version 2022.08.2-alpha-35c4faa1`
syncing mainnet (goerli sync on same version worked)

**Comment by AskAlexSharov** [comment]
@iamchrissmith fixed in new versions

**Comment by iamchrissmith** [comment]
> @iamchrissmith fixed in new versions

Thank you (and for the quick response)! i thought I was on the latest tag, but it appears switching to `v2022.08.03` did allow me to restart my latest sync without redownloading all the snapshots
