### ISSUE TITLE
Does Erigon sacrifices the data integrity for less disk usage and high state query performance?

### ISSUE THREAD

**Issue by cifer76** [ledgerwatch/erigon#4449]
Hi I'm new to Erigon I'm not sure if the title suits. As my understanding about Erigon, it uses a flatten db schema to store the account state(and history) instead of the merkle patricia tree the Geth uses, actually I and our team are also considering this approach as it can save a lot of disk space the intermediate nodes of the merkle tree occupied, as well as providing a better account state query and initial sync performance.

So when I found that Erigon has adopted this approach I felt very happy, but I do have a question that, the merkle patricia tree in geth guarantees a tight data integrity since all account state are link-proof level by level, but in Erigon all of the account state are stored individually thus loosely, I feel this could be an major issue, as the node can theoretically manipulate the records in the flatten db now.

Do we have some proof mechanism to prevent this from happenning now? I have looked the source code and it seems the `GetProof` rpc call hasn't been implemented yet

**Comment by AskAlexSharov** [comment]
Erigon also calculating state root for new blocks: does it not on PlainState (flatten non-crypto-hashed keys), to calc trie root it using HashedSate (copy of PlainState but crypto-hashed) and storing some branch-nodes in TrieAccount table. 

Most space-saving comes from encoding of Historical state changes: by inverted diffs. See: https://github.com/ledgerwatch/erigon-lib/blob/bbf96d05808e5bbcbf78ee67a0b1715887d1309d/kv/tables.go#L69
