### ISSUE TITLE
How can I set the websocket port to public?

### ISSUE THREAD

**Issue by sonderangebot10** [ledgerwatch/erigon#4495]
Hi!

I want to access the websocket port from an external machine. Thus, I need to make the port public instead of private. On geth I can do this by default. However, on erigon I cannot see such an option when running the client.

Is there any easy way to do this? Maybe someone could point me to the location I should modify in the code?

Thanks!

**Comment by AskAlexSharov** [comment]
—http.addr=0.0.0.0
