### ISSUE TITLE
Euler upgrade (systemcontracts.upgrade) GenesisHash - no value assigned anywhere

### ISSUE THREAD

**Issue by IvanLazarevsky** [ledgerwatch/erigon#4497]
Hello!
I'm not a Go developer at all, so I will refrain from submitting pull requests, but I've just found one suspicious place while trying to apply Euler upgrade changes over older commit.

Here (https://github.com/ledgerwatch/erigon/pull/4461) by @enriavil1 
new variable **GenesisHash** was added.
```
var (
	GenesisHash common.Hash
	//upgrade config
	ramanujanUpgrade = make(map[string]*Upgrade)

@@ -44,6 +44,8 @@ var (
	mirrorUpgrade = make(map[string]*Upgrade)

	brunoUpgrade = make(map[string]*Upgrade)

	eulerUpgrade = make(map[string]*Upgrade)
)
```

It is used to define network here (**core/systemcontracts/upgrade.go**):
```
func UpgradeBuildInSystemContract(config *params.ChainConfig, blockNumber *big.Int, statedb *state.IntraBlockState) {
	if config == nil || blockNumber == nil || statedb == nil {
		return
	}
	var network string
	switch GenesisHash {
	/* Add mainnet genesis hash */
	case params.BSCGenesisHash:
		network = mainNet
	case params.ChapelGenesisHash:
		network = chapelNet
	case params.RialtoGenesisHash:
		network = rialtoNet
	default:
		network = defaultNet
	}
```
	
instead of older
```
		switch config.ChainName {
	case networkname.BSCChainName:
		network = mainNet
	case networkname.ChapelChainName:
		network = chapelNet
	case networkname.RialtoChainName:
		network = rialtoNet
	default:
		network = defaultNet
	}
```
	
The problem is - I didn't find any place where this variable **GenesisHash** gets assigned (devel branch).
In BSC repository (https://github.com/bnb-chain/bsc) it gets assigned at **core/genesis.go**, function **SetupGenesisBlockWithOverride**

Is there something I don't see or the concern is legitimate?

**Comment by LiamSteph1208** [comment]
Herr

**Comment by AlexeyAkhunov** [comment]
@IvanLazarevsky Yes, I think you are right, will fix
