### ISSUE TITLE
[BSC] Sync stuck since upgrade to 2022.06.06

### ISSUE THREAD

**Issue by Denis-score** [ledgerwatch/erigon#4518]
#### System information

erigon version 2022.06.6-alpha-77240899

OS & Version: Linux (debian 11)

Commit hash : 7724089985bf9cb8bb7d1bde92892256a6af859f

#### Steps to reproduce the behaviour
Upgrade to 2022.06.06 then restart

#### Backtrace

````
INFO[06-22|20:47:15.687] Build info                               git_branch=HEAD git_tag=v2022.06.06 git_commit=7724089985bf9cb8bb7d1bde92892256a6af859f
INFO[06-22|20:47:15.687] Starting Erigon on BSC mainnet...
INFO[06-22|20:47:15.689] Maximum peer count                       ETH=100 total=100
INFO[06-22|20:47:17.792] Set global gas cap                       cap=50000000
INFO[06-22|20:47:17.798] Opening Database                         label=chaindata path=/data/erigon/chaindata
INFO[06-22|20:47:17.799] Re-Opening DB in exclusive mode to apply migrations
INFO[06-22|20:47:17.800] Apply migration                          name=reset_blocks_3
INFO[06-22|20:47:17.801] Applied migration                        name=reset_blocks_3
INFO[06-22|20:47:17.801] Updated DB schema to                     version=6.0.0
INFO[06-22|20:47:17.802] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Engine: parlia}" genesis=0x0d21840abff
46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
INFO[06-22|20:47:17.802] Initialising Ethereum protocol           network=56
INFO[06-22|20:47:17.802] Using snapshots                          on=true
WARN[06-22|20:47:17.802] Incorrect snapshot enablement            got=true change_to=false
INFO[06-22|20:47:17.802] Effective                                prune_flags= snapshot_flags=
INFO[06-22|20:47:18.332] Starting private RPC server              on=0.0.0.0:9090
INFO[06-22|20:47:18.332] new subscription to logs established
INFO[06-22|20:47:18.337] Started P2P networking                   version=66 self=enode://e8445158a924fbadabc5cc6bf0ef4059d544279460eea5674c586db24bf93b2452d5d911f9db67b3b4205c04908b64175461e6f64207729d66
1b401d3d0e7849@127.0.0.1:30303 name=erigon/v2022.06.6-alpha-77240899/linux-amd64/go1.18.3
INFO[06-22|20:47:18.342] [1/16 Headers] Waiting for headers...    from=18907620
INFO[06-22|20:47:38.343] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=55.7MB sys=100.6MB
INFO[06-22|20:47:51.707] [1/16 Headers] Processed                 highest inserted=18920611 age=2s
INFO[06-22|20:47:51.742] [4/16 Bodies] Processing bodies...       from=18907620 to=18920611
INFO[06-22|20:47:56.137] [4/16 Bodies] Processed                  highest=18920611
INFO[06-22|20:47:56.138] [5/16 Senders] Started                   from=18907620 to=18920611
INFO[06-22|20:48:01.469] [6/16 Execution] Blocks execution        from=18907620 to=18920611
INFO[06-22|20:48:01.469] Apply upgrade euler at height 18907621   system-contract-upgrade=Mainnet
INFO[06-22|20:48:01.469] Upgrade contract 0x0000000000000000000000000000000000001000 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/db8bb560ac5a1265c685b719c7e976dced162310 system-cont
ract-upgrade=Mainnet
INFO[06-22|20:48:01.469] Upgrade contract 0x0000000000000000000000000000000000001001 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/db8bb560ac5a1265c685b719c7e976dced162310 system-cont
ract-upgrade=Mainnet
WARN[06-22|20:48:01.528] [6/16 Execution] Execution failed        block=18907621 hash=0x46350ef180209caa04feabb4527593439a4130593d4f5de7f764ded615fd1400 err="supposed to get a actual transaction, but get none"
INFO[06-22|20:48:01.528] UnwindTo                                 block=18907620 bad_block_hash=0x46350ef180209caa04feabb4527593439a4130593d4f5de7f764ded615fd1400
INFO[06-22|20:48:01.528] [6/16 Execution] Completed on            block=18907620
INFO[06-22|20:48:03.442] Timings (slower than 50ms)               Headers=33.364s Bodies=4.395s Senders=5.331s Execution=58ms Unwind Bodies=1.819s Unwind Headers=90ms
INFO[06-22|20:48:03.442] [1/16 Headers] Waiting for headers...    from=18907620
INFO[06-22|20:48:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=439.1MB sys=1.2GB
INFO[06-22|20:48:43.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=864.1MB sys=1.2GB
INFO[06-22|20:49:03.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.4GB sys=1.6GB

INFO[06-22|20:49:17.803] [p2p] GoodPeers                          eth66=14
INFO[06-22|20:49:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.7GB sys=1.9GB
INFO[06-22|20:49:43.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.7GB sys=2.2GB
INFO[06-22|20:49:43.443] Req/resp stats                           req=820 reqMin=18907600 reqMax=18920648 skel=17 skelMin=18909156 skelMax=19203876 resp=852 respMin=18907601 respMax=18920649 dups=877
INFO[06-22|20:49:43.443] Queue sizes                              anchors=1 links=12455 persisted=52545
INFO[06-22|20:49:43.443] {18908195-18920649 links=12455 (18908195-18920649)} => b3fc739dcb10f8649b932d990d391bec746b39bc391fc12daa1ee94339559008, anchorQueue.idx=0, next retry in 4.997649841s
INFO[06-22|20:50:03.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=2.3GB sys=2.6GB
INFO[06-22|20:50:03.443] Req/resp stats                           req=887 reqMin=18907611 reqMax=18920654 skel=17 skelMin=18909156 skelMax=19203876 resp=913 respMin=18907612 respMax=18920655 dups=1123
INFO[06-22|20:50:03.443] Queue sizes                              anchors=0 links=0 persisted=52545
INFO[06-22|20:50:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=2.1GB sys=3.0GB
INFO[06-22|20:50:23.443] Req/resp stats                           req=885 reqMin=18907604 reqMax=18920661 skel=15 skelMin=18909156 skelMax=19203876 resp=908 respMin=18907605 respMax=18920662 dups=1064
INFO[06-22|20:50:23.443] Queue sizes                              anchors=0 links=0 persisted=52545
````

Then nothing more happen. The service loop to "[1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=4.0GB sys=4.5GB"

**Comment by m4tr0x** [comment]
Same for me here. The only values moving are "respMin", "respMax" and "dups". What irritates is, that blk/sec is 0 and the number isnt moving any upwards towards the most recent block.

**Comment by AskAlexSharov** [comment]
@radian-rgc , not same. Your node does print Error message in logs.

**Comment by AskAlexSharov** [comment]
@radian-rgc probably you need update to support Euler hardfork

**Comment by radian-rgc** [comment]
> @radian-rgc probably you need update to support Euler hardfork

Thanks @AskAlexSharov 

I want to update erigon but need Go1.8 version, i update Golang to the last version but after run make erigon i got the below error:

```
cannot find package "github.com/ledgerwatch/erigon-lib/common/dbg" in any of:
        /usr/local/go/src/github.com/ledgerwatch/erigon-lib/common/dbg (from $GOROOT)
```

What's wrong ?

**Comment by radian-rgc** [comment]
> @radian-rgc not go1.8, but go1.18

mistake type 😅 so what about the error ? i think somthing about GOROOT or GOPATH :/

**Comment by radian-rgc** [comment]
> > @radian-rgc probably you need update to support Euler hardfork
> 
> Thanks @AskAlexSharov
> 
> I want to update erigon but need Go1.8 version, i update Golang to the last version but after run make erigon i got the below error:
> 
> ```
> cannot find package "github.com/ledgerwatch/erigon-lib/common/dbg" in any of:
>         /usr/local/go/src/github.com/ledgerwatch/erigon-lib/common/dbg (from $GOROOT)
> ```
> 
> What's wrong ?

fixed above problem by `export GO111MODULE="on"` 

and now I'm running last version and start migration 

![ccs](https://user-images.githubusercontent.com/23151404/175345008-22c1ea05-de4e-436e-a777-0a6b3f63348c.png)

**Comment by Denis-score** [comment]
@AskAlexSharov do you have an idea for my issue ? It's not the same.

**Comment by AskAlexSharov** [comment]
@AlexeyAkhunov do you see any insight in this logs: https://github.com/ledgerwatch/erigon/issues/4518#issue-1280890875

**Comment by radian-rgc** [comment]
@AskAlexSharov 
After update erigon to the last version and migration complete, the problem come again and block locked at 18907620 🤔🤔

![Screenshot_2022-06-24-12-48-10-707_com sonelli juicessh](https://user-images.githubusercontent.com/23151404/175494327-136ccafe-c551-4881-8746-664327440733.jpg)

Please help, our services are down becuse of this problem 

Thank you

**Comment by AskAlexSharov** [comment]
Try: “./build/bin/integration stage_headers —unwind=10_000 —datadir=<your_datadir>”

**Comment by radian-rgc** [comment]
@AskAlexSharov 

Nothing change... :(

`./build/bin/integration stage_headers --unwind=10_000 --datadir=dexpool`

Still i go the same error:

`block body hash too few txs amount: 18930041, 1, trace: [stageloop.go:125 panic.go:844 accessors_chain.go:627 accessors_chain.go:521 accessors_chain.go:1099 body_algos.go:151 stage_bodies.go:134 default_stages.go:59 sync.go:327 sync.go:235 stageloop.go:159 stageloop.go:80 asm_amd64.s:1571]`

**Comment by AskAlexSharov** [comment]
"is it possible to skip this block ?" - you can try to remove this check from code, but I don't know what will happen (because I don't know root cause of the problem).

**Comment by nikolinsko** [comment]
> Same for me here. The only values moving are "respMax" and "dups". What irritates is, that blk/sec is 0 and the number isnt moving any upwards towards the most recent block. I, for myself downloaded the snapshot provided by BNB48Club and ran the erigon client as following:
> 
> `erigon --chain bsc --datadir D:\bsc\data --http --http.addr 127.0.0.1 --http.port 8545 --ws --port 30311 --snapshots=false --prune= --prune.h.older=5000 --prune.r.older=5000 --prune.t.older=5000 --prune.c.older=5000`
> 
> the recent output log is as following:
> 
> ```
> INFO[06-23|06:39:12.220] [1/16 Headers] Wrote block headers       number=18862983 blk/second=0.000 alloc=3.7GB sys=7.7GB
> INFO[06-23|06:39:12.221] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=18864519 skelMax=19159239 resp=37 respMin=18864519 respMax=18930032 dups=556
> INFO[06-23|06:39:12.222] Queue sizes                              anchors=0 links=21830 persisted=65535
> INFO[06-23|06:39:32.223] [1/16 Headers] Wrote block headers       number=18862983 blk/second=0.000 alloc=3.9GB sys=7.7GB
> INFO[06-23|06:39:32.223] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=18864519 skelMax=19159239 resp=61 respMin=18864519 respMax=18930039 dups=613
> INFO[06-23|06:39:32.225] Queue sizes                              anchors=0 links=21838 persisted=65535
> INFO[06-23|06:39:52.220] [1/16 Headers] Wrote block headers       number=18862983 blk/second=0.000 alloc=3.1GB sys=7.7GB
> INFO[06-23|06:39:52.220] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=18864519 skelMax=19159239 resp=54 respMin=18864519 respMax=18930045 dups=521
> INFO[06-23|06:39:52.222] Queue sizes                              anchors=0 links=21849 persisted=65535
> INFO[06-23|06:40:12.221] [1/16 Headers] Wrote block headers       number=18862983 blk/second=0.000 alloc=3.3GB sys=7.7GB
> INFO[06-23|06:40:12.221] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=18864519 skelMax=19159239 resp=42 respMin=18864519 respMax=18930051 dups=734
> INFO[06-23|06:40:12.223] Queue sizes                              anchors=0 links=21855 persisted=65535
> INFO[06-23|06:40:32.222] [1/16 Headers] Wrote block headers       number=18862983 blk/second=0.000 alloc=3.5GB sys=7.7GB
> INFO[06-23|06:40:32.222] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=18864519 skelMax=19159239 resp=62 respMin=18864519 respMax=18930058 dups=569
> INFO[06-23|06:40:32.223] Queue sizes                              anchors=0 links=21863 persisted=65535
> INFO[06-23|06:40:51.003] [p2p] GoodPeers                          eth66=92
> ```

First of all thanks for the information about the snapshot of bnbclub, saved me weeks of syncing up.
Are you sure your on a suitable devel commit? I downloaded the snapshot yesterday and could sync it up without a problem, maybe it might help to download the snapshot again otherwise?

**Comment by AlexeyAkhunov** [comment]
> @AlexeyAkhunov do you see any insight in this logs: [#4518 (comment)](https://github.com/ledgerwatch/erigon/issues/4518#issue-1280890875)


I can see the error is starting at Euler hard fork block, but I don't know why. perhaps that was a block from un-upgraded node, in which case it should have recovered

**Comment by AlexeyAkhunov** [comment]
@AskAlexSharov I suspect these nodes that are failing like that are having the pre-alpha DB format (as they started syncing on experimental versions prior the first alpha release). @radian-rgc @Denis-score please confirm what was your previous version. To fix that, you'll probably need to reset all the block bodies and re-download them, by using
`./build/bin/integration stage_bodies --reset --datadir <datadir>`

**Comment by mandrigin** [comment]
@radian-rgc can you check a solution from this issue? https://github.com/ledgerwatch/erigon/issues/4659#issuecomment-1177268066

**Comment by NarupoomChaisawat** [comment]
> #### System information
> erigon version 2022.06.6-alpha-77240899
> 
> OS & Version: Linux (debian 11)
> 
> Commit hash : [7724089](https://github.com/ledgerwatch/erigon/commit/7724089985bf9cb8bb7d1bde92892256a6af859f)
> 
> #### Steps to reproduce the behaviour
> Upgrade to 2022.06.06 then restart
> 
> #### Backtrace
> ```
> INFO[06-22|20:47:15.687] Build info                               git_branch=HEAD git_tag=v2022.06.06 git_commit=7724089985bf9cb8bb7d1bde92892256a6af859f
> INFO[06-22|20:47:15.687] Starting Erigon on BSC mainnet...
> INFO[06-22|20:47:15.689] Maximum peer count                       ETH=100 total=100
> INFO[06-22|20:47:17.792] Set global gas cap                       cap=50000000
> INFO[06-22|20:47:17.798] Opening Database                         label=chaindata path=/data/erigon/chaindata
> INFO[06-22|20:47:17.799] Re-Opening DB in exclusive mode to apply migrations
> INFO[06-22|20:47:17.800] Apply migration                          name=reset_blocks_3
> INFO[06-22|20:47:17.801] Applied migration                        name=reset_blocks_3
> INFO[06-22|20:47:17.801] Updated DB schema to                     version=6.0.0
> INFO[06-22|20:47:17.802] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Engine: parlia}" genesis=0x0d21840abff
> 46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
> INFO[06-22|20:47:17.802] Initialising Ethereum protocol           network=56
> INFO[06-22|20:47:17.802] Using snapshots                          on=true
> WARN[06-22|20:47:17.802] Incorrect snapshot enablement            got=true change_to=false
> INFO[06-22|20:47:17.802] Effective                                prune_flags= snapshot_flags=
> INFO[06-22|20:47:18.332] Starting private RPC server              on=0.0.0.0:9090
> INFO[06-22|20:47:18.332] new subscription to logs established
> INFO[06-22|20:47:18.337] Started P2P networking                   version=66 self=enode://e8445158a924fbadabc5cc6bf0ef4059d544279460eea5674c586db24bf93b2452d5d911f9db67b3b4205c04908b64175461e6f64207729d66
> 1b401d3d0e7849@127.0.0.1:30303 name=erigon/v2022.06.6-alpha-77240899/linux-amd64/go1.18.3
> INFO[06-22|20:47:18.342] [1/16 Headers] Waiting for headers...    from=18907620
> INFO[06-22|20:47:38.343] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=55.7MB sys=100.6MB
> INFO[06-22|20:47:51.707] [1/16 Headers] Processed                 highest inserted=18920611 age=2s
> INFO[06-22|20:47:51.742] [4/16 Bodies] Processing bodies...       from=18907620 to=18920611
> INFO[06-22|20:47:56.137] [4/16 Bodies] Processed                  highest=18920611
> INFO[06-22|20:47:56.138] [5/16 Senders] Started                   from=18907620 to=18920611
> INFO[06-22|20:48:01.469] [6/16 Execution] Blocks execution        from=18907620 to=18920611
> INFO[06-22|20:48:01.469] Apply upgrade euler at height 18907621   system-contract-upgrade=Mainnet
> INFO[06-22|20:48:01.469] Upgrade contract 0x0000000000000000000000000000000000001000 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/db8bb560ac5a1265c685b719c7e976dced162310 system-cont
> ract-upgrade=Mainnet
> INFO[06-22|20:48:01.469] Upgrade contract 0x0000000000000000000000000000000000001001 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/db8bb560ac5a1265c685b719c7e976dced162310 system-cont
> ract-upgrade=Mainnet
> WARN[06-22|20:48:01.528] [6/16 Execution] Execution failed        block=18907621 hash=0x46350ef180209caa04feabb4527593439a4130593d4f5de7f764ded615fd1400 err="supposed to get a actual transaction, but get none"
> INFO[06-22|20:48:01.528] UnwindTo                                 block=18907620 bad_block_hash=0x46350ef180209caa04feabb4527593439a4130593d4f5de7f764ded615fd1400
> INFO[06-22|20:48:01.528] [6/16 Execution] Completed on            block=18907620
> INFO[06-22|20:48:03.442] Timings (slower than 50ms)               Headers=33.364s Bodies=4.395s Senders=5.331s Execution=58ms Unwind Bodies=1.819s Unwind Headers=90ms
> INFO[06-22|20:48:03.442] [1/16 Headers] Waiting for headers...    from=18907620
> INFO[06-22|20:48:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=439.1MB sys=1.2GB
> INFO[06-22|20:48:43.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=864.1MB sys=1.2GB
> INFO[06-22|20:49:03.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.4GB sys=1.6GB
> 
> INFO[06-22|20:49:17.803] [p2p] GoodPeers                          eth66=14
> INFO[06-22|20:49:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.7GB sys=1.9GB
> INFO[06-22|20:49:43.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=1.7GB sys=2.2GB
> INFO[06-22|20:49:43.443] Req/resp stats                           req=820 reqMin=18907600 reqMax=18920648 skel=17 skelMin=18909156 skelMax=19203876 resp=852 respMin=18907601 respMax=18920649 dups=877
> INFO[06-22|20:49:43.443] Queue sizes                              anchors=1 links=12455 persisted=52545
> INFO[06-22|20:49:43.443] {18908195-18920649 links=12455 (18908195-18920649)} => b3fc739dcb10f8649b932d990d391bec746b39bc391fc12daa1ee94339559008, anchorQueue.idx=0, next retry in 4.997649841s
> INFO[06-22|20:50:03.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=2.3GB sys=2.6GB
> INFO[06-22|20:50:03.443] Req/resp stats                           req=887 reqMin=18907611 reqMax=18920654 skel=17 skelMin=18909156 skelMax=19203876 resp=913 respMin=18907612 respMax=18920655 dups=1123
> INFO[06-22|20:50:03.443] Queue sizes                              anchors=0 links=0 persisted=52545
> INFO[06-22|20:50:23.443] [1/16 Headers] Wrote block headers       number=18907620 blk/second=0.000 alloc=2.1GB sys=3.0GB
> INFO[06-22|20:50:23.443] Req/resp stats                           req=885 reqMin=18907604 reqMax=18920661 skel=15 skelMin=18909156 skelMax=19203876 resp=908 respMin=18907605 respMax=18920662 dups=1064
> INFO[06-22|20:50:23.443] Queue sizes                              anchors=0 links=0 persisted=52545
> ```
> 
> Then nothing more happen. The service loop to "[1/16 Headers] Wrote block headers number=18907620 blk/second=0.000 alloc=4.0GB sys=4.5GB"

**Comment by syjcnss** [comment]
Same here. I compiled Erigon from tag `v2022.07.01`

```
erigon_bsc  | [INFO] [09-14|16:36:52.859] [4/16 Bodies] Unwinding transactions...  current block=21301045
erigon_bsc  | [INFO] [09-14|16:36:56.506] [p2p] GoodPeers                          eth66=24
erigon_bsc  | [EROR] [09-14|16:37:00.297] Staged Sync                              err="must not happen, ResetSequence: 3392069073, lastInDB: 3392069073, trace: [stageloop.go:125 panic.go:844 accessors_chain.go:854 stage_bodies.go:286 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:159 stageloop.go:80 asm_amd64.s:1571]"
erigon_bsc  | [INFO] [09-14|16:37:04.526] [txpool] stat                            block=20755733 pending=10000 baseFee=0 queued=30000 alloc=3.0GB sys=7.1GB
erigon_bsc  | [INFO] [09-14|16:37:22.541] [4/16 Bodies] Unwinding transactions...  current block=20820476
```
