### ISSUE TITLE
Execute Blocks Stage can use  Multi thread

### ISSUE THREAD

**Issue by differs** [ledgerwatch/erigon#4522]
# Rationale

Why should this feature exist?
excute blocks stage use too much time

**Comment by AndreaLanfranchi** [comment]
Cause every block needs to be executed to determine the new states of accounts and contracts touched by transactions held in the block itself.
Multi threading on execution is extremely difficult as block x to be executed needs the state up to block x - 1

**Comment by cifer76** [comment]
> Erigon2 Upgrade2 will have this feature: https://erigon.substack.com/p/erigon-2-three-upgrades

to clarify, upgrade2 will solve this not by multi-threads, but by packaging execution results(state, receipts, traces) into static files.
