### ISSUE TITLE
High CPU usage in 2022.06.06

### ISSUE THREAD

**Issue by ekimd** [ledgerwatch/erigon#4523]
I'm running the docker image from 2022.06.06 and I'm noticing that the CPU usage is much higher now than with the image I was using previously from Apr/May--somewhere around 3x what it was previously.  Is this expected?

**Comment by AskAlexSharov** [comment]
1 cpu will be used often and heavily to create new snapshots. This expected. Everything else not expected. 

Now snapshots production is not very optimized, but even after optimizations probably still better reserve 1 cpu for snapshots production.

**Comment by ekimd** [comment]
Understood.  Thanks for the fast response.
