### ISSUE TITLE
Eliminate the need to modify erigon-lib when adding new table

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#4525]
This is a code/feature request:

Currently adding a new table requires modifying table.go in erigon-lib, adding a constant to ChainDataTables array.

Problem: I'm doing some tests with new indexes, had to fork erigon-lib and replace the version in go.mod@erigon. Having to rebase it every new release is driving me crazy, pls I need a solution 😛

Is there some workaround that could be coded so I don't have to change erigon-lib, but also keep whatever safety checkings erigon does at init?

My tables have a "Ots_" name prefix if this could help in any way. I can change the prefix to something more neutral if you can go with having a standard prefix for custom tables.

**Comment by AskAlexSharov** [comment]
1. Can use “replace” in erigon’s go.mod to point it to your local folder “./../erigon-lib”.
2. Can use go.work
3. Can add tables when opening db, by: mdbx.New().Path(p).WithTablesCfg(your_func_to_add_table).Open()

**Comment by mandrigin** [comment]
@wmitsuda is that good enough solutions? If so, please, close the issue :)

**Comment by AskAlexSharov** [comment]
You need 3

**Comment by wmitsuda** [comment]
will soon submit PR, so closing for now.
