### ISSUE TITLE
eth_getTransactionReceipt crashes

### ISSUE THREAD

**Issue by creatzor** [ledgerwatch/erigon#4530]
#### System information

Erigon version: `erigon version 2022.99.99-dev-4e780725`

OS & Version: Linux

Commit hash : ??

#### Expected behaviour
No crash

#### Actual behaviour
Crash

#### Steps to reproduce the behaviour
Call eth_getTransactionReceipt for a lot of receipts (100+) 
Try with transactions from this block number `1783947`

#### Backtrace

```
[EROR] [06-24|<IP>] RPC method eth_getTransactionReceipt crashed: runtime error: slice bounds out of range [33:1]
[service.go:217 panic.go:838 panic.go:117 decompress.go:578 block_reader.go:558 block_reader.go:594 block_snapshots.go:242 block_reader.go:593 eth_api.go:136 eth_receipts.go:271 value.go:556 value.go:339 service.go:222 handler.go:484 handler.go:389 handler.go:343 handler.go:181 handler.go:271 asm_amd64.s:1571] 
[WARN] [06-24|<IP>] Served                                   conn=<IP>:51322 method=eth_getTransactionReceipt reqid=1656093470362 t=2.198658ms err="method handler crashed"
```

**Comment by enriavil1** [comment]
Is this still happening?

**Comment by creatzor** [comment]
> Is this still happening?

Yes, sorry for the delay. It happens intermittently. It may be related to computing resources.

**Comment by FWangZil** [comment]
**I'm having a similar problem, when requesting a slightly larger amount(>800QPS) of eth_getTransactionReceipt , it raises "method=eth_getTransactionReceipt reqid=0 t=1.00073377s err="context canceled".**

## System information
Erigon version: erigon version 2022.99.99-dev-d6001225 (Similar problem since 2022.99.99-dev-92e2311e)

OS & Version: Linux Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-163-generic x86_64)

Commit hash : d6001225e7c9e13eb5a9ab34d12d60403c861df6

**Comment by AskAlexSharov** [comment]
“context canceled” - it means client canceled the request, or client gone.

**Comment by FWangZil** [comment]
> 

It is possible that the client timeout was not returned and the erigon RPC service became unavailable simultaneously, and I have raised a separate issue describing this situation.

#4794

**Comment by FWangZil** [comment]
> “context canceled” - it means client canceled the request, or client gone.

It is possible that the client timeout was not returned and the erigon RPC service became unavailable simultaneously, and I have raised a separate issue describing this situation.

https://github.com/ledgerwatch/erigon/issues/4794
