### ISSUE TITLE
pruneLogIndex func must use ETL instead of maps: to limit RAM usage

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4538]

**Comment by leonardchinonso** [comment]
I've looked at how `etl`s are used in the code, but don't really understand how they can replace the maps for `addresses` and `topics` used in `pruneLogIndex` function

**Comment by mandrigin** [comment]
This one is taken by @nanevardanyan at the moment

**Comment by nanevardanyan** [comment]
This was handled by the following pull request [4707](https://github.com/ledgerwatch/erigon/pull/4707). Should I close the issue @mandrigin ?

**Comment by AskAlexSharov** [comment]
yes
