### ISSUE TITLE
eth_getFilterLogs  not yet implemented ?

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#4547]
**eth_getFilterLogs**  not yet implemented ?
I can't find any information from RPC Implementation Status (https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon)

**Comment by AskAlexSharov** [comment]
Something was implemented here: https://github.com/ledgerwatch/erigon/pull/4253

**Comment by MysticRyuujin** [comment]
That something does not include eth_getFilterLogs
