### ISSUE TITLE
`rawdb.ReadHeader()` cannot find blocks

### ISSUE THREAD

**Issue by hrthaowang** [ledgerwatch/erigon#4554]
#### System information

erigon version 2022.99.99-dev-63fa65cf

#### Behavior
When I called `eth_estimateGas`, it could not find the block header.

`ValueError: {'code': -32000, 'message': 'block 14917087(a62c8a3c98465abaabc2d60e9b067a4e05634791e7627b787a094b35a5e7af31) not found'}`

#### Steps to reproduce the behavior
We can reproduce this behavior with this script.
`w3.eth.estimate_gas({"to":"0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc", "data": "0x0902f1ac"}, 14917087)`

#### Solution
I think the bug might be due to the fact that `rawdb.ReadHeader()` is deprecated. In order to fix the bug in `estimateGas`. We can replace `HeaderByNumberOrHash` by the following

```
blockNum, _, _, err := rpchelper.GetBlockNumber(bNrOrHash, dbtx, api.filters)
if err != nil {
	return 0, err
}
block, err := api.blockByNumberWithSenders(dbtx, blockNum)
if err != nil {
	return 0, err
}
h := block.Header()
```

**Comment by AskAlexSharov** [comment]
I think you also synced with snapshots. It means your db has no old headers. "rawdb" it's package to read db only. 
anyway, agree (api.blockByNumberWithSenders also will use blocksLRU - which is make sense for estimateGas i think): https://github.com/ledgerwatch/erigon/pull/4556
