### ISSUE TITLE
Improved health check / health check for syncing

### ISSUE THREAD

**Issue by gfxlabs** [ledgerwatch/erigon#4560]
# Rationale

Hi! 

In order to keep our RPC downtime low, we run multiple nodes and load balance between them.

However, with the current healthcheck, it responds a successful code even if the node is still syncing, and it's hard to configure a 
 complicated dynamic health check request to use the block number in body for the health check. Not to mention it's a bit annoying sometimes to send a request with data in body. 

While it is possible to perform the healthcheck using a shell script, it would be much simpler and safer if was possible to perform this health check using a get request with headers, see traefik and k8s:
https://doc.traefik.io/traefik/routing/services/#health-check
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes
 
# Implementation

for now i just build my own images, and i did this 
https://github.com/ledgerwatch/erigon/blob/182ea3a118626db7a2af883dda3147d1b73f8e98/cmd/rpcdaemon/health/health.go#L31-L174

I'm more than happy to implement this, would rather do that than maintain the fork. I know current applications probably depend on the current implementation of the healthcheck, so perhaps making this endpoint /health2 would be better? Anyways, let me know and if it sounds like an okay plan then i can get it done :D

**Comment by tirumerla** [comment]
@gfxlabs Interesting, i'm in the same boat as you (currently working on an implementation to make sure our nodes sync ). Our nodes are behind an NLB. While health checks are using GET calls, i usually use a POST call to get the latest block number ( to test if the node is syncing properly ). I'm planning on adding a reverse proxy ( like nginx or traefik ) to modify incoming GET request to a POST request to json rpc or adding a flask app route to modify GET request to POST. I'm curious to hear your thoughts. 

Based on what you mention your approach is to pass some headers to the GET request to know if the sync is working?

**Comment by gfxlabs** [comment]
@tirumerla yep! here, i actually started writing up what i was thinking with the headers, it's here

https://github.com/ledgerwatch/erigon/blob/c1c34c87162cc008c6e8e3b2c7561786e6f1a06f/cmd/rpcdaemon/health/health.go#L81-L135
and yes exactly, i really wanted to avoid putting a proxy in the middle.  so with this, i make a GET request to `/health` with 
headers:
```
X-ERIGON-HEALTHCHECK: synced
X-ERIGON-HEALTHCHECK: min_peer_count10
X-ERIGON-HEALTHCHECK: check_block15039100
```
so this will make sure that the node thinks its synced, that it has more than 10 peers, and the current block is above 15039100

i'm currently adding something like `X-ERIGON-HEALTHCHECK: max_seconds_behind600`, to check if the latest block received is within 600 seconds of current time, for instance. of course you can set the number to whatever. i think that would remove the need to check an external source for the current block.

**Comment by mandrigin** [comment]
@gfxlabs kudos for the issue! we can try to upstream your changes relatively soon, are you running a fork right now?

**Comment by elee1766** [comment]
> @gfxlabs kudos for the issue! we can try to upstream your changes relatively soon, are you running a fork right now?

hey, thanks!

yeah, I'm running the fork right now on both of my nodes.

**Comment by gfxlabs** [comment]
oh that was my other account lol, the fork is here https://github.com/gfxlabs/erigon/tree/feat/healthcheck-2

**Comment by mandrigin** [comment]
nah, it is to normal RPCDaemon, but we will check if we can add this natively
