### ISSUE TITLE
Changing prune flags during initial sync

### ISSUE THREAD

**Issue by codylittle** [ledgerwatch/erigon#4584]
Hey all,

I'm aware that changing prune flags after sync is prohibited as outlined in #3658.
However, I'm "most" (15m/19m) of the way through a sync of the BSC mainnet and have had a change of heart on not pruning.

Is the general advise still to just resync, or is there documentation available on the tool referenced by [Alex](https://github.com/ledgerwatch/erigon/issues/3658#issuecomment-1066014075)?

**Comment by AskAlexSharov** [comment]
We don't allow change prune flags after node creation. For now re-sync is needed. 
We will re-visit this problem after Erigon2 Upgrade2 release: https://erigon.substack.com/p/erigon-2-three-upgrades
