### ISSUE TITLE
Error building when using erigon module as dependency for extended rpc daemon

### ISSUE THREAD

**Issue by farwayer** [ledgerwatch/erigon#4586]
```
../../../go/pkg/mod/github.com/ledgerwatch/erigon@v1.9.7-0.20220620155524-7724089985bf/turbo/snapshotsync/snapshothashes/embed.go:34:12: pattern erigon-snapshots/bor-mainnet.toml: no matching files found
```

I'm not Go pro dev but look like `go get` do not initialize `erigon-snapshots` git submodule in `erigon/turbo/snapshotsync/snapshothashes`. Сan you suggest how to fix this error?

**Comment by AskAlexSharov** [comment]
git submodules
You can run “make erigon” it will update git submodules for you

**Comment by farwayer** [comment]
@AskAlexSharov I'm not building erigon itself, we are using `erigon` go module as dep for custom rpc daemon (with extended API). In this case importing some stuff from `erigon` causes building error

**Comment by mandrigin** [comment]
One option could be to point your depednency to a local dir that is already prepared with `git submodule` etc. I don't think `erigon` repo is friendly to be used as go module itself.
