### ISSUE TITLE
Error sync node from some last blocks

### ISSUE THREAD

**Issue by N3KRoN** [ledgerwatch/erigon#4592]
#### System information

Erigon version: 2022.99.99-dev-c03d5735

OS & Version: Linux

Today about 50 minutes ago the node stopped syncing, on manual restart I got an error in TxLookup
<img width="1227" alt="Screen Shot 2022-06-30 at 19 55 10" src="https://user-images.githubusercontent.com/11051346/176734548-f3f5fed6-9ea3-4121-b2a5-5d4f3e07a65e.png">

**Comment by N3KRoN** [comment]
`INFO[06-30|19:23:46.354] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
INFO[06-30|19:23:46.354] Build info                               git_branch=devel git_tag=v2021.10.03-1381-gc03d57356 git_commit=c03d57356c225eeafd703e95d52ec9823881d8e9
INFO[06-30|19:23:46.354] Starting Erigon on Ethereum mainnet... 
INFO[06-30|19:23:46.355] Maximum peer count                       ETH=100 total=100
INFO[06-30|19:23:46.355] torrent verbosity                        level=2
INFO[06-30|19:23:48.457] Set global gas cap                       cap=50000000
INFO[06-30|19:23:48.524] Opening Database                         label=chaindata path=/opt/ethereum/chaindata
INFO[06-30|19:23:48.525] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[06-30|19:23:48.525] Initialising Ethereum protocol           network=1
INFO[06-30|19:23:48.525] Using snapshots                          on=false
WARN[06-30|19:23:48.525] Incorrect snapshot enablement            got=false change_to=true
INFO[06-30|19:23:48.525] Effective                                prune_flags= snapshot_flags="--snapshots=true --snap.stop=true"
INFO[06-30|19:23:52.118] Disk storage enabled for ethash DAGs     dir=/opt/ethereum/ethash-dags count=2
INFO[06-30|19:23:52.474] Starting private RPC server              on=localhost:9000
INFO[06-30|19:23:52.474] new subscription to logs established 
INFO[06-30|19:23:52.482] Started P2P networking                   version=66 self=enode://...@127.0.0.1:30303 name=erigon/v2022.99.99-dev-c03d5735/linux-amd64/go1.18.1
INFO[06-30|19:23:52.484] [Snapshots] Fetching torrent files metadata 
INFO[06-30|19:23:54.846] [Snapshots] Stat                         blocks=14960999 segments=14960999 indices=14960999 alloc=2.6GB sys=4.1GB
INFO[06-30|19:23:54.846] [1/16 Headers] Waiting for headers...    from=15051224
INFO[06-30|19:23:54.922] New txs subscriber joined 
INFO[06-30|19:23:54.922] new subscription to newHeaders established 
INFO[06-30|19:24:14.847] [1/16 Headers] Wrote block headers       number=15051224 blk/second=0.000 alloc=2.7GB sys=4.1GB
INFO[06-30|19:24:34.847] [1/16 Headers] Wrote block headers       number=15051538 blk/second=15.700 alloc=3.1GB sys=4.2GB
INFO[06-30|19:24:53.639] [1/16 Headers] Processed                 highest inserted=15051539 age=1m4s
INFO[06-30|19:24:53.639] [1/16 Headers] DONE                      in=1m1.154748535s
INFO[06-30|19:24:53.654] [4/16 Bodies] Processing bodies...       from=15051224 to=15051539
INFO[06-30|19:25:18.215] [4/16 Bodies] Processed                  highest=15051539
INFO[06-30|19:25:18.216] [5/16 Senders] Started                   from=15051224 to=15051539
INFO[06-30|19:25:18.841] [6/16 Execution] Blocks execution        from=15051224 to=15051539
WARN[06-30|19:25:18.845] [6/16 Execution] Execution failed        block=15051225 hash=0x46252ba27024920def0df49be70059030447e62d76cd95bccf789218a29a9c96 err="could not apply tx 8 from block 15051225 [0x318d53b3cb96ef80172e0c6b63c61336a89f08811cf477aa959d614f8bce1656]: nonce too low: address 0x8729539b95216E4fdD82957C05766CfeBaf75960, tx: 4080 state: 4081"
INFO[06-30|19:25:18.845] UnwindTo                                 block=15051224 bad_block_hash=0x46252ba27024920def0df49be70059030447e62d76cd95bccf789218a29a9c96
INFO[06-30|19:25:18.845] [6/16 Execution] Completed on            block=15051224
EROR[06-30|19:25:18.952] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:19.738] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:20.632] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:21.435] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:22.232] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:23.029] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:23.827] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:24.624] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:25.423] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:26.220] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:27.001] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:27.799] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:28.596] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:29.392] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:30.189] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:30.987] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:31.787] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:32.610] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:33.429] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:34.257] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:35.081] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:35.907] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"
EROR[06-30|19:25:36.731] Staged Sync                              err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"`

**Comment by AlexeyAkhunov** [comment]
Can you show the logs of when it stopped syncing before you restarted? Any errors happened there (look for `EROR` and `WARN` strings)

**Comment by N3KRoN** [comment]
error here: 
`WARN[06-30|19:25:18.845] [6/16 Execution] Execution failed block=15051225 hash=0x46252ba27024920def0df49be70059030447e62d76cd95bccf789218a29a9c96 err="could not apply tx 8 from block 15051225 [0x318d53b3cb96ef80172e0c6b63c61336a89f08811cf477aa959d614f8bce1656]: nonce too low: address 0x8729539b95216E4fdD82957C05766CfeBaf75960, tx: 4080 state: 4081"
INFO[06-30|19:25:18.845] UnwindTo block=15051224 bad_block_hash=0x46252ba27024920def0df49be70059030447e62d76cd95bccf789218a29a9c96
INFO[06-30|19:25:18.845] [6/16 Execution] Completed on block=15051224
EROR[06-30|19:25:18.952] Staged Sync err="[14/16 TxLookup] transform: empty block body 15051224, hash 29391891dc1d75e45ed671783fc86f00ed6b8c17c8deaaa7a9c56c4e11d4ebc9"`


Im trying ./interaction stage_stage but it didn't help.
