### ISSUE TITLE
Erigon BSC panic when I close a subscription

### ISSUE THREAD

**Issue by Sleapy31** [ledgerwatch/erigon#4593]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev-087105d1

OS & Version: Windows/Linux/OSX
Ubuntu 20.04

Commit hash : 
commit 087105d1f31d83ff88ceeca30dfe36dc01de28d7 

#### Expected behaviour
When I close a subscribtion, it close it and Erigon continue to run. If I close my application with a subscription open, Erigon should not panic

#### Actual behaviour
When I close a subscription, from my web3 client or if I kill my application, Erigon panic and crash.

#### Steps to reproduce the behaviour
Open a subscription like "new heads" and close it.

#### Backtrace

````
EROR[06-30|19:37:45.878] catch panic                              err="close of closed channel" stack="[log_panic.go:24 panic.go:838 chan.go:364 eth_filters.go:173 asm_amd64.s:1571]"
INFO[06-30|19:37:45.878] Got interrupt, shutting down...

````
This issue is happening only on BSC, I have another Erigon node synced on Eth mainnet on another server who works as expected.

**Comment by Sleapy31** [comment]
Hi, I still have an issue, not exactly the same but it's related.

panic: send on closed channel

goroutine 5638 [running]:
github.com/ledgerwatch/erigon/turbo/rpchelper.(*Filters).OnNewEvent(0xc0b069a780, 0xc000118060?)
        github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:465 +0x32b
github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices.(*RemoteBackend).Subscribe(0xc0b4ab27d0, {0x1f3c828, 0xc000c12980}, 0xc0ac254630)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices/eth_backend.go:140 +0x1d5
github.com/ledgerwatch/erigon/turbo/rpchelper.New.func1()
        github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:82 +0xe2
created by github.com/ledgerwatch/erigon/turbo/rpchelper.New
        github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:71 +0x33f

**Comment by primalcs** [comment]
sorry, found this one too

**Comment by mandrigin** [comment]
@primalcs @AlexeyAkhunov so was it fixed? If so, please close the issue

**Comment by primalcs** [comment]
@Sleapy31 do you have any more troubles here?

**Comment by Sleapy31** [comment]
> @Sleapy31 do you have any more troubles here?

No it is working now thank you. I will reopen if there is any issues
