### ISSUE TITLE
How to startup a bsc customize private chain.

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#4596]
Does erigon support this feature（customize private chain）?     If yes,  `--chain`  How should I set this parameter

**Comment by AskAlexSharov** [comment]
See https://github.com/ledgerwatch/erigon/blob/devel/DEV_CHAIN.md

**Comment by masayil** [comment]
> Reference in new iss

The consensus protocol is clique. Can it change to parlia?

**Comment by masayil** [comment]
> See https://github.com/ledgerwatch/erigon/blob/devel/DEV_CHAIN.md

The consensus protocol is clique. Can it change to parlia? Create a BSC private chain?
