### ISSUE TITLE
unwind: empty block body 15050000

### ISSUE THREAD

**Issue by pospool** [ledgerwatch/erigon#4606]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.05.6-alpha-327e7d96
OS & Version: Windows/Linux/OSX
Ubuntu 18.04

My node's data was out of sync yesterday, and the following error was reported when checking the log. How can I solve it?

`Jul 02 05:11:48 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:48.288] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:49 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:49.005] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:49 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:49.725] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:50 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:50.450] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:51 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:51.174] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:51 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:51.894] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:52 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:52.619] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:53 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:53.337] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:54 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:54.071] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:54 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:54.798] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:55 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:55.520] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:56 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:56.238] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"
Jul 02 05:11:56 Ubuntu-1804-bionic-64-minimal erigon[16988]: [EROR] [07-02|05:11:56.955] Staged Sync                              err="[14/16 TxLookup] unwind: empty block body 15050000, hash c43d35f6a64f8a64f046c8deb4069572d622dfe7f028f62301b186f08f0e96f2"`

**Comment by AskAlexSharov** [comment]
15050000 it's https://blog.ethereum.org/2022/06/16/gray-glacier-announcement/
try update erigon version

**Comment by pospool** [comment]
> 15050000 it's https://blog.ethereum.org/2022/06/16/gray-glacier-announcement/
> try update erigon version

Whe I upgraded Erigon to the  2022.06.6-alpha-77240899, I got this error:

`Jul 03 09:21:00 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:21:00.137] [6/16 Execution] Unwind Execution        from=15050008 to=15049999
Jul 03 09:21:03 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:21:03.210] [4/16 Bodies] Processing bodies...       from=15049999 to=15068160
Jul 03 09:21:23 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:21:23.210] [4/16 Bodies] Wrote block bodies         block_num=15055476 delivery/sec=7.4MB wasted/sec=0B alloc=3.3GB sys=5.4GB
Jul 03 09:21:32 Ubuntu-1804-bionic-64-minimal erigon[1420]: [WARN] [07-03|09:21:32.246] Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
Jul 03 09:21:43 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:21:43.213] [4/16 Bodies] Wrote block bodies         block_num=15055620 delivery/sec=15.8MB wasted/sec=2.4MB alloc=5.1GB sys=5.5GB
Jul 03 09:21:46 Ubuntu-1804-bionic-64-minimal erigon[1420]: [WARN] [07-03|09:21:46.077] Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
Jul 03 09:22:03 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:22:03.210] [4/16 Bodies] Wrote block bodies         block_num=15055904 delivery/sec=7.7MB wasted/sec=0B alloc=4.0GB sys=5.5GB
Jul 03 09:22:16 Ubuntu-1804-bionic-64-minimal erigon[1420]: [WARN] [07-03|09:22:16.040] Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
Jul 03 09:22:21 Ubuntu-1804-bionic-64-minimal erigon[1420]: [WARN] [07-03|09:22:21.162] Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
Jul 03 09:22:23 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:22:23.211] [4/16 Bodies] Wrote block bodies         block_num=15056734 delivery/sec=9.3MB wasted/sec=213.2KB alloc=5.0GB sys=5.5GB
Jul 03 09:22:36 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:22:36.633] [p2p] GoodPeers                          eth66=5
Jul 03 09:22:43 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:22:43.211] [4/16 Bodies] Wrote block bodies         block_num=15059785 delivery/sec=5.4MB wasted/sec=0B alloc=5.6GB sys=5.9GB
Jul 03 09:23:03 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:03.211] [4/16 Bodies] Wrote block bodies         block_num=15059785 delivery/sec=966.3KB wasted/sec=0B alloc=5.7GB sys=6.1GB
Jul 03 09:23:23 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:23.211] [4/16 Bodies] Wrote block bodies         block_num=15059846 delivery/sec=442.8KB wasted/sec=0B alloc=5.9GB sys=6.2GB
Jul 03 09:23:43 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:43.211] [4/16 Bodies] Wrote block bodies         block_num=15063663 delivery/sec=323.3KB wasted/sec=0B alloc=6.0GB sys=6.4GB
Jul 03 09:23:58 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:58.307] [4/16 Bodies] Processed                  highest=15068160
Jul 03 09:23:58 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:58.307] [4/16 Bodies] DONE                       in=2m55.097654613s
Jul 03 09:23:58 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:23:58.308] [5/16 Senders] Started                   from=15049999 to=15068160
Jul 03 09:24:10 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:24:10.279] [6/16 Execution] Blocks execution        from=15049999 to=15068160
Jul 03 09:24:11 Ubuntu-1804-bionic-64-minimal erigon[1420]: [WARN] [07-03|09:24:11.290] [6/16 Execution] Execution failed        block=15050007 hash=0x6e8b4ef5bd95cbf612e8b65643f18f96f8ee77c91f799260d84b831d6c2d6978 err="could not apply tx 0 from block 15050007 [0x46fc16f7c02f9fafd22f206118dd951e8898011163646f8ffc71c08b7b4b5e41]: nonce too low: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 43240980 state: 43628199"
Jul 03 09:24:11 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:24:11.290] UnwindTo                                 block=15050006 bad_block_hash=0x6e8b4ef5bd95cbf612e8b65643f18f96f8ee77c91f799260d84b831d6c2d6978
Jul 03 09:24:15 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:24:15.820] [6/16 Execution] Completed on            block=15050006
Jul 03 09:24:35 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:24:35.824] [4/16 Bodies] Unwinding transactions...  current block=15057150
Jul 03 09:24:36 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:24:36.633] [p2p] GoodPeers                          eth66=9
Jul 03 09:24:46 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:24:46.672] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:25:05 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:25:05.686] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:25:24 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:25:24.680] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:25:43 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:25:43.617] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:26:02 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:26:02.746] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:26:22 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:26:22.082] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:26:36 Ubuntu-1804-bionic-64-minimal erigon[1420]: [INFO] [07-03|09:26:36.633] [p2p] GoodPeers                          eth66=12
Jul 03 09:26:41 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:26:41.265] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:27:00 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:27:00.407] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:27:19 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:27:19.538] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:27:38 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:27:38.316] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:27:56 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:27:56.933] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 03 09:28:16 Ubuntu-1804-bionic-64-minimal erigon[1420]: [EROR] [07-03|09:28:16.116] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"`

**Comment by AskAlexSharov** [comment]
FYI: https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by AskAlexSharov** [comment]
try:
```
make integration
./build/bin/integration state_stages --unwind=10 --datadir=<your_datadir>
./build/bin/integration stage_headers --unwind=10 --datadir=<your_datadir>
```

**Comment by pospool** [comment]
> try:
> 
> ```
> make integration
> ./build/bin/integration state_stages --unwind=10 --datadir=<your_datadir>
> ./build/bin/integration stage_headers --unwind=10 --datadir=<your_datadir>
> ```

After the execution is completed, there is a new error report


`Jul 04 05:42:48 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:42:48.009] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 04 05:43:08 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:08.724] [4/16 Bodies] Unwinding transactions...  current block=15068611
Jul 04 05:43:13 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:43:13.838] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 04 05:43:24 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:24.410] [p2p] GoodPeers                          eth66=13
Jul 04 05:43:34 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:34.560] [4/16 Bodies] Unwinding transactions...  current block=15068879
Jul 04 05:43:39 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:43:39.280] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 04 05:43:59 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:59.997] [4/16 Bodies] Unwinding transactions...  current block=15068733
Jul 04 05:44:04 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:04.955] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 04 05:44:25 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:44:25.676] [4/16 Bodies] Unwinding transactions...  current block=15069086
Jul 04 05:44:30 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:30.126] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"
Jul 04 05:44:50 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:44:50.847] [4/16 Bodies] Unwinding transactions...  current block=15068733
Jul 04 05:44:55 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:55.872] Staged Sync                              err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"`

**Comment by pospool** [comment]
> > try:
> > ```
> > make integration
> > ./build/bin/integration state_stages --unwind=10 --datadir=<your_datadir>
> > ./build/bin/integration stage_headers --unwind=10 --datadir=<your_datadir>
> > ```
> 
> After the execution is completed, there is a new error report
> 
> `Jul 04 05:42:48 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:42:48.009] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]" Jul 04 05:43:08 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:08.724] [4/16 Bodies] Unwinding transactions... current block=15068611 Jul 04 05:43:13 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:43:13.838] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]" Jul 04 05:43:24 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:24.410] [p2p] GoodPeers eth66=13 Jul 04 05:43:34 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:34.560] [4/16 Bodies] Unwinding transactions... current block=15068879 Jul 04 05:43:39 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:43:39.280] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]" Jul 04 05:43:59 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:43:59.997] [4/16 Bodies] Unwinding transactions... current block=15068733 Jul 04 05:44:04 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:04.955] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]" Jul 04 05:44:25 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:44:25.676] [4/16 Bodies] Unwinding transactions... current block=15069086 Jul 04 05:44:30 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:30.126] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]" Jul 04 05:44:50 Ubuntu-1804-bionic-64-minimal erigon[12079]: [INFO] [07-04|05:44:50.847] [4/16 Bodies] Unwinding transactions... current block=15068733 Jul 04 05:44:55 Ubuntu-1804-bionic-64-minimal erigon[12079]: [EROR] [07-04|05:44:55.872] Staged Sync err="must not happen, ResetSequence: 1122983, lastInDB: 1652931666, trace: [stageloop.go:116 panic.go:844 accessors_chain.go:841 stage_bodies.go:284 default_stages.go:62 sync.go:359 sync.go:203 stageloop.go:150 stageloop.go:53 asm_amd64.s:1571]"`

I solve this issue by this command:
` ./build/bin/integration  stage_headers --reset --datadir=/home/eth/.local/share/erigon
`
