### ISSUE TITLE
BNB Smart Chain Mainnet gasPrice Method Error

### ISSUE THREAD

**Issue by du5** [ledgerwatch/erigon#4630]
```
/ # apk add curl
OK: 13 MiB in 22 packages
/ # curl --location --request POST 'localhost:8545/' \
> --header 'Content-Type: application/json' \
> --data-raw '{
> "jsonrpc":"2.0",
> "method":"eth_gasPrice",
> "params":[],
> "id":73
> }'
{"jsonrpc":"2.0","id":73,"result":"0x0"}
```

```
/ # erigon --version
erigon version 2022.07.1-alpha-09776394
/ #
```

flags ` --prune= --prune.h.older=5000 --prune.t.older=5000 --prune.c.older=5000 --chain=bsc --db.pagesize=16k --http --http.api=eth,web3,net,txpool --http.compression`

![image](https://user-images.githubusercontent.com/54979375/177195731-31c3d41b-0c8c-4a27-856a-96234592c0a2.png)

**Comment by AskAlexSharov** [comment]
```
make integration
./build/bin/integration print_stages --datadir=<your_datadir>
```

**Comment by AskAlexSharov** [comment]
you use erigon's built-in http, right? Not external rpcdaemon?

**Comment by AskAlexSharov** [comment]
Can reproduce. Fixed by https://github.com/ledgerwatch/erigon/pull/4635
It was regression from https://github.com/ledgerwatch/erigon/pull/4528 which caused uin64 underflow (PendingBlock=-1 was converted to uint64)

**Comment by mandrigin** [comment]
@AskAlexSharov do you think it also fixed 4634?

**Comment by mandrigin** [comment]
@du5 so if that is fixed, I am closing this issue. Feel free to reopen if needed.

**Comment by NarupoomChaisawat** [comment]
> > ```
> > make integration
> > ./build/bin/integration print_stages --datadir=<your_datadir>
> > ```
> 
> ```shell
> ➜ erigon git:(097763943) ./build/bin/integration print_stages --datadir /mnt/nvme/erigon/
> หมายเหตุ: prune_atไม่'t หมายถึง 'ข้อมูลทั้งหมดก่อนหน้านี้ถูกลบ' - มันเป็นเพียงขั้นตอนหมายถึง ฟังก์ชันพรุนถูกเรียกใช้ไปยังบล็อกนี้ เนื่องจาก 1 ขั้นตอนอาจตัดข้อมูลหลายประเภทเป็นระยะทางลูกพรุนที่แตกต่างกัน
> 
>                          stage_at prune_at
> ส่วนหัว 19274430 0
> บล็อกแฮชส์ 19274430 0
> ร่างกาย 19274430 0
> ผู้ส่ง 19274430 0
> 19274430 19274430การดําเนินการ
> การแปล 0 0 0
> แฮชสเตท 19274430 0
> 19274430 19274430ระดับกลาง
> บัญชีประวัติศาสตร์19274430 19274430ดัชนี
> การเก็บรักษาประวัติศาสตร์19274430 19274430ดัชนีอินเด็กซ์
> สมุดบันทึกดัชนี 19274430 0
> 19274430 19274430การโทรเทรซ
> 19274430 19269430การค้นหา Tx
> เสร็จสิ้น19274430 0
> --
> ระยะลูกพรุน: --prune.h.older=5000 --prune.t.older=5000 --prune.c.older=5000
> 
> ลําดับ: EthTx = 3204453673, ไม่ใช่ภาษาTx = 9450
> 
> ส่วนหัวแรกใน DB : 19184000
> ร่างกายแรกในฐานข้อมูล : 19184000
> 
> ➜ erigon git:(0810900424)
> ```



>

**Comment by NarupoomChaisawat** [comment]
@NarupoomChaisawat
