### ISSUE TITLE
PoS http configuration is very confusing

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#4641]
This is a follow-up of this [long] discussion that started on discord (please read them all up to the last msg from me saying I'm going to open an issue on github): https://discord.com/channels/687972960811745322/906989870419959818/977295597092618280

Since I agree with most points there, I'd like to summarize the pain points:

1 - mixing configuration of RPC endpoints

Post-merge, you'll having 2 RPC endpoints: :8545 for general use, :8551 for CL. They should not depend on each other's config. 8551 is a privileged port, meant to NOT be opened to public, it is authenticated and it's RPC methods are well defined by EL <-> CL spec.

Currently, enabling 8551 requires you to add the `engine` namespace to the `--http.api` config. `-http.api` is so far meant to enable namespaces on 8545. Now you introduce a change in semantics requiring `engine_` to be added to that config to enable something on 8551. But at the same time it DOES NOT enable `engine_` 8545 (and it MUST NOT) because this is a privileged API.

Solution: don't use `-http.api` param to control CL semantics, let it be a well defined config to control only APIs for 8545.

Also, the argument that geth does the same was denied in a twitter conversation between Chase/Marius.

2 - does it even make sense to any config to control what is enabled or not on :8551? the set of RPC methods is well defined by spec: https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#underlying-protocol

IMHO, only those APIs must be exposed on 8551, no reason for them to be configurable.

3 - `--rpc.accessList` must not interfere on CL endpoint

I whitelisted only some methods in our public sepolia.otterscan.io node, however while configuring a new node for the sepolia merge, I had to disable this entire feature because it was also being applied to the CL endpoint.

I.e., you cant disable `eth_call` on 8545 because it will also disable it on 8551, but it is required by CL spec.

Solution: again, don't apply `--rpc.accessList` rules on 8551.

4 - `--http.vhosts` param must not be applied to CL endpoint

Same as above, the reasoning is: 8545 is a public port, it would make sense for it to have a public hostname assigned; 8551 is an internal, privileged port, it'll be probably exposed on localhost (if CL running together) or in a local network host, if it has a hostname, it'll probably NOT follow a public domain.

If you want to enable a vhosts config to the CL endpoint, make it another config. It makes no sense to mix the same set of vhosts to both endpoints.

**Comment by wmitsuda** [comment]
@MysticRyuujin pls add your comments!

**Comment by MysticRyuujin** [comment]
I agree with all of the above. The `8551` port has a well defined spec and use case, its configuration options should probably be limited but they should definitely be isolated/specific to that port/use case, and the other flags need only apply to the actual JSON-RPC port.

**Comment by mandrigin** [comment]
(1) add 2 flags `--authrpc.addr localhost --authrpc.port 8551` for engine API specifically (same as in Geth to simplify setup)
(2) refactor launching RPC, always filter out `engine_` APIs from the RPCDaemon and hardcode these APIs for the engine HTTP. Move jwt auth only to the engine API.

**Comment by PeaStew** [comment]
when delagting http to rpcdaemon on Ropsten, noticed that setting http=false also disabled engine.port, this was unexpected behaviour as they are not related to each other in my thinking, and of course presents a problem for CL <-> EL interaction

**Comment by mandrigin** [comment]
There is already a PR about this, @nanevardanyan can you check that what @PeaStew wrote does not happen there?

**Comment by nanevardanyan** [comment]
Sure

**Comment by nanevardanyan** [comment]
This issue was fixed by the PR: https://github.com/ledgerwatch/erigon/pull/4822. Should we close it?

**Comment by MysticRyuujin** [comment]
I don't think changes were reflected in any of the README files. I'm happy with the changes but README files are now incorrect.

**Comment by nanevardanyan** [comment]
Good point, will update READMEs. Thank you!
