### ISSUE TITLE
[Streaming] Pending Transaction Hashes without Body

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#4657]
#### System information

Erigon version: v2022.04.05

OS & Version: Ubuntu

#### Bug

Erigon is sending Pending Transaction Hashes which returns `null` with `eth_getTransactionByHash` for very long time. Sometimes forever.

**Comment by mandrigin** [comment]
@Texnomic need more info.
network, command-line, which exact RPC are you using, what is `eth_syncing` and why you mention "Streaming" here.

**Comment by Texnomic** [comment]
> @Texnomic need more info. network, command-line, which exact RPC are you using, what is `eth_syncing` and why you mention "Streaming" here.

@mandrigin I mentioned `Streaming` as in RPC Method `eth_subscribe` + `newPendingTransactions` 

#### Network:
Mainnet (Synced)

#### Command:

```shell
rpcdaemon --ws --grpc --pprof --metrics --metrics.expensive --grpc.healthcheck --datadir /mnt/data/ --private.api.addr 127.0.0.1:9090 --http.addr 0.0.0.0 --metrics.addr 0.0.0.0 --metrics.port 6071 --verbosity 4 --http.port 8545 --http.vhosts '*' --http.api eth,erigon,web3,net,debug,trace,txpool,db,parity --pprof.port 6063  
```

#### RPC:
`eth_subscribe` -> `newPendingTransactions` -> `eth_getTransactionByHash` -> `null`

**Comment by Texnomic** [comment]
@mandrigin Any update on this issue ?
