### ISSUE TITLE
[Streaming] Duplicated Pending Transaction Hashes

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#4658]
#### System information

Erigon version: v2022.04.05

OS & Version: Ubuntu

#### Bug

Erigon is sending duplicated Pending Transaction Hashes multiple times.

**Comment by mandrigin** [comment]
Again, your network, erigon command line, rpc commands that you use to receive hashes, and response you are getting. Please add that otherwise it is impossible to debug.

**Comment by Texnomic** [comment]
> Again, your network, erigon command line, rpc commands that you use to receive hashes, and response you are getting. Please add that otherwise it is impossible to debug.

#### Network:
Mainnet

#### Command:

```shell
rpcdaemon --ws --grpc --pprof --metrics --metrics.expensive --grpc.healthcheck --datadir /mnt/data/ --private.api.addr 127.0.0.1:9090 --http.addr 0.0.0.0 --metrics.addr 0.0.0.0 --metrics.port 6071 --verbosity 4 --http.port 8545 --http.vhosts '*' --http.api eth,erigon,web3,net,debug,trace,txpool,db,parity --pprof.port 6063  
```

#### RPC:
`eth_subscribe` -> `newPendingTransactions`

**Comment by Texnomic** [comment]
@mandrigin Any update on this issue ?
