### ISSUE TITLE
trace_* grinds RPC calls to 5X slower

### ISSUE THREAD

**Issue by alysak6075** [ledgerwatch/erigon#4661]
#### System information

Erigon version: `erigon version 2022.06.6-alpha-77240899`

OS & Version: Windows/Linux/OSX

CentOS 8

Commit hash : `7724089985bf9cb8bb7d1bde92892256a6af859f`

#### Expected behaviour
RPC calls return in a normal fashion 

#### Actual behaviour
after several concurrent `trace_*` calls, all calls to RPC slow down by 5X or more times

#### Steps to reproduce the behaviour
call `trace_transaction` on any hash

this was not an issue on `v2022.04.02`

no errors or issues in the log. Everything just takes forever.

Running on bare metal SATA SSD

**Comment by mandrigin** [comment]
does it recover if you give some "rest" to the node?

**Comment by alysak6075** [comment]
Yes

**Comment by mandrigin** [comment]
yep, it isn't a leak, we have fixed json streaming in the latest `devel` branch see https://github.com/ledgerwatch/erigon/issues/4637

**Comment by mandrigin** [comment]
@alysak6075 did it help?

**Comment by alysak6075** [comment]
Hi. Sorry ive been traveling for a while. Havent had the time to dedicate to testing. I will test ASAP and will let you know.

**Comment by mandrigin** [comment]
@alysak6075 sure, looking forward to the results

**Comment by AskAlexSharov** [comment]
I did cut-off 50ms from trace_* calls by https://github.com/ledgerwatch/erigon/pull/4985

**Comment by mandrigin** [comment]
okay, I will close it for now @alysak6075 if the issue persists, please reopen
