### ISSUE TITLE
rpcdaemon v2022.07.02: MDBX_NOTFOUND: No matching key/data pair found

### ISSUE THREAD

**Issue by yiteng-guo** [ledgerwatch/erigon#4673]
#### System information

Erigon version: `./erigon --version`: devel or v2022.07.02

Commit hash : devel=e13a318e0

#### Expected behaviour

```
rpcdaemon --datadir=/path/to/erigon --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool,db --http.addr=0.0.0.0 --http.port 8546 --http.vhosts="*"
```

This command should work.

#### Actual behaviour

Exits with
```
EROR[07-07|14:38:46.857] Could not connect to DB                  err="create bucket: CodeR, mdbx_dbi_open: MDBX_NOTFOUND: No matching key/data pair found
```

Note that it works without any problem if I don't add `--datadir` to rpcdaemon.

#### Steps to reproduce the behaviour

DataDir structure
```
/path/to/erigon 
 |- bor
 |- chaindata
 |- etl-temp
 |- jwt.hex
 |- LOCK
 |- nodekey
 |- nodes
 |- snapshots
 |- txpool
```

**Comment by AskAlexSharov** [comment]
show erigon cli flags

**Comment by AskAlexSharov** [comment]
How do you build rpcdaemon? I feel that you run “./cmd/rpcdaemon22” instead of “./cmd/rpcdaemon”

**Comment by yiteng-guo** [comment]
```
make erigon && make rpcdaemon
```
and
```
./build/bin/rpcdaemon ...
```

I just cleaned my build dir and only built the rpcdaemon by `make rpcdaemon`. It didn't work as well.

**Comment by yiteng-guo** [comment]
Any update on this?

**Comment by AskAlexSharov** [comment]
What error you see now? On what request?

**Comment by yiteng-guo** [comment]
nvm. My erigon and rpcdaemon were on different versions. It worked after I upgraded both to the latest alpha releases.
