### ISSUE TITLE
Large torrent announce response panic erigon client every time on Windows

### ISSUE THREAD

**Issue by mconover** [ledgerwatch/erigon#4674]
#### System information

Erigon version: erigon version 2022.07.1-alpha-09776394

OS & Version: Windows 11

Commit hash : 
This one works: erigon.exe version 2022.06.6-alpha-77240899
This one panics across all Windows devices I have tested: erigon version 2022.07.1-alpha-09776394

This is due to default UDP buffer size being 8K and no easy way to increase the size. So this was some change in the alpha branch between June 20 and July 1.

#### Expected behaviour
Erigon starts torrent traffic and either concludes

#### Actual behaviour
Erigon exits with the error message:
panic: read udp6 [::]:53397: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

#### Steps to reproduce the behaviour
Use the latest alpha branch and it will fail uncoditionally as soon as it starts torrent communication

#### Backtrace
goroutine 253 [running]:
github.com/anacrolix/torrent/tracker/udp.(*ConnClient).reader(0xc08406a140)
        github.com/anacrolix/torrent@v1.44.0/tracker/udp/conn-client.go:42 +0x295
created by github.com/anacrolix/torrent/tracker/udp.NewConnClient
        github.com/anacrolix/torrent@v1.44.0/tracker/udp/conn-client.go:102 +0x245
panic: read udp6 [::]:53394: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

goroutine 275 [running]:
github.com/anacrolix/torrent/tracker/udp.(*ConnClient).reader(0xc083fa4000)
        github.com/anacrolix/torrent@v1.44.0/tracker/udp/conn-client.go:42 +0x295
created by github.com/anacrolix/torrent/tracker/udp.NewConnClient
        github.com/anacrolix/torrent@v1.44.0/tracker/udp/conn-client.go:102 +0x245
[15:38:04.32] erigon exited with error 2 (aborting)

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
I will take a look

**Comment by AskAlexSharov** [comment]
@mconover hi, try branch: `win_limit_udp`

**Comment by AskAlexSharov** [comment]
Great

**Comment by acdop100** [comment]
I unfortunately am still getting this error even on the `win_udp_limit` branch. Here is my error:

panic: read udp6 [::]:49157: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

goroutine 373 [running]:
github.com/anacrolix/torrent/tracker/udp.(*ConnClient).reader(0xc0ab246280)
        github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/tracker/udp/conn-client.go:46 +0x295
created by github.com/anacrolix/torrent/tracker/udp.NewConnClient
        github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/tracker/udp/conn-client.go:112 +0x297

Not sure what to do at this point. I've run `.\wmake.ps1 clean` as well with no change.

**Comment by acdop100** [comment]
Disabling the downloader component seems to get past this. Are there any updates on this?

**Comment by AskAlexSharov** [comment]
no, didn't work on it since last update
