### ISSUE TITLE
how to run a eriogon node on bsc net  with Snap sync mode?

### ISSUE THREAD

**Issue by flywukong** [ledgerwatch/erigon#4681]
I need to run a eriogon node on bsc net , also , I wonder if this can be done with with Snap sync mode.
thanks for any guide

**Comment by AskAlexSharov** [comment]
—chain=bsc

**Comment by flywukong** [comment]
https://github.com/ledgerwatch/erigon/issues/4681#issuecomment-1179469167

I saw that  Snap sync seems disabled  in bsc mainnet

**Comment by AskAlexSharov** [comment]
I think - enabled by default.
