### ISSUE TITLE
 Staged Sync  err="runtime error: invalid memory address or nil pointer dereference, 

### ISSUE THREAD

**Issue by mtgnoah** [ledgerwatch/erigon#4684]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev-b06b4b4c

OS & Version: Ubuntu

Commit hash : 

#### Expected behaviour
It it supposed to just do this
INFO[07-09|08:20:09.539] [6/16 Execution] Executed blocks         number=14981548 blk/s=16.6 tx/s=2957.0 Mgas/s=257.0 gasState=0.48 estimated duration=3h46m28.700s batch=531.2MB alloc=4.8GB sys=8.8GB

#### Actual behaviour
Occasionally it does this
 Staged Sync  err="runtime error: invalid memory address or nil pointer dereference, trace: [stageloop.go:125 panic.go:844 panic.go:220 signal_unix.go:818 stage_execute.go:142 stage_execute.go:305 default_stages.go:85 sync.go:327 sync.go:235 stageloop.go:159 stageloop.go:80 asm_amd64.s:1571]"

#### Steps to reproduce the behaviour
My computer crashed during a power outtage and now this happens around block 14990000 and occasionally erigon just crashes the whole pc. 

#### Backtrace

````
[backtrace]
````

**Comment by mandrigin** [comment]
Many things to unpack here :)

(1) Can you share the full log?

(2) Can you try on the latest release and on the latest `devel` version?

**Comment by mtgnoah** [comment]
> Many things to unpack here :)
> 
> (1) Can you share the full log?
> 
> (2) Can you try on the latest release and on the latest `devel` version?

Yes I will try on latest release and will then post the full log

**Comment by mtgnoah** [comment]
I tried to use a backup of this too which had left off at 10 million blocks and got the same error again.

**Comment by awskii** [comment]
@mtgnoah please verify your datadir via 
```
cd ERIGON_SOURCE
./build/bin/downloader --datadir /path/To/ErigonDataDirectory`
```

Maybe some bodies or tx data was not downloaded correctly (or not finished) which led to this

**Comment by mandrigin** [comment]
@mtgnoah yeah, I also have seen this error, we will invistigate

**Comment by mandrigin** [comment]
in the meantime, try the latest devel one more time, a couple of things were fixed there

**Comment by mtgnoah** [comment]
I ended up just deleting and starting from scratch but I do have a backup of that datadir so I might be able to test the error eventually if I buy more ssds.

**Comment by mandrigin** [comment]
okay, I will close for now, if I reproduce it again, I will reopen
