### ISSUE TITLE
Ropsten sync from scratch gives `Fork choice missing header` error constantly

### ISSUE THREAD

**Issue by iFA88** [ledgerwatch/erigon#4686]
Greetings!

I have synced ropsten from scratch with prysm but i got constantly `Fork choice missing header` error after activated PoS.
https://gist.github.com/iFA88/8fa7a082015e5a1e1fa28a9369b64290
After unwind 1000 blocks:
https://gist.github.com/iFA88/953af843e8cf9f10a48d3b5a54a4d940

Prysm works good, i have an other erigon+prysm combo on another server which works well.
Any suggestion welcome. Thanks!

**Comment by iFA88** [comment]
After restart and after 45 min some miracle happened and now syncing new pos blocks:
https://gist.github.com/iFA88/26ef069c98c0be99954c0b94d673de36

**Comment by mandrigin** [comment]
yeah, it does show that and then it loads all of them somehow, I do not consider this harmful unless it repeat the same headers over and over again.
that could happen on chain forks and reorgs

**Comment by mandrigin** [comment]
> > yeah, it does show that and then it loads all of them somehow, I do not consider this harmful unless it repeat the same headers over and over again. that could happen on chain forks and reorgs
> 
> Yeah, just it was about a day in this state :(

It is just a bad mode of syncing, it sync but slowly. We will try to improve but right now we need to focus on critical issues.
