### ISSUE TITLE
Consistency in version number

### ISSUE THREAD

**Issue by 73649** [ledgerwatch/erigon#4695]
#### System information

Erigon version: v2022.07.02

OS & Version: Ubuntu 20.04 LTS

Commit hash : This is the problem I am reporting

#### Expected behaviour
Version number should be consistent 

#### Actual behaviour
I downloaded Release v2022.07.02 and when I ran "git describe --tag", it says:
`v2022.07.02`

But when I ran it, the log starts with:
`Build info                               git_branch=devel git_tag=v2021.10.03-1405-g8e3c09949 git_commit=8e3c099490948ce33729c991b4bdff553420c201`

When I call json RPC using 
curl --data '{"method":"web3_clientVersion","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://127.0.0.1:8545, it responds with:
`{"jsonrpc":"2.0","id":1,"result":"erigon/2022.99.99/linux-amd64/go1.18.3"}`

Can we have some consistency in version, please?

**Comment by AskAlexSharov** [comment]
Show more info:
- what “git status” shows
- what command you using to build erigon
- - what command you using to run erigon
- - what “erigon —version” shows

**Comment by gavbennett** [comment]
@AskAlexSharov Attached is I think all the info you were looking for.

I'm experiencing the same issue as it relates to version #. Additionally, I'm having the issue noted in #4674 
![Terminal](https://user-images.githubusercontent.com/94311667/181933649-3fe8a30c-a1e4-44be-a607-72a3de8f0cad.png)

I followed the steps in #4606 to make integration/unwind, but after re-running erigon the issue remained the same.

**Comment by AskAlexSharov** [comment]
Original issue: https://github.com/anacrolix/torrent/issues/764
Need to solve it somehow
