### ISSUE TITLE
RPC method eth_getLogs crashed: runtime error: index out of range [2] with length 0

### ISSUE THREAD

**Issue by x-EricH-x** [ledgerwatch/erigon#4710]
Suspecting a bug, but can also be data corruption in my local node,
but either way I don't have good clues on how to solve it.

#### System information

Erigon version: 2022.07.2-alpha-c7a94eee

OS & Version: Linux, Ubuntu 22.04 LTS

Commit hash : HEAD detached at v2022.07.02

#### Expected behaviour
JSON RPC should returns sth like
````
{
  "id":0
  "jsonrpc":"2.0"
  "result":[{...},{...}, ...]
}
````
#### Actual behaviour
JSON RPC returned.

request:
````
{ 'id': 0,
  'jsonrpc': '2.0',
  'method': 'eth_getLogs',
  'params': [ { 'address': '0x34d85c9cdeb23fa97cb08333b511ac86e1c4e258',
                'fromBlock': '0xe022e8',
                'toBlock': '0xe022e8',
                'topics': [ '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef']}]}
````

response:
```
{ 'error': {'code': -32000, 'message': 'method handler crashed'},
  'id': 0,
  'jsonrpc': '2.0'}
```

and in the rpc daemon, there is an error msg
````
EROR[07-13|19:54:43.681] RPC method eth_getLogs crashed: runtime error: index out of range [2] with length 0
[service.go:217 panic.go:838 panic.go:93 eth_receipts.go:199 value.go:556 value.go:339 service.go:222 handler.go:503 handler.go:408 handler.go:353 handler.go:187 handler.go:277 asm_amd64.s:1571] 
````

#### Steps to reproduce the behaviour

send a `eth_getLogs` rpc call using the request shown above

#### Backtrace
N/A

**Comment by x-EricH-x** [comment]
> @x-EricH-x can you also show the command-line of Erigon you are running, especially the pruning flags?

sure, I didn't explicitly pass any pruning flags though.

here is the line for erigon
```
time ./erigon-repo/build/bin/erigon --datadir=./erigon-data/ --private.api.addr=localhost:9090 --http=false
```

and here is the line for the rpc daemon
```
time ./erigon-otterscan/build/bin/rpcdaemon --datadir=./erigon-data/ --ws --txpool.api.addr=localhost:9090 --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool,ots --http.corsdomain "*"
```

**Comment by x-EricH-x** [comment]
> > Suspecting a bug, but can also be data corruption in my local node, but either way I don't have good clues on how to solve it.
> > #### System information
> > Erigon version: 2022.07.2-alpha-c7a94eee
> > OS & Version: Linux, Ubuntu 22.04 LTS
> > Commit hash : HEAD detached at v2022.07.02
> > #### Expected behaviour
> > JSON RPC should returns sth like
> > ```
> > {
> >   "id":0
> >   "jsonrpc":"2.0"
> >   "result":[{...},{...}, ...]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Actual behaviour
> > JSON RPC returned.
> > request:
> > ```
> > { 'id': 0,
> >   'jsonrpc': '2.0',
> >   'method': 'eth_getLogs',
> >   'params': [ { 'address': '0x34d85c9cdeb23fa97cb08333b511ac86e1c4e258',
> >                 'fromBlock': '0xe022e8',
> >                 'toBlock': '0xe022e8',
> >                 'topics': [ '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef']}]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > response:
> > ```
> > { 'error': {'code': -32000, 'message': 'method handler crashed'},
> >   'id': 0,
> >   'jsonrpc': '2.0'}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in the rpc daemon, there is an error msg
> > ```
> > EROR[07-13|19:54:43.681] RPC method eth_getLogs crashed: runtime error: index out of range [2] with length 0
> > [service.go:217 panic.go:838 panic.go:93 eth_receipts.go:199 value.go:556 value.go:339 service.go:222 handler.go:503 handler.go:408 handler.go:353 handler.go:187 handler.go:277 asm_amd64.s:1571] 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Steps to reproduce the behaviour
> > send a `eth_getLogs` rpc call using the request shown above
> > #### Backtrace
> > N/A
> 
> 0466c3ab45c0611f2befdacdeb39954f131ff3f25b28b3b7ac971aa536949f6a

what does "0466c3ab45c0611f2befdacdeb39954f131ff3f25b28b3b7ac971aa536949f6a" means and why am I getting a thumbs down?

**Comment by mandrigin** [comment]
@x-EricH-x I removed that comment, no clue who that is.

**Comment by leonardchinonso** [comment]
I want to pick this up @mandrigin. Have anyone on it yet?

**Comment by x-EricH-x** [comment]
@leonardchinonso 
I believe no one have picked it up yet, and would be great if you can help investigate.

I am trying to do a fresh sync from the scratch atm, but that will take some time and I am not sure if it will actually help.

**Comment by leonardchinonso** [comment]
Alright, I'll pick it up today, thank you!

**Comment by x-EricH-x** [comment]
@mandrigin 

hi, the fresh sync is finished and it seems it result is normal now.
I guess it is indeed data corruption.

Do you know if there is a command in erigon to check data integrity?
Would be nice to run it if similar issue arise again, as fresh will take days and therefore much better to have a check before blindly doing a fresh sync : )
