### ISSUE TITLE
Allow re-downloading missing snapshot data

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#4711]
Since all of the files required for snapshot sync are already shared via BitTorrent - it would be cool if a node started with missing snapshot data could identify the missing pieces and re-download.

I attempted to test if this was possible by simply moving all of the `v1-013000-013500*` files to a different folder then starting Erigon, hoping Erigon would notice that the files were missing and re-download them. However, I got the following error:

```
[INFO] [07-13|21:19:32.269] [Snapshots] Fetching torrent files metadata 
[EROR] [07-13|21:19:32.299] Staged Sync                              err="[1/16 Headers] ReopenSegments: snapshot missed: from 13000000 to 13500000"
[INFO] [07-13|21:19:33.033] [Snapshots] Fetching torrent files metadata 
[EROR] [07-13|21:19:33.064] Staged Sync                              err="[1/16 Headers] ReopenSegments: snapshot missed: from 13000000 to 13500000"
```
Repeating

This would make sharing full archive node snapshots easier, as we wouldn't have to re-distribute and duplicate the storage of these files that are already shared by lots of nodes.

**Comment by enriavil1** [comment]
You can try it out now on the latest devel
