### ISSUE TITLE
eth_getTransactionByHash return null result for all transaction

### ISSUE THREAD

**Issue by neal-zhu** [ledgerwatch/erigon#4725]
eth_getTransactionByHash return null result for all transaction

**Comment by AskAlexSharov** [comment]
Show erigon logs and output of eth_syncing

**Comment by AskAlexSharov** [comment]
I thin you not synced yet

**Comment by joucksHua** [comment]
meto

**Comment by leonardchinonso** [comment]
Hi @neal-zhu, I want to pick this up in case its a bug. Can you share your running state and erigon logs so I'll know if its a syncing issue or not
