### ISSUE TITLE
docker-compose and makefile referencing stale tags

### ISSUE THREAD

**Issue by raymogg** [ledgerwatch/erigon#4735]
#### System information

Erigon version: `./erigon --version`

OS & Version:Linux

Commit hash : 

#### Expected behaviour
When running `docker-compose`, the system should start up.

#### Actual behaviour
The docker-compose file is attempting to pull a docker image `thorax/erigon:latest` however when referring to dockerhub (https://hub.docker.com/r/thorax/erigon/tags) it appears that it should be referencing `thorax/erigon:stable`.

#### Steps to reproduce the behaviour
Run make docker-compose

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
“stable” it’s very old deprecated tag. We don’t recommend to use it now. 
we will come with better naming soon

**Comment by raymogg** [comment]
> “stable” it’s very old deprecated tag. We don’t recommend to use it now. we will come with better naming soon

So if I was to modify the docker-compose file, should I refer to the ` docker_default_uid` tag?

**Comment by AskAlexSharov** [comment]
What’s wrong with releases? Like: v2022.07.02

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon/releases
