### ISSUE TITLE
eth_getBlockTransactionCountByHash & eth_getBlockTransactionCountByNumber return null

### ISSUE THREAD

**Issue by soos3d** [ledgerwatch/erigon#4755]
#### Expected behavior

Should return the number of transactions recorded in that block. Something like this:

```sh
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x6c"
}
````

#### Actual behavior

It returns ```null```

```sh
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": null
}
````

#### Steps to reproduce the behavior

Send this request to an Ethereum node running Erigon:

```sh
curl -X POST 'ERIGON_NODE_URL' \
-H 'Content-Type: application/json' \
--data'{"method":"eth_getBlockTransactionCountByHash","params":["0xef746ecf9ee19f508fb16d204ace10ac799f938d4cb87852fe85ab8de24b70ab"],"id":1,"jsonrpc":"2.0"}'
```

Sending the same request to an archive node running Geth retrieves the correct result. 

The block exists in the Erigon database as the following request returns the correct data:

```sh
curl -X POST 'NODE_URL' \
-H 'Content-Type: application/json' \
--data'{"method":"eth_getBlockByHash","params":["0xaafff6dbabc20c5c2d58f5a8f336575f22681fd23a9e53bf81e69d8130a29b9c",false],"id":1,"jsonrpc":"2.0"}'
```

> Requests tested with Postman, web3.py, and web3.js.
Web3.py results in a traceback, web3.js and Postman return ```null```.

**Comment by leonardchinonso** [comment]
Hi @soos3d do you still have this issue?

**Comment by soos3d** [comment]
> Hi @soos3d do you still have this issue?

Yes, it is still doing it.
