### ISSUE TITLE
Instructions in readme cause people to build devel branch at random commits instead of release branches

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#4756]
#### System information

![image](https://user-images.githubusercontent.com/34198053/179778259-c3b0000a-f371-4ca5-82bd-bfe301ecf780.png)

These instructions really should have instructions on how to find the latest release branches for beta/alpha and how to check them out before building:
```
git clone --recurse-submodules -j8 https://github.com/ledgerwatch/erigon.git
cd erigon
```
<-- find `<release branch>` instructions -->
```
git checkout <release branch>
make erigon
./build/bin/erigon
```

**Comment by PeaStew** [comment]
Latest Beta: https://github.com/ledgerwatch/erigon/releases?q=beta&expanded=true
Latest Alpha: https://github.com/ledgerwatch/erigon/releases?q=alpha&expanded=true

**Comment by tjayrush** [comment]
I'm not officially on the team, but you should make a PR instead of just an issue. I've done that in the past. The team is very open to useful additions to the README such as this.

Plus, I think you're absolutely right. Better instructions are needed. I've gotten bitten multiple times by building the wrong version.

**Comment by AskAlexSharov** [comment]
Now tags do not contain information: is it "beta" or "alpha". it's confusing. Only way to find release - search on github: https://github.com/ledgerwatch/erigon/issues/4756#issuecomment-1189148133
We will change naming of versions/tags soon - will add there clear label about beta/alpha/etc... 
For now we recommend: run latest "alpha" version.

**Comment by PeaStew** [comment]
> I'm not officially on the team, but you should make a PR instead of just an issue. I've done that in the past. The team is very open to useful additions to the README such as this.
> 
> Plus, I think you're absolutely right. Better instructions are needed. I've gotten bitten multiple times by building the wrong version.

Was asked by @mandrigin to make an issue specifically.

**Comment by mandrigin** [comment]
Yep, I did ask for that, because even fixing now won’t really solve it until we promote the current alpha to stable. And then it’s a good time to update the docs.
