### ISSUE TITLE
do erigon need execution  after downloading snapshot?

### ISSUE THREAD

**Issue by flywukong** [ledgerwatch/erigon#4768]
I doubt whether erigon need execution from genesis or  just exection from the height of snapshot after downloading snapshot.

Suppose I now have an erigon node stage sync that has completed a 1000w height block,  then use the erigon snapshots command to create a 1..1000w height snapshot.  Then we start a downloader service to seed the torrent file and start another erigon which has specify this downloader addr to download the snapshot. So after downloading snapshot, the new started erigon node can start the stage sync and execution from the 1000w block or still need execution from genesis  ?

**Comment by AskAlexSharov** [comment]
Yes. 
But it will change in future. 
“Erigon2 Upgrade2” will add snapshots of state: https://erigon.substack.com/p/erigon-2-three-upgrades

**Comment by mandrigin** [comment]
answered, will be implemented in the future updates
