### ISSUE TITLE
erigon polygon network unusual approach, weird reply data size and slow reply

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#4769]
#### System information

Erigon version: 2022.07.2-alpha-c7a94eee

OS & Version: Linux

Commit hash : 
```
/usr/local/bin/erigon --datadir=/node/full/polygon-erigon/ --chain=bor-mainnet --prune=hrtc --bor.heimdall=${heimdallAddr} --port=31290 --private.api.addr=127.0.0.1:31293 --torrent.port=31294 --http=false --db.read.concurrency 2000 --rpc.batch.concurrency 10000
/usr/local/bin/rpcdaemon --datadir=/node/full/polygon-erigon/ --private.api.addr=localhost:31293 --http.api 'eth,erigon,web3,net,debug,trace,txpool,db,starknet,bor' --http.addr 0.0.0.0 --http.port 31291 --http.vhosts '*' --http.corsdomain '*' --ws --db.read.concurrency 2000 --rpc.batch.concurrency 80000
```

#### Expected behaviour
json rpc request method `eth_getBlockByNumber`
Use methods to request data, return data in seconds, and support a considerable amount of concurrency

#### Actual behaviour
Tested on the same server, bor concurrency is 60k/reqs per second
, but erigon is only 9k/reqs under this method, and the return time is very long
bor: 
    k6: 60k/reqs
    net upload speed: 20M/s
erigon
    k6: 9s/reqs
    net upload speed: 900M/s

The network used here is very strange. According to the block data size and request rate, this large body will not be returned to the requester.
![image](https://user-images.githubusercontent.com/24621599/179988710-69863295-330f-4147-b372-4237677b5a3f.png)
![image](https://user-images.githubusercontent.com/24621599/179988756-c5a694f6-0de4-49a7-9cc8-f82a5a4c4284.png)
![image](https://user-images.githubusercontent.com/24621599/179988830-62e13c07-4c36-457f-a614-0f322319c2b6.png)

#### Steps to reproduce the behaviour
Use the k6 load tool to run the following script, you need to modify the IP and block height in the script

#### Backtrace

````
[backtrace]
````
[1.txt](https://github.com/ledgerwatch/erigon/files/9149963/1.txt)

**Comment by AskAlexSharov** [comment]
1. do you request historical blocks or recent blocks?
2. try reduce --db.read.concurrency to default value
3. try add --pprof flag to rpcdaemon, start load test, and show us result of `go tool pprof -png  http://127.0.0.1:6060/debug/pprof/profile\?seconds\=20 > cpu.png`
4. "bor concurrency is 60k/reqs per second" - what is "bor concurrency"?
