### ISSUE TITLE
polygon: trace_block:  insufficient funds for gas * price + value 

### ISSUE THREAD

**Issue by joucksHua** [ledgerwatch/erigon#4784]
#### System information

Erigon version: last

OS & Version: Linux
block_num:10852073 10852077
jsonrpc request:{
    "jsonrpc": "2.0",
    "method": "trace_block",
    "params": ["0xa596e9"],  
    "id": 1
}
request result:
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "first run for txIndex 2 error: insufficient funds for gas * price + value: address 0x1CA971963bdb4BA2BF337c90660674AcFf5Beb3f have 1340837000000000 want 2808193000000000"
    }
}

**Comment by AskAlexSharov** [comment]
Erigon cli flags?

**Comment by joucksHua** [comment]
> Erigon cli 标志？

./bin/erigon \
        --chain=bor-mainnet \
        --bor.heimdall=http://10.10.17.2:2327 \
        --torrent.download.rate=512mb \
        --torrent.upload.rate=6mb \
        --datadir=/opt/erigon-bor/data \
        --torrent.port=42069 \
        --port=40306 \
        --private.api.addr=localhost:9092 \
        --http \
        --http.port=9547 \
        --http.addr=10.10.17.4 \
        --http.api=eth,erigon,web3,net,debug,trace,txpool

**Comment by joucksHua** [comment]
block_num:10852073, 10852077, 11318361, 11318363
hope to solve this problem！

**Comment by penglipeng666** [comment]
me too !!!
Hope to solve this problem soon

**Comment by michaelscheung** [comment]
I see that there is PR to fix this issue. In case it is at all useful, I have attached a list of over 40,000 blocks where I've encountered this error for polygon:
[insufficient_funds_blocks.txt](https://github.com/ledgerwatch/erigon/files/9276430/insufficient_funds_blocks.txt)
