### ISSUE TITLE
how to change chaindata from pagesize 4k to 8k

### ISSUE THREAD

**Issue by flywukong** [ledgerwatch/erigon#4789]
I have run a archive node using erigon which has finished syncing to latest block using pagesize 4k ,  now the data is nearly 6.5T now . Now I need  make the data in mdbx  turned to pagesize 8k  to support  more data in future . Instead of   running another archive node from genesis  using pagesize 8k ,   I wonder if I can use the mdbx tool to finish this change which is faster ?

**Comment by AskAlexSharov** [comment]
Create new db with 8kb pagesize. Copy all data there: my mdbx_dump/mdbx_load, or by “integration mdbx_to_mdbx”

**Comment by flywukong** [comment]
@AskAlexSharov  how can I create new db with 8kb pagesize?  by start another erigon node with 8Kb?

**Comment by AskAlexSharov** [comment]
yep

**Comment by mandrigin** [comment]
okay, ping me if there are any more questions, closing this for now
