### ISSUE TITLE
erigon execution failed  on bsc 

### ISSUE THREAD

**Issue by flywukong** [ledgerwatch/erigon#4798]
I have finished sync and catched up to latest block using erigon on bsc with archive mode.

**But I got some warn , and sync will stoped and keep on writing header after error:  
It happens every  5-15 hours** 

[WARN] [07-22|16:57:27.170] [6/16 Execution] Execution failed        block=19778438 hash=0xaf953acfb4a537588944d186f8d1f06108dc734d63426886ef04d5d6428d2d8e err="mismatched receipt headers for block 19778438 (0x7c0fda9097bbf96b30b00497a39d3c6b3dc715beb9f904707b7f1d1782098ca5 != 0xd0184e4ef435c2c8893edf85a4b0067af15dce4e54ac298fdbdd1c5e3eb85ee3)"

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/19421226/180586701-cef52641-2e0e-4f41-bec0-53b2941c6ebf.png">

 After restarting,  it can continue to synchronize blocks normally

**Comment by du5** [comment]
@AskAlexSharov  This problem is caused by validating nodes being slashed https://bscscan.com/address/0x0000000000000000000000000000000000001001#events

**Comment by du5** [comment]
https://bscscan.com/tx/0x130700c4a226a5267ee613d5b0b57074799a654198f5548a69719bdfa34b45e6

**Comment by du5** [comment]
#4821
