### ISSUE TITLE
Can't make <datadir>/etl-temp a mount (so can't use tmpfs etc.)

### ISSUE THREAD

**Issue by softwareplumber** [ledgerwatch/erigon#4815]
#### System information

Erigon version: 2022.99.99-dev-9637b25a

OS & Version: Windows/Linux/OSX

Commit hash :  e13a318e0b3b97e8161d40708000d5025d066bac

#### Expected behaviour

In docker (or kubernetes, or whatever) should be able to put the etl-temp folder on a separate filesystem (maybe tmpfs or whatever).

#### Actual behaviour

Application errors out on startup as it does os.RemoveAll on etl-temp, which tries to remove the folder itself, which returns an error if the folder is amount

#### Steps to reproduce the behaviour

erigon --datadir=/data
where /data/etl-temp is a mount

In backend.go (around line 150): 

	tmpdir := stack.Config().Dirs.Tmp
	if err := **os.RemoveAll(tmpdir);** err != nil { // clean it on startup
		return nil, fmt.Errorf("clean tmp dir: %s, %w", tmpdir, err)
	}

**Comment by AskAlexSharov** [comment]
Is it fixing for you: https://github.com/ledgerwatch/erigon/pull/4816

**Comment by softwareplumber** [comment]
LGTM but I just finished for the night - I'll rebuilt tomorrow to make sure. 
Many thanks
Jon

**Comment by mandrigin** [comment]
@softwareplumber ping me if it doesn't help you
