### ISSUE TITLE
Very slow TruncateBlocks issue during migration with latest Erigon

### ISSUE THREAD

**Issue by krunkosaurus** [ledgerwatch/erigon#4840]
#### System information

Erigon version: `erigon version 2022.99.99-dev-329d5864`

OS & Version: OSX, latest M1 Mac Mini + 4TB SSD

#### Actual behaviour

Upgraded to latest Erigon build. Ran Erigon and it needs to migrate data and redownlaod last 400k blocks. They have been processing at around 3 blocks a minute. It's going to take 106 days at this rate. I tried restarting computer, ensuring all proper ports are unblocked, tested my download speeds and all is fine. Please advise if I should just start from scratch or any other info you need.

#### Expected behaviour

Be able to finish sync within a few days.

<img width="1307" alt="Screen Shot 2022-07-27 at 4 58 22 PM" src="https://user-images.githubusercontent.com/20738/181206917-a1bf852e-a3ad-442e-8ae2-80add8e9fe06.png">
<img width="415" alt="Screen Shot 2022-07-27 at 10 47 17 AM" src="https://user-images.githubusercontent.com/20738/181207348-4b044214-700f-4231-8305-356d697795f2.png">

**Comment by AskAlexSharov** [comment]
Stop and update erigon version again

**Comment by krunkosaurus** [comment]
Will do and let it run for a few hours and report back. Thanks @AskAlexSharov

**Comment by krunkosaurus** [comment]
Updated to latest (620d65ef10318677d1739d3c849b7d0f8a8c4424) and still processing (truncating) at about 3 blocks per minute: 

```
INFO[07-27|23:53:47.099] Build info                               git_branch=devel git_tag=v2021.10.03-1547-g620d65ef1-dirty git_commit=620d65ef10318677d1739d3c849b7d0f8a8c4424
INFO[07-27|23:53:47.101] Starting Erigon on Ethereum mainnet...
INFO[07-27|23:53:47.106] Maximum peer count                       ETH=100 total=100
INFO[07-27|23:53:47.107] torrent verbosity                        level=2
INFO[07-27|23:53:49.474] [torrent] Public IP                      ip=172.221.8.25
INFO[07-27|23:53:49.477] Set global gas cap                       cap=50000000
INFO[07-27|23:53:49.550] Opening Database                         label=chaindata path=/Volumes/crucial/eth-mainnet/chaindata
INFO[07-27|23:54:38.181] Re-Opening DB in exclusive mode to apply migrations
INFO[07-27|23:55:40.770] Apply migration                          name=reset_blocks_3
WARN[07-27|23:55:41.925] NOTE: this migration will remove recent blocks (and senders) to fix several recent bugs. Your node will re-download last ~400K blocks, should not take very long
INFO[07-27|23:57:14.542] TruncateBlocks                           block=14947315
INFO[07-27|23:57:33.001] TruncateBlocks                           block=14947309
INFO[07-27|23:57:41.941] TruncateBlocks                           block=14947147
```

I have about 1TB of data downloaded. Let me know if its just best to blow it all away and redownload from scratch.

**Comment by AskAlexSharov** [comment]
then Erigon does think you need this db migration. 
please try branch `faster_truncate` - maybe it will help your speed

**Comment by krunkosaurus** [comment]
@AskAlexSharov I found I wasn't properly updating the bin file and still loading the version from Oct 2021. My bad. Closing this ticket now.
