### ISSUE TITLE
Build fails in stable branch

### ISSUE THREAD

**Issue by newearthmartin** [ledgerwatch/erigon#4845]
Erigon builds ok on the `devel` branch and, paradoxically, fails in the `stable` branch:

```
make erigon
Building Erigon
rm -f /root/src/erigon/build/bin/tg # Remove old binary to prevent confusion where users still use it because of the scripts
CGO_CFLAGS="-g -O2  -DMDBX_FORCE_ASSERTIONS=0 " go build -tags nosqlite -trimpath -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=dc86e022548d20506b6f6123e57a8b687a77c8ff -X github.com/ledgerwatch/erigon/params.GitBranch=stable -X github.com/ledgerwatch/erigon/params.GitTag=v2022.04.05-2-gdc86e0225" -o /root/src/erigon/build/bin/erigon ./cmd/erigon
# crawshaw.io/sqlite
In file included from /usr/include/string.h:535,
                 from /root/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/./c/sqlite3.c:14113,
                 from /root/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/static.go:19:
In function �memcpy�,
    inlined from �sqlite3Fts5IndexQuery� at /root/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/./c/sqlite3.c:220863:18:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10: warning: �__builtin_memcpy� specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
Done building.
```

It would be nice to have a branch that always has the latest stable release so that it can be pulled and built periodically to ensure to have the latest stable release in production.

**Comment by AskAlexSharov** [comment]
@newearthmartin `stable` branch -  it's branch with very old version of erigon - we don't merge any new features to this branch (no The Merge support there, no snapshots sync, etc...).
I recommend you just use releases: https://github.com/ledgerwatch/erigon/releases

**Comment by newearthmartin** [comment]
May I suggest that a branch is created that merges on release points? That's usually the meaning of a `stable` branch, a branch that you can checkout and build and you know it's going to work well. Otherwise for every release one has to personally go, find the name of the latest tag, manually check it out, and build it.

**Comment by newearthmartin** [comment]
In other words: can you revive the `stable` branch?

**Comment by AskAlexSharov** [comment]
sure. 
we will do it "soon" when current releases become more stable. then we will change label of current releases from "alpha" to "beta" and will use "stable" branch for releases.
