### ISSUE TITLE
Explicit `--snapshots` flag undoes `--prune`

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#4849]
#### System information

Erigon version: `git_branch=devel git_tag=v2021.10.03-1548-gaee4b5378-dirty git_commit=aee4b5378871feb5886072fd80b2fc87a820384f`

OS & Version: Linux

#### Issue

When running Erigon with `--prune` flags and an explicit `--snapshots true`, then `--prune` is negated:
`Effective                                prune_flags= snapshot_flags="--snapshots=true"`

When running Erigon without an explicit `--snapshots true` and relying on defaults, prune flags are honored:
`Effective                                prune_flags="--prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 --prune.r.before=4367322" snapshot_flags="--snapshots=true"`

**Comment by AskAlexSharov** [comment]
“true” is the keyword in shell. It breaks cli parsing. Do —snapshots=true

**Comment by yorickdowne** [comment]
Thanks for taking the time to answer this!
