### ISSUE TITLE
Add --config-file flag that points to configuration file

### ISSUE THREAD

**Issue by barnabasbusa** [ledgerwatch/erigon#4863]
# Rationale

Why should this feature exist?
Having all the configuration parameters stored in an easily editable format (such as YAML file) enables the users to quickly edit their flags without needing to reload the systemd daemon. 

What are the use-cases?
Instead of having 
```
erigon \
--chain sepolia \
--port 30302 \
--datadir /root/sepolia-erigon \
--http.port 8542 \
--engine.port 8552 
``` 
one could have `erigon --config-file /path/erigon-config.yaml`

Where the config file contains:
```yaml
chain: "sepolia"
port: 30302
datadir: "/root/sepolia-erigon"
http.port: 8542
engine.port: 8552
```
The more flags you have the more benefit you'll see.

# Implementation

Do you have ideas regarding the implementation of this feature?
Prysm (similarly written in go) handles the config-file flag as such:
https://github.com/prysmaticlabs/prysm/blob/cc1ea81d4a6032809cfc9d6a543d87f8392b4c74/cmd/flags.go#L266

Are you willing to implement this feature? 
No. Someone with more in depth knowledge of the project should implement this feature.

**Comment by enriavil1** [comment]
I'll implement it

**Comment by beejiujitsu** [comment]
+1 this would be useful for running Erigon in Kubernetes / configuring via configMap mounted to a file.

**Comment by enriavil1** [comment]
> +1 this would be useful for running Erigon in Kubernetes / configuring via configMap mounted to a file.

My PR will add support to YAML and TOML confit files.

**Comment by beejiujitsu** [comment]
> > +1 this would be useful for running Erigon in Kubernetes / configuring via configMap mounted to a file.
> 
> My PR will add support to YAML and TOML confit files.

Right. What I mean is, in kubernetes you can store text files as a Configmap object/manifest, then mount it in a pod as a file to use with the method you're implementing.

**Comment by icculp** [comment]
+1 this will be useful for integrations/automations. Preferred method for passing parameters for Node Launcher is to use config files. End users can't customize their nodes otherwise.

**Comment by barnabasbusa** [comment]
@icculp  the feature has been merged 2 weeks ago.
