### ISSUE TITLE
Feature request: fetch contract creation info by providing creator's address

### ISSUE THREAD

**Issue by fenghaojiang** [ledgerwatch/erigon#4869]
# Feature request: fetch contract creation info by providing creator's address

Why should this feature exist?  

It seems there is no way to find what contracts were created by a specific account except "trace_xxx" methods which costs you lots of time by making the request and traversing the blocks.

What are the use-cases? 

Directly return the contract address is really useful in some analytical scenarios.

**Comment by wmitsuda** [comment]
See: https://github.com/wmitsuda/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator

Is that what you need? if so, I can consider pushing it upstream under `erigon_getContractCreator` if core devs agree.

**Comment by tjayrush** [comment]
> See: https://github.com/wmitsuda/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator
> 
> Is that what you need? if so, I can consider pushing it upstream under `erigon_getContractCreator` if core devs agree.

I would use this if it was in the `erigon_` namespace. Currently we have an inefficient version of the same thing.

**Comment by fenghaojiang** [comment]
> See: https://github.com/wmitsuda/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator
> 
> Is that what you need? if so, I can consider pushing it upstream under `erigon_getContractCreator` if core devs agree.

Not exactly but similar. What I want is to get the contract address list by giving a creator account as input. But your implementation will be helpful in some way. Thank you.

**Comment by fenghaojiang** [comment]
> See: https://github.com/wmitsuda/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator
> 
> Is that what you need? if so, I can consider pushing it upstream under `erigon_getContractCreator` if core devs agree.

May I view your implementation? May be I can help to make PRs or contribute to erigon in Go.
