### ISSUE TITLE
eth_getBlock(pending) - to implement

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4876]
- add grpc api to txpool (if possible now)
- return pending block by json rpc
- add test
- (Can be done by another PR) support subscription to pending block

**Comment by mandrigin** [comment]
I think @dmitriyselivanov is on it already (see issue https://github.com/ledgerwatch/erigon/issues/2771#issuecomment-1187633742)

**Comment by leonardchinonso** [comment]
> I think @dmitriyselivanov is on it already (see issue [#2771 (comment)](https://github.com/ledgerwatch/erigon/issues/2771#issuecomment-1187633742))

I was about to pick this up. I'll just wait a bit then

**Comment by enriavil1** [comment]
We do have a subscribe pending block filter

**Comment by enriavil1** [comment]
I believe we can close this issue @AskAlexSharov
