### ISSUE TITLE
HTTP endpoint no service was provided, on devel branch

### ISSUE THREAD

**Issue by zzir** [ledgerwatch/erigon#4883]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash : 9ed2f8d98b7b0ec81e75eb38bac546a95a607f06

#### Actual behaviour

HTTP JSON-RPC endpint No service was provided

#### Backtrace

````bash
make
./build/bin/erigon --datadir=/data1/erigon-mainnet --chain=mainnet  --ws --http --http.addr="0.0.0.0" --http.port=8545 --http.trace  --http.corsdomain="*" --http.vhosts="*" --http.api="eth,debug,net,trace,web3,erigon,admin,txpool"
````

Port 8545 is not working. after switching the alpha branch, working normally.

**Comment by leonardchinonso** [comment]
Some fixes were made this morning, kindly pull code and check again. Unless you're fine with the alpha branch.

**Comment by enriavil1** [comment]
@nanevardanyan just fixed this issue with the latest commit in devel.
