### ISSUE TITLE
nodeDB.QuerySeeds failed err="mdbx_txn_begin: MDBX_PANIC during initial sync

### ISSUE THREAD

**Issue by aftermathdigital** [ledgerwatch/erigon#4891]
#### System information

Erigon version: erigon version 2022.99.99-dev-d866b119

OS & Version: Ubuntu server 22.04

Commit hash : d866b119236c9b93ca071abc0e45526cf82b58d7

32gb ram, ryzen 5600g

#### Expected behaviour

During initial sync, the node should synchronize without indicating hardware failure in the logs

#### Actual behaviour

The console is littered with intermittent 

```
WARN[08-01|17:10:17.667] nodeDB.QuerySeeds failed
err="mdbx_txn_begin: MDBX_PANIC: Likely because hardware failure
```

Under the guidance of the error message, I've run some memory stress tests which haven't returned any failures, though I was unable to run the smartmontools to check the disk. The disk is a new 4tb nvme ssd.

One thing I had noticed early on in the sync was that, for some reason, ubuntu server's installation had only used 100gb of my 4tb drive. At this point, the disk was not full, I don't remember its exact utilization. I've since grown the drive to 4tb, as can be seen:

```
/dev/mapper/ubuntu--vg-ubuntu--lv  3.6T  880G  2.6T  26% /
```

I'm not sure why this would cause this error to be thrown, and I don't want to re-start my sync if I can avoid it, but I'm happy to do so if you think it will help.

#### Steps to reproduce the behaviour

Followed the readme 'getting started' section to begin an initial node sync.

#### Backtrace

````
label: sentry, trace: [kv_mdbx.go:442 kv_mdbx.go:670 nodedb.go:414 nodedb.go:399 asm_amd64.s:1571]
````

It's certainly possible I've messed up, but the discord appears to be invite only, so I thought this would be the best place to post.

**Comment by AskAlexSharov** [comment]
1. Check if no space left on disk
2. If you have no problem with space on disk and still see error - follow recommendations in error message

**Comment by aftermathdigital** [comment]
Having re-started the sync it now appears to be working, I'm not sure what the issue was, I think I must have underestimated whether or not erigon had already failed to write to a full-disk before growing the volume.
