### ISSUE TITLE
FR: http.verbosity

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#4892]
# Rationale

With a lot of people running the http server on Erigon itself now, it would be nice if we could define the verbosity of the JSON-RPC requests specifically.

When running rpcdaemon remotely we could set `--verbosity=5` and get all the details that way, but running that on erigon is way too much data. `torrent.verbosity` and `database.verbosity` already exist, would be nice if `http.verbosity` existed as well.

**Comment by AskAlexSharov** [comment]
At least it must write to logs rpc requests on higher levels. (If inject logger everywhere is the big task).

**Comment by quickchase** [comment]
Still a feature request

**Comment by quickchase** [comment]
What a save
