### ISSUE TITLE
Erigon crashes "fatal error: concurrent map iteration and map write"

### ISSUE THREAD

**Issue by quick-pawiromitchel** [ledgerwatch/erigon#4893]
#### System information
Erigon version: `erigon version 2022.07.4-alpha`
OS & Version: Linux
Chain: BSC Testnet

#### Backtrace
Looking at the backtrace, it could be a filter causing this (we do have filter enabled)
```
runtime.goexit()
         runtime/asm_amd64.s:1571 +0x1 fp=0xc0067b0fe8 sp=0xc0067b0fe0 pc=0x48dc01
 created by [github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Logs](http://github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Logs)
         [github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_filters.go:235](http://github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_filters.go:235) +0x138
```
Full log here [erigonCrash.log](https://github.com/ledgerwatch/erigon/files/9237349/erigonCrash.log)

**Comment by quick-pawiromitchel** [comment]
I removed the filter methods, but I'm still seeing the same error

**Comment by McSim85** [comment]
I believe it's  BSC Testnet.

**Comment by quick-pawiromitchel** [comment]
@hexoscott thanks for the effort to try and fix the problem, I've updated all the nodes to `erigon version 2022.99.99-dev-35878b29`, but is still crashing.

**Comment by quick-pawiromitchel** [comment]
looks like the backtrace changes: 
[erigonCrash2.log](https://github.com/ledgerwatch/erigon/files/9260667/erigonCrash2.log)

**Comment by hexoscott** [comment]
Ah ok, no problem, I'll have another look this week.  Do you have some steps to re-produce the error?

**Comment by quick-pawiromitchel** [comment]
I'm unable to reproduce the issue, it looks like it appears randomly.

**Comment by mandrigin** [comment]
@hexoscott so the previous one was on subscribe and this one on unsubscribe :) I guess quickly subscribing and unsubscribing could be a way to reproduce it.

```
erigon[3728402]: github.com/ledgerwatch/erigon/turbo/rpchelper.(*Filters).UnsubscribeLogs(0xc0005b6380, 0xc003996dc8?)
erigon[3728402]: #011github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:433 +0x2c7 fp=0xc003996eb0 
```

**Comment by hexoscott** [comment]
OK, a new PR up for this one.  I replicated the issue within a unit test first which helped a lot with dummy address/topic criteria for the call to `SubscribeLogs`.  This one should be good to go once merged.

**Comment by quick-pawiromitchel** [comment]
hey @hexoscott and @mandrigin , I've built the latest of Erigon to incorporate this PR at ~9AM UTC https://github.com/ledgerwatch/erigon/pull/4971 and it's stable 🥳 

Going to monitor it closely, many thanks!

**Comment by mandrigin** [comment]
@quick-pawiromitchel awesome! I will close the issue but feel free to comment or reopen if it repeats
