### ISSUE TITLE
trace_transaction method is too slow

### ISSUE THREAD

**Issue by taiki94** [ledgerwatch/erigon#4913]
The trace module of the RPC endpoint is too slow, can it be fixed?

In the case of openethereum it was very fast: it took about 10 seconds for a trace_transaction request of about 200 transactions in one block to finish.

On the other hand, in the case of erigon, it takes about 2 minutes under the same conditions.
Please improve the performance.

**Comment by AskAlexSharov** [comment]
Erigon doesn't store traces in db. OE does. We don’t plan to change it in near future (low priority task).

**Comment by taiki94** [comment]
@AskAlexSharov 
Thank you for your response.
I am sorry to hear about the low priority, but I understand.
