### ISSUE TITLE
Opening port 8551

### ISSUE THREAD

**Issue by bert2002** [ledgerwatch/erigon#4915]
Hi,
I am trying to find a way to open the port 8551 with the docker setup, but it does not seems to work. The purpose is to connect `lighthouse` to `erigon.`
Right now I am setting `--engine.addr=0.0.0.0` for the rpcdaemon, but it does not work. 

Is there anything else needed with the docker-compose setup?

Thanks,
bert

**Comment by yperbasis** [comment]
There've been a couple of changes in our `devel` branch recently:
1. `rpcdaemon` does not expose the Engine API, only `erigon` itself does
2. `--engine.addr` was renamed to `--authrpc.addr` (and correspondingly has to be supplied to `erigon`, not `rpcdaemon`)

**Comment by panghalamit** [comment]
Is there a plan to cut a release from devel before the goerli merge for above changes?

**Comment by AskAlexSharov** [comment]
Every Thursday

**Comment by bert2002** [comment]
Then I will wait @AskAlexSharov :)

**Comment by bert2002** [comment]
Is there any plan to release this week? @AskAlexSharov

**Comment by AskAlexSharov** [comment]
yes, but no ETA

**Comment by bert2002** [comment]
It is working now with `--authrpc.addr`
