### ISSUE TITLE
Websocket newHeads subscription returns uncled block in case of reorg

### ISSUE THREAD

**Issue by jondoe1337** [ledgerwatch/erigon#4917]
#### System information

Erigon version: `2022.06.6-alpha-77240899`

OS & Version: Linux using Docker

#### Expected behaviour
This is the output of a GETH node, doing the same subscription:

```
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x32feeb5eccc0ab42a50f054b61caf2cd","result":{"number":"0xe8fe9b","timestamp":"0x62ea6d53","hash":"0x39da42e587a9d8c28a2a589cc1c01b1c960b031a0ac18e171f52a6020f664418"}}}
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x32feeb5eccc0ab42a50f054b61caf2cd","result":{"number":"0xe8fe9b","timestamp":"0x62ea6d52","hash":"0x384271f075b648ee7cbabca99e4a7c1296564e3a7205e85f7ac06a49b0d1aaef"}}}
```

#### Actual behaviour
In case of a reorg the following events are fired:
```
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xa69712a0a19f44206ad48eab378cf387","result":{"number":"0xe8fe9b","timestamp":"0x62ea6d53","hash":"0x39da42e587a9d8c28a2a589cc1c01b1c960b031a0ac18e171f52a6020f664418"}}}
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xa69712a0a19f44206ad48eab378cf387","result":{"number":"0xe8fe9b","timestamp":"0x62ea6d52","hash":"0x384271f075b648ee7cbabca99e4a7c1296564e3a7205e85f7ac06a49b0d1aaef"}}}
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xa69712a0a19f44206ad48eab378cf387","result":{"number":"0xe8fe9b","timestamp":"0x62ea6d53","hash":"0x39da42e587a9d8c28a2a589cc1c01b1c960b031a0ac18e171f52a6020f664418"}}}
```
Note: Output is truncated. The valid block is that one int the middle: https://etherscan.io/block/15269531 
#### Steps to reproduce the behaviour
Connect to a websocket, fire subscription:
```
{"id": 1, "method": "eth_subscribe", "params": ["newHeads"]}
```
Wait for a reorg

**Comment by enriavil1** [comment]
Can you try out the branch `notifying-cannonical-header` I added a check to make sure only canonical headers are announced through the subscription.

**Comment by jondoe1337** [comment]
Hey @enriavil1 I'm just trying to sync a goerli node locally but my container keeps crashing without errors after unpacking the snapshot. However I saw this in the log

``` 
git_branch=notifying-cannonical-header git_tag=v2021.10.03-1601-g7f73a56aa-dirty git_commit=7f73a56aabfc0571447479361551abfde281ea94
```

The git_tag seems to me pretty old? 🤔 Or am I missing something.

**Comment by enriavil1** [comment]
I honestly don't know why it is an old git tag, but just in case I just merged the devel changes onto the branch so it has to be updated. Thank you!

**Comment by jondoe1337** [comment]
@enriavil1 sorry for the late reply, took me some time to sync a goerli node however it looks good: 

```
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x9e17a7e172070380ffcc6ed1c8846534","result":{"number":"0x7095c4","hash":"0x86b5d3a60cefbe256d76b15ceeff98d2adcfade3da3892b8a60a1605e27ce7f5"}}}
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x9e17a7e172070380ffcc6ed1c8846534","result":{"number":"0x7095c4","hash":"0x4b18799be64d604231df1e7fa9faafa5cfdd528ad56a5c0b987c4db1d7fb5a30"}}}
```
(The latter seems so be the truth according to etherscan)

**Comment by jondoe1337** [comment]
Thanks for the fix @enriavil1 - good job! 👍
