### ISSUE TITLE
PrunceAncientBlocks reads br.snapshots.cfg.KeepBlocks incorrectly

### ISSUE THREAD

**Issue by mconover** [ledgerwatch/erigon#4922]
#### System information

Erigon version: `./erigon --version`
Checked on latest version of alpha branch

OS & Version: Windows/Linux/OSX

Commit hash : 68e35417fc 

#### Expected behaviour
Ancient blocks in snapshots are pruned if --snap.keepblock is false (default behavior) and aborts if it is set

#### Actual behaviour
This appears to do the the opposite:
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  969) func (br *BlockRetire) PruneAncientBlocks(tx kv.RwTx) error {
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  970) 	if !br.snapshots.cfg.KeepBlocks {
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  971) 		return nil
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  972) 	}
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  973) 	currentProgress, err := stages.GetStageProgress(tx, stages.Senders)
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  974) 	if err != nil {
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  975) 		return err
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  976) 	}
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  977) 	canDeleteTo := CanDeleteTo(currentProgress, br.snapshots)
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  978) 	if _, _, err := rawdb.DeleteAncientBlocks(tx, canDeleteTo, 100); err != nil {
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  979) 		return nil
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  980) 	}
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  981) 	if err := rawdb.PruneTable(tx, kv.Senders, canDeleteTo, context.Background(), 100); err != nil {
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  982) 		return err
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  983) 	}
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  984) 	return nil
68e35417fc (Alex Sharov                 2022-07-23 11:09:16 +0700  985) }

#### Steps to reproduce the behaviour
Launch erigon with old enough blocks in the snapshot database

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/4924
