### ISSUE TITLE
Slight difference in debug_traceBlockByHash output from Geth

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#4935]
#### System information

Erigon version: `2022.07.04-alpha` 

There's a slight difference in how Geth and Erigon return the data, erigon has an extra `result` key for some reason.

#### Expected behaviour
This is how Geth would return the result:

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": [
    {
      "result": {
        "type": "CALL",
```

#### Actual behaviour
This is how Erigon returns the result:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": [
    {
      "type": "CALL",
```

#### Steps to reproduce the behaviour
```
{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByHash",
  "params": [
    "<blockHash>",
    { "tracer": "callTracer" }
  ],
  "id": 0
}
```

Edit: I got them backwards

**Comment by jiezhang** [comment]
Can you also clarify how Erigon conveys the tracing error? 

For geth, the trace struct may [contain an error field](https://github.com/ethereum/go-ethereum/blob/f67e54c92fb7edcc44fa3739dfbc5d59790cc6f8/eth/tracers/api.go#L900), e.g.
```
{
  {"result": {"type": "CALL", ...}},
  {"result": {"type": "CALL", ...}},
  {"error": "execution timeout"}
}
```

Does Erigon return an empty struct in the event of any errors?
```
{
  {"type": "CALL", ...},
  {"type": "CALL", ...},
  {}
}
```

**Comment by vbouzon** [comment]
> Can you also clarify how Erigon conveys the tracing error?
> 
> For geth, the trace struct may [contain an error field](https://github.com/ethereum/go-ethereum/blob/f67e54c92fb7edcc44fa3739dfbc5d59790cc6f8/eth/tracers/api.go#L900), e.g.
> 
> ```
> {
>   {"result": {"type": "CALL", ...}},
>   {"result": {"type": "CALL", ...}},
>   {"error": "execution timeout"}
> }
> ```
> 
> Does Erigon return an empty struct in the event of any errors?
> 
> ```
> {
>   {"type": "CALL", ...},
>   {"type": "CALL", ...},
>   {}
> }
> ```

@jiezhang 

In case of error it looks like 
```
{
  {"type": "CALL", ...},
  ,
  {"type": "CALL", ...},
  
}
```
There is not even a struct, only an empty item. You can try it with reducing the execution timeout (e.g 20ms).

**Comment by jiezhang** [comment]
@vbouzon An "empty" item is not a valid JSON. Can you change it to `{}` or `null`?

See https://go.dev/play/p/lJ8KyptxYp5

**Comment by vbouzon** [comment]
I'm not maintainer of this project, It was comment as I had the same question two days ago.

For your information, an undefined item in array seems valid even it looks like bug: 
https://playcode.io/944108/

**Comment by jaleel-salhi-cb** [comment]
Errors don't result in valid JSON with the erigon client, for example:

`{"result":,"error":{"code":-32000,"message":"execution timeout"}}`

@vbouzon your example is valid in golang, but this is not valid for the json spec. i.e. adding the above snippet into any online JSON validator will yield "invalid" result

If a maintainer of the project sees this, I second Jie's suggestion:

> Can you change it to {} or null?

**Comment by jiezhang** [comment]
I don't think that's a valid JSON in any programming language:
- JS: https://playcode.io/944128
- Golang: https://go.dev/play/p/lJ8KyptxYp5

**Comment by AskAlexSharov** [comment]
It’s invalid json because trace_ methods doing json streaming - means manual json assembling. Need to fix.

**Comment by jaleel-salhi-cb** [comment]
```
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByHash",
    "params": ["0xc3ecff728ede47a56b51031fd5cd1e5aa7701aa0aeaee69b0f6eda5b36f7f7b8", {"tracer":"callTracer"}],
    "id": 0
}
```

Is an example input that returns invalid JSON in a format similarly described in vbouzon's comment.

**Comment by jaleel-salhi-cb** [comment]
Commenting to keep this alive.
