### ISSUE TITLE
Show logPrefix when commit batch (so user can understand on which stage he is now)

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4941]
now it shows something like: 
![unknown](https://user-images.githubusercontent.com/46885206/183002372-dba8877b-b8f7-40b6-94f8-990cb0d2d692.png)

**Comment by ahmedyounis** [comment]
Thanks @AskAlexSharov for creating this issue on improving the logs! It will be very helpful... im  also reviewing the geth logs to see if we can improve on Erigon's.

**Comment by enriavil1** [comment]
On what chain did that happen? I want to try and recreate it.
