### ISSUE TITLE
Polygon Heimdall Sync Issue

### ISSUE THREAD

**Issue by plvnts** [ledgerwatch/erigon#4942]
On most recent commit/devel branch:
Any idea how to fix?

<img width="1049" alt="Screen Shot 2022-08-05 at 9 35 31 AM" src="https://user-images.githubusercontent.com/51814841/183008653-81375c42-39b6-4f92-bd54-c23a91aaebb4.png">

**Comment by AskAlexSharov** [comment]
if you're not running heimdall rest-server locally add this: --bor.heimdall https://heimdall.api.matic.network
