### ISSUE TITLE
feature request: add field`timestamp` to `eth_getLogs` response 

### ISSUE THREAD

**Issue by fenghaojiang** [ledgerwatch/erigon#4951]
# feature request: add field`timestamp` to `eth_getLogs` response 

Why should this feature exist?

every time I make an `eth_getLogs` request and the response has no field of time. I have to make other requests such as `eth_getBlock` to fetch field `timestamp` information.

# Implementation

Are you willing to implement this feature?

Yes, I will be very willing to help if I can.  

#4950 

Actually, I modify the request, I wonder if this pull request is good enough. Plz have a check.

**Comment by tjayrush** [comment]
A 100 times "yes" on adding `timestamp` from me.

We (TrueBlocks) would very much want this.

This would cut down the number of RPC calls we make during the creation of the Unchained Index by 1/2.

Note, however, that this creates an incompatibility between Erigon and other nodes. There should be a strong push to get other nodes to add `timestamp` to `eth_getLogs` through an EIP. Barring that, this should probably be in the `erigon_` namespace.

**Comment by fenghaojiang** [comment]
alreay merged. I will close this issue.

**Comment by fenghaojiang** [comment]
> A 100 times "yes" on adding `timestamp` from me.
> 
> We (TrueBlocks) would very much want this.
> 
> This would cut down the number of RPC calls we make during the creation of the Unchained Index by 1/2.
> 
> Note, however, that this creates an incompatibility between Erigon and other nodes. There should be a strong push to get other nodes to add `timestamp` to `eth_getLogs` through an EIP. Barring that, this should probably be in the `erigon_` namespace.

I would like to help. But can you explain what's an EIP? I don't quite get it.

**Comment by tjayrush** [comment]
It's how Ethereum improves itself. EIP == Ethereum Improvement Proposal. 

It's a huge amount of work, maybe too huge, but here's the repo: https://github.com/ethereum/EIPs

**Comment by wmitsuda** [comment]
I commented on discord, will add my considerations here too:

"I just saw it got merged... please don't do that, I totally agree with all previous comments here, I think it is ok to add a new erigon_something method, but please let's not change the eth_ standard methods by ourselves, no matter current standards are good or bad.
changing existing eth_ methods will lead to confusion, people can see this new field added to erigon response, assume it is a standard, and complain when they see, e.g., geth does not return it."

**Comment by fenghaojiang** [comment]
> It's how Ethereum improves itself. EIP == Ethereum Improvement Proposal.
> 
> It's a huge amount of work, maybe too huge, but here's the repo: https://github.com/ethereum/EIPs

Ok, thank you. I will undo my changes and add it into api with `erigon_` prefix.

**Comment by fenghaojiang** [comment]
> I commented on discord, will add my considerations here too:
> 
> "I just saw it got merged... please don't do that, I totally agree with all previous comments here, I think it is ok to add a new erigon_something method, but please let's not change the eth_ standard methods by ourselves, no matter current standards are good or bad. changing existing eth_ methods will lead to confusion, people can see this new field added to erigon response, assume it is a standard, and complain when they see, e.g., geth does not return it."

really appreciated for you suggestion. I will undo my changes.

**Comment by fenghaojiang** [comment]
Here are my changes. Plz check The PR #4964

**Comment by fenghaojiang** [comment]
I undo my change and add it to `erigon_getLogs` in PR #4968. Have a check plz.

**Comment by tjayrush** [comment]
If you're following this issue (even though it's closed), perhaps you'll add your voice to support this discussion: https://ethereum-magicians.org/t/proposal-for-adding-blocktimestamp-to-logs-object-returned-by-eth-getlogs-and-related-requests/11183.

`eth_getLogs` should have `timestamp`. That's obvious to everyone. Unfortunately we have to do it through an EIP, which means the more voices speaking out the better. Add your voice.

**Comment by fenghaojiang** [comment]
> If you're following this issue (even though it's closed), perhaps you'll add your voice to support this discussion: https://ethereum-magicians.org/t/proposal-for-adding-blocktimestamp-to-logs-object-returned-by-eth-getlogs-and-related-requests/11183.
> 
> `eth_getLogs` should have `timestamp`. That's obvious to everyone. Unfortunately we have to do it through an EIP, which means the more voices speaking out the better. Add your voice.

Sure. Glad to help.

**Comment by eshaan7** [comment]
As I've noted [here](https://github.com/ethereum/execution-apis/issues/295#issuecomment-2467605743), this applies to logs returned by `eth_getTransactionReceipt` and `eth_getBlockReceipts` methods as well. [Reth](https://github.com/paradigmxyz/reth/pull/7606) already implemented this.

I think this issue should be re-opened.

**Comment by bmoyroud** [comment]
Geth now supports `blockTimestamp` in logs.

It was added to logs in [Geth v1.16.0](https://github.com/ethereum/go-ethereum/releases/tag/v1.16.0) (Terran Rivets).
It is now hex encoded as of [v1.16.1](https://github.com/ethereum/go-ethereum/releases/tag/v1.16.1).
