### ISSUE TITLE
RPC daemon not starting with ./build/bin/rpcdaemon command

### ISSUE THREAD

**Issue by gavbennett** [ledgerwatch/erigon#4954]
OS: Windows 11

From what I've read, to start the RPC daemon you must first have it made then:
`./build/bin/rpcdaemon --datadir=<your_data_dir> --txpool.api.addr=localhost:9090 --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool`

When I execute that code in my terminal all that happens is the pop-up asking how I want to open this type of file. My guess is because, in the "bin" folder, the rpcdaemon file type is categorized as "File" whereas all the others (such as erigon) are "Application".

Not sure if this is an issue with the code base or if I'm missing something obvious but any help would be appreciated.
![RPC Daemon File](https://user-images.githubusercontent.com/94311667/183300561-16c751a8-0d4e-43f5-9a3a-9123bbb814c9.png)

![RPC Daemon Output](https://user-images.githubusercontent.com/94311667/183300750-be862758-0b9b-42cc-bcae-3c17baf32d7a.png)

**Comment by leonardchinonso** [comment]
- How did you get your executable on windows? Did you use `wmake`?
- Try `.\wmake.ps1 rpcdaemon` and check if it produces a `.exe` type file
- If it still does not work, have you considered using WSL or docker?

I'm tagging @AndreaLanfranchi because he has more knowledge on using windows

**Comment by gavbennett** [comment]
haha yep, the `.\wmake.ps1` was the issue.

Thank you!
