### ISSUE TITLE
Extremely slow eth_estimateGas

### ISSUE THREAD

**Issue by plvnts** [ledgerwatch/erigon#4956]
Hi, we're experiencing extremely slow eth_estimateGas calls on a high-end server. 

```
time curl -s -H "Content-Type: application/json" -X POST http://localhost:8545 --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to": "0x32be343b94f860124dc4fee278fdcbd38c102d88", "from": "0x32be343b94f860124dc4fee278fdcbd38c102d88"}],"id":1}'
```

```
real	0m1.216s
```

1.2s seems really slow for a local node. I was under the impression it should be orders of magnitudes faster. Any ideas how to increase the speed?

**Comment by AskAlexSharov** [comment]
How do you run erigon? How do you run rpcdaemon?

**Comment by AskAlexSharov** [comment]
I mean cli flags

**Comment by plvnts** [comment]
erigon/build/bin/erigon --datadir=... --chain=mainnet --ws
