### ISSUE TITLE
callTracer crashing on Ethereum Mainnet block 4_890_213

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#4960]
#### System information
Erigon version: `7a2e7e8c062ca1efa7db97b8aec71a674d9959ce`

#### Description
When calling `debug_traceBlockByNumber` on block `0x4A9E65` with `callTracer` - there is a `method handler crash`

With JSON-RPC streaming, malformed JSON is returned because of this. But the root cause is the method handler crash with `callTracer`

#### Expected behaviour
Don't crash?

#### Actual behaviour
[bad response.txt](https://github.com/ledgerwatch/erigon/files/9282526/bad.response.txt)

#### Steps to reproduce the behaviour
```json
{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "params": ["0x4A9E65", { "tracer": "callTracer", "timeout": "240s" }],
  "id": 1
}
```

**Comment by mandrigin** [comment]
is there anything in the logs? stack trace or something like that?

**Comment by quickchase** [comment]
Actually, yes.


```
[EROR] [08-08|16:58:39.350] RPC method debug_traceBlockByNumber crashed: interface conversion: interface {} is float64, not int64

[service.go:217 panic.go:838 runtime.go:2161 panic.go:838 vm.go:512 panic.go:838 iface.go:262 jsvm.go:80 tracer.go:135 jsvm.go:62 value.go:556 value.go:339 runtime.go:1756 vm.go:2658 vm.go:2630 vm.go:402 func.go:172 func.go:180 func.go:140 runtime.go:2166 vm.go:518 runtime.go:2165 jsvm.go:199 tracer.go:552 tracer.go:636 interpreter.go:313 evm.go:75 evm.go:274 state_transition.go:416 state_transition.go:230 tracing.go:144 tracing.go:103 tracing.go:31 value.go:556 value.go:339 service.go:222 handler.go:480 handler.go:413 handler.go:361 handler.go:192 handler.go:285 asm_amd64.s:1571]
```

**Comment by quickchase** [comment]
Bump

**Comment by quickchase** [comment]
So there are like 34,000 blocks that cannot be traced and have this method handler crashed after a `null` / invalid JSON

https://gist.github.com/maurodelazeri/692d04d143fc15ff06549d4c4512ed31

**Comment by alangshur** [comment]
@quickchase any resolution to this? I'm noticing the same thing in that exact same block. In fact, looks like the culprit is the transaction `0x1abefc71081a2c0115b1cc9d2a3c21bcd0cbc0355007d649898ad4d08d361c7e` if you do `debug_traceTransaction`.

**Comment by quickchase** [comment]
May be related to #5308

**Comment by AlexeyAkhunov** [comment]
I checked that is it not crashing anymore on `devel` after the implementation of native tracers
