### ISSUE TITLE
runtime error: invalid memory address when starting rpcdaemon (dev chain) 

### ISSUE THREAD

**Issue by Serhy** [ledgerwatch/erigon#4974]
#### System information

Erigon version: `erigon version 2022.99.99-dev-0d08bd09`

Commit hash : 0d08bd096fb78a8ba4a1788583eb011ac488c1fc

#### Expected behaviour
No internal desc runtime errors. I can send eth_sendRawTransaction fine.
```
$ sudo ./rpcdaemon --datadir=dev --private.api.addr=localhost:9091 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity --http.port 8545
INFO[08-08|12:54:14.244] DB schemas compatible                    reader=6.0.0 database=6.0.0
INFO[08-08|12:54:14.285] [Snapshots] see new                      blocks=0
INFO[08-08|12:54:14.285] rpc filters: subscribing to Erigon events 
TraceRequests = false
INFO[08-08|12:54:14.288] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=false grpc=false
INFO[08-08|12:54:14.293] interfaces compatible                    remote_db= client=6.0.0 server=6.0.0
INFO[08-08|12:54:14.293] interfaces compatible                    remote_service=eth_backend client=3.1.0 server=3.1.0
INFO[08-08|12:54:14.293] interfaces compatible                    remote_service=mining client=1.0.0 server=1.0.0
INFO[08-08|12:54:14.294] interfaces compatible                    remote_service=tx_pool client=1.0.0 server=1.0.0
```

#### Actual behaviour
```
$ ./rpcdaemon --datadir=dev --private.api.addr=localhost:9091 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity --http.port 8545
INFO[08-09|14:14:14.252] DB schemas compatible                    reader=6.0.0 database=6.0.0
INFO[08-09|14:14:14.275] rpc filters: subscribing to Erigon events 
INFO[08-09|14:14:14.278] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=false grpc=false
WARN[08-09|14:14:55.321] [Snapshots] reopen                       err="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference"
INFO[08-09|14:14:55.322] interfaces compatible                    remote_db= client=6.0.0 server=6.0.0
WARN[08-09|14:14:55.322] [Snapshots] reopen                       err="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference"
INFO[08-09|14:14:55.322] interfaces compatible                    remote_service=eth_backend client=3.1.0 server=3.1.0
INFO[08-09|14:14:55.322] interfaces compatible                    remote_service=mining client=1.0.0 server=1.0.0
INFO[08-09|14:14:55.323] interfaces compatible                    remote_service=tx_pool client=1.0.0 server=1.0.0
```

#### Steps to reproduce the behaviour
Issue originally noticed when sending eth_sendRawTransaction on dev chain (see response below), so expected result would be also the transaction succeeded:
1) Pull latest `devel` changes
2) Build erigon and rpcdaemon ( `make erigon && make rpcdaemon` )  
3) Start erigon and start rpcdaemon: `./erigon --datadir=dev --chain dev --private.api.addr=localhost:9091 --mine --http=false --http.port=8545`
`./rpcdaemon --datadir=dev --private.api.addr=localhost:9091 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity --http.port 8545`
(Actual result of stacktrace of RPCdaemon visible above)
4) Try to send transaction: 
```
curl --location --request POST 'localhost:8545' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":2.0,"method":"eth_sendRawTransaction", "params": ["0xf86c80843b9aca0082520894a94f5374fce5edbc8e2a8697c15331677e6ebf0b87470de4df82000080820a96a054533dba7ea5edabe2c875baf70bef36352a82786e5d826781265a426dea78cea04348961fa435012b76a14dbf6228c13a2475d3243dd3fcc8c373f4defa6b8ad2"],
     "id": 12}'
```
 
**Actual result:**
```

{
    "jsonrpc": "2.0",
    "id": 12,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

**Comment by nanevardanyan** [comment]
This issue was fixed by the following PR: https://github.com/ledgerwatch/erigon/pull/5006
Feel free to verify and close the issue @Serhy.

**Comment by enriavil1** [comment]
> This issue was fixed by the following PR: https://github.com/ledgerwatch/erigon/pull/5006
> 
> Please feel free to verify and close the issue @Serhy. 

Sorry @nanevardanyan but your PR solved a different issue. Your PR solves the issue of a nil ptr inside of `eth_sendRawTransaction`. This error is from `reopen()` which happens inside ends up happening because of an incorrect check inside of erigon-lib. Thank you very much for your PR as you did solve an issue. Tomorrow I'll open a PR with the erigon-lib fix for this issue.

**Comment by nanevardanyan** [comment]
Oh okay, I just verified for `eth_sendRawTransaction` to make sure it does not crash with nil pointer anymore. 
Thanks!
