### ISSUE TITLE
Method handler crashed when using getPastLogs API

### ISSUE THREAD

**Issue by JosephK95** [ledgerwatch/erigon#4982]
Hi all,

When we execute `getPastLogs` API, it seems that Erigon crashes if the `toBlock` parameter receives a value larger than MaxUint32.

#### System information
Erigon version: 2022.07.4-alpha-d88fc824
OS & Version: Ubuntu 20.04.4 LTS
Node.js / web3.js versions: v16.15.0 / v1.7.3

#### Expected behaviour
Erigon should return an array of log objects or perform error handling.

#### Actual behaviour
<pre>
...
[EROR] [08-10|13:13:36.167] RPC method eth_getLogs crashed: rangeEnd-1 > MaxUint32
[service.go:217 panic.go:838 roaring.go:1489 eth_receipts.go:121 value.go:556 value.go:339 service.go:222 handler.go:507 handler.go:412 handler.go:360 handler.go:191 handler.go:284 asm_amd64.s:1571]
[WARN] [08-10|13:13:36.167] Served                                   conn=127.0.0.1:39210 method=eth_getLogs reqid=2 t=116.468Âµs err="method handler crashed"
...
</pre>

#### Steps to reproduce the behaviour
1. Download the following file and untar it:
[crash.tar.gz](https://github.com/ledgerwatch/erigon/files/9296728/crash.tar.gz)
2. Untar the data-erigon.tar.gz file in the 'crash' directory.
3. Execute Erigon binary with the following flags:
`erigon --datadir ./crash/data-erigon --http.port 8547 --http --http.api eth --networkid 15 --nodiscover`
4. Execute the test case file: `node crash/test1.js`

**Comment by fenghaojiang** [comment]
The method in roaring `AddRange` The function uses 64-bit parameters even though a Bitmap stores 32-bit values because it is allowed and meaningful to use [0,uint64(0x100000000)) as a range. 

I will fix it. Thx for your report.

**Comment by fenghaojiang** [comment]
I fixed the issue in PR #4968.

**Comment by revittm** [comment]
Closing as fixed in #4968
