### ISSUE TITLE
stop syncing goerli testnet at block 7382822 

### ISSUE THREAD

**Issue by rlaace423** [ledgerwatch/erigon#4999]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).

I'm using erigon node for my comany use (Goerli testnet).

It stop about 2 hours ago, so I restarted it but had no luck.
Then I updated erigon to latest build, (2022-08-01-alpha) but there's no changes.

Current log is below.
![image](https://user-images.githubusercontent.com/5516480/184059549-d5e13084-11fd-4a4b-9c03-15beb28d0d93.png)

Also I found that there's POS upgrade at goerli. Is there something that I have to do?

**Comment by splix** [comment]
Can confirm the same issue on two different servers. 

Tried `integration stage_headers --unwind` and `integration state_stages --unwind` but it doesn't help. 

On star it puts the "POS ACTIVATED" ASCII Banner but seems to stuck in `[1/16 Headers] Waiting for Beacon Chain...` as nothing moves forward after that.

**Comment by mandrigin** [comment]
@splix @rlaace423 whats your beacon node setup?

**Comment by rlaace423** [comment]
> @splix @rlaace423 whats your beacon node setup?

I started like below
`erigon --datadir=./data --chain=goerli --http.addr=0.0.0.0 --http.port=8545 --http.corsdomain=* --ws --http.vhosts=* --http.api=eth,net,trace,web3,erigon`

It worked well from 24th June.

**Comment by rlaace423** [comment]
Sorry for my ignorance.

I didn't know about beacon-chain,

I works like a charm with prysm :)

**Comment by darklow** [comment]
> Sorry for my ignorance.
> 
> I didn't know about beacon-chain,
> 
> I works like a charm with prysm :)

Would you mind sharing what changed did you made? I'm having same problem. Thanks

**Comment by splix** [comment]
> @splix @rlaace423 whats your beacon node setup?

I was under impression that Erigon contains everything to run on Goerli. Because `erigon -h | grep beacon` gives nothing and I just expected it would continue to work as it was configured before. I see now that it need a different setup to continue.

**Comment by rlaace423** [comment]
> > Sorry for my ignorance.
> > I didn't know about beacon-chain,
> > I works like a charm with prysm :)
> 
> Would you mind sharing what changed did you made? I'm having same problem. Thanks

@darklow @splix 
I've installed prysm (one of beacon chain client) and connected it with erigon.
I used default `--authrpc.xxx` options, and used already generated jwt.hex file which generated by erigon and used for communicating with beacon chain client.

For syncing prysm fast, I've also used infura.io and tried [this document](https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync). It works well!

**Comment by mandrigin** [comment]
> > @splix @rlaace423 whats your beacon node setup?
> 
> I was under impression that Erigon contains everything to run on Goerli. Because `erigon -h | grep beacon` gives nothing and I just expected it would continue to work as it was configured before. I see now that it need a different setup to continue.

No, at the moment after “the merge” you need to run two nodes, a consensus layer (beacon node) and execution layer (erigon). And that’s the same for all other ELs too: geth, Nethermind, besu. So make sure your setup is ready to mainnet fork.
