### ISSUE TITLE
previous README.md show a wrong block number (11184524) for the `--prune.r.before` parameter instead of `11052984`

### ISSUE THREAD

**Issue by jeremie-H** [ledgerwatch/erigon#5026]
#### System information

Erigon version: `erigon version 2022.08.1-alpha-7dabdc32`

OS & Version: `Debian GNU/Linux 11 (bullseye)`

Commit hash : `7dabdc32`

#### Expected behaviour
Erigon, as an EL layer to be used with a CL has a [paragraph](https://github.com/ledgerwatch/erigon#beacon-chain-consensus-layer) in the readme page.
This § explain how to run erigon in pruned mode, and working with a beacon chain (without specifying the network)
Currently, the recommandation is the following parameters :
- `--prune=htc --prune.r.before=<old block number>`

and a pruned instance of erigon with rights parameters should be used as an EL with a CL.

#### Actual behaviour

but for a long time, in the README.md the recommandation was the following parameters:
- `--prune=htc --prune.r.before=11184524`

We can see the change in this commit
https://github.com/ledgerwatch/erigon/commit/7199dcf7a2826da5dd9d30bc9e24860edb4de2eb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L181.

From my mind, it's ok to make generic this kind of parameter, but the issue is that **the previous block number noticed 11184524 was wrong** ❌   !

---

On the mainnet, the deposit contract is created on the block **11052984** ✔️ [etherscan link](https://etherscan.io/tx/0xe75fb554e433e03763a1560646ee22dcb74e5274b34c5ad644e7c0f619a7e1d0)

So i dont know why the block number was **11184524** ❌ before in the documentation, but if erigon prune receipts between the real contract creation block **11052984** <  **pruned receipts** < **11184524**. It could have some strange behaviours I suppose because there are missing receipts from the contract creation.

#### Question :question:
Should we resync all started instances with the wrong block number ?

#### Communication 🗣️
_I think we should communicate to all stakers who had started in prune mode, with this wrong block number, if a resync is needed._

#### Steps to reproduce the behaviour
start an instance with  `--prune=htc --prune.r.before=11184524`

**Comment by jeremie-H** [comment]
after a little search, the number 11184524 was the first transaction on the deposit contract : 
![image](https://user-images.githubusercontent.com/11060749/184379203-6bea5133-be63-47cd-a4d0-13d5cf8bf970.png)

**Comment by birdmeister** [comment]
What could be a possible outcome of pruning before '11184524' instead of '11052984'? A full resync is painful at this point in time as we are close to the merge.

**Comment by jeremie-H** [comment]
I agree with @birdmeister , i see that in the code, the block number used to prune is 11052984, so everybody who follow the previous recommandations could be in trouble.
I don't know if pruning before 11184524 will be ok.

**Comment by enriavil1** [comment]
As long as the receipt of the deposit contract was not pruned then you don't have any problem.

**Comment by jeremie-H** [comment]
well, that exactly the origin of my issue here...
with the previous recommandation of pruning on 11184524, the receipt of the deposit contract **was pruned**

**Comment by adamgall** [comment]
Surprised this isn't getting more attention, with being so close to the merge. 

I'm in the same boat -- just finished syncing with `prune.r.before=11184524`, and upon restarting erigon the logs say

```
the specified prune.before.r block number is higher than the deposit contract contract block number highest block number=11052984
```

I guess I'll kick off another resync...

**Comment by enriavil1** [comment]
After PR #5065 if you specify the `prune=r` erigon will by default prune all the receipts before the deposit contract.

**Comment by adamgall** [comment]
> After PR https://github.com/ledgerwatch/erigon/pull/5065 if you specify the prune=r erigon will by default prune all the receipts before the deposit contract.

Awesome, thanks for the response! Will it also _not_ prune receipts _after_ the deposit contract creation block?

**Comment by enriavil1** [comment]
> > After PR https://github.com/ledgerwatch/erigon/pull/5065 if you specify the prune=r erigon will by default prune all the receipts before the deposit contract.
> 
> 
> 
> Awesome, thanks for the response! Will it also _not_ prune receipts _after_ the deposit contract creation block?

No it should not but we might change it in the future so we can prune all the receipts except the the deposit contract.

**Comment by jeremie-H** [comment]
> After PR #5065 if you specify the `prune=r` erigon will by default prune all the receipts before the deposit contract.

from my point of view, the question was "what about erigon instances started with the previous bad recommandation(prune.r.before=111844524)?
Will there re-download of the missing receipts starting from deposit contract until the first transaction on it ?
perhaps i'm not understanding well, but i still miss something (a wide communication on it perhaps if resync is needed ?)

but hey, i 've switch to geth to be sure, there is too much ambiguity from my PoV

**Comment by systemfreund** [comment]
I'd be interested to know aswell, because I'm running an erigon instance with the previous recommended options and wondering if it will break eventually or not

**Comment by enriavil1** [comment]
sadly resync will be necessary or at least the reset of stage_exec but in that case it is the same as a resync

**Comment by cleot** [comment]
> I'd be interested to know aswell, because I'm running an erigon instance with the previous recommended options and wondering if it will break eventually or not

still working after the bellatrix upgrade?

**Comment by banteg** [comment]
i just checked and this seems a non-issue.
there were no deposits before 11,184,524.
the first deposit was at block 11,185,311. 

<img width="421" alt="Screen Shot 2022-09-06 at 19 45 37" src="https://user-images.githubusercontent.com/4562643/188678908-73a49f84-eba2-41af-9443-6f3b594c5f98.png">
