### ISSUE TITLE
Erigon must self-heal from “Waiting for torrents metadata: 121/122“ state

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5042]
- If add to snapshots folder bad .torrent file (no peers), or if start erigon with one https://github.com/ledgerwatch/erigon-snapshot/blob/main/goerli.toml#L3 , then change some hash there and start erigon with new goerli.toml file
- Erigon now stuck in this state. But likely Erigon can detect such problem and self-heal. By force verify or by check that all files are available in goerli.toml, or somehow else

**Comment by enriavil1** [comment]
Arent we already verifying after we start erigon?

**Comment by AskAlexSharov** [comment]
> Arent we already verifying after we start erigon?

yes, but this issue is not about "some snapshot was broken", this issue is about "by some reason we have wrong/old/buggy  .torrent file in snapshots dir which nobody in network seed". 

There are 2 type of .torrent files:
- some are hardcoded in https://github.com/ledgerwatch/erigon-snapshot
- and also erigon producing new snapshots (during normal work) and seed them (and create for them .torrent files in snapshots dir)

it means having .torrent files which are not in whitelist - is generally ok if we produced them. 
but if user added manually .torrent file there(it's valid use-case - when user restore snapshots dir from backup or copy it to another server), or if old version of erigon created wrong .torrent file - then erigon will try to download them and never complete because nobody seed them.

**Comment by AskAlexSharov** [comment]
But! 

Now I realized next logic is correct:
- Erigon must try to download only whitelisted .torrent files
- Erigon can seed .torrent files if they are not whitelisted

and `Waiting for torrents metadata: 121/122` means Erigon trying to download not-whitelisted .torrent file, which is wrong.

**Comment by enriavil1** [comment]
Meaning Erigon should never be able to finish downloading since they are not whitelisted torrent files. What if someone wants to use their own snapshots?

**Comment by AskAlexSharov** [comment]
To summarise: 
- Erigon must not try to download files if they are not whitelisted in https://github.com/ledgerwatch/erigon-snapshot
- even if user manually created .torrent file in snapshots dir

**Comment by AskAlexSharov** [comment]
`What if someone wants to use their own snapshots?` - just place custom snapshots to snapshots dir. 1. use and seed non-whitelisted snapshots is fine 2. download non-whitelisted snapshots not fine.

**Comment by enriavil1** [comment]
Well we still have the issue that sometimes downloader gets stuck at "Waiting for torrents metadata: 122/122" so maybe we should change it to that.

**Comment by AskAlexSharov** [comment]
It’s another story. Never seen. But yes, need fix it somehow - if it happening

**Comment by enriavil1** [comment]
I believe it still happening because we have not changed anything, but it hasn't happened to me for a while

**Comment by AskAlexSharov** [comment]
@enriavil1 maybe this is the reason: https://github.com/ledgerwatch/erigon/issues/4979
