### ISSUE TITLE
Failing to build native erigon on windows

### ISSUE THREAD

**Issue by Sean4572435243** [ledgerwatch/erigon#5046]
Following the below instructions from https://github.com/ledgerwatch/erigon#windows:

> Build executable binaries natively for Windows using provided wmake.ps1 PowerShell script. Usage syntax is the same as make command so you have to run .\wmake.ps1 [-target] <targetname>. Example: .\wmake.ps1 erigon builds erigon executable. All binaries are placed in .\build\bin\ subfolder. There are some requirements for a successful native build on windows :
> 
> [Git](https://git-scm.com/downloads) for Windows must be installed. If you're cloning this repository is very likely you already have it
> [GO Programming Language](https://golang.org/dl/) must be installed. Minimum required version is 1.18
> GNU CC Compiler at least version 10 (is highly suggested that you install chocolatey package manager - see following point)
> If you need to build MDBX tools (i.e. .\wmake.ps1 db-tools) then [Chocolatey package manager](https://chocolatey.org/) for Windows must be installed. By Chocolatey you need to install the following components : cmake, make, mingw by choco install cmake make mingw.

This is my failed outcome:

> PS C:\users\Blockchain\erigon> .\wmake.ps1 erigon
> 
>  ------------------------------------------------------------------------------
>   Erigon's wmake.ps1 : Selected target(s) erigon
>  ------------------------------------------------------------------------------
> 
>  Found GIT version 2.37.2
>  Found GO version 1.19
> 
>  Erigon Branch : devel
>  Erigon Tag    : v2021.10.03-1670-g52987a56f
>  Erigon Commit : 52987a56f30f3e784e848fae2445fd03af903f80
> 
> 
>  Building erigon
> package noboltdb is not in GOROOT (C:\Program Files\Go\src\noboltdb)
> malformed import path "-buildvcs=false": leading dash
> malformed import path "-v": leading dash
> malformed import path "-ldflags": leading dash
> malformed import path "-X github.com/ledgerwatch/erigon/params.GitCommit=52987a56f30f3e784e848fae2445fd03af903f80 -X git
> hub.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/erigon/params.GitTag=v2021.10.03-1670-g52987
> a56f": leading dash
> malformed import path "-o": leading dash
> stat C:\users\Blockchain\erigon\build\bin\erigon.exe: directory not found
>  ERROR : Could not build target erigon
> PS C:\users\Blockchain\erigon>
> 

I have no idea how to fix this.  Any help would be greatly appreciated.

The generated build command that's failing is this:

go build -trimpath -tags nosqlite,noboltdb -buildvcs=false -v -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=52987a56f30f3e784e848fae2445fd03af903f80 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/erigon/params.GitTag=v2021.10.03-1670-g52987a56f" -o "C:\users\Blockchain\erigon\build\bin\erigon.exe" ./cmd/erigon;$?

**Comment by AskAlexSharov** [comment]
"directory not found" - what if you create directory?

**Comment by Sean4572435243** [comment]
I created the C:\Program Files\Go\src\noboltdb directory, but that just changed the message to "no Go files in ..."
If instead you were referring to creating the C:\users\Blockchain\erigon\build\bin directory, it's already there.

My best guess is the makefile incorrectly assembles the parameters for the compilation, as evidenced by the other "malformed" parameter warnings.  

Has anybody successfully compiled erigon on windows?

**Comment by Sean4572435243** [comment]
This is what's failing:

go build -trimpath -tags nosqlite,noboltdb -buildvcs=false -v -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=52987a56f30f3e784e848fae2445fd03af903f80 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/erigon/params.GitTag=v2021.10.03-1670-g52987a56f" -o "C:\users\Blockchain\erigon\build\bin\erigon.exe" ./cmd/erigon;$?

**Comment by AskAlexSharov** [comment]
"Has anybody successfully compiled erigon on windows?" - CI does https://github.com/ledgerwatch/erigon/runs/7819952314?check_suite_focus=true#step:8:1


```
go build -trimpath -tags nosqlite,noboltdb -buildvcs=false -v -ldflags "-X github.com/ledgerwatch/erigon/params.GitCommit=52987a56f30f3e784e848fae2445fd03af903f80 -X github.com/ledgerwatch/erigon/params.GitBranch=devel -X github.com/ledgerwatch/erigon/params.GitTag=v2021.10.03-1670-g52987a56f" -o "C:\users\Blockchain\erigon\build\bin\erigon.exe" ./cmd/erigon;$?
``` 
yep


@AndreaLanfranchi hi. help plz. 2 errors:
```
package noboltdb is not in GOROOT (C:\Program Files\Go\src\noboltdb)
stat C:\users\Blockchain\erigon\build\bin\erigon.exe: directory not found
```

**Comment by Sean4572435243** [comment]
I found a workaround.  Split the tags.  So instead of 
-tags nosqlite,noboltdb
do
-tags nosqlite -tags noboltdb

**Comment by Sean4572435243** [comment]
Also, please add to the instruction that the Windows System "Path" variable needs to be augmented with:
C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin

**Comment by AskAlexSharov** [comment]
Maybe you didn’t install chocolately or didn’t install mingw by  chocolately?

**Comment by Sean4572435243** [comment]
I sure did, I followed the instructions to a tee. 
choco install cmake make mingw
watched them all install
