### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by Sean4572435243** [ledgerwatch/erigon#5081]
#### System information

Erigon version: Latest

OS & Version: Windows Server 2012 R2 / Hyper-V VM

Commit hash : 

#### Expected behaviour

Doesn't crash

#### Actual behaviour

Crash, as shown:

> INFO[08-16|10:18:39.291] Build info                               git_branch=dev
> el git_tag=v2021.10.03-1670-g52987a56f git_commit=52987a56f30f3e784e848fae2445fd
> 03af903f80
> INFO[08-16|10:18:39.299] Starting Erigon on Ethereum mainnet...
> INFO[08-16|10:18:39.309] Maximum peer count                       ETH=100 total=
> 100
> INFO[08-16|10:18:39.314] starting HTTP APIs                       APIs=eth,net,e
> ngine,admin
> INFO[08-16|10:18:39.318] torrent verbosity                        level=WRN
> INFO[08-16|10:18:41.442] Set global gas cap                       cap=50000000
> INFO[08-16|10:18:41.771] Opening Database                         label=chaindat
> a path=D:\\Erigon\\chaindata
> INFO[08-16|10:18:42.003] Initialised chain configuration          config="{Chain
> ID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2
> 463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, P
> etersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000,
> London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Tota
> l Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Engine: ethash}" g
> enesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
> INFO[08-16|10:18:42.030] Effective                                prune_flags= s
> napshot_flags="--snapshots=true" history.v2=false
> INFO[08-16|10:18:57.151] Initialising Ethereum protocol           network=1
> INFO[08-16|10:18:57.157] Disk storage enabled for ethash DAGs     dir=D:\\Erigon
> \\ethash-dags count=2
> INFO[08-16|10:18:57.366] Starting private RPC server              on=127.0.0.1:9
> 090
> INFO[08-16|10:18:57.367] new subscription to logs established
> INFO[08-16|10:18:57.376] rpc filters: subscribing to Erigon events
> INFO[08-16|10:18:57.388] new subscription to newHeaders established
> INFO[08-16|10:18:57.390] [txpool] Started
> INFO[08-16|10:18:57.392] New txs subscriber joined
> INFO[08-16|10:19:57.379] [txpool] stat                            block=0 pendin
> g=0 baseFee=0 queued=14 alloc=2.5GB sys=4.3GB
> EROR[08-16|10:19:57.809] catch panic                              err="runtime e
> rror: index out of range [9500000] with length 9500000" stack="[main.go:29 panic
> .go:884 panic.go:119 config.go:246 block_snapshots.go:186 config.go:245 block_sn
> apshots.go:286 config.go:243 backend.go:566 node.go:115 main.go:58 app.go:526 ap
> p.go:286 main.go:34 proc.go:250 asm_amd64.s:1594]"

#### Steps to reproduce the behaviour

I previously successfully torrented all the archival data from a prior build.  Now to capture other bug-fixes, I stopped erigon, I then executed wmake.ps1, all the code was retrieved.  I had to modify the -tags to fix a separate bug, but was able to get a successful build.  Then I ran the following:

C:\Users\Blockchain\erigon\build\bin\erigon.exe --datadir D:\Erigon

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
please update erigon it was fixed
