### ISSUE TITLE
fatal error: unexpected signal during runtime execution (signal SIGBUS)

### ISSUE THREAD

**Issue by khkwan0** [ledgerwatch/erigon#5082]
This has been reported before but closed due to lack of info here...
https://github.com/ledgerwatch/erigon/issues/3859

I am seeing this as well...
Is there a certain branch I should be using?

This is the log of the run...
https://gist.github.com/khkwan0/f8eda7c1704f818b95139969966956a8

```
% ./erigon --version
erigon version 2022.99.99-dev-c1eef706
```

Here is my script that is used to start it...
```
#!/bin/bash

erigon/build/bin/erigon --chain=bsc --datadir=/mnt/highpoint --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 2>&1 | tee erigon_logs.txt
```

**Comment by AskAlexSharov** [comment]
```
make db-tools
./build/bin/mdbx_chk -vv <your_datadir>/chaindata
```

**Comment by AskAlexSharov** [comment]
SIGBUS on MMAP may be because of hardware failure: Please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk
