### ISSUE TITLE
Local devnet/private network: Empty blocks not processed despite correct flags

### ISSUE THREAD

**Issue by wsdt** [ledgerwatch/erigon#5087]
#### System information

Erigon version: `./erigon --version`

OS & Version: Ubuntu on WSL (Windows 11) -> everything within Docker-containers

Commit hash : `620d65ef10318677d1739d3c849b7d0f8a8c4424`
-> will also try to reproduce this today with the most recent hash!

#### Expected behaviour
Erigon should progress, it's stuck at block 1 (custom genesis) despite providing the flags `--mine --dev.period 1`

#### Actual behaviour
Always stuck on block 1, despite being connected to the consensus layer/beacon node (which has a validator that successfully connects). 

According to Discord when writing with @AlexeyAkhunov it seems to be a (temporary) bug. 

#### Steps to reproduce the behaviour
Our Erigon fork that we are working on: https://github.com/bobanetwork/erigon
-> Specific commit: https://github.com/bobanetwork/erigon/tree/297ddf02c2c2586d39d1c580fa98d9fee2827ee1

That's the main branch we are working on to get the full-stack running: 
https://github.com/bobanetwork/boba/tree/wsdt/l1-erigon-posdevnet
-> Specific commit: https://github.com/bobanetwork/boba/commit/e44d88c0915270acbd55707169546382b88acf3c

This is the docker-compose file to reproduce the issue (everything seems to work fine besides this): 
https://github.com/bobanetwork/boba/blob/wsdt/l1-erigon-posdevnet/ops/docker-compose-erigontest.yml

#### Backtrace

````bash
l1_execution_client_1                   | [DBUG] [08-15|13:31:04.205] Request skeleton                         anchors=0 top seen height=0 highestInDb=0
l1_execution_client_1                   | [DBUG] [08-15|13:31:04.683] [1/5 MiningCreateBlock] Candidate txs    amount=0
l1_execution_client_1                   | [INFO] [08-15|13:31:04.684] [1/5 MiningCreateBlock] Start mine       block=1 baseFee=875000000 gasLimit=30000000
l1_execution_client_1                   | [INFO] [08-15|13:31:04.684] [4/5 IntermediateHashes] Regeneration trie hashes started
l1_execution_client_1                   | [INFO] [08-15|13:31:04.684] [4/5 IntermediateHashes] Trie root       hash=0x8155380c2edb2521aa6e12b83b4f70bb8689d188f63c8b36b016e61776801014
l1_execution_client_1                   | [INFO] [08-15|13:31:04.684] [4/5 IntermediateHashes] Regeneration ended
l1_execution_client_1                   | [INFO] [08-15|13:31:04.684] Sealing paused, waiting for transactions
````

Thank you in advance! 
Happy for feedback. 

Might also spend some time myself to try to fix this, but would be very grateful to get pointed into the right direction!

**Comment by AskAlexSharov** [comment]
@fynn-z , hi. do you know why this can happen?

**Comment by wsdt** [comment]
ok when using the latest commit, the `--engine-addr` doesn't exist anymore.

**Comment by wsdt** [comment]
Ok when just removing that flag, i seem to be at the same stage again as referred in the issue. So the bug (if it is one) seems to have retained over several weeks.

**Comment by enriavil1** [comment]
@leonardchinonso

**Comment by leonardchinonso** [comment]
> @leonardchinonso

Looking at it

**Comment by wsdt** [comment]
Also get the output: 
```bash
Using developer account                  address=0x123463a4B065722E99115D6c222f267d9cABb524
Using custom developer period            seconds=1
```

**Comment by wsdt** [comment]
Ok wow, found it! Thank you all for the effort. 
The issue, was more an inconsistency of parameters (in the custom genesis block we had the dev.period defined by an environment variable that was defined as 0 under a different naming and via command line we defined the period as 1.

**Comment by fynn-z** [comment]
> @fynn-z , hi. do you know why this can happen?

sorry, I don't know either.

**Comment by wsdt** [comment]
for everyone coming here, the issue was that we provided the the `dev.period` on one side as flag via command line and additionally in the custom genesis block (what I didn't see). The original configuration in the genesis block seems to be the one that is taken in this case. 

Hope that helps anyone.
