### ISSUE TITLE
Erigon loops on [Snapshots] download step even though it shows 100%

### ISSUE THREAD

**Issue by jubos** [ledgerwatch/erigon#5098]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev-6e18bef6

OS & Version: Windows/Linux/OSX
Linux

Commit hash : 
6e18bef60ae12b633b472969d1fe3adf58d0127d

#### Expected behaviour

Erigon progresses past Snapshots download.

#### Actual behaviour
Loops on 100% progress and doesn't advance

#### Steps to reproduce the behaviour
Run the following:
./build/bin/erigon --datadir=/mnt/blocks/ --downloader.verify

#### Backtrace

````
INFO[08-17|16:16:49.874] [txpool] stat                            block=0 pending=19 baseFee=0 queued=120 alloc=2.4GB sys=3.2GB
INFO[08-17|16:16:49.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=1 connections=1 files=90 alloc=2.4GB sys=3.2GB
INFO[08-17|16:17:09.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=1 connections=1 files=90 alloc=2.5GB sys=3.2GB
INFO[08-17|16:17:29.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=2 connections=2 files=90 alloc=2.6GB sys=3.2GB
INFO[08-17|16:17:49.861] [p2p] GoodPeers                          eth66=33
INFO[08-17|16:17:49.874] [txpool] stat                            block=0 pending=19 baseFee=0 queued=120 alloc=2.7GB sys=3.2GB
INFO[08-17|16:17:49.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=2 connections=2 files=90 alloc=2.7GB sys=3.2GB
INFO[08-17|16:18:09.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=2 connections=2 files=90 alloc=2.2GB sys=3.2GB
INFO[08-17|16:18:29.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=1 connections=1 files=90 alloc=2.3GB sys=3.2GB
INFO[08-17|16:18:49.873] [txpool] stat                            block=0 pending=19 baseFee=0 queued=120 alloc=2.4GB sys=3.2GB
INFO[08-17|16:18:49.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=2 connections=2 files=90 alloc=2.4GB sys=3.2GB
INFO[08-17|16:19:09.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=2 connections=2 files=90 alloc=2.5GB sys=3.2GB
INFO[08-17|16:19:29.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=204.8KB/s upload=0B/s peers=1 connections=1 files=90 alloc=2.6GB sys=3.2GB
INFO[08-17|16:19:49.861] [p2p] GoodPeers                          eth66=33
INFO[08-17|16:19:49.873] [txpool] stat                            block=0 pending=19 baseFee=0 queued=120 alloc=2.7GB sys=3.2GB
INFO[08-17|16:19:49.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=2 connections=2 files=90 alloc=2.7GB sys=3.2GB
INFO[08-17|16:20:09.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=1 connections=1 files=90 alloc=2.2GB sys=3.2GB
INFO[08-17|16:20:29.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=1 connections=1 files=90 alloc=2.3GB sys=3.2GB
INFO[08-17|16:20:49.874] [txpool] stat                            block=0 pending=19 baseFee=0 queued=120 alloc=2.3GB sys=3.2GB
INFO[08-17|16:20:49.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=0B/s upload=0B/s peers=1 connections=1 files=90 alloc=2.3GB sys=3.2GB
INFO[08-17|16:21:09.886] [Snapshots] download                     progress="100.00% 226.2GB/226.2GB" download=102.4KB/s upload=0B/s peers=1 connections=1 files=90 alloc=2.4GB sys=3.2GB
````

**Comment by AskAlexSharov** [comment]
please add --metrics flag, start erigon wait when it gets to 100% point, then show us:
`http://localhost:6060/debug/vars`

**Comment by jubos** [comment]
Vars:
`
{
"cmdline": ["build/bin/erigon","--datadir=/mnt/blocks/erigon-mainnet","--downloader.verify","--metrics"],
"completedHandshakeConnectionFlags": {"ETr": 1, "Tr": 1, "eTr": 266, "eTrU": 206},
"connsToSelf": 0,
"dht": {},
"dhtAnnounceErrors": 0,
"dhtReadBlocked": 0,
"dhtReadNotKRPCDict": 0,
"dhtReadUnmarshalError": 0,
"dhtReadZeroPort": 0,
"dhtWriteErrors": 0,
"dhtWrites": 0,
"go-libutp": {"received messages": 6227, "socket PacketConn writes": 5222, "successful mmsg receive calls": 5671, "utp_check_timeouts calls": 654, "utp_issue_deferred_acks calls": 2768},
"memstats": {"Alloc":2238910096,"TotalAlloc":3600873096,"Sys":2798587128,"Lookups":0,"Mallocs":21517788,"Frees":7616119,"HeapAlloc":2238910096,"HeapSys":2618163200,"HeapIdle":348839936,"HeapInuse":2269323264,"HeapReleased":5029888,"HeapObjects":13901669,"StackInuse":15859712,"StackSys":15859712,"MSpanInuse":35506336,"MSpanSys":39478080,"MCacheInuse":38400,"MCacheSys":46800,"BuckHashSys":3224414,"GCSys":111493688,"OtherSys":10321234,"NextGC":4334556224,"LastGC":1660846463008379844,"PauseTotalNs":1793714,"PauseNs":[225800,184040,29290,30260,30450,36500,27400,31091,37190,37091,33031,36110,35980,34070,33900,39860,823831,35820,52000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1660846339141437189,1660846339143943062,1660846339147320538,1660846339152612715,1660846339160027986,1660846341292856025,1660846341309814579,1660846341320348544,1660846341340100613,1660846341370107736,1660846341404308035,1660846341441976729,1660846341495950026,1660846341587714537,1660846341714192838,1660846341929801467,1660846342265162617,1660846342785311001,1660846463008379844,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":19,"NumForcedGC":0,"GCCPUFraction":0.001114361068831797,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":12188,"Frees":6886},{"Size":16,"Mallocs":2427771,"Frees":2204565},{"Size":24,"Mallocs":12647399,"Frees":1093947},{"Size":32,"Mallocs":1582629,"Frees":528353},{"Size":48,"Mallocs":1036529,"Frees":979293},{"Size":64,"Mallocs":468344,"Frees":233337},{"Size":80,"Mallocs":267030,"Frees":121886},{"Size":96,"Mallocs":407247,"Frees":353164},{"Size":112,"Mallocs":20282,"Frees":14673},{"Size":128,"Mallocs":33107,"Frees":22163},{"Size":144,"Mallocs":150280,"Frees":142239},{"Size":160,"Mallocs":6390,"Frees":4420},{"Size":176,"Mallocs":6983,"Frees":4845},{"Size":192,"Mallocs":19512,"Frees":6731},{"Size":208,"Mallocs":27116,"Frees":20605},{"Size":224,"Mallocs":22718,"Frees":16845},{"Size":240,"Mallocs":8671,"Frees":6494},{"Size":256,"Mallocs":31800,"Frees":4477},{"Size":288,"Mallocs":124008,"Frees":120639},{"Size":320,"Mallocs":3967,"Frees":2741},{"Size":352,"Mallocs":2116,"Frees":1568},{"Size":384,"Mallocs":2856,"Frees":2028},{"Size":416,"Mallocs":4233,"Frees":515},{"Size":448,"Mallocs":44307,"Frees":24305},{"Size":480,"Mallocs":725,"Frees":497},{"Size":512,"Mallocs":37915,"Frees":5296},{"Size":576,"Mallocs":1762,"Frees":1408},{"Size":640,"Mallocs":198,"Frees":114},{"Size":704,"Mallocs":342,"Frees":190},{"Size":768,"Mallocs":817,"Frees":759},{"Size":896,"Mallocs":976,"Frees":824},{"Size":1024,"Mallocs":8476,"Frees":5917},{"Size":1152,"Mallocs":1363,"Frees":977},{"Size":1280,"Mallocs":861,"Frees":664},{"Size":1408,"Mallocs":6063,"Frees":5366},{"Size":1536,"Mallocs":208,"Frees":185},{"Size":1792,"Mallocs":390,"Frees":297},{"Size":2048,"Mallocs":17608,"Frees":1417},{"Size":2304,"Mallocs":630,"Frees":464},{"Size":2688,"Mallocs":219,"Frees":89},{"Size":3072,"Mallocs":224,"Frees":187},{"Size":3200,"Mallocs":17,"Frees":4},{"Size":3456,"Mallocs":17,"Frees":5},{"Size":4096,"Mallocs":405411,"Frees":1419},{"Size":4864,"Mallocs":223,"Frees":186},{"Size":5376,"Mallocs":67,"Frees":24},{"Size":6144,"Mallocs":1979,"Frees":148},{"Size":6528,"Mallocs":10,"Frees":2},{"Size":6784,"Mallocs":180,"Frees":173},{"Size":6912,"Mallocs":26,"Frees":11},{"Size":8192,"Mallocs":740,"Frees":581},{"Size":9472,"Mallocs":153,"Frees":27},{"Size":9728,"Mallocs":28,"Frees":27},{"Size":10240,"Mallocs":153,"Frees":145},{"Size":10880,"Mallocs":12,"Frees":11},{"Size":12288,"Mallocs":137,"Frees":129},{"Size":13568,"Mallocs":6,"Frees":4},{"Size":14336,"Mallocs":165,"Frees":135},{"Size":16384,"Mallocs":304,"Frees":288},{"Size":18432,"Mallocs":5,"Frees":3}]},
"messageTypesReceived": {"Extended": 479, "HaveAll": 472, "HaveNone": 1, "Piece": 10, "Unchoke": 6},
"mseCryptoProvides": {},
"numGoroutine": 2518,
"pieceHashedCorrect": 0,
"pieceHashedNotCorrect": 5,
"pieceInclinationsNew": 0,
"pieceInclinationsPut": 0,
"pieceInclinationsReused": 0,
"receivedKeepalives": 0,
"request-strategy": {},
"requestedChunkLengths": {},
"requestsReceivedForMissingPieces": 0,
"stm": {},
"torrent": {"Extended messages written for protocol \"ut_pex\"": 6, "added connections": 474, "chunks received": {"total": 10}, "connection.mainReadLoop returned with error": 2, "connection.mainReadLoop returned with no error": 472, "deleted connections": 946, "establish outgoing connection": 1642, "excess reserve peers discarded": 416, "initiated conn with fallback header obfuscation": 1, "initiated conn with preferred header obfuscation": 473, "messages written of type Bitfield": 10, "messages written of type Extended": 960, "messages written of type HaveAll": 938, "messages written of type Interested": 10, "messages written of type NotInterested": 10, "messages written of type Request": 20, "messages written of type Unchoke": 320, "network dialed first: tcp": 269, "network dialed first: udp": 209, "peers added by source \"Tr\"": 32844, "peers not added because of bad addr": 4, "peers replaced": 3707, "peers supporting extension": {"\"lt_donthave\"": 1, "\"share_mode\"": 1, "\"upload_only\"": 1, "\"ut_holepunch\"": 1, "\"ut_metadata\"": 473, "\"ut_pex\"": 473}, "successful dials": 539, "successful_peer_wire_protocol_handshake_peer_reserved_bytes": {"0000000000100005": 473, "0000000000180005": 1}, "unsuccessful dials": 10539},
"torrentConcurrentChunkWrites": 0,
"tracker/http": {"http responses with nonempty peers key": 107, "http responses with string peers": 107, "successful http announces": 107},
"utpMultiMsgRecvs": 429,
"utpNonUtpPacketsDropped": 0,
"utpSingleMsgRecvs": 5242,
"utpSocketNonUtpPacketsReceived": 1,
"utpSocketUtpPacketsReceived": 6226,
"webtorrent": {}
}
`

A few minutes later
`
{
"cmdline": ["build/bin/erigon","--datadir=/mnt/blocks/erigon-mainnet","--downloader.verify","--metrics"],
"completedHandshakeConnectionFlags": {"ETr": 72, "ETrU": 27, "Tr": 31, "TrU": 27, "eTr": 4905, "eTrU": 3231},
"connsToSelf": 0,
"dht": {},
"dhtAnnounceErrors": 0,
"dhtReadBlocked": 0,
"dhtReadNotKRPCDict": 0,
"dhtReadUnmarshalError": 0,
"dhtReadZeroPort": 0,
"dhtWriteErrors": 0,
"dhtWrites": 0,
"go-libutp": {"received messages": 74533, "socket PacketConn writes": 95773, "successful mmsg receive calls": 71179, "utp_check_timeouts calls": 10553, "utp_issue_deferred_acks calls": 49397},
"memstats": {"Alloc":2741618616,"TotalAlloc":11100884960,"Sys":2977965336,"Lookups":0,"Mallocs":88724517,"Frees":71273365,"HeapAlloc":2741618616,"HeapSys":2788294656,"HeapIdle":34971648,"HeapInuse":2753323008,"HeapReleased":5742592,"HeapObjects":17451152,"StackInuse":17694720,"StackSys":17694720,"MSpanInuse":40863104,"MSpanSys":41501760,"MCacheInuse":38400,"MCacheSys":46800,"BuckHashSys":3580366,"GCSys":116620672,"OtherSys":10226362,"NextGC":4528256096,"LastGC":1660848867477123112,"PauseTotalNs":3018205,"PauseNs":[225800,184040,29290,30260,30450,36500,27400,31091,37190,37091,33031,36110,35980,34070,33900,39860,823831,35820,52000,37660,51530,53000,58790,44650,53290,53490,89150,62640,135321,52820,58720,72230,52520,53630,63770,62250,52130,54020,62880,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1660846339141437189,1660846339143943062,1660846339147320538,1660846339152612715,1660846339160027986,1660846341292856025,1660846341309814579,1660846341320348544,1660846341340100613,1660846341370107736,1660846341404308035,1660846341441976729,1660846341495950026,1660846341587714537,1660846341714192838,1660846341929801467,1660846342265162617,1660846342785311001,1660846463008379844,1660846583251003653,1660846703468335423,1660846823689927292,1660846943905375854,1660847064126942180,1660847184340971174,1660847304566045925,1660847424787233914,1660847545010640137,1660847665237207474,1660847785460041819,1660847905679566165,1660848025905696655,1660848146127838893,1660848266347952856,1660848386580677456,1660848506812946383,1660848627033055933,1660848747249729081,1660848867477123112,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":39,"NumForcedGC":0,"GCCPUFraction":0.0004922108472551862,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":776512,"Frees":723684},{"Size":16,"Mallocs":14333935,"Frees":13496135},{"Size":24,"Mallocs":18966808,"Frees":6932909},{"Size":32,"Mallocs":12276547,"Frees":10529495},{"Size":48,"Mallocs":7798307,"Frees":7389786},{"Size":64,"Mallocs":9101017,"Frees":8373806},{"Size":80,"Mallocs":3777661,"Frees":3486877},{"Size":96,"Mallocs":3341575,"Frees":3182933},{"Size":112,"Mallocs":353481,"Frees":336383},{"Size":128,"Mallocs":685948,"Frees":650005},{"Size":144,"Mallocs":1138894,"Frees":1075857},{"Size":160,"Mallocs":100186,"Frees":95369},{"Size":176,"Mallocs":146542,"Frees":139147},{"Size":192,"Mallocs":922213,"Frees":824043},{"Size":208,"Mallocs":388640,"Frees":372227},{"Size":224,"Mallocs":369939,"Frees":352045},{"Size":240,"Mallocs":140796,"Frees":131085},{"Size":256,"Mallocs":112398,"Frees":81946},{"Size":288,"Mallocs":964406,"Frees":890322},{"Size":320,"Mallocs":51139,"Frees":47743},{"Size":352,"Mallocs":44191,"Frees":41652},{"Size":384,"Mallocs":51071,"Frees":48361},{"Size":416,"Mallocs":24954,"Frees":19921},{"Size":448,"Mallocs":4707101,"Frees":4387383},{"Size":480,"Mallocs":19597,"Frees":17784},{"Size":512,"Mallocs":128161,"Frees":93100},{"Size":576,"Mallocs":28584,"Frees":26470},{"Size":640,"Mallocs":13455,"Frees":11912},{"Size":704,"Mallocs":14362,"Frees":13349},{"Size":768,"Mallocs":9017,"Frees":8339},{"Size":896,"Mallocs":13300,"Frees":12292},{"Size":1024,"Mallocs":88738,"Frees":82181},{"Size":1152,"Mallocs":46282,"Frees":42287},{"Size":1280,"Mallocs":12730,"Frees":11834},{"Size":1408,"Mallocs":78424,"Frees":75547},{"Size":1536,"Mallocs":2162,"Frees":2028},{"Size":1792,"Mallocs":4702,"Frees":4153},{"Size":2048,"Mallocs":28073,"Frees":11143},{"Size":2304,"Mallocs":10930,"Frees":10190},{"Size":2688,"Mallocs":7355,"Frees":6768},{"Size":3072,"Mallocs":5734,"Frees":5332},{"Size":3200,"Mallocs":1524,"Frees":1433},{"Size":3456,"Mallocs":1128,"Frees":1038},{"Size":4096,"Mallocs":409570,"Frees":5395},{"Size":4864,"Mallocs":2395,"Frees":2205},{"Size":5376,"Mallocs":1342,"Frees":1169},{"Size":6144,"Mallocs":3125,"Frees":1252},{"Size":6528,"Mallocs":839,"Frees":792},{"Size":6784,"Mallocs":559,"Frees":525},{"Size":6912,"Mallocs":538,"Frees":391},{"Size":8192,"Mallocs":4354,"Frees":3984},{"Size":9472,"Mallocs":1355,"Frees":1168},{"Size":9728,"Mallocs":186,"Frees":179},{"Size":10240,"Mallocs":612,"Frees":536},{"Size":10880,"Mallocs":237,"Frees":230},{"Size":12288,"Mallocs":867,"Frees":798},{"Size":13568,"Mallocs":354,"Frees":343},{"Size":14336,"Mallocs":443,"Frees":389},{"Size":16384,"Mallocs":1205,"Frees":1091},{"Size":18432,"Mallocs":235,"Frees":217}]},
"messageTypesReceived": {"Extended": 8366, "HaveAll": 8265, "HaveNone": 8, "Piece": 81, "Reject": 5415, "Unchoke": 71},
"mseCryptoProvides": {},
"numGoroutine": 2714,
"pieceHashedCorrect": 0,
"pieceHashedNotCorrect": 40,
"pieceInclinationsNew": 0,
"pieceInclinationsPut": 0,
"pieceInclinationsReused": 0,
"receivedKeepalives": 109,
"request-strategy": {},
"requestedChunkLengths": {},
"requestsReceivedForMissingPieces": 0,
"stm": {},
"torrent": {"Extended messages written for protocol \"ut_pex\"": 187, "added connections": 8293, "chunks received": {"total": 81}, "connection.mainReadLoop returned with error": 28, "connection.mainReadLoop returned with no error": 8255, "deleted connections": 16538, "establish outgoing connection": 26412, "excess reserve peers discarded": 1979, "initiated conn with fallback header obfuscation": 58, "initiated conn with preferred header obfuscation": 8235, "messages written of type Bitfield": 126, "messages written of type Cancel": 8016, "messages written of type Extended": 16960, "messages written of type HaveAll": 16460, "messages written of type Interested": 126, "messages written of type NotInterested": 80, "messages written of type Request": 10994, "messages written of type Unchoke": 4966, "network dialed first: tcp": 5242, "network dialed first: udp": 3326, "peers added by source \"Tr\"": 56269, "peers not added because of bad addr": 971, "peers replaced": 9702, "peers supporting extension": {"\"lt_donthave\"": 99, "\"share_mode\"": 99, "\"upload_only\"": 99, "\"ut_holepunch\"": 99, "\"ut_metadata\"": 8273, "\"ut_pex\"": 8273}, "successful dials": 8952, "successful_peer_wire_protocol_handshake_peer_reserved_bytes": {"0000000000100005": 8261, "0000000000180005": 32}, "unsuccessful dials": 169195, "written keepalives": 99},
"torrentConcurrentChunkWrites": 0,
"tracker/http": {"http responses with nonempty peers key": 278, "http responses with string peers": 278, "successful http announces": 278},
"utpMultiMsgRecvs": 2922,
"utpNonUtpPacketsDropped": 0,
"utpSingleMsgRecvs": 68257,
"utpSocketNonUtpPacketsReceived": 73,
"utpSocketUtpPacketsReceived": 74460,
"webtorrent": {}
}
`

**Comment by jubos** [comment]
8 hours later, it runs out of memory on a 64GB ram machine.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x19df28b?, 0x2030?})
        runtime/panic.go:1047 +0x5d fp=0x7feec27fbc88 sp=0x7feec27fbc58 pc=0x45c7fd
runtime.sysMapOS(0xc5af000000, 0x19ac00000?)
        runtime/mem_linux.go:187 +0x11b fp=0x7feec27fbcd0 sp=0x7feec27fbc88 pc=0x43d73b
runtime.sysMap(0x2dd4b80?, 0x7fef5b5b9000?, 0x450ba0?)
        runtime/mem.go:142 +0x35 fp=0x7feec27fbd00 sp=0x7feec27fbcd0 pc=0x43d115
runtime.(*mheap).grow(0x2dd4b80, 0xcd4c8?)
        runtime/mheap.go:1459 +0x23d fp=0x7feec27fbd70 sp=0x7feec27fbd00 pc=0x44dc5d
runtime.(*mheap).allocSpan(0x2dd4b80, 0xcd4c8, 0x0, 0x1)
        runtime/mheap.go:1191 +0x1be fp=0x7feec27fbe08 sp=0x7feec27fbd70 pc=0x44d3be
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:910 +0x65 fp=0x7feec27fbe50 sp=0x7feec27fbe08 pc=0x44ce45
runtime.systemstack()
        runtime/asm_amd64.s:492 +0x49 fp=0x7feec27fbe58 sp=0x7feec27fbe50 pc=0x48ebe9
```

**Comment by mikolajsobolewski** [comment]
Have the same problem. Maybe have any workarounds?

**Comment by AskAlexSharov** [comment]
@mikolajsobolewski does --torrent.port open for TCP and UDP?

**Comment by jubos** [comment]
I am still stuck even after upgrading to defbddf8d64718c71ec24c408f31c7f28ecf3e9e.  It does show download and upload bandwidth and peers connections, but doesn't advance past the Snapshot download.

Do you think it is worth trying to open the ports on the router?

**Comment by mikolajsobolewski** [comment]
> @mikolajsobolewski does --torrent.port open for TCP and UDP?
Sorry for delay and yes, torrent port open for TCP and UDP
