### ISSUE TITLE
Trouble reading in toml

### ISSUE THREAD

**Issue by icculp** [ledgerwatch/erigon#5109]
I'm having trouble reading in parameters with a toml file via the `--config` flag. Any flag that would be separated by a dot in the command line I can't get to parse in the toml file, such as --http.port, --http.api, --private.api.addr, etc. I'm not sure if this is a bug or if I'm unaware of the proper syntax. Could someone point me in the right direction? 
![image](https://user-images.githubusercontent.com/57159226/185501586-d01f4ca3-eb3f-4c50-8990-36e87276f3a6.png)
![image](https://user-images.githubusercontent.com/57159226/185501527-9a43a52f-320a-49e5-9ae2-03da22e3b99b.png)

**Comment by enriavil1** [comment]
api is not in an array

**Comment by icculp** [comment]
I tried it with all of the above, with array brackets and without, with each word wrapped in quotes individually and with quotes only on the ends. But if I take out all other parameters, and only try http.port, for example, which there is no ambiguity about array format, I get the same error with the port as an integer or as a string.

**Comment by icculp** [comment]
Even tried it as the following to no avail...
[HTTP]
port = whatever

http.port = whatever

[HTTP]
http.port = whatever

**Comment by enriavil1** [comment]
> Even tried it as the following to no avail...
> 
> [HTTP]
> 
> port = whatever
> 
> 
> 
> http.port = whatever
> 
> 
> 
> [HTTP]
> 
> http.port = whatever
> 
> 
> 
> 
> 
> 

Could you post the whole file so I can actually just try it out with the exact file.

**Comment by icculp** [comment]
The toml file? The screenshot is the whole thing

**Comment by enriavil1** [comment]
> The toml file? The screenshot is the whole thing

Okay 👍 I will use it to recreate it your issue thank you

**Comment by enriavil1** [comment]
I found the problem headers such as [HTTP] actually break the structure of the file that it currently has. Erigon also didn't parse slices before, but now we do. I have added examples and how to use the config files in the ReadMe
