### ISSUE TITLE
--prune shortcut doesn't work

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5115]
`erigon --prune=hrtc`
`EROR[08-19|11:31:55.494] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.r.older=90000 --prune.t.older=90000 --prune.c.older=90000"`

**Comment by yperbasis** [comment]
Still happening for me with the latest `devel`.
