### ISSUE TITLE
Could not check configuration values between execution and consensus client error

### ISSUE THREAD

**Issue by andrii1890** [ledgerwatch/erigon#5169]
Hi. Try to connect pryzm (v3.0.0) ro erigon (2022.08.02-alpha) and get this error in pryzm log:

ERROR powchain: Could not check configuration values between execution and consensus client error=the execution layer doesn't have a terminal total difficulty. expected: 0xc70d808a128d7380000: client error while processing request

**Comment by bsamuels453** [comment]
how'd you fix it @andrii1890

**Comment by andrii1890** [comment]
Hi. Make the latest version
https://github.com/ledgerwatch/erigon/tree/v2022.08.02

чт, 25 серп. 2022, 01:44 користувач Benjamin Samuels <
***@***.***> пише:
