### ISSUE TITLE
TTD is not returned to consensus client

### ISSUE THREAD

**Issue by panghalamit** [ledgerwatch/erigon#5189]
#### System information

Erigon version: `./erigon --version`
git_branch=heads/v2022.08.02 git_tag=v2022.08.02-dirty

OS & Version: Windows/Linux/OSX
Linux

Commit hash : 
35c4faa1b41e8379a74d0385505add0dd450c2ed

#### Expected behaviour
Latest version should return TTD value to consensus client

#### Actual behaviour

>[WARN] [08-25|18:52:05.001] Served                                   conn=10.100.27.141:33502 method=engine_exchangeTransitionConfigurationV1 reqid=1 t=57.192µs err="the execution layer doesn't have a terminal total difficulty. expected: 0xc70d808a128d7380000"                          │
│ [WARN] [08-25|18:52:07.707] Served                                   conn=10.100.27.141:33502 method=engine_exchangeTransitionConfigurationV1 reqid=1 t=57.89µs err="the execution layer doesn't have a terminal total difficulty. expected: 0xc70d808a128d7380000"                           │
│ [WARN] [08-25|18:52:17.002] Served                                   conn=10.100.27.141:33502 method=engine_exchangeTransitionConfigurationV1 reqid=1 t=61.602µs err="the execution layer doesn't have a terminal total difficulty. expected: 0xc70d808a128d7380000"                          │
│ [WARN] [08-25|18:52:29.002] Served                                   conn=10.100.27.141:33502 method=engine_exchangeTransitionConfigurationV1 reqid=1 t=50.443µs err="the execution layer doesn't have a terminal total difficulty. expected: 0xc70d808a128d7380000"                       │

#### Backtrace

````
[backtrace]
````

Logs indicate TTD is set in configuration 

>  [INFO] [08-25|18:49:34.869] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Mui │
│ r Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3

**Comment by panghalamit** [comment]
More context on this. 
Node was upgraded from `v2022.05.09` to `v2022.08.02`

**Comment by panghalamit** [comment]
Also seeing these in logs, what do they mean?

> │ [INFO] [08-25|20:54:44.850] {15043571-15411292 links=367761 (15043571-15410764-15410786-15410787-15410799-15410822-15410823-15410834-15410839-15410860-15410861-15410869-15410875-15410878-15410885-15410889-15410908-15410913-15410934-15410936-15410970-15410981-15410989-15411006-15411037 │
│ -15411049-15411054-15411096-15411112-15411113-15411132-15411154-15411157-15411165-15411171-15411225-15411232-15411274-15411292)} => 8bd1cb82a54195540851dba164d8b8c1d706443da5b61a147a8a92bd01b764ba, anchorQueue.idx=0, next retry in 4.977680833s

**Comment by enriavil1** [comment]
That's normal it means its downloading headers.

**Comment by enriavil1** [comment]
Has your node still processing heads?

**Comment by panghalamit** [comment]
My node restarted during migration process . Rewinding upto 400k blocks when I upgraded the node. 

Processing stopped at block 15050010

> │ [INFO] [08-29|19:15:20.023] [snapshots] Dumping txs                  block num=14783016 alloc=4.8GB sys=12.6GB                                                                                                                                                                                        │
│ [INFO] [08-29|19:15:20.057] Req/resp stats                           req=31 reqMin=15046515 reqMax=15046735 skel=15 skelMin=15051546 skelMax=15346266 resp=45 respMin=15046517 respMax=15344922 dups=2688                                                                                             │
│ [INFO] [08-29|19:15:20.068] Queue sizes                              anchors=1 links=389176 persisted=0                                                                                                                                                                                               │
│ [INFO] [08-29|19:15:20.068] {15046708-15435869 links=389176 (15046708-15435582-15435603-15435605-15435648-15435716-15435728-15435733-15435749-15435751-15435777-15435789-15435812-15435862-15435869)} => 91ef38685cef1153a554e6224f374013982ab2a4c84486e0ef47d783bec81c26, anchorQueue.idx=0, next re │
│ [INFO] [08-29|19:15:27.460] [txpool] stat                            block=15050010 pending=9894 baseFee=0 queued=30000 alloc=5.1GB sys=12.6GB                                                                                                                                                        │
│ [INFO] [08-29|19:15:37.696] [snapshots] Dumping txs                  block num=14783727 alloc=5.6GB sys=12.6GB                                                                                                                                                                                        │
│ [INFO] [08-29|19:15:40.057] Req/resp stats                           req=45 reqMin=15046471 reqMax=15046706 skel=17 skelMin=15051546 skelMax=15346266 resp=73 respMin=15046473 respMax=15435872 dups=3266                                                                                             │
│ [INFO] [08-29|19:15:40.068] Queue sizes                              anchors=1 links=389223 persisted=0                                                                                                                                                                                               │
│ [INFO] [08-29|19:15:40.068] {15046664-15435872 links=389223 (15046664-15435582-15435603-15435605-15435648-15435716-15435728-15435733-15435749-15435751-15435777-15435789-15435812-15435862-15435872)} => 0899905f5e8f190efe3747e7e5d9e382f0d82526b164cb9a8b258fd0c88ef4b5, anchorQueue.idx=0, next re │
│ [INFO] [08-29|19:15:57.153] [snapshots] Dumping txs                  block num=14784352 alloc=6.4GB sys=12.6GB                                                                                                                                                                                        │
│ [INFO] [08-29|19:16:00.057] Req/resp stats                           req=39 reqMin=15046434 reqMax=15046663 skel=15 skelMin=15051546 skelMax=15346266 resp=62 respMin=15046436 respMax=15435874 dups=2708                                                                                             │
│ [INFO] [08-29|19:16:00.068] Queue sizes                              anchors=1 links=389262 persisted=0                                                                                                                                                                                               │
│ [INFO] [08-29|19:16:00.068] {15046627-15435874 links=389262 (15046627-15435582-15435603-15435605-15435648-15435716-15435728-15435733-15435749-15435751-15435777-15435789-15435812-15435862-15435874)} => a70d3a4b85e2cee60d2a142632977d050f08d53281430056ece5f1990f3978ab, anchorQueue.idx=0, next re │
│ [INFO] [08-29|19:16:17.233] [snapshots] Dumping txs                  block num=14785057 alloc=3.9GB sys=12.6GB                                                                                                                                                                                        │
│ [INFO] [08-29|19:16:20.057] Req/resp stats                           req=29 reqMin=15046407 reqMax=15046626 skel=16 skelMin=15051546 skelMax=15346266 resp=49 respMin=15046409 respMax=15435875 dups=3267                                                                                             │
│ [INFO] [08-29|19:16:20.068] Queue sizes                              anchors=1 links=389290 persisted=0                                                                                                                                                                                               │
│ [INFO] [08-29|19:16:20.068] {15046600-15435875 links=389290 (15046600-15435582-15435603-15435605-15435648-15435716-15435728-15435733-15435749-15435751-15435777-15435789-15435812-15435862-15435875)} => 44c51ec42fcfa363f26638142743e08dc5955671de494f216e698d51c80e0923, anchorQueue.idx=0, next re │
│ [INFO] [08-29|19:16:27.668] [txpool] stat                            block=15050010 pending=9894 baseFee=0 queued=30000 alloc=4.3GB sys=12.6GB                                                                                                                                                        │
│ [INFO] [08-29|19:16:38.486] [snapshots] Dumping txs                  block num=14785782 alloc=4.8GB sys=12.6GB                                                                                                                                                                                        │
│ [INFO] [08-29|19:16:40.057] Req/resp stats                           req=22 reqMin=15046388 reqMax=15046599 skel=16 skelMin=15051546 skelMax=15346266 resp=38 respMin=15046390 respMax=15435876 dups=2693                                                                                             │
│ [INFO] [08-29|19:16:40.069] Queue sizes                              anchors=1 links=389310 persisted=0                                                                                                                                                                                               │
│ [INFO] [08-29|19:16:40.069] {15046581-15435876 links=389310 (15046581-15435582-15435603-15435605-15435648-15435716-15435728-15435733-15435749-15435751-15435777-15435789-15435812-15435862-15435876)} => fceabc36c1bbbaec4154cc1814d81412d18ec5a24551640cc6500fa11769fe8e, anchorQueue.idx=0, next re │
│ [INFO] [08-29|19:16:52.305] [p2p] GoodPeers                          eth66=32                                                                                                                                                                                                                         │
│ [INFO] [08-29|19:16:56.734] Flushed buffer file                      name=/var/lib/erigon/etl-temp/erigon-sortable-buf-4213626109 alloc=5.6GB sys=12.6GB                                                                                                                                              │
│ [INFO] [08-29|19:16:57.220] [snapshots] Dumping txs                  block num=14786453 alloc=5.6GB sys=12.6GB

**Comment by panghalamit** [comment]
I am not sure if this means it is making some progress syncing 
`│ [INFO] [08-29|19:16:57.220] [snapshots] Dumping txs block num=14786453 alloc=5.6GB sys=12.6GB`

**Comment by panghalamit** [comment]
I think I might be in bad state from following steps 
1) upgrade from v2022.05.09 to v2022.08.02
2) Resulted in migration , and unwinding of some 400k blocks
3) Node was reverted back to v2022.05.09 while migration was in progress 
4) I have now upgraded the node to v2022.08.03. 

Not sure if node would be able to recover on its own or not.

**Comment by panghalamit** [comment]
I had to restore the node from old backup before the upgrade to get it out of the limbo. Closing this as this is resolved for me
