### ISSUE TITLE
Prometheus dashboard configuration incorrect for non-docker environments?

### ISSUE THREAD

**Issue by dylancaponi** [ledgerwatch/erigon#5220]
It seems like [the erigon prometheus/grafana dashboard file](https://github.com/ledgerwatch/erigon/blob/devel/cmd/prometheus/dashboards/erigon.json) which is linked to from several ETH node setup guides is not properly configured for a non-docker environment.

Changing: `turbogeth16c.weblogix.it` in several places to `127.0.0.1/debug/metrics/prometheus:6060` and deleting all appearances of `instance=~"$instance"` seems to populate the dashboard.

Also `“$__rate_interval”` is broken and must be changed to `“$__interval”`

Should I make a PR with these changes or put a new dashboard file somewhere else in the repo?

**Comment by AskAlexSharov** [comment]
1. rate_interval it's an variable - you can find it in dashboard settings, and it works. 
2. $instance is dynamic variable which extracted from `go_goroutines` metric. does your node export this metric?
3. `turbogeth16c.weblogix.it` I believe it's just default filter - you can change node filter in UI. Can you?

**Comment by AskAlexSharov** [comment]
4. .json file is not for manual editting - edit board by UI - then export it by `settings -> json model`

**Comment by AskAlexSharov** [comment]
I did look deeper and yep, seems weblogix part are redundant. removed by  https://github.com/ledgerwatch/erigon/pull/5225

**Comment by dylancaponi** [comment]
I don't see why it matters if you edit the json or via UI as long as it's valid JSON when you're done.

I tried the file from your PR and no charts load. I'm not sure what `instance=~"$instance"` is supposed to do, but I have to remove all occurrences of it for my dashboard to populate.

**Comment by dylancaponi** [comment]
Also, the `devel` branch has no human reviewers for merges? That seems problematic no?

**Comment by dylancaponi** [comment]
1. Ah this is a version issue, I'll update my prometheus: https://github.com/grafana/grafana/issues/44542

**Comment by AskAlexSharov** [comment]
> Also, the `devel` branch has no human reviewers for merges? That seems problematic no?

We have reviewers, just it’s not required. Each person reviewing own domain.
