### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by LeoHChen** [ledgerwatch/erigon#5228]
#### System information

Erigon version: `./erigon --version`

OS & Version: Linux on ARM64 platform

go version go1.18.3 linux/arm64

Commit hash : 

commit 808180e80133dbbd1e532f766eccbc03db9b1815 (HEAD -> devel, origin/devel, origin/HEAD)
Author: Alex Sharov <AskAlexSharov@gmail.com>
Date:   Tue Aug 30 11:30:34 2022 +0700

    grafana clean (#5226)

#### Expected behaviour

`make erigon` should pass after checkout the `devel` branch.

#### Actual behaviour

```
Building erigon
go: downloading github.com/ledgerwatch/erigon-lib v0.0.0-20220828042332-9e0d939137d5
../../common/debug/memstats.go:7:2: github.com/ledgerwatch/erigon-lib@v0.0.0-20220828042332-9e0d939137d5: invalid version: unknown revision 9e0
d939137d5

```

#### Steps to reproduce the behaviour

```
make erigon
```

#### Backtrace

````
[backtrace]
````

**Comment by baileywainwright** [comment]
@LeoHChen what Linux distribution are you using? I had a similar error but was able to resolve this by setting the go env GOPROXY value to "https://proxy.golang.org,direct".

**Comment by grassr00t** [comment]
ha, I am using Amazon Linux 2

**Comment by LeoHChen** [comment]
@baileywainwright I am using Amazon Linux 2.  My build machine is on AWS.

**Comment by LeoHChen** [comment]
And the trick solved my problem.  Appreciate! @baileywainwright
