### ISSUE TITLE
Erigon BSC stops syncing unless restarted

### ISSUE THREAD

**Issue by 14MR** [ledgerwatch/erigon#5263]
#### System information

Erigon version: `erigon version 2022.08.2-alpha-35c4faa1`

OS & Version: Linux

Commit hash : `git_commit=35c4faa1b41e8379a74d0385505add0dd450c2ed`

#### Expected behaviour
Keeping up to date with new blocks

#### Actual behaviour
After syncing blocks which are older then current time, erigon stops syncing newer ones

#### Steps to reproduce the behaviour
1. Run erigon with above mentioned version 
2. Wait for sync of older blockls
3. Erigon will stop catching newer ones

#### Backtrace

Logs are in attachment
[bsc.log](https://github.com/ledgerwatch/erigon/files/9476290/bsc.log)

**Comment by AskAlexSharov** [comment]
logs have error: 
```
[EROR] [08-30|22:40:38.416] Staged Sync                              err="[5/16 Senders] retireBlocksInSingleBackgroundThread: [5/16 Senders Prune] retire blocks last error: DumpBlocks: DumpHeaders: header missed in db: block_num=20000000,  hash=ba219d00ab4ea174ead8efa90c80e9d9f9990e221bf8e7da1881ec210edbb879, fromBlock=20000000, toBlock=20500000"
```
temporary workaround for this error: --snap.stop

**Comment by 14MR** [comment]
It worked, thank you
