### ISSUE TITLE
Can we release erigon 2 before merge?

### ISSUE THREAD

**Issue by marshalys** [ledgerwatch/erigon#5271]

**Comment by AskAlexSharov** [comment]
Release every Thursday

**Comment by marshalys** [comment]
Still alpha version?
Can I use it in production ?

**Comment by AskAlexSharov** [comment]
yes. use `alpha` releases.
`alpha` means - we will do big incompatible change of db format in future - for such big change can't provide auto-migration path, it will require re-sync. but it will happen in not very close future.

**Comment by marshalys** [comment]
ok, thank you!
