### ISSUE TITLE
trace_block issue

### ISSUE THREAD

**Issue by ScalableIntegration** [ledgerwatch/erigon#5284]
Calls trace_block("0x728c6f") and trace_transaction("0x5ac02c918167f0e1b9b3c0497a70a04414a5aa21da596ebec82063648b194ff0") in goerli testnet network on erigon returns error: insufficient funds for gas.
On other block/transaction such calls returns expected data.

Same error for polygon network already exists as issue: https://github.com/ledgerwatch/erigon/issues/4963
$ curl -X POST -d '{"jsonrpc": "2.0", "params": ["0x728c6f"], "id": 1, "method": "trace_block"}' "http://ip"
{"jsonrpc":"2.0","result":null,"error":{"code":-32000,"message":"first run for txIndex 119 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 20283555769489071 want 20283568769489071"},"id":1}

$ curl -X POST -d '{"jsonrpc": "2.0", "params": ["0x5ac02c918167f0e1b9b3c0497a70a04414a5aa21da596ebec82063648b194ff0"], "id": "bc04m4s7", "method": "trace_transaction"}' "http://ip"
{"jsonrpc":"2.0","result":null,"error":{"code":-32000,"message":"first run for txIndex 119 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 20283555769489071 want 20283568769489071"},"id":1}

We are using erigon version 2022.08.3-alpha-defbddf8
./erigon --datadir=/data --private.api.addr=... --chain goerli --verbosity 4 --authrpc.jwtsecret=...
./rpcdaemon --datadir=/data --http.port ... --http.addr=... --private.api.addr=... --http.api=eth,net,trace

**Comment by ScalableIntegration** [comment]
Same issue occurs on eth mainnet for block 15539509.

**Comment by revitteth** [comment]
This is fixed in latest Devel, closing :)
