### ISSUE TITLE
Please change the docs for the merge. I’m meaning to create a faq.

### ISSUE THREAD

**Issue by ytrezq** [ledgerwatch/erigon#5285]
How to run an Erigon2 full archival node with debugging and tracing after the Merge ?
How to connect Erigon2 to a consensus Client ? Are any consensus client compatible with Erigon2 ? If not, which is the consensus client which like Erigon, has the fastest sync speed ?
Is setting the consensus client to archive mode required for running an Erigon2 full archive mode or is it possible to set up an Erigon2 archive node with a light consensus client ?

**Comment by quickchase** [comment]
https://chasewright.com/getting-started-with-turbo-geth-on-ubuntu/

**Comment by ytrezq** [comment]
@quickchase : you don’t explain if setting the consensus client to archive mode required for running an Erigon2 full archive mode or is it possible to set up an Erigon2 archive node with a light consensus client ?

Also, [building is failing](https://github.com/ledgerwatch/erigon/issues/4153#issuecomment-1240123160)

**Comment by quickchase** [comment]
You don't need an archive lighthouse to use archive erigon. Also:

![SmartSelect_20220908_044123_Brave.jpg](https://user-images.githubusercontent.com/87909910/189090169-464ce3e4-b16f-4e87-be6d-944f4c7fbe2d.jpg)
