### ISSUE TITLE
Passing --history.v2 runtime argument has no effect

### ISSUE THREAD

**Issue by JamesCropcho** [ledgerwatch/erigon#5293]
#### System information

Erigon version: `./erigon --version`

```
erigon version 2022.09.1-alpha-4067b7c4
```

OS & Version: Windows/Linux/OSX

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
$ uname -a
Linux hostname 5.15.0-1019-aws #23-Ubuntu SMP Wed Aug 17 18:33:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

#### Expected behaviour

Using runtime argument `--history.v2` or `--history.v2=true` should result in using the new DB and Snapshots format of history.

#### Actual behaviour

Using runtime argument `--history.v2` results in:

```
Effective  prune_flags="--prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000" snapshot_flags="--snapshots=true" history.v2=false
```

**Comment by AskAlexSharov** [comment]
1. it's not allowed to change this flag after node creation
2. it's experimental flag, renamed to --experimental.history.v2
