### ISSUE TITLE
Which version I should use after "the merge" in mainnet？

### ISSUE THREAD

**Issue by marshalys** [ledgerwatch/erigon#5300]
Hi！
Now I use version [2022.04.05-deprecated](https://github.com/ledgerwatch/erigon/releases/tag/v2022.04.05), it's good! 
But after merge this version can't keep running, so I want to know witch version I should use after "the merge", thank you!

**Comment by AskAlexSharov** [comment]
Last alpha release

**Comment by marshalys** [comment]
ok, thank you!
