### ISSUE TITLE
question: about the trace_filter

### ISSUE THREAD

**Issue by shiziwen** [ledgerwatch/erigon#5304]
What does Trace_filter do? 

Is there any documentation about this interface? 

For example, what is the meaning of each field of the return value?

**Comment by banteg** [comment]
https://openethereum.github.io/JSONRPC-trace-module
https://docs.alchemy.com/reference/trace-api-quickstart

**Comment by shiziwen** [comment]
> 

Thank you, I will read the docs.

**Comment by shiziwen** [comment]
@banteg  About the trace_filter, for every transaction matching given fromAddress or toAddress, it will need to execute it on the block which contains the transaction again?

**Comment by shiziwen** [comment]
And is there public reign fullnode which I can test the trace api? such as trace_filter.

**Comment by shiziwen** [comment]
> And is there public reign fullnode which I can test the trace api? such as trace_filter.

I found https://eth-mainnet.alchemyapi.io/v2/demo can be used to test

**Comment by shiziwen** [comment]
@banteg Fro trace_filter, fromAddress and toAddress are contract address?
