### ISSUE TITLE
Fastest way to get all transaction receipts from Erigon

### ISSUE THREAD

**Issue by SuchJitter** [ledgerwatch/erigon#5311]
Currently I'm trying to index all transactions on ethereum mainnet into a NOSQL database, what would be the fastest way about doing this. Can we directly go into erigon's database in some way. Right now I just have one big for loop, getting blocks sequentially and asynchronously getting all the transaction receipts for the txid's.

**Comment by enriavil1** [comment]
Hmm you could try using the snapshots directly.

**Comment by AskAlexSharov** [comment]
1. Can do batch json-rpc requests
2. Can do parallel json-rpc requests

**Comment by AskAlexSharov** [comment]
See —rpc.batch.concurrency

**Comment by SuchJitter** [comment]
> See —rpc.batch.concurrency

I have done this, still can only get a maximum of around 5000 tx receipts per second. Using around 60 threads.

**Comment by AskAlexSharov** [comment]
can also try to increase --db.read.concurrency 
can also add --pprof flag and see where is the bottleneck

**Comment by SuchJitter** [comment]
> can also try to increase --db.read.concurrency can also add --pprof flag and see where is the bottleneck

[This is the cpu profiling from pprof](https://ibb.co/b1JKJvy)
