### ISSUE TITLE
method eth_newBlockFilter does not exist/is not available

### ISSUE THREAD

**Issue by bl4ck5un** [ledgerwatch/erigon#5336]
#### System information

Erigon version: erigon version 2022.09.1-alpha-4067b7c4

OS & Version: Linux

Commit hash : 4067b7c4

#### Expected behaviour

`eth_newBlockFilter` should be available according to https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon.

#### Actual behaviour

`eth_newBlockFilter` is not available. Though `eth_newPendingTransactionFilter` does seem to work.

```
[WARN] [09-12|01:40:35.966] Served                                   conn=172.23.0.6:48390 method=eth_newBlockFilter reqid=2 t=9.606µs err="the method eth_newBlockFilter does not exist/is not available"
```

#### Steps to reproduce the behaviour

Sync the node, and query the said method via RPC.

**Comment by enriavil1** [comment]
you need to whitelist it through `--rpc.accesslist`

**Comment by bl4ck5un** [comment]
thanks for your reply. Just to clarify --- according to the [doc](https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md#allowing-only-specific-methods-allowlist), allow listing is used when "you might want to only allow certain methods". In my case, I want to enable all methods in the `eth` namespace (with `--http.api=eth`). Should I put all methods in `--rpc.accesslist`, or just `eth_newBlockFilter`.
