### ISSUE TITLE
Missed block proposal because Erigon refused to build the payload

### ISSUE THREAD

**Issue by guzkodes** [ledgerwatch/erigon#5354]
```erigon version 2022.09.1-alpha-4067b7c4```

Erigon was resolving forks (it does that a lot) and printed

```
[WARN] Skipping payload building because forkchoiceState.headBlockHash is not the head of the canonical chain forkChoice.HeadBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000 headHeader.Hash=0x2b4c48870abd6e7dde805bf4b5703cd506b7687057fc987eb4eaccc31e402ee4
```

The validator, Nimbus, could not build the block:

```
getExecutionPayload: newExecutionPayload invalid topics="beacval" executionPayloadStatus=ok(INVALID_BLOCK_HASH)
Unable to get execution payload. Skipping block proposal topics="beacval"
```

And I lost the block proposal 

When looking at my Erigon logs, I see multiple chunks a day of 
```
un ch acc: ba8c2aa61704cc14db988970b227af9a4e9ee5fa, 0, 03020322080be110d2a6eef6f1
un ch acc: bcc84003d99562052570a594927e76e1e568466f, 0, 020729011b1c8ec400
un ch acc: bcd92c3778b456da29ba29db156c4223dfd2dde1, 0, 0302020107826ab3311bbf66
un ch acc: bd2819709cc834d5a1496642b2905bbd24db392f, 0, 0301990801ad2500fb3fb9a3
un ch acc: bd31ea8212119f94a611fa969881cba3ea06fa3d, 1, 0d0101010120857e34d35e463e37286
```

Apparently this makes Erigon unavailable for the beacon chain since it is resolving forks and not read to answers requests, and the reason the damage is not bigger is because the beacon chain doesn't use it much now, but after the Merge it will be a disaster.

See other related issues https://github.com/ledgerwatch/erigon/issues/5316 and https://github.com/ledgerwatch/erigon/issues/5280

What is the reason for this? Network/bandwidth speed is definitely not an issue

**Comment by littleskunk** [comment]
Same problem here in combination with lighthouse. Any chance this is getting fixed any time soon? Or should we better migrate over to besu?

**Comment by guzkodes** [comment]
I think Erigon is a reasonable block attestation tool, but if you are not using archive, better to stick to geth: it uses less disk and memory and actually produces blocks more reliably
