### ISSUE TITLE
Question: The Merge

### ISSUE THREAD

**Issue by breezytm** [ledgerwatch/erigon#5366]
For the merge, can I use my existing devel db or I must switch to alpha and do a full resync? I noticed devel [image](https://hub.docker.com/layers/thorax/erigon/devel/images/sha256-0cc94a8d8a3286605283efcc6387535677295a78e2cd9e0f3994ea36b39aa0d3?context=explore) on docker hub was recently updated.

**Comment by AskAlexSharov** [comment]
devel and alpha are compatible and are fine for TheMerge
