### ISSUE TITLE
Some strange message logs

### ISSUE THREAD

**Issue by vanphandinh** [ledgerwatch/erigon#5367]
There are just a few hours before The Merge. I'm watching the Erigon node logs.
Here are some strange message logs. I want to ask what it is.

![Screen Shot 2022-09-15 at 11 28 20 AM](https://user-images.githubusercontent.com/13887599/190315414-cc668f52-389b-4189-93ec-420d023d24b2.png)
![Screen Shot 2022-09-15 at 11 28 04 AM](https://user-images.githubusercontent.com/13887599/190315377-e6dfe157-8fe0-4e27-bb70-11a2ed3db4e0.png)

**Comment by AskAlexSharov** [comment]
please ignore it.
