### ISSUE TITLE
Unsettled forkchoice after unwind height=xxx

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#5372]
version:2022.09.1-alpha-4067b7c4
![image](https://user-images.githubusercontent.com/65291464/190405756-53d08769-3e5f-490c-b90f-9c5482fd2a30.png)

I have tried restarting the node several times. But the node cannot recover. This problem first appeared  at block  15538049
![image](https://user-images.githubusercontent.com/65291464/190407932-0fe73db5-76da-4b88-b895-97a9a8f56c44.png)

I think I should unwind the earlier block. What should I do？

**Comment by guzkodes** [comment]
Same here. Lost 1h worth of attestations. Restarted and it seems to be moving on. I guess that is why the version is called ```alpha```

**Comment by masayil** [comment]
> Same here. Lost 1h worth of attestations. Restarted and it seems to be moving on. I guess that is why the version is called `alpha`

I have checked the block data after 15538049 and it is correct. But node seems to be stuck in a weird loop

**Comment by enriavil1** [comment]
What is the loop like. Also the log message is expected it is not related to a problem it just means Erigon will begin handling previous forkchoices before continuing to download headers.

**Comment by enriavil1** [comment]
> > Same here. Lost 1h worth of attestations. Restarted and it seems to be moving on. I guess that is why the version is called `alpha`
> 
> I have checked the block data after 15538049 and it is correct. But node seems to be stuck in a weird loop

Could you send the logs please

**Comment by masayil** [comment]
> > > Same here. Lost 1h worth of attestations. Restarted and it seems to be moving on. I guess that is why the version is called `alpha`
> > 
> > 
> > I have checked the block data after 15538049 and it is correct. But node seems to be stuck in a weird loop
> 
> Could you send the logs please



[log.txt](https://github.com/ledgerwatch/erigon/files/9575494/log.txt)

**Comment by masayil** [comment]
CL status:
![image](https://user-images.githubusercontent.com/65291464/190414412-3416c8b5-75dd-4c51-98b7-89d9c4a704dd.png)

**Comment by masayil** [comment]
@enriavil1 
log:
[erigon.txt](https://github.com/ledgerwatch/erigon/files/9576039/erigon.txt)

**Comment by gotzl** [comment]
I think I've the same issue, CL status is similar to the above. In the 
[erigon.log](https://github.com/ledgerwatch/erigon/files/9576068/erigon.log) (UTC timestamps), first 'unusual' msg I can spot is
```
Sep 15 07:18:15 raspberrypi4-64 erigon[100670]: [INFO] [09-15|07:18:15.475] [1/15 Headers] Fork choice missing header with hash b71dc61e7d753b51fc7b717ca4a387b95b890b3fdb4100f85cda70cad33efa8e
```

(Maybe as a side info, I've only upgraded yesterday from 2022.08.03-alpha to 2022.09.01-alpha)

**Comment by enriavil1** [comment]
> @enriavil1
> log:
> [erigon.txt](https://github.com/ledgerwatch/erigon/files/9576039/erigon.txt)

I don't see the problem in the logs your node is syncing.

**Comment by masayil** [comment]
> > @enriavil1
> > log:
> > [erigon.txt](https://github.com/ledgerwatch/erigon/files/9576039/erigon.txt)
> 
> I don't see the problem in the logs your node is syncing.

Maybe I should wait a while to observe the node.Anyway thanks for your help

**Comment by enriavil1** [comment]
No worries does logs just mean that the node is missing those headers, but it will download them I changed a bit the log message in this PR so people don't get confuse about them. It is not actually an error: #5376

**Comment by gotzl** [comment]
@enriavil1 sorry to extend on this, but for me the CL is still not happy .. Maybe you can shed a light on some behavior I don't understand in the log posted by @masayil (I see similar behavior from my node ...)

For instance, I'm wondering about these messages:
```
[INFO] [09-15|22:13:49.098] RPC Daemon notified of new headers       from=15539407 to=15539408 header sending=22.397µs log sending=316ns
...
[INFO] [09-15|22:14:06.575] RPC Daemon notified of new headers       from=15539407 to=15539414 header sending=17.06µs log sending=238ns
...
[INFO] [09-15|22:16:42.364] RPC Daemon notified of new headers       from=15539407 to=15539629 header sending=319.505µs log sending=385ns
[INFO] [09-15|22:16:42.364] [1/15 Headers] Waiting for Beacon Chain... 
[INFO] [09-15|22:16:42.366] [1/15 Headers] Fork choice re-org        headerNumber=15539629 forkingPoint=15539407
[INFO] [09-15|22:16:42.366] UnwindTo                                 block=15539407 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
[INFO] [09-15|22:16:42.366] [1/15 Headers] Unsettled forkchoice after unwind height=15539629 forkchoice="&{HeadBlockHash:0x879cc9deb81eb1bd5bd56ac9ca3a9d072698deae66ddef4aeb76036cf46b6819 SafeBlockHash:0x7b5dca6f38c02bed3088d422679fb18fe53cc6a77c216ab6b9a3e98ca0cc95db FinalizedBlockHash:0xcdf9ed89b0c43cda17398dc4da9cfc505e5ccd19f7c39e3b43474180f1051e01}"
[INFO] [09-15|22:16:42.373] [4/15 Bodies] Processing bodies...       from=15539407 to=15539629
[INFO] [09-15|22:16:49.656] [4/15 Bodies] Processed                  highest=15539629
[INFO] [09-15|22:16:49.656] [5/15 Senders] Started                   from=15539407 to=15539629
[INFO] [09-15|22:16:50.119] [6/15 Execution] Blocks execution        from=15539407 to=15539629
```

Is it OK that the 'from' block in the 'RPC Daemon notified of new headers' message doesn't change?

Do I understand correctly, that due to the 'Fork choice re-org', the blocks executed in between 22:13:49.098 and 22:16:42.364, eg
```
[INFO] [09-15|22:14:47.095] [5/7 Execution] Blocks execution         from=15539407 to=15539424
[INFO] [09-15|22:14:48.104] [5/7 Execution] Completed on             block=15539424
```
are downloaded (?) and executed again?

**Comment by enriavil1** [comment]
That's all alright. I just changed the logs so it does not look like an error. But you are essensitially downloading a new block that is in blockNum=X with a different hash.

**Comment by enriavil1** [comment]
If you want to know more about it look up things related eth2.0 `forkChoiceUpdateV1`
