### ISSUE TITLE
About eth2.0

### ISSUE THREAD

**Issue by kledgold** [ledgerwatch/erigon#5373]
Hello, the current erigon version can only be synchronized to a height of 15537418. Is it because of the merger of ETH2.0? How can I use erigon to synchronize eth2.0 data?

**Comment by enriavil1** [comment]
you need to connect erigon to a consensus layer client aka a CL. The three that you can use are: Nimbus, Nethermind, and Prysm

**Comment by winmax0208** [comment]
Hi bro ! Not lighthouse compatible?  do I cpoy the file jwt.hex from erigon to the CL client? My CL client is not on the same server as erigon

**Comment by winmax0208** [comment]
> 

thanks
