### ISSUE TITLE
trace_* results are inconsistent with debug_* calls on some Post merge blocks 

### ISSUE THREAD

**Issue by panghalamit** [ledgerwatch/erigon#5377]
#### System information

Erigon version: `./erigon --version`
2022.09.01

OS & Version: Windows/Linux/OSX
Linux

Commit hash :  4067b7c4da6c5d741d3027d95ae2afdf6b7a943a

#### Expected behaviour
Expect debug_* and trace_* to return same value transfers . 

#### Actual behaviour
For example following transaction 
https://etherscan.io/tx/0xebd54184b7198eda06aa83af64d8afb9acfd215c5b5e79208b9bdc54bbd8b303

internal tx from `trace_*` has different receiver address than that of `debug_*`  

`trace_transaction` response 

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "action": {
                "from": "0x6d29c41c0abff0cf2b384d0602d25856ca5d8fa0",
                "callType": "call",
                "gas": "0x13184",
                "input": "0x0f2c93290000000000000000000000001400851fd74458160e43f47e316c9060ece09ba300000000000000000000000079a07e8bdfc90fb442d73106968ce16c0cbefdd4",
                "to": "0x316923d43be091fe0ba213ae602a7e21eca54ece",
                "value": "0x16345785d8a0000"
            },
            "blockHash": "0xd264f748c518244933b8d0e6f538cfe7e43b17af992e32a1ec81af0cdba4ad38",
            "blockNumber": 15538763,
            "result": {
                "gasUsed": "0x886c",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
            },
            "subtraces": 1,
            "traceAddress": [],
            "transactionHash": "0xebd54184b7198eda06aa83af64d8afb9acfd215c5b5e79208b9bdc54bbd8b303",
            "transactionPosition": 91,
            "type": "call"
        },
        {
            "action": {
                "from": "0x316923d43be091fe0ba213ae602a7e21eca54ece",
                "callType": "call",
                "gas": "0xa747",
                "input": "0x",
                "to": "0x79a07e8bdfc90fb442d73106968ce16c0cbefdd4",
                "value": "0x16345785d8a0000"
            },
            "blockHash": "0xd264f748c518244933b8d0e6f538cfe7e43b17af992e32a1ec81af0cdba4ad38",
            "blockNumber": 15538763,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [
                0
            ],
            "transactionHash": "0xebd54184b7198eda06aa83af64d8afb9acfd215c5b5e79208b9bdc54bbd8b303",
            "transactionPosition": 91,
            "type": "call"
        }
    ]
}
```

`debug_traceTransaction` response

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "type": "CALL",
        "from": "0x6d29c41c0abff0cf2b384d0602d25856ca5d8fa0",
        "to": "0x316923d43be091fe0ba213ae602a7e21eca54ece",
        "value": "0x16345785d8a0000",
        "gas": "0x13184",
        "gasUsed": "0x8876",
        "input": "0x0f2c93290000000000000000000000001400851fd74458160e43f47e316c9060ece09ba300000000000000000000000079a07e8bdfc90fb442d73106968ce16c0cbefdd4",
        "output": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "time": "1.980004ms",
        "calls": [
            {
                "type": "CALL",
                "from": "0x316923d43be091fe0ba213ae602a7e21eca54ece",
                "to": "0x1400851fd74458160e43f47e316c9060ece09ba3",
                "value": "0x16345785d8a0000",
                "input": "0x",
                "output": "0x"
            }
        ]
    }
}
```
#### Backtrace

````
[backtrace]
````

**Comment by alexlee85** [comment]
actually they are two different api,  trace_transaction is "**parity trace api**", debug_traceTransaction is "**go-ethereum debug api**".  so there's nothing wrong with this.

**Comment by panghalamit** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/5402

**Comment by PPianAIC** [comment]
@panghalamit Can you tell me how your erigon node runs, because there is a problem with debug_traceTransaction, it always has a error of nonce too low.
thanks!!!
example:
> curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_traceTransaction", "params": ["0xe13fc133c17a0322bd1cf45e07d07ce033e63c085ef607fd5385834f0fdeaf44", {"tracer": "callTracer"}], "id":1}' http://127.0.0.1:8454
> {"jsonrpc":"2.0","id":1,"result":nullnull,"error":{"code":-32000,"message":"transaction 7fa6136222f011b1e4f85df64b9e481574a09b8336969de271f2e5cc3a4eb40b failed: nonce too low: address 0x896E642d1bd3E83836adaa051534744004C09afA, tx: 15 state: 21"}}
### System information
> erigon version 2.38.1-stable
### Command
> ./build/bin/erigon --datadir=/data1/ethereum/ethereum/.erigon --chain=mainnet --http --http.port=8454 --http.addr 0.0.0.0 --http.api eth,debug,net,trace,web3,erigon,txpool --ws --externalcl --vmdebug --snap.keepblocks --authrpc.port=8551 --authrpc.addr 0.0.0.0 --authrpc.vhosts localhost --authrpc.jwtsecret /data1/ethereum/ethereum/consensus/prysm/jwt.hex
