### ISSUE TITLE
Method trace_block returns error for block 0xed1d35

### ISSUE THREAD

**Issue by artstar** [ledgerwatch/erigon#5380]
#### System information

Erigon version: 2022.09.1-alpha-4067b7c4

OS & Version: Ubuntu 18.04

#### Actual behaviour

Request: 
curl --data '{"method":"trace_block","params":["0xed1d35"],"id": 1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <url>

Response
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216"}}

**Comment by nining** [comment]
I have the same issue with the server log:
`[WARN] [09-16|00:37:59.719] Served                                   conn=127.0.0.1:59994 method=trace_block reqid=4 t=165.086394ms err="first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216"
`

**Comment by nining** [comment]
> What chain is this

ethereum mainnet after the merge.

**Comment by dsoldatow** [comment]
After block 15540506
{'method': 'trace_block', 'params': ['0xed211a'], 'jsonrpc': '2.0', 'id': 1}
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"parse error"}}

**Comment by Rob-Petri** [comment]
I am experiencing the same issue.   Is this being looked into?

**Comment by cwelton** [comment]
Seeing this issue across three different node providers all running Erigon

**Comment by darklow** [comment]
Can confirm same error on same block 15539509 on all our mainnet Erigon nodes running `v2022.09.01`:

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "trace_block", "params": [15539509], "id":1}' http://IP:8545/`

Response:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216"}}`

**Comment by alexlee85** [comment]
same issue here.

**Comment by penglipeng666** [comment]
me too, I hope it's over soon**!!!**

**Comment by penglipeng666** [comment]
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216"
    }
}

**Comment by MrN1x0n** [comment]
same problem. 

`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216"}}
`

**Comment by luarx** [comment]
> Seeing this issue across three different node providers all running Erigon

@cwelton btw, could you share which node providers use Erigon? I am interested to use some

**Comment by CaiJiJi** [comment]
same problem :(

**Comment by Serhy** [comment]
JFY, I checked each block (iterated `{"method":"trace_block","params":["{block_number}"],"id": 1,"jsonrpc":"2.0"}`) and it's only 15539509th one which returns the error from description.

**Comment by alexlee85** [comment]
this problem already be fixed, should close it.
