### ISSUE TITLE
Excessively noisy warning logs for "trace_get not available"

### ISSUE THREAD

**Issue by stoooops** [ledgerwatch/erigon#5383]
#### System information

Erigon version: `erigon version 2022.08.3-alpha-0c64c3f2`

OS & Version: Linux

Commit hash : 0c64c3f2c795da998c539c059edbc5544d03bb7b

#### Expected behaviour
Logs are usable for human

#### Actual behaviour
The same warning log is repeated inifinitely. Has been running now for 18 hours straight.

There is obviously no such endpoint, so I have no idea why it is checking every single port for something that doesn't exist and telling me it doesn't exist 50,000 times.

![image](https://user-images.githubusercontent.com/3518037/190512058-ce74b14c-9b64-4c66-8ba6-95116d81a59d.png)

#### Steps to reproduce the behaviour
I was trying to prune so I started with `--prune` parameter which apparently set some state which means I can never change the prune parameter again.

So to repair this, I deleted my `chaindata` folder and update the `prune` parameters as seen in the command.

I don't know what ultimately started this behavior or how to fix it.

`sudo -u erigon ./build/bin/erigon --datadir ~erigon/.ethereum/erigon --http.api web3,eth,erigon,net,txpool --prune.h.before 10000000 --prune.r.before 10000000 --prune.t.before 10000000 --prune.c.before 10000000`

**Comment by stoooops** [comment]
When I add the `trace` flag to `http.api` and restart, I get a different infinitely repeating log:
![image](https://user-images.githubusercontent.com/3518037/190515495-1b381573-e2f4-47df-a25d-dcafec4cae10.png)

I think in general whatever code pattern is looping 50,000 times and logging warnings needs to be revisited. You can still check all the ports (if that's correct behavior) without destroying log readability.

**Comment by Texnomic** [comment]
The log message seems coming from wrong `JSON-RPC` request time. Are you sure that no other software is connected and generating such wrong `trace_get` method ?
