### ISSUE TITLE
Stuck with `Staged Sync err="[1/15 Headers] BuildMissedIndices: TransactionsIdx: at=15410000-15420000, expect: 1721282, got 1721281`

### ISSUE THREAD

**Issue by mizu-eth** [ledgerwatch/erigon#5384]
#### System information

Erigon version: 2022.09.1-alpha-4067b7c4

OS & Version: Linux

Commit hash : 4067b7c4

#### Actual behaviour

I left a comment on closed issue #5138 but I'm not sure if anyone will see it so I hope you don't mind me creating a separate issue. I'll copy and expand on it below.

I'm having the same problem as https://github.com/ledgerwatch/erigon/issues/5138#issuecomment-1229506636. This happened very soon after the merge by the way. My problem is that it's happening with generated snapshots and not downloaded snapshots, so I can't just remove and redownload them:

```
Staged Sync err="[1/15 Headers] BuildMissedIndices: TransactionsIdx: at=15410000-15420000, expect: 1721282, got 1721281, [block_snapshots.go:1537 panic.go:844 block_snapshots.go:1560 block_snapshots.go:760 block_snapshots.go:801 asm_amd64.s:1571]"
```

Any way I can fix this without resyncing from scratch? For instance, could I download those snapshot files from someone who already has them or just disable snapshots entirely?

I'm also kind of curious as to how that data could have gotten corrupted. Any idea? I did shut Erigon down before this started happening but it was a graceful shutdown (not a sigkill). The reason I shut it down was that I was getting the following output about 100 times per second:

```
[INFO] [09-15|07:45:24.743] [1/15 Headers] Waiting for Beacon Chain... 
[INFO] [09-15|07:45:24.743] [1/15 Headers] Fork choice missing header with hash 851d606639505502fc6a8e8b8177bdcf1549338ad98ab35f1d47560f2eb7cf5f 
[INFO] [09-15|07:45:24.743] Commit cycle                             in=3.998µs
[INFO] [09-15|07:45:24.743] RPC Daemon notified of new headers       from=15537663 to=15537664 header sending=3.967µs log sending=121ns
[INFO] [09-15|07:45:24.743] [1/15 Headers] Waiting for Beacon Chain... 
[INFO] [09-15|07:45:24.743] [1/15 Headers] Fork choice missing header with hash 851d606639505502fc6a8e8b8177bdcf1549338ad98ab35f1d47560f2eb7cf5f 
[INFO] [09-15|07:45:24.744] Commit cycle                             in=3.276µs
[INFO] [09-15|07:45:24.744] RPC Daemon notified of new headers       from=15537663 to=15537664 header sending=4.829µs log sending=111ns
```

It's when I restarted it that the `BuildMissedIndices` error logs started.

**Comment by watsontandrew** [comment]
I'm seeing a similar issue (same build) at around the same time (shortly after merge taking place). 
A fix that does not involve a resync would be wonderful.

**Comment by Texnomic** [comment]
Not sure if it related to #5382 as I'm experiencing similar issue.

**Comment by watsontandrew** [comment]
> Not sure if it related to #5382 as I'm experiencing similar issue.

Could be. I certainly noticed some `Unexpected header` entries

**Comment by ineron** [comment]
Try the flag --snap.stop it worked for me 
erigon version 2022.09.2-dev-506dac35

**Comment by mizu-eth** [comment]
@ineron That seems to have worked. Thank you so so much!

**Comment by mizu-eth** [comment]
@ineron Actually, although adding --snap.stop did allow Erigon to keep syncing up to close to the current block, my consensus client (lodestar) is now stuck trying to getLogs from Erigon which seem to be unavailable:

```
[WARN] [...] Served                                   conn=... method=eth_getLogs reqid=2 t=10.224289ms err="block not found 15410022"
[INFO] [...] Served                                   conn=... t=13.828979ms method=eth_getLogs reqid=2 params="[{\"fromBlock\":\"0xeb1fe9\",\"toBlock\":\"0xeb23d0\",\"address\":\"0x00000000219ab540356cbb839cbe05303d7705fa\",\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"]}]"
```

This is the error on the CL side:
```
Error: JSON RPC error: block not found 15410022, eth_getLogs
```

**Comment by ineron** [comment]
> @ineron Actually, although adding --snap.stop did allow Erigon to keep syncing up to close to the current block, my consensus client (lodestar) is now stuck trying to getLogs from Erigon which seem to be unavailable:
> 
> ```
> [WARN] [...] Served                                   conn=... method=eth_getLogs reqid=2 t=10.224289ms err="block not found 15410022"
> [INFO] [...] Served                                   conn=... t=13.828979ms method=eth_getLogs reqid=2 params="[{\"fromBlock\":\"0xeb1fe9\",\"toBlock\":\"0xeb23d0\",\"address\":\"0x00000000219ab540356cbb839cbe05303d7705fa\",\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"]}]"
> ```
> 
> This is the error on the CL side:
> 
> ```
> Error: JSON RPC error: block not found 15410022, eth_getLogs
> ```

Do you have the latest version of erigon?

**Comment by mizu-eth** [comment]
> Do you have the latest version of erigon?

Yes, currently running 2022.09.2-stable-38b35e09 and was running 2022.09.01 before that. I wonder if I could just download the v1-015410-015420-*  files from someone (I assume they're generated deterministically?)... But that might be a bit of a stretch.

**Comment by ineron** [comment]
> @ineron Actually, although adding --snap.stop did allow Erigon to keep syncing up to close to the current block, my consensus client (lodestar) is now stuck trying to getLogs from Erigon which seem to be unavailable:
> 
> ```
> [WARN] [...] Served                                   conn=... method=eth_getLogs reqid=2 t=10.224289ms err="block not found 15410022"
> [INFO] [...] Served                                   conn=... t=13.828979ms method=eth_getLogs reqid=2 params="[{\"fromBlock\":\"0xeb1fe9\",\"toBlock\":\"0xeb23d0\",\"address\":\"0x00000000219ab540356cbb839cbe05303d7705fa\",\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"]}]"
> ```
> 
> This is the error on the CL side:
> 
> ```
> Error: JSON RPC error: block not found 15410022, eth_getLogs
> ```

It seems that he swears at the requested block which does not exist yet. It can be if the database is out of sync.

**Comment by mizu-eth** [comment]
I guess I'll have to start syncing from scratch. But it looks like I need a completely unpruned node for my use case anyway lol: #5423.
