### ISSUE TITLE
erigon+lighthouse  error

### ISSUE THREAD

**Issue by kledgold** [ledgerwatch/erigon#5386]
Did you encounter this problem again?
Execute lighthouse and report an error:

Sep 16 03:38:10.379 WARN Execution endpoint is not synced        action: trying fallback, last_seen_block_unix_timestamp: 1663260095, endpoint: http://127.0.0.1:8551/, auth=true, service: deposit_contract_rpc
Sep 16 03:38:10.379 ERRO No synced execution endpoint            advice: ensure you have an execution node configured via --execution-endpoint or if pre-merge, --eth1-endpoints, service: deposit_contract_rpc
Sep 16 03:38:10.379 ERRO Error updating deposit contract cache   error: "All fallbacks errored: http://127.0.0.1:8551/, auth=true => EndpointError(FarBehind)", retry_millis: 60000, service: deposit_contract_rpc

**Comment by lqucool** [comment]
I have encountered this problem.
I run the lighthouse with --reconstruct-historic-states, and the erigon normal synchronization

**Comment by kledgold** [comment]
> I have encountered this problem. I run the lighthouse with --reconstruct-historic-states, and the erigon normal synchronization

Hello, I still get an error after adding this command

**Comment by lqucool** [comment]
I run erigon with the command:
```
./build/bin/erigon --datadir /home/data/mainnet --ethash.dagdir /home/data/thash --private.api.addr=localhost:9090  --authrpc.addr=127.0.0.1  --http=false --override.terminaltotaldifficulty=0xc70d808a128d7380000  --verbosity=3 2>&1 | tee log/erigon.log &
```
run the lighthouse:
```
./lighthouse --network mainnet beacon  --execution-endpoint http://127.0.0.1:8551 --reconstruct-historic-states  --execution-jwt /home/data/mainnet/jwt.hex --datadir ./here
```

after the erigon catch up with the latest block, the lighthouse's error didn't show up.

![image](https://user-images.githubusercontent.com/32100315/190557422-d5223360-546a-460d-a43f-7d740d8ccb6f.png)

**Comment by lqucool** [comment]
> > I have encountered this problem. I run the lighthouse with --reconstruct-historic-states, and the erigon normal synchronization
> 
> Hello, I still get an error after adding this command

This error may be that erigon is too far behind

**Comment by kledgold** [comment]
> > > 我遇到了这个问题。我使用 --reconstruct-historic-states 运行灯塔，并使用 erigon 正常同步
> > 
> > 
> > 你好，添加这个命令后还是报错
> 
> 这个错误可能是 erigon 太后了

Excuse me, is your lighthouse started directly? Are there any pre-operations?

**Comment by lqucool** [comment]
> > > > 我遇到了这个问题。我使用 --reconstruct-historic-states 运行灯塔，并使用 erigon 正常同步
> > > 
> > > 
> > > 你好，添加这个命令后还是报错
> > 
> > 
> > 这个错误可能是 erigon 太后了
> 
> Excuse me, is your lighthouse started directly? Are there any pre-operations?

yeah, start directly, no pre-operations.

**Comment by x3ccd4828** [comment]
any luck with this? I am having the same issue not sure if this is an erigon or lighthouse issue.

**Comment by ehsanhajian** [comment]
same here. please update if you have any workaround.

**Comment by almindor** [comment]
I have the same problem, erigon freshly started ends up at "Waiting for consensus layer...". Lighthouse connects and errors with this same error.

`erigon version 2.28.1-stable-9711af6d`
`Lighthouse v3.2.1-6d5a2b5`

**Comment by ChaosRaleigh** [comment]
@almindor Have you fixed your problem? I am also encountering the same problem and is stuck with 2/16 Waiting For Consensus Layer

**Comment by almindor** [comment]
> @almindor Have you fixed your problem? I am also encountering the same problem and is stuck with 2/16 Waiting For Consensus Layer

No, I'm about to give up on erigon for now.

**Comment by x3ccd4828** [comment]
I had a similar problem when using btrfs. I switched to xfs and I started from scratch. After a week all was good. Not sure if the filesystem is the problem. But worth a shot.

**Comment by almindor** [comment]
> I had a similar problem when using btrfs. I switched to xfs and I started from scratch. After a week all was good. Not sure if the filesystem is the problem. But worth a shot.

I'm using basic ext4, I don't suspect this has anything to do with that.

**Comment by ehsanhajian** [comment]
This is what I did on systemd. First run erigon node then run lighthouse and after a few days, the problem is solved.

**Comment by ehsanhajian** [comment]
> same here. please update if you have any workaround.

This is what I did on systemd. First run erigon node then run lighthouse and after a few days, the problem is solved.

**Comment by almindor** [comment]
> > same here. please update if you have any workaround.
> 
> This is what I did on systemd. First run erigon node then run lighthouse and after a few days, the problem is solved.

I've got mine running for over a week now and lighthouse keeps reporting the same error over and over. Erigon seems to just be stuck on waiting for POS.

**Comment by ChaosRaleigh** [comment]
@almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck.

**Comment by almindor** [comment]
> @almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck. I am using the same version as you for both.

Did lighthouse report 
``` ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
```

though?

**Comment by ChaosRaleigh** [comment]
@almindor Yes I did get that. My apologies, currently I am not on my laptop. However you should also see something like " INFO   Syncing " on your beacon node.

**Comment by luwang920** [comment]
> > @almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck. I am using the same version as you for both.
> 
> Did lighthouse report
> 
> ```
> ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
> ```
> 
> though?

Hi  I got the same issue , did you fix it ? thanks

**Comment by ChaosRaleigh** [comment]
> > > @almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck. I am using the same version as you for both.
> 
> > 
> 
> > Did lighthouse report
> 
> > 
> 
> > ```
> 
> > ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
> 
> > ```
> 
> > 
> 
> > though?
> 
> 
> 
> Hi  I got the same issue , did you fix it ? thanks 

I just waited for my beacon node to finish syncing and then Erigon will start syncing.

**Comment by luwang920** [comment]
> > > > @almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck. I am using the same version as you for both.
> > 
> > 
> > > 
> > 
> > 
> > > Did lighthouse report
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > though?
> > 
> > 
> > Hi  I got the same issue , did you fix it ? thanks
> 
> I just waited for my beacon node to finish syncing and then Erigon will start syncing.

so this error doesn't affect the synchronization ? just waiting for it ...
May I ask another question ? How long the syncing takes?  my est-time is around 1 day , is that too long ? 
8CPU 64Gi RAM
Thanks :)

**Comment by ChaosRaleigh** [comment]
> > > > > @almindor For mine, I just left it for 5 days not bothering it and now I am at 7/16. After checking the logs the beacon node have not synced fully hence Erigon was stuck. I am using the same version as you for both.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Did lighthouse report
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > though?
> 
> > > 
> 
> > > 
> 
> > > Hi  I got the same issue , did you fix it ? thanks
> 
> > 
> 
> > I just waited for my beacon node to finish syncing and then Erigon will start syncing.
> 
> 
> 
> so this error doesn't affect the synchronization ? just waiting for it ...
> 
> May I ask another question ? How long the syncing takes?  my est-time is around 1 day , is that too long ? 
> 
> 8CPU 64Gi RAM
> 
> Thanks :)
> 
> 
> 
> 

Well, it took me 5 days. Yea it does not affect as long as you see that your beacon node is syncing.
