### ISSUE TITLE
Support for dynamically changing --rpc.evmtimeout value

### ISSUE THREAD

**Issue by darinvhs** [ledgerwatch/erigon#5389]
#System Information
erigon version 2022.08.2-alpha-35c4faa1

# Rationale
Q: Why should this feature exist
A: Increase timeout value for eth_call method

Q: What are the use-cases?
A: Give more time to eth_call during transaction

# Implementation
Q: Do you have ideas regarding the implementation of this feature?
A: Yes.
Q: Are you willing to implement this feature?
A: Yes.

**Comment by revitteth** [comment]
Closing issue as PR is merged :)
