### ISSUE TITLE
Empty blocks created with teku CL

### ISSUE THREAD

**Issue by hexoscott** [ledgerwatch/erigon#5430]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash : 

#### Expected behaviour

no empty blocks created

#### Actual behaviour

empty blocks being created

#### Steps to reproduce the behaviour

n/a

#### Backtrace

````
[backtrace]
````

Logs from Ignacio iic | Stakely on discord:
[message1.txt](https://github.com/ledgerwatch/erigon/files/9599500/message1.txt)

[empty_block.log](https://github.com/ledgerwatch/erigon/files/9599495/empty_block.log)

**Comment by iicc1** [comment]
Thanks for opening this issue. We use Web3Signer, Lighthouse VC, Teku BN, and Erigon EC in this setup. These are the versions that we are using, which are the latest stable releases:
```
Erigon version 2022.09.2-stable-38b35e09
Teku version: teku/v22.9.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
Lighthouse/v3.1.0-aa022f4
web3signer/v22.8.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
```

OS: Ubuntu 22.04 LTS

We produce around 40-50 blocks per day with this setup, and only around 10% of these have this issue.

**Comment by hexoscott** [comment]
Great thanks 👍  I think the first step here will be to add in some extra logging.  From an initial investigation it looks like CL is requesting the payload immediately after sending the ForkchoiceUpdated request which causes the block building to stop early with no transactions.  Some more debug logs should confirm/deny this theory and we can go from there 👍

**Comment by hexoscott** [comment]
Hi @iicc1, my PR for increasing the logging has now been merged into devel.  Would it be possible to run your setup with erigon built from devel so we can confirm/deny if the CL is the issue.  Thanks!

**Comment by iicc1** [comment]
Thanks @hexoscott
We would like to test it with a smaller group of validators we have using Docker.
Is this the correct image? https://hub.docker.com/layers/thorax/erigon/devel/images/sha256-2e0482fdd448a8f01e89c5feca99394140bf9da0d25dee5e0fe8b625e6164f91?context=explore
Also, what level of verbosity do you want us to have? We currently use verbosity=4
Thanks

**Comment by hexoscott** [comment]
No problem, verbosity=4 should be good.  It looks like we're still waiting for the docker image to be built for the latest devel.  Will message here when ready.

**Comment by hexoscott** [comment]
Hi @iicc1, the image should be available at `docker pull thorax/erigon:docker_mining_logs`

**Comment by iicc1** [comment]
Thanks for the image, we have just updated it. I will report any empty blocks here

**Comment by rotsen11** [comment]
🥲
  
  
  
  
  
  
  

  
  
>

**Comment by iicc1** [comment]
Empty block detected: https://etherscan.io/block/15582935
Here you can find the logs: https://cdn.discordapp.com/attachments/910855470720372777/1022188066636570695/erigon_log_21092022.log

**Comment by hexoscott** [comment]
Thanks @iicc1, the logs show another issue unrelated to the one I was trying to hunt down 😢 .  Originally I thought the CL was requesting the payload too soon after requesting a block to be built, but these logs show a scenario where we have candidate transactions but then none of them make it through into the block.... so something else entirely but still the same problem with an empty block.

I'll have a look into why this might be happening as well, but please could you continue to monitor for empty blocks and keep sending the logs so I can work on the original hunch as well 😄  thanks!

**Comment by iicc1** [comment]
No problem, I will continue uploading logs here in case of any empty block

**Comment by iicc1** [comment]
New empty block: https://etherscan.io/block/15594635
Logs: [empty_block_23092022.txt](https://github.com/ledgerwatch/erigon/files/9632610/empty_block_23092022.txt)

**Comment by iicc1** [comment]
New empty block: https://etherscan.io/block/15639206
Logs: [erigon_29092022.log](https://github.com/ledgerwatch/erigon/files/9676972/erigon_29092022.log)

**Comment by iicc1** [comment]
New empty block: https://etherscan.io/block/15643708
Logs: [erigon_30092022.log](https://github.com/ledgerwatch/erigon/files/9684163/erigon_30092022.log)

**Comment by iicc1** [comment]
More empty blocks @hexoscott 
https://etherscan.io/block/15656821
Logs: [erigon_15656821.log](https://github.com/ledgerwatch/erigon/files/9692547/erigon_15656821.log)

https://etherscan.io/block/15656336
Logs: [erigon_15656336.log](https://github.com/ledgerwatch/erigon/files/9692548/erigon_15656336.log)

**Comment by iicc1** [comment]
New empty block: https://etherscan.io/block/15663866
Logs: [erigon_15663866.log](https://github.com/ledgerwatch/erigon/files/9693889/erigon_15663866.log)

**Comment by hexoscott** [comment]
So that last log there is really interesting.

First a forkchoice updated message where we build a block on payload 177 for hash 0xd7bec49eea12f35e29d80c72909cd974e07e5de2614ca4b3989a182fa700310a, then nothing after that to request the payload from CL.

Then we get another forkchoice updated where we build payload 178 for the same hash 0xd7bec49eea12f35e29d80c72909cd974e07e5de2614ca4b3989a182fa700310a, but we first receive a false flag for building this and then true immediately afterwards, so we start building but receive a GetPayload request before that even starts within the same 1ms window so we of course finish early and end up with no transactions in the block....

@AskAlexSharov, @AlexeyAkhunov, @mandrigin - How shall we handle this scenario, it looks like a fault in CL from my view, it shouldn't be asking for a payload immediately after requesting one be built or using the same hash in multiple requests.  But then we do have transactions available and I'd imagine Validators want the block to be built correctly... should we perhaps build the block on payload request instead?  Not sure on timeouts or rules around how long we have to build a block though.

**Comment by iicc1** [comment]
Do you want us to upgrade to v2022.10.01 or do you prefer to continue debugging the current version?

**Comment by iicc1** [comment]
Another empty block: https://etherscan.io/block/15681724
Logs: [erigon_15681724.log](https://github.com/ledgerwatch/erigon/files/9715691/erigon_15681724.log)

**Comment by iicc1** [comment]
We had to roll back to `docker_mining_logs` since we were producing many empty blocks. We continued producing empty blocks, almost all the blocks were empty. We had to switch the execution client.
Here you can find some empty block logs:

https://etherscan.io/block/15690692 --> [erigon_15690692.log](https://github.com/ledgerwatch/erigon/files/9729253/erigon_15690692.log)
https://etherscan.io/block/15690667 --> [erigon_15690667.log](https://github.com/ledgerwatch/erigon/files/9729256/erigon_15690667.log)

**Comment by hexoscott** [comment]
Sorry to hear about that @iicc1.  As a heads up I've put in some changes which might help with this, although experimental for now in PR https://github.com/ledgerwatch/erigon/pull/5701

**Comment by hexoscott** [comment]
@iicc1 - this is now in release 2.28.0 if you wanted to give that a try.  I'm going to close the issue down for now, feel free to re-open if this continues to be a problem.
