### ISSUE TITLE
Failed to sync goerli

### ISSUE THREAD

**Issue by ianhe8x** [ledgerwatch/erigon#5434]
#### System information

Erigon version: `./erigon --version` v2022.09.02

OS & Version: Linux

Commit hash : 
tag: v2022.09.02

Launch config:
`build/bin/erigon --downloader.verify --datadir /data/erigon_goerli --prune=disabled --chain=goerli …`

CL:
lighthouse v3.1.0

#### Actual behaviour
[EROR] [09-19|23:59:54.100] Staged Sync                              err="runtime error: invalid memory address or nil pointer dereference, trace: [stageloop.go:136 panic.go:844 panic.go:220 signal_unix.go:818 block.go:1231 stage_finish.go:77 default_stages.go:224 sync.go:352 sync.go:255 stageloop.go:170 stageloop.go:91 asm_amd64.s:1571]"

#### Steps to reproduce the behaviour
It is a fresh node

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
fixed in `devel`
