### ISSUE TITLE
Block Error

### ISSUE THREAD

**Issue by itgav** [ledgerwatch/erigon#5443]
Erigon version: 2022.07.2-alpha-c7a94eee

OS & Version: Windows 11

Commit hash : c7a94eeea05d7c0d569c811399642a7d108d8c82

Attach is an image of erigon running. I'm not exactly sure what it's doing but the behavior of explicitly trying to link batches of blocks is abnormal. When ran all night the terminal reached a point where it quit Erigon after an unscrollable amount of Go routines were posted to the terminal.

Any ideas what to do here?

![Erigon Block Error](https://user-images.githubusercontent.com/94311667/191234247-7f5708a6-0c9d-4352-8df9-588e66c41f28.png)

![Before Quitting Erigon](https://user-images.githubusercontent.com/94311667/191234963-fe9fb49f-726b-42e7-af45-b6a0cb8f50db.png)

**Comment by enriavil1** [comment]
Was there any warning Log?

**Comment by itgav** [comment]
Needed a consensus client... duh.
