### ISSUE TITLE
trace_filter -> first run for txIndex 0 error

### ISSUE THREAD

**Issue by SinErgy84** [ledgerwatch/erigon#5453]
Erigon version: 2022.09.03

OS & Version: Ubuntu 20.04.5 LTS

Actual behaviour:

While using ```trace_filter``` on block 15535003 this results in an error ```first run for txIndex 0 error: nonce too high: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 45174735 state: 45174734```

**Update** Same or similar errors occures also on:

- 15535005: ```first run for txIndex 0 error: nonce too high: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 45174742 state: 45174741```
- 15535019: ```first run for txIndex 0 error: nonce too high: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 45174778 state: 45174777```
- 15535029: ```first run for txIndex 0 error: nonce too high: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 45174822 state: 45174821```
- [...]
- 15535044: ```first run for txIndex 17 error: fee cap less than block base fee: address 0xa6Ae57b1dA8238Cd149bC718c40578E4620b752c, gasFeeCap: 25192850622 baseFee: 28522961378```
- [...]
- 15535048: ```first run for txIndex 37 error: fee cap less than block base fee: address 0xB90688cb809E38986f91377F01150dBb7e6a5986, gasFeeCap: 28170445487 baseFee: 28436614824```
- 15535053: ```first run for txIndex 56 error: nonce too high: address 0x5EB656432b07fB784c0455e58f865BDe2A7fAc82, tx: 57578 state: 57577```

Expected behaviour: 

Normal output like for block 15535002 etc.

**Comment by c0deright** [comment]
The erigon node @SinErgy84 is reporting errors for is running via the following systemd service files:

### erigon.service

```
[Unit]
Description=Ethereum erigon daemon
After=network.target

[Service]
User=erigon
Group=erigon

Type=simple
ExecStart=/home/erigon/erigon-client --http --http.addr 0.0.0.0 --http.api "trace,eth,net,web3" --http.vhosts='*' --maxpeers 30 --verbosity 3 --private.api.addr '' --torrent.download.rate 100mb --prune hrtc --prune.h.older 2300000 --prune.r.older 2300000 --prune.t.older 2300000 --prune.c.older 2300000
StandardOutput=append:/home/erigon/.local/share/erigon/log.txt
KillSignal=SIGINT

Restart=always
PrivateTmp=true
TimeoutStopSec=3600s
TimeoutStartSec=10s
StartLimitInterval=120s
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
```

### prysm.service

```
[Unit]
Description=Ethereum Beacon Chain (prysm)
After=network.target

[Service]
User=erigon
Group=erigon

Type=simple
ExecStart=/home/erigon/prysm-client --datadir=/home/erigon/.prysm --grpc-gateway-port 3500 --rpc-port 4000 --p2p-tcp-port 13000 --p2p-udp-port 12000 --monitoring-port 8080 --execution-endpoint=http://localhost:8551 --jwt-secret=/home/erigon/.local/share/erigon/jwt.hex --log-file=/home/erigon/.prysm/log.txt --block-batch-limit 1024

Restart=always
PrivateTmp=true
TimeoutStopSec=3600s
TimeoutStartSec=10s
StartLimitInterval=120s
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
```

### Symlinks

```
/home/erigon/erigon-client -> erigon-clients/selfcompiled/erigon-2022.09.03
/home/erigon/prysm-client  -> prysm-clients/beacon-chain-v3.1.1-modern-linux-amd64
```

### Logfile

Logfile doesn't mention anything about the trace errors

### Expected behaviour

Using block 15535002:

```
% curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_filter","params":[{"fromBlock":"0xed0B9a","toBlock":"0xed0B9a","fromAddress":["0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8"]}],"id":1,"jsonrpc":"
2.0"}' | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "action": {
        "from": "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
        "callType": "call",
        "gas": "0x37e88",
        "input": "0x",
        "to": "0x8293e9b3e4c534f32084cea01efcb0de697b855e",
        "value": "0x433841ff0c06547"
      },
[..]
```

### Actual behaviour

Using block 15535003:

```
% curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_filter","params":[{"fromBlock":"0xed0B9b","toBlock":"0xed0B9b","fromAddress":["0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8"]}],"id":1,"jsonrpc":"
2.0"}' | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "error": {
        "code": -32000,
        "message": "first run for txIndex 0 error: nonce too high: address 0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8, tx: 45174735 state: 45174734"
      }
    }
  ]
}
```

**Comment by enriavil1** [comment]
If you come from a previous version sync then you will have to run `./build/bin/integration --stage_headers --reset --chain=your-chain --datadir=/your/datadir` to fix this issue

**Comment by c0deright** [comment]
Hi @enriavil1,

thank you for that info, will try. I have some questions:
1. I guess I have to shutdown `erigon` daemon before running the `integration` program, right?
2. How am I (and other users) supposed to know that I have to run this type of migration process to convert/fix the datadir after updating erigon? I didn't see this mentioned in the release notes.

**Comment by manishrjain** [comment]
Getting similar error:

```
$ curl $URL -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_traceTransaction", "params": ["0x893c428fed019404f704cf4d9be977ed9ca01050ed93dccdd6c169422155586f", {"tracer": "callTracer"}], "id":10}' -s | jq
{
  "jsonrpc": "2.0",
  "id": 10,
  "result": null,
  "error": {
    "code": -32000,
    "message": "tracing failed: nonce too low: address 0xFD2605a2bF58fDbB90db1Da55dF61628B47F9e8c, tx: 9 state: 357"
  }
}
```

This was on a brand new Erigon node.

**Comment by AskAlexSharov** [comment]
@manishrjain i think you are nit synced

**Comment by manishrjain** [comment]
@AskAlexSharov It's synced up to 12 million-th block and the query is touching like 5 million-th block. Are you saying it must be fully synced for traces to work?

**Comment by AskAlexSharov** [comment]
@AskAlexSharov Erigon didn't build history indices yet. see https://github.com/ledgerwatch/erigon/blob/devel/eth/stagedsync/README.md
also see `make integration` `./build/bin/integration pritn_stages`
also see rpc method `eth_syncing`
