### ISSUE TITLE
Optimize PoS downloader

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#5456]
Currently the Proof-of-Stake downloader (`StartPoSDownloader`, `requestMoreHeadersForPOS`, `ProcessHeadersPOS`, etc in `turbo/stages/headerdownload/header_algos.go`) is too simplistic: it only downloads from one peer at a time, thus making Erigon susceptible to slow or bad peers. That might be a problem during the initial sync, but especially afterwards, at the tip of the chain, CL can occasionally tell Erigon to switch to a side fork with some missing ancestors, and in that scenario the latency of the downloader is crucial.

For example, here's the log of an Erigon instance run by gateway.fm, with a few "[Downloader] Timeout", leading to erigon failing behind the tip of the chain:
[alloc_logs_erigon.stderr.0.w.log](https://github.com/ledgerwatch/erigon/files/9617406/alloc_logs_erigon.stderr.0.w.log)

A few things can be made to improve the PoS downloader, namely:
- Simultaneous downloading from multiple peers;
- Better penalization of bad or slow peers;
- Tweaking the number of attempts & timeout threshold.

**Comment by revitteth** [comment]
Code changes here: https://github.com/ledgerwatch/erigon/pull/5948
