### ISSUE TITLE
stucked at 15537419

### ISSUE THREAD

**Issue by lxl-CSlearner** [ledgerwatch/erigon#5472]
my syn process always has be killed, then I updated to version `erigon/v2022.09.3-dev-fb0f811f/linux-amd64/go1.18.1`, now it is always stucked at 15537419, It seems be stucked at stage 2 like this.
![image](https://user-images.githubusercontent.com/61180702/191713834-523b09d1-83bb-43ad-aad8-4d2942465f89.png)
I acctually dont know what is consensus layer , and i never configured it on the old version.
this is my start flags
`./build/bin/erigon --datadir ../eth_data --private.api.addr 127.0.0.1:10000 --port 30313 --metrics`
Thank you for your patient answer.

**Comment by AskAlexSharov** [comment]
after TheMerge - having Consensus Client is required for mainnet:
https://ethereum.org/en/upgrades/get-involved/#clients
https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients
https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/#consensus-clients
