### ISSUE TITLE
start v2022.09.03 catch panic - err="interface conversion: interface {} is int, not string"

### ISSUE THREAD

**Issue by Maboperu** [ledgerwatch/erigon#5489]
System information

Erigon version: 2022.09.03

OS & Version: Windows Server 2022

Expected behaviour

-> Erigon starts without catch panic 

Actual behaviour

-> Erigon starts with panic and cannot initiate further steps

Start with Powershell:

INFO[09-23|12:58:54.409] Build info                               git_branch=alpha git_tag=v2022.09.03 git_commit=32bd69e5316050005e34448ec6b0165f97173d50
EROR[09-23|12:58:54.436] catch panic                              err="interface conversion: interface {} is int, not string" stack="[main.go:30 panic.go:884 iface.go:262 main.go:110 main.go:51 app.go:526 app.go:286 main.go:35 proc.go:250 asm_amd64.s:1594]"

Im looking forward to answers.

Thank you.

**Comment by enriavil1** [comment]
what is your erigon command

**Comment by enriavil1** [comment]
I believe you set up your config file wrong if so this PR is allowing values to be other than string #5491

**Comment by Maboperu** [comment]
My commands:

Powershell Script to start erigon with config file:

D:\erigon\build\bin\erigon.exe --config=D:\config\er.yaml

and here are my yaml config:

chain : mainnet
port : 30303
private.api.addr : 127.0.0.1:9090
ws : true

prune : htc
prune.r.before : 11052984

datadir : D:\eth1chain
ethash.dagdir : D:\eth1chain\erigon-thash

snapshots : false 

http : true 
http.port : 8545

authrpc.port : 8551
authrpc.jwtsecret : D:\jwt\jwt.hex

Thank you

**Comment by enriavil1** [comment]
tokay I have changed it so it should work

**Comment by enriavil1** [comment]
try out my branch

**Comment by Maboperu** [comment]
I try your branch and it works with my config file - Thank you :-)

**Comment by enriavil1** [comment]
No problem

**Comment by Maboperu** [comment]
upgrade is merged
