### ISSUE TITLE
Max 2 Workers on Snapshot Indexing?

### ISSUE THREAD

**Issue by jacobpake** [ledgerwatch/erigon#5496]
Currently when indexing downloaded snapshots we use max 2 workers. Is it unsafe to increase this?

https://github.com/ledgerwatch/erigon/blob/622d355f5ae5f3a84cc51667e00c5a935932ab9e/eth/stagedsync/stage_snapshots.go#L121

**Comment by AskAlexSharov** [comment]
It's safe, just nobody worked on it yet. not very clear how much RAM it using.

**Comment by revitteth** [comment]
Question seems answered, let's close :)
