### ISSUE TITLE
Accidentally deleted mdbx.dat file

### ISSUE THREAD

**Issue by PolarSyncZ** [ledgerwatch/erigon#5508]
Hello,
I accidentally deleted the .dat file in txpools and now the client just sits when started at txpool started and queues pending txs but does not initialize. Will it eventually rebuild this file? I can see a new one has appeared at /erigon-data/txpool/mdbx.dat.

If not, is there somewhere I can get a copy of an updated txpool .dat file? I just need the completed file and everything should work but am unsure if it will rebuild on its own and how long that might take...thank for any help!

**Comment by wmitsuda** [comment]
You can delete the entire txpool dir and it'll be recreated.
