### ISSUE TITLE
ERIGON STUCK AT SNAPSHOT [1/16]

### ISSUE THREAD

**Issue by darshildarji** [ledgerwatch/erigon#5542]
ERGION VERSION: 20022.9.3

Beacon node fully synced

erigon logs

Sep 27 08:22:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:00.960] [txpool] stat                            block=15537419 pending=3552 baseFee=30000 queued=30000 alloc=414.3MB sys=659.5MB
Sep 27 08:22:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:00.989] [1/16 Snapshots] download                progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=7m0s download=0B/s upload=0B/s
Sep 27 08:22:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:00.989] [1/16 Snapshots] download                peers=2 connections=5 files=123 alloc=415.0MB sys=659.5MB
Sep 27 08:22:10 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:10.976] Served                                   conn=10.1.0.58:6866 method=eth_accounts reqid=59 t=28.951µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:14 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:14.949] Served                                   conn=10.1.0.58:1798 method=eth_accounts reqid=29 t=24.27µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:20 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:20.990] [1/16 Snapshots] download                progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=7m20s download=0B/s upload=0B/s
Sep 27 08:22:20 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:20.990] [1/16 Snapshots] download                peers=2 connections=5 files=123 alloc=464.6MB sys=659.5MB
Sep 27 08:22:23 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:23.052] Served                                   conn=10.1.0.58:31201 method=eth_accounts reqid=63 t=22.39µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:35 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:35.126] Served                                   conn=10.1.0.58:2618 method=eth_accounts reqid=11 t=24.791µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:36 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:36.263] Served                                   conn=10.1.0.58:43361 method=eth_accounts reqid=7 t=22.32µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:40 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:40.990] [1/16 Snapshots] download                progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=7m40s download=0B/s upload=0B/s
Sep 27 08:22:40 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:22:40.990] [1/16 Snapshots] download                peers=2 connections=6 files=123 alloc=524.5MB sys=659.5MB
Sep 27 08:22:47 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:47.205] Served                                   conn=10.1.0.58:18500 method=eth_accounts reqid=0 t=23.921µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:57 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:57.573] Served                                   conn=10.1.0.58:14207 method=eth_accounts reqid=2 t=25.4µs err="the method has been deprecated: eth_accounts"
Sep 27 08:22:59 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:22:59.275] Served                                   conn=10.1.0.58:44083 method=eth_accounts reqid=87 t=25.931µs err="the method has been deprecated: eth_accounts"
Sep 27 08:23:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:00.609] [p2p] GoodPeers                          eth66=14
Sep 27 08:23:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:00.969] [txpool] stat                            block=15537419 pending=3552 baseFee=30000 queued=30000 alloc=357.6MB sys=663.5MB
Sep 27 08:23:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:00.989] [1/16 Snapshots] download                progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=8m0s download=0B/s upload=0B/s
Sep 27 08:23:00 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:00.989] [1/16 Snapshots] download                peers=2 connections=6 files=123 alloc=359.6MB sys=663.5MB
Sep 27 08:23:11 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:23:11.349] Served                                   conn=10.1.0.58:39869 method=eth_accounts reqid=77 t=20.961µs err="the method has been deprecated: eth_accounts"
Sep 27 08:23:18 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:23:18.896] Served                                   conn=10.1.0.58:2053 method=eth_accounts reqid=16 t=22.51µs err="the method has been deprecated: eth_accounts"
Sep 27 08:23:20 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:20.990] [1/16 Snapshots] download                progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=8m20s download=0B/s upload=0B/s
Sep 27 08:23:20 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:20.990] [1/16 Snapshots] download                peers=2 connections=6 files=123 alloc=495.0MB sys=663.5MB
Sep 27 08:23:23 ip-10-1-3-78 erigon[302342]: [WARN] [09-27|08:23:23.427] Served                                   conn=10.1.0.58:16841 method=eth_accounts reqid=93 t=21.89µs err="the method has been deprecated: eth_accounts"

**Comment by darshildarji** [comment]
stuck at:

"Sep 27 08:23:20 ip-10-1-3-78 erigon[302342]: [INFO] [09-27|08:23:20.990] [1/16 Snapshots] download progress="54.64% 234.2GB/428.7GB" download-time-left=999hrs:99m:99s total-download-time=8m20s download=0B/s upload=0B/s"

**Comment by undiabler** [comment]
`download=0B/s upload=0B/s` you are not downloading anything
Check your internet availability. You can be blocked from connecting to new peers.
As you can see this number is way to low `download peers=2`

**Comment by AskAlexSharov** [comment]
- restart erigon
- check that --torrent.port is open for TCP and UDP on firewall

**Comment by itgav** [comment]
I had the same issue. Whenever it occurred, I would restart Erigon and that worked. However, it's also mentioned in #7753 where the respondents seem to conclude that it might be caused by the flags used.
