### ISSUE TITLE
Add flag on rpcdaemon for not limiting feecap

### ISSUE THREAD

**Issue by raulmonge** [ledgerwatch/erigon#5619]
Tried to send a tx with high gas fee and got this error.

![Error image](https://i.imgur.com/ytwAdG1.png)

I saw there is a `rpc.txfeecap` flag on erigon config flags but not in the rpcdaemon flags, when I try to implement it with on the exec command

`ExecStart=/user/erigon/build/bin/rpcdaemon --datadir=/user/.local/share/erigon --txpool.api.addr=localhost:9090 --private.api.addr=localhost:9090 --http.addr=0.0.0.0 --http.api=eth,erigon,web3,net,debug,trace,txpool --ws --rpc.txfeecap=0`

It returns this error
`[EROR] [10-04|17:50:13.688] unknown flag: --rpc.txfeecap`

**Comment by AskAlexSharov** [comment]
@MysticRyuujin because it’s option of txpool, and rpcdaemon doesn’t have txpool inside.  txpool or inside erigon or independent process.
