### ISSUE TITLE
StagedSync: prune between blocks

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5627]
Change stagedsync logic (on tip of chain):
- open write transaction
- run forward stages
- commit 
- send notifications about new block arrived (to RPCDaemon, etc...)
- run prune stages in new write transaction

Current logic: run forward and prune stages in 1 write transaction

Pros: more predictable block-processing time, send notifications earlier

**Comment by AskAlexSharov** [comment]
Keep it

**Comment by jeromelaurens** [comment]
yes plz keep it 
this is very important to help widespread adoption of erigon vs geth : geth send notifications about new block arrived 1 second before erigon on average

**Comment by AskAlexSharov** [comment]
```
I think on next pattern - on MDBX_DURABLE: 
begin(TxNoSync)
do insert+update work
commit() // no fsync here
send notifications about new data arrival to other apps, they may start reading new data at this time (by new read transactions) 
begin()
do some deletes of old data
commit() // fsync here
```

**Comment by AskAlexSharov** [comment]
Implemented by https://github.com/ledgerwatch/erigon/pull/6222
