### ISSUE TITLE
Tons of Errors after updating to  v2022.10.01

### ISSUE THREAD

**Issue by guzkodes** [ledgerwatch/erigon#5633]
it keeps throwing this errors every second or so:

Oct 05 12:37:48 erigon[1943092]: [EROR] [10-05|12:37:48.418] Failed to derive block receipts fields   hash=0xd250605131c60b23f340175205c0592a95b98ac3b29e34b9614f9cb9c84bf526 number=15437218 err="transaction and senders count mismatch, tx count = 190, senders count = 0" stack="[accessors_chain.go:980 accessors_chain.go:1002 handlers.go:179 sentry_multi_client.go:638 sentry_multi_client.go:714 sentry_multi_client.go:679 sentry_multi_client.go:214 asm_amd64.s:1571]"

**Comment by guzkodes** [comment]
Also started missing most of attestations since upgraded last couple of hours

**Comment by AskAlexSharov** [comment]
1. "integration print_stages"
2. your prune flags

**Comment by guzkodes** [comment]
I restarted both execution layer and consensus layer: errors stop appearing.

**Comment by revitteth** [comment]
If errors are gone, let's close :)
