### ISSUE TITLE
RPC daemon crash loop on v2022.10.01

### ISSUE THREAD

**Issue by mohoff** [ledgerwatch/erigon#5635]
#### System information

Erigon version: `2022.10.01`

#### Expected behaviour

RPC daemon starts as separate process

#### Actual behaviour

Erigon logs are fine but RPC daemon logs show an error loop:

```
[INFO] [10-05|13:38:04.622] DB schemas compatible                    reader=6.0.0 database=6.0.0
[INFO] [10-05|13:38:04.636] Use --snapshots=false
[INFO] [10-05|13:38:04.636] rpc filters: subscribing to Erigon events
[EROR] [10-05|13:38:04.636] Could not connect to DB                  err="create aggregator: ReopenFiles: NewHistory: accounts, NewInvertedIndex: accounts, open /home/erigon/erigon-sepolia-data/snapshots/history: no such file or directory"
```

Restarting the RPC daemon process does not fix it

**Comment by AskAlexSharov** [comment]
1. start erigon once on this datadir
2. or manually create this folder

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/5638
thank you

**Comment by mohoff** [comment]
Thanks. Creating `snapshots/history/` and restarting both processes did it
