### ISSUE TITLE
ethstats broken again

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#5649]
#### System information

Erigon version: `v2022.10.01`

OS & Version: Linux

#### Expected behaviour
Erigon correctly reports stats to ethstats.net

#### Actual behaviour
![image](https://user-images.githubusercontent.com/8877131/194377965-9abf7951-7077-417d-bd0a-f33e7ed0609a.png)

#### Steps to reproduce the behaviour
Run erigon, configure ethstats

#### Backtrace

The only thing I see in the logs is:
````
Failed to retrieve stats server message  err="websocket: close 1006 (abnormal closure): unexpected EOF"
````

I think this is a new problem, my nodes have been on ethstats for a long time, and despite the instability of the ethstats server/website, it used to work.

**Comment by naviocean** [comment]
Get the same issue
