### ISSUE TITLE
Stuck at Merge and No Libmdbx folder

### ISSUE THREAD

**Issue by itgav** [ledgerwatch/erigon#5667]
Erigon version: 2.27.0-dev-ff2e763a

OS & Version: Windows 11

I tried using the `--experimental.lightclient` flag but remain stuck at the merge block (see attached). 
![Stuck at Merge](https://user-images.githubusercontent.com/94311667/194642439-a273a0ff-4fae-4253-81af-08c5babe56ee.png)

I tried to `print_stages` and potentially `--unwind` but am unable to because the there's an error when trying to make the db-tools (see attached) because the "libmdbx" folder is no longer present after the v2022.09.01 tag.... The terminal switched to v2022.09.02 
 in the below picture because I was testing to see where the change took place. The issue is identical in the 2.27.0-dev-ff2e763a version. 
![libmdbx does not exist](https://user-images.githubusercontent.com/94311667/194642867-eec204ec-ab19-4182-9150-18fc7c35c9f3.png)

So two issues, not sure if they're related. How do I successfully merge with the new embedded CL? How do I access/make the db-tools after v2022.09.01?

**Comment by Giulio2002** [comment]
uh, okay I will work on it, I can reproduce as well

**Comment by Giulio2002** [comment]
probably result of my refactorings

**Comment by Giulio2002** [comment]
fixed in #5668, please switch to latest `devel`

**Comment by itgav** [comment]
I downloaded the latest `devel` and am having all the same issues except for the "Genesis time" errors that popped up when running Erigon. Here's what it shows when I print stages: 
![print_stages](https://user-images.githubusercontent.com/94311667/194718064-5ef9d802-ba8a-4500-841a-fb659309a6b8.png)

Does this seem like a Me error? Firewall error? Do I need to unwind a stage? Or is this an issue with the code?

tyty

**Comment by Giulio2002** [comment]
well, try to let it run for a while, I saw you were stuck at stage bodies so you have to complete that before anything happens

**Comment by itgav** [comment]
Working like a charm! Thank you.
