### ISSUE TITLE
segment /path/datadir/snapshots/v1-019000-019500-transactions.seg has too short record

### ISSUE THREAD

**Issue by McSim85** [ledgerwatch/erigon#5691]
#### System information

Erigon version: `./erigon --version`
```
erigon -v
erigon version 2.27.0-stable
```

OS & Version: Ubuntu 20.04.4 LTS

Commit hash :  https://github.com/ledgerwatch/erigon/commit/6d8b304eae78cef7aa3f3eb7ed584559bdfe7dbb

Chain: BSC Mainnet Archive node
`ExecStart=/usr/bin/erigon --metrics --metrics.addr=127.0.0.1 --snapshots=true --chain=bsc --db.pagesize 64kb --datadir=/home/bsc/datadir --ethash.dagdir=/home/bsc/ethash --http --http.addr="0.0.0.0" --http.compression --http.vhosts="*" --http.corsdomain="*" --http.api=eth,debug,net,trace,web3,erigon --ws --ws.compression --rpc.gascap=600000000 --torrent.download.rate=20mb --txpool.disable`

#### Expected behaviour

return transaction data

#### Actual behaviour / Steps to reproduce the behaviour

```
$ curl 127.0.0.1:8545 -d '{"method":"trace_transaction","params":["0xd72d1c9fc54874c8284563626a5d4b7e8d39ad13d91d93c642ac5567b425eb60"],"id":1,"jsonrpc":"2.0"}' -H "content-type: application/json"
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"segment /home/bsc/datadir/snapshots/v1-019000-019500-transactions.seg has too short record: len(buf)=0 \u003c 21"}}
```

#### Backtrace

I see only this message in the logs

````
Oct 10 16:36:31 bsc-erigon-archive-4 erigon[1175409]: [WARN] [10-10|16:36:31.194] Served                                   conn=127.0.0.1:41106 method=trace_transaction reqid=1 t=1.342944ms err="segment /home/bsc/datadir/snapshots/v1-019000-019500-transactions.seg has too short record: len(buf)=0 < 21"
````

**Comment by masayil** [comment]
It works on my bsc nodes

**Comment by masayil** [comment]
```
root@erigon-bsc-0:~/svc/node/snapshots# md5sum v1-019000-019500-transactions.seg
03e65b928777186adddded1d801300dc  v1-019000-019500-transactions.seg
```

**Comment by a26nine** [comment]
@masayil @AskAlexSharov We noticed that the issue occurs when building with go v`1.19.x`. It works fine when built with `1.18.x`. Just in case...
