### ISSUE TITLE
bsc morgan hardfork support

### ISSUE THREAD

**Issue by sjlee1125** [ledgerwatch/erigon#5692]
https://github.com/bnb-chain/bsc/releases/tag/v1.1.16
There will be  bsc hard fork.

Mainnet: The hardfork upgrade named Moran is expected to happen at block height 22,107,423. The current block generation speed forecasts this to occur around 12 Oct. 2022 at 8:00 AM (UTC).

Testnet: The hardfork upgrade expected to happen at block height 23,603,940. The current block generation speed forecasts this to occur around 11 Oct. 2022 at 8:00 AM (UTC).

could erigon support this hardfork?

**Comment by sjlee1125** [comment]
bsc testnet stopped after hardfork.

**Comment by f0rmatting** [comment]
v1.1.16 also stoped for testnet

```shell
curl -X "POST" "https://data-seed-prebsc-1-s1.binance.org:8545/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "id": 12547,
  "method": "web3_clientVersion"
}'
{
  "jsonrpc": "2.0",
  "id": 12547,
  "result": "Geth/v1.1.16-cb131fab/linux-amd64/go1.17.13"
}
```

```shell
curl -X "POST" "https://data-seed-prebsc-1-s1.binance.org:8545/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "id": 12547,
  "method": "eth_blockNumber"
}'

{
  "jsonrpc": "2.0",
  "id": 12547,
  "result": "0x1682ae4"
}
```
