### ISSUE TITLE
FR: output EVM stack and memory states for LOG0-4 operation in tracing

### ISSUE THREAD

**Issue by Yxang** [ledgerwatch/erigon#5699]
# Rationale

Why should this feature exist?

It would make getting emitted event logs possible when making any custom eth call by `trace_call` rpc method with `vmTrace` param. I found a way [from here](https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall) that uses `debug_traceCall` to get event logs, but I failed in erigon, also `debug_traceCall` seems not very usable (I am also having #3494, #5365).

What are the use-cases?

Getting emitted logs for any custom eth call through `trace_call`. A few similar demands: https://github.com/ethereum/go-ethereum/issues/20694, [link](https://ethereum.stackexchange.com/questions/121738/parsing-event-logs-from-vmtrace-in-trace-call)

# Implementation

I already have a simple implementation https://github.com/ledgerwatch/erigon/commit/bef823af9a488bd2028314f779e14c9adda0228c. One of my concern is if this breaks any standard. I didn't find any detailed documentation that describes the behavior of `vmTrace` parameter or this rpc method.

**Comment by quickchase** [comment]
Bump

**Comment by jaxonly** [comment]
That's a good idea. Bump

**Comment by Yxang** [comment]
After v2.33.0 `debug_` methods should be usable to fetch logs by any custom call, closing this issue.

https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall
