### ISSUE TITLE
Can i change db.pagesize

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#5708]
Will modifying this parameter affect the database?

**Comment by AskAlexSharov** [comment]
no. 

- or re-sync
- or create new db with this parameter, then copy all data from old db to new one by `integration mdbx_to_mdbx`

**Comment by academe-01** [comment]
> no.
> 
> * or re-sync
> * or create new db with this parameter, then copy all data from old db to new one by `integration mdbx_to_mdbx`

https://github.com/ledgerwatch/erigon/blob/6d8b304eae78cef7aa3f3eb7ed584559bdfe7dbb/cmd/integration/commands/refetence_db.go#L350

but it does delete new db, without reading pagesize.
Am I wrong?
