### ISSUE TITLE
New issues for erigon version:v2022.10.01、 v2.27.0、 v2.28.0 

### ISSUE THREAD

**Issue by zhy827827** [ledgerwatch/erigon#5709]
CL version: prysm 3.1.1

When I launch the erigon new version，Eth new blocks can be synchronized at first,after a while, will not synchronize the new block.

logs:
[2/16 Headers] Waiting for Consensus Layer.........

This issues does not exist in  erigon-2022.09.03.
How do  upgrade erigon new version ? What configuration needs to be changed?

**Comment by mookim-eth** [comment]
see https://github.com/ledgerwatch/erigon/issues/5569

>After TheMerge - Erigon it's an Execution Layer. Need connect some Consensus Client to Erigon:
https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients

**Comment by zhy827827** [comment]
Yes, i deploymet prysm 3.1.1. 
 this is my config:
beacon/beacon-chain-v3.1.1-linux-amd64 --http-web3provider=http://localhost:8551 --jwt-secret=/data/ethdata/jwt.hex --datadir=/data/beacon/data --p2p-max-peers 100 --min-sync-peers 5

**Comment by zhy827827** [comment]
Synchronize blocks in the first few minutes，The block is then unsynchronized, waiting for CL. I don't know how to solve update new version.
