### ISSUE TITLE
RPC method eth_getLogs crashed: runtime error: index out of range [289] with length 289

### ISSUE THREAD

**Issue by fabwa** [ledgerwatch/erigon#5731]
git_branch=devel git_tag=v2021.10.03-1954-gc28b1d2 git_commit=c28b1d230b19360a839608f3aeda2f52f08222cf

`curl -H "Content-Type: application/json" -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address":[],"fromBlock":"0x1e49500","toBlock":"0x1e49500","topics":[["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0xec3afb067bce33c5a294470ec5b29e6759301cd3928550490c6d48816cdc2f5d"]]}]}'`

> RPC method eth_getLogs crashed: runtime error: index out of range [289] with length 289
> [service.go:217 panic.go:838 panic.go:93 eth_receipts.go:222 value.go:556 value.go:339 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]

**Comment by Zorato** [comment]
We have the same issue for some blocks (i.e. [28581696](https://mumbai.polygonscan.com/block/28581696)) when running Polygon Mumbai archive node (w/o pruning) on v2.28.0.

**Comment by fabwa** [comment]
https://github.com/ledgerwatch/erigon/pull/5739 Fixes it :-) Thanks a lot!
