### ISSUE TITLE
Preindexed snapshots

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#5736]
# Rationale

I think this feature will make speed of node syncing so much. After downloading torrents snapshots of blocks, node make very slow and consumed a lot of memory indexation stage.

# Implementation

I think it's possible to store index snapshots nearby of blocks snapshot and download via torrents too.

**Comment by AskAlexSharov** [comment]
Right now by design every node has different indices. It using random “seed” value. To prevent “unbalance index” attack vector.

**Comment by AskAlexSharov** [comment]
FYI: can change `GOMAXPROCS` evn variable to reduce amount of parallel indexers (and RAM as a result)

**Comment by allada** [comment]
You can also download a pre-indexed one here:
https://github.com/allada/bsc-archive-snapshot
or
https://github.com/allada/eth-archive-snapshot

You can just delete the mdbx file(s) after the sync is done and you'd have just the snapshots + indexes.

**Comment by revitteth** [comment]
Looks like we can close this - if any more questions please ask :)
