### ISSUE TITLE
eliasfano32: optimize search to use jump tables

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5743]
now eliasfano32.Search does use naive implementation: using .get() method
maybe possible first search inside jump table 
and then only search inside 1 cunk
then we will not random-touch many parts in large EliasFano index - it will improve speed and ram usage (less pages touch - less disk reads, less pages in ram)

**Comment by fenghaojiang** [comment]
My implementation is not the best solution. 
Suppose we have MMAP with EliasFano of size: `16 * pageSize`.

1. `count` cost 8 bytes.
2. `maxOffset` cost 8 bytes.
3. `lowestBits` cost 8 bytes (Type uint64 of one).
4.  The first two numbers of jumpBits cost 16 bytes. (Type uint64 of two).
5.  Calculate locations from 4. And get at most two uint64 numbers which cost 16 bytes. (Type uint64 of two at most). 

If the page is only one monotone non-decreasing sequence, it will cost you only 56 bytes leaving the middle calculation aside.

**Comment by fenghaojiang** [comment]
My implementation is not the best solution.
Suppose we have MMAP with EliasFano of size: 16 * pageSize.

1. `count` cost 8 bytes.
2. `maxOffset` cost 8 bytes.
3. `lowestBits` cost 8 bytes (Type uint64 of one).
4.  The first two numbers of jumpBits cost 16 bytes. (Type uint64 of two).
5.  Calculate locations from 4. And get upperbits location. The read specific 2 indice of upperbit at most two uint64 numbers which cost 16 bytes. (Type uint64 of two at most).

If the page is only one monotone non-decreasing sequence, it will cost you only 56 bytes leaving the middle calculation aside.

**Comment by fenghaojiang** [comment]
If the page store more than one monotone non-decreasing sequences, I think the result size would be 56bytes * `sequences size` at most.

**Comment by AskAlexSharov** [comment]
> My implementation is not the best solution. Suppose we have MMAP with EliasFano of size: 16 * pageSize.
> 
> 1. `count` cost 8 bytes.
> 2. `maxOffset` cost 8 bytes.
> 3. `lowestBits` cost 8 bytes (Type uint64 of one).
> 4. The first two numbers of jumpBits cost 16 bytes. (Type uint64 of two).
> 5. Calculate locations from 4. And get upperbits location. The read specific 2 indice of upperbit at most two uint64 numbers which cost 16 bytes. (Type uint64 of two at most).
> 
> If the page is only one monotone non-decreasing sequence, it will cost you only 56 bytes leaving the middle calculation aside.


1,2,3 - all ont the same first page - it's fine
4 - likely also on the first page?
5. touch 2 pages  

so, in worst case - we touch 3 pages - which is good i think
min pageSize is 4Kb, so 56 bytes read is not much different from 560 bytes read as soon as they are co-located.

**Comment by fenghaojiang** [comment]
> > My implementation is not the best solution. Suppose we have MMAP with EliasFano of size: 16 * pageSize.
> > 
> > 1. `count` cost 8 bytes.
> > 2. `maxOffset` cost 8 bytes.
> > 3. `lowestBits` cost 8 bytes (Type uint64 of one).
> > 4. The first two numbers of jumpBits cost 16 bytes. (Type uint64 of two).
> > 5. Calculate locations from 4. And get upperbits location. The read specific 2 indice of upperbit at most two uint64 numbers which cost 16 bytes. (Type uint64 of two at most).
> > 
> > If the page is only one monotone non-decreasing sequence, it will cost you only 56 bytes leaving the middle calculation aside.
> 
> 1,2,3 - all ont the same first page - it's fine 4 - likely also on the first page? 5. touch 2 pages
> 
> so, in worst case - we touch 3 pages - which is good i think min pageSize is 4Kb, so 56 bytes read is not much different from 560 bytes read as soon as they are co-located.

4. It's on the first page. 

Thank you for your explanation.

**Comment by fenghaojiang** [comment]
When I run following test, result bits doesn't match bits in the link. https://www.antoniomallia.it/sorted-integers-compression-with-elias-fano-encoding.html 

Something goes wrong? 

lowerBits:[62 0] upperBits:[264790] ;

convert to binary: 
lowerBits: 111110
upperBits: 1000000101001010110

it does not match results on the page: doesn't match bits in the link. https://www.antoniomallia.it/sorted-integers-compression-with-elias-fano-encoding.html 


`func TestEliasFano(t *testing.T) {
	offsets := []uint64{2, 3, 5, 7, 11, 13, 24}
	count := uint64(len(offsets))
	maxOffset := offsets[0]
	for _, offset := range offsets {
		if offset > maxOffset {
			maxOffset = offset
		}
	}
	ef := NewEliasFano(count, maxOffset)
	for _, offset := range offsets {
		ef.AddOffset(offset)
	}
	ef.Build()
	fmt.Println(fmt.Sprintf("%+v", ef))
}
`

**Comment by fenghaojiang** [comment]
```go
func TestEliasFano(t *testing.T) {
	offsets := []uint64{2, 3, 5, 7, 11, 13, 24}
	count := uint64(len(offsets))
	maxOffset := offsets[0]
	for _, offset := range offsets {
		if offset > maxOffset {
			maxOffset = offset
		}
	}
	ef := NewEliasFano(count, maxOffset)
	for _, offset := range offsets {
		ef.AddOffset(offset)
	}

	ef.Build()
	fmt.Println(fmt.Sprintf("%+v", ef))
}
```

**Comment by fenghaojiang** [comment]
sry for without formating. Here is the code.  

```go
func TestEliasFano(t *testing.T) {
	offsets := []uint64{2, 3, 5, 7, 11, 13, 24}
	count := uint64(len(offsets))
	maxOffset := offsets[0]
	for _, offset := range offsets {
		if offset > maxOffset {
			maxOffset = offset
		}
	}
	ef := NewEliasFano(count, maxOffset)
	for _, offset := range offsets {
		ef.AddOffset(offset)
	}

	ef.Build()
	fmt.Println(fmt.Sprintf("%+v", ef))
}
```

**Comment by AskAlexSharov** [comment]
@fenghaojiang hi. i guess article is wrong. hard to flip bits in mind. 
also I just found next fatal error: https://github.com/ledgerwatch/erigon/issues/5830
