### ISSUE TITLE
Non-conforming error response for missing block with eth_call (and possibly others)

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#5750]
#### System information

v2.28.0 Ethereum

#### Expected behaviour

For missing block

### Geth
`curl 'https://rpc.ankr.com/eth' -H 'Content-Type: application/json' -sd '{"jsonrpc":"2.0","id":0,"method":"eth_call","params":[{"data":"0xeca067ad","from":"0x0000000000000000000000000000000000000000","to":"0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a"},"0xffffff"]}'`

Response:
`{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"header not found"}}`

### Erigon 
`curl 'https://rpc.ankr.com/eth' -H 'Content-Type: application/json' -sd '{"jsonrpc":"2.0","id":0,"method":"eth_call","params":[{"data":"0xeca067ad","from":"0x0000000000000000000000000000000000000000","to":"0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a"},"0xffffff"]}'`

Response:
`{"jsonrpc":"2.0","id":0,"result":"0x"}`

for caching this is an issue, because you wouldn't cache an error response, but you would cache a valid response 
is there any reason why Erigon doesn't conform with the Geth spec here?

**Comment by masayil** [comment]
I tested on my own geth and erigon.this problem does exist

**Comment by PeaStew** [comment]
Not stale, issue continues with 2.30.0

**Comment by PeaStew** [comment]
Not stale unless confirmed as fixed
