### ISSUE TITLE
Add all Gossip to Sentinel

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#5824]
As of now Erigon sentinel implements all gossip related to lightclient, but for a full fledged node we need all of them. here are the specs for all gossip messagges:

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md

https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/p2p-interface.md

https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/p2p-interface.md

You can modify cmd/sentinel_node in order to test your changes.

In order to accomplish this, implementing all CL types under cltypes package will be necessary + generate respective SSZ encoding :)

**Comment by michaelneuder** [comment]
Done with the `beacon_aggregate_and_proof` topic. Doing the remaining topics now.

**Comment by michaelneuder** [comment]
now we are looking at the processing of the packets for the req/resp domain. 

in `cmd/lightclient/rpc/common.go` we have functions to process incoming packets (send them from the sentinel to to actual client: see https://giulioswamp.substack.com/i/76604841/modular-archittecture). In these functions, we call `DecodeAndRead` which is defined in `cmd/lightclient/sentinel/communication/ssz_snappy/stream.go`. 

the logic is as follows:

```
if _, err := r.Read(getPrefixFromResponseType(val)); err != nil {
  return err
}
```

this `getPrefixFromResponseType` is the slightly strange function:

```
func getPrefixFromResponseType(val cltypes.ObjectSSZ) []byte {
	if _, ok := val.(*cltypes.LightClientBootstrap); ok {
		return make([]byte, 7)
	}
	if val.SizeSSZ() <= 16 {
		return []byte{0x08}
	}
	return []byte{0x4a, 0x26, 0xc5, 0x8b, 0xc8, 0x04}
}
```

we need to understand these prefixes.

**Comment by michaelneuder** [comment]
i feel like it would be helpful to have a sample packet of each type to play with to understand what the SSZ encoding is for each of them. 

note that these four functions are part of the lightclient service and they reach use a sentinel client to send a request over the network and get a response: `SendLightClientFinaltyUpdateReqV1, SendLightClientOptimisticUpdateReqV1, SendLightClientBootstrapReqV1, SendLightClientUpdatesReqV1`.

they each call `SendRequest` on the `SentinelServer` (using their sentinel client), which is defined in cmd/lightclient/sentinel/service/service.go. this function doesn't do any processing, just returns the raw bytes: 

```
        respData, foundErrReq, err := s.sentinel.SendRequestRaw(req.Data, req.Topic)
	return &lightrpc.ResponseData{
		Data:  respData,
		Error: foundErrReq,
	}, err
```

to get some sample packets, i need to construct some requests to send to the sentinel server.

**Comment by michaelneuder** [comment]
https://github.com/ledgerwatch/erigon/pull/5878 modifies the test sentinel node we are using to send a request on the `LightClientFinalityUpdateV1` topic. 

Running locally gives the following error:
```
INFO[10-27|00:47:01.126] Sending test request for LightClientFinalityUpdateV1
EROR[10-27|00:47:01.133] rpc error: code = Unknown desc = failed to connect to a random peer err=no peers
```
i might need @Giulio2002 to help me get the right CLI flags to get connected to some peers. my plan is basically to get a test packet for each of the light client req/resp topics and then try to understand the SSZ encoding and why these seemingly random prefixes are present.

**Comment by Giulio2002** [comment]
Oh you need to try over and over, you do get connections immediatelly, it takes time, just let it try for 1-2 minutes, thats enough to get peers

> #5878 modifies the test sentinel node we are using to send a request on the `LightClientFinalityUpdateV1` topic.
> 
> Running locally gives the following error:
> 
> ```
> INFO[10-27|00:47:01.126] Sending test request for LightClientFinalityUpdateV1
> EROR[10-27|00:47:01.133] rpc error: code = Unknown desc = failed to connect to a random peer err=no peers
> ```
> 
> i might need @Giulio2002 to help me get the right CLI flags to get connected to some peers. my plan is basically to get a test packet for each of the light client req/resp topics and then try to understand the SSZ encoding and why these seemingly random prefixes are present.

**Comment by michaelneuder** [comment]
https://github.com/ledgerwatch/erigon/issues/5884 has more context for the issue we are facing

**Comment by michaelneuder** [comment]
this can be closed IMO.

**Comment by Giulio2002** [comment]
done ser
