### ISSUE TITLE
Datadir larger than it should be. 900+ Gb for mainnet non-archive node with prune flags set.

### ISSUE THREAD

**Issue by Petter-s** [ledgerwatch/erigon#5866]
#### System information
Erigon version: `erigon version 2.28.1-dev`
OS: Ubuntu

I'm currently in the process of trying to sync an Ethereum mainnet full node (non-archive) with Erigon. According to the system requirements, this should require about 400 Gb in storage.

However, I am still syncing and my Erigon datadir has already exceeded 900 Gb.  So I'm assuming something is wrong. Before switching to Erigon I used Geth, and with Geth the datadir was about 650 Gb when fully synced.

This is how I run Erigon:

```
erigon \
--chain=mainnet \
--datadir="/media/pett3r/Proj/ETH_mainnet_erigon/" \
--prune=htrc \
--ws \
--authrpc.port=8552
```
As you can see I have the prune flag set. Do I need to have any other config flags set to achieve the 400 Gb datadir? Or are my prune flags set incorrectly?

**Comment by AskAlexSharov** [comment]
Unfortunatelly after TheMerge we can't delete old receipts - because ConsensusLayer does read them. 
We can keep "only useful receipts"(of deposit contract) but it's not implemented yet. And receipts itself are big and store much duplicative data. 
We will work on it in future, but not started yet.
