### ISSUE TITLE
[ETH] Erigon stops syncing blocks and a restart is needed in order to fix it

### ISSUE THREAD

**Issue by adricu** [ledgerwatch/erigon#5871]
#### System information

Erigon version: erigon version 2.28.1-stable-9711af6d

OS & Version: Erigon docker thorax/erigon

#### Expected behaviour
Erigon syncs blocks without problems all the time

#### Actual behaviour
Erigon stops syncing blocks and a restart is needed in order to fix it

#### Steps to reproduce the behaviour
Don't know how to reproduce it as it happens randomly 

Discord related questions:
- https://discord.com/channels/687972960811745322/738982866670714901/1032681804215353436
- https://discord.com/channels/687972960811745322/738982866670714901/1029123460263325767
- https://discord.com/channels/687972960811745322/738982866670714901/1034456817868214272

[Relevant Logs](https://github.com/ledgerwatch/erigon/files/9867475/erigon_mainnet_issue_20_oct_2022.log)

**Comment by adricu** [comment]
Unstability from last days
![image](https://user-images.githubusercontent.com/2545053/198543792-0a208914-8e35-4711-9b64-9b3512a20278.png)

**Comment by marbew** [comment]
updating prysm to 3.1.2 fixed this issue for my erigon setup
