### ISSUE TITLE
Decoding responses on the sentinel for the Req/Resp Domain

### ISSUE THREAD

**Issue by michaelneuder** [ledgerwatch/erigon#5884]
@Giulio2002 and I are trying to understand how to decode packets on the Req/Resp domain. 

Currently, when a packet is received, the prefix is stripped from the front of the slice: [here](https://github.com/ledgerwatch/erigon/blob/d9ff645fbf64c42f71a4f8f2ee038b00fc0a8a11/cmd/lightclient/sentinel/communication/ssz_snappy/stream.go#L162). 

The logic for the amount of bytes to remove from the front of the packet is:
```
	if _, ok := val.(*cltypes.LightClientBootstrap); ok {
		return make([]byte, 7)
	}
	if val.SizeSSZ() <= 16 {
		return make([]byte, 1)
	}
	return make([]byte, 6)
```

or in other words, if it is a LightClietBootstrap message -> remove 7 bytes, if the size of the deserialized object is <=16 bytes -> remove one byte, otherwise -> remove 6 bytes. 

As we are expanding the handlers on the req/resp domain, we would like to better understand how to determine the size of that prefix. 

https://github.com/ledgerwatch/erigon/pull/5878 has a minimal working example of this with a test finality update packet: 

we read the first six bytes:
```
	// Read first six bytes.
	r := bytes.NewReader(fullPacket)
	r.Read(make([]byte, 6))
```

and then we are able to decompress and decode the SSZ encoded object. If we do not trim the first six bytes, we get the following error `unable to decompress data: snappy: corrupt input`. If we do trim the first 6 bytes, then we get the decoded object:

```
decoded object: &{
  AttestedHeader:0xc00015c230 
  FinalizedHeader:0xc00015c2a0 
  FinalityBranch:[[52 99 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [65 101 88 22 4 244 176 47 93 194 65 37 79 221 228 105 165 92 142 193 186 58 67 20 134 241 135 34 122 125 115 57] [172 122 65 185 199 105 189 49 177 241 177 210 33 99 244 214 26 95 84 189 174 224 193 54 236 63 221 184 78 109 127 253] [221 85 168 161 105 38 209 149 105 3 159 122 244 254 178 255 91 77 120 187 125 142 51 120 0 141 50 174 6 219 151 239] [0 85 229 188 59 64 96 194 166 103 55 135 128 213 137 87 28 183 254 10 242 76 181 154 34 69 191 188 199 55 40 100] [95 23 207 224 0 161 38 165 131 206 255 211 250 35 98 251 173 131 104 203 253 249 177 151 226 215 171 138 240 89 169 36]] 
  SyncAggregate:0xc00020e080 
  SignatureSlot:5007072
}
```

**Comment by michaelneuder** [comment]
got a test MetadataV1 object decoded:

```
metadataV1Response = []byte{
		16, 255, 6, 0, 0, 115, 78, 97, 80, 112, 89, 1, 20, 0, 0, 164,
		58, 252, 14, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0,
	}
```

decodes into 

```
&{SeqNumber:11 Attnets:9007199254740992}
```

the first byte of the message is `0x10 = 16` and the message length is 16 bytes, so that works with the https://developers.google.com/protocol-buffers/docs/encoding#varints encoding. I wasn't able to get a MetadataV2 object decoded.

**Comment by michaelneuder** [comment]
OK we needed to do the include the fork digest in the wire format: https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/p2p-interface.md#forkdigest-context. these are a fixed set of four bytes that precede the varint.

using `fork.ComputeForkDigest` we get a fork digest of `[74 38 197 139]`. the first six bytes of our finality update object is:

```
finalityUpdateResponse = []byte{
		74, 38, 197, 139, 200, 4, ...
```

we see that those first four bytes are indeed the digest, so we remove them. then we have to interpret the varint. we get

```
200           4
11001000      00000100 // binary
 1001000       0000100 // trim MSB
 0000100       1001000 // little endian

 00001001001000 = 584 base 10 // concat and interpret
```

584 is the SizeSSZ of `&cltypes.LightClientFinalityUpdate{}`. this all seems correct to me

**Comment by michaelneuder** [comment]
confirming that this works with the other lightclient types: 

for `&cltypes.LightClientOptimisticUpdate{}`. we have a first six bytes of 

```
optimisticUpdateResponse = []byte{
		74, 38, 197, 139, 152, 2
```

going ahead with the varint calculation:


```
152           2
10011000      00000010 // binary
 0011000       0000010 // trim MSB
 0000010       0011000 // little endian

 00000100011000 = 280 base 10 // concat and interpret
```
280 is the SizeSSZ of `&cltypes.LightClientOptimisticUpdate{}`.

**Comment by Giulio2002** [comment]
Good work!

**Comment by michaelneuder** [comment]
The size of the four LightClient types are 

```
type=*cltypes.LightClientFinalityUpdate, sizeSSZ=584
type=*cltypes.LightClientOptimisticUpdate, sizeSSZ=280
type=*cltypes.LightClientBootstrap, sizeSSZ=24896
type=*cltypes.LightClientUpdate, sizeSSZ=25368
```

the code to generate this is:

```
	updateType := &cltypes.LightClientFinalityUpdate{}
	optimisticType := &cltypes.LightClientOptimisticUpdate{}
	bootstrapType := &cltypes.LightClientBootstrap{}
	lightclientType := &cltypes.LightClientUpdate{}
	fmt.Printf("type=%T, sizeSSZ=%d\n", updateType, updateType.SizeSSZ())
	fmt.Printf("type=%T, sizeSSZ=%d\n", optimisticType, optimisticType.SizeSSZ())
	fmt.Printf("type=%T, sizeSSZ=%d\n", bootstrapType, bootstrapType.SizeSSZ())
	fmt.Printf("type=%T, sizeSSZ=%d\n", lightclientType, lightclientType.SizeSSZ())
```

this is just for reference.

**Comment by michaelneuder** [comment]
having a bit of trouble understanding the `BeaconBlocksByRange` response i am getting: 

the request i am sending is

```
         blocksByRangeReq := &cltypes.BeaconBlocksByRangeRequest{
		StartSlot: 5000000, // arbitrary slot (currently at ~5030000)
		Count:     2,       // just need two blocks to verify correctness.
		Step:      1,       // deprecated, must be set to 1.
	}
```
this is just asking for 2 blocks starting at the 5 millionth slot. seems simple enough. we get a non error response, which i saved to `erigon/cmd/sentinel/sentinel/communication/ssz_snappy/beacon_blocks_by_range.txt`. 

in the `stream_test.go` file i am just trying to decode this response using the `TestDecodeLizSSZ`, but am not successful so far. the first four bytes are `0x4a26c58b`, which is the fork digest, so that is all good. the next three bytes are the varint:

```
94            d6            05
10010100      11010110      00000101    // binary
 0010100       1010110       0000101    // trim MSB
 0000101       1010110       0010100    // little endian

 000010110101100010100 = 92948 base 10 // concat and interpret
```

this is a super big response for only supposed to have 2 blocks. i added some logging to `stream.go` to try to understand the decoding, and i confirmed that the varint matches what we expect:

```
*** encoded=92948, bytes count=3, obj size=1076
```

the bytes count indicates that 3 bytes were used in the varint, which also makes sense, but the size of the `&cltypes.SignedBeaconBlockBellatrix{}` is only 1076 bytes, which makes me think the response we are getting is way too big....

looking at the spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#beaconblocksbyrange

```
Request Content:

(
  start_slot: Slot
  count: uint64
  step: uint64 # Deprecated, must be set to 1
)
Response Content:

(
  List[SignedBeaconBlock, MAX_REQUEST_BLOCKS]
)

```

it seems like we have the right request:

```
/*
 * BeaconBlocksByRangeRequest is the request for getting a range of blocks.
 */
type BeaconBlocksByRangeRequest struct {
	StartSlot uint64
	Count     uint64
	Step      uint64 // Deprecated, must be set to 1
}
```

pretty bizarre.

**Comment by michaelneuder** [comment]
https://github.com/ledgerwatch/erigon/pull/5917 has the latest test in `erigon/cmd/sentinel/sentinel/communication/ssz_snappy/stream_test.go` and the request can be sent with `go run erigon/cmd/sentinel/main.go`.

**Comment by michaelneuder** [comment]
i should mention that the error i am seeing now is:
```
    --- FAIL: TestDecodeLizSSZ/beaconBlocksByRangeResponse (0.00s)
        stream_test.go:171:
            	Error Trace:	/Users/michaelneuder/github/erigon/cmd/sentinel/sentinel/communication/ssz_snappy/stream_test.go:171
            	Error:      	Received unexpected error:
            	            	unmarshalling: incorrect offset
```

we hit this error during this logic

```
        sr := snappy.NewReader(r)
	for i := 0; i < int(count); i++ {
		var n int
		raw := make([]byte, objSize)
		if n, err = sr.Read(raw); err != nil {
			return fmt.Errorf("readPacket: %w", err)
		}
		pos += uint64(n)
		fmt.Printf("*** read n bytes=%d, pos=%d\n", n, pos)

		if err := list[i].UnmarshalSSZ(raw); err != nil {
			return fmt.Errorf("unmarshalling: %w", err)
		}
```

we read 1076 bytes into a buffer and then try to unmarshall into a `&cltypes.SignedBeaconBlockBellatrix{}` object and the error is thrown in `UnmarshalSSZ`. for debug purposes i printed the `pos` which is `pos=1083 = 4 + 3+ 1076= prefix + varint length + &cltypes.SignedBeaconBlockBellatrix{}.SizeSSZ()`.

**Comment by michaelneuder** [comment]
some progress: i was able to extract one block from the message using `DecodeListSSZBeaconBlock` in https://github.com/ledgerwatch/erigon/pull/5917.

```
        // See https://beaconcha.in/slot/5000000 for target data.
	// Confirm block contents are correct
	slot := outBlock.Block.Slot
	wantSlot := 5000000
	bn := outBlock.Block.Body.ExecutionPayload.BlockNumber
	wantBn := uint64(15835292)
	pi := outBlock.Block.ProposerIndex
	wantPi := 101643

^^^ this all worked for slot 5000000 block
```

i can't get the second block out though. here is some things to note.

```
1. the size of the raw file is 61539 bytes.

2. when you read the fork digest + the varint, 7 bytes are removed: 
this shows up in the length and size of the reader: len(r)=61532, size(r)=61539

3. the varint encodes a size=92948, which is bigger than the message, which makes sense because the message is compressed and the varint represents the uncompressed message size. 

4. after the sr.Read, we find that 
n bytes read=65536, len(r)=30775, size(r)=61539
a few things to note: 
A) 65536 = 2^16, this makes me think that a hard stop on the number of bytes read in a single `.Read` might be being imposed
B) len(r) = 30775 => 61532-30775 = 30757 bytes of the compressed string were read.
C) 30757 != 65536, which means that the num bytes returned by `sr.Read(raw)` corresponds to the number of uncompressed bytes that are read. 
D) looking at the raw buffer we allocate for sr to write into, exactly 65536 are written to the slice. 
i confirmed this by setting all the values of the raw array to 0xFE and confirming that starting at index n, they take that value  raw[n-1:n+3]=[0 254 254 254]
```

based on this, my theory is that we need to read all of the contents from the snappy reader into the buffer first. and then do the deserialization into the proto objects.

**Comment by michaelneuder** [comment]
ok i figured it out:

confirmed this data with https://beaconcha.in/slot/5000000 and https://beaconcha.in/slot/5000001 

```
*** fork digest=[74 38 197 139]
*** encoded=92948, numBytes=3
*** len(r)=61532, size(r)=61539
*** n bytes read=65536, len(r)=30775, size(r)=61539
*** n2 bytes read=27412, len(r)=19753, size(r)=61539
***

 block 1: slot=5000000, block number=15835292, proposer ind=101643

*** fork digest2=[74 38 197 139]
*** encoded2=38278, numBytes2=3
*** n3 bytes read=38278, len(r)=0, size(r)=61539
***

 block 2: slot=5000001, block number=15835293, proposer ind=5639
```
