### ISSUE TITLE
`latest` block identifier returns null

### ISSUE THREAD

**Issue by iFA88** [ledgerwatch/erigon#5893]
Hey!
RPC call `eth_getBlockByNumber` with parameter `["latest",false]` returns `null` result during syncing which is a very unexpected result.
I'm using `git_branch=HEAD git_tag=v2.28.1 git_commit=9711af6ddf01f1eb96c9dfb7bf33c5d69e6f648a` with bultin rpcdaemon.
Br:
iFA

**Comment by iFA88** [comment]
On this chart the latest block queried in every second and parsed into 5 minute interval. When there are no ticker that means in 5 mins there was no one valid response.
![image](https://user-images.githubusercontent.com/18205395/198705178-4673c039-ba78-4d5a-be5c-6e82ac104b5c.png)

**Comment by enriavil1** [comment]
If you are trying to get latest executed there is a specific parameter for it. After the merge latest will return the latest fork choice head hash not the latest executed

**Comment by iFA88** [comment]
I would like to have the latest finalized block, where a `null` is not an acceptable response :(

**Comment by enriavil1** [comment]
latest executed is essentially latest finalised, or you can use finalised I believe which is the latest finalised head fork hash

**Comment by iFA88** [comment]
According to my best knowledge the execution is just a 7th phase in the process. For me the finalize means that every phase is done and committed into the db.
I'm 100% sure, that this response is invalid because when the latest block is null this means there is no one block which can serve to me.

**Comment by enriavil1** [comment]
What chain is it happening on and is it post merge? Also latest in erigon is the latest executed block until post merge which changes to lates forkchoice head hash

**Comment by iFA88** [comment]
This happens on main net and sometime on sepolia. When my client need to sync many block at once then I got this issue.

**Comment by iFA88** [comment]
Definition: https://github.com/ethereum/execution-apis/blob/main/src/schemas/block.yaml#L101

**Comment by iFA88** [comment]
Little update:
```
root@fsALFA:/opt/logs/nodes/eth# curl --data '{"method":"eth_getBlockByNumber","params":["latest", false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" 10.0.0.3:4004
{"jsonrpc":"2.0","id":1,"result":null}
root@fsALFA:/opt/logs/nodes/eth# curl --data '{"method":"eth_getBlockByNumber","params":["finalized", false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" 10.0.0.3:4004
{"jsonrpc":"2.0","id":1,"result":null}
root@fsALFA:/opt/logs/nodes/eth# curl --data '{"method":"eth_getBlockByNumber","params":["safe", false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" 10.0.0.3:4004
{"jsonrpc":"2.0","id":1,"result":null}
```
At this time on the client:
```
[INFO] [10-31|22:37:09.271] [p2p] GoodPeers                          eth66=101
[INFO] [10-31|22:37:12.824] [txpool] stat                            block=15869803 pending=7996 baseFee=30000 queued=29609 alloc=899.9MB sys=2.9GB
[INFO] [10-31|22:37:20.304] [5/16 Bodies] Downloading block bodies   block_num=15869803 delivery/sec=435.2KB wasted/sec=0B remaining=927 delivered=114 alloc=949.4MB sys=2.9GB
[INFO] [10-31|22:37:31.539] [5/16 Bodies] Writing block bodies       block_num=15869835 remaining=896 alloc=1.0GB sys=2.9GB
[INFO] [10-31|22:37:40.304] [5/16 Bodies] Downloading block bodies   block_num=15869835 delivery/sec=522.6KB wasted/sec=0B remaining=895 delivered=267 alloc=1.1GB sys=2.9GB
[INFO] [10-31|22:38:00.304] [5/16 Bodies] No block bodies to write in this log period block number=15869835 blk/second=0.000
[INFO] [10-31|22:38:12.830] [txpool] stat                            block=15869803 pending=8134 baseFee=30000 queued=30000 alloc=1.3GB sys=2.9GB
[INFO] [10-31|22:38:20.305] [5/16 Bodies] Downloading block bodies   block_num=15869835 delivery/sec=135.4KB wasted/sec=0B remaining=895 delivered=304 alloc=1.4GB sys=2.9GB
[INFO] [10-31|22:38:40.304] [5/16 Bodies] Downloading block bodies   block_num=15869835 delivery/sec=105.8KB wasted/sec=0B remaining=895 delivered=336 alloc=820.0MB sys=2.9GB
[INFO] [10-31|22:39:00.304] [5/16 Bodies] No block bodies to write in this log period block number=15869835 blk/second=0.000
[INFO] [10-31|22:39:09.271] [p2p] GoodPeers                          eth66=101
[INFO] [10-31|22:39:12.825] [txpool] stat                            block=15869803 pending=8364 baseFee=30000 queued=30000 alloc=1.0GB sys=2.9GB
[INFO] [10-31|22:39:20.304] [5/16 Bodies] Downloading block bodies   block_num=15869835 delivery/sec=104.6KB wasted/sec=0B remaining=895 delivered=364 alloc=1.1GB sys=2.9GB
[INFO] [10-31|22:39:20.304] [5/16 Bodies] Processed                  highest=15869835
[INFO] [10-31|22:39:20.304] [5/16 Bodies] DONE                       in=2m20.000824311s
[INFO] [10-31|22:39:20.304] [6/16 Senders] Started                   from=15869803 to=15869835
[INFO] [10-31|22:39:20.399] [7/16 Execution] Blocks execution        from=15869803 to=15869835
[INFO] [10-31|22:39:30.516] [7/16 Execution] Completed on            block=15869835
[INFO] [10-31|22:39:30.516] [8/16 HashState] Promoting plain state   from=15869803 to=15869835
[INFO] [10-31|22:39:30.516] [8/16 HashState] Incremental promotion   from=15869803 to=15869835 codes=true csbucket=AccountChangeSet
[INFO] [10-31|22:39:31.349] [8/16 HashState] Incremental promotion   from=15869803 to=15869835 codes=false csbucket=AccountChangeSet
[INFO] [10-31|22:39:33.408] [8/16 HashState] Incremental promotion   from=15869803 to=15869835 codes=false csbucket=StorageChangeSet
[INFO] [10-31|22:39:36.017] [9/16 IntermediateHashes] Generating intermediate hashes from=15869803 to=15869835
[INFO] [10-31|22:39:48.553] [10/16 CallTraces] Pruned call trace intermediate table from=15779803 to=15779834
[INFO] [10-31|22:40:12.829] [txpool] stat                            block=15869803 pending=8498 baseFee=30000 queued=30000 alloc=1.3GB sys=2.9GB
[INFO] [10-31|22:41:09.271] [p2p] GoodPeers                          eth66=101
```

**Comment by iFA88** [comment]
Bump

**Comment by iFA88** [comment]
Issue is still available with v2.32.0

**Comment by AskAlexSharov** [comment]
Thank you. Hope we will fix it :-)

**Comment by enriavil1** [comment]
Are you using an external CL? I also noticed that unless the block body is written it will always return nil, so those five minutes intervals might be erigon catching up writing block bodies. @iFA88 could you please confirm if it is correct?

**Comment by iFA88** [comment]
@enriavil1 Yes, i'm using prysm. If you wish i can try out the builtin CL for a test.
Eventual i have coded a script which checks `Previously known bad block` and `RPC daemon notified` for block height from log file. When happens it restarts the service. It happens 10-30 times pro day. When i dont do this, then the erigon loops forever without syncing.
I have two servers, one with m2 one with sata ssd where i run erigon mainnet, the issue happens on the sata ssd at most.

**Comment by enriavil1** [comment]
Okay this might be a different issue than I thought it would be. Is the ssd external?

**Comment by iFA88** [comment]
> Okay this might be a different issue than I thought it would be. Is the ssd external?

No, its internal SATA with zfs and compression zle (before was zstd-fast-1). There is 4 samsung evo 870 2tb ssd which is used like raid10.

**Comment by enriavil1** [comment]
Have you tried syncing a new node from scratch and seeing if it works. I been trying to replicate what is happening to you ( I am the tip of Mainnet ) and can't seem to get it to happen
