### ISSUE TITLE
Erigon couldn't catch up with latest block every a few hours

### ISSUE THREAD

**Issue by shijie0** [ledgerwatch/erigon#5915]
#### System information

Erigon version: erigon version 2.28.1-stable

OS & Version: Linux,  Ubuntu 20.04.5 LTS

Consensus client: lighthouse v3.1.2-01e84b7

Start command: 
```bash
/usr/local/bin/erigon --chain=mainnet --port=30303 --http.addr=0.0.0.0 --http.port=8545 --torrent.port=42069 --http --ws --http.api=eth,debug,net,trace,web3,erigon,engine --authrpc.addr=0.0.0.0 --authrpc.jwtsecret=/opt/jwtsecret

/usr/bin/lighthouse --network mainnet beacon_node --http --execution-endpoint=http://10.13.14.124:8551 --execution-jwt=/opt/jwtsecret --datadir /home/ec2-user/lighthouse
```
#### Actual behaviour
Every about 2 hours, erigon will stop syncing and start download Pos headers, then followed by writing block bodies, then followed by "TxLookup pruning, empty block body" this process result in the node far behind sync and causing lighthouse node showing the following errors:
```
Oct 31 09:35:29 ip-10-13-14-55.us-west-2.compute.internal lighthouse[29748]: Oct 31 09:35:29.001 WARN Head is optimistic                      execution_block_hash: 0xe2ad672b78b6af6280964408e9c0e3976947bdfa0670e4e1f28015d1f28c3558, info: chain not fully verified, block and attestation production disabled until execution engine syncs, service: slot_notifier
Oct 31 09:35:29 ip-10-13-14-55.us-west-2.compute.internal lighthouse[29748]: Oct 31 09:35:29.001 INFO Synced                                  slot: 5032075, block: 0x263b…ae86, epoch: 157252, finalized_epoch: 157250, finalized_root: 0x4c11…5d0c, exec_hash: 0xe2ad…3558 (unverified), peers: 21, service: slot_notifier
Oct 31 09:35:36 ip-10-13-14-55.us-west-2.compute.internal lighthouse[29748]: Oct 31 09:35:36.184 INFO New block received                      root: 0xaac3a679e24fa6013d6a8ba1c30553d62df78378c8db539083ac6240cc92d468, slot: 5032076
```

Attached is erigon log when it is not catching up.
[erigon.log](https://github.com/ledgerwatch/erigon/files/9899997/erigon.log)

**Comment by sjlee1125** [comment]
same issue..
In my case Consensus client: prysm 3.1.2

**Comment by PolarSyncZ** [comment]
Any update on this issue? I have the same problem on 2.29 version...it did not happen on previous versions. Once an hour the node slows down when processing snapshots and pruning, then displays the TxLookup pruning, empty block body error. It seems to be slowing down the node significantly and not allowing me to stay synced to the head of the chain on BSC mainnet. Please advise.

**Comment by AskAlexSharov** [comment]
@PolarSyncZ 
"TxLookup pruning" on tip of chain: adding pruning limit in this case by https://github.com/ledgerwatch/erigon/pull/6086
