### ISSUE TITLE
Suspicious disk space leak

### ISSUE THREAD

**Issue by Zorato** [ledgerwatch/erigon#5916]
#### System information

Erigon version: `[maticnetwork 0.0.3](https://github.com/maticnetwork/erigon)`

OS & Version: Ubuntu 22.04

#### Expected behaviour
Erigon bor-mainnet archive occupies ~4.5TB

#### Actual behaviour
Synced, uses ~4.5TB for a few days. Then drains all available space (1.8TB) in hours:

![image](https://user-images.githubusercontent.com/2941327/199008381-a6a15147-da8a-426c-9ebb-17d34f992945.png)

Execution params:
```
/home/blockchain/polygon-mainnet/erigon --chain=bor-mainnet --snapshots=true --datadir=/home/blockchain/polygon-mainnet/chaindata --db.pagesize=16kb --bor.heimdall=https://heimdall.api.matic.network --port=30304 --no-downloader --private.api.addr=127.0.0.1:9090 --torrent.port=42069 --metrics --metrics.port=8695 --metrics.addr=0.0.0.0 --snap.keepblocks=true
```

#### Backtrace

````
[INFO] [10-30|22:38:01.199] Commit cycle                             in=16.983985ms
[INFO] [10-30|22:38:01.199] RPC Daemon notified of new headers       from=35003633 to=35003634 header sending=5.46µs log sending=189ns
[INFO] [10-30|22:38:01.199] [1/16 Headers] Waiting for headers...    from=35003634
[INFO] [10-30|22:38:03.175] [1/16 Headers] Processed                 highest inserted=35003635 age=0
[INFO] [10-30|22:38:03.248] [6/16 Execution] Completed on            block=35003635
[INFO] [10-30|22:38:03.320] [13/16 LogIndex] Running from blocks 35003635 to 35003635 endBlock=35003635
[INFO] [10-30|22:38:03.328] Timings (slower than 50ms)               Headers=1.975s Execution=51ms
[INFO] [10-30|22:38:03.328] Tables                                   PlainState=163.2GB AccountChangeSet=233.5GB StorageChangeSet=516.3GB BlockTransaction=4.7GB TransactionLog=2.3TB FreeList=2.2GB ReclaimableSpace=2.2TB
[EROR] [10-30|22:38:03.336] Staged Sync                              err="mdbx_txn_commit_ex: input/output error"
[EROR] [10-30|22:38:03.350] Failed to recover header sentriesClient  err="mdbx_txn_begin: MDBX_PANIC: Likely because hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: chaindata, trace: [kv_mdbx.go:442 kv_mdbx.go:670 header_algos.go:321 stageloop.go:91 asm_amd64.s:1571]"
````

Any help on `ReclaimableSpace=2.2TB` is highly appreciated!

**Comment by iFA88** [comment]
Hey, do you tried without `snap.keepblocks` ?
What is the reason that you need so high page size? In that case lmdb will allocate very big db. I would like recommend to use filesystem with some compression. 4kb pagesize is enough for 4.2tb db, 8kb would be enough for ~8tb, then 16kb is enough for 16tb, i think that is unnecessary.
(This all is just my personal opinion)

**Comment by AskAlexSharov** [comment]
1. `du -ha datadir` to see where exactly used space
2. `make db-tools` and `./build/bin/mdbx_stat -ef <datadir>/chaindata` to see how much space kept in `GC` column
3. If you see high ReclaimableSpace - it means you did run some too long read transaction on db - so, it can't reclaim old space (until old read transaction finish). Do you run any custom analytics? Do you run any long-running requests? 
4. Only way to force-reclaim space is `./build/bin/mdbx_copy -c`

**Comment by Zorato** [comment]
>do you tried without snap.keepblocks

No. I used snapshot from https://snapshot.polygon.technology/ (to skip initial block execution stage) which says to use `snap.keepblocks=true`. This is also the reason to use 16kb page size - this is the value Polygon team used for sync.

1. du -ha -d1 chaindata/
```
4.0K	chaindata/jwt.hex
12K	chaindata/etl-temp
0	chaindata/LOCK
62G	chaindata/bor
494G	chaindata/snapshots
92M	chaindata/txpool
4.0K	chaindata/nodekey
6.8M	chaindata/nodes
6.0T	chaindata/chaindata
6.6T	chaindata/
```
and chaindata is 
```
6.0T	chaindata/chaindata/mdbx.dat
1004K	chaindata/chaindata/mdbx.lck
```
2. mdbx_stat results
```
Running for chaindata/chaindata/...
Environment Info
  Pagesize: 4096
  Dynamic datafile: 49152..8796093022208 bytes (+2147483648/-4294967296), 12..2147483648 pages (+524288/-1048576)
  Current mapsize: 8796093022208 bytes, 2147483648 pages 
  Current datafile: 6592774799360 bytes, 1609564160 pages
  Last transaction ID: 5239962
  Latter reader transaction ID: 5239962 (0)
  Max readers: 116
  Number of reader slots uses: 1
Garbage Collection
  Pagesize: 4096
  Tree depth: 3
  Branch pages: 62
  Leaf pages: 13458
  Overflow pages: 559873
  Entries: 595484
Page Usage
  Total: 2147483648 100%
  Backed: 1609564160 75.0%
  Allocated: 1609217585 74.9%
  Remained: 538266063 25.1%
  Used: 1039450951 48.4%
  GC: 569766634 26.5%
  Retained: 864 0.0%
  Reclaimable: 569765770 26.5%
  Available: 1108031833 51.6%
Status of Main DB
  Pagesize: 4096
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 2
  Overflow pages: 0
  Entries: 91
  ```
  3. No long-running queries that I'm aware of - our common usage scenario is:
   - run erigon binary with metrics collection via prometheus
   - run rpcdaemon on the same machine to serve RPC requests
   - our app establishes WS connection to rpcdaemon, subscribes to new blocks, sometimes queries eth_getBlockByNumber or other get_block methods (must be quick), on every new block it makes trace block (usually takes lass than a second). Is there any internal rpcdaemon timeout for long queries (i.e. when block tracing takes more than 30 seconds?)
  4. Does it require 2x free space to run (is it going to copy, then reclaim OR reclaim at once), or I can run it on almost full drive (i.e. with a few GBs free disk space)?
  
Thanks for the reply!

**Comment by Zorato** [comment]
Ok, will provide trace if this happens again. Unfortunately I don't have 2x free space, since I could only delete a few tmp files to free a few GB. Will re-sync from the snapshot and keep an eye on it!

**Comment by iFA88** [comment]
@Zorato I would use compressed filesystem for mdbx, like zfs with `compression=zstd-fast-1`.

**Comment by Zorato** [comment]
Thanks, will try!
