### ISSUE TITLE
Trace_call stateDiff parameter returning incorrect response

### ISSUE THREAD

**Issue by billqn** [ledgerwatch/erigon#5933]
Network - Ethereum Mainnet

Erigon version: `./erigon/2.28.1`

OS & Version: linux-amd64

 When calling ```trace_call``` with an extremely large value, passing in the ```stateDiff``` parameter, we expect the response to be ```"insufficient funds for transfer:’``` or similar. 

Instead, the response returns incorrect data. 

Curl command to reproduce:
```
curl -X POST   'localhost:8545'   --header 'Content-Type: application/json'   --data '{"jsonrpc":"2.0","method":"trace_call","params":[{"from":"0xc1f02f43d8c0aede650aecca29a94e9498b30286","to":"0x07bb7a938f4ac7043c3127513a910599ca88ea06", "gas": "0x5208", "gasPrice": "0x21faec1933", "value": "0x1456f22c1aee9000000000000000000000000"},["trace", "stateDiff"],"latest"],"id":1}'|jq
```

Actual Output:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "output": "0x",
    "stateDiff": {
      "0x07bb7a938f4ac7043c3127513a910599ca88ea06": {
        "balance": {
          "*": {
            "from": "0x96c404020e4000",
            "to": "0x1456f22c1aee9000000000096c404020e4000"
          }
        },
        "code": "=",
        "nonce": "=",
        "storage": {}
      },
      "0xc1f02f43d8c0aede650aecca29a94e9498b30286": {
        "balance": "=",
        "code": "=",
        "nonce": {
          "*": {
            "from": "0x67",
            "to": "0x68"
          }
        },
        "storage": {}
      },
      "0xf2f5c73fa04406b1995e397b55c24ab1f3ea726c": {
        "balance": {
          "*": {
            "from": "0x204edb4a833651e1",
            "to": "0x20582c3bfd4c05d9"
          }
        },
        "code": "=",
        "nonce": "=",
        "storage": {}
      }
    },
    "trace": [
      {
        "action": {
          "from": "0xc1f02f43d8c0aede650aecca29a94e9498b30286",
          "callType": "call",
          "gas": "0x0",
          "input": "0x",
          "to": "0x07bb7a938f4ac7043c3127513a910599ca88ea06",
          "value": "0x1456f22c1aee9000000000000000000000000"
        },
        "result": {
          "gasUsed": "0x0",
          "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [],
        "type": "call"
      }
    ],
    "vmTrace": null
  }
}
```
Expected Output (taken from a Nethermind Node):
```
{
"jsonrpc": "2.0",
"error": {
  "code": -32000,
  "message": "insufficient funds for transfer: address 0xc1f02f43d8c0aede650aecca29a94e9498b30286"
},
"id": 1
}
```

**Comment by AlexeyAkhunov** [comment]
This is how Parity/OpenEthereum used to work. In our code we call it "gas bailout", and it specifically prevents failure in such cases. I introduced this in this PR: https://github.com/ledgerwatch/erigon/pull/2485 when trying to make `trace_call` behave the same as OpenEthereum.

Since there is no specification for how `trace_call` has to behave in this case, do we just remove gasBailout in this case? Nethermind is now the "gold standard" ?

**Comment by quickchase** [comment]
Haha 😵‍💫

I guess in my opinion the RPC should be true to the EVM, but perhaps a solution is to allow an override?

Other methods allow for state-overrides, is that even a possibility? Second parameter allowing gasBailout? Is that too complicated?

**Comment by AlexeyAkhunov** [comment]
We have `--trace.compat                   Bug for bug compatibility with OE for trace_ routines` option, which we can use to shift this particular bailout functionality under. If someone still needs strict adherence to OE, this would be the way

**Comment by AlexeyAkhunov** [comment]
The idea of the `gasBailout` is that it allows `trace_call` to be used without caring too much about whether your hypothetical address has enough ETH or not.

**Comment by AlexeyAkhunov** [comment]
I am kind of reluctant to change it, because I do understand why it behaves the way it is, and I am afraid by fixing it, we would get even more bug reports about this change of behaviour. Please state the impact of this issue
