### ISSUE TITLE
curl to eth_getLogs returns nothing when using topics filter

### ISSUE THREAD

**Issue by mahirkarim1** [ledgerwatch/erigon#5942]
#### System information

Erigon version: 2.28.1-stable-9711af6d

OS & Version: Ubuntu 20.04.5 LTS

Commit hash : 

#### Expected behaviour

eth_getLogs with the topics parameter should return logs filtered by the topic. According to #5547 this problem should have been fixed by in v2022.09.02+.

#### Actual behaviour

Command returns
`{"jsonrpc":"2.0","id":1,"result":[]}`

When no topics or address filter is supplied, getLogs works as intended.

#### Steps to reproduce the behaviour

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getLogs", "params": [{"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}], "id":1}' http://localhost:8545` 

Returns nothing

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getLogs", "params": [{}], "id":1}' http://localhost:8545` 

Works fine

**Comment by mahirkarim1** [comment]
Also block parameters work fine

**Comment by fenghaojiang** [comment]
> #### System information
> Erigon version: 2.28.1-stable-9711af6d
> 
> OS & Version: Ubuntu 20.04.5 LTS
> 
> Commit hash :
> 
> #### Expected behaviour
> eth_getLogs with the topics parameter should return logs filtered by the topic. According to #5547 this problem should have been fixed by in v2022.09.02+.
> 
> #### Actual behaviour
> Command returns `{"jsonrpc":"2.0","id":1,"result":[]}`
> 
> When no topics or address filter is supplied, getLogs works as intended.
> 
> #### Steps to reproduce the behaviour
> `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getLogs", "params": [{"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}], "id":1}' http://localhost:8545`
> 
> Returns nothing
> 
> `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getLogs", "params": [{}], "id":1}' http://localhost:8545`
> 
> Works fine

Wrong scheme. 
Try:
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getLogs", "params": [{"topics":[["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]]}], "id":1}' http://localhost:8545

**Comment by fenghaojiang** [comment]
`topics` are like [["xxx"], ["xxx"]]

**Comment by mahirkarim1** [comment]
Thanks, but that doesn't work either

**Comment by enriavil1** [comment]
What chain are you using?

**Comment by mahirkarim1** [comment]
BSC
