### ISSUE TITLE
"[Downloader] Timeout" - erigon must self-heal from this error

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5952]
seems sync stop after this error

log
```
[WARN] [11-04|02:12:43.000] [Downloader] Timeout                     requestId=1 peerID=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by nate-staked** [comment]
i am also experiencing this error, on latest v2.28.1:

```
[INFO] [11-04|18:06:51.615] [Downloader] posAnchor                   blockHeight=15898336
[INFO] [11-04|18:07:05.246] [5/16 Bodies] No block bodies to write in this log period block number=15898004 blk/second=0.000
[WARN] [11-04|18:07:15.257] [Downloader] Timeout                     requestId=1 peerID=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[INFO] [11-04|18:07:25.246] [5/16 Bodies] No block bodies to write in this log period block number=15898004 blk/second=0.000
```

**Comment by nate-staked** [comment]
Is there a way to fix it? restarted but still stuck

**Comment by mondsen** [comment]
I have the same issue with v2.28.1:
- first occurance yesterday around 6:20h - 7:20h UTC (seemed to be after a reorg? took around 1h to recover)
- 2nd occurance today starting 7:30h - still ongoing

**Comment by AskAlexSharov** [comment]
no update, but we working on it

**Comment by revitteth** [comment]
@dmitriyselivanov is picking this one up :)

**Comment by dylancaponi** [comment]
Same here, version `2.28.1-dev-ab3a0b0f`

Started at `Nov 17 23:49:50 UTC`

Please advise what I should do to fix.

**Comment by dylancaponi** [comment]
Updating to newest `devel` solved this problem for now.

**Comment by AskAlexSharov** [comment]
@dmitriyselivanov 
 restart seems helped. Also some my guess: maybe it related to `pkill -9 erigon` during StageBodies. Because seems new "internal consensus" preventing erigon from gracefull shutdown (need to pass root context there). So, I did kill.

**Comment by nandubatchu** [comment]
@AskAlexSharov - this is happening for me on docker image `thorax/erigon:v2.29.0` - what is the remedy?

**Comment by nandubatchu** [comment]
@AskAlexSharov is there any breaking change while upgrading from `thorax/erigon` from `v2.29.0` to `v2.32.1`?

**Comment by AskAlexSharov** [comment]
No
