### ISSUE TITLE
Logging parameters not read by toml

### ISSUE THREAD

**Issue by icculp** [ledgerwatch/erigon#5976]
None of the logging parameters are effective when specified in a toml file and read in via --config flag during runtime. Other parameters are read in (some need quotes).

```
datadir = "/erigon/data"
port = "{{PEER_PORT}}"
chain = "{{NETWORK}}"
http = "true"

"log.dir.verbosity" = 4
"log.console.verbosity" = 0
"log.dir.path" = "/erigon/data/"

"http.addr" = "0.0.0.0"
"http.api" = "engine,eth,erigon,web3,net,debug,trace,txpool"
"http.port" = "{{RPC_PORT}}"
"http.corsdomain" = "*"

"authrpc.jwtsecret" = "/erigon/config/jwt.hex"
"authrpc.addr" = "0.0.0.0"
"authrpc.port" = {{AUTH_PORT}}
"authrpc.vhosts" = "*"
```

I have tried
[log]
dir.path = ... 

With quotes and without, upper and lower case. Also tried "log.dir.path" = ... with and without quotes to no avail. None of the other logging parameters work either, including verbosity for console and dir. Tried with latest version, 2.29.0

**Comment by revitteth** [comment]
Oversight when I implemented the flags, will fix this shortly!

**Comment by revitteth** [comment]
https://github.com/ledgerwatch/erigon/pull/6251
