### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by DrawnWren** [ledgerwatch/erigon#5977]
# Rationale
`fmt.Errorf()` calls don't produce the easiest to debug error logs.

# Implementation

Would you accept a PR that moves to an error logging system that is a little more complex like i.e. this: https://medium.com/swlh/error-tracing-tips-on-golang-763624cded11

I'd be happy to implement, and open to other solutions if you have better ones.

**Comment by AskAlexSharov** [comment]
Hi. Thank you. Probably I will deny this FR. By next reasoning: 
1. We are public software - it means other people using us and then doing bug-reports - "full path to file" will reveal details of their internal infrastructure (paths on server). 
2. We are public software - which often used by "unskilled" users - showing trace will only confuse them. If we will show human-friendly error message - likely they will self-help and not come to Bug-tracker. But showing human-friendly message with stack - likely will just scare them and they will not read the message.
3. We have much C code. It means most of important errors - anyway will have limited stack. 
4. In my (personal) experience - having more context (more variables in error message) is more useful than knowing trace. 
5. In my (personal) experience - most complicated for debugging errors (like state-root miss-match) are well-known - everybody know where it happening, but anyway it may take days to debug them. 
6. We already have some self-made system of pre-defined error-prefixes/logs-prefixes to understand which sub-system produced this log/error. 

Pros: 
- actually we have 2-3 places in code - where having stack is super-useful, we added it there. For example: `erigon-lib/kv/mdbx/kv_mdbx.go` has func `dbg.Stack()`
