### ISSUE TITLE
Incorrect value field (reward) while tracing BSC blocks

### ISSUE THREAD

**Issue by a26nine** [ledgerwatch/erigon#5987]
Erigon version: `2.28.1`

While tracing BSC blocks with `trace_block`, the `value` field for the reward returns `0x1bc16d674ec80000` — equivalent to 2 ETH. This comes from pre-merge ETH where the miner reward per block was 2 ETH.

For ETH, this has been fixed and returns `0x0`. Can we do the same for BSC?

### BSC
```
{
  "method": "trace_block",
  "params": [
    "0x15c99d7"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
```
👇🏻
```
{
      "action": {
        "author": "0xa6f79b60359f141df90a0c745125b131caaffd12",
        "rewardType": "block",
        "value": "0x1bc16d674ec80000"
      },
      "blockHash": "0x967bd9a6b4d03c7886e0c8dbe49a16c1eb52efc7c7a06b52882b573c1b4629cb",
      "blockNumber": 22845911,
      "result": null,
      "subtraces": 0,
      "traceAddress": [],
      "type": "reward"
}
```

### ETH
```
{
  "method": "trace_block",
  "params": [
    "0xf2e008"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
```
👇🏻
```
{
      "action": {
        "author": "0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5",
        "rewardType": "block",
        "value": "0x0"
      },
      "blockHash": "0x34162a641846868ae505d3112b37ff5cf414be96f84c5fac0673972f73a09f55",
      "blockNumber": 15917064,
      "result": null,
      "subtraces": 0,
      "traceAddress": [],
      "type": "reward"
}
```

**Comment by enriavil1** [comment]
When is BSC suppose to have a value reward of 0?

**Comment by a26nine** [comment]
> When is BSC suppose to have a value reward of 0?

No, BSC is not supposed to have a block reward of 0. However, while tracing a block, the current arbitrary value `0x1bc16d674ec80000` comes from the old ETH (PoW) setup. The Erigon team has already changed it to `0x0` for ETH after The Merge (PoS) (many issues for the same). Then why not do it for BSC too?

Do you think `0x1bc16d674ec80000` is accurate and should stay?
