### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by binomialstew** [ledgerwatch/erigon#5993]
I tried to join the discord to ask a question as was recommended, but it said the invite link provided in this template was invalid (possibly expired).

I'm wondering if Erigon is performing correctly on my system.
```
INFO[11-06|16:17:53.590] [txpool] stat                            block=14999999 pending=10000 baseFee=0 queued=14913 alloc=2.8GB sys=3.0GB
...
INFO[11-07|17:16:50.880] [txpool] stat                            block=14999999 pending=9922 baseFee=0 queued=30000 alloc=4.6GB sys=7.3GB
```
So it seems it has reduced 78 "pending" in 25 hours. Are these blocks? That does not really make sense to me, but maybe I am misunderstanding.

Either way, any way I can improve performance in general?

3.5 GHz 6-Core Intel Xeon E5
64GB RAM
Gigabit internet

**Comment by AskAlexSharov** [comment]
@binomialstew no, Erigon stuck at `block=14999999` - likely it's related to https://github.com/ledgerwatch/erigon/issues/5952
- you need search in logs - some lines before this `txpool` lines
- txpool is not related to sync
- you can --txpool.disable to avoid confusion - and enable it later when erigon fully in-sync

**Comment by binomialstew** [comment]
Seeing this:

```
INFO[11-07|22:02:36.452] [7/16 Execution] Blocks execution        from=10558304 to=14999999
INFO[11-07|22:02:56.472] [7/16 Execution] Executed blocks         number=10558349 blk/s=2.2 tx/s=462.1 Mgas/s=28.0 gasState=0.00 batch=849.2KB alloc=2.8GB sys=3.0GB
INFO[11-07|22:03:16.604] [7/16 Execution] Executed blocks         number=10558414 blk/s=3.2 tx/s=641.0 Mgas/s=38.9 gasState=0.00 batch=2.2MB alloc=3.0GB sys=3.2GB
```
 Is it only set to process to `14999999`? I've restarted a couple times with no improvement.

Is there a prior version I can use in the meantime to get this synced?

**Comment by binomialstew** [comment]
Executed blocks seem to be increasing, at least...

**Comment by binomialstew** [comment]
Is the discord still open?
