### ISSUE TITLE
Erigon for Polygon stuck at 21237748 block

### ISSUE THREAD

**Issue by Aracki** [ledgerwatch/erigon#6000]
#### System information

The Erigon node was started with `v2.28.1` and stuck on the block: `21237748`. I've tried also with `v2.29.0` but problem remains.

#### Issue

Logs seems ok:
```
[p2p] GoodPeers                          eth66=33
[6/16 Senders] Recovery                  block_number=29906533 ch=0/10000
no pending block found returning latest executed block
no pending block found returning latest executed block
[txpool] stat                            block=35348432 pending=10000 baseFee=0 queued=30000 alloc=4.7GB sys=10.0GB
```

...but for the last 4 days the latest block is always the same. Any ideas?

**Comment by chetanbothra** [comment]
hi @Aracki are u still having this issues ? if yes did you try to unwind ?

build/bin/integration state_stages --unwind=1 --datadir <data_dir> --chain bor-mainnet
build/bin/integration stage_headers --unwind=1 --datadir<data_dir>--chain bor-mainnet

**Comment by Aracki** [comment]
Sorry but I see no `build/` dir within erigon repo. Maybe I am misunderstanding something?

**Comment by chetanbothra** [comment]
You need to stop all running erigon service
Then do 'make integration'
This will generate an integration file under build and bin
You can then run this command

**Comment by Aracki** [comment]
`state_stages` command still running, but it's printing: 
```
[INFO] [11-15|20:36:08.685] [8/16 HashState] ETL [1/2] Extracting    from=AccountChangeSet progress=0
[INFO] [11-15|20:36:08.685] [8/16 HashState] ETL [1/2] Extracting    from=AccountChangeSet progress=0
[INFO] [11-15|20:36:08.685] [8/16 HashState] ETL [1/2] Extracting    from=AccountChangeSet progress=0
```

and in `debug-error.log` file:
```
9/16 IntermediateHashes] Wrong trie root of block 21237748: e04f5a6ae6a4c64bf46543bec4f29d4ab133fea54ed6bbe8de5106f90217aa5a, expected (from header): e015e8a7eb7010e3cc35faf05cb6830a61d9d142271180be44c961bc99b86653. Block hash: 5b4ad893f5c0acff9aecff7827e09516b602eab4d0107505760e795d3f6ff01a"
```
