### ISSUE TITLE
What's the expected sync behavior if we restart after OOM at [7/16 Snapshots]?

### ISSUE THREAD

**Issue by 0xSage** [ledgerwatch/erigon#6008]
**System information**
Erigon version: 2.29.0-dev-29b23895

**OS & Version**
Ubuntu 22.04

**Issue**
An OOM issue killed a fresh client sync at [7/16 Snapshots]. To resolve this, I increased swapfile size and decreased `batchSize`, and then restarted sync.

**Notable Logs**
```sh
[WARN] "..transactions.seg": would have banned ... for touching piece xxxx after failed piece check
# ...
[1/16 Snapshots] download peers=...
# ... some time later
[1/16 Snapshots] DONE
[2/16 Headers] Waiting for Consensus Layer...
# ...
# Then I seem to be stuck, and only getting the standard INFO logs
[p2p] GoodPeers
[txpool] stat ...
```

**Expected Behavior**
Sync to either start from cache (at 7/16 snapshots) OR to start from scratch, and resume past [2/16 snapshots]. Instead, I'm not sure what's happening/if I'm stuck. There are no more error/warn messages.

**Questions**
- Is the "failed piece check" warning related to my issue?
- Do I need to clear cache somewhere to resume from 7/16 snapshots?
- What can I read to truly understand snapshots, what's happening at each step, etc? 

Thank you

**Comment by AskAlexSharov** [comment]
7/16 - it’s stage of execution blocks, not relate much to snapshots (only reading them). Just decrease batchSize 4-8 times. Also can add “GOGC=50 ./build/bin/erigon ….” to reduce ram usage a bit. 

Also I don’t know how much RAM you have. 

We will reduce defaults a bit. 

“Would have banned” - ignore it - not dangerous

**Comment by 0xSage** [comment]
Ok, thanks! My RAM is 64gb, swap space was 2gb, so was surprised at the OOM. Will rerun with reduced batch size.

How do I purge everything to restart the sync from scratch? I corrupted the state by mucking around too much. And am now unable to restart client with the new flag settings - even after deleting datadir/etc.

**Comment by AskAlexSharov** [comment]
delete datadir is enough
