### ISSUE TITLE
Receipt missing

### ISSUE THREAD

**Issue by DaraDoyoung** [ledgerwatch/erigon#6011]
#### System information

Erigon version: `erigon version 2022.10.1-dev-d566d4af`

OS & Version: Linux

It seems that some transaction receipts are empty. I am fully synced, and my erigon script with lighthouse for beacon node is:
```
nohup erigon \
  --datadir ~/data \
  --http \
  --http.addr 0.0.0.0 \
  --http.api 'eth,web3,net,debug,trace,txpool' \
  --http.vhosts '*' \
  --http.port 8545 \
  --ws \
  --torrent.download.rate=20mb \
  --authrpc.addr=127.0.0.1 \
  --authrpc.port=8551 \
  --prune.h.older=90000 \
  --prune.r.older=90000 \
  --prune.t.older=90000 \
  --prune.c.older=90000 \
  --private.api.addr=localhost:9090 \
  >> ~/data/logs/erigon.log \
  2>&1 &


/home/ubuntu/.cargo/bin/lighthouse \
  --network mainnet \
  --datadir ~/data\
  beacon_node \
  --http \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt /home/ubuntu/data/jwt.hex \
  --checkpoint-sync-url https://beaconstate.info \
  >> ~/data/logs/lighthouse.log \
  2>&1 &
ps -ef | grep lighthouse | grep network | awk '{print $2}' | xargs screen -dm
```
The block number that I am having issue is 64026 (There are a lot more, but I am reporting with this specific block number), and this block contains 2 transactions(https://etherscan.io/txs?block=64026).

```
curl -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionReceipt","params":["0x1793311c9b86ba333d3a02dbd16c21a8f18df05a7743758e6dbd74cdcdf1bbef"],"id":1,"jsonrpc":"2.0"}' localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"getReceipts error: nonce too low: address 0x0C2073BA44D3dDbdb639C04e191039A71716237f, tx: 0 state: 1"}}
```
If I send curl to check getTransactionReceipt it gives me error like above.
But with my geth node that I am running along with the erigon node, 
```
curl -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionReceipt","params":["0x1793311c9b86ba333d3a02dbd16c21a8f18df05a7743758e6dbd74cdcdf1bbef"],"id":1,"jsonrpc":"2.0"}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x7fc37194f89bf37855b8a0fe1c8c7e47804d8547c6f7904f239f37fc3d1c516b","blockNumber":"0xfa1a","contractAddress":null,"cumulativeGasUsed":"0x11e2f","effectiveGasPrice":"0xdbd746f87","from":"0xcce611cd2bfdc3260099b99b71ccfbe4a06d8b7d","gasUsed":"0xc9c3","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","root":"0x30ab0ef31b0460817e4279e19083348c0c20ca46c3a741346594a2966adb5b5b","to":"0xfbc128067a2fe13c11bbc6cc55f29aa1f27630da","transactionHash":"0x1793311c9b86ba333d3a02dbd16c21a8f18df05a7743758e6dbd74cdcdf1bbef","transactionIndex":"0x1","type":"0x0"}}
```
It works well. 
Is there anything that I have done wrong that made me not get receipts for every transaction? Or is this a bug from erigon?

ADD)
I have also tried with blocks after 90000, since I have options
```
  --prune.h.older=90000 \
  --prune.r.older=90000 \
  --prune.t.older=90000 \
  --prune.c.older=90000 \
```
but 90002 block makes same error..

**Comment by enriavil1** [comment]
If I remember correctly prune.*.older will prune blocks older than the value you set from latest meaning that if you have prune.r.older=90000 then it will prune all receipts older than latestBlockNum-90000

**Comment by enriavil1** [comment]
Any how the correct response if the receipt was pruned is nil so there is something wrong

**Comment by DaraDoyoung** [comment]
@enriavil1 Hmm.. If this is meaning something is wrong, any ideas where to look at for the problem?

**Comment by enriavil1** [comment]
> @enriavil1 Hmm.. If this is meaning something is wrong, any ideas where to look at for the problem?

Yes I have an idea on what can be wrong, but also even if I apply a fix you will not be able to retrieve the blocks because they are pruned for you.

**Comment by DaraDoyoung** [comment]
If I remove the prune flags,
```
  --prune.h.older=90000 \
  --prune.r.older=90000 \
  --prune.t.older=90000 \
  --prune.c.older=90000 \
```
and run erigon again, would this get the pruned data back?
Or to get data for pruned data, do I need to sync the blocks again from the beginning?

**Comment by enriavil1** [comment]
> If I remove the prune flags,
> 
> ```
> 
>   --prune.h.older=90000 \
> 
>   --prune.r.older=90000 \
> 
>   --prune.t.older=90000 \
> 
>   --prune.c.older=90000 \
> 
> ```
> 
> and run erigon again, would this get the pruned data back?
> 
> Or to get data for pruned data, do I need to sync the blocks again from the beginning?
> 
>   

You will have to sync from the beginning. When you start syncing and set or don't set a prune flag then you can't later on change it 🙁

**Comment by DaraDoyoung** [comment]
Okay, that's a sad news..
It would be wonderful if you give me notification when the fix is ready! :slightly_smiling_face:

**Comment by DaraDoyoung** [comment]
@enriavil1 Hi, I am getting receipts for the latest transaction hash, however I am still getting errors for the historical transaction hashes.
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method":"eth_getTransactionReceipt", "params": ["0xc20aad7604213f6ff3aec15b9036d0783a218ccb8c5d7a9241946a5e3f492ca4"], "id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x0bd1e23cdbc4ec9d76c6ae161acba0023a4af967aa68f2f503e6decb6f4c0b36","blockNumber":"0xf5f142","contractAddress":null,"cumulativeGasUsed":"0xe38eb5","effectiveGasPrice":"0x2ca98dadb","from":"0xaa1a3034092b6933d136cfc1f8199d17e3ac1105","gasUsed":"0x5208","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","to":"0x47ff82890d575139fa486e2bc0eb07086415db92","transactionHash":"0xc20aad7604213f6ff3aec15b9036d0783a218ccb8c5d7a9241946a5e3f492ca4","transactionIndex":"0x99","type":"0x2"}}
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method":"eth_getTransactionReceipt", "params": ["0x1793311c9b86ba333d3a02dbd16c21a8f18df05a7743758e6dbd74cdcdf1bbef"], "id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"getReceipts error: nonce too low: address 0x0C2073BA44D3dDbdb639C04e191039A71716237f, tx: 0 state: 1"}}
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method":"eth_getTransactionReceipt", "params": ["0x02714854e314876838e9629221c3482464a6de97dee52e03def03ed5ba0748c1"], "id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"getReceipts error: nonce too high: address 0xA7EFAe728D2936e78BDA97dc267687568dD593f3, tx: 906697 state: 0"}}
```

Has there been any progress on this issue?

**Comment by thanhlmm** [comment]
Hmm, how can we resolve that? I have the same issue as above

**Comment by enriavil1** [comment]
If you have pruning set like `--prune=htrc` erigon will automatically prune anything that is 90000 blocks older than the latest, so you will only have not pruned the last 90000 blocks

**Comment by DaraDoyoung** [comment]
@enriavil1 Yes. But I have same issue with recent blocks before 90000 blocks as well.
I've tested same rpc call with geth full node but geth node gives data whereas erigon gives `nonce too low` or `nonce too high` error message.
Even if the response is not available due to pruning, `nonce too low` or `nonce too high` error message looks awkward.

**Comment by DaraDoyoung** [comment]
@enriavil1 Any updates? :) 
I'm still having same problem as I reported earlier. This txHash is from about 9000 blocks behind (which is in the boundary of latestblock - 90000) but I get the same error :(
Network: goerli
Erigon version: 2.42.0-stable-d8d04663

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method":"eth_getTransactionReceipt", "params": ["0xf904d12085b5c8dd5cf6af7cf98a34f5673f5a22abb14a17fd5ec5ab5008a802"], "id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"getReceipts error: insufficient funds for gas * price + value: address 0xe0a2Bd4258D2768837BAa26A28fE71Dc079f84c7 have 0 want 100000000021000000000000"}}
```

By the way, my erigon archive node seems to work fine. I don't know why my full node is messed up..
