### ISSUE TITLE
sync SUPER SLOWLY!!! HELP!

### ISSUE THREAD

**Issue by BNB666666666** [ledgerwatch/erigon#6018]
https://user-images.githubusercontent.com/117515691/201124436-61ad2fee-73f0-4bc2-8752-b9f95df923da.png

https://user-images.githubusercontent.com/117515691/201123652-f53b6a14-193e-409a-82cb-b5dccb4d58ca.png

What should I do?
Why it can be so choking?     X (

**Comment by AskAlexSharov** [comment]
closing. 

please create better bug-report: 
- avoid emotional/screaming/offending words/phrases. be more constructive.
- give us more context: erigon version, your server hardware (CPU/OS/RAM/Disk/Raid/etc...), what network you syncing, do you have other software on same server, etc...
- if you did some recent actions: server reboot, etc... please say about it also

**Comment by BNB666666666** [comment]
CPU：Xeon E5 2680    x2   (16cores)
OS:CENTOS 7.9
RAM:64G
Disk:SSD 2T 

networksyncing: BSC
no other software on same server


actions:
just reboot the computer and the erigon , but it still sync super slowly.

**Comment by BNB666666666** [comment]
erigon version:2.28.0

**Comment by BNB666666666** [comment]
command: ./erigon --chain=bsc --prune=hrtc --db.pagesize=16k --datadir /run/media/xxx/erigondata/erigon --private.api.addr=0.0.0.0:9090 -metrics --metrics.addr=0.0.0.0 --metrics.port=9350 --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --torrent.download.rate=20mb

**Comment by AskAlexSharov** [comment]
You can try warmup after reboot by: 
make db-tools
./build/bin/mdbx_dump -s PlainState <datadir>/chaindata > /dev/null
