### ISSUE TITLE
Run erigon 2.29.0  error

### ISSUE THREAD

**Issue by BNB666666666** [ledgerwatch/erigon#6025]
#### System information
CPU： 16 cores
RAM: 64G
Disk: ssd 2T
Erigon version: `./erigon --version`
2.29.0
OS & Version: Windows/Linux/OSX
CentosOS
Commit hash : 

#### Expected behaviour
erigon 2.29.0 run successfully

#### Actual behaviour

![image](https://user-images.githubusercontent.com/117515691/201262586-a291574d-cf14-4de7-9457-49a006cd204e.png)

[xxx@localhost 新加卷]$ ./erigon29
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

#### Backtrace

````
[backtrace]
````

**Comment by hitchhooker** [comment]
receiving when using downloaded client

 can be solved if building client at the host machine
