### ISSUE TITLE
Port conflict using internal CL when running multiple erigon processes on the same machine, bound to the same IP address

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#6038]
#### System information

v2.30.0

Running two Ethereum (Goerli in this case) nodes on the same server

Issue with Ethereum (Goerli) when running two nodes on the same server, there is no reference to port 4000 in the help, also it is not running an external sentinel, believe this is coming from using the internal CL client 

`Erigon startup                           err="failed creating sentinel listener err=listen udp4 0.0.0.0:4000: bind: address already in use"`

it appears that in order to run two nodes on the same machine you either need two different external IP addresses (and bind each erigon to one) or run an external sentry process(?) to get around the inability to set the port of the internal CL

reverting to `--externalcl` solves the issue but then requires running a separate CL process.

Possible solution: allow setting the port of the internal CL

**Comment by PeaStew** [comment]
resolved by https://github.com/ledgerwatch/erigon/commit/ae01026ca9bcdb3c16e8d6b5def34aba8e8a97db, 2.30.0 cannot be used in multinode setup (except in docker) and then port can be set using lightclient switches

**Comment by PeaStew** [comment]
resolved by https://github.com/ledgerwatch/erigon/commit/ae01026ca9bcdb3c16e8d6b5def34aba8e8a97db, 2.30.0 cannot be used in multinode setup (except in docker) and then port can be set using lightclient switches

**Comment by TangMonk** [comment]
Still problem, How to fix?
