### ISSUE TITLE
Pruning and disk space how it works?

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#6040]
Hello.
I have synced BSC mainnet and prune=hrtc param, this equals 90K blocks. My DB size is ~800GB at current time. Is really 90K blocks consume ~800G? That means average block size is 9.1 MB but according to https://bscscan.com/chart/blocksize is ~45 Kbytes today. Why is there such a huge difference?

**Comment by AskAlexSharov** [comment]
Unfortunately after TheMerge we can’t prune receipts because CL may request them. And receipts are big. We will impruve it in future.
