### ISSUE TITLE
after upgrade from v0.28 - DumpHeaders: header missed in db: block_num

### ISSUE THREAD

**Issue by rasdotsu** [ledgerwatch/erigon#6044]
#### System information

Erigon version: 2.30.0-stable-35f493c5

OS & Version: Linux 

Commit hash : 35f493c5d021965f994bee615d441b2b35811f8f

Begin push error with snapshots

```
erigon-erigon-1      | [WARN] [11-14|08:55:20.054] [1/16 Snapshots Prune]                   err="retire blocks error: DumpBlocks: DumpHeaders: header missed in db: block_num=20500000,  hash=f824adf616e7e42270029fa8876ef18d8e51c56429a822e9fa1c44c703dc5cc6, fromBlock=20500000, toBlock=21000000"
erigon-erigon-1      | [INFO] [11-14|08:55:20.055] [snapshots] Retire Blocks                range=20500k-21000k
```

And tried re-download snapshots and again this error.

**Comment by AskAlexSharov** [comment]
do:
make integration
./build/bin/integration stage_headers --reset
start erigon with --downloader.verify flag once
