### ISSUE TITLE
EIP 1153

### ISSUE THREAD

**Issue by tynes** [ledgerwatch/erigon#6049]
# Rationale

[EIP 1153](https://eips.ethereum.org/EIPS/eip-1153) has been moved to CFI for Shanghai https://github.com/ethereum/execution-specs/pull/642. The previous link includes links to the other client implementations. As discussed on ACD, it is planned to be included in the upcoming Shangdong testnet. Opening this issue to track progress on its implementation in Erigon.

# Implementation

I believe much of the code can be reused from `go-ethereum`. Would you like me to open a PR porting over the implementation?

**Comment by yperbasis** [comment]
@tynes Yes, please port https://github.com/ethereum/go-ethereum/pull/26003
