### ISSUE TITLE
Add an endpoint to allow getting the 	TrieNode by a given root state hash.

### ISSUE THREAD

**Issue by krasi-georgiev** [ledgerwatch/erigon#6054]
# Rationale

Why should this feature exist?
 - to allow quering archive nodes for the state at a given root hash 

What are the use-cases?
 - running local simulations on top a given state at a good performance and minimal db/rpc calls.

# Implementation
Do you have ideas regarding the implementation of this feature?
 - not yet, but willing to look into the code. In geth this is possible via the `debug_dbget` rpc call.

Are you willing to implement this feature?
 - yes

**Comment by krasi-georgiev** [comment]
I see that you have or had `db_getString` and `db_getHex` what is the reason to deprecate those?

**Comment by krasi-georgiev** [comment]
moved to using a different approach

**Comment by ChanHongMing** [comment]
Hello, I am currently looking for a similar thing to `debug_dbget`, may you elaborate on the different approach? Thanks a lot @krasi-georgiev

**Comment by krasi-georgiev** [comment]
can't remember, was too long ago
