### ISSUE TITLE
External CL should be the DEFAULT

### ISSUE THREAD

**Issue by dylancaponi** [ledgerwatch/erigon#6077]
It seems against ETH ethos to opt-out with an `--externalcl` flag. It's also a breaking change for everyone who upgrades.

**Comment by Giulio2002** [comment]
How is that against ETH ethos? if you are referring to the fact that goes against "client diversity" , It does not really matter because it is non-validating, and even if it were validating it would still be default. regarding the `--externalcl` flag we personally do not find it `breaking`.

**Comment by koraykoska** [comment]
@Giulio2002 Whether something is a breaking change is not subjective. I upgraded erigon recently on dozens of machines and for my existing setup it was definitely breaking.

And what @dylancaponi meant by ETH ethos: There is a clear reason why the CL is promoted as its own system. You know that there are already many parts of the EL that might be considered a separate product (and you can run most of them individually using erigon). The clear differentiator with the CL mentality is giving the feeling to all node providers that you actually have to choose. This implicitly leads to client diversity which is crucial for reasons we all know.

Just to add my 2 cents: I think seeing erigon as "the one binary you run to spin up your own Ethereum node" is a good philosophy that might even increase decentralization as it's also easy enough to run for people who don't care enough to actually spend a lot of time with it. Though, adding an explicit statement in the README that it is preferable to choose one of all the existing CL clients manually and a link to the client diversity page wouldn't hurt.

**Comment by dylancaponi** [comment]
If a user simply upgrades without changing any configuration and Erigon no longer works, I consider that a breaking change. Release notes should include warnings and instructions to avoid breaking changes.

[v2.43.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.43.0) was a breaking change because anyone who had the `--externalcl` flag set found that Erigon would not startup and the error message did not explain why. It only said `flag provided but not defined: -externalcl` and immediately failed startup.

Several people in the discord (besides me) had this same issue and thus friction and delay was added to their upgrade.

This could be avoided with a simple message in the release notes:
`Breaking change: If you have --externalcl in your configuration, _remove it_ before restarting Erigon. External CL usage is now the default`

Instead I see: `Added first phase of Caplin (embeddable Consensus Layer implementation), replaces embedded CL light client. Disabled by default, enabled by --internalcl command line flag.` which might raise alarm bells with the most savvy operators but it's not a clear call to action.

**Comment by Giulio2002** [comment]
> If a user simply upgrades without changing any configuration and Erigon no longer works, I consider that a breaking change. Release notes should include warnings and instructions to avoid breaking changes.
> 
> [v2.43.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.43.0) was a breaking change because anyone who had the `--externalcl` flag set found that Erigon would not startup and the error message did not explain why. It only said `flag provided but not defined: -externalcl` and immediately failed startup.
> 
> Several people in the discord (besides me) had this same issue and thus friction and delay was added to their upgrade.
> 
> This could be avoided with a simple message in the release notes: `Breaking change: If you have --externalcl in your configuration, _remove it_ before restarting Erigon. External CL usage is now the default`
> 
> Instead I see: `Added first phase of Caplin (embeddable Consensus Layer implementation), replaces embedded CL light client. Disabled by default, enabled by --internalcl command line flag.` which might raise alarm bells with the most savvy operators but it's not a clear call to action.

I understand your concerns and I have a solution: https://github.com/ethereum/go-ethereum. this should fix it. hope it helps

**Comment by dylancaponi** [comment]
@Giulio2002 I like Erigon and want to help it improve. This is why I'm going to the effort of providing constructive criticism. What do you hope to achieve by pushing away users?

**Comment by koraykoska** [comment]
@Giulio2002 <https://github.com/Giulio2002> How does it help to be salty?
We are all using erigon for a reason and think it’s superior. But does this
mean there cannot be simple but powerful suggestions to make it even better?
Being as old as it already is, erigon can easily adapt at least documenting
breaking changes. Nobody asks for no breaking changes at all. We understand
that being able to introduce breaking changes keeps you more agile.
But to be honest, the approach of telling people "it’s alpha software, fuck
off" led to Nethermind overtaking erigon quite impressively. Keep it up if
that’s your goal.
