### ISSUE TITLE
Embedded light client should ignore private IPs during discovery

### ISSUE THREAD

**Issue by 0xStrobe** [ledgerwatch/erigon#6079]
v2.30.0 made it default to use the embedded consensus client.

However, the light client will be naively trying to connect with any IPs shared by peers during the discovery process. This may included non-global and unreachable IPs like `10.10.1.1`, and some hosting providers identify these connection attempts as netscan activities which are against their TOS.

This has caused issues as seen in issues like: https://github.com/ledgerwatch/erigon/issues/6067, https://github.com/ledgerwatch/erigon/issues/6034

We should make it default to ignore non-global IPs during discovery. This can be a rather serious issue since some hosting providers will ban users due to this.

Lighthouse has encountered similar issues in https://github.com/sigp/lighthouse/issues/3006#issuecomment-1039691245 and the fix was implemented in https://github.com/sigp/lighthouse/pull/3023/.

**Comment by Giulio2002** [comment]
I think it is now good, if it is not good pls open again and lets make this good :)
