### ISSUE TITLE
power outage ERROR

### ISSUE THREAD

**Issue by BNB666666666** [ledgerwatch/erigon#6081]
![image](https://user-images.githubusercontent.com/117515691/202832038-007320ae-397a-4144-9bdc-25cba1dae27e.png)

**Comment by BNB666666666** [comment]
last time it runs generally.But I just meet power outrage.Then it went wrong

**Comment by BNB666666666** [comment]
@AskAlexSharov

**Comment by AskAlexSharov** [comment]
- or another erigon already running on same datadir
- or erigon does run db-migrations

if you think it's an "power outage" related: 
- run "make db-tools" and "./build/bin/mdbx_chk"
- check that fsync is enabled on your file-system

**Comment by AskAlexSharov** [comment]
FYI: it's also safe to delete `datadir/nodes` folder
