### ISSUE TITLE
WARN[11-19|14:38:32.500] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"

### ISSUE THREAD

**Issue by ASISBusiness** [ledgerwatch/erigon#6082]
WARN[11-19|14:38:32.500] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:32.506] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:33.497] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:33.503] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:33.508] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:33.517] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:34.509] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:34.515] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:34.522] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:34.531] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:35.521] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:35.527] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:35.533] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
WARN[11-19|14:38:35.539] Status error, sentry not ready yet       stream=RecvMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:111 asm_amd64.s:1594]"
WARN[11-19|14:38:36.534] Status error, sentry not ready yet       stream=RecvUploadHeadersMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:93 asm_amd64.s:1594]"
WARN[11-19|14:38:36.557] Status error, sentry not ready yet       stream=RecvUploadMessage err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:78 asm_amd64.s:1594]"
WARN[11-19|14:38:36.563] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"

_Originally posted by @BNB666666666 in https://github.com/ledgerwatch/erigon/issues/2246#issuecomment-1320819205_

**Comment by BNB666666666** [comment]
> ```
>     WARN[11-19|14:38:32.500] Status error, sentry not ready yet       stream=PeerEvents err="could not start server: mdbx_env_open: MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag, label: sentry, trace: [kv_mdbx.go:221 nodedb.go:124 nodedb.go:90 server.go:532 server.go:504 sentry_grpc_server.go:875 sentry_client.go:213 sentry_multi_client.go:153 sentry_multi_client.go:126 asm_amd64.s:1594]"
> ```
> 
> WARN[11-19|14：38：32.506] 状态错误，哨兵尚未准备就绪 流=RecvMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者在打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：111 asm_amd64.s：1594]”WARN[11-19|14：38：33.497] 状态错误，哨兵尚未准备就绪 流=RecvUploadHeadersMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：93 asm_amd64.s：1594]”WARN[11-19|14：38：33.503] 状态错误，哨兵尚未准备就绪 流=RecvUploadMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：78 asm_amd64.s：1594]”WARN[11-19|14：38：33.508] 状态错误，哨兵尚未准备就绪 流=对等事件 err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE 标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：126 asm_amd64.s：1594]”WARN[11-19|14：38：33.517] 状态错误，哨兵尚未准备就绪 stream=RecvMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者在打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：111 asm_amd64.s：1594]”WARN[11-19|14：38：34.509] 状态错误，哨兵尚未准备就绪 流=RecvUploadHeaders消息 err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：93 asm_amd64.s：1594]”WARN[11-19|14：38：34.515] 状态错误，哨兵尚未准备就绪 流=RecvUploadMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：78 asm_amd64.s：1594]”WARN[11-19|14：38：34.522] 状态错误，哨兵尚未就绪 流=对等事件 err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者环境已被使用le 打开与 MDBX_EXCLUSIVE 标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：126 asm_amd64.s：1594]“WARN[11-19|14：38：34.531] 状态错误，哨兵尚未准备好 流=RecvMessage err=”无法启动服务器： mdbx_env_open： MDBX_BUSY：另一个写入事务正在运行，或者打开时环境已被使用MDBX_EXCLUSIVE标志，标签：哨兵，跟踪：[kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：111 asm_amd64.s：1594]“WARN[11-19|14：38：35.521] 状态错误，哨兵尚未准备好 流=RecvUploadHeadersMessage err=”无法启动服务器： mdbx_env_open： MDBX_BUSY：另一个写入事务正在运行，或者打开时环境已被使用MDBX_EXCLUSIVE标志，标签：哨兵，跟踪：[kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：93 asm_amd64.s：1594]”WARN[11-19|14：38：35.527] 状态错误，哨兵尚未准备就绪 流=RecvUploadMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：78 asm_amd64.s：1594]”WARN[11-19|14：38：35.533] 状态错误，哨兵尚未准备就绪 流=对等事件 err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者在打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：126 asm_amd64.s：1594]”WARN[11-19|14：38：35.539] 状态错误，哨兵尚未准备就绪 流=RecvMessage err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：111 asm_amd64.s：1594]”WARN[11-19|14：38：36.534] 状态错误，哨兵尚未准备就绪 流=RecvUploadHeaders消息 err=“无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：93 asm_amd64.s：1594]”WARN[11-19|14：38：36.557] 状态错误，哨兵尚未准备就绪 流=RecvUploadMessage err=“无法启动 服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_client.go：78 asm_amd64.s：1594]“WARN[11-19|14：38：36.563] 状态错误，哨兵尚未就绪 流=对等事件 err=”无法启动服务器： mdbx_env_open： MDBX_BUSY： 另一个写入事务正在运行，或者打开时环境已被使用 MDBX_EXCLUSIVE标志， 标签： 哨兵， 跟踪： [kv_mdbx.go：221 nodedb.go：124 nodedb.go：90 server.go：532 server.go：504 sentry_grpc_server.go：875 sentry_client.go：213 sentry_multi_client.go：153 sentry_multi_客户：126 asm_amd64.s：1594]”
> 
> _最初发布者@BNB666666666in[#2246 （评论）](https://github.com/ledgerwatch/erigon/issues/2246#issuecomment-1320819205)_

do u get same problem?

**Comment by AskAlexSharov** [comment]
- or another erigon already running on same datadir
- or erigon does run db-migrations

**Comment by AskAlexSharov** [comment]
FYI: it's also safe to delete `datadir/nodes` folder
