### ISSUE TITLE
During initial sync after data download, Eirgon consumes all available ram and starts swapping to disk (128GB)

### ISSUE THREAD

**Issue by b1f00d78** [ledgerwatch/erigon#6084]
#### System information

Erigon version: 2.30.0-stable-35f493c5

OS & Version: Windows 11

#### Expected behaviour

Erigon should be free to consume RAM, but not exceed what is available.
Provide an ability to cap the memory available to Erigon.

#### Actual behaviour

Erigon continues to absorb RAM until there is non available on the machine, at this point it starts swapping to disk, but does not increase further (maybe 100-200MB on disk swap file).
I cannot sync this node, as it always starts swapping memory to disk.

#### Steps to reproduce the behaviour

`.\build\bin\erigon.exe --datadir ..\ErigonArchiveData\`
After it downloads the data to begin sync, during the Verify process and afterwards, Eirgon reports it is consuming about 24GB of RAM, but actually holds about 115GB in it's working set. No other processes can access this ram, and eventually the system crashes.

Built with Go go1.19.3 windows/amd64

**Comment by b1f00d78** [comment]
Building this in WSL and running in WSL, creates the same behaviour, except WSL is limited to 64GB of RAM.

It consumes all available RAM, starts thrashing the swap file, then crashes the WSL instance.

![image](https://user-images.githubusercontent.com/116952836/202868434-69d13aec-3ce6-417e-bfe5-68a7fefa5209.png)

**Comment by AskAlexSharov** [comment]
1. provide logs
2. if you can reproduce it - you can provide for us memory usage picture by: add `--pprof` flag, when you see high RAM usage do `go tool pprof -inuse_space -png http://127.0.0.1:6060/debug/pprof/heap > mem.png`

**Comment by b1f00d78** [comment]
I'm not pursuing this any further just wanted to provide a bug report - I've dumped all logs and data apologies.
