### ISSUE TITLE
Start Initial Sync from snapshots w/o CL headers

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#6095]
# Rationale

When Erigon starts for the first time, it downloads all the snapshots, but then it waits for the CL to start providing headers in stage 2.

I ran into a situation where my CL was re-syncing too, so Erigon basically just sat there doing nothing, waiting for headers from the CL which it won't send until it's done with its genesis sync.

I think it would make sense that when doing the initial genesis sync from the snapshots, Erigon should not wait for new headers and it should just start genesis sync with the blocks it has (maybe after a timeout?)

Starting the internal CL in Erigon comes with its own problems if you intend to use an external CL anyway.

## Why should this feature exist? / What are the use-cases?
In rare situations where you're starting a new node, both EL and CL from Genesis, Erigon could be processing the snapshots while the CL syncs too.

**Comment by AskAlexSharov** [comment]
pros:
- it's a good architecture pattern: ServiceA must work as much as possible even if it depend on ServiceB and ServiceB is down. ServiceA must be able to startup, handle requests, handle some work, be responsive, etc... 

cons:
- some stages will get slower on big second cycle: for example stage_hash_state, stage_trie. 
- timeout - if some "real problem" happen with CL - timeout will hide it. so you may know about it after few days.
- it's not very clear - must EL be "passive" or "active" (which service will drive the whole workflow forward)

**Comment by pyk** [comment]
hey it seems also happen on my fresh node:

```
pyk@shiver:~$ ./erigon/erigon -v
erigon version 2.30.0-stable
```

```
Nov 21 04:36:26 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:26.903] [txpool] stat                            block=0 pending=1 baseFee=0 queued=26 alloc=221.6MB sys=591.9MB
Nov 21 04:36:26 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:26.903] [LightClient] P2P                        peers=4
Nov 21 04:36:26 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:26.926] [1/16 Snapshots] download                progress="78.48% 194.2GB/247.4GB" download-time-left=4hrs:31m total-download-time>
Nov 21 04:36:26 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:26.926] [1/16 Snapshots] download                peers=175 connections=188 files=93 alloc=221.8MB sys=591.9MB
Nov 21 04:36:46 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:46.926] [1/16 Snapshots] download                progress="78.51% 194.2GB/247.4GB" download-time-left=4hrs:19m total-download-time>
Nov 21 04:36:46 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:36:46.926] [1/16 Snapshots] download                peers=177 connections=193 files=93 alloc=411.7MB sys=591.9MB
Nov 21 04:37:06 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:37:06.925] [1/16 Snapshots] download                progress="78.53% 194.3GB/247.4GB" download-time-left=4hrs:52m total-download-time>
Nov 21 04:37:06 shiver erigon-ethereum-mainnet[807]: [INFO] [11-21|04:37:06.925] [1/16 Snapshots] download                peers=176 connections=192 files=93 alloc=337.2MB sys=591.9MB
```

the `txpool` is always in pending state:

```
[txpool] stat                            block=0 pending=1 baseFee=0 queued=26 alloc=221.6MB sys=591.9MB
```

Do I need to do something in order to successfully sync the mainnet? or I just need wait the process till finished?

ty ser 🙏

**Comment by quickchase** [comment]
@pyk this is totally unrelated. Your logs clearly indicate it's still downloading snapshots. See how progress percentile is increasing?

**Comment by pyk** [comment]
@quickchase I'm so sorry ser 🙏 

> I think it would make sense that when doing the initial genesis sync from the snapshots, Erigon should not wait for new headers and it should just start genesis sync with the blocks it has (maybe after a timeout?)

I thought this mean that the txpool should be processed while downloading the snapshot, hence i'm trying to make sure that I can sync the mainnet. I marked my comment above as off-topic 🙏 🙇

**Comment by quickchase** [comment]
Ah, I understand now. Just to answer your question though: I doubt the txpool would be useful before full sync and the mempool isn't required and has nothing to do with syncing in general, you can disable the mempool and your node works (if you're not a validator) and syncs fine.

**Comment by MysticRyuujin** [comment]
@AskAlexSharov in response

> cons:
some stages will get slower on big second cycle: for example stage_hash_state, stage_trie.

When we sync BSC or Polygon, the first cycle takes like a week (or longer) and during that time Polygon and BSC generate a TON of blocks, but Erigon still handles the second cycle just fine (as far as I can tell). So I'm not sure how much weight to put behind that concern? It can take up to a week to sync the CL from genesis in an Archive sync, I think the time lost from that is far greater than the time lost from having a larger second cycle.

> timeout - if some "real problem" happen with CL - timeout will hide it. so you may know about it after few days.

I don't know if a timeout is a good idea or not, under normal operating conditions probably not, I was just putting it out as an idea how it might handle the situation on genesis sync.
