### ISSUE TITLE
BSC archive does not work. Symptom summary:

### ISSUE THREAD

**Issue by temuera** [ledgerwatch/erigon#6106]
#### System information
Erigon version: `2.30`
OS & Version: Linux
Commit hash : f33ec06572328ccfc8481c60770c213ddb61a1ea
HDD: MULTI NVME RAID0
RAM:256~768G DDR4
CPU:32C64H intel 5218 or AMD7302

I have multiple bsc's archive nodes deployed. none of them work now:(

**Case 1: upgrade from old veroisn.**
Can not download snapshots:
`INFO[11-22|09:15:15.661] [1/16 Snapshots] download                progress="99.96% 562.2GB/562.5GB" download-time-left=999hrs:99m total-download-time=45m40s download=0B/s upload=0B/s
`
**snapshot download will never succeed.**

**Case 2: clean install !!!!!**
snapshots download successful, but cannot build chain with loop:
`[INFO] [11-22|09:19:20.646] [2/16 Headers] No block headers to write in this log period block number=22999999`

**Case 3: remove snapshots folder**
snapshots download successful,  but getting error:
`INFO[11-21|04:54:54.812] [1/16 Snapshots] Fetching torrent files metadata EROR[11-21|04:54:54.822] Staged Sync err="runtime error: slice bounds out of range [1500017:1048576], trace: [stageloop.go:140 panic.go:890 panic.go:153 index.go:101 block_snapshots.go:183 block_snapshots.go:164 block_snapshots.go:618 block_snapshots.go:720 stage_snapshots.go:439 stage_snapshots.go:121 stage_snapshots.go:89 default_stages.go:20 sync.go:345 sync.go:255 stageloop.go:178 stageloop.go:94 asm_amd64.s:1594]"`
**Then enter CASE1 forever**

I've tried adding the "downloader.verify||snap.stop" parameter and unwind with integration.

There isn't any way to get my archive node to work.

@AskAlexSharov

**Comment by AskAlexSharov** [comment]
1. Increase logs verbosity, it will print not finished files, remove them (with .idx and with .torrent) files. Remove snapshots/db folder. Start erigon. 

2. Show more logs

**Comment by temuera** [comment]
`
INFO[11-23|06:43:37.601] [1/16 Snapshots] Total difficulty index: 22933k/22499k
INFO[11-23|06:43:57.615] [1/16 Snapshots] DONE                    in=14m36.159521088s
INFO[11-23|06:43:58.298] [2/16 Headers] Waiting for headers...    from=22499999
INFO[11-23|06:44:18.298] [2/16 Headers] No block headers to write in this log period block number=22499999
INFO[11-23|06:44:21.441] [txpool] stat                            block=0 pending=0 baseFee=0 queued=22 alloc=4.1GB sys=5.6GB
.........
INFO[11-23|06:44:38.299] [2/16 Headers] No block headers to write in this log period block number=22499999
INFO[11-23|06:44:58.299] [2/16 Headers] No block headers to write in this log period block number=22499999
INFO[11-23|06:45:18.298] [2/16 Headers] No block headers to write in this log period block number=22499999

`

**Comment by du5** [comment]
download from https://github.com/BNB48Club/bsc-snapshots

**Comment by quickchase** [comment]
> No block headers to write in this log period

This is a known, ongoing issue. There's really no solid solution. Sometimes just rebooting helps, but sometimes it does not. Others say deleting files works but that seems to be as helpful as just rebooting in my experience.

Just search that error under Issues, you'll see like 8 open issues with that error in the logs
