### ISSUE TITLE
Hetzner port scanning (:4000) - Downloader: re-write "is ipv6 enabled" logic

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#6117]
Seems Hetzner doesn't like current solution (does alert as "port scanning" activity):  
```
l, err := net.Listen("tcp6", fmt.Sprintf(":%d", port))
	if err != nil {
		isDisabled := strings.Contains(err.Error(), "cannot assign requested address") || strings.Contains(err.Error(), "address family not supported by protocol")
		if !isDisabled {
			log.Warn("can't enable ipv6", "err", err)
		}
	} 
```

But I don't know cross-platform lib for Go.

As a hot-fix we can:
- On linux move to `/sys/module/ipv6/parameters/disable` see https://www.golinuxcloud.com/linux-check-ipv6-enabled/
- On other systems just disable `ipv6` until user's complain

Optionaly can:
- try to find some cross-platform lib for this, maybe on C/Java 
- do something for Win (but I don't know how much dependencies has this solution - does it depend on exact terminal syntax?): https://stackoverflow.com/questions/2083412/detect-if-ipv6-is-enabled-on-windows-machines

Related to https://github.com/ledgerwatch/erigon/issues/6034#issuecomment-1325596391 , https://github.com/ledgerwatch/erigon/issues/6067 , https://github.com/ledgerwatch/erigon/pull/6093

**Comment by revitteth** [comment]
Hotfix erigon-lib PR: https://github.com/ledgerwatch/erigon-lib/pull/745

**Comment by revitteth** [comment]
Hotfix merged - closing and will pursue more complete solution on another issue.

**Comment by anonymous-sushi** [comment]
Hotfix did not work on linux server, hetzner still pinging

**Comment by AskAlexSharov** [comment]
We don’t know why. Hetzner doesn’t give any details.

**Comment by anonymous-sushi** [comment]
> We don’t know why. Hetzner doesn’t give any details.

Well Hetzner does give you a netscan table of ip:ports scanned. I am not too familiar with what is going on with the need to scan ips but is there a way to just provide Erigon with a set list of safe ips to peer from instead of searching random addresses? or throttle the amount of ips it scans in a short time.

**Comment by AskAlexSharov** [comment]
1. we have no proofs that such fixed list will help. FYI:
- one set of peers: p2p
- another set of peers: lightclient (embedded CL)
- another sett of peers: bittorent  

2. also erigon does bind many ports:  https://github.com/ledgerwatch/erigon#default-ports-and-protocols--firewalls

**Comment by anonymous-sushi** [comment]
looks like most of the netscan provided by hetzner was from port 4000

**Comment by AskAlexSharov** [comment]
Good to kwon. 
4000 - it's internal CL. This is new part of Erigon. Let's investigate...
CC: @Giulio2002 @revitteth

**Comment by revitteth** [comment]
@anonymous-sushi do you have a copy of the information from Hetzner? I'd be interested to see the detail there.

**Comment by revitteth** [comment]
Adding some context, the slightly vague warning message from Hetzner:
![image](https://user-images.githubusercontent.com/693995/204265179-1679a75e-e4fd-471c-b52d-f2d174dac165.png)

**Comment by revitteth** [comment]
ok update on this one - our list of private IP ranges isn't adequate for Hetzner: https://community.hetzner.com/tutorials/block-outgoing-traffic-to-private-networks

In this case I think we should probably provide a flag which allows these ranges to be included. @AskAlexSharov do you have any thoughts on this?

**Comment by revitteth** [comment]
In response to my own question, we already provide some advice on running on Hetzner https://github.com/ledgerwatch/erigon#default-ports-and-protocols--firewalls here. I believe if the firewall rules are setup to block outbound traffic as in the article in my last comment, that should be sufficient to run on Hetzner without warnings. It doesn't seem like we should be putting in code to cater for this.

**Comment by revitteth** [comment]
@anonymous-sushi @AskAlexSharov do we have any update on whether the above updates to firewall rules worked?

**Comment by anonymous-sushi** [comment]
> @anonymous-sushi @AskAlexSharov do we have any update on whether the above updates to firewall rules worked?

works fine for me, no issues
