### ISSUE TITLE
trace_block incorrectly marks top-level traces as having an error

### ISSUE THREAD

**Issue by henryperson** [ledgerwatch/erigon#6125]
### Version
Recently I have been using erigon through a node provider so I'm not actually sure what version they're running. But I have good reason to believe this issue was happening on `v2022.09.01`.

### Description
Sometimes, for a very short period after a block has been seen by a node (haven't timed it, but guessing it's <100ms), `trace_block` will report that certain top-level traces are errored when they are not actually errored. Subtraces of that top-level trace will be missing as a result. That is how I first noticed the issue—I had a script listening for new blocks, and noticed that I was missing traces. I was able to reliably reproduce the issue with a simple script that listens for new blocks, runs `trace_block`, waits 30 seconds, runs `trace_block` again, and then compares the number of results (though I believe a mismatch in the number of results is a symptom of incorrectly tracing the block). The issue happens about 4% of the time, so if you run a script that does this for 15 mins you're >95% to see this issue.

As a part of my current project I have been running a script that listens for blocks, runs `trace_block`, and stores the result in a database for months. I did some digging into our data and found that this issue started after Sep 15 of this year. So I believe this was introduced with the merge.

### Reproducing
Below is a zip file with a couple files that can help for debugging (can't upload .go and .json files apparently). The first is a simple go script that will reproduce the issue using the method I described above. You can run it with `ETHEREUM_WS_URL=your_erigon_ws go run main.go`. The other two files are from block 16020424 containing every trace result from the initial trace_block (which had an incomplete result) and the later trace_block (which has the correct result). As you can see the top level trace for the first transaction in the block is considered "Reverted" by the initial trace_block but later was changed to null. [That transaction](https://etherscan.io/tx/0xd98711dcb42595e12465cd9d696c239a4e32184a77f43c8479e99faf213bf8a1) did not revert.

[trace_block_materials.zip](https://github.com/ledgerwatch/erigon/files/10085207/trace_block_materials.zip)

**Comment by quickchase** [comment]
Chase from QuickNode here, this issue happens on recent releases as well. There are multiple customers reporting similar behavior from our nodes. We have reproduced this issue on single instances.

Traces will be wrong one minute, correct the next. It's difficult to reproduce but not impossible. The behavior feels like a race condition or similar is being hit and is not directly isolated to the latest block.

One customer is tracing `blocknumber - 10` and then re-tracing later and finding different results as well.

There is definitely a bug somewhere causing incorrect traces to be returned randomly.

**Comment by J-A-M-E-5** [comment]
I understand Erigon is a new project and I am impressed with its performance so far. It concerns me the lack of feedback or acceptance of this bug. I'm switching to use Geth for my project and Erigon for just archival data. I wanted to use Erigon to keep up with the chain head but I can't handle a scenario such as this as I need to do realtime transaction tracing, and lack of any action or just a "has been noted" concerns me.

**Comment by quickchase** [comment]
In defense of the Erigon team:

Part of the problem is that it's incredibly hard to reproduce at will on any given system for any given block. If y'all have scripts that can make it easier to debug please share.

I know there is a go script attached but it took hours to reproduce it once for me, across half a dozen nodes. It seems to happen on some nodes more than others, etc.

I know @AlexeyAkhunov tried to reproduce for a few hours and failed. It's not easy to debug... 😔

**Comment by J-A-M-E-5** [comment]
> I know @AlexeyAkhunov tried to reproduce for a few hours and failed. It's not easy to debug... 😔

That's good to know. Just somebody even informally commenting that earlier would at least let the casual reader know that something is being done, perhaps even encourage more people to get involved in trying to find a repeatable way to reproduce this bug. The hive mind...

Thanks, I will be monitoring progress of this bug and will try and reproduce.

**Comment by cyril-kit** [comment]
Thank you for the updates! If I find a way to reproduce too, I will share here.

**Comment by tjayrush** [comment]
I have no idea if this helps or not, but we've seen similar issues to this for years not only on load-balances access to the nodes through providers such as Infura and QuickNode, but even on our own nodes. The front of the chain is unsettled. What we do is have three levels of "finality" to our extracted blocks: "unripe", "staged", and "final."

Final is arbitrarily old but at least a few hours. We never re-visit final blocks.

Staged is at least 28 blocks old (six minutes) and we revisit them one more time before we make them final.

Unripe is anything under 28 blocks old and get revisited every 12 seconds until they become 28 blocks old.

I'm not sure why scripts were working prior to a certain release and stopped after, but I'm not surprised that the head of the chain is unsettled.

Maybe Erigon changed something that increased the likelyhood of a re-org deeper into the history higher. That wouldn't break consensus, but it would manifest itself in this way if the extraction script was getting too close to the head of the chain.

Again, not sure that helps, but for people reading this in the future, it may give some context.

**Comment by quickchase** [comment]
From my perspective I don't think this is related to re-orgs. This can happen on older blocks, I believe it's a concurrency issue or some kind of race condition. You call it one second it's fine, the next it's wrong, the next it's fine.

@AlexeyAkhunov mentioned that maybe it's due to shared memory access but idk. Really need a way to reproduce reliably.

**Comment by J-A-M-E-5** [comment]
> From my perspective I don't think this is related to re-orgs.

Agree. If it were re-orgs you'd see the re-org in the logs.

> What we do is have three levels of "finality" to our extracted blocks: "unripe", "staged", and "final."

From a UX point of view informing a user they have received a ERC-20 token twice or in a block that subsequently changes is a bit sucky when dealing with a re-org, but a re-org is something the user understands or can Google. It happens. In a very rare case such as a network attack we might see a freeze or a longer re-org. In any case, it's not my fault if the user or my client asks - it's Vitalik's, it's how blockchains work... deal with it!

However expecting to wait 28 blocks for some sort of finality due to "we are using Erigon so have to wait 28 blocks" is something else.  In my case my clients reaction will be "Why didn't you use geth?" or "You told me we could do this all on my 4TB SSD and you told me Erigon was good. I can't afford a 15TB SSD for geth, project cancelled". It was my fault for choosing Erigon.

**Comment by henryperson** [comment]
For those looking at this for a solution—I meant to write in my original comment how I had handled this but reading it again I am realizing it's not at all clear.

Since the issue is with top-level traces being marked as errored, you can compare the `error` field on top-level traces (non-nil transaction hash + empty `traceAddress`) to the `status` field from the receipt for that transaction. If, for any transactions, `receipt.status == 1 && trace.error != nil` or `receipt.status == 0 && trace.error == nil` then you have run into this issue. Throw an error and try fetching the block again.

Of course I agree that it would be better if this issue were solved. But practically, in the short term, if someone is blocked because of this issue hopefully this helps.

**Comment by AlexeyAkhunov** [comment]
If anyone manages to reproduce it on Eth main net, please post here the query, the incorrect response you got, and IMPORTANTLY, the timestamp of when request/response was made. This may help us reproduce it

**Comment by henryperson** [comment]
I ran into this issue again, but on polygon mainnet and—more interestingly—the block is from over a year ago and I am consistently getting this response.

It is happening on the following blocks/transactions:
- [22117271](https://polygonscan.com/block/22117271) due to [this transaction](https://polygonscan.com/tx/0x05cbef5a8980f673b28b12a1eea96d73e13acf0d19c398fcced3c2ebf3ba31fb)
- [22117799](https://polygonscan.com/block/22117799) due to [this transaction](https://polygonscan.com/tx/0x887a01b4f85b4557e0c73a02907b36ae9e187f589853f0825a3dc23348603e62)
- [22117897](https://polygonscan.com/block/22117897) due to [this transaction](https://polygonscan.com/tx/0x3b59371018b75982a9849108d89eb3b513b80a099addc07ab8ea2f6b37826dcf)
- [22118052](https://polygonscan.com/block/22118052) due to [this transaction](https://polygonscan.com/tx/0x169c9547db18171c33e4461722dd09f1b47e28ee00420527d06dd4974a4d9161)
- [22118179](https://polygonscan.com/block/22118179) due to [this transaction](https://polygonscan.com/tx/0x609f5d91c3a8b1271f27e492cabb132a565cbc8219741e5d3099df092429266e)
- [22118482](https://polygonscan.com/block/22118482) due to [this transaction](https://polygonscan.com/tx/0x6298cf24504ba7d6295f04be092e636a541912c0075eb24a1a8c2895516ab0c0)
- [22118680](https://polygonscan.com/block/22118680) due to [this transaction](https://polygonscan.com/tx/0xa6b955dce604e9bb554bd1fb5b0cdc4886b163124af8470de668c44af070599f)
- [22119912](https://polygonscan.com/block/22119912) due to [this transaction](https://polygonscan.com/tx/0xcc8c56431cba2ca7c78015d7f1ae340e56eb27d96ea37d54a63ed5686c2dafe4)
- [22127201](https://polygonscan.com/block/22127201) due to [this transaction](https://polygonscan.com/tx/0x3e8bedbd96bb309dc5a150dc24db21dc96311a06c8ac5b7b34584042ddc6a9a9)
- [22127286](https://polygonscan.com/block/22127286) due to [this transaction](https://polygonscan.com/tx/0xe1e3a93bd909a2298c0609ccbb7760d18cf27096940a58373282893b7fc7b36f)
- [22127584](https://polygonscan.com/block/22127584) due to [this transaction](https://polygonscan.com/tx/0xe955af346ad0e381300173bb293027430053b6dec76d89372e0d3d1ffcba549d)
- [22132260](https://polygonscan.com/block/22132260) due to [this transaction](https://polygonscan.com/tx/0x898b037aadb132ac659490381fcc23543fdc70da1c775d39b8b3c6fb1507a09f)
- [22132594](https://polygonscan.com/block/22132594) due to [this transaction](https://polygonscan.com/tx/0xc6158fa40417824d3fb16da6c602fc494b459188c26911afd61023f4af876283)

If this is likely to be a separate issue let me know and I can make a new issue for it

**Comment by qk-santi** [comment]
Keeping it alive

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Any way to reopen this? 😬
