### ISSUE TITLE
Use of the erigon bsc mainnet and testnet synchronisation

### ISSUE THREAD

**Issue by Liamlu28** [ledgerwatch/erigon#6127]
I have two VMs that need to use ergon to synchronize the test network and the main network of the bsc chain with the following command. The version is erigon v2.30.0

### Mainnet command
ExecStart=/home/erigon/blockchain/erigon/build/bin/erigon --datadir /data/bsc-data --private.api.addr=localhost:9090 --networkid 65 --nat any --chain=bsc --staticpeers enode://22455eaa4eaf4c12dc2386840a590fdc632ef669f86a8e1adf8d1421ca2c2f69d6cef6ecc8b976f945d1fcbc3c8181edf75494b1ecb28eaf15f8b21413644385@54.217.65.254:30311,enode://c6e730d262ee0fe4e747423708c1553798c2d04e6002c3e29dc3cb46ef264f35e982ba1351d74a9cbff7c6da2b268c80bee62f8f27006b375639958cb2c28e26@3.114.158.196:30311,enode://1841077024720c251f58e6eeb10c2a3846db3610b2f4e8210e7035d0623f4ab6caef94c3bf215cb548e7c7e41d2755da33b63685de425e07aeb5cef017ea8cb5@52.51.36.24:30311,enode://d509ceb8272be80280cc8a8dd9cd01f99b2ba37c611218476794d61fc08b114f30031e1a9eb95ae1323e354b6f2f4d2a9bfb7207a48ef1b4fb84182ab21d1a89@52.213.84.200:30311,enode://d257b0f8d362161bb4a18b13253b1f6abb273a89d85fed73458f84dbf52d14ce556fd32ac07cbc49cd69d99c03ceddeccab919e10351c9d4e795a4c36404aef7@3.218.112.8:30311,enode://eab705bab55816ad0a39ac2080d413fc337117413f76eb5bbf4505edf7545eaed13b7562657310831b86a2ea1e04ee34c8fce8eb19cca2aaeb6ddd61759e68fb@35.72.50.231:30311,enode://2523b1dfdd9a70aa806fd558eebf7e6dbe90882178a4eb0325336277e415e44cef1aae8ecf494313f43b9eabae4416ac7b7281af027763af26cb821d63ae844e@54.247.157.151:30311,enode://38144f02adbe8817b2b0f241f921491bc612dd8cd603fa9cd3faa31c76697ad5e00297cba38d0a8f594752c56c9a7e84f53d7f71c0b37b5680cea5e732b6b946@34.243.164.24:30311,enode://2aadea249d51e076060c97cbc293a2d90052d1786062f137aa8f4afe06996b674ecdbe660d3033b3d46d9cdaf2c3e3db6c031e218edc5a2613caa7f9705774f9@34.193.176.125:30311,enode://7cf8161c39e500f91d0311ad639d87fe52e938e6f3e64f381b0f0bb6f1f24161c65b548e406853e7e3c684bf65fe39d7aa8350b62106da91a301ef2044a78208@35.75.218.3:30311,enode://bcccac7dfbd21bd1dbbb7bf64ef7af6986520091f00320905e5919d12167fc8c94698099946933747ad2ea24745d35ebc980f9ba1475a839c83574d5ccf318d9@34.196.94.250:30311,enode://e8a97e90dae05940a04a37ddad445b1d1f270e1a0ec1caf31f77ecd9a664db3c0f4750914afbb6f017d214ecef4a5f991b2f16987a76ec38ceb06f7f8f2f9f76@52.17.96.222:30311,enode://4b79ca4c3457c689edd4d1739a8bd0b0e410824ef4f177db574c7f854404b4728c21a832378ef4d754901c1fd20d3c491325adecff1f6ffa79f511c59ab5b4ab@18.200.9.45:30311,enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@13.114.81.214:30311 --prune=disabled

### Mainnet  logs report error
```
Nov 25 06:13:22 geth-02 root[360712]: [INFO] [11-25|06:13:22.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:13:42 geth-02 root[360712]: [INFO] [11-25|06:13:42.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:13:42 geth-02 root[360712]: [INFO] [11-25|06:13:42.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:13:53 geth-02 root[360712]: [INFO] [11-25|06:13:53.774] [p2p] GoodPeers                          eth66=0
Nov 25 06:14:02 geth-02 root[360712]: [INFO] [11-25|06:14:02.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:14:02 geth-02 root[360712]: [INFO] [11-25|06:14:02.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
^ANov 25 06:14:21 geth-02 root[360712]: [INFO] [11-25|06:14:21.684] [txpool] stat                            block=19999999 pending=1 baseFee=0 queued=19 alloc=2.7GB sys=3.4GB
Nov 25 06:14:22 geth-02 root[360712]: [INFO] [11-25|06:14:22.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:14:22 geth-02 root[360712]: [INFO] [11-25|06:14:22.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:14:42 geth-02 root[360712]: [INFO] [11-25|06:14:42.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:14:42 geth-02 root[360712]: [INFO] [11-25|06:14:42.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:15:01 geth-02 CRON[361115]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 25 06:15:02 geth-02 root[360712]: [INFO] [11-25|06:15:02.476] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:15:02 geth-02 root[360712]: [INFO] [11-25|06:15:02.476] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
^ANov 25 06:15:21 geth-02 root[360712]: [INFO] [11-25|06:15:21.684] [txpool] stat                            block=19999999 pending=1 baseFee=0 queued=19 alloc=2.5GB sys=3.4GB
Nov 25 06:15:22 geth-02 root[360712]: [INFO] [11-25|06:15:22.476] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:15:22 geth-02 root[360712]: [INFO] [11-25|06:15:22.476] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:15:42 geth-02 root[360712]: [INFO] [11-25|06:15:42.476] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:15:42 geth-02 root[360712]: [INFO] [11-25|06:15:42.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:15:53 geth-02 root[360712]: [INFO] [11-25|06:15:53.774] [p2p] GoodPeers                          eth66=0
Nov 25 06:16:02 geth-02 root[360712]: [INFO] [11-25|06:16:02.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:16:02 geth-02 root[360712]: [INFO] [11-25|06:16:02.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
^ANov 25 06:16:21 geth-02 root[360712]: [INFO] [11-25|06:16:21.683] [txpool] stat                            block=19999999 pending=1 baseFee=0 queued=19 alloc=2.7GB sys=3.4GB
Nov 25 06:16:22 geth-02 root[360712]: [INFO] [11-25|06:16:22.477] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:16:22 geth-02 root[360712]: [INFO] [11-25|06:16:22.477] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
Nov 25 06:16:42 geth-02 root[360712]: [INFO] [11-25|06:16:42.476] [2/16 Headers] No block headers to write in this log period block number=19999999
Nov 25 06:16:42 geth-02 root[360712]: [INFO] [11-25|06:16:42.476] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
```

### TestNet start command 
 /home/erigon/blockchain/erigon/build/bin/erigon --datadir /data/chapel-bsc-data --private.api.addr=localhost:9091 --nat any --chain=chapel --http.port=8545 --http.addr=0.0.0.0

### Testnet LOGS
Nov 25 06:18:54 bsc-testnent root[2100]: [INFO] [11-25|06:18:54.350] [p2p] GoodPeers                          eth66=2
Nov 25 06:18:54 bsc-testnent root[2100]: [INFO] [11-25|06:18:54.372] [txpool] stat                            block=0 pending=0 baseFee=0 queued=0 alloc=748.0MB sys=2.0GB
Nov 25 06:18:54 bsc-testnent root[2100]: [INFO] [11-25|06:18:54.384] [2/16 Headers] No block headers to write in this log period block number=9070080
Nov 25 06:19:14 bsc-testnent root[2100]: [INFO] [11-25|06:19:14.384] [2/16 Headers] Wrote block headers       number=9073152 blk/second=153.600 alloc=860.2MB sys=2.0GB
Nov 25 06:19:34 bsc-testnent root[2100]: [INFO] [11-25|06:19:34.384] [2/16 Headers] Inserting headers         progress=9084608 queue=1
Nov 25 06:19:54 bsc-testnent root[2100]: [INFO] [11-25|06:19:54.372] [txpool] stat                            block=0 pending=0 baseFee=0 queued=0 alloc=868.5MB sys=2.0GB
Nov 25 06:19:54 bsc-testnent root[2100]: [INFO] [11-25|06:19:54.383] [2/16 Headers] Wrote block headers       number=9099264 blk/second=1305.600 alloc=868.9MB sys=2.0GB
Nov 25 06:19:55 bsc-testnent root[2100]: [INFO] [11-25|06:19:55.755] [parlia] snapshots build, gather headers block=9100000
Nov 25 06:19:55 bsc-testnent root[2100]: [INFO] [11-25|06:19:55.755] [parlia] snapshots build, recover from headers block=9100000
Nov 25 06:20:14 bsc-testnent root[2100]: [INFO] [11-25|06:20:14.383] [2/16 Headers] Inserting headers         progress=9150794 queue=1

Are the commands and logs I'm using appropriate?Thanks

**Comment by AskAlexSharov** [comment]
- mainnet - node synced already? Or you just started? If just started - can you please start from scratch on same v2.30.0 version
- testnet - i think you are fine

**Comment by Liamlu28** [comment]
> * mainnet - node synced already? Or you just started? If just started - can you please start from scratch on same v2.30.0 version
> * testnet - I think you are fine

I've deleted BSC mainnet data and have been running a new node.

### New nodes LOGS

Nov 28 22:27:51 bsc-mainnet root[6033]: [WARN] [11-28|22:27:51.405] Could not send beacon block to ETH1      err="not a proof-of-stake chain"
Nov 28 22:28:07 bsc-mainnet root[6033]: [INFO] [11-28|22:28:07.790] [1/16 Snapshots] download                progress="0.05% 269.2MB/533.4GB" download-time-left=351hrs:2m total-download-time=12m20s download=442.4KB/s upload=0B/s
Nov 28 22:28:07 bsc-mainnet root[6033]: [INFO] [11-28|22:28:07.790] [1/16 Snapshots] download                peers=83 connections=193 files=129 alloc=605.2MB sys=967.8MB
Nov 28 22:28:27 bsc-mainnet root[6033]: [INFO] [11-28|22:28:27.776] [1/16 Snapshots] download                progress="0.05% 282.2MB/533.4GB" download-time-left=231hrs:22m total-download-time=12m40s download=671.2KB/s upload=0B/s
Nov 28 22:28:27 bsc-mainnet root[6033]: [INFO] [11-28|22:28:27.778] [1/16 Snapshots] download                peers=83 connections=206 files=129 alloc=444.3MB sys=967.8MB
Nov 28 22:28:27 bsc-mainnet root[6033]: [INFO] [11-28|22:28:27.956] [p2p] GoodPeers                          eth66=0
Nov 28 22:28:47 bsc-mainnet root[6033]: [INFO] [11-28|22:28:47.757] [txpool] stat                            block=0 pending=0 baseFee=0 queued=0 alloc=438.6MB sys=967.8MB
Nov 28 22:28:47 bsc-mainnet root[6033]: [INFO] [11-28|22:28:47.764] [LightClient] P2P                        peers=4
Nov 28 22:28:47 bsc-mainnet root[6033]: [INFO] [11-28|22:28:47.776] [1/16 Snapshots] download                progress="0.05% 282.2MB/533.4GB" download-time-left=231hrs:22m total-download-time=13m0s download=671.2KB/s upload=0B/s
Nov 28 22:28:47 bsc-mainnet root[6033]: [INFO] [11-28|22:28:47.776] [1/16 Snapshots] download                peers=83 connections=206 files=129 alloc=439.1MB sys=967.8MB
Nov 28 22:29:03 bsc-mainnet root[6033]: [EROR] [11-28|22:29:03.493] [NewPayload] not a proof-of-stake chain
Nov 28 22:29:03 bsc-mainnet root[6033]: [WARN] [11-28|22:29:03.494] Could not send beacon block to ETH1      err="not a proof-of-stake chain"
Nov 28 22:29:07 bsc-mainnet root[6033]: [INFO] [11-28|22:29:07.776] [1/16 Snapshots] download                progress="0.06% 300.5MB/533.4GB" download-time-left=194160hrs:41m total-download-time=13m20s download=819B/s upload=0B/s
Nov 28 22:29:07 bsc-mainnet root[6033]: [INFO] [11-28|22:29:07.778] [1/16 Snapshots] download                peers=87 connections=223 files=129 alloc=515.1MB sys=967.8MB
Nov 28 22:29:15 bsc-mainnet root[6033]: [EROR] [11-28|22:29:15.828] [NewPayload] not a proof-of-stake chain
Nov 28 22:29:15 bsc-mainnet root[6033]: [WARN] [11-28|22:29:15.828] Could not send beacon block to ETH1      err="not a proof-of-stake chain"
Nov 28 22:29:27 bsc-mainnet root[6033]: [INFO] [11-28|22:29:27.776] [1/16 Snapshots] download                progress="0.06% 300.5MB/533.4GB" download-time-left=194160hrs:41m total-download-time=13m40s download=819B/s upload=0B/s
Nov 28 22:29:27 bsc-mainnet root[6033]: [INFO] [11-28|22:29:27.776] [1/16 Snapshots] download                peers=87 connections=223 files=129 alloc=562.1MB sys=967.8MB

**Comment by AskAlexSharov** [comment]
See also: —torrent.download.rate

**Comment by Liamlu28** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/3294496/205483820-349f564f-9536-4238-8f7f-e91645f10798.png">
Is it normal status?
