### ISSUE TITLE
Dumping txs ?

### ISSUE THREAD

**Issue by marshalys** [ledgerwatch/erigon#6132]
what does "Dumping txs" meaning?
why it's so slow?
how can I speed up?

thx！

log:

[INFO] [11-25|10:10:13.289] [snapshots] Dumping txs                  block num=15002988 alloc=4.3GB sys=14.7GB
[INFO] [11-25|10:10:34.356] [snapshots] Dumping txs                  block num=15005086 alloc=4.1GB sys=14.7GB
[INFO] [11-25|10:10:54.757] [snapshots] Dumping txs                  block num=15007102 alloc=5.7GB sys=14.7GB
[INFO] [11-25|10:11:13.654] [snapshots] Dumping txs                  block num=15008973 alloc=5.2GB sys=14.7GB
[INFO] [11-25|16:48:23.411] [snapshots] Dumping txs                  block num=15012595 alloc=4.2GB sys=9.5GB
[INFO] [11-25|16:48:43.036] [snapshots] Dumping txs                  block num=15014306 alloc=6.3GB sys=9.5GB
[INFO] [11-25|16:49:02.788] [snapshots] Dumping txs                  block num=15016162 alloc=3.0GB sys=9.8GB
[INFO] [11-25|16:49:22.201] [snapshots] Dumping txs                  block num=15017861 alloc=3.8GB sys=9.8GB
[INFO] [11-25|16:49:41.958] [snapshots] Dumping txs                  block num=15019496 alloc=5.1GB sys=9.8GB
[INFO] [11-25|17:15:10.780] [snapshots] Dumping txs                  block num=15022573 alloc=3.4GB sys=9.8GB
[INFO] [11-25|17:15:28.992] [snapshots] Dumping txs                  block num=15023861 alloc=5.1GB sys=9.8GB
[INFO] [11-25|17:15:50.231] [snapshots] Dumping txs                  block num=15025446 alloc=3.2GB sys=9.8GB
[INFO] [11-25|17:16:08.828] [snapshots] Dumping txs                  block num=15027122 alloc=3.9GB sys=9.8GB
[INFO] [11-25|17:16:28.759] [snapshots] Dumping txs                  block num=15028719 alloc=4.7GB sys=9.8GB
[INFO] [11-25|17:27:15.133] [snapshots] Dumping txs                  block num=15032213 alloc=3.6GB sys=9.8GB
[INFO] [11-25|17:27:35.123] [snapshots] Dumping txs                  block num=15033769 alloc=5.5GB sys=9.8GB
[INFO] [11-25|17:27:56.907] [snapshots] Dumping txs                  block num=15035256 alloc=3.5GB sys=9.8GB
[INFO] [11-25|17:28:14.782] [snapshots] Dumping txs                  block num=15036838 alloc=4.2GB sys=9.8GB
[INFO] [11-25|17:28:34.773] [snapshots] Dumping txs                  block num=15038569 alloc=4.9GB sys=9.8GB
[INFO] [11-25|17:39:14.583] [snapshots] Dumping txs                  block num=15042361 alloc=4.8GB sys=10.0GB
[INFO] [11-25|17:39:35.456] [snapshots] Dumping txs                  block num=15043869 alloc=4.2GB sys=10.0GB
[INFO] [11-25|17:39:54.582] [snapshots] Dumping txs                  block num=15045755 alloc=5.1GB sys=10.0GB
[INFO] [11-25|17:40:16.025] [snapshots] Dumping txs                  block num=15047053 alloc=3.7GB sys=10.0GB
[INFO] [11-25|17:40:34.585] [snapshots] Dumping txs                  block num=15048584 alloc=4.3GB sys=10.0GB
[INFO] [11-25|17:40:56.393] [snapshots] Dumping txs                  block num=15049943 alloc=5.0GB sys=10.0GB
[INFO] [11-25|17:51:26.292] [snapshots] Dumping txs                  block num=15052902 alloc=4.5GB sys=5.0GB
[INFO] [11-25|17:51:44.744] [snapshots] Dumping txs                  block num=15055006 alloc=4.2GB sys=5.1GB
[INFO] [11-25|17:52:04.746] [snapshots] Dumping txs                  block num=15057046 alloc=2.8GB sys=5.2GB
[INFO] [11-25|17:52:24.744] [snapshots] Dumping txs                  block num=15059207 alloc=3.7GB sys=5.2GB
[INFO] [11-25|18:01:00.878] [snapshots] Dumping txs                  block num=15063694 alloc=3.1GB sys=5.8GB
[INFO] [11-25|18:01:23.019] [snapshots] Dumping txs                  block num=15066268 alloc=4.1GB sys=5.8GB
[INFO] [11-25|18:01:42.359] [snapshots] Dumping txs                  block num=15068664 alloc=2.7GB sys=6.1GB
[INFO] [11-25|18:10:04.465] [snapshots] Dumping txs                  block num=15073243 alloc=3.1GB sys=6.2GB
[INFO] [11-25|18:10:23.039] [snapshots] Dumping txs                  block num=15075454 alloc=3.8GB sys=6.2GB
[INFO] [11-25|18:10:44.451] [snapshots] Dumping txs                  block num=15077890 alloc=4.9GB sys=6.5GB
[INFO] [11-25|18:11:03.039] [snapshots] Dumping txs                  block num=15079825 alloc=3.2GB sys=6.6GB
[INFO] [11-25|18:20:13.519] [snapshots] Dumping txs                  block num=15083121 alloc=2.7GB sys=6.6GB
[INFO] [11-25|18:20:34.678] [snapshots] Dumping txs                  block num=15084689 alloc=3.6GB sys=6.6GB
[INFO] [11-25|18:20:53.520] [snapshots] Dumping txs                  block num=15087090 alloc=2.7GB sys=6.6GB
[INFO] [11-25|18:21:13.522] [snapshots] Dumping txs                  block num=15089485 alloc=3.6GB sys=6.6GB
[INFO] [11-25|18:30:03.009] [snapshots] Dumping txs                  block num=15092802 alloc=4.9GB sys=6.6GB
[INFO] [11-25|18:30:22.586] [snapshots] Dumping txs                  block num=15094768 alloc=3.3GB sys=6.6GB
[INFO] [11-25|18:30:41.597] [snapshots] Dumping txs                  block num=15096853 alloc=4.2GB sys=6.6GB
[INFO] [11-25|18:31:02.166] [snapshots] Dumping txs                  block num=15098611 alloc=3.2GB sys=6.6GB
[INFO] [11-25|19:16:19.157] [snapshots] Dumping txs                  block num=15103976 alloc=4.6GB sys=4.9GB
[INFO] [11-25|19:16:40.822] [snapshots] Dumping txs                  block num=15106752 alloc=3.2GB sys=5.0GB
[INFO] [11-25|19:17:00.171] [snapshots] Dumping txs                  block num=15108806 alloc=3.9GB sys=5.0GB
[INFO] [11-25|19:17:20.079] [snapshots] Dumping txs                  block num=15111002 alloc=2.6GB sys=5.0GB
[INFO] [11-25|19:17:39.151] [snapshots] Dumping txs                  block num=15113545 alloc=3.4GB sys=5.0GB
[INFO] [11-25|19:18:01.999] [snapshots] Dumping txs                  block num=15116447 alloc=4.4GB sys=5.0GB
[INFO] [11-25|19:18:19.201] [snapshots] Dumping txs                  block num=15118727 alloc=3.8GB sys=5.4GB
[INFO] [11-25|19:18:39.154] [snapshots] Dumping txs                  block num=15121467 alloc=3.3GB sys=5.4GB
[INFO] [11-25|19:18:59.956] [snapshots] Dumping txs                  block num=15124317 alloc=4.1GB sys=5.4GB
[INFO] [11-25|19:19:19.154] [snapshots] Dumping txs                  block num=15127061 alloc=2.6GB sys=5.4GB
[INFO] [11-25|19:19:40.190] [snapshots] Dumping txs                  block num=15130123 alloc=3.5GB sys=5.4GB
[INFO] [11-25|19:20:00.615] [snapshots] Dumping txs                  block num=15132951 alloc=4.2GB sys=5.4GB
[INFO] [11-25|19:20:19.757] [snapshots] Dumping txs                  block num=15135435 alloc=5.0GB sys=5.4GB
[INFO] [11-25|19:20:39.330] [snapshots] Dumping txs                  block num=15138025 alloc=3.3GB sys=5.4GB
[INFO] [11-25|19:20:59.153] [snapshots] Dumping txs                  block num=15140599 alloc=3.9GB sys=5.4GB
[INFO] [11-25|19:21:22.203] [snapshots] Dumping txs                  block num=15142483 alloc=4.6GB sys=5.4GB
[INFO] [11-25|19:21:39.153] [snapshots] Dumping txs                  block num=15145176 alloc=3.0GB sys=5.4GB
[INFO] [11-25|19:21:59.863] [snapshots] Dumping txs                  block num=15147739 alloc=3.7GB sys=5.4GB
[INFO] [11-25|19:22:19.518] [snapshots] Dumping txs                  block num=15150326 alloc=4.4GB sys=5.4GB
[INFO] [11-25|19:22:40.291] [snapshots] Dumping txs                  block num=15153177 alloc=2.8GB sys=5.4GB
[INFO] [11-25|19:23:00.120] [snapshots] Dumping txs                  block num=15155669 alloc=3.5GB sys=5.4GB
[INFO] [11-25|19:23:21.022] [snapshots] Dumping txs                  block num=15158364 alloc=4.3GB sys=5.4GB
[INFO] [11-25|19:23:39.746] [snapshots] Dumping txs                  block num=15160951 alloc=2.6GB sys=5.4GB
[INFO] [11-25|19:23:59.155] [snapshots] Dumping txs                  block num=15163065 alloc=3.2GB sys=5.4GB
[INFO] [11-25|19:24:19.727] [snapshots] Dumping txs                  block num=15164997 alloc=3.8GB sys=5.4GB
[INFO] [11-25|19:24:39.154] [snapshots] Dumping txs                  block num=15167127 alloc=4.4GB sys=5.4GB
[INFO] [11-25|19:25:00.117] [snapshots] Dumping txs                  block num=15169768 alloc=2.8GB sys=5.4GB
[INFO] [11-25|19:25:19.852] [snapshots] Dumping txs                  block num=15172054 alloc=3.5GB sys=5.4GB
[INFO] [11-25|19:25:39.157] [snapshots] Dumping txs                  block num=15174575 alloc=4.2GB sys=5.4GB
[INFO] [11-25|19:25:59.154] [snapshots] Dumping txs                  block num=15177087 alloc=4.9GB sys=5.4GB
[INFO] [11-25|19:26:19.243] [snapshots] Dumping txs                  block num=15179622 alloc=3.2GB sys=5.4GB
[INFO] [11-25|19:26:39.526] [snapshots] Dumping txs                  block num=15182273 alloc=4.0GB sys=5.4GB
[INFO] [11-25|19:26:59.547] [snapshots] Dumping txs                  block num=15184901 alloc=4.7GB sys=5.4GB
[INFO] [11-25|19:27:19.153] [snapshots] Dumping txs                  block num=15187395 alloc=2.9GB sys=5.4GB
[INFO] [11-25|19:27:39.156] [snapshots] Dumping txs                  block num=15189518 alloc=3.6GB sys=5.4GB
[INFO] [11-25|19:27:59.706] [snapshots] Dumping txs                  block num=15192228 alloc=4.4GB sys=5.4GB
[INFO] [11-25|19:28:19.152] [snapshots] Dumping txs                  block num=15195201 alloc=2.7GB sys=5.4GB
[INFO] [11-25|19:28:39.156] [snapshots] Dumping txs                  block num=15197676 alloc=3.4GB sys=5.4GB
[INFO] [11-25|19:28:59.153] [snapshots] Dumping txs                  block num=15199733 alloc=4.0GB sys=5.4GB
[INFO] [11-25|21:15:03.102] [snapshots] Dumping txs                  block num=15202796 alloc=3.2GB sys=5.0GB
[INFO] [11-25|21:15:21.690] [snapshots] Dumping txs                  block num=15204777 alloc=4.0GB sys=5.0GB
[INFO] [11-25|21:15:41.417] [snapshots] Dumping txs                  block num=15207399 alloc=3.1GB sys=5.2GB
[INFO] [11-25|21:16:01.439] [snapshots] Dumping txs                  block num=15209258 alloc=4.1GB sys=5.3GB
[INFO] [11-25|21:16:21.428] [snapshots] Dumping txs                  block num=15211778 alloc=5.1GB sys=5.9GB
[INFO] [11-25|21:16:41.430] [snapshots] Dumping txs                  block num=15213800 alloc=3.7GB sys=5.9GB
[INFO] [11-25|21:17:01.418] [snapshots] Dumping txs                  block num=15215627 alloc=4.6GB sys=5.9GB
[INFO] [11-25|21:17:21.419] [snapshots] Dumping txs                  block num=15217763 alloc=3.1GB sys=5.9GB
[INFO] [11-25|21:17:41.417] [snapshots] Dumping txs                  block num=15220059 alloc=4.4GB sys=5.9GB
[INFO] [11-25|21:18:03.470] [snapshots] Dumping txs                  block num=15222022 alloc=3.8GB sys=5.9GB
[INFO] [11-25|21:18:21.419] [snapshots] Dumping txs                  block num=15224166 alloc=5.1GB sys=5.9GB
[INFO] [11-25|21:18:41.420] [snapshots] Dumping txs                  block num=15226840 alloc=3.9GB sys=5.9GB
[INFO] [11-25|21:19:01.433] [snapshots] Dumping txs                  block num=15229273 alloc=4.8GB sys=5.9GB
[INFO] [11-25|21:19:21.418] [snapshots] Dumping txs                  block num=15231673 alloc=3.5GB sys=5.9GB
[INFO] [11-25|21:19:41.419] [snapshots] Dumping txs                  block num=15233852 alloc=4.9GB sys=5.9GB
[INFO] [11-25|21:20:01.426] [snapshots] Dumping txs                  block num=15236516 alloc=3.5GB sys=5.9GB
[INFO] [11-25|21:20:21.422] [snapshots] Dumping txs                  block num=15239357 alloc=4.9GB sys=5.9GB
[INFO] [11-25|21:20:42.031] [snapshots] Dumping txs                  block num=15242278 alloc=3.9GB sys=5.9GB
[INFO] [11-25|21:21:01.450] [snapshots] Dumping txs                  block num=15244561 alloc=4.9GB sys=5.9GB
[INFO] [11-25|21:21:21.427] [snapshots] Dumping txs                  block num=15247257 alloc=3.1GB sys=5.9GB
[INFO] [11-25|21:21:41.418] [snapshots] Dumping txs                  block num=15250108 alloc=3.9GB sys=5.9GB
[INFO] [11-25|21:22:01.428] [snapshots] Dumping txs                  block num=15252503 alloc=4.5GB sys=5.9GB
[INFO] [11-25|21:22:23.306] [snapshots] Dumping txs                  block num=15254977 alloc=3.2GB sys=6.2GB
[INFO] [11-25|21:22:41.421] [snapshots] Dumping txs                  block num=15256697 alloc=3.7GB sys=6.2GB
[INFO] [11-25|21:23:01.422] [snapshots] Dumping txs                  block num=15258899 alloc=4.9GB sys=6.2GB
[INFO] [11-25|21:23:21.428] [snapshots] Dumping txs                  block num=15261295 alloc=3.3GB sys=6.2GB
[INFO] [11-25|21:23:41.634] [snapshots] Dumping txs                  block num=15263201 alloc=4.3GB sys=6.2GB
[INFO] [11-25|21:24:01.418] [snapshots] Dumping txs                  block num=15265782 alloc=5.1GB sys=6.2GB
[INFO] [11-25|21:24:21.832] [snapshots] Dumping txs                  block num=15267751 alloc=3.5GB sys=6.2GB
[INFO] [11-25|21:24:41.423] [snapshots] Dumping txs                  block num=15269780 alloc=4.1GB sys=6.2GB
[INFO] [11-25|21:25:01.728] [snapshots] Dumping txs                  block num=15271914 alloc=4.8GB sys=6.2GB
[INFO] [11-25|21:25:21.423] [snapshots] Dumping txs                  block num=15274352 alloc=2.9GB sys=6.2GB
[INFO] [11-25|21:25:41.426] [snapshots] Dumping txs                  block num=15276994 alloc=3.7GB sys=6.2GB
[INFO] [11-25|21:26:02.300] [snapshots] Dumping txs                  block num=15279159 alloc=4.4GB sys=6.2GB
[INFO] [11-25|21:26:21.747] [snapshots] Dumping txs                  block num=15280877 alloc=4.9GB sys=6.2GB
[INFO] [11-25|21:26:41.648] [snapshots] Dumping txs                  block num=15282369 alloc=2.8GB sys=6.2GB
[INFO] [11-25|21:27:01.421] [snapshots] Dumping txs                  block num=15284652 alloc=3.5GB sys=6.2GB
[INFO] [11-25|21:27:21.419] [snapshots] Dumping txs                  block num=15287040 alloc=4.2GB sys=6.2GB
[INFO] [11-25|21:27:41.780] [snapshots] Dumping txs                  block num=15289643 alloc=5.0GB sys=6.2GB
[INFO] [11-25|21:28:01.423] [snapshots] Dumping txs                  block num=15291895 alloc=3.1GB sys=6.2GB
[INFO] [11-25|21:28:21.429] [snapshots] Dumping txs                  block num=15293961 alloc=3.6GB sys=6.2GB
[INFO] [11-25|21:28:41.419] [snapshots] Dumping txs                  block num=15296070 alloc=4.4GB sys=6.2GB
[INFO] [11-25|21:29:01.419] [snapshots] Dumping txs                  block num=15298304 alloc=5.0GB sys=6.2GB

**Comment by AskAlexSharov** [comment]
It’s creation of new snapshot in background. You don’t need to speedup

**Comment by AskAlexSharov** [comment]
> my problem is I can't find the tx when the block number is not Dumping, why?

It must not happen, but can be a bug. Node creating snapshot for blocks: 15.0m-15.5m

you searching for some recent transaction:  16048368

likely snapshots are not related to your problem. 

1. Show other logs (without DumpingTx)
2. Show “make integration” “integration print_stages”
3. You still can’t find it?

**Comment by AskAlexSharov** [comment]
Your —prune flags?

**Comment by AskAlexSharov** [comment]
so. my advise: 
- wait for migration finish
- check that you still can't find that transaction
- stop erigon
- `make integration`
- `./build/bin/integration stage_tx_lookup --reset`
- `./build/bin/integration stage_tx_lookup`
- start erigon
