### ISSUE TITLE
erigon + lighthouse 

### ISSUE THREAD

**Issue by kledgold** [ledgerwatch/erigon#6172]
Hello, have you ever encountered the following situation

lighthouse：
{ code: -32000, message: "engine api should not be used, restart with --externalcl" }

erigon：
[EROR] [12-01|14:26:56.567] EXTERNAL CONSENSUS LAYER IS NOT ENABLED, PLEASE RESTART WITH FLAG --externalcl 
[WARN] [12-01|14:26:56.567] Served                                   conn=127.0.0.1:59398 method=engine_newPayloadV1 reqid=1 t=1.462061ms err="engine api should not be used, restart with --externalcl"

**Comment by kledgold** [comment]
I understand

**Comment by axiomatic-aardvark** [comment]
@kledgold how did you fix it?
