### ISSUE TITLE
Add flag on rpcdaemon for not limiting feecap

### ISSUE THREAD

**Issue by fabwa** [ledgerwatch/erigon#6174]
Re-Opening https://github.com/ledgerwatch/erigon/issues/5619

This prevents production usage..

**Comment by moraesjeremias** [comment]
Hey @AskAlexSharov what was the resolution on this and #5619? I'd like to know whether this feature was prioritized or not.? 
Thank you for your words on this case!

**Comment by AskAlexSharov** [comment]
@moraesjeremias we have flag —txpool.pricelimit 
Is it what you looking for?

**Comment by moraesjeremias** [comment]
Actually is the opposite @AskAlexSharov. See the diff bellow according to [geth-docs](https://geth.ethereum.org/docs/fundamentals/command-line-options) and compared to erigon client.

From Geth docs:
> --rpc.txfeecap value   (default: 1) Sets a cap on transaction fee (in ether) that can be sent via the RPC APIs (0 =no cap)

> --txpool.pricelimit value (default: 1) Minimum gas price limit to enforce for acceptance into the pool


From Erigon client help:
> --txpool.pricelimit value Minimum gas price (fee cap) limit to enforce for acceptance into the pool (default: 1)

Is that possible to be prioritized this implementation in Erigon? I appreciate your help!
