### ISSUE TITLE
BSC stuck at block header 23000000

### ISSUE THREAD

**Issue by unlimittt** [ledgerwatch/erigon#6185]
latest devel clone
erigon --chain=bsc --prune=htc

[2/16 Headers] No block headers to write in this log period block number=22999999

**Comment by AskAlexSharov** [comment]
maybe related to https://github.com/ledgerwatch/erigon/issues/6165

**Comment by ineron** [comment]
I have same problem
![Uploading ~ — root@uni-node-2etcsupervisord.d — ssh ◂ ssh node2 — bash 2022-12-03 18-16-27.png…]()

**Comment by temuera** [comment]
same problem+1

**Comment by egorFiNE** [comment]
same. 
Rel #5703, #6194, #6000 and others.

**Comment by Incrediblez7** [comment]
same problem at block number = 21510857

**Comment by temuera** [comment]
No block headers to write in this log period block number=23533399
