### ISSUE TITLE
Getting "allowing hasher to be garbage collected" when under heavy load

### ISSUE THREAD

**Issue by 0xStrobe** [ledgerwatch/erigon#6195]
I'm trying to sync an SQL database using a local Erigon's RPC endpoints, but I intermittently get the message "allowing hasher to be garbage collected". Whenever these messages appear, it seems that Erigon's performance drastically reduces.

Is it due to some resource allocation limits which I can hopefully increase manually? Erigon was not using up all the CPU or RAM (CPU about 50%, RAM 70%).

**Comment by AskAlexSharov** [comment]
It’s ok. Likely we must remove this log line, and probably switch to sync.Pool

**Comment by AskAlexSharov** [comment]
Here we go https://github.com/ledgerwatch/erigon/pull/6200

**Comment by 0xStrobe** [comment]
Niceee! Wen v2.31.0? <img height=18 src="https://user-images.githubusercontent.com/107649472/205485366-6ad5242c-cd2e-4e46-a540-f08d82688e6e.png" alt="up only llama" />
