### ISSUE TITLE
Error building binaries

### ISSUE THREAD

**Issue by alef-carvalho** [ledgerwatch/erigon#6246]
#### System information

Erigon version: 
2.30.0

OS & Version: 
Amazon Linux 2

Commit hash : 
-

#### Expected behaviour
Build and output Erigon binaries

#### Actual behaviour
Error building binaries: 

```sh 
../../eth/stagedsync/stage_mining_create_block.go:18:2: github.com/ledgerwatch/erigon-lib@v0.0.0-20221111035555-f9fe50d566fb: invalid version: unknown revision f9fe50d566fb
```

#### Steps to reproduce the behaviour

```sh
clone repository
run "make erigon" command
```

**Comment by AskAlexSharov** [comment]
go env
go version

likely you have disabled go modules
