### ISSUE TITLE
Switch Docker build to a `glibc` distro

### ISSUE THREAD

**Issue by cgst** [ledgerwatch/erigon#6255]
# Rationale

The current Docker build is based on `golang:1.19-alpine3.16`, which is optimized for size but considered experimental.

Quoting from the [Go project DockerHub](https://hub.docker.com/_/golang):
> ### `golang:<version>-alpine`
>This variant is highly experimental, and not officially supported by the Go project (see [golang/go#19938](https://github.com/golang/go/issues/19938) for details).
>
> The main caveat to note is that it does use [musl libc](https://musl.libc.org/) instead of [glibc and friends](https://www.etalabs.net/compare_libcs.html), which can lead to unexpected behavior. See [this Hacker News comment thread](https://news.ycombinator.com/item?id=10782897) for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

The libc implementation is of particular interest to Erigon users because MDBX makes extensive use of POSIX file locks for shared access. An example unexpected behavior arises when you combine a `glibc`-based database reader (e.g., a locally-built `cmd/hack`) with a `musl`-based writer that holds a non-exclusive lock (e.g., `thorax/erigon` Erigon daemon running in the same process namespace). The reader hangs even though MDBX and Erigon are designed to support this use case. The workaround is to rebuild the reader with `musl` (difficult on most dev workstations) or rebuild the writer with `glibc` (i.e., give up on the official Docker image).

Users are free to build Erigon in any number of ways, and those who are sensitive to the libc implementation can roll their own build. Nevertheless, it's reasonable to ask if the default/official Docker build should be based on `glibc` or `musl` libc. It is my personal view that `glibc` is more widely supported and leads to fewer surprises, which makes for a more sensible default.

# Implementation

Rebase the official [`Dockerfile`](https://github.com/ledgerwatch/erigon/blob/devel/Dockerfile) on a glibc distro, such as Bullseye (Debian). I've tried it locally and it's a small change.

# Considerations

- Alpine Linux images are optimized for size, so just about anything else we use will be bigger. For example, Debian's `bullseye-sim` base is [~30MB](https://hub.docker.com/_/debian/tags?page=1&name=bullseye-slim) vs Alpine's [~3MB](https://hub.docker.com/_/alpine/tags).
- Incompatibility goes both ways. It's conceivable others may expect or prefer a `musl`-based Erigon build.

**Comment by elee1766** [comment]
like abhishek mentioned on discord, would be best imo have both a debian based and alpine based image.

can keep the alpine based image as the default - won't break existing things

it seems the binaries are actually already build in glibc world? https://github.com/ledgerwatch/erigon/blob/devel/.goreleaser.yml 

not 100% sure on how erigon does their releases to dockerhub.

**Comment by cgst** [comment]
Maybe @timmyers can chime in?

**Comment by elee1766** [comment]
so `RUN adduser -D -u $UID -g $GID erigon` will need to be changed to something along the lines of `RUN adduser --uid $UID erigon`

i moved our erigon ci to a [public repo](https://gfx.cafe/images/erigon/-/tree/master/) and moved a node to run on the debian based image.

will report if i notice anything wrong with that node in comparison to our others. seems to be fine so far.
