### ISSUE TITLE
Depending on the timing transactions traces can be corrupted

### ISSUE THREAD

**Issue by cyril-kit** [ledgerwatch/erigon#6258]
So, I'm not sure if it's a bug but I'm running a data scraper on my own erigon full archive node. Depending on the state of the node, the traces that I'm extracting can hold the wrong information. I find that out later in my ETL processes.

Reextracting the traces that had the wrong information solve the issue. So, here is my question, how can I be sure that a block range is really finalized with a rpc query? Or is it a bug in erigon?

Thanks in advance for the support.

**Comment by AskAlexSharov** [comment]
eth_syncing has field currentBlock. Its equal to stageFinish

after node startup (after long downtime) first sync cycle may happen in > 1 db transacton (reader can see block in db but no trace indices yet). Then all sync cycles happen in 1 db transaction (reader always see consistent data).

**Comment by quickchase** [comment]
Could be related to #6125

**Comment by cyril-kit** [comment]
Thank you @quickchase and @AskAlexSharov ,
As Quickchase mention, I think that is the issue we faced. I had wrong status in my Traces (error instead of success) and sometime wrong value related to internal transaction in the traces too.

Also, when the node is syncing, I'm using the Finished stage height as the max height to extract. But when eth_syncing returns False, I'm relying on eth_blockNumber.

And thank you for explaining the sync cycle and db transaction. It helps me better understand the internal of Erigon. I'm thinking to become a contributor on this project at some point.
