### ISSUE TITLE
Memory Hog

### ISSUE THREAD

**Issue by guzkodes** [ledgerwatch/erigon#6265]
Erigon version: 2.31.0-stable-a53e8a3e

Erigon has been eating a lot of memory since the last two releases:

```
 PID       USER    RES   RSan   SHR   SWAP  %CPU  %MEM     TIME+         COMMAND
261960 erigon   11.1g   7.0g   4.0g      0         61.2      35.4       401:12.23   /usr/local/bin/erigon 
```

The top command shows It is eating ```7g``` of resident anonymous memory and ```4g``` of shareable memory (can be freed if needed)

Is there any configuration to limit this? The memory keeps growing and eventually the process is killed by the Linux OOM killer

**Comment by AskAlexSharov** [comment]
no total limit, but can try reduce some defaults
1. --batchSize=8mb
2. `--torrent.conns.perfile=4`
3. GOGC=50 GOMEMLIMIT=6000MiB https://tip.golang.org/doc/gc-guide

Also you can: 
add flag `--pprof`
`go tool pprof -inuse_space -png http://127.0.0.1:6060/debug/pprof/heap > mem.png`

Optionally: 
--txpool.disable

**Comment by guzkodes** [comment]
Thanks, will git it a try. But
```
--txpool.disable
```

Is a no go for staking, correct?

**Comment by AskAlexSharov** [comment]
Correct

**Comment by alysak6075** [comment]
Steps 1 & 3 stopped the node from crashing/being unresponsive during initial sync. Thank You!
