### ISSUE TITLE
Synchronization stopped on regular running with logs full of "Previously known bad block“ messages

### ISSUE THREAD

**Issue by nining** [ledgerwatch/erigon#6269]
#### System information

Erigon version: erigon version 2.31.0-stable-a53e8a3e

OS & Version: Linux Ubuntu 22.04.1 LTS

Commit hash : a53e8a3e

#### Expected behaviour
Normal synchronization

#### Actual behaviour
Synchronization stopped

#### Steps to reproduce the behaviour
Synchronization stopped on regular running
After restarting erigon process, the synchronization may resume.

#### Logs
When synchronization stopped, the logs are full of the following messages:

````
[WARN] [12-10|02:19:10.279] [NewPayload] Previously known bad block  hash=0xa4c6b5edda53540803cdf5b77a6a2c4e97b6d38776ea0b59d0d0129f1ecb3f02
[WARN] [12-10|02:19:10.516] [NewPayload] Previously known bad block  hash=0xa360ab9f974cf8d3b7fd70f6d10b866324860630ade81ede49e6d3ff7975f76b
````

**Comment by gitmewai** [comment]
Yes I have encountered similar issue and reported in #6217 with logs provided

**Comment by Stronzo-sky** [comment]
Hi. 

I`m running the latest release and it still happens to me very often - kinda once a day. Probably i have a bad pare of erigon and lighthouse - i dont know. But exactly after "Previously known bad block" erigon stucks. Just got another one (see the logs). Subscribed on #6269 and #6217 and qurious that none of the developers is even trying to answer :(. Also was ignored in discord erigon section. 

I restart both CL and EL and sync continues but without human interaction for just a stupid restart -- erigon + lighthouse are unable to continue sync.

[badblock.log](https://github.com/ledgerwatch/erigon/files/10217639/badblock.log)

**Comment by jasonyihk** [comment]
having the same issue on Mainnet:
```
[WARN] [12-19|18:06:04.071] [NewPayload] Previously known bad block  hash=0xa0e4366201fb1ba581c46d5451f3d8669bd12505f56203e1fa9d8c9c908f1009
[WARN] [12-19|18:06:13.141] [NewPayload] Previously known bad block  hash=0xa0e4366201fb1ba581c46d5451f3d8669bd12505f56203e1fa9d8c9c908f1009
```

**Comment by ekreutz** [comment]
I have the same issue on the mainnet. It's extremely concerning, I'm not sure if Erigon can be used in an enterprise environment at this point.

System:
- Ubuntu 20.04.5 LTS
- Erigon_2.31.0 (using prebuilt binary)
- Prysm 3.2.0

I'm not on the most recent Erigon version, but I guess the issue is relevant since other people experience it even on the latest version.

To me, it seems that the initial error that kicked things off was an empty block? That's the first error I'm seeing before shortly getting stuck not syncing.

Key log lines for discoverability:
```
[EROR] [12-26|03:15:37.644] [5/7 Execution] Empty block              blocknum=16266162
[WARN] [12-26|03:15:37.644] Removing beacon request due to           err="unsuccessful execution, progress 16266161 < expected 16266168" requestId=151816
[INFO] [12-26|03:15:37.816] [5/16 Bodies] Writing block bodies       block_num=16266167 remaining=0 alloc=3.5GB sys=7.7GB
[INFO] [12-26|03:15:38.547] [7/16 Execution] Completed on            block=16266167
[INFO] [12-26|03:15:41.542] Commit cycle                             in=503.990467ms
[INFO] [12-26|03:15:41.542] Timings (slower than 50ms)               Headers=12.557s Bodies=171ms Execution=708ms HashState=571ms IntermediateHashes=938ms CallTraces=301ms AccountHistoryIndex=127ms StorageHistoryIndex=264ms LogIndex=195ms TxLookup=92ms
[INFO] [12-26|03:15:41.542] Tables                                   PlainState=82.3GB AccountChangeSet=174.5GB StorageChangeSet=262.9GB BlockTransaction=7.8GB TransactionLog=498.7GB FreeList=171.3MB ReclaimableSpace=171.3GB
[INFO] [12-26|03:15:41.542] RPC Daemon notified of new headers       from=16266161 to=16266167 hash=0xafb51795ca0bb2b4ddb3af1dfcf4c46575e7f048533999e8f67f867ad63e0605 header sending=15.678µs log sending=213ns
[INFO] [12-26|03:15:41.542] [2/16 Headers] Waiting for Consensus Layer... 
[INFO] [12-26|03:15:41.543] [2/16 Headers] Waiting for Consensus Layer... 
[INFO] [12-26|03:16:18.929] [p2p] GoodPeers                          eth66=107 eth67=33
[WARN] [12-26|03:16:22.006] [NewPayload] Previously known bad block  hash=0x29e49fbe94081052e2da820688b890c2a89357611bfb4fde5244942eee88f41c
[INFO] [12-26|03:16:39.280] [txpool] stat                            block=16266167 pending=4498 baseFee=30000 queued=30000 alloc=3.0GB sys=7.7GB
[INFO] [12-26|03:17:20.514] [txpool] stat                            block=16266167 pending=4914 baseFee=30000 queued=30000 alloc=3.4GB sys=7.7GB
[INFO] [12-26|03:18:18.929] [p2p] GoodPeers                          eth66=107 eth67=33
[INFO] [12-26|03:18:20.512] [txpool] stat                            block=16266167 pending=5275 baseFee=30000 queued=30000 alloc=2.9GB sys=7.7GB
[INFO] [12-26|03:19:20.519] [txpool] stat                            block=16266167 pending=5647 baseFee=30000 queued=30000 alloc=3.3GB sys=7.7GB
```

Attaching a longer log snippet too, for context.

[erigon-errors_2022-12-26.log](https://github.com/ledgerwatch/erigon/files/10318344/erigon-errors_2022-12-26.log)

**Comment by Stronzo-sky** [comment]
> I'm not sure if Erigon can be used in an enterprise environment at this point.

it`s a tech preview so yes, not suitable for production.

as for a bug itself - we are all in the same boat here, what is really sad - that this problem is being consequently ignored by the devs - no questions, no assignments, no additional log requests or anything.

**Comment by AskAlexSharov** [comment]
thanks for feedback. just no free arms to work on it now

**Comment by AlexeyAkhunov** [comment]
thanks everyone for providing log snippets. I have found a repeating pattern of how the problem seems to start:
```
[INFO] [12-26|03:15:37.586] [2/16 Headers] Handling new payload      height=16266178 hash=0xf838b2de85f6450e7ed70180c16351ebc0107f229ee80855d272fbb75d854374
[INFO] [12-26|03:15:37.607] [2/16 Headers] Downloading PoS headers... height=16266177 hash=0x3ba02c6475321aa854b93cef0ae513d538efb6caa060369b448c2bf4f93bf44d requestId=151816
[INFO] [12-26|03:15:37.630] UnwindTo                                 block=16266167 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
[INFO] [12-26|03:15:37.634] [2/7 Bodies] Writing block bodies        block_num=16266168 remaining=0 alloc=3.5GB sys=7.7GB
[EROR] [12-26|03:15:37.644] [5/7 Execution] Empty block              blocknum=16266162
[WARN] [12-26|03:15:37.644] Removing beacon request due to           err="unsuccessful execution, progress 16266161 < expected 16266168" requestId=151816
```

Which suggests to me that this is a failure of the interaction between "in memory" execution of the `NewPayload` and its downloading of the block bodies. I will take a closer look at the code. Most importantly I would need to find a way to reproduce it reliably which I cannot at the moment

**Comment by AlexeyAkhunov** [comment]
Another snippet containing this pattern:
```
[INFO] [12-10|05:05:28.468] [5/16 Bodies] DONE                       in=1m40.001054671s
[INFO] [12-10|05:05:28.474] Commit cycle                             in=2.887784ms
[INFO] [12-10|05:05:28.474] Timings (slower than 50ms)               Bodies=1m40.001s
[INFO] [12-10|05:05:28.474] Tables                                   PlainState=80.9GB AccountChangeSet=1.5GB StorageChangeSet=2.6GB BlockTransaction=7.4GB TransactionLog=314.2GB FreeList=324.1MB ReclaimableSpace=324.1GB
[INFO] [12-10|05:05:28.474] RPC Daemon notified of new headers       from=16151789 to=16151792 hash=0x463d95f4591243b67910f0548a2930514818422e6eda83706fe5d0c6f2c07048 header sending=68.905µs log sending=984ns
[INFO] [12-10|05:05:28.475] [2/16 Headers] Waiting for Consensus Layer...
[INFO] [12-10|05:05:36.825] [2/16 Headers] Handling new payload      height=16151801 hash=0xa713e6ad1ae48f295b87cb8993f1f923b266e8d72093a68ff9d2544cee26443f
[INFO] [12-10|05:05:36.871] [2/16 Headers] Downloading PoS headers... height=16151800 hash=0x4e1c8f35f0651d4517e8d6ea41bfba0f6fff2cae1998bb94fc24ecbc69b15f3e requestId=312268
[INFO] [12-10|05:05:37.234] UnwindTo                                 block=16151792 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
[INFO] [12-10|05:05:37.262] [2/7 Bodies] Writing block bodies        block_num=16151793 remaining=0 alloc=3.7GB sys=11.2GB
[EROR] [12-10|05:05:37.325] [5/7 Execution] Empty block              blocknum=16151790
[WARN] [12-10|05:05:37.330] Removing beacon request due to           err="unsuccessful execution, progress 16151789 < expected 16151793" requestId=312268
[INFO] [12-10|05:05:37.686] [5/16 Bodies] Writing block bodies       block_num=16151792 remaining=0 alloc=3.7GB sys=11.2GB
[INFO] [12-10|05:05:38.687] [7/16 Execution] Completed on            block=16151792
[INFO] [12-10|05:05:43.805] Commit cycle                             in=2.128283495s
```

**Comment by AlexeyAkhunov** [comment]
I think I know how to reproduce this - hopefully my node will finish sync up tomorrow and I will try

**Comment by ekreutz** [comment]
Brilliant news @AlexeyAkhunov.

What's the development cycle like on an issue like this? If the fix seems to be working and it passes code review, how many versions down the line would it make it into a "stable" release?

Regardless, thanks for keeping us updated

**Comment by AlexeyAkhunov** [comment]
> Brilliant news @AlexeyAkhunov.
> 
> What's the development cycle like on an issue like this? If the fix seems to be working and it passes code review, how many versions down the line would it make it into a "stable" release?
> 
> Regardless, thanks for keeping us updated

If we find a fix which seems to be fixing the problem, it will end up in the next release after the fix

**Comment by AlexeyAkhunov** [comment]
The fix is merged into `devel`, would you be able to try?

**Comment by ekreutz** [comment]
I'm running a small cluster of nodes, all of which are on the latest "stable" version at any given moment. I'm happy to (continue to) provide logs if they fail, but can't currently run pre-release or devel versions. This might be possible in the future if we spin up staging or testing nodes...

**Comment by Stronzo-sky** [comment]
> The fix is merged into `devel`, would you be able to try?

current stable binary will be still compatible with db after running devel binary? i mean will it be possible to just swap the binary back to current stable after trying devel in case of issues?

**Comment by AskAlexSharov** [comment]
yes

**Comment by nikolinsko** [comment]
i did not encounter any problems with erigon version 2.32.0-dev-0b8f4aea for about 5 days now too :)
