### ISSUE TITLE
 BSC node stuck after HF

### ISSUE THREAD

**Issue by grocon** [ledgerwatch/erigon#6293]
#### System information

Erigon version: git_tag=v2.31.0-rc.4

OS & Version: Debian/Linux

#### Expected behaviour
BSC chain should not be stuck

#### Actual behaviour
BSC chain is stuck at block 23846018

#### Steps to reproduce the behaviour
I did multiple times an unwind
`build/bin/integration stage_headers --unwind=100 --chain=bsc --datadir /home/bscnode/.bsc`
then start erigon
`erigon --chain=bsc --prune=hrtc --db.pagesize=16k --http --private.api.addr= --http.api=eth,web3,trace,txpool --snap.stop --torrent.port 42070 --http.port 18545 --port 30404 --datadir /home/bscnode/.bsc --maxpeers 256`

then it says
`WARN[12-13|09:23:38.490] [7/16 Execution] Execution failed block=23846019 hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6 err="expected system tx (hash 0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x109286049017740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28), actual tx (hash 0xd9fcd3f24acf6855ce04d3bec42f8188b56b8a5dcb27434cc7ed23c2062ce58d, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x1092907ec599740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28)"`

it is then stuck and logs repeat saying
`INFO[12-13|09:25:20.785] [2/16 Headers] No block headers to write in this log period block number=23846018`

**Comment by bdonglobal** [comment]
yes, me too. I am hitting the same issue:

Dec 14 05:19:33 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:19:33.559] [5/16 Bodies] Processed                  highest=23888344
Dec 14 05:19:33 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:19:33.559] [5/16 Bodies] DONE                       in=9m7.263633606s
Dec 14 05:19:33 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:19:33.559] [6/16 Senders] Started                   from=23846018 to=23888344
Dec 14 05:20:03 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:03.560] [6/16 Senders] Recovery                  block_number=23869714 ch=10000/10000
Dec 14 05:20:28 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:28.677] [7/16 Execution] Blocks execution        from=23846018 to=23888344
Dec 14 05:20:30 ip-172-31-0-59 start_erigon_service.sh[1526535]: [WARN] [12-14|05:20:30.079] [7/16 Execution] Execution failed        block=23846019 hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6 err="expected system tx (hash 0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x109286049017740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28), actual tx (hash 0xd9fcd3f24acf6855ce04d3bec42f8188b56b8a5dcb27434cc7ed23c2062ce58d, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x1092907ec599740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28)"
Dec 14 05:20:30 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:30.079] UnwindTo                                 block=23846018 bad_block_hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6
Dec 14 05:20:30 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:30.082] [7/16 Execution] Completed on            block=23846018
Dec 14 05:20:38 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:38.403] [2/16 Headers] Waiting for headers...    from=23846018
Dec 14 05:20:54 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:54.541] [p2p] GoodPeers                          eth66=45 eth67=4
Dec 14 05:20:58 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:20:58.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:21:18 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:21:18.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:21:38 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:21:38.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:21:58 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:21:58.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:22:18 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:22:18.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:22:18 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:22:18.403] Req/resp stats                           req=977 reqMin=23845827 reqMax=23888584 skel=18 skelMin=23847554 skelMax=24142274 resp=5537 respMin=23845828 respMax=23888587 dups=377016
Dec 14 05:22:38 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:22:38.403] [2/16 Headers] No block headers to write in this log period block number=23846018
Dec 14 05:22:38 ip-172-31-0-59 start_erigon_service.sh[1526535]: [INFO] [12-14|05:22:38.403] Req/resp stats                           req=1245 reqMin=23845907 reqMax=23888592 skel=18 skelMin=23847554 skelMax=24142274 resp=7355 respMin=23845918 respMax=23888593 dups=549629

**Comment by BillyTsangGC** [comment]
I Got this Error either now.


[INFO] [12-14|14:53:56.001] [5/16 Bodies] No block bodies to write in this log period block number=23871451
[INFO] [12-14|14:54:49.469] [5/16 Bodies] Writing block bodies       block_num=23889643 remaining=0 alloc=3.3GB sys=5.6GB
[INFO] [12-14|14:54:50.198] [txpool] stat                            block=23846000 pending=10000 baseFee=340 queued=30000 alloc=3.3GB sys=5.6GB
[INFO] [12-14|14:54:54.154] [5/16 Bodies] Processed                  highest=23889643
[INFO] [12-14|14:54:54.154] [5/16 Bodies] DONE                       in=38m58.152741212s
[INFO] [12-14|14:54:54.154] [6/16 Senders] Started                   from=23846018 to=23889643
[INFO] [12-14|14:55:12.387] [7/16 Execution] Blocks execution        from=23846018 to=23889643
[WARN] [12-14|14:55:12.456] [7/16 Execution] Execution failed        block=23846019 hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6 err="expected system tx (hash 0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x109286049017740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28), actual tx (hash 0xd9fcd3f24acf6855ce04d3bec42f8188b56b8a5dcb27434cc7ed23c2062ce58d, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x1092907ec599740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28)"
[INFO] [12-14|14:55:12.456] UnwindTo                                 block=23846018 bad_block_hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6
[INFO] [12-14|14:55:12.456] [7/16 Execution] Completed on            block=23846018
[INFO] [12-14|14:55:25.025] [2/16 Headers] Waiting for headers...    from=23846018
[INFO] [12-14|14:55:45.026] [2/16 Headers] No block headers to write in this log period block number=23846018
[INFO] [12-14|14:55:49.744] [p2p] GoodPeers                          eth66=19 eth67=6
[INFO] [12-14|14:55:50.207] [txpool] stat                            block=23846000 pending=10000 baseFee=340 queued=30000 alloc=2.8GB sys=5.9GB
[INFO] [12-14|14:56:05.025] [2/16 Headers] No block headers to write in this log period block number=23846018
[INFO] [12-14|14:56:25.026] [2/16 Headers] No block headers to write in this log period block number=23846018
[INFO] [12-14|14:56:45.025] [2/16 Headers] No block headers to write in this log period block number=23846018
[INFO] [12-14|14:56:50.198] [txpool] stat                            block=23846000 pending=10000 baseFee=340 queued=30000 alloc=3.2GB sys=5.9GB
[INFO] [12-14|14:57:05.025] [2/16 Headers] No block headers to write in this log period block number=23846018
[INFO] [12-14|14:57:05.025] Req/resp stats                           req=13 reqMin=23846017 reqMax=23850049 skel=14 skelMin=23847554 skelMax=24142274 resp=50 respMin=23846018 respMax=23890451 dups=298
[INFO] [12-14|14:57:25.025] [2/16 Headers] No block headers to write in this log period block number=23846018

how can i fix this?

**Comment by kledgold** [comment]
i also encounter this problem, how to deal with it

**Comment by justforfunya** [comment]
same issue 
`WARN[12-16|08:09:17.740] [7/16 Execution] Execution failed        block=23846019 hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6 err="expected system tx (hash 0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x109286049017740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28), actual tx (hash 0xd9fcd3f24acf6855ce04d3bec42f8188b56b8a5dcb27434cc7ed23c2062ce58d, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x1092907ec599740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28)"`
the tx does not exists in bscscan **0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25**
