### ISSUE TITLE
No peers on Chiado

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#6307]
For some reason Erigon can't find/connect to p2p peers on Chiado. Also, the peer count on Gnosis Chain seems to be low.

**Comment by jomuel** [comment]
We still suspect there is a seperate issue from the fixed Gnosis chain issue (#6308). Currently debugging disconnects from static peers on Chiado.

**Comment by jomuel** [comment]
The problem seems to be Nethermind's useless peers logic. Nethermind disconnects from all peers that are not Nethermind nodes and on block height 0. In a network of only Nethermind nodes, this can lead to other clients like erigon to be shut out.

We have created snapshots for Chiado, so erigon nodes can start at a block height greater than 0, and verified that erigon can join the network normally in that case.

This issue will be closed when the snapshots are up.

**Comment by yperbasis** [comment]
Is that an explicit check in Nethermind against non-Nethermind nodes? Do you know where it is in the code? We can probably ask them to remove it. 

Also, I'm curious why we din't encounter this problem on Gnosis Chain before we had snapshots for it. Perhaps it was due to a population of old Parity nodes.

**Comment by jomuel** [comment]
> Is that an explicit check in Nethermind against non-Nethermind nodes? Do you know where it is in the code? We can probably ask them to remove it.

Yes, there is an explicit check to privilege Nethermind nodes (they are never dropped as useless peers). I think so too, I'll open an issue in Nethermind about the useless peers logic.

> Also, I'm curious why we din't encounter this problem on Gnosis Chain before we had snapshots for it. Perhaps it was due to a population of old Parity nodes.

Nethermind only drops useless peers every 30 seconds. So with a bit of luck, one erigon node may have synced a few blocks before being dropped and thus get itself and the other erigon nodes unstuck.

**Comment by yperbasis** [comment]
Nethermind guys are saying that they don't have preferential treatment of Nethermind peers. They advise to debug peer drop issues with `--Network.DiagTracerEnabled true` flag.

**Comment by filoozom** [comment]
Would it be possible to document how you were able to sync a node and create the snaphots? Sounds useful for the future 🙂

**Comment by jomuel** [comment]
> Would it be possible to document how you were able to sync a node and create the snaphots? Sounds useful for the future

Basically we built Nethermind from source with the call to `DropUselessPeers()` commented out, synced that and then ran an erigon node with our Nethermind node as a static peer. I don't expect us to run into that exact problem again though.
