### ISSUE TITLE
eth_estimateGas returns a result that's too low

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#6313]
#### System information

Erigon version: 2.31.0

This worked in 2.30.0

I can reproduce this at will but unfortunately with the way the contract works, there is a short few-minute window every hour or so where the test can actually be run, as otherwise it returns an error from the contract.

`curl -s -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":8,"method":"eth_estimateGas","params":[{"data":"0xba214c3c00000000000000000000000000000000000000000000000000000000007c1dc00000000000000000000000000000000000000000000000000038a734c51e3ee500000000000000000000000000000000000000000000dd4a192c662b0188e92c","from":"0xddb58b3c9b71121831f714aa63e8d81c83dccffc","gasPrice":"0x0","to":"0x12f96dc173a806d18d71fafe3c1ba2149c3e3dc6"}]}' https://goerli-erigon-node.example.com` - this will, when the timing is right, return a gas limit of `160294`. The same query against Nethermind returns `245973`

This exact curl will now return `execution reverted: Network prices for an equal or higher block are set` and that's expected because of how the contract works. 

Please let me know what you'd need to see from the Erigon side to get to the bottom of it. Trace logs?

**Comment by WyseNynja** [comment]
another example courtesy of fabwa:
```{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from": "0x197231d7f9cd0a61c802bde8cdd14637bc4746b6","to": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174","data": "0xa9059cbb0000000000000000000000003a6a56042e462d66dda25a76ede3e7f8e628b92c0000000000000000000000000000000000000000000000000000000002fa2d61"}],"id":1}```

erigon: 0xa346

boa: 0xd226

**Comment by hexoscott** [comment]
Thanks for the info, out of curiosity if you have access to a node running something other than Erigon, do the results vary with an empty call to estimate gas, without a from/to/data?

**Comment by yorickdowne** [comment]
An empty one returns the same result

```
ubuntu@cl-worker1-a:~$ curl -s -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":8,"method":"eth_estimateGas","params":[{"gasPrice":"0x0"}]}' https://goerli-erigon.example.com
{"jsonrpc":"2.0","id":8,"result":"0xcf08"}

ubuntu@cl-worker1-a:~$ curl -s -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":8,"method":"eth_estimateGas","params":[{"gasPrice":"0x0"}]}' https://goerli-geth.example.com
{"jsonrpc":"2.0","result":"0xcf08","id":8}
```

**Comment by yorickdowne** [comment]
BTW that example by fabwa returns the same result on Erigon and Nethermind for me.

**Comment by hexoscott** [comment]
Erigon on version 2.31 returns the same as Nethermind, that's interesting

**Comment by yorickdowne** [comment]
Not on everything, alas. The test I ran to open this case was against Erigon and Nethermind, with Erigon returning a low value. It's just a bit finicky to actually run because of the way the contract behaves.

**Comment by hexoscott** [comment]
That and ever changing account balances.  This is something that would be good to get into a test suite via web3 or otherwise against devnet.  Lots of variables though to it all and many paths in the code based on them.  Hard to cover all bases.

**Comment by hexoscott** [comment]
I have a hunch that I want to explore, and a "meet halfway" fix between the old behaviour and the new performance tweaks that I'll give a try tomorrow.  Will update here if I make some progress.

**Comment by yorickdowne** [comment]
@hexoscott Agreed that a comprehensive RPC/WS test suite is desperately needed. That's larger than Erigon: Generally speaking, the issue of "the RPC spec is "do what Geth does"" is creating pain with every client that's not Geth. I know the spec has evolved from there, but afaik there's still no comprehensive multi-client test suite.

**Comment by hexoscott** [comment]
That would be brilliant and no doubt speed up development for all involved.  There is a potential fix for this now merged into devel if you'd like to give that a try?

**Comment by yorickdowne** [comment]
estimated gas remains lower than Nethermind by around 13k, yet high enough to complete the tx. Output just now:

```
root@1063e8dcdb5c:/.rocketpool# ./yorickTest /.rocketpool/ https://goerli-erigon.example.com
Using password file [/.rocketpool/data/password]
Using wallet file [/.rocketpool/data/wallet]
Getting RPL price for block 8145600...
RPL price: 0.016077 ETH
Estimating RPL price submission gas...
Calculated Gas Limit: 154963
Smartnode Safe Gas Limit: 232444
root@1063e8dcdb5c:/.rocketpool# ./yorickTest /.rocketpool/ https://goerli-nethermind.example.com
Using password file [/.rocketpool/data/password]
Using wallet file [/.rocketpool/data/wallet]
Getting RPL price for block 8145600...
RPL price: 0.016077 ETH
Estimating RPL price submission gas...
Calculated Gas Limit: 163982
Smartnode Safe Gas Limit: 245973
root@1063e8dcdb5c:/.rocketpool#
```

**Comment by hexoscott** [comment]
That's great news, I'm glad it's working OK.  I'll close this issue down, but do open it again if another issue shows up 😄

**Comment by Beasta** [comment]
i'm having this issue
