### ISSUE TITLE
metrics.expensive not available in version 2.31.0

### ISSUE THREAD

**Issue by jasonyic** [ledgerwatch/erigon#6320]
#### System information

Erigon version: erigon version 2.31.0-stable-a53e8a3e

OS & Version: Linux

Commit hash : 

#### Expected behaviour
`metrics.expensive` should be available

#### Actual behaviour
flag provided but not defined: -metrics.expensive
Incorrect Usage: flag provided but not defined: -metrics.expensive

#### Steps to reproduce the behaviour
`metrics.expensive` was available in 2.30.x

**Comment by AskAlexSharov** [comment]
i removed the flag, we never used it

**Comment by aldredb** [comment]
@AskAlexSharov If `metrics.expensive` is disabled, can you guide on how do we get `chain_head_header` metrics?

**Comment by AskAlexSharov** [comment]
some metric with label `stage=Headers`?

**Comment by aldredb** [comment]
@AskAlexSharov For a verified block, should we use `stage="finish"`?

**Comment by AskAlexSharov** [comment]
yes
