### ISSUE TITLE
Rare panic during staged sync (nil dereference)

### ISSUE THREAD

**Issue by dcposch** [ledgerwatch/erigon#6321]
#### System information

Erigon version: `2022.09.1-alpha-4067b7c4`

OS & Version: Ubuntu 22.04 on x64

Commit hash : `4067b7c4`

#### Expected behaviour

Syncs the chain.

#### Actual behaviour

After weeks of running without issue, I got the following error:

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/169280/207799127-a49bf65e-f919-4993-90f8-fb8519294a6e.png">

Afterward, Erigon spammed the logs, printing those last few lines repeatedly thousands of times. Later, the process died.

#### Steps to reproduce the behaviour

I don't know how to reproduce this, sorry. My Erigon node ran without issue for many weeks prior to this crash.

#### Backtrace

```
runtime error: invalid memory address or nil pointer dereference, trace: stageloop.go:129
panic.go:844 panic.go:220 signal_unix.go:818 fork_validator.go:279 fork_validator.go:216 stage_headers.go:673 collector.go:276 collector.go:144 stage_headers.go:686 stage_headers.go:732
stage_headers.go:195 stage_headers.go:163 default_stages.go:20 sync.go:352 sync.go:255 stageloop.go:163 stageloop.go:84 asm_amd64.s:1571
```

**Comment by dcposch** [comment]
not sure if #6324 fixed this

**Comment by dcposch** [comment]
has the nil dereference been fixed?

**Comment by AskAlexSharov** [comment]
yes

**Comment by dcposch** [comment]
sg, i'll close this then.

is there any regular (say, nightly or weekly) sync-from-scratch process?
would that be useful information for the dev team? thinking we could collect
- failure rate (sync gets stuck vs completes successfully)
- time to sync

i love erigon but my experience setting up an archive node was a bit rough.
