### ISSUE TITLE
AuthRPC should not start automatically unless --externalcl flag is set

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#6339]
# Rationale

Assumption: When using the internal CL there should be no need to communicate between CL and EL over AuthRPC port

# Implementation

AuthRPC should not start automatically unless --externalcl flag is set

**Comment by PeaStew** [comment]
Alternative: new flag `--authrpc false`

**Comment by Giulio2002** [comment]
Already discussed it into discord.
