### ISSUE TITLE
How to start erigon with full sync mode?

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#6359]
The default sync mode is `archive`, I did not see any paramters could passed to erigon to use full sync mode. Please help, thanks

**Comment by AskAlexSharov** [comment]
--prune flags
see `erigon --help | grep prune`

**Comment by TangMonk** [comment]
thanks a lot, so I just set `--prune=rt` for full sync ?

**Comment by AskAlexSharov** [comment]
we don't allow change --prune flag on the fly
