### ISSUE TITLE
TraceAddress for trace_transaction is incorrect

### ISSUE THREAD

**Issue by Uxio0** [ledgerwatch/erigon#6375]
#### System information

Erigon version: `v4.31.0`. `v4.32.0` is broken too. `v4.30.0` is working as expected.

OS & Version: Linux

#### Expected behaviour

`traceAddress` inside traces return the same result that OpenEthereum did or Nethermind. 

#### Actual behaviour

Erigon returns different values

#### Steps to reproduce the behaviour

Take a look at the `traceAddress` for the traces on:
https://etherscan.io/vmtrace?txhash=0xc27273dc6e631d275baa527e1b07cd9097887317c26034bf8ea7bbe38c9353f0&type=parity#raw

Try to get them from Erigon using `trace_transaction` and compare

Erigon `v2.31.0` and `v2.32.0` `traceAddress`:
```
[[],
 [0],
 [0, 0],
 [0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [0, 1, 1, 0],
 [0, 1, 2],
 [0, 1, 2, 0],
 [0, 1, 2, 1],
 [0, 1, 2, 2],
 [0, 1, 2, 3],
 [0, 1, 2, 3, 0],
 [0, 1, 2, 3, 0, 0],
 [0, 1, 2, 4],
 [0, 1, 2, 5],
 [0, 1, 2, 6]]
```

Etherscan and Erigon `v2.30.0` `traceAddress`:
```
[[],
 [0],
 [0, 0],
 [0, 0, 0],
 [0, 0, 1],
 [0, 0, 1, 0],
 [0, 0, 2],
 [0, 0, 2, 0],
 [0, 0, 2, 1],
 [0, 0, 2, 2],
 [0, 0, 2, 3],
 [0, 0, 2, 3, 0],
 [0, 0, 2, 3, 0, 0],
 [0, 0, 2, 4],
 [0, 0, 2, 5],
 [0, 0, 2, 6]]
```

**Comment by AlexeyAkhunov** [comment]
Ok, I am getting to this one now

**Comment by AlexeyAkhunov** [comment]
Running this on `devel` and it looks like it is giving correct results. Can you try please? perhaps I have fixed this "accidentally" when implementing native tracers recently

**Comment by Uxio0** [comment]
Hi @AlexeyAkhunov , it's not easy for us to test this. Even if this is fixed, shouldn't a test exist so it doesn't happen again?

**Comment by Uxio0** [comment]
Hi @AlexeyAkhunov and thanks for your answer, it's not easy for us to test this. Even if this is fixed, shouldn't a test exist so it doesn't happen again?

**Comment by AskAlexSharov** [comment]
> Hi @AlexeyAkhunov and thanks for your answer, it's not easy for us to test this. Even if this is fixed, shouldn't a test exist so it doesn't happen again?

yes. feel free to PR.

**Comment by Uxio0** [comment]
Confirmed this is fixed in https://github.com/ledgerwatch/erigon/releases/tag/v2.38.1
