### ISSUE TITLE
2.32.0-stable got no bootstrap or good peers    for  eth chain (--p2p.protocol=66)

### ISSUE THREAD

**Issue by justforfunya** [ledgerwatch/erigon#6376]
#### System information

Erigon version: `./erigon --version`
erigon version 2.32.0-stable
OS & Version: Windows/Linux/OSX
Ubuntu 20.04.5 LTS
Commit hash : 
https://github.com/ledgerwatch/erigon/commit/021891a311430ffefde77fcceda567ba324e9abe
#### Actual behaviour
erigon_2.32.0  eth chain can not  Retrieve  peers while bsc \polygon works fine
erigon_2.30.0 works fine with eth chain 

INFO[12-20|09:12:39.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:12:49.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:12:59.308] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:13:09.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:13:19.308] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:13:29.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
I

#### Steps to reproduce the behaviour
./erigon --chain=mainnet --datadir  eth_data --http.addr 0.0.0.0  --http.port 8545 --http.vhosts=192.168.0.18  --torrent.download.rate=50m   --ws --http.api=eth,debug,net,trace,web3,erigon --authrpc.port=8551 --torrent.port=6206 --private.api.addr=0.0.0.0:9091  --port=6031 --nat=extip:x.x.x.x --prune= --prune.h.older=12000000 --prune.r.older=12000000 --prune.t.older=12000000 --prune.c.older=12000000 --snapshots=true --p2p.protocol=66
.....
INFO[12-20|09:12:39.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:12:49.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:12:59.308] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:13:09.309] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[12-20|09:13:19.308] [Checkpoint Sync] Retrieving bootstrap   peers=0
#### Backtrace

````
[backtrace]
````

**Comment by Doc-Pixel** [comment]
I test built a dockerized erigon on a local VM running ubuntu 22, this works as expected.
After copying the docker-compose to my physical node server (also ubuntu22_, I get the same issues.

If I figure it out on my server, I'll report back :-)

**Comment by Doc-Pixel** [comment]
update:

In my case this happened because I port erigon over wireguard and I had the allowedIPs parameter set too tight.

For your specific situations I would check 
`iptables -L` are there any rules filtering your output / input traffic?
same for `ip rule` and `ip route`
in case you use ufw, check `ufw status` to see if it is on. If the ufw is on, try turning it off `ufw disable`. Dont forget to turn it on after!

Hope this helps!
