### ISSUE TITLE
Prometheus metric doesn't have the metric type details

### ISSUE THREAD

**Issue by aldredb** [ledgerwatch/erigon#6379]
Prometheus metric doesn't have the metric type details e.g.

```
# HELP node_cpu_seconds_total Seconds the CPUs spent in each mode.
# TYPE node_cpu_seconds_total counter       <-----This metadata is required 
```

# Rationale

Why should this feature exist? - Monitoring systems that scrapes Prometheus metrics such as CloudWatch needs the metric type details to correctly scrape the metrics
What are the use-cases? - Provisioning Erigon on AWS and using CloudWatch to monitor

**Comment by saez0pub** [comment]
Same with datadog, could not get metrics because the type is missing.

**Comment by jlosito** [comment]
@AskAlexSharov could this possibly be re-opened? I'm facing this issue now as well. I'd be willing to try to implement a fix as well.

**Comment by AskAlexSharov** [comment]
@jlosito reopened

**Comment by mattmalec** [comment]
We got this working by forking the VictoriaMetrics library and adding the `HELP` and `TYPE` comments. Let me know if this would be worth PRing. Thanks!

https://github.com/VictoriaMetrics/metrics/issues/48#issuecomment-1670388793

![image](https://github.com/ledgerwatch/erigon/assets/32992688/397c6d8a-26b8-4df1-8c76-d0920d9912e7)
