### ISSUE TITLE
More descriptive error when querying for pruned state

### ISSUE THREAD

**Issue by WyseNynja** [ledgerwatch/erigon#6391]
#### System information

Erigon version: v2.32.0

OS & Version: Linux

Commit hash : 021891a311430ffefde77fcceda567ba324e9abe

#### Expected behaviour

On an archive node, eth_call for an old block gives a successful result.

On a pruned node, eth_call for a pruned block gives some kind of error about missing state. Something like  "state was pruned. data available after block X".

#### Actual behaviour

The pruned node gives a very generic `execution reverted`.

#### Steps to reproduce the behaviour

```
curl http://127.0.0.1:8545 \
    -H "Content-Type: application/json" \
    --data '{"method":"eth_call","params": [{"to":"0x6cb1d641d1b2c5020eb8126a162b83a01ce83fbf","data":"0x48651601"},"0xf3979a"],"id":1,"jsonrpc":"2.0"}'
```

erigon archive:
```
{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000050000000000000000000000004b45addffa952bc7a81ffb73694287643915b0500000000000000000000000000000000000000000000000000e3102ed3b1964b400000000000000000000000019c674f7679c33f5c0248d9f736b2726447c41cf0000000000000000000000000000000000000000000000000e474d3fcb1631e1000000000000000000000000ef251ac05d180a0ffbce8ae0fc65f175a09ae02f0000000000000000000000000000000000000000000000000e358988bc00dfe200000000000000000000000090272940265f21d57a8f9317a8d04a624f0639030000000000000000000000000000000000000000000000000e2cef09c893b8590000000000000000000000009492a8e34126ec4a8494ba77ec197d6de131d6600000000000000000000000000000000000000000000000000dfc5f13335caac2"}
```

erigon --prune htc:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted"}}
```

geth --syncmode snap:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing trie node ed712c449c80a003e7d0b7b51e01666594d51481bca056f4a01fabddd130142f (path ) \u003cnil\u003e"}}
```

# Rationale

When sending a request to pruned node, it is not possible to know whether the eth_call failed in the past or is failing because state has been pruned.

Geth gives a "missing trie node" error. I know erigon does state differently than geth, but it would be very useful to have a more specific error.

I am currently connecting to many nodes and several of them have non-default configuration. I also don't have direct access to their configuration. It would be very useful to be able to know a nodes capabilities for serving state by simply making an eth_call (or eth_getLogs or any other rpc method that might required pruned data). 

# Implementation

I think a more descriptive error would be fine, but a `erigon_prune_mode` rpc call could also work.

This is kind of similar to [#3434,](https://github.com/ledgerwatch/erigon/issues/3434),  but that's more about geth vs erigon and this is about erigon archive vs prune.

**Comment by elee1766** [comment]
this makes sense to me

i think it would be best to encode the variable data in the data field of error? 

```
"error": {"code":-32000,"message":"block pruned", "data":{"block":"0xPrunedBlockNumber","tail":"0xLatestUnprunedBlockNumber"}}
```

**Comment by enriavil1** [comment]
Can you guys try this branch `added-prune-error` it should return an error if the block has been pruned

**Comment by WyseNynja** [comment]
Sure! I'll test this on one of my prune nodes (currently running v2.32.0) tomorrow.

**Comment by WyseNynja** [comment]
I build `added-prune-error` on one of my pruned nodes. I get the same error.

```
ethereum-prune-erigon-1  | [INFO] [12-23|19:05:09.718] Build info                               git_branch=added-prune-error git_tag= git_commit=d1fe34ded910a9338aff27c41dd521dc1843d27b
```

```
$ curl http://127.0.0.1:8545     -H "Content-Type: application/json"     --data '{"method":"eth_call","params": [{"to":"0x6cb1d641d1b2c5020eb8126a162b83a01ce83fbf","data":"0x48651601"},"0xf3979a"],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted"}}
```

I also think we should follow @elee1766 's suggestion and put the prune information into the `data` field.

**Comment by enriavil1** [comment]
@WyseNynja I read it wrong and only added trace_call prune err. I just changed it so it is returned in the data field and added it to eth_call can you please try again.

**Comment by enriavil1** [comment]
@WyseNynja any luck?

**Comment by WyseNynja** [comment]
Haven't had time. I should this week though. On Jan 8, 2023, at 4:40 AM, Enrique Jose Avila Asapche ***@***.***> wrote:﻿
@WyseNynja any luck?

**Comment by enriavil1** [comment]
Okay thank you! I am avoiding syncing a pruned node to test

**Comment by WyseNynja** [comment]
Trying this today

**Comment by WyseNynja** [comment]
I've been fighting polygon all day and haven't had time for this.
