### ISSUE TITLE
About sync progress

### ISSUE THREAD

**Issue by harveyff** [ledgerwatch/erigon#6406]
Hi,
I am a beginner in Erigon, I have some questions, I hope someone who knows can help answer, thank you.
I followed the documentation to start a goerli. It has been going on for more than 2 days. I put the latest log information in the attachment. Does this mean that the synchronization is successful? Is it an rpc node that can be used?

Question 2 : about the consensus node. Is it necessary to build a consensus node? Or can I use other solutions?

Start command:
nohup ./build/bin/erigon --datadir=/erigon/goerli --chain=goerli >>log 2>&1 &

Version:
erigon/2.32.0/linux-amd64/go1.19.4

Log：
[log.txt](https://github.com/ledgerwatch/erigon/files/10284929/log.txt)

**Comment by AskAlexSharov** [comment]
1. yes
2. we have built-in one. but if you need external add --externalcl
