### ISSUE TITLE
Erigon returns same value for Latest and Finalized

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#6450]
#### System information

2.32.0

Linux

#### Expected behaviour

Latest and Finalized (and Safe) should not be the same value as they should relate to different epochs
https://www.alchemy.com/overviews/ethereum-commitment-levels

#### Actual behaviour

Latest and Finalized return the same value

#### Steps to reproduce the behaviour

`{"jsonrpc":"2.0", "method": "eth_getBlockByNumber", "params": ["latest", false], "id": 0}`
`{"jsonrpc":"2.0", "method": "eth_getBlockByNumber", "params": ["finalized", false], "id": 0}`

affected calls include (but not limited to):

- eth_getLogs
- eth_getBlockByNumber
- eth_getBlockTransactionCountByNumber
- eth_getUncleCountByBlockNumber
- eth_getTransactionByBlockNumberAndIndex
- eth_getBalance
- eth_getStorageAt
- eth_getTransactionCount
- eth_getCode
- eth_call

Code indicates it should be doing something different

https://github.com/ledgerwatch/erigon/blob/devel/eth/stagedsync/stage_headers.go#L263

**Comment by PeaStew** [comment]
We are using internalcl exclusively, so indeed the fix needs to be for that

**Comment by Giulio2002** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6867
