### ISSUE TITLE
trace_call and other calls on the pending block fail on POS

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#6461]
Commit hash :  master

Tracing and other calls on the pending block on ethereum POW, used to work (afaik) when adding `--mine --miner.etherbase=...` flags to erigon. 
It looks like after the merge this is not possible anymore.

`eth.getBlockByNumber('pending', false)` and similar RPC calls with these flags enabled now throw with 

```Error: Returned error: ETHBACKENDClient.PendingBlock() error: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil```

Is this feature broken after POS transition, or is there any way to make it work?

**Comment by billyadelphia** [comment]
Same issue, just calling block pending give same error 
`const block = await web3Local.eth.getBlock("pending");`
`ETHBACKENDClient.PendingBlock() error: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil`

probably related to my other issue #5325

**Comment by hexoscott** [comment]
Hi @geomad / @billyadelphia,

Are you running rpc daemon as a separate process or embedded within erigon as a single instance?

**Comment by geomad** [comment]
> Hi @geomad / @billyadelphia,
> 
> Are you running rpc daemon as a separate process or embedded within erigon as a single instance?

Hi! Rpc daemon is running as a separate process for me.

**Comment by hexoscott** [comment]
Thanks, that could likely explain the nil error, will need to dig at the underlying cause.

**Comment by geomad** [comment]
> Thanks, that could likely explain the nil error, will need to dig at the underlying cause.

Thanks! I think I also tried it with the embed daemon and had the same result! I will confirm in a few hrs and let you know.

**Comment by geomad** [comment]
> Thanks, that could likely explain the nil error, will need to dig at the underlying cause.

It looks like with embed client, erigon doesn't return an error, but `eth.getBlockByNumber('pending', false)` returns the latest instead of the pending block.

**Comment by Giulio2002** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/8200
