### ISSUE TITLE
I have the following problem when starting erigon

### ISSUE THREAD

**Issue by ZhangLxAlex** [ledgerwatch/erigon#6500]
[INFO] [12-30|06:50:55.933] Build info                               git_branch=HEAD git_tag=v0.0.3-dirty git_commit=c6e91549edca88e357480d909c668a6aa7f23ea1
[INFO] [12-30|06:50:55.933] Starting Erigon on Bor Mainnet... 
[INFO] [12-30|06:50:55.942] Maximum peer count                       ETH=100 total=100
[INFO] [12-30|06:50:55.942] torrent verbosity                        level=2
[INFO] [12-30|06:50:58.045] Set global gas cap                       cap=50000000
[INFO] [12-30|06:50:58.102] Opening Database                         label=chaindata path=/root/erigon/data/chaindata
[EROR] [12-30|06:50:58.133] Erigon startup                           err="mdbx_env_open: block device required, label: chaindata, trace: [kv_mdbx.go:214 node.go:323 node.go:326 backend.go:158 node.go:121 node.go:112 main.go:41 app.go:526 app.go:286 main.go:28 proc.go:250 asm_amd64.s:1571]"

My dockerfile
```
FROM ubuntu:20.04

RUN apt-get update && apt-get install build-essential wget vim supervisor git unzip curl jq liblz4-tool g++ make gcc -y

RUN cd /root && wget https://dl.google.com/go/go1.18.1.linux-amd64.tar.gz && tar zxvf go1.18.1.linux-amd64.tar.gz

ENV PATH=/root/go/bin:$PATH

RUN cd /root && git clone --recurse-submodules -j8 https://github.com/maticnetwork/erigon.git && cd erigon && git checkout v0.0.3 && make erigon

RUN cd /root/erigon && mkdir data

ADD supervisor_ploy.conf /etc/supervisor/conf.d/

RUN echo "successfull install ploy erigon"
```

My supervisor
```
[program:go]
command=/root/erigon/build/bin/erigon --chain=bor-mainnet --bor.heimdall=https://heimdall.api.matic.network --datadir=/root/erigon/data/
redirect_stderr=true
stdout_logfile=/root/erigon/data/ploy_erigon.log
```

**Comment by AskAlexSharov** [comment]
What is volume driver?

**Comment by ZhangLxAlex** [comment]
aliyun   nas   
https://help.aliyun.com/product/27516.html?spm=5176.59209.J_5834642020.4.6e6576b9ZT764b

**Comment by AskAlexSharov** [comment]
Which Docker command is used ?

**Comment by AskAlexSharov** [comment]
It must not be NFS. Because Database need POSIX flock feature.

**Comment by ZhangLxAlex** [comment]
docker run -d --name erigen -p 8833:30303 -p 8838:8545 -p 8835:9090 -v /data3/pploy_erigon_data:/root/erigon/data/ erigon supervisord -n -c /etc/supervisor/supervisord.conf

my docker start command

**Comment by AskAlexSharov** [comment]
do you:
- run it inside NAS
or 
- you mount NAS's folder to your laptop and run erigon on laptop
?

**Comment by AskAlexSharov** [comment]
what file-system used here: /data3/pploy_erigon_data
?

**Comment by ZhangLxAlex** [comment]
1. I am running erigon on an aliyun nas server.
2、linux file-system
xxxcn-hongkong.nas.aliyuncs.com:/ nfs 1.0P 11T 1014T 2% /data3/pploy_erigon_data

**Comment by AskAlexSharov** [comment]
NFS - it doesn’t support POSIX flock. 

 You need some non-network file system
