### ISSUE TITLE
How to add trusted nodes in Erigon

### ISSUE THREAD

**Issue by binhgo** [ledgerwatch/erigon#6501]
Hi team, 

Can someone show me an example on how to add trusted nodes in erigon. The reason is that I have 3 ETH nodes behind a load balancer, but their syncing sometime is not the same block heigh, so I want to add the other two as trusted node for a node, so they can all keep in-sync with others.

Thanks

**Comment by AskAlexSharov** [comment]
—staticpeers

**Comment by binhgo** [comment]
Sorry, 1 more question: is there a way I can get the enode info of a node? I know I can view it when launch the node, but is there any command to view it?

**Comment by AskAlexSharov** [comment]
1. Erigon print in logs on startup 
2. Can send rpc request, something like admin_nodeInfo
