### ISSUE TITLE
In some cases eth_call method returns different result compare to Geth

### ISSUE THREAD

**Issue by 1doce8** [ledgerwatch/erigon#6518]
Hey, could you please clarify why there is a difference between Geth and Erigon responses in this case?

**System information**
OS: Linux

Geth client version
```
Geth
Version: 1.1.18
Git Commit: 03ff2992ab4674c1df8f568ee9a31596f3503c26
Architecture: amd64
Go Version: go1.17.13
Operating System: linux
GOPATH=
GOROOT=go
```

Erigon client version 
`erigon version 2.32.0-stable-021891a3`

**Steps to reproduce**
Execute the following request:
`{"jsonrpc":"2.0","method":"eth_call","params":[{"from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155","to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567","gas": "0x76c0","gasPrice": "0x9184e72a000","value": "0x9184e72a","data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"}, "latest"],"id":1}`

Geth client response:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0xb60E8dD61C5d32be8058BB8eb970870F07233155 have 0 want 304000002441406250 (supplied gas 30400)"}}`

Erigon client response:
`{"jsonrpc":"2.0","id":1,"result":"0x"}`

**Comment by nanevardanyan** [comment]
Hello @1doce8! Thank you for reporting this.
There is no reason behind it, it was an issue that is already fixed in the next version. 
Please upgrade to 2.33.0 and you will see the expected behavior.

**Comment by Maharacha** [comment]
We noticed this issue on `2.40.1`. Just upgraded to `2.40.0` and still having it. @nanevardanyan
