### ISSUE TITLE
Can't enable the metric's server using yaml config

### ISSUE THREAD

**Issue by derrenen** [ledgerwatch/erigon#6530]
#### System information

Erigon version: erigon version 2.32.0-dev-720b5f77 (https://github.com/ledgerwatch/erigon/releases/tag/v2.32.0)

OS & Version: Ubuntu 22.04 LTS

#### Expected behaviour

Configuration using the CLI works fine:

1. Run: `erigon --metrics`

2. Run: `curl http://127.0.0.1:6060/debug/metrics/prometheus`
    Output:

```
cache_total{target="acc_read"} 0
cache_total{target="st_read"} 0
cache_total{target="write"} 0
db_commit_seconds{phase="audit",quantile="0.5"} 0
db_commit_seconds{phase="audit",quantile="0.9"} 0
db_commit_seconds{phase="audit",quantile="0.97"} 0
db_commit_seconds{phase="audit",quantile="0.99"} 0
db_commit_seconds{phase="audit",quantile="1"} 0
```

#### Actual behaviour

1. Run: `curl http://127.0.0.1:6060/debug/metrics/prometheus`
    Output: `curl: (7) Failed to connect to 127.0.0.1 port 6060 after 0 ms: Connection refused`

#### Steps to reproduce the behaviour

1. Create a config file (/etc/erigon/erigon.yaml) with the following content:

```
metrics: true

log.console.verbosity: info
log.dir.verbosity: warn
log.dir.path: /var/log/erigon

datadir: /var/lib/erigon

snapshots: true

torrent.download.rate: 64MB
torrent.upload.rate: 16MB

batchSize: 1024MB
etl.bufferSize: 4096MB

chain: bor-mainnet

http: true
http.addr: 127.0.0.1
http.port: 8545
http.vhosts: "*"
http.api:
  - eth
  - net
  - trace
  - web3

bor.heimdall: 127.0.0.1:1317
```

2. Run Erigon `erigon --config=/etc/erigon/erigon.yaml`

**Comment by AlexZolotarenko** [comment]
Same issue.
Seems like rootcause - is that metrics are enabled from 'erigon-libs' and there 
https://github.com/ledgerwatch/erigon-lib/blob/main/common/metrics/metrics_enabled.go#L34
they just look in 'os.Args'  for --metrics key in the cli params.

**Comment by hexoscott** [comment]
This has been addressed in the merged code into devel now
