### ISSUE TITLE
trace_transaction returns many null action

### ISSUE THREAD

**Issue by justforfunya** [ledgerwatch/erigon#6546]
#### System information

Erigon version: `./erigon --version`
2.33.0-stable
OS & Version: Windows/Linux/OSX
ubuntu20.04
Commit hash : 
https://github.com/ledgerwatch/erigon/commit/cbc27008d509df6c04f340609e6635d7c98dfb09
#### Expected behaviour
I think trace should return no null action property

#### Actual behaviour
bsc chain 
curl --location --request POST 'http://192.168.0.1:8545' \
--header 'x-api-key: YOUR-API-KEY' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc": "2.0",
"method": "trace_transaction",
"params": ["0xfbf45dfc92bdc169318da9186684d38331ecafbe11b5c519b02e46c52719c397"],
"id": "1"}'

returns 
{
		"action": null,
		"blockHash": "0xec1be81ce7ff2cf1288332b24e8907a007bd0d1aa0c6b34283a198df87ad10c7",
		"blockNumber": 24607123,
		"result": {
			"gasUsed": "0x0",
			"output": "0x"
		},
		"subtraces": 0,
		"traceAddress": [0, 0, 7, 0, 0],
		"transactionHash": "0xfbf45dfc92bdc169318da9186684d38331ecafbe11b5c519b02e46c52719c397",
		"transactionPosition": 3,
		"type": "call"
	}

#### Backtrace

````
[backtrace]
````

**Comment by Serhy** [comment]
Hey @justforfunya, thanks for report! 
Could you confirm please which chain is it happening(where 0xfbf45dfc92bdc169318da9186684d38331ecafbe11b5c519b02e46c52719c397 transaction is) so it's possible to reproduce? Definitely not ETH Mainnet, but looks like Gnosis mainnet (but still not sure)

**Comment by enriavil1** [comment]
This seems to be happening in bsc chain right?

**Comment by enriavil1** [comment]
Are you running erigon with any prune flags?

**Comment by enriavil1** [comment]
> @enriavil1   --prune=hrtc

What you are trying to trace has most likely been pruned
