### ISSUE TITLE
--torrent.download.rate not working as expected and Erigon destroying my bandwidth

### ISSUE THREAD

**Issue by C-K-Loan** [ledgerwatch/erigon#6548]
I have followed the instructions in the Readme and setup Erigon on my home-server which looks to run fine at first.
But all my bandwidth is completely used up, not even SSH is working anymore.

After killing Erigon, it take 1-2 minute for the internet to work again, sometimes I need to restart my router. 

So after reading all your documentation, I see you have `torrent.download.rate` and `torrent.upload.rate` parameters. 
I try to use them, but my internet connection is still completely blown up. 
Its also really slow, like 400KB/s,. I can usually download files at ~ 10MB/s. 
Note: Its slow, regardless if I am using those flags or not. Also using standard `geth` I did not have this problem
Is there anything else I can do? Is this only while synching and when I am fully synched it will not use so much bandwidth?

I am using this command, but nothing changes : 
```shell
./erigon --datadir=/some/path --chain=mainnet  --torrent.download.rate=1mb --torrent.upload.rate=1mb
```
![image](https://user-images.githubusercontent.com/18140070/211666620-8200a312-b97a-4a86-b8c6-d78d2f954f64.png)

#### System information

Erigon version: `./erigon --version`
```
#  Version: 
erigon version 2.32.0-stable-021891a3
```

OS & Version: **Windows/Linux/OSX[**
Using Debian Based OS, POP-OS. 

#### Expected behaviour
Erigon should use less of my internet, so that my network is still working fine when using the torrent.download and torrent.upload flags

#### Actual behaviour
It still seems to use all all available bandwidth and is baraely making any progress[[

#### Steps to reproduce the behavior

Install erigon and run 
`./erigon --datadir=/some/path --chain=mainnet  --torrent.download.rate=1mb --torrent.upload.rate=1mb
`

**Comment by AskAlexSharov** [comment]
If I create git branch, can you test it?

**Comment by C-K-Loan** [comment]
@AskAlexSharov sure, thank you for looking into this!

**Comment by AskAlexSharov** [comment]
@C-K-Loan try branch `torrent_smaller_chunk2`

**Comment by C-K-Loan** [comment]
@AskAlexSharov  Amazing, this branch works like a charm!

 no need to use any `--torent.download.rate` flags and my internet stays very usable. 

thank you so much 
![image](https://user-images.githubusercontent.com/18140070/211727450-99239406-28e5-40ca-923e-2ab13a76b0a7.png)
