### ISSUE TITLE
To limit Prune of execution stage

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#6584]
Here is unlimited: https://github.com/ledgerwatch/erigon/blob/6338bacc9553b7341268a386aa9093b59e2812f5/eth/stagedsync/stage_execute.go#L770

Reason is: stage LogIndex (Prune or Forward) does read everything what not pruned. Maybe need improve LogIndex - so it can take in account value of —prune flag, not just iterate over all logs/changesets which we have in DB. 

Problem: too long pruning, does stop node from sync. https://github.com/ledgerwatch/erigon/issues/6564

Opinion: 
- also can prune as much as possible if initialSync=true, otherwise prune by small steps (like 100 blocks limit, or 500ms limit).

**Comment by awskii** [comment]
In a simple way I restricted amount of blocks to prune from. Does it fits?
https://github.com/ledgerwatch/erigon/pull/6911
