### ISSUE TITLE
Regression in performance (between v2.31.0 and v2.34.0)

### ISSUE THREAD

**Issue by ngotchac** [ledgerwatch/erigon#6597]
#### System information

We are running on Linux Debian, Erigon with both v2.30.0 and v2.34.0

The v2.34.0 was built with `make erigon` on source, since the binaries were not available.

#### Issue

We are seeing some performance regression between our 2 nodes' version, v2.30.0 running fine, but v2.34.0 lagging behind. This happens on both Ethereum mainnet as well as Polygon.

This is our metrics on Ethereum, the green line being v2.34.0 and yellow v2.30.0 (not shown since it's in sync)
![image](https://user-images.githubusercontent.com/2864519/212841243-2cc29eb5-dcb4-4907-8ded-2fa2bfd26e52.png)

Same for Polygon (colours are reversed, yellow is v2.34.0):
![image](https://user-images.githubusercontent.com/2864519/212841450-28fc1800-3ce0-4631-8ccb-1db4b68e377c.png)

Here are some stats on our Ethereum server running v2.34.0:
- Disk is `/dev/md1        7.7T  2.5T  4.8T  34% /` (4TB NVMe in RAID 0)
- Disk usage over time (the break in the middle is when we updated to v2.34.0):
![image](https://user-images.githubusercontent.com/2864519/212843245-e3ad0bf1-05ee-4d6b-9a5c-456563e7d16f.png)
- Erigon stats: 
![image](https://user-images.githubusercontent.com/2864519/212843452-86531030-8eb3-41ca-9686-e0cf171c2481.png)

I'm running the Polygon node with `pprof`, and everytime it's stuck it seems to be in `github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2`, eg.:
```
#	0x8d9c2b	github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2+0x4b		_cgo_gotypes.go:1064
#	0x8dbe32	github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put.func1+0xb2			github.com/torquem-ch/mdbx-go@v0.28.1/mdbx/cursor.go:233
#	0x8dbbf0	github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put+0x90				github.com/torquem-ch/mdbx-go@v0.28.1/mdbx/cursor.go:233
#	0xde367d	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).append+0x39d		github.com/ledgerwatch/erigon-lib@v0.0.0-20230113043530-7c475cb52ecc/kv/mdbx/kv_mdbx.go:1248
#	0xde3680	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Append+0x3a0		github.com/ledgerwatch/erigon-lib@v0.0.0-20230113043530-7c475cb52ecc/kv/mdbx/kv_mdbx.go:1617
#	0xddf9e7	github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).Append+0x87			github.com/ledgerwatch/erigon-lib@v0.0.0-20230113043530-7c475cb52ecc/kv/mdbx/kv_mdbx.go:1080
#	0xff32b2	github.com/ledgerwatch/erigon/core/rawdb.AppendReceipts+0x1d2			github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:1077
#	0x142c377	github.com/ledgerwatch/erigon/eth/stagedsync.executeBlock+0x837			github.com/ledgerwatch/erigon/eth/stagedsync/stage_execute.go:185
#	0x142f12d	github.com/ledgerwatch/erigon/eth/stagedsync.SpawnExecuteBlocksStage+0xf4d	github.com/ledgerwatch/erigon/eth/stagedsync/stage_execute.go:450
#	0x140a719	github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func19+0xb9		github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:101
#	0x147838c	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage+0x16c		github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:353
#	0x14771e4	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run+0x284			github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:255
#	0x1b9106a	github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep+0x48a			github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:167
#	0x1b90704	github.com/ledgerwatch/erigon/turbo/stages.StageLoop+0x164			github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95
```

So maybe a regression in the latest MDBX release?

I can share more info/data if needed!

**Comment by AskAlexSharov** [comment]
Hi. 
1. How long v2.34.0 is running? (Maybe new version need a bit time to adopt, existing db)
2. Show logs
3. Show `make db-tools` `./build/bin/mdbx_stat -ef <your_datadir>/chaindata`

**Comment by ngotchac** [comment]
1. It's been running for ~4 days for the Ethereum chain, and ~1 day for Polygon one (I restarted a couple of times)
2. You can see logs for today here: https://gist.github.com/ngotchac/a9b5960492d806f0c1f179d9e720ea07 ; it starts to be out-of-sync around 04:00
3. Output
```
$ ./build/bin/mdbx_stat -ef /var/lib/erigon/chaindata
mdbx_stat v0.12.3-0-gf1fdb889 (2023-01-07T00:11:51+03:00, T-7c6941447b4b70d0657d92e9375af0ecfb3e4c71)
Running for /var/lib/erigon/chaindata...
Environment Info
  Pagesize: 4096
  Dynamic datafile: 12288..8796093022208 bytes (+2147483648/-4294967296), 3..2147483648 pages (+524288/-1048576)
  Current mapsize: 8796093022208 bytes, 2147483648 pages 
  Current datafile: 1917702897664 bytes, 468189184 pages
  Last transaction ID: 12227920
  Latter reader transaction ID: 12227920 (0)
  Max readers: 32114
  Number of reader slots uses: 3
Garbage Collection
  Pagesize: 4096
  Tree depth: 3
  Branch pages: 5
  Leaf pages: 738
  Overflow pages: 75696
  Entries: 79727
Page Usage
  Total: 2147483648 100%
  Backed: 468189184 21.8%
  Allocated: 467965002 21.8%
  Remained: 1679518646 78.2%
  Used: 390869248 18.2%
  GC: 77095754 3.6%
  Retained: 20 0.0%
  Reclaimable: 77095734 3.6%
  Available: 1756614380 81.8%
Status of Main DB
  Pagesize: 4096
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 3
  Overflow pages: 0
  Entries: 104
```
4. The charts:
GC Overflow
![image](https://user-images.githubusercontent.com/2864519/212869897-ce031aca-c65a-4db2-8b6e-eeae79f8cd89.png)
GC Leaf
![image](https://user-images.githubusercontent.com/2864519/212869960-8d6b56cc-a6a8-4c98-84a8-31f38d96e096.png)
Exec Steps in DB is always at 0

**Comment by ngotchac** [comment]
Yeah actually it's not "too much" of an issue if it's temporary. Could it be that the DB was never properly cleaned-up before this release, so now it has to clean a lot of things? If so, I can let it run and update this issue if there is any progress.

Here's the `Commit speed` graph for the last 24h
![image](https://user-images.githubusercontent.com/2864519/212891529-aa43ddc5-667b-4466-ace9-cccf72126355.png)

I'm running the command and will see if it improves things

**Comment by AskAlexSharov** [comment]
1. Commit time is worse, but not so bad: 1s it's fine - because this commit actually happening after sending notifications about new header/block. So, it happening "between block" when node is free. My guess - it must get to normal after some time - because I didn't see such behavior in our tests. 
2. You mentioned that `rawdb.AppendReceipts` is slow. I don't see it in logs: line `Timings` doesn't show any slow stage. StageHeaders may be slow/slower - but it's likely not related to MDBX.
3. Do you see any other symptoms?

**Comment by ngotchac** [comment]
Yeah let's see if it improves over time. I was mainly wondering if there was a change you could think of in MDBX's usage that could explain this.

Regarding the `rawdb.AppendReceipts` it was just an example of where the `stages.StageLoop` go-routine was stuck at (via `pprof`) for quite some time (>10minutes). That's why I thought it was an "issue" with MDBX.

Thanks for helping debugging BTW :+1:

**Comment by AskAlexSharov** [comment]
1. There was over 9000 changes related to GC :-) Last 6 months we didn't upgrade mdbx because all that releases has problems with GC. But seems we fixed all. We know that migration from old version may take a bit of GC defrag, but your grafana shows that `commit.sync` also increased. But maybe it's just because your node was "slow by another reason" and processed many blocks every cycle instead of 1-by-1 and as a result it commit many blocks at once and in grafana we can see it as "slower" commit, but actually it just committed 1K blocks. You may show `Commit` chart to see frequency of commits. 

2. pprof doesn't show "how long it stuck in given func" as i remember... Of-course it can be the case. But I don't see slow Execution stage in "Timings" in logs.

**Comment by ngotchac** [comment]
So here's the Commit graph for the past 24h
![image](https://user-images.githubusercontent.com/2864519/212912679-ac662c4b-9296-4e89-b881-5b7363528f56.png)

For (2) it was just my best guess of were it was stuck, looking at the go-routines in `pprof` and via the logs ehe

**Comment by AskAlexSharov** [comment]
@ngotchac how is it working now?

**Comment by ngotchac** [comment]
Hey @AskAlexSharov :) I'll update this issue again on Monday, but basically things look perfect on Ethereum:
![image](https://user-images.githubusercontent.com/2864519/213720889-ec30335e-893a-4348-9240-5177cb640ad9.png)

But still lagging a bit behind on Polygon (the green line is for a server we updated on the 17th):
![image](https://user-images.githubusercontent.com/2864519/213721130-ebb5bfcd-fafb-43f7-96d4-86dfcb3ebac0.png)

It might still be doing some DB GC work on Polygon, which has much more data. 

I'll update we some new data in a few days, but I think we'll be able to close this issue by then :crossed_fingers:

**Comment by AlexeyAkhunov** [comment]
To eliminate (or confirm) the MDBX upgrade being a culprit, can you please try branch `rollback-mdbx` ?

**Comment by ngotchac** [comment]
> To eliminate (or confirm) the MDBX upgrade being a culprit, can you please try branch `rollback-mdbx` ?

I'll try that on Monday, sure! Can you just confirm it won't break the DB (if migrations has already been applied for example)? :sweat_smile:

**Comment by AlexeyAkhunov** [comment]
> > To eliminate (or confirm) the MDBX upgrade being a culprit, can you please try branch `rollback-mdbx` ?
> 
> I'll try that on Monday, sure! Can you just confirm it won't break the DB (if migrations has already been applied for example)? 😅

hopefully by Monday it will all be figured out and patched :) No, it should not break the DB

**Comment by AskAlexSharov** [comment]
what is your —db.pagesize?

**Comment by ngotchac** [comment]
> what is your —db.pagesize?

I was using the default value (didn't add any special argument), so it seems it was at 4KB

> can you please try branch `rollback-mdbx`

I guess the branch was deleted (merged?) so I'm currently testing the latest release, v2.36.1, on Polygon. It does look much better (I upgraded around 9:10):
![image](https://user-images.githubusercontent.com/2864519/214004749-9e4f7869-bbeb-4cec-9456-a7afeafe681b.png)

I'll report back at the EOD
