### ISSUE TITLE
Getting Timeout in request from Consensu Client TEKU

### ISSUE THREAD

**Issue by PacoBits** [ledgerwatch/erigon#6609]
We have 3 CL-EC Teku-Erigon servers. After upgrading Erigon to the latest v2.34.0 from v2.33.0 and working fine several hours, one of the teku nodes started to crash. Erigon shows no errors, only teku shows errors, but we tried a status sync on teku and the same error again. We restarted and it is not possible to recover the service, we regressed to erigon v2.33.0 and it is not solved. After several hours a second teku node shows the same error. It is a backup node and 3 hours later it is recovered without any action from our side. 
We have checked with the teku team and it seems that erigon does not respond within 8 seconds and a timeout exception is raised in teku. 

About our setup,it has been working well for several months.

We have a 3-layer configuration with the validator client, the Beacon node and the execution client running separately.
We are using Mev-boost

Validator setup and version: Lighthouse/v3.4.0-38514c0
lighthouse vc
```
--beacon-nodes http://TEKU_IP,http://ip2,http://ip3
--network mainnet
--metrics
--metrics-allow-origin *
--graffiti "Block by xxxxxxx"
--suggested-fee-recipient 0x388Cxxxxxxxxxxxx
--init-slashing-protection
--metrics-port xxx
--http
--builder-proposals
```

Teku setup and version: teku/v22.12.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
```
 command: ["--network=mainnet",
              "--data-base-path=*************",
              "--p2p-port=9000",
              "--rest-api-enabled=true",
              "--rest-api-host-allowlist=*",
              "--initial-state=https://mainnet-checkpoint-sync.stakely.io/eth/v2/debug/beacon/states/finalized",
              "--metrics-enabled=true",
              "--p2p-subscribe-all-subnets-enabled=true",
              "--ee-endpoint=http://ERIGON_IP:8551",
              "--ee-jwt-secret-file=/*********",
              "--validators-graffiti='Block by ******'",
              "--validators-proposer-default-fee-recipient=*****************",
              "--validators-builder-registration-default-enabled=true",
              "--validators-proposer-blinded-blocks-enabled=true",
              "--builder-endpoint=http://localhost:18550",
              "--log-destination=CONSOLE",
              "--logging=INFO"
              ]
```

Erigon Setup and version:  v2.34.0-dirty git_commit=937fb2c4d95b0640904b7dd715c1736e7d0a5ede
```

     --prune htc
     --prune.r.before=11184524
     --private.api.addr=localhost:9091
     --maxpeers 100
     --nat any
     --http
     --http.addr --------
     --http.port 8545
     --http.api=eth,debug,net,trace,web3,erigon,engine,txpool
     --authrpc.port 8551
     --authrpc.addr 0.0.0.0
     --authrpc.jwtsecret ************
     --private.api.addr=localhost:9091
     --chain mainnet
     --metrics
     --port 30303
     --torrent.port 42070
     --datadir=**************
     --authrpc.vhosts "*"
     --externalcl
     --port 30302
```

I attached logs from Erigon and teku. 

[erigo-teku-17012023.log](https://github.com/ledgerwatch/erigon/files/10439280/erigo-teku-17012023.log)

**Comment by TateB** [comment]
i'm experiencing similar problems running the same setup

**Comment by adamgall** [comment]
I'm experiencing similar timeout problems with Erigon, but I'm running Lighthouse as the CL. No errors being show in Erigon logs, but errors being shown in Lighthouse logs:

```
ERRO Execution engine call failed            error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec

WARN Error whilst processing payload status  error: Api { error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }) }, service: exec

CRIT Failed to update execution head         error: ExecutionForkChoiceUpdateFailed(EngineError(Api { error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }) })), service: beacon
```

Previously, the Lighthouse / Erigon setup was working flawlessly on my setup, but have been missing 4-5% of attestations per day for the last ~week since upgrading to the 2.33.x and 2.34 Erigon versions.

**Comment by PacoBits** [comment]
After 24 hours, the first EC-CL recovers, but now the second server shows the same error. 

```
teku_node_1  | 2023-01-18 07:52:00.190 INFO  - Execution Client is responding to requests again after a previous failure
teku_node_1  | 2023-01-18 07:52:08.200 WARN  - Execution Client request timed out. Make sure the Execution Client is online and in sync.
```

**Comment by PacoBits** [comment]
version 2.38.1 is working well.
Closed.
