### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by ekawibisono** [ledgerwatch/erigon#6627]
Hello,
I have problems installing erigon, please help.

Go Version : go version go1.19.4 linux/amd64

![image](https://user-images.githubusercontent.com/22586872/213392916-4aa5e2c9-57f0-4e32-b443-0e6edb2ec2de.png)

**Comment by AskAlexSharov** [comment]
I guess you incorrectly installed golang

**Comment by ekawibisono** [comment]
Hello, Thanks for the solution, problem has solved, i re-installing go again
