### ISSUE TITLE
DumpBlocks: DumpHeaders: header missed in db

### ISSUE THREAD

**Issue by Denis-score** [ledgerwatch/erigon#6636]
#### System information

Erigon version: `2.33.1`

OS & Version: Linux

#### Behaviour
I have this error in my logs. I already tried to remove all snapshots and re-download. I tried to reset "stage_header". Error is still there. 

#### Backtrace

````
Jan 20 08:26:27 rpc-bsc-erigon-prod-01 erigon[885487]: [WARN] [01-20|08:26:27.184] [1/16 Snapshots Prune]                   err="retire blocks error: DumpBlocks: DumpHeaders: header missed in db: block_num=23000000,  hash=0f07d19b35592f91c9474277bfd72ec11e00b5e77eb3f8966f58804f50c75565, fromBlock=23000000, toBlock=23500000"
````

**Comment by AskAlexSharov** [comment]
Temporary workaround: —snap.stop

**Comment by Denis-score** [comment]
Yes I have this workaround @AskAlexSharov, but is this problem related to my node or it's an erigon issue ?

**Comment by AskAlexSharov** [comment]
I think bug of erigon
