### ISSUE TITLE
Inconsistent block response between Erigon and Bor

### ISSUE THREAD

**Issue by Malcador** [ledgerwatch/erigon#6639]
#### System information

Erigon version: thorax/erigon:v2.35.0

#### Expected behaviour

I'd expect to get a consistent response between both nodes.

#### Actual behaviour

After [this](https://github.com/ledgerwatch/erigon/pull/6080) PR the miner field started being populated in the block responses. The actual miner field during execution is `0x0` so not only is this a bit misleading, but also causes issues in re-executing transactions for clients that rely on RPC.

The official version of Bor populates RPC responses as `0x0`.

#### Steps to reproduce the behaviour

Invoke `eth_getBlockByNumber` on a regular Bor node and an Erigon node and compare the `miner` field

### Example

Req:
```json
{
	"jsonrpc":"2.0",
	"method":"eth_getBlockByNumber",
	"params":[
		"0x33d", 
		false
	],
	"id":"1"
}
```

Erigon resp:
`..."miner": "0xb8bb158b93c94ed35c1970d610d1e2b34e26652c"... `

Bor:
`..."miner": "0x0000000000000000000000000000000000000000"...`

**Comment by quickchase** [comment]
This change was reverted in bor, it hasn't been reverted in Erigon
