### ISSUE TITLE
Grafana setup in Makefile tries to chown with user 472, without creating user 472.

### ISSUE THREAD

**Issue by dreadedhamish** [ledgerwatch/erigon#6654]
#### System information

Erigon version: `2.35.2`

OS & Version: OSX High Sierra

Commit hash : 

#### Expected behaviour
Either the Makefile should create user 472 for Grafana, 
or
use provided docker user

#### Actual behaviour
```
XDG_DATA_HOME=/Volumes/erigon DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 make docker-compose
Docker build args:
    DOCKER_UID: 501
    DOCKER_GID: 20

Ensuring host OS user exists with specified UID/GID...
✔️ host OS user exists: macpro51
mkdir -p /Volumes/erigon/erigon /Volumes/erigon/erigon-grafana /Volumes/erigon/erigon-prometheus
ls -aln /Volumes/erigon | grep -E "472.*0.*erigon-grafana" || chown -R 472:0 /Volumes/erigon/erigon-grafana
chown: /Volumes/erigon/erigon-grafana: Operation not permitted
make: *** [setup_xdg_data_home] Error 1
```

#### Steps to reproduce the behaviour
Clean install without Grafana user 472.

**Comment by AskAlexSharov** [comment]
https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#migrate-to-v51-or-later

In docker or on host?

**Comment by dreadedhamish** [comment]
> https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#migrate-to-v51-or-later
> 
> In docker or on host?

On host? This is the default setup provided in the docker-compose.

**Comment by AskAlexSharov** [comment]
I don’t believe it can guess path like /Volumes on host…

**Comment by dreadedhamish** [comment]
It creates the folders successfully as the Host user - there is no guess work.
It then seeks to change ownership of /erigon-grafana/ to user 472, which is the default for Grafana apparently, but nowhere has the makefile created this user.

**Comment by dreadedhamish** [comment]
This is a very stock install - all I've done is follow the instructions on designating a data-dir.

**Comment by keithchew** [comment]
This is a chown permission error. Since the Makefile was executed as a non-root user, the folder created is owned by that user. Therefore, the script will not be able to chown that folder to another user. Only root is allowed to do that. I have not ran the Makefile myself, but the hint above should get you further. Maybe try running the Makefile with root permissions, ie either as root or sudo.

**Comment by dreadedhamish** [comment]
AH thanks.
