### ISSUE TITLE
MDBX_VERSION_MISMATCH when trying to open the database in a separate process

### ISSUE THREAD

**Issue by unitezen** [ledgerwatch/erigon#6661]
I can read the database file in my go application (by importing erigon and erigon-lib) using`kv2.NewMDBX(logger).RoTxsLimiter(semaphore.NewWeighted(100)).Path(chaindataDir).Readonly().Open()`
when erigon and rpcdaemon is not running. 

However, when I started up erigon and rpcdaemon (which starts fine if my app is not running) and start my application, I cannot read the database file anymore with error logged as `mdbx_env_open: MDBX_VERSION_MISMATCH: DB version mismatch libmdbx`. Any pointers would be appreciated.

Seems like something to do with `mdbx_setup_lck:16496 lock region has os/format signature 0x3634b11f, expected 0x3634fb9f`

**Comment by AskAlexSharov** [comment]
Check that linux kernel version > 4

**Comment by lqucool** [comment]
have the same problem, the linux kernel version is :  `Linux ubuntu 5.4.0-135-generic #152-Ubuntu`
Is any way to slove? thanks. @unitezen

**Comment by AskAlexSharov** [comment]
@lqucool fixed by: 
https://github.com/ledgerwatch/erigon/pull/6729/files
