### ISSUE TITLE
Erigon uses AMD AVX instructions - how to build for a non-AVX processor?

### ISSUE THREAD

**Issue by dreadedhamish** [ledgerwatch/erigon#6672]
I have an older Xeon X5676 processor - beefy enough for everything I do, but it predates AVX instructions, and the Erigon Docker image uses AVX instructions!

Before I teach myself from scratch how to build an image without this instruction set, and to potentially help others in the future, has anyone done this and could you share the command you used to build an AMD (non-AVX) build of Erigon?

**Comment by AskAlexSharov** [comment]
Build it without docker?

**Comment by AskAlexSharov** [comment]
make erigon

**Comment by dreadedhamish** [comment]
I was hoping to do it in Docker - I like the all-in-one docker-compose image.

**Comment by dreadedhamish** [comment]
but it's an option - thanks.

**Comment by AskAlexSharov** [comment]
Maybe just 
make docker 
On your machine

**Comment by dreadedhamish** [comment]
I'm using an older OSX - High Sierra - and it's a real pain for Docker - it takes a lot of mucking around to get it running the service in the background, which I'm trying to avoid, and the easier path is to run the Docker Desktop application.

**Comment by keithchew** [comment]
If you are running Docker on your machine, you can try docker run with ubuntu 20.04. Then bash into container and follow build instructions. This will give you a working erigon container. Once you are happy, then you can work your way up and build your own docker image.
