### ISSUE TITLE
How does Erigon handle rebroadcasts?

### ISSUE THREAD

**Issue by imnotanoob** [ledgerwatch/erigon#6690]
Hello,

I work for a company that broadcasts multiple eth transactions daily. We are currently looking to switch from GETH to Erigon.

I had two questions around the txpool in Erigon and how it works. I saw it is not a fork of Geth

Issue 1 Essentially:

- We broadcast a transaction at times of gas spikes.
- The ethereum execution layer lets us know the transaction failed to broadcast due to insufficient gas provided.
- We keep increasing gas, but still not enough.
- When gas spike comes down, we reduce our gas price, but the node remembers a previous transaction with a higher gas price is still in the tx pool, so it prevents it from being sent.

My question:
- Does Erigon automatically re-broadcast transactions?
- Does Erigon keep transactions in the tx pool if it was unable to be submitted?

**Comment by AskAlexSharov** [comment]
1. There is no such thing as “gas price” in txpool. Or you have N gas on-your-balance or not. “price of gas” is not involved and not tracked. 
2.  There is “base fee” in every new block header, this limit may work similar: increase/decrease may change which txs are ready for mining/rebroadcasting. So, txpool does re-calc things on every new block and rebroadcast what need. 



Txpool rebroadcast all txs when they moving to “pending sun-pool”. See:  https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design

**Comment by AskAlexSharov** [comment]
I see some flag `--txpool.pricelimit` it's mapped to `MinFeeCap` 
probably you did mean this field, and txs also have `FeeCap` field.

So
1. if sender balance doesn't pass this check - it's rejected: https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L773
2. this field also taking into account when re-calculation of txn-related fields is happening inside txpool. See: https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L1254 and https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L1301
3. Txs sorting also taking in account MinFeeCap: https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L2342

**Comment by imnotanoob** [comment]
Thank you so much.
