### ISSUE TITLE
"block has less receipts than expected" for eth_getTransactionReceipt for some Bor Receipts

### ISSUE THREAD

**Issue by madumas** [ledgerwatch/erigon#6730]
#### System information

Erigon version: `v2.26.0`

OS & Version: Linux

Commit hash :  3ec0ed769fc9ee11c5a23b213309a82fb0921ac7

#### Expected behaviour

RPC should return the Bor state sync transaction receipt on `eth_getTransactionReceipt` for all blocks, including those who don't have a transaction other than the State Sync.

Example:
```{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0fff012db1ec67cbd27c1defc5652e78bbf84edb45a80ba711b4bdb456f02869"],"id":1}```
should return a full receipt. This block (32015808) has no other transaction that the State Sync

#### Actual behaviour

Error `block has less receipts than expected`:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"block has less receipts than expected: 0 \u003c= 0, block: 32015808"}}
```

#### Steps to reproduce the behaviour
- Sync v2.26.0 for polygon using `--snapshot=false`
-  ```curl -X POST http://node:port -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0fff012db1ec67cbd27c1defc5652e78bbf84edb45a80ba711b4bdb456f02869"],"id":1}'```

#### Backtrace

````
n/a
````

**Comment by revitteth** [comment]
@madumas looks like this is fixed, I will close :)
