### ISSUE TITLE
Erigon 2.37.0 ignores the snapshot option on clean startup (2.36.0 works), (2.36.1 also broken)

### ISSUE THREAD

**Issue by matthewdarwin** [ledgerwatch/erigon#6741]
#### System information

Erigon version: `./erigon --version`

$ erigon --version
erigon version 2.37.0-stable-12419c75

Linux

Erigon Command (with flags/config):

 erigon --version; rm -r /var/lib/erigon/*; /usr/bin/erigon --chain bor-mainnet --datadir /var/lib/erigon --db.pagesize 16kb --snapshots=false

Concensus Layer:

Nethermind

Chain/Network: 

Polygon

#### Expected behaviour

I'm trying to start erigon without snapshots.  Seems like it doesn't recognize the snapshot option.   
$ erigon --version
erigon version 2.37.0-stable-12419c75
 specifically 
INFO[01-29|19:29:38.015] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false

version 2.37.0: Broken
![image](https://user-images.githubusercontent.com/26171839/215351833-262564fc-4d51-4807-8176-b76a8fb51114.png)

version 2.36.0: OK
![image](https://user-images.githubusercontent.com/26171839/215351838-28c35f14-b3d9-4075-bab0-1ab980497481.png)

**Comment by matthewdarwin** [comment]
This issue has been discussed extensively in the graph discord #erigon channel.

**Comment by trader-payne** [comment]
Funny, setting snaps to false on an synced archive with snap=false outputs this:
```Jan 29 21:11:45 polygon-de-falk-2 erigon[1363272]: [WARN] [01-29|21:11:45.023] Incorrect snapshot enablement            got=false change_to=false```

**Comment by AskAlexSharov** [comment]
@matthewdarwin fixed by https://github.com/ledgerwatch/erigon/pull/6743
@trader-payne just it's not allowed to change flag after first erigon start. same for --prune flags

**Comment by trader-payne** [comment]
@AskAlexSharov I was referring to this piece `got=false change_to=false`, as it's already `false` and needs to be changed to `false` again 😄

**Comment by AskAlexSharov** [comment]
ah, but probably also fixed…
