### ISSUE TITLE
Erigon got interrupt, shutting down immediately.

### ISSUE THREAD

**Issue by lovelyrrg51** [ledgerwatch/erigon#6742]
#### System information

Erigon version: erigon version 2.37.0-stable-12419c75

OS & Version: ubuntu 22.04

Commit hash: 

Erigon Command (with flags/config):
```
CMD: erigon
Args: ["--chain=bsc", "--datadir=/data", "--torrent.download.rate=128mb",
      "--networkid=56", "--nat=any", "--http=false",
      "--private.api.addr=localhost:9090"]
```

Concensus Layer: No

Concensus Layer Command (with flags/config): No

Chain/Network: BSC-Mainnet

#### Actual behaviour
![image](https://user-images.githubusercontent.com/56916797/215418102-50eab979-41ad-4aff-84ac-0c2030afd22e.png)

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
what is your expectation? 
I guess you just pressed Ctrl+C

**Comment by lovelyrrg51** [comment]
I've expected that erigon works continuously.
Of course, not pressed CTRL + C.
Implemented it via kubernetes by helm-charts.

**Comment by AskAlexSharov** [comment]
Then kuber pressed Ctrl+C

**Comment by lovelyrrg51** [comment]
Great, Thanks for your support.
I will check.

**Comment by lovelyrrg51** [comment]
It works! @darkhorse-spb 
I'd really appreciate your help.
BTW, how could I contact to you? @darkhorse-spb
