### ISSUE TITLE
i has download history data of chaindata,txpool stat too slow

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#6749]
Only a few hundred blocks an hour, chaindata i had download.why do it sync too slow.

start command /erigon-2.37.0/build/bin/erigon --private.api.addr=localhost:9090 --bodies.cache=4g --http.api=eth,erigon,engine,web3,net,debug,trace,txpool --datadir=/dev

I can't request to get old block info. cause sync too slow

**Comment by AskAlexSharov** [comment]
Show logs
