### ISSUE TITLE
Persistent Issue: No block headers to write in this log period

### ISSUE THREAD

**Issue by PolarSyncZ** [ledgerwatch/erigon#6767]
#### System information

Erigon version: `./erigon --version` 
v2.35.0 and v2.36.1

OS & Version: Fedora36

Erigon Command (with flags/config):

--chain bsc --externalcl --snapshots=true --db.pagesize=16k --datadir=/erigon/data/bsc --txpool.disable --nat=extip:X,X,X,X --http.addr=0.0.0.0 --http.vhosts=* --maxpeers=100 --prune=disabled

Concensus Layer: nimbus

Concensus Layer Command (with flags/config): externalcl

Chain/Network: 

 BSC

#### Backtrace

Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.138] [2/16 Headers] Waiting for headers...    from=25315214
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.150] [2/16 Headers] Processed                 highest inserted=25315243 age=1s
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.189] [5/16 Bodies] Processing bodies...       from=25315214 to=25315243
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.195] [5/16 Bodies] Writing block bodies       block_num=25315243 remaining=0 alloc=3.0GB sys=7.5GB
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.195] [5/16 Bodies] Processed                  highest=25315243
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.196] [6/16 Senders] Started                   from=25315214 to=25315243
Feb 02 09:32:57 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:32:57.331] [7/16 Execution] Blocks execution        from=25315214 to=25315243
Feb 02 09:33:04 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:04.781] [7/16 Execution] Completed on            block=25315243
Feb 02 09:33:04 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:04.781] [8/16 HashState] Promoting plain state   from=25315214 to=25315243
Feb 02 09:33:04 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:04.781] [8/16 HashState] Incremental promotion   from=25315214 to=25315243 codes=true csbucket=AccountChangeSet
Feb 02 09:33:05 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:05.077] [8/16 HashState] Incremental promotion   from=25315214 to=25315243 codes=false csbucket=AccountChangeSet
Feb 02 09:33:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:06.078] [8/16 HashState] Incremental promotion   from=25315214 to=25315243 codes=false csbucket=StorageChangeSet
Feb 02 09:33:08 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:08.822] [9/16 IntermediateHashes] Generating intermediate hashes from=25315214 to=25315243
Feb 02 09:33:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:33:14 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:33:14.976] [10/16 CallTraces] Pruned call trace intermediate table from=25225214 to=25225242
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.826] Commit cycle                             in=58.427704786s
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.826] Timings (slower than 50ms)               Senders=135ms Execution=7.45s HashState=4.041s IntermediateHashes=6.117s CallTraces=2.523s AccountHistoryIndex=1.578s StorageHistoryIndex=3.41s LogIndex=2.21s TxLookup=1.735s
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.826] Tables                                   PlainState=201.0GB AccountChangeSet=498.0GB StorageChangeSet=1.1TB BlockTransaction=3.4GB TransactionLog=2.0TB FreeList=1.8MB ReclaimableSpace=7.3GB
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.827] RPC Daemon notified of new headers       from=25315214 to=25315243 hash=0x9e1a97c330107cdca049924bc1aa39c8a53f9c66fb72279a4b51e6cfc4324bd7 header sending=60.152µs log sending=345ns
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.847] [2/16 Headers] Waiting for headers...    from=25315243
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.858] [2/16 Headers] Processed                 highest inserted=25315246 age=1m18s
Feb 02 09:34:24 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:24.862] [5/16 Bodies] Writing block bodies       block_num=25315246 remaining=0 alloc=4.3GB sys=7.5GB
Feb 02 09:34:25 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:25.735] [7/16 Execution] Completed on            block=25315246
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [EROR] [02-02|09:34:26.776] [9/16 IntermediateHashes] Wrong trie root of block 25315246: abb8a55d0c7324a8a83666bee57f9fd430c5a533faa142371a1da4e1bf33748a, expected (from header): ca1062731dd4f886a2d7670155117d7d3a7131d0131f85de4ab96277f38d0936. Block hash: 38da88e367b59d9d4b4044d72929cb2c1e7329b3c42bb7eac1644c3dfa06cff9
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [WARN] [02-02|09:34:26.776] Unwinding due to incorrect root hash     to=25315244
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.776] UnwindTo                                 block=25315244 bad_block_hash=0x38da88e367b59d9d4b4044d72929cb2c1e7329b3c42bb7eac1644c3dfa06cff9
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.776] [8/16 HashState] Unwinding started       from=25315246 to=25315244 storage=false codes=true
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.794] [8/16 HashState] Unwinding started       from=25315246 to=25315244 storage=false codes=false
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.799] [8/16 HashState] Unwinding started       from=25315246 to=25315244 storage=true codes=false
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.810] [7/16 Execution] Unwind Execution        from=25315246 to=25315244
Feb 02 09:34:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:26.834] [2/16 Headers] Waiting for headers...    from=25315244
Feb 02 09:34:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:34:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:35:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:35:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:35:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:35:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:35:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:35:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:35:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:35:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:36:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:36:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:06.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315301 dups=11
Feb 02 09:36:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:36:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315308 dups=11
Feb 02 09:36:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:36:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:36:46.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315314 dups=12
Feb 02 09:37:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:37:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:06.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=18 respMin=25315244 respMax=25315321 dups=11
Feb 02 09:37:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:37:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:37:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=21 respMin=25315244 respMax=25315328 dups=12
Feb 02 09:37:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:37:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:37:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=22 respMin=25315244 respMax=25315334 dups=16
Feb 02 09:38:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:38:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:06.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315341 dups=11
Feb 02 09:38:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:38:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=17 respMin=25315244 respMax=25315348 dups=10
Feb 02 09:38:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:38:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:38:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=22 respMin=25315244 respMax=25315354 dups=16
Feb 02 09:39:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:39:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:06.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=26 respMin=25315244 respMax=25315361 dups=19
Feb 02 09:39:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:39:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:39:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=21 respMin=25315244 respMax=25315368 dups=13
Feb 02 09:39:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:39:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:39:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=25315244 skelMax=25610156 resp=16 respMin=25315244 respMax=25315374 dups=10
Feb 02 09:40:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:40:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:06.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=18 respMin=25315244 respMax=25315381 dups=10
Feb 02 09:40:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:40:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=26 respMin=25315244 respMax=25315388 dups=18
Feb 02 09:40:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:40:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:40:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=22 respMin=25315244 respMax=25315394 dups=15
Feb 02 09:41:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:41:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:06.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=22 respMin=25315244 respMax=25315401 dups=15
Feb 02 09:41:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:41:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:41:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=16 respMin=25315244 respMax=25315408 dups=9
Feb 02 09:41:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:41:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:41:46.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=25315244 skelMax=25610156 resp=15 respMin=25315244 respMax=25315414 dups=4
Feb 02 09:42:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:06.837] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:42:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:06.837] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=21 respMin=25315244 respMax=25315421 dups=13
Feb 02 09:42:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:42:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=20 respMin=25315244 respMax=25315426 dups=13
Feb 02 09:42:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:42:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:42:46.834] Req/resp stats                           req=2 reqMin=25315237 reqMax=25315429 skel=16 skelMin=25315244 skelMax=25610156 resp=12 respMin=25315238 respMax=25315434 dups=195
Feb 02 09:43:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:43:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:06.835] Req/resp stats                           req=4 reqMin=25315246 reqMax=25315440 skel=17 skelMin=25315244 skelMax=25610156 resp=12 respMin=25315244 respMax=25315441 dups=6
Feb 02 09:43:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:11.401] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:43:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:43:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:26.835] Req/resp stats                           req=2 reqMin=25315246 reqMax=25315440 skel=15 skelMin=25315244 skelMax=25610156 resp=21 respMin=25315244 respMax=25315448 dups=202
Feb 02 09:43:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:43:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:43:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=17 respMin=25315244 respMax=25315454 dups=11
Feb 02 09:44:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:44:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:06.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=31 respMin=25309438 respMax=25315461 dups=20
Feb 02 09:44:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:44:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=25315244 skelMax=25610156 resp=25 respMin=25315244 respMax=25315468 dups=17
Feb 02 09:44:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:44:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:44:46.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315474 dups=12
Feb 02 09:45:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:45:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:06.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=25315244 skelMax=25610156 resp=19 respMin=25315244 respMax=25315481 dups=11
Feb 02 09:45:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:45:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:45:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=21 respMin=25315244 respMax=25315488 dups=14
Feb 02 09:45:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:45:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:45:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=25315244 skelMax=25610156 resp=18 respMin=25309371 respMax=25315494 dups=3
Feb 02 09:46:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:46:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:06.834] Req/resp stats                           req=2 reqMin=25315303 reqMax=25315495 skel=15 skelMin=25315244 skelMax=25610156 resp=16 respMin=25310733 respMax=25315501 dups=198
Feb 02 09:46:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:46:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=16 respMin=25315244 respMax=25315508 dups=9
Feb 02 09:46:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:46.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:46:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:46:46.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=25315244 skelMax=25610156 resp=8 respMin=25315508 respMax=25315514 dups=1
Feb 02 09:47:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:06.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:47:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:06.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=25315244 skelMax=25610156 resp=15 respMin=25315244 respMax=25315521 dups=5
Feb 02 09:47:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:47:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:26.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:47:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:26.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16 skelMin=25315244 skelMax=25610156 resp=15 respMin=25315244 respMax=25315528 dups=5
Feb 02 09:47:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:47:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:47:46.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=18 skelMin=25315244 skelMax=25610156 resp=12 respMin=25315244 respMax=25315534 dups=6
Feb 02 09:48:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:48:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:06.835] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=16 respMin=25315244 respMax=25315541 dups=7
Feb 02 09:48:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:48:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:26.834] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=25315244 skelMax=25610156 resp=12 respMin=25315244 respMax=25315548 dups=4
Feb 02 09:48:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:46.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:48:46 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:48:46.834] Req/resp stats                           req=2 reqMin=25315361 reqMax=25315553 skel=17 skelMin=25315244 skelMax=25610156 resp=8 respMin=25315244 respMax=25315554 dups=2
Feb 02 09:49:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:49:06.835] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:49:06 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:49:06.835] Req/resp stats                           req=3 reqMin=25315361 reqMax=25315553 skel=15 skelMin=25315244 skelMax=25610156 resp=22 respMin=25309465 respMax=25315561 dups=8
Feb 02 09:49:11 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:49:11.400] [p2p] GoodPeers                          eth66=88 eth67=22
Feb 02 09:49:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:49:26.834] [2/16 Headers] No block headers to write in this log period block number=25315244
Feb 02 09:49:26 ip-10-0-15-130 start_erigon_service.sh[969932]: [INFO] [02-02|09:49:26.834] Req/resp stats                           req=3 reqMin=25315361 reqMax=25315553 skel=17 skelMin=25315244 skelMax=25610156 resp=22 respMin=25315009 respMax=25315568 dups=203

@AskAlexSharov This issue is still happening and is now worse than ever for us. Previously it was rare that we had to restart erigon, usually it would show this error but progress, now it get's stuck here and requires a restart and happens multiple times a day on v2.35.0 and v2.36.1. PLease advise as this is making it difficult to use erigon on BSC.

**Comment by 0x19dG87** [comment]
Moreover, I found that in this state memory leak is insane. It consumes almost all my memory 60GB and it is happening only when the process is stuck

**Comment by PolarSyncZ** [comment]
I've upgraded to v2.37.0-stable and am testing it. I have not seen this error yet but will continue to monitor.
