### ISSUE TITLE
Failed to build a block

### ISSUE THREAD

**Issue by DanielCambray** [ledgerwatch/erigon#6770]
Hi, I cannot make a block proposal. Here are the informations.

#### System information

Erigon version: 2.37.0

OS & Version: Linux (docker image)

Erigon Command (with flags/config): --prune.h.older=90000 --prune.r.older=90000 --prune.t.older=90000 --prune.c.older=90000 --authrpc.addr=0.0.0.0  --authrpc.vhosts="*" --db.pagesize=16kb --externalcl

Concensus Layer: prysm

Concensus Layer Command (with flags/config): --p2p-host-ip=${ClientIP} --datadir=/var/lib/prysm/beaconchain --execution-endpoint=http://10.8.0.2:8551 --accept-terms-of-use --jwt-secret=/var/lib/prysm/beaconchain/jwt.hex --checkpoint-sync-url=https://mainnet-checkpoint-sync.stakely.io --genesis-beacon-api-url=https://mainnet-checkpoint-sync.stakely.io

Chain/Network: main

#### Backtrace

````
[INFO] [02-02|20:38:06.854] Building block... 
[INFO] [02-02|20:38:06.871] [1/5 MiningCreateBlock] Start mine       block=16543546 baseFee=33533673540 gasLimit=30000000
[WARN] [02-02|20:38:06.894] Failed to build a block                  err="runtime error: invalid memory address or nil pointer dereference, trace: [stageloop.go:262 panic.go:884 panic.go:260 signal_unix.go:835 stage_mining_exec.go:199 stage_mining_exec.go:135 stagebuilder.go:41 sync.go:353 sync.go:255 stageloop.go:275 backend.go:518 block_builder.go:30 asm_amd64.s:1594]"
[INFO] [02-02|20:38:11.410] Received GetPayloadV1                    payloadId=1
[EROR] [02-02|20:38:11.410] Failed to build PoS block                err="runtime error: invalid memory address or nil pointer dereference, trace: [stageloop.go:262 panic.go:884 panic.go:260 signal_unix.go:835 stage_mining_exec.go:199 stage_mining_exec.go:135 stagebuilder.go:41 sync.go:353 sync.go:255 stageloop.go:275 backend.go:518 block_builder.go:30 asm_amd64.s:1594]"
````

**Comment by hexoscott** [comment]
Hi @DanielCambray,

A couple of things to check.  Are you running erigon as a single process or splitting out txpool/rpcdaemon into their own processes?

It looks like you're missing the --mine and --miner.sigfile flags in order to build blocks.

**Comment by DanielCambray** [comment]
Hi,

I was running erigon with split txpool/rpcdaemon.
I wasn't aware that I need to add --mine and --miner.sigfile flags.

I will try that.

**Comment by yperbasis** [comment]
Please re-open if the issue still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
