### ISSUE TITLE
Syncing stuck on block 15999999 for 4 nodes on ethereum mainnet

### ISSUE THREAD

**Issue by SLoeuillet** [ledgerwatch/erigon#6773]
#### System information

Erigon version: `./erigon --version`
erigon version 2.37.0-stable-12419c75

OS & Version: Ubuntu 20.04

Commit hash: 12419c75

Erigon Command (with flags/config):
/usr/sbin/erigon --bodies.cache=2G --chain=mainnet --datadir=/var/lib/erigon --downloader.disable.ipv6 --healthcheck --http.addr=XXXXXX --http.api=eth,erigon,web3,net,txpool,ots,debug,trace,admin,parity --http.corsdomain=XXXXXX --http.vhosts=XXXXXX --lightclient.discovery.addr=XXXXXX --metrics --nat extip:XXXXXX --private.api.addr=XXXXXX:9090 --torrent.download.rate 512mb --torrent.upload.rate 512mb --ws - --log.console.verbosity=dbug

Concensus Layer: built-in / internal

Concensus Layer Command (with flags/config): none

Chain/Network: ethereum mainnet / 1

#### Expected behaviour

eth_GetBlockByNumber("latest") follows HEAD, metrics shows all stages synced around HEAD

#### Actual behaviour

eth_GetBlockByNumber("latest") shows 15999999 in hex, metrics shows all stages synced at 15999999

#### Steps to reproduce the behaviour

Reproduced it on all my 4 Eth mainnet nodes
Got at least 2 other people reproducing it (one on discord, one on 14999999 issue)

#### Backtrace

````
[backtrace]
````

Looks similar to https://github.com/ledgerwatch/erigon/issues/5531  which was on block 14999999

**Comment by SLoeuillet** [comment]
Metrics on all 4 stucked node :
```
sync{stage="account_history_index"} 15999999
sync{stage="block_hashes"} 15999999
sync{stage="bodies"} 15999999
sync{stage="call_traces"} 15999999
sync{stage="execution"} 15999999
sync{stage="finish"} 15999999
sync{stage="hash_state"} 15999999
sync{stage="headers"} 15999999
sync{stage="intermediate_hashes"} 15999999
sync{stage="log_index"} 15999999
sync{stage="senders"} 15999999
sync{stage="snapshots"} 15999999
sync{stage="storage_history_index"} 15999999
sync{stage="translation"} 0
sync{stage="tx_lookup"} 15999999
```

**Comment by SLoeuillet** [comment]
Here is a link valid for 30 days to download the debug log since startup :
https://transfert.free.fr/KpE9Co

**Comment by SLoeuillet** [comment]
--downloader.verify=true enabled on all 4 nodes now, didn't change anything :

Feb 03 16:44:21 geth01-ethereum-mainnet-ovh erigon[3552092]: [INFO] [02-03|16:44:21.137] [Snapshots] Blocks Stat                  blocks=16000k indices=16000k alloc=2.9GB sys=5.8GB
Feb 03 16:44:21 geth01-ethereum-mainnet-ovh erigon[3552092]: [INFO] [02-03|16:44:21.137] [1/16 Snapshots] DONE                    in=1m29.019953229s

Then again, everything but Consensus Layer stuck at 15999999

**Comment by lovelyrrg51** [comment]
@SLoeuillet please let me know how to pass the downloading snapshots from erigon.
Downloading internal snapshot is paused on `2.37.0-stable-12419c75`
![image](https://user-images.githubusercontent.com/56916797/216666583-15dbc351-38b9-4480-b58c-7e2f2a58d325.png)

**Comment by SLoeuillet** [comment]
@lovelyrrg51 open tcp + udp 42069 on your firewall

**Comment by lovelyrrg51** [comment]
Great, it works!
Thanks for your support. @SLoeuillet

**Comment by SLoeuillet** [comment]
Looks like ForkChoice change in 2.38.0 fixed that bug
Feel free to close

**Comment by ngocbd** [comment]
I still got this bug
![image](https://user-images.githubusercontent.com/439333/219854491-a69fbf9e-23ae-4ceb-b66b-9f682614a8a6.png)
firewall is disable
and version is 2.38.0

![image](https://user-images.githubusercontent.com/439333/219854590-10afe74b-2bd7-4e8f-90e9-c9f2c0eaf0ae.png)

**Comment by miguelgilmartinez** [comment]
> I still got this bug ![image](https://user-images.githubusercontent.com/439333/219854491-a69fbf9e-23ae-4ceb-b66b-9f682614a8a6.png) firewall is disable and version is 2.38.0
> 
> ![image](https://user-images.githubusercontent.com/439333/219854590-10afe74b-2bd7-4e8f-90e9-c9f2c0eaf0ae.png)

Exactly the same. v2.39.0

**Comment by farhan-systango** [comment]
@SLoeuillet I am running it on Kubernetes with nvme storage machines & using the latest stable image. I am also facing same issue.
`[INFO] [03-01|07:39:31.413] [txpool] stat                            block=15999999 pending=0 baseFee=0 queued=9326 alloc=2.9GB sys=5.8GB`

**Comment by lovelyrrg51** [comment]
> I still got this bug ![image](https://user-images.githubusercontent.com/439333/219854491-a69fbf9e-23ae-4ceb-b66b-9f682614a8a6.png) firewall is disable and version is 2.38.0
> 
> ![image](https://user-images.githubusercontent.com/439333/219854590-10afe74b-2bd7-4e8f-90e9-c9f2c0eaf0ae.png)

It's not bug. after downloading block bodies, recovery, execute blocks, ...
Your node will be normal sync.

**Comment by lovelyrrg51** [comment]
Hey, @farhan-systango I recommend that will restart your kubenetes pod with kubectl restart command.

**Comment by lovelyrrg51** [comment]
Btw, you should be careful `--snapshots` flag when re-start your pod. It should be false.
@farhan-systango

**Comment by farhan-systango** [comment]
Thanks @lovelyrrg51 After restarting it started syncing again..
