### ISSUE TITLE
erigon failed to compile with go1.20

### ISSUE THREAD

**Issue by chenrui333** [ledgerwatch/erigon#6774]
To Reproduce
Compile with go 1.20 and it will fail with the following error:

```
# github.com/lucas-clemente/quic-go/internal/qtls
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

**Comment by AskAlexSharov** [comment]
We need update `github.com/libp2p/go-libp2p`

**Comment by AskAlexSharov** [comment]
@Giulio2002 is it hard to update libp2p?

**Comment by J-A-M-E-5** [comment]
Just noticed this. Going to get more users reporting this error as geth seems to have stopped supporting go1.18 (ubuntu default) which mean's Ubuntu geth users will update their golang. Then they can't compile erigon if they used latest version.

Just happened to me: https://github.com/ethereum/go-ethereum/issues/26679

Quick fix - keep golang1.8 (ubuntu default). Install custom golang1.20 just to build geth.

`PATH=/home/me/src/goroot-1.21/bin:$PATH make -j8 geth`

**Comment by AskAlexSharov** [comment]
Fixed in devel
