### ISSUE TITLE
stuck in stage 2/15 headers

### ISSUE THREAD

**Issue by lxl-CSlearner** [ledgerwatch/erigon#6783]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).
version  is erigon version 2.36.0-dev-3aec07f4
my flag `./build/bin/erigon --datadir=data --chain=mainnet --port=30303 --http.port=8545 --authrpc.port=8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon -authrpc.jwtsecret ./data/jwt.hex --externalcl`
the log like this, please tell me what's wrong with my client.
![image](https://user-images.githubusercontent.com/61180702/216901949-f08c6883-90da-43df-b74b-383473453777.png)
and this is consensus client Prysm log
![image](https://user-images.githubusercontent.com/61180702/216902719-f80fddd3-795c-4c16-b3b6-8240d57d6dec.png)

**Comment by greenertux** [comment]
You should update to the latest Erigon version (I recommend 2.37.0 because 2.38.0 seems to have a pretty severe bug), but I don't see anything wrong in the logs you posted.

**Comment by zhy827827** [comment]
me tooooo. stuck in stage 2/15 headers.
/home/ubuntu/erigon/bin/erigon --datadir=/opt/bscdata/erigon --chain=bsc --prune=hrtc  --http.addr=0.0.0.0 --authrpc.vhosts=* --http.corsdomain * --http.vhosts * --db.pagesize=16k --torrent.download.slots 7 --torrent.download.rate=512mb --torrent.upload.rate=20mb --private.api.addr=0.0.0.0:9090  --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --http.api eth,erigon,web3,net,debug,trace,txpool

**Comment by AskAlexSharov** [comment]
@zhy827827 try update

**Comment by thorstenhirsch** [comment]
Does v2.38 solve the issue and "escape" from the loop of an existing v2.36 datadir? Or do we need to start the sync with v2.38 from beginning?

**Comment by greenertux** [comment]
> Does v2.38 solve the issue and "escape" from the loop of an existing v2.36 datadir? Or do we need to start the sync with v2.38 from beginning?

In my case the problem was solved after updating to 2.37.0

**Comment by lxl-CSlearner** [comment]
> Does v2.38 solve the issue and "escape" from the loop of an existing v2.36 datadir? Or do we need to start the sync with v2.38 from beginning?
It did not work in my case, I have stop it for several days and I will try again.
