### ISSUE TITLE
Fix Release GH Action

### ISSUE THREAD

**Issue by ngotchac** [ledgerwatch/erigon#6794]
The Github "Release" action is broken since a few releases ago, cf. latest run for 2.38.0 https://github.com/ledgerwatch/erigon/actions/runs/4098423404/jobs/7067519110

It seems that it now only fails because of permissions issue to push a Docker image to `thorax/erigon`. A fix would be to whether disable the docker builds & push in the `goreleaser` config file, fix the permissions, or push the images to another Docker repo (eg. Github one). I'd make a PR to disable it in `goreleaser` but I'm not sure what's your take on this

**Comment by AskAlexSharov** [comment]
Will take a look tomorrow

**Comment by AskAlexSharov** [comment]
I will try update token

Also need fix this warning: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by AskAlexSharov** [comment]
I did create new token, but it didn't help. 
So, i just disabled "docker push" in goreleaser and did it manually by "docker push --all-tags thorax/erigon"

**Comment by ngotchac** [comment]
Sounds good, thanks!! I'll let you close it, or I can do so after the next release
