### ISSUE TITLE
docker image thorax/erigon: stat --datadir=/data: no such file or directory: unknown

### ISSUE THREAD

**Issue by thorstenhirsch** [ledgerwatch/erigon#6862]
Erigon v2.32.0 was running fine with my docker settings, but v2.38.1 is giving me an error upon start:

````
./run-erigon-pol.sh    
cec931f91ffac4ce0321c3a639726bf04b77b3e9073849c8db402333985ff5a3
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--datadir=/data": stat --datadir=/data: no such file or directory: unknown.
ERRO[0001] error waiting for container:
````
Here's my run command:
````
docker run --name erigon-pol -d \
    -p 8545:8545 \
    -v /home/me/docker/erigon-pol-data:/data \
    thorax/erigon:v2.38.1 \
    --datadir=/data \
    --chain=bor-mainnet
````
The chain doesn't matter, it happens for mainnet as well. So it comes down to how the volume mount is being handled. The directory `/home/me/docker/erigon-pol-data` exists, there's no typo. I also tried mounting it under a different directory like `/mnt`, but the error remains the same. The error is also reproducible on other Linux machines with other distributions and other filesystems.

The only way to resolve the error I've found so far is to go back to v2.32.0.

**Comment by AskAlexSharov** [comment]
what if you add binary name? `thorax/erigon:v2.38.1 erigon --datadir=/data`?

**Comment by thorstenhirsch** [comment]
Solves the problem. But then the next error during start is:
```
Fatal: failed to load node key from /data/nodekey: open /data/nodekey: permission denied
```
The file is there and has the same permissions as with v2.32.0:
```
-rw------- 1 root  root     64 Feb 11 17:55 nodekey
```
Has the uid in the Dockerfile changed?

**Comment by AskAlexSharov** [comment]
I see in dockerfile: 
```
# Setup user and group
#
# from the perspective of the container, uid=1000, gid=1000 is a sensible choice
# (mimicking Ubuntu Server), but if caller creates a .env (example in repo root),
# these defaults will get overridden when make calls docker-compose
ARG UID=1000
ARG GID=1000
RUN adduser -D -u $UID -g $GID erigon
USER erigon
```

**Comment by thorstenhirsch** [comment]
Alright, now it works. So in order to upgrade an existing datadir from v2.32.0 to a newer version, one needs to...

1. update `docker run` with `--user $(id -u):$(id -g)`
2. change ownership of files: `chown -R $(id -u):$(id -g) datadir`
3. add `erigon` to the run command after the image name or `--entrypoint erigon`

Well, I think 1. and 2. are probably not required for most people, because most distributions use uid=1000 for the 1st user account. But for me it was necessary, because I'm using a cloud environment, in which my uid looks like a random number.

And for 3. I suggest to add an entrypoint to the Dockerfile. I could do the update and create a PR... if that's okay...?

**Comment by AskAlexSharov** [comment]
Thank you. Feel free to PR code or readme. Just make sure that docker has many binaries and need posibility to run them also (lazy to release 15 docker images * 2 architectures for each binary).
