### ISSUE TITLE
(Torrent) Downloader connections after sync is complete?

### ISSUE THREAD

**Issue by mondsen** [ledgerwatch/erigon#6876]
I would have used the Discord option as stated in the template for "Ask a question" but the link is not working. Therefore I ask the question here:

Is the downloader after the inital staged sync still required? 

If not, and that would be my guess, why are there so many DNS queries for torrent trackers (see this post https://github.com/ledgerwatch/erigon/issues/5145)? For me it would only make sense to have the downloader active and query the trackers if it is still in use. Is this really the case? If not maybe this could result in an improvement to disable the downloader after sync?

**Comment by AskAlexSharov** [comment]
No free cheese. You can download data only because other members of network (synced) seeding it for you. And you will seed for others. 

Snapshots storing real useful data (old blocks) - so, seeding them means same as “seeding old blocks” by p2p protocol.

**Comment by mondsen** [comment]
Thanks for clarification! 🙏 Maybe a thing to improve is documentation? I was really wondering about the excessive DNS queries for torrent trackers. I can make a proposal an open a PR if you like.

**Comment by AskAlexSharov** [comment]
There is ~7 hostnames of trackers - don’t know why need much dns requests

**Comment by mondsen** [comment]
These are the queries from the first **8 hours** of today:
![grafik](https://user-images.githubusercontent.com/53463563/218956334-b5c5b54e-468f-48a9-ae75-bc42a22d5c3f.png)

**Comment by AskAlexSharov** [comment]
Seems not looks as coincidence:  30K / 8h / 60m / 60sec = 1 
:-)

**Comment by anacrolix** [comment]
That is concerning! I think Go doesn't do any DNS caching of its own, it's normal to provide this at the system level. What OS are you running on?

I did break this precedent for anacrolix/dht in https://github.com/anacrolix/dht/blob/master/dns.go. I think it would be okay to use a similar strategy in anacrolix/torrent for trackers. I'm curious if anyone has more insight into how this is normally handled (like system level should be fine).

**Comment by luncht1me** [comment]
I'd like to be able to limit these requests. My ISP doesn't like it and my modem gets bogged down after a few days of seeding. I've tried reducing with `--torrent.conns.perfile`, `--torrent.upload.rate`, `--maxpeers` and `--sentry.drop-useless-peers` but I'm still getting some bad internet issues over time while syncing.

Any way to reduce the network impact? So far for me the only solution to restore my network is to completely power down my modem and reset it.

**Comment by anacrolix** [comment]
Please open or reference an issue at anacrolix/torrent for this!

**Comment by AskAlexSharov** [comment]
@luncht1me do you see same problem if re-compile erigon with `netgo` tag? 
Example: `go build -tags=netgo,nosqlite,noboltdb -o ./build/bin/erigon ./cmd/erigon`

For more info see: https://github.com/golang/go/issues/30310

**Comment by victorelec14** [comment]
i have the same problem, more as 20 Queries per second and 460,000 queries per day #9330

**Comment by battlmonstr** [comment]
duplicate of https://github.com/ledgerwatch/erigon/issues/5145
