### ISSUE TITLE
fast sync mode not working

### ISSUE THREAD

**Issue by harveyff** [ledgerwatch/erigon#6906]
Hi teams,

Thank you for your great work.

I know that Erigon runs in archive mode by default, and I've successfully run several chains in archive mode and it works fine.

I have a problem now that I want to run the fast mode of eth, I started it with the following command, it still seems to be running in archive mode (because if it is fast mode, it has less data and the sync completes faster), please ask me What did you miss?

```
./build/bin/erigon --datadir=/erigon --chain=mainnet --prune=htc --prune.r.before=16645753 --port=30303 --http.port=8545 --authrpc.port= 8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,erigon,web3,net,debug,trace,txpool --http. corsdomain=* --http.addr=0.0.0.0 --http.vhosts=* --log.console.verbosity=debug
```

**Comment by AskAlexSharov** [comment]
We don't have "snap sync of state" yet. So, with --prune flag Erigon will execute all blocks anyway. Just you will have less data in result. So, it's expected and will be improved by ErigonV3.
