### ISSUE TITLE
Syncing Stuck

### ISSUE THREAD

**Issue by dhyaniarun1993** [ledgerwatch/erigon#6931]
#### System information

Erigon version: `./erigon --version`
2.39.0
The issue is happening on all release after v2.36.1.

Erigon Command (with flags/config):
Miner
```
erigon --datadir=dev --chain=dev --private.api.addr=localhost:9090 --mine
```

Syncer
```
erigon --datadir=dev2 \          
          --http \
          --http.port=8555 \
          --http.api=eth,erigon,web3,net,debug,trace,txpool,parity \
          --port=30313 \
          --chain=dev \
          --networkid=1515 \
          --authrpc.port=9555 \
          --prune=disabled \
          --staticpeers="endpoint"
```

Concensus Layer: NA

Chain/Network:  Dev

#### Expected behaviour
Syncer node should sync to the latest block

#### Actual behaviour
Syncer node is stuck after `Wrote block headers`

#### Steps to reproduce the behaviour
Follow [dev chain setup instructions](https://github.com/ledgerwatch/erigon/blob/devel/DEV_CHAIN.md) and create some transaction using metamask.

Logs attached
[erigon_miner.log](https://github.com/ledgerwatch/erigon/files/10804935/erigon_miner.log)
[erigon_syncer.log](https://github.com/ledgerwatch/erigon/files/10804936/erigon_syncer.log)

**Comment by dhyaniarun1993** [comment]
Hey Guys,

We looked into this more and the changes done on `eth/stagedsync/stage_headers.go` file at [this](https://github.com/ledgerwatch/erigon/commit/5b5fb38786d83ce493d2dffdacde1743c83061d1) commit is the issue. The sync works on dev chain after reverting this commit. Please look into this.

**Comment by racytech** [comment]
Hi @dhyaniarun1993,

Thanks for posting this issue. Could you please also post working commit ID?

**Comment by dhyaniarun1993** [comment]
> Hi @dhyaniarun1993,
> 
> Thanks for posting this issue. Could you please also post working commit ID?

It's working for `v2.36.0` and breaking for `v2.36.1`

**Comment by racytech** [comment]
I just tested it on latest devel branch, found no issues... there might be a delay in body staging, other then that everything works as it intended. I included logs, please take a look

[erigon_miner.log](https://github.com/ledgerwatch/erigon/files/10877834/erigon_miner.log)
[erigon_syncer.log](https://github.com/ledgerwatch/erigon/files/10877837/erigon_syncer.log)
[rpcdaemon.log](https://github.com/ledgerwatch/erigon/files/10877838/rpcdaemon.log)

**Comment by dhyaniarun1993** [comment]
> I just tested it on latest devel branch, found no issues... there might be a delay in body staging, other then that everything works normal. I included logs, please take a look. The problem I think you have is here `--staticpeers=<miner_endpoint>` make sure it is correct.
> 
> [erigon_miner.log](https://github.com/ledgerwatch/erigon/files/10877847/erigon_miner.log) [erigon_syncer.log](https://github.com/ledgerwatch/erigon/files/10877837/erigon_syncer.log) [rpcdaemon.log](https://github.com/ledgerwatch/erigon/files/10877838/rpcdaemon.log)

I am still experiencing the same issue on the latest commit. I don't think the problem is with `--staticpeers=<miner>` since GoodPeers shows 1 peer. I waited for for an hr but still it's stuck.

**Comment by racytech** [comment]
It has to be fixed now for sure. I tested it multiple times. Try latest release 2.40
