### ISSUE TITLE
Incorrect data returned from eth_getTransactionReceipt (simple, repeatable)

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#6956]
This curl call when run against Nethermind:

```
curl --data '{"method":"eth_getTransactionReceipt","params":["0xb719b7c7f1c4f490ee8445ca3a8f47a983f86554ea27582bf269273cfb1ca5ae"],"id":"19","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <NETHERMIND_RPC_ENDPOINT> | jq
```

Returns this data:

```
{
  "jsonrpc": "2.0",
  "result": {
    "transactionHash": "0xb719b7c7f1c4f490ee8445ca3a8f47a983f86554ea27582bf269273cfb1ca5ae",
    "transactionIndex": "0xf2",
    "blockHash": "0x6be1532306ad8dbdb36b7d49ef519a532f36539546ffd6c8e65d27a0c5a43f27",
    "blockNumber": "0xfd8e17",
    "cumulativeGasUsed": "0x1a0e6c8",
    "gasUsed": "0x31000",
    "effectiveGasPrice": "0x308618af2",
    "from": "0xf3008681b545d23ed9b83c34218ba4b21d4f0140",
    "to": null,
    "contractAddress": "0x6784d7583cf2528daa270b555a4cb5376648488f",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x0",
    "error": "BadInstruction",
    "type": "0x0"
  },
  "id": "19"
}
```

While the same call, when run against Erigon, returns this data:

```
{
  "jsonrpc": "2.0",
  "id": "19",
  "result": null
}
```

Erigon is incorrect.

Here's the transaction on Etherscan: https://etherscan.io/tx/0xb719b7c7f1c4f490ee8445ca3a8f47a983f86554ea27582bf269273cfb1ca5ae

**Comment by tjayrush** [comment]
Other examples of similar errors:

```
0x484894104febe494f4bd04ea0482fcdf6d8e9bfbbdc66c2817fe556ba7b45f4a
0x249e49da0744ad323a8f8edd10ab8e9851021caa6dbde8878cd881523f9ab26b
0xd0700d48835234a91bb2e4b545acc46911b1696110350f67f7d376af72a7d4c3
```

**Comment by tjayrush** [comment]
Related:

https://github.com/ledgerwatch/erigon/issues/3243
https://github.com/ledgerwatch/erigon/issues/4530
https://github.com/ledgerwatch/erigon/issues/6011
https://github.com/ledgerwatch/erigon/issues/6574

**Comment by tjayrush** [comment]
I pretty much update each time there's a release, so I think the node was in a bad state a couple of weeks/months ago. I saw a not on some of those referenced issues saying a full re-sync is necessary. Is that correct?

Currently running 2.39.0, but was running each successive version (with some skipping) as they become available.

If it's true that a re-sync is needed, perhaps we could create a test (such as to run curl on all the above-referenced transaction ids), and if they fail, then a person needs to re-sync.

You could then close all of the attached issues.

But -- if it's not necessary to re-sync, of course, most people would choose not to. 

So -- upshot -- is there any way to determine with clarity that one must re-sync?

**Comment by J-A-M-E-5** [comment]
> When you discover data corruption in one, you can flick to the other node, and re-sync/rebuild the bad node.

I imagine the best option would be to run two different versions, as if data corruption or error was caused by erigon programming error in same version you'd just have a copy of the error on the other machine wouldn't you?

I'm happy to accept that any sort of crash which results in unclean shutdown, even if caused by a programming bug means that my node is potentially corrupt. I am already putting procedures in place to not restart node automatically, to check all log files for problematic starts and problematic closes, and the return code from erigon etc...  Are there any sort of guarantees that if my node never crashes and I am running a stable release that it will be fine? 

Is there any sort of thorough testing performed on release candidates, i.e. are they guaranteed if the node never crashed to produce good results? Are they tested for example with a full resync and then all ETH and token balances for example compared against a full archival geth node? I don't have the resources to run a full archival geth node, if I did I would do that.

**Comment by J-A-M-E-5** [comment]
> but most likely it is caused by an unclean shutdown/restart
As I said, I'm willing to take the "loss" and resync if ever I get an unclean shutdown or a messy (re)start. For these reasons I got a UPS, and I do backups. But yeah in case of buggy data I am backing up buggy data.

> I wouldn't be surprised if larger web3 companies that provide web3 endpoints are doing this to ensure data integrity and uptime.

If we all sit and think that, maybe nobody is! 😆 "Don't trust, verify!"

I'd love to have the funds to run and maintain geth full archival node which I don't - which is one of the reasons I am using erigon. It concerns me mostly for erigonv3 when eventually people will never sync from genesis again and what is state computed by somebody else could be found to be wrong at some point.

Certainly running through TrueBlocks or similar a geth node, a nethermind node and a erigon node and getting exactly the same results (without code patches in Trueblocks) would be a confidence booster.

**Comment by tjayrush** [comment]
As the originator of this issue, I guess this issue can be closed. Sounds like I'm in for a re-sync. Please re-open if you wish.
