### ISSUE TITLE
syning question

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#6962]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).
1. will disk be read io higher when node is syncing? 
2. can another node read my node info? lead to my disk read io being higher?

**Comment by AskAlexSharov** [comment]
1. "higher" then what? yes, sync is not free - it's heavy work. are you about read or write? 
2. yes: by "eth p2p" peers can request headers/blocks/receipts. and by BitTorrent protocol peers may request parts of snapshots. see "erigon --help | grep p2p" and "erigon --help | grep torrent" flags to control.

**Comment by AskAlexSharov** [comment]
1. can start only RPCDaemon
2. can --nodiscover 
2. can --txpool.disable

**Comment by AskAlexSharov** [comment]
"syncing read io higher than it synced" - hard question. Dode does many things. IO depends on RAM mount. etc...
