### ISSUE TITLE
Stop sync at a specific block

### ISSUE THREAD

**Issue by maximebucher** [ledgerwatch/erigon#6964]
Hello,

Is it possible to stop synchronization at a specific block? Keeping the RPC services.

I use the Erigon node as a database and I'm not interested in new blocks, my hard disk will soon be full.

Thanks!

**Comment by AskAlexSharov** [comment]
try --nodiscover

**Comment by J-A-M-E-5** [comment]
OP @maximebucher : Can't you just run the RPC subsystem and not run erigon node at all? I think that's how RPC works, you can run it just using the database and no syncing will be performed at all.

Now to try and answer the title of this issue, stopping sync on a **particular block number**....

geth has added this feature recently with a command line option:-
```
--synctarget value            
          File for containing the hex-encoded block-rlp as sync target(dev feature)
```
This is their rationale: https://github.com/ethereum/go-ethereum/issues/26464 The idea I think is they can sync nodes in stages to share an entire historic history across machines. Why they don't just install erigon on one is lost on me! 😄 

I think it would be useful cause it's always nice to give user such functionality, however would another way in Erigon be using the hash of the block immediately after the block you want to stop on and temporarily invalidate it?

`--bad.block value                                        Marks block with given hex string as bad and forces initial reorg before normal staged sync `

Have not tested but I imagine node would sit there panicking? Do you need to start up erigon every time with this value? If you start it without this parameter doe it then continue to sync or do you need to do some cmd line stuff first to remove the block invalidation?

Maybe another way if the block is after PoS activation would be to proxy the communication between an external CL and Erigon and lie about the current head, and don't send the beacon info for any blocks higher than what you want. Seems bloody complicated though!

For sure for someone who knows the code there's a one-line hardcode somewhere which would do it, but I still think it would be nice such an option. e.g. a use-case I can think of is you know you can sync 75% of the node on your SSD and then it gets full. So you could tell erigon to stop at a block near that. You then move your files to your hard disk or whatever and continue syncing. And of course for people who run with pruning and need historic data before it gets stale it's useful.

**Comment by maximebucher** [comment]
It works thank you!

**Comment by 0xgeert** [comment]
> It works thank you!

By restarting with —nodiscover?
