### ISSUE TITLE
EngineError when requesting block at slot 43200 on Zhejiang testnet

### ISSUE THREAD

**Issue by peterbitfly** [ledgerwatch/erigon#6976]
#### System information

Erigon version: `erigon version 2.39.0-dev-f01e3d17`

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):
```
/usr/bin/erigon
  --datadir=/home/ubuntu/eldata
  --networkid=1337803
  --http
  --http.api eth,erigon,engine,debug,trace,txpool
  --http.port 8545
  --http.addr 0.0.0.0
  --http.vhosts *
  --http.corsdomain *
  --ws
  --private.api.addr=127.0.0.1:9999
  --externalcl
  --rpc.batch.limit 10000000
  --rpc.returndata.limit 1000000000
  --authrpc.port=8551
  --authrpc.addr=127.0.0.1
  --authrpc.jwtsecret=/home/ubuntu/jwtsecret
  --batchSize=32m
 
--bootnodes=enode://691c66d0ce351633b2ef8b4e4ef7db9966915ca0937415bd2b408df22923f274873b4d4438929e029a13a680140223dcf701cabe22df7d8870044321022dfefa@64.225.78.1:30303,enode://89347b9461727ee1849256d78e84d5c86cc3b4c6c5347650093982b726d71f3d08027e280b399b7b6604ceeda863283dcfe1a01e93728b4883114e9f8c7cc8ef@146.190.238.212:30303,enode://c2892072efe247f21ed7ebea6637ade38512a0ae7c5cffa1bf0786d5e3be1e7f40ff71252a21b36aa9de54e49edbcfc6962a98032adadfa29c8524262e484ad3@165.232.84.160:30303,enode://71e862580d3177a99e9837bd9e9c13c83bde63d3dba1d5cea18e89eb2a17786bbd47a8e7ae690e4d29763b55c205af13965efcaf6105d58e118a5a8ed2b0f6d0@68.183.13.170:30303,enode://2f6cf7f774e4507e7c1b70815f9c0ccd6515ee1170c991ce3137002c6ba9c671af38920f5b8ab8a215b62b3b50388030548f1d826cb6c2b30c0f59472804a045@161.35.147.98:30303
```
Concensus Layer:

Concensus Layer Command (with flags/config):
```
/usr/bin/lighthouse
  --datadir /home/ubuntu/beacon
  --testnet-dir=/home/ubuntu/custom_config_data
  bn
  --prune-payloads false
  --disable-enr-auto-update
  --port=9000
  --discovery-port=9000
  --eth1
  --boot-nodes=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk,enr:-Ly4QOS00hvPDddEcCpwA1cMykWNdJUK50AjbRgbLZ9FLPyBa78i0NwsQZLSV67elpJU71L1Pt9yqVmE1C6XeSI-LV8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhEDhTgGJc2VjcDI1NmsxoQIgMUMFvJGlr8dI1TEQy-K78u2TJE2rWvah9nGqLQCEGohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA,enr:-MK4QMlRAwM7E8YBo6fqP7M2IWrjFHP35uC4pWIttUioZWOiaTl5zgZF2OwSxswTQwpiVCnj4n56bhy4NJVHSe682VWGAYYDHkp4h2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhJK-7tSJc2VjcDI1NmsxoQLDq7LlsXIXAoJXPt7rqf6CES1Q40xPw2yW0RQ-Ly5S1YhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA,enr:-MS4QCgiQisRxtzXKlBqq_LN1CRUSGIpDKO4e2hLQsffp0BrC3A7-8F6kxHYtATnzcrsVOr8gnwmBnHYTFvE9UmT-0EHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhKXoVKCJc2VjcDI1NmsxoQK6J-uvOXMf44iIlilx1uPWGRrrTntjLEFR2u-lHcHofIhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-LK4QOQd-elgl_-dcSoUyHDbxBFNgQ687lzcKJiSBtpCyPQ0DinWSd2PKdJ4FHMkVLWD-oOquXPKSMtyoKpI0-Wo_38Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhES3DaqJc2VjcDI1NmsxoQNIf37JZx-Lc8pnfDwURcHUqLbIEZ1RoxjZuBRtEODseYN0Y3CCIyiDdWRwgiMo,enr:-KG4QLNORYXUK76RPDI4rIVAqX__zSkc5AqMcwAketVzN9YNE8FHSu1im3qJTIeuwqI5JN5SPVsiX7L9nWXgWLRUf6sDhGV0aDKQ7ijXswAAAHJGBQAAAAAAAIJpZIJ2NIJpcIShI5NiiXNlY3AyNTZrMaECpA_KefrVAueFWiLLDZKQPPVOxMuxGogPrI474FaS-x2DdGNwgiMog3VkcIIjKA
  --http
  --http-address=0.0.0.0
  --http-port=4000
  --listen-address=0.0.0.0
  --target-peers=100
  --http-allow-sync-stalled
  --execution-endpoint=http://127.0.0.1:8551
  --jwt-secrets=/home/ubuntu/jwtsecret
  --count-unrealized
  --slots-per-restore-point=32
```

Chain/Network: Zhejiang

When requesting the block body at slot 80646 via the beacon api `curl -v http://localhost:4000/eth/v1/beacon/blocks/43200` we get the following error:
```
{"code":500,"message":"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\"missing field `withdrawals`\", line: 0, column: 0)) }))","stacktraces":[]}
```

This is also the case for all successive blocks up to block 91765 after which the api returns again valid results.

We are using lh version v3.5.0 together with erigon (latest devel). According to the lh devs (see https://github.com/sigp/lighthouse/issues/4035) this is an issue with erigon.

**Comment by michaelsproul** [comment]
Lighthouse uses eth_getBlockByHash currently to reconstruct payloads, and is expecting all Capella blocks to have a non-null `withdrawals` field.

We will soon switch to using the new PayloadBodies methods, which will alleviate the issue on our side. The underlying Erigon issue with eth_getBlockByHash should probably still be resolved though.

**Comment by hexoscott** [comment]
Hi @peterbitfly, there was a commit merged prior to version 2.39.0 (#6893) that could well fix this issue.  It would require a wipe and resync to be applied correctly though.  Just checking if you did the re-sync before I investigate further, thanks

**Comment by peterbitfly** [comment]
Hello, we did a full resync with `erigon version 2.40.0-stable-38fb38a9` but the issue still persists.

**Comment by peterbitfly** [comment]
Hello, we are now encountering the same issue on goerli with erigon v2.42.0 and lh v4.0.1:
```
curl localhost:4000/eth/v1/beacon/blocks/5193760
{"code":500,"message":"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0xfef2e95d2bed7eccc3d1ed9d9e58116d31018467cc95013ea7b683d3ea3c496d, EngineError(Api { error: Json(Error(\"missing field `withdrawals`\", line: 0, column: 0)) }))","stacktraces":[]}
```

Currently this bug makes retrieval of historical blocks after the shanghai fork impossible.

**Comment by michaelsproul** [comment]
@peterbitfly We could also work around this on the LH side if we merge this PR: https://github.com/sigp/lighthouse/pull/4102. I'll update it for unstable this weekend

You could also work around this by syncing LH through the merge (not from current finalized) with `--prune-payloads false`

**Comment by Giulio2002** [comment]
> Lighthouse uses eth_getBlockByHash currently to reconstruct payloads, and is expecting all Capella blocks to have a non-null `withdrawals` field.
> 
> We will soon switch to using the new PayloadBodies methods, which will alleviate the issue on our side. The underlying Erigon issue with eth_getBlockByHash should probably still be resolved though.

what you are saying is that you guys are expecting [] instead of null, is that correct?

**Comment by michaelsproul** [comment]
Yeah, if it's a Capella execution payload the withdrawals should be [] when they're empty, not `null` or missing

**Comment by Giulio2002** [comment]
Ok, I will fix that; however, you should consider properly handling it on your side. Just a nice thing to have :).

**Comment by guybrush** [comment]
> @peterbitfly But https://goerli.etherscan.io/block/5193760 predates Shanghai and so shouldn't have withdrawals. Do you observe the issue for Shanghai blocks?

https://goerli.beaconcha.in/slot/5193760 does not predate Shanghai: `CAPELLA_FORK_EPOCH: 162304`

we get the error from the [beaconnode-api](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockV2)

```bash
curl localhost:4000/eth/v1/beacon/blocks/5193760
{"code":500,"message":"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0xfef2e95d2bed7eccc3d1ed9d9e58116d31018467cc95013ea7b683d3ea3c496d, EngineError(Api { error: Json(Error(\"missing field `withdrawals`\", line: 0, column: 0)) }))","stacktraces":[]}

curl localhost:4000/eth/v2/beacon/blocks/5193760
{"code":500,"message":"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0xfef2e95d2bed7eccc3d1ed9d9e58116d31018467cc95013ea7b683d3ea3c496d, EngineError(Api { error: Json(Error(\"missing field `withdrawals`\", line: 0, column: 0)) }))","stacktraces":[]}
```
