### ISSUE TITLE
Erigon on Windows always crashes

### ISSUE THREAD

**Issue by yerazy** [ledgerwatch/erigon#6986]
#### System information

Erigon version: erigon version 2.38.0-dev-ae8657e2 and erigon version 2.38.1-stable-52fd6d60

OS & Version:  run and compiled on Windows 10 Pro 22H2 (19045.2006), just launched on Windows server 2019 (1809) 

Commit hash: 

Erigon Command (with flags/config):
erigon --datadir="E:\erigon-test-windows" --chain=mainnet --torrent.download.rate=256mb --log.dir.path="E:\erigon-test-windows" --nat=any --port=30303 --http.port=8545 --authrpc.port=8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon

Concensus Layer: -

Concensus Layer Command (with flags/config): -

Chain/Network:  mainnet

#### Actual behaviour
Constant crashes of the program at any time. the main network cannot be launched in any way.
I tried the bsc network, it even starts the download with several attempts, if you ignore the errors and restart each time. 

#### Steps to reproduce the behaviour
First I compiled the file on Windows 10 Pro 22H2 (19045.2006). gcc 12.2.0,go1.19.4/1.20.1 for 2.38.0-dev and go1.18.10 for 2.38.1-stable,git 2.39.2.windows.1 (no compilation errors). Launched, errors appear as in the log, nothing works. Further, the erigon executable file was transferred to Windows server 2019 (1809), installed "go" in the same way there, and executed "choco install cmake make mingw". Everything is exactly the same, the same errors and erigon does not work. On both systems, I tried the same bsc network, but after downloading a couple of hundred GB, it still crashes. The main network of the ether cannot even be launched - it immediately crashes.

log
[full log erigon.txt](https://github.com/ledgerwatch/erigon/files/10851714/full.log.erigon.txt)

**Comment by AskAlexSharov** [comment]
try https://github.com/ledgerwatch/erigon#windows
i guess guys forgot add     -D __BLST_PORTABLE__ to wmake.ps1
@yerazy  can you try git branch `win_cflags`?

**Comment by yerazy** [comment]
> try https://github.com/ledgerwatch/erigon#windows i guess guys forgot add -D **BLST_PORTABLE** to wmake.ps1 @yerazy can you try git branch `win_cflags`?

The `win_cflags` branch works fine, the mainnet download started right away with no errors on both systems. Thank you.
