### ISSUE TITLE
Erigon - Grafana legacy queries Datasource PBFA97CFB590B2093 was not found

### ISSUE THREAD

**Issue by lucasgonzalezzan** [ledgerwatch/erigon#6994]
I used the config file for Grafana Dashboard on https://github.com/ledgerwatch/erigon/blob/devel/cmd/prometheus/dashboards/erigon.json 
The import fails with the error in the title. The solution is to remove all the json items 
"uid": "PBFA97CFB590B2093"
Is there a more recent file? If not, hopefully this will help sby else.

Sorry if this is not the place to post it.

**Comment by AskAlexSharov** [comment]
ok https://github.com/ledgerwatch/erigon/pull/6998

**Comment by AskAlexSharov** [comment]
removed by https://github.com/ledgerwatch/erigon/pull/7247
