### ISSUE TITLE
Cannot find peers for Sepolia after last hardfork

### ISSUE THREAD

**Issue by Aracki** [ledgerwatch/erigon#7004]
After last hard fork happened, our Erigon Sepolia nodes have difficulties finding any peers. On the other side with our Geth Sepolia we haven't experienced any issues so far.

**Comment by Aracki** [comment]
Should we start using p2p protocol 67 instead of default one 66? 

Geth (https://github.com/ethereum/go-ethereum/releases/tag/v1.10.23) recently changed to eth/67.

**Comment by jajaislanina** [comment]
I have the same issue and regardless of protocol (tried the default eth67 & eth68 and forcing eth66).

**Comment by mahdibaghdadi** [comment]
Same issue here. Did anyone find the solution?

**Comment by yperbasis** [comment]
Hopefully fixed by PR #7502.
