### ISSUE TITLE
trace_block reports wrong 'action.to' address for traces with callType=callcode

### ISSUE THREAD

**Issue by 0xgeert** [ledgerwatch/erigon#7007]
#### System information

Erigon version: `./erigon --version`
erigon version 2.30.0-dev-45938124

OS & Version: Windows/Linux/OSX
Ubuntu 22.04

Commit hash: 
? 

Erigon Command (with flags/config):
`erigon --datadir /xxx --chain mainnet --prune= --http --ws --http.addr=0.0.0.0 --http.port=9545 --http.api=engine,eth,net,admin,web3,trace --http.vhosts=*`

Concensus Layer:
included in above

Chain/Network: 
Ethereum mainnet

#### Expected behaviour

Doing `eth_getBalance` on block `x` and `x+1 `for a given address gives a state-diff. 
This statediff should be reproducible by  `trace_block(x)`

#### Actual behaviour
The above is correct for all cases, except when traces with `callType=callcod` are involved.

#### Steps to reproduce the behaviour

First do 2 getBalances on block x and x+1 this gives a state/balance - diff. Balance + balance-diff crosschecked with etherscan and appears to be correct. 
https://etherscan.io/tx/0x63e04753794d94780b585da71820602f1d9ca9764fddf3e56d2d1afb941bfbb9#statechange

````
{"method":"eth_getBalance","params":["0xd2f06b96b41a6cbd916e3e762e837193ac74e89b", 119665],"id":1,"jsonrpc":"2.0"}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x0" // zero
}

{"method":"eth_getBalance","params":["0xd2f06b96b41a6cbd916e3e762e837193ac74e89b", 119666],"id":1,"jsonrpc":"2.0"}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x8ac7230489e80000" // 10000000000000000000
}
````

However, the reported 2 traces that lead up to this state change are NOT correct (omitting unrelated reward trace for brevity)
Specifically, the second trace with type=callcode has an unexplainable 'to' = 0x273930d21e01ee25e4c219b63259d214872220a2
As per this trace, this results in a balance deduction of 10000000000000000000 from address 0xd2f06b96b41a6cbd916e3e762e837193ac74e89b
Again this is incorrect as per the `eth_getBalance` above

````
{"method":"trace_block","params":[119666],"id":1,"jsonrpc":"2.0"}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
      {
          "action": {
              "from": "0xee38df16452bb041e346caa6679efc57c8bd4603",
              "callType": "call",
              "gas": "0x1a6d4",
              "input": "0x",
              "to": "0xd2f06b96b41a6cbd916e3e762e837193ac74e89b",
              "value": "0x8ac7230489e80000"
          },
          "blockHash": "0x8f911b53c5491ac7acf950f343f80e63769925aada620fba16fb5999abc49f72",
          "blockNumber": 119666,
          "result": {
              "gasUsed": "0x2034",
              "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          "subtraces": 1,
          "traceAddress": [],
          "transactionHash": "0x63e04753794d94780b585da71820602f1d9ca9764fddf3e56d2d1afb941bfbb9",
          "transactionPosition": 0,
          "type": "call"
      },
      {
          "action": {
              "from": "0xd2f06b96b41a6cbd916e3e762e837193ac74e89b",
              "callType": "callcode",
              "gas": "0x18c56",
              "input": "0x",
              // Wrong. According to etherscan it should go to itself. I.e.: from = to. 
              // Again getBalance is correct (both listing balance=0 for this address on block=119665 and block=119666)
              "to": "0x273930d21e01ee25e4c219b63259d214872220a2",  // Wrong
              "value": "0x8ac7230489e80000"
          },
          "blockHash": "0x8f911b53c5491ac7acf950f343f80e63769925aada620fba16fb5999abc49f72",
          "blockNumber": 119666,
          "result": {
              "gasUsed": "0x5a4",
              "output": "0x"
          },
          "subtraces": 0,
          "traceAddress": [
              0
          ],
          "transactionHash": "0x63e04753794d94780b585da71820602f1d9ca9764fddf3e56d2d1afb941bfbb9",
          "transactionPosition": 0,
          "type": "call"
      },
  ]
}
````

It is described [here](https://ethereum.stackexchange.com/a/3672/73032) that callcode has a bug, which is why it was replaced by delegatecall.
Perhaps that's the issue here. Etherscan at least seems to have fixed this to point to itself, i.e. 
from = 0xd2f06b96b41a6cbd916e3e762e837193ac74e89b / to = 0xd2f06b96b41a6cbd916e3e762e837193ac74e89b

Essentially making it a no-op. Tracking other traces with callType=callcode (non-exhaustive) etherscan seems to make all callcode-traces noops

**Comment by iFA88** [comment]
Hey!
For me seems that correct.
You know that this action is a CALLCODE, so the `to` represents the address where is the code what need to be executed, but in the current context.

**Comment by 0xgeert** [comment]
@iFA88 Yeah just came in here to close. You're correct.
