### ISSUE TITLE
Stuck on block 15999999 (prysm as CL)

### ISSUE THREAD

**Issue by Apehaenger** [ledgerwatch/erigon#7009]
#### System information

Erigon version: 3.2.1

OS & Version: Linux AMD64
Erigon Command (with flags/config):
```
--chain mainnet --datadir mainnet --externalcl \
--prune htc --prune.r.before 11052984 \
--private.api.addr localhost:9090 \
--http --ws --http.api engine,eth,erigon,web3,net,debug,txpool \
--metrics
```

Concensus Layer: prysm
Concensus Layer Command (with flags/config): ```beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=/location/of/erigon/jwt.hex --suggested-fee-recipient=0x....```

Chain/Network: mainnet

#### Actual behaviour
Stuck on block 15999999

Hi folks!

I'm trying to get erigon & prysm running on a machine. At first as Node, but should become a validator.
Already read #5531 multiple times, but now after approx. 6 days and prysm saying it will take further 104h I'm pretty sure something is running wrong on my side.

Erigon synced pretty fast (approx. 1 day) up to block 15999999, but then it stuck there.
Found this post here (as well as some others) and also recognized in startup log that he's waiting for CL.
So I installed prysm, it did something during the next 2-3 days, but now since approx. 2 days he's doing opportunistic block valdiations?... and say he'll need further >= 100h.

This is what I constantly get on erigon console:
```
Mär 02 23:53:28 CN1 erigon[652]: [INFO] [03-02|23:53:28.005] [txpool] stat                            block=15999999 pending=0 baseFee=0 queued=30000 alloc=4.8GB sys=6.5GB
Mär 02 23:53:47 CN1 erigon[652]: [INFO] [03-02|23:53:47.648] [] ETL [2/2] Loading                     into=PlainState current_prefix=8e5da5a4
Mär 02 23:54:17 CN1 erigon[652]: [INFO] [03-02|23:54:17.648] [] ETL [2/2] Loading                     into=PlainState current_prefix=e571cfe2
Mär 02 23:54:26 CN1 erigon[652]: [INFO] [03-02|23:54:26.113] Write to db                              progress=2.3M/3.9M current table=Code
Mär 02 23:54:27 CN1 erigon[652]: [INFO] [03-02|23:54:27.682] [p2p] GoodPeers                          eth67=22 eth66=4 eth68=6
Mär 02 23:54:32 CN1 erigon[652]: [INFO] [03-02|23:54:32.570] [txpool] stat                            block=15999999 pending=0 baseFee=0 queued=30000 alloc=3.4GB sys=6.5GB
Mär 02 23:54:48 CN1 erigon[652]: [INFO] [03-02|23:54:48.631] [7/15 Execution] Executed blocks         number=6836669 blk/s=7.9 tx/s=806.5 Mgas/s=50.2 gasState=0.00 batch=0B alloc=3.5GB sys=6.5GB
Mär 02 23:55:03 CN1 erigon[652]: [INFO] [03-02|23:55:03.057] [7/15 Execution] Executed blocks         number=6837217 blk/s=38.0 tx/s=3963.0 Mgas/s=252.6 gasState=0.01 batch=6.4MB alloc=4.5GB sys=6.5GB
Mär 02 23:55:23 CN1 erigon[652]: [INFO] [03-02|23:55:23.065] [7/15 Execution] Executed blocks         number=6838163 blk/s=47.3 tx/s=4654.9 Mgas/s=313.9 gasState=0.02 batch=17.4MB alloc=3.0GB sys=6.5GB
Mär 02 23:55:27 CN1 erigon[652]: [INFO] [03-02|23:55:27.716] [txpool] stat                            block=15999999 pending=0 baseFee=0 queued=30000 alloc=3.6GB sys=6.5GB
Mär 02 23:55:43 CN1 erigon[652]: [INFO] [03-02|23:55:43.075] [7/15 Execution] Executed blocks         number=6839493 blk/s=66.5 tx/s=4858.1 Mgas/s=419.0 gasState=0.03 batch=31.0MB alloc=3.1GB sys=6.5GB
```

Whereas prysm log:
```
[2023-03-02 23:53:59]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x819943d6f9af slot=4732411
...
...
[2023-03-02 23:54:05]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x621ef653c191 slot=4732415
[2023-03-02 23:54:05] ERROR powchain: Unable to process past deposit contract logs, perhaps your execution client is not fully synced error=processPastLogs: no contract code at given address
[2023-03-02 23:54:06]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x620fdacf37d7 slot=4732416
...
...
[2023-03-02 23:54:15]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xcf2dc9271b22 slot=4732422
[2023-03-02 23:54:16]  INFO p2p: Peer summary activePeers=55 inbound=41 outbound=14
[2023-03-02 23:54:20]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x5cfa1cd768ae slot=4732423
```

and sometimes also:
```
[2023-03-02 23:54:46]  INFO initial-sync: Processing block batch of size 64 starting from  0xe54d1abb... 4732576/5914471 - estimated time remaining 34h44m28s blocksPerSecond=9.4 peers=55
[2023-03-02 23:54:46]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x5633fec8537655e8769009da09f2c6694a938847bbee0c18e99c84e70deaf0dc (in processBatchedBlocks, slot=4732576)
...
...
[2023-03-02 23:54:53]  INFO initial-sync: Processing block batch of size 63 starting from  0x86ebeb03... 4732768/5914472 - estimated time remaining 17h16m34s blocksPerSecond=19.0 peers=55
[2023-03-02 23:54:53]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x2506470be9dab60
```

I need to note that I run erigon in prune mode, but I tripple checked the block number as it got changed 740 times within the last  2 weeks ;-)

For sure, I opened tcp + udp at port 42069, as well as I did the necessary forwarding in my router.
I also tested without firewall.
Tested with online "open port" tester, but because I haven't found one which was able to test open port with IPv6 I disabled 
today (and also because I read somewhere that there are no IPv6 P2P nodes) completely IPv6 on the machine.

But no luck :-/

Does it make sense to be patient for further 3-6000 days or does anyone has an idea whats wrong with me or my machine? ;-)

**Comment by SLoeuillet** [comment]
[7/15 Execution] Executed blocks 
 is the longest step as it executes every block since genesys sequentialy, one by one

Erigon 3 (or 4 ?) in the roadmap would bring parallel execution, much faster

Snapshots end at block 16M, new headers & blocks are downloaded via P2P (<16M are via BitTorrent snapshot files)

**Comment by AskAlexSharov** [comment]
bottleneck: disk read latency (not throughput). also more RAM may help.

**Comment by Apehaenger** [comment]
Quite thanks for your answers!

1. Does it mean that it's expected that erigon pause at 15999999 and wait till CL (prysm) reaches a specific state (i.e. >7/15)?
2. Can I assume that message: ```[INFO] [03-03|14:34:15.634] [p2p] GoodPeers eth67=20 eth66=3 eth68=8``` indicate that P2P will work (no mistake in firewall or router-forwarding)?

Regarding possible bottleneks:

4. Unfortunatley I'm on max. RAM sockets. Need to change them completely. Is it advisable to go to 32GB before switching to validator-mode or is the 16GB difference majory a benefit during initial indexing?
5. It turns out that I skipped the readme part that indicated that Btrfs will cost me +3 days. I could shrink my Btrfs, create an EXT4, copy, index and revert to Btrfs once indexed. Usefull?! Or should I remain on EXT4 once copied?

**Comment by AskAlexSharov** [comment]
`[txpool] stat` it's logs from TxPool component, it's not related to sync progress.

**Comment by Apehaenger** [comment]
Thanks a lot for your comment.

> `[txpool] stat` it's logs from TxPool component, it's not related to sync progress.

:see_no_evil: I fully poke in the fog :man_shrugging:
Can't identify a status/progress relation in the output of erigon and prysm. Also couldn't find any info whats expected to see.

If I interpret it right, this line in prysm:
```[2023-03-04 12:34:24]  INFO initial-sync: Processing block batch of size 64 starting from  0xdd92a824... 4822204/5925470 - estimated time remaining 95h46m10s blocksPerSecond=3.2 peers=44```
and the following ```Called new payload with optimistic block ...``` is what I see as
```[7/15 Execution] Executed blocks ...```
log entries in erigon?!

Means I only made around 6 estimated hours within approx. 24 real hours = 15 further days?
Think I'll switch to EXT4 and check if it significantly speed up :thinking:

**Comment by Mahan-F** [comment]
Hi all

I'm having the same issue here as @Apehaenger. The Erigon client has been running for over two weeks in the `[7/15 Execution] Executed blocks` state.

Some other logs from the Erigon client:
```
[p2p] GoodPeers                          eth67=30 eth68=16
[txpool] stat                            block=15999999 pending=0 baseFee=0 queued=30000 alloc=5.4GB sys=9.3GB
```

I am also using Erigon + Prysm to run an archival node.

Is there something wrong with my setup, or do I just need to wait for longer?

Both clients are running on a Linux machine with 32GB RAM and 12 vCPU (AMD EPYC)

**Comment by Apehaenger** [comment]
BTW: I changed the Filesystem from Btrfs to Ext4 (on top of an PCIe 3.0 x4 connected NVMe) and measured the improvement during the last 24 hours.
At least for this [7/15 Execution] state the improvement was 0% or negative.
I made now 5 estimated hours within the last 24 real hours, so I've to count for further 14 days :-/

@Mahan-F how long does your prysm estimate?
```[2023-03-05 18:31:52]  INFO initial-sync: Processing block batch of size 64 starting from  0x72b378c6... 4904935/5934457 - estimated time remaining 89h22m5s blocksPerSecond=3.2 peers=53```
And how much hours estimation do your reach in real?

@Mahan-F as you're syncing an archive node, you don't have any pruning configured?

How do you plan to go on?
It feels dusty and wrong... atm, and as far as I understood, we're doing since a couple of days (you 14 or more) only? "optimistic blocks".
I think I've to start over, but I'm unsure what to drop, erigon or prysm.
Prysm has a pretty good documentation... what's your plan?

**Comment by Apehaenger** [comment]
Short feedback.

Reverted back to Btrfs as Ext4 did not improved the processing speed in any case.

Tried Teku (as BN) but Teku (BN) said that erigon is out of sync (same as prysm said). So I fully switched to Besu (as EC) and Teku as (BN) and now after approx. 30 hrs. both are in sync and everything looks good.

Will close the issue as it's not relevant to me anymore ;-)

**Comment by Maksat2022** [comment]
Hi, erigon v2.42.0 facing the problem on block but on 14999999 like here https://github.com/ledgerwatch/erigon/issues/5531. 
opening tcp + udp 42069 on firewall and --downloader.verify not helping to solve the problem

**Comment by fernandezpaco** [comment]
Same here
