### ISSUE TITLE
how to build the light node？

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#7022]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).

how to build the light node？Can I set up the last few 1 thousands of blocks

**Comment by AskAlexSharov** [comment]
we don't support "light node" mode, only "full node".
