### ISSUE TITLE
Sync delayed about 10-20 minutes to latest block

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7029]
#### System information

Erigon version: `erigon-cli version 2.30.0-stable-35f493c5`

OS & Version: Ubuntu 22.04

Network: 1000 MBps bandwidth
Cpu: Intel i7 12700
Memory: 64 GB 
Disk: NVME SSD (1000MB/s)

erigon.toml config: 

```
datadir="/mnt1/archive"
port=30304
"authrpc.port"=8557
"torrent.port"=42070
"private.api.addr"="127.0.0.1:9091"
chain="mainnet"
http=true
ws=true
"authrpc.addr"="0.0.0.0"
"http.addr"="0.0.0.0"
"http.api"=["eth","debug","net","trace","web3","erigon","admin", "txpool"]
"http.port"=7546
```

Chain/Network:  Mainnet

#### Expected behaviour

Sync with latest block without delay

#### Actual behaviour

Sync delayed 10-20 minutes to latest block (compared with etherscan)

<img width="908" alt="image" src="https://user-images.githubusercontent.com/3498786/223082540-83864611-c837-44c9-8995-ef9785851ed5.png">

**Comment by AskAlexSharov** [comment]
- logs? 
- FS?

**Comment by TangMonk** [comment]
> * logs?
> * FS?

what is FS?

**Comment by AskAlexSharov** [comment]
FileSystem
