### ISSUE TITLE
v2.40.0 Memory Leak

### ISSUE THREAD

**Issue by 0x19dG87** [ledgerwatch/erigon#7035]
#### System information

Erigon version: erigon version 2.40.0-stable-cc2090e7

OS & Version: Ubuntu 22.04

Erigon Command (with flags/config): 
./erigon \
--chain=bor-mainnet \
--datadir=/storage/erigon/datadir \
--ethash.dagdir=/storage/erigon/datadir/ethash \
--snapshots=true \
--bor.heimdall=http://localhost:1317 \
--http --http.addr=172.20.0.1 --http.port=8545 --http.compression --http.vhosts=* --http.corsdomain=* \
--http.api=eth,debug,net,trace,web3,erigon,bor,ots \
--ws --ws.compression \
--rpc.gascap=300000000 \
--metrics --metrics.addr=localhost --metrics.port=6960

Chain/Network: Polygon

#### Expected behaviour
Sync process running without memory leak

#### Actual behaviour
Memory leak

#### Steps to reproduce the behaviour
Start erigon version 2.40.0

#### Backtrace

````
Memory leak starts after updating to the new version. Before I was running version 2.37.0

systemctl status erigon.service

Active: active (running) since Mon 2023-03-06 17:13:50 EET; 22min ago
   Main PID: 3902651 (erigon)
      Tasks: 56 (limit: 76997)
     Memory: 46.3G
        CPU: 36min 8.548s

Below is a part of the log, but it cannot move further after [2/15 Headers] No block headers to write in this log period block number=39821312


`Mar 06 17:52:11 sm5504-352 systemd[1]: Started Erigon Polygon Service.
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [WARN] [03-06|17:52:12.579] no log dir set, console logging only
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.579] Starting metrics server                  addr=http://localhost:6960/debug/metrics/prometheus
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [WARN] [03-06|17:52:12.588] no log dir set, console logging only
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.588] Build info                               git_branch=HEAD git_tag=v2.40.0-dirty git_commit=cc2090e78324e732c6245980070465282093f239
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.588] Starting Erigon on Bor Mainnet...
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.589] Maximum peer count                       ETH=100 total=100
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.589] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon,bor,ots
Mar 06 17:52:12 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:12.589] torrent verbosity                        level=WRN
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.700] Set global gas cap                       cap=300000000
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.705] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.705] Opening Database                         label=chaindata path=/storage/erigon/datadir/chaindata
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.710] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Sharding: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [WARN] [03-06|17:52:14.711] Incorrect snapshot enablement            got=true change_to=false
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.711] Effective                                prune_flags= snapshot_flags= history.v3=false
Mar 06 17:52:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:14.726] Initialising Ethereum protocol           network=137
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.379] Starting private RPC server              on=127.0.0.1:9090
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.379] new subscription to logs established
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.380] rpc filters: subscribing to Erigon events
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.381] new subscription to newHeaders established
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.381] New txs subscriber joined
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.382] Reading JWT secret                       path=/storage/erigon/datadir/jwt.hex
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.383] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.384] HTTP endpoint opened                     url=172.20.0.1:8545 ws=true ws.compression=true grpc=false
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.390] [txpool] Started
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.392] [2/15 Headers] Waiting for headers...    from=39820950
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.408] Started P2P networking                   version=68 self=enode://fe783c8f5d4ad894dc3504958a168348f2343061de2165a0a2c7ba158ad69602de8e8b50f574a4c9464d80d82fdcdbe373e3d206d96201c5f17d5e584e7afd98@127.0.0.1:30304 name=erigon/v2.40.0-stable-cc2090e7/linux-amd64/go1.18.1
Mar 06 17:52:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:16.419] Started P2P networking                   version=67 self=enode://fe783c8f5d4ad894dc3504958a168348f2343061de2165a0a2c7ba158ad69602de8e8b50f574a4c9464d80d82fdcdbe373e3d206d96201c5f17d5e584e7afd98@127.0.0.1:30303 name=erigon/v2.40.0-stable-cc2090e7/linux-amd64/go1.18.1
Mar 06 17:52:36 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:36.393] [2/15 Headers] Wrote block headers       number=39821312 blk/second=18.100 alloc=142.2MB sys=241.7MB
Mar 06 17:52:56 sm5504-352 erigon[3925470]: [INFO] [03-06|17:52:56.393] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:53:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:53:16.380] [txpool] stat                            block=39564607 pending=11 baseFee=0 queued=24 alloc=1.5GB sys=1.9GB
Mar 06 17:53:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:53:16.393] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:53:36 sm5504-352 erigon[3925470]: [INFO] [03-06|17:53:36.392] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:53:56 sm5504-352 erigon[3925470]: [INFO] [03-06|17:53:56.393] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:54:14 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:14.727] [p2p] GoodPeers                          eth66=82 eth67=1 eth68=1
Mar 06 17:54:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:16.389] [txpool] stat                            block=39564607 pending=49 baseFee=4 queued=9436 alloc=2.8GB sys=4.0GB
Mar 06 17:54:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:16.392] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:54:16 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:16.392] Req/resp stats                           req=967 reqMin=39821121 reqMax=40034207 skel=19 skelMin=39821311 skelMax=39858367 resp=2274 respMin=39821122 respMax=40037868 dups=241201
Mar 06 17:54:36 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:36.393] [2/15 Headers] No block headers to write in this log period block number=39821312
Mar 06 17:54:36 sm5504-352 erigon[3925470]: [INFO] [03-06|17:54:36.393] Req/resp stats                           req=1363 reqMin=39821121 reqMax=39987359 skel=19 skelMin=39821311 skelMax=39858367 resp=2848 respMin=39821122 respMax=40037877 dups=274266`
````

**Comment by 0x19dG87** [comment]
Return back to 2.37.0 and it does not have this problem

`Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.275] New txs subscriber joined
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.276] Reading JWT secret                       path=/storage/erigon/datadir/jwt.hex
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.277] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.278] HTTP endpoint opened                     url=172.20.0.1:8545 ws=true ws.compression=true grpc=false
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.285] [2/15 Headers] Waiting for headers...    from=39820950
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.286] [txpool] Started
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.299] Started P2P networking                   version=67 self=enode://fe783c8f5d4ad894dc3504958a168348f2343061de2165a0a2c7ba158ad69602de8e8b50f574a4c9464d80d82fdcdbe373e3d206d96201c5f17d5e584e7afd98@127.0.0.1:30304 name=erigon/v2.37.0-stable-12419c75/linux-amd64/go1.18.1
Mar 06 20:56:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:39.319] Started P2P networking                   version=66 self=enode://fe783c8f5d4ad894dc3504958a168348f2343061de2165a0a2c7ba158ad69602de8e8b50f574a4c9464d80d82fdcdbe373e3d206d96201c5f17d5e584e7afd98@127.0.0.1:30303 name=erigon/v2.37.0-stable-12419c75/linux-amd64/go1.18.1
Mar 06 20:56:59 sm5504-352 erigon[4073503]: [INFO] [03-06|20:56:59.286] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:57:19 sm5504-352 erigon[4073503]: [INFO] [03-06|20:57:19.286] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:57:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:57:39.276] [txpool] stat                            block=39564607 pending=0 baseFee=0 queued=1 alloc=77.8MB sys=165.8MB
Mar 06 20:57:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:57:39.286] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:57:59 sm5504-352 erigon[4073503]: [INFO] [03-06|20:57:59.286] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:58:19 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:19.287] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:58:19 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:19.287] Req/resp stats                           req=1 reqMin=40042322 reqMax=40042514 skel=18 skelMin=39820950 skelMax=39857814 resp=2 respMin=0 respMax=0 dups=0
Mar 06 20:58:36 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:36.060] [p2p] GoodPeers                          eth66=66 eth67=0
Mar 06 20:58:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:39.276] [txpool] stat                            block=39564607 pending=1 baseFee=0 queued=1 alloc=94.3MB sys=173.9MB
Mar 06 20:58:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:39.286] [2/15 Headers] No block headers to write in this log period block number=39820950
Mar 06 20:58:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:39.286] Req/resp stats                           req=3 reqMin=40041963 reqMax=40042539 skel=20 skelMin=39820950 skelMax=39857814 resp=3 respMin=40042156 respMax=40042540 dups=0
Mar 06 20:58:59 sm5504-352 erigon[4073503]: [INFO] [03-06|20:58:59.287] [2/15 Headers] Wrote block headers       number=39826134 blk/second=259.200 alloc=115.9MB sys=221.7MB
Mar 06 20:59:19 sm5504-352 erigon[4073503]: [INFO] [03-06|20:59:19.285] [2/15 Headers] Inserting headers         progress=39877402 queue=1
Mar 06 20:59:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:59:39.276] [txpool] stat                            block=39564607 pending=112 baseFee=60 queued=3351 alloc=270.7MB sys=433.4MB
Mar 06 20:59:39 sm5504-352 erigon[4073503]: [INFO] [03-06|20:59:39.286] [2/15 Headers] Inserting headers         progress=39917164 queue=1
Mar 06 20:59:59 sm5504-352 erigon[4073503]: [INFO] [03-06|20:59:59.287] [2/15 Headers] Wrote block headers       number=39968790 blk/second=7132.800 alloc=250.0MB sys=433.6MB
Mar 06 21:00:16 sm5504-352 erigon[4073503]: [INFO] [03-06|21:00:16.348] [2/15 Headers] Processed                 highest inserted=40042570 age=3s
Mar 06 21:00:16 sm5504-352 erigon[4073503]: [INFO] [03-06|21:00:16.348] [2/15 Headers] DONE                      in=3m37.063151609s
Mar 06 21:00:36 sm5504-352 erigon[4073503]: [INFO] [03-06|21:00:36.061] [p2p] GoodPeers                          eth66=88 eth67=1
Mar 06 21:00:39 sm5504-352 erigon[4073503]: [INFO] [03-06|21:00:39.278] [txpool] stat                            block=39564607 pending=117 baseFee=108 queued=5658 alloc=102.0MB sys=544.6MB
Mar 06 21:00:49 sm5504-352 erigon[4073503]: [INFO] [03-06|21:00:49.779] [5/15 Bodies] Processing bodies...       from=39820950 to=40042570
Mar 06 21:01:09 sm5504-352 erigon[4073503]: [INFO] [03-06|21:01:09.779] [5/15 Bodies] Downloading block bodies   block_num=39831833 delivery/sec=76.1MB wasted/sec=0B remaining=210736 delivered=32813 cache=256.0MB alloc=465.9MB sys=1008.8MB
Mar 06 21:01:29 sm5504-352 erigon[4073503]: [INFO] [03-06|21:01:29.880] [5/15 Bodies] Writing block bodies       block_num=39838316 remaining=204254 alloc=482.1MB sys=1.1GB
Mar 06 21:01:39 sm5504-352 erigon[4073503]: [INFO] [03-06|21:01:39.829] [txpool] stat                            block=39564607 pending=117 baseFee=151 queued=7722 alloc=508.9MB sys=1.1GB
Mar 06 21:01:49 sm5504-352 erigon[4073503]: [INFO] [03-06|21:01:49.784] [5/15 Bodies] Writing block bodies       block_num=39865055 remaining=177515 alloc=342.0MB sys=1.1GB`

**Comment by AskAlexSharov** [comment]
`alloc=2.8GB` means Erigon using 3GB. 
maybe related to: https://github.com/ledgerwatch/erigon#htop-shows-incorrect-memory-usage

**Comment by 0xKrishna** [comment]
Regarding `no block header issue`
Try https://github.com/ledgerwatch/erigon/pull/7046

**Comment by 0x19dG87** [comment]
> `alloc=2.8GB` means Erigon using 3GB. maybe related to: https://github.com/ledgerwatch/erigon#htop-shows-incorrect-memory-usage

But in this case, my server would not have stopped responding. I had to reboot the server in order to run at least some commands. I am wondering if it is only me facing this issue

**Comment by AskAlexSharov** [comment]
when you see high `alloc` in logs or RAM in monitoring: 
```
add flag --pprof
go tool pprof -inuse_space -png http://127.0.0.1:6060/debug/pprof/heap > mem.png
```
show this file
