### ISSUE TITLE
erigon version 2.40.0-stable debug_traceTransaction is not woking for eth chain and  paniced

### ISSUE THREAD

**Issue by justforfunya** [ledgerwatch/erigon#7040]
#### System information

Erigon version: `./erigon --version`
erigon version 2.40.0-stable
OS & Version: Windows/Linux/OSX
ubuntu 20.04
Commit hash: 
https://github.com/ledgerwatch/erigon/commit/38fb38a92edccb9ea1505686ed5e361208bf81f1
Erigon Command (with flags/config):
 ./erigon --chain=mainnet --datadir eth_data --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=192.168.0.108 --torrent.download.rate=50m --torrent.upload.rate=100kb --ws --http.api=eth,debug,net,trace,web3,erigon --authrpc.port=8551 --torrent.port=86581 --private.api.addr=0.0.0.0:9091 --port=8658 --prune= --prune.h.older=12000000 --prune.r.older=12000000 --prune.t.older=12000000 --prune.c.older=12000000 --snapshots=true --p2p.protocol=66
Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 
eth
#### Expected behaviour
erigon version 2.40.0-stable debug_traceTransaction not woking for eth chain，and triggers panic

#### Actual behaviour
 curl -X POST --data '{
>    "jsonrpc": "2.0",
>    "method": "debug_traceTransaction",
>    "params": ["0xefbd76fa76a70a2736bfe015a4fab42c3ff4fa814d26679dab8625ebbac824da"],
>    "id": "0xefbd76fa76a70a2736bfe015a4fab42c3ff4fa814d26679dab8625ebbac824da"
> }' -H 'content-type:application/json;' http://192.168.1.108:8545
{"jsonrpc":"2.0","id":"0xefbd76fa76a70a2736bfe015a4fab42c3ff4fa814d26679dab8625ebbac824da","result":{"structLogs":[],"gas":21000,"failed":false,"returnValue":""}}

erigon says:
[EROR] [03-07|11:12:51.518] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
#### Steps to reproduce the behaviour
just run latest verson the trace any tx than has been synced

#### Backtrace
here is the panic info
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1563 eth_api.go:282 tracing.go:191 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]
[EROR] [03-07|11:10:00.276] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1563 eth_api.go:282 tracing.go:191 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]
[INFO] [03-07|11:10:18.184] [LightClient] P2P                        peers=1
[INFO] [03-07|11:10:18.976] [txpool] stat                            block=16771510 pending=10000 baseFee=3721 queued=30000 alloc=2.5GB sys=7.7GB
[EROR] [03-07|11:10:49.565] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1563 eth_api.go:282 tracing.go:191 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]
[INFO] [03-07|11:11:18.183] [txpool] stat                            block=16771510 pending=10000 baseFee=3724 queued=30000 alloc=2.8GB sys=7.7GB
[INFO] [03-07|11:11:18.184] [LightClient] P2P                        peers=3
[INFO] [03-07|11:11:37.308] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=00000000000000000000000000000000000000000000000000000000000002feffffffff
[INFO] [03-07|11:11:46.435] [p2p] GoodPeers                          eth66=84
[EROR] [03-07|11:11:51.532] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1563 eth_api.go:282 tracing.go:191 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]
[INFO] [03-07|11:12:06.471] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000229d70bc1ca126f854aa9df814af1844495bc77affffffff
[INFO] [03-07|11:12:18.184] [LightClient] P2P                        peers=1
[INFO] [03-07|11:12:18.189] [txpool] stat                            block=16771510 pending=10000 baseFee=3729 queued=30000 alloc=2.5GB sys=7.7GB
[INFO] [03-07|11:12:36.585] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000557b08a0cab46bfe22471b65522757ea92a9e7a5ffffffff
[EROR] [03-07|11:12:51.518] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 block.go:1563 eth_api.go:282 tracing.go:191 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]
[INFO] [03-07|11:13:06.488] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000917ad55ee8a34c2074ce729212e4216a833beb18ffffffff
[INFO] [03-07|11:13:18.181] [txpool] stat                            block=16771510 pending=10000 baseFee=3733 queued=30000 alloc=3.0GB sys=7.7GB
````
[backtrace]
````

this error is not  happen on older version before 3.40

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/7042
