### ISSUE TITLE
Analysis of chaindata/mdbx.dat - best backup strategies for such a huge file

### ISSUE THREAD

**Issue by J-A-M-E-5** [ledgerwatch/erigon#7050]
I thought I'd open up a ticket (this is not a bug) to encourage feedback and input from others. Idea is devising the best strategy for regular backups of erigon to "the cloud". The principle problem is tackling the 1.7TB mdbx.dat file, the main database. Unless you have super-fast bandwidth you are not going to send 1.7TB of data in 24 hours! If you are already running your erigon in the cloud (VPS/dedicated server) then you don't have this problem, but many users would be running locally simply because it's expensive having a node in the cloud principally due to disk-space required. However for $5/month you can store 2TB of backups with a backup service.

### Following assumptions have been made.

- MDBX database has a default pagesize of 4KB (this is the standard unless you tweak options when performing initial sync of erigon).
- User has 2TB of "scratch storage" on the local system - perhaps a hard disk. A place to quickly copy their mdbx.dat file to, for minimum erigon downtime possible. I personally run erigon and geth purged node so always have new block announcement/TXs etc.. unless geth happened to crash whilst I was backing up erigon, but redundancy is a whole subject unto itself, so let's try and keep the problem as simple as possible...

### Basic steps (we won't go into how-to backup other erigon files as that's quite simple): 

1. Shutdown erigon.
2. Copy mdbx.dat to scratch storage + other erigon files.
3. Restart erigon. (step 2 could have taken ~3 hours, so that's 3 hours downtime).
4. Copy scratch storage to cloud.
5. Goto step 1

### Slightly more advanced (minimise erigon downtime):

1. Shutdown erigon.
2. If on LVM turn on snapshotting, otherwise with btrfs/ZFS etc.. make a snapshotted (frozen) version of the mdbx.dat file
3. Copy other files (this is quick as it is mostly appended data)
4. Restart erigon (steps 2 to 3 for sure took less than 5 minutes, you had less than 5 minutes downtime).
5. Copy snapshot to scratch storage
6. Delete snapshot - it should be noted until you delete the snapshot your disk I/O will be reduced.
7. Copy scratch storage to cloud
8. Goto step 1

So whilst your "backup" is now on the scratch disk it's not really a backup as its sitting inside the same server and an electrical problem could destroy everything. You might do a rsync over a LAN to another server which removes that issue, but a building fire destroys your backup. Until that backup is miles away you have no real backup. Which brings us to the cloud...

OK so first backup to cloud there's no other way of doing it except for sending the 1.7TB. This took over 10 days for me. After that your backup is 10 days out of date, which means any attempts to differential copy (e.g. rsync with delta) will have a high load of 10 days worth of changes to process. Say this takes 8 days. You then have for the next backup just 8 days worth of changes which is going to be less to transfer and probably takes 6  days, and so on... As long as whatever strategy you use keeps reducing the time between backups, eventually this _should_ come down to around the desired 24 hours.

Rsync has a standard block_size "window" which is automatically calculated but can be manually specified. According to [this post](https://unix.stackexchange.com/a/587783) as we are dealing with a massive file our default rsync block size is going to be ~131KB which is for sure not optimal unless you have very few changes (minutes/hours) to the database since last backup. If you have lots of memory you can specify a block size of just 4KB and use the [--max-alloc=SIZE](https://download.samba.org/pub/rsync/rsync.1#opt--max-alloc) parameter. Whilst this 4KB matches erigon's default database pagesize this is probably not optimal either as for every block there is not only a memory overhead (--max-alloc will need to be around 32GiB for 4KB block size) but there will also be an overhead in internet traffic per block to ensure each block is delta-synced.

Also you have to bare in mind if your last backup was 12 hours ago your optimal block size will be different than if your last backup was 30 days ago.

This is where I am now, on the second sync running with a 8KB rsync blocksize. It seems around 3x quicker than the initial sync. Why 8KB? I dunno. 4KB seemed too silly. 1MB seemed too high. I'd like to know if this was optimal.

### Other ideas I've thought of:-

Use a tool such as [dcfldd](https://manpages.ubuntu.com/manpages/jammy/man1/dcfldd.1.html) to read the database but split it into files of N-bytes size, with the advantage that the entire file (as it was read from input) is md5summed for integrity, and also each part is. This makes one big problem into potentially thousands of little ones, which could all be rsynced. The only real downside to this is if you need to restore you might need extra diskspace to eventually "cat" the split files back into one big file. This means you can use 4KB rsync blocksize for these files on a system with less than 32GB of free memory. You could also be smarter  and compare the hashes of each split file (dcfldd already hashed them) to the previous backup, if it is the same as last time you can set the timestamp for that file to be the same as last time and rsync will ignore it as that particular chunk was unchanged.

This is where I am. I aim to revise this ticket as I make new discoveries and technical findings, perhaps upload some bash script or code examples etc... Relying on the collective brain-power and experience of all erigon users who for sure if they are interested in backups have seen these issues.

I guess the best thing that could be achieved is to take a local backup of database at 00:00 UTC on day 1, and the same backup at 00:00 UTC day 2. And then create (or find) a tool to analyse differences between both files and calculate an optimal block size. Then repeat for an interlude of 2 days, 3 days, perhaps up to 20 days or until we got a good feel for how much 24 hours of blockchain activity impacts the database in terms of where changes are happening. Of course this is not exact as every 24 hours on the blockchain is different, but it has to be better than plucking numbers out of the air! Knowing a good blocksize to use depending on how many days your last-backup is stale, would help users get to the (for now) mythical status of sub-24 hour cloud backups as quickly as possible. There's also other variables to consider, what happens if you compact/reindex your erigon database - I'd presume you'd be back to waiting 10 days to back it up as practically every block would change.

To be continued... I appreciate all input & feedback.

**Comment by J-A-M-E-5** [comment]
Some other ideas. Sync erigon with page size of 512K rather than standard 4K. I will be doing a resync from zero of Erigon as soon as I get my secondary server setup (redundancy) as I am not sure due to crashing a few times if my database is tainted or not, so may as well try this 512K page size.

Apparently according to the lead dev with a bigger page size it makes the filesize of mdbx.dat smaller but there is no performance difference or perhaps a slight decrease when running erigon - or at least he didn't see one. At this stage I'd be happy to sacrifice a little bit of erigon performance for a faster backup and less disk-space so I think these variables all need to be investigated. Also of course whilst my aim is to speed up rsync, the principle of block-sizes and finding "the best" applies to RAID stripe sizes, filesystem block/cluster sizes, which effects thing such as snapshots too. It for sure makes a big difference specifying block size instead of accepting default when creating LVM partitions and how each snapshot is a series of block-level changes.

I am not sure if after a full sync of erigon if the best thing to do first would be a full compact of the database, and then initial backup or if it is better to leave the database with this "slack space". My upload speed is limited to around 3MiB/s, however recently with ~10% of today's backup rsynced using delta against backup from ~14 days ago I have seen rsync processing speeds of 120MiB/s. For the first 5% of the file rsync speed seemed to be max upload speed which suggests lots of changes at the start of the file. I almost gave up the idea of trying to rsync/delta before I saw this 120MiB/s, so patience is indeed a virtue. Obviously running at 40x my connection speed suggests that around 10% into the file not a lot has changed in the past 2 weeks. Now a slow speed is around 8MiB/s which is still double my wire speed so the delta algo is performing well at 8k block size. Would it perform better at 16k? At 4k? I dunno!!!

So my latest rsync estimates are around 60 hours for this backup to be complete, which is a huge increase from the ~340 hours initial backup took. Of course if I then immediately do another backup I'll only have 60 hours of changes for rsync to diff. I think I'm going to keep this 8k rsync blocksize even though right now it's consuming a lot of RAM, at least until I get under 24 hours backup time, and then bring it up and keep rsyncing and see what happens as I cannot dedicate this much RAM permanently for backups.

**Comment by dreadedhamish** [comment]
Have you considered using ZFS snapshots and ZFS send/recv? I'm still researching it, but it looks fairly basic to take regular snapshots (incremental) and send them to a remote repository.  You wouldn't need to stop Erigon, and snapshots only take up space when there are changes.

**Comment by dreadedhamish** [comment]
Snapshots saves some time downloading, but it's not downloading the processed state, only the transactions in bulk, which erigon then processes. You are still looking at days depending on your system specs. The answer should be just copying the database.

**Comment by dreadedhamish** [comment]
Check out ZFS. You can perform snapshots and export them without any downtime.

**Comment by dreadedhamish** [comment]
Full disclosure - i haven't set it up yet, and I'm early in the process. Everywhere I've read praises ZFS for these instant snapshots, so I'm hoping it as good as promised. 
There are 2 ways I'm planning on using it - hourly snapshots that aren't kept for very long. I've recently had my erigon database get corrupted, and when this happens again I plan on restoring from these local snapshots. As a secondary backup I'll have another pool somewhere else that uses zfs-send to only send snapshots - so only incremental changes.
Looking at the ZFS features I'm not sure you coudn't set the 2 databases up to mirror each other, and then do a push/pull if one has an error.
