### ISSUE TITLE
Prune settings no longer work in 2.40.1 coming from 2.39.0

### ISSUE THREAD

**Issue by greenertux** [ledgerwatch/erigon#7057]
#### System information

Erigon version: 2.40.1

OS & Version: Linux

Commit hash: 94b4cee5a898a47b9241ce824622af6350e5dc5b

Erigon Command (with flags/config): 

Concensus Layer: n/a

Chain/Network: ETH

#### Expected behaviour
Erigon should run using --prune=htc in version 2.40.1 as it did in 2.39.0

#### Actual behaviour
I get the following error when replacing the 2.39.0 image by 2.40.1 (docker):
err="not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000"
not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000

Even running explicitly with the flags mentioned in the error message does not solve the error.

#### Steps to reproduce the behaviour
Run erigon 2.39.0 with --prune=htc and migrate to 2.40.1

**Comment by mandrigin** [comment]
in 2.40.0 there was a breaking change in Docker, probably you didn't adjust your command line

**Comment by greenertux** [comment]
Thanks, apparently I misunderstood it. I removed "erigon" from my command arguments and it started working again.
