### ISSUE TITLE
Infinite loop "[parlia] snapshots build, gather headers"

### ISSUE THREAD

**Issue by zhy827827** [ledgerwatch/erigon#7067]
Erigon verison:2.40.1,Data  will not be synchronized.Infinite loop "[parlia] snapshots build, gather headers"

Mar 10 02:01:15 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:15.351] [parlia] snapshots build, gather headers block=25100000
Mar 10 02:01:15 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:15.522] [parlia] snapshots build, gather headers block=25000000
Mar 10 02:01:15 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:15.694] [parlia] snapshots build, gather headers block=24900000
Mar 10 02:01:15 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:15.864] [parlia] snapshots build, gather headers block=24800000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.037] [parlia] snapshots build, gather headers block=24700000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.207] [parlia] snapshots build, gather headers block=24600000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.377] [parlia] snapshots build, gather headers block=24500000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.550] [parlia] snapshots build, gather headers block=24400000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.721] [parlia] snapshots build, gather headers block=24300000
Mar 10 02:01:16 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:16.891] [parlia] snapshots build, gather headers block=24200000
Mar 10 02:01:17 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:17.075] [parlia] snapshots build, gather headers block=24100000
Mar 10 02:01:17 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:17.249] [parlia] snapshots build, gather headers block=24000000
Mar 10 02:01:17 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:17.488] [parlia] snapshots build, gather headers block=23900000
Mar 10 02:01:17 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:17.856] [parlia] snapshots build, gather headers block=23800000
Mar 10 02:01:18 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:18.080] [parlia] snapshots build, gather headers block=23700000
Mar 10 02:01:18 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:18.273] [parlia] snapshots build, gather headers block=23600000
Mar 10 02:01:18 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:18.450] [parlia] snapshots build, gather headers block=23500000
Mar 10 02:01:18 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:18.620] [parlia] snapshots build, gather headers block=23400000
Mar 10 02:01:18 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:18.795] [parlia] snapshots build, gather headers block=23300000
Mar 10 02:01:19 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:19.525] [parlia] snapshots build, gather headers block=25800000
Mar 10 02:01:19 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:19.712] [parlia] snapshots build, gather headers block=25700000
Mar 10 02:01:19 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:19.891] [parlia] snapshots build, gather headers block=25600000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.069] [parlia] snapshots build, gather headers block=25500000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.243] [parlia] snapshots build, gather headers block=25400000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.420] [parlia] snapshots build, gather headers block=25300000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.594] [parlia] snapshots build, gather headers block=25200000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.768] [parlia] snapshots build, gather headers block=25100000
Mar 10 02:01:20 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:20.940] [parlia] snapshots build, gather headers block=25000000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.112] [parlia] snapshots build, gather headers block=24900000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.283] [parlia] snapshots build, gather headers block=24800000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.456] [parlia] snapshots build, gather headers block=24700000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.626] [parlia] snapshots build, gather headers block=24600000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.799] [parlia] snapshots build, gather headers block=24500000
Mar 10 02:01:21 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:21.976] [parlia] snapshots build, gather headers block=24400000
Mar 10 02:01:22 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:22.150] [parlia] snapshots build, gather headers block=24300000
Mar 10 02:01:22 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:22.322] [parlia] snapshots build, gather headers block=24200000
Mar 10 02:01:22 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:22.737] [parlia] snapshots build, gather headers block=24100000
Mar 10 02:01:22 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:22.959] [parlia] snapshots build, gather headers block=24000000
Mar 10 02:01:23 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:23.158] [parlia] snapshots build, gather headers block=23900000
Mar 10 02:01:23 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:23.329] [parlia] snapshots build, gather headers block=23800000
Mar 10 02:01:23 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:23.503] [parlia] snapshots build, gather headers block=23700000
Mar 10 02:01:23 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:23.675] [parlia] snapshots build, gather headers block=23600000
Mar 10 02:01:23 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:23.846] [parlia] snapshots build, gather headers block=23500000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.017] [parlia] snapshots build, gather headers block=23400000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.189] [parlia] snapshots build, gather headers block=23300000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.365] [parlia] snapshots build, gather headers block=25800000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.537] [parlia] snapshots build, gather headers block=25700000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.712] [parlia] snapshots build, gather headers block=25600000
Mar 10 02:01:24 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:24.886] [parlia] snapshots build, gather headers block=25500000
Mar 10 02:01:25 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:25.075] [parlia] snapshots build, gather headers block=25400000
Mar 10 02:01:25 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:25.262] [parlia] snapshots build, gather headers block=25300000
Mar 10 02:01:25 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:25.448] [parlia] snapshots build, gather headers block=25200000
Mar 10 02:01:25 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:25.641] [parlia] snapshots build, gather headers block=25100000
Mar 10 02:01:25 rockx-mainnet-bsc-archive-sg-02 erigon[996723]: [INFO] [03-10|02:01:25.817] [parlia] snapshots build, gather headers block=25000000

**Comment by hackhy** [comment]
The same bug

**Comment by YuXiaoCoder** [comment]
The same bug

**Comment by wpexia** [comment]
same here, any updates?

**Comment by yperbasis** [comment]
BSC is no longer supported by Erigon. Please consider https://github.com/node-real/bsc-erigon instead.
