### ISSUE TITLE
batch limit 100 exceeded:

### ISSUE THREAD

**Issue by ashrita-systango** [ledgerwatch/erigon#7072]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Chain/Network: 
Ethereum / Mainnet

#### Expected behaviour
I am calling eth_getTransactionReceipt method via http request, ideally it should give me result.

#### Actual behaviour
I am getting limit exceeded error, 
````
{"jsonrpc":"2.0","id":null,"error":{"code":-32000,"message":"batch limit 100 exceeded: 142 requests given"}}
````

#### Sample code
````
        reqs = []
        receipts = []
        for transaction in transactions:
            params = {
                "method": "eth_getTransactionReceipt",
                "params": [transaction],
                "id": transaction,
                "jsonrpc": "2.0",
            }
            reqs.append(params)

         response = requests.request("POST", url, data=reqs)
````

**Comment by AskAlexSharov** [comment]
--batch limit

**Comment by AskAlexSharov** [comment]
--rpc.batch.limit

**Comment by ashrita-systango** [comment]
Updated the --rpc.batch.limit to 1500 still getting the batch limit error
![image_2023_03_13T12_10_31_228Z](https://user-images.githubusercontent.com/52913696/224698215-790609ba-2d0a-4324-b24a-db02698e42f1.png)
![Screenshot from 2023-03-13 17-41-55](https://user-images.githubusercontent.com/52913696/224698238-e00a7348-1926-47ed-ab01-601d00bc5094.png)

**Comment by AskAlexSharov** [comment]
@ashrita-systango i don't know - it must work. maybe related to this breaking change: https://github.com/ledgerwatch/erigon/releases/tag/v2.40.0
