### ISSUE TITLE
LightClient Peers after v2.37.0 

### ISSUE THREAD

**Issue by keithchew** [ledgerwatch/erigon#7076]
Erigon version: 2.40.1

Has anyone else noticed that after v2.37.0, it is hard to find peers for the internal lightclient? In v2.37, there were always peers in mainnet (for goerli it is less, but still workable). I have tried v2.38, 2.39 and v2.40, and this is common in the logs:
```
[INFO] [03-10|13:06:47.119] [p2p] GoodPeers                          eth67=33 eth68=33
[INFO] [03-10|13:06:55.574] [LightClient] P2P                        peers=0
```
Sometimes it goes up to 1 or 2 then back to 0. As a result, erigon gets stuck, up to days.

**Comment by SilversterSunset** [comment]
You can try the `--v5disc` flag. It helped me. Also pay attention to these options: `--lightclient.discovery.port`, `--lightclient.discovery.tcpport`.

**Comment by whidrasl** [comment]
Solved in https://github.com/ledgerwatch/erigon/issues/7077?
Maybe users use internal client, but only some of them allow external connections (maybe beacause of `--lightclient.discovery.addr=127.0.0.1` by default). And that's why most of users can't connect to each other :-)

**Comment by winchell** [comment]
Having this issue as well. @keithchew are you in a cloud/container environment?
