### ISSUE TITLE
Runtime Error : index out of range [7] with length 0

### ISSUE THREAD

**Issue by mr-stegosaurus** [ledgerwatch/erigon#7079]
#### System information

Erigon version: v2.31.0-rc.4-661-gd5fbc5011 

OS & Version: Linux

Erigon Command (with flags/config): ./build/bin/erigon --datadir=../goerli/ --chain=goerli --prune.t.older 90000 --torrent.download.rate=20mb --externalcl -http

Concensus Layer: Prysm

Concensus Layer Command (with flags/config):
./prysm.sh beacon-chain --datadir=../goerli --p2p-max-peers=150 --execution-endpoint=http://localhost:8551 --prater --jwt-secret=/home/mrstego123/Ethereum/execution/goerli/jwt.hex --genesis-state=genesis.ssz

Chain/Network: Goerli

#### Expected behavior
I believe it should be processing snapshots without runtime errors. Seems to sync extremely slowly under these conditions. Often 2blck/s

#### Actual behavior
After running up to the execution stage, it seems to randomly start outputting the errors show below. Not sure what is causing these runtime errors. When hitting this stage it will print runtime errors for each block, Prysm will switch to optimistic mode and the sync process goes from 15hr left to 125hr left. Seems like something is running incorrectly.

I've tried wiping chaindata clean and starting from scratch. Ran "make integration" workflow and it didn't seem to fix anything.

#### Steps to reproduce the behaviour
Run the above commands, will exist with and without Prysm running

#### Backtrace

WARN[03-10|20:34:46.691] no log dir set, console logging only 
WARN[03-10|20:34:46.696] no log dir set, console logging only 
INFO[03-10|20:34:46.696] Build info                               git_branch=devel git_tag=v2.31.0-rc.4-661-gd5fbc5011 git_commit=d5fbc5011e44bf47bcd7e2be128b812dc2d5ed5f
INFO[03-10|20:34:46.696] Starting Erigon on Görli testnet... 
INFO[03-10|20:34:46.699] Maximum peer count                       ETH=100 total=100
INFO[03-10|20:34:46.699] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[03-10|20:34:46.699] torrent verbosity                        level=WRN
INFO[03-10|20:34:48.800] Set global gas cap                       cap=50000000
INFO[03-10|20:34:48.801] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=20mb upload.rate=4mb
INFO[03-10|20:34:48.801] Opening Database                         label=chaindata path=/home/mrstego123/Ethereum/execution/goerli/chaindata
INFO[03-10|20:34:48.803] Initialised chain configuration          config="{ChainID: 5, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 1561651, Muir Glacier: <nil>, Berlin: 4460644, London: 5062605, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: 10790000, Merge Netsplit: <nil>, Shanghai: 1678832736, Cancun: <nil>, Sharding: <nil>, Prague: <nil>, Engine: clique}" genesis=0xbf7e331f7f7c1dd2e05159666b3bf8bc7a8a3a9eb1d518969eab529dd9b88c1a
INFO[03-10|20:34:48.803] Effective                                prune_flags="--prune.t.older=90000" snapshot_flags="--snapshots=true" history.v3=false
INFO[03-10|20:34:49.710] Initialising Ethereum protocol           network=5
INFO[03-10|20:34:49.721] Starting private RPC server              on=127.0.0.1:9090
INFO[03-10|20:34:49.721] new subscription to logs established 
INFO[03-10|20:34:49.721] rpc filters: subscribing to Erigon events 
INFO[03-10|20:34:49.721] New txs subscriber joined 
INFO[03-10|20:34:49.721] new subscription to newHeaders established 
INFO[03-10|20:34:49.721] Reading JWT secret                       path=/home/mrstego123/Ethereum/execution/goerli/jwt.hex
INFO[03-10|20:34:49.721] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
INFO[03-10|20:34:49.721] HTTP endpoint opened                     url=127.0.0.1:8545 ws=false ws.compression=true grpc=false
INFO[03-10|20:34:49.732] [txpool] Started 
INFO[03-10|20:34:49.732] [1/15 Snapshots] Fetching torrent files metadata 
INFO[03-10|20:34:49.733] [snapshots] Blocks Stat                  blocks=8500k indices=8500k alloc=685.8MB sys=854.1MB
INFO[03-10|20:34:49.734] Started P2P networking                   version=68 self=enode://4c9644c5814d4976396a84cdf1f8a6289e89f6bb552d668c8e2c847bc15ef81aafb0de7858150c10551a90f8f8fc8962c5fae875fe56658ad565dc540c6e2f4a@127.0.0.1:30304 name=erigon/v2.40.0-dev-d5fbc501/linux-amd64/go1.18.1
INFO[03-10|20:34:49.739] Started P2P networking                   version=67 self=enode://4c9644c5814d4976396a84cdf1f8a6289e89f6bb552d668c8e2c847bc15ef81aafb0de7858150c10551a90f8f8fc8962c5fae875fe56658ad565dc540c6e2f4a@127.0.0.1:30303 name=erigon/v2.40.0-dev-d5fbc501/linux-amd64/go1.18.1
EROR[03-10|20:34:50.152] Staged Sync                              err="runtime error: index out of range [7] with length 0, trace: [stageloop.go:132 panic.go:844 panic.go:89 binary.go:125 accessors_chain.go:1315 block_snapshots.go:1127 stage_snapshots.go:525 default_stages.go:25 sync.go:425 sync.go:285 stageloop.go:251 kv_mdbx.go:676 stageloop.go:251 stageloop.go:94 asm_amd64.s:1571]"
INFO[03-10|20:34:50.670] [1/15 Snapshots] Fetching torrent files metadata 
INFO[03-10|20:34:50.671] [snapshots] Blocks Stat                  blocks=8500k indices=8500k alloc=944.5MB sys=1.0GB
EROR[03-10|20:34:51.184] Staged Sync                              err="runtime error: index out of range [7] with length 0, trace: [stageloop.go:132 panic.go:844 panic.go:89 binary.go:125 accessors_chain.go:1315 block_snapshots.go:1127 stage_snapshots.go:525 default_stages.go:25 sync.go:425 sync.go:285 stageloop.go:251 kv_mdbx.go:676 stageloop.go:251 stageloop.go:94 asm_amd64.s:1571]"
INFO[03-10|20:34:51.702] [1/15 Snapshots] Fetching torrent files metadata 
INFO[03-10|20:34:51.703] [snapshots] Blocks Stat                  blocks=8500k indices=8500k alloc=726.4MB sys=1.2GB
EROR[03-10|20:34:52.061] Staged Sync                              err="runtime error: index out of range [7] with length 0, trace: [stageloop.go:132 panic.go:844 panic.go:89 binary.go:125 accessors_chain.go:1315 block_snapshots.go:1127 stage_snapshots.go:525 default_stages.go:25 sync.go:425 sync.go:285 stageloop.go:251 kv_mdbx.go:676 stageloop.go:251 stageloop.go:94 asm_amd64.s:1571]"
^CINFO[03-10|20:34:52.080] Got interrupt, shutting down... 
INFO[03-10|20:34:52.080] Exiting Engine... 
INFO[03-10|20:34:52.080] RPC server shutting down 
INFO[03-10|20:34:52.080] RPC server shutting down 
INFO[03-10|20:34:52.080] Exiting... 
INFO[03-10|20:34:52.080] RPC server shutting down 
WARN[03-10|20:34:52.080] Failed to serve http endpoint            err="http: Server closed"
WARN[03-10|20:34:52.080] Failed to serve http endpoint            err="http: Server closed"
INFO[03-10|20:34:52.082] Engine HTTP endpoint close               url=127.0.0.1:8551
INFO[03-10|20:34:52.082] HTTP endpoint closed                     url=127.0.0.1:8545
mrstego123@Stakosaurus:~/Ethereum/execution/erigon$ ^C

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/7081
