### ISSUE TITLE
heimdall node setup for bor-mainnet with erigon

### ISSUE THREAD

**Issue by 0x090909** [ledgerwatch/erigon#7099]
Hello guys, I have a hard time figuring out how to setup heimdall for polygon with snapshots, all the docs around are outdated and the commands dont really work.

Is there somebody who can point out how to run a heimdall node locally?

Thank you

**Comment by zhy827827** [comment]
run a heimdall: [heimdall ](https://wiki.polygon.technology/docs/operate/full-node-binaries)

**Comment by Sreeram1993** [comment]
As per the readme docs it says, Erigon doesn't support block generation. Does that mean to setup an archival node with block generation we have to go with bor + heimdall itself rather than erigon+heimdall setup. If yes then what is the total archive size for bor+heimdall and if there are any snapshots available for archival data ?

**Comment by zhy827827** [comment]
https://github.com/ledgerwatch/erigon/issues/7103

**Comment by 0x090909** [comment]
> As per the readme docs it says, Erigon doesn't support block generation. Does that mean to setup an archival node with block generation we have to go with bor + heimdall itself rather than erigon+heimdall setup. If yes then what is the total archive size for bor+heimdall and if there are any snapshots available for archival data ?

https://snapshots.polygon.technology/

**Comment by thorstenhirsch** [comment]
You temporarily need ~9 TB:
- 2.2 TB for the erigon datadir snapshot download
- 5.9 TB for the extracted erigon datadir snapshot
- 0.2 TB for the heimdall datadir snapshot download
- 0.5 TB (or so) for the extracted heimdall datadir

So after extraction 6.x TB might be enough for the moment, but keep in mind that the data is steadily growing.
