### ISSUE TITLE
Erigon stopped taking params from docker-compose after updating to version 2.40.1

### ISSUE THREAD

**Issue by slider90** [ledgerwatch/erigon#7126]
#### System information

Erigon version: `2.40.1`

OS & Version: Docker(Linux)

#### Expected behaviour
Erigon node works as expected and takes params from docker-compose.

#### Actual behaviour
Erigon stopped taking params from docker-compose.
for example, “--authrpc.addr=0.0.0.0”,`

#### Steps to reproduce the behaviour
Update Erigon node to version 2.40.1
Update Lighthouse to version 3.5.1

Indicate in docker-compose in command block the following params:
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551

#### Backtrace
Version 2.40.1
````
[INFO] [03-17|10:36:49.411] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
[INFO] [03-17|10:36:49.412] HTTP endpoint opened                     url=127.0.0.1:8545 ws=false ws.compression=true grpc=false

````
Version 2.39.0
```
{“lvl”:“info”,“msg”:“HTTP endpoint opened for Engine API”,“t”:“2023-03-17T11:06:55.074551379Z”,“url”:“0.0.0.0:8551",“ws”:true,“ws.compression”:true}
```
So even after indicating `--authrpc.addr=0.0.0.0` param in docker-compose - version 2.40.1 doesn't take it.
Version 2.39.0 works as expected

**Comment by whidrasl** [comment]
where did you put `--authrpc.addr=0.0.0.0`? in docker-compose.yml? in .env (ERIGON_FLAGS)?

**Comment by whidrasl** [comment]
.yaml? not .yml?
`docker-compose.yml` is under Git. It's not supposed to be changed.
Anyway. Cloning https://github.com/ledgerwatch/erigon.git (devel branch), coping .env.example to .env, adding `ERIGON_FLAGS=--authrpc.addr=0.0.0.0` to .env and running `docker-compose up erigon` produces following log:
`HTTP endpoint opened for Engine API      url=[::]:8551 ws=true ws.compression=true`
without authrpc.addr it by default produces `HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true`

**Comment by slider90** [comment]
@whidrasl we changed this file, added params and saved with extension .yaml. It doesn't matter .yaml or yml for docker compose. 
which image version do you use? 
with version 2.39.0 it works as you described.
In 2.40.1 with -`-authrpc.addr=0.0.0.0` value Erigon produces `url=127.0.0.1:8551 ws=true ws.compression=true` but should be
`{“lvl”:“info”,“msg”:“HTTP endpoint opened for Engine API”,“t”:“2023-03-17T11:06:55.074551379Z”,“url”:“0.0.0.0:8551",“ws”:true,“ws.compression”:true}
`

**Comment by whidrasl** [comment]
If it is non-repository file, please show diff for it (where do you put new command-line arguments, at least).
And please check environment variables and .env file for --authrpc.addr

**Comment by whidrasl** [comment]
@slider90 my .env:
```
# host OS dedicated user (for docker especially)
ERIGON_USER=erigon

# UID, GID of user inside docker process which must exist also on host OS
DOCKER_UID=1000     # random number [1001, 10000] chosen arbitrarily for example
DOCKER_GID=1000     # can choose any valid #. 1000 tends to be taken by first user

ERIGON_FLAGS=--authrpc.addr=0.0.0.0
TAG=v2.40.1
```
So, in logs:
`Build info                               git_branch=heads/v2.40.1 git_tag=v2.40.1-dirty git_commit=94b4cee5a898a47b9241ce824622af6350e5dc5b`

**Comment by whidrasl** [comment]
BTW, did you see that?
![image](https://user-images.githubusercontent.com/14200104/225929143-99ee9f3a-b095-4340-87fa-30324ae65889.png)

**Comment by slider90** [comment]
@whidrasl The issue has been resolved. We fixed our docker-compose file.
Thanks a lot for you assistance.
