### ISSUE TITLE
Node lag and [Sentinel] fail to decode gossip packet  err="incorrect size"

### ISSUE THREAD

**Issue by mi-yu** [ledgerwatch/erigon#7128]
#### System information

Erigon version: `v2.33.1`

OS & Version: Linux

#### Details

Recently my Erigon node started to lag 10-15 blocks behind the tip of the chain for short periods of time, and I noticed these logs correlate with the lag spikes.

```
[WARN] [03-17|23:35:14.338] [Sentinel] fail to decode gossip packet  err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
```

I was unable to find more information about this log. I also noticed that there have been several releases since 2.33.1, would upgrading help here?

Thanks!

**Comment by Giulio2002** [comment]
https://github.com/ledgerwatch/erigon/pull/7134 fixed this
