### ISSUE TITLE
Erigon stuck at writing block headers

### ISSUE THREAD

**Issue by manjeet-thadani** [ledgerwatch/erigon#7140]
#### System information
I have setup polygon archive node with Erigon + Heimdall setup and my Erigon is stuck at processing block header (40449538) for more than 2 days with following log errors:
```
Mar 19 22:34:18 polygon-archive-2 erigon[117523]: [INFO] [03-19|22:34:18.804] [2/16 Headers] No block headers to write in this log period block number=40449538
Mar 19 22:34:18 polygon-archive-2 erigon[117523]: [INFO] [03-19|22:34:18.804] Req/resp stats                           req=98 reqMin=40446917 reqMax=40447206 skel=17 skelMin=40449538 skelMax=40744450 resp=130 respMin=40446919 respMax=40541200 dups=1021
```

However, Heimdall is completely synced and working fine. Also, I have verified Heimdall Rest Server is working fine.

Erigon version: erigon version 2.35.2-stable-800645ee
Heimdall version: 0.3.0

OS & Version: Linux

Erigon Commit hash: 800645eee

Erigon Command (with flags/config):
```
erigon --chain=bor-mainnet  --snapshots=true --bor.heimdall=http://localhost:1317 --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net,trace,web3,erigon,bor --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6969
```

Chain/Network:  137 mainnet

#### Expected behaviour
Erigon should start syncing the later blocks

#### Actual behaviour
Erigon is stuck at processing block header.

**Comment by 0xKrishna** [comment]
Try using v2.40.1 and v0.3.2 on heimdall
Also use `--snapshots=false` and remove `bor-heimdall` flag if you are using localhost 1317 as that is default.
