### ISSUE TITLE
JSONRPC return a broken json with message: "rlp: end of list"

### ISSUE THREAD

**Issue by AgoL5866** [ledgerwatch/erigon#7152]
#### System information

Erigon version: v2.40.1

OS & Version: Linux

Chain/Network: mainnet

#### Expected behaviour
response a right json string and error mesage

#### Actual behaviour
when request debug a blockNumber than the latest block, it will return a broken json.

#### Steps to reproduce the behaviour

current block : 16875449
```
curl http://endpoint_url --header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "params": ["16875450",{"tracer":"callTracer"}],
    "id": 1
}'
```
#### Backtrace

````
{
    "jsonrpc": "2.0",
    "id": 1,
    "result":nullnull,
    "error": {
        "code": -32000,
        "message": "rlp: end of list"
    }
}
````

**Comment by wahtique** [comment]
This seem like the same issue as https://github.com/ledgerwatch/erigon/issues/7033 .
