### ISSUE TITLE
Lighthouse 4.0.0 and "context canceled" Error 

### ISSUE THREAD

**Issue by JP-Ellis** [ledgerwatch/erigon#7172]
## System information

- Erigon Version: `erigon version 2.40.1-stable`
  - Command
    ```
    /usr/bin/erigon \
      --datadir=/eth/erigon \
      --http.port 8545 \
      --http.api eth,erigon,engine,web3 \
      --authrpc.port 8551 \
      --authrpc.jwtsecret /eth/jwt.hex \
      --private.api.addr localhost:8552 \
      --private.api.ratelimit 65536 \
      --metrics \
      --metrics.port 6060 \
      --externalcl \
      --prune htc \
      --prune.r.before=11184524
    ```
- OS: Linux (`Linux 6.1.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 04 Jan 2023 16:28:15 +0000 x86_64 GNU/Linux `)
- Concensus Layer: Lighthouse
  - Version:
    ```
    Lighthouse v4.0.0-0616e01
    BLS library: blst-modern
    SHA256 hardware acceleration: true
    Allocator: jemalloc
    Specs: mainnet (true), minimal (false), gnosis (true)
    ```
  - Command:
    ```
    /usr/bin/lighthouse beacon_node \
      --datadir /var/lib/lighthouse \
      --staking \
      --metrics \
      --validator-monitor-auto \
      --execution-endpoint http://localhost:8551 \
      --execution-jwt /eth/jwt.hex \
      --builder http://localhost:18550
    ```

## Behaviour

- After a few hours, sync stalls completely with the error `"context canceled"`.
- Once error happens, Erigon still generates logs, but generally appears unresponsive (sending a kill signal does not cause it to shut down, and I have to send all 10 kill signals for it to forcefully restart)
- After a restart, Erigon syncs again with no issues until this issue appears randomly
- This error only appeared after upgrading Lighthouse to `v4.0.0`. I have tested it with the `v4.0.1-rc.0` hotfix as well, and the error remains. I suspect that is the root cause of the issue.

Logs are located in the follow gist [JP-Ellis/30aeca74b7760ea603f709309051aefc](https://gist.github.com/JP-Ellis/30aeca74b7760ea603f709309051aefc)

**Comment by yorickdowne** [comment]
To be clear this is with Lighthouse `v4.0.0` or `v4.0.1-rc.0`.

Lighthouse complains that Erigon no longer responds on the Engine API

We've seen this on post-Shapella Goerli and pre-Shapella mainnet.

It's very reproducible, so it should be fairly easy to debug.

**Comment by JP-Ellis** [comment]
@yorickdowne The versions are specified verbatim in the main message, I just messed up the title.

I will be upgrading the `v4.0.1-rc.0` of Lighthouse in light of the [most recent release](https://github.com/sigp/lighthouse/releases/tag/v4.0.1-rc.0).

**Comment by yorickdowne** [comment]
"This error only appeared after upgrading Erigon to `v4.0.0`" - that's why the clarification.

`v4.0.1-rc.0` causes the same behavior with Erigon.

**Comment by JP-Ellis** [comment]
Entirely my bad, typo is fixed 👍

**Comment by yorickdowne** [comment]
I can reproduce this on Goerli with Erigon source-compiled from `devel` and Lighthouse `v4.0.1-rc.0`

**Comment by yorickdowne** [comment]
Debug logs. Failure around 11:49 UTC. Logs aren't very instructive alas
[erigonstall.debug.log.tar.gz](https://github.com/ledgerwatch/erigon/files/11068789/erigonstall.debug.log.tar.gz)

**Comment by yorickdowne** [comment]
Clarification: Erigon doesn't ignore SIGTERM. It just is unable to actually shut down entirely.

```
execution_1  | [INFO] [03-25|11:58:36.421] Got interrupt, shutting down... 
execution_1  | [DBUG] [03-25|11:58:36.421] Error while executing stage              err="[2/15 Headers] server is stopping"
execution_1  | [DBUG] [03-25|11:58:36.421] Handling incoming message                stream=RecvMessage err="context canceled"
execution_1  | [INFO] [03-25|11:58:36.421] Exiting Engine... 
execution_1  | [DBUG] [03-25|11:58:36.421] rpcdaemon: the subscription to pending blocks channel was closed 
execution_1  | [INFO] [03-25|11:58:36.421] RPC server shutting down 
execution_1  | [INFO] [03-25|11:58:36.421] Exiting... 
execution_1  | [INFO] [03-25|11:58:36.421] RPC server shutting down 
execution_1  | [DBUG] [03-25|11:58:36.421] Handling incoming message                stream=RecvUploadMessage err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.421] Served                                   conn=172.18.0.3:33076 method=engine_forkchoiceUpdatedV2 reqid=1 t=31m1.996573279s err="context canceled"
execution_1  | [DBUG] [03-25|11:58:36.421] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [WARN] [03-25|11:58:36.421] NewPayload                               err="context canceled"
execution_1  | [DBUG] [03-25|11:58:36.421] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [EROR] [03-25|11:58:36.421] Staged Sync                              err="[2/15 Headers] server is stopping"
execution_1  | [WARN] [03-25|11:58:36.422] Served                                   conn=172.18.0.3:49054 method=engine_newPayloadV2 reqid=1 t=35m23.820669261s err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.421] Served                                   conn=172.18.0.3:57830 method=engine_forkchoiceUpdatedV2 reqid=1 t=31m8.415568952s err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.421] NewPayload                               err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.422] Served                                   conn=172.18.0.3:49376 method=engine_newPayloadV2 reqid=1 t=25m16.930276228s err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.421] Served                                   conn=172.18.0.3:57810 method=engine_forkchoiceUpdatedV2 reqid=1 t=31m11.261330227s err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.422] Failed to serve http endpoint            err="http: Server closed"
execution_1  | [WARN] [03-25|11:58:36.421] Served                                   conn=172.18.0.3:57804 method=engine_forkchoiceUpdatedV2 reqid=1 t=31m16.417928013s err="context canceled"
execution_1  | [INFO] [03-25|11:58:36.421] RPC server shutting down 
execution_1  | [WARN] [03-25|11:58:36.423] Failed to serve http endpoint            err="http: Server closed"
execution_1  | [WARN] [03-25|11:58:36.421] NewPayload                               err="context canceled"
execution_1  | [WARN] [03-25|11:58:36.423] Served                                   conn=172.18.0.3:41594 method=engine_newPayloadV2 reqid=1 t=35m33.861133645s err="context canceled"
execution_1  | [DBUG] [03-25|11:58:36.422] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [DBUG] [03-25|11:58:36.423] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [DBUG] [03-25|11:58:36.423] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [DBUG] [03-25|11:58:36.423] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [DBUG] [03-25|11:58:36.421] Handling incoming message                stream=RecvMessage err="context canceled"
execution_1  | [INFO] [03-25|11:58:36.422] HTTP endpoint closed                     url=[::]:8545
execution_1  | [DBUG] [03-25|11:58:36.423] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [DBUG] [03-25|11:58:36.424] Handling incoming message                stream=RecvUploadHeadersMessage err="querying BlockHeaders: context canceled"
execution_1  | [INFO] [03-25|11:58:36.424] Engine HTTP endpoint close               url=[::]:8551
execution_1  | [DBUG] [03-25|11:58:36.425] Error in DNS random node sync            tree=all.goerli.ethdisco.net err="lookup all.goerli.ethdisco.net on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled"
execution_1  | [WARN] [03-25|11:58:42.768] Already shutting down, interrupt more to panic. times=9
```

And this is where it remains until forcibly killed

**Comment by yorickdowne** [comment]
Uploaded trace logs to here: https://www.dropbox.com/s/qim77hurooysz6b/erigonstall.trace.log.tar.gz?dl=0

Issue occurs around 16:15

**Comment by michaelsproul** [comment]
Given that Erigon was OK with LH v3.5.1 I suspect this is related to the `getPayloadBodiesByRange` engine API call which we recently added support for in Lighthouse.

**Comment by yorickdowne** [comment]
We have a user report that this is not fixed with Erigon `v2.41.0`. Still running my own test.

**Comment by yorickdowne** [comment]
We have a user report that this is not fixed with Erigon `v2.41.0`. Still running my own test.

**Comment by yorickdowne** [comment]
We have a user report that this is not fixed with Erigon `v2.41.0`. Still running my own test.

**Comment by mwpastore** [comment]
> We have a user report that this is not fixed with Erigon `v2.41.0`. My own test confirms that.

Can confirm.

**Comment by jt9897253** [comment]
Same issue here, also with erigon 2.41.0 and lighthouse 4.0.1. The [patch](https://github.com/ledgerwatch/erigon/issues/7172#issuecomment-1485642441) from @mwpastore appears to improve the situation.

**Comment by banteg** [comment]
observing the same issue, trying out the patch

**Comment by emilianobonassi** [comment]
same here

**Comment by yorickdowne** [comment]
Or a similar issue. Prysm doesn't use getPayloadBodiesByRangeV1 according to Nishant. The symptoms seen are similar: context canceled and Erigon no longer responds on RPC/Engine.

Either this is the same issue as Lighthouse and it's got nothing to do with ByRange, or it's a separate issue.

**Comment by cleot** [comment]
Served                                   conn=127.0.0.1:53420 method=engine_getPayloadBodiesByRangeV1 reqid=1 t=10.001134724s err="context canceled"

Erigon v2.41.0
Lighthouse v4.0.1

**Comment by McSim85** [comment]
Seems like related to 
https://github.com/ledgerwatch/erigon/issues/7198

**Comment by mwpastore** [comment]
Still up and running with the above patch after about 20 hours.

**Comment by yorickdowne** [comment]
We're being asked to test #7199

**Comment by ethDreamer** [comment]
@mwpastore were you able to test this?

**Comment by mwpastore** [comment]
@ethDreamer It's running now but it's only been about an hour.

**Comment by geomad** [comment]
Someone said he tested #7199 before it got merged and he was still having issues. testing it now myself as well.

**Comment by ethDreamer** [comment]
thanks - keep us updated :)

**Comment by yorickdowne** [comment]
Time to restart these tests on v2.42

**Comment by yorickdowne** [comment]
2.42 stayed stable overnight for 12 hours on 9 servers. As far as I can tell, this is fixed.
