### ISSUE TITLE
When i run an erigon node for Goerli, JSONRPC requests to 8545 fail

### ISSUE THREAD

**Issue by ethereumdegen** [ledgerwatch/erigon#7178]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).

When i run an erigon node for Goerli, JSONRPC requests to 8545 fail. But when i run an erigon node with the exact same config for mainnet, JSONRPC requests to 8545 succeed.  This is not explained in the documentation as far as i can tell.  

In fact if I run my server in goerli at all and then try to switch back to mainnet, JSONRPC requests also dont work. The only thing that works is a fresh reinstall and config to mainnet.

**Comment by yorickdowne** [comment]
That’s not a bug, it’s a config issue. I run it on Goerli, works fine. You can check the way eth-docker runs the thing for reference, even if you don’t use eth-docker to run it.
