### ISSUE TITLE
Implement download limiter for phases other than snapshot

### ISSUE THREAD

**Issue by codeshocks** [ledgerwatch/erigon#7182]
> This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).

Discord link is expired!

***

Is there any download limiter for phases other than snapshot?

Stage n.5/16 (Bodies) is maxing out my 20MB/s bandwidth to the point where it's impossible to `wget` or `apt update` and it's still going to take ~5 days at this rate.

[trickle](https://linux.die.net/man/1/trickle) doesn't seem to work.

**Comment by AskAlexSharov** [comment]
About discord: https://github.com/ledgerwatch/erigon#erigon-discord-server

**Comment by AskAlexSharov** [comment]
we don't have such limiter. reduce of --bodies.cache may a bit help.
trickle - you need limit UDP (not TCP) and maybe limit more outbund traffic - to reduce amount of Erigon's requests for new bodies. 
use --snapshots=true
