### ISSUE TITLE
Erigon won't sync sepolia network

### ISSUE THREAD

**Issue by matthewdarwin** [ledgerwatch/erigon#7191]
#### System information

erigon version 2.41.0-stable-52d5f37b

Linux

Erigon Command (with flags/config):

/usr/bin/erigon --chain sepolia --datadir /var/lib/erigon --torrent.download.rate 1024mb --metrics --metrics.addr 0.0.0.0 --metrics.port 6061 --http.addr 0.0.0.0 --http.port 8545 --http.vhosts * --http.api eth,debug,net,trace --db.pagesize 16kb --batchSize 2048MB --rpc.returndata.limit 1000000 --maxpeers 50

Chain/Network: 

Sepolia

#### Expected behaviour

Erigon will sync sepolia network

#### Actual behaviour

Error message:

https://sepolia.checkpoint-sync.ethdevops.io/eth/v2/debug/beacon/states/finalized": dial tcp: lookup sepolia.checkpoint-sync.ethdevops.io on 1.1.1.1:53: no such host

#### Steps to reproduce the behaviour

Just start erigon

**Comment by iFA88** [comment]
Hey there! Any suggestion for this? Maybe change the hardcoded url to another?

**Comment by AskAlexSharov** [comment]
ok. fixed url by https://github.com/ledgerwatch/erigon/commit/cd2c5fe0fd67be16fcd1cf6adfb8f2f0f0fe6e04
but real problem is: Erigon didn't fallback to 2-nd url - even that we have it

**Comment by iFA88** [comment]
`Get "https://checkpoint-sync.sepolia.ethdevops.io/eth/v2/debug/beacon/states/finalized": dial tcp: lookup checkpoint-sync.sepolia.ethdevops.io on 88.151.96.15:53: no such host` :(
