### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by mcdee** [ledgerwatch/erigon#7210]
#### System information

Erigon version: `erigon version 2.42.0-stable`

OS & Version: Ubuntu 22.04

Chain/Network: 

mainnet

#### Expected behaviour

Starting erigon downloaded from the releases page from fresh (no existing data) with a simple `./erigon` results in a crash.

(This also happens with our systems that have existing data, however this is the simplest reproducible case.)

#### Actual behaviour

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x233b0 pc=0x233b0]
```

#### Steps to reproduce the behaviour

- wget https://github.com/ledgerwatch/erigon/releases/download/v2.42.0/erigon_2.42.0_linux_amd64.tar.gz
- tar zxf erigon_24.2.0_linux_amd64.tar.gz
- ./erigon

#### Backtrace

Full log attached.
[log.txt](https://github.com/ledgerwatch/erigon/files/11098791/log.txt)

**Comment by Nickforall** [comment]
Having the same issue here, crash after `Sentinel started`

**Comment by AskAlexSharov** [comment]
@mcdee @McSim85 @Nickforall : 
let's try reduce scope of problem. 
after erigon crush on new datadir, run on same datadir next command:
`go run ./cmd/downloader --datadir=<your_datadir>`
and tell me if it also crush or not
(can't reproduce).

**Comment by mcdee** [comment]
This is using the binary downloaded from github, as per the **Steps to reproduce the behaviour** in the bug report, so no additional binaries are present.  If I compile from source at the `v2.42.0` tag then running `./erigon` seems to be working.

**Comment by AskAlexSharov** [comment]
@mcdee 
how do you compile from source? by our `make` or not?`

also show: 
`uname -a`
`go version`
`cc -v`

**Comment by mcdee** [comment]
Yes, I just run `make` to compile it.  Again, to be clear:
- when running from source it works
- when running from the released download at https://github.com/ledgerwatch/erigon/releases/download/v2.42.0/erigon_2.42.0_linux_amd64.tar.gz it crashes

```sh
uname -a
Linux dev 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```sh
go version
go version go1.20.2 linux/amd64
```

```sh
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
```

**Comment by Nickforall** [comment]
Yeah same here, our verion built from source runs smoothly. This problem only occurs with distributed [erigon_2.42.0_linux_amd64.tar.gz](https://github.com/ledgerwatch/erigon/releases/download/v2.42.0/erigon_2.42.0_linux_amd64.tar.gz) binary. (also tried 2.39, 2.41, same issues).

For what it's worth:

```
Linux ip-(...).ec2.internal 6.1.19-30.43.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 15 14:44:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

go version go1.19.6 linux/amd64

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-amazon-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-amazon-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/amazonlinux/amazon-linux-2022 --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.3.1-20221121/obj-x86_64-amazon-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_64=x86-64-v2 --with-arch_32=x86-64 --build=x86_64-amazon-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.1 20221121 (Red Hat 11.3.1-4) (GCC)
```

**Comment by AskAlexSharov** [comment]
seems i fixed it by https://github.com/ledgerwatch/erigon/pull/7229

**Comment by begetan** [comment]
Why need to keep broken release 2.42.0-stable but not a fixed version like 2.42.1?

**Comment by muratso** [comment]
I've just started getting this same error again with amd64 and arm64 binaries of 2.48.1. This happens only when I restart my long-running node for whatever reason, and sometimes after trying a few times, it comes up.
I haven't tried building from source yet. I wonder if this might be somehow related to the OS. I noticed some other people on this issue were using amazonlinux (so am I). @AskAlexSharov should I open a new issue or should we re-open this one?

**Comment by shakhzodkudratov** [comment]
Confirm that the `2.48.1` binary from releases for amd64 is crashing, however, it is running stable when I compile it from develop branch
[erigon-crash-logs.txt](https://github.com/ledgerwatch/erigon/files/12375477/erigon-crash-logs.txt)
