### ISSUE TITLE
evm binary is exceedingly slow

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ledgerwatch/erigon#7215]
I started doing some fuzzing again and noticed that the throughput was abysmal.
`INFO [03-29|21:33:13.762] Processing tests                         count=10 remaining=4,626,790 elapsed=29.414069944s`
I'm fuzzing geth, nethermind, besu, erigon. After removing the throughput shot up a lot 
`INFO [03-29|21:46:56.737] Processing tests                         count=327 remaining=4,626,473 elapsed=16.028118734s` 
I suspect erigon is doing a lot of work in `init()` functions. 
I've removed erigon from the fuzzing for now, will add it back once the evm throughput is roughly in line with the other clients

**Comment by AskAlexSharov** [comment]
@MariusVanDerWijden hi.
1. Today some optimization in https://github.com/ledgerwatch/erigon/pull/7219
2. My guess: our db doesn't have in-memory mode, I think main bottleneck is create/remove new db. But hard to say without knowing which command do your run. Show example command plz? (can eliminate this overhead by creating db on tmpfs).

**Comment by MariusVanDerWijden** [comment]
@AskAlexSharov sorry for taking so long to respond
```
 cat FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce.json
{"FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce":{"env":{"currentCoinbase":"b94f5374fce5edbc8e2a8697c15331677e6ebf0b","currentDifficulty":"0x20000","currentRandom":"0x0000000000000000000000000000000000000000000000000000000000020000","currentGasLimit":"0x26e1f476fe1e22","currentNumber":"0x1","currentTimestamp":"0x3e8","previousHash":"0x044852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d","currentBaseFee":"0x10"},"pre":{"0x000000000000000000000000000000ca1100f022":{"code":"0x67706f6f73616c5f6173617f6c65725f616c6c3f35676f676f70726f746f2e737461626c655f6d61727368616061527f7d716c65725f616c6c3f35676f676f70726f746f2e737461626c655f6d6172736081527f68617d716c65725f616c6c3f35676f676f70726f746f2e737461626c655f6d6160a152607260c153607360c2536068","storage":{},"balance":"0x0","nonce":"0x0"},"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b":{"code":"0x","storage":{},"balance":"0x3fffffffffffffff","nonce":"0x0"}},"transaction":{"gasPrice":"0x80","nonce":"0x0","to":"0x000000000000000000000000000000ca1100f022","data":["0x727368617d716c65725f616c6c3f35676f676f70726f746f2e737461626c655f6d61727368617d716c65725f616c6c3f35676f676f70726f746f2e737461626c655f6d61727368617d716c65725f616c6c3f35676f676f70726f746f2e737461626c655f"],"gasLimit":["0x1312d00"],"value":["0x655f6d61"],"secretKey":"0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8"},"out":"0x","post":{"Shanghai":[{"hash":"0x67537d10ffe3bcffee4fe655d1893128562405566a9958cb92934af5977d07f0","logs":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","indexes":{"data":0,"gas":0,"value":0}}]}}}

devops@smc-boulder-02 ➜  out git:(master) ✗ time ~/marius/clients/erigon/cmd/evm/evm statetest FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce.json
[
  {
    "name": "FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce",
    "pass": true,
    "stateRoot": "0x67537d10ffe3bcffee4fe655d1893128562405566a9958cb92934af5977d07f0",
    "fork": "Shanghai"
  }
]
~/marius/clients/erigon/cmd/evm/evm statetest   3.05s user 0.10s system 101% cpu 3.112 total
devops@smc-boulder-02 ➜  out git:(master) ✗ time ~/marius/clients/go-ethereum/cmd/evm/evm statetest FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce.json
[
  {
    "name": "FuzzyVM-1a984b47a0e74d78098e59d34ffa4346d67675b7fe6c78d91a2cabbdd55100ce",
    "pass": true,
    "stateRoot": "0x67537d10ffe3bcffee4fe655d1893128562405566a9958cb92934af5977d07f0",
    "fork": "Shanghai"
  }
]
~/marius/clients/go-ethereum/cmd/evm/evm statetest   0.03s user 0.01s system 122% cpu 0.035 total
```

This is with the old version will update to your optimization and report back

**Comment by AskAlexSharov** [comment]
@MariusVanDerWijden so, there is 2 bottlenecks:
1. it create too big initial db size (defaults are too big). just fixed. 
2. every time you run it - it creating new db and delete in the end. We can switch to using `shared` db (we will not commit any data to this db and will not delete it. It will reduce disk touches, reduce some parallelism. let's test it).
```
// - faster sequential tests: don't need create/delete db
// - less parallelism: multiple processes can open same DB but only 1 can create rw-transaction (other will wait when 1-st finish)
```
Done in `devel`, see: https://github.com/ledgerwatch/erigon/blob/2515b9c069b63a2141dc6348bf22edd2e0c2b917/cmd/evm/staterunner.go#LL121C15-L121C21

**Comment by MariusVanDerWijden** [comment]
Hmm looks the same with the newest branch to me

**Comment by AskAlexSharov** [comment]
@MariusVanDerWijden what is the problem now? time of run 1 particular test is slow or parallel throughput (how much of concurrency?) ?
what is the speed differenece? internal time measurement shows: 7ms vs 2ms on geth (is it bad?)

**Comment by MariusVanDerWijden** [comment]
Ah I didn't check the parallel throughput, only checked running a single test. I'm going to try some more today
