### ISSUE TITLE
Is it possible to prune down an archive node?

### ISSUE THREAD

**Issue by codeshocks** [ledgerwatch/erigon#7236]
Polygon offers an [archive node snapshot].
On a machine with low specs but fast connection, a faster sync strategy than syncing from scratch would be to download this "snapshot" of an archive node and prune it down.

The `integration` tooling allows to change the prune flags with an "if you know what you are doing" warning.

So allow me to ask: in this case alone -- that is, before the first startup of a "snapshot" of an archive node -- is it safe to run `./build/bin/integration force_set_prune --datadir <> --prune.h.older=250000 --prune.r.older=250000  --prune.t.older=250000  --prune.c.older=250000"`? 
Will it convert the archive node to a pruned node and resize the chaindata folder down from the 5TB is it now to the ~1.5TB a full node should be?

[archive node snapshot]: https://wiki.polygon.technology/docs/operate/snapshot-instructions-heimdall-bor/

**Comment by sundafa** [comment]
erigon
Changes to the prune mode are not allowed after the first boot, so downloading archive snapshots can only be run in archive mode

**Comment by codeshocks** [comment]
Any advice into where I can start looking in order to write a PR that would support this?

**Comment by AskAlexSharov** [comment]
@codeshocks oh, pretty everywhere :-)
- from the fact: that our db (MDBX) can't reduce in size even that you deleted data (it can, but probability is low - depends on fragmentation). To reduce db size will need additional step (with additional disk space): "mdbx_dump/mdbx_load" or "integration mdbx_to_mdbx" which will copy data to new db.
- to the fact: that such feature will add tons of new corner-cases and scenarios which will increase maintenance cost: every Bug-report I will need to clarify - how people did sync first, and what they changed later, and when they changed, and what version of Erigon they used when changed mode, etc... 
- and need protect users from "added --prune flag by human-mistake and lost all data" case
