### ISSUE TITLE
Polygon - nullnull response tracing tx

### ISSUE THREAD

**Issue by qk-santi** [ledgerwatch/erigon#7248]
Erigon version: v0.0.6 https://github.com/maticnetwork/erigon/releases/tag/v0.0.6
Commit hash: [d9c5a01](https://github.com/ledgerwatch/erigon/commit/d9c5a01103912a64b31c01afac05ab62dfa5c65d)
Chain/Network: Polygon/Matic

When tracing on Polygon, Erigon returns an error while bor returns successfully.

Erigon fork for Polygon returns a `nullnull` response on certain blocks.
It doesn't matter the tracer used, default or callTracer returns with same error.
It also says missing block number when it's a transaction what we are passing.

#### Erigon response
```
curl http://xxxx:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xfde3ac0d79c9bd1b211a1018fa28dd58dc4809718da29d5ba8214aff13f6a77f",{"tracer":"callTracer","timeout":"1200s"}],"id":2368715}'

{"jsonrpc":"2.0","id":2368715,"result":nullnull,"error":{"code":-32000,"message":"missing block number"}}
```

#### Bor response
```
curl http://xxxx:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xfde3ac0d79c9bd1b211a1018fa28dd58dc4809718da29d5ba8214aff13f6a77f",{"tracer":"callTracer","timeout":"1200s"}],"id":2368715}' | jq

{
  "jsonrpc": "2.0",
  "id": 2368715,
  "result": {
    "gas": 0,
    "failed": false,
    "returnValue": "",
    "structLogs": []
  }
}
```

**Comment by 0xKrishna** [comment]
I have asked to share a link with `--snapshots=false`, Maybe you can try to recover a node using that and run the same query on that to confirm the same.

**Comment by qk-santi** [comment]
@0xKrishna thanks for the insights!

Independently of the reason, wouldn't Erigon need to answer in a JSON compatible way?
`nullnull` is breaking compatibility with JSON parsers 😬

**Comment by 0xKrishna** [comment]
Yes, That is something I will surely look into.

**Comment by rx294** [comment]
> Yes, That is something I will surely look into.

Thank you @0xKrishna.. please see if this can be expedited.  It would be really helpful.

**Comment by 0xKrishna** [comment]
Hi @qk-santi , Sorry for the delay, You know last few days were holidays.

Regarding the issue, I am trying to reproduce this on my nodes but getting
```
{"jsonrpc":"2.0","id":2368715,"result":null}
```

You are getting this on all of your nodes or any specific ?

**Comment by qk-santi** [comment]
Hi @0xKrishna!

Based on your comment we thought it would be just a matter of cloning a good Erigon instance and "call it done", but we have seen all nodes at some point answer `nullnull` but it is for different transactions.
Not all nodes answer incorrectly at the same time, it varies per transaction, but it is always the same set of nodes answering incorrectly for the same transaction.

Listing below a few ones for you to test:
```
0xdc970bb0c869079b9f263b660042eecb84cf3a72238700674cdf340a31971957
0xfa0fb3daa158eb3b89aafbbdfe05fb70cf59d9f8d4402470278fc1d6dc3ef3b1
0x8299a5ad78dc1ab879b7a2326f3f13d0d98150fb576a28b93a94bc571199245b
0xaa17015e7784a3f1e4b0377eb61d4be21968fb6ec43933966e3f14736788bd8a
0x2a2265d143620f06566e6f6f2677bd70c87311fbe342346e3f9f880b066daa19
0xfa0fb3daa158eb3b89aafbbdfe05fb70cf59d9f8d4402470278fc1d6dc3ef3b1
0x59d3453cb0e714353b984b3fcecb08d70645dac7e5175dd0c8b17f880a8825a0
0x26102b097407e9683556d9f826cbe471de24f0fe54b353f3f7bd56524a00895d
```

**Comment by 0xKrishna** [comment]
Okay, Thanks
I will check all these txns on all of my nodes.

**Comment by qk-santi** [comment]
@0xKrishna did you happen to find any `nullnull` response with any of the txs above?

**Comment by 0xKrishna** [comment]
@qk-santi Yes, Thanks for the txns, I am able to reproduce the `nullnull` response, Sorry I wasn't able to work on it lately but will take this on priority now.

**Comment by 0xKrishna** [comment]
Is this response fine in case of missing block ?
```
{"jsonrpc":"2.0","id":2368715,"result":null,"error":{"code":-32000,"message":"missing block number"}}
```

**Comment by qk-santi** [comment]
@0xKrishna looks good!
Having valid JSON is enough 😄 

Will wait for it to get into the next release!

**Comment by yperbasis** [comment]
Fixed by #7334

**Comment by qk-santi** [comment]
@0xKrishna @yperbasis 

Just realised the response is not JSON-RPC 2.0 compliant

It should skip the `result` field if the `error` one exists:

```
{"jsonrpc":"2.0","id":2368715,"error":{"code":-32000,"message":"missing block number"}}
```

**Comment by jleeqn** [comment]
This issue can be reproduced on the `debug_traceCall` method. 

Example payload below:

**Request**

`
curl http://xxxx:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{
    "method": "debug_traceCall",
    "params": [
        {
            "from": "0x11ee8d2faf33ca7435dc2a9c796694109a8d8d3b",
            "to": "0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b",
            "value": "0x0",
            "data": "0x3593564c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000064716cd7000000000000000000000000000000000000000000000000000000000000000108000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000037888ace5f7898500000000000000000000000000000000000000000000040813e9f38898b1a26200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000001936c91190e901b7dd55229a574ae22b58ff498a"
        }, "latest", {
            "tracer": "callTracer",
            "debug": true,
            "enableMemory": true,
            "enableReturnData": true,
            "blockoverrides": {
                "number": "latest"
            }
        }
    ],"id":1,"jsonrpc":"2.0"
}'
`

**Response**

`
{"jsonrpc":"2.0","id":1,"result":nullnull,"error":{"code":-32000,"message":"tracing failed: fee cap less than block base fee: address 0x11Ee8D2fAf33cA7435DC2a9C796694109a8d8D3b, gasFeeCap: 0 baseFee: 133042005047"}}
`

**Comment by qk-santi** [comment]
keeping this open

**Comment by 0xKrishna** [comment]
So no result when there is an error ? That's remaining, Right ?

**Comment by qk-santi** [comment]
Yes, that's it, result field and error field can't both exist in JSON-RPC 2.0 ;)

**Comment by qk-santi** [comment]
Thanks @AskAlexSharov! understood then 🙏
