### ISSUE TITLE
node can't continue sync

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#7254]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://github.com/ledgerwatch/erigon#erigon-discord-server).
erigon version:erigon version 2.42.0-stable-d8d04663
start param erigon --private.api.addr=0.0.0.0:9091 --http.addr=0.0.0.0 --http.port=80 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,engine,web3,net,debug,trace,txpool --datadir=/mnt/**/ --chain=mainnet --prune=htcr --prune.r.older=10000 --prune.h.older=10000 --prune.t.older=10000 --prune.c.older=10000
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/84554944/229698314-31954c76-7fdc-458f-b8d7-372fcc3dabf7.png">

New blocks are synchronized when the program is started, but not automatically after a period of time, need restart the node that will continue syncing

**Comment by AskAlexSharov** [comment]
I think we fixed it in `devel` branch

**Comment by TangMonk** [comment]
use prysm
