### ISSUE TITLE
Rpc calls making syncing slow

### ISSUE THREAD

**Issue by DaraDoyoung** [ledgerwatch/erigon#7257]
Hi, my ethereum mainnet erigon archive node is used for some service and it's getting quite a lot of rpc calls, and this is making my node to stop syncing. However cpu, memory status seems to be fine. 
I'm currently using m6i.2xlarge instance on AWS(8vCPUs, 32G memory).
Any suggestions on this problem?

![image](https://user-images.githubusercontent.com/95335707/229771846-fe049a50-7982-4188-a893-3af5c83fc6b8.png)
![image](https://user-images.githubusercontent.com/95335707/229771890-5858c2a1-3b65-4224-a566-6f7bf2c9fe7b.png)

**Comment by AskAlexSharov** [comment]
what if you increase `--db.read.concurrency`?
