### ISSUE TITLE
Will BSC's v1.1.21 hardfork upgrade support it?

### ISSUE THREAD

**Issue by harveyff** [ledgerwatch/erigon#7270]
Hi teams,

Thanks again for your great work.

I read that blog, and I know something about bsc and matic. It was said that they will no longer be supported from April 1st. Is this a confirmed thing?

That is, the hardfork upgrade of BSC on April 12 will definitely not be supported, right? If so, I will replace the bsc with another client.

best wishes.

**Comment by harveyff** [comment]
This has almost certainly happened, I see that the bsc test chain has been removed from the latest devel.

**Comment by calmbeing** [comment]
@harveyff  Please checkout this repo ` https://github.com/node-real/bsc-erigon/releases/tag/v1.0.2`, nodereal will continue to support bsc with erigon

**Comment by du5** [comment]
#7246
