### ISSUE TITLE
I am experiencing the same problem and none of the above solutions work for me -

### ISSUE THREAD

**Issue by shep-analytics** [ledgerwatch/erigon#7274]
I am experiencing the same problem and none of the above solutions work for me -

I freshly installed ubuntu 22 server, installed go with
`sudo snap install go --classic`

then
```
git clone --branch stable --single-branch https://github.com/ledgerwatch/erigon.git
cd erigon
make erigon
./build/bin/erigon
```

trying `go build -v ./cmd/erigon` results in

github.com/ledgerwatch/erigon-lib/sais
github.com/ledgerwatch/erigon-lib/sais: build constraints exclude all Go files in /home/teancum/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230405025700-b2bfe9a2ca46/sais
github.com/torquem-ch/mdbx-go/mdbx
github.com/torquem-ch/mdbx-go/mdbx: build constraints exclude all Go files in /home/teancum/go/pkg/mod/github.com/torquem-ch/mdbx-go@v0.27.10/mdbx
github.com/supranational/blst/bindings/go
\# github.com/supranational/blst/bindings/go
/home/teancum/go/pkg/mod/github.com/supranational/blst@v0.3.10/bindings/go/rb_tree.go:130:18: undefined: Message
github.com/ledgerwatch/erigon-lib/types
github.com/anacrolix/go-libutp
\# github.com/anacrolix/go-libutp
/home/teancum/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:9:2: undefined: mu
/home/teancum/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:10:8: undefined: mu
/home/teancum/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:11:20: undefined: libContextToSocket
\# github.com/ledgerwatch/erigon-lib/types
/home/teancum/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230405025700-b2bfe9a2ca46/types/txn.go:450:24: undefined: secp256k1.RecoverPubkeyWithContext
/home/teancum/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230405025700-b2bfe9a2ca46/types/txn.go:450:59: undefined: secp256k1.DefaultContext

_Originally posted by @shep-analytics in https://github.com/ledgerwatch/erigon/issues/5210#issuecomment-1499798449_

**Comment by shep-analytics** [comment]
Solved --

install go using apt instead of snap

**Comment by monossido** [comment]
Fixed for me by installing
```
sudo apt-get install gcc
sudo apt-get install build-essential
```
