### ISSUE TITLE
mdbx defragmented?

### ISSUE THREAD

**Issue by keithchew** [ledgerwatch/erigon#7283]
I have just setup a new Erigon node, which has sycned up to head. Comparing the MDBX file with an older Erigon (6 months), the difference is quite significant: 1.7TB for new Erigon, 2.2T for older Erigon.

Both are running on latest v2.42.0. Perhaps the mdbx.dat file for older Erigon has defragmented over time? Is there a command I can run to trim/vacuum/defragment the size of of the mdbx file?

**Comment by AskAlexSharov** [comment]
can do by: 
1. need create db first by running erigon in new datadir with flags you need
2. Migrate all data of chaindb by “integration mdbx_to_mdbx”
