### ISSUE TITLE
checkpoint sync always 0

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#7296]
#### System information

Erigon version: `./erigon --version`
v2.40.0
OS & Version: Windows/Linux/OSX
ubuntu 
Commit hash: 

Erigon Command (with flags/config):
38fb38a92edccb9ea1505686ed5e361208bf81f1
Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 
goerli
 /erigon --ws=true --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.api=eth,erigon,engine,web3,net,debug,trace,txpool --datadir=/***t --chain=goerli
#### Expected behaviour
successfully syning

#### Actual behaviour
![image](https://user-images.githubusercontent.com/84554944/231403394-5d0ca08f-b915-47a1-bec4-2f6222d06f8a.png)

#### Backtrace

````
[backtrace]
````

**Comment by melynx** [comment]
I'm having the same issue too.
Running v2.43.0 from git devel branch.

**Comment by tunlong** [comment]
I have the same issue too...

**Comment by nalepae** [comment]
Same issue too.
