### ISSUE TITLE
BSC -- "Added future link"

### ISSUE THREAD

**Issue by zformular** [ledgerwatch/erigon#7301]
INFO[04-13|02:34:24.451] [1/16 Snapshots] Fetching torrent files metadata
INFO[04-13|02:34:24.455] [Snapshots] Blocks Stat                  blocks=27191k indices=27191k alloc=3.1GB sys=3.3GB
INFO[04-13|02:34:24.455] [2/16 Headers] Waiting for headers...    from=27281610
WARN[04-13|02:34:29.872] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:29.990] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.082] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.083] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.087] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.288] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.614] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.669] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.859] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:30.934] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.008] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.390] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.701] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.714] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.943] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.943] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:31.956] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:32.118] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:32.478] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:32.693] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:32.739] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471
WARN[04-13|02:34:32.742] [Downloader] Added future link           hash=0x58ffbd83340d5381ce7c3444489f26d7e45ff37b2572d7ba0df533d8fd16c1ac height=27281611 timestamp=1681297471

**Comment by du5** [comment]
#7246

**Comment by arthurgervais** [comment]
😭 how much?

**Comment by calmbeing** [comment]
@zformular supported here: https://github.com/node-real/bsc-erigon/commit/c8167d4f040fdfbafe70627360b9065416ad5745
