### ISSUE TITLE
Eth mainnet sync problem with "withdrawals before shanghai"  error.

### ISSUE THREAD

**Issue by madenmud** [ledgerwatch/erigon#7311]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://github.com/ledgerwatch/erigon#erigon-discord-server).

Hi, I'm facing following error message with 2.42 version with lighthouse and teku CL clients.

erigon_1      | [WARN] [04-14|07:20:29.551] Served                                   conn=172.31.0.9:46452 method=engine_newPayloadV2 reqid=1 t=1.594018ms err="withdrawals before shanghai"
light_node_1  | Apr 14 07:20:29.551 WARN Execution engine call failed            error: ServerMessage { code: -32602, message: "withdrawals before shanghai" }, service: exec
light_node_1  | Apr 14 07:20:29.551 WARN Error whilst processing payload status  error: Api { error: ServerMessage { code: -32602, message: "withdrawals before shanghai" } }, service: exec
light_node_1  | Apr 14 07:20:41.000 INFO Syncing                                 est_time: --, distance: 73 slots (14 mins), peers: 9, service: slot_notifier
downloader_1  | [INFO] [04-14|07:20:47.014] [snapshots] Seeding                      up=0B/s peers=2 conns=2 files=99

Any advice would be appreciated.

**Comment by Giulio2002** [comment]
update your client version, you are running outdated nodes
