### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#7320]
#### System information
Erigon version: v2.42.0
OS & Version: Ubuntu 20.04
Commit hash: 2.42.0-stable-beb97784
Erigon Command (with flags/config): `erigon -chain=mainnet --prune=disabled --authrpc.jwtsecret=/node/archive/eth/erigon/jwt.hex --db.read.concurrency 10000 --rpc.batch.concurrency 30000 --externalcl --rpc.gascap=600000000 --rpc.evmtimeout=30s --rpc.batch.limit=100 --rpc.returndata.limit=104857600 --http=true --http.api 'eth,net,web3,debug,trace,txpool'`
Concensus Layer: lighthouse
Concensus Layer Command (with flags/config): `lighthouse bn -d /node/archive/eth/lighthouse --network mainnet --execution-jwt '/node/archive/eth/erigon/jwt.hex' --checkpoint-sync-url=https://sync-mainnet.beaconcha.in`
Chain/Network: eth

#### Expected behaviour
Normal operation and stable memory

#### Actual behaviour
The memory usage suddenly increases until it is killed by the system

#### Steps to reproduce the behaviour
no real reason found.
You can try using rpc to continuously request
Below are some of the methods and quantities we request
![image](https://user-images.githubusercontent.com/24621599/232372879-b767bd96-4ac3-4dcf-80c4-14f39a059b7c.png)

#### Backtrace

````
[backtrace]
````
![image](https://user-images.githubusercontent.com/24621599/232372715-ff94a28f-f477-4627-960a-88e58db05ead.png)

**Comment by AskAlexSharov** [comment]
If you again will see the leak: 
add flag `--pprof`
```
go tool pprof -inuse_space -png http://127.0.0.1:6060/debug/pprof/heap > mem.png
```
show this file

**Comment by AskAlexSharov** [comment]
also maybe you have logs of erigon for this period of time

**Comment by sundafa** [comment]
Sorry, ETH nodes are prone to being killed by the host. Due to insufficient memory, the time to observe information after restarting is very short.
The following is the memory information of the BSC archive node. After 30 minutes of activation, the memory reaches over 60GB.
The startup method and request method are similar, perhaps providing some information.
And I noticed that the top display occupies 60% of the memory, but the memory displayed as used in the free command is not as large.

[profile.pb.gz](https://github.com/ledgerwatch/erigon/files/11280481/profile.pb.gz)
![mem-60](https://user-images.githubusercontent.com/24621599/233276275-3669c8d8-b7e4-4739-aa91-1dd3e85b8352.png)

**Comment by sundafa** [comment]
Information when the BSC archive node occupies 20G of memory.
![mem-17](https://user-images.githubusercontent.com/24621599/233277196-4608ff3b-ba3e-4462-a804-d60362c32c1d.png)

**Comment by sundafa** [comment]
These settings cannot control memory growth.
```
GOGC=50
GOMEMLIMIT=16000MiB
GOMAXPROCS=4
```

I do not deny that there are nodes that are functioning properly, but there are also nodes that are not functioning properly.
Most nodes operate normally, but sometimes memory usage suddenly increases continuously.

For the BSC node, the memory has increased and requests have not been closed. After restarting without requesting, the memory continues to increase to 60GB

**Comment by sundafa** [comment]
@keithchew Thank you for your suggestion and resolving some of the issues.
Through observation, some of the nodes that set the memory limit are effective, while some nodes may experience high memory levels and gradually decrease. However, it takes a long time, about 2 hours, to return to the 20% value above the limit and no longer decrease

**Comment by AskAlexSharov** [comment]
> Information when the BSC archive node occupies 20G of memory.
> ![mem-17](https://user-images.githubusercontent.com/24621599/233277196-4608ff3b-ba3e-4462-a804-d60362c32c1d.png)

This mem-profile shows that Erigon using 2GB, not 20GB. See also: https://github.com/ledgerwatch/erigon#htop-shows-incorrect-memory-usage
