### ISSUE TITLE
Not understand what says in the file db_walkthrough.MD

### ISSUE THREAD

**Issue by lurais** [ledgerwatch/erigon#7323]
hello , I am very curious about the improvement of the storage, but I can not understand what says in the file db_walkthrough.MD. Is there any more detail or simple description about that? Just like the file in [stagedsync](https://github.com/ledgerwatch/erigon/tree/devel/eth/stagedsync)?

**Comment by AskAlexSharov** [comment]
@lurais 
1. can see Alex's presentation of https://www.youtube.com/results?search_query=alexey+akhunov 
2. can see comments in `erigon-lib/kv/tables.go`
3. FYI: also have https://erigon.substack.com and https://t.me/monoblunt

**Comment by lurais** [comment]
@AskAlexSharov Thanks for your help. Could you tell me , how does it reduce the storage data into the disk? Or  which source file I can find the answer in this repo?

**Comment by AskAlexSharov** [comment]
Most important parts are: 
- `change sets`(way we store history of state) and `plain state` (way we store state)
- see also `DupSort` feature of lmdb/mdbx.

**Comment by lurais** [comment]
> * plain state

@AskAlexSharov Hello , I read the doc and not very clear , do you mean that you use these ways to reduce the storage:
1.Erigon uses a single Merkle trie for both accounts and the storage.It means to reuse some middle nodes?
2.use change sets to store the history of state to replace the mpt trie storage? 
3.without storing the key by using DupSort?

**Comment by AskAlexSharov** [comment]
FYI: can ask general questions in Discord - community can answer them as well

**Comment by lurais** [comment]
> FYI: can ask general questions in Discord - community can answer them as well

I sent a email to the address but not have joined your discord yet.
