### ISSUE TITLE
Confusing API response for blocks not passed all sync stages (eth_getLogs)

### ISSUE THREAD

**Issue by alexqrid** [ledgerwatch/erigon#7339]
#### Description
Staged sync is awesome, but API responses should not confuse the user.
Today I faced the following issue which seems like a bug:  

0. Node started to sync, downloaded headers and tried to run the next stages.  
1. At that moment my indexer were trying to parse info block by block and received the information about the transactions.  
2. **While trying to get logs for the parsed blocks (`eth_getLogs`) the api responded with empty array of the logs for ERC-20 `transfer` topic.**
3. After a while I queried again for the same blocks and saw non-empty array of logs from the `eth_getLogs` response.

I believe the problem happens before LogIndex stage.

#### System information
OS & Version: Linux

Erigon Command (with flags/config):
`--txpool.accountslots 1024 --trace.maxtraces 100500 --txpool.lifetime 6h0m0s --batchSize 1024M --private.api.ratelimit 100500 --db.pagesize=16kb --etl.bufferSize 1024MB --p2p.protocol=66  --maxpeers 50 --healthcheck --bor.heimdall="http://<my_heimdall_ip>" --chain bor-mainnet --torrent.download.rate=512mb --torrent.upload.rate=10mb --torrent.port 42014 --snapshots=false`

Chain/Network: Bor

#### Expected behaviour
`eth_getLogs` should respond with error for not fully processed blocks, i.e. for the blocks that didn't passed all erigon stages of the sync

#### Actual behaviour
`eth_getLogs` returns an empty array of logs

#### Steps to reproduce the behaviour
Try to query `rpcdaemon` for the block that didn't pass the `LogIndex` stage with the following payload:
```
{
"method": "eth_getLogs",
    "params":[
              {"blockhash": <hash>,
               "topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"],
              }],
    "id": 0,
}
```

**Comment by AskAlexSharov** [comment]
yes. nice to have.
FYI: after erigon startup 1st sync cycle every stage does commit separately (it allow us don't loose partial progress and do other optimizations). but then all stages commit together (in 1 rwtx).

**Comment by alexqrid** [comment]
> it allow us don't loose partial progress

Yes it's a great thing, thanks! But the mentioned edge cases is critical for the `Bor` chain, where the node can be synced, but then it lags for a few hundred blocks, then syncs again.

I have an alerts for my polygon node lag, alert is triggered when the head block number is not updated during 5 minutes, look at the behaviour:

```
UTC 03:48 AM
Erigon node is lagging
Erigon node POLYGON-MAIN on instance xxx seems lagging. Latest block is 41697759 
UTC 4:09 AM
Erigon node is lagging
Erigon node POLYGON-MAIN on instance xxx seems lagging. Latest block is 41698310 
UTC 4:54 AM
Erigon node is lagging
Erigon node POLYGON-MAIN on instance xxx seems lagging. Latest block is 41699498 
```

I believe for such kind of cases we need to have the mentioned expected behaviour.
I will try to figure out how this can be implemeneted.

**Comment by AskAlexSharov** [comment]
"node can be synced, but then it lags for a few hundred blocks, then syncs again." - only 1-st cycle after Erigon startup is in special mode. other cycles - regardless it's size - are commit at once.

**Comment by alexqrid** [comment]
> only 1-st cycle after Erigon startup is in special mode. other cycles - regardless it's size - are commit at once.

Thanks! Oh, this was crucial for my nodes, becaus with the `Bor` and `Parlia` something is wrong with `p2p` communication, as nodes sometimes fall behind and don't receive new blocks, only restart helps, and after the restarts my parsers process blocks and miss logs.
What do you think if I make a PR for a flag like `--atomic-sync` which will force the node to sync in a single transaction only and make it False by default?

**Comment by Har01d** [comment]
> What do you think if I make a PR for a flag like `--atomic-sync` which will force the node to sync in a single transaction only

This will be indeed valuable as right now one can't be sure whether the output from `eth_getLogs` is empty or the data hasn't been committed yet. If you use a node to constantly retrieve data this is crucial. For example, block explorers or DEX screeners rely on data from logs and right now they may miss some data if they use Erigon nodes. It's better to receive the data with a small delay rather than not to be sure about the data.

**Comment by AskAlexSharov** [comment]
@alexqrid i think it's leak of abstractions (who care about this low level implementation details). It just must not brake sync. 

@Har01d - best way to solve it: subscribe to "new headers" event - it triggered after commit. It means if you call `eth_getLogs` after receive "new headers" event - it for sure committed. ("new headers" - it's historical name of event from geth). 
FYI: there is also "new logs" event as I remember.
By websocket: https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub

**Comment by alexqrid** [comment]
> who care about this low level implementation details

Actually this is an important part of the erigon implementation,  unfortunately undocumented behaviour, that took time to realise why the logs missed and then appeared. Your comment helped a lot.

Unfortunately, solutions you mentioned are not the silver bullet and suits for the websocket cases, but not for ones using http queries.

**Comment by AskAlexSharov** [comment]
@alexqrid - there are anyway other reasons why logs may be missed and then appeared: erigon doesn't store non-canonical logs. it means if network does reorg several times between same forks: A, B, A, B, A - you will see logs, then not see, then see again.

**Comment by AskAlexSharov** [comment]
Erigon does store non-canonical blocks, and in theory can re-exec such blocks to generate logs, but Erigon doesn't store non-canonical state history - so, has no basis to re-exec non-canonical blocks.

**Comment by AskAlexSharov** [comment]
` but not for ones using http queries.` - geth has api for http-based subscriptions (pull-based).  Maybe Erigon also has.

**Comment by tsutsu** [comment]
In a standard blockchain ETL-agent design, you keep a cursor of blocks you've ingested, poll `eth_blockNumber`, and when `eth_blockNumber` increases past your cursor, you do various other RPC calls to collect info about the new block. Most blockchain ETL-agents have this design, in my experience. It is dumb, easy, debuggable, and robust to several failure-modes that event-subscription logic isn't. Can we please solve this problem for height-polling agents?

For example, by [allowing the agent to specify that it only wants to be made aware of blocks that have passed all stages](https://github.com/ledgerwatch/erigon/pull/7528).
