### ISSUE TITLE
Are there MATIC bor archival snapshots ? 

### ISSUE THREAD

**Issue by Sreeram1993** [ledgerwatch/erigon#7343]
Was trying to setup a Bor archival node for polygon, and was successful with it. But my nodes are like 2 years behind in terms of historical sync. is there any archival snapshots available for BOR (not erigon) so that the sync time can be reduced.

**Comment by AskAlexSharov** [comment]
Providing infrastructure of ready-to-use snapshots - is out of Erigon project scope. You may ask community (for example in our Discord) - probably they have.
