### ISSUE TITLE
Link to hosted documentation

### ISSUE THREAD

**Issue by jlosito** [ledgerwatch/erigon#7350]
I see that the erigon project hosts documentation on readthedocs, but usually projects provide a link to documentation within the About section of the repository. Otherwise, someone may not know it's being hosted there. Would it be possible to add the link to the documentation in the about section of this project?

https://erigon.readthedocs.io/en/latest/index.html

**Comment by AskAlexSharov** [comment]
I think it's unfinished and abandoned docs.
