### ISSUE TITLE
[BUG] metrics not work in 2.42.0 release

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7366]
#### System information

Erigon version: `2.42.0`

OS & Version: Linux

Concensus Layer: prysm

Chain/Network:  Mainnet

Erigon Command (with flags/config): /mnt1/erigon-2.42.0 --config /mnt1/erigon.toml

erigon.toml config file: 

```
datadir="/mnt1/archive"
port=30304

"authrpc.port"=8557
"authrpc.addr"="0.0.0.0"
"authrpc.vhosts"="*"
"authrpc.jwtsecret"="/home/david/ethereum/consensus2/jwt.hex"
externalcl=true

metrics=true
"metrics.addr"="0.0.0.0"

"torrent.port"=42071
"private.api.addr"="127.0.0.1:9091"
chain="mainnet"
http=true
ws=true
"http.addr"="0.0.0.0"
"http.api"=["eth","debug","net","trace","web3","erigon","admin", "txpool", "ots"]
"http.corsdomain"="*"
"http.port"=7546
```

```
$ curl http://localhost:6060/debug/metrics/prometheus
curl: (7) Failed to connect to localhost port 6060 after 0 ms: Connection refused
```

**Comment by AskAlexSharov** [comment]
1. are you on same host with erigon? no docker? 
2. show erigon startup logs

**Comment by TangMonk** [comment]
> 1. are you on same host with erigon? no docker?
> 2. show erigon startup logs

no docker, start log is fine, nothing different

**Comment by AskAlexSharov** [comment]
@TangMonk `start log is fine` - no. 
there is no line about metrics server start. example: 
```
INFO[04-24|10:22:36.575] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
```
so, erigon doesn't see your --metrics flag

**Comment by AskAlexSharov** [comment]
I guess it's fixed by: https://github.com/ledgerwatch/erigon/pull/7089

**Comment by TangMonk** [comment]
So is this a confirmed issue?
