### ISSUE TITLE
blocked with panic :runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by justforfunya** [ledgerwatch/erigon#7374]
#### System information

Erigon version: `./erigon --version`
v2.43.0
OS & Version: Windows/Linux/OSX
ubuntu 20.04
Commit hash: 
https://github.com/ledgerwatch/erigon/commit/1106475e345d936aa1220ace3e95d746ec361fa4
Erigon Command (with flags/config):
./erigon  --chain=bor-mainnet --datadir  matic_data_archive --http.addr 0.0.0.0  --http.port 8547 --http.vhosts=192.168.0.108   --ws --http.api=eth,debug,net,trace,web3,erigon --authrpc.port=8553   --torrent.port=62071   --private.api.addr=0.0.0.0:9092 --port=3330 --bor.heimdall=https://heimdall-api.polygon.technology/   --snapshots=true --p2p.protocol=66
Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 
polygon
#### Actual behaviour
die loop  while downloading headers,says "runtime error: index out of range [0] with length 0, trace: [stageloop.go:132 panic.go:890 panic.go:113 btree_generic.go:522 btree_generic.go:779 header_algos.go:392
tage_headers.go:822 stage_headers.go:144 default_stages.go:36 sync.go:358 sync.go:260 stageloop.go:166 stageloop.go:94 asm_amd64.s:1598]"

this is log:
EROR[04-24|08:58:55.108] Staged Sync                              err="runtime error: index out of range [0] with length 0, trace: [stageloop.go:132 panic.go:890 panic.go:113 btree_generic.go:522 btree_generic.go:779 header_algos.go:392
tage_headers.go:822 stage_headers.go:144 default_stages.go:36 sync.go:358 sync.go:260 stageloop.go:166 stageloop.go:94 asm_amd64.s:1598]"
INFO[04-24|08:59:05.099] [txpool] stat                            pending=4224 baseFee=18861 queued=30000 alloc=3.0GB sys=5.3GB
INFO[04-24|08:59:17.547] [2/15 Headers] Waiting for headers...    from=39881103
INFO[04-24|08:59:37.539] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|08:59:57.539] [2/15 Headers] Wrote block headers       number=39889401 blk/second=414.900 alloc=3.5GB sys=5.3GB
INFO[04-24|09:00:04.768] [p2p] GoodPeers                          eth66=7
INFO[04-24|09:00:05.109] [txpool] stat                            pending=4225 baseFee=18865 queued=30000 alloc=3.5GB sys=5.3GB
INFO[04-24|09:00:17.539] [2/15 Headers] No block headers to write in this log period block number=39889401
INFO[04-24|09:00:37.539] [2/15 Headers] Wrote block headers       number=39889787 blk/second=19.300 alloc=3.1GB sys=5.3GB
INFO[04-24|09:00:57.539] [2/15 Headers] Wrote block headers       number=39891716 blk/second=96.450 alloc=3.2GB sys=5.3GB
INFO[04-24|09:01:05.099] [txpool] stat                            pending=4256 baseFee=18866 queued=30000 alloc=3.2GB sys=5.3GB
INFO[04-24|09:01:17.539] [2/15 Headers] No block headers to write in this log period block number=39891716
INFO[04-24|09:01:37.539] [2/15 Headers] No block headers to write in this log period block number=39891716
EROR[04-24|09:01:42.662] Staged Sync                              err="runtime error: index out of range [0] with length 0, trace: [stageloop.go:132 panic.go:890 panic.go:113 btree_generic.go:522 btree_generic.go:779 header_algos.go:392
tage_headers.go:822 stage_headers.go:144 default_stages.go:36 sync.go:358 sync.go:260 stageloop.go:166 stageloop.go:94 asm_amd64.s:1598]"
INFO[04-24|09:01:43.362] [2/15 Headers] Waiting for headers...    from=39881103
INFO[04-24|09:02:03.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:02:04.769] [p2p] GoodPeers                          eth66=8
INFO[04-24|09:02:05.108] [txpool] stat                            pending=4256 baseFee=18866 queued=30000 alloc=3.4GB sys=5.3GB
INFO[04-24|09:02:23.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:02:43.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:03:03.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:03:12.172] [txpool] stat                            pending=4259 baseFee=18875 queued=30000 alloc=3.0GB sys=5.3GB
INFO[04-24|09:03:23.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:03:23.362] Req/resp stats                           req=156 reqMin=39899823 reqMax=41883941 skel=7 skelMin=39881102 skelMax=39918158 resp=94 respMin=39914685 respMax=41883941 dups=191
INFO[04-24|09:03:43.362] [2/15 Headers] Wrote block headers       number=39881294 blk/second=9.550 alloc=3.1GB sys=5.3GB
INFO[04-24|09:04:03.362] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:04:04.769] [p2p] GoodPeers                          eth66=6
INFO[04-24|09:04:05.112] [txpool] stat                            pending=4260 baseFee=18877 queued=30000 alloc=3.1GB sys=5.3GB
INFO[04-24|09:04:23.362] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:04:43.363] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:05:03.362] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:05:05.098] [txpool] stat                            pending=4260 baseFee=18877 queued=30000 alloc=3.0GB sys=5.3GB
INFO[04-24|09:05:23.362] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:05:43.363] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:06:03.362] [2/15 Headers] No block headers to write in this log period block number=39881294
INFO[04-24|09:06:04.768] [p2p] GoodPeers                          eth66=7
INFO[04-24|09:06:05.109] [txpool] stat                            pending=4260 baseFee=18877 queued=30000 alloc=3.1GB sys=5.3GB
INFO[04-24|09:06:23.362] [2/15 Headers] No block headers to write in this log period block number=39881294

#### Backtrace
     pending=4256 baseFee=18866 queued=30000 alloc=3.2GB sys=5.3GB
INFO[04-24|09:01:17.539] [2/15 Headers] No block headers to write in this log period block number=39891716
INFO[04-24|09:01:37.539] [2/15 Headers] No block headers to write in this log period block number=39891716
EROR[04-24|09:01:42.662] Staged Sync                              err="runtime error: index out of range [0] with length 0, trace: [stageloop.go:132 panic.go:890 panic.go:113 btree_generic.go:522 btree_generic.go:779 header_algos.go:392
tage_headers.go:822 stage_headers.go:144 default_stages.go:36 sync.go:358 sync.go:260 stageloop.go:166 stageloop.go:94 asm_amd64.s:1598]"
INFO[04-24|09:01:43.362] [2/15 Headers] Waiting for headers...    from=39881103
INFO[04-24|09:02:03.362] [2/15 Headers] No block headers to write in this log period block number=39881103
INFO[04-24|09:02:04.769] [p2p] GoodPeers                          eth66=8
INFO[04-24|09:02:05.108] [txpool] stat                            pending=4256 baseFee=18866 queued=30000 alloc=3.4GB sys=5.3GB
````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
@justforfunya looks like a race-condition. if you can help us by run erigon as `go run -race ./cmd/erigon <your_cli_flags>` and see if there is any `WARNING: DATA RACE` output - feel free. If not - it's ok - we will try to reproduce by self.
