### ISSUE TITLE
Polygon trace_* API thows error in block 16434166, txn: 0x9e66dce4a502d2f1cfb6eec48e29bb48c5cdebc0d567e4a40102a6f7ffe8ad45

### ISSUE THREAD

**Issue by zimbabao** [ledgerwatch/erigon#7379]
#### System information

Erigon version: erigon version 2.42.0-stable-d8d04663

OS & Version:Linux 5.4.228-131.415.amzn2.x86_64

Commit hash: https://github.com/ledgerwatch/erigon/commit/d8d04663483f639d2bdd016f588ac8d231e90396

Erigon Command (with flags/config): `erigon--datadir=/data/volumes/erigon-bor--private.api.addr=localhost:9090--chain=bor-mainnet--http=true--http.addr=0.0.0.0--http.port=8545--maxpeers=300--metrics--metrics.addr=0.0.0.0--metrics.port=6061--private.api.addr=localhost:9090--http.api=eth,erigon,web3,net,debug,trace,txpool,admin,engine--ws--ws.compression--rpc.gascap=300000000--http.addr=0.0.0.0--txpool.api.addr=0.0.0.0:9091--http.vhosts=*--pprof--pprof.addr=0.0.0.0--pprof.port=6059` 

Chain/Network: 

#### Expected behaviour
Return right trace

#### Actual behaviour
Returns nil trace and empty
```
    {
      "result": null
    },
    {
      "error": {
        "code": -32000,
        "message": "tracing failed: insufficient funds for gas * price + value: address 0x4923DE87853E95751A87eaFe957A88A564387dac have 80536310754448087 want 83776049439690320"
      }
    },
```

#### Steps to reproduce the behaviour
Make trace_block call with 16434166 or trace_transaction with txn 0x9e66dce4a502d2f1cfb6eec48e29bb48c5cdebc0d567e4a40102a6f7ffe8ad45

#### Backtrace

````
[backtrace]
````

**Comment by tangbinyeer** [comment]
erigon: 2.43.0

Error using debug_trace_block_by_hash
{'code': -32000, 'message': 'tracing failed: insufficient funds for gas * price + value: address 0x07A9f5E893cEEF86EB766623Df2e63e9ACFD9aFB have 2626313033574552 want 26426510 00000000'}
