### ISSUE TITLE
Integration panic on DB copy - MDBX_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by crypto7world** [ledgerwatch/erigon#7381]
#### System information

Erigon version: `./erigon --version`
erigon version 2.43.0-stable-1106475e

OS & Version: Windows/Linux/OSX
Linux - AmazonLinux2 - Kernel v5.10 - AARCH64

Integration Command (with flags/config):
`integration mdbx_to_mdbx --chaindata /mnt/data/erigon2/chaindata/ --chaindata.to /mnt/backup/erigon2/chaindata --datadir /dev/shm/erigon-backup`

Chain/Network: 
Goerli

#### Expected behaviour
This exact command used to perform a compacted backup of chaindata and was still working in December 2022.
I expected it to continue working.

#### Actual behaviour
Now I notice it does not work anymore on my development environment. It crashes right at the beginning. The error message report a random bucket at each try.
`panic: bucket: HashedStorage, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached`
or
`panic: bucket: IncarnationMap, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached`
or
`panic: bucket: PlainState, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached`
and so on.

An obvious change since December explaining the behavior could be the added flags on the opening of the dst DB:
BEFORE:
```
func mdbxToMdbx(ctx context.Context, logger log.Logger, from, to string) error {
	src := mdbx2.NewMDBX(logger).Path(from).Flags(func(flags uint) uint { return mdbx.Readonly | mdbx.Accede }).MustOpen()
	dst := mdbx2.NewMDBX(logger).Path(to).
		WriteMap().
		Flags(func(flags uint) uint { return flags | mdbx.NoMemInit }).
		MustOpen()
	return kv2kv(ctx, src, dst)
}
```
NOW:
```
func mdbxToMdbx(ctx context.Context, logger log.Logger, from, to string) error {
	src := mdbx2.NewMDBX(logger).Path(from).Flags(func(flags uint) uint { return mdbx.Readonly | mdbx.Accede }).MustOpen()
	dst := mdbx2.NewMDBX(logger).Path(to).
		WriteMap().
		Flags(func(flags uint) uint { return flags | mdbx.NoMemInit | mdbx.WriteMap | mdbx.Accede }).
		MustOpen()
	return kv2kv(ctx, src, dst)
}
```

Whether or not Erigon is running in parallel does not change anything (it used to work with Erigon running, which was very handy to perform hot backups).

Could be related to the fact that the database I'm trying to backup is already a restoration from a previous backup (made in December 2022) created with the same integration command.
Erigon seem to behave OK but is logging a warning on startup that may or may not be related:
```
INFO] [04-25|12:48:40.344] Opening Database                         label=chaindata path=/mnt/data/erigon2/chaindata
[INFO] [04-25|12:48:40.344] [db] params: growStep=2GB, mapsSize=7TB, shrinkThreshold=-1, pageSize=4KB, label=chaindata, WriteMap=false, Durable=false, NoReadahead=true,
mdbx_setup_dxb:15949 filesize mismatch (expect 535382781952b/130708687p, have 536870912000b/131072000p)
```

#### Backtrace
full output of the `integration` command:
````
[root@ip-10-142-194-63 ~]# integration mdbx_to_mdbx --chaindata /mnt/data/erigon2/chaindata/ --chaindata.to /mnt/backup/erigon2/chaindata --datadir /dev/shm/erigon-backup
INFO[04-25|12:56:01.707] logging to file system                   log dir=/dev/shm/erigon-backup/logs file prefix=erigon log level=info json=false
panic: bucket: HashedStorage, mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached

goroutine 1 [running]:
github.com/ledgerwatch/erigon/cmd/integration/commands.kv2kv({0x1897930, 0x4000793340?}, {0x18a4cc8, 0x40008c5040}, {0x18a4cc8, 0x40008c5110})
        github.com/ledgerwatch/erigon/cmd/integration/commands/refetence_db.go:489 +0xa00
github.com/ledgerwatch/erigon/cmd/integration/commands.mdbxToMdbx({0x1897930, 0x4000793340}, {0x18a3de0, 0x40004c5d20}, {0xffffdaad149f, 0x1c}, {0xffffdaad14cb, 0x1d})
        github.com/ledgerwatch/erigon/cmd/integration/commands/refetence_db.go:437 +0x20c
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func4(0x2203fc0?, {0x14af57d?, 0x6?, 0x6?})
        github.com/ledgerwatch/erigon/cmd/integration/commands/refetence_db.go:103 +0x8c
github.com/spf13/cobra.(*Command).execute(0x2203fc0, {0x40008a2120, 0x6, 0x6})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x2204580)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x128
````

**Comment by crypto7world** [comment]
I can confirm that rolling back the flags change is fixing the issue. My copy is now in progress.
As I'm not sure of what those flags are used for so I will not submit a patch (I'm not a Go dev, sorry) but if someone actually understanding what he is doing want to patch it, it is in:
`cmd/integration/commands/refetence_db.go`
line 435 (from commit 1106475e345d936aa1220ace3e95d746ec361fa4 / stable)

The change I made is simply:
CURRENT:
```
func mdbxToMdbx(ctx context.Context, logger log.Logger, from, to string) error {
	src := mdbx2.NewMDBX(logger).Path(from).Flags(func(flags uint) uint { return mdbx.Readonly | mdbx.Accede }).MustOpen()
	dst := mdbx2.NewMDBX(logger).Path(to).
		WriteMap().
		Flags(func(flags uint) uint { return flags | mdbx.NoMemInit | mdbx.WriteMap | mdbx.Accede }).
		MustOpen()
	return kv2kv(ctx, src, dst)
}
```
NEW:
```
func mdbxToMdbx(ctx context.Context, logger log.Logger, from, to string) error {
	src := mdbx2.NewMDBX(logger).Path(from).Flags(func(flags uint) uint { return mdbx.Readonly | mdbx.Accede }).MustOpen()
	dst := mdbx2.NewMDBX(logger).Path(to).
		WriteMap().
		Flags(func(flags uint) uint { return flags | mdbx.NoMemInit }).
		MustOpen()
	return kv2kv(ctx, src, dst)
}
```

Out of curiosity, I would not mind an explanation of WHY those flag are producing the behavior I observed.

**Comment by AskAlexSharov** [comment]
@crypto7world it's because `mdbx_to_mdbx` can't really create target db with all useful flags which Erigon has. So, you better create target db by starting erigon in new datadir for 10 sec with all cli flags you like. 

`mdbx_to_mdbx` opens target db with `mdbx.Accede` mode - which meanns it doesn't overwrite any db flags. And default db size limit is likely too small. (see --db.size.limit). 

Main problem here: 
- sometime users using mdbx_to_mdbx for backup, but another to change db pageSize. Means one users want "copy all db configuration" another "do not want copy db configuration". So, it's a bit unclear for me - which usecase must be default. Even if backup is default - need provide way to perform another use-case (support all that cli flags).

**Comment by AskAlexSharov** [comment]
@crypto7world give me some your feedback about `mdbx_to_mdbx` for backups. Now it using tons of threads to "read-ahead the data". Is it working well with "running erigon"? No impact on Erigon's performance?

**Comment by crypto7world** [comment]
@keithchew 
> hi @crypto7world just for my knowledge, how long does it take to do this backup copy? can you give me a rough idea and also which chain your are backing up.

It takes ages. The DB copy alone **for the Goerli testnet** takes ~8 hours. I'm not sure to remember how long it took on my last mainnet backup in December but I believe it was around 26 hours. I will update you on that in the coming days. More on my usecase/resources with my answers to Alex.

@AskAlexSharov 
> @crypto7world it's because mdbx_to_mdbx can't really create target db with all useful flags which Erigon has. So, you better create target db by starting erigon in new datadir for 10 sec with all cli flags you like.

I didn't think of that but I will try it, if it can make it work without me having to patch `integration` I'm all for it. Thanks for the tip!

> @crypto7world give me some your feedback about mdbx_to_mdbx for backups. Now it using tons of threads to "read-ahead the data". Is it working well with "running erigon"? No impact on Erigon's performance? What is your disk type?

My usecase is running a semi-custodian staking service on AWS. I'm using Erigon as an EL with Lighthouse as the CL. As I'm not big enough to have multiple nodes running at a profit, mainnet Lighthouse and Erigon are both running on a single EC2 instance **im4gn.xlarge (4 CPU, 16GB RAM, 1875GB directly attached SSD)**.

It is of course possible that I lose this single node and I must be able to come back online in a "reasonable amount of time" (roughly 24hours), which precludes syncing from scratch. Hence the backup usecase. Using `integration` **allows me to backup Erigon database while having Erigon running**, which is the most important feature for me because I'm staking and don't want to stop Erigon and loose hours of attestations at each backup.

The following numbers are taken from the Goerli testnet node, on which I'm currently performing tests. It is an **im4gn.large (2 CPU, 8GB RAM, 937GB directly attached SSD)**. I'm performing the backup from the instance SSD to a temporary gp3 EBS volume (3000 IOPS and 125MB/s throughput baseline). 

The destination database volume (gp3) seems to receive mainly sequential write IOPS with occasional bursts of read IOPS. It is mainly reported idle by AWS metrics. No issue here I think.

The source database volume is impacted a great deal with peaks as high as 10000 read IOPS _as a minute average_ during backup vs ~200 read IOPS max under normal operation (thanks to caching, Erigon does not read so much), so an additional ~9000IOPS. But the specific hardware I'm on can go far beyond that, so no real problem.
If I look at CPU/RAM, `integration` reports **alloc=15.3MB sys=31.9MB** in logs during the whole process but `top` shows a consumption of **~12% CPU and ~16% RAM**.
In my usecase I don't care too much honestly, the bottom-line for me is that I'm able to continue emitting timely attestations during backups and that's all that matter.

I may fare a little better with 16kb page size, as it is the effective IO size of my volume, but I don't have performance issues as it is now so...

**Comment by allada** [comment]
> Hence the backup usecase. Using integration allows me to backup Erigon database while having Erigon running, which is the most important feature for me because I'm staking and don't want to stop Erigon and loose hours of attestations at each backup.

You might want to look into possibly using `zfs` as a filesystem. It's a little slower to read for erigon, but if configured properly it is about 5-10% slower than ext4, supports disk compression (full nodes provide around 50% compression) and most importantly supports instant snapshots, and you are not "required" to stop erigon to create snapshot (but it's good practice to stop erigon for a few seconds only while the `zfs snap` command is run (usually takes ~0.5 seconds).

What I used to do is:
```
zfs snap tank/erigon@snap
zfs send tank/erigon@snap | zstd -v -3 | aws s3 cp - s3://path_to_s3_backup
zfs destroy tank/erigon@snap
```

Then for restore:
```
aws s3 cp s3://path_to_s3_backup - | zstd -v -d | zfs recv tank/erigon -o mountpoint=/path_to_erigon_data
zfs destroy tank/erigon@snap
```

To see more advanced zfs and a bunch of hacks on how to make both uploads and downloads of data to s3 extremely fast see:
https://github.com/allada/eth-archive-snapshot/blob/master/build_archive_node.sh
