### ISSUE TITLE
unable to read itable block error when syncing 

### ISSUE THREAD

**Issue by or2008** [ledgerwatch/erigon#7384]
Hi,

I've been syncing the node for the past few days. Everything was going okay, and I thought it was about to finish. Then, my PC froze, so I had to restart it. The sync resumed, but after a few minutes, the PC froze again. I tried restarting it a few more times, but on each time the PC froze again.

I managed to catch the error once before the PC died:

![image](https://user-images.githubusercontent.com/3414979/234359592-9280cd9f-7121-433d-9d3a-ec7c278dad4a.png)

Any help or suggestions would be greatly appreciated. Is this a bug? Maybe the SSD load is too much, and I can limit Erigon's access to it? Should I format the disk and start over?

I am using Erigon via ETH-docker.

Thanks.

**Comment by tjayrush** [comment]
https://askubuntu.com/questions/1100838/ext4-fs-error-device-sda2-ext4-find-entry1436-ubuntu-18-04
