### ISSUE TITLE
Segment has too short record

### ISSUE THREAD

**Issue by keithchew** [ledgerwatch/erigon#7386]
I have 2 erigon nodes running (version v2.42.0), one of them is giving this error when requesting a transaction, other node is fine:

```
segment /root/.ethereum/snapshots/v1-016500-017000-transactions.seg has too short record: len(buf)=0 < 21
```

If there any command I can run to fix up the snapshot segment file, without rebuilding the node from scratch?

**Comment by AskAlexSharov** [comment]
« Is it safe to copy these files from non corrupted node to the other node?» - yes

total re-building of such segment can be triggered by: 
- remove file
- run “”integration stage_headers —reset”


I don’t have another command for such problem.
