### ISSUE TITLE
mdbx_env_open: cannot allocate memory

### ISSUE THREAD

**Issue by lambo4jos** [ledgerwatch/erigon#7390]
#### System information
Rock5B 16GB RAM

Erigon version: `./erigon --version`
erigon version 2.41.0-stable

OS & Version: Windows/Linux/OSX
Linux erigoneth4tb 5.10.110-rockchip-rk3588 #23.02.2 SMP Fri Feb 17 23:59:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Erigon Command (with flags/config):
./erigon --chain=mainnet --datadir /home/ethereum/.erigon --private.api.addr= --port=50121 --http=true --http.addr=0.0.0.0 --http.port=3649 --http.vhosts=* --torrent.port=32155 --downloader.verify --ws=true --http.api=eth,engine,debug,net,trace,web3,erigon --torrent.download.rate=32mb --db.pagesize=16KB

Concensus Layer:
built in erigon consensus layer

Chain/Network: 
ethereum

#### Expected behaviour
Erigon should start as expected

#### Actual behaviour
Apr 26 11:21:52 erigoneth4tb erigon[2519]: [INFO] [04-26|11:21:52.594] Opening Database                         label=chaindata path=/home/ethereum/.erigon/chaindata
Apr 26 11:21:52 erigoneth4tb erigon[2519]: [EROR] [04-26|11:21:52.601] Erigon startup                           err="mdbx_env_open: cannot allocate memory, label: chaindata, trace: [kv_mdbx.go:269 node.go:323 node.go:326 backend.go:206 node.go:113 main.go:62 command.go:273 app.go:332 app.go:309 main.go:37 proc.go:250 asm_arm64.s:1172]"
Apr 26 11:21:52 erigoneth4tb erigon[2519]: mdbx_env_open: cannot allocate memory, label: chaindata, trace: [kv_mdbx.go:269 node.go:323 node.go:326 backend.go:206 node.go:113 main.go:62 command.go:273 app.go:332 app.go:309 main.go:37 proc.go:250 asm_arm64.s:1172]
Apr 26 11:21:52 erigoneth4tb systemd[1]: erigon.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 11:21:52 erigoneth4tb systemd[1]: erigon.service: Failed with result 'exit-code'.
Apr 26 11:21:52 erigoneth4tb systemd[1]: erigon.service: Scheduled restart job, restart counter is at 5.
Apr 26 11:21:52 erigoneth4tb systemd[1]: Stopped Ethereum Erigon client daemon.
Apr 26 11:21:52 erigoneth4tb systemd[1]: erigon.service: Start request repeated too quickly.
Apr 26 11:21:52 erigoneth4tb systemd[1]: erigon.service: Failed with result 'exit-code'.
Apr 26 11:21:52 erigoneth4tb systemd[1]: Failed to start Ethereum Erigon client daemon.

**Comment by AskAlexSharov** [comment]
@lambo4jos 
 what if you add --db.size.limit=2Tb ?

**Comment by lambo4jos** [comment]
> @lambo4jos what if you add --db.size.limit=2Tb ? (or 1Tb - depending on your current db size)

@AskAlexSharov Thank you for the response! I tested this, and also tried upgrading to erigon version 2.43.0-stable-7e8beecf and am still receiving the error seen below. My chaindata folder is 1.8TB, and the .erigon folder where all the chaindata, snapshots, nodes data, etc, in total is 2.1TB. I tried 2TB and 3TB as options for the value:

```
Apr 28 06:41:14 erigoneth4tb erigon[1674]: [INFO] [04-28|06:41:14.567] [db] params: growStep=2GB, mapsSize=2TB, shrinkThreshold=-1, pageSize=16KB, label=chaindata, WriteMap=false, Durable=false, NoReadahead=true,
Apr 28 06:41:14 erigoneth4tb erigon[1674]: [EROR] [04-28|06:41:14.570] Erigon startup                           err="mdbx_env_open: cannot allocate memory, label: chaindata, trace: [kv_mdbx.go:266 node.go:323 node.go:326 backend.go:203 node.go:106 main.go:59 command.go:274 app.go:332 app.go:309 main.go:36 proc.go:250 asm_arm64.s:1172]"
Apr 28 06:41:14 erigoneth4tb erigon[1674]: mdbx_env_open: cannot allocate memory, label: chaindata, trace: [kv_mdbx.go:266 node.go:323 node.go:326 backend.go:203 node.go:106 main.go:59 command.go:274 app.go:332 app.go:309 main.go:36 proc.go:250 asm_arm64.s:1172]
Apr 28 06:41:14 erigoneth4tb systemd[1]: erigon.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 06:41:14 erigoneth4tb systemd[1]: erigon.service: Failed with result 'exit-code'.
Apr 28 06:41:14 erigoneth4tb systemd[1]: erigon.service: Scheduled restart job, restart counter is at 5.
Apr 28 06:41:14 erigoneth4tb systemd[1]: Stopped Ethereum Erigon client daemon.
Apr 28 06:41:14 erigoneth4tb systemd[1]: erigon.service: Start request repeated too quickly.
Apr 28 06:41:14 erigoneth4tb systemd[1]: erigon.service: Failed with result 'exit-code'.
Apr 28 06:41:14 erigoneth4tb systemd[1]: Failed to start Ethereum Erigon client daemon.
```

**Comment by lambo4jos** [comment]
> 

@AskAlexSharov Late follow-up to close this matter as it was a kernel config issue related to [#4871](https://github.com/ledgerwatch/erigon/issues/4871). Rather than recompiling, I updated the machine to a newer arm OS version that has the newer kernel config parameter the was preventing the machine from running erigon, and the issue resolved
