### ISSUE TITLE
RPC method trace_filter crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vkuzenkov** [ledgerwatch/erigon#7400]
#### System information

Erigon version: 2.43.0

OS & Version: Ubuntu 20.04

Commit hash: 

Erigon Command (with flags/config): 

```
erigon  --chain=goerli
              --maxpeers=400
              --log.console.verbosity=debug
              --private.api.ratelimit=318720
              --datadir=/home/erigon/.local/share/erigon
              --http=false
              --private.api.addr="0.0.0.0:9090"
              --authrpc.addr="0.0.0.0"
              --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
              --authrpc.vhosts="*"
              --metrics
              --metrics.addr=0.0.0.0
```

```
rpcdaemon --datadir=/home/erigon/.local/share/erigon
              --private.api.addr="erigon-goerli:9090"
              --txpool.api.addr="erigon-goerli:9090"
              --ws
              --http.addr="0.0.0.0"
              --http.vhosts="*"
              --http.corsdomain="*"
              --http.trace
              --rpc.batch.concurrency=300
              --rpc.returndata.limit=500000
              --rpc.streaming.disable (without this parameter error also reproduces)
              --http.api=eth,erigon,debug,net,web3,trace,txpool       
              --metrics
              --metrics.addr=0.0.0.0
```

Concensus Layer:

lighthouse

Concensus Layer Command (with flags/config):

 ```
lighthouse
              bn
              --network=goerli
              --datadir=/home/erigon/.local/share/erigon/consensys
              --checkpoint-sync-url={{ checkpoint_sync_url }}
              --reconstruct-historic-states
              --http
              --http-address=0.0.0.0
              --execution-jwt=/home/erigon/.local/share/erigon/jwt.hex
              --execution-endpoint=http://erigon-goerli:8551
              --disable-deposit-contract-sync

```
Chain/Network:  goerli

#### Expected behaviour
{
    "jsonrpc": "2.0",
    "id": 445,
    "method": "trace_filter",
    "params": [{"fromBlock":"0x87cddc","toAddress":["0x1643e812ae58766192cf7d2cf9567df2c37e9b7f"],"toBlock":"0x87cddc"}]
}

{
    "jsonrpc": "2.0",
    "id": 445,
    "result": [
        {
            "action": {
                "from": "0xafb4bce970b77222a74d240294bd67216114b8eb",
                "callType": "call",
                "gas": "0xd291",
                "input": "0x095ea7b3000000000000000000000000779d1b5315df083e3f9e94cb495983500ba8e90700000000000000000000000000000000000000000000000006f05b59d3b1ffff",
                "to": "0x1643e812ae58766192cf7d2cf9567df2c37e9b7f",
                "value": "0x0"
            },
            "blockHash": "0xfe12089ecb9c2660fe6cb30d6073648e9044fa4358e7e4479ad1c414dfc1693f",
            "blockNumber": 8900060,
            "result": {
                "gasUsed": "0xaafe",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
            },
            "subtraces": 2,
            "traceAddress": [],
            "transactionHash": "0x2a577f35e8b6e61914485ce793ca19c50af5ca7d0e918d3d68d95b6abd49b613",
            "transactionPosition": 72,
            "type": "call"
        },
        {
            "action": {
                "from": "0x312ae3c2364231efa3f99b29d73e141b1110a92b",
                "callType": "call",
                "gas": "0xd29d",
                "input": "0x095ea7b3000000000000000000000000779d1b5315df083e3f9e94cb495983500ba8e9070000000000000000000000000000000000000000000000000011c37937e07fff",
                "to": "0x1643e812ae58766192cf7d2cf9567df2c37e9b7f",
                "value": "0x0"
            },
            "blockHash": "0xfe12089ecb9c2660fe6cb30d6073648e9044fa4358e7e4479ad1c414dfc1693f",
            "blockNumber": 8900060,
            "result": {
                "gasUsed": "0xaafe",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
            },
            "subtraces": 2,
            "traceAddress": [],
            "transactionHash": "0xa5f5c189a0543af91253efb02489ed3086f343f239b28e51ade4cf58108185ed",
            "transactionPosition": 147,
            "type": "call"
        }
    ]
}

#### Actual behaviour
Call RPC method trace_filter

{
    "jsonrpc": "2.0",
    "id": 445,
    "method": "trace_filter",
    "params": [{"fromBlock":"0x87cddc","toAddress":["0x1643e812ae58766192cf7d2cf9567df2c37e9b7f"],"toBlock":"0x87cddc"}]
}

Get error:

{ code: ServerError(-32000), message: "method handler crashed", data: None }

Logs:
RPC method trace_filter crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:884 panic.go:260 signal_unix.go:837 stream.go:184 trace_filtering.go:384 value.go:586 value.go:370 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]

#### Steps to reproduce the behaviour

Call RPC method trace_filter

{
    "jsonrpc": "2.0",
    "id": 445,
    "method": "trace_filter",
    "params": [{"fromBlock":"0x87cddc","toAddress":["0x1643e812ae58766192cf7d2cf9567df2c37e9b7f"],"toBlock":"0x87cddc"}]
}

#### Backtrace

````
RPC method trace_filter crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:884 panic.go:260 signal_unix.go:837 stream.go:184 trace_filtering.go:384 value.go:586 value.go:370 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
````
P.S. On 2.42.0 everything is fine.

**Comment by ineron** [comment]
I have the same error:

**Comment by darinvhs** [comment]
seeing this error on the BSC chain as well, so it's not a protocol-specific issue

**Comment by ybstaked** [comment]
Also seeing this error while using erigon for graph

**Comment by ineron** [comment]
> Also seeing this error while using erigon for graph

Yes, it was because of the graph that the question arose.
I used 2.32 before and had no problems.

**Comment by quickchase** [comment]
https://github.com/ledgerwatch/erigon/pull/7539

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open

**Comment by chainpeers** [comment]
For issue status: I'm exploring this issue

**Comment by gladcow** [comment]
For issue status: I'm investigating the issue

**Comment by gladcow** [comment]
Looks like issue is fixed with https://github.com/ledgerwatch/erigon/pull/7539

I've used last devel branch to test it, started goerli lighthouse and erigon nodes with the same params,  last version returns correct answer:
```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0","id": 445,"method": "trace_filter","params": [{"fromBlock":"0x87cddc","toAddress":["0x1643e812ae58766192cf7d2cf9567df2c37e9b7f"],"toBlock":"0x87cddc"}]}' localhost:8545
{"jsonrpc":"2.0","id":445,"result":[{"action":{"from":"0xafb4bce970b77222a74d240294bd67216114b8eb","callType":"call","gas":"0xd291","input":"0x095ea7b3000000000000000000000000779d1b5315df083e3f9e94cb495983500ba8e90700000000000000000000000000000000000000000000000006f05b59d3b1ffff","to":"0x1643e812ae58766192cf7d2cf9567df2c37e9b7f","value":"0x0"},"blockHash":"0xfe12089ecb9c2660fe6cb30d6073648e9044fa4358e7e4479ad1c414dfc1693f","blockNumber":8900060,"result":{"gasUsed":"0xaafe","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":2,"traceAddress":[],"transactionHash":"0x2a577f35e8b6e61914485ce793ca19c50af5ca7d0e918d3d68d95b6abd49b613","transactionPosition":72,"type":"call"},{"action":{"from":"0x312ae3c2364231efa3f99b29d73e141b1110a92b","callType":"call","gas":"0xd29d","input":"0x095ea7b3000000000000000000000000779d1b5315df083e3f9e94cb495983500ba8e9070000000000000000000000000000000000000000000000000011c37937e07fff","to":"0x1643e812ae58766192cf7d2cf9567df2c37e9b7f","value":"0x0"},"blockHash":"0xfe12089ecb9c2660fe6cb30d6073648e9044fa4358e7e4479ad1c414dfc1693f","blockNumber":8900060,"result":{"gasUsed":"0xaafe","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":2,"traceAddress":[],"transactionHash":"0xa5f5c189a0543af91253efb02489ed3086f343f239b28e51ade4cf58108185ed","transactionPosition":147,"type":"call"}]}
```
Erigon version is 
```
$ ./erigon --version
erigon version 2.50.0-dev-33d8c08c
```
 
@qk-santi , @ineron ,  @vkuzenkov ,  can you confirm issue is fixed in last version?

**Comment by yperbasis** [comment]
Please re-open if the issue still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
