### ISSUE TITLE
[2/15 Headers] Waiting for Consensus Layer... 

### ISSUE THREAD

**Issue by Theworldzyours** [ledgerwatch/erigon#7427]
Hello together, 

somehow  my erigon node got stuck at 2/15 headers as it seems. I'm running the 2.43 version and the console output is attached below, any idea why that is?

INFO[05-02|20:23:48.880] [txpool] stat                            pending=160 baseFee=557 queued=187 alloc=2.8GB sys=3.8GB
INFO[05-02|20:23:49.189] [2/15 Headers] Handling new payload      height=17174839 hash=0x3a59c28170d78d5a7212db032e9f8a569f22a60e01790a3a5809aabffec21159
INFO[05-02|20:23:49.432] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:23:49.507] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:23:50.095] Commit cycle                             in=455.3117ms
INFO[05-02|20:23:50.095] Timings (slower than 50ms)               Headers=99ms
INFO[05-02|20:23:50.096] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:23:50.096] RPC Daemon notified of new headers       from=17174838 to=17174839 hash=0x3a59c28170d78d5a7212db032e9f8a569f22a60e01790a3a5809aabffec21159 header sending=0s log sending=0s
INFO[05-02|20:23:51.565] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:02.585] [2/15 Headers] Handling new payload      height=17174840 hash=0x9c2f926325310e009c2da4a8106aebf5908264548ac4208b510da3535a84bcd1
INFO[05-02|20:24:02.921] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:02.974] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:24:03.873] Commit cycle                             in=564.8419ms
INFO[05-02|20:24:03.873] Timings (slower than 50ms)               Headers=241ms
INFO[05-02|20:24:03.873] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:24:03.874] RPC Daemon notified of new headers       from=17174839 to=17174840 hash=0x9c2f926325310e009c2da4a8106aebf5908264548ac4208b510da3535a84bcd1 header sending=61.1µs log sending=0s
INFO[05-02|20:24:05.567] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:14.775] [2/15 Headers] Handling new payload      height=17174841 hash=0x03345f29d1b8722faf02e743897c0037eb07fb2704c89b7faa2de2df6edfda19
INFO[05-02|20:24:15.121] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:15.179] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:24:16.418] Commit cycle                             in=1.0336389s
INFO[05-02|20:24:16.418] Timings (slower than 50ms)               Headers=94ms
INFO[05-02|20:24:16.418] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:24:16.419] RPC Daemon notified of new headers       from=17174840 to=17174841 hash=0x03345f29d1b8722faf02e743897c0037eb07fb2704c89b7faa2de2df6edfda19 header sending=0s log sending=0s
INFO[05-02|20:24:18.455] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:22.524] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:26.911] [2/15 Headers] Handling new payload      height=17174842 hash=0x8cafa2575fc7e567787280c6bf5dc97d55dda2c0b11a67a43d21cb332f1dea9f
INFO[05-02|20:24:27.166] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:28.009] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:24:28.661] Commit cycle                             in=328.3055ms
INFO[05-02|20:24:28.661] Timings (slower than 50ms)               Headers=1.03s
INFO[05-02|20:24:28.662] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:24:28.662] RPC Daemon notified of new headers       from=17174841 to=17174842 hash=0x8cafa2575fc7e567787280c6bf5dc97d55dda2c0b11a67a43d21cb332f1dea9f header sending=0s log sending=0s
INFO[05-02|20:24:30.330] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:37.793] [2/15 Headers] Handling new payload      height=17174843 hash=0x06fb05f7c7a630d040fa1c94d11932e47935ff6533d880eb2a2f7324e6062918
INFO[05-02|20:24:38.056] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:38.148] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:24:38.897] Commit cycle                             in=415.6179ms
INFO[05-02|20:24:38.897] Timings (slower than 50ms)               Headers=264ms
INFO[05-02|20:24:38.898] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:24:38.898] RPC Daemon notified of new headers       from=17174842 to=17174843 hash=0x06fb05f7c7a630d040fa1c94d11932e47935ff6533d880eb2a2f7324e6062918 header sending=0s log sending=0s
INFO[05-02|20:24:40.401] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:48.874] [txpool] stat                            pending=277 baseFee=521 queued=188 alloc=2.4GB sys=3.8GB
INFO[05-02|20:24:50.248] [2/15 Headers] Handling new payload      height=17174844 hash=0x968f520ccecb36066fc0c04139a48487e557959dbcbaf37178c08a12a7c4f512
INFO[05-02|20:24:50.600] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:24:50.723] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:24:51.826] Commit cycle                             in=868.4943ms
INFO[05-02|20:24:51.827] Timings (slower than 50ms)               Headers=162ms LogIndex=52ms
INFO[05-02|20:24:51.827] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:24:51.828] RPC Daemon notified of new headers       from=17174843 to=17174844 hash=0x968f520ccecb36066fc0c04139a48487e557959dbcbaf37178c08a12a7c4f512 header sending=0s log sending=0s
INFO[05-02|20:24:53.965] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:25:00.738] [2/15 Headers] Handling new payload      height=17174845 hash=0xcf0d262d0b100a3865f4c30f1044a92b3661ef8918cc3699c859633c5643ecb0
INFO[05-02|20:25:00.970] [2/15 Headers] Waiting for Consensus Layer... 
INFO[05-02|20:25:01.053] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[05-02|20:25:01.595] Commit cycle                             in=268.9102ms
INFO[05-02|20:25:01.596] Timings (slower than 50ms)               Headers=246ms
INFO[05-02|20:25:01.596] Tables                                   PlainState=92.8GB AccountChangeSet=1.5GB StorageChangeSet=2.5GB BlockTransaction=10.0GB TransactionLog=400.1GB FreeList=179.9MB ReclaimableSpace=179.9GB
INFO[05-02|20:25:01.596] RPC Daemon notified of new headers       from=17174844 to=17174845 hash=0xcf0d262d0b100a3865f4c30f1044a92b3661ef8918cc3699c859633c5643ecb0 header sending=0s log sending=0s
INFO[05-02|20:25:03.023] [2/15 Headers] Waiting for Consensus Layer...

**Comment by harshsingh-cs** [comment]
@Theworldzyours are you using any external consensus layer? check this out - https://github.com/ledgerwatch/erigon/releases/tag/v2.43.0#:~:text=Added%20first%20phase%20of%20Caplin%20(embeddable%20Consensus%20Layer%20implementation)%2C%20replaces%20embedded%20CL%20light%20client.%20Disabled%20by%20default%2C%20enabled%20by%20%2D%2Dinternalcl%20command%20line%20flag.

**Comment by Theworldzyours** [comment]
Hey thanks for getting back! I'm using lighthouse at the moment as CL client. Before with 2.42 i was using the lightclient, which did perform satisfactory given my requirements. Lighthouse seems to be working fine for me though, please see the logs below. You think I should give Caplin a shot?  

May 04 19:44:48.804 INFO New block received                      root: 0x3466b3ff94729ebd05cb5c5f2a5833cc8ebee7c23de9df9e8809510d0ab985e4, slot: 6367122    
May 04 19:44:53.016 INFO Synced                                  slot: 6367122, block: 0x3466…85e4, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x7bb1…2511 (verified), peers: 30, service: slot_notifier
May 04 19:45:01.222 INFO New block received                      root: 0xb69945c94bb197ca1019d43e47d2370a59a96ed1d7ba7cea9d2a6b5996e049d9, slot: 6367123    
May 04 19:45:05.006 INFO Downloading historical blocks           est_time: --, distance: 1709697 slots (33 weeks 6 days), service: slot_notifier
May 04 19:45:05.009 INFO Synced                                  slot: 6367123, block: 0xb699…49d9, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x6831…19b8 (verified), peers: 31, service: slot_notifier
May 04 19:45:12.038 INFO New block received                      root: 0xe967925f966334a2872430e2d7f4066ac1ec2bbb576b2d2b6e6365b97209d4f2, slot: 6367124    
May 04 19:45:17.007 INFO Synced                                  slot: 6367124, block: 0xe967…d4f2, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0xcd14…d05c (verified), peers: 35, service: slot_notifier
May 04 19:45:24.679 INFO New block received                      root: 0xb8cb61b0435dcb4261d5db98b6143c140dc599a0e54c98901cc1d22796fcd05f, slot: 6367125    
May 04 19:45:29.005 INFO Synced                                  slot: 6367125, block: 0xb8cb…d05f, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x2238…002c (verified), peers: 34, service: slot_notifier
May 04 19:45:36.595 INFO New block received                      root: 0xe1256699da51c873058a718fbedcb07faec9f4a460376c1abe0a9ae479d73fdb, slot: 6367126    
May 04 19:45:41.010 INFO Synced                                  slot: 6367126, block: 0xe125…3fdb, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x40a9…4a35 (verified), peers: 32, service: slot_notifier
May 04 19:45:48.759 INFO New block received                      root: 0x9a87a0ec7352d77272283af1f93d6235ec299de0a258ff3e8351e448dd52185d, slot: 6367127    
May 04 19:45:53.002 INFO Synced                                  slot: 6367127, block: 0x9a87…185d, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0xfcce…9137 (verified), peers: 33, service: slot_notifier
May 04 19:45:59.970 INFO New block received                      root: 0xf4c33777903172e3d352d11a9f988b742a137d45e173fd9168b12193654f8ddb, slot: 6367128    
May 04 19:46:05.003 INFO Downloading historical blocks           est_time: --, distance: 1709697 slots (33 weeks 6 days), service: slot_notifier
May 04 19:46:05.005 INFO Synced                                  slot: 6367128, block: 0xf4c3…8ddb, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x95ba…4209 (verified), peers: 32, service: slot_notifier
May 04 19:46:12.569 INFO New block received                      root: 0x4c22e4879b0b1da9e4dad196e0b142386f13f3c9a4503a7330a1919f4b4f8ed4, slot: 6367129    
May 04 19:46:17.013 INFO Synced                                  slot: 6367129, block: 0x4c22…8ed4, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0xe193…8cae (verified), peers: 29, service: slot_notifier
May 04 19:46:24.482 INFO New block received                      root: 0x3f03d1521ab48b4804b24897e4bbde875edef4ecc9a6aad9f530b4ada65ccfb4, slot: 6367130    
May 04 19:46:29.002 INFO Synced                                  slot: 6367130, block: 0x3f03…cfb4, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x3969…fd9e (verified), peers: 30, service: slot_notifier
May 04 19:46:36.497 INFO New block received                      root: 0xd76500baa16d39ace302ebf0493d9d04476b1dc169f18a9eb2ee9e3032431946, slot: 6367131    
May 04 19:46:41.008 INFO Synced                                  slot: 6367131, block: 0xd765…1946, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x9082…97f7 (verified), peers: 30, service: slot_notifier
May 04 19:46:49.661 INFO New block received                      root: 0xc6742696f0eee36b4c348e67820870d4d216ed7ca7d0c8d4a160dc7d05a765ed, slot: 6367132    
May 04 19:46:53.009 INFO Synced                                  slot: 6367132, block: 0xc674…65ed, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x5c6d…36bd (verified), peers: 31, service: slot_notifier
May 04 19:47:00.350 INFO New block received                      root: 0xcfb28080d943c83439037ae1228b2786cdbf6ac6b5a61afecc5f6a00409cb6a2, slot: 6367133    
May 04 19:47:05.012 INFO Downloading historical blocks           est_time: --, distance: 1709697 slots (33 weeks 6 days), service: slot_notifier
May 04 19:47:05.015 INFO Synced                                  slot: 6367133, block: 0xcfb2…b6a2, epoch: 198972, finalized_epoch: 198970, finalized_root: 
0xeff4…c928, exec_hash: 0x436b…bfee (verified), peers: 31, service: slot_notifier
May 04 19:47:13.374 INFO New block received                      root: 0xf883eeed4c9a5fa07d6f2c865dda8f05eab60fa61fb109cc039443b03fd8aece, slot: 6367134    
May 04 19:47:17.0

**Comment by Theworldzyours** [comment]
Hey @keithchew, thanks a lot! Just thought there might be some issue with the headers updating, but i did all kinds of tests in the meantime and everything seems to be working just fine.

**Comment by a26nine** [comment]
@Theworldzyours Were you able to resolve this?
