### ISSUE TITLE
Execute block is very slow   

### ISSUE THREAD

**Issue by 32ethers** [ledgerwatch/erigon#7437]
I'm trying to start my own node. But it's not finished after weeks. I checked with api

```sh
curl -H "content-type:application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' localhost:8545 | jq
```

 ant got this: 
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "currentBlock": "0x0",
    "highestBlock": "0xfbc51f",
    "stages": [
      {
        "stage_name": "Snapshots",
        "block_number": "0xfbc51f"
      },
      {
        "stage_name": "Headers",
        "block_number": "0xfbc51f"
      },
      {
        "stage_name": "BlockHashes",
        "block_number": "0xfbc51f"
      },
      {
        "stage_name": "Bodies",
        "block_number": "0xfbc51f"
      },
      {
        "stage_name": "Senders",
        "block_number": "0xfbc51f"
      },
      {
        "stage_name": "Execution",
        "block_number": "0xc8c1f7"
      },
      {
        "stage_name": "Translation",
        "block_number": "0x0"
      },
      {
        "stage_name": "HashState",
        "block_number": "0x0"
      },
      {
        "stage_name": "IntermediateHashes",
        "block_number": "0x0"
      },
      {
        "stage_name": "AccountHistoryIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "StorageHistoryIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "LogIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "CallTraces",
        "block_number": "0x0"
      },
      {
        "stage_name": "TxLookup",
        "block_number": "0x0"
      },
      {
        "stage_name": "Finish",
        "block_number": "0x0"
      }
    ]
  }
}

```

all has been synced to 0xfbc51f, but Execution is only 0xc8c1f7

I checked log, it shows

```
INFO[05-04|06:41:05.319] [7/15 Execution] Executed blocks         number=13166031 blk/s=2.4 tx/s=433.4 Mgas/s=37.5 gasState=0.26 batch=248.2MB alloc=4.4GB sys=6.8GB
INFO[05-04|06:41:25.754] [7/15 Execution] Executed blocks         number=13166080 blk/s=2.4 tx/s=415.9 Mgas/s=36.1 gasState=0.26 batch=249.6MB alloc=2.7GB sys=6.8GB
INFO[05-04|06:41:45.319] [7/15 Execution] Executed blocks         number=13166114 blk/s=1.7 tx/s=328.2 Mgas/s=27.1 gasState=0.26 batch=250.7MB alloc=2.9GB sys=6.8GB
INFO[05-04|06:41:52.975] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=3.1GB sys=6.8GB
INFO[05-04|06:42:04.864] [7/15 Execution] Executed blocks         number=13166157 blk/s=2.2 tx/s=425.9 Mgas/s=34.9 gasState=0.26 batch=252.1MB alloc=3.2GB sys=6.8GB
INFO[05-04|06:42:24.704] [7/15 Execution] Executed blocks         number=13166208 blk/s=2.6 tx/s=483.4 Mgas/s=40.9 gasState=0.26 batch=253.7MB alloc=3.6GB sys=6.8GB
INFO[05-04|06:42:44.664] [7/15 Execution] Executed blocks         number=13166281 blk/s=3.7 tx/s=635.1 Mgas/s=54.7 gasState=0.27 batch=255.9MB alloc=4.0GB sys=6.8GB

```

I notied blocks per second is very slow, only about 2.5 blk/s. But as I saw in other cases, it should be above 50 blk/s

Here is status about my server, OS is Ubuntu 22.04.2 LTS, and hardware is list below: 
* cpu: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (18 cores)
* ram: 128GB
* disk: Disk /dev/sdb: 3.73 TiB, Disk model: Fanxiang FP325T 

And the server runs a erigon node and a lighthouse node. erigon version has updatd to 2.43.  start commend: 
```sh
./erigon --datadir="/node/eth/erigon/"  --private.api.addr=localhost:9070 --http --http.port 8545 --http.addr=10.0.0.0 --http.api=eth,erigon,web3,net,debug,trace,txpool
./lighthouse beacon_node --network mainnet --datadir /node/eth/lighthouse --port 9800 --execution-endpoint http://127.0.0.1:8551 --execution-jwt /node/eth/erigon/jwt.hex
```

There are some interest things: 
1. cpu usage and memory usage is very low. Erigon should use all the momery but only 10G is used. 
 
![图片](https://user-images.githubusercontent.com/115340054/236134133-0b8a7112-a260-4802-aee9-36d81ae0bc47.png)

2. After I restart erigon, execute speed would be 15 blk/s, but after a while, it fall back to 2.5 blk/s.
3. Disk usage is low too,  lighthouse will cause some disk writing but erigon will not..

![图片](https://user-images.githubusercontent.com/115340054/236135074-d5eab1bf-9a58-4975-875b-a078224987fe.png)

Please help, thanks.

**Comment by AskAlexSharov** [comment]
"After I restart erigon" - you will execute blocks which was executed in the past (most of data is in ram - this is reason why it's faster. 
current bottleneck is "disk read latency" (not throughput). 
execution of blocks is single-threaded now (it will be changed in Erigon3) 


Because you have big RAM - you may try next command to force some data to RAM (not sure will it help or not):
```
make integration
./build/bin/integration warmup --bucket=PlainState --datadir=<datadir>
cat <datadir>snapshots/v1-013000-013500-* > /dev/null
```

**Comment by 32ethers** [comment]
> "After I restart erigon" - you will execute blocks which was executed in the past (most of data is in ram - this is reason why it's faster. current bottleneck is "disk read latency" (not throughput). execution of blocks is single-threaded now (it will be changed in Erigon3)
> 
> Because you have big RAM - you may try next command to force some data to RAM (not sure will it help or not):
> 
> ```
> make integration
> ./build/bin/integration warmup --bucket=PlainState --datadir=<datadir>
> cat <datadir>snapshots/v1-013000-013500-* > /dev/null
> ```

I got some improvment, now it's about 8 blk/s. But I wonder if I can skip block execution? 

And what's the milestone for erigon3? When it's available?

**Comment by AskAlexSharov** [comment]
`if I can skip block execution?` - Erigon has no feature of "snap sync of latest state" yet. so, need exec now. 

`what's the milestone for erigon3? When it's available?` - we don't have ETA yet, because recently we extended scope. It's in development under `--experimental.history.v3` and not production-ready yet.  
See also: https://erigon.substack.com/p/big-release-and-renaming-of-erigon https://erigon.substack.com/p/future-of-the-support-of-bnb-smart https://erigon.substack.com/p/erigon-receives-200000-grant-from

**Comment by 32ethers** [comment]
The speed is still too slow for me, I think I'd better find some snapshot

**Comment by 32ethers** [comment]
The speed is still too slow for me, I think I'd better find some snapshot

**Comment by 32ethers** [comment]
Turn out the shame is on the ssd. After I changed it to WestDigit, the speed can go up to 25 blk/s
