### ISSUE TITLE
Questions about transaction gossiping

### ISSUE THREAD

**Issue by pcw109550** [ledgerwatch/erigon#7440]
Hi. According to the docs: [Transaction Pool Design:Relaying transactions to other network peers](https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design#relaying-transactions-to-other-network-peers),

It is noted that tx gossiping between peer is broken:
> Note that this functionality appears to be broken in the current implementation, i.e. pending transactions are not getting relayed.

I tried to skim through the source, but could not find related code. All I could find was newBlock gossiping(which is disabled after the merge):

https://github.com/ledgerwatch/erigon/blob/30430d585af1b8a98e74ffe890da4426a2585744/turbo/stages/bodydownload/body_algos.go#L207-L208

May I ask that is tx gossiping in erigon working? If yes, can I ask a entrypoint of the related code? 

Thanks!

Here are some researches that I did: 

According to this [doc: Erigon “The Merge” Architecture](https://hackmd.io/@4_PBxu6jQtO7qASCOn0H6w/SJUyNkuA9),
> Gossip on the EL will be disabled and instead we are going to use the P2P network only for Syncing up to the chain tip. Once on chain tip, the Consensus Layer will be the one telling us what new blocks to validate and what fork to follow so no gossip is required on Erigon.

So this means there IS NO gossip at all at erigon execution layer.

According to this [doc: Erigon Blog: Architecture of Erigon - separable and embeddable components](https://erigon.substack.com/p/architecture-of-erigon-separable),
> ETH TxPool uses ETH sentry to download initial set of transactions currently unconfirmed, as well as to receive gossip about new transactions, re-broadcast them, and inject transactions created by users and submitted via ETH RPC api.

So this means there IS gossip for transactions.

**Comment by AskAlexSharov** [comment]
I think it's implemented.
You can find production of such event by `p.newPendingTxs <-`
And handling of this event by `announcements := <-newTxs` here https://github.com/ledgerwatch/erigon-lib/blob/main/txpool/pool.go#L1429
