### ISSUE TITLE
NAT Parameter broke in 2.43.0

### ISSUE THREAD

**Issue by fattox** [ledgerwatch/erigon#7472]
#### System information
Erigon version: 2.43.0
OS & Version: Ubuntu 22.04
Chain/Network: Eth, Polygon... etc

#### Expected behaviour
The NAT parameter no longer seems to work as intended.

Using for example `nat=extip:1.2.3.4`
... should result in an enode address with IP of `1.2.3.4`

#### Actual behaviour
Instead, it just shows `127.0.0.1`. The port also shows as `0`, so it's unclear if one or more parameters such as '--port' are also faulty.

`self=enode://xxxxxx@127.0.0.1:0 name=erigon/v2.43.0-stable-1106475e/linux-amd64/go1.20.3`

Therefore, it's currently not possible to set a valid external IP:port for peering. The assigned IP set by the flag seems to work for the torrent feature though, according to the startup logs (`[torrent] Public IP ip=1.2.3.4`).

Everything was working on `v2.42.0`, tested on a few different nodes on both Eth and Polygon, before and after upgrading.

#### Steps to reproduce the behaviour
Use the nat flag to set an external IP: `--nat=extip:${PUBLIC_IP}`

**Comment by AskAlexSharov** [comment]
hi. checked. nat working just we do log wrong value 
fixed by https://github.com/ledgerwatch/erigon/pull/7480

**Comment by fattox** [comment]
Thanks, will close the issue and check on next release! 👍
