### ISSUE TITLE
Database size is twice with external CL

### ISSUE THREAD

**Issue by iFA88** [ledgerwatch/erigon#7492]
Greetings!

I synced a fresh new erigon ( `git_branch=HEAD git_tag=v2.43.0 git_commit=1106475e345d936aa1220ace3e95d746ec361fa4` ) with the following parameters:
`--datadir=/mnt/m2/eth --chain=mainnet --port=30304 --http.addr=10.0.0.4 --http.api=eth,erigon,web3,trace,net,debug,admin --http.port=4004 --http.vhosts=* --torrent.download.rate 125mb --rpc.batch.limit=1024`

Sync is finished and the chaindata folder looks like this:
```
du mdbx.dat
2010604501	mdbx.dat
```
I have two another erigon node with same erigon version and same db related parameters just with internal cl, these chaindata folder looks like:
```
du mdbx.dat
990925233	mdbx.dat
```
I expected less data when i use external CL.

Br:
iFA

**Comment by iFA88** [comment]
bump

**Comment by wmitsuda** [comment]
the first one looks "correct", it is ~2TB, the ones with ~1TB look pruned.

couldn't it be you intended to have a pruned node, but forgot the flags in the externalcl one?

**Comment by iFA88** [comment]
> the first one looks "correct", it is ~2TB, the ones with ~1TB look pruned.
> 
> couldn't it be you intended to have a pruned node, but forgot the flags in the externalcl one?

Hey there! Both are non-pruned, they have all historical state.

**Comment by wmitsuda** [comment]
is the second one 1TB, right? I wish unpruned mainnet takes 1TB :)

if so, I think something is odd with your older node (no idea what, though)
