### ISSUE TITLE
`evm` executable leaves database files behind

### ISSUE THREAD

**Issue by holiman** [ledgerwatch/erigon#7511]
After running the fuzzer for some time, my system hit out-of-disk errors. 
It had filled the disk with `/tmp/erigon-memdb-<numbers>/`, where each folder contains one `mdbx.dat` at `24KiB`, and an `mdbx.lck` at `1MiB`. It seems that each invocation of `evm` creates one 

Example to create one:
```
/home/martin/workspace/erigon-evm --json --noreturndata --nomemory statetest /tmp/00048943-mixed-1.json
```
I retried with `60024361821f6bcc6b8e724aed1b07531c447fce`, same issue.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/7517
