### ISSUE TITLE
 Caplin Stability focus

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#7513]
# Caplin Phase 1 Stability focus

- [x] Join EIP4844 testnet
- [x] Make sepolia syncable and stay on tip most of the time
- [x] Make goerli syncable and stay on tip most of the time
- [x] Try to achieve 60% unit test coverage instead of whatever lower percentage we have now.
- [x] Gnosis Chain X Caplin
- [x] Make gnosis stay on tip
- [x] Metrics and Diagnostics
- [x] Peering issues

**Comment by Giulio2002** [comment]
Devnet 5 4844: https://4844-devnet-5.ethpandaops.io/

**Comment by Giulio2002** [comment]
Status of each issue:

* EIP4844: did not even joined any testnet yet so dunno.
* Sepolia catch up but fall out of sync too much
* Goerli cannot get in sync and some dies after a while (reproduced only on remote machine), could be config issue
* Tests are lacking
* Config is in but needs update
* We have grafana but we could do better

**Comment by Giulio2002** [comment]
CC @enriavil1

**Comment by enriavil1** [comment]
> CC @enriavil1 

I am honored to be CCed by the Top G 🧎

**Comment by Giulio2002** [comment]
https://github.com/ledgerwatch/erigon/pull/7519

**Comment by Giulio2002** [comment]
I will close it as I am happy with the results :)
