### ISSUE TITLE
The problem of high CPU usage in the program

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#7535]
#### System information

Erigon version: 2.42.0-stable-beb97784

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config): ${nodeServiceDir}/bin/erigon --datadir=${nodeServiceDir}/erigon --chain=mainnet --prune=hrtc --authrpc.jwtsecret=${nodeServiceDir}/erigon/jwt.hex --db.read.concurrency 5000 --rpc.batch.concurrency 10000 --rpc.gascap=600000000 --rpc.evmtimeout=30s --rpc.batch.limit=100 --rpc.returndata.limit=104857600

Concensus Layer: lighthouse

Concensus Layer Command (with flags/config): ${nodeServiceDir}/bin/lighthouse bn -d ${nodeServiceDir}/lighthouse --network mainnet  --execution-jwt ${nodeServiceDir}/erigon/jwt.hex --checkpoint-sync-url=https://sync-mainnet.beaconcha.in

Chain/Network: eth

#### Expected behaviour
RPC server with normal CPU usage

#### Actual behaviour
After running for a long time, suddenly the CPU usage rate remains above 95%

#### Steps to reproduce the behaviour
unknown

#### Backtrace

Perf tool records CPU usage,  [.] runtime.findObject uses 53.83% CPU performance
Attached Pref result file

[perf.zip](https://github.com/ledgerwatch/erigon/files/11504299/perf.zip)

**Comment by AskAlexSharov** [comment]
logs?

**Comment by sundafa** [comment]
The log is very normal, and it is no different from normal run

**Comment by AskAlexSharov** [comment]
fine. then we can't help.
