### ISSUE TITLE
Runaway goroutine count

### ISSUE THREAD

**Issue by BriungRi** [ledgerwatch/erigon#7544]
#### System information

Erigon v2.43.0

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 1 (ETH Mainnet)

#### Expected behaviour

Stable # of goroutines

#### Actual behaviour

Monotonically (seemingly) increasing number of goroutines

#### Steps to reproduce the behaviour

Leave Erigon on for >24 hours

#### Backtrace

pprof

![image](https://github.com/ledgerwatch/erigon/assets/8957844/7f71b315-1349-48b8-8ea6-3fbf256ecfb9)
[zipped pprof file](https://github.com/anacrolix/torrent/files/11478890/goroutine.pprof.zip)

Possibly related issue: https://github.com/anacrolix/torrent/issues/820

Possible fix is to bump the anacrolix/torrent package version

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon/pull/7545
