### ISSUE TITLE
NewPooledTransactionHashes88 RLP parse error - leading zeros

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#7588]
#### System information

Erigon version: `./erigon --version`

2.44.0-dev-14653bbd

Linux and macOS

Commit hash: 

Happens both on devel 14653bbda1d8403a678a1f2440e118a8427f7e18 and tag v2.43.0

Erigon Command (with flags/config):

```
./build/bin/erigon
		--chain mainnet \
		--datadir /mnt/nvme/data1 \
		--maxpeers 10 \
		--p2p.protocol 68 \
		--nat stun \
		--internalcl
```

Concensus Layer: internalcl

Concensus Layer Command (with flags/config): --internalcl

Chain/Network: mainnet

#### Actual behaviour

Getting a lot of error messages:

Handling incoming message msg=NEW_POOLED_TRANSACTION_HASHES_68 err="parsing NewPooledTransactionHashes88: rlp parse: integer encoding for RLP must not have leading zeros: 00000077"

#### Expected behaviour

No such messages.

#### Steps to reproduce the behaviour

Run the command and wait a minute.

**Comment by luncht1me** [comment]
+1 having this issue too. I've run `integration` to unwind almost a million blocks and resynced and still didn't fix.
Saw somewhere in trace logs at one point hashes were coming out like `0000000001properhexhashofcorrectlength00000001`

**Comment by wtdcode** [comment]
updates on this?

**Comment by wtdcode** [comment]
@AskAlexSharov Any suggestions on this?
