### ISSUE TITLE
 When will Erigon work as a EL and CL client?

### ISSUE THREAD

**Issue by Ungolim** [ledgerwatch/erigon#7602]
@Giulio2002 im tired of waiting. We need Rocket Pool smartnode integration too asap

thank you

**Comment by Giulio2002** [comment]
Sorry to dissapoint you, but validator node wont be available anytime soon. you can expect an official release soon but definitely not validating node

**Comment by Giulio2002** [comment]
cheers mate

**Comment by Giulio2002** [comment]
Actually no, i changed my mind

**Comment by Giulio2002** [comment]
# Caplin checklist

- [ ] Propoer JSON/SSZ Beacon RPC endpoint for validator nodes
- [ ] Collections of operations
     - [ ] Voluntary exits
     - [ ] Aggregate and proofs
     - [ ] Proposer slashings
     - [ ] Attester Slashings
     - [ ] Withdrawal
     - [ ] BlsExecutionChanges
- [ ] Implement all validator endpoints 
     - [[ ] Voluntary exits
     - [ ] Aggregate and proofs
     - [ ] Proposer slashings
     - [ ] Attester Slashings
     - [ ] Withdrawal
- [ ] follow this link, I aint't writing all that (https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi)

**Comment by anthonyra** [comment]
@Giulio2002

Some clarification here, does the `--internalcl` allow Erigon to be a full node just not a validator? If it can be a standalone full node, is there anyway to double check the status of the internal CL? Like is it on or off or error'ing?

**Comment by Giulio2002** [comment]
oh uhm sorry, for the late response, --internalcl can be used as a full node, yes. said that, it will error if it gets borked. logs are not the best but if you want more verbosity run logs in debug mode

**Comment by anthonyra** [comment]
> oh uhm sorry, for the late response, --internalcl can be used as a full node, yes. said that, it will error if it gets borked. logs are not the best but if you want more verbosity run logs in debug mode

No worries! I've tried to use `--internalcl` however it resulted in a death loop so decided to go with lighthouse in the meantime but it'd be great to only use Erigon for an archive node for example.
