### ISSUE TITLE
Fix SSZ tests after data_gas_used was added

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#7640]
[v1.4.0-alpha.1](https://github.com/ethereum/consensus-specs/releases/tag/v1.4.0-alpha.1) of the consensus specs adds `data_gas_used` to the header and changes `data_gas_used`  from uint256 to uint64. PR #7639 implements the change, but w/o the necessary updates to the SSZ tests, whose embed SSZ serialization is obsolete now. Namely, the following tests need to be updated:
- TestHashTreeRoot
- TestGetters
- TestBlockProcessingDeneb
- TestEncodeDecode

**Comment by Giulio2002** [comment]
Fixed by https://github.com/ledgerwatch/erigon/pull/7650

**Comment by Giulio2002** [comment]
hippity hoppity, your issue is my property
