### ISSUE TITLE
Difference in Synchronization Speed Between Two Erigon Nodes In Same Lan

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7652]
Hello,

I am currently running two Erigon nodes on two separate machines within the same local network. I've noticed a consistent lag in synchronization for one of the nodes, which is often dozens of blocks behind the other.

Both machines have similar configurations and are running the same version of Erigon. However, I'm still observing a discrepancy in their performance, with one consistently lagging behind the other in terms of synchronization speed.

Here's what I've tried so far:

1. Checked the hardware performance of both machines (CPU, memory, disk I/O, network bandwidth) and found no significant differences.
2. Verified the network connections and found no issues.
3. Checked the storage speeds, again finding no significant differences.
4. Reviewed the configurations for both nodes, which are identical.
5. Despite these checks, the problem persists.

Do you have any suggestions on what might be causing this, or steps I could take to diagnose and fix the issue? Any advice would be greatly appreciated.

Thank you.

**Comment by AskAlexSharov** [comment]
lagging behind - may be related to "pruning". Did fix several "slow pruning" problems in https://github.com/ledgerwatch/erigon/pull/7643
