### ISSUE TITLE
trace_callMany output different from Nethermind & etherscan

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#7675]
Reported by Nikita Mescheryakov from Nethermind.

The following request produces an apparently wrong result with Erigon:
[request.txt](https://github.com/ledgerwatch/erigon/files/11666489/request.txt)
```
curl -X POST -H "Content-Type: application/json" --data @request.txt localhost:8545
```
Output by Erigon https://github.com/ledgerwatch/erigon/commit/37a8450d5f915125e8b5f0147b51ecd07cf044db
[erigon.txt](https://github.com/ledgerwatch/erigon/files/11666499/erigon.txt)

Output by Nethermind:
[nethermind.txt](https://github.com/ledgerwatch/erigon/files/11666511/nethermind.txt)

Nethermind agrees with https://etherscan.io/tx/0x0cada03f6477d0db5cec925d113e705b116e4176f82aefcd35415dcaa310ea93#statechange

For example, according to both Nethermind & Etherscan, the balance of 0x6b75d8af000000e20b7a7ddf000ba900b4009a80 changes from 0x21CEFBB06C to 0x22241F6A74, while Erigon's state diff is from 0x22e4eb0f32 to 0x233a0ec93a.

**Comment by ArielTM** [comment]
maybe check also using `debug_traceCallMany`. It's logic slightly differ

**Comment by praveenbm5** [comment]
Any updates on this...

I am also facing wierd issues because of this

**Comment by tjayrush** [comment]
comment

**Comment by yperbasis** [comment]
The historical block number argument in ETH JSON-RPC function calls refers to the state at the _end_ of the block. So, in order to reproduce historical execution of the first transaction of block 17231118, the block number argument should be 17231117 (=0x106ED0D). Then Erigon agrees with Etherscan. See also https://ethereum.stackexchange.com/questions/146983/the-block-number-argument-in-eth-json-rpc-function-calls.
