### ISSUE TITLE
Caplin - Improvements and Phase 2 sprint

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#7676]
# Rationale

We need caplin to be memory efficient and start phase2.

# Implementation

- [x] EL compatible Engine API (other than erigon)
- [x] Record mode
- [x] Regression tests
- [x] disk-based backup beacon states
- [x] Phase2 Architecting
- [x] Hard fork gossip transition (CL)
- [x] Concurrent BLS

**Comment by Giulio2002** [comment]
regarding hive tests i am happy if we can just even run them. CC @enriavil1

**Comment by enriavil1** [comment]
> regarding hive tests i am happy if we can just even run them. CC @enriavil1 

I'll make you happy ❤️
