### ISSUE TITLE
 Caught SIGILL in blst_cgo_init

### ISSUE THREAD

**Issue by thorstenhirsch** [ledgerwatch/erigon#7683]
Running erigon fails with the following error message:
```
$ erigon --help
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
```

#### System information

erigon v2.44.0
Ubuntu 22.04.2
amd64 (MacBook Pro 2014, so it's a rather old intel CPU)

The CPU and the Go package don't seem to be compatible!

See:
https://github.com/bnb-chain/bsc/issues/1521
https://github.com/bnb-chain/bsc/issues/1562

**Comment by Giulio2002** [comment]
We do not support bsc please report on nodereal

**Comment by thorstenhirsch** [comment]
The problem occurs when calling `erigon --help`. I posted links to bsc issues to show that they had the problem as well (and resolved it).

**Comment by yperbasis** [comment]
This might be related to https://github.com/supranational/blst/issues/10 (see also https://github.com/ethereum/go-ethereum/pull/27155).

**Comment by thorstenhirsch** [comment]
Is it already fixed? I just built the current devel branch and cannot reproduce the SIGILL anymore:
```
$ ./erigon --version
erigon version 2.47.0-dev-35422986
```
