### ISSUE TITLE
Pruning Call Trace Table?

### ISSUE THREAD

**Issue by 0xSheller** [ledgerwatch/erigon#7744]
Can't seem to find this in the documentation. 

Erigon is currently on [10/15 CallTraces] Pruning call trace table. 

Did not specify pruning when launching erigon. Is this normal behavior?

This stage is extremely slow, slower than Execution stage. Been on this stage for an entire week now. Using an AWS io3 disk with really high throughput/iops.

If i exit the sync at this stage to restart the server for whatever reason, will it restart from stage 1/15? The server was accidentally restarted during execution stage near the very end and it had to restart from block 0 so not sure if this behavior applies per stage or the entire process.

**Comment by AskAlexSharov** [comment]
make integration 
./build/bin/integration print_stages

**Comment by 0xSheller** [comment]
> make integration ./build/bin/integration print_stages


```
INFO[06-16|19:32:28.691] logging to file system                   log dir=mainnet/logs file prefix=integration log level=info json=false
INFO[06-16|19:32:59.221] [snapshots] Blocks Stat                  blocks=16500k indices=16500k alloc=2.3GB sys=2.4GB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

                                 stage_at        prune_at
Snapshots                        0               0
Headers                          0               0
BlockHashes                      0               0
Bodies                           0               0
Senders                          0               0
Execution                        0               0
Translation                      0               0
HashState                        0               0
IntermediateHashes               0               0
AccountHistoryIndex              0               0
StorageHistoryIndex              0               0
LogIndex                         0               0
CallTraces                       0               0
TxLookup                         0               0
Finish                           0               0
--
prune distance:

blocks.v2: blocks=16499999, segments=16499999, indices=16499999

history.v3: false, txs.v3: false, idx steps: 0.00, lastMaxTxNum=0->1, lastBlockInSnap=0

sequence: EthTx=2, NonCanonicalTx=0

in db: first header 0, last header 0, first body 0, last body 0
```
![image](https://github.com/ledgerwatch/erigon/assets/93097065/d112b845-ca76-443f-bc6c-9cfb5afe9645)

**Comment by AskAlexSharov** [comment]
Yes, no prune flag. But i understand the reason now: erigon does move old blocks from db to snapshot files. It also moves txlookup index there. And then prune blocks and index. On recent release (or maybe not released yet) - we reduced amount of such pruning per cycle - to make it fast. Here: https://github.com/ledgerwatch/erigon/pull/7643/files#diff-ab9a3faf1e1180eb3a5fc3d320722c5ec450a65971062fbcfb8fe9754f4f583cL239

**Comment by 0xSheller** [comment]
> 

Is it safe to stop, update, and resume? or will i lose progress of entire sync?

**Comment by 0xSheller** [comment]
> Yes, no prune flag. But i understand the reason now: erigon does move old blocks from db to snapshot files. It also moves txlookup index there. And then prune blocks and index. On recent release (or maybe not released yet) - we reduced amount of such pruning per cycle - to make it fast. Here: https://github.com/ledgerwatch/erigon/pull/7643/files#diff-ab9a3faf1e1180eb3a5fc3d320722c5ec450a65971062fbcfb8fe9754f4f583cL239



> > 
> 
> Is it safe to stop, update, and resume? or will i lose progress of entire sync?

bumping this again @AskAlexSharov  AskAlexSharov

**Comment by AskAlexSharov** [comment]
"Is it safe to stop" - in-general: yes. but `v2.44.0 - v2.45.1` releases had bug - which will loose all the progress.
