### ISSUE TITLE
requested block is too old

### ISSUE THREAD

**Issue by Venoox** [ledgerwatch/erigon#7748]
`Served method=eth_getProof reqid=16 t=120.8µs err="requested block is too old, block must be within 1000 blocks of the head block number (currently 3696916)"`

I'm not sure is this a limitation of Erigon or a bug?

**Comment by 0xSheller** [comment]
> `Served method=eth_getProof reqid=16 t=120.8µs err="requested block is too old, block must be within 1000 blocks of the head block number (currently 3696916)"`
> 
> I'm not sure is this a limitation of Erigon or a bug?

This is expected behavior. 


Per code comments: 

```
// maxGetProofRewindBlockCount limits the number of blocks into the past that
// GetProof will allow computing proofs.  Because we must rewind the hash state
// and re-compute the state trie, the further back in time the request, the more
// computationally intensive the operation becomes.  The staged sync code
// assumes that if more than 100_000 blocks are skipped, that the entire trie
// should be re-computed. Re-computing the entire trie will currently take ~15
// minutes on mainnet.  The current limit has been chosen arbitrarily as
// 'useful' without likely being overly computationally intense.  This parameter
// could possibly be made configurable in the future if needed.
```

Basically what you're trying to do is so expensive on a compute level that there's a hard limit. You could increase this by updating the `maxGetProofRewindBlockCount` param in eth_call.go and rebuilding. I highly advise against this tho.
