### ISSUE TITLE
Node lags behind when web socket is on for eth_subscribe for new block

### ISSUE THREAD

**Issue by Aman-Maheshwari7** [ledgerwatch/erigon#7761]
#### System information

Erigon version: 0xpolygon/erigon:0.0.5

OS & Version: Ubuntu

Chain/Network: 

#### Expected behaviour
When eth_subscribe is used for every new block through web socket, node should remain in sync and return the data as well.

#### Actual behaviour
When eth_subscribe is used for every new block through web socket, node becomes out-of-sync and also misses many blocks for eth_subscribe.

**Comment by AskAlexSharov** [comment]
maybe fixed by https://github.com/ledgerwatch/erigon/pull/7724
