### ISSUE TITLE
 ERIGON v2.46.0's version runs an error

### ISSUE THREAD

**Issue by zhy827827** [ledgerwatch/erigon#7766]
**Use Ericon to run the Polygon chain:**
erigon --datadir=/opt/data/polygondata --chain=bor-mainnet  --bor.heimdall=http://127.0.0.1:1317 --db.pagesize=16k --db.size.limit 7T  --private.api.addr=0.0.0.0:9090 --http.api eth,erigon,web3,net,debug,trace,txpool --ws --ws.compression --http.addr=0.0.0.0 --http.corsdomain '*' --http.vhosts '*'

Logs:

INFO[06-20|02:12:05.855] Opening Database                         label=chaindata path=/opt/rockx/polygondata/chaindata
INFO[06-20|02:12:08.057] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
EROR[06-20|02:12:08.058] Erigon startup                           err="openClient: mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: downloader, trace: [kv_mdbx.go:262 downloader.go:471 downloader.go:90 backend.go:993 backend.go:298 node.go:105 main.go:66 make_app.go:42 command.go:274 app.go:332 app.go:309 main.go:37 proc.go:250 asm_amd64.s:1598]"
openClient: mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: downloader, trace: [kv_mdbx.go:262 downloader.go:471 downloader.go:90 backend.go:993 backend.go:298 node.go:105 main.go:66 make_app.go:42 command.go:274 app.go:332 app.go:309 main.go:37 proc.go:250 asm_amd64.s:1598]

My disk is a 12T SSD disk.there is still 4T of disk space left

**Comment by zhy827827** [comment]
`mdbx_stat -ef  /opt/data/polygondata/chaindata
mdbx_stat v0.12.0-71-g1cac6536 (2022-07-28T09:57:31+07:00, T-9a6d7e5b917e5fbd14dc51835fa749d092aa1d72)
Running for /opt/data/polygondata/chaindata...
Environment Info
  Pagesize: 4096
  Dynamic datafile: 49152..7696581394432 bytes (+2147483648/-4294967296), 12..1879048192 pages (+524288/-1048576)
  Current mapsize: 7696581394432 bytes, 1879048192 pages
  Current datafile: 6307811459072 bytes, 1539993032 pages
  Last transaction ID: 95580885
  Latter reader transaction ID: 95580885 (0)
  Max readers: 116
  Number of reader slots uses: 1
Garbage Collection
  Pagesize: 4096
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 108
  Entries: 111
Page Usage
  Total: 1879048192 100%
  Backed: 1539993032 82.0%
  Allocated: 1539993032 82.0%
  Remained: 339055160 18.0%
  Used: 1539883816 82.0%
  GC: 109216 0.0%
  Retained: 0 0.0%
  Reclaimable: 109216 0.0%
  Available: 339164376 18.0%
Status of Main DB
  Pagesize: 4096
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 3
  Overflow pages: 0
  Entries: 111`

**Comment by zhy827827** [comment]
I added a parameter to run now (--no-downloader)

**Comment by AskAlexSharov** [comment]
it's ok to delete folder datadir/snapshots/db

**Comment by AskAlexSharov** [comment]
label: downloader

**Comment by zhy827827** [comment]
thank you~
