### ISSUE TITLE
Add version-info to prometheus-metrics

### ISSUE THREAD

**Issue by guybrush** [ledgerwatch/erigon#7768]
# Rationale

Right now its only possible to get the version-info via `/debug/metrics/version`

Being able to get the version of a running node via a standardized way (prometheus) will make it easier to run and maintain the process.

# Implementation

I suggest using a gauge, just like it is used for golang-info

```
go_info{version="go1.20.5"} 1
```

It could be shown as

```
erigon_info{version="2.45.1-stable",commit="29f8e97cf7adc0210191a7081ec288cd8aca34b1"} 1
```

**Comment by AskAlexSharov** [comment]
@guybrush how to display such info in grafana?

**Comment by AskAlexSharov** [comment]
is it https://github.com/ledgerwatch/erigon/pull/7769 ?

**Comment by AskAlexSharov** [comment]
wonder if rpcdaemon need own metric too

**Comment by guybrush** [comment]
sorry i am not familiar with github.com/VictoriaMetrics/metrics.

not sure how you register metrics that then get exposed via /debug/prometheus.

also not sure if i understand your question regarding grafana, you just make a query against `erigon_info` (if you use that metric-name).

**Comment by guybrush** [comment]
maybe copy this pattern https://github.com/search?q=repo%3Aledgerwatch/erigon%20rpcRequestGauge&type=code

i could not see a clear pattern how metrics are set in erigon-codebase, would have made a PR otherwise

**Comment by AskAlexSharov** [comment]
ok, then done by https://github.com/ledgerwatch/erigon/pull/7769

**Comment by guybrush** [comment]
nice! thank you so much!
