### ISSUE TITLE
metrics are not being updated with new blocks

### ISSUE THREAD

**Issue by nateless** [ledgerwatch/erigon#7778]
#### System information

Erigon version: 2.46.0

OS & Version: Linux

Concensus Layer: lighthouse

Chain/Network: eth main

#### Expected behaviour

Metrics should be updated with the current block height

#### Actual behaviour

blocks are being applied, but metrics are being updated only once in 30 or 60 minutes.

<img width="847" alt="image" src="https://github.com/ledgerwatch/erigon/assets/470685/d47149ad-08cf-48c1-b7b9-596d01541cce">

PS: gap in metrics is our issue when we restarted node.

**Comment by AskAlexSharov** [comment]
Erigon logs plz

**Comment by nateless** [comment]
Hey @AskAlexSharov, my apologies for the late response. Unfortunately, it's not feasible to provide the information you're asking for due to the vast volume of consensus logs (Lighthouse), API calls, and other data. If you could specify what I should look for or grep, that would be a great help.
