### ISSUE TITLE
Erigon stops syncing

### ISSUE THREAD

**Issue by zlxadata** [ledgerwatch/erigon#7786]
Erigon currently stops syncing, but no errors are reported.
The capacity of the mdbx.data file in chaindata is 1486058684416 bytes, which has not changed for two days.
(The consensus node pryms is running normally and is currently synchronized to 6456000.)
Where is the problem?

**Comment by AskAlexSharov** [comment]
no diagnostic info - then we can't help. 
please open new issue, with: version, network name, logs, any other other useful info.
