### ISSUE TITLE
Erigon currently stops syncing, but no errors are reported

### ISSUE THREAD

**Issue by zlxadata** [ledgerwatch/erigon#7793]
#### System information

Erigon version：erigon version 2.43.0-stable

OS & Version：Linux - Ubuntu 22.10

Commit hash: 

Erigon Command (with flags/config)：
--datadir=/node2/data-erigon
--torrent.download.rate=20mb 
--http --http.addr 0.0.0.0 
--authrpc.jwtsecret /node2/data-erigon/jwt.hex

Concensus Layer：Prysm v4.0.5

Concensus Layer Command (with flags/config):
--datadir=/node2/data-prysm 
--jwt-secret=/node2/data-erigon/jwt.hex 
--rpc-host=0.0.0.0 
--grpc-gateway-host=0.0.0.0 
--monitoring-host=0.0.0.0 -
-execution-endpoint=http://127.0.0.1:8551 
--accept-terms-of-use=true

Chain/Network: 

Expected behaviour
Erigon data is continuously synchronized, and the mdbx.data file in the chaindata directory should continue to grow.

Actual behaviour
Erigon currently stops syncing, but no errors are reported.The capacity of the mdbx.data file in chaindata is 1486058684416 bytes, which has not changed for two days.

Steps to reproduce the behaviour
erigon does not currently have continuous sync data，but no errors are reported.

diagnostic info 1：logs info
[INFO] [06-23|16:25:30.126] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.6GB sys=3.1GB
[INFO] [06-23|16:26:30.121] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.3GB sys=3.1GB
[INFO] [06-23|16:27:30.118] [p2p] GoodPeers                          eth67=29 eth68=21
[INFO] [06-23|16:27:30.126] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.6GB sys=3.1GB
[INFO] [06-23|16:28:30.121] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.4GB sys=3.1GB
[INFO] [06-23|16:29:30.118] [p2p] GoodPeers                          eth67=29 eth68=21
[INFO] [06-23|16:29:30.125] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.6GB sys=3.1GB
[INFO] [06-23|16:30:30.121] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.5GB sys=3.1GB
[INFO] [06-23|16:31:30.117] [p2p] GoodPeers                          eth68=23 eth67=28
[INFO] [06-23|16:31:30.126] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=2.8GB sys=3.1GB

diagnostic info 1：stack trace
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0xd9f315        github.com/anacrolix/torrent.(*Client).initiateProtocolHandshakes+0x195        /root/go/pkg/mod/github.com/anacrolix/torrent@v1.48.1-0.20230219022425-e8971ea0f1bf/cli>
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0xd9f72f        github.com/anacrolix/torrent.(*Client).establishOutgoingConnEx+0x30f        /root/go/pkg/mod/github.com/anacrolix/torrent@v1.48.1-0.20230219022425-e8971ea0f1bf/client>
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0xd9fbd7        github.com/anacrolix/torrent.(*Client).establishOutgoingConn+0x77        /root/go/pkg/mod/github.com/anacrolix/torrent@v1.48.1-0.20230219022425-e8971ea0f1bf/client.go>
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0xd9fdc4        github.com/anacrolix/torrent.(*Client).outgoingConnection+0xc4                /root/go/pkg/mod/github.com/anacrolix/torrent@v1.48.1-0.20230219022425-e8971ea0f1bf/clie>
6月 23 16:34:10 zlaxdata erigon[1873737]: 1 @ 0x459e16 0x48ae95 0x13f03ed 0x48e0a1
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0x48ae94        time.Sleep+0x134                                                                /usr/local/go/src/runtime/time.go:195
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0x13f03ec        github.com/ledgerwatch/erigon-lib/downloader.(*Downloader).mainLoop.func1+0x4c        /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230423044930-fc9dd7>
6月 23 16:34:10 zlaxdata erigon[1873737]: 1 @ 0x459e16 0x48ae95 0x8b3436 0x48e0a1
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0x48ae94        time.Sleep+0x134                                                /usr/local/go/src/runtime/time.go:195
6月 23 16:34:10 zlaxdata erigon[1873737]: #        0x8b3435        github.com/VictoriaMetrics/metrics.summariesSwapCron+0x35        /root/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.23.1/summary.go:237

**Comment by AskAlexSharov** [comment]
- let's try to upgrade erigon? 
- also can provide next info: `curl -sK -v http://localhost:6060/debug/pprof/goroutine?debug=1 > goroutines.txt`
- what is prysm version?

**Comment by zlxadata** [comment]
Thanks for your answer！
1.My prysm version is：V 4.0.5
2.The Command：curl -sK -v http://localhost:6060/debug/pprof/goroutine?debug=1 > goroutines.txt

curl: option -sK: error encountered when reading a file
curl: try 'curl --help' or 'curl --manual' for more information

3.How to upgrade while erigon is running？

**Comment by icculp** [comment]
Maybe unrelated, but mumbai on 2.47 doesn't keep up and keeps thinking it's synced when it's is in fact not.
![image](https://github.com/ledgerwatch/erigon/assets/57159226/3ed312b6-ffaf-409a-9534-c2400a6d5e48)

**Comment by AskAlexSharov** [comment]
@icculp hi. your comment is not related to this issue. please create another issue with logs, hardware info, disk type, etc...

**Comment by zlxadata** [comment]
I use this command：curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://127.0.0.1:8545
Get the current latest synchronized block height：0xfbc51f（blockno：16499999）and stop syncing。

And after I upgrade erigon to 2.47.0, the capacity of the mdbx.data file in chaindata is changed from1486058684416 bytes to 1484386635776 bytes。

I don't know what to do now

**Comment by AskAlexSharov** [comment]
Show logs

**Comment by zlxadata** [comment]
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.239] [2/15 Headers] Handling new payload      height=15558339 hash=0x7be1a05890f40c1bd304d184c8e069eeb739389a236ab4afc202e3bcee3ec17e
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.240] [2/15 Headers] Waiting for Consensus Layer...
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.241] [2/15 Headers] Handling new payload      height=15558340 hash=0x8d5ae617d21823a98ac5f6b99188c4fb03189bbc16939b56245e5db02cb23738
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.242] [2/15 Headers] Waiting for Consensus Layer...
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.246] [2/15 Headers] Handling new payload      height=15558341 hash=0x126536944b6448d7251a36830ec2393b2ceb30f1ee936d553043fc87556c7ed2
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.247] [2/15 Headers] Waiting for Consensus Layer...
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.253] [2/15 Headers] Handling new payload      height=15558342 hash=0x3a29bdb012a9ef1c9470a9e6494a68af42f4ab2756c239e0e7cd8563088e3eed
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.255] [2/15 Headers] Waiting for Consensus Layer...
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.255] [2/15 Headers] Handling new payload      height=15558343 hash=0xe29c12529b281c1a1e7f251a3a0f3ee4e22451f4e1562ffa706349a274ec54f4
6月 25 00:44:40 zlaxdata erigon[1138816]: [INFO] [06-25|00:44:40.257] [2/15 Headers] Waiting for Consensus Layer...

Is this correct?

**Comment by zlxadata** [comment]
And then...

6月 25 01:08:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:08:27.785] [txpool] stat                            pending=10000 baseFee=25149 queued=30000 alloc=2.7GB sys=4.6GB
6月 25 01:09:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:09:27.773] [txpool] stat                            pending=10000 baseFee=25154 queued=30000 alloc=2.9GB sys=4.6GB
6月 25 01:10:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:10:27.767] [p2p] GoodPeers                          eth68=28 eth67=25 eth66=2
6月 25 01:10:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:10:27.785] [txpool] stat                            pending=10000 baseFee=25157 queued=30000 alloc=2.6GB sys=4.6GB
6月 25 01:11:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:11:27.773] [txpool] stat                            pending=10000 baseFee=25160 queued=30000 alloc=2.9GB sys=4.6GB
6月 25 01:12:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:12:27.767] [p2p] GoodPeers                          eth67=26 eth68=28 eth66=2
6月 25 01:12:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:12:27.784] [txpool] stat                            pending=10000 baseFee=25176 queued=30000 alloc=2.6GB sys=4.6GB
6月 25 01:13:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:13:27.772] [txpool] stat                            pending=10000 baseFee=25188 queued=30000 alloc=2.9GB sys=4.6GB
6月 25 01:14:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:14:27.768] [p2p] GoodPeers                          eth68=28 eth67=25 eth66=2
6月 25 01:14:27 zlaxdata erigon[1138816]: [INFO] [06-25|01:14:27.783] [txpool] stat                            pending=10000 baseFee=25199 queued=30000 alloc=2.6GB sys=4.6GB

**Comment by zlxadata** [comment]
Now：

**Comment by zlxadata** [comment]
Now：
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.612] [2/15 Headers] Handling new payload      height=15665736 hash=0x0c030af9089215cc02b720b59d8b4cf05be683931e22bd69f6dac8ac0935721f
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.613] [2/15 Headers] Waiting for Consensus Layer...
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.616] [2/15 Headers] Handling new payload      height=15665737 hash=0x0524d828dfb24d88ab3d936c27240dcfdd5a005d5533395b7ca29abf35383da2
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.617] [2/15 Headers] Waiting for Consensus Layer...
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.837] [2/15 Headers] Handling new payload      height=15665738 hash=0x049839b9065041f2d32f7c4932a81a16d9b77a5dc17f11162d81796dcd25e86b
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.838] Timings (slower than 50ms)               Headers=220ms
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.838] [2/15 Headers] Waiting for Consensus Layer...
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.844] [2/15 Headers] Handling new payload      height=15665739 hash=0xbf7531d4ae1448edfae829c1a5d5109060cf5a2dac42ce14c0ddb184bf2d50c5
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.846] [2/15 Headers] Waiting for Consensus Layer...
6月 25 09:26:59 zlaxdata erigon[1138816]: [INFO] [06-25|09:26:59.863] [2/15 Headers] Waiting for Consensus Layer...

**Comment by KiKiiKiK** [comment]
Hi. Did your issue get solved? @zlxadata 
I am having the similar problem after staged sync finished.
