### ISSUE TITLE
Erigon support balances query via graphQL

### ISSUE THREAD

**Issue by Sreeram1993** [ledgerwatch/erigon#7794]
As part of graphQL support with trigon client, I did see getblockdetails and getchainid but does it support the get balances query ? If yes can someone share the documentation of the same.

**Comment by AskAlexSharov** [comment]
cmd/rpcdaemon/commands/graphql_api.go:
```
type GraphQLAPI interface {
	GetBlockDetails(ctx context.Context, number rpc.BlockNumber) (map[string]interface{}, error)
	GetChainID(ctx context.Context) (*big.Int, error)
}
```
seems graphql doesn't have much

**Comment by Sreeram1993** [comment]
> cmd/rpcdaemon/commands/graphql_api.go:
> 
> ```
> type GraphQLAPI interface {
> 	GetBlockDetails(ctx context.Context, number rpc.BlockNumber) (map[string]interface{}, error)
> 	GetChainID(ctx context.Context) (*big.Int, error)
> }
> ```
> 
> seems graphql doesn't have much

Exactly. I wanted to see if I could get balances via graphql. Looks like I will have to go with the get balance rpm call itself.

**Comment by SLoeuillet** [comment]
Hello
Sorry, I did only implement those 2 basic GraphQL endpoints
Does geth implement the endpoint you need ?
