### ISSUE TITLE
ETH mainnet : trace_block method is no longer returning "reward" trace

### ISSUE THREAD

**Issue by qn-srikanth** [ledgerwatch/erigon#7827]
#### System information

Erigon version: [erigon/2.47.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.47.0)

OS & Version: Linux : 41-Ubuntu

Consensus Layer: Lighthouse/v4.2.0-c547a11

Chain/Network: ETH mainnet

---
#### Expected behaviour

```
curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x10C3960"],"id":1,"jsonrpc":"2.0"}'  | jq '.result[-1].type'
```

```
"type": "reward"
```

---

#### Actual behaviour

```
curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x10C3960"],"id":1,"jsonrpc":"2.0"}'  | jq '.result[-1].type'
```

```
"type": "call"

```

---

#### Steps to reproduce the behavior

```
curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x10C3960"],"id":1,"jsonrpc":"2.0"}'
```

"reward" type trace is missing. Running on an older version (Erigon/2.42.0) gives  the last trace of type "reward".

![image](https://github.com/ledgerwatch/erigon/assets/107944932/8e884f99-e5cc-41bb-8b2f-859503ad5b15)

**Comment by harshsingh-cs** [comment]
@qn-srikanth  did you manage to fix the issue. I see the PR which had the fix is closed and there is signs of this fix in devel also

**Comment by qn-srikanth** [comment]
@harshsingh-cs  Since rewards are now coming from the Beacon chain, this seems like the expected behavior.
