### ISSUE TITLE
Increase default  --db.size.limit for Polygon to something more then 3TB

### ISSUE THREAD

**Issue by zekchan** [ledgerwatch/erigon#7829]
# Rationale
Size of full synced Polygon full node data folder
```
$ du -sh *
60G	bor
5.8T	chaindata
4.0K	jwt.hex
0	LOCK
376M	logs
4.0K	nodekey
179M	nodes
690G	snapshots
12K	temp
```
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by AskAlexSharov** [comment]
I don't really want to make DB flags depend on network name. 
because it making circular dependency: we storing chainConfig inside DB. it means "to open db need know chain name, to get chain name need to read chainConfig from db".

**Comment by skolem-dan** [comment]
I'm a little confused why this would require reading from the DB to figure out. Before the DB size limit was slashed, `./erigon --chain=bor-mainnet --bor.heimdall=...` was the minimum set of flags needed to sync a Polygon archive node from scratch. I certainly don't know Erigon's internals very well, but that sure looks to me like the chain name is readily available before opening the DB. The same goes for anyone using `--config` to specify a non-default chain in a file.

Am I missing something here? I can understand the reluctance to have defaults for opening the database vary depending on what chain is being used, but without doing so, #7478 is a breaking change for some users (even if it does also resolve a different issue for others) and this sounds like the only way to fix that regression.

**Comment by AskAlexSharov** [comment]
@skolem-dan 
1. --chain parameter is not required as i remember (we have many binaries: txpool/integration/erigon/rpcdaemon/... all of them must require --chain) 
3. it must be prohibited to change this flag after first start - means need store it in db and re-check after db-opening. 
3. about https://github.com/ledgerwatch/erigon/pull/7478 : I don't really remember why we have db limit < 8tb now. we had some bugs related to it (on some systems with some amount of RAM/swap), but i forgot. I think now - that it was related to some Erigon's bug (not to OS limitations).  Also maybe after https://github.com/ledgerwatch/erigon/pull/7798 we can increase default for all, maybe not. 
4. somehow need to handle case: user already has 4kb pagesize db - trying to open db with > 8tb limit will cause error. and maybe other similar cases. 
5. need think about `--chain=polygon --prune=hrtc` - maybe don't need any special logic, maybe need.
