### ISSUE TITLE
Gas Value is wrong in `debug_trace*` method for blocks in archive

### ISSUE THREAD

**Issue by ella-quicknode** [ledgerwatch/erigon#7831]
#### System information

Erigon version: `erigon version 2.47.0-stable-5536d645`

OS & Version: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1035-oracle x86_64)

Chain/Network:  Eth-Mainnet archive node 

#### Expected behaviour

To retrieve correct data in debug trace methods. 

#### Actual behaviour

The gas value from `debug_trace*` methods are wrong. 

#### Example 1

Run this below cURL, please replace with a valid URL.  

```
curl -X POST http://localhost -H 'Content-Type: application/json' -d '{"method":"debug_traceBlockByNumber","params":["0x107490F", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}' | jq '.result[0].result.gas'
```

You will see an output `"0x250bf"` which is wrong.  The correct gas value is `0x2aa2f`. 

Associated transaction on ETH scan [is here](https://etherscan.io/tx/0x04aea2f53dee77b533d015311246f472674c8f501f4674c08dd832a821686712)

#### Example 2

Another example cURL for getting `traceTransaction`. Please replace with a valid URL.  

```
curl -X POST http://localhost -H 'Content-Type: application/json' -d '{"method":"debug_traceTransaction","params":["0x3d7651e7556cd62950ee34fc5871bba468c3f04e547767da31db123d4ed1007c", {"tracer": "callTracer"}], "id":1,"jsonrpc":"2.0"}'
```

You will get a wrong gas value `0x370ff`, the correct value is: `0x3eb40` 

Associated transaction on ETH scan [is here](https://etherscan.io/tx/0x3d7651e7556cd62950ee34fc5871bba468c3f04e547767da31db123d4ed1007c).

**Comment by jiOnederfull** [comment]
How's going on this issue?

**Comment by jiOnederfull** [comment]
Yeah, I've also cheked that query below produces different results as shown in the picture. I'm curious if ledgerwatch is aware of it and working on fixing it.

```sh
curl {endpoint} \
 -X POST \
 -H "Content-Type: application/json" \
 --data '{"method":"debug_traceBlockByNumber",
       "params":[
           "0xdf23e", 
           {"tracer": "callTracer"}
          ],
        "id":1,
        "jsonrpc":"2.0"
       }'
```

![image](https://github.com/ledgerwatch/erigon/assets/48719289/1a863601-fbe9-4ee8-afb0-5d2a392c7da2)
![image](https://github.com/ledgerwatch/erigon/assets/48719289/99078a94-bed0-46b6-a8e0-2623cb26da8a)

**Comment by qk-santi** [comment]
Keeping it open

**Comment by crazyokey1990** [comment]
same problem

**Comment by nateless** [comment]
Any updates on this task?
