### ISSUE TITLE
erigon import does not work

### ISSUE THREAD

**Issue by zjuujz8021** [ledgerwatch/erigon#7833]
I try to sync by importing block files. The blockchain files are exported by the Geth full node. **BUT** the import cmd does not work at all. Erigon outputs that a beacon chain is needed. Actually, I had started the beacon by --internalcl. How can I start the importing process?

#### System information
Erigon version: v2.46.0
OS & Version: Ubuntu 20.04 LTS
Commit hash: 
6755f7e1fdb0aaa59ff02f5a871492d6c906b06c

Erigon Command (with flags/config):
./build/bin/erigon import  file-path
./build/bin/erigon --internalcl import file-path
BOTH do not work.

Concensus Layer:
N.A.
Concensus Layer Command (with flags/config):
N.A.
Chain/Network: 
mainnet

#### Expected behaviour
import and sync with the blockchain file 

#### Actual behaviour
**It does not work, with repeated warning output:**
INFO[07-01|04:29:24.629] [2/15 Headers] Waiting for Consensus Layer...
WARN[07-01|04:29:24.629] [2/15 Headers] Nil beacon request. Should only happen in tests

**Comment by AskAlexSharov** [comment]
I think we don't have "erigon import" command

**Comment by zjuujz8021** [comment]
> I think we don't have "erigon import" command

The cmd is in defined in /turbo/app/import_cmd.go, line 34

**Comment by AskAlexSharov** [comment]
oh, never used myself

**Comment by AskAlexSharov** [comment]
@Giulio2002 hi, is it easy to add  --internalcl support in "erigon import"?
