### ISSUE TITLE
Polygon: memory leak

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#7864]
https://discord.com/channels/687972960811745322/738982866670714901/1126584109452513300

![mem](https://github.com/ledgerwatch/erigon/assets/46885206/ddf23677-3e98-4571-b8f7-fddb0c7b5cce)

**Comment by AlexeyAkhunov** [comment]
Fix: https://github.com/ledgerwatch/erigon/pull/7868

**Comment by MrFreezeDZ** [comment]
Could this be the problem why our Kubernetes restarts the container erigon runs in (16GB RAM) because of OutOfMemory every time when syncing from a previous downloaded snapshot?

when I grep:
`grep "Starting Erigon on Bor Mainnet"  /data/logs/erigon.log -B 5`

I get a lot of the following output, which does log nothing suspicious but you can see the restart:

> 
    --
    [INFO] [07-13|06:20:57.351] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.0GB sys=12.1GB
    [INFO] [07-13|06:21:12.994] [5/15 Bodies] Downloading block bodies   block_num=43955430 delivery/sec=9.5MB wasted/sec=0B remaining=1061546 delivered=961826 cache=3.5MB alloc=7.8GB sys=12.1GB
    [INFO] [07-13|06:21:32.995] [5/15 Bodies] Downloading block bodies   block_num=43960591 delivery/sec=10.0MB wasted/sec=0B remaining=1056385 delivered=966899 cache=2.4MB alloc=8.8GB sys=12.1GB
    [INFO] [07-13|06:21:41.768] logging to file system                   log dir=/data/logs file prefix=erigon log level=info json=false
    [INFO] [07-13|06:21:41.769] Build info                               git_branch=heads/v2.48.0 git_tag=v2.48.0-dirty git_commit=084acc1af2e853ee4a57dbdd6920b6a1e58ef85c
    [INFO] [07-13|06:21:41.769] Starting Erigon on Bor Mainnet... 
    --
    [INFO] [07-13|07:50:13.280] [5/15 Bodies] Downloading block bodies   block_num=43978898 delivery/sec=15.8MB wasted/sec=0B remaining=1040392 delivered=933424 cache=2.4MB alloc=7.2GB sys=12.1GB
    [INFO] [07-13|07:50:16.313] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.5GB sys=12.1GB
    [INFO] [07-13|07:50:33.280] [5/15 Bodies] Downloading block bodies   block_num=43984797 delivery/sec=16.1MB wasted/sec=0B remaining=1034493 delivered=939608 cache=20.0MB alloc=8.9GB sys=12.1GB
    [INFO] [07-13|07:50:38.147] logging to file system                   log dir=/data/logs file prefix=erigon log level=info json=false
    [INFO] [07-13|07:50:38.148] Build info                               git_branch=heads/v2.48.0 git_tag=v2.48.0-dirty git_commit=084acc1af2e853ee4a57dbdd6920b6a1e58ef85c
    [INFO] [07-13|07:50:38.148] Starting Erigon on Bor Mainnet... 




Could one of the following erigon parameters help with this? I got them by `erigon --help | grep mem`
>
    --clique.snapshots value                                 number of recent vote snapshots to keep in memory (default: 1024)
    --clique.signatures value                                number of recent block signatures to keep in memory (default: 16384)

**Comment by AskAlexSharov** [comment]
Yes, this and also https://github.com/ledgerwatch/erigon/issues/6646
