### ISSUE TITLE
Ericon upgrade to V0.0.8 to report an error,mdbx_map_full: Environment Mapsize Limit Reache d

### ISSUE THREAD

**Issue by hanzhenlong1314** [ledgerwatch/erigon#7865]
Apply Migration name = TXS_V3
Page_alloc_slowpath: 10501 Unable Alloc 12 Pages, Flags 0x2, ErrCode -30792
[EROR] [07-10 | 09: 39: 28.438] Ericon Startup err = "migrator.apply.up: txs_v3, mdbx_txn_commit_ex: mdbx_map_full: Environment Mapsize Limit Reache d "
migrator.Apply.uup: txs_v3, mdbx_txn_commit_ex: mdbx_map_full: environment mapsize

**Comment by AskAlexSharov** [comment]
—db.size.limit

**Comment by hanzhenlong1314** [comment]
command=/root/erigon/build/bin/erigon --chain=bor-mainnet --bor.heimdall=https://heimdall-api.polygon.technology --datadir=/root/erigon/data/ --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=*
