### ISSUE TITLE
The interface cannot be accessed after upgrading to v0.0.8.

### ISSUE THREAD

**Issue by hanzhenlong1314** [ledgerwatch/erigon#7869]
![image](https://github.com/ledgerwatch/erigon/assets/25896081/3524a424-a72b-4515-b6db-72b6325db2d6)
![image](https://github.com/ledgerwatch/erigon/assets/25896081/f93b807a-2c31-4a1b-9a85-64130f183088)

**Comment by AskAlexSharov** [comment]
what is "interface"?

**Comment by hanzhenlong1314** [comment]
> what is "interface"?

For example curl -X POST http://127.0.0.1:8838 --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",true],"id" :73}' -H "Content-Type: application/json" cannot be accessed

**Comment by hanzhenlong1314** [comment]
@AskAlexSharov Is this log normal?

**Comment by AskAlexSharov** [comment]
show cli flags
logs normal

**Comment by hanzhenlong1314** [comment]
> show cli flags logs normal
We have fixed it, it is our own problem, thanks for the support, this problem can be closed
