### ISSUE TITLE
There is a memory leak in the rpchelper function

### ISSUE THREAD

**Issue by sundafa** [ledgerwatch/erigon#7870]
#### System information

Erigon version: v2.48.0
OS & Version: Linux
Commit hash: 
Erigon Command (with flags/config): `${nodeServiceDir}/bin/erigon --datadir=${nodeServiceDir}/erigon --chain=mainnet --prune=hrtc --authrpc.jwtsecret=${nodeServiceDir}/erigon/jwt.hex --rpc.gascap=600000000 --rpc.evmtimeout=30s --rpc.batch.limit=100 --rpc.returndata.limit=104857600 --http=true --http.api 'eth,net,web3,debug,trace,txpool' --http.addr ${listeningAddr} --http.corsdomain '*' --http.vhosts '*' --ws --authrpc.addr localhost --port 31300 --http.port 31301 --private.api.addr='' --authrpc.port=31303 --torrent.port=31304 --p2p.allowed-ports 31306,31318`

Concensus Layer: lighthouse
Concensus Layer Command (with flags/config): `${nodeServiceDir}/bin/lighthouse bn -d ${nodeServiceDir}/lighthouse --network mainnet --execution-endpoint http://127.0.0.1:31303 --execution-jwt ${nodeServiceDir}/erigon/jwt.hex --checkpoint-sync-url=https://sync-mainnet.beaconcha.in --port 31309 --http --http-port 31307`

Chain/Network: mainnet

#### Actual behaviour
The memory of erigon2.48 version grows very fast. After analysis, rpchelper.distributeLog continues to increase memory and does not release it.
pprof command execution steps
```
~/t1/erigon # go tool pprof http://localhost:6060/debug/pprof/heap
Fetching profile over HTTP from http://localhost:6060/debug/pprof/heap
Saved profile in /root/pprof/pprof.erigon.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz
File: erigon
Build ID: 0bdbb52af0840c55a0c2b432c5589ae097907a33
Type: inuse_space
Time: Jul 11, 2023 at 1:53am (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) list
command list requires an argument
(pprof) top
Showing nodes accounting for 33782.72MB, 96.92% of 34857.50MB total
Dropped 857 nodes (cum <= 174.29MB)
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
30625.55MB 87.86% 87.86% 30625.55MB 87.86%  github.com/ledgerwatch/erigon/turbo/rpchelper.(*LogsFilterAggregator).distributeLog.func1
 1683.76MB  4.83% 92.69%  1683.76MB  4.83%  github.com/ledgerwatch/erigon-lib/compress.newPatternTable (inline)
  928.07MB  2.66% 95.35%   928.07MB  2.66%  github.com/ledgerwatch/erigon/turbo/rpchelper.(*Filters).AddLogs.func1
  278.01MB   0.8% 96.15%  1961.26MB  5.63%  github.com/ledgerwatch/erigon-lib/compress.buildCondensedPatternTable
  261.90MB  0.75% 96.90%   261.90MB  0.75%  bytes.growSlice
    3.19MB 0.0091% 96.91%   214.35MB  0.61%  encoding/json.Marshal
       1MB 0.0029% 96.91%  2034.56MB  5.84%  github.com/ledgerwatch/erigon-lib/compress.NewDecompressor
    0.70MB 0.002% 96.92%   928.77MB  2.66%  github.com/ledgerwatch/erigon/turbo/rpchelper.(*SyncMap[...]).Do
    0.56MB 0.0016% 96.92%   456.28MB  1.31%  github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg
         0     0% 96.92%   215.72MB  0.62%  bytes.(*Buffer).Write
(pprof) list distributeLog.func1
Total: 34.04GB
ROUTINE ======================== github.com/ledgerwatch/erigon/turbo/rpchelper.(*LogsFilterAggregator).distributeLog.func1 in github.com/ledgerwatch/erigon/turbo/rpchelper/logsfilter.go
   29.91GB    29.91GB (flat, cum) 87.86% of Total
         .          .    131:				return nil
         .          .    132:			}
         .          .    133:		}
         .          .    134:		var topics []libcommon.Hash
         .          .    135:		for _, topic := range eventLog.Topics {
   12.60GB    12.60GB    136:			topics = append(topics, gointerfaces.ConvertH256ToHash(topic))
         .          .    137:		}
         .          .    138:		if filter.allTopics == 0 {
         .          .    139:			if !a.chooseTopics(filter, topics) {
         .          .    140:				return nil
         .          .    141:			}
         .          .    142:		}
   17.30GB    17.30GB    143:		lg := &types2.Log{
         .          .    144:			Address:     gointerfaces.ConvertH160toAddress(eventLog.Address),
         .          .    145:			Topics:      topics,
         .          .    146:			Data:        eventLog.Data,
         .          .    147:			BlockNumber: eventLog.BlockNumber,
         .          .    148:			TxHash:      gointerfaces.ConvertH256ToHash(eventLog.TransactionHash),
(pprof)
```

#### Backtrace

````
[backtrace]
````
![mem75g](https://github.com/ledgerwatch/erigon/assets/24621599/59f91e24-138e-4fae-b2fa-01110d6efc92)

**Comment by sundafa** [comment]
file: https://github.com/ledgerwatch/erigon/blob/06315065c2a29d60f4dfea80aa22266533a33ed7/turbo/rpchelper/logsfilter.go#L126

**Comment by AlexeyAkhunov** [comment]
Do you use `eth_newFilter` RPC call a lot perhaps, without cleaning them up. It looks from the profile like there are lots of active filters created, and they are not polled, so Erigon keeps 128 or 256 logs for each active filters, which creates apparent memory leak. Creating filters is considered therefore a "dangerous" API, for this exact reason and should either be avoided or used with extra care

**Comment by sundafa** [comment]
thank you for your reply
I will pay attention to this kind of problem in the future
