### ISSUE TITLE
Documenting Configuration File Flags

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#7875]
Currently, it is very difficult to discover new features and its configuration flags. Unless I'm missing something, the only way of doing so is diving into codebase and try to enable features via its flags and see they can run in stable release.

Example:
1. GraphQL
2. Becaon APIs
3. RPC Modules
4. etc.

I'm willing to participate in doing it with a little bit of guiding :)

**Comment by AskAlexSharov** [comment]
@Texnomic maybe just in “erigon —help” each flag must have label like “[since: v2.48.0]”?
