### ISSUE TITLE
Bug with eth_newFilter and eth_getFilterLogs

### ISSUE THREAD

**Issue by wuzhong-zhu** [ledgerwatch/erigon#7903]
#### System information

Erigon version: `erigon/2.48.0/linux-amd64/go1.20.5` 

OS & Version:Linux

Chain/Network: Polygon

#### Expected behaviour
`eth_getFilterLogs` re-executes the block and collects log information. Using [this transaction](https://polygonscan.com/tx/0xc2d7dac2549545c9179fa019481614d5fd4742dd33256d4a5bae069112941d6c#eventlog) as an example.

Against a regular Geth node, running the following command:
```
{
  "jsonrpc": "2.0",
  "method": "eth_newFilter",
  "params": [
    {
      "topics": [
        "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
      ],
      "fromBlock": "0x2B13F9E",
      "toBlock": "0x2B13F9E",
      "address": [
        "0xF25212E676D1F7F89Cd72fFEe66158f541246445"
      ]
    }
  ],
  "id": 31
}
```
and 
```
{
  "jsonrpc": "2.0",
  "method": "eth_getFilterLogs",
  "params": [
    "0xFILTER_ID_HERE"
  ],
  "id": 31
}
```
returns the following result:
`{"jsonrpc":"2.0","id":31,"result":[{"address":"0xf25212e676d1f7f89cd72ffee66158f541246445","topics":["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0x00000000000000000000000025e6bc33060c1fee8e08532d0c1c32c4cbf10e2c","0x00000000000000000000000059e242d352ae13166b4987ae5c990c232f7f7cd6"],"data":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","blockNumber":"0x2b13f9e","transactionHash":"0xc2d7dac2549545c9179fa019481614d5fd4742dd33256d4a5bae069112941d6c","transactionIndex":"0x27","blockHash":"0xe296a39e37071bbcf0fc925d9b1190e70d8a5f959156b238ed3b0596f702f147","logIndex":"0x93","removed":false}]}`

#### Actual behaviour
`eth_getFilterLogs` always returns an empty array as a result.
```
{
    "jsonrpc": "2.0",
    "id": 31,
    "result": []
}
```

#### Backtrace
Calling eth_getLogs against the same node returns accurate result
````
{
  "jsonrpc": "2.0",
  "method": "eth_getLogs",
  "params": [
    {
      "topics": [
        "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
      ],
      "fromBlock": "0x2B13F9E",
      "toBlock": "0x2B13F9E",
      "address": [
        "0xF25212E676D1F7F89Cd72fFEe66158f541246445"
      ]
    }
  ],
  "id": 31
}
````
Result:
```

{
    "jsonrpc": "2.0",
    "id": 31,
    "result": [
        {
            "address": "0xf25212e676d1f7f89cd72ffee66158f541246445",
            "topics": [
                "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
                "0x00000000000000000000000025e6bc33060c1fee8e08532d0c1c32c4cbf10e2c",
                "0x00000000000000000000000059e242d352ae13166b4987ae5c990c232f7f7cd6"
            ],
            "data": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            "blockNumber": "0x2b13f9e",
            "transactionHash": "0xc2d7dac2549545c9179fa019481614d5fd4742dd33256d4a5bae069112941d6c",
            "transactionIndex": "0x27",
            "blockHash": "0xe296a39e37071bbcf0fc925d9b1190e70d8a5f959156b238ed3b0596f702f147",
            "logIndex": "0x93",
            "removed": false
        }
    ]
}
```
So it shouldn't be an issue with the state availability.

Any suggestion is appreciated. Thanks!

**Comment by Termina1** [comment]
I think the problem is not state availability, the problem is that erigon does not respect filter requests semantics. For example, let's say we have request:
```
{
  "method": "eth_newFilter",
  "params": [{
    "address":["0xdAC17F958D2ee523a2206206994597C13D831ec7"],
    "fromBlock": "0x11483b9",
    "toBlock": "0x11483ba"
  }],
  "id": "100",
  "jsonrpc":"2.0"
}
```

So, basically we create a useless filter, because it should update.

Expected behaviour that eth_getFilterLogs would return all logs from block 0x11483b9 to 0x11483ba, while eth_getFilterChanges should return empty array indefinitely. This behaviour can be observed with Nethermind and SaaS like infura.

However, erigon (v2.48.1) just ignores from/to block parameters. It just returns all logs from subsequent blocks (after filter was created), moreover the semantics of eth_getFilterLogs is the same as eth_getFilterChanges, so those methods for erigon are identical.

**Comment by Termina1** [comment]
One more thing I would like to add, for me it looks like erigon (and other clients) actually collect logs into some buffer, which means if there are a lot of different filters the memory starts to leak very fast. However, it should be trivial to reimplement eth_getFilterLogs/eth_getFilterChangs using eth_getLogs. We just need to store filter somewhere + track last seen block for filter, and then just run eth_getLogs.

It should reduce memory footprint significantly with tradeoff of CPU, however from my experience I don't see a lot of use cases for eth_getFilterLogs where latency is critical.
