### ISSUE TITLE
How to get the historical proof?

### ISSUE THREAD

**Issue by lurais** [ledgerwatch/erigon#7926]
Hello, I want to use the erigon as a rpc server to get the computing proofs to prove the historical state of some accounts, Is that avaliable in erigon ? If it is possible , what should I do?

**Comment by AskAlexSharov** [comment]
no. we support eth_getProof - only for last 1K blocks currently.

**Comment by lurais** [comment]
So why is it not provided? Have you tested it before? If the acquisition of all historical blocks is supported, how much storage space will be increased if you do not get the history by this way of fallback to the assigned block?

**Comment by AskAlexSharov** [comment]
we don't store any historical proofs - and never did. so, I don't know how much space it may take. 
we storing only history of accounts/storage.
Latests MerkleTrie size is ~80gb

**Comment by lurais** [comment]
Hello , the MerkleTrie is the db current state and intermediate hashes? As I know, erigon do not store the trie but only the intermediate hashes and the current state.

**Comment by AskAlexSharov** [comment]
Yes
