### ISSUE TITLE
initial sync progress gone after reboot when sync is not finished

### ISSUE THREAD

**Issue by MrFreezeDZ** [ledgerwatch/erigon#7927]
#### System information

Erigon version: `erigon version 2.48.0-stable-084acc1a`

OS & Version: `Alpine Linux v3.17` (Kubernetes (GKE) running image https://hub.docker.com/r/thorax/erigon) 
96GB RAM
4 CPUs
10 TB SSD (in Kubernetes so the IOPS is not optimal I guess)

Commit hash: `git_branch=heads/v2.48.0 git_tag=v2.48.0-dirty git_commit=084acc1af2e853ee4a57dbdd6920b6a1e58ef85c`

Erigon Command (with flags/config):
```
erigon --chain=bor-mainnet --datadir=/data/ --bor.heimdall=http://heimdallrest --authrpc.vhosts=heimdallrest --authrpc.jwtsecret=/secret/jwt.hex --db.size.limit=8TB --maxpeers=500 --torrent.download.rate=300mb --h
ttp --ws --http.api=eth,admin,debug,net,trace,web3,erigon,txpool --authrpc.addr=0.0.0.0
```

Concensus Layer:
Heimdall

Concensus Layer Command (with flags/config):
`heimdalld start --home=/heimdall-home`

Chain/Network: 
Bor-Mainnet

#### Expected behaviour
At least when a sync stage X/15 reports DONE, the sync progress is restarted from the last finished stage after a reboot.

#### Actual behaviour
After the reboot in sync stage 12/15 and after over 200 hours of sync time Erigon begins syncing again from the previous downloaded snapshot from 23th of may 2023.

#### Steps to reproduce the behaviour
Reboot Erigon after one of the first 11 finished sync stages. 

#### Backtrace
Just the logs where you can see the reboot and then beginning the sync again from the start.
````
[INFO] [07-24|13:14:08.225] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=9.6GB sys=17.3GB
[INFO] [07-24|13:14:11.087] [12/15 StorageHistoryIndex] ETL [2/2] Loading into=StorageHistory current_prefix=2ab0e9e4
[INFO] [07-24|13:14:34.063] [12/15 StorageHistoryIndex] ETL [2/2] Loading into=StorageHistory current_prefix=2ab0e9e4
[INFO] [07-24|13:15:04.062] [12/15 StorageHistoryIndex] ETL [2/2] Loading into=StorageHistory current_prefix=2ab0e9e4
[INFO] [07-24|13:15:08.251] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=12.6GB sys=17.3GB
[INFO] [07-24|13:15:34.062] [12/15 StorageHistoryIndex] ETL [2/2] Loading into=StorageHistory current_prefix=2ab0e9e4
[INFO] [07-24|13:15:36.979] Got interrupt, shutting down... 
[INFO] [07-24|13:15:36.988] Exiting... 
[INFO] [07-24|13:15:36.988] Exiting Engine... 
[INFO] [07-24|13:15:36.992] RPC server shutting down 
[INFO] [07-24|13:15:36.992] RPC server shutting down 
[INFO] [07-24|13:15:36.996] RPC server shutting down 
[INFO] [07-24|13:15:37.024] Engine HTTP endpoint close               url=[::]:8551
[INFO] [07-24|13:15:37.024] HTTP endpoint closed                     url=127.0.0.1:8545
[INFO] [07-24|13:22:43.702] logging to file system                   log dir=/data/logs file prefix=erigon log level=info json=false
[INFO] [07-24|13:22:43.710] Build info                               git_branch=heads/v2.48.0 git_tag=v2.48.0-dirty git_commit=084acc1af2e853ee4a57dbdd6920b6a1e58ef85c
[INFO] [07-24|13:22:43.710] Starting Erigon on Bor Mainnet... 
[INFO] [07-24|13:22:43.716] Maximum peer count                       ETH=500 total=500
[INFO] [07-24|13:22:43.716] starting HTTP APIs                       APIs=eth,admin,debug,net,trace,web3,erigon,txpool
[INFO] [07-24|13:22:43.716] torrent verbosity                        level=WRN
[INFO] [07-24|13:22:45.819] Set global gas cap                       cap=50000000
[INFO] [07-24|13:22:45.821] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=300mb upload.rate=4mb
[INFO] [07-24|13:22:45.821] Opening Database                         label=chaindata path=/data/chaindata
[INFO] [07-24|13:23:06.797] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Gl
acier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141
b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
[INFO] [07-24|13:23:14.653] Initialising Ethereum protocol           network=137
[INFO] [07-24|13:23:25.708] Starting private RPC server              on=127.0.0.1:9090
[INFO] [07-24|13:23:25.708] new subscription to logs established 
[INFO] [07-24|13:23:25.708] rpc filters: subscribing to Erigon events 
[INFO] [07-24|13:23:25.709] new subscription to newHeaders established 
[INFO] [07-24|13:23:25.709] Reading JWT secret                       path=/secret/jwt.hex
[INFO] [07-24|13:23:25.709] New txs subscriber joined 
[INFO] [07-24|13:23:25.709] HTTP endpoint opened for Engine API      url=[::]:8551 ws=true ws.compression=true
[INFO] [07-24|13:23:25.710] HTTP endpoint opened                     url=127.0.0.1:8545 ws=true ws.compression=true grpc=false
[INFO] [07-24|13:23:25.731] [1/15 Snapshots] Fetching torrent files metadata 
[INFO] [07-24|13:23:25.755] Started P2P networking                   version=67 self=enode://5c7e7f86397bdd12efc18dddd7b2154a0b93c971ede780f587b3e70f3a196bae42a99cb859e4518296e24a6663a41a26c79311128e8ab2f497567abc5da7a29b@127.0.0.1:0 
name=erigon/v2.48.0-stable-084acc1a/linux-amd64/go1.20.5
[INFO] [07-24|13:23:25.764] Started P2P networking                   version=68 self=enode://5c7e7f86397bdd12efc18dddd7b2154a0b93c971ede780f587b3e70f3a196bae42a99cb859e4518296e24a6663a41a26c79311128e8ab2f497567abc5da7a29b@127.0.0.1:0 
name=erigon/v2.48.0-stable-084acc1a/linux-amd64/go1.20.5
[INFO] [07-24|13:23:34.858] [snapshots] Blocks Stat                  blocks=42967k indices=42967k alloc=3.2GB sys=6.1GB
[INFO] [07-24|13:23:34.858] [2/15 Headers] Waiting for headers...    from=43057508
[INFO] [07-24|13:23:35.181] Span with given block number is not loaded fetching span=6728
[INFO] [07-24|13:23:54.859] [2/15 Headers] Wrote block headers       number=43058472 blk/second=48.200 alloc=3.5GB sys=6.1GB
````

**Comment by MrFreezeDZ** [comment]
Could this be something similar to https://github.com/ledgerwatch/erigon/discussions/7756 ?

**Comment by wtdcode** [comment]
Same here, quite frustrating

**Comment by AskAlexSharov** [comment]
It's trade-off between: "show only fully-indexed data" VS "commit partial progress"
at initial-sync we choose commit partial data (non-indexed data are visible by RPC), but then we switch to show only consistent data (indexed, etc...) - commit all stages at once. 

current logic is here: https://github.com/ledgerwatch/erigon/blob/521f0df55b6a44ed322b417cc6cf93b92060a947/turbo/stages/stageloop.go#L112 - if you see better idea/logic - feel free to advise

**Comment by wtdcode** [comment]
> It's trade-off between: "show only fully-indexed data" VS "commit partial progress" at initial-sync we choose commit partial data (non-indexed data are visible by RPC), but then we switch to show only consistent data (indexed, etc...) - commit all stages at once.
> 
> current logic is here:
> 
> https://github.com/ledgerwatch/erigon/blob/521f0df55b6a44ed322b417cc6cf93b92060a947/turbo/stages/stageloop.go#L111
> 
> - if you see better idea/logic - feel free to advise

I fail to understand. If "commit partial progress" is implemented during the initial sync, why do I lost my progress?

**Comment by AskAlexSharov** [comment]
because you are not at "initial sync" - you "starting from backup". likely in this case also need switch to "commit partial progress" mode - but I don't see "good heuristic" how Erigon can auto-detect it.

**Comment by AskAlexSharov** [comment]
in the past we used "is first sync cycle" heuristic - but it confused other users - they saw partial data after erigon restart.

**Comment by wtdcode** [comment]
Thanks for reply. I tried to switch to stable (v2.48.1) and my progress is back. Really weird though.

**Comment by MrFreezeDZ** [comment]
> - if you see better idea/logic - feel free to advise

The first idea I have is just to use a flag so the erigon command could be used to either use "commit partial progress" or not. This way we could decide which commit strategy is used and it would overrule any logic. So we could choose partial commits during our inital sync phase and then just remove the parameter.

**Comment by AskAlexSharov** [comment]
@MrFreezeDZ actually i'm agree with your advise. Let's do this way:
- adding flag - for manual problem-solving: https://github.com/ledgerwatch/erigon/pull/8090 
- because I don't see good solution myself: next week I will deeper dive in possible solutions/limitations with other team-mates.

**Comment by wtdcode** [comment]
> @MrFreezeDZ actually i'm agree with your advise. Let's do this way:
> 
> * adding flag - for manual problem-solving: [add flag --force.partial.commit: to workaround problem "start from backup takes long time and can't save partial progress" #8090](https://github.com/ledgerwatch/erigon/pull/8090)
> * because I don't see good solution myself: next week I will deeper dive in possible solutions/limitations with other team-mates.
> 
> You can cherry-pick #8090 on top of v2.48.1 - we don't plan new release this week.
> 
> Thank you.

Hey @AskAlexSharov, may I know the current status of this feature? Does erigon auto detect the correct behavior now?

**Comment by AskAlexSharov** [comment]
We added `--sync.loop.block.limit` flag for this case.  
(maybe `--sync.loop.block.limit` flag not supported by `--internalcl` mode)

**Comment by wtdcode** [comment]
> We added `--sync.loop.block.limit` flag for this case. (maybe `--sync.loop.block.limit` flag not supported by `--internalcl` mode)

Cool, so the progress is committed per loop, right?

**Comment by AskAlexSharov** [comment]
> > We added `--sync.loop.block.limit` flag for this case. (maybe `--sync.loop.block.limit` flag not supported by `--internalcl` mode)
> 
> Cool, so the progress is committed per loop, right?

all stages run forward for this amount of blocks - then commit - then next batch of blocks.
