### ISSUE TITLE
debug_traceBlockByHash returns "method handler crashed" for certain blocks

### ISSUE THREAD

**Issue by Andrei-sys** [ledgerwatch/erigon#7938]
#### System information

Erigon version: `./erigon --version`
erigon version 2.48.1-stable-674b77f0
OS & Version: Windows/Linux/OSX
Ubuntu

For Goerli:

Example RPC Call:

curl -X POST  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0", "id":2, "method": "debug_traceBlockByHash", "params": [ "0x8f57b9dbebf86d3d7dd6c8ab751d496ed73bbf9f0124d46326d9b1c1efbd2d9f" , {"tracer": "callTracer", "tracerConfig": {"onlyTopCall": false, "withLog": true}}] }' localhost:8545
{"jsonrpc":"2.0","id":2,"result":[{"result":null,"error":{"code":-32000,"message":"method handler crashed"}}

On a side note, a similar problem appeared on Nodereal's implementation of BSC and it has been fixed some time ago: https://github.com/node-real/bsc-erigon/issues/140.

We were wondering whether anyone else has seen this problem before or not. Any ideas would be highly appreciated. Thanks in advance!

**Comment by AskAlexSharov** [comment]
Logs?

**Comment by Andrei-sys** [comment]
Jul 28 10:23:26 archive-eth-goerli-0 erigon[985219]: [EROR] [07-28|10:23:26.775] RPC method debug_traceBlockByHash crashed: runtime error: index out of range [-1]
Jul 28 10:23:26 archive-eth-goerli-0 erigon[985219]: [service.go:219 panic.go:884 panic.go:113 call.go:177 interpreter.go:234 interpreter.go:262 evm.go:57 evm.go:395 evm.go:443 state_transition.go:416 state_transition.go:185 tracing.go:198 tracing.go:144 tracing.go:37 value.go:586 value.go:370 service.go:224 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
Jul 28 10:23:26 archive-eth-goerli-0 erigon[985219]: [INFO] [07-28|10:23:26.837] local tx propagated                      tx_hash=c34bd8760b62d1fc0e3af486a1d3685cd7c364a13a7bcd8b1e7c9b5cfdce8215 announced to peers=127 broadcast to peers=5 baseFee=8106305162
Jul 28 10:23:27 archive-eth-goerli-0 erigon[985219]: [WARN] [07-28|10:23:27.117] Served                                   conn=162.19.232.109:1206 method=eth_estimateGas reqid=1072 t=6.942498ms err="execution reverted"
Jul 28 10:23:27 archive-eth-goerli-0 erigon[985219]: [EROR] [07-28|10:23:27.503] RPC method debug_traceBlockByHash crashed: runtime error: index out of range [-1]
Jul 28 10:23:27 archive-eth-goerli-0 erigon[985219]: [service.go:219 panic.go:884 panic.go:113 call.go:177 interpreter.go:234 interpreter.go:262 evm.go:57 evm.go:395 evm.go:443 state_transition.go:416 state_transition.go:185 tracing.go:198 tracing.go:144 tracing.go:37 value.go:586 value.go:370 service.go:224 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
Jul 28 10:23:27 archive-eth-goerli-0 erigon[985219]: [WARN] [07-28|10:23:27.704] Served                                   conn=162.19.232.109:1206 method=eth_estimateGas reqid=1076 t=4.957702ms err="execution reverted"
Jul 28 10:23:28 archive-eth-goerli-0 erigon[985219]: [EROR] [07-28|10:23:28.036] RPC method debug_traceBlockByHash crashed: runtime error: index out of range [-1]
Jul 28 10:23:28 archive-eth-goerli-0 erigon[985219]: [service.go:219 panic.go:884 panic.go:113 call.go:177 interpreter.go:234 interpreter.go:262 evm.go:57 evm.go:395 evm.go:443 state_transition.go:416 state_transition.go:185 tracing.go:198 tracing.go:144 tracing.go:37 value.go:586 value.go:370 service.go:224 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
Jul 28 10:23:28 archive-eth-goerli-0 erigon[985219]: [WARN] [07-28|10:23:28.298] Served                                   conn=162.19.232.109:1206 method=eth_estimateGas reqid=1080 t=6.665425ms err="execution reverted"

**Comment by Andrei-sys** [comment]
@AskAlexSharov Do you have any updates on the above?

**Comment by Andrei-sys** [comment]
After upgrading to erigon version 2.49.1-stable-205eeda0 we get the following, does this mean the issue is solved or what's that error about? @AskAlexSharov @0xKrishna 
` # curl -X POST  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0", "id":2, "method": "debug_traceBlockByHash", "params": [ "0x8f57b9dbebf86d3d7dd6c8ab751d496ed73bbf9f0124d46326d9b1c1efbd2d9f" , {"tracer": "callTracer", "tracerConfig": {"onlyTopCall": false, "withLog": true}}] }' localhost:8545`
`{"jsonrpc":"2.0","id":2,"result":[{"result":{"from":"0x26552c482c3df577e32996f18aec6f69176257f2","gas":"0x9dd88","gasUsed":"0xaae60","to":"0x0000000000000000000000000000000000000000","input":"0xa0270dbc0000000000000000000000000000000000000000000000000000000000000032","error":"stack underflow (0 \u003c=\u003e 2)","value":"0x16345785d8a0000","type":"CREATE"}}]}`

**Comment by alexandresobolevski** [comment]
+1

```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "params": [
        "0x114e295",
        {"tracer": "callTracer", "tracerConfig": { "withLog": true, "onlyTopCall": false }}
  ]
}
```

returns

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32603,
        "message": "method handler crashed"
    }
}
```

**Comment by alexandresobolevski** [comment]
More blocks where this error occurs on mainnet:
```
18144555
18145687
18145941
18146167
18146229
18146262
```

**Comment by yperbasis** [comment]
Please re-open if the issue still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
