### ISSUE TITLE
Does the change sets store the changes of blocks in the forks?

### ISSUE THREAD

**Issue by lurais** [ledgerwatch/erigon#7956]
hello, from the guide I want to know:https://github.com/ledgerwatch/erigon/blob/devel/docs/programmers_guide/db_walkthrough.MD
1.Does the change sets store the changes of blocks in the forks? if not ,it just rewind to switch to the right fork?
2.Why does the change sets store the values the accounts had before the change but not after the change?
3.If I use fullnode not an archive node, will the disk usage be decreased when compare to the geth fullnode?

**Comment by lurais** [comment]
> 1. No, yes.
> 2. https://youtu.be/CSpc1vZQW2Q
> 3. Erigon disk usage will increase - deletes are not free. Compare to geth - hard to say: we have 4 more indices enabled by default.

@AskAlexSharov From the youtube video, the change sets store the values the accounts had before the change for it is easier to rewind blocks?

**Comment by AskAlexSharov** [comment]
<img width="775" alt="Screenshot 2023-08-09 at 23 55 41" src="https://github.com/ledgerwatch/erigon/assets/46885206/40c885e1-8d86-4a47-b137-1b9a8e7ed7ba">

so - for efficient pruning

**Comment by lurais** [comment]
> <img alt="Screenshot 2023-08-09 at 23 55 41" width="775" src="https://user-images.githubusercontent.com/46885206/259502794-40c885e1-8d86-4a47-b137-1b9a8e7ed7ba.png">
> so - for efficient pruning

@AskAlexSharov so is that pruning latest blocks or some old change sets? Or that is good to rewind blocks and prune old change sets both?

**Comment by lurais** [comment]
> Old

@AskAlexSharov With current state rewind the change sets to some latest block , means the change sets which is lower than current rewinded block will not be kept? So only some latest change sets will remain ,is that right?

**Comment by AskAlexSharov** [comment]
https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node - it deleting some old data
https://ethereum.org/en/developers/docs/nodes-and-clients/#archive-node - keeps all

**Comment by lurais** [comment]
> https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node - it deleting some old data https://ethereum.org/en/developers/docs/nodes-and-clients/#archive-node - keeps all

@AskAlexSharov Assuming that the current block height is M, by rolling back to the specified block height N, the data before the specified block height N is equivalent to not being retained, and then only the data between M and N is retained in the change sets ,Is it right?

**Comment by lurais** [comment]
> > https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node - it deleting some old data https://ethereum.org/en/developers/docs/nodes-and-clients/#archive-node - keeps all
> 
> @AskAlexSharov hello, assuming that the current block height is M, by rolling back to the specified block height N, the data before the specified block height N is equivalent to not being retained, and then only the data between M and N is retained in the change sets ,Is it right?

@AskAlexSharov is this right?

**Comment by AskAlexSharov** [comment]
yes
