### ISSUE TITLE
Erigon Sync very slow

### ISSUE THREAD

**Issue by 10xc0ffee** [ledgerwatch/erigon#7962]
# Erigon Version
*erigon version 2.48.1-stable-674b77f0*

Command
```
~/code/erigonlog/erigon --log.dir.path ~/code/erigonlog/ --log.dir.verbosity 3 \
       --datadir /Volumes/blockchain/erigon/ \
       --chain mainnet \
       --http --ws --http.trace --http.api eth,debug,net,trace,web3,erigon,txpool --http.addr "192.168.0.16" --http.vhosts "192.168.0.13" --http.port 8545 --graphql \
       --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /Volumes/blockchain/erigon/jwtsecret \
       --private.api.addr localhost:9090 \
       --metrics --metrics.addr "192.168.0.16" --metrics.port 6060 \
       --pprof --pprof.addr "192.168.0.16" --pprof.port 6060

```

# Chain data Sync

Only 10+blk/s.

```
INFO[08-02|22:41:46.573] [snapshots] Blocks Stat                  blocks=17000k indices=17000k alloc=4.1GB sys=4.3GB
INFO[08-02|22:41:48.585] [7/15 Execution] Blocks execution        from=10751279 to=16999999
INFO[08-02|22:42:08.608] [7/15 Execution] Executed blocks         number=10751483 blk/s=10.2 tx/s=1475.4 Mgas/s=123.8 gasState=0.00 batch=5.6MB alloc=3.2GB sys=4.3GB
INFO[08-02|22:42:29.208] [7/15 Execution] Executed blocks         number=10751810 blk/s=16.4 tx/s=2309.2 Mgas/s=197.4 gasState=0.01 batch=15.5MB alloc=2.5GB sys=4.3GB
INFO[08-02|22:42:43.883] [txpool] stat                            pending=0 baseFee=0 queued=42 alloc=2.9GB sys=4.3GB
INFO[08-02|22:42:49.223] [7/15 Execution] Executed blocks         number=10752018 blk/s=10.4 tx/s=1503.4 Mgas/s=125.8 gasState=0.02 batch=21.9MB alloc=3.2GB sys=4.3GB
```

# Hardware

<img width="256" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/d9af295a-5fd0-4aca-a1f8-3a018c46b609">

<img width="397" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/c2119a8f-d8f2-4296-aa3f-29951008c347">

<img width="422" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/7eba6484-f67b-464e-85b4-9eb69540cc8e">

**Comment by zayg** [comment]
The very first day, the speed of sync is hundreds of blk/s, now it becomes 10blk/s. Not sure what's going on.

**Comment by tjayrush** [comment]
I'm not an expert nor am I part of the Erigon team, but I suspect two things are happening.

Remember, the sync happens from block zero forward in time.

1. The number of transactions per block increases massively over time and
2. The complexity of the transactions increases massively over time. 

These two combine to slow things down the later in the chain's history the sync gets.

I would close this issue as you're describing expected behavior, but perhaps someone else can chime in.

**Comment by zayg** [comment]
> I'm not an expert nor am I part of the Erigon team, but I suspect two things are happening.
> 
> Remember, the sync happens from block zero forward in time.
> 
> 1. The number of transactions per block increases massively over time and
> 2. The complexity of the transactions increases massively over time.
> 
> These two combine to slow things down the later in the chain's history the sync gets.
> 
> I would close this issue as you're describing expected behavior, but perhaps someone else can chime in.

Thank you @tjayrush. It makes sense, though the doc says it takes ~4 days to do a sync in archive mode, but for me it is already a week and I guess it will need another week to finish the sync.

**Comment by wmitsuda** [comment]
I think the 4 days estimate is outdated, also blocks/s is not a good measure for the reasons TJ has explained above, I think mgas/s is more accurate over time, and also it may say something about how performant is your disk.

**Comment by zayg** [comment]
> I think the 4 days estimate is outdated, also blocks/s is not a good measure for the reasons TJ has explained above, I think mgas/s is more accurate over time, and also it may say something about how performant is your disk.

Initially,
```
[INFO] [07-30|10:42:19.717] [7/15 Execution] Executed blocks         number=2064674 blk/s=2988.9 tx/s=22050.1 Mgas/s=724.2 gasState=0.16 batch=186.7MB alloc=3.7GB sys=12.6GB
```
Now,

```
[INFO] [08-03|19:50:06.738] [7/15 Execution] Executed blocks         number=11402476 blk/s=11.8 tx/s=1831.6 Mgas/s=144.3 gasState=0.13 batch=196.6MB alloc=3.9GB sys=6.7GB

```

Drop from 700 to 140 MGas/s

**Comment by wmitsuda** [comment]
that's a little odd... don't know why it dropped so much,

USB drive? I also use an external USB + mac, don't remember how much mgas/s it was the last time I synced from scratch, but the total process is slower than in an optimal hardware, i.e., at least 2 weeks in total.

**Comment by wmitsuda** [comment]
also, mine is a 2019 macbook, I see yours is a 2015 model, so slower CPU, it'll probably affect performance during execution stage.

I also have an older macbook, 2016 model and it's pretty much slower using same USB drive.

**Comment by wmitsuda** [comment]
I just remembered this tweet from @MysticRyuujin : https://twitter.com/mysticryuujin/status/1662432277773844485

I think there is not much to hope from a 2015 CPU, no matter which client you use.

**Comment by zayg** [comment]
@wmitsuda Do you think could be memory? Erigon only uses 8GB of memory, and I only have 16GB memory in total.

For CPU, I does notice a very wired behavior: periodically, the even CPU ID are getting very idle. Any thoughts?
<img width="245" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/25634765-a649-4e59-85cc-fd0f15ec098f">

**Comment by zayg** [comment]
I found that the current stage is "execute blocks" -- per doc, this stage is single threaded and IO heavy.

the blk/s is very slow, so does the SSD throughput (see disk3, it periodically dump at 15MB/s and then drop to 0)
<img width="432" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/9bb800d8-d9ff-40d0-9d2f-2fecd7becc4f">

**Comment by zayg** [comment]
Need help.. I tried the following things but not helping:
1. renice the Erigon process to -20.
2. run 'sudo taskpolicy -B -t 0 -p `pgrep erigon``
3. change GOMAXPROCS to 10

**Comment by AskAlexSharov** [comment]
Show logs

**Comment by AskAlexSharov** [comment]
Then it’s expected speed on 16gb RAM machine. State is ~80gb. And no much of disk reads parallelization here (disk random read latency - is the bottleneck).

you can try add env variable WRITE_MAP=true

**Comment by zayg** [comment]
@AskAlexSharov Thanks! some follow up questions:

1. What is provided by WRITE_MAP=true?
2. One thing I notice the Erigon process in my instance is that the CPU usage spikes every 10s-15s -- looks like Erigon is working hard for couple of seconds and then become very idle for another couple of seconds. Same thing happens on the disk io, the disk throughput increases along with the CPU usage spike. But I don't understand why the system becomes idle periodically (I couldn't correlate it with the disk read speed). Do you have any ideas?
<img width="430" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/64ee1c69-5ea7-4d97-957d-32d70bfd6531">

**Comment by zayg** [comment]
@AskAlexSharov As suggested, I have changed my server to 23 cores (2.93 Ghz) with 144 GB memory and 4TB SSD. The linux version is 3.10.0-1160.el7.x86_64.

I am still having issues with the same pattern.
Do you have any estimation about how long it takes to sync with archive mode? For me, it is already one week and it will take another two weeks if the speed doesn't drop further.

**Comment by AskAlexSharov** [comment]
currently bottleneck is at disk latency (not throughput) - so, hard to recommend something without knowing disk type. 

With 144Gb RAM you can add --batchSize=1G and can try run (without stoping erigon):
```
./build/bin/integration warmup --bucket=PlainState --datadir=<your_datadir>
```

**Comment by farmage** [comment]
restarted once again. the speed degradation is now even faster
`INFO[08-24|09:02:36.621] [snapshots] Blocks Stat                  blocks=17000k indices=17000k alloc=3.1GB sys=4.3GB                                                                    
INFO[08-24|09:02:37.309] [7/15 Execution] Blocks execution        from=7114578 to=16999999                                                                                              
INFO[08-24|09:02:57.319] [7/15 Execution] Executed blocks         number=7116259 blk/s=84.0 tx/s=6965.4 Mgas/s=467.4 gasState=0.02 batch=20.7MB alloc=2.3GB sys=4.3GB                   
INFO[08-24|09:03:17.317] [7/15 Execution] Executed blocks         number=7117791 blk/s=76.6 tx/s=8442.6 Mgas/s=505.1 gasState=0.04 batch=41.8MB alloc=3.3GB sys=4.6GB
INFO[08-24|09:03:33.683] [txpool] stat                            pending=0 baseFee=0 queued=95 alloc=3.8GB sys=4.6GB
INFO[08-24|09:03:37.324] [7/15 Execution] Executed blocks         number=7119323 blk/s=76.6 tx/s=9148.5 Mgas/s=516.9 gasState=0.05 batch=65.3MB alloc=4.3GB sys=4.6GB
INFO[08-24|09:03:57.330] [7/15 Execution] Executed blocks         number=7121014 blk/s=84.5 tx/s=6946.7 Mgas/s=481.8 gasState=0.07 batch=87.2MB alloc=2.9GB sys=4.7GB
INFO[08-24|09:04:17.321] [7/15 Execution] Executed blocks         number=7122756 blk/s=87.1 tx/s=8690.9 Mgas/s=517.6 gasState=0.09 batch=111.0MB alloc=3.8GB sys=4.7GB
INFO[08-24|09:04:33.646] [p2p] GoodPeers                          eth68=4 eth67=4 eth66=1
INFO[08-24|09:04:33.682] [txpool] stat                            pending=0 baseFee=0 queued=139 alloc=4.2GB sys=4.7GB
INFO[08-24|09:04:37.321] [7/15 Execution] Executed blocks         number=7124315 blk/s=78.0 tx/s=9069.6 Mgas/s=496.5 gasState=0.11 batch=135.9MB alloc=2.6GB sys=4.8GB
INFO[08-24|09:04:57.324] [7/15 Execution] Executed blocks         number=7125658 blk/s=67.1 tx/s=6269.9 Mgas/s=385.4 gasState=0.12 batch=154.8MB alloc=2.6GB sys=4.8GB
INFO[08-24|09:05:17.327] [7/15 Execution] Executed blocks         number=7126359 blk/s=35.0 tx/s=2358.4 Mgas/s=207.3 gasState=0.13 batch=162.2MB alloc=3.7GB sys=4.8GB
INFO[08-24|09:05:33.683] [txpool] stat                            pending=0 baseFee=0 queued=208 alloc=2.4GB sys=4.8GB
INFO[08-24|09:05:37.312] [7/15 Execution] Executed blocks         number=7127055 blk/s=34.8 tx/s=2681.7 Mgas/s=220.1 gasState=0.14 batch=170.6MB alloc=2.7GB sys=4.8GB
INFO[08-24|09:05:57.385] [7/15 Execution] Executed blocks         number=7127766 blk/s=35.4 tx/s=3569.9 Mgas/s=236.6 gasState=0.15 batch=180.1MB alloc=4.0GB sys=4.8GB
INFO[08-24|09:06:17.431] [7/15 Execution] Executed blocks         number=7128423 blk/s=32.8 tx/s=3299.1 Mgas/s=216.1 gasState=0.15 batch=189.3MB alloc=3.0GB sys=4.8GB
INFO[08-24|09:06:33.646] [p2p] GoodPeers                          eth68=5 eth67=9 eth66=2
INFO[08-24|09:06:33.683] [txpool] stat                            pending=0 baseFee=0 queued=259 alloc=3.8GB sys=4.8GB
INFO[08-24|09:06:37.321] [7/15 Execution] Executed blocks         number=7128976 blk/s=27.8 tx/s=2814.0 Mgas/s=182.0 gasState=0.16 batch=197.9MB alloc=4.2GB sys=5.0GB
INFO[08-24|09:06:57.336] [7/15 Execution] Executed blocks         number=7129577 blk/s=30.0 tx/s=3253.1 Mgas/s=203.5 gasState=0.17 batch=207.1MB alloc=3.4GB sys=5.0GB
INFO[08-24|09:07:17.365] [7/15 Execution] Executed blocks         number=7130048 blk/s=23.5 tx/s=2551.0 Mgas/s=162.2 gasState=0.17 batch=214.7MB alloc=4.4GB sys=5.0GB
INFO[08-24|09:07:33.682] [txpool] stat                            pending=0 baseFee=0 queued=1018 alloc=2.5GB sys=5.3GB
INFO[08-24|09:07:37.328] [7/15 Execution] Executed blocks         number=7130437 blk/s=19.5 tx/s=1639.5 Mgas/s=135.9 gasState=0.18 batch=221.0MB alloc=2.6GB sys=5.3GB
INFO[08-24|09:07:57.353] [7/15 Execution] Executed blocks         number=7130960 blk/s=26.1 tx/s=1985.3 Mgas/s=172.6 gasState=0.19 batch=228.8MB alloc=3.6GB sys=5.3GB
`
CPU is 16 core, loaded minimum
RAM 32Gb

**Comment by zayg** [comment]
> leave here my 5c ) env variable WRITE_MAP=true helps a little. after restart the b/s rises from 16-20 to 70-80, but after 10 minutes everything goes back to the old values. iotop shows that the disk load is minimal. sometimes there are spikes about 10mb/s of Disk Write , but most load is no more than 1mb/s

@farmage  In my case, the disk write is ~20MB/s for couple of seconds, then reduces to less than 1MB/s for couple of seconds. Not sure what's going on.

**Comment by AskAlexSharov** [comment]
"RAM 32Gb" - no magic, mainnet state is ~80gb and when it grows over RAM - you will start face more and more page-faults (page cache misses). "read-ahead strategy" is not easy for turing-complete-smart-contracts, we have some - but very limited. and page-cache-miss speed is limited by disk-latency (not by throughput): faster disk or bigger ram will help.

"after 10 minutes everything goes back" - it's also about page-cache-misses - when you re-start you re-execution some last blocks - and you see it as "fast speed" because no page-misses (same blocks was just executed). 

can a bit optimize state size by - manual db compaction: "integration mdbx_to_mdbx" or "mdbx_dump|mdbx_load" (see ./cmd/integraion/readme.md).

As an experiment (likely will not help much) - you can try: 
- stop erigon
- run: integration stage_exec --batchSize=1g

**Comment by zayg** [comment]
@AskAlexSharov  I tried the --batchSize=1g
```
INFO[08-25|23:06:14.762] [7/15 Execution] Executed blocks         number=14660536 blk/s=14.5 tx/s=2731.2 Mgas/s=226.0 gasState=0.22 batch=932.4MB alloc=9.5GB sys=15.7GB
INFO[08-25|23:06:34.748] [7/15 Execution] Executed blocks         number=14660856 blk/s=16.0 tx/s=3001.7 Mgas/s=248.9 gasState=0.22 batch=943.1MB alloc=11.5GB sys=15.7GB
INFO[08-25|23:06:54.808] [7/15 Execution] Executed blocks         number=14661148 blk/s=14.6 tx/s=2859.8 Mgas/s=224.8 gasState=0.22 batch=953.0MB alloc=7.5GB sys=15.7GB
INFO[08-25|23:07:05.639] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=8.6GB sys=15.7GB
INFO[08-25|23:07:07.343] [Caplin] P2P                             peers=33
INFO[08-25|23:07:14.773] [7/15 Execution] Executed blocks         number=14661430 blk/s=14.1 tx/s=2607.6 Mgas/s=216.0 gasState=0.23 batch=962.4MB alloc=9.2GB sys=15.7GB
INFO[08-25|23:07:27.235] [p2p] GoodPeers                          eth67=33 eth68=33
INFO[08-25|23:07:34.815] [7/15 Execution] Executed blocks         number=14661728 blk/s=14.9 tx/s=2897.8 Mgas/s=231.4 gasState=0.23 batch=972.0MB alloc=11.1GB sys=15.7GB
EROR[08-25|23:07:45.057] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
INFO[08-25|23:07:54.779] [7/15 Execution] Executed blocks         number=14662038 blk/s=15.5 tx/s=2947.2 Mgas/s=241.3 gasState=0.23 batch=981.7MB alloc=7.1GB sys=15.7GB
INFO[08-25|23:08:05.635] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=8.1GB sys=15.7GB
INFO[08-25|23:08:07.343] [Caplin] P2P                             peers=33
INFO[08-25|23:08:14.767] [7/15 Execution] Executed blocks         number=14662349 blk/s=15.6 tx/s=2721.1 Mgas/s=238.7 gasState=0.23 batch=991.4MB alloc=8.9GB sys=15.7GB
INFO[08-25|23:08:34.774] [7/15 Execution] Executed blocks         number=14662629 blk/s=14.0 tx/s=2448.0 Mgas/s=212.7 gasState=0.23 batch=1000.0MB alloc=10.6GB sys=15.7GB
INFO[08-25|23:08:54.766] [7/15 Execution] Executed blocks         number=14662926 blk/s=14.9 tx/s=2483.5 Mgas/s=229.9 gasState=0.24 batch=1009.3MB alloc=6.5GB sys=15.7GB
INFO[08-25|23:09:05.634] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=7.3GB sys=15.7GB
```

Seems doesn't help. I want to try the integration warmup. I wonder what does it do and what's the different between integration warmup and the page cache. Because the erigon process already uses a large amount of caches (I suppose those are state of the chain?).

Good news is if I wait for 3 more days, probably it will finish...

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon#htop-shows-incorrect-memory-usage

**Comment by zayg** [comment]
@AskAlexSharov Could you elaborate? I still don't understand the difference between page cache and the cache maintained by "integration warmup".

**Comment by AskAlexSharov** [comment]
No difference. But when Data >> Ram - PageCache is evicting and more pressure comes to disk latency.

**Comment by zayg** [comment]
Thanks @AskAlexSharov 

Finally the stage 7 is done. But I am hitting another issue:
```
Could not download block                 reason="replay block, code: 2" slot=7207173
```
details:
```
[DBUG] [08-29|10:48:35.581] AddChainSegment: missing segment         block=0x2e969d7f7a4bb76a9801269d246a8acd1e6e6af2a309d0a33aeb74884a37bad4
[WARN] [08-29|10:48:35.581] Could not download block                 reason="replay block, code: 2" slot=7207173
[DBUG] [08-29|10:48:35.581] [Sentinel Peers] bad peers has been banned peer-id=16Uiu2HAkwunNci6hjgLWPCbESq3vxNimpLjYBS6DxYruzffoMJmw reason=
[DBUG] [08-29|10:48:35.581] [Sentinel Peers] disconnecting from peer peer-id=16Uiu2HAkwunNci6hjgLWPCbESq3vxNimpLjYBS6DxYruzffoMJmw reason=
[DBUG] [08-29|10:48:39.769] [Sentinel Peers] peer replied            peer-id=16Uiu2HAm1znM7oSwbrvXFrPCy168ARr37TTyUK71FwiMQyhP64bX uses=2 success=1
[DBUG] [08-29|10:48:39.903] Could not retrieve state: Missing header missing=0x08e3fe01c63fd35a3ee6faf0fb27f12d7a2d8571acbd258c5f3e39f3944bff14 longRecconection=0xdd32161da4b48e94b7bdcfbe4a02f62eac580711acd3e68be5b25d344747cf45 shortRecconection=0x3d055f938315c4e62f4757e6fb055ae3881f18faa59c78e7bd33ec38af79e0e7
[DBUG] [08-29|10:48:39.903] AddChainSegment: missing segment         block=0x2e969d7f7a4bb76a9801269d246a8acd1e6e6af2a309d0a33aeb74884a37bad4
[WARN] [08-29|10:48:39.903] Could not download block                 reason="replay block, code: 2" slot=7207173
[DBUG] [08-29|10:48:39.903] [Sentinel Peers] bad peers has been banned peer-id=16Uiu2HAm1znM7oSwbrvXFrPCy168ARr37TTyUK71FwiMQyhP64bX reason=
[DBUG] [08-29|10:48:39.904] [Sentinel Peers] disconnecting from peer peer-id=16Uiu2HAm1znM7oSwbrvXFrPCy168ARr37TTyUK71FwiMQyhP64bX reason=
[DBUG] [08-29|10:48:45.525] [txpool] Commit                          written_kb=524 in=74.395459ms
[DBUG] [08-29|10:48:50.257] [Sentinel Peers] disconnecting from peer peer-id=16Uiu2HAm4327iRHEd6xFQ2UoDyL8T6xxkHaBoaBNALQEYYNCDiX9 reason="failed to dial 16Uiu2HAm4327iRHEd6xFQ2UoDyL8T6xxkHaBoaBNALQEYYNCDiX9:\n  * [/ip4/54.160.240.242/tcp/9000] dial tcp4 54.160.240.242:9000: i/o timeout"
[DBUG] [08-29|10:48:50.741] [p2p] Handshake failure                  peer=3e226ffa60b7b28fa675 err="genesis hash does not match: theirs c5404f768c212b3ebbabb02a5ca45926322fc9a6f24f5e57d2cba5434b1c7980, ours d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
[DBUG] [08-29|10:49:06.289] [txpool] Commit                          written_kb=668 in=5.073956067s
[INFO] [08-29|10:49:06.290] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=5.8GB sys=16.3GB
[INFO] [08-29|10:49:07.343] [Caplin] P2P                             peers=22
[DBUG] [08-29|10:49:16.269] [Sentinel Peers] peer replied            peer-id=16Uiu2HAkurZR8uYXw1xd2khrcBcYma98UpDp719PiMrJUifu3cqF uses=2 success=1
[DBUG] [08-29|10:49:16.401] Could not retrieve state: Missing header missing=0x08e3fe01c63fd35a3ee6faf0fb27f12d7a2d8571acbd258c5f3e39f3944bff14 longRecconection=0xdd32161da4b48e94b7bdcfbe4a02f62eac580711acd3e68be5b25d344747cf45 shortRecconection=0x3d055f938315c4e62f4757e6fb055ae3881f18faa59c78e7bd33ec38af79e0e7
[DBUG] [08-29|10:49:16.401] AddChainSegment: missing segment         block=0x2e969d7f7a4bb76a9801269d246a8acd1e6e6af2a309d0a33aeb74884a37bad4
[WARN] [08-29|10:49:16.401] Could not download block                 reason="replay block, code: 2" slot=7207173
```

**Comment by AskAlexSharov** [comment]
I don’t know current state of your node

**Comment by zayg** [comment]
Update:
Thank god. Almost there.. 
```
INFO[09-06|12:58:39.157] [7/15 Execution] Executed blocks         number=18055589 blk/s=6.6 tx/s=1011.3 Mgas/s=99.1 gasState=0.07 batch=319.5MB alloc=9.8GB sys=17.1GB
INFO[09-06|12:58:59.158] [7/15 Execution] Executed blocks         number=18055817 blk/s=11.4 tx/s=1694.0 Mgas/s=172.1 gasState=0.08 batch=326.4MB alloc=11.1GB sys=17.1GB
```
CPU/MEM
<img width="495" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/d2627a68-8527-4609-a13d-ea24db70d5b3">

IO

<img width="507" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/9121f28b-da33-4af5-a05e-9cd2fd14321f">

**Comment by zayg** [comment]
Update:
Almost there...

```
INFO[09-08|00:21:45.607] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000c3d6be6a3703bf34859fd949235995ce754418cdffffffff
INFO[09-08|00:22:15.606] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000c4d7aa60e74d25211d8a40441fb3440e5ff2e483ffffffff
INFO[09-08|00:22:45.615] [13/15 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current_prefix=000000000000000000000000c5c3bb3fed7d880350a5e62b1c34bede0c936c3affffffff
```

CPU/MEM
<img width="512" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/b6eb2317-4788-4381-b2c1-9e400bd55d61">


IO
<img width="376" alt="image" src="https://github.com/ledgerwatch/erigon/assets/3822934/aea22a8c-5e40-4a7d-aaa4-26e393167908">

**Comment by 10xc0ffee** [comment]
Update: 

```
INFO[09-08|11:48:47.720] [5/15 Bodies] Downloading block bodies   block_num=18061942 delivery/sec=3.3MB wasted/sec=0B remaining=30697 delivered=5351 cache=2.9MB alloc=6.6GB sys=7.5GB
INFO[09-08|11:49:07.724] [5/15 Bodies] Writing block bodies       block_num=18062467 remaining=30173 alloc=3.9GB sys=7.5GB
INFO[09-08|11:49:27.722] [5/15 Bodies] Writing block bodies       block_num=18062657 remaining=29983 alloc=4.2GB sys=7.5GB
INFO[09-08|11:49:47.726] [5/15 Bodies] Writing block bodies       block_num=18063214 remaining=29426 alloc=4.8GB sys=7.5GB
```

**Comment by 10xc0ffee** [comment]
Update:

```
[DBUG] [09-09|10:14:25.983] [1/15 Snapshots] DONE                    in=9.266µs
[INFO] [09-09|10:14:25.983] [2/15 Headers] Waiting for Consensus Layer...
[DBUG] [09-09|10:14:25.983] [NewPayload] got reply                   payloadStatus="{Status:VALID LatestValidHash:0x7cf9acd07d7c4b80d87d7b49f143f69ae9703bb85da124d0828d9c3afc70a172 ValidationError:<nil> CriticalError:<nil>}"
[DBUG] [09-09|10:14:27.551] [ForkChoiceUpdated] sending forkChoiceMessage head=0x7cf9acd07d7c4b80d87d7b49f143f69ae9703bb85da124d0828d9c3afc70a172
[DBUG] [09-09|10:14:27.551] [2/15 Headers] Handling fork choice      headerHash=0x7cf9acd07d7c4b80d87d7b49f143f69ae9703bb85da124d0828d9c3afc70a172
[INFO] [09-09|10:14:27.551] [2/15 Headers] Fork choice update: flushing in-memory state (built by previous newPayload)
[DBUG] [09-09|10:14:28.030] [2/15 Headers] DONE                      in=2.046493814s
[DBUG] [09-09|10:14:28.030] [3/15 CumulativeIndex] DONE              in=108.358µs
[DBUG] [09-09|10:14:28.030] [4/15 BlockHashes] DONE                  in=3.824µs
[DBUG] [09-09|10:14:28.030] [5/15 Bodies] DONE                       in=31.905µs
[DBUG] [09-09|10:14:28.030] [6/15 Senders] DONE                      in=251.827µs
[DBUG] [09-09|10:14:28.030] [7/15 Execution] DONE                    in=6.783µs
[DBUG] [09-09|10:14:28.030] [8/15 HashState] DONE                    in=3.473µs
[DBUG] [09-09|10:14:28.030] [9/15 IntermediateHashes] DONE           in=3.763µs
[DBUG] [09-09|10:14:28.110] [10/15 CallTraces] DONE                  in=79.777234ms
[DBUG] [09-09|10:14:28.169] [11/15 AccountHistoryIndex] DONE         in=58.701448ms
[DBUG] [09-09|10:14:28.254] [12/15 StorageHistoryIndex] DONE         in=85.366801ms
[DBUG] [09-09|10:14:28.314] [13/15 LogIndex] DONE                    in=60.077071ms
[DBUG] [09-09|10:14:28.395] [14/15 TxLookup] DONE                    in=80.114581ms
[DBUG] [09-09|10:14:28.395] [15/15 Finish] DONE                      in=38.9µs
[INFO] [09-09|10:14:28.399] RPC Daemon notified of new headers       from=18099356 to=18099357 hash=0x7cf9acd07d7c4b80d87d7b49f143f69ae9703bb85da124d0828d9c3afc70a172 header sending=27.309µs log sending=581ns
[INFO] [09-09|10:14:28.399] Timings (slower than 50ms)               Headers=2.046s CallTraces=79ms AccountHistoryIndex=58ms StorageHistoryIndex=85ms LogIndex=60ms TxLookup=80ms
[INFO] [09-09|10:14:28.399] Tables                                   PlainState=98.7GB AccountChangeSet=246.9GB StorageChangeSet=295.8GB BlockTransaction=147.5GB TransactionLog=603.5GB FreeList=9.2MB ReclaimableSpace=18.5GB
```

**Comment by 10xc0ffee** [comment]
Finally caught up. Thanks folks here for all the help!

**Comment by ChinW** [comment]
@10xc0ffee this took you 1month to complete?

**Comment by 10xc0ffee** [comment]
@ChinW  almost 4 weeks. I don't know if it is due to my SSD, the read speed is ~10MB/s. Please let me know if you are going to try it out.

**Comment by ChinW** [comment]
already trying out, took me 1 week now, still in progress

**Comment by 10xc0ffee** [comment]
Just want to update this thread:

I encountered some wired issue after fully sync. 

https://github.com/ledgerwatch/erigon/issues/8220
