### ISSUE TITLE
Support build with Go 1.21

### ISSUE THREAD

**Issue by yorickdowne** [ledgerwatch/erigon#7984]
# Implementation

The quic-go dependency would need to be updated from `0.33.0` to something more recent that supports Go 1.21, e.g. `0.37.3`

Error message when building with Go 1.21 currently:

```
Building erigon
# github.com/quic-go/quic-go/internal/qtls
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

quic-go from 0.37 on no longer requires its own TLS code, which means it should survive updates to the Go compiler far more easily:

"With the upcoming Go 1.21 release, we're now able to rely on the Go standard library's TLS implementation's QUIC support."

https://github.com/quic-go/quic-go/releases/tag/v0.37.0

**Comment by AskAlexSharov** [comment]
it dep from libp2p - maybe need update libp2p

**Comment by mooijtech** [comment]
Solved this via:
```
$ go install golang.org/dl/go1.20@latest
$ go1.20 download
$ sudo mv /usr/local/bin/go1.20 /usr/local/bin/go
```

**Comment by AskAlexSharov** [comment]
https://github.com/libp2p/go-libp2p/pull/2488

**Comment by AskAlexSharov** [comment]
https://github.com/ledgerwatch/erigon/pull/8008

**Comment by AskAlexSharov** [comment]
blocked by https://github.com/libp2p/go-libp2p/issues/2428#issuecomment-1681777427

**Comment by chenrui333** [comment]
> blocked by [libp2p/go-libp2p#2428 (comment)](https://github.com/libp2p/go-libp2p/issues/2428#issuecomment-1681777427)


FYI, v0.30.0 has shipped.

**Comment by AskAlexSharov** [comment]
blocked by https://github.com/ledgerwatch/erigon/issues/8078

**Comment by chenrui333** [comment]
can be closed via https://github.com/ledgerwatch/erigon/pull/8288

**Comment by yperbasis** [comment]
Please re-open if the issue still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
