### ISSUE TITLE
Memory consumption more than 64gb

### ISSUE THREAD

**Issue by michalgrzegor** [ledgerwatch/erigon#8000]
#### System information

Erigon version: v2.47.0

OS & Version: Linux

Erigon Command (with flags/config):
```
            - --chain=bor-mainnet
            - --datadir=/data/polygon-mainnet
            - --pprof
            - --prune=hrtc
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --private.api.addr=127.0.0.1:9090
            - --http.vhosts=*
            - --http.corsdomain=*
            - --bor.heimdall=http://heimdall-node-polygon:1317
```

Chain/Network: polygon-mainnet 

#### Expected behaviour
memory consumption less than 16gb

#### Actual behaviour
An ec2 machine with 64GB memory. The node runs out of memory every 1 hour. I need help understanding this chart:
[mem.pdf](https://github.com/ledgerwatch/erigon/files/12321565/mem.pdf)

**Comment by AskAlexSharov** [comment]
i think it's fixed in later erigon versions
