### ISSUE TITLE
Ledgerwatch/erigon:2.48.1 or Maticnetwork/erigon:0.0.8 which to go with for Polygon?

### ISSUE THREAD

**Issue by trugard** [ledgerwatch/erigon#8019]
While there's lots of activity over here on ledgerwatch, there is the 0.0.8 release over at https://github.com/maticnetwork/erigon. 0.0.8 doesn't seem as active, but there are comments on a short/medium term branch. So we're looking for guidance on which client to go with. Any inputs would be great.

**Comment by 0xKrishna** [comment]
Use erigon/v2.48.1 for long term support.
