### ISSUE TITLE
metrics endpoint producing duplicates, and therefore invalid Prometheus Export Format

### ISSUE THREAD

**Issue by angusscott** [ledgerwatch/erigon#8053]
#### System information

Erigon version: erigon version 2.48.1-stable-674b77f0

OS & Version: Windows/Linux/OSX

Erigon Command (with flags/config):

Chain/Network: Ethereum

#### Expected behaviour

Expect metrics to not include duplicates, and #HELP/#TYPE comments to appear in advance of the metrics they define

#### Actual behaviour

Metrics are appearing duplicated and out of sequence (#HELP/#TYPE) appearing after the metrics

#### Steps to reproduce the behaviour

Start an instance of Erigon, with --metrics enabled, and make a request.

Following an upgrade from v2.43.0 to v2.48.1 of Erigon, the metrics endpoint (/debug/metrics/prometheus), Telegraf is unable to parse the Prometheus Export Format, caused by duplicate metrics (and metrics appearing out of order, with metric appearing before #HELP and #TYPE information.

**Result from v2.48.1**

curl -s http://localhost:6060/debug/metrics/prometheus | grep "go_gc_duration_seconds"

go_gc_duration_seconds{quantile="0"} 5.3329e-05
go_gc_duration_seconds{quantile="0.25"} 9.0795e-05
go_gc_duration_seconds{quantile="0.5"} 0.000119249
go_gc_duration_seconds{quantile="0.75"} 0.000179327
go_gc_duration_seconds{quantile="1"} 0.076610138
go_gc_duration_seconds_sum 3.005057495
go_gc_duration_seconds_count 3192
\# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
\# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 5.3329e-05
go_gc_duration_seconds{quantile="0.25"} 9.0795e-05
go_gc_duration_seconds{quantile="0.5"} 0.000119249
go_gc_duration_seconds{quantile="0.75"} 0.00018207
go_gc_duration_seconds{quantile="1"} 0.076610138
go_gc_duration_seconds_sum 3.005057495
go_gc_duration_seconds_count 3192

**Result from v2.43.0**

curl -s http://localhost:6060/debug/metrics/prometheus | grep "go_gc_duration_seconds"

go_gc_duration_seconds{quantile="0"} 0.000106077
go_gc_duration_seconds{quantile="0.25"} 0.000119962
go_gc_duration_seconds{quantile="0.5"} 0.000128057
go_gc_duration_seconds{quantile="0.75"} 0.000138066
go_gc_duration_seconds{quantile="1"} 0.00027549
go_gc_duration_seconds_sum 6.798991387
go_gc_duration_seconds_count 35210

**Comment by AskAlexSharov** [comment]
Probably i can fix tomorrow

**Comment by mh0lt** [comment]
I have this fixed on this branch https://github.com/ledgerwatch/erigon/tree/heimdall_metrics, which I expect to merge into develop tomorrow after the primary fix in the branch is confirmed.

Just to confirm this is the output if I run in heimdall_metrics.  Part of the change here is changing the prometheus output to include meta-data which the polygon devops team need in general for thier data dog integration.
```
$ curl -s http://localhost:6060/debug/metrics/prometheus | grep "go_gc_duration_seconds"
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 4
```

**Comment by angusscott** [comment]
Great to see, all I ask is you pass the result through expfmt.TextParser's TextToMetricFamilies method, which will guarantee the result is formatted correctly (although the above looks correct. (I believe you're already using expfmt to generate the result, from what I could gleam from the Erigon code base)
