### ISSUE TITLE
debug_storageRangeAt method is taking more than 10 mins to respond for block hash doesn't exists

### ISSUE THREAD

**Issue by ella-quicknode** [ledgerwatch/erigon#8063]
#### System information

Erigon version: `erigon/2.48.1`

OS & Version: `linux-amd64/go1.20.7`

Chain/Network: Ethereum-mainnet archive node

#### Expected behaviour

Relating to `debug_storageRangeAt` method. 

To get a fast response time even when tx hash can't be found. Geth was able to respond a null when tx hash doesn't exist, so expecting Erigon to have the same behaviour. 

#### Actual behaviour

When tx hash doesn't exist for the `debug_storageRangeAt` method, it's taking more than 10 minutes for the node to respond.  

#### Steps to reproduce the behaviour

Payload for tx hash doesn't exist, taking ~10 minutes

```
{"jsonrpc":"2.0","method":"debug_storageRangeAt","id":0,"params":["0xbbedd56498245376e12894595e0869692d863121e64b922f5ba913e0b8ae20fb",0,"0x000000000022D473030F116dDEE9F6B43aC78BA3","0x0000000000000000000000000000000000000000000000000000000000000000",10]}
```

If run the same payload with Geth, taking less than 1 second.

**Comment by yperbasis** [comment]
Hopefully this shouldn't be a problem in Erigon 3 because we'll have transaction-level granularity of state history there.

**Comment by AskAlexSharov** [comment]
@ella-quicknode where is `txnHash` in your request? `debug_storageRangeAt` has next parameters: blockHash, txIdx, contractAddress, keyStart, maxResult

**Comment by ella-quicknode** [comment]
Hi @AskAlexSharov , sorry about the misleading message. I meant block hash (updated the header). 
This is an old issue and it's not replicable anymore. We can probably close it.

**Comment by AskAlexSharov** [comment]
Thank you
