### ISSUE TITLE
1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=16999999 min_in_db=17746000

### ISSUE THREAD

**Issue by SadeRespector** [ledgerwatch/erigon#8067]
#### System information

Erigon version: 2.48.1

OS & Version: linux

Commit hash:  [1fd9d20](https://github.com/ledgerwatch/erigon/commit/1fd9d20e14e69109dde4c2004ec90168bc5012c5)

Erigon Command (with flags/config): --datadir=/mainnetdata --chain=mainnet --port=30303 --http.port=8545 --authrpc.port=8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=eth,debug,net,trace,web3,erigon 

Concensus Layer: lighthouse

Concensus Layer Command (with flags/config): lighthouse bn   --network mainnet   --execution-endpoint http://localhost:8551   --execution-jwt /mainnetdata/jwt.hex   --checkpoint-sync-url https://beaconstate.info    --disable-deposit-contract-sync

Chain/Network: mainnet

#### Expected behaviour
snapshots has all blocks

#### Actual behaviour
snapshots stop at block 017000 and will not continue

#### Steps to reproduce the behaviour
unknown

#### Backtrace
INFO[08-24|13:32:41.748] logging to file system                   log dir=/mainnetdata/logs file prefix=integration log level=info json=false
INFO[08-24|13:32:43.400] [snapshots] Blocks Stat                  blocks=16500k indices=16500k alloc=2.2GB sys=2.3GB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

 				 stage_at 	 prune_at
Snapshots 			 17986078 	 0
Headers 			 17986078 	 0
BlockHashes 			 17986078 	 0
Bodies 				 17986078 	 0
Senders 			 17986078 	 0
Execution 			 17986078 	 17986078
Translation 			 0 		 0
HashState 			 0 		 0
IntermediateHashes 		 0 		 0
AccountHistoryIndex 		 17986078 	 0
StorageHistoryIndex 		 17986078 	 0
LogIndex 			 17986078 	 0
CallTraces 			 17986078 	 17986078
TxLookup 			 17986078 	 17746000
Finish 				 17986078 	 0
--
prune distance: 

blocks.v2: blocks=16499999, segments=16999999, indices=16499999

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->1, lastBlockInSnap=0

sequence: EthTx=2109009724, NonCanonicalTx=0

in db: first header 17746000, last header 17986082, first body 17746000, last body 17986078
````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
can be fixed by `integration stage_headers --reset`

**Comment by SadeRespector** [comment]
> integration stage_headers --reset

running stage_headers --reset returns 

```./build/bin/integration stage_headers --reset --datadir /mainnnetdata --chain mainnet
INFO[08-25|00:33:29.414] logging to file system                   log dir=/mainnnetdata/logs file prefix=integration log level=info json=false
mdbx_setup_dxb:15946 filesize mismatch (expect 65536b/16p, have 1048576b/256p)
panic: cannot write history: table: AccountHistory, err: mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached

goroutine 1 [running]:
github.com/ledgerwatch/erigon/cmd/integration/commands.newSync({0x1bcf2b0?, 0xc000131770}, {0x1bd7a70?, 0xc000e9cd00}, 0x0, {0x1bd7c10?, 0xc0000a80a0})
	github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:1500 +0x1445
github.com/ledgerwatch/erigon/cmd/integration/commands.stageHeaders({0x1bd7a70?, 0xc000e9cd00}, {0x1bcf2b0?, 0xc000131770}, {0x1bd7c10?, 0xc0000a80a0})
	github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:697 +0x1b6
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func10(0x25a99e0, {0x16f13e5?, 0x5?, 0x5?})
	github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:98 +0x2ed
github.com/spf13/cobra.(*Command).execute(0x25a99e0, {0xc000131810, 0x5, 0x5})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x25ad080)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(0x467b85?, {0x1bcf2b0?, 0xc000131770?})
	github.com/spf13/cobra@v1.7.0/command.go:985 +0x4a
main.main()
	github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0xed
```

**Comment by AskAlexSharov** [comment]
increase --db.size.limit

**Comment by wtdcode** [comment]
reset wont' work, https://github.com/ledgerwatch/erigon/issues/5639#issuecomment-1272463475 this should work.

**Comment by penonds** [comment]
> can be fixed by `integration stage_headers --reset`

hello, How to install integration？ can you send a link?
