### ISSUE TITLE
Caplin: db folder miss-configuration

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8083]
my erigon datadir is `/mnt/erigon/erigon` 
and i see something like database in folder: `/mnt/erigon/erigon/mnt/erigon/erigon` 
it has folders like: 
```
00  0e  1e  32  42
...
```
probably some path or folder name to sqlite miss-configured.

**Comment by Giulio2002** [comment]
thats fine as it creates another filesystem for caplin

**Comment by AskAlexSharov** [comment]
mmm... sorry, but i don't understand why it's fine. 

in my head: 
`/path/to/datadir/caplin_folder` is fine
 but `/path/to/datadir/path/to/datadir` looks like a bug

**Comment by Giulio2002** [comment]
no it is intended because caplin creates its own fs within datadir

**Comment by AskAlexSharov** [comment]
just checked code, seems you creating 2 fs instead of 1: 
```
dataDirFs := afero.NewBasePathFs(afero.NewOsFs(), dirs.DataDir)
persistence.NewbeaconChainDatabaseFilesystem(afero.NewBasePathFs(dataDirFs, dirs.DataDir)
```

**Comment by Giulio2002** [comment]
dataDirFs := afero.NewBasePathFs(afero.NewOsFs(), dirs.DataDir) is passed to the other fs

**Comment by AskAlexSharov** [comment]
In my head `/Users/monki/work/erigon/caplin_fs` is enough for anything (can do any black magic inside this dir (or `caplin_fs_<caplin_id>` if need many of them in 1 datadir).
Make content of datadir depend on datadir path - feels very fragile. For example: I always do on my laptop `cp -R /datadir1 /datadir2` - to run dangerous experiments on `/datadir2`.  

It's ok, maybe i just don't understand the use-case.

**Comment by Giulio2002** [comment]
Its just the library we use for it, but maybe I can make it look nicer?

**Comment by AskAlexSharov** [comment]
Next pattern will not work? 
caplinFs := afero.NewBasePathFs(afero.NewOsFs(), filepath.Join(dirs.DataDir, “caplin”))
persistence.NewbeaconChainDatabaseFilesystem(caplinFs)
