### ISSUE TITLE
rpc: pre-allocate all methods metrics (and their names) to global map 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8085]
now on each rpc call we doing fmt.Sprintf inside `newRPCServingTimerMS()`
need to pre-allocate metrics (or metric names) for all RPC methods - in-advance. Then only lookup in global map (or 2 maps - for success and failure metrics) by method name.

**Comment by pyropy** [comment]
Hi, can I pick this up maybe?

**Comment by AskAlexSharov** [comment]
How to get methods - list - probably reflection on «api” object. There is list of them.
