### ISSUE TITLE
Snapshot download stops at 99.98% every time

### ISSUE THREAD

**Issue by nivshitrit** [ledgerwatch/erigon#8101]
#### System information

Erigon version: 2.48.1

OS & Version:/Linux/

Erigon Command (with flags/config): 
--chain=mumbai --bor.heimdall=heimdal-rest:1317

Concensus Layer: heimdall

Concensus Layer Command (with flags/config):
 heimdall start --chain=mumbai --home=/heimdall-home

Chain/Network: mumbai

#### Expected behaviour
downlaod snapshot to 100%

#### Actual behaviour
download gets stuck at 99.98% everytime, suddenly 0 peers and it wont continue even if i let it sit for hours and hours

#### Steps to reproduce the behaviour
download erigon mumbai snapshot with this command:
`curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mumbai --client erigon --extract-dir data --validate-checksum true`

logs:
```
[INFO] [08-30|08:11:16.133] [p2p] GoodPeers 
[INFO] [08-30|08:11:16.182] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=68.0MB sys=219.5MB
[INFO] [08-30|08:11:16.210] [1/15 Snapshots] download                progress="99.98% 20.8GB/20.8GB" download-time-left=999hrs:99m total-download-time=1h6m0s download=0B/s upload=0B/s
[INFO] [08-30|08:11:16.210] [1/15 Snapshots] download                peers=1 connections=1 files=156 alloc=68.0MB sys=219.5MB
[INFO] [08-30|08:11:36.210] [1/15 Snapshots] download                progress="99.98% 20.8GB/20.8GB" download-time-left=999hrs:99m total-download-time=1h6m20s download=0B/s upload=0B/s
[INFO] [08-30|08:11:36.210] [1/15 Snapshots] download                peers=0 connections=0 files=156 alloc=55.1MB sys=219.5MB

```
````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
- stop erigon
- ./build/bin/downloader --log.console.verbosity=4
- it will show 1-2 problematic files
- remove them from folder `datadir/snapshots`. For example if file `v1-038500-039000-transactions.seg` has problem, do `rm <datadir>/snapshots/v1-038500-039000-*`
- remove folder `datadir/snapshots/db`
- start erigon
- write here with which files you had problems

**Comment by nivshitrit** [comment]
> * stop erigon
> * ./build/bin/downloader --log.console.verbosity=4
> * it will show 1-2 problematic files
> * remove them from folder `datadir/snapshots`. For example if file `v1-038500-039000-transactions.seg` has problem, do `rm <datadir>/snapshots/v1-038500-039000-*`
> * remove folder `datadir/snapshots/db`
> * start erigon
> * write here with which files you had problems

i left running for more hours and suddenly it has finished downloading. it now attempts to download part 2/15 and i get this 2 logs over and over again in a loop, should i create a new issue for this ?

`[INFO] [08-30|12:49:44.810] [2/15 Headers] No block headers to write in this log period block number=25999999
[INFO] [08-30|12:49:44.810] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0`

**Comment by AskAlexSharov** [comment]
Do you have external ConsensusLayer? Or using —internalcl?

**Comment by SuperEdison** [comment]
INFO[09-12|16:46:03.413] [torrent] Start                          my peerID=2d4754303030332d6d27cc4c5cad167fa00406a3
INFO[09-12|16:46:03.413] Started gRPC server                      on=127.0.0.1:9093
INFO[09-12|16:46:23.414] [snapshots] Downloading                  progress="0.00% 0B/0B" download=0B/s upload=0B/s peers=0 conns=0 files=0
INFO[09-12|16:46:43.414] [snapshots] Seeding                      up=0B/s peers=0 conns=0 files=0
INFO[09-12|16:47:03.413] [snapshots] Seeding                      up=0B/s peers=0 conns=0 files=0
INFO[09-12|16:47:23.414] [snapshots] Seeding                      up=0B/s peers=0 conns=0 files=0
INFO[09-12|16:47:43.413] [snapshots] Seeding                      up=0B/s peers=0 conns=0 files=0
