### ISSUE TITLE
About erigon-mainnet-snapshot	

### ISSUE THREAD

**Issue by harveyff** [ledgerwatch/erigon#8125]
Hi team,

Thank you for your great work,

I plan synchronize the archive node of polygon, is there a latest incremental snapshot, I see from the [snapshot page](https://snapshots.polygon.technology/) of polygon that it is still in preparation,
```
erigon-mainnet-snapshot | Under maintenance. ETA Aug 2023 for Erigon bor-mainnet incremental snapshots.
```

best wishes

**Comment by AskAlexSharov** [comment]
hi. we don't maintain this snapshots.

**Comment by AskAlexSharov** [comment]
Hi. This page is not part of Erigon project. Please contact with Polygon team (they are also in our Discord). Thank you.
