### ISSUE TITLE
MacOS user home dir fails to be created

### ISSUE THREAD

**Issue by christophercampbell** [ledgerwatch/erigon#8130]
#### System information

Erigon version: erigon version 2.37.0-dev-ed9b1ca7

OS & Version: OSX

Commit hash: ed9b1ca7

#### Expected behaviour

`make user_macos` should not fail

#### Actual behaviour

```
» make user_macos                                                                                                   
sudo dscl . -create /Users/erigon
sudo dscl . -create /Users/erigon UserShell /bin/bash
sudo dscl . -list /Users UniqueID | grep erigon | grep 3473 || sudo dscl . -create /Users/erigon UniqueID 3473
sudo dscl . -create /Users/erigon PrimaryGroupID 3473
sudo dscl . -create /Users/erigon NFSHomeDirectory /Users/erigon
sudo dscl . -append /Groups/admin GroupMembership erigon
sudo -u erigon mkdir -p ~erigon/.local/share
mkdir: /Users/erigon: Permission denied
make: *** [user_macos] Error 1
```

The dev user has sudo, and previous admin commands succeed. I believe it may be that the failed command is run as `erigon` so does not have permissions to create the directory.

Subsequently, `docker compose up` components report fatal errors because they cannot create file system artifacts. For example:

```
erigon-rpcdaemon-1   | Fatal: failed to save node key to /.local/share/erigon/nodekey: mkdir /.local: permission denied
erigon-rpcdaemon-1   | Fatal: failed to save node key to /.local/share/erigon/nodekey: mkdir /.local: permission denied
```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/8133
