### ISSUE TITLE
I am running the eth node of erigon and the disk occupies 3.2T. Is this normal?

### ISSUE THREAD

**Issue by kledgold** [ledgerwatch/erigon#8148]
I am running the eth node of erigon and the disk occupies 3.2T. Is this normal?

**Comment by AskAlexSharov** [comment]
Yes. Can also show
make db-tools
./build/bin/mdbx_stat -ef datadir/chaindata

**Comment by Giulio2002** [comment]
You probably collected detritus as fragmented data
