### ISSUE TITLE
Long response times for eth_getLogs on relatively recent blocks

### ISSUE THREAD

**Issue by klkvr** [ledgerwatch/erigon#8188]
Following eth_getLogs request
```
{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1147f5b", "toBlock": "0x114872b"}],"id":0}
```
Takes more than a minute to complete on my erigon node on the first run. Geth/Alchemy respond in under 5s

It seems that erigon has some caching happening under the hood. However, such response times on cold cache make indexing via erigon very hard. Are such long response times expected or am I doing something wrong?

**Comment by AskAlexSharov** [comment]
1. do you have --prune flags?
2. there is PageCache in our OS. What is your use-case - index large ranges of blocks? or read 1 exact old block?

**Comment by klkvr** [comment]
1. No
2. Just indexing of events from some point of history until now. I am just calling getLogs on ranges 2000 blocks wide

**Comment by AskAlexSharov** [comment]
For large range indexing use-case - don't need to care about individual 1 block cold-machine call - you just need send a bit more parallel requests - it will automatically warmup cold data (just by parallel touching some co-located data).  
first try increase parallelism on server-side: 
- increate --db.read.concurrency
- increase --db.batch.concurrency

If doesn't help - then try: 
- make batches smaller and send them in-parallel from client side.

**Comment by AskAlexSharov** [comment]
1. if you don't have pruning - try call eth_getBlockReciepts instead of eth_getLogs. As i remember it will read receipts from db instead of re-executing old blocks. eth_getLogs is built for custom complex filtering and probably always re-exec old blocks even if you have receipts in db.
