### ISSUE TITLE
Is it possible to reconstruct specific block data?

### ISSUE THREAD

**Issue by rayn316** [ledgerwatch/erigon#8190]
When running the archive node, it is found that some block data is empty. Some blocks may be damaged due to node kill, but the node can be synchronized normally.
I wonder if the integration tool can reconstruct the data at a specific block height?

**Comment by AskAlexSharov** [comment]
no, don't have such tool. only have command to drop all blocks from db: "integration stage_headers --reset" - erigon will re-download them
