### ISSUE TITLE
eth_getLogs cannot accept block strings other than "latest"

### ISSUE THREAD

**Issue by BrendanChou** [ledgerwatch/erigon#8199]
#### System information

Latest (devel branch)

Commit hash: 9c4797847265437d5dd1d00bdba23d549b5db2b1

#### Expected behaviour

Geth and other providers accept using `"finalized"` as a block identifier for the purposes of getting logs. Erigon also supports `"finalized"` for some block identifiers such as to `eth_getBlockByNumber`. This behavior should be ported correctly for the `eth_getLogs` RPC call.

As of writing, Geth, Reth, and Nethermind all support this behavior

#### Actual behaviour

Throws error: `"negative value for ToBlock: -4"`

#### Steps to reproduce the behaviour

`eth_getBlockByNumber` works okay:
```
curl \
-X POST \
-H 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["finalized", false],"id":0}' \
<ERIGON_NODE_URL>
```
```
{"jsonrpc":"2.0","result": ... }
```

**`eth_getLogs` fails:**
```
curl \
-X POST \
-H 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"finalized"}],"id":0}' \
<ERIGON_NODE_URL>
```
```
{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"negative value for FromBlock: -4"}}
```

#### More Info

The bug is [here](https://github.com/ledgerwatch/erigon/blob/devel/turbo/jsonrpc/eth_receipts.go#L122) where you exclude only `rpc.LatestBlockNumber` and do not consider-valid the other "magic int values" defined [here](https://github.com/ledgerwatch/erigon/blob/devel/rpc/types.go#L80)

**Comment by AskAlexSharov** [comment]
Have fun

**Comment by pyropy** [comment]
@BrendanChou Looking at the [ETH JSON-RPC API Docs](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs) seems like `eth_getLogs` supports values `latest
`, `pending` or  `earliest`. On the other hand RPC Provider QuickNode in their docs states that supported values are `latest`, `pending`, `safe` and `finalized`.

Should we comply with ETH docs and maybe add other supported values to `erigon` namespace or?

**Comment by BrendanChou** [comment]
Safe and Finalized we're added as a result of moving to proof-of-stake. It's not clear to me where the official documentation/specs are kept
