### ISSUE TITLE
Broken metric type format for rpc_duration_seconds

### ISSUE THREAD

**Issue by jakubgs** [ledgerwatch/erigon#8214]
#### System information

Erigon version: `2.49.1`

#### Expected behaviour
Correct format of `rpc_duration_seconds` metric type.

#### Actual behaviour
Prometheus fails to scrape metrics because of wrong format of `TYPE` line:
```
 > curl -s http://localhost:7063/debug/metrics/prometheus | grep TYPE | grep rpc
# TYPE rpc_duration_seconds{method="engine_exchangeTransitionConfigurationV1",success="success"} summary
# TYPE rpc_duration_seconds{method="engine_forkchoiceUpdatedV2",success="success"} summary
# TYPE rpc_duration_seconds{method="engine_newPayloadV2",success="success"} summary
# TYPE rpc_duration_seconds{method="eth_syncing",success="success"} summary
# TYPE rpc_failure counter
# TYPE rpc_total counter
```
Result:
```
invalid metric type "method=\"admin_nodeInfo\",success=\"success\"} summary"
```
Those labels should not be visible there. Because of this all Erigon metrics are un-scrapable.

#### Steps to reproduce the behaviour

Just look at the metrics endpoint output.

**Comment by angusscott** [comment]
Already captured by https://github.com/ledgerwatch/erigon/issues/8181

**Comment by jakubgs** [comment]
Any news on this? Do you recommend downgrading from `2.49.1` to mitigate this because we're missing all Erigon metrics because of this bug.

**Comment by matcra587** [comment]
fwiw, I had to revert to `2.48.1` for it to start working again.

**Comment by jakubgs** [comment]
Can confirm `2.50.2` has fixed this issue. Thank you for fixing it.
