### ISSUE TITLE
newPayload failed / error executing clstage - CatchUpBlocks err="parent's total difficulty not found with hash

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#8218]
#### System information

2.49.1

Linux

Erigon Command (with flags/config):

erigon --datadir='data' \
          --ethash.dagdir='data/ethash-dags' \
          --chain='mainnet' \
          --torrent.port=31014 \
          --private.api.addr='127.0.0.1:31013' \
          --torrent.download.rate='10000mb' \
          --batchSize='512MB' \
          --etl.bufferSize='512MB' \
          --nat='extip:x.x.x.x' \
          --http=false \
          --db.pagesize='16KB' \
          --p2p.protocol='66,67,68' \
          --p2p.allowed-ports='11310,11311,11312,11313,11314,11315,11316,11317,11318,11319' \
          --authrpc.jwtsecret='data/jwt.hex' \
          --authrpc.addr='127.0.0.1' \
          --authrpc.port=31019 \
          --lightclient.discovery.addr='x.x.x.x' \
          --lightclient.discovery.port=31017 \
          --lightclient.discovery.tcpport=31018 \
          --internalcl

Concensus Layer: internalcl

Chain/Network: Ethereum mainnet

`error executing clstage                  app=caplin stage=CatchUpBlocks err="parent's total difficulty not found with hash c66efb7ea78be28070aa386a4f7c3d9c42fa3deef8c8f5dbf604bc765cf5f32f and height 18149112: <nil>"`
`newPayload failed                        err="parent's total difficulty not found with hash 675fa522586f775322380601a2ff5a67f8a45f1d1e38423084c0d820853f4708 and height 18149113: <nil>"`

[erigon.log](https://github.com/ledgerwatch/erigon/files/12640935/erigon.log)

**Comment by Giulio2002** [comment]
https://github.com/ledgerwatch/erigon/pull/8222

**Comment by mbwmbw1337** [comment]
Same issue.

**Comment by mbwmbw1337** [comment]
> #8222

It seems to have fixed updating to:
```
/home/erigon/erigon/build/bin/erigon --version
erigon version 2.49.2-stable-a8ae8a03
```

**Comment by PeaStew** [comment]
> > #8222
> 
> It seems to have fixed updating to:
> 
> ```
> /home/erigon/erigon/build/bin/erigon --version
> erigon version 2.49.2-stable-a8ae8a03
> ```

Just restarting 'fixes' the issue :) but we need a proper fix

**Comment by Giulio2002** [comment]
Fixed completely
