### ISSUE TITLE
 [1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=8499999 min_in_db=8838000

### ISSUE THREAD

**Issue by penonds** [ledgerwatch/erigon#8233]
Erigon: 2.48.1
os：linux ubuntu
chain：goerli

integration print_stages --chain goerli
![image](https://github.com/ledgerwatch/erigon/assets/143255999/482e624b-e228-4d3e-b01b-5f3c3c2c551a)

warn: 
[1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=8499999 min_in_db=8838000

**Comment by AskAlexSharov** [comment]
Try “integration stage_headers —reset”

**Comment by penonds** [comment]
> integration

I run “ integration stage_headers —reset” through docker exec when container is running, but the execution would stay in the “logging to file system ... ”for a long time , and the execution was not successful.

**Comment by AskAlexSharov** [comment]
Stop erigon

**Comment by penonds** [comment]
> Stop erigon

Resolved Thanks
