### ISSUE TITLE
Corrupted transactions in `engine_getPayloadBodiesByRangeV1`

### ISSUE THREAD

**Issue by michaelsproul** [ledgerwatch/erigon#8245]
#### System information

Erigon version: v2.49.2 and v2.49.1
Chain/Network: Mainnet, and Gnosis chain

#### Expected behaviour

Erigon's `getPayloadBodiesByRangeV1` should return the correct transaction bytes to the caller.

#### Actual behaviour

On the Lighthouse issue tracker we've had several reports of Erigon producing incorrect data on the payload bodies endpoint. Lighthouse checks that payload bodies match their payload header (i.e. the transactions_root & withdrawals_root), and that check is sometimes failing.

LH bug report with context is here: https://github.com/sigp/lighthouse/issues/4739

Recently @xrchz ran the `getPayloadBodiesByRangeV1` query for a couple of blocks, showing exactly how Erigon's responses deviate from what is expected (I checked against Reth and Besu for comparison):

- Data for block 0x1144c42: https://gist.github.com/michaelsproul/dd2a94f75e5f62fde761b70e4ad0293e
- Data for block 0x115478a: https://gist.github.com/michaelsproul/f6f347bd6ce357e128580e5eedbaab7e

I've seen this reported by 3 Lighthouse-Erigon users, on mainnet (x2) and Gnosis chain. I guess it could be caused by database corruption. Hopefully the bytes of the response are meaningful to an Erigon dev and it's just a simple encoding issue.

**Comment by xrchz** [comment]
> Recently @xrchz ran the `getPayloadBodiesByRangeV1` query for a couple of blocks, showing exactly how Erigon's responses deviate from what is expected

It was erigon 2.49.2 producing these

**Comment by michaelsproul** [comment]
Thanks! Updated the description

**Comment by xrchz** [comment]
Same error continues in erigon version 2.50.2

**Comment by mans17** [comment]
Same errors continues in erigon 2.51.0-a952e91f/linux-amd64/go1.20.7 
(I guess you know, but if you need some << dangerous >> tests to be done, I've a "no staking in progress" synced with this error).

**Comment by michaelsproul** [comment]
@Giulio2002 I know you're v busy, but any idea what this could be?

**Comment by Giulio2002** [comment]
Fixed in https://github.com/ledgerwatch/erigon/pull/8416

**Comment by nateq314** [comment]
@Giulio2002 also posting here for completeness... should this issue be reopened, due to the revert?

**Comment by yperbasis** [comment]
> @Giulio2002 also posting here for completeness... should this issue be reopened, due to the revert?

Nope, it was better fixed by PR #8427
