### ISSUE TITLE
error: first run for txIndex 0 error

### ISSUE THREAD

**Issue by ironmask285** [ledgerwatch/erigon#8246]
I setup erigon for goerli network. But I called rpc api , it show error : WARN[09-20|13:29:30.341] Served                                   conn=127.0.0.1:53650 method=trace_block reqid=1 t=327.476874ms err="first run for txIndex 0 error: nonce too high: address 0x8EA825A5Fd77fD4180Da0BB0c14309925c991b58, tx: 1030 state: 0"
please help me !

**Comment by ironmask285** [comment]
noted :  I run without --prune option

**Comment by quick-pawiromitchel** [comment]
experiencing the same issue
{"method":"trace_block","params":["0x1181414"],"id":1,"jsonrpc":"2.0"}

full error is `first run for txIndex 0 error: nonce too high: address 0x0000000000000000000000000000000000000000, tx: xxxx state: 0`

Block numbers:
18345924
18345935
18345941
18356366
18356824
etc ...

Goes away whenever Erigon is restarted

**Comment by somnathb1** [comment]
Hopefully fixed by https://github.com/ledgerwatch/erigon/pull/10737
