### ISSUE TITLE
"failed creating sentinel listener" when reality is error is in creating lightclient DISCV5 protocol

### ISSUE THREAD

**Issue by mbwmbw1337** [ledgerwatch/erigon#8273]
"failed creating sentinel listener" when reality is error is in creating lightclient DISCV5 protocol

```
 /home/erigon/erigon/build/bin/erigon --version
erigon version 2.50.0-dev-13720af4
```

Error displayed `Sep 22 09:52:31 dal-edge-3.glexia.com bash[2337165]: failed creating sentinel listener err=listen udp4 0.0.0.0:4000: bind: address already in use`

**Comment by Giulio2002** [comment]
I mean that is what it is, I will improve the error message
