### ISSUE TITLE
Even though prune is set to create a recent archive node, API calls still only return latest 90000 blocks

### ISSUE THREAD

**Issue by dreadedhamish** [ledgerwatch/erigon#8284]
I have a recent archive node set up with the pruning flags below (prune everything before 1649269). Erigon has been synced for at least 2 months without issue.
When I make API calls to Erigon they consistently return a null result before block 18308999, which is 90832 blocks ago.
Becuase that number is so close to 90000, the default for prune=hrtc, I hazard a guess that even though I've specified the range to retain Erigon has used the default values regardless.

To test if Erigon was seeing the flags I removed them and for the following error on startup:
Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.r.older=90000 --prune.h.before=16492698 --prune.t.before=16492698 --prune.c.before=16492698"
| not allowed change of --prune flag, last time you used: --prune.r.older=90000 --prune.h.before=16492698 --prune.t.before=16492698 --prune.c.before=16492698

So Erigon is seeing the flags, but it appaers not respecting them and instead using the defaults.

How can I fix this?

Hamish

#### System information

Erigon version: `latest`

OS & Version: Docker on Manjaro (latest)

Erigon Command (with flags/config):
 command: |
      --prune.h.before=16492698 --prune=r --prune.t.before=16492698 --prune.c.before=16492698
      ...

Concensus Layer: Prysm

Chain/Network: Pulsechain

#### Expected behaviour
Ability to query through the API all transactions above the prune-before block.

#### Actual behaviour
Can only query the alst 90K blocks.

**Comment by dreadedhamish** [comment]
Actually I've narrowed it down - when I run the RPC through the main erigon image then I can scan the entire range. 
However when I run a seperate rpcdaemon it connects OK but has this 90K block limitation.

How do I make the dedicated rpcdaemon see all the blocks?

**Comment by AskAlexSharov** [comment]
show erigon logs
