### ISSUE TITLE
Unable to get peers on Holesky, endlessly regenerating

### ISSUE THREAD

**Issue by jakubgs** [ledgerwatch/erigon#8320]
#### System information

Erigon version: `2.49.3`
OS & Version: Ubuntu 22.04
Erigon Command (with flags/config):
```
--chain=holesky
--maxpeers=20
--nat=extip:194.33.40.246
--allow-insecure-unlock
--datadir=/data
--mine=true
--miner.sigfile=/keys/sigfile
--prune=hrtc
--metrics
--metrics.addr=0.0.0.0
--metrics.port=6061
--http
--http.addr=0.0.0.0
--http.port=8546
--http.api=eth,net,erigon,admin,engine
--authrpc.addr=0.0.0.0
--authrpc.port=8552
--authrpc.jwtsecret=/keys/jwtsecret
--v5disc=true
--nodiscover=false
```
Concensus Layer: Nimbus Beacon Node `23.9.1`
Chain/Network: `holesky`

#### Expected behaviour
The node can find peers and helps with attestations.

#### Actual behaviour
The node cannot find peers:
```
 > curl -s 0:6064/debug/metrics/prometheus | grep p2p_peers
# TYPE p2p_peers gauge
p2p_peers 0

 > ./rpc.sh admin_peers
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": []
}
```
And peers cannot be added manually. I have tried creating `static-nodes.json`, `trusted-nodes.json`, and using the `admin_addPeer` RPC method. The files seem to be ignored, and the RPC method doesn't exist:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32601,
    "message": "the method admin_addPeer does not exist/is not available"
  }
}
```
Which makes no sense to me.

The node itself just keeps printing this in logs:
```json
{"lvl":"info","msg":"[5/6 IntermediateHashes] Regeneration trie hashes started","t":"2023-09-28T15:44:21.544146331Z"}
{"hash":"0x69d8c9d72f6fa4ad42d4702b433707212f90db395eb54dc20bc85de253788783","lvl":"info","msg":"[5/6 IntermediateHashes] Trie root","t":"2023-09-28T15:44:21.545434523Z"}
{"lvl":"info","msg":"[5/6 IntermediateHashes] Regeneration ended","t":"2023-09-28T15:44:21.545558847Z"}
```
And the logs are full of those. The p2p port is `closed` too.

**Comment by racytech** [comment]
what are the nimbus flags?

**Comment by jakubgs** [comment]
Same ones that work perfectly fine with 10 Geth nodes and 10 Nethermind nodes:
```
--network=holesky
--history=prune
--jwt-secret=/data/beacon-node-holesky-stable/jwt.hex
--el=http://localhost:8552
--tcp-port=9001
--udp-port=9001
--max-peers=320
--sync-light-client=false
--subscribe-all-subnets=false
--doppelganger-detection=true
--num-threads=0
--rest=true
--rest-address=0.0.0.0
--rest-port=9301
--rest-max-body-size=16384
--rest-max-headers-size=128
--metrics=true
--metrics-address=0.0.0.0
--metrics-port=9201
--validator-monitor-auto=true
--validator-monitor-details=false
```

**Comment by racytech** [comment]
Thanks! Investigating...

**Comment by racytech** [comment]
Please remove --nodiscover=false since it set to false by default and it seems that --nodiscover does not accept a value, so when you set it like `--nodicover=false` it doesn't read the value and assumes it true.

**Comment by jakubgs** [comment]
Sure, I can do that, but honestly, but we use the same flags on Mainnet and Prater erigon nodes and it works fine:
```
 > grep nodiscover docker-compose.yml          
      --nodiscover=false
 > ./rpc.sh admin_peers | jq '.result | length'
19
```

Done: https://github.com/status-im/infra-role-erigon/commit/5ee43ddf
Will roll it out soon, gotta go out for a bit though. Thanks for investigating this.

But it would be good to fix that flag formatting if possible.

**Comment by jakubgs** [comment]
Actually, it appears you are right. I can see some peers on a changed node:
```
admin@linux-11.ih-eu-mda1.nimbus.holesky:~ % grep nodisc /docker/erigon-holesky-01/docker-compose.yml 
admin@linux-11.ih-eu-mda1.nimbus.holesky:~ % /docker/erigon-holesky-01/rpc.sh admin_peers | jq '.result[].name'
"Geth/v1.13.1-stable-3f40e65c/linux-amd64/go1.21.1"
"erigon/v2.49.3-stable-411913dd/linux-amd64/go1.20.8"
"Geth/v1.13.1-stable-3f40e65c/linux-amd64/go1.21.1"
```
I think you caught the correct bug.

**Comment by racytech** [comment]
Cam I close this issue? Or you need something else?

**Comment by jakubgs** [comment]
Sorry, we were just verifying. Thank you for you help. I believe this was the cause of lack of peers.

We are investigating some other issue on Holesky related to Erigon, but we will open a separate issue when we some more info.
