### ISSUE TITLE
Prometheus metric error after upgrade to v2.49.3

### ISSUE THREAD

**Issue by Johnaverse** [ledgerwatch/erigon#8322]
#### System information

Erigon version: erigon version 2.49.3-stable-411913dd
Lighthouse: v4.5.0-441fc16

Chain: Holesky Testnet, polygon

Prometheus metric error after upgrade to v2.49.3
`invalid metric type "method=\"engine_exchangeCapabilities\",success=\"success\"} summary"`

Prometheus Endpoint: `/debug/metrics/prometheus`

**Comment by sbond14** [comment]
Seeing the same thing here after upgrading to 2.50.1

Error: Invalid metric name: rpc_duration_seconds{method="engine_exchangeTransitionConfigurationV1",success="success"}_time

**Comment by chichi13** [comment]
I confirm the problem on my side in `2.50.1`, prometheus cannot process the information. The problem seems to be here:

```
rpc_duration_seconds{method="eth_getLogs",success="success"}_time 300.000000
rpc_duration_seconds{method="eth_getLogs",success="success"}_sum 0.000000
rpc_duration_seconds{method="eth_getLogs",success="success"}_count 5
...
rpc_duration_seconds{method="eth_syncing",success="success"}_time 300.000000
rpc_duration_seconds{method="eth_syncing",success="success"}_sum 0.000000
rpc_duration_seconds{method="eth_syncing",success="success"}_count 5
```

**Comment by jmc000** [comment]
[v2.50.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.50.2) seems to have fixed this problem

> Metrics label fixes by @mh0lt in https://github.com/ledgerwatch/erigon/pull/8339

upgraded from `v2.50.1` to `v2.50.2` and it fixed the Prometheus error we had w/ @chichi13 , thanks!

**Comment by AymericNoel** [comment]
Just upgraded to `v2.50.2` and prometheus metrics up again, thanks !

**Comment by Johnaverse** [comment]
v2.50.2 work for me too
