### ISSUE TITLE
Internal CL Download History Progress Reverted

### ISSUE THREAD

**Issue by shunsukew** [ledgerwatch/erigon#8334]
#### System information

Erigon version: `./erigon --version`
```
erigon version 2.49.2-stable
```

OS & Version: Windows/Linux/OSX
```
Linux Ubuntu 2204 latest
```

Erigon Command (with flags/config)
```
/usr/local/bin/erigon --chain=goerli \
  --datadir=/data/erigon \
  --torrent.download.rate=125mb \
  --maxpeers 15 \
  --private.api.addr=localhost:9090 \
  --metrics.addr=0.0.0.0 \
  --metrics.port=6060 \
  --pprof \
  --pprof.addr=0.0.0.0 \
  --pprof.port=6061 \
  --internalcl
```

Concensus Layer: Internal CL

Chain/Network: Goerli

#### Expected behaviour
CL Download History resumes from block number where process stopped last time.

#### Actual behaviour
Block number reverted when restarting node process.

#### Steps to reproduce the behaviour
Restart node process.

Currently, syncing Goerli archive node with Internal CL.
Initially, I ran node without `--internalcl` flag, added it later because block sync stopes at `0x81b31f`.
As we can see in the first image, Download history progress reached to `5951279` after leaving it for about 4~5 days. However, restarting node reverts progress to `6636192` (2nd image). 

(Before Restart)
<img width="1469" alt="Screen Shot 2023-10-01 at 16 58 46" src="https://github.com/ledgerwatch/erigon/assets/28953860/163d0fcc-87c2-46ff-9d3a-c7cb1b1ec952">

(After Restart)
<img width="1460" alt="Screen Shot 2023-10-01 at 16 58 23" src="https://github.com/ledgerwatch/erigon/assets/28953860/a8bd7ed0-21bd-4a4e-b1d1-666b955fe8a2">

**Comment by shunsukew** [comment]
I assume it’s because downloaded data is not written to the disk. Configuring frequency to flush data would be helpful. Approx 700000 blocks without being written to the disk is too large.

**Comment by Giulio2002** [comment]
progress for that stage is not saved at the moment, I will make a separate issue for that.

**Comment by wbelhomsi** [comment]
Did your node manage to work?
I have a similar issue, initially ran it without internalcl then the node got stuck at `0x81b31f` I turned on `internalcl` and left it for a couple of days, and it is still stuck at the same block number
```
{"jsonrpc":"2.0","id":67,"result":"0x81b31f"}
```
Current Logs show no issues (tried restarting it multiple times)
![Screenshot 2023-11-23 at 10 17 20 AM](https://github.com/ledgerwatch/erigon/assets/40052755/3362d22e-c3fd-4116-8f2f-7b33b548f744)
