### ISSUE TITLE
Storage Requirements for Sepolia and Goerli

### ISSUE THREAD

**Issue by shunsukew** [ledgerwatch/erigon#8335]
In the [README](https://github.com/ledgerwatch/erigon#system-requirements), it is mentioned that 

For an Archive node of Ethereum Mainnet we recommend >=3TB storage space: 1.8TB state (as of March 2022), 200GB temp files (can symlink or mount folder <datadir>/temp to another disk). Ethereum Mainnet Full node ( see --prune* flags): 400Gb (April 2022).

What about testnets such as Sepolia and Goerli? Also, in case with running archive node with internal CL.

**Comment by AskAlexSharov** [comment]
sepolia: 338G, goerli: i don't know

**Comment by mikolajsobolewski** [comment]
goerli: 882G

**Comment by shunsukew** [comment]
Thank you so much for the information.
