### ISSUE TITLE
Does erigon internal CL supports checkpoint sync?

### ISSUE THREAD

**Issue by shunsukew** [ledgerwatch/erigon#8340]
Erigon node takes long time for `Downloading History` process in case `--internalcl` flag is enabled.
Does it support checkpoint sync so that node can finish initial sync faster? If it has, how can I enable that option?
(As long as I can see, I couldn't find info in docs and help command in version `2.49.2`)

**Comment by Giulio2002** [comment]
it does it already, that is erigon syncing actually. it is actually more performant this wqy
