### ISSUE TITLE
UpdateForkChoice: needs to be used in tests

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8365]
Currently tests are using: `MockSentry.InsertChain -> insertPoS -> StageLoopIteration`
As a result - existing tests do not test UpdateForkChoice logic and can't catch bugs in UpdateForkChoice. 

I fixed couple bugs in updateForkChoice:
- pruning was missed 
- erigon3 `rawdbv3.TxNums.Truncate` was called wrong way - existed some tests

I understand that UpdateForkChoice is not compatible - and changing a lot. But it make sense to adopt at-least some existing tests (for example `jsonrpc` package tests) to use UpdateForkChoice.

**Comment by Giulio2002** [comment]
Ok, so are we talking about spectest?

**Comment by Giulio2002** [comment]
I can try doing spectests
