### ISSUE TITLE
rpcdaemon call_tracer crash in debug_traceBlockByNumber call

### ISSUE THREAD

**Issue by hitdavid** [ledgerwatch/erigon#8379]
#### System information

Erigon version: `rpcdaemon at devel branch (8850f3a)`

OS & Version: Linux/OSX

Commit hash: 8850f3a

Erigon Command (with flags/config): rpcdaemon

Concensus Layer: prysm

Chain/Network: ethereum

#### Expected behaviour

call
```
curl http://<IP>:<PORT> \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"debug_traceBlockByNumber","params":["0x116E138", {"tracer": "callTracer", "tracerConfig": {"withlog": true}}], "id":1,"jsonrpc":"2.0"}'
```
and return a trace of block

#### Actual behaviour

rpcdaemon crashed

#### Steps to reproduce the behaviour

run rpcdaemon of code release v2.50.2, run test

#### Backtrace

````
EROR[10-05|07:24:30.929] RPC method debug_traceBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:219 panic.go:884 panic.go:260 signal_unix.go:841 arc.go:67 bor.go:152 bor.go:465 evm.go:39 tracing.go:60 tracing.go:97 tracing.go:32 value.go:586 value.go:370 service.go:224 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
````

**Comment by hitdavid** [comment]
I debug the code of version devel (8850f3a),
call the test debug_traceBlockByNumber req, and failed at bor.go L152

https://github.com/ledgerwatch/erigon/blob/7dd678896ae68fcadb996f07b6146cae6fab8a85/consensus/bor/bor.go#L148-L173

sigcache.Get(hash) may cause a deadlock in my computer

**Comment by hitdavid** [comment]
release v2.50.1 or before are OK after patched this hotfix https://github.com/ledgerwatch/erigon/pull/8369

**Comment by yperbasis** [comment]
Please re-open this issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
