### ISSUE TITLE
polygon bor-mainnet panic: runtime error: invalid memory address or nil pointer dereference v2.51.0

### ISSUE THREAD

**Issue by cheneyweb** [ledgerwatch/erigon#8406]
#### System information

Erigon version: 2.51.0-a0160bee

OS & Version: AlmaLinux v9.2

Commit hash: 

Erigon Command (with flags/config):

/root/erigon-stable/build/bin/erigon --datadir=/mnt/backup/polygon \
--ethash.dagdir=/mnt/backup/polygon/ethash \
--chain=bor-mainnet \
--port=20303 \
--http.addr=0.0.0.0 \
--http.port=28545 \
--authrpc.port=28551 \
--torrent.port=22069 \
--p2p.allowed-ports=20303,20304,20305,20306,20307 \
--private.api.addr=127.0.0.1:29090 \
--bor.heimdall=https://heimdall-api.polygon.technology \
--http \
--http.api=eth,debug,net,trace,web3,erigon,bor,txpool \
--db.size.limit=10TB \
--db.pagesize=16KB

Concensus Layer:
https://heimdall-api.polygon.technology

Concensus Layer Command (with flags/config):

Chain/Network: 
bor-mainnet

#### Expected behaviour
normal startup

#### Actual behaviour

When I upgraded from 2.49.3 to 2.51.0 it wouldn't start up!

I've tried deleting the txpool folder, but it doesn't work

What should I do for it?

#### Backtrace

````
3|erigon-polygon  | [INFO] [10-09|10:08:18.518] logging to file system                   log dir=/mnt/backup/polygon/logs file prefix=erigon log level=info json=false
3|erigon-polygon  | [INFO] [10-09|10:08:18.518] Build info                               git_branch=release/2.51 git_tag=v2.51.0 git_commit=a0160beee4032491501d89c5347bb1c4710ee6cc
3|erigon-polygon  | [INFO] [10-09|10:08:18.518] Starting Erigon on Bor Mainnet...
3|erigon-polygon  | [INFO] [10-09|10:08:18.518] Maximum peer count                       ETH=100 total=100
3|erigon-polygon  | [INFO] [10-09|10:08:18.518] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon,bor,txpool
3|erigon-polygon  | [INFO] [10-09|10:08:18.519] torrent verbosity                        level=WRN
3|erigon-polygon  | [INFO] [10-09|10:08:20.621] Set global gas cap                       cap=50000000
3|erigon-polygon  | [INFO] [10-09|10:08:20.622] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
3|erigon-polygon  | [INFO] [10-09|10:08:20.622] Opening Database                         label=chaindata path=/mnt/backup/polygon/chaindata
3|erigon-polygon  | [INFO] [10-09|10:08:21.972] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
3|erigon-polygon  | [INFO] [10-09|10:08:43.416] Initialising Ethereum protocol           network=137
3|erigon-polygon  | [INFO] [10-09|10:08:43.416] Opening Database                         label=bor path=/mnt/backup/polygon/bor
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] Starting private RPC server              on=127.0.0.1:29090
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] new subscription to logs established
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] rpc filters: subscribing to Erigon events
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] New txs subscriber joined
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] new subscription to newHeaders established
3|erigon-polygon  | [INFO] [10-09|10:08:43.615] Reading JWT secret                       path=/mnt/backup/polygon/jwt.hex
3|erigon-polygon  | [INFO] [10-09|10:08:43.616] HTTP endpoint opened for Engine API      url=127.0.0.1:28551 ws=true ws.compression=true
3|erigon-polygon  | [INFO] [10-09|10:08:43.616] HTTP endpoint opened                     url=[::]:28545 ws=false ws.compression=true grpc=false
3|erigon-polygon  | [WARN] [10-09|10:08:43.616] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
3|erigon-polygon  | [WARN] [10-09|10:08:43.616] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
3|erigon-polygon  | [INFO] [10-09|10:08:43.619] Started P2P networking                   version=67 self=enode://ea701a505e25af0929d42bf4fea1a37fd88333ab9c55dce3ca53bfa78fe3121f5e01b618321a01d17456a409c99b142124c81fc58e6e87e341006bc0f9039e69@127.0.0.1:0 name=erigon/v2.51.0-a0160bee/linux-amd64/go1.20.6
3|erigon-polygon  | [INFO] [10-09|10:08:43.619] Started P2P networking                   version=68 self=enode://ea701a505e25af0929d42bf4fea1a37fd88333ab9c55dce3ca53bfa78fe3121f5e01b618321a01d17456a409c99b142124c81fc58e6e87e341006bc0f9039e69@127.0.0.1:0 name=erigon/v2.51.0-a0160bee/linux-amd64/go1.20.6
3|erigon-polygon  | [INFO] [10-09|10:08:43.626] [txpool] Started
3|erigon-polygon  | [INFO] [10-09|10:08:43.635] [1/15 Snapshots] Fetching torrent files metadata
3|erigon-polygon  | [INFO] [10-09|10:08:44.659] Got new checkpoint from heimdall         start=48492198 end=48493477 rootHash=0xe7de6c2be7326f5a60d64fe7d15bceaf978fd05dbf71a8746989f6c5e0bc323f
3|erigon-polygon  | panic: runtime error: invalid memory address or nil pointer dereference
3|erigon-polygon  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf57a78]
3|erigon-polygon  | goroutine 9480 [running]:
3|erigon-polygon  | github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0xc0a215e120?)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/core/types/block.go:1669 +0x38
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.borVerify({0x2f922f0?, 0xc0e33628d0?}, 0xc0e463a380, 0x2e3eea6, 0x2e3f3a5, {0xc0064ca0f2, 0x40}, 0x1)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/bor_checkpoint_verifier.go:143 +0xb38
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.fetchWhitelistCheckpoint({0x2f922f0, 0xc0e33628d0}, {0x2fa4948?, 0xc0d82eb4a0?}, 0xc0064c9e48, 0xc0e463a380)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist_helpers.go:45 +0x57c
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.handleWhitelistCheckpoint({0x2f922f0?, 0xc0e33628d0?}, {0x2fa4948?, 0xc0d82eb4a0?}, 0x0?)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:152 +0x75
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.retryHeimdallHandler(0x2c71e00, 0xc0e463a380, 0x0?, 0x0?, {0x285fd81, 0x14})
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:118 +0xdb
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.RetryHeimdallHandler(...)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:100
3|erigon-polygon  | github.com/ledgerwatch/erigon/eth/borfinality.startCheckpointWhitelistService(0x0?)
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:65 +0x45
3|erigon-polygon  | created by github.com/ledgerwatch/erigon/eth/borfinality.Whitelist
3|erigon-polygon  | 	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:46 +0x225
````

**Comment by cheneyweb** [comment]
When I updated to 2.52.0, the error message changed to the following (and the last version that worked was 2.49.3):

13|erigon- | [INFO] [10-11|09:49:03.330] logging to file system                   log dir=/mnt/backup/polygon/logs file prefix=erigon log level=info json=false
13|erigon- | [INFO] [10-11|09:49:03.330] Build info                               git_branch=release/2.52 git_tag=v2.52.0 git_commit=761af94b2296d6fd4a5cd6f11666837d5841a2b6
13|erigon- | [INFO] [10-11|09:49:03.330] Starting Erigon on Bor Mainnet...
13|erigon- | [INFO] [10-11|09:49:03.331] Maximum peer count                       ETH=100 total=100
13|erigon- | [INFO] [10-11|09:49:03.331] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon,bor,txpool
13|erigon- | [INFO] [10-11|09:49:03.331] torrent verbosity                        level=WRN
13|erigon- | [INFO] [10-11|09:49:05.433] Set global gas cap                       cap=50000000
13|erigon- | [INFO] [10-11|09:49:05.434] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
13|erigon- | [INFO] [10-11|09:49:05.434] Opening Database                         label=chaindata path=/mnt/backup/polygon/chaindata
13|erigon- | [INFO] [10-11|09:49:06.776] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
13|erigon- | [EROR] [10-11|09:49:06.778] Erigon startup                           err="openClient: torrentcfg.openClient: mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: downloader, trace: [kv_mdbx.go:267 downloader.go:640 downloader.go:94 backend.go:1119 backend.go:323 node.go:122 main.go:80 make_app.go:43 command.go:274 app.go:332 app.go:309 main.go:41 proc.go:250 asm_amd64.s:1598]"
13|erigon- | openClient: torrentcfg.openClient: mdbx_env_open: MDBX_CORRUPTED: Maybe free space is over on disk. Otherwise it's hardware failure. Before creating issue please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options., label: downloader, trace: [kv_mdbx.go:267 downloader.go:640 downloader.go:94 backend.go:1119 backend.go:323 node.go:122 main.go:80 make_app.go:43 command.go:274 app.go:332 app.go:309 main.go:41 proc.go:250 asm_amd64.s:1598]

**Comment by AskAlexSharov** [comment]
`label: downloader` please remove datadir/downloader folder

**Comment by cheneyweb** [comment]
I rolled back to version 2.49.3 after executing it for a while, stopped after observing that the logs were fully synchronized and updated to 2.52.0, and then I noticed that I could start up normally again, I didn't delete the datadir/downloader, I don't know if this will have an effect or not, I'll continue to observe the synchronization, thank you very much!

**Comment by mh0lt** [comment]
This seems to have been resolved please re-open if further investigation is required
