### ISSUE TITLE
Ability to sync blocks without execution

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8419]
To simplify block snapshots creation process please allow to sync blocks without executing them.
1. In the past Erigon was able to do so: It did run `STOP_BEFORE_STAGE=Execution`
2. In the past Erigon was able to sync blocks in 1-st sync cycle, now in 1-st cycle it executing blocks from snapshots, in 2-nd downloading and executing blocks in 1-transaction (and loosing all downloaded blocks if restart)
3. erigon also has ` --force.partial.commit` flag, see https://github.com/ledgerwatch/erigon/pull/8299

**Comment by fabiohild** [comment]
Hello sir, is the `--force.partial.commit` never being merged? This is very useful for folks like myself, running a research node on less than ideal hardware. By the time my node finishes processing the snapshots it is 400k blocks behind the tip, and it's slow, taking a few days to do the staged sync. If anything happens meanwhile, I'm back to where the snapshot sync finished (in my case, either power outages or my external ssd overheating and shutting down itself).

This doesn't need to be necessarily a flag, but could be auto turned on if the staged sync is going over more than 10k or 100k blocks.

**Comment by AskAlexSharov** [comment]
Done in E3.
