### ISSUE TITLE
Invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by damianlluch** [ledgerwatch/erigon#8429]
Hi people, I've been working on this project for a few days now. I have managed to synchronize the node, and connect from curl. It has been impossible from web3.
Now I'm getting this error when starting the node.

System information

Erigon 2.51.0

OS & Version: Linux

Command:

```./build/bin/erigon --chain=mumbai --bor.heimdall=https://heimdall-api-testnet.polygon.technology --bor.milestone=true --http=true --http.addr=0.0.0.0 --http.port=8545 --http.compression=true --http.vhosts=* --http.corsdomain=* --ws=true --ws.compression=true --http.api=eth,net,trace,web3,erigon --torrent.download.rate=512mb --torrent.upload.rate=512mb```

Actual behaviour

```
INFO[10-10|12:56:57.193] [5/15 Bodies] Processing bodies...       from=40940501 to=41049390
INFO[10-10|12:57:07.155] Got new milestone from heimdall          start=41049298 end=41049321 hash=0xee855a2c94287ab31200d2eb86a1ae970d11055d8bbc627066d181a1f3140ac8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf3feb8]

goroutine 11621 [running]:
github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0xc027329740?)
        github.com/ledgerwatch/erigon/core/types/block.go:1669 +0x38
github.com/ledgerwatch/erigon/eth/borfinality.borVerify({0x2f3a8f0?, 0xc02504df20?}, 0xc050930310, 0x2725cd2, 0x2725ce9, {0xc02787bf42, 0x40}, 0x0)
        github.com/ledgerwatch/erigon/eth/borfinality/bor_checkpoint_verifier.go:92 +0x525
github.com/ledgerwatch/erigon/eth/borfinality.fetchWhitelistMilestone({0x2f3a8f0, 0xc02504df20}, {0x2f4cce8?, 0xc04ded3860?}, 0xc02d733e48, 0x465c2c0?)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist_helpers.go:80 +0x51e
github.com/ledgerwatch/erigon/eth/borfinality.handleMilestone({0x2f3a8f0?, 0xc02504df20?}, {0x2f4cce8?, 0xc04ded3860?}, 0xc04ecb3f50?)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:172 +0x85
github.com/ledgerwatch/erigon/eth/borfinality.retryHeimdallHandler(0x2c239e8, 0xc050930310, 0xc03db790a0?, 0x46c945?, {0x2808253, 0x13})
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:133 +0x31a
github.com/ledgerwatch/erigon/eth/borfinality.RetryHeimdallHandler(...)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:100
github.com/ledgerwatch/erigon/eth/borfinality.startMilestoneWhitelistService(0xc03e5d55c0?)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:76 +0x45
created by github.com/ledgerwatch/erigon/eth/borfinality.Whitelist
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:47 +0x265
```

**Comment by danspina1** [comment]
Similar issue here too, slightly different goroutine

`EngineBlockDownloader] No block bodies to write in this log period block number=18337702
[INFO] [10-13|13:14:37.216] [4/12 Execution] Completed on            block=18341704
[INFO] [10-13|13:14:39.169] [txpool] stat                            pending=1042 baseFee=4032 queued=7384 alloc=8.5GB sys=14.7GB
[INFO] [10-13|13:14:42.411] RPC Daemon notified of new headers       from=18341703 to=18341704 hash=0xe4e23ce4b8fdab07d01c3cb14c60d29a44b99c77db783cbd5ca07a846baf5986 header sending=16.101µs log sending=240ns
[INFO] [10-13|13:14:42.412] head updated                             hash=0xe4e23ce4b8fdab07d01c3cb14c60d29a44b99c77db783cbd5ca07a846baf5986 number=18341704
[INFO] [10-13|13:14:48.659] [NewPayload] Handling new payload        height=18341705 hash=0x2ad6ea8cbbe477418ba99a1844822bbcc29eeff31d5d1c661b55700c97cd2885
[INFO] [10-13|13:14:49.220] [5/7 Execution] Completed on             block=18341705
[INFO] [10-13|13:14:50.082] [4/12 Execution] Completed on            block=18341705
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0xbc3ec7]

goroutine 9090687 [running]:
github.com/RoaringBitmap/roaring.(*Bitmap).Remove(0xc167dd1b30, 0x117df49)
	github.com/RoaringBitmap/roaring@v1.2.3/roaring.go:773 +0x47
github.com/RoaringBitmap/roaring/roaring64.(*Bitmap).Remove(0xc0ced39cc0, 0x117df49)
	github.com/RoaringBitmap/roaring@v1.2.3/roaring64/roaring64.go:348 +0x54
github.com/ledgerwatch/erigon/turbo/stages/bodydownload.(*BodyDownload).NotDelivered(...)
	github.com/ledgerwatch/erigon/turbo/stages/bodydownload/body_algos.go:371
github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader.(*EngineBlockDownloader).downloadAndLoadBodiesSyncronously.func1()
	github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader/body.go:114 +0x80f
github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader.(*EngineBlockDownloader).downloadAndLoadBodiesSyncronously(0xc0bfd1bc70, {0x2dc7bd0?, 0xc128549f40}, 0xfb35a872c393a2f4?, 0x117cfa7)
	github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader/body.go:183 +0x6ea
github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader.(*EngineBlockDownloader).download(0xc0bfd1bc70, {0x44, 0x91, 0xd3, 0x4e, 0x1d, 0xdb, 0x32, 0x6f, 0x66, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader/core.go:67 +0x7a7
created by github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader.(*EngineBlockDownloader).StartDownloading
	github.com/ledgerwatch/erigon/turbo/engineapi/engine_block_downloader/core.go:117 +0x225
[INFO] [10-13|13:14:54.999] logging to file system                   log dir=/data/erigon/logs file prefix=erigon log level=info json=false
[INFO] [10-13|13:14:55.000] Enabling metrics export to prometheus    path=http://0.0.0.0:6060/debug/metrics/prometheus
[INFO] [10-13|13:14:55.000] Build info                               git_branch=HEAD git_tag=v2.49.2 git_commit=1b54c31c7178cef0553e05fc810f810318e04385
[INFO] [10-13|13:14:55.000] Starting Erigon on Ethereum mainnet...`

**Comment by czarly** [comment]
Leave my case here to confirm... trying to run a polygon main net erigon full node

```
[INFO] [10-14|01:49:20.324] Started P2P networking                   version=66 self=enode://f5e46ab99f22722348289a7da293f4b1de33de0276d715c3f3829de8c95ba78528ddaf7030306774e910324bf0c39915d51a9be10714b94b1060fad2ea947054@127.0.0.1:0 name=erigon/v2.51.0-a0160bee/linux-amd64/go1.20.9
[INFO] [10-14|01:49:20.590] Got new milestone from heimdall          start=48690192 end=48690204 hash=0x90488eddddf2da05dbbd74748eed735a386e6740e5bb8768a0cc1ed7a8f6084d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5a058]

goroutine 229 [running]:
github.com/ledgerwatch/erigon/core/types.(*Block).Hash(0xc000dd22a0?)                                 
        github.com/ledgerwatch/erigon/core/types/block.go:1669 +0x38
github.com/ledgerwatch/erigon/eth/borfinality.borVerify({0x2f993f0?, 0xc001a2c000?}, 0xc0007857a0, 0x2e6f410, 0x2e6f41c, {0xc004525132, 0x40}, 0x0)
        github.com/ledgerwatch/erigon/eth/borfinality/bor_checkpoint_verifier.go:92 +0x525
github.com/ledgerwatch/erigon/eth/borfinality.fetchWhitelistMilestone({0x2f993f0, 0xc001a2c000}, {0x2faba48?, 0xc000a923c0?}, 0xc001a4fe48, 0xc0007857a0)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist_helpers.go:85 +0x6c3
github.com/ledgerwatch/erigon/eth/borfinality.handleMilestone({0x2f993f0?, 0xc001a2c000?}, {0x2faba48?, 0xc000a923c0?}, 0x0?)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:172 +0x85
github.com/ledgerwatch/erigon/eth/borfinality.retryHeimdallHandler(0x2c78e08, 0xc0007857a0, 0x0?, 0x0?, {0x28631c8, 0x13})
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:118 +0xdb
github.com/ledgerwatch/erigon/eth/borfinality.RetryHeimdallHandler(...)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:100
github.com/ledgerwatch/erigon/eth/borfinality.startMilestoneWhitelistService(0x0?)
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:76 +0x45
created by github.com/ledgerwatch/erigon/eth/borfinality.Whitelist
        github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:47 +0x265
```

**Comment by 0xKrishna** [comment]
Fixed in the latest version.

**Comment by damianlluch** [comment]
I have finally been able after 3 weeks (where I have been on and off with this node) to try to launch my node with Mumbai.
I finally connected to it through Metamask. Now,
How can I get it running in the background? What is the best way?

I currently run it like this:

```
./build/bin/erigon --chain=mumbai --bor.heimdall=https://heimdall-api-testnet.polygon.technology --bor.milestone=true --http=true --http.addr=0.0.0.0.0 --http.port=8545 --http. compression=true --http.vhosts='*' --http.corsdomain='*' --ws=true --ws.compression=true --http.api=eth,net,trace,web3,erigon --torrent.download.rate=512mb --torrent.upload.rate=512mb
```
Adding the inverted commas, it seems that was the solution, it really made me spend many hours with it, and today thanks to a comment I saw in the issues, I tried that way and I was able to connect.

Thank you very much for your help.

**Comment by mh0lt** [comment]
Its not clear if this has been fixed or gone away - please reopen if further actions is requires
