### ISSUE TITLE
Support `safe/finalized` block strings in `eth_getLogs`

### ISSUE THREAD

**Issue by BrendanChou** [ledgerwatch/erigon#8454]
# Rationale

[This](https://github.com/ledgerwatch/erigon/issues/8199) issue was closed after only supporting a subset of the block string values. Support all block string values in `eth_getLogs`.

# Implementation

One-liner: Change [this](https://github.com/pyropy/erigon/blob/99788a01a1c840df1dfb10da40f222cd0c62b2cf/turbo/jsonrpc/eth_receipts.go#L41) `-2` to `-4`. (Should also change the name of the variable).

**Comment by Termina1** [comment]
Please, fix it

**Comment by yperbasis** [comment]
Fixed by PR #9686
