### ISSUE TITLE
Erigon misreports Tx Size on eth/68

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ledgerwatch/erigon#8456]
It looks like erigon nodes are always claiming 1 or two bytes less than they are actually sending. Most likely missing the txtype bytes. See also https://github.com/ethereum/go-ethereum/pull/28261

**Comment by karalabe** [comment]
This is very annoying, please fix. Or we can just start dropping Erigon peers for protocol violation. Either works for me really.
