### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by nitteo** [ledgerwatch/erigon#8462]
#### System information

Erigon version: `./erigon --2.52.1`

OS & Version:  Ubuntu 22.04.2 LTS

Commit hash: 

Erigon Command (with flags/config):/root/soft/erigon  --maxpeers 90 --datadir=/zfspool02/erigon --lightclient.discovery.port=4003 --lightclient.discovery.port=4004 --authrpc.jwtsecret=/root/soft/jwt.hex --chain=mainnet --torrent.download.rate=20mb --torrent.upload.rate=10kb --maxpeers=10 --port=30302 --authrpc.addr=192.168.0.222 --http.port=8542 --authrpc.port=8552 --torrent.port=42068 --private.api.addr=127.0.0.1:9091 --http --ws --http.api=eth,debug,net,trace,web3,erigon --prune=htcr

Concensus Layer: prysm

Concensus Layer Command (with flags/config):

Chain/Network: main

ERROR:
INFO[10-13|13:17:21.433] [EngineBlockDownloader] Processing bodies... from=18291861 to=18291925
INFO[10-13|13:17:51.435] [EngineBlockDownloader] Downloading block bodies block_num=18291905 delivery/sec=209.9KB wasted/sec=0B remaining=19 delivered=44 cache=0B alloc=2.4GB sys=4.4GB
EROR[10-13|13:17:56.843] [txpool] flush is local history          err="label: txpool, table: PoolTransaction, err: mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x171be67]

goroutine 2623 [running]:
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flushLocked(0xc00086a240, {0x30936d8?, 0xc06f4c6ea0})
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1769 +0xa7
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flushNoFsync.func1({0x30936d8?, 0xc06f4c6ea0})
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1737 +0x4b
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).UpdateNosync(0xc0ba43fee8?, {0x3066140?, 0xc0014800f0?}, 0xc0586c06a0)
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/kv/mdbx/kv_mdbx.go:657 +0xb6
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flushNoFsync(0xc00086a240, {0x3066140, 0xc0014800f0}, {0x30785d8, 0xc0507ddad0})
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1736 +0x17d
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flush(0xc0ba43fee8?, {0x3066140, 0xc0014800f0}, {0x30785d8?, 0xc0507ddad0?})
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1756 +0xff
github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x3066140?, 0xc0014800f0}, {0x30785d8, 0xc0507ddad0}, {0x0?, 0x0?}, 0xc00086a240, 0xc0b4290420, 0xc0b4280320, 0xc0b42886f0, ...)
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/txpool/pool.go:1623 +0x36a
created by github.com/ledgerwatch/erigon/eth.New
        /go/src/github.com/ledgerwatch/erigon/eth/backend.go:681 +0x4025

**Comment by AskAlexSharov** [comment]
it fixed in later version. please delete datadir/txpool folder
