### ISSUE TITLE
Erigon runs out of memory on 32GB machine syncing Gnosis Chain

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#8496]
Hey [@yperbasis](https://t.me/yperbasis)  I'm having issues syncing an Erigon node on a 32 GB RAM machine (which I wouldn't consider as being low RAM). It gets OOM killed constantly and then restarts from the same block.
There's nothing special in the logs, it just gets killed and the restarted by Docker and starts again.
Same happened to us on newest version
Works fine on lower, no OOM
https://dpaste.org/SuJCu
Thanks for confirming! And yes, latest too for me: v2.52.5
Which one are you using now?
Same version on a single batch that gets constant OOMs
Other batches on older version are fine
Actually I see that we’ve updated the batch to 2.52.4
And no more OOMs there
At least for last 5 hours
Maybe a memory leak or something?
https://github.com/ledgerwatch/erigon/pull/8467/files#diff-e177ddb5610d1f3426c15cb512999613785b20838954e48187883e6263bb282bR656

That's pretty much the only change.
GitHub
fix: newly mined blocks now include transactions and check new blocks with empty...
Description
This PR is a follow-up of #8442.

The previous PR resolved the issue where newly mined blocks had their receipt hash set to an empty root...
gnosis-erigon-1  | [INFO] [10-16|13:40:18.426] [p2p] GoodPeers                          eth68=30 eth67=27 eth66=1
gnosis-erigon-1  | [INFO] [10-16|13:40:20.440] [4/12 Execution] Executed blocks         number=30157025 blk/s=16.3 tx/s=113.6 Mgas/s=203.4 gasState=0.70 batch=169.1MB alloc=917.9MB sys=2.1GB
gnosis-erigon-1  | [INFO] [10-16|13:40:29.087] [txpool] stat                            pending=251 baseFee=0 queued=6581 alloc=710.3MB sys=2.1GB
gnosis-erigon-1 exited with code 137
Still happens with v2.52.0 :(
I confirm! Facing the same!
My got stuck 2 times! Earlier 30M , i reatarted with updated image and now at 28M!

With resource hogging
At least yours is making progress 😜
I just keep restarting again and again from 30006999
Not really🥲 my node is down for 1 week still hoping that it will get synced
https://github.com/ledgerwatch/erigon/issues/8341
[GitHub](https://github.com/ledgerwatch/erigon/pull/8467/files)
My Gnosis Archival node with Erigon + Lighthouse is stuck at block 30202550 · Is...
System information Erigon version: ./erigon --version v2.50.0 OS & Version: Windows/Linux/OSX Linux (docker_ Commit hash: Erigon Command (with flags/c...
Ah yes, this is another issue. Try integrations stage_headers --unwind=2000. That binary should exist in the default Docker container. Stop Erigon first 😉

There's a memory leak fix in our devel (PR #8431), but we haven't released it yet. Hopefully that helps with OOM issues.
I did with 89k🤣 (90k is limit) didnt help buy yeah will do that again🤭
So the Docker devel tag should work, right?
Yes, it should

I'll let it run on v2.50.0 just to see, but I'll upgrade to that right after.
Seems a lot better on that version based on the current RAM usage
(Never mind)
Latest devel OOMed again and still wasn't able to sync on the 32 GB machine

Do you observe OOM with 2.52.4 as well?
I tried 2.50.0, 2.52.5, 2.52.0 and the latest devel
And which have OOM? All?
Yes

**Comment by AskAlexSharov** [comment]
Need finish this task: https://github.com/ledgerwatch/erigon/issues/6646#issuecomment-1425157327

**Comment by yperbasis** [comment]
Should be fixed by PR #8632
