### ISSUE TITLE
Disabling snapshots not working after deleting snapshots

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#8501]
#### System information

Erigon version: `./erigon --version`

devel

OS & Version: Linux

Commit hash: ab04de6d9f9fc4291dbfd113dadc79e798fd8daf

Erigon Command (with flags/config):

```
--prune=htrc
--snapshots=false
--internalcl
```

Chain/Network: mainnet

#### Expected behaviour

When starting erigon, it defaults to snapshots enabled.
Snapshots take a lot of space, and I wanted to free up some space by not using them.
I've deleted and disabled them, but it didn't work.

I expect that `--snapshots=false` completely disables the snapshots feature.

#### Actual behaviour

Snapshots got re-downloaded again and take up >300 Gb disk space.

#### Steps to reproduce the behaviour

1. Start without snapshots flag.
2. Stop.
3. Delete `<datadir>/snapshots`
3. Add `--snapshots=false` flag.
4. Restart.

**Comment by AskAlexSharov** [comment]
"I expect that --snapshots=false completely disables the snapshots feature." - we don't support changing big node modes after startup - to reduce amount of unreproducible bugs - when user enabling/disabling/enabling/disabling things and then error happens. Unlikely we can test such cases. 

Currently value of --snapshots flag stored in db at startup. 

Same about --prune flags.

**Comment by battlmonstr** [comment]
@AskAlexSharov I see. Is there a workaround to reset this db flag somehow in case I'm fine with potential bugs?

**Comment by AskAlexSharov** [comment]
Exactly this key can remove by
“hack —action=rmSnKey”
 
 prune can do by 
“integration force_prune_flag”

**Comment by AskAlexSharov** [comment]
There is also —snap.stop for temporary stop production of snapshots

**Comment by battlmonstr** [comment]
@AskAlexSharov thanks!
