### ISSUE TITLE
failed setting externalcl flag with value=false error=no such flag -externalcl

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#8509]
#### System information

Erigon version: `erigon version 2.52.5`

OS & Version: Linux

Erigon Command (with flags/config):

Consensus Layer: Prysm

Chain/Network:  Mainnet

erigon.toml config below:

```
datadir = "/mnt1/archive"
port = 30304
"authrpc.port" = 8557
"authrpc.addr" = "0.0.0.0"
"authrpc.vhosts" = "*"
"authrpc.jwtsecret" = "/home/david/ethereum/consensus2/jwt.hex"
externalcl = false
metrics = true
"torrent.port" = 42071
"private.api.addr" = "127.0.0.1:9091"
chain = "mainnet"
http = true
ws = true
"http.addr" = "0.0.0.0"
"http.api" = ["eth", "debug", "net", "trace", "web3", "erigon", "admin", "txpool", "ots"]
"http.corsdomain" = "*"
"http.port" = 7546
```

error:

```
failed setting config flags from yaml/toml file err="failed setting externalcl flag with value=false error=no such flag -externalcl"
failed setting externalcl flag with value=false error=no such flag -externalcl
```

**Comment by ellioht** [comment]
At this commit: 2ce5e761bb07a3a45fad302ed60a7efdfcd8fb1f the ‘externalcl’ flag was replaced with ‘internalcl’ flag

```
InternalConsensusFlag = cli.BoolFlag{
		Name:  "internalcl",
		Usage: "enables external consensus",
	}

**Comment by TangMonk** [comment]
> At this commit: [2ce5e76](https://github.com/ledgerwatch/erigon/commit/2ce5e761bb07a3a45fad302ed60a7efdfcd8fb1f) the ‘externalcl’ flag was replaced with ‘internalcl’ flag
> 
> ```
> InternalConsensusFlag = cli.BoolFlag{
> 		Name:  "internalcl",
> 		Usage: "enables external consensus",
> 	}
> 	
> ```
Erigon was using internal consensus client by default before, It is changed? 
Are users now encouraged to install other consensus clients themselves?

**Comment by AskAlexSharov** [comment]
It’s user’s choice
