### ISSUE TITLE
Running ETH often causes crashes

### ISSUE THREAD

**Issue by git-ljm** [ledgerwatch/erigon#8511]
#### System information

Erigon version: `2.51.0-a0160bee`

OS & Version: Linux

Commit hash: a0160beee4032491501d89c5347bb1c4710ee6cc

Erigon Command (with flags/config):  erigon --datadir=/data --private.api.addr=0.0.0.0:9090 --http.api=eth,erigon,engine,debug,net,trace,web3 --http=true --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=* --http.corsdomain=* --ws=true --log.console.json --internalcl --prune=htc --prune.r.before=11052984

Consensus Layer:  internalcl

Consensus Layer Command (with flags/config): --internalcl

Chain/Network:  eth mainnet

####tail  log

````
{"from":18285782,"lvl":"info","msg":"[7/12 CallTraces] Pruned call trace intermediate table","t":"2023-10-18T07:42:16.640621466Z","to":18285820}
{"app":"caplin","lvl":"info","msg":"P2P","peers":38,"t":"2023-10-18T07:42:44.688808578Z"}
{"from":18375782,"hash":"0xc7b8d8b90cf42913670a193dc15624560e328d0418212cd1ca186c474cf12a2c","header sending":"3.639889ms","log sending":"313ns","lvl":"info","msg":"RPC Daemon notified of new headers","t":"2023-10-18T07:43:40.242519204Z","to":18375821}
{"hash":"0xc7b8d8b90cf42913670a193dc15624560e328d0418212cd1ca186c474cf12a2c","lvl":"info","msg":"head updated","number":18375821,"t":"2023-10-18T07:43:40.287488664Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":29,"t":"2023-10-18T07:43:44.69076023Z"}
{"eth67":"32","eth68":"33","lvl":"info","msg":"[p2p] GoodPeers","t":"2023-10-18T07:44:09.393479846Z"}
{"app":"caplin","err":"failed to write block root to beacon_indicies: sql: transaction has already been committed or rolled back","lvl":"warn","msg":"error executing clstage","stage":"CatchUpBlocks","t":"2023-10-18T07:44:15.460250193Z"}
{"alloc":"15.6GB","baseFee":0,"lvl":"info","msg":"[txpool] stat","pending":10000,"queued":29940,"sys":"23.7GB","t":"2023-10-18T07:44:16.911593878Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":22,"t":"2023-10-18T07:44:44.690738466Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":35,"t":"2023-10-18T07:45:44.690478217Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":30,"t":"2023-10-18T07:46:54.172866931Z"}
{"eth67":"32","eth68":"33","lvl":"info","msg":"[p2p] GoodPeers","t":"2023-10-18T07:47:13.298709367Z"}
{"current key":"3d3c6e6f","lvl":"info","msg":"[7/7 IntermediateHashes] Calculating Merkle root","t":"2023-10-18T07:47:26.075116887Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":29,"t":"2023-10-18T07:47:45.304256169Z"}
{"current key":"3dfbb126","lvl":"info","msg":"[7/7 IntermediateHashes] Calculating Merkle root","t":"2023-10-18T07:47:47.474298136Z"}
{"alloc":"17.2GB","baseFee":0,"lvl":"info","msg":"[txpool] stat","pending":10000,"queued":30000,"sys":"23.7GB","t":"2023-10-18T07:48:03.101014742Z"}
{"current key":"43acef30","lvl":"info","msg":"[7/7 IntermediateHashes] Calculating Merkle root","t":"2023-10-18T07:48:20.843264193Z"}
{"current key":"a0a5031a","lvl":"info","msg":"[7/7 IntermediateHashes] Calculating Merkle root","t":"2023-10-18T07:48:43.601593448Z"}
{"app":"caplin","lvl":"info","msg":"P2P","peers":5,"t":"2023-10-18T07:48:45.502506176Z"}
{"lvl":"info","msg":"Got interrupt, shutting down...","t":"2023-10-18T07:48:53.725077208Z"}
{"err":"[7/7 IntermediateHashes] stopped","lvl":"warn","msg":"Could not validate block","t":"2023-10-18T07:48:53.729394122Z"}
{"err":"context canceled","lvl":"eror","msg":"[txpool] collect info to propagate","t":"2023-10-18T07:48:53.743203139Z"}
{"lvl":"info","msg":"Exiting Engine...","t":"2023-10-18T07:48:53.810275537Z"}
{"lvl":"info","msg":"RPC server shutting down","t":"2023-10-18T07:48:53.810373593Z"}
{"lvl":"info","msg":"RPC server shutting down","t":"2023-10-18T07:48:53.813402984Z"}
{"lvl":"info","msg":"Engine HTTP endpoint close","t":"2023-10-18T07:48:53.821144361Z","url":"[127.0.0.1:8551](http://127.0.0.1:8551/)"}
{"lvl":"info","msg":"Exiting...","t":"2023-10-18T07:48:53.824399157Z"}
{"lvl":"info","msg":"RPC server shutting down","t":"2023-10-18T07:48:53.861214762Z"}
{"err":"EOF","lvl":"warn","msg":"[Beacon Gossip] Fatal error receiving gossip","t":"2023-10-18T07:48:53.836687215Z"}
{"lvl":"info","msg":"HTTP endpoint closed","t":"2023-10-18T07:48:53.88128076Z","url":"[::]:8545"}
{"err":"[7/7 IntermediateHashes] stopped","lvl":"warn","msg":"newPayload failed","t":"2023-10-18T07:48:53.800131987Z"}
{"lvl":"warn","msg":"fail to process block","reason":"[7/7 IntermediateHashes] stopped","slot":7565910,"t":"2023-10-18T07:48:53.903789994Z"}
{"app":"caplin","lvl":"info","msg":"[Caplin] exiting clstages loop","t":"2023-10-18T07:48:53.906063167Z"}
{"err":"db closed","lvl":"warn","method":"trace_transaction","msg":"Served","reqid":"11523015","t":"104.897µs"}
{"err":"db closed","lvl":"warn","method":"eth_getTransactionReceipt","msg":"Served","reqid":"11523014","t":"99.742µs"}
{"err":"db closed","lvl":"warn","method":"eth_getTransactionReceipt","msg":"Served","reqid":"11523016","t":"114.408µs"}
````

**Comment by xjhweb** [comment]
same p.b +1

new archive node sync with internalcl .

build from newest commit.

**Comment by xjhweb** [comment]
more detail:


`
[32mINFO[0m[10-18|19:38:51.677] [Caplin] Epoch downloaded                [32mapp[0m=caplin [32mstage[0m=CatchUpEpochs [32mepoch[0m=236469
[32mINFO[0m[10-18|19:39:03.295] [Caplin] Epoch downloaded                [32mapp[0m=caplin [32mstage[0m=CatchUpEpochs [32mepoch[0m=236470
[32mINFO[0m[10-18|19:39:08.244] [snapshots] Dumping txs                  [32mblock num[0m=18021922 [32malloc[0m=7.2GB [32msys[0m=8.4GB
[32mINFO[0m[10-18|19:39:13.675] [Caplin] Epoch downloaded                [32mapp[0m=caplin [32mstage[0m=CatchUpEpochs [32mepoch[0m=236471
runtime: g4818432: frame.sp=0xc03d51c680 top=0xc03d51dfe0
        stack=[0xc03d51a000-0xc03d51e000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0x290091a?, 0x0?})
        runtime/panic.go:1077 +0x5c fp=0x7a575562a910 sp=0x7a575562a8e0 pc=0x46377c
runtime.(*unwinder).finishInternal(0x0?)
        runtime/traceback.go:561 +0x12a fp=0x7a575562a950 sp=0x7a575562a910 pc=0x48a3ea
runtime.(*unwinder).next(0x7a575562ab50?)
        runtime/traceback.go:442 +0x232 fp=0x7a575562a9c8 sp=0x7a575562a950 pc=0x48a1f2
runtime.copystack(0xc0f1c00d00, 0x800000002?)
        runtime/stack.go:934 +0x2d2 fp=0x7a575562acc0 sp=0x7a575562a9c8 pc=0x47d9f2
runtime.newstack()
        runtime/stack.go:1116 +0x47f fp=0x7a575562ae70 sp=0x7a575562acc0 pc=0x47df9f
runtime.morestack()
        runtime/asm_amd64.s:593 +0x8f fp=0x7a575562ae78 sp=0x7a575562ae70 pc=0x49812f

goroutine 4818432 [copystack]:
github.com/prysmaticlabs/gohashtree._hash(0xc0d0fc0000, 0xc0d0fc0000, 0x2)
        github.com/prysmaticlabs/gohashtree@v0.0.3-alpha.0.20230510131438-bf992328364a/hash_amd64.s:775 +0x18fd5 fp=0xc03d51c688 sp=0xc03d51c680 pc=0x128cb55
created by github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage in goroutine 15803
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:34 +0x3c9

goroutine 1 [chan receive, 8 minutes]:
runtime.gopark(0xc05d0a3768?, 0x46e96b?, 0x48?, 0x37?, 0x46e9a0?)
        runtime/proc.go:398 +0xce fp=0xc0972db730 sp=0xc0972db710 pc=0x46666e
runtime.chanrecv(0xc000b5e060, 0x0, 0x1)
        runtime/chan.go:583 +0x3cd fp=0xc0972db7a8 sp=0xc0972db730 pc=0x431b0d
runtime.chanrecv1(0xc000692000?, 0x303a800?)
        runtime/chan.go:442 +0x12 fp=0xc0972db7d0 sp=0xc0972db7a8 pc=0x431712
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)
        github.com/ledgerwatch/erigon/node/node.go:271
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc0e0da6a60)
        github.com/ledgerwatch/erigon/turbo/node/node.go:34 +0x6e fp=0xc0972db820 sp=0xc0972db7d0 pc=0x209056e
main.runErigon(0xc000ce71c0)
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:90 +0x505 fp=0xc0972dbac0 sp=0xc0972db820 pc=0x20a58e5
github.com/ledgerwatch/erigon/turbo/app.MakeApp.func1(0xc000ce71c0)
        github.com/ledgerwatch/erigon/turbo/app/make_app.go:43 +0xb7 fp=0xc0972dbbc0 sp=0xc0972dbac0 pc=0x209a7b7
github.com/urfave/cli/v2.(*Command).Run(0xc000053e40, 0xc000ce71c0, {0xc0001c6000, 0x16, 0x16})
        github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x998 fp=0xc0972dbe50 sp=0xc0972dbbc0 pc=0x8f6778
github.com/urfave/cli/v2.(*App).RunContext(0xc0000550e0, {0x3027968?, 0x4ad24a0}, {0xc0001c6000, 0x16, 0x16})
        github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x5b7 fp=0xc0972dbeb8 sp=0xc0972dbe50 pc=0x8f30f7
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:41 +0x85 fp=0xc0972dbf40 sp=0xc0972dbeb8 pc=0x20a5305
runtime.main()
        runtime/proc.go:267 +0x2bb fp=0xc0972dbfe0 sp=0xc0972dbf40 pc=0x4661fb
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc0972dbfe8 sp=0xc0972dbfe0 pc=0x499fc1
`

**Comment by yperbasis** [comment]
Please re-open this issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
