### ISSUE TITLE
polygon mumbai: trace_block() returns "block not found" for 4 blocks (38809009, 38809010, 38809011, 38809012)

### ISSUE THREAD

**Issue by TeinEin** [ledgerwatch/erigon#8522]
#### System information

Erigon version: `2.52.5`

OS & Version: Linux
Ubuntu Server 22.04 LTS (HVM)
Architecture = 64-bit ARM

Commit hash: 7c5e4e770f122299c34a9309a37a33a146443da8

Erigon Command (with flags/config):
`./erigon --db.pagesize="16kb" --chain="mumbai" --datadir="~/snapshots/erigon/datadir_fresh" --bor.heimdall="http://localhost:1317" --http --http.addr="0.0.0.0" --http.api="eth,debug,trace,erigon,net,txpool,bor,web3,admin" --torrent.download.rate="4gb" --verbosity="4" --log.dir.verbosity="4" --sentry.log-peer-info --db.size.limit="8TB" --bootnodes="enode://bdcd4786a616a853b8a041f53496d853c68d99d54ff305615cd91c03cd56895e0a7f6e9f35dbf89131044e2114a9a782b792b5661e3aff07faf125a98606a071@43.200.206.40:30303,enode://209aaf7ed549cf4a5700fd833da25413f80a1248bd3aa7fe2a87203e3f7b236dd729579e5c8df61c97bf508281bae4969d6de76a7393bcbd04a0af70270333b3@54.216.248.9:30303"`

Consensus Layer:
heimdalld v1.0.2

Consensus Layer Command (with flags/config):
`/usr/bin/heimdalld start --home "/var/lib/heimdall" \
    --chain=mumbai \
--seeds="9df7ae4bf9b996c0e3436ed4cd3050dbc5742a28@43.200.206.40:26656,d9275750bc877b0276c374307f0fd7eae1d71e35@54.216.248.9:26656,1a3258eb2b69b235d4749cf9266a94567d6c0199@52.214.83.78:26656" \
--rest-server`

Chain/Network: 
Mumbai

#### Expected behaviour
Expect a normal trace_block() response for blocks 38_809_009, 38_809_0010, 38_809_0011, 38_809_012

#### Actual behaviour
Although other blocks return the expected response, these 4 blocks do not.
```
assessing blockNumber: 38809008
traces exist: localhost

assessing blockNumber: 38809009
{'code': -32000, 'message': 'block 43920d0b38c1c71a4112ad391fc253114d849f8ee78417380db7e5b04755494b not found'}: localhost

assessing blockNumber: 38809010
{'code': -32000, 'message': 'block 9252323c9603b1c5a6a93ea5f0c0a864c93e061b328bfef3f0e61094d55d4e0c not found'}: localhost

assessing blockNumber: 38809011
{'code': -32000, 'message': 'block 53bc7c33b0572a6071a5b7393965536fb67d8ae144bd163cb65ea4ce0bd6cbf9 not found'}: localhost

assessing blockNumber: 38809012
{'code': -32000, 'message': 'block 351bfce02128f9669d34d375ad57b4fcc22e8d854639458ab2772bcae4c05610 not found'}: localhost

assessing blockNumber: 38809013
traces exist: localhost
```

#### Steps to reproduce the behaviour
```
# assessing blockrange 0x2502db0 to 0x2502db5
import requests

def convert_hex_to_decimal(n):
    return int(n, base=16)


def convert_decimal_to_hex(n):
    return hex(n)


def create_json_data(target_block):
    return {'jsonrpc': '2.0', 'method': 'trace_block', 'params': [convert_decimal_to_hex(target_block)], 'id': 1}


def is_error_response(response):
    output = response.json().get('error')
    return 'traces exist' if not output else output


# should be parameters
STARTING_BLOCK_NUMBER = convert_hex_to_decimal('0x25029C0')
ENDING_BLOCK_NUMBER = convert_hex_to_decimal('0x2503190')

ENDPOINTS_PER_NETWORK = {
    "polygon_mainnet": {},
    "mumbai": {
        "localhost": "http://localhost:8545",
    },
}

i_block_num = STARTING_BLOCK_NUMBER
while i_block_num <= ENDING_BLOCK_NUMBER:
    print(f"assessing blockNumber: {i_block_num}")
    for endpoint_name, endpoint in ENDPOINTS_PER_NETWORK['mumbai'].items():
        json_data = create_json_data(i_block_num)
        response = requests.post(endpoint, headers={}, json=json_data)
        output = is_error_response(response)
        print(f"{output}: {endpoint_name}")
    
    i_block_num += 1

    print("")
```

Note: I tried again with a newly synced node from the polygon snapshot and got the same result
`curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mumbai --client erigon --extract-dir ~/snapshots/erigon/datadir_fresh --validate-checksum true`

**Comment by TeinEin** [comment]
likely related: https://github.com/ledgerwatch/erigon/issues/8523

**Comment by TeinEin** [comment]
using https://rpc.ankr.com/polygon_mumbai seems to return the correct response for these blocks

**Comment by mh0lt** [comment]
Mumbai is not a supported network
