### ISSUE TITLE
polygon mumbai: debug_traceBlockByHash() returns "block with hash not found" for blockNumber=38809009

### ISSUE THREAD

**Issue by TeinEin** [ledgerwatch/erigon#8523]
#### System information

Erigon version: `2.52.5`

OS & Version: Linux
Ubuntu Server 22.04 LTS (HVM)
Architecture = 64-bit ARM

Commit hash: 7c5e4e770f122299c34a9309a37a33a146443da8

Erigon Command (with flags/config):
`./erigon --db.pagesize="16kb" --chain="mumbai" --datadir="~/snapshots/erigon/datadir_fresh" --bor.heimdall="http://localhost:1317" --http --http.addr="0.0.0.0" --http.api="eth,debug,trace,erigon,net,txpool,bor,web3,admin" --torrent.download.rate="4gb" --verbosity="4" --log.dir.verbosity="4" --sentry.log-peer-info --db.size.limit="8TB" --bootnodes="enode://bdcd4786a616a853b8a041f53496d853c68d99d54ff305615cd91c03cd56895e0a7f6e9f35dbf89131044e2114a9a782b792b5661e3aff07faf125a98606a071@43.200.206.40:30303,enode://209aaf7ed549cf4a5700fd833da25413f80a1248bd3aa7fe2a87203e3f7b236dd729579e5c8df61c97bf508281bae4969d6de76a7393bcbd04a0af70270333b3@54.216.248.9:30303"`

Consensus Layer:
heimdalld v1.0.2

Consensus Layer Command (with flags/config):
`/usr/bin/heimdalld start --home "/var/lib/heimdall" \
    --chain=mumbai \
--seeds="9df7ae4bf9b996c0e3436ed4cd3050dbc5742a28@43.200.206.40:26656,d9275750bc877b0276c374307f0fd7eae1d71e35@54.216.248.9:26656,1a3258eb2b69b235d4749cf9266a94567d6c0199@52.214.83.78:26656" \
--rest-server`

Chain/Network: 
Mumbai

#### Expected behaviour
Expect a normal debug_traceBlockByHash() response for blockNumber=38809009 when calling via curl:
`curl localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0x9252323c9603b1c5a6a93ea5f0c0a864c93e061b328bfef3f0e61094d55d4e0c", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json"`

#### Actual behaviour
The RPC call returns an error and continues to return an error unless `eth_getBlockByNumber()` is called, at which point the `debug_traceBlockByHash()` call begins to succeed.
```
ubuntu@ip-172-31-15-247:~/py_test$ curl localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0x9252323c9603b1c5a6a93ea5f0c0a864c93e061b328bfef3f0e61094d55d4e0c", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32000,"message":"invalid arguments; block with hash 9252323c9603b1c5a6a93ea5f0c0a864c93e061b328bfef3f0e61094d55d4e0c not found"}}

ubuntu@ip-172-31-15-247:~/py_test$ curl localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["38809011", false],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":{"baseFeePerGas":"0x10","difficulty":"0x6","extraData":"0x000000000000000000000000000000000000000000000000000000000000000027e04a58f4ee7d4703cbe99e07780a3999862d7762806007152c6b87ef7ae0893fe0b31c3ca610aa6eed9d0c25ad2d681e1571682ca9edc929f982b59c353bd001","gasLimit":"0x13c16d4","gasUsed":"0x2895af","hash":"0x351bfce02128f9669d34d375ad57b4fcc22e8d854639458ab2772bcae4c05610","logsBloom":"0x0000008001200000400040000020000000000000000000000101010020010120000010000000000000040010000020140080806000120000100000000000008000004000000001000000000900a020800400004001000004024500600000010000000000020000080000082c004008000000800000880041800000100000000400840000800000004000000400000000003804800400800000000002008040002000200010000000008000000000000080000000000000001001800000000048000010028000810000010920080200000040000000008000001080000200200002000800080000020000000000000000000000000a0000806000040000100000","miner":"0x0000000000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x2502db3","parentHash":"0x53bc7c33b0572a6071a5b7393965536fb67d8ae144bd163cb65ea4ce0bd6cbf9","receiptsRoot":"0xb2056e8b0a7e80042dbc9e9c60e5bbdaa8799a3b451754c41b1520a8ba17848c","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x10a8","stateRoot":"0x8ade1b897bad0202dabfae934bb1834d09882031fd8e892bcd70479707ceb90a","timestamp":"0x64d3989a","totalDifficulty":"0xe396e00","transactions":["0x3addcb017b045efac697eaabad308f86e992718dad793726d761c23bc93d881e","0x643ea447fa01b67fcf95db24e24796e293243f80681f8efb2cdedebc36eeb77a","0x0d06fff67f2ad1160b50bfcdaa819c00052cb5b91c59487cccd38788adc17eb5","0x06df0bf1ef7142d42bcf8941732c1a4bbc3e62433834a2a68c3a67cc5486e791","0xd0adf64ce775838a965509dfdc8c73ca1224af46a8d112fd332f317742047d48","0xfaac5a7d1424bf1e3666792fd15ced3cde850ea359051d7038b147c64415c8ec","0xf0747a1a1d4ea9f1bba478e5e2ec0e6a6897e82561dcfb58107215c2d0b4e99a","0x975c7d9e0e83ad7c54f5efa3cd04c51f31f0e74f27fa387d3918db8518a59a17","0x5ea097aa27a25df45681fa3041a8390438f533e570cf6b9dc6f0f256657e574f"],"transactionsRoot":"0x044b7a4e0e89535b7abcb0445dd87e50ffae07230b2e73ac073b76cc0d182418","uncles":[]}}

ubuntu@ip-172-31-15-247:~/py_test$ curl localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0x351bfce02128f9669d34d375ad57b4fcc22e8d854639458ab2772bcae4c05610", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":[{"result":{"from":"0x73aeba89481252eefa1488ccffd69a68b9ba749f","gas":"0x2bb835","gasUsed":"0x1dce16","to":"0x3232f21a6e08312654270c78a773f00dd61d60f5","input":"0x6ca862e20...."]}}
# the rest of the response has been omitted for brevity
```

It seems that `eth_getBlockByNumber()` is loading the relevant data into system memory, but not permanently fixing the data corruption issue in the erigon database because once the host machine reboots, `debug_traceBlockByHash()` goes back to returning an error unless fixed again by `eth_getBlockByNumber()`

**Comment by TeinEin** [comment]
likely related: https://github.com/ledgerwatch/erigon/issues/8522

**Comment by mh0lt** [comment]
Mumbai is not a supported network
