### ISSUE TITLE
Snapshot downloader: speed drops to 0

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#8549]
#### System information

Erigon version: 2.53.0-dev-e8c0ce33

OS & Version: Ubuntu 23.10

Commit hash: e8c0ce33ebd7f750ad8d98c0aa0f65d111dee807

Erigon Command (with flags/config):
```
nohup ../build/bin/erigon --chain mumbai --datadir /mnt/giant/erigon/mumbai --bor.heimdall='https://heimdall-api-testnet.polygon.technology' >>out_mumbai.log 2>&1 &
```

Consensus Layer: none

Consensus Layer Command (with flags/config): N/A

Chain/Network: Mumbai

#### Expected behaviour

More or less consistent download speed of almost 16MB/s

#### Actual behaviour

Download speed often drops down to 0 and stays at 0 for hours. Restarting helps only for a few minutes. Then the speed drops down to 0 again.

[out_mumbai.log](https://github.com/ledgerwatch/erigon/files/13062887/out_mumbai.log)

#### Steps to reproduce the behaviour

Try syncing Mumbai from scratch

**Comment by yperbasis** [comment]
I observed similar behaviour for Gnosis Chain, so I don't think it's specific to Polygon.

**Comment by yperbasis** [comment]
> I observed similar behaviour for Gnosis Chain, so I don't think it's specific to Polygon.

Actually, the speed for Gnosis Chai seems to be better on my machine, so this might be specific to Mumbai.

**Comment by yperbasis** [comment]
For some reason it seems to recover better from 0 speeds on my MacBook compared with my Ubuntu PC.

**Comment by AskAlexSharov** [comment]
fixed
