### ISSUE TITLE
Erigon downgrade causes execution reverted on smart contracts

### ISSUE THREAD

**Issue by SuchJitter** [ledgerwatch/erigon#8625]
#### System information

Erigon version: v2.53.2

OS & Version: Linux Centos 8.5

Commit hash: 

Erigon Command (with flags/config):
./erigon --chain=mainnet --datadir=/home/neweth --authrpc.jwtsecret=/opt/jwtsecret --authrpc.port=8551 --torrent.port=42068 --torrent.download.rate=2000mb --http.addr=0.0.0.0 --ws --db.read.concurrency 400000 --rpc.batch.concurrency 20000 --rpc.batch.limit=100000

Consensus Layer:
Prysm

Consensus Layer Command (with flags/config):

Chain/Network: 
Mainnet

#### Expected behaviour
Downgrading from 2.53.2 to 2.49.0 to prevent RPC regression.

#### Actual behaviour
Reverifying snapshot and reverting on every smart contract call.

#### Steps to reproduce the behaviour
Downgrade from 2.53 to any version lower than 2.51

#### Backtrace

````
[backtrace]
````

**Comment by yperbasis** [comment]
Downgrade is not something we support well unfortunately.
