### ISSUE TITLE
Could not start execution service        err="[1/12 Snapshots] BuildMissedIndices: BodiesIdx: at=v1-017000-017500-bodies.seg, runtime error: slice bounds out of range [34:10], [block_snapshots.go:2053 panic.go:884 panic.go:153 decompress.go:561 block_snapshots.go:2110 block_snapshots.go:2069 block_snapshots.go:900 block_snapshots.go:970 errgroup.go:75 asm_amd64.s:1598]"

### ISSUE THREAD

**Issue by lucyzhang314** [ledgerwatch/erigon#8668]
System information

Erigon version: `./erigon --version`

erigon version 2.54.0-dev-e08b031f

OS & Version: Windows/Linux/OSX

Windows 11 专业版 Insider Preview  25987.1000 Windows Feature Experience Pack 1000.25987.1000.0

Commit hash: 

Erigon Command (with flags/config):  erigon.exe --datadir .  --internalcl --experimental.history.v3=true

Consensus Layer: N/A

Consensus Layer Command (with flags/config): N/A

Chain/Network:  Mainnet

![image](https://github.com/ledgerwatch/erigon/assets/40690755/fd14a8b0-922a-41a0-90a7-7be91427889a)

**Comment by timmsGithub** [comment]
+1

**Comment by AskAlexSharov** [comment]
start once with `--downloader.verify`

**Comment by timmsGithub** [comment]
I just solved the problem desterday.
1) Delete your erigon folder
2) Delete your data folder (where chaindata is located)

i think it was an error for me because i only deleted the snapshot dirand not the whole data dir.

**Comment by AskAlexSharov** [comment]
nice.

FYI: if remove datadir/snapshot need also remove datadir/downloader
