### ISSUE TITLE
Beacon API for InternalCL

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#8685]
# Rationale

Why should this feature exist?

InternalCL for Erigon is an amazing feature as it allows us to avoid running a separate client for beacon node for EL synchronisation and avoid having a dependency on two software teams for reliability, however to support Beacon API endpoints for use in staking for example we still need to run a separate CL client and having the Beacon API endpoint also provided with Erigon would make this the complete package.

What are the use-cases? 

Staking in particular requires information about the validator set.

# Implementation

Do you have ideas regarding the implementation of this feature?

Expose the following API endpoints from the Internal CL:

/eth/v1/validator/duties/proposer/<point>
/eth/v1/beacon/states/<point>/finality_checkpoints
/lighthouse/validator_inclusion/<epoch>/global
/eth/v1/beacon/states/<point>/sync_committees
/eth/v1/beacon/states/<point>/committees
/eth/v1/beacon/states/<point>/finality_checkpoints
/eth/v1/beacon/states/<slot>/validator_balances
/eth/v1/beacon/rewards/attestations/<point>
/eth/v1/beacon/states/<point>/validators/<key>
/eth/v1/beacon/headers/<point>
/eth/v1/beacon/headers
/eth/v1/beacon/blocks/<point>
/eth/v1/beacon/rewards/blocks/<point>
/eth/v2/debug/beacon/states/<point>
/eth/v1/validator/duties/proposer/<point>
/eth/v1/beacon/rewards/sync_committee/<point>
/eth/v1/node/syncing
/eth/v1/beacon/genesis
/eth/v1/beacon/states/%s/validators
/eth/v2/beacon/blocks/%s
/eth/v1/beacon/states/%s/fork
/eth/v1/beacon/pool/voluntary_exits

Are you willing to implement this feature?

The specifics of the implementation of InternalCL are in many cases unique to Erigon, I believe the Erigon team are in the best position to implement this, however we would be available for testing and verification and can put some development resources towards it if requested.

@Giulio2002

**Comment by Giulio2002** [comment]
https://github.com/ledgerwatch/erigon/pull/8727 This should add a few of them

I will make a bunch of bull points with your features and see how many should be already covered

**Comment by Giulio2002** [comment]
- [ ] /eth/v1/validator/duties/proposer/
- [ ] /eth/v1/beacon/states/finality_checkpoints
- [ ] /lighthouse/validator_inclusion//global
- [ ] /eth/v1/beacon/states/sync_committees
- [ ] /eth/v1/beacon/states/committees
- [ ] /eth/v1/beacon/states/finality_checkpoints
- [ ] /eth/v1/beacon/states//validator_balances
- [ ] /eth/v1/beacon/rewards/attestations/
- [ ] /eth/v1/beacon/states/validators/
- [ ] /eth/v1/beacon/headers/
- [ ] /eth/v1/beacon/headers
- [ ] /eth/v1/beacon/blocks/
- [ ] /eth/v1/beacon/rewards/blocks/
- [ ] /eth/v2/debug/beacon/states/
- [ ] /eth/v1/validator/duties/proposer/
- [ ] /eth/v1/beacon/rewards/sync_committee/
- [ ] /eth/v1/node/syncing
- [ ] /eth/v1/beacon/genesis
- [ ] /eth/v1/beacon/states/%s/validators
- [ ] /eth/v2/beacon/blocks/%s
- [ ] /eth/v1/beacon/states/%s/fork
- [ ] /eth/v1/beacon/pool/voluntary_exits

**Comment by Giulio2002** [comment]
moved to https://github.com/ledgerwatch/erigon/issues/8780
