### ISSUE TITLE
Return yParity from eth_getBlockByNumber

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#8686]
#### System information

Erigon version: `v2.53.4`

Chain/Network: Ethereum Mainnet

#### Expected behaviour
return yParity in the output of eth_getBlockByNumber

#### Actual behaviour
yParity key missing in the output of eth_getBlockByNumber

#### Steps to reproduce the behaviour

Send the following JSON-RPC request to an Erigon node and then either a Geth, Reth, or Nethermind Node, and compare the outputs:

```json
{"method":"eth_getBlockByNumber","params":["0x10b7cfb",true],"id":1,"jsonrpc":"2.0"}
```

Geth, Reth, and Nethermind include a field called `yParity` in the output. Erigon does not.

**Comment by MRabenda** [comment]
Hey,

@0xKrishna is there a chance that someone will support here?
