### ISSUE TITLE
Erigon Backup for crash emergency

### ISSUE THREAD

**Issue by chromafunk** [ledgerwatch/erigon#8694]
If I shutdown Erigon gracefully while synced and backup the datadir, can I use it later on in case of catastrophic event ?

I'm just trying to find out contingency measures to be prepared for the future, since the time to sync from scratch is significant

Thanks

**Comment by AskAlexSharov** [comment]
Yes. Just stop erigon and backup.

**Comment by chromafunk** [comment]
thanks !
