### ISSUE TITLE
Erigon doesn't shutdown gracefully

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#8725]
#### System information

Erigon version: [2.54.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.54.0)-aeec5221

OS & Version: macOS Sonoma 14.0

Erigon Command (with flags/config): `erigon --datadir /Users/andrew/Library/Erigon/ethereum`

Consensus Layer: Lighthouse

Consensus Layer Command (with flags/config): `lighthouse bn --execution-endpoint=http://127.0.0.1:8551 --execution-jwt=/Users/andrew/Library/Erigon/ethereum/jwt.hex --checkpoint-sync-url=https://beaconstate.info`

Chain/Network: Ethereum mainnet

#### Expected behaviour
`kill` shutdowns the process gracefully

#### Actual behaviour
10 kills are required to kill Erigon

#### Backtrace
[out_ethereum.log](https://github.com/ledgerwatch/erigon/files/13347158/out_ethereum.log)

**Comment by yperbasis** [comment]
The issue appears to be intermittent. Sometimes erigon shuts down gracefully.

**Comment by battlmonstr** [comment]
Regression from https://github.com/ledgerwatch/erigon/pull/8661
