### ISSUE TITLE
metrics: restore rusage metrics

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8830]
use https://github.com/shirou/gopsutil to restore:
- rusage majflt/minflt
- disk read/write mb/s
- disk read/write syscall/s
some of this metrics was lost long time ago, some recently (victoria metric lib reported them

you can find in dashboard `process_major_pagefaults_total`, can use any metric name as you like.

**Comment by AskAlexSharov** [comment]
cc: @taratorio

**Comment by mh0lt** [comment]
I'm going to get Shoham to work on this as an initial task.
