### ISSUE TITLE
Upgrading from erigon 2.48.1 to 2.5x (currently trying 2.54.0) causes node to stop syncing

### ISSUE THREAD

**Issue by wwhchung** [ledgerwatch/erigon#8833]
#### System information

erigon version 2.54.0-aeec5221

OS & Version: Linux

Commit hash: 
tag - v2.54.0

Erigon Command (with flags/config):
/usr/bin/erigon --config=/data/erigon/erigon.yaml

Consensus Layer:
lighthouse
Lighthouse v4.5.0-441fc16

Consensus Layer Command (with flags/config):
/usr/bin/lighthouse bn --datadir /data/lighthouse --network mainnet --http --execution-endpoint http://127.0.0.1:8551 --execution-jwt /data/erigon/jwtsecret

Chain/Network: 
mainnet

#### Expected behaviour
Node properly syncs after version upgrarde

#### Actual behaviour
Node is no longer syncing, with messages:
[WARN] [11-26|17:06:15.372] Served                                   conn=127.0.0.1:26722 method=engine_forkchoiceUpdatedV2 reqid=1 t=68.793491ms err="unexpected chain cap: 18657009"

#### Steps to reproduce the behaviour
Full sync on v2.48.1, then upgrade to v2.54.0

#### Backtrace
N/A

**Comment by AskAlexSharov** [comment]
show "integration print_stages"

**Comment by bretep** [comment]
We're seeing the same issue on our nodes.

Something I noticed on startup of erigon:
```
[INFO] [11-28|21:56:55.656] [db] chaindata                           sizeLimit=3TB pageSize=4096
```

When running `integration print_stages`:
```
INFO[11-28|22:00:48.990] logging to file system                   log dir=/blockchain/logs file prefix=integration log level=info json=false
INFO[11-28|22:00:48.992] [db] chaindata                           sizeLimit=2TB pageSize=4096
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

 				 stage_at 	 prune_at
Snapshots 			 18846895 	 0
Headers 			 18846895 	 0
BorHeimdall 			 0 		 0
BlockHashes 			 18846895 	 0
Bodies 				 18846895 	 0
Senders 			 18846895 	 0
Execution 			 18846895 	 18846895
Translation 			 0 		 0
HashState 			 18846895 	 0
IntermediateHashes 		 18846895 	 18846895
AccountHistoryIndex 		 18846895 	 0
StorageHistoryIndex 		 18846895 	 0
LogIndex 			 18846895 	 0
CallTraces 			 18846895 	 18846895
TxLookup 			 18846895 	 0
Finish 				 18846895 	 0
--
prune distance:

blocks.v2: blocks=0, segments=0, indices=0

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->1, lastBlockInSnap=0

sequence: EthTx=2063258825, NonCanonicalTx=63761

in db: first header 1, last header 18952054, first body 1, last body 18952054
--
```

**Comment by eldarbogdanov** [comment]
I'm observing the same on v2.55.1. Like @bretep , the sizeLimit in container logs does not match the one from `integration print_stages`:
```
docker logs 2>&1 eth_erigon | grep chaindata
[INFO] [12-15|23:43:46.812] Opening Database                         label=chaindata path=/mnt/data/eth_erigon/core/chaindata
[INFO] [12-15|23:43:46.820] [db] chaindata                           sizeLimit=8TB pageSize=4096
```

```
/ $ integration print_stages --datadir /mnt/data/eth_erigon/core --chain mainnet
INFO[12-15|23:53:32.297] logging to file system                   log dir=/mnt/data/eth_erigon/core/logs file prefix=integration log level=info json=false
INFO[12-15|23:53:32.298] [db] chaindata                           sizeLimit=2TB pageSize=4096
INFO[12-15|23:53:35.581] [snapshots] Blocks Stat                  blocks=18518k indices=18518k alloc=2.2GB sys=2.3GB
INFO[12-15|23:53:35.584] [bor snapshots] Blocks Stat              blocks=0k indices=0k alloc=2.2GB sys=2.3GB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

                                 stage_at        prune_at
Snapshots                        18608589        0
Headers                          18794467        0
BorHeimdall                      0               0
BlockHashes                      18794467        0
Bodies                           18608589        0
Senders                          18608589        0
Execution                        18608589        18608589
Translation                      0               0
HashState                        18608589        0
IntermediateHashes               18608589        18608589
AccountHistoryIndex              18608589        0
StorageHistoryIndex              18608589        0
LogIndex                         18608589        0
CallTraces                       18608589        18608589
TxLookup                         18608589        18518000
Finish                           18608589        0
--
prune distance: 

blocks.v2: true, blocks=18517999, segments=18517999, indices=18517999

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->0, lastBlockInSnap=0

sequence: EthTx=2199760036, NonCanonicalTx=1870330

in db: first header 18518000, last header 18794904, first body 18518000, last body 18794904
```

**Comment by B1Q** [comment]
what's the solution to this?

**Comment by wwhchung** [comment]
I had tried that (CL and Erigon stopped) and still encountered this error.

**Comment by bretep** [comment]
Resolution to this for me was to start with ```--db.size.limit=6000000000000````

**Comment by wwhchung** [comment]
How do you get this output info?
> Just an update on the above, the snapshot stage eventually kicked in and caught up:
> 
> ```
>                                  stage_at        prune_at
> Snapshots                        19058024        0
> Headers                          19058025        0
> BorHeimdall                      0               0
> BlockHashes                      19058025        0
> Bodies                           19058025        0
> Senders                          19058025        0
> Execution                        19058025        19058025
> Translation                      0               0
> HashState                        19058025        0
> IntermediateHashes               19058025        19058025
> AccountHistoryIndex              19058025        0
> StorageHistoryIndex              19058025        0
> LogIndex                         19058025        0
> CallTraces                       19058025        19058025
> TxLookup                         19058025        18967160
> Finish                           19058025        0
> --
> ```

**Comment by zformular** [comment]
+1

**Comment by zformular** [comment]
> +1

same issue, i tried state_stages unwind=100, log shows
`
 				 stage_at 	 prune_at
Snapshots 			 19395908 	 0
Headers 			 19395908 	 0
BlockHashes 			 19395908 	 0
Bodies 				 19395908 	 0
Senders 			 19395908 	 0
Execution 			 19395908 	 19395908
Translation 			 0 		 0
HashState 			 19395908 	 0
IntermediateHashes 		 19395908 	 19395908
AccountHistoryIndex 		 19395908 	 0
StorageHistoryIndex 		 19395908 	 0
LogIndex 			 19395908 	 0
CallTraces 			 19395908 	 19395908
TxLookup 			 19395908 	 19301550
Finish 				 19395908 	 0
--
prune distance:

blocks.v2: blocks=19304999, segments=19304999, indices=19304999

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->0, lastBlockInSnap=0

sequence: EthTx=2331207830, NonCanonicalTx=2257357

in db: first header 19304900, last header 19415660, first body 19304900, last body 19415660
`

`
INFO[03-12|01:19:37.291] [snapshots:download] Blocks Stat         blocks=19305k indices=19305k alloc=4.1GB sys=4.3GB
INFO[03-12|01:19:37.291] [4/12 Execution] Blocks execution        from=19395808 to=19395908
INFO[03-12|01:19:52.381] [4/12 Execution] Completed on            block=19395908
INFO[03-12|01:19:52.381] [5/12 HashState] Promoting plain state   from=19395808 to=19395908
INFO[03-12|01:19:52.381] [5/12 HashState] Incremental promotion   from=19395808 to=19395908 codes=true csbucket=AccountChangeSet
INFO[03-12|01:19:52.487] [5/12 HashState] Incremental promotion   from=19395808 to=19395908 codes=false csbucket=AccountChangeSet
INFO[03-12|01:19:52.646] [5/12 HashState] Incremental promotion   from=19395808 to=19395908 codes=false csbucket=StorageChangeSet
INFO[03-12|01:19:53.445] [6/12 IntermediateHashes] Generating intermediate hashes from=19395808 to=19395908
INFO[03-12|01:19:59.480] [snapshots] Prune Blocks                 to=19305000 limit=100
INFO[03-12|01:20:01.627] [EngineBlockDownloader] Downloading PoS headers... hash=0xb867ceac9b821d574870ee0299ae63b5d2e465898a7793894e1080415afa81fb requestId=0
INFO[03-12|01:22:35.212] [p2p] GoodPeers
INFO[03-12|01:22:35.531] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.5GB sys=4.6GB
INFO[03-12|01:25:35.213] [p2p] GoodPeers
INFO[03-12|01:25:35.532] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.9GB sys=4.6GB
INFO[03-12|01:28:35.213] [p2p] GoodPeers
INFO[03-12|01:28:35.531] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.7GB sys=4.6GB
INFO[03-12|01:30:13.111] [NewPayload] Handling new payload        height=19415730 hash=0x8f3ff005c107314fec2a7f4a13721ad4cf3ba67e4a729c08569315f075b8641c
INFO[03-12|01:30:25.283] [NewPayload] Handling new payload        height=19415731 hash=0x64ef1209e88f2d4ec11664577d5c9bace0c572d5dea9b60991c10c05720b1728
INFO[03-12|01:30:38.508] [NewPayload] Handling new payload        height=19415732 hash=0xc5735a7fe281dfa09036124e689af75672a57f1f20627891e59010b2b3d948e6
`

**Comment by wwhchung** [comment]
> Did you wait for Erigon to fully settle down? I waited for it to complete the snapshot phase, which took over a day.

That did it.  Thanks.  Upgrade successful.

**Comment by yperbasis** [comment]
Please re-open this issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
