### ISSUE TITLE
Erigon Sepolia stuck at 3999999

### ISSUE THREAD

**Issue by wbelhomsi** [ledgerwatch/erigon#8846]
#### System information

Erigon version: `2.54.0`

OS & Version: `Amazon Linux 2023 (arm64)` (62 GB RAM - 32 CPU)

Commit hash:  (aeec5221c93be843d282e34379d9281e68906f79)

Erigon Command (with flags/config):
```
ExecStart=/nodes/volume1/eth/bin/erigon \
--chain=sepolia \
--datadir=/nodes/volume1/eth/sepolia \
--internalcl=true\
--ws \
--http.vhosts="*" \
--http.addr=0.0.0.0 \
--http.port=9547 \
--http.api="admin,debug,eth,net,txpool,web3,erigon" \
--torrent.port=42068 \
--maxpeers=50 \
--rpc.txfeecap=10 \
--state.cache=8192
```

Consensus Layer:
Tried internalcl and Tried Lighthouse

Consensus Layer Command (with flags/config):
Lighthouse:
```
ExecStart=/nodes/volume1/lighthouse/bin/lighthouse bn \
--network sepolia \
--datadir /nodes/volume1/lighthouse/sepolia \
--checkpoint-sync-url=https://sepolia.beaconstate.info \
--http \
--execution-endpoint http://127.0.0.1:18551 \
--execution-jwt /home/wbe/lighthouse/jwtsecret/jwt.hex
```

Chain/Network: Sepolia

#### Expected behavior
To actually continue syncing after block `3999999` and reach the latest block

#### Actual behavior
It has been stuck at `3999999` ever since. The logs are not very helpful. I tried running it with lighthouse at the start, and I was not getting any results.
I can confirm that the lighthouse is not the issue because I span a GETH client and made it communicate with the lighthouse client and the GETH client is now fully synced.
I tried switching internalcl but I'm still stuck without any results

![Screenshot 2023-11-28 at 6 15 17 PM](https://github.com/ledgerwatch/erigon/assets/40052755/0f4ccf7b-d727-4102-bd0e-bba13101d019)
Actually it was stuck before showing this log: `[3/12 Senders]`

```
curl http://localhost:9547 -X POST -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}'
{"jsonrpc":"2.0","id":67,"result":"0x3d08ff"}
```

```
 curl http://localhost:9547 -X POST -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":67}'
{"jsonrpc":"2.0","id":67,"result":false}
```

Im sure I opened all necessary ports, but I'm happy to be proven wrong. Any help would be appreciated

PS: I also had the same issue with goerli, but gaveup on goerli and tried sepolia but got stuck again

**Comment by AskAlexSharov** [comment]
block_number is growing in your logs. you are good.
