### ISSUE TITLE
Run Erigon without snapshots 

### ISSUE THREAD

**Issue by gabronick** [ledgerwatch/erigon#8968]
#### System information

Erigon version: v2.55.1

OS & Version: Ubuntu 22.04 X86_64

Erigon Command (with flags/config):  erigon --datadir="/datadir" --prune=htrc --prune.h.older=90000  --prune.r.older=90000 --prune.t.older=90000 --prune.c.older=90000 --http --http.addr="127.0.0.1" --http.port="8545" --http.vhosts="*" --http.corsdomain="*" --http.api="eth,net,web3,txpool" --ws --no-downloader  --snapshots=false  --snap.stop 

Consensus Layer: Ligthhouse 

Consensus Layer Command (with flags/config):  lighthouse beacon_node --private --network=mainnet --datadir=/mnt/nvme/ETH/erigon/beacon --http --http-address 0.0.0.0 --http-allow-origin='*' --metrics --execution-jwt=/mnt/nvme/ETH/erigon/datadir/jwt.hex --execution-endpoint http://127.0.0.1:8551 --checkpoint-sync-url https://sync.invis.tools --disable-deposit-contract-sync

Chain/Network:  Ethereum

#### Expected behaviour

Erigon will sync from block 0

#### Actual behaviour

Erigon downloads the PoS header, then downloads the block's bodies, erigon crashes, when restarting it starts downloading everything again

#### Steps to reproduce the behaviour

start erigon, let it download some data for a while, restart erigon

**Comment by yperbasis** [comment]
Please check with [v2.59.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.0) and re-open if the issue is still there.
