### ISSUE TITLE
Can't sync - no peers 

### ISSUE THREAD

**Issue by karol-murawski** [ledgerwatch/erigon#8983]
Hi, we are trying to sync from last erigon snapshot on v2.55.1. Looks like there is almost no peers (max 2 sometimes). 

```
[INFO] [12-14|12:02:55.458] [2/15 Headers] No block headers to write in this log period number=50592894 blk/second=0.000 alloc=85.7MB sys=141.1MB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [12-14|12:02:55.458] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=50592893 skelMax=50629949 resp=0 respMin=0 respMax=0 dups=0
[INFO] [12-14|12:03:24.730] [p2p] GoodPeers                          eth66=2
```

Can I set any static peers list? Where I can find it?

**Comment by 0x1un** [comment]
same issue.

**Comment by sokiaoba** [comment]
Same here

**Comment by 0x1un** [comment]
@sokiaoba After running my node for a while, the peers get progressively less until they are out of sync. This problem only occurs on bor-mainnet. And the way I solved it, was to reboot

**Comment by sokiaoba** [comment]
@0x1un 

Thank you for your reply. I asked it in Erigon community & could resolved it by setting bootnodes.
https://discord.com/channels/687972960811745322/983710221308416010/1189754555802591293

```
--bootnodes='enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303'
```
