### ISSUE TITLE
MDBX_TOO_LARGE startup error

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#9026]
#### System information

RAM total: 16 Gb
RAM free: 12 Gb
RAM cached: 3 Gb

chaindata size: 441G

Nothing is running except the default OS stuff.

Erigon version: `./erigon --version`

v2.55.1

OS & Version: Windows/Linux/OSX

Debian 12

Erigon Command (with flags/config):

--prune=htrc

Consensus Layer:

--internalcl

Chain/Network: 

mainnet

#### Expected behaviour

chaindata mdbx.dat is much smaller (400gb) than the available RAM (12 gb), so why could it NOT be mapped?

#### Actual behaviour

Erigon startup                           err="mdbx_env_open: MDBX_TOO_LARGE: Database is too large for current system, e.g. could NOT be mapped into RAM, label: chaindata, trace: [kv_mdbx.go:295 node.go:365 node.go:368 backend.go:239 node.go:124 main.go:65 make_app.go:52 command.go:274 app.go:332 app.go:309 main.go:34 proc.go:267 asm_amd64.s:1650]"

**Comment by AskAlexSharov** [comment]
@battlmonstr see breaking change section in recent release notes: https://github.com/ledgerwatch/erigon/releases
Existing nodes whose MDBX page size equals 4kb must add `--db.size.limit=8TB` flag. Otherwise you will get MDBX_TOO_LARGE error.
