### ISSUE TITLE
Polygon mainnet archive node not fully syncing

### ISSUE THREAD

**Issue by DaraDoyoung** [ledgerwatch/erigon#9147]
#### System information

Erigon version: `erigon version 2.54.0-aeec5221`

OS & Version: Linux Ubuntu 22.04 LTS

Commit hash: aeec5221c93be843d282e34379d9281e68906f79

Erigon Command (with flags/config):
```
erigon --datadir $DATA_DIR \
  --chain=bor-mainnet \
  --bor.heimdall=http://localhost:1317 \
  --http --http.addr '0.0.0.0' \
  --http.vhosts '*' \
  --http.port 8545 \
  --http.api 'eth,net,web3,txpool,bor,debug,trace' \
  --private.api.addr=localhost:9091 \
  --ws \
  --torrent.upload.rate="1024mb" \
  --torrent.download.rate="1024mb" \
  --p2p.protocol 66 \
  --metrics \
  --txpool.globalslots 131072 \
  --txpool.globalbasefeeslots 60000 \
  --txpool.globalqueue 131072 \
  --maxpeers 100 \
  --rpc.batch.limit 3000 \
  --db.size.limit 16TB \
  >> ~/node/logs/bor.log \
  2>&1 &
```

Consensus Layer: heimdall

Consensus Layer Command (with flags/config):
```
heimdalld start --home /home/ubuntu/.heimdalld   >> ~/node/logs/heimdalld.log   2>&1 &
```

Chain/Network: Polygon Mainnet

#### Expected behaviour
Sync on time.

#### Actual behaviour
This graph shows block gap the node has compared to the latest block of the network. As seen in the graph node seems to be fully synced, then the syncing process slows down so the gap between the node and the network grows up to 300 blocks.
![image](https://github.com/ledgerwatch/erigon/assets/95335707/5375588b-141d-42df-aa00-fac6ff854cc7)

This is happening because the time it takes for erigon to execute received blocks is taking more time than the block creation time, therefore as the node is executing the previous blocks, the network forwards.

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/a352406d-7f38-4469-b4f5-
![image](https://github.com/ledgerwatch/erigon/assets/95335707/2b2cc8a3-ebbd-4ea4-bea2-50df56939962)

This is iostat from the node. I'm currently using AWS set up by ec2 r6g.8xlarge instance with gp3 16,000 iops, 300 throughput.

I've successed making the erigon node sync on time with GCP instance and the difference we saw with the AWS node was its read io latency, GCP was under 0.3 seconds, whereas AWS was always above 0.5 seconds.

I want to know if the node specs are not enough to fully sync.
If possible I would like to know what instance type in AWS is best practice to run Polygon mainnet erigon archive nodes.

By the way, Polygon Mainnet Erigon Full nodes, Polygon Mumbai Erigon Full, Archive nodes work well. It's only the mainnet archive nodes that are having this problem.

If more information is needed, pease ask for more.

**Comment by taratorio** [comment]
this has been answered on discord but posting a summary here for others:

"""
Alex Sharov
I see "commit cycle 4sec" - let's take a look inside of it:
curl -s -v http://localhost:6060/debug/metrics/prometheus  | grep db_commit 

Alex Sharon
FS type? disk type? raid? ram amount? 

doyoung
db_commit_seconds_sum{phase="ending"} 0.12831978000000002
db_commit_seconds_count{phase="ending"} 46
db_commit_seconds_sum{phase="preparation"} 0.0006408359999999997
db_commit_seconds_count{phase="preparation"} 46
db_commit_seconds_sum{phase="sync"} 989.7341403180001
db_commit_seconds_count{phase="sync"} 46
db_commit_seconds_sum{phase="total"} 1090.047220482
db_commit_seconds_count{phase="total"} 46
db_commit_seconds_sum{phase="write"} 83.922921306
db_commit_seconds_count{phase="write"} 46

doyoung
disk type i'm using gp3 ebs volume from AWS, ram 128 G (r6i.4xlarge ec2 instance)

Alex Sharov GMT
gp3 is high-latency network disk (parallel throughput oriented). I think it's just impossible to have erigon's polygon on chain tip without nvme or ram which can fit at least PlainState table 
mdbx_stat -s PlainState datadir/chaindata
integration warmup --table=PlainState
(also Hashed and Trie tables are involved) 

doyoung
then how about io2?

Peter
You cannot run Polygon or BSC erigon on cloud without having an attached local NVME
There is no network attached storage that has low enough latency so far in my experience

Peter
there is basically just the i3.metal and the r6 platform on AWS that has local NVME
"""

there may also be other compute providers which may have alternative NVME and/or bare metal options
