### ISSUE TITLE
Error after resyncing beacon chain,  err: unexpected chain cap: 18932454"

### ISSUE THREAD

**Issue by PolarSyncZ** [ledgerwatch/erigon#9150]
I had to wipe out and resync my consensus layer. I am using the internalcl now and my execution layer is behind the head of the chain as it was stopped for a day. I synced the beacon chain on the internalcl and teku and receive this error on both when trying to sync. I have let the client sync for several hours and do not see downloading over the network anymore as I did for the first 6 hours or so. Is there any way to get syncing to start from the last block in the execution client?

### System information

Erigon version: `./erigon --version`

latest

OS & Version: Windows/Linux/OSX

fedora37

Commit hash: 

Erigon Command (with flags/config):

Consensus Layer: internalcl

Consensus Layer Command (with flags/config):

Chain/Network: eth mainnet

#### Expected behaviour

Sync process begins

#### Actual behaviour

I have tried this with caplin and teku and receive the same error. Erigon will not progress and begin processing blocks. 

Jan 07 01:28:50  run-erigon.sh[9489]: [WARN] [01-07|01:28:50.447] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"

#### Steps to reproduce the behaviour

I had to wipe out and resync my consensus layer. I am using the internalcl now and my execution layer is behind the head of the chain. I synced the beacon chain on the internalcl and teku and receive this error on both. 

#### Backtrace

Jan 06 22:55:22 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:22.302] Started Ethereum 2.0 Gossip Service      app=caplin
Jan 06 22:55:40 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:40.157] [Caplin] starting clstages loop          app=caplin
Jan 06 22:55:40 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:40.157] Starting downloading History             app=caplin stage=DownloadHistoricalBlocks from=8146304
Jan 06 22:55:54 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:54.605] Backfilling finished
Jan 06 22:55:55 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:55.161] Ready to insert history, waiting for sync cycle to finish app=caplin stage=DownloadHistoricalBlocks
Jan 06 22:55:55 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:55.167] [Caplin] Downloading epochs from reqresp app=caplin stage=CatchUpEpochs from=254572 to=254576
Jan 06 22:55:57 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:55:57.437] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254572
Jan 06 22:56:21 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:56:21.865] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254573
Jan 06 22:56:22 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:56:22.303] P2P                                      app=caplin peers=7
Jan 06 22:56:43 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:56:43.447] [p2p] GoodPeers                          eth67=3 eth66=1 eth68=14
Jan 06 22:57:20 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:57:20.293] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254574
Jan 06 22:57:22 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:57:22.303] P2P                                      app=caplin peers=6
Jan 06 22:57:38 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:57:38.894] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254575
Jan 06 22:57:52 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:57:52.134] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254576
Jan 06 22:58:06 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:58:06.372] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=254577
Jan 06 22:58:19 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:19.198] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"
Jan 06 22:58:19 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:19.198] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"
Jan 06 22:58:22 ip-10-0-1-122 run-erigon.sh[9489]: [INFO] [01-06|22:58:22.302] P2P                                      app=caplin peers=13
Jan 06 22:58:26 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:26.578] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"
Jan 06 22:58:26 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:26.578] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"
Jan 06 22:58:27 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:27.387] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"
Jan 06 22:58:27 ip-10-0-1-122 run-erigon.sh[9489]: [WARN] [01-06|22:58:27.388] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: unexpected chain cap: 18932454"

[backtrace]
````

**Comment by ZephyrShannon** [comment]
I have the same problem. Anyone can help me out here?

**Comment by Giulio2002** [comment]
this is not caplin related.
