### ISSUE TITLE
can not make erigon version v2.56.2

### ISSUE THREAD

**Issue by hitdavid** [ledgerwatch/erigon#9227]
git switch -c v2.56.2
make erigon

failed with error:

Building erigon
go: downloading github.com/ledgerwatch/erigon-snapshot v1.3.1-0.20240101230756-23fbc6c56a1d
../../erigon-lib/chain/snapcfg/util.go:10:2: github.com/ledgerwatch/erigon-snapshot@v1.3.1-0.20240101230756-23fbc6c56a1d: invalid version: unknown revision 23fbc6c56a1d
../../erigon-lib/chain/snapcfg/util.go:11:2: github.com/ledgerwatch/erigon-snapshot@v1.3.1-0.20240101230756-23fbc6c56a1d: invalid version: unknown revision 23fbc6c56a1d
make: *** [Makefile:109: erigon.cmd] Error 1

**Comment by muyinliu** [comment]
see also #5228, try to use command `export GOPROXY="https://proxy.golang.org,direct"` and build again.
