### ISSUE TITLE
Downloader is in panic mode when it's run as separate process 

### ISSUE THREAD

**Issue by ivan-genev** [ledgerwatch/erigon#9271]
#### System information

Erigon version: thorax/erigon:v2.56.2

OS & Version: Linux

Erigon Command (with flags/config):
`--txpool.disable=true --metrics --metrics.addr=0.0.0.0 --metrics.port=6060`
```
    datadir : "/data/erigon"
    chain : "mainnet"
    http : false
    private.api.addr : "0.0.0.0:9090"
    sentry.api.addr : "localhost:9091"
    pprof.addr : "0.0.0.0"
    pprof.port : "6061"
    authrpc.jwtsecret : "/data/erigon/jwt.hex"
```
downloader is started with 
`--downloader.api.addr=0.0.0.0:9093 --torrent.download.rate=80mb --datadir=/data/erigon`

Chain/Network: mainnet

#### Expected behaviour
to run downloader as separate process 

#### Actual behaviour
erigon log 
`[EROR] [01-19|12:53:10.433] [1/12 Snapshots] call downloader         err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:9093: connect: connection refused\""`
downloader log
`[EROR] [01-19|12:53:14.240] mdbx_env_open: resource temporarily unavailable, label: chaindata, trace: [kv_mdbx.go:295 main.go:515 main.go:164 main.go:150 command.go:944 command.go:1068 command.go:992 command.go:985 main.go:52 proc.go:250 asm_amd64.s:1598]`

**Comment by AskAlexSharov** [comment]
Add —no-downloader

**Comment by ivan-genev** [comment]
It didnt help 
even erigon now is not saying that downloader is started and there are no errors the downloader still gives the same error.
`[EROR] [01-21|15:34:44.279] mdbx_env_open: resource temporarily unavailable, label: chaindata, trace: [kv_mdbx.go:295 main.go:515 main.go:164 main.go:150 command.go:944 command.go:1068 command.go:992 command.go:985 main.go:52 proc.go:250 asm_amd64.s:1598]`

**Comment by ivan-genev** [comment]
> no-downloader

Sorry for the late response, it seems that this function wont work. Erigon process will always start the downloader.
ps : Sorry I missed that.

**Comment by AskAlexSharov** [comment]
1. see in our docker-compose.yml: 
```
pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
```
probably you forgot it. 
2. or you missed flag --no-downloader (if no - show us cli flags). 

closing for now - because old issue. feel free to open. thank you.
