### ISSUE TITLE
Timing out on receiving blocks should still move progress forward.

### ISSUE THREAD

**Issue by mandrigin** [ledgerwatch/erigon#929]
For example, in our staged sync, we downloaded headers from 0 to 1000,
When downloading bodies, we downloaded only from 0 to 100 and then there is a timeout.

In that case, we should go through the other stages of staged sync and only then go to the beginning.

Otherwise, I got into issue when I was consistently 3-4 hours behind HEAD mostly because I couldn't download all the block bodies, got timeouts. But each time I did download a couple of blocks.

**Comment by AskAlexSharov** [comment]
fixed by download.v2 release
