### ISSUE TITLE
polygon-erigon  No block headers to write

### ISSUE THREAD

**Issue by zyx0355** [ledgerwatch/erigon#9297]
#### System information

Erigon version: `./erigon --version`
thorax/erigon:stable
OS & Version: Windows/Linux/OSX
centos

Erigon Command (with flags/config):
docker run -d -p 30303:30303 -p 8545:8545 -v /data/erigon-polygon:/opt/erigon/polygon -it thorax/erigon:stable --chain=bor-mainnet --prune=hrtc --bor.heimdall=https://192.168.11.185:1317 --http.api=eth,erigon,web3,net,debug,trace,txpool --maxpeers=250 --snapshots=false --datadir=/opt/erigon/polygon --private.api.addr=localhost:9090 --metrics --metrics.addr=0.0.0.0 --db.size.limit=10TB --db.pagesize=16kb --torrent.upload.rate=312mb --torrent.download.rate=312mb --clique.datadir=/opt/erigon/polygon/clique --port=30303 --metrics.port=6060 --ethash.dagdir=/opt/erigon/ethash/dag --log.console.verbosity=info

Chain/Network: 
bor-miannet polygon

problem：
INFO[01-24|03:10:42.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:10:42.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:11:02.552] [p2p] GoodPeers
INFO[01-24|03:11:02.578] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=22.6MB sys=65.3MB
INFO[01-24|03:11:02.591] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:11:02.591] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:11:22.591] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:11:22.591] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:11:42.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:11:42.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:12:02.579] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=16.7MB sys=65.3MB
INFO[01-24|03:12:02.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:12:02.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:12:22.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:12:22.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:12:42.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:12:42.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:13:02.553] [p2p] GoodPeers
INFO[01-24|03:13:02.579] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=22.5MB sys=65.3MB
INFO[01-24|03:13:02.591] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:13:02.591] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:13:22.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:13:22.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:13:42.591] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:13:42.591] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:14:02.579] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=16.6MB sys=65.3MB
INFO[01-24|03:14:02.591] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:14:02.591] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0
INFO[01-24|03:14:22.592] [2/15 Headers] No block headers to write in this log period block number=0
INFO[01-24|03:14:22.592] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0 dups=0

**Comment by mh0lt** [comment]
Looking at the log for this it looks like you have no peers: `INFO[01-24|03:13:02.553] [p2p] GoodPeers`

You should see something like `INFO] [01-31|20:48:46.140] [p2p] GoodPeers                          eth68=49 eth67=34 eth66=17`

This is not an erigon issue in itself its cause by either underlying network issues, bad configuration of erigon params or firewall settings or missing or incorrect bootnodes for initial connectivity.
