### ISSUE TITLE
internal failure: Cancun is active but ExcessBlobGas is nil

### ISSUE THREAD

**Issue by david0395** [ledgerwatch/erigon#9338]
#### System information

Erigon version: `erigon version 2.57.1 `

OS & Version: Ubuntu 20.04 LTS

Erigon Command (with flags/config):

Consensus Layer: beacon-chain version Prysm/v4.2.0/3a2b486bde28f9b2a02c716782a738c64d62a8e8. Built at: 2024-01-11 01:35:41+00:00

Chain/Network: goerli

#### Actual behaviour
After Upgrade we got a lot of log WARN entries like :

"[WARN] [01-29|14:13:48.130] [rpc] served                             conn=127.0.0.1:40960 method=eth_call reqid=3 t=152.024µs err="internal failure: Cancun is active but ExcessBlobGas is nil""

With downgrade to 2.55.1 the WARNING disappear.

#### Steps to reproduce the behaviour
Upgrade erigon_2.55.1 to 2.57.1

**Comment by quickchase** [comment]
This also happens with `debug_traceCallMany`

**Comment by davidberiro** [comment]
I fixed this here https://github.com/ledgerwatch/erigon/pull/9705/files

**Comment by drinksbydrew** [comment]
I'm still getting this on the latest devel

```[WARN] [03-14|03:33:40.488] [rpc] served                             conn=127.0.0.1:58894 method=eth_call reqid=3 t=132.448µs err="internal failure: Cancun is active but ExcessBlobGas is nil"```

**Comment by realchoubey** [comment]
I'm getting same error after upgrading to 2.58.2. What should we do? 
```[WARN] [03-15|05:48:42.095] [rpc] served                             conn=16.16.155.161:47474 method=eth_call reqid=586 t=149.51µs err="internal failure: Cancun is active but ExcessBlobGas is nil"
[WARN] [03-15|05:48:44.191] [rpc] served                             conn=16.16.155.161:47474 method=eth_call reqid=588 t=154.489µs err="internal failure: Cancun is active but ExcessBlobGas is nil"```

**Comment by drinksbydrew** [comment]
> I'm getting same error after upgrading to 2.58.2. What should we do?
> 
> ```
> [WARN] [03-15|05:48:44.191] [rpc] served                             conn=16.16.155.161:47474 method=eth_call reqid=588 t=154.489µs err="internal failure: Cancun is active but ExcessBlobGas is nil"```
> ```

Have you upgraded rpcdaemon and your consensus client (e.g. prysm)?
