### ISSUE TITLE
[POLYGON] eth_getBlockTransactionCountByNumber returns one tx count less than actual, likely StateSync TX is not being counted

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#9355]
#### System information

Erigon version: 2.57.3

OS & Version: Linux

Chain/Network: Polygon

#### Expected behaviour
Requesting eth_getBlockTransactionCountByNumber should match the number of tx when calling eth_getBlockByNumber

```
    {
      "jsonrpc": "2.0",
      "method": "eth_getBlockTransactionCountByNumber",
      "params": ["0x3284480"],
      "id": 1
    }
```

Should return 109, eth_getBlockTransactionCountByNumber returns 109, Geth returns 109

#### Actual behaviour

Returns 108, it apparently is not counting the StateSync TX which is present in this block

Almost certainly is related to this code: https://github.com/ledgerwatch/erigon/blob/8669a82f752bc2d06d2466c2ccf55c772cb2ca04/turbo/jsonrpc/eth_block.go#L351C1-L360C3

#### Steps to reproduce the behaviour

Request:

```
    {
      "jsonrpc": "2.0",
      "method": "eth_getBlockTransactionCountByNumber",
      "params": ["0x3284480"],
      "id": 1
    }
```

**Comment by taratorio** [comment]
this is fixed in this PR - https://github.com/ledgerwatch/erigon/pull/9275
should be included in next Erigon release.
feel free to reopen if you see any issues
