### ISSUE TITLE
trace_block crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ella-quicknode** [ledgerwatch/erigon#9507]
#### System information

Erigon version: `erigon/2.58.0/linux-amd64/go1.21.7`
OS & Version: `Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-1051-oracle x86_64)` 
Consensus Layer: `lighthouse`

Chain/Network: Ethereum Holesky 

#### Expected behaviour

Calling `trace_block` for blocks smaller than `889,000` gets `method handler crashed` error.  
If calling blocks smaller than `500,000`, we get `could not find block 5000000` even tho [block 500000](https://holesky.etherscan.io/block/500000) exists.  

example payload : `{"method":"trace_block","params":["0xD90A8"],"id":1,"jsonrpc":"2.0"}` 

#### Actual behaviour

Response we get: 

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```

#### Steps to reproduce the behaviour

Try parse the block number `889000` (get crashed), or `889001` (working), `500000`. 

```
curl -X POST http://localhost:8545 -H 'Content-Type: application/json' -d '{"method":"trace_block","params":["0xD90A8"],"id":1,"jsonrpc":"2.0"}'
```

#### Backtrace

* error log observed for block 889,000

````
[EROR] [02-24|12:21:15.142] RPC method trace_block crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:219 panic.go:914 panic.go:261 signal_unix.go:861 block.go:1394 trace_adhoc.go:1135 trace_filtering.go:975 trace_filtering.go:190 value.go:596 value.go:380 service.go:224 handler.go:532 handler.go:482 handler.go:421 handler.go:241 handler.go:334 asm_amd64.s:1650]
````

* logs for block less than 500,000

```
[WARN] [02-24|12:24:09.278] [rpc] served                             conn=100.125.35.6:52296 method=trace_block reqid=1 t=87.664µs err="could not find block 500000"
```

**Comment by jleeqn** [comment]
### Test results with blocks 888999, 889000, 889001

[888999](https://holesky.etherscan.io/block/888999)
:x: {"method":"debug_traceBlockByNumber","params":["0xD90A7", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32000,"message":"invalid arguments; block with number 888999 not found"}}  
```
:x: {"method":"trace_block","params":["0xD90A7"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```
:x: {"method":"trace_transaction","params":["0x0d74d3d50eb59b51a7eba37f74015f9b1f1130230108c6254a13bbf02948ba1a"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":null} 
```

[889000](https://holesky.etherscan.io/block/889000)
:white_check_mark: {"method":"debug_traceBlockByNumber","params":["0xD90A8", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":[{"txHash":"0xab301423d9eb3146f…
```
:x: {"method":"trace_block","params":["0xD90A8"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```
:x: {"method":"trace_transaction","params":["0x0d74d3d50eb59b51a7eba37f74015f9b1f1130230108c6254a13bbf02948ba1a"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}} 
```

[889001](https://holesky.etherscan.io/block/889001)
:white_check_mark: {"method":"debug_traceBlockByNumber","params":["0xD90A9", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0x0bd6d443d93a8a8c7bd5b055bd7c4...
```
:white_check_mark: {"method":"trace_block","params":["0xD90A9"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":[{"txHash":"0x5de82ca31f43c4986d34a5b34ac2585f305a...
```
:white_check_mark: {"method":"trace_transaction","params":
["0x0d74d3d50eb59b51a7eba37f74015f9b1f1130230108c6254a13bbf02948ba1a"],"id":1,"jsonrpc":"2.0"}
```
{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0x62f9caa98f3227ba4c5831839cc8...
```

**Comment by taratorio** [comment]
@ella-quicknode @jleeqn this indicates your node is not synced properly. I just did a fresh sync using latest code on "devel" branch and all the rpc requests you've mentioned work ok for me. Can you please try with a fresh sync using v2.58.1 or latest "devel" and let me know how it goes?

The only takeaway from this is that we need to fix the panic you are seeing with a descriptive err message like "block num missing". Here's a PR for this - https://github.com/ledgerwatch/erigon/pull/9552

**Comment by taratorio** [comment]
closing since PR for handling panics has been merged
feel free to re-open if you still have trouble after fresh re-sync with latest code
