### ISSUE TITLE
debug_traceTransaction giving negative balance in result

### ISSUE THREAD

**Issue by rahul-mnz** [ledgerwatch/erigon#9531]
I tried debug_traceTransaction using data mentioned below - 
'{"method":"debug_traceTransaction","params":["0x5c08231a3c34bd1be6ac7df553d451246175f3dad3245ab5e4413cde35ace52e",{"tracer":"prestateTracer","tracerConfig":{"diffMode":true}}],"id":1,"jsonrpc":"2.0"}'

I tried in all my erigon archive nodes, I am getting below result in 'pre' section - 

"pre":{"0x5124fcc2b3f99f571ad67d075643c743f38f1c34":{"balance":"0x12a1dab4b5dcf2597","nonce":40990},"0xa7613d72e7e0c4f9d58a24e40d47449a86c6ac4c":{"balance":"0x26d0f0ae4cc48000"},"0xc51ea5ee7f65699874e1734c36f8cb08e6f8f92c":{"balance":"-0xde0b6b3a7640000"}}}}

But if I am trying some public endpoints from chainlink, those nodes are not even showing this addr.

What could be the config changes am I missing ?

**Comment by taratorio** [comment]
@rahul-mnz thank you very much for reporting this. It is a bug in our prestate tracer. A fix will be included in `v2.60.3`
