### ISSUE TITLE
subdir for temp files

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/erigon#959]
I'm running turbogeth on a 1TB drive, with 197 GiB in tempfiles it got filled to the brim and got stuck.  It would be great if temp / disk usage would be taking into account available space.

Regardless, it would be better if tempfiles would get their own subdir (within the datafolder), so it's easier to mount it on a different disk, considering the large size.

**Comment by AskAlexSharov** [comment]
I’m sure that 1Tb usual files and 1Tb of mmap files are not equal terabyte. Because only OS can read/write them, not App, and i’m sure that OS has integration with BTRFS for this case. But, yes, definitely we need explore that snapshotting works well.

**Comment by AskAlexSharov** [comment]
What i really mean: BTRFS needs not just small files But knowledge “what changed” for incremental Snapshoting, and OS has information which pages are new in Mmap file and when was updated.
