### ISSUE TITLE
v2.58.1 Matic Amoy Network debug_traceBlockByNumber throws "invalid arguments; block with number 255 not found" error

### ISSUE THREAD

**Issue by pc-quiknode** [ledgerwatch/erigon#9614]
#### System information

Erigon version: `2.58.1-f12e451c`

OS & Version: Linux

Commit hash: f12e451c

Erigon Command (with flags/config):

```
    --chain=amoy\
    --bor.heimdall="http://localhost:1317" \
    --snapshots=true \
    --p2p.protocol=66 \
    --bor.milestone=true \
    --txpool.disable
```

Consensus Layer: Heimdall

Consensus Layer Command (with flags/config):
```
   --chain=amoy \
    --rest-server \
    --chain-id=80002
```

Chain/Network: Matic Amoy Testnet

#### Expected behaviour

debug_traceBlockByNumber does not return error

#### Actual behaviour
```
$ curl -X POST --data '{"method":"debug_traceBlockByNumber","params":["0xff", {"tracer": "callTracer"}],"id":"synth_debug","jsonrpc":"2.0"}' -H "Content-Type: application/json" localhost:8545
{"jsonrpc":"2.0","id":"synth_debug","result":null,"error":{"code":-32000,"message":"invalid arguments; block with number 255 not found"}}
```

Downgrading to v2.57.3 fixes the issue

**Comment by AskAlexSharov** [comment]
maybe fixed by https://github.com/ledgerwatch/erigon/pull/9616

**Comment by pc-quiknode** [comment]
The issue still persists with v2.59.3
Now getting
```
invalid arguments; block with hash bb90a345e3002f6bc1adc4e254d7cdc505eb69d088022cd328c090b4c4060c42 not found
```

**Comment by quickchase** [comment]
I think this is fixed by doing a resync on the latest version
