### ISSUE TITLE
[documentation] Performance optimization of node, at compile time?

### ISSUE THREAD

**Issue by JamesCropcho** [ledgerwatch/erigon#9654]
Greetings.

Is there anything that can be done at the time of compiling (e.g. to `make erigon` and vicinity) to improve the performance of Erigon during runtime (even at the expense of decrease in time/space-efficiency of compilation)?

**Comment by AskAlexSharov** [comment]
we have `Data >> Ram` means likely bottleneck is in disk (way data stored on disk, etc...). 
you can add more ram, lower-latency disk, etc... 

profile-guided compilation - supported by golang but likely will not help.

we have C deps - means can tune gcc-things (likely will not help) - like `-O3`:
```
export CGO_CFLAGS="-O2 -g -D__BLST_PORTABLE__ -DMDBX_DISABLE_VALIDATION=1 -DMDBX_ENV_CHECKPID=0 -Wno-unknown-warning-option -Wno-enum-int-mismatch -Wno-strict-prototypes"
export CGO_CXXFLAGS="-O2 -g"
export CGO_FFLAGS="-O2 -g"
export CGO_LDFLAGS="-O2 -g"
export GOAMD64="v3"
export GOFLAGS="-trimpath -tags=nosqlite,noboltdb,netgo -buildvcs=false"
```

**Comment by AskAlexSharov** [comment]
evn variables: 
`WRITE_MAP=true` - may help in some cases (slow FS  or disk)
`MERGE_THRESHOLD=3` - may help in some cases
`SNAPSHOT_MADV_RND=false` - may help for initial sync - but will greatly increase IO
