### ISSUE TITLE
eth_subscribe logs subcription skipping logs

### ISSUE THREAD

**Issue by adytzu2007** [ledgerwatch/erigon#9699]
Hey, we've found an issue with subscriptions for logs in erigon. Basically, if there are more than 128 logs, it's very likely that some of them will be dropped because the channel is too small. We made a hotfix in a private branch and verified that this was indeed the root cause. You can find the commit [here](https://github.com/bwarelabs/erigon/commit/0c935506b20b3f0c9ebfff763b6fb1119898e674).

We were thinking about opening a PR and making this configurable but I'm not sure where the config should reside and whether this is the proper fix so I wanted to gather some feedback before starting to work on a more permanent solution.

**Comment by somnathb1** [comment]
If you could reproduce on Ethereum mainnet, it would be greatly helpful

**Comment by yperbasis** [comment]
Fixed by PR #9810
