### ISSUE TITLE
upgrade to v2.59.0

### ISSUE THREAD

**Issue by temuera** [ledgerwatch/erigon#9774]
Current Node:  **v2.58.2 Archive with Caplin.**

```
rm -rf <datadir>/caplin <datadir>/snapshots <datadir>/downloader
make integration
./build/bin/integration stage_headers --reset --datadir=<datadir>
./build/bin/integration stage_snapshots --reset --datadir=<datadir> 
```

why need remove all snapshots folder? this will re-download 580G of data, which will take a long time.

can just add `--downloader.verify `?

**Comment by Giulio2002** [comment]
caplin snapshot format has changed, if you do not want the downtime, you are free not to run the command but that will make `--caplin.archive` unusable. you should at least do `rm -rf <datadir>/caplin`
