### ISSUE TITLE
Make Caplin Beacon Checkpoint-URI Sync Config Flag CLI-flaggable, not just for debugging as it is currently.

### ISSUE THREAD

**Issue by alexpeterson91** [ledgerwatch/erigon#9780]
# Rationale

Make the Caplin Beacon Checkpoint URI a CLI flaggable parameter that if provided overrides the default configuration

## Why should this feature exist?

This has long been a request of mine but it became somewhat critical recently.  In the last week the Gnosis Chain hardcoded checkpoint sync went offline around the time that v0.58.2 was released, it was replaced just after publication (like hours if that) of the v0.58.2 by in PR #9682 by @Giulio2002, now included in the current latest release v0.59.0, with the official Gnosis Chain checkpoint sync URI but it also has no backups, and it further centralizes the use of Caplin on, Gnosis chain, Chiado, since there are only 1 options for checkpoint.  For the other chains supported theres a list but from what i read in the code it has a list and starts at the top looking for working endpoints or by some logic compare against latest heads vs other checkpoints down the list.
So by having it hardcoded as it is now all chains are either required to (Gnosis+Chiado) use a single endpoint as a Caplin checkpoint, and the other chains with many options,  it appears that from my reading at least the first checkpoint endpoint or 2nd listed for each chain will be used for basically all Caplin node runners again centralizing more to a single source/provider.  Regardless of if my interpretation of my last statement is even correct, I still think that giving node runners the ability to easily via a CLI flag override the current caplin default Checkpoint-Sync-URI from the default config if they so choose via setting this flag setting a custom checkpoint sync URI (more on benefits of that below) https://github.com/ledgerwatch/erigon/blob/28c0c573ccf65b931ac3feaa2eaf029bedb90daa/cmd/caplin/caplinflags/flags.go#L67C2-L70C13

For those of us using the docker image, this particular issue that occured this last week became a problem very fast, and in order to keep my nodes running I had to start running devel tags from docker which were not stable but at least allowed the node to continue syncing/running, repulling devel as new commits rolled in that stabilized it more.

## What are the use-cases?

- Increased decentralization on at least Gnosis Chain and it's testnet Chiado (since they only have one active option in the default config
- Allows for individuals, groups, communities, institutions, and Web3 Infrastructure companies (in my case I work for Dappnode, and we provide our own checkpoints for several major chains defaulted for all our users) so at least some of these groups want to use their own endpoints which may be more reliable or have better performance than the primary checkpoint URIs due to significantly lower usage, very low latency connections for large runners who have a running checkpoint on site
- Also allows the same for those who want a dedicated 3rd party (Infura/Alchemy/(pokt?)) checkpoint for their endpoint.
- Many Node runners, want/require to have full trust in their checkpoints, and would prefer to use one of their own nodes to provide checkpoints for themselves, not a 3rd party.
- Finally this would avoid this last week's issue where Gnosis chain stopped syncing on erigon due to the single hardcoded checkpoint sync for caplin going offline and it not being resolved until very very shortly (hours at most) after the lastest release after it went offline, which is very critical so that if the chain has only one working hardcoded checkpoint sync it isnt rendered useless until a fix is in or users add their own checkpoint which can be gotten from many sources.

### Implementation

Do you have ideas regarding the implementation of this feature?

I believe PRs #9682 and #9458 also by @Giulio2002 has a basic roadmap for activating cfg flags as CLI flags especially since they specifically relate to the enabling flags and editing handling etc. make this a rather simple change

And to clarify i suggest adding this CLI flag as an override for the existing setup, so that if the flag is provided with a valid checkoint URL then it gets used (could be cool to also have it failover to default checkpoint(s) if the URL provided in the flag, i.e. if it is out of date (significantly), not responding or cant otherwise be reached the flag is ignored essentially)

#### Are you willing to implement this feature? 

I would take a stab at it, however as I'm not very used to using the Erigon Codebase directly, nor is Go a language im good at writing, but can read it well.  (though I learned a lot more than i knew before just writing this PR),  so far the codebase has been really more just as reference for configurations while building custom docker packages for Dappnode I would request someone such as @Giulio2002 (we spoke about this on discord, and asked me to tag him in an issue) could do it, so that this can be done right the first time, im sure I'd make enough mistakes with this PR at the moment that the review would take longer than some seasoned contributor just knocking it out.

**Comment by Giulio2002** [comment]
Implemented in: https://github.com/ledgerwatch/erigon/pull/10412
