### ISSUE TITLE
Failed to unregister peer: peer is not registered

### ISSUE THREAD

**Issue by mandrigin** [ledgerwatch/erigon#982]
It looks like we have some leftovers in our peer handling mechanism somewhere.

I regularly get log messages like

```
ERROR[08-27|11:01:49.055] Failed to unregister sync peer           peer=7acf264334c7ec61 err="peer is not registered"
```

They don't seem to be harmful, but I think it is worth investigating.

**Comment by AlexeyAkhunov** [comment]
Should not be reproducible now with the new downloader
