### ISSUE TITLE
debug_traceBlockByNumber  tracing failed: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by jin-1233** [ledgerwatch/erigon#9830]
**System information：**
erigon version 2.58.2-125509e4
**Expected behaviour:**
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "txHash": "0x712d1d36cdc62ee0eddcbd350439dc2b53ed1707638528d381722b61f923ccfc",
      "result": {
        "from": "0x5d3f2ae166d55ab4d6ee8f8cdc25ae13f117ae8e",
        "gas": "0x5208",
        "gasUsed": "0x5208",
        "to": "0xa387008f74e2df173b0e223fc90f959c87cd3178",
        "input": "0x",
        "value": "0x220be968da9aba78",
        "type": "CALL"
      }
    },
   ...
    {
      "txHash": "0xbaf632dab6e995086c4a287799d09b7a8852272e6eca352f4326a49fa864b947",
      "result": {
        "from": "0x19c8015a3fe489ca3b0a9ad2735e7d62f13be8dd",
        "gas": "0x523f",
        "gasUsed": "0x523f",
        "to": "0xd4e96ef8eee8678dbff4d535e033ed1a4f7605b7",
        "input": "0x",
        "value": "0x672674b5c03594",
        "type": "CALL"
      }
    }
  ]
}
```
**Actual behaviour**
Request:
```
curl --data '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params": ["0x129f683", {"tracer": "callTracer", "timeout": "3m"}],"id":1}' -H "Content-Type: application/json" -X POST localhost:8545 |jq .
```
Response:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "txHash": "0x712d1d36cdc62ee0eddcbd350439dc2b53ed1707638528d381722b61f923ccfc",
      "result": {
        "from": "0x5d3f2ae166d55ab4d6ee8f8cdc25ae13f117ae8e",
        "gas": "0x5208",
        "gasUsed": "0x5208",
        "to": "0xa387008f74e2df173b0e223fc90f959c87cd3178",
        "input": "0x",
        "value": "0x220be968da9aba78",
        "type": "CALL"
      }
    },
   ...
   {
      "txHash": "0xbaf632dab6e995086c4a287799d09b7a8852272e6eca352f4326a49fa864b947",
      "result": null,
      "error": {
        "code": -32000,
        "message": "tracing failed: insufficient funds for gas * price + value: address 0x19c8015A3FE489CA3B0a9Ad2735e7d62F13Be8DD have 29764455010466486 want 30050293010466486"
      }
    }
  ]
}
```
**My suspicions**
Is it because gas and gasUsed are equal?

**Comment by 14MR** [comment]
Removing `--rpc.gascap` resolves this issue.

**Comment by yperbasis** [comment]
Please re-open the issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.

**Comment by Termina1** [comment]
@yperbasis hey, this is still can be reproduced on v2.59.3
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "debug_traceCall",
    "params": [
      {
        "from": "0x1B32104C1C23Dfdf52654D0cAf257D34eFFdCd00",
        "to": "0xc88f23fABfD264AeE6DF7a98052fBea4E92b7419",
        "gas": "0x25521E",
        "maxFeePerGas":"0x174876e800",
        "data": "0x0ad245280000000000000000000000000000000000000000000000000000000000000000"
      },
      "0x12B8643",
      {
        "tracer": "prestateTracer"
      }
    ]
  }
```

**Comment by yperbasis** [comment]
> @yperbasis hey, this is still can be reproduced on v2.59.3
> 
> ```
> {
>     "id": 1,
>     "jsonrpc": "2.0",
>     "method": "debug_traceCall",
>     "params": [
>       {
>         "from": "0x1B32104C1C23Dfdf52654D0cAf257D34eFFdCd00",
>         "to": "0xc88f23fABfD264AeE6DF7a98052fBea4E92b7419",
>         "gas": "0x25521E",
>         "maxFeePerGas":"0x174876e800",
>         "data": "0x0ad245280000000000000000000000000000000000000000000000000000000000000000"
>       },
>       "0x12B8643",
>       {
>         "tracer": "prestateTracer"
>       }
>     ]
>   }
> ```

Erigon returns "`tracing failed: insufficient funds for gas * price + value: address 0x1B32104C1C23Dfdf52654D0cAf257D34eFFdCd00 have 5738534981036526 want 244585400000000000`" for this call.
But this is correct because the balance of account `0x1B32104C1C23Dfdf52654D0cAf257D34eFFdCd00` at the beginning of block 19629635 was 0.005738 ETH, which wasn't enough to cover the cost of the requested transaction (gas * maxFeePerGas = 0.2445854 ETH).
