### ISSUE TITLE
eth_sendRawTransaction fails with INTERNAL_ERROR: blobs limit in txpool is full

### ISSUE THREAD

**Issue by akegaviar** [ledgerwatch/erigon#9834]
#### System information

Erigon version: `erigon/2.59.0`

Chain/Network: Ethereum mainnet chain id 1

#### Expected behaviour

Doing an `eth_sendRawTransaction` works.

#### Actual behaviour

Doing an `eth_sendRawTransaction` fails with `INTERNAL_ERROR: blobs limit in txpool is full`

#### Steps to reproduce the behaviour

The easiest is to add an Erigon endpoint (Ethereum Mainnet) to a MetaMask and try sending an amount of ETH to one of accounts.

The transaction will fail.

MetaMask > Settings > Advanced > Download state logs > `INTERNAL_ERROR: blobs limit in txpool is full`

Geth seems to work fine btw, no issue.

**Comment by wangtao19911111** [comment]
hi bro ,how it going?

**Comment by DmytroShalaiev** [comment]
Same issue.

**Comment by KonstantinRyazantsev** [comment]
same issue

**Comment by somnathb1** [comment]
See flags `--txpool.blobslots` and `--txpool.totalblobpoollimit`
