### ISSUE TITLE
My node is synced but doesn't exectute blocks one by one but in batches

### ISSUE THREAD

**Issue by boltpl81** [ledgerwatch/erigon#9874]
Below is my log, and it looks like my client is synced, consensus is synced, but it doesn't execute new blocks one by one. It does it in batches.  What could be wrong?

**(this part is being repeated all the time)**
kwi 06 14:37:37 mgrom-node erigon[11969]: [INFO] [04-06|14:37:37.946] head updated                             hash=0x8dcfc97a7dea0da4a69d1da1f33db804cf23fa20d13ba79f6ada4c5111d366b4 number=19596725
kwi 06 14:38:21 mgrom-node erigon[11969]: [INFO] [04-06|14:38:21.579] P2P                                      app=caplin peers=54
kwi 06 14:39:21 mgrom-node erigon[11969]: [INFO] [04-06|14:39:21.579] P2P                                      app=caplin peers=58
kwi 06 14:39:24 mgrom-node erigon[11969]: [INFO] [04-06|14:39:24.698] [p2p] GoodPeers                          eth68=4 eth67=22
kwi 06 14:39:27 mgrom-node erigon[11969]: [INFO] [04-06|14:39:27.324] [txpool] stat                            pending=1762 baseFee=666 queued=1034 alloc=8.7GB sys=9.6GB
kwi 06 14:39:27 mgrom-node erigon[11969]: [INFO] [04-06|14:39:27.824] [mem] memory stats                       Rss=13.9MB Size=0B Pss=13.9MB SharedClean=4B SharedDirty=0B PrivateClean=4.2MB PrivateDirty=9.7MB Referenced=13.9MB Anonymous=9.7MB Swap=0B alloc=8.7GB sys=9.6GB
kwi 06 14:40:21 mgrom-node erigon[11969]: [INFO] [04-06|14:40:21.580] P2P                                      app=caplin peers=59
kwi 06 14:41:21 mgrom-node erigon[11969]: [INFO] [04-06|14:41:21.579] P2P                                      app=caplin peers=48
kwi 06 14:41:50 mgrom-node erigon[11969]: [INFO] [04-06|14:41:50.668] [Caplin] Progress                        app=caplin stage=CatchUpBlocks progress=8798601 from=8798596 to=8798602
kwi 06 14:42:21 mgrom-node erigon[11969]: [INFO] [04-06|14:42:21.581] P2P                                      app=caplin peers=43
kwi 06 14:42:24 mgrom-node erigon[11969]: [INFO] [04-06|14:42:24.698] [p2p] GoodPeers                          eth68=2 eth67=23
kwi 06 14:42:28 mgrom-node erigon[11969]: [INFO] [04-06|14:42:28.078] [txpool] stat                            pending=3237 baseFee=946 queued=2947 alloc=5.5GB sys=11.0GB
kwi 06 14:42:28 mgrom-node erigon[11969]: [INFO] [04-06|14:42:28.079] [mem] memory stats                       Rss=15.3MB Size=0B Pss=15.3MB SharedClean=4B SharedDirty=0B PrivateClean=4.5MB PrivateDirty=10.8MB Referenced=15.3MB Anonymous=10.8MB Swap=0B alloc=5.5GB sys=11.0GB
kwi 06 14:43:21 mgrom-node erigon[11969]: [INFO] [04-06|14:43:21.580] P2P                                      app=caplin peers=42
kwi 06 14:44:21 mgrom-node erigon[11969]: [INFO] [04-06|14:44:21.580] P2P                                      app=caplin peers=35
kwi 06 14:45:21 mgrom-node erigon[11969]: [INFO] [04-06|14:45:21.580] P2P                                      app=caplin peers=38
kwi 06 14:45:24 mgrom-node erigon[11969]: [INFO] [04-06|14:45:24.697] [p2p] GoodPeers                          eth68=2 eth66=1 eth67=21
kwi 06 14:45:27 mgrom-node erigon[11969]: [INFO] [04-06|14:45:27.339] [txpool] stat                            pending=4687 baseFee=1029 queued=3055 alloc=10.1GB sys=13.0GB
kwi 06 14:45:28 mgrom-node erigon[11969]: [INFO] [04-06|14:45:28.709] [mem] memory stats                       Rss=15.3MB Size=0B Pss=15.3MB SharedClean=4B SharedDirty=0B PrivateClean=2.6MB PrivateDirty=12.7MB Referenced=15.3MB Anonymous=12.7MB Swap=0B alloc=5.3GB sys=13.0GB
kwi 06 14:46:21 mgrom-node erigon[11969]: [INFO] [04-06|14:46:21.580] P2P                                      app=caplin peers=50
kwi 06 14:46:30 mgrom-node erigon[11969]: [INFO] [04-06|14:46:30.496] [3/12 Senders] Started                   from=19596725 to=19596776
kwi 06 14:46:31 mgrom-node erigon[11969]: [INFO] [04-06|14:46:31.348] [4/12 Execution] Blocks execution        from=19596725 to=19596776
kwi 06 14:46:45 mgrom-node erigon[11969]: [INFO] [04-06|14:46:45.041] [4/12 Execution] Completed on            block=19596776
kwi 06 14:46:45 mgrom-node erigon[11969]: [INFO] [04-06|14:46:45.041] [5/12 HashState] Promoting plain state   from=19596725 to=19596776
kwi 06 14:46:45 mgrom-node erigon[11969]: [INFO] [04-06|14:46:45.041] [5/12 HashState] Incremental promotion   from=19596725 to=19596776 codes=true csbucket=AccountChangeSet
kwi 06 14:46:46 mgrom-node erigon[11969]: [INFO] [04-06|14:46:46.144] [5/12 HashState] Incremental promotion   from=19596725 to=19596776 codes=false csbucket=AccountChangeSet
kwi 06 14:46:47 mgrom-node erigon[11969]: [INFO] [04-06|14:46:47.643] [5/12 HashState] Incremental promotion   from=19596725 to=19596776 codes=false csbucket=StorageChangeSet
kwi 06 14:46:51 mgrom-node erigon[11969]: [INFO] [04-06|14:46:51.088] [6/12 IntermediateHashes] Generating intermediate hashes from=19596725 to=19596776
kwi 06 14:47:05 mgrom-node erigon[11969]: [INFO] [04-06|14:47:05.885] [7/12 CallTraces] Pruned call trace intermediate table from=19506725 to=19506775
kwi 06 14:47:16 mgrom-node erigon[11969]: [INFO] [04-06|14:47:16.901] RPC Daemon notified of new headers       from=19596725 to=19596776 amount=51 hash=0x3d5ff46bada0f92085cb866bffa8484d2686287d4e5fb460b0936152b8f763c0 header sending=307.867µs log sending=627ns
kwi 06 14:47:16 mgrom-node erigon[11969]: [INFO] [04-06|14:47:16.902] head updated                             hash=0x3d5ff46bada0f92085cb866bffa8484d2686287d4e5fb460b0936152b8f763c0 number=19596776

**Comment by boltpl81** [comment]
I've turned on verbosity level 4 and got a lot of those

> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="target root is missing"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.880] bad attestation received                 err="bad attestation data"
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.884] clstage finish                           app=caplin stage=CatchUpBlocks in=27.921568116s next=CatchUpBlocks
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.943] [db] open                                lable=inMem sizeLimit=512MB pageSize=4096
> kwi 06 18:20:04 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:04.945] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=8799696 targetSlot=8799698 requestedSlots=2
> kwi 06 18:20:06 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:06.594] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:06 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:06.609] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:06 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:06.660] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:06 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:06.883] txpool.Fetch.handleInboundMessage PooledTransactions reply exceeds p2pTxPacketLimit requested=32 processed=32
> kwi 06 18:20:06 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:06.971] [txpool.fetch] Handling incoming message msg=TRANSACTIONS_66 err="rlp parse transaction: wrapped blob tx: rlp parse: must be a list"
> kwi 06 18:20:07 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:07.132] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:07 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:07.508] txpool.Fetch.handleInboundMessage PooledTransactions reply exceeds p2pTxPacketLimit requested=32 processed=32
> kwi 06 18:20:07 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:07.557] txpool.Fetch.handleInboundMessage PooledTransactions reply exceeds p2pTxPacketLimit requested=32 processed=32
> kwi 06 18:20:07 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:07.578] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.051] [txpool.fetch] Handling incoming message msg=POOLED_TRANSACTIONS_66 err="txn rlp too big"
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.535] Execution ForkValidator.ValidatePayload  extendCanonical=false
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.535] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x715bfd6fe3674c788474c94ef692d604d0a139f69b27099b65c97ef22789e345 unwindPoint=19597836
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.538] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0xcbc1f10113849f7ff49473f46b8539a9a224d64b79fa622e99db881cb53fa789 unwindPoint=19597835
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.540] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0xa651dc8c09146b4fc5bf75dac0cdefcdf440ef9ebbc77d2d07e80bbf6d8fdac0 unwindPoint=19597834
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.541] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0xe2deef5aa7c7f37a2ce75cf468ee2330ca2b7cd9a5c599b6ef47132b36802579 unwindPoint=19597833
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.543] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x664281439933945a1838920a9d0946ed4af1d33425928ade70880fd55fd296fd unwindPoint=19597832
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.545] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x463f3cb1c7b625e9c4c8e2c6ccf88937dba92babb37d5ba62dbd0ea6300ab359 unwindPoint=19597831
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.546] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x4d8232d4d405eeb6cca2c46d59d28b63043aff0803f913d2caa4daabe3c4ab86 unwindPoint=19597830
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.549] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x50b240944705fc984ba6855738147d4b87fbecff00aa714152af19c9bdd418b2 unwindPoint=19597829
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.552] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x6a17211c5ff6f39b44c189ee33f8c63f471ece4fd3e60fcf228e80ec7a0eb971 unwindPoint=19597828
> kwi 06 18:20:08 mgrom-node erigon[12077]: [DBUG] [04-06|18:20:08.554] Execution ForkValidator.ValidatePayload  foundCanonical=true currentHash=0xbd5ee94e789c3745d5824c121e2501778bf15969e7ae659ba6029deaf324b48a unwindPoint=19597827

**Comment by Giulio2002** [comment]
this looks like a very old version of erigon and you are using caplin which used to be unstable. switch to latest and see if it fixes it

**Comment by boltpl81** [comment]
Thanks, I've updated erigon two days ago and nothing has changes. So finally I've decided to try without caplin, and it works now.
