### ISSUE TITLE
eth_getLogs has buggy topics/address index on pruned node - does not return logs when filtered 

### ISSUE THREAD

**Issue by m-e-m-f-i-s-19** [ledgerwatch/erigon#9880]
#### System information
ryzen 16 core
nvme 7 tb
ram 128 gb

Erigon version: `./erigon --version`
`v2.59.0`, `devel`

OS & Version: Windows/Linux/OSX
`Debian GNU/Linux 10`

Commit hash: 
0f0a445216b7d33bd189a2de328ff1b16eb21b89

Erigon Command (with flags/config):
```
./execution/erigon/build/bin/erigon \
    --chain=gnosis \
    --datadir=/home/gno/gnosis/datadir \
    --authrpc.jwtsecret=./jwtsecret/jwt.hex \
    --http=false \
    --prune=htcr
```

Consensus Layer:
`lighthouse`

Consensus Layer Command (with flags/config):
```
/consensus/lighthouse \
    --network gnosis beacon_node \
    --datadir=data \
    --http \
    --execution-endpoint http://localhost:8551 \
    --execution-jwt ./jwtsecret/jwt.hex \
    --checkpoint-sync-url "https://checkpoint.gnosischain.com"
```

Chain/Network: 
`gnosis`

#### Expected behaviour
`GetLogs` returns logs when topics and/or address provided 

#### Actual behaviour

`GetLogs` doesn't return logs when topics or address provided.
Neither `erigon_getLogs`, `eth_getLogs` doesn't work.

#### Steps to reproduce the behaviour
create `ethereum.FilterQuery`, set `FromBlock`, `ToBlock`, `Topics` - no logs in response
(however if topic removed expected logs are in place among all others)

**Comment by m-e-m-f-i-s-19** [comment]
Seems like after applying intersection `out.And(topicsBitmap)` the `blockNumbers` become empty.

**Comment by m-e-m-f-i-s-19** [comment]
After some debugging, appeared that `getTopicsBitmap` returns wrong data, so intersection doesn't work. `getTopicsBitmap` doesn't return any block from requested range `FromBlock` - `ToBlock range`.

**Comment by somnathb1** [comment]
Please share a query example

**Comment by m-e-m-f-i-s-19** [comment]
Works fine (contains log with the topic or address):
```
query := ethereum.FilterQuery{
		FromBlock: new(big.Int).SetUint64(33307220),
		ToBlock:     new(big.Int).SetUint64(33307230),
	}
```
Not working:
```
query := ethereum.FilterQuery{
		Addresses: []common.Address{common.HexToAddress("0xc35DADB65012eC5796536bD9864eD8773aBc74C4")},
		FromBlock: new(big.Int).SetUint64(33307220),
		ToBlock:     new(big.Int).SetUint64(33307230),
	}
```
Not working:
```
query := ethereum.FilterQuery{
		FromBlock: new(big.Int).SetUint64(33307220),
		ToBlock:     new(big.Int).SetUint64(33307230),
		Topics:    [][]common.Hash{{common.HexToHash("0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9")}},
	}
```

**Comment by somnathb1** [comment]
Confirming that the issue isn't present in 2.57.3, but does happen on `devel` as of today

**Comment by somnathb1** [comment]
Does not happen on archive node, but on pruned node in latest `devel`

**Comment by m-e-m-f-i-s-19** [comment]
`2.57.3` is pre-dencun, so I assume we can't switch back after latest `devel`. will it be fixed any time soon or should we switch to archive node?
