### ISSUE TITLE
Amoy testnet bootnodes

### ISSUE THREAD

**Issue by 1scrooge** [ledgerwatch/erigon#9966]
Hi.
Could somebody share are bootnodes for the Amoy testnet?

**Comment by Giulio2002** [comment]
"enode://bce861be777e91b0a5a49d58a51e14f32f201b4c6c2d1fbea6c7a1f14756cbb3f931f3188d6b65de8b07b53ff28d03b6e366d09e56360d2124a9fc5a15a0913d@54.217.171.196:30303",
	"enode://4a3dc0081a346d26a73d79dd88216a9402d2292318e2db9947dbc97ea9c4afb2498dc519c0af04420dc13a238c279062da0320181e7c1461216ce4513bfd40bf@13.251.184.185:30303",
